### DISCUSSION TITLE
Service discovery on Docker Swarm

### DISCUSSION THREAD

**Discussion by mattdy** [gethomepage/homepage#1045] [Support]
Hi - I'm new to Homepage, trying to get automatic service discovery running on my Docker Swarm using the instructions here: https://gethomepage.dev/en/configs/docker/

_docker-compose.yml_
```
version: "3.7"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true

        - traefik.http.routers.homepage-secure.rule=Host(`<REDACTED>`)
        - traefik.http.routers.homepage-secure.entrypoints=websecure
        - traefik.http.routers.homepage-secure.tls=true
        - traefik.http.routers.homepage-secure.tls.certresolver=letsencrypt

        - traefik.http.routers.homepage.rule=Host(`<REDACTED>`)
        - traefik.http.routers.homepage.entrypoints=web
        - traefik.http.routers.homepage.middlewares=homepage-force-secure
        - traefik.http.middlewares.homepage-force-secure.redirectscheme.scheme=https
        - traefik.http.middlewares.homepage-force-secure.redirectscheme.permanent=true

        - traefik.http.services.homepage.loadbalancer.server.port=3000

        - traefik.docker.network=traefik

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
        - SWARM=1
        - POST=0 # Disallow any POST operations (effectively read-only)
    networks:
      - traefik
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
        - 2375:2375
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

networks:
  traefik:
    external: true

volumes:
  homepage:
    driver: glusterfs
    name: "docker/homepage"
```

_docker.yaml_
```
production:
  host: dockerproxy
  port: 2375
  swarm: true
```

When I access Homepage, I can see the request to `GET /containers/json?all=true` on dockerproxy, however this seems to only return results from the machine that is running docker-socket-proxy (which doesn't have any of the services I've labelled for inclusion on Homepage). What am I missing to make Homepage query against all containers running in the Swarm?

Thanks!
