### DISCUSSION TITLE
Wrong value widgets and services

### DISCUSSION THREAD

**Discussion by FreezingKas** [gethomepage/homepage#1082] [Support]
Hello,

When I start Homepage in docker, widgets metrics and services metrics (like deluge or plex) doesn't have value :
![image](https://user-images.githubusercontent.com/57356272/222964046-8d6297e3-1bd0-4c0c-b948-c1c54c2fe18d.png)

Sometimes when I recreate the container, values shows up but layouts are broken.
Have i done something wrong ?
Nothing in debug logs.

Here's my config file : 

services.yaml
```yml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Websites:
    - FreezingKas Website:
        href: https://domain/
        description: Personal Website
        server: my-docker
        container: freezingkas
        icon: https://cdn.changelog.com/uploads/icons/topics/1ww/icon_large.svg?v=63735622919
    - FreezingKas Plex:
        href: https://plex.domain
        description: Streaming Website Plex
        icon: plex
        widget:
          type: plex
          url: http://plex.domain:32400
          key: <edited>

- Utilities:
    - Bitwarden:
        href: http://bitwarden.domain
        description: Password Vault
        server: my-docker
        container: bitwarden
        icon: bitwarden
    - Deluge:
        href: https://deluge.domain
        description: Torrent FreezingKas
        icon: deluge
        widget:
          type: deluge
          url: http://deluge.domain
          password: deluge # webui password

    - Joal:
        href: https://seedvault.domain
        description: Seeder Joal Seedvault
        icon: https://images.pling.com/cache/85x85-2/img/00/00/50/02/87/1277562/7946ccc9bf429eeacc0df663f1d2e99757d0.png
    - Registry Docker:
        href: https://registry.domain
        description: Images Private Registry
        icon: docker
        server: my-docker
        container: registry

- GCC:
    - CTFd:
        href: http://ctfd.domain
        description: CTFd GCC Session
        icon: https://cdn-icons-png.flaticon.com/512/395/395841.png

- Games:
    - Minecraft:
        description: Minecraft Server
        server: my-docker
        container: minecraft-mc-1
        icon: minecraft

- Proxies:
    - Traefik VPS:
        description: Traefik VPS State
        icon: traefik
        href: https://traefik.domain
        widget:
          type: traefik
          url: https://traefik.domain
          username: admin
          password: <edited>

    - Traefik Titan:
        description: Traefik Titan State
        icon: traefik
        href: https://traefik.titan.domain
        widget:
          type: traefik
          url: https://traefik.titan.domain
          username: admin
          password: <edited>
```

widgets.yaml
```yml
---
- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- greeting:
    text_size: xl
    text: FreezingKas
```

settings.yaml
```yml
---
title: Homepage FreezingKas
favicon: /images/pngegg.ico
layout:
  Websites:
    icon: html
  Utilities:
    icon: terminal
  GCC:
    icon: https://cdn.discordapp.com/icons/827467869649764362/f7633e4843c1317e7e051177ecfbc27e.webp?size=96
  Games:
    icon: https://i.ibb.co/cTfcKK3/pngwing-com.png
  Proxies:
    icon: https://i.ibb.co/WnJ3W9t/pngwing-com-1.png
    style: row
    columns: 2
```
