### DISCUSSION TITLE
Proxmox widget returns error 500

### DISCUSSION THREAD

**Discussion by schumi2004** [gethomepage/homepage#1095] [Support]
### Description

Followed the insctructions to add Proxmox widget and created api-user as instructed.
https://gethomepage.dev/en/services/proxmox/

When opening homepage i'm getting an API error with error code 500.

### Steps to reproduce

Follow insctructions from https://gethomepage.dev/en/services/proxmox/

### homepage version

v0.6.10 (af2566c, 28 feb 2023)

### Installation method

Docker

### Configuration

```yaml
- Proxmox:
        icon: proxmox.png
        href: http://10.0.0.150:8006
        description: Server Hypervisor
        widget:
          type: proxmox
          url: https://10.0.0.150:8006
          username: homepage
          password: my_api_token_secret
          #fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
```

### Container Logs

[2023-03-10T14:25:24.109Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://10.0.0.150:8006/api2/json/cluster/resources
[2023-03-10T14:25:38.016Z] error: <httpProxy> Error calling http://10.0.0.150/api2/json/cluster/resources...
[2023-03-10T14:25:38.017Z] error: <httpProxy> [
  500,
  Error: socket hang up
      at connResetException (node:internal/errors:717:14)
      at Socket.socketOnEnd (node:_http_client:526:23)
      at Socket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
]
[2023-03-10T14:25:38.017Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://10.0.0.150:8006/api2/json/cluster/resources

### Browser Logs

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### Other

I put Proxmox behind reverse proxy but this is all internal communication not via proxy at all.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
