### DISCUSSION TITLE
Services loading very slowly

### DISCUSSION THREAD

**Discussion by JordyEGNL** [gethomepage/homepage#1178] [Support]
### Description

Homepage doesnt show services on first launch, it takes around 60-120 seconds to load. The services are also not using the configuration from settings.yaml
![image](https://user-images.githubusercontent.com/65036298/229731285-c5564f3a-34f7-4492-a657-7f8a8dbf37be.png)

When it happens:
- Most of the time

How I load the site:
- Over Tailscale VPN
- To Traefik container
- To Homepage container

All the services are loading via labels
```yaml
    labels:
      # Homepage config
      homepage.group: Applications
      homepage.name: Jellyfin
      homepage.icon: jellyfin.png
      homepage.href: https://jellyfin.domain.tld/
```

settings.yaml
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: [REDACTED]
  weatherapi: weatherapiapikey

title: Dashboard
background: /images/wallpaper.png
base: https://home.domain.tld
backgroundOpacity: 0.15
color: zinc
target: _self
headerStyle: boxed
quicklaunch:
    searchDescriptions: true

layout: 
  Management:
    style: row
    columns: 5
    icon: mdi-server
  Applications:
    style: row
    columns: 4
    icon: mdi-server
  Monitoring:
    style: column
  Networking:
    style: column
```

services.yml
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services 

- Management:
    - Proxmox:
        href: [REDACTED]
        description: Hypervisor
        icon: proxmox.png
        ping: [REDACTED]
        widget:
          type: proxmox
          url: [REDACTED]
          username: [REDACTED]
          password: [REDACTED]
etc...
```

![image](https://user-images.githubusercontent.com/65036298/229731475-62deadff-dd4f-41cd-ac38-9c5fd3470a62.png)

After 2 minutes I got this as result, but it is not organised as it should be, as seen in the settings.yaml. It sometimes works perfectly fine but most of the time it does this.
![image](https://user-images.githubusercontent.com/65036298/229733019-230dd0dd-ef4a-4778-9645-8ce4f48c3eed.png)

### Steps to reproduce

As described in the description. If you need more tell me :)

### homepage version

v0.6.12 (88089a8)

### Installation method

Docker

### Container Logs

Logs are set to debug but only "listening on port 3000"

### Browser Logs

![image](https://user-images.githubusercontent.com/65036298/229733527-8ffb4f6d-df9b-441b-acd7-ca8f3e3558cb.png)
This could be relevant

### Other

What I have tried:
- Incognito mode
- Chrome, Edge and Firefox
- Cleared cookies
- Restarting container
- Changed PUID and PGID to 1000 (owner of files)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
There is a known issue about needing to hit the circular arrow button (or update a config file) after container recreation but the taking a long time thing seems to be related to your setup.

First, did you check if things load faster directly ie on the local machine? If it’s the same I would then try to see if you can isolate this to any specific widget or container. I’ve never seen it take that long but I suspect it’s related to your setup and not an actual “bug” here…

**Reply by JordyEGNL** [reply]
Hi,

I think it has to do with the docker.yaml file, when I remove that file everything seems to be working as expected.

I don't have any 'server: or container:' in the services.yml

**Reply by shamoon** [reply]
What did you have in the file? If you delete the file entirely it’ll get recreated. Sounds like the docker server is taking a long time to respond

**Reply by JordyEGNL** [reply]
I had remote servers in the file, connected via a docker socket proxy.

Used image: ghcr.io/tecnativa/docker-socket-proxy

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/docker/

my-docker:
    host: dockerproxy
    port: 2375

#server1:
#   socket: /var/run/docker.sock
#
#server2:
#   host: hostname
#   port: 2375
#
#server3:
#   host: hostname
#   port: 2375
#
#server4:
#   host: hostname
#   port: 2375

```

Every connection is going over Tailscale.
It is working fine when only using **my-docker** but when adding a remote docker proxy the loading time gets very slow
