### DISCUSSION TITLE
[Feature Request] GPU Memory/Utilization

### DISCUSSION THREAD

**Discussion by MillsyBot** [gethomepage/homepage#1194] [Feature Requests]
Would like to have a widget that would display the local resource utilization for GPU similar to nvidia-smi command: 
````
# nvidia-smi
Wed Sep  7 18:03:58 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P2000        Off  | 00000000:01:00.0 Off |                  N/A |
| 44%   30C    P8     5W /  75W |      2MiB /  5120MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
````

**Comment by benphelps** [comment]
This would be an awesome addition, but I worry about the extra baggage it'd attach to the image for users not interested or without GPUs.  I'll have to do some investigation to see how large the nvidia-smi package would be, and if it can be added to an Alpine linux image.

**Comment by BuHaneenHHHH** [comment]
this addition would be great. i think you can make a another image with nvidia smi and keep the original without it. that way each user can select which image to use. but in the end it is up to you @benphelps and which option is easier for you to maintain this great docker application.

thank you for your hard work

**Comment by ghost** [comment]
I would like the Intel gpu top aswell

**Comment by github-actions** [comment]
This discussion has been automatically closed due to lack of community interest.

**Comment by Opa-** [comment]
I'm currently doing a small docker image that expose the nvidia-smi info as json : https://github.com/Opa-/nvidia-smi-rest

<img width="411" alt="image" src="https://github.com/gethomepage/homepage/assets/6153672/bcc75dc8-9054-4ee1-bd65-5e21333b959a">

```yaml
version: '3'
services:
  nvidia-smi-rest:
    image: opaopa/nvidia-smi-rest:latest
    container_name: nvidia-smi-rest
    ports:
      - 7777:7777
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
    labels:
      - homepage.group=fsociety
      - homepage.name=Nvidia
      - homepage.weight=7
      - homepage.icon=/icons/nvidia.svg
```

I think this would be a preferable approach rather than having to include nvidia-smi into gethomepage container.

All that's left to do is deciding what the widget would expose and code it (if this discussion get enough upvotes :) )

**Reply by Opa-** [reply]
For anyone interested, I managed to do what I needed with the customapi widget

```yaml
version: '3'
services:
  nvidia-smi-rest:
    image: opaopa/nvidia-smi-rest:latest
    container_name: nvidia-smi-rest
    ports:
      - 7777:7777
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
    labels:
      - homepage.group=foobar
      - homepage.name=Nvidia SMI
      - homepage.weight=7
      - homepage.icon=/icons/nvidia.svg
      - homepage.widget.type=customapi
      - homepage.widget.url=http://ip:7777
      - homepage.widget.refreshInterval=10000
      - homepage.widget.mappings[0].field.nvidia_smi_log.gpu.gpu_power_readings=power_draw
      - homepage.widget.mappings[0].label=Power
      - homepage.widget.mappings[1].field.nvidia_smi_log.gpu.temperature=gpu_temp
      - homepage.widget.mappings[1].label=Temp
      - homepage.widget.mappings[2].field.nvidia_smi_log.gpu.fb_memory_usage=used
      - homepage.widget.mappings[2].label=Mem
      - homepage.widget.mappings[3].field.nvidia_smi_log.gpu=fan_speed
      - homepage.widget.mappings[3].label=Fan Speed
      - homepage.widget.mappings[3].format=percent
```

This is with automatic discovery, but you end up with useless stats on the container itself :

<img width="414" alt="image" src="https://github.com/gethomepage/homepage/assets/6153672/3fdfb264-7f3e-48aa-91bb-c3f8f572f3cb">

With a service widget declared in gethomepage config :

```yaml
- foobar:
  - NVIDIA:
      icon: /icons/nvidia.svg
      weight: 0
      widget:
        type: customapi
        url: http://ip:7777
        refreshInterval: 10000
        mappings:
          - field:
              nvidia_smi_log:
                gpu:
                  gpu_power_readings: power_draw
            label: Power
          - field:
              nvidia_smi_log:
                gpu:
                  temperature: gpu_temp
            label: Temp
          - field:
              nvidia_smi_log:
                gpu:
                  fb_memory_usage: used
            label: Mem
          - field:
              nvidia_smi_log:
                gpu: fan_speed
            label: Fan Speed
            format: percent
```

You end up with a cleaner version :

<img width="408" alt="image" src="https://github.com/gethomepage/homepage/assets/6153672/63e99255-ef9c-427b-a662-0c33f6e131dc">

(I used this icon https://iconduck.com/icons/112195/nvidia)
