### DISCUSSION TITLE
[Feature Request] Allow Bookmarks to use the bookmarked site's favicon as icon

### DISCUSSION THREAD

**Discussion by jmlc11** [gethomepage/homepage#1196] [Feature Requests]
Not sure if this is a simple or complex request, but it would be very cool for the look of the bookmarks part.

**Comment by N1ghtshad0w** [comment]
I was thinking the same.
Why mess with a third party icons when you can get it from the source?
At least when an icon is updated/changed, the change will be reflected immediately from the source.

**Comment by joncrangle** [comment]
Given that Homepage [supports remote icons](https://gethomepage.dev/en/configs/services/#icons), could you not achieve this by specifying the remote favicon location within your `bookmarks.yaml` file?

For instance, the following would display the Github favicon:
```yaml
- Developer:
    - Github:
        - icon: https://github.com/favicon.ico
          href: https://github.com/
```
