### DISCUSSION TITLE
[Feature Request] Custom health checks

### DISCUSSION THREAD

**Discussion by bverkron** [gethomepage/homepage#1212] [Feature Requests]
**Is your feature request related to a service? Please describe.**
I love widgets in general and the status icon you get when using the docker integration. I think it would also be great if there were a way to do custom health checks (and other things) for services that don't have widgets and don't run in a container.

**Is your feature request related to a problem? Please describe.**
Not really.

**Additional context**
I imagine something similar to the health checks feature available for docker compose files but simplified a little
https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck

Example:
```
healthcheck:
  test: ['curl -s -o /dev/null -w "%{http_code}" http://google.com']
  success: "200"
  interval: 30s
  timeout: 10s
  retries: 3
```

Effectively it could allow you to execute arbitrary shell commands and then look for a specific result that indicates success **_or_** it could just look for a true / false response.

This could actually be quite powerful and be leveraged for lots of different things if implemented the right way. Lots of potential here :)

Some other examples:

If my NAS WebUI up?
```
healthcheck:
  test: ['httpcode=$(wget --no-check-certificate --spider -S "https://192.168.1.219/cgi-bin/" 2>&1 | grep "HTTP/" | awk '{print $2}') && if [ "$httpcode" -eq "200" ]; then echo true; else echo false; fi']
  interval: 30s
  timeout: 10s
  retries: 3
```

Is Syncthing on my NAS up? (not running via docker so can't use that integration)
```
healthcheck:
  test: ['response=$(wget -qO- --no-check-certificate --header="X-API-Key: d6sgwkSggXKvMPYMsPzmfSoWgjKUzN3i" "https://192.168.1.219:8384/rest/system/ping" | grep -o "pong") && if [ "$response" = "pong" ]; then echo true; else echo false; fi']
  interval: 30s
  timeout: 10s
  retries: 3
```

Escaping complex strings could be a pain but you could also allow referencing a ~`.sh`~ `.js` file in say a "scripts" folder or something. I fully get that writing a widget is the correct way to do this but for those who don't have development experience but that can be very time consuming and a deal breaker compared to something like this which could involve throwing together a quick line of code for a simple check.

**Edit**: Just noticing that the widgets use javascript so substitute the bash commands with js equivalents 😅. Those this could really open up a can of worms I guess...
