### DISCUSSION TITLE
[Feature Request] integration with netdata

### DISCUSSION THREAD

**Discussion by spupuz** [gethomepage/homepage#1217] [Feature Requests] [answered]
### Description

integration with netdata is it possibile?

**Comment by spupuz** [comment]
would also nice to link resources (cpu, ram and diks) to an external link custom like netdata.
Son when clicking on resources i open netdata detail

**Comment by gromoslaw-kroczka** [comment]
+1

It will be great to have for example number of:
[critical-alerts] & [warnings-alerts]

**Comment by Byrnesdigital** [comment]
Agreed. I currently have it on my homepage just as a service but a more fleshed out widget would be nice

**Comment by pluusla** [comment]
I agree, a service widget for Netdata would be really great. +1

**Comment by lumper5** [comment]
It has to be possible. Heimdall supports netdata Warnings and Critical without additional configuration - just point it to the URL and it shows up.

**Reply by Byrnesdigital** [reply]
I'm sure there's a way we could rig something up with the custom API widget. I'm looking at Heimdall and the NetData app it has to see if there's a way to kinda reverse engineer it so that it works with Homepage/Next.JS, which I'm not horribly familiar with. If that doesn't work might just try making something work from scratch with the custom api.

**Reply by ping-localhost** [reply]
**EDIT**: Created a PR to add a simple Netdata widget to this project: https://github.com/gethomepage/homepage/pull/2672

---

You can access the local Netdata API via `http://127.0.0.1:19999/api/v1/info`. [From what I can see](https://github.com/linuxserver/Heimdall-Apps/blob/master/Netdata/Netdata.php), Heimdall takes that JSON and transforms the `alarms` object, which translates to:

``` yaml
- Netdata:
    icon: netdata.png
    description: Homelab management
    widget:
      type: customapi
      url: http://127.0.0.1:19999/api/v1/info
      mappings:
        - field:
            alarms: warning
          label: Warnings
          format: number
        - field:
            alarms: critical
          label: Criticals
          format: number
```

---

![image](https://github.com/gethomepage/homepage/assets/37925797/e6b8a695-c04c-46f4-8743-f0714e8c5edd)
