### DISCUSSION TITLE
[Feature Request] Add widget to display data from unraid

### DISCUSSION THREAD

**Discussion by ptbsare** [gethomepage/homepage#1218] [Feature Requests]
### Description

Widget for unraid which can display cpu/disk usage retrieved from the unraid web interface.

**Comment by jbeck22** [comment]
+1 for this enhancement from me!

**Comment by aidzer0** [comment]
+1 on this one, if VM/docer/disk space remaining could be added, that would be amazing! Cheers.
Unraid has an API that allows unraid servers plug in to work, not sure what this would involve though.

**Comment by danktankk** [comment]
i would like this also - would be great to have

**Comment by Clannis** [comment]
i would also like this

**Comment by MountainGod2** [comment]
By mounting your drive path to Homepage combined with a Glances container, you can get the majority of the important info (CPU/RAM usage, disk stats, etc.) as an information widget in the header:
```yaml
#widgets.yaml
 - resources:
    cpu: true
    memory: true
    label: System

- resources:
    label: Drives
    disk:
      - /mnt/cache # cache drive
      - /mnt/user0 # array summary
      - /mnt/disk1 # individual disk

- glances:
    url: http://{{HOMEPAGE_VAR_SERVER_IP}}:61208
    expanded: true
    label: Glances
```
![image](https://github.com/benphelps/homepage/assets/88257202/2970c587-c073-436e-b608-292d2ac33242)


And with the newly added charts, you can monitor pretty much every sensor Glances exposes as a service widget in the main area:

![image](https://github.com/benphelps/homepage/assets/88257202/d0565a13-08e6-4d7e-b893-0899ea7703a9)



For some clarity though, unraid doesn't "have an API" per se, and the last info I saw as far as an official one goes was [this comment by a (former) dev](https://www.reddit.com/r/unRAID/comments/us0hww/local_unraid_api_for_things_like_disk_status_or/jmz80qw/?context=6). The closest we have at the moment [is this project](https://forums.unraid.net/topic/141974-support-fork-unraid-api-re/) which itself is a fork of an earlier plugin which works via scraping the webUI every time there's an update and formatting that for a MQTT broker.

While I agree a somewhat more native way to display things like containers / VM's currently running, would be nice, in the meantime if you happen to run Home Assistant on your unraid install anyway, you can do some fun stuff with templates to get similar results if you wanted:

```yaml
- HA Templates:
    - Unraid:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}/
        server: my-docker
        container: homeassistant
        widget:
          type: homeassistant
          url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8123
          key: {{HOMEPAGE_VAR_HOMEASSISTANT_LLAT}}
          custom:
            - template: "{% if is_state('switch.mercury_array','on') -%}
                          Online
                        {%- else -%}
                          Offline
                        {%- endif %}"
              label: Array
            - template: "{{ states.switch | selectattr('object_id', 'match', 'mercury_docker_') | selectattr('state','equalto','on') | map(attribute='entity_id') | list | length }}/{{ states.switch | selectattr('object_id', 'match', 'mercury_docker_') | map(attribute='entity_id') | list | length }}"
              label: Containers
            - template: "{{ states.sensor | selectattr('object_id', 'match', 'mercury_vm_') | selectattr('state','equalto','started') | map(attribute='entity_id') | list | length }}/{{ states.sensor | selectattr('object_id', 'match', 'mercury_vm_') | map(attribute='entity_id') | list | length }}"
              label: VM's
```

![image](https://github.com/benphelps/homepage/assets/88257202/c83d2f61-1551-41ef-907a-9cd1a7ba5313)
