### DISCUSSION TITLE
[Feature Request] Add basic auth for traefik widget

### DISCUSSION THREAD

**Discussion by rubengmez** [gethomepage/homepage#1234] [Feature Requests]
### Description

To access traefik api when basic auth middleware is enabled.

**Comment by frg** [comment]
This can already be done by passing in `username` and `password` in the Traefik widget configuration.

```yaml
widget:
  type: traefik
  url: <Traefik url>
  username: <Basic auth username>
  password: <Basic auth password>
```

Also see: https://github.com/benphelps/homepage/issues/376
