### DISCUSSION TITLE
[Feature Request] PrusaLink Widget

### DISCUSSION THREAD

**Discussion by Crazycorgi** [gethomepage/homepage#1236] [Feature Requests]
### Description

Prusa's Mini+ has recently received a software update supporting control of the printer and read-only api data. Using this new web ui is very useful, however, a small widget showing the status of the print and the file name (and whatever else because there is a lot of info it exposes) would be very nice to have in homepage.

There are two information API's exposed and both require "X-Api-Key" in the Request Headers for authentication.

**The two endpoints are:**
http://printer-ip/api/job
**Example Response:**
`{"state":"Operational","job": null,"progress": null}`
or when printing:
`{"state":"Printing","job":{"estimatedPrintTime":650,"file":{"name":"1,75-Clip-Closed-Hole_0.15mm_PLA_MINI_8m.gcode","path":"/usb/1_75-C~1.GCO","display":"1,75-Clip-Closed-Hole_0.15mm_PLA_MINI_8m.gcode"}},"progress":{"completion":0.23,"printTime":290,"printTimeLeft":360}}`

http://printer-ip/api/printer
Example Response:
`{"telemetry":{"temp-bed":55.4,"temp-nozzle":172.0,"print-speed":100,"z-height":34.1,"material":"PLA"},"temperature":{"tool0":{"actual":172.0,"target":0.0,"display":0.0,"offset":0},"bed":{"actual":55.4,"target":0.0,"offset":0}},"state":{"text":"Operational","flags":{"operational":true,"paused":false,"printing":false,"cancelling":false,"pausing":false,"sdReady":false,"error":false,"closedOnError":false,"ready":true,"busy":false}}}`
or when printing:
`{"telemetry":{"temp-bed":59.8,"temp-nozzle":215.6,"print-speed":100,"z-height":0.7,"material":"PLA"},"temperature":{"tool0":{"actual":215.6,"target":215.0,"display":215.0,"offset":0},"bed":{"actual":59.8,"target":60.0,"offset":0}},"state":{"text":"Printing","flags":{"operational":false,"paused":false,"printing":true,"cancelling":false,"pausing":false,"sdReady":false,"error":false,"closedOnError":false,"ready":false,"busy":false}}}`

There may be more you find online, but this is the very basic info I have found by just looking at the network tab in inspect element.

**Comment by danyial** [comment]
As long as there is no widget for it yet, you can try this

```
    - Prusa:
        icon: mdi-printer-3d-nozzle
        href: http://<<<PRINTER_IP>>>
        description: Prusa MK3s
        widget:
            type: customapi
            url: http://<<<PRINTER_IP>>>/api/job
            refreshInterval: 5000 # optional - in milliseconds, defaults to 10s
            method: GET # optional, e.g. POST
            headers:
                X-Api-Key: <<<API_KEY>>>
            mappings:
                - field:
                    progress: pos_z_mm
                  format: float
                  suffix: mm
                  label: Layerheight
                - field:
                    progress: completion
                  format: number
                  remap:
                      - value: null
                        to: 0
                  scale: 100
                  suffix: "%"
                  label: Progress
                - field: state
                  format: text
                  label: Status
```
