### DISCUSSION TITLE
[Feature Request] OPNsense Widget

### DISCUSSION THREAD

**Discussion by ashapiro-fn** [gethomepage/homepage#1252] [Feature Requests]
### Description

Can WAN download rates (not totals) also be added as available option fields for the OPNsense widget?

**Comment by Oupsman** [comment]
unfortunately, that's not the kind of datas we can get from API calls. I'm working on something, but it involves local storage on the browser and I have a behaviour that I don't understand : from homepage, multiple calls to the API endpoint return the same datas, but when I try the same thing using a shell script, I get different data everytime.

**Comment by Oupsman** [comment]
I have something that works, and a code that seems rather clean to me, but I'm not sure I'll do a PR because that brings the number of fields to 6 AND that would be the first widget to use localStorage (and that one bothers me very much). 

![DeepinScreenshot_select-area_20221231111847](https://user-images.githubusercontent.com/11260343/210133234-e176eb7c-5f6c-41d5-ae0d-c2d3cb2f69b9.png)


With the right configuration, you can only display the fields you want though :     
```
    - OPNSense: 
        icon: opnsense.png
        href: href
        description: OPNSense Maison
        widget:
          type: opnsense
          url: url
          username: key
          password: secret
          fields: ["cpu", "memory", "wanUploadRate", "wanDownloadRate"]
          
    - OPNSense OVH:
        icon: opnsense.png
        href: href
        description: OPNSense OVH
        widget:
          type: opnsense
          url: url
          username: key
          password: secret
          fields: ["cpu", "memory", "wanUpload", "wanDownload"]   
```

I have the idea to add another configuration item : total or rate, but I still don't have figured out how to access it from the component.jsx file.
