### DISCUSSION TITLE
[Feature Request] Plex Docker Stats Optionally In Tautulli Service

### DISCUSSION THREAD

**Discussion by Facinorous-420** [gethomepage/homepage#1273] [Feature Requests]
### Description

This one is a bit unique and potentially just me who needs this, but I think it would be cool to be able to add my Plex docker health stats to my Tautulli service. 

The reason for this, is the Plex widget contains a lot of redundant information that can be found in Sonarr, Radarr, and Tautulli service widgets: 
![image](https://user-images.githubusercontent.com/63425706/213875124-69742740-5ec8-4ebc-874b-e43d48df5152.png)

Most people who have Plex running would have these other services running too, and I see the only real purpose to have a Plex service is to check the docker health (the Running, CPU, and Mem stats). So the reason for opening this issue, and coming up with this idea is to remove the Plex service leaving more room for other services which do not provide redundant data.

I think it would be neat to have an optional config options for a Tautulli widget to also pull the Plex docker status, so we can combine these two services into one service.

Something like this:
![image](https://user-images.githubusercontent.com/63425706/213875404-3588319f-d6ba-4ae2-b32b-904e876593ea.png)

Please note Im not the best graphics designer and I made this in a few minutes, but you can hopefully get the idea I am going with this from this example. At the top corner there would be two docker container statuses, prefixed with a P or T depending on which container (P for Plex T for Tautulli). When clicked to expand the docker status, it will reveal the status of BOTH Plex and Tautulli.

An example of how we could handle this in the config could be adding two optional keys to the service:
For the adding letters to the above docker stats, we could pull the names from "container" and "container2".
```
    - Tautulli:
        href: https://plex.com/
        icon: plex
        description: Plex Monitoring
        server: docker1
        container: tautulli
        server2: docker1
        container2: plex
        widget:
             type: tautulli
             url: https://tautulli.com/
             key: TautulliAPIKey
```

I am not sure if this would be within the scope of the project, and am looking to start a discussion on if this would be an addition welcome to Homepage, as well as the best way to achieve this if so.
