### DISCUSSION TITLE
[Feature Request] Add Qwant search engine

### DISCUSSION THREAD

**Discussion by petitssuisses** [gethomepage/homepage#1286] [Feature Requests]
### Description

Could you please add Qwant search engine in the list ?
https://www.qwant.com

Requests have the following form : 
https://www.qwant.com/?q=homepage+selfosted&t=web

Thanks !

**Comment by ywaf** [comment]
```
- search:
    provider: custom
    url: https://qwant.com/?q=
    target: _blank
```

in widgets.yaml

read the docs - https://gethomepage.dev/en/widgets/search/
