### DISCUSSION TITLE
[Feature Request] Service account auth for Grafana widget

### DISCUSSION THREAD

**Discussion by davepgreene** [gethomepage/homepage#1299] [Feature Requests]
### Description

The Grafana widget only allows you to authenticate via basic auth (i.e. a username/password). It would be really nice if you could update the widget to also support [service accounts](https://grafana.com/docs/grafana/latest/administration/service-accounts/) that authenticate by sending the service account's token as a `Bearer` token rather than basic auth.

The change should be simple. It would involve updating the grafana widget [proxy handler](https://github.com/benphelps/homepage/blob/main/src/widgets/grafana/widget.js#L5) to use the `credentialedProxyHandler` and add a conditional in [this block](https://github.com/benphelps/homepage/blob/main/src/utils/proxy/handlers/credentialed.js#L27-L52) that checks for the presence of a `key` in the `widget` object and sets the `Authorization` header to `Bearer <key>`. In the event that a `username` and `password` are provided it could fall back to using the base64 encoded `Basic` auth that's provided from the `genericProxyHandler`.

**Comment by llaumgui** [comment]
Good idéal. My Grafana widget does't work since my LDAP migration. Service account is more secure.

**Comment by jackrh** [comment]
I took a stab at this, since it looked simple, and with the detailed instructions provided by @davepgreene above it certainly was.
https://github.com/gethomepage/homepage/compare/main...jackrh:homepage:main

I would submit a PR but the issue is most of the data the widget uses is from /api/admin/stats , which I discovered doesn't support tokens - 



> The Admin HTTP API does not currently work with an API Token. API Tokens are currently only linked to an organization and an organization role. They cannot be given the permission of server admin, only users can be given that permission. So in order to use these API calls you will have to use Basic Auth and the Grafana user must have the Grafana Admin permission. (The default admin user is called admin and has permission to use this API.)
https://grafana.com/docs/grafana/latest/developers/http_api/admin/#admin-api


Until Grafana adds a token with the ability to have server wide permissions, I don't see a way of getting this to work as is.

**Reply by ForsakenRei** [reply]
Recently discovered this, you need admin to get some statistics is pretty sad.

**Comment by markalex2209** [comment]
If you have Prometheus scraping metrics from Grafana, you can replaces whole widget with [Prometheus Metric](https://gethomepage.dev/widgets/services/prometheusmetric/) one and show same exact data without need for any credentials (or with auth you configured on proxy in front of Prometheus if you are into that kind of things)
```
        widget:
            type: prometheusmetric
            url: http://prometheus.host.or.ip
            refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
            metrics:
                - label: Dashboards
                  query: grafana_stat_totals_dashboard
                - label: Data sources
                  query: grafana_stat_totals_datasource
                - label: Total alerts
                  query: grafana_stat_totals_alert_rules
                - label: Alerts triggered
                  query: grafana_alerting_alerts{state="alerting"}
```
Depending on situation, you might also want `grafana_alerting_alerts{state=~"alerting|nodata|error"}` instead of last query.
