### DISCUSSION TITLE
[Feature Request] Codex Widget

### DISCUSSION THREAD

**Discussion by ajslater** [gethomepage/homepage#1301] [Feature Requests]
### Description

[Codex](https://github.com/ajslater/codex) is a webserver comic book reader. Support for codex is often conducted on the [Mylar](https://github.com/mylar3/mylar3) discord.

A widget for Codex would accept an API Key and display the number of Publishers, Series and Issues that Codex is serving.

![codex-widget](https://user-images.githubusercontent.com/263494/222602785-e4edb46b-cc3b-499e-939a-28b300d5e472.png)

### Other

I have a fully working and linted PR for this widget ready to submit at a moment's notice, but protocol seems not to be to submit PRs first.
Docs for usage will be extremely similar to other simple widgets, e.g.:
```
        widget:
          type: codex
          url: https://codex.host.or.ip:port
          key: yourCodexAPIKey
```

I have a PR submitted with Codex's icons to [Dashboard Icons](https://github.com/walkxcode/dashboard-icons/pull/299)
So with any luck that should work out of the box. If not, I'll write docs showing users which url they can get Codex's icon from on their own server.
