### DISCUSSION TITLE
[Feature Request] Crafty Controller Service Widget

### DISCUSSION THREAD

**Discussion by Averexs** [gethomepage/homepage#1312] [Feature Requests]
### Description

Hey everyone! I'm looking to add my current Minecraft management service into homepage but noticed there it no service widget for it. I am currently using Crafty Controller to manage my servers. Looking at their wiki page, they do have an API which can be called. Would it be possible to add the Crafty Controller service widget in the future? Maybe have a x/20 players logged in or check the status of the server. Might include which version/flavor of Minecraft the server is running.

More Info: https://wiki.craftycontrol.com/en/4/docs/API%20V2

**Comment by mgrimace** [comment]
Adding my support for this request, just installed Crafty on Oracle and it'd be a great homepage addition. Recommended for anyone managing a server.

**Comment by mgrimace** [comment]
> ### Description
> Hey everyone! I'm looking to add my current Minecraft management service into homepage but noticed there it no service widget for it. I am currently using Crafty Controller to manage my servers. Looking at their wiki page, they do have an API which can be called. Would it be possible to add the Crafty Controller service widget in the future? Maybe have a x/20 players logged in or check the status of the server. Might include which version/flavor of Minecraft the server is running.
> 
> More Info: https://wiki.craftycontrol.com/en/4/docs/API%20V2
> 
> ### Other
> _No response_

I created a Crafty service widget using the customapi, it has a few limitations, see #2085 for how to setup:
<img width="443" alt="Screen Shot 2023-09-29 at 2 24 47 PM" src="https://github.com/benphelps/homepage/assets/55518507/575ade92-bf13-4ef1-bc1b-3f680d86dc64">

**Reply by Averexs** [reply]
Heck yeah, I appreciate you working on this. I’ll have to check this out.

**Reply by oscarrc** [reply]
I want to add to this as #2085 is locked.

It is stated there that as now server id is an UUID cannot be used and that is not correct. Simply wrap the url with double quotes and it should work:

```yaml
- Crafty:
        icon: https://docs.craftycontrol.com/img/favicon.ico
        href: https://{{HOMEPAGE_VAR_CRAFTY_IP}}:8443 #this will be your crafty IP if you don't use secrets
        widget:
            type: customapi
            url: "https://{{HOMEPAGE_VAR_CRAFTY_IP}}:8443/api/v2/servers/<UUID>/stats" # Note the double quotes
            refreshInterval: 10000 
            method: GET 
            headers: 
                Authorization: "Bearer {{HOMEPAGE_VAR_CRAFTY_TOKEN}}" # Double quotes here too as it may contain dashes
            mappings:
              - field: status 
                label: Status
                format: text 
              - field: 
                   data: online
                label: players
                format: number
              - field: 
                   data: cpu
                label: CPU
                format: percent
              - field: 
                   data: mem_percent
                label: RAM
                format: percent
```
