### DISCUSSION TITLE
[Feature Request] Add Tabs to accomodate for several homepages

### DISCUSSION THREAD

**Discussion by T-h-o-m-a-s** [gethomepage/homepage#1316] [Feature Requests] [answered]
### Description

For a power user with many services and many bookmarks, the homepage gets quite crowded.
It woud be awsome with a tab feature to switch between several homepages. 
Either as a list to the left. Or as "browser tabs" just under the line. Or why not configurable :)

**Comment by jvteleco** [comment]
Yes, this would be great, to create subpages (similar to Homer or Dashy).  I am deploying a second docker container to host the second page, but would prefer just to have a single container with two or more subpages.
The (sub)pages could be "independent" (a different yaml file) or maybe just create a Tag inside the services.yaml to indicate Section/tab/subpage 1, 2, 3, etc. 
Thanks

**Comment by KyleTryon** [comment]
I would potentially like to take a stab at this. The biggest dilemma in my mind is the configuration for it.

It feels as though the tab could be set under `layout`, where by default, everything is on the default "first" tab:

```yaml
layout:
  Media:
    tab: 2
    style: row
    columns: 4
```

I would need to dive deeper into sorting to make sure I understand how that part happens but the next issue will be bookmarks, which I think similarly need a way to specify tags.

Imo, it might be a bit off topic for this particular discussion, but I think maybe they layout schema in general could use an update (would require a major version change).

Here is just a rough example of what I think might be a decent alternative:

```yml
layout:
  boomarks:
    - "Social Media"
    - "Developer Tools"
    - "Other Utilities":
          tab: 2
  services:
    - Media:
         tab: 2
         style: row
         columns: 4
```

Or something a little more data-friendly (inspired by helm configs):

```yml
layout:
  boomarks:
    - name: "Social Media"
    - name: "Developer Tools"
    - name: "Other Utilities"
      tab: 2
  services:
    - name: "Media"
      tab: 2
      style: row
      columns: 4
```

Which unmarshals to this very nice JSON:

```json
{
  "layout": {
    "boomarks": [
      {
        "name": "Social Media"
      },
      {
        "name": "Developer Tools"
      },
      {
        "name": "Other Utilities",
        "tab": 2
      }
    ],
    "services": [
      {
        "name": "Media",
        "tab": 2,
        "style": "row",
        "columns": 4
      }
    ]
  }
}
```
