### DISCUSSION TITLE
[Feature Request] Support for Technitium

### DISCUSSION THREAD

**Discussion by iceman73** [gethomepage/homepage#1319] [Feature Requests] [answered]
### Description

Support for  https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md#dashboard-api-calls

**Comment by stepsysadmin** [comment]
Upvoted, would also like a native widget.

This can currently be done using the custom API widget:

Issue ``http://(technitium-ip):5380/api/user/createToken?user=(username)&pass=(password)&tokenName=(name)`` in a browser and copy the API token

Then specify in the services.yaml:

```
        widget:
          type: customapi
          url: http://(technitium-ip):5380/api/dashboard/stats/get?token=(token)
          refreshInterval: 10000 
          method: GET 
          mappings:
            - field:
                response:
                  stats: totalQueries
              label: Queries
              format: text
            - field:
                response:
                  stats: totalBlocked
              label: Blocked
              format: text
            - field:
                response:
                  stats: totalClients
              label: Clients
              format: text
```
