### DISCUSSION TITLE
Kopia: API Error Information

### DISCUSSION THREAD

**Discussion by Tiritibambix** [gethomepage/homepage#1352] [Support] [answered]
Hello, I run Homepage with docker. I love it !

Today, I tried to configure the widget for Kopia.
I edited my `services.yaml` as follow:

```
    - Kopia:
        icon: kopia.png
        href: http://192.168.1.xxx:xxxxx/
        widget:
          type: kopia
          url: http://192.168.1.xxx:xxxxx/
          username: username
          password: password
```
where `username` and `password` are those I use to login to the Kopia's webui.

I get `API Error Information`.

What could be the reason ?

All I get in the logs is `error: undefined`

Thanks for your help.
