### DISCUSSION TITLE
Navidrome Token md5(password + salt)

### DISCUSSION THREAD

**Discussion by jerome6994** [gethomepage/homepage#1364] [Support] [answered]
Good morning

First of all I would like to congratulate the work done, it's great even for a person like me who is not familiar with all this

I have a blocking point on the Navidrome widget I don't understand the token what I have to put
`token: token #md5(password + salt)`

If I have 

- username = username
- passwd = Password123

 how should I proceed?

Thanks

Jérôme

**Comment by jerome6994** [comment]
Hello,
I can't do it at all!
I don't understand how this works!

If you could help me, thank you in advance.

![image](https://user-images.githubusercontent.com/66921143/232401633-e3449ce5-c83b-40c4-92ed-30663472c3b8.png)

**Reply by shamoon** [reply, marked as answer]
Use e.g. https://www.md5hashgenerator.com and paste in username and salt (nothing in between them)

```yaml
...
      user: admin #password admin
      token: 8d253e163606489984701a66ce03024e # using site above with adminca976fd9
      salt: ca976fd9
...
```
