### DISCUSSION TITLE
[Feature Request] Background opacity/blur customization

### DISCUSSION THREAD

**Discussion by bryan065** [gethomepage/homepage#1378] [Feature Requests] [answered]
### Description

Since having custom CSS is against the principal of a static page, can we get opacity and/or blur filter customization for the background? As is, some backgrounds make the text extremely hard to read. I know opacity is there already but having blur/saturation too would be nice.

Something like this in the settings.yaml file:

```
background:
   image: https://source.unsplash.com/random
   opacity: 60
   blur: 0.6
   saturation: 0.5
```
