### DISCUSSION TITLE
Proxmox Widget doesn't load

### DISCUSSION THREAD

**Discussion by thegabriele97** [gethomepage/homepage#1387] [Support] [answered]
### Description

Hi! I am new and I am trying to integrate HomePage with Proxmox. I followed the steps provided in the official documentation but I only get an error as follows. If I try with CURL to reach that url (adding the correct auth header as indicated in my services.yaml file) I receive a JSON response that I assume it is correct, so why here doesn't work? How can I debug it? Thank you!

![image](https://user-images.githubusercontent.com/35406071/233278254-45a5611e-ba4b-4c1d-be13-f6cf8c4df562.png)

### Steps to reproduce

1. Add widget
2. Wait for error

### homepage version

v0.6.16 (0ae13d8, Apr 8, 2023)

### Installation method

Docker

### Configuration

```yaml
- Proxmox:
        href: https://----------
        ping: https://-------
        icon: proxmox.png
        widget:
            type: proxmox
            url: https://-----------
            username: ------
            password: ---------
```

### Container Logs

error: <credentialedProxyHandler> HTTP Error 401 calling https://------/api2/json/cluster/resources

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
