### DISCUSSION TITLE
[Feature Request] Multiple widget for portainer

### DISCUSSION THREAD

**Discussion by pippo73** [gethomepage/homepage#1428] [Feature Requests] [answered]
### Description

Hello, 
I would like to know if there is a way to have multiple portainer sevices.
Before rising a bug, I would like to know if someone of you managed to implement it.
I've tried, but it gives me only the firs values for both the widget

```
#        - Portainer:
#            href: http://192.168.1.91:9000/
#            description: Homepage
#            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
#            widget:
#                type: portainer
#                url: http://192.168.1.91:9000
#                env: 9
#                key: ptr_{key}=
#
#        - Portainer:
#            href: http://192.168.1.91:9000/
#            description: influxDB
#            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
#            widget:
#                type: portainer
#                url: http://192.168.1.91:9000
#                env: 10
#                key: ptr_{key}=

```
thanks to all

**Comment by crispybegs** [comment]
i have three portainer widgets from three different machines running

<img width="278" alt="Screenshot 2023-04-28 at 09 00 12" src="https://user-images.githubusercontent.com/129169122/235090161-6a82acd3-3e5a-420f-b8da-8110777f08a5.png">

my services.yaml looks like this

    - Portainer (Nipogi 1):
        icon: portainer-alt.png
        href: https://192.168.1.44:9443
        widget:
          type: portainer
          url: https://192.168.1.44:9443
          env: 2
          key: ptr_xxxxxxxxx

    - Portainer (Nipogi 2):
        icon: portainer-alt.png
        href: https://192.168.1.64:9443
        widget:
          type: portainer
          url: https://192.168.1.64:9443
          env: 2
          key: ptr_xxxxxxxxx

    - Portainer (Mac):
        icon: portainer-alt.png
        href: https://192.168.1.48:9443
        widget:
          type: portainer
          url: https://192.168.1.48:9443
          env: 2
          key: ptr_xxxxxxxxx

**Reply by pippo73** [reply]
thank you @crispybegs but if I understood well you file, you have different instances of portainer.
I have only one portainer server that has different Environments connected to different server on which is running a docker istance.
tell me if I'm wrong

**Reply by crispybegs** [reply]
oh i see, sorry yes, these are different instances of portainer on separate machines

**Comment by ArbiterGR** [comment]
AFAIK you can create as many services using the same portainer instance  as you want for your different enviorments, with the same api endpoint. All you need to do, is to specify the enviroment that you want to monitor, ie env: 2 etc. You can get the enviroment id by going to your portainer instance, clicking on the enviroment you want and notice the number in the URL after the /#!/

In my homepage config, all 3 of my portainer services, come from 1 instance:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/3236764/235196429-48906766-b835-490e-b3bd-88ab716bdc67.png">

**Reply by pippo73** [reply]
this is similar to what I would like to obtain, but it seems not working on my system
this is my services.yaml file

```
- Portainer:
        - Portainer:
            href: http://192.168.1.91:9000/
            description: Portainer
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
            widget:
                type: portainer
                url: http://192.168.1.91:9000
                env: 2
                key: ptr_key=


        - Portainer:
            href: http://192.168.1.91:9000/
            description: Homepage
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
            widget:
                type: portainer
                url: http://192.168.1.91:9000
                env: 9
                key: ptr_key=
```

this is what I get

![image](https://user-images.githubusercontent.com/757121/235201383-d6cece58-402d-414c-b4bd-90b9f48042f0.png)

But this is what happens on my portainer
![image](https://user-images.githubusercontent.com/757121/235202163-84f61542-8c2f-4a90-a0b8-207648a6ee57.png)

and when I change the first env value, it replicates to both boxes.
One thing that I've noticed is that if split the 2 portainers in 2 differnet columns, it works as expected, but I would like to keep all them in one column
```

- Portainer:
        - Portainer:
            href: http://192.168.1.91:9000/
            description: Portainer
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
            widget:
                type: portainer
                url: http://192.168.1.91:9000
                env: 10
                key: ptr_key=

- Portainer 2:
        - Portainer:
            href: http://192.168.1.91:9000/
            description: Homepage
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
            widget:
                type: portainer
                url: http://192.168.1.91:9000
                env: 9
                key: ptr_key=
```

![image](https://user-images.githubusercontent.com/757121/235203877-64b29d1f-a9fb-4116-9822-59b9dde73aae.png)

**Comment by ArbiterGR** [comment, marked as answer]
Maybe try to differenciate the name a bit to see if it gives the expected result, like this: 

```
- Portainer:
        - Portainer:
            href: http://192.168.1.91:9000/
            description: Portainer
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
            widget:
                type: portainer
                url: http://192.168.1.91:9000
                env: 2
                key: ptr_key=


        - Portainer2:
            href: http://192.168.1.91:9000/
            description: Homepage
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
            widget:
                type: portainer
                url: http://192.168.1.91:9000
                env: 9
                key: ptr_key=
```

Does that work ?
