### DISCUSSION TITLE
Minecraft Widget using tcp instead of udp?

### DISCUSSION THREAD

**Discussion by kladderadeng** [gethomepage/homepage#1435] [Support]
### Description

I added the Minecraft Widget as per the docs and the Status is always Offline for me.

My Service section looks like this:

- Minecraft:
      description: Local Server
      icon: minecraft
      server: docker
      container: minecraft
      widget:
          type: minecraft
          url: udp://192.168.0.12:19132

In the Homepage logs however, I can see this error:

> homepage       | [2023-04-30T13:14:35.428Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.0.12:19132
> homepage       |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

It looks to me like a TCP connection is attempted instead of UDP and because of that the connection to the Minecraft Server fails?

I also entered the Homepage Container and tested the connection with a nc -zvu 192.168.0.12 19132 successfully.

### Steps to reproduce

1. Run a Minecraft Server on Port 19132
2. Add the Minecraft Widget to your services
3. Check Homepage for the Status (in my case Offline)
4. Check the Homepage Logs

### homepage version

v0.6.16 (0ae13d8)

### Installation method

Docker

### Configuration

```yaml
- Minecraft:
      description: Local Server
      icon: minecraft
      server: docker
      container: minecraft
      widget:
          type: minecraft
          url: udp://192.168.0.12:19132
```

### Container Logs

homepage       | [2023-04-30T13:14:35.428Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.0.12:19132
homepage       |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Working fine for me
```
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    ports:
      - 19132:25565
    environment:
      EULA: "TRUE"
    labels:
      - homepage.group=Auto-Discovered2
      - homepage.name=minecraft
      - homepage.icon=minecraft.png
      - homepage.description=minecraft
      - homepage.widget.type=minecraft
      - homepage.widget.url=udp://localhost:19132
```

<img width="377" alt="Screenshot 2023-04-30 at 7 23 39 AM" src="https://user-images.githubusercontent.com/4887959/235358268-3c84c723-edc4-4a29-8c54-07a91ff64fb8.png">

Perhaps theres something with the IP resolution, but homepage only uses the hostname and port from the url. Perhaps try re-creating things...
