### DISCUSSION TITLE
New FreshRSS widget not working with FreshRSS Docker install

### DISCUSSION THREAD

**Discussion by aries223** [gethomepage/homepage#1453] [Support] [answered]
I have followed the directions in the Homepage FreshRSS widget page, as well as the instructions to enable the api in FreshRSS. The result on Homepage in the FreshRSS widget is 'NaN'.
Is there something wrong with the widget, or something im doing/not doing?

![frss](https://user-images.githubusercontent.com/83663127/235745862-a960e81e-f33e-4552-9cd5-0100d4f20c2b.jpg)

My endpoints Pass:
```
FreshRSS API endpoints
Google Reader compatible API
Your API address:
http://192.168.1.156/api/greader.php
Google Reader API configuration test:
✔️ PASS

Fever compatible API
Your API address:
http://192.168.1.156/api/fever.php
Fever API configuration test:
✔️ PASS
```
My services.yml:
```
    - FreshRSS:
        icon: freshrss
        href: http://192.168.1.156/i/
        description: 192.168.1.156
        widget:
          type: freshrss
          url: http://192.168.1.156/api/greader.php
          username: <username>
          password: <api-pasword>
```
If I use the 'fever.php' api, this results:
```
API Error: Unexpected token 'I', "Internal S"... is not valid JSON
```
My docker-compose.yml:
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /home/me/desktop/config:/app/config # Make sure your local config directory exists
      - /home/me/desktop/images:/app/public/images # location for background images
      - /home/me/desktop/icons:/app/public/icons # location for custom icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```
I have tried the port 3000 in the widget url and get the same NaN result.

Logs:
```homepage    | [2023-05-02T18:09:33.150Z] error: <freshrssProxyHandler> Unable to login to FreshRSS API: TypeError: Cannot read properties of undefined (reading 'split')
homepage    |     at login (/app/.next/server/pages/api/services/proxy.js:1714:89)
homepage    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
homepage    |     at async freshrssProxyHandler (/app/.next/server/pages/api/services/proxy.js:1796:5)
homepage    |     at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:9)
homepage    |     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
homepage    |     at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
homepage    |     at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
homepage    |     at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:365:29)
homepage    |     at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:303:20)
homepage    |     at async Server.<anonymous> (/app/server.js:19:5)
homepage    | [2023-05-02T18:09:33.169Z] error: <freshrssProxyHandler> Error getting data from FreshRSS: http://192.168.1.156/api/greader.php/api/greader.php/reader/api/0/subscription/list?output=json status 400. Data: Bad Request!
homepage    | [2023-05-02T18:09:33.188Z] error: <freshrssProxyHandler> Error getting data from FreshRSS: http://192.168.1.156/api/greader.php/api/greader.php/reader/api/0/unread-count?output=json status 400. Data: Bad Request!
```

**Comment by shamoon** [comment, marked as answer]
Widget url should be just `url: http://192.168.1.156`

**Reply by aries223** [reply]
LOL! ok that was easy... Thanks for the help!

**Comment by pocelka** [comment]
I don't want to open new topic, but I have the same problem except the part about logs from container, as there are no logs.

All I'm getting is:

```
API Error: Unexpected token 'I', "Internal S"... is not valid JSON
```

from homepage.

This is my config:

```yaml
    - Fresh RSS:                                                                                                        
        icon: freshrss.png                                                                                              
        href: http://192.168.1.3:9003                                                                                   
        description: RSS Reader                                                                                         
        widget:                                                                                                         
          type: freshrss                                                                                                
          fields: ["unread"]                                                                                            
          href: http://192.168.1.3:9003                                                                                 
          username: <user>
          password: <api token>
```

There is also nothing in developer tools, except http 500.
