### DISCUSSION TITLE
Proxmox widget fails to load

### DISCUSSION THREAD

**Discussion by Rikeroo** [gethomepage/homepage#1474] [Support]
Can't get the proxmox widget to load any data from the proxmox api, despite following the revised instructions on the wiki. Looks like the proxy is trying to call a page on the wrong subnet? I've tried using http, with no difference.

services.yaml file:
```yaml
    - Proxmox:
        icon: proxmox.png
        href: https://<PROXMOX IP>/
        descrption: Proxmox GUI
        widget:
            type: proxmox
            url: https://192.168.1.81:8006
            username: api@pam!homepage
            password: <API KEY>
```
Error in docker container logs:
```
  }
]
[2023-05-08T12:58:05.261Z] error: <httpProxy> Error calling http://192.168.0.122/admin/admin/api.php...
[2023-05-08T12:58:05.261Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.0.122:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.0.122',

    port: 80
  }
]
```
