### DISCUSSION TITLE
Rootless docker can't get info about containers

### DISCUSSION THREAD

**Discussion by snpefk** [gethomepage/homepage#1480] [Support]
Hi!
Trying to get information about container I configure docker socket in `config/docker.yaml` like this: 
```yaml
my-docker:
    host: dockerproxy
    port: 2375
```
and of course run `dockerproxy` with `homepage` container, but having error on main page

```
error: <dockerStatsService> Error: (HTTP code 503) unexpected - <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

 
    at /app/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:343:17
    at getCause (/app/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:373:7)
    at Modem.buildPayload (/app/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:342:5)
    at IncomingMessage.<anonymous> (/app/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:310:16)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Can't figure out why :( 

Here is my `compose.yaml`: 
```yaml
version: "3.3"
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - /home/pi/containers/homepage/config/:/app/config
    ports:
      - 3000:3000
    restart: unless-stopped
```
