### DISCUSSION TITLE
How to use the pihole widget behind a SSO provider?

### DISCUSSION THREAD

**Discussion by diogosilva30** [gethomepage/homepage#1502] [Support] [answered]
I have deployed pihole with **no password** with a traefik forward auth that redirects the user to `sso.mydomain.com`. My homepage is hosted at `lab.mydomain.com` and pihole under `pihole.mydomain.com`.
According to the documentation I need to specify an API key If my Pi hole instance has authentication, which is not the case.
So I specified the kubernetes ingress as such:
```yaml
annotations:
    #   - Middleware to protect this service with SSO
    traefik.ingress.kubernetes.io/router.middlewares: |
      ${traefik_auth_middleware},
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: DNS and adblocker
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: pi-hole.png
    gethomepage.dev/name: Pi Hole
    gethomepage.dev/widget.type: "pihole"
    gethomepage.dev/widget.url: "https://${hostname}"
```
The integration was working fine without the `widget` integration. Now it fails:
![Screen Shot 2023-05-13 at 12 41 54 PM](https://github.com/benphelps/homepage/assets/49190578/9ef4868d-4f0f-467c-9eee-aa15ee5b41b3)

The error:
```
API Error: Invalid data
URL: https://pihole.dsilva.dev/admin/api.php?summaryRaw&auth=
Response Data:



<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>authentik</title>
<link rel="shortcut icon" type="image/png" href="/static/dist/assets/icons/icon.png">
<link rel="prefetch" href="/static/dist/assets/images/flow_background.jpg" />
<link rel="icon" href="/static/dist/assets/icons/icon.png">
<link rel="shortcut icon" href="/static/dist/assets/icons/icon.png">
<script>
    window.authentik = {
        locale: "en-us",
        config: JSON.parse('{\u0022error_reporting\u0022: {\u0022enabled\u0022: true, \u0022sentry_dsn\u0022: \u0022https://151ba72610234c4c97c5bcff4e1cffd8@o4504163616882688.ingest.sentry.io/4504163677503489\u0022, \u0022environment\u0022: \u0022k8s\u0022, \u0022send_pii\u0022: false, \u0022traces_sample_rate\u0022: 0.1}, \u0022capabilities\u0022: [\u0022can_geo_ip\u0022, \u0022can_impersonate\u0022], \u0022cache_timeout\u0022: 300, \u0022cache_timeout_flows\u0022: 300, \u0022cache_timeout_policies\u0022: 300, \u0022cache_timeout_reputation\u0022: 300}'),
        tenant: JSON.parse('{\u0022matched_domain\u0022: \u0022authentik\u002Ddefault\u0022, \u0022branding_title\u0022: \u0022authentik\u0022, \u0022branding_logo\u0022: \u0022/static/dist/assets/icons/icon_left_brand.svg\u0022, \u0022branding_favicon\u0022: \u0022/static/dist/assets/icons/icon.png\u0022, \u0022ui_footer_links\u0022: [], \u0022ui_theme\u0022: \u0022automatic\u0022, \u0022flow_authentication\u0022: \u0022default\u002Dauthentication\u002Dflow\u0022, \u0022flow_invalidation\u0022: \u0022default\u002Dinvalidation\u002Dflow\u0022, \u0022flow_user_settings\u0022: \u0022default\u002Duser\u002Dsettings\u002Dflow\u0022, \u0022default_locale\u0022: \u0022\u0022}'),
        versionFamily: "2023.4",
        versionSubdomain: "version-2023-4",
        build: "",
    };
    window.addEventListener("DOMContentLoaded", () => {
        
    });
</script>
<script>
window.authentik.flow = {
    "layout": "stacked",
};
</script>
<link rel="stylesheet" type="text/css" href="/static/dist/authentik.css">
<link rel="stylesheet" type="text/css" href="/static/dist/theme-dark.css" media="(prefers-color-scheme: dark)">
<link rel="stylesheet" type="text/css" href="/static/dist/custom.css" data-inject>
<script src="/static/dist/poly.js?version=2023.4.1" type="module"></script>
<script src="/static/dist/standalone/loading/index.js?version=2023.4.1" type="module"></script>
<script src="/static/dist/flow/FlowInterface.js?version=2023.4.1" type="module"></script>
<style>
:root {
    --ak-flow-background: url("/static/dist/assets/images/flow_background.jpg");
}
</style>
<meta name="sentry-trace" content="a94a99f5c2a0450c8ea456303e2b27e9-ba5d23ed4b523fc7-0" />
</head>
<body>
<ak-message-container></ak-message-container>
<ak-flow-executor>
<ak-loading></ak-loading>
</ak-flow-executor>
</body>
</html>
```
From the error logs it's clear that it's reaching the SSO provider page (authentik). 

Any idea if this setup is currently possible?
