### DISCUSSION TITLE
[Feature Request] OpenWrt Service Widgets

### DISCUSSION THREAD

**Discussion by zjjxwhh** [gethomepage/homepage#1509] [Feature Requests] [answered]
### Description

Hello! Thank you so much for your work, I love this project. 
I want to know if it is possible to add an OpenWrt router status service widget, so that I can easily view various statuses of the router on the homepage, including running time, real-time upload speed, real-time download speed, network status, etc.
There is a [corresponding integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/upnp) in home-assistant can do this, so I hope homepage does too.
Thanks again for your work!

**Comment by luweijun1992** [comment]
+1

**Comment by irlam** [comment]
+1

**Comment by zrr1999** [comment]
+1

**Comment by xinmans** [comment]
hope can supportted

**Comment by ghost** [comment]
Here is the configuration I have created for OpenWRT. 
To customize it, you will need to replace the IP address, port, or domain name of OpenWRT. 
Additionally, please copy the cookie from your browser. 
You can then set the mappings to select the desired keywords based on the JSON returned by the URL.

``` yaml
- Openwrt:
      href: https://{openwrt_IP}:{openwrt_Port}/
      icon: https://{openwrt_IP}:{openwrt_Port}/luci-static/argon/logo.png
      description: OpenWrt is a highly extensible GNU/Linux distribution for embedded devices.
      siteMonitor: https://{openwrt_IP}:{openwrt_Port}/cgi-bin/luci/
      widget:
        type: customapi
        url: https://{openwrt_IP}:{openwrt_Port}/cgi-bin/luci/admin/status/overview?status=1
        headers:
          cookie: sysauth=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        mappings:
          - field: cpustat
            label: CPU
          - field: cpuusage
            label: cpuusage    
          - field: uptime
            label: uptime
          - field: conncount
            label: conncount
```
