### DISCUSSION TITLE
Unable to get blur to work?

### DISCUSSION THREAD

**Discussion by yuniq-neko** [gethomepage/homepage#1521] [Support] [answered]
Hi there,
Currently on v0.6.19 and can't seem to make background blur work at all? 😢 
This is my settings.yaml:
```
background:
  image: https://bing.biturl.top/?resolution=3840&format=image&index=random&mkt=ja-JP
  blur: md
layout:
  Media:
    style: row
    columns: 4
headerStyle: boxed
```
and this is a snippet of what my background currently looks like, no blur affect being applied at all :/
<img width="670" alt="image" src="https://github.com/benphelps/homepage/assets/14962951/adb23f23-247f-45e1-bd3e-d99146653627">
Any ideas?
