### DISCUSSION TITLE
[Feature Request] Ability to span sections across columns

### DISCUSSION THREAD

**Discussion by LilTrublMakr** [gethomepage/homepage#154] [Feature Requests]
Would it be possible to set up the ability to span a section across columns? For example, I like to have some apps that don't fit in to any categories going across the top of the main section of the page. 

I am imagining that we would be allowed to span the services across the columns and the bookmarks around rows if that makes sense.

example of my current dashboard:

[Imgur](https://imgur.com/8rNAOfQ)

**Comment by benphelps** [comment]
This is a great idea and should be pretty easy to add.

**Reply by benphelps** [reply]
And has been added, see here: https://github.com/benphelps/homepage/wiki/Settings#layout

**Reply by LilTrublMakr** [reply]
Works beautifully! Thank you for the fast work!

**Reply by LilTrublMakr** [reply]
Does this also work for bookmarks or just services?

**Reply by benphelps** [reply]
Just services for now, I'll get around to enabling it for bookmarks as well.

**Reply by LilTrublMakr** [reply]
Awesome. No rush. Now that my OCD is mostly satisfied, I am swapping over from Flame to Homepage!

**Reply by Tataukee** [reply]
@LilTrublMakr , Would you be able to post an example of your settings.yaml configuration to achieve the rows horizontally ? 
currently my settings.yaml is empty and i looked at the link where @benphelps guided you and i am just lost ..

**Reply by LilTrublMakr** [reply]
services.yaml
```
- // Applications:
  - Mealie:
      icon: /icons/mealie.png
      href: https://recipes.sudo
      container: Mealie
  - Gitea:
      icon: /icons/gitea.png
      href: http://gitea.sudo
  - Vikunja:
      icon: /icons/vikunja.png
      href: http://tasks.sudo
      container: vikunja-api
  - NextCloud:
      icon: /icons/nextcloud.png
      href: https://cloud.sudo
      container: nextcloud
  - Paperless:
      icon: /icons/paperless-ng.png
      href: http://paperless.sudo
  - SnipeIT:
      icon: /icons/snipe-it.png
      href: http://snipeit.sudo
      container: snipe-it-personal
  - NC SnipeIT:
      icon: /icons/snipe-it.png
      href: http://tower.sudo:8082
      container: snipe-it
  - 3CX:
      icon: /icons/3cx.png
      href: http://3cx.sudo
  - NetBox:
      icon: /icons/netbox.png
      href: http://netbox.sudo
      container: netbox
```

settings.yaml
```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Settings

title: Dashboard

theme: dark
color: neutral

layout:
  // Applications:
    style: row
    columns: 4
```

The titles must match. You might also need to click the refresh button in the lower right for it to work.
