### DISCUSSION TITLE
Configuring docker when dockers are in individual LXCs on Proxmox

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#1541] [Support] [answered]
I'm new to Docker and I have started a small Proxmox homelab setup with various media services running using docker compose on separate linux containers (LXCs). For example Plex is on LXC1, the various "Arrs" are on LXC2, etc, each with their own IP address (e.g., 192.168.0.x, 192.168.0.y, .z, etc.). Homepage is on its own, separate LXC (e.g., LXC3) with its own IP. 

How do I best set up each docker on each LXC to send their info to Homepage (to make use of the Docker status widget)? Thanks in advance!

**Comment by mgrimace** [comment, marked as answer]
I'll answer this myself:

I added dockerproxy to each LXC running docker, including homepage using the following docker compose:

```
version: "3.3"
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
        - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
        - 2375:2375
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
```
Then, back in the Homepage config folder, I add each container's detail to docker.yaml and give them a name, for example:

```
docker-arr:
  host: [IP]
  port: 2375

docker-plex:
  host: [IP]
  port: 2375
```

Then in the services.yaml, I add the following lines to each of the services, for example:

```
server: docker-arr # The docker server that was configured
container: sonarr # The name of the container you'd like to connect
```
