### DISCUSSION TITLE
[Feature Request] Add TZ env to set timezone

### DISCUSSION THREAD

**Discussion by mguilherme** [gethomepage/homepage#1549] [Feature Requests]
### Description

Add compatibility to docker to be able to set the timezone with `TZ`

eg:

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Lisbon  
    volumes:
      - config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: unless-stopped

volumes:
  config:
```
