### DISCUSSION TITLE
[Feature Request] Adding an opacity option to the widget andd service tiles

### DISCUSSION THREAD

**Discussion by Esdeath79** [gethomepage/homepage#1557] [Feature Requests]
### Description

Hi there,
I think it would be great if we could change the opacity of the widget/service tiles. With this there would be less need for a change in the background wallpaper.
Something like this (using sonarr as example and similiar to how to change the background):

```
 - Sonarr:
      icon: sonarr.png
      href: http://sonarr.host.or.ip
      widget:
         opacity: 0-100 <-------
          type: sonarr
          fields: ["wanted", "queued"]
          url: http://sonarr.host.or.ip
          key: apikeyapikeyapikeyapikeyapikey
```
