### DISCUSSION TITLE
Tdarr Widget value of "Processed" label

### DISCUSSION THREAD

**Discussion by Nonoss117** [gethomepage/homepage#1563] [General]
I thought that the label "Processed", indicates the number of files that are transcoded with success or not required.
It doesn't seems to be that.
It seems to be : "Health check: Healthy" + "Transcode: Success/Not required"

Can't someone explain me the value of the label "Processed" ?
Thank's

![image](https://github.com/benphelps/homepage/assets/79055577/a1f3b15b-1f0f-4e54-b1dc-7ef450ce7cfb)

![image](https://github.com/benphelps/homepage/assets/79055577/b45c3c93-b672-4d41-9d79-3a7366b28655)

My yaml :

```yaml
    - Tdarr:
        icon: tdarr.png
        href: http://192.168.1.100:8265/
        server: nas-docker
        container: tdarr
        description: Transcodage vidéos
        widget:
          type: tdarr
          fields: ["queue", "processed", "errored", "saved"]
          url: http://192.168.1.100:8265
```
