### DISCUSSION TITLE
Omada Widget API issue

### DISCUSSION THREAD

**Discussion by spezzuti** [gethomepage/homepage#1564] [Support]
### Description

Currently attempting to add Omada widget. API address works as expected in browser, verified login credentials, etc. However, when setting up widget, getting API error:

API Error: Unexpected token 'I', "Internal S"... is not valid JSON

Unsure what is causing this

### Steps to reproduce

1. Add Omada widget info to services
2. save & refresh 
3. API error
![image](https://github.com/benphelps/homepage/assets/71993933/a28f896c-8ca9-4a37-a06a-ae7105e69d28)
![image](https://github.com/benphelps/homepage/assets/71993933/2c68b016-ba41-4001-9920-5b46df621bd1)

### homepage version

v0.6.20 6046f79

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please complete the issue template with all steps including the troubleshooting steps etc

From the template:

> If this is a service widget issue and you do not include any information here your issue will be closed.

**Comment by spezzuti** [comment]
troubleshooting steps (best I was able to attempt)

1. tried url as http://omada.tplinkcloud.com https://omada.tplinkcould.com (also without http or https)
2. tried url as ip:port with http, https and without 
3. checked API URL - this gets response from Omada API {"errorCode":0,"msg":"Success.","result":{"controllerVer":"5.9.31","apiVer":"3","configured":true,"type":1,"supportApp":true,"omadacId":"2064891c44d3bc213e95bfb9769d8473","registeredRoot":true}}
4. verified login credentials are working as expected
5. attempted with and without site:

**Comment by shamoon** [comment]
Thanks. Importantly: did you run those queries from inside the homepage container?

**Comment by shamoon** [comment]
I dont have an Omada device to test with, the logic should be:

`${url}/api/info // I think this is what you posted above`

POST with credentials to `${url}/${cId}/api/v2/login`

that would return a token and finally this is sent to
POST `${url}/${cId}/api/v2/sites?token=${token}&currentPage=1&currentPageSize=1000`
substituting in the token and passing it also in the headers ie `"Csrf-Token": token`

I realize this is not trivial to construct the cURL requests but I am not aware of any issues with the widget and the vast majority of the time issues like this are somewhere in your setup i.e. networking, authentication etc. and not a bug here. The only real way to know is to re-create the logic of the widget and see if / where things go wrong. If you can provide API output (again, from inside the homepage container) for the above and they all look normal then I can try to see if theres a real bug here.

**Comment by spezzuti** [comment]
so, ignore any ignorance of mine, but I'm still  not perfect with docker yet. Generally, doing anything from within the container, I use the console on Portainer, which I can't do with Homepage (as it doesn't allow me use of the console)

I have run the curl commands from the server running the container:
 curl <ip:port>/cID/api/v2/login = curl: (35) error:0A00010B:SSL routines::wrong version number

checking the URL via browser returns: {"errorCode":-1600,"msg":"Unsupported request path."}

So either way I'm not receiving any token. Granted, I may be missing something in between at the moment. You let me know what else I can do and I'm ready. Also, thank you in advance

**Reply by shamoon** [reply]
Try changing the portainer command to bin/sh, you can also do this from the cli with https://docs.docker.com/engine/reference/commandline/exec/ (thats what portainer uses)

The reason this is important is because often the issue is networking, and Im starting to think thats what it is here. The docker container cannot 'reach' your Omada device, obviously there are multiple potential reasons why.

**Comment by spezzuti** [comment]
so running the commands from inside the container (curl {url}/{ciID}/api/v2/login) presents the same response:
curl: (35) error:0A00010B:SSL routines::wrong version number
(with it run as https://ip)

when run as http:// - returns an empty prompt

**Reply by shamoon** [reply]
The first step of the troubleshooting guide is ping, did you do that?: https://gethomepage.dev/en/more/troubleshooting/#service-widget-errors

**Reply by spezzuti** [reply]
yes ping replies with no issues .054ms

**Reply by shamoon** [reply]
I honestly don’t know if omada uses https or not, but the `${url}/api/info` call would be the first one homepage calls so I would start there

**Comment by Healzangels** [comment]
Came across this thread as having a similar issue setting up QNap but do have a working Omada setup. Just took a look and mine is pretty basic 

        widget:
            type: omada
            url: https://x.x.x.x 
            username: Removed
            password: Removed
            site: Default
            
I used https:// + did not include any sort of port number/no web ui port.

**Comment by Newtoniano** [comment]
@spezzuti make sure you put `https` in your widget url and in the href. Had the same issue when I mistakenly typed http instead. The aforementioned snippet works for me.

**Comment by zolfey** [comment]
I just had this error and troubleshooted for 3 hours to find out it is something with my password that was causing the issue as that singular password will cause Omada to return the API error. I have now changed the password so the password was `&#3#&Xj*i8@g%ZrUMdtM6` if the developer or anyone else can figure out what is causing the issue I believe it is something to do wit the passwords.

**Comment by jazzyoki** [comment]
i have the exactly same issue like the original poster with exactly the same error message.

**Comment by ryaneford** [comment]
Having similar issues with the widget using OC200

**Comment by jmairs** [comment]
I've read countless posts about the Omada Controller with Traefik reverse proxy and Homepage. I didn't really find help in those posts, but I did manage to cobble together a configuration that's working for me via Docker Compose and Dockge... Maybe I'm the help. :)

One note: for the initial login, visit https://docker-host-ip:8043. Accept the certificate error. Change your controller settings to NOT redirect HTTP to HTTPS. Then it'll allow Traefik and Homepage both to connect and work via http on 8088. And thus, you can access it via Traefik with working https -AND- have a nifty Homepage widget.

```
services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.13 #see https://github.com/mbentley/docker-omada-controller/issues/418
    restart: unless-stopped
    ports:
      - 8088:8088
      - 8043:8043
      - 8843:8843
      - "27001:27001/udp"
      - "29810:29810/udp"
      - 29811-29816:29811-29816
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      - PUID=1000
      - PGID=1000
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=America/New_York
    volumes:
      - ./omada/data:/opt/tplink/EAPController/data
      - ./omada/logs:/opt/tplink/EAPController/logs
    labels:
      #traefik
      - "traefik.enable=true"
      - "traefik.http.routers.omada-controller.rule=Host(`omada.domain.local`)"
      - "traefik.http.routers.omada-controller.entrypoints=https"
      - "traefik.http.routers.omada-controller.tls=true"
      - "traefik.http.services.omada-controller.loadbalancer.server.port=8088"
      #homepage
      - "homepage.group=Network Management"
      - "homepage.name=TP-Link Omada"
      - "homepage.icon=si-tplink"
      - "homepage.href=https://omada.domain.local"
      - "homepage.description=TP-Link Omada Network Management"
      - "homepage.widget.type=omada"
      - "homepage.widget.url=http://docker-host-ip:8088"
      - "homepage.widget.username=username"
      - "homepage.widget.password=password"
      - "homepage.widget.site=SiteName"
    networks:
      - proxy

networks:
  proxy:
    external: true

x-dockge:
  urls:
    - https://omada.domain.local
```

**Comment by TheNetworkLair** [comment]
I had the same issue as a poster above where I had a password with a lot of special characters. Something similar to IO*U6tr&^%r867&%$^%.  What fixed it for me was putting single quotes around my password. After reading the post I think sometimes somehow homepage/omada fail to authenticate somehow but putting password in single quotes fixed it for me.



    - omada:
        icon: omada.png
        href: https://192.168.x.x:8043
        description: Omada Status
        widget:
            type: omada
            url: https://192.168.x.x:8043
            username: adminuser
            password: 'adminpass'
            site: omada-site


TLDR; Put password in single quotes. Fixed it for me.

**Comment by bryan065** [comment]
Just putting this here for others to see. Recently updated to the newer `5.15.20` beta version which forcefully redirects to https (toggle to disable redirect has been removed). For some reason if I used it with https and a port appended, I would get API errors.

Using docker and MACVLAN driver, it'll give the controller it's own IP+MAC. Then I made sure to use port 80 for http and 443 for https. After that, it started working without API errors.

### Docker (Portainer):
```
services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:beta
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535    # changed to support beta cluster mode for controller high availability
        hard: 65535    # changed to support beta cluster mode for controller high availability
    stop_grace_period: 60s
    environment:
      - PUID=1001
      - PGID=100
      - MANAGE_HTTP_PORT=80    # Changed to port 80 for homepage dashboard
      - MANAGE_HTTPS_PORT=443  # Changed to port 443 for homepage dashboard
      - PORTAL_HTTP_PORT=8888
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - TZ=$TIMEZONE
    volumes:
      - /srv/remotemount/docker_config/omada:/opt/tplink/EAPController/data
      - /srv/remotemount/docker_config/omada:/opt/tplink/EAPController/logs
    networks:
      default:
        ipv4_address: 192.168.86.254      # Choose an IP on the subnet your network is on, that's not conflicting with any existing IP's or DHCP range
        mac_address: 52:65:56:EC:49:67    # Choose a random MAC address that's not conflicting

networks:
  default:
    name: omada    # MACVLAN network
    external: true
```

### MACVLAN Docker network:
Create a MACVLAN docker network (follow guides online, I'm using Portainer. It's possible to create all this through to docker-compose file as well). My main network is on `192.168.86.0/24` and the DHCP range is `192.168.86.1 - 192.168.86.48` so it won't conflict with any IP's on the MACVLAN network which is set to the `192.168.86.49 - 192.168.86.254` range. Alternatively, you can use the `IPV4 Excluded IPs` option when creating the MACVLAN network.

![Screenshot 2025-03-21 141553](https://github.com/user-attachments/assets/51d28128-1b7a-4ba1-97dc-2874db966f43)

### Omada Controller:
Make sure the http and https ports are also set in the Omada controller global settings. `Global view > Settings > System settings.`

![Screenshot 2025-03-21 142707](https://github.com/user-attachments/assets/a0b89d9f-dd58-4fe6-b549-dad8c323d742)

### Homepage setting:
Finally, last step is the Omada widget.

![Screenshot 2025-03-21 143705](https://github.com/user-attachments/assets/dcd78296-9e3f-4687-ba63-81e771191738)

![Screenshot 2025-03-21 143812](https://github.com/user-attachments/assets/29ccae08-8ab7-42b9-bf07-4d5298e8aecd)

![Screenshot 2025-03-21 144151](https://github.com/user-attachments/assets/e4b52283-7d32-42f6-a546-79c51a5f9600)

**Comment by goozoon** [comment]
For me im getting the same error when I just put type: omada and nothing else

```
    - Omada:
        icon: omada.png
        href: https://192.168.0.101:8043/
        description: Omada
        widget:
          type: omada
#          url: http://192.168.0.101:8088/
#          username: omda
#          password: 'K643567357wrd3uSV'
```

It should be something with Omada widget

**Comment by animosity022** [comment]
Yeah, no love for me either. I tried a fair amount of different things and just left with that it doesn't work.

**Reply by dbowles1975** [reply]
It works about 75% of  the time for me, but randomly throws the exact error in the original post. I can usually make it go away by restarting the Docker container. I've given up on using the widget as well.

**Comment by fallenleavesgocrunch** [comment]
OC200 here and I too get {"errorCode":-1600,"msg":"Unsupported request path."} from within Homepage's container.

**Reply by fallenleavesgocrunch** [reply]
The script here actually works - https://community.tp-link.com/en/business/forum/topic/253944
So I think there's a problem in the widget.

**Comment by dbowles1975** [comment]
Has anyone made any progress with this? Perhaps using the custom API widget instead?

**Reply by joshoram80** [reply]
Nothing working here for me either since upgrading controller

**Reply by dbowles1975** [reply]
> Nothing working here for me either since upgrading controller

It's been working for me since changing the widget URL to https with the correct port appended.

**Comment by pymiras** [comment]
Any updates on this issue? I experience the same problems. Tried all options, http/https, with/without port in the URL, password with/without single quotes. Nothing worked. Still see no values in the widget. My current config:

```
    - Omada:
        href: https://192.168.178.83:8043
        icon: omada.svg
        ping: 192.168.178.83
        widget:
            type: omada
            url: https://192.168.178.83:8043
            username: michael
            password: 'kzl7f4o4acA1!'
            site: Home
            fields: ["connectedAp", "activeUser", "alerts"]

```
