### DISCUSSION TITLE
Widget in docker version cannot display the correct storage capacity of the mounted hard drive

### DISCUSSION THREAD

**Discussion by cugfzx** [gethomepage/homepage#1582] [Support]
### Description

I mounted a  a large capacity hard drive on /app and set the storage capacity of the /app folder in the configuration file, but still displayed the storage usage of the root directory.
![image](https://github.com/benphelps/homepage/assets/52901066/fcf2ed32-9d26-4f61-9dbb-8e41080fa2f3)
![image](https://github.com/benphelps/homepage/assets/52901066/04c846ad-ce1a-482f-8814-20adbf7d5ecd)

### Steps to reproduce

1.Mount a hard drive on /app
2.Set widgets. yaml to the following content:
- resources:
    cpu: true
    memory: true
    disk: /app
3.Open the homepage webpage and you will find that the widget in the upper left corner still displays the capacity usage of the root directory

### homepage version

v0.6.20

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /app

	
- search:
    provider: duckduckgo
    target: _blank
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by ennvita** [comment]
Did you bind your /app (on host) to a folder in the container? It looks like it's reading the /app in the container not on the host. Try adding the volume bind. `/app:/drive`  to your `docker run` command or your `docker-compose.yml` and change your resources to look like this `disk: /drive` 

IIRC this should solve your problem

**Comment by shamoon** [comment]
`/app` refers to a directory at the root of the docker container, not sure why you would use that (you shouldn't)

See https://gethomepage.dev/en/widgets/resources/

> Any disk you wish to access must be mounted to your container as a volume.

So e.g.

docker-compose.yml
```yaml
  homepage:
    image: ghcr.io/benphelps/homepage:main
    ...
    volumes:
      ...
      - /media/disk:/mnt/cooldisk
```

homepage widgets.yaml
```yaml
- resources:
    label: MyMachine
    ...
    disk: 
        - /
        - /mnt/cooldisk
```
