### DISCUSSION TITLE
Wallpaper blur not full screen

### DISCUSSION THREAD

**Discussion by rashedobaid** [gethomepage/homepage#1588] [Support]
Hi! Blur, saturate and brightness settings doesnt work properly on 2k (1440p) maybe more on higher resolutions. It doesnt scale full screen. Works on fine on phones. Opacity does its job.

`Homepage version: v0.6.20 (6046f79, May 20, 2023)`

Here is my settings.yaml:
```
background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
```
![Homepage-Issue](https://github.com/benphelps/homepage/assets/24500062/5a7073ab-c2ba-42c1-b8b6-0ef7accb1f73)
