### DISCUSSION TITLE
Newly added icons do not load without container re-creation

### DISCUSSION THREAD

**Discussion by shalak** [gethomepage/homepage#1615] [Support] [answered]
### Description

When adding new icons to a directory mount, the icons are not loaded until the container is recreated

### Steps to reproduce

1. Create docker-compose with a directory mount dedicated for icons, e.g.:

```yaml
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    volumes:
      - /path/to/config:/app/config
      - /path/to/icons:/app/public/icons
      - /path/to/wallpapers:/app/public/wallpapers
```
2. Copy new icon file to icons dir, e.g. `/path/to/icons/proxmox.png`
3. Add new service to `/path/to/config/services.yaml`, e.g.:

```
- CategoryName:
    - ServiceName:
        href: https://url.to.service
        icon: /icons/proxmox.png
```
4. Open homepage

Expected:

Icon is loaded

Actual:

Icon is not loaded, `logo` placeholder is shown instead:
<img width="255" alt="image" src="https://github.com/benphelps/homepage/assets/1536554/9d1e1ae1-2d04-4ae0-952a-30b1fa3d1288">

Restarting the container solves the issue.

### homepage version

v0.6.20 (6046f79, May 19, 2023)

### Installation method

Docker

### Browser Logs

404 on the proxmox.png appears

### Troubleshooting

I `docker exec`ed into the container and confirmed that the `/app/public/icons/proxmox.png` exists and is readable.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
