### DISCUSSION TITLE
Quick question regarding sort order for widgets.yaml

### DISCUSSION THREAD

**Discussion by upD8R** [gethomepage/homepage#1650] [Support]
Hi there, just starting w/ homepage and I like it very much.
Still working on the content and layout but I do have aa question regarding the order in the header box.

I use resources and glances input and although all of entries are below the e.g. search box on the yaml they are shown first,
Actually, I'd like to have date, search, weather on top and the system info below that.

https://imgur.com/a/jPORZ36

Is this possible, and if yes, how to achieve this?

**Comment by luweijun1992** [comment]
+1

**Comment by snorkrat** [comment]
Stumbled on this as I also am wondering how to sort items in the header.

In my widgets.yml I have the following order:

```
- greeting:
- search:
- openmeteo:
- resources:
```
However, resources always appears right after the greeting.  Do we have to use custom css to order items in the header?

**Comment by craciuncosmin** [comment]
Any answer to this? I'm wondering the same thing

> Stumbled on this as I also am wondering how to sort items in the header.
> 
> In my widgets.yml I have the following order:
> 
> ```
> - greeting:
> - search:
> - openmeteo:
> - resources:
> ```
> 
> However, resources always appears right after the greeting. Do we have to use custom css to order items in the header?

**Reply by sunny-azu-red** [reply]
I actually switched the positions of the weather and resources through custom css and js, so yes... it's possible, just not by simply switching the order in the `widgets.yml` file.

![image](https://github.com/gethomepage/homepage/assets/163424707/3d275858-ba69-46e6-af40-398db229e1cc)
![image](https://github.com/gethomepage/homepage/assets/163424707/ebcb276a-b6d5-4cf4-94df-cc72e4de3147)
![image](https://github.com/gethomepage/homepage/assets/163424707/528e5bf8-c4d0-4064-8ebe-8aa9165e03d9)

I can share the code if you wish but my use case is somewhat particular and always a work in progress.

**Reply by craciuncosmin** [reply]
Hey, apologies for the late reply. I'd very much like to have a look at your code, if you're still willing to share it.
As a sidenote, am pleasantly surprised to see you're a fellow brașovean 😄

**Reply by sunny-azu-red** [reply]
Salut 👋
This is what I have right now.

![image](https://github.com/gethomepage/homepage/assets/163424707/22979dd7-9db3-474f-b526-1ff6e6d4233d)

```js
(function() {
    // update the glances resources url to internet accessible
    let glances = document.getElementsByClassName("information-widget-link").item(0);
    if(glances)
        glances.setAttribute('href', 'https://glances-for-chances.azu.red/');

    // reverse the weather and glances
    let weather = document.getElementById("information-widgets-right");
    if(weather && glances) {
        weather.classList.replace("grow", "grow-0");
        glances.classList.remove("grow-0");
        glances.querySelector(".information-widget-resource:last-child").classList.remove("mr-3");
    }

    // different greeting messages
    const greetings = {
        morning: "Good Morning Sunny 🥱",
        afternoon: "Good Afternoon Sunny 😃",
        evening: "Good Evening Sunny 🤪",
        night: "Good Night Sunny 😴"
    };
    let host = document.querySelector("li.service[data-name='Azured']");
    if(host) {
        let msg = host.querySelector("p.service-description");
        let hr = new Date().getHours();
        if (hr >= 6 && hr <= 11) msg.innerHTML = greetings.morning;
        else if (hr >= 12 && hr <= 18) msg.innerHTML = greetings.afternoon;
        else if (hr >= 19 && hr <= 23) msg.innerHTML = greetings.evening;
        else msg.innerHTML = greetings.night;
    }
})();
```

```css
@media only screen and (min-width: 1024px){
/**
    html {
        font-size: 20px;
    }
**/
    body {
        zoom: 1.2;
    }
}

@media only screen and (max-width: 767px){
    a.information-widget-link {
        flex-grow: 1;

        div.information-widget-resource {
           margin: 0 0.75rem;
        }
    }

    #information-widgets-right {
        display: none;
    }
}

body {
    #footer {
        display: none;
    }

    #page_container {
        --bg-color: 0 0 0;
    }

    #information-widgets {
        border-color: rgb(var(--color-200)/.2);

        #widgets-wrap {
            flex-direction: row-reverse;

            #information-widgets-right {
                margin: 0px;

                form {
                    display: none;
                }
            }
        }
    }

    #layout-groups {
        margin-top: 0.9rem;

        li.service[data-name="Azured"] > div > div {
            div.bottom-3.left-3, div.bottom-3.right-3 {
                bottom: 0.5rem;
            }

            div.bottom-3.left-3 > div:last-child {
                display: none;
            }

            div.overflow-clip:last-child {
                height: 52px;
            }
        }

        li.service[data-name="NPM"] {
            div.service-block:last-child {
                display: none;
            }
        }

        li.service[data-name="TOP"] > div > div {
            div.top-4.right-3 {
                top: 2rem;
            }

            div.bottom-4.right-3 {
                bottom: 0.75rem;

                > div > div {
                   font-size: .65rem;
                }

                > div > div:last-child {
                   display: none;
                }
            }

            div.overflow-clip:last-child {
                height: 52px;
            }
        }
    }
}
```
