### DISCUSSION TITLE
Docker Sockets numbers

### DISCUSSION THREAD

**Discussion by just5ky** [gethomepage/homepage#167] [Support] [answered]
Love the project. 
Finally, moving away from Flame dashboard
Thank-you for making `homepage`

I want to know how many docker dockets can we add?
I have 5 servers.

```yml
my-local-docker:
  socket: /var/run/docker.sock
my-remote-docker:
  host: 192.168.0.101
  port: 2375
```

Can i just keep adding more docker sockets like this?
```yml
my-othe-docker2:
  host: 192.168.0.102
  port: 2375

my-othe-docker3:
  host: 192.168.0.103
  port: 2375
```

And then just pass in the label.

```yml
- Emby:
  icon: emby.png
  href: "http://emby.home/"
  description: Media server
  server: my-othe-docker2 # The docker server that was configured
  container: emby # The name of the container you'd like to connect
```
