### DISCUSSION TITLE
[Bug?] Information widget

### DISCUSSION THREAD

**Discussion by Cinj216** [gethomepage/homepage#173] [Support]
**Describe the bug**
Since the last update, the information widget contains massive spaces between the resources forcing them to take more than one line whereas they were all in one continuous line previously on mobile. "expanded: true" existing or not makes no difference.

**Expected behavior**
CPU, RAM, HDD on one line instead of HDD below CPU because of the huge chunk of empty space between CPU and RAM.

**Screenshots**
Will provide if asked.

**Configuration**
```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

- resources:
    expanded: true
    cpu: true
    memory: true
    disk: /
```

**Additional context**
Worked fine prior to v0.3.39. Watchtower automatically pulls new releases every night after midnight EDT so I can't pinpoint the exact version that worked previously. I attempted to pull the image just now just to make sure this was the latest version and it indeed was.
