### DISCUSSION TITLE
Service Widgets not working

### DISCUSSION THREAD

**Discussion by mutschler** [gethomepage/homepage#1761] [Support] [answered]
### Description

All Service Widget don't seem to work, network requests fail with Internal Server Error

### Steps to reproduce

1. add a service with widget
2. see API-Error appear

### homepage version

0.6.26

### Installation method

Docker

### Configuration

```yaml
config of services:

- Network:
    - Uptime Kuma:
        description: Uptime Watcher
        icon: uptime-kuma
        widget:
          type: uptimekuma
          href: http://myurl
          slug: secretstatuspage
    - Gluetun:
        description: Gluetun VPN
        icon: gluetun
        server: my-docker
        container: gluetun
        widget:
          type: gluetun
          href: gluetunurl:8000
    - pterodactyl:
        widget:
          type: pterodactyl
          href: urlhere
          key: secretkey
```

### Container Logs

```
homepage    | Listening on port 3000
homepage    | [2023-08-02T14:28:15.224Z] error: undefined
homepage    | [2023-08-02T14:28:15.227Z] error: undefined
homepage    | [2023-08-02T14:28:15.228Z] error: undefined
homepage    | [2023-08-02T14:28:15.413Z] error: undefined
homepage    | [2023-08-02T14:28:20.424Z] error: undefined
homepage    | [2023-08-02T14:28:20.426Z] error: undefined
```

### Browser Logs

Example for one Service, repeats for every service with widget
```
 GET http://url/api/services/proxy?type=uptimekuma&group=Network&service=Uptime+Kuma&endpoint=status_page 500 (Internal Server Error)
```

### Troubleshooting

- Ping from container is working
- curl from container also gives correct response

### Other

the error message in log is kinda useless...
i wasn't able to get anything useful to show up at all:

setting `DEBUG_LEGEL` to `debug` didn't work for me i tried:
docker-compose way (with and without quotes) which only made it omit everything expect the listen part:
```
environment:
     - LOG_LEVEL='debug'
```
running the container directly and using `-e DEBUG_LEVEL='debug'` behaves the same.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
