### DISCUSSION TITLE
Paperless-ngx statistics not working

### DISCUSSION THREAD

**Discussion by blue-kaleidoscope** [gethomepage/homepage#1769] [Support] [answered]
Hi,

on the Discord channel I found a discussion where someone has the same issue as I have: https://discord.com/channels/1019316731635834932/1090183959649984526
However, there seems to be no active discussion which is why I seek help here.

On my local NAS I am using paperless-ngx inside a docker container. When configuring the widget, I do not receive any Inbox/Total documents information:
```
- Paperless-ngx:
        href: http://192.168.188.22:8000
        icon: paperless-ngx.svg   
        server: my-docker
        container: paperless-ngx-webserver-1
        showStats: true
        widget:
            type: paperlessngx
            url: http://192.168.188.22:8000
            username: <username>
            password: <password>
```
![image](https://github.com/benphelps/homepage/assets/56046815/59ec4fe7-59c2-4d7c-82c4-376bd60cf021)

The credentials are correct. I am actually using it with no authentication on my system. So the paperless-ngx `docker-compose.env` contains `PAPERLESS_AUTO_LOGIN_USERNAME=<username>`. When querying against the endpoint inside my browser I receive something:
```
{"documents_total":2349,"documents_inbox":0,"inbox_tag":5,"document_file_type_counts":[{"mime_type":"application/pdf","mime_type_count":2347},{"mime_type":"image/jpeg","mime_type_count":2}],"character_count":30421384}
```

Could you please help me?

Many thanks in advance,
Oliver

**Comment by shamoon** [comment]
The reason the [troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/#service-widget-errors) recommends running the queries from inside the homepage container is because they will often point out connectivity issues which is certainly what `ETIMEDOUT` would make me think

Start with that and let us know

**Comment by blue-kaleidoscope** [comment]
So, `ping` works inside the container:
```
/app # ping 192.168.188.22
PING 192.168.188.22 (192.168.188.22): 56 data bytes
64 bytes from 192.168.188.22: seq=0 ttl=64 time=0.276 ms
64 bytes from 192.168.188.22: seq=1 ttl=64 time=0.163 ms
```
But `curl` does not:
```
/app # curl http://192.168.188.22:8000/api/statistics/?format=json
```
It just waits and waits and waits and no output is given.

Outside of the container `curl` delivers a meaningful output:
```
[~] # curl http://192.168.188.22:8000/api/statistics/?format=json
{"documents_total":2354,"documents_inbox":0,"inbox_tag":5,"document_file_type_counts":[{"mime_type":"application/pdf","mime_type_count":2352},{"mime_type":"image/jpeg","mime_type_count":2}],"character_count":30462624}[~] #
```

**Reply by shamoon** [reply]
Oh I just read your top post again, have you tried using actual auth and disabling the the auto login setting (which btw, isn't recommended)?

**Reply by blue-kaleidoscope** [reply]
I did but the behaviour is still the same. When having logged off on the web UI and entering `http://192.168.188.22:8000/api/statistics/?format=json` into the browser, I get a "missing credentials" message: `{"detail":"Anmeldedaten fehlen."}`
In the logs I can see that also: `paperless-ngx-webserver-1  | [2023-08-04 08:18:06,858] [WARNING] [django.request] Unauthorized: /api/statistics/`

But still, when using inside the `homepage` container
```
/app # curl http://192.168.188.22:8000/api/statistics/?format=json
curl: (28) Failed to connect to 192.168.188.22 port 8000 after 130673 ms: Couldn't connect to server
```
the connection is not established at all (no log entries on paperless-ngx side) but `ping` makes me receive an answer.
Makes we wonder whether this is something QNAP specific again. I say this because the QTS embedded Linux sometimes acts in tiny details very different than a Linux dist one has full control of.

Regarding the auto login. I know it is not recommended but it is more convenient for me and my partner as the server is not exposed outside our network and the risk is acceptable over the convenience of not dealing with credentials. ^^

**Reply by blue-kaleidoscope** [reply, marked as answer]
Solved by workaround. I brought both the homepage and the paperless-ngx-webserver-1 container into the same container network. Using the webserver's lokal IP address makes me finally access the service:
```
    - Paperless-ngx:
        href: http://192.168.188.22:8000
        icon: paperless-ngx.svg
        server: my-docker
        container: paperless-ngx-webserver-1
        showStats: true
        widget:
            type: paperlessngx
            url: http://172.29.40.4:8000
            username: <username>
            password: <password>
```

So, no homepage issue. ;-)

**Reply by Jordo0G** [reply]
Thanks mate.

After adding the homepage container into the same subnet as the npm container the widget started working.
I just specified the npm network in the docker compose file 

```
   networks:
	- nginx-proxy_default
networks:
  nginx-proxy_default:
    external: true
```
