### DISCUSSION TITLE
widgets can't access api for plex and jellyfin behind SSL HAproxy

### DISCUSSION THREAD

**Discussion by cclarke591** [gethomepage/homepage#1776] [Support]
I'm currently trying to use the widget for services to load data for jellyfin and plex.
It's returning 503 errors, saying that no server could be found. Its clear that its getting stuck at the proxy. But loading the same URL in a web browser, works fine. Does https work? I noticed in the docs that both cases are http.

Side note the plex proxy sends all traffic containing plex.domain.net to the internal ip with the port number 32400.

Thoughts?

```
- Media:

    - Plex:
          icon: plex
          href: https://plex.domain.net/
          widget:
              type: plex
              url: https://plex.domain.net
              key: <X-Plex-Token>
    - Jellyfin:
          icon: jellyfin
          href: https://jellyfin.domain.net/
          widget:
              type: jellyfin
              url: https://jellyfin.domain.net
              key: <full api key>
              enableBlocks: false # optional, defaults to false
              enableNowPlaying: false # optional, defaults to true
```
