### DISCUSSION TITLE
Search via Spacebar setting target: _blank doesn't work

### DISCUSSION THREAD

**Discussion by link5412** [gethomepage/homepage#1792] [Support]
### Description

When Search bar at the top is used a new Tab is opened as expected.
When Search Mac Spotlight esk is invoked via Space or any other Key, when Result is accepted with Enter always opens a new Window.

Has anyone the same problem?
Now i use Autofocus on the Search Bar to get around that problem and don't use Spotlight style Search anymore.

### Steps to reproduce

1. Set target: _blank everywhere i know settings.yml, widgets.yml
2. Invoke Search on Homepage with Space or other Key.
3. Accept Search with Enter.
4. Page does **not** open as new Tab.

### homepage version

v0.6.28

### Installation method

Docker

### Configuration

```yaml
widgets.yml:
- search:
    provider: google # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank # One of _self, _blank, _parent or _top

settings.yml:
title: Home
language: de
target: _blank # Possible options include _blank, _self, and _top
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
