### DISCUSSION TITLE
Change Listening Port

### DISCUSSION THREAD

**Discussion by kuantek** [gethomepage/homepage#1794] [Support]
Is it possible to change the port that is listening within the container. I realize that this is a bit of a corner case, but I will be running this on a host that is already hosting grafana (also listens on port 3000). I am aware that I can change the port via mapping the host port to the container port, something like 3001:3000, however, that will mess with iptables. Due to the way docker interacts with IP tables, I have manually defined the ports in iptables to allow certain traffic.

Docker does not QUITE ignore the iptables, if the mapped port matches, I only have to put one iptable allow in, however if the mapped port doesn't match, I would have to add a ufw allow as well, which would break the standardization in my environment. Is there any kind of configuration within the container where I can have it listen on a different port?

**Comment by anilcelebi** [comment]
Hi,

We are trying to open a company repo but kuantek name is recently taken by you. Can i kindly ask you to consider changing the name of your repo. Kuantek Elektronik is a Türkiye based company with kuantek.com.tr and kuantek.com are also belong to us.

You can contact us from info@kuantek.com.tr

Regards,

**Comment by raghubhaskar** [comment]
I have another service using 3000, need to know if this is possile as well please.

**Comment by TheRolfFR** [comment]
Hello, if you are using Docker, this is just a port to change https://gethomepage.dev/en/installation/docker/#overview.
You have to modify the port field inside the docker-compose file or the option -p to change the exposed ports.

**Reply by kuantek** [reply]
"I am aware that I can change the port via mapping the host port to the container port, something like 3001:3000, however, that will mess with iptables. Due to the way docker interacts with IP tables, I have manually defined the ports in iptables to allow certain traffic"

Just changing the exposed port doesn't solve my use case because of the way docker interacts with iptables and ufw (lack thereof in the case of ufw)

**Comment by pjosuah** [comment]
Hi,
Adding to the latest comment: changing ports in docker-compose doens't solve the issue, the container is always listening on 3000.

**Comment by IIIdefconIII** [comment]
Same here, wanne start uding what up docker, alot of docker  isntances run oob on 3000

Can/will you change it like 3005, which is free compared against alot of docker containers im using, or make a config file that we can set our own internal port?

**Comment by IIIdefconIII** [comment]
a environment variable would be nice

**Comment by TheRolfFR** [comment]
Isn't PORT already a environment variable? 
https://github.com/benphelps/homepage/blob/c525dda77d40700b3afbc995980aff253727cb4f/Dockerfile#L59-L60

**Reply by IIIdefconIII** [reply]
thanks, indeed, could you tell me how i should apply it to a docker compose file on a synology?

I got this now:

```
 homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: always
    security_opt:
      - no-new-privileges:true    
    ports:
      - 3000:3000
    environment:
      TZ: $TZ    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/homepage/config:/app/config
      - $DOCKERDIR/homepage/images:/app/public/images
      - $DOCKERDIR/homepage/icons:/app/public/icons
      - /volume1:/volume1
      - /volume2:/volume2
      - /volume3:/volume3
      - /volume4:/volume4
      - /volume5:/volume5     
  ```

**Reply by IIIdefconIII** [reply]
should i change it to:

```
 homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: always
    security_opt:
      - no-new-privileges:true    
    ports:
      - 3123:3123    
    environment:
      TZ: $TZ    
      ENV PORT:3123      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/homepage/config:/app/config
      - $DOCKERDIR/homepage/images:/app/public/images
      - $DOCKERDIR/homepage/icons:/app/public/icons
      - /volume1:/volume1
      - /volume2:/volume2
      - /volume3:/volume3
      - /volume4:/volume4
      - /volume5:/volume5   
```

**Comment by Nonoss117** [comment]
I suggest to change :
ENV PORT:3123 -> PORT:3123
(remove ENV term)

**Reply by IIIdefconIII** [reply]
I love you! without kidding, thank you very, very much! that worked!

**Comment by IIIdefconIII** [comment]
!archive

**Comment by IIIdefconIII** [comment]
solution:

```
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: always
    security_opt:
      - no-new-privileges:true    
    ports:
      - 3123:3123
    environment:
      TZ: $TZ
      PORT: 3123
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/homepage/config:/app/config
      - $DOCKERDIR/homepage/images:/app/public/images
      - $DOCKERDIR/homepage/icons:/app/public/icons
      - /volume1:/volume1
      - /volume2:/volume2
      - /volume3:/volume3
      - /volume4:/volume4
      - /volume5:/volume5      
    labels:
     ## Pullio
      org.hotio.pullio.notify: "true"
      org.hotio.pullio.update: "true"
```
