### DISCUSSION TITLE
[Feature Request] Add weight using docker labels

### DISCUSSION THREAD

**Discussion by Emporea** [gethomepage/homepage#1805] [Feature Requests]
### Description

It would be really nice to be able to sort multiple docker instances by giving them weight as a label.

To use this example from the docs:
```
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    ports:
      - 8096:8096
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Emby
      - homepage.icon=emby.png
```

A simple `homepage.weight=1` or `homepage.widget.weight=1` would be really nice to have.

**Comment by joncrangle** [comment]
I currently pass `- homepage.weight=#` in the labels portion for my services, and they are sorted accordingly. It comes in really handy when you sort independently by group.

This feature was added in [v0.6.4](https://github.com/benphelps/homepage/releases/tag/v0.6.4).

Try adding a `- homepage.weight=1` to your labels and it should work.

**Reply by Emporea** [reply]
Just adding the docker label `homepage.weight=1` doesnt seem to work for me.

Do I also nees to create a service.yaml and set a weight again? Thats weird or what am i missing.

**Reply by joncrangle** [reply]
There is no need to create a service.yaml file. The weights in the labels section of the docker-compose file are honored.

In the following example, the widgets would be sorted as service2 and then service1:

```yaml
service1:
    container_name: service1
    image: dockerimage
    labels:
      - homepage.group=Group1
      - homepage.name=Service1
      - homepage.icon=icon.png
      - homepage.href=url
      - homepage.description=Description 1
      - homepage.weight=1
      - homepage.widget.type=type
      - homepage.widget.url=url
      - homepage.widget.key=key

service2:
    container_name: service2
    image: dockerimage
    labels:
      - homepage.group=Group1
      - homepage.name=Service2
      - homepage.icon=icon.png
      - homepage.href=url
      - homepage.description=Description 2
      - homepage.weight=0
      - homepage.widget.type=type
      - homepage.widget.url=url
      - homepage.widget.key=key
```
