### DISCUSSION TITLE
Gotify is not working

### DISCUSSION THREAD

**Discussion by pippo73** [gethomepage/homepage#1810] [Support]
### Description

![2023-08-13 08_26_35-Casa di Leo](https://github.com/benphelps/homepage/assets/757121/e8e780b3-b0c1-4d53-9166-04e5faa1f759)

### Steps to reproduce

```
    - Notifiche:
        href:  https://mysite.com
        description: Mi ha detto un uccellino
        ping: http://myinternalip
        icon: gotify.png
        widget:
          type: gotify
          url: https://mysite.com
          key: apikey
```

### homepage version

v0.6.28 (63a5622, 4 ago 2023)

### Installation method

Docker

### Configuration

```yaml
all the rest of my services.yaml wroks
```

### Container Logs

I have a lot of errors as follows
```

[2023-08-13T06:29:11.282Z] error: undefined
[2023-08-13T06:29:15.955Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://mysite.com/message
[2023-08-13T06:29:19.987Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://mysite.com/client
[2023-08-13T06:29:19.991Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://mysite.com/application

```

### Troubleshooting

_docker exec homepage ping_ works
don't know which is the right string to use for the curl test.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
