### DISCUSSION TITLE
Docker integration via socket

### DISCUSSION THREAD

**Discussion by lucamondini** [gethomepage/homepage#185] [Support]
Hi all,

I can't complete the docker integration and I don't know why.
Here is my docker.yaml:

```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

my-docker:
    socket: /var/run/docker.sock
```

My services.yaml:

```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎

- Group A:
    - Sonarr:
        icon: sonarr.png
        href: http://XXX.XXX.XXX.XX:8989/
        description: Series management
        server: my-docker
        container: Sonarr
        widget:
          type: sonarr
          url: http://XXX.XXX.XXX.XX:8989/
          key: <key>
```
I created the container mapping the volume as described in the wiki:

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: Homepage
    user: 1000:1000
    ports:
      - 3000:3000
    volumes:
      - /opt/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
```

Thank you so much.
