### DISCUSSION TITLE
[Help] Layout configuration...

### DISCUSSION THREAD

**Discussion by juanmanuelbc** [gethomepage/homepage#1854] [Support]
Please, I hope there's a way to achieve this layout configuration (but I think there isn't):
![imatge](https://github.com/benphelps/homepage/assets/13131391/31525c4c-8b1e-4b04-9a79-ee88cd3675b4)
Now, I'm using these settings:
```
layout:
    Synology:
        icon: mdi-nas
        style: row
        columns: 4
    Raspberry:
        icon: mdi-raspberry-pi
        style: row
        columns: 4
```
So, if anyone can help me or confirm that it's not possible to configure...
Thank you!!!

**Comment by A-Void-Me** [comment]
Did you try changing columns: 4 to -> 2? Because with 4 those 2 places will be blocked.

**Comment by juanmanuelbc** [comment]
> Did you try changing columns: 4 to -> 2? Because with 4 those 2 places will be blocked.

Yes, tested, and this is the result:
![imatge](https://github.com/benphelps/homepage/assets/13131391/d08ec950-7ce2-4b9e-a5cc-bcebd7956bd3)
These are the settings used in this case:
```
layout:
    Synology:
        icon: mdi-nas
        style: row
        columns: 4
    Raspberry:
        icon: mdi-raspberry-pi
        style: row
        columns: 4
```
I'm opened to any test in order to achieve the goal...
Thanks!!!

**Comment by mgrimace** [comment]
As far as I can tell, you have each device under a separate heading, so the style and columns you specified here wouldn't really apply since each of `synology` and `raspberry` groups only include one service. By saying 'row' for only one service, it should tell the widget to span the entire row. Since there's no other services under the each heading, the columns don't matter.

If you want them side by side, just remove the row style and use the default single columns.

An alternative method:
You could instead put them both under one service heading, then change your value in columns to `2`.

For example, in services.yaml, you might have them both under a heading like `Servers`, `Montoring` or whatever works. 

```yaml
- Servers:
    
    - Synology:
        icon: mdi-nas
        href: ...
        etc:...
 
    - Raspberry Pi:
       icon:...
```

Then, in settings, you'd put the one heading into a 2-column row, making sure that the heading here matches what you chose above.

```yaml
layout:
    Servers:
        style: row
        columns: 2
```
