### DISCUSSION TITLE
[Feature Request] Support for bookmarks via docker labels

### DISCUSSION THREAD

**Discussion by ravensorb** [gethomepage/homepage#1857] [Feature Requests]
### Description

Not all docker apps have services that need full widgets.  It would be great if there was a way to set the type to "bookmark" and then define the icon and URL that would be triggered on a click.

Ex:
```
service1:
    container_name: service1
    image: dockerimage
    labels:
      - homepage.group=Group1
      - homepage.name=News Bookmarks
      - homepage.icon=icon.png
      - homepage.href=url
      - homepage.description=My Hosted RSS Reader
      - homepage.widget.type=bookmark
```
