### DISCUSSION TITLE
[Feature Request] Additional formats for customapi widget

### DISCUSSION THREAD

**Discussion by zerebos** [gethomepage/homepage#1870] [Feature Requests]
### Description

It would be nice to have more formats, especially `bytes` for the customapi widget. I looked into adding this myself by including a `template` option for each `field` in `mappings` (e.g. `{{value, byte(binary: true)}}`) that has `custom` format type, which works well, the only problem is that not all APIs are guaranteed to use bytes directly over something already scaled (MiB/KiB). But there was no good way to try and re-scale it to bytes through the yaml, so I added a `scale` option to `prettyBytes` (https://github.com/benphelps/homepage/blob/main/next-i18next.config.js) with a modification like this:

```js
if (options.scale) {
    const index = UNITS.indexOf(options.scale);
    if (index >= 0) number *= (options.binary ? 1024 : 1000) ** index;
  }
```

with a usage like
```yml
- Syncthing:
        icon: mdi-sync
        widget:
          type: customapi
          url: http://syncthing:8384/rest/svc/report
          headers:
            X-API-Key: redacted
          mappings:
            - field: totMiB
              label: Stored
              template: "{{value, bytes(binary: true; scale: 'MiB')}}"
              format: custom
```

This works, and correctly formats the size.

![image](https://github.com/benphelps/homepage/assets/6865942/b1874619-3d35-4863-a25f-a79cf8847a47)

I'm just not sure this implementation above is really the best solution to this problem. It might be better to scale it somehow in the `customapi` widget directly and use `common.bbytes` and not allow fully custom template strings like I did.

Maybe shamoon or benphelps will have a better idea for implementation.
