### DISCUSSION TITLE
How can I add 2x rows of bookmarks

### DISCUSSION THREAD

**Discussion by gravelfreeman** [gethomepage/homepage#1873] [Support] [answered]
Basically I would like to add 2x rows of 4x columns each for the bookmarks. I can't seem to find how to achieve this.

**Comment by GetOutOfMyBakery** [comment, marked as answer]
In case you're still looking to do this (and assuming I've understood your question right), here's how:

in `settings.yaml`
```yaml
layout

    First Group Of Bookmarks:
      style: row
      columns: 4

    Second Group Of Bookmarks:
      style: row
      columns: 4
```

in `bookmarks.yaml`
```yaml
- First Group Of Bookmarks:
  - Homepage 1:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
  - Homepage 2:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
  - Homepage 3:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
  - Homepage 4:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation

- Second Group Of Bookmarks:
  - Homepage 1:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
  - Homepage 2:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
  - Homepage 3:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
  - Homepage 4:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
```

## How it looks
<img width="1394" alt="image" src="https://github.com/gethomepage/homepage/assets/12701930/36b1cc44-a6b1-4c21-8dd0-9035f9917930">

***

If that gets too cluttered, you can hide the descriptions:
```yaml
- Homepage 5:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: ""
```

<img width="1361" alt="image" src="https://github.com/gethomepage/homepage/assets/12701930/b1777b4c-ba63-4011-9a0c-b0b34a304f55">
