### DISCUSSION TITLE
Implementing secrets

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#1882] [Support] [answered]
In the services.yaml, let's say I want to use:

```yaml
    - Plex:
        icon: plex.png
        href: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400/web
        description: Plex server
        widget:
            type: plex
            url: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
            fields: ["streams", "movies", "tv"]
```
and similar labels for my other services. Where do the actual subsitutions live? For example, can I create a single .secrets file with a list of all the subsitution labels?

Example .secrets:
```
HOMEPAGE_VAR_SERVER_IP=192.168.x
HOMEPAGE_VAR_DOMAIN=mydomain.com
HOMEPAGE_VAR_PLEX_IP=192.168.y
HOMEPAGE_VAR_USER=username
HOMEPAGE_VAR_USER_EMAIL=my email
HOMEPAGE_VAR_PLEX_KEY=key 1
HOMEPAGE_VAR_SONARR_KEY= key 2
etc.
```

I've never used secrets before so this is a bit confusing for me. The documentation reads like I can use labels, but can those labels exist in a secret file like above, or do they have to be listed in the homepage compose.yaml? And files reads like each secret gets its own file, which would be a staggering amount of files. 

Any help with this would very much be appreciated!
