### DISCUSSION TITLE
All my qbittorent widgets are showing the same data

### DISCUSSION THREAD

**Discussion by gravelfreeman** [gethomepage/homepage#1888] [Support] [answered]
I can't get 4x different qbittorrent widgets at the same time. All the information is duplicated from one install.

Here's my code, as you can see the URLs are correctly pointing different services.

```
    - qBittorrent:
        icon: qbittorrent
        href: https://qb1.domain.tld
        ping: http://qbittorrent.ix-qbittorrent.svc.cluster.local:10091
        widget:
            type: qbittorrent
            url: http://qbittorrent.ix-qbittorrent.svc.cluster.local:10091
            username: admin
            password: adminadmin
    - qBittorrent:
        icon: qbittorrent
        href: https://qb2.domain.tld
        ping: http://qbittorrent-2.ix-qbittorrent-2.svc.cluster.local:10092
        widget:
            type: qbittorrent
            url: http://qbittorrent-2.ix-qbittorrent-2.svc.cluster.local:10092
            username: admin
            password: adminadmin
    - qBittorrent:
        icon: qbittorrent
        href: https://qb3.domain.tld
        ping: http://qbittorrent-3.ix-qbittorrent-3.svc.cluster.local:10093
        widget:
            type: qbittorrent
            url: http://qbittorrent-3.ix-qbittorrent-3.svc.cluster.local:10093
            username: admin
            password: adminadmin
    - qBittorrent:
        icon: qbittorrent
        href: https://qb4.domain.tld
        ping: http://qbittorrent-4.ix-qbittorrent-4.svc.cluster.local:10094
        widget:
            type: qbittorrent
            url: http://qbittorrent-4.ix-qbittorrent-4.svc.cluster.local:10094
            username: admin
            password: adminadmin
```
