### DISCUSSION TITLE
[Feature Request] Quick Launch Search Always Opens New Tab

### DISCUSSION THREAD

**Discussion by taylorcjensen** [gethomepage/homepage#1916] [Feature Requests]
### Description

Duplicate of #1087 from @viszz, using feature request format.

It doesn't look like quick launch internet search has the ability to specify `target: _self` like most other places.

In `widgets.yaml` you're able to specify:

```
- search:
      provider: custom
      url: https://kagi.com/search?q=
      target: _self
```

Ideally in `settings.yaml` we add an option under `quickLanch` that allows internet searches to happen with a specific target as well.
