### DISCUSSION TITLE
Customize link text on bookmarks...

### DISCUSSION THREAD

**Discussion by Jaxel** [gethomepage/homepage#1943] [Feature Requests]
### Description

Right now, the bookmarks system automatically adds the link host as text on the right side of the bookmark, such as:

```
  - Google Firebase:
    - icon: https://www.gstatic.com/mobilesdk/160503_mobilesdk/logo/favicon.ico
      href: https://console.firebase.google.com/
```

This will add the text `console.firebase.google.com` to the bookmark. It would be nice if we could define the text that appears on the right using a `description` tag.

**Comment by GetOutOfMyBakery** [comment]
Fly-by comment to say this was introduced shortly after you requested it:
- https://github.com/gethomepage/homepage/pull/2034

[Bookmark docs](https://gethomepage.dev/v0.8.3/configs/bookmarks/):
```yaml
- Social:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/
          description: The front page of the internet
```
