### DISCUSSION TITLE
[Bug] API Error: Proxmox Backup Server

### DISCUSSION THREAD

**Discussion by huseyinkogo** [gethomepage/homepage#1948] [Support]
### Description

Hi,

I'm getting the API ERROR for PBS.

Like the url is correct however its always been showing API ERROR: JSON.parse: unexpected character at line 1 column 1 of the JSON data

![Screenshot from 2023-09-09 20-42-24](https://github.com/benphelps/homepage/assets/76049382/4aac5b63-b4b6-4f91-a0c1-337695385270)

### Steps to reproduce

from the services.yaml file

### homepage version

v0.6.29 (fc7e73e, Aug 26, 2023)

### Installation method

Docker

### Configuration

```yaml
- Proxmox Backup Server:
        icon: syncthing.svg
        href: https://10.20.2.3:8007
        ping: https://10.20.2.3:8007
        widget:
          type: proxmoxbackupserver
          url: https://10.20.2.3:8007
          username: api_token_id
          password: api_token_secret
```

### Container Logs

n/a

### Browser Logs

XHRGET
https://homepage.kogo.com/api/services/proxy?type=proxmoxbackupserver&group=Backup/Sync&service=Proxmox+Backup+Server&endpoint=nodes/localhost/status
[HTTP/2 403 Forbidden 541ms]

### Troubleshooting

When i was playing it, i was like let me change the widget url to http from https.
after i was getting the following error:

```
    API Error: Unknown error
    URL: http://10.20.2.3:8007/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1693990706342
    Raw Error:
    {
        "errno": -104,
        "code": "ECONNRESET",
        "syscall": "read"
    }
```
![Screenshot from 2023-09-09 20-45-34](https://github.com/benphelps/homepage/assets/76049382/64813869-361e-4209-8690-3b0dfa91e9a0)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
A 403 error is auth.
You didnt post troubleshooting info and Im guessing you didnt search. Other people have had problems setting up the auth, that usually seems to be the issue. The widget isn't broken.

**Comment by Milkysunshine** [comment]
Did you give the api token permissions?

I got this working yesterday by giving the api token permissions to access / with an Audit role. 

Configuration>Access Control>Permissions Tab
Click Add -> API Token Permission

    Path: /
    API Token: select the Token ID
    Role: Audit
    Propagate: Checked

**Comment by huseyinkogo** [comment]
thanks for the reply.
the fields are set correctly; 
![image](https://github.com/benphelps/homepage/assets/76049382/68f29a4a-c834-4de6-8c7f-8a7e94932458)



regarding the permissions its already been set (@Milkysunshine )
![image](https://github.com/benphelps/homepage/assets/76049382/94ca2c95-b1c6-420c-a285-52721a1aed18)

**Comment by Milkysunshine** [comment]
Here's what I have working:

```
    - Proxmox Backup Server:
        icon: proxmox-light.png
        href: https://192.168.XXX.XXX:8007/
        description: Great Basin
        ping: https://192.168.XXX.XXX:8007/
        widget:
            type: proxmoxbackupserver
            url: https://192.168.XXX.XXX:8007
            username: USERNAME@pam!homepage
            password: `REDA-CTED-FOR-OBVIOUSREASONS
```

I think I see your issue. Your token is created for the pbs realm not the pam realm. Create a new token for a user in the pam realm and see if that resolves it.
