### DISCUSSION TITLE
Kavita Wigdet

### DISCUSSION THREAD

**Discussion by pocelka** [gethomepage/homepage#1949] [Support] [answered]
### Description

I have two problems with homepage when using Kavita widget. 

1. When I configure it with password it crashes the homepage. Fort his I have the configuration like this:

```yaml
- Others:                                                                                                               
    - Kavita:                                                                                                           
        icon: kavita.png                                                                                                
        href: http://192.168.1.3:9007                                                                                   
        description: E-book Reader                                                                                      
        widget:                                                                                                         
          type: kavita                                                                                                  
          fields: ["seriesCount", "totalFiles"]                                                                         
          url: http://192.168.1.3:9007                                                                                  
          username: username
          password: password with 30 characters containing special characters
```

2. If I use instead of password API key I get:
![image](https://github.com/benphelps/homepage/assets/20441822/62e7757c-e338-4ca3-add1-ec714db1faf0)

### Steps to reproduce

1. Start lscr.io/linuxserver/kavita:amd64-0.7.7 image as container
2. Configure widget for homepage wither with long password or API key

### homepage version

v0.6.29 (fc7e73e, Aug 26, 2023)

### Installation method

Docker

### Container Logs

**Logs 1:**
[2023-09-09T12:18:27.475Z] error: Failed to load services.yaml, please check for errors
[2023-09-09T12:18:27.475Z] error: YAMLException: unidentified alias "password with 30 characters - contains special characters" (73:51)
 70 |  ... seriesCount", "totalFiles"]
 71 |  ... //192.168.1.3:9007
 72 |  ... username
 73 |  ... password with 30 characters - contains special characters
-----------------------------------------^

**Logs 2:**
[2023-09-09T12:27:31.500Z] error: <kavitaProxyHandler> Unable to login to Kavita API: SyntaxError: Unexpected token Y in JSON at position 0
    at JSON.parse (<anonymous>)
    at login (/app/.next/server/pages/api/services/proxy.js:3115:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async apiCall (/app/.next/server/pages/api/services/proxy.js:3148:9)
    at async KavitaProxyHandler (/app/.next/server/pages/api/services/proxy.js:3203:7)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:365:29)
[2023-09-09T12:27:31.501Z] error: <kavitaProxyHandler> Error getting data from Kavita: http://192.168.1.3:9007/api/Stats/server/stats status 401. Data: 
[2023-09-09T12:27:32.562Z] error: undefined
[2023-09-09T12:27:36.558Z] error: undefined

### Troubleshooting

```bash
docker exec homepage ping 192.168.1.3      
PING 192.168.1.3 (192.168.1.3): 56 data bytes
64 bytes from 192.168.1.3: seq=0 ttl=64 time=0.059 ms
64 bytes from 192.168.1.3: seq=1 ttl=64 time=0.118 ms
64 bytes from 192.168.1.3: seq=2 ttl=64 time=0.060 ms
64 bytes from 192.168.1.3: seq=3 ttl=64 time=0.155 ms
^C
````

```bash
❯ http://192.168.1.3:9007/api/Opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/series?query=Last%20Hunter
zsh: no matches found: http://192.168.1.3:9007/api/Opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/series?query=Last%20Hunter

❯ curl -X GET "http://192.168.1.3:9007/api/Opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/series?query=Last%20Hunter" -H "accept: */*" -H "Authorization: 4e2f526b-fc77-4f09-aa2d-df789ec0318f"
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/2005/Atom">
  <updated>2023-09-09T12:43:51</updated>
  <id>search-series</id>
  <title>Last Hunter</title>
  <icon>/api/opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/favicon</icon>
  <author>
    <name>Kavita</name>
    <uri>https://www.kavitareader.com</uri>
  </author>
  <link rel="self" type="application/atom+xml;profile=opds-catalog;kind=acquisition" href="/api/opds//api/opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/series?query=Last Hunter" />
  <link rel="start" type="application/atom+xml;profile=opds-catalog;kind=navigation" href="/api/opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f" />
  <link rel="search" type="application/opensearchdescription+xml" href="/api/opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/search" />
  <entry>
    <updated>2023-09-09T12:43:51</updated>
    <id>869</id>
    <title>Fog of War (The Last Hunter Book 8) (Epub)</title>
    <link rel="subsection" type="application/atom+xml;profile=opds-catalog;kind=navigation" href="/api/opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/series/869" />
    <link rel="http://opds-spec.org/image" type="image/jpeg" href="/api/image/series-cover?seriesId=869&amp;apiKey=4e2f526b-fc77-4f09-aa2d-df789ec0318f" />
    <link rel="http://opds-spec.org/image/thumbnail" type="image/jpeg" href="/api/image/series-cover?seriesId=869&amp;apiKey=4e2f526b-fc77-4f09-aa2d-df789ec0318f" />
  </entry>
  <entry>
    <updated>2023-09-09T12:43:51</updated>
    <id>858</id>
    <title>Last Hunter (Epub)</title>
    <link rel="subsection" type="application/atom+xml;profile=opds-catalog;kind=navigation" href="/api/opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/series/858" />
    <link rel="http://opds-spec.org/image" type="image/jpeg" href="/api/image/series-cover?seriesId=858&amp;apiKey=4e2f526b-fc77-4f09-aa2d-df789ec0318f" />
    <link rel="http://opds-spec.org/image/thumbnail" type="image/jpeg" href="/api/image/series-cover?seriesId=858&amp;apiKey=4e2f526b-fc77-4f09-aa2d-df789ec0318f" />
  </entry>
  <entry>
    <updated>2023-09-09T12:43:51</updated>
    <id>874</id>
    <title>The Last Hunter (Epub)</title>
    <link rel="subsection" type="application/atom+xml;profile=opds-catalog;kind=navigation" href="/api/opds/4e2f526b-fc77-4f09-aa2d-df789ec0318f/series/874" />
    <link rel="http://opds-spec.org/image" type="image/jpeg" href="/api/image/series-cover?seriesId=874&amp;apiKey=4e2f526b-fc77-4f09-aa2d-df789ec0318f" />
    <link rel="http://opds-spec.org/image/thumbnail" type="image/jpeg" href="/api/image/series-cover?seriesId=874&amp;apiKey=4e2f526b-fc77-4f09-aa2d-df789ec0318f" />
  </entry>
</feed>%                                 
```

### Other

EDIT: So I tried it also with (according to official swagger end point tester):

```bash
curl -X GET "http://192.168.1.3:9007/api/Stats/server/stats" -H "accept: text/plain" -H "Authorization: 4e2f526b-fc77-4f09-aa2d-df789ec0318f"
```

and it doesn't produce any output. Might it be that there is an error in Kavita side?

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
