### DISCUSSION TITLE
Working custom api syntax for Dell iDRAC via Redfish

### DISCUSSION THREAD

**Discussion by Milkysunshine** [gethomepage/homepage#1952] [General]
I got this working on my servers, and figured I would share. Make sure Redfish is enabled in the idrac settings. 

```
    - iDRAC (R730 XD):
        icon: idrac.png
        href: https://IDRAC-IP
        description: Proxmox
        ping: https://IDRAC-IP/redfish/
        widget:
            type: customapi
            url: https://IDRAC-IP/redfish/v1/Chassis/System.Embedded.1/Thermal
            username: root # iDRAC is root by default
            password: YOURPASSWORD
            mappings:
              - field:
                  Temperatures:
                    2: ReadingCelsius
                label: CPU 1 Temp
              - field:
                  Temperatures:
                    3: ReadingCelsius
                label: CPU 2 Temp
              - field:
                  Temperatures:
                    0: ReadingCelsius
                label: Inlet Temp
              - field:
                  Fans:
                    1: Reading
                label: Fan Speed
```
![Screenshot 2023-09-09 114142](https://github.com/benphelps/homepage/assets/78696021/b19bbf91-44cc-489f-9e01-f0b897d3e3e1)

**Comment by ctv99** [comment]
do you have any more settings like drive array?

**Reply by Milkysunshine** [reply]
If you go to https://IDRACIP/redfish/v1 It gives you a list of what next subfolders are available. You can poke around from there and see if you can find what you are looking for, or you can check the redfish documentation.

You would have to choose if you wanted info from the Thermal page or a different page because of the way homepage works. As of the last time I checked, you can only have 1 url per widget so you can only get information that is provided on the URL's page.

I hope this helps a little bit, if not, feel free to reach back out.

**Reply by ctv99** [reply]
Thx for Reply - I fixed bad inlet temp reading

Here are some updated Modules
![Screenshot 2024-01-31 114752](https://github.com/gethomepage/homepage/assets/18556245/344c85cf-ce9c-4a25-a461-8a7b5d95f162)

   - iDRAC (R740 XD) Temps:
        icon: idrac.png
        href: https://ip
        description: Proxmox
        ping: https://ip/redfish/
        widget:
            type: customapi
            url: https://ip/redfish/v1/Chassis/System.Embedded.1/Thermal
            username: root # iDRAC is root by default
            password: calvin
            mappings:
              - field:
                  Temperatures:
                    0: ReadingCelsius
                label: CPU 1 Temp
                suffix: °C
              - field:
                  Temperatures:
                    1: ReadingCelsius
                label: CPU 2 Temp
                suffix: °C
              - field:
                  Temperatures:
                    2: ReadingCelsius
                label: Inlet Temp
                suffix: °C
              - field:
                  Fans:
                    1: Reading
                label: Fan Speed
                suffix: rpm
   - iDRAC (R740 XD) Power:
        icon: idrac.png
        href: https://ip
        description: Proxmox
        ping: https://ip/redfish/
        widget:
            type: customapi
            url: https://ip/redfish/v1/Chassis/System.Embedded.1/Power
            username: root # iDRAC is root by default
            password: calvin
            mappings:
              - field:
                  PowerSupplies:
                    0: LineInputVoltageType
                label: PS1 Line Voltage
                format: text
              - field:
                  PowerSupplies:
                    1: LineInputVoltageType
                label: PS2 Line Voltage
                format: text
              - field:
                  PowerSupplies:
                    0: PowerOutputWatts
                label: PS1 Output Wattage
                suffix: w
              - field:
                  PowerSupplies:
                    1: PowerOutputWatts
                label: PS2 Output Wattage
                suffix: w
   - iDRAC (R740 XD) Raid Volume:
        icon: idrac.png
        href: https://ip
        description: Proxmox
        ping: https://ip/redfish/
        widget:
            type: customapi
            url: https://IP/redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Volumes/Disk.Virtual.0:RAID.Integrated.1-1/Oem/Dell/DellVolumes/Disk.Virtual.0:RAID.Integrated.1-1
            username: root # iDRAC is root by default
            password: calvin
            mappings:
              - field: OperationName
                label: Current Operation
                format: text
              - field: OperationPercentComplete
                label: Percentage Complete
                format: percent
              - field: BusProtocol
                label: Drive Trype
                format: text
              - field: RaidStatus
                label: Status
                format: text

**Reply by Milkysunshine** [reply]
Cool, I'm glad you figured it out, and thanks for sharing.

I'm running all of my disk controllers in IT mode (HBA), so the idrac/Raid Controller doesn't do much for my personally, but the power usage is definitely useful!

Personally, I'd probably use the AverageConsumedWatts ( the average watts used over the past 60 seconds) instead of the second psu input line voltage as I don't have truly redundant power and other than a straight up PSU failure, redundant power supplies are only going to waste electricity for me. 

There are clearly plenty of options though!

**Reply by zmweske** [reply]
Here's another couple examples for anyone else's reference

```yaml
        widget:
            type: customapi
            url: http://custom.api.host.or.ip:port/redfish/v1/Chassis/System.Embedded.1/Power
            refreshInterval: 5000
            username: apireadonly # iDRAC is root by default
            password: password
            mappings:
              - field:
                  PowerControl:
                    0: PowerConsumedWatts
                suffix: W
                label: Power Usage
```
```yaml
        widget:
            type: customapi
            url: http://custom.api.host.or.ip:port/redfish/v1/Chassis/System.Embedded.1/Thermal
            refreshInterval: 5000
            username: apireadonly # iDRAC is root by default
            password: password
            mappings:
              - field:
                  Temperatures:
                    1: ReadingCelsius
                label: Inlet Temp
                suffix: °C
              - field:
                  Temperatures:
                    2: ReadingCelsius
                label: CPU 1 Temp
                suffix: °C
              - field:
                  Temperatures:
                    3: ReadingCelsius
                label: CPU 2 Temp
                suffix: °C
              - field:
                  Temperatures:
                    0: ReadingCelsius
                label: Exhaust
                suffix: °C
```
As stated earlier, I don't know if there is a way to include both the power and thermal in the same single widget

I was also able to create a new iDRAC user with read only permissions and can confirm that these most basic permissions do work:
![image](https://github.com/gethomepage/homepage/assets/31971632/ff155d77-e4bc-4776-b557-355692fbdde2)
