### DISCUSSION TITLE
Portainer widget not connecting

### DISCUSSION THREAD

**Discussion by moutasem1989** [gethomepage/homepage#1975] [Support] [answered]
I have set up the `services.yaml` gage as following:

```
    - Portainer:
        href: https://portainer.homelab.local/
        description: Docker managment platform
        icon: ./portainer.png
        widget:
            type: portainer
            url: https://portainer.homelab.local/
            env: 2
            key: ptr_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
it retuns this error:
`API Error: Unexpected non-whitespace character after JSON at position 4`
Can someone help me figure out where the problem is?
