### DISCUSSION TITLE
[Feature Request] Filter config for autodiscovery

### DISCUSSION THREAD

**Discussion by hugosxm** [gethomepage/homepage#1976] [Feature Requests] [answered]
### Description

Hi, 

I would like to use a label as a filter for which container would appear in homepage autodiscovery mode, let me explain why ^^: 

Let's say I have TWO instances of homepage, running on the same kube or swarm cluster. I want to use auto discovery so I place labels / annotations on all my containers / ingress but I want to select on wich instance of homepage each service will appear.

So it could be usefull for that case to have a parameters that say only discover the containers / ingress that have the labels / annotation that is specified in that parameter.

A full exemple would be in swarm : 

config of homepage main: 

```
my-docker:
    host: dockerproxy
    port: 2375
    swarm: true
    filter: homepage.main=true
```

config of homepage secondary : 

```
my-docker:
    host: dockerproxy
    port: 2375
    swarm: true
    filter: homepage.secondary=true
```

service I want to see on BOTH homepage

```
    labels:
      - homepage.main=true
      - homepage.secondary=true
      - homepage.group=Media
      - homepage.name=Emby
      - homepage.icon=emby.png
      - homepage.href=http://emby.home/
      - homepage.description=Media server
``` 

service I want to see on homepage main only

```
    labels:
      - homepage.main=true
      - homepage.group=Media
      - homepage.name=Emby
      - homepage.icon=emby.png
      - homepage.href=http://emby.home/
      - homepage.description=Media server
``` 

Hope this is clear enough !
