### DISCUSSION TITLE
Synology Diskstation widget -> authentication error

### DISCUSSION THREAD

**Discussion by Cantello** [gethomepage/homepage#1990] [Support]
I wanted to add the synology widget to Homepage in order to see at a glance the free amount on my volumes. However, after creating the user as per the instructions, it still does not work but instead just produces authentication errors:

`warn: <synologyProxyHandler> Unable to call http://192.168.1.1:5000/webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 400, error: Authentication failed..`

I can login with that user without problems and the user is part of the admin group (in order to access SYNO.Core.System.*).

Any ideas?

**Comment by fiowhe** [comment]
Push - I have the same problem here. Unfortunately, I only came across this after a few hours of tinkering

**Comment by LuciDuki** [comment]
I have the same Problem:

- [2023-10-03T10:28:43.061Z] warn: <synologyProxyHandler> Unable to login.  Code: 400
- [2023-10-03T10:28:43.072Z] warn: <synologyProxyHandler> Unable to call http://10.13.37.25:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info.  code: 400, error: Authentication failed..
- [2023-10-03T10:28:43.268Z] warn: <synologyProxyHandler> Unable to login.  Code: 400
- [2023-10-03T10:28:43.271Z] warn: <synologyProxyHandler> Unable to call http://10.13.37.25:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info&type="storage".  code: 400, error: Authentication failed..
- [2023-10-03T10:28:43.361Z] warn: <synologyProxyHandler> Unable to login.  Code: 400
- [2023-10-03T10:28:43.363Z] warn: <synologyProxyHandler> Unable to call http://10.13.37.25:5000/webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 400, error: Authentication failed..
- [2023-10-03T10:28:48.438Z] warn: <synologyProxyHandler> Unable to login.  Code: 400
- [2023-10-03T10:28:48.443Z] warn: <synologyProxyHandler> Unable to call http://10.13.37.25:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info.  code: 400, error: Authentication failed..
- [2023-10-03T10:28:48.642Z] warn: <synologyProxyHandler> Unable to login.  Code: 400
- [2023-10-03T10:28:48.648Z] warn: <synologyProxyHandler> Unable to call http://10.13.37.25:5000/webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 400, error: Authentication failed..
- [2023-10-03T10:28:48.668Z] warn: <synologyProxyHandler> Unable to login.  Code: 400
- [2023-10-03T10:28:48.672Z] warn: <synologyProxyHandler> Unable to call http://10.13.37.25:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info&type="storage".  code: 400, error: Authentication failed..


I am using Homepage V0.7.0 and DSM 7.2 Update 3
2FA is not activated for any user and adaptive MFA is also deactivated

**Comment by tom-dell** [comment]
I'm having this issue too, homepage just says "API Error" and when I click, the error message that normally displays is just empty.
I tried a few different url options (IP/http/s).

Homepage in docker v0.7.3, on DSM 7.2-64570 Update 3.
No 2FA, and I can manually login with that user.

Had a look at my logs, and `docker logs homepage` just dumps these lines over and over.

```
...warn: <synologyProxyHandler> Error 200 obtaining SYNO.Core.System info
...warn: <synologyProxyHandler> Error 200 obtaining SYNO.Core.System info
...warn: <synologyProxyHandler> Error 200 obtaining SYNO.Core.System.Utilization info
```

**Comment by rhasselbusch** [comment]
Check your passwords for special charackters.
'#' for example will break your yml without an error, because it is tnterpreted as a comment (that was my case).
Maybe other charackters produce an equal error.

Because i couldn't figure out how to escape the # correctly, i created a new user with a simpler password and that worked great.

**Reply by JulienSambre** [reply]
Thanks, it solved the problem : I have generated a strong password but without special character and it works like a charm!

**Reply by jewstan83** [reply]
For future solution seekers:

It was a combination of both special characters in the password and connecting with a public domain name. Changed to an alphanumeric password and LAN IP and it works perfectly. Thanks to @rhasselbusch for the solution.

**Reply by ACombatWombat** [reply]
This was my issue as well, once I removed all special characters I was able to pull data through API. Thanks a million @rhasselbusch!

**Reply by cusuanan** [reply]
Thank you rhasselbusch and jewstan83! I have use a strong password only including letters and numbers. And it works.

**Comment by vobi1024** [comment]
I have similar issues... The interesting thing is, that the DiskStation widget works fine. Only the DownloadStation widget show API Error, and nothing in the logs, only "error: undefined".

**Comment by cyrus104** [comment]
I just ran into the same problem, this is a bug in the way it works.

**Comment by junyuyuan** [comment]
我试了一下，当我把密码中的符号全部去掉，只使用字母和数字时，正常工作了。

**Comment by ikolsteren** [comment]
I am still having an issue with this widget for just one of my devices.   I have 8 Synology DSM widgets working and just 1 isn't.
The one that isnt working is of course one of the ones I care about
I have a simple password - the account has no 2FA on it - i can login to DSM with it and have done all the approval stuff.    using plain http for the widget.   i have checked the firewall etc on my DSM and at a loss.   This one unit has never been working.   The rest are no issue
Logs are showing a 402 error though -

**Reply by almawdah** [reply]
Same problem here, hope somebody finds a solution.

**Reply by almawdah** [reply]
It works now after I checked "Allow for Download Station" under Applications in the user settings.

**Reply by fanaticDavid** [reply]
@almawdah Thank you so much for your comment, I have my diskstation widget working now! But it makes no sense that I have to allow access to Download Station when I am **only** using the diskstation widget!

**Reply by ikolsteren** [reply]
Yes that did if for me too - had to create a new user that had DSM and Download Station permissions.
I was using an LDAP user originally but because of some weirdness Download Station is not available with LDAP users.
But new local user and DSM + Download works

**Comment by AdamXweb** [comment]
Same happened for me - had to allow both DSM and download station, even with just a widget type diskstation

**Comment by jbeckman1974** [comment]
I fought this all day!!! Thanks to @AdamXweb that was the fix.  I was doing only DSM and was getting errors.  Once I added Download Station permission to my user it started working...  This has been a long day, but I guess this is one thing down...

### For all:  ADD DSM and DOWNLOAD STATION permissions to your user, even if using only one of the apps.

**Reply by cbharis** [reply]
I literally just came here to say this is the solution! Thanks so much for this!!

**Reply by m-condamin** [reply]
Thanks a lot dear !

**Reply by mikenhu** [reply]
Thank you so much! This should be mentioned in the official doc

**Comment by devoopes** [comment]
I was having the exact same issue. Both DSM and Download station would not load. After all through above troubleshooting I took a guess at my (older?) DSM doesn't support long passwords? (was using 35 characters) Changed my password to a random 20 character just letters and numbers and its working now. 

Also, HTTP not HTTPS and you must include port.

**Comment by LETRA** [comment]
I have the same problem. I have tried the last two proposed solutions “add DSM and Download Station permissions to your user, even if using only one of the apps” and “Change password to a random 20 character just letters and numbers also url with HTTP not HTTPS and include port” and it doesn't work. I have also checked other parameters that were in other comments. Does anyone know how to fix this?

**Reply by AdamXweb** [reply]
Are you using Quickconnect or a URL behind a reverse proxy?

**Reply by LETRA** [reply]
Thank you. I don't think so, but these days I installed Deluge and the same thing happened to me. I changed the Deluge webUI password to a single 18 character letters and numbers and it worked. I have to test with Download Station, but that would mean changing the user account password to a very easily breakable one. If the problem is long passwords with special characters I think Homepage should fix that bug.

**Reply by AdamXweb** [reply]
I agree that it should support more characters. 
Out of curiosity, did you create a [separate user](https://github.com/gethomepage/homepage/blob/dev/docs/widgets/services/diskstation.md) when setting up the widget?

**Reply by LETRA** [reply]
I don't use the diskstation widget but wanted to use the download station widget which also has the same problem and is also discussed in the thread. I have not created separate users to manage the widgets, sorry.

**Comment by markalex2209** [comment]
Had similar problem, or more specifically #3611.
Since I had Prometheus monitoring metrics from Synology, and was not happy with storing plaintext password in config anyway, ended up replacing usage of this widget with [Prometheus Metric](https://gethomepage.dev/widgets/services/prometheusmetric/)

```
        widget:
            type: prometheusmetric
            url: http://prometheus.host.or.ip
            refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
            metrics:
                - label: Uptime
                  query: time() - node_boot_time_seconds{instance="synology:9100"}
                  format:
                      type: duration
                - label: CPU usage
                  query: 100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle", instance="synology:9100"}[5m])))
                  format:
                      type: percent
                      options:
                        maximumFractionDigits: 1
                - label: Memory used
                  query: ((node_memory_MemTotal_bytes{instance="synology:9100"} - node_memory_MemFree_bytes{} - node_memory_Cached_bytes{}) / node_memory_MemTotal_bytes{}) * 100
                  format:
                      type: percent
                      options:
                        maximumFractionDigits: 1
                - label: Space left
                  query: node_filesystem_avail_bytes{instance="synology:9100",mountpoint=~"/volume2"}
                  format:
                      type: bbytes
                      options:
                        maximumFractionDigits: 1
```
