### DISCUSSION TITLE
How to get glances info widget to show CPU identifier instead of swap

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#2014] [Support] [answered]
Hello,
I'd like to have the glances widget show the CPU info and not swap with  `chart: false` enabled. How do I customize `metric: info`?

Current services.yaml:

```yaml
- Glances:
    - Proxmox:    
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_PROXMOX_IP}}:61208
            username: {{HOMEPAGE_VAR_GLANCES_USER}}
            password: {{HOMEPAGE_VAR_GLANCES_PASS}}
            metric: info
            chart: false
```

Actual output:

<img width="372" alt="Screen Shot 2023-09-17 at 4 38 41 PM" src="https://github.com/benphelps/homepage/assets/55518507/8f2df3f6-4be2-4da0-b064-e6db6c1d77f4">

Desired output: 

<img width="520" alt="Screen Shot 2023-09-17 at 4 39 10 PM" src="https://github.com/benphelps/homepage/assets/55518507/82fdaabb-921c-4ce0-8263-5bf0f279e67c">
