### DISCUSSION TITLE
Nginx config prevents custom.css/custom.js loading so settings.yaml dont apply in v0.6.33

### DISCUSSION THREAD

**Discussion by MFYDev** [gethomepage/homepage#2017] [Support] [answered]
### Description

Hello there, I just started using Homepage today and thank you for this wonderful project!

I did a fresh install by using docker compose according to the official docs.

But every time if I change anything in the settings, all the settings won't take effect. All other yaml files will take effect immediately. I tried to fully delete the container, and also prune the volume and networks. None of them worked.

### Steps to reproduce

1. Use the below docker compose file to install 
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 9883:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```
2. Go to `./config/settings.yaml` and add `title: My Own Homepage` to the end of the file.
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
title: My Own Homepage
```
3. The setting won't take effect at all no matter what

### homepage version

0.6.33

### Installation method

Docker

### Configuration

```yaml
Just like the docker compose file above
```

### Container Logs

<img width="772" alt="image" src="https://github.com/benphelps/homepage/assets/53750381/a6cbbbb6-8b9c-41f3-aae7-1b9d2078f4b0">

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
