### DISCUSSION TITLE
hideErrors not working as expected

### DISCUSSION THREAD

**Discussion by hermannw** [gethomepage/homepage#2020] [Support] [answered]
When I set hideError to true in the settings.yaml, it works as expected but when I try to do the same in services.yaml, it does not work.
Example:
```
   - Octoprint:
        icon: octoprint.png
        href: https://192.168.1.1xx
        ping: https://192.168.1.1xx
        description: Octoprint
        hideErrors: true
        widget:
          type: octoprint
          url: https://192.168.1.1xx
          key: 49B49CCxxxxxx
```
Still shows this when Octoprint is offline.

![image](https://github.com/benphelps/homepage/assets/5613181/67a1ef9b-5e8a-458d-96dd-804aba5b6c2f)

Am I missing something?
