### DISCUSSION TITLE
Customapi widget and docker automatic service discovery

### DISCUSSION THREAD

**Discussion by dimitricappelle** [gethomepage/homepage#2027] [Support]
I love the customapi widget and I use automatic service discovery for almost all of my docker containers. But I'm having trouble to combine both. I'm struggling to format the 'mappings' so I can add them to the docker-compose.yml.
Any help would be appreciate. 

```  yml
mappings:
      - field: key # needs to be YAML string or object
        label: Field 1
        format: text # optional - defaults to text
      - field: # needs to be YAML string or object
          path:
            to: key2
        format: number # optional - defaults to text
        label: Field 2
      - field: # needs to be YAML string or object
          path:
            to:
              another: key3
        label: Field 3
        format: percent # optional - defaults to text
```

``` yml
labels:
  - homepage.widget.mappings...
```

**Comment by dimitricappelle** [comment]
Written as followed I managed to get a 'correct' docker-compose file with errors.

``` yaml
labels:
      ...
      homepage.widget.method: GET
      homepage.widget.mappings: >
      - field: key # needs to be YAML string or object
         label: Field 1
         format: text # optional - defaults to text
      - field: # needs to be YAML string or object
          path:
            to: key2
        format: number # optional - defaults to text
        label: Field 2
      - field: # needs to be YAML string or object
          path:
            to:
              another: key3
        label: Field 3
        format: percent # optional - defaults to text
```
But it doesn't work as the mappings are assigned in one assignment assuming a yaml object which is not the case. It's a string that still needs to be parsed as yaml.

A simple change in the service-helpers.js could do the trick.

As is:
``` js
if (type === "customapi") {
  if (mappings) cleanedService.widget.mappings = mappings;
  if (refreshInterval) cleanedService.widget.refreshInterval = refreshInterval;
}
```

To be:
``` js
if (type === "customapi") {
  if (mappings) {
    if (typeof mappings == "string") {
      cleanedService.widget.mappings = yaml.load(mappings);
    } else {
      cleanedService.widget.mappings = mappings;
    }
  }
  if (refreshInterval) cleanedService.widget.refreshInterval = refreshInterval;
}
```

If ok, I'll make a pull request for it.
