### DISCUSSION TITLE
[Feature Request] Custom API Information widget ?

### DISCUSSION THREAD

**Discussion by vikramsoni2** [gethomepage/homepage#2036] [Feature Requests]
### Description

I am thinking of adding my server's power consumption ( the data is provided by shelly plug ). 
Found in the documentation that I can create a Custom API Service widget, however its not exactly what I am looking for. I could create a component for Information Widget which uses custom API and shows me the current wattage of my server.
But wanted to ask, is there such functionality already implemented?
cheers!

**Comment by MatthiasOs** [comment]
I implemented an custom shelly widget:
https://github.com/gethomepage/homepage/discussions/3612
Maybe that's what you are looking for?

**Reply by vikramsoni2** [reply]
thanks, I just used this custom api:

But your widget looks good !!!  Will definitely give it a try.

```
- Power:
        icon: shelly.png
        description: Shelly plug S
        href: https://home.shelly.cloud/#/device/43454f83d547
        widget:
            type: customapi
            url: http://shelly.mydomain.com/meter/0
            refreshInterval: 10000 
            method: GET
            mappings:

              - field: power 
                label: Watts
```
