### DISCUSSION TITLE
[QUESTION] help on new tab feature (v30+)

### DISCUSSION THREAD

**Discussion by walteroa2023** [gethomepage/homepage#2043] [Support] [answered]
I've a nice layout of homepage, but to much info in one page, so, **I decided to go for a tabbed approach**.

![image](https://github.com/benphelps/homepage/assets/142554546/46f9a776-720b-41df-ae9f-8bd9814c1a78)

Now, due to my lack of knowledge on this new feature, I couldn't make it work... which frustrated me at amazing levels..

**i've tried to use the sample updated on the documentation, but nothing happens...**

```yaml
Bookmark Group on First Tab:
  tab: First

  First Service Group:
    tab: Performance
    style: row
    columns: 4

  Second Service Group:
    tab: Second
    columns: 4

  Third Service Group:
    tab: Third
    style: row

  Bookmark Group on Fourth Tab:
    tab: Fourth

  Service Group on every Tab:
    style: row
    columns: 4
```

who can help on this? I can share my settings.yaml or service.yaml file if needed..

help is welcome. Thx in advance :)

**Comment by shamoon** [comment]
Just to check: 
- ~~running the latest (or at least > .29) version?~~ Edit: I see your version in the title so assuming you've double-checked you correctly applied the update
- indentation is correct? (its not in your copy/pasted snippet above)

Otherwise, just post your actual settings.yaml content

**Reply by walteroa2023** [reply]
app updated to [v0.6.35 (d4a3929, 20 de sept de 2023)
[settings.txt](https://github.com/benphelps/homepage/files/12690128/settings.txt)

file renamed to txt to be uploaded (was .yaml)

**Reply by shamoon** [reply, marked as answer]
It looks like you just copy/pasted the sample at the bottom, which won't do anything. The `tab` field needs to be specified under `layout` for each service, e.g. for you:

```yaml
layout:

  Performance:
    tab: First
    icon: /icons/perf.png
    style: row
    columns: 6

  Top Containers:
    tab: Second
    icon: /icons/dockerwale.png
    style: row
    columns: 8

  Infrastructure:
    tab: Third
    icon: /icons/servers.png
    style: row
    columns: 6
...
```
