### DISCUSSION TITLE
Ability to set the default sorting weight in the docker settings

### DISCUSSION THREAD

**Discussion by UnclePhil** [gethomepage/homepage#2049] [Feature Requests]
### Description

in the doc you say that 
> Default weight for discovered services is 0
In this case, if you try to have your "administration" service before "all others", you need to set a `homepage.weight` labels for all services. 

If in the settings you allow something like this
```
docker-apps:
  host: my.docker.apps
  port: 2375
  swarm: true
  default_weight: 100
```
and set docker labels _just_ for admin services.

You have an automatic sorting system without too much configuration
