### DISCUSSION TITLE
[ERROR] Something went wrong. TypeError: p.drive is undefined

### DISCUSSION THREAD

**Discussion by jhermann** [gethomepage/homepage#2058] [Support]
I get this message since today for my "Storage" group with the disk resources. Any ideas?

This is the widget definition:
```
- resources:
    label: Storage (root, home, M9T, T7 Shield)
    disk:
        - /
        - /mnt/disk1
        - /mnt/disk2
        - /mnt/disk3
    expanded: true
```
The disks are mounted / mapped in the compose file. It worked yesterday, no clue what (I) changed.
