### DISCUSSION TITLE
Bookmarks not visible after upgrade to v0.6.35

### DISCUSSION THREAD

**Discussion by dejan-marcura** [gethomepage/homepage#2062] [Support] [answered]
### Description

There are no bookmarks displayed although previously configured

![image](https://github.com/benphelps/homepage/assets/56027770/5a58ae6c-fdb5-45a5-8c3e-3f97545d749d)

### Steps to reproduce

1. Load homepage dashboard
2. Navigate to the bottom of the page
3. Bookmarks section not visible

### homepage version

v0.6.35

### Installation method

Docker

### Configuration

```yaml
Bookmarks configuration file

---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Storage:
    - Transmission:
        - icon: transmission.png
          href: https://transmission.myhomeserver.online/
    - QNAP TS-433:
        - icon: /images/icons/qnap-icon.png
          href: https://nas.myhomeserver.online/

- Utilities:
    - Portainer:
        - icon: portainer.png
          href: https://portainer.myhomeserver.online/
    - FileBrowser NAS:
        - icon: filebrowser.png
          href: https://files.myhomeserver.online/
    - Yopass:
        - icon: /images/icons/yopass.svg
          href: https://yopass.myhomeserver.online/
    - IT-tools:
        - icon: it-tools.svg
          href: https://tools.myhomeserver.online/
- Network:
    - NAS:
        - icon: /images/icons/qnap.png
          href: http://qnap.myhomeserver.local/
          abbr: QNAP TS-433
    - Router:
        - icon: /images/icons/linksys-wrt.png
          href: http://router.myhomeserver.local/
          abbr: Linksys WRT3200ACM
    - Wi-Fi mesh:
        - icon: /images/icons/tplink.png
          href: http://wifi.myhomeserver.local/
          abbr: TP-Link Deco AC1200
```

### Troubleshooting

There are no console or network errors

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
What does your `layout` block under settings look like?

**Reply by dejan-marcura** [reply]
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: NAS624EC9
theme: dark
favicon: /images/icons/favicon.ico
headerStyle: underlined

layout:
  Media:
    icon: /images/icons/group-media.png
    style: column
    tab: Application services
  Utilities:
    icon: /images/icons/group-utilities.png
    style: column
    tab: Application services
  Network:
    icon: /images/icons/group-network.png
    style: column
    tab: Application services
  Storage:
    icon: /images/icons/group-storage.png
    style: column
    tab: Application services

  QNAP:
    icon: /images/icons/group-hardware.png
    style: row
    columns: 4
    tab: Infrastructure
  OrangePi:
    icon: /images/icons/group-hardware.png
    style: row
    columns: 4
    tab: Infrastructure

```
