### DISCUSSION TITLE
[Feature Request] Add portforwarded Field to Gluetun

### DISCUSSION THREAD

**Discussion by yoshi43** [gethomepage/homepage#2066] [Feature Requests]
### Description

I would love to be able to display the forwarded port from Gluten on the homepage.

It looks like it is accessible by calling http://gluetun.host.or.ip/v1/openvpn/portforwarded

Thank you!

**Comment by s3rverro0m** [comment]
I just set up Gluetun on Homepage and it would be amazing to show the forwarded port.

**Comment by saydo17** [comment]
I was able to use the custom api widget to do this.  Unfortunatly, I lose the other fields because the custom api widget only allows a single endpoint, #2475.
```
widget:
    type: customapi
    url: http://gluetun.host.or.ip/v1/openvpn/portforwarded
    method: GET
    mappings:
      - field: port
        label: Port
```
