### DISCUSSION TITLE
[How-to] Crafty Controller (Minecraft) widget using customapi

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#2085] [General]
With much help from their discord, I've been able to put together a Crafty widget. Note the requirements and limitations below.

<img width="442" alt="Screen Shot 2023-09-29 at 1 53 51 PM" src="https://github.com/benphelps/homepage/assets/55518507/5aa1c771-7200-4d1b-bbef-8eddfea5ee48">

```yaml
    - Crafty:
        icon: https://docs.craftycontrol.com/img/favicon.ico
        href: https://{{HOMEPAGE_VAR_CRAFTY_IP}}:8443 #this will be your crafty IP if you don't use secrets
        widget:
            type: customapi
            url: https://{{HOMEPAGE_VAR_CRAFTY_IP}}:8443/api/v2/servers/1/stats # in this line /1/ is the server ID, if you have multiple servers, you can change this number to a specific server of your choice
            refreshInterval: 10000 
            method: GET 
            headers: 
                Authorization: Bearer {{HOMEPAGE_VAR_CRAFTY_TOKEN}} #this will be your API token that you generate within the webUI
            mappings:
              - field: status 
                label: Status
                format: text 
              - field: 
                   data: online
                label: players
                format: number
              - field: 
                   data: cpu
                label: CPU
                format: percent
              - field: 
                   data: mem_percent
                label: RAM
                format: percent
```
## Requirements
Requires an API token. In the Crafty webUI click the settings gear, find your user (e.g., admin), then click the pencil edit icon for the user. Click the API key tab. For some reason, it requires `superuser` to be selected. Accordingly, consider using a secret as I did above. 

## Limitations
Only shows stats for a single, specific server, designated by the ID number in the path, `1` in my example above. If you have multiple crafty servers, you'd have to make additional widgets, changing this path.

## Other Possible Fields

Anything under: https://wiki.craftycontrol.com/en/4/docs/API%20V2#get-a-server-s-statistics is fair game. Here's a few that might be useful to swap in (untested):

```yaml
             - field:
                 data:
                   server_id: server_name #name of the current server specified by the ID# in the path
                label: name
                format: text
             - field:
                 data:
                   server_id: server_ip #ip address of the current server
                label: IP
                format: number
             - field:
                 data:
                   server_id: server_port #port for the current server
                label: PORT
                format: number                                
             - field:
                 data:
                   server_id: type #e.g., minecraft-bedrock
                 label: type
                 format: text  
             - field: 
                   data: online #number of players online
                label: players
                format: number
              - field: 
                   data: cpu
                label: CPU
                format: percent
              - field: 
                   data: mem_percent
                label: RAM
                format: percent
              - field: 
                   data: running
                label: running
                format: text
```

Closes: #1312

**Comment by mgrimace** [comment]
As a quick follow-up I submitted an issure re. the limitations to the crafty gitlab: https://gitlab.com/crafty-controller/crafty-4/-/issues/283. Ideally, we won't need a superuser token, and can present 'overall' stats rather than per server.

**Comment by mgrimace** [comment]
Updated with whole-server stats, and because the server_ID switched from number to UUID and AFAIK the hyphens in the UUID break the widget (http error)

```yaml
    - Crafty Controller: 
        icon: https://docs.craftycontrol.com/img/favicon.ico
        href: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
        ping: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
        widget:
            type: customapi
            url: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443/api/v2/crafty/stats
            refreshInterval: 10000
            method: GET
            headers:
                Authorization: Bearer {{HOMEPAGE_VAR_CRAFTY_TOKEN}}
            mappings:
              - field: status
                label: Status
                format: text
              - field:
                   data: cpu_usage
                label: CPU
                format: percent
              - field:
                   data: mem_percent
                label: RAM
                format: percent
              - field:
                   data: mem_usage
                label: RAM
                format: text
                suffix: "/24GB"
```
