### DISCUSSION TITLE
Need help getting Calendar to work in latest release of Homepage

### DISCUSSION THREAD

**Discussion by ozdeadmeat** [gethomepage/homepage#2090] [General]
Hi, I am trying to get the new calendar feature in Homepage to work. Is the widget information going in services.yaml or widgets.yaml. It all seems quite unclear in the documentation. Also, my experience with the widget system in the services.yaml usually needs to be part of a defined element first. What is that element as the only thing given on the website is the widget component of the configuration. Does ANYONE have a working config I could see of this calendar feature working as copying and pasting the config from the website appears to not do anything. or return an error.

**Comment by ozdeadmeat** [comment]
This is all I have managed to get out of it so far.

![image](https://github.com/benphelps/homepage/assets/11052863/d6ad4971-d64c-462f-8f31-ae4117366076)

**Comment by ozdeadmeat** [comment]
services.yaml Media Managers element has all my Radarr etc in there. And I have just pasted what was on the homepage website for this widget into the front of the Media Managers section.

```
- Media Managers:
    - widget:
      type: calendar
      firstDayInWeek: monday # optional - defaults to monday
      integrations: # optional
        - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
          service_group: Media Managers # group name where widget exists
          service_name: Sonarr # service name for that widget
          #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
          params: # optional - additional params for the service
            unmonitored: true # optional - defaults to false, used with *arr stack
        - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
          service_group: Media Managers # group name where widget exists
          service_name: Radarr # service name for that widget
          #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
          params: # optional - additional params for the service
            unmonitored: true # optional - defaults to false, used with *arr stack
        - type: lidarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
          service_group: Media Managers # group name where widget exists
          service_name: Lidarr # service name for that widget
          #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
          params: # optional - additional params for the service
            unmonitored: true # optional - defaults to false, used with *arr stack
        - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
          service_group: Media Managers # group name where widget exists
          service_name: Readarr # service name for that widget
          #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
          params: # optional - additional params for the service
            unmonitored: true # optional - defaults to false, used with *arr stack
```

**Comment by denispapec** [comment]
Hey @ozdeadmeat, 
It goes to services.yaml

You're missing main service description like name, icon, etc... and then widget is part where you define it's a calendar service, for example:

```
- Media Managers
    - Calendar:
        name: Calendar
        widget:
          type: calendar
          integrations:
            - type: radarr
            ...
```

edit: I can see in latest message that you're missing a service configuration part and went to configure service widget configuration directly in there.

**Reply by ozdeadmeat** [reply]
Thanks mate, It is looking a bit better now. Is there a way to fix the gap on the right of the calendar?

![image](https://github.com/benphelps/homepage/assets/11052863/d68d9448-0c7d-4045-a3ba-444a50d92d16)

**Reply by denispapec** [reply]
Put calendar in a group that is a column type, and other services in put in another column.

**Reply by ozdeadmeat** [reply]
I know that is probably done in the settings.yaml, do you have an example I could take a look at? How do you get two column types to show up next to each other, wouldn't they just show one after the other?

**Reply by ozdeadmeat** [reply]
OK, I think I sorted it

```
layout:
  Infrastructure:
    style: row
    columns: 4
  Media Management:
    style: column
  Media Services:
    style: column
  Streaming Server:
    style: column
    columns: 3
```

**Reply by shamoon** [reply]
You would probably want to make the calendar in its own group and then media next to it as a column (which is default)

```
style: row
columns: 3
```

means the group will spread horizontally as a row over 3 columns so calendar will be one column, next service the next etc

**Reply by ozdeadmeat** [reply]
Thanks for your help mate.

**Comment by shamoon** [comment]
Every widget example in the docs is just the widget part, they all need to be under a service.

**Reply by ozdeadmeat** [reply]
Yeah I guess I just hadn't done this in a while. It wasn't clear to me.

**Reply by mgrimace** [reply]
For what it’s worth it wasn’t clear to me at first from the documentation either, namely because the calendar screenshot used in the description doesn’t have a service name in it at all.

**Comment by dualice** [comment]
Hello,

I am trying the same thing but not getting anywhere.

In my services.yml I have:

```
- Calendar:
    - Calendar:
      name: Calendar
      widget:
        type: calendar
        firstDayInWeek: sunday # optional - defaults to monday
        integrations: # optional
          - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
            service_group: Calendar # group name where widget exists
            service_name: Sonarr # service name for that widget
            #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
            params: # optional - additional params for the service
              unmonitored: true # optional - defaults to false, used with *arr stack
          - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
            service_group: Calendar # group name where widget exists
            service_name: Radarr # service name for that widget
            #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
            params: # optional - additional params for the service
              unmonitored: true # optional - defaults to false, used with *arr stack
          - type: lidarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
            service_group: Calendar # group name where widget exists
            service_name: Lidarr # service name for that widget
            #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
            params: # optional - additional params for the service
              unmonitored: true # optional - defaults to false, used with *arr stack
          - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
            service_group: Calendar # group name where widget exists
            service_name: Readarr # service name for that widget
            #color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
            params: # optional - additional params for the service
              unmonitored: true # optional - defaults to false, used with *arr stack
```
              
              
In settings.yml I have:

```
  - Calendar:
      tab: Calendar
      style: row
      columns: 3
```

but all I get is:

![image](https://github.com/gethomepage/homepage/assets/4249448/af92d695-839c-4bce-9585-90cd75651053)

Please help!
Thank you!
