### DISCUSSION TITLE
[Feature Request] GraphQL support for customapi

### DISCUSSION THREAD

**Discussion by LeFauxMatt** [gethomepage/homepage#2102] [Feature Requests] [answered]
### Description

I would like to add a widget to a custom api which uses graphql.

customapi almost supports this use case, but I'm not sure how to send the data payload to the api endpoint.

For example:

```yaml
widget:
    type: customapi
    url: http://myservice/graphql
    method: POST
    data: {query:stats{video_count creator_count}}
    headers:
        Content-Type: application/json
    mappings:
        - field:
            data:
                query: video_count 
            label: Videos
        - field:
            data:
                query: creator_count
            label: Creators
```

### Other

Here is how that query could be run via curl:

`curl -X POST -H "Content-Type: application/json" --data '{ "query": " stats { video_count creator_count }" }' myservice/graphql`
