### DISCUSSION TITLE
[Feature Request] Folding@home widget

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#2112] [Feature Requests] [answered]
### Description

Folding@Home, aka FAH, aka Folding at Home allows users to donate idle computing power to help fight diseases like cancer, COVID, Alzheimer's, etc. ([website](https://api.foldingathome.org))
The service has a webui (screenshot below), and api ([documentation](https://api.foldingathome.org)) that allows stats to be pulled: 
![Screenshot 2023-10-04 at 10 46 52 AM](https://github.com/benphelps/homepage/assets/55518507/e682a561-91e2-4d8d-b098-34dace2fbf09)

**Comment by shamoon** [comment]
I like this one just cause it's a cool project. I think you can probably do it with `customapi` tho?

**Reply by mgrimace** [reply]
It should be pretty straightforward with `customapi`
it looks like `curl -G https://api.foldingathome.org/uid/:id/totals`returns the 'work units' and 'score' for a specific userID. There's other stats than can be grabbed for a user based on ID or a team as well.

So it *should* just be a matter of using `https://api.foldingathome.org/uid/:id/totals` as the endpoint, and doing the mappings. My only challenge is finding a userID. I think you can grab from the name using something like `curl -G https://api.foldingathome.org/user/:name`, but my name doesn't seem to have anything associated with it yet, perhaps until I complete a work unit... investigating. 

I just set this up today so it's all new to me. I'll post my findings!

**Comment by mgrimace** [comment, marked as answer]
Ok, using `customapi` you can pull team stats or individual user stats. Other fields and API information can be found [here](https://api.foldingathome.org)

## Team stats

<img width="413" alt="Screenshot 2023-10-04 at 9 55 30 PM" src="https://github.com/benphelps/homepage/assets/55518507/1efeb662-05c2-455f-b91d-ab5f1f4368dc">

```yaml
    - Folding at Home:
        icon: foldingathome.png
        href: http://[IP, NAME, or SECRET]:7396 #add your address here
        widget:
            type: customapi
            url: https://api.foldingathome.org/team/[your team id] #add your teamID here
            refreshInterval: 43200000 #set for every 12 hours, for daily scores to not overuse their api 
            method: GET
            mappings:
              - field: name 
                label: Name
                format: text
              - field: wus
                label: work units
                format: number
                scale: 0.0000001 #adjust the scale as necessary
                suffix: mil #adjust the suffix as necessary
              - field: rank
                label: Rank
                format: number
              - field: score
                label: score
                format: number
                scale: 0.0000000001 #adjust the scale as necessary
                suffix: bil #adjust the suffix as necessary
```

## User stats

<img width="332" alt="Screenshot 2023-10-04 at 10 01 31 PM" src="https://github.com/benphelps/homepage/assets/55518507/6ad47569-418c-4aef-916a-46035b69b0ea">

```yaml
    - Folding at Home:
        icon: foldingathome.png
        href: http://[IP, NAME, or SECRET]:7396 #add your address here
        widget:
            type: customapi
            url: https://api.foldingathome.org/user/[Your Name] #add your user name here
            refreshInterval: 43200000 #set for every 12 hours, for daily scores to not overuse their api
            method: GET
            mappings:
              - field: name 
                label: Name
                format: text
              - field: wus
                label: work units
                format: number
              - field: rank
                label: Rank
                format: number
              - field: score
                label: score
                format: number
```

Note, I'm using [Banano](https://bananominer.com) as the test user/team here. Individual user stats are delayed for new accounts, so if you've created a new account it may not show your individual stats right away. It's not clear for how long.

**Updates**
- I changed the refresh interval to twice daily, feel free to change to more frequent though with these stats it's probably uncessary. There's also some potential caution on over-using the API and account banning.
- `rank` is probably not a useful field for an individual new user (e.g., I'm 'unranked' resulting in NaN in the box), just comment that out if you're new and not getting anything here.
