### DISCUSSION TITLE
[Feature Request] Quick Launch keywords / tags

### DISCUSSION THREAD

**Discussion by jbperrin88** [gethomepage/homepage#2123] [Feature Requests]
### Description

Hi there,

It would be nice if we can add some kind of tags / keywords to bookmark or service item to find them easily with quick search.

It may be a new field on each item like this :

```
- Group A
  - Item 1
        href: https://linkitem1
        description: this is item 1
        tags: one unique string 
  - Item 2
        href: https://linkitem2
        description: this is item 2
        tags: 
          - tags 1
          - tags 2
          - tags X  
```

I'll try to test my own code for this and push it tehre.

Best regards
