### DISCUSSION TITLE
[BUG] dot, when applied in settings doesn't show up for ping services, but basic does

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#2127] [Support] [answered]
Hello,

I believe this is a bug, but I'm not certain.
When I apply `dot` universally within settings.yaml, the dot does show up for docker services (as expected), but does _not_ show up on non-docker services, where ping is enabled in services.yaml (unexpected). 

In settings.yaml
```yaml
statusStyle: 'dot'
```
No over-ride style is set in the services.yaml. Here is the service entry:

```yaml
    - Plex:
        icon: plex.png
        href: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400/web
#        description: Plex server
        ping: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400
        widget:
            type: plex
            url: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
            fields: ["movies", "tv"]
```

<img width="578" alt="Screen Shot 2023-10-05 at 8 53 36 AM" src="https://github.com/gethomepage/homepage/assets/55518507/a15b6903-d972-45a9-a8d6-e6f1d4687966">

However, when I use `basic` in settings.yaml, it does show up as expected:
<img width="574" alt="Screen Shot 2023-10-05 at 8 51 14 AM" src="https://github.com/gethomepage/homepage/assets/55518507/37d70fb2-5324-4b35-9aaa-16265e11ceb1">

Homepage version: main (ed3055a, Oct 5, 2023)

**Comment by Nonoss117** [comment]
Hello, same for me :

Version : main (ed3055a, 5 oct. 2023)
```yml
 statusStyle:
```
![image](https://github.com/gethomepage/homepage/assets/79055577/85507f9b-7af6-4c27-b943-ab676b5d6d13)
.

```yml
 statusStyle: basic
```
![image](https://github.com/gethomepage/homepage/assets/79055577/131df823-9cc8-402d-8bfe-c1a547a0e921)
.

```yml
 statusStyle: dot
```
![image](https://github.com/gethomepage/homepage/assets/79055577/98e7e8dc-037f-494f-9124-d60d27f007dc)

**Comment by mirekmal** [comment]
I believe 'dot' setting is valid only for docker widget at the moment. Per documentation:
```You can choose from the following styles for docker or k8s status and ping: dot or basic```
So rather lack of this feature for other widgets than a bug...

**Reply by Nonoss117** [reply]
Oh, ok.
So `No statusStyle` and `statusStyle: basic` are working, but `statusStyle: dot` is not working
It was working with previous versions of homepage.
Bad luck for us

**Reply by mgrimace** [reply]
> I believe 'dot' setting is valid only for docker widget at the moment. Per documentation: `You can choose from the following styles for docker or k8s status and ping: dot or basic` So rather lack of this feature for other widgets than a bug...

*and ping: dot or basic* is the key in that phrase there, and it was working in the initial release of the feature (commit: 58c7fb1) where the dot styling was added to ping first. I also tested adding the userStyle override in settings.yaml for Plex, and it results in no dot (which was working previously, and should show 'dot'). So I do believe it is an unintentional bug with the recent code refactoring, where docker was added to the existing ping/dot feature.

```yaml
    - Plex:
        icon: plex.png
        href: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400/web
#        description: Plex server
        ping: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400
        statusStyle: dot #previously working
        widget:
            type: plex
            url: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
            fields: ["movies", "tv"]
```
<img width="404" alt="Screenshot 2023-10-05 at 10 12 56 AM" src="https://github.com/gethomepage/homepage/assets/55518507/618872b3-9aec-4e2c-83a3-46ec0c88cfca">

I am however implementing these features as soon as they're released in main, so it's possible something has changed that I have missed on my end.
