### DISCUSSION TITLE
Calendar API Error

### DISCUSSION THREAD

**Discussion by luweijun1992** [gethomepage/homepage#2150] [General]
Configuration:
```
- Calendar:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday # optional - defaults to monday
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
              service_group: Calendar # group name where widget exists
              service_name: Calendar # service name for that widget
              color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
              params: # optional - additional params for the service
                unmonitored: true # optional - defaults to false, used with *arr stack
```

Result:
![image](https://github.com/gethomepage/homepage/assets/58923704/d0f1ce32-c00c-475a-b167-9941e55b0862)

**Comment by chandz05** [comment]
Getting the same thing. Error message is: "API Error: radarr: Service does not support API calls"

**Reply by denispapec** [reply]
Hi @chandz05 , @luweijun1992 
make sure that `service_group` and `service_name` point towards the `sonarr` or `radarr` instance on the dashboard with their group and service names, for example:
```
...
   integrations:
     - type: sonarr
       service_group: Media
       service_name: Sonarr
       ...
```

**Reply by chandz05** [reply]
@denispapec This is what I have:

```
- Calendar:
    - Calendar:
        name: Calendar
        widget:
            type: calendar
            integrations:
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
            service_group: Media # group name where widget exists
            service_name: radarr # service name for that widget
- Media:
    - radarr:
        name: radarr
        icon: radarr.png
        href: http://[ip]:7878
        server: docker
        container: radarr
        widget:
            type: radarr
            url: http://[ip]:7878
            key: [key]
```
