### DISCUSSION TITLE
USB connected drives on Synology not working for resources

### DISCUSSION THREAD

**Discussion by poudenes** [gethomepage/homepage#2159] [Support]
Installed the Homepage tool on my Synology and everything is working correct. The drive itself is working
```
- resources:
      label: Storage
      expanded: true
      disk: /
```
But a external connected USB drive isn't working
```
- resources:
      label: Storage
      expanded: true
      disk: /volumeUSB1
```
Path to drive is correct.
Can this be a "rights" issue?
