### DISCUSSION TITLE
Portainer API Error

### DISCUSSION THREAD

**Discussion by sleeplessKomodo** [gethomepage/homepage#2179] [Support] [answered]
Hello! Homepage has been amazing to use so far, but I've run into this small issue with an API error for the portainer widget. The error is, 

`API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

I am using docker on a local machine on my home network. 

and my services.yaml is as follows, 

```
- Server Management:
    - Portainer:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
        href: https://192.xxx.x.xx:9443
        description: Making Docker and Kubernetes management easy.
        server: docker
        container: portainer
        widget:
          type: portainer
          url: http://192.xxx.x.xx:9443
          key: ptr_*******************************************=
```

I am new to servers, containerization and networking in general, so I'm not sure if this is a configuration error, or something else. Any hints in the right direction are welcomed!
