### DISCUSSION TITLE
Layout help

### DISCUSSION THREAD

**Discussion by iHumberto** [gethomepage/homepage#2180] [Support]
Hi guys, 

I need a little help with layout setting.  I want to put the calendar beside some widgets, but its not working well...

I created a group called media (inside the widgets.yaml file) and I put the calendar in it with others widgets like Jellyfin, jellyserr, Prowlarr etc...

After this I create a layout inside settings.yaml with this set up:

```
Media:
    style: row
    columns: 2
    icon: mdi-movie-open-star-outline
```

but the output is something like this:

![image](https://github.com/gethomepage/homepage/assets/26930588/c34763a3-a732-488b-a238-e6c86a0569aa)

There is any way to put the others widgets below jellyfin (bc there's a huge empty space there).

**Comment by shamoon** [comment]
There are other ways to 'hack' this layout a bit but I think the most straightforward is to put calendar in its own group, the *arr services in another and then put them in order in the layout. Then finally make the _next_ group in your layout a row, which will keep the calendar / *arr groups to take up only 2 columns total (if you dont have a row next homepage will keep adding more columns up to 4)

<img width="1515" alt="Screenshot 2023-10-12 at 12 32 06 PM" src="https://github.com/gethomepage/homepage/assets/4887959/f9b5aaa5-4f38-4679-b527-4ee9e610dd4d">

e.g.

```yaml
layout:
  Testing:
  Media:
  Home Management & Info:
    style: row
```

**Reply by bpwats** [reply]
Would you mind showing sample code to display the calendar? I cannot get it to show at all. I have the latest HomePage installed on unRAID.
I have a section in `settings.yaml` similar toy yours. I would expect this in `services.yaml` (dots are dashes)
- Calendar: #group name, also in settings.yaml, may have tab defined
    - My Calendar: #service name
      widget:
        type: calendar
        ... (additional optional settings, my arrs are setup correctly)

**Reply by iHumberto** [reply]
Sure..... Here's my code to display the calendar inside the services.yaml fil:

```
- Calendar: #group_name
    - Calendário: #Widget_name
        widget:
            type: calendar
            firstDayInWeek: sunday
            integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
                  service_group: Media Management # group name where widget exists
                  service_name: Sonarr # service name for that widget
                  color: purple
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
                  service_group: Media Management # group name where widget exists
                  service_name: Radarr # service name for that widget
                  color: violet
```

Looks like this:

![image](https://github.com/gethomepage/homepage/assets/26930588/325c526d-8513-4b02-8b6d-1cd91ddb390e)
