### DISCUSSION TITLE
How to do column layout with tabs?

### DISCUSSION THREAD

**Discussion by ThinkSalat** [gethomepage/homepage#2181] [Support]
Is it possible to get a layout like this but with tabs?

![image](https://github.com/gethomepage/homepage/assets/31082405/677a6a08-f595-4bab-8a34-69c00e292582)

What I want is two sections side by side, each with 2 items max on each row.
This is how it's set up now, but I 'd like the servarr sections and download section to each have two items per row. so for example the sonarr and radar items would be on the same row, with bazarr and prowlarr below it. the downloads section could remain how it is now.

![image](https://github.com/gethomepage/homepage/assets/31082405/82b8238d-4f82-40da-9786-f28763fdf9b2)

is it possible to configure this? 

Here's the section from my settings.yaml

```

layout:
  Speed Dial:
    tab: Speed Dial
    style: row
    columns: 4
  Servarr:
    tab: NAS
    style: column
    rows: 2
  Downloads:
    tab: NAS
    style: column
    rows: 2
  Media Servers:
    tab: NAS
    style: row
    rows: 4
```

and the section from my services.yaml

```
- Servarr:
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.50.89:8989
        description: Series management
        widget:
          type: sonarr
          url: http://192.168.50.89:8989
          key: xxxx
    - Radarr:
        icon: radarr.png
        href: http://192.168.50.89:7878
        description: Movie management
        widget:
          type: radarr
          url: http://192.168.50.89:7878
          key: xxxxxx
    - Bazarr:
        icon: bazarr.png
        href: http://192.168.50.89:6767
        description: Subtitle Managment
        widget:
          type: bazarr
          url: http://192.168.50.89:6767
          key: xxxxx
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.50.89:9696
        description: Usenet/Tracker Managment
        widget:
          type: prowlarr
          url: http://192.168.50.89:9696
          key: xxxxxxxx
```
