### DISCUSSION TITLE
[Feature Request] Allow internet search in quicklaunch without allowing the searchbar widget

### DISCUSSION THREAD

**Discussion by k4rli** [gethomepage/homepage#2188] [Feature Requests]
### Description

Currently it's required to have

```yaml
- search:
    provider: duckduckgo
    target: _blank
```

in `widgets.yaml` to have internet search in quicklaunch search bar as well. In order to not duplicate the search bar in quicklaunch+dashboard, it would be nice to be able to only have search via quicklaunch and to be able to configure search provider for it. 

Configuration could be done in `settings.yaml`

```yaml
providers:
  openweathermap: ...
  search: duckduckgo // or default value
  
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  hideVisitURL: false
```

**Comment by Flo2410** [comment]
An easy workaround for this is to add the following custom CSS:

```CSS
#information-widgets-right > .information-widget-search {
  display: none;
}
```
