### DISCUSSION TITLE
[Feature Request] Vikunja To-Do list widget

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#2193] [Feature Requests] [answered]
### Description

I'm requesting a Homepage widget for Vikunja, a self-hosted to-do list, [link](https://vikunja.io)

Official screenshot:
![image](https://github.com/gethomepage/homepage/assets/55518507/35a8061c-a25a-4ae9-b1b7-aa8999640cdf)

API documentation is found here: https://vikunja.io/docs/api-documentation/

**Comment by shamoon** [comment]
Cool project. I suspect you can achieve something for this with https://gethomepage.dev/v0.7.3/widgets/services/customapi/

**Reply by mgrimace** [reply]
Thanks, I found the public API documentation, https://try.vikunja.io/api/v1/docs with all the get and post options, as well as my own instance at `[mydomain]/api/v1/docs` but it is presently beyond me how to get the tasks and turn them into relevant widget counts/fields. That being said, I was able to do it for some other services using the customapi. I'll keep reading up, and hopefully if others are interested they might be able to contribute as well.

**Comment by alexgarciavila** [comment]
I'm interested in this functionality!
It could be very interesting to display the number of pending tasks, for example, or those with a close end date.

**Comment by edarsey** [comment, marked as answer]
<img width="1229" alt="Screen Shot 2024-05-01 at 2 29 39 PM" src="https://github.com/gethomepage/homepage/assets/16458401/bc74f828-7811-4d7b-9b51-0cd44b9b018a">

Since Vikunja has a 2 container stack in my docker compose setup, this is what I did for it.
This API call is for "done" tasks, the next one is for created tasks. You can make as many or as few fields as you want, but it is a fixed amount, I have 5. 
```
         widget:
          type: customapi
          url: https://sub.example.com/api/v1/tasks/all?sort_by=done_at&order_by=desc
          refreshInterval: 60000
          method: GET
          headers:
            Authorization: Bearer [token]
          display: list
          mappings:
            - field:
                0: title
              label: Last Done
              format: text
              additionalField:
                field:
                  0: done_at
                format: date
            - field:
                1: title
              label: Done Before
              format: text
              additionalField:
                field:
                   1: done_at
                format: date
```

`url: https://sub.example.com/api/v1/tasks/all?sort_by=created&order_by=desc`
