### DISCUSSION TITLE
Kubernetes Cluster not connected

### DISCUSSION THREAD

**Discussion by urbaman** [gethomepage/homepage#2196] [Support]
Hi,

I deployed Homepage with the helm chart, v0.7.1 (last one I see among the availavle images) and I cannot get the Kubernetes resources to work:

```
 kubernetes.yaml: |
    mode: cluster
```

```
  widgets.yaml: |
    - logo:
        icon: mdi-home-outline-#0328fc
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - Kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
```

The homepage shows `Missing Kubernetes`

I did enable rbac and serviceaccount.
