### DISCUSSION TITLE
Portainer in kubernetes error

### DISCUSSION THREAD

**Discussion by urbaman** [gethomepage/homepage#2197] [Support]
Hi,

I'm trying the Portainer Widget on kubernetes. Portainer v2.19.1

I did configure Portainer:

```
      - Portainer:
          description: Portainer Management UI
          href: https://portainer.domain.com
          icon: portainer.svg
          widget:
            type: portainer
            url: https://portainer.domain.com
            env: 1
            key: ptr_<token>
```

But it shows an error on the homepage:

`API Error: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)`
