### DISCUSSION TITLE
[Feature Request] Allow to configure service name

### DISCUSSION THREAD

**Discussion by Dark3clipse** [gethomepage/homepage#2199] [Feature Requests]
### Description

Currently the name of a service displayed in the homepage is derived from the keyname of the encapsulating object.

Example service in my config:
```
- MikroTik_10GbE_Switch:
    icon: si-mikrotik-#293239
    href: https://switch.example.com
    description: Web GUI for MikroTik 10GbE Cloud Ethernet Router.
    widget:
      type: mikrotik
      url: https://switch.example.com
      username: api
```

Notice the need to use underscores in the key "MikroTik_10GbE_Switch".

In some configurations, the key cannot contain spaces. 

In particular, I am deploying to kubernetes using gitops principle with flux. I am using a secrets manager to inject the api password into the config. To do this, I need to let flux know the path of where to inject the password, which looks like this:

```
 - kind: Secret
      name: switch-secret
      valuesKey: user-api-password
      targetPath: config.services[2].Infrastructure[1].MicroTik_10GbE_Switch.widget.password
```

Flux complains that spaces are not allowed when I try the name with spaces. So, as a result, I am forced with underscores in my service name in the homepage gui.

Ideally, configuration keys should be decoupled from what is visualized in homepage.

My proposal is to add a "name" key to the service object. When set, the value from this property will be used to display in homepage instead.
