### DISCUSSION TITLE
Cannot get all Docker stats and Calendar to work on unRAID

### DISCUSSION THREAD

**Discussion by bpwats** [gethomepage/homepage#2210] [Support] [answered]
Hello,

I have Homepage installed on unRAID using a custom network eth0 and direct access to the docker socket by default. “nobody” owns the HP source files. This works up to the point I can see whether my containers are up and running or not.

However, the Calendar does not show and also clicking on “Running” does not show cpu/mem stats. Presumably I need to use the security enhanced Docker.

So I downloaded the Dockersocket from CA. Set the custom network and applied an IP-address. The container port 2375 cannot be set by default. In Docker.yaml I changed the default socket to
my-docker:
  host: dockersocket
  port: 2375
Restarted HP. No success.
What am I doing wrong?

**Comment by Brikolo** [comment, marked as answer]
Hello, you can try this in `docker.yaml`

Keep dockersocket container

```yaml
MyUnraidDocker:               # this name will be used in settings.yml
  host: YourUnraidIP          # ex: 192.168.1.100
  port: 2375
```

and after, this is an example (speedtest-tracker) in `settings.yml` :
```yaml
    - Speedtest-Tracker:
        icon: speedtest-tracker.png
        href: put the container IP:PORT          #ex http://192.168.1.100:8045
        server: MyUnraidDocker                   # same name as docker.yml
        container: put the container name     # ex: speedtest-tracker
        description: blabla
        widget:
          type: speedtest
          url: put the container IP:PORT          #ex http://192.168.1.100:8045
```
