### DISCUSSION TITLE
[Feature Request] Columns within column categories

### DISCUSSION THREAD

**Discussion by HeasHeartfire** [gethomepage/homepage#2213] [Feature Requests]
### Description

I think it would be cool to be able to define columns within a column-style section, so services have the ability to stack next to each other instead of taking always the full with.

For example, instead of this:
![image](https://github.com/gethomepage/homepage/assets/13722220/533e5f40-8e11-4058-8824-241dbe8202d2)

I'd like to be able to do this (it's a quick edit, don't mind the colors):
![image](https://github.com/gethomepage/homepage/assets/13722220/273d837d-135c-427a-b40a-bcfe59fb4bf7)

I don't know how it could be done. I'm guessing making the "columns" attribute work on "style:column" as well and then on each service being able to define a column span of some sort.

There are probably better or smarter ways to do this, but here is a mockup:
```
layout:
  Servicios:
    style: column
    columns: 2
    services:
      Nextcloud:
           column-span: 1
      Owncloud:
           column-span: 1

```
This is assuming that the services would be able to be referenced at this stage in the same way the categories can. Otherwise it might make sense to move the column span to each service on services.yaml
