### DISCUSSION TITLE
Unable to show ZFS array in resources?  (re: API error)

### DISCUSSION THREAD

**Discussion by sofakng** [gethomepage/homepage#2237] [Support] [answered]
I'm trying to show my two ZFS arrays in the resources list but it displays "API Error".

```
- resources:
    cpu: true
    memory: true
    expanded: true
    disk:
      - /tank
      - /storage
      - /
```

The root disk (/) shows the information correctly, but the other two display errors.

Am I doing something wrong?
