### DISCUSSION TITLE
Using Docker Socket Proxy with Homepage

### DISCUSSION THREAD

**Discussion by tr4cks** [gethomepage/homepage#2252] [Support] [answered]
Hey,

For a while I've been trying to set up [docker proxy](https://github.com/Tecnativa/docker-socket-proxy) to use Homepage. I've followed the documentation and modified the `docker.yaml` configuration file, but I can't get the status of the docker containers. It seems that homepage is still trying to access the docker socket directly, even though I'm telling it to use the proxy. By the way, I can see in the docker proxy logs that Homepage is indeed making a request to obtain the list of all containers.

Here's the server-side error message: `<dockerStatusService> Error: connect ENOENT /var/run/docker.sock at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)`.
And here's the documentation I followed: https://gethomepage.dev/v0.7.4/configs/docker/#using-docker-socket-proxy

If anyone has managed to get it to work with version `v0.7.4`, I'd be interested.
Thank you.

**Comment by tr4cks** [comment, marked as answer]
Ok so I come back to you for anyone who would make the same mistake as me. I started trying to debug the application when I realized that I had forgotten to define the docker server in the services configuration.

```yaml
- Group A:
    - Service A:
        href: http://localhost/
        description: This is my service
        server: my-docker # <<< HERE
        container: my-container
```

This server name must match the configuration in the `docker.yaml` file:

```yaml
my-docker: # <<< HERE
  host: dockerproxy
  port: 2375
```

This is not explicitly described in this documentation: https://gethomepage.dev/v0.7.4/configs/docker/#using-docker-socket-proxy.
It might be a good idea to add a sentence to specify that these 2 fields must match and, above all, to make sure you haven't forgotten them?

In any case thanks to the author for Homepage which is really cool!
