### DISCUSSION TITLE
[Feature Request] Start Sections Hidden on page

### DISCUSSION THREAD

**Discussion by ozdeadmeat** [gethomepage/homepage#2265] [Feature Requests]
### Description

Can there be flag we can put into specific parts of the layout so that when the page loads that section of the site is hiden?

Example:
```
layout:
  Infrastructure:
    style: row
    columns: 4
  Downloaders:
    style: row
    columns: 3
   starthidden: true
  Media Management:
    style: column
    starthidden: true
```
