### DISCUSSION TITLE
[Feature Request] Fork Pi.Alert support

### DISCUSSION THREAD

**Discussion by YoSafeguard** [gethomepage/homepage#2289] [Feature Requests]
### Description

Hello!
There is a fork Pi.Alert ([https://github.com/leiweibau/Pi.Alert](https://github.com/leiweibau/Pi.Alert)) It suits me much better than the one you use. Is it possible to support this fork in widgets?
Thank you!

**Comment by mgrimace** [comment]
Hi, if that's the script install version or the tteck proxmox version, then all you need to do is shift from IP:port, to IP/pialert/

```yaml
    - Pi.Alert:
        icon: pi-alert.png
        href: http://{{HOMEPAGE_VAR_PIALERT_IP}}/pialert
        siteMonitor: {{HOMEPAGE_VAR_PIALERT_IP}}
        widget:
            type: pialert
            url: http://{{HOMEPAGE_VAR_PIALERT_IP}}/pialert/
```

Note, I used secrets to define my IP as {{HOMEPAGE_VAR_PIALERT_IP}}. If you're not using secrets, you'll have to literally enter the IP for Pi.Alert in the services.yaml here.
