### DISCUSSION TITLE
TrueNAS Scale, should Kubernetes work?

### DISCUSSION THREAD

**Discussion by Reiss-Cashmore** [gethomepage/homepage#2291] [Support]
Hi,

so I have tried to configure Homepage to enable the Kubernetes integration with no success. On both the Truenas and Truecharts distributions but with no success.

Looking at the Truecharts values.yaml everything that is needed for Kubernetes integration looks present. Service Account is enabled, RBAC is enabled

https://github.com/truecharts/charts/blob/master/charts/stable/homepage/values.yaml

The only configuration I do when deploying the homepage image is to set a mounted storage volume for the configs
<img width="761" alt="Screenshot 2023-11-09 at 19 37 18" src="https://github.com/gethomepage/homepage/assets/17616211/d415b5bd-b6f5-4fde-b505-a75c9876756c">

I've tried both cluster mode and default mode

```
  kubernetes:
    mode: cluster
```

```
  kubernetes:
    mode: default
```

```
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
```

but this doesn't work

<img width="162" alt="image" src="https://github.com/gethomepage/homepage/assets/17616211/73c20889-c7e2-4672-869a-8189a8971b5f">

In the installation guide it references this chart for the unofficial https://github.com/jameswynn/helm-charts/tree/main/charts/homepage but I was unable to add this as a catalog for Truenas Scale. I tried some variations on the repo url with and without .git but you get errors like this

<img width="426" alt="image" src="https://github.com/gethomepage/homepage/assets/17616211/fd3930e4-9b06-45ca-8ad6-28b4543cc6b6">

Am I missing something?

I have resorted to opening the docker service port on my truenas instance but this doesn't really work well either because every time I upgrade the homepage container, it's container name is automatically renamed by Kubernetes so I have to change all of my service docker: fields every time I do an update or they break
