### DISCUSSION TITLE
feature iFrame height setting

### DISCUSSION THREAD

**Discussion by henkiewie** [gethomepage/homepage#2303] [Support] [answered]
I read the discussions about the new iFrame feature and I really like it.
But every value tried as explained in the tailwind website like `classes: h-full or auto or h-120` gives me a halfsize iFrame.
I know It's still a work in progress, but any hints would be appreciated.
https://github.com/gethomepage/homepage/pull/2261

```
    - Test2 iFrame:
        widget:
          type: iframe
          name: azuracast
          src: https://example.com
          #classes: h-120 sm:h-120 md:h-120 lg:h-120 xl:h-120 2xl:h-72 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
          classes: h-full
          #referrerPolicy: same-origin # optional, no default
          #allowPolicy: autoplay fullscreen gamepad # optional, no default
          #allowFullscreen: true # optional, default: true
          #loadingStrategy: eager # optional, default: eager
          #allowScrolling: no # optional, default: yes
          #refreshInterval: 2000 # optional, no default      
```
