### DISCUSSION TITLE
Service Widget for NUT UPS monitor

### DISCUSSION THREAD

**Discussion by adm2k** [gethomepage/homepage#2304] [Feature Requests]
### Description

Would like to see a service widget for NUT UPS monitor. https://networkupstools.org/

Specifically, the following data: "status", "battery %", "load%" and "battery runtime"

This does not seem to be available for any dashboard. I just started using Homepage and prefer it to any of the otheres!
This would complete my setup. Let me know if any more information is needed.

**Comment by wonkygecko** [comment]
Hey so I use APCUPSd which is near the same thing. I played around a bit with this last night with the custom API option to look at data and see if I could trick Homepage into pulling data in correctly, but the raw data page isn't formatted in JSON.

I do see there are a few API add on projects for APCUPSd on Github so I'm going to try and install one of those projects and see if i can generate the data into a proper JSON and query it through the API requests. Afterwards if I get it working with custom API I can look into the documentation on how to generate a true named widget for Homepage.

Again though, it will definitely need the addition of an API module to be configured on your APCUPSd/NUT host to make the widget work through Homepage.

Can't promise any time frame as I have a bunch of random projects I'm working on currently but I do have about half of December off and this is something I would like to see functionality wise as well, so I'm hoping to maybe get it figured out by the end of the year.

**Comment by adm2k** [comment]
Thanks for the feedback!

What I have done (so far) is use the iFrame widget and hacked the NUT upsstats.html to display the data i wanted. See the below:

![image](https://github.com/gethomepage/homepage/assets/120423301/d451f1a7-57ea-446e-8d2d-2112fca17e34)

Good luck on your efforts to get something working I appreciate it!

al

**Comment by ArthurMitchell42** [comment]
I use NUTCase which is a docker container which doubles up as a Prometheus data scraper and a JSON server for NUT servers.
This gives me 
![image](https://github.com/gethomepage/homepage/assets/82239494/06e0574c-8373-4082-a211-3b2f06138df7)
The service code is:
```
- UPS-Other:
    - DS9 UPS:
        href: http://10.0.10.9:9995/log?lines=40
        description: DS9 UPS
        icon: ups.png
        widget:
            type: customapi
            url: http://10.0.10.9:9995/json?target=10.0.10.9:3493
            refreshInterval: 60000 # In milliseconds, set to ~60s
            method: GET
            mappings:
                - field: 
                    ups:
                      input.voltage
                  label: Input
                  format: text
                  suffix: V
                - field: 
                    ups: battery.runtime
                  label: Runtime
                  format: float
                  scale: 1/60
                  suffix: Min
                - field: 
                    ups:
                      ups.load
                  label: Power
                  format: text
                  suffix: "%"
                - field: 
                    ups:
                      ups.status
                  label: Status
                  format: text
                  remap:
                    - value: "OL"
                      to: On-Line
                    - value: "OB"
                      to: Discharge
```
and the container and documentation are here:
https://hub.docker.com/r/kronos443/nutcase
https://github.com/ArthurMitchell42/nutcase
