### DISCUSSION TITLE
Widget resource not mapping disks correctly

### DISCUSSION THREAD

**Discussion by zhyph** [gethomepage/homepage#2308] [Support]
Hello, I'm using homepage on a docker compose in a WSL enviroment, but when running a command inside the container as `df /disks/e` it returns the correct size for that mounted volume, but when returning from the network tab it treats all the resources as '/', and weirdly enough sometimes it returns correctly, couldn't figure out why yet.

This was a random successful attempt on getting the disk c size and incorrect on the other one (notice the `"mount": "/"`):

```
// correct return on: http://*:3000/api/widgets/resources?type=disk&target=/disks/c
{
    "drive": {
        "fs": "drvfs",
        "type": "9p",
        "size": 1999619747840,
        "used": 1341160726528,
        "available": 658459021312,
        "use": 67.07,
        "mount": "/disks/c",
        "rw": false
    }
}
// incorrect return on: http://*:3000/api/widgets/resources?type=disk&target=/disks/e
{
    "drive": {
        "fs": "overlay",
        "type": "overlay",
        "size": 1081101176832,
        "used": 10468089856,
        "available": 1015640731648,
        "use": 1.02,
        "mount": "/",
        "rw": false
    }
}
```
The disks inside the container (yea, i know my disks are fucked):
```
/app # ls /disks
c  d  e
/app # df /disks/c -h
Filesystem                Size      Used Available Use% Mounted on
drvfs                     1.8T      1.2T    613.2G  67% /disks/c
/app # df /disks/d -h
Filesystem                Size      Used Available Use% Mounted on
drvfs                   111.8G    111.3G    471.6M 100% /disks/d
/app # df /disks/e -h
Filesystem                Size      Used Available Use% Mounted on
drvfs                   931.5G    902.0G     29.6G  97% /disks/e
/app # df /disks/ -h
Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G      9.7G    945.9G   1% /
```
This is my `widget.yml`:
```
- resources:
    label: Disk C Windows
    expanded: true
    disk: /disks/c

- resources:
    label: Disk D Windows
    expanded: true
    disk: /disks/d

- resources:
    label: Disk E Windows
    expanded: true
    disk: /disks/e
```
And this is my `docker-compose.yml`:
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /mnt/c:/disks/c
      - /mnt/d:/disks/d
      - /mnt/e:/disks/e
      - /home/zhyp/data/homepage:/app/config # Make sure your local config directory exists
        #      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: always
```
