### DISCUSSION TITLE
[Feature Request] Nested Groups

### DISCUSSION THREAD

**Discussion by tmeuze** [gethomepage/homepage#2310] [Feature Requests] [answered]
### Description

Thank you a lot for the great project. 

Simple request I think - but I couldn't find any talk of it: is it possible and/or planned to support nesting or sub-grouping? I particularly would appreciate the ability to collapse a parent group header to hide any children groups, and to set nested layout options such that you can fine-tune appearances. 

Or maybe this already exists and I'm totally missing it?

### Other

Simple Example:

services.yaml:
```
- Metrics:

    - Administration:
        - App 1:
        ...

    - Network:
        - App 5:
        ...
```

settings.yaml:
```
layout:

    Metrics:
        style: row
        columns: 4

    Administration:
        style: column

    Network:
        style: column
```
OR
```
layout:

    Metrics:
        style: row
        children:

            - Administration:
                style: column

            - Network:
                style: column
```

**Comment by snorkrat** [comment]
I'd also like this - this would allow me to have different column configurations for different rows in the same group.

EG: The first row could have 2 columns and the rows below could have 4 columns.  I could create the parent group with 1 column, child 1 with 2 columns and child 2 with 4 columns, hiding the headers on the child groups.

**Comment by RoboMagus** [comment]
I really like the graphical elaboration in #3083, which seems similar(?) to what's requested here.

**Comment by Tywele** [comment]
Would love to have a feature like this.

**Comment by mkopnsrc** [comment]
Would love to see this feature implemented given this is the second highest voted feature request. Thanks Devs

**Comment by DamitusThyYeetus123** [comment]
I would be happy to implement this, but I think I need a visual idea of what it would look like in order to implement it. The syntax example is helpful, but how it would visually work is also something i'd need.

**Reply by Tywele** [reply]
#3083 provides a visual concept of the idea.

**Comment by DamitusThyYeetus123** [comment]
![image](https://github.com/user-attachments/assets/0f301c38-2274-466d-84b9-a58185870234)
![image](https://github.com/user-attachments/assets/cf940174-4551-4f5e-9435-3679bbe361ed)
![image](https://github.com/user-attachments/assets/24b4e297-2ed2-4837-91f7-ad001902447f)
Basic concept (just messing with inspect element to figure something out), is this about what people are looking for?

**Reply by DamitusThyYeetus123** [reply]
The way I see this working in yaml based in reading through the source code is

services.yaml:
```yaml
- First group
  - Service A:
    href: ...
    description: ...
  - Subgroup A:
    type: group
    - Service B:
      href: ...
      description: ...
```
