### DISCUSSION TITLE
Help with Custom API and specific JSON mapping example

### DISCUSSION THREAD

**Discussion by davephoto** [gethomepage/homepage#2319] [Support]
I'm looking to implement additional widgets for a Mikrotik router using the Custom API and mapping.

I think can send the router this REST API command:

`curl -k -u USERNAME:PASSWORD https://172.16.1.1/rest/interface/monitor-traffic --data '{"interface": "pppoe-out1", "duration": "1s", ".proplist": ["name","rx-bits-per-second","tx-bits-per-second"]}' -H "content-type: application/json"`

which returns the following:

`[{".section":"0","name":"pppoe-out1","rx-bits-per-second":"66768","tx-bits-per-second":"22696"}]`

or, reformatted:

```
[
  {
    ".section": "0",
    "name": "pppoe-out1",
    "rx-bits-per-second": "66768",
    "tx-bits-per-second": "22696"
  }
]
```

I believe the proper widget configuration equivalent to the above `curl` looks something like:

```
        widget:
            type: customapi
            url: https://172.16.1.1/rest/interface/monitor-traffic
            refreshInterval: 10000
            username: USERNAME
            password: PASSWORD
            method: POST
            data: {"interface": "pppoe-out1", "duration": "1s", ".proplist": ["name","rx-bits-per-second","tx-bits-per-second"]}
            headers:
                content-type: application/json

```

I've tried a few things for `mappings:` to no avail, including the following:

```
            mappings:
                - field: rx-bits-per-second
                  label: RX
                  format: bitrate
                - field: tx-bits-per-second
                  label: TX
                  format: bitrate
``` 

Can anyone help shed some light on what I might be doing wrong? Thanks!
