### DISCUSSION TITLE
documentation on bookmarks

### DISCUSSION THREAD

**Discussion by icf20** [gethomepage/homepage#2321] [Support]
i ave been reading the documentation about bookmarks and is not obvious if there is a option to have bookmarks per tabs or not, so can you have bookmarks in certain tabs only?

**Comment by shamoon** [comment]
I believe the tabs docs covers that pretty clearly, it’s in the example there too.

You can put bookmarks on tabs. Also, easy enough to just try?

https://gethomepage.dev/v0.8.0/configs/settings/#tabs

**Reply by icf20** [reply]
u have in bookmarks 

```
- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/
          description: The front page of the internet

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

```
there is no mention of tabs
