### DISCUSSION TITLE
Connecting to multiple Kubernetes clusters?

### DISCUSSION THREAD

**Discussion by gnunn1** [gethomepage/homepage#2332] [Support]
I have homepage running on a small nuc type PC in my homelab with a couple of kubernetes (openshift) clusters running on separate servers.  When I attempt to add a couple of services with Kubernetes clusters using the default mode my expectation is that it will use the ~/.kube/config kubecontexts to connect to the clusters.

However I'm not seeing how the individual services get tied to specific kubecontexts, right now the widget just shows "Status: Offline". I'm not sure if there is naming convention or something else that is used to link the Homepage service to the appropriate kubecontext?

Here is my configuration in services.yaml:

```
- OpenShift:
    - Home:
        href: https://xxx.xxx.com
        icon: https://avatars.githubusercontent.com/u/792337?s=200&v=4
        widget:
          type: kubernetes
          cluster:
            show: true
            cpu: true
            memory: true
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
    - Hub:
        href: https://xxx.xxx.com
        icon: https://avatars.githubusercontent.com/u/792337?s=200&v=4
        widget:
          type: kubernetes
          cluster:
            show: true
            cpu: true
            memory: true
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
```

And my kubernetes.yaml:

```
mode: default
```
