### DISCUSSION TITLE
Portainer and NGINX do not show info

### DISCUSSION THREAD

**Discussion by trythatagain** [gethomepage/homepage#234] [Support] [answered]
I can not get either Portainer or NGINX widget to show information. Others work Sonarr, Jellyfin etc, so I think I've set them up correctly, I use vs-coder for yml files and have tried online yml formatter and all seems fine.

So both show green activity, and when clicked show cpu etc, but not the other information I've seen on here. 
I've tried both http and https for portainer and generated more than 1 key, to see if a key was duff.

I'm using OpenMediaVault (OMV), but wouldn't of thought that made a difference.
I use Dozzle for logs and below is all thats in the homepage log
20/09/2022 18:21:47Listening on port 3000
20/09/2022 18:21:47(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
20/09/2022 18:21:47(Use `node --trace-warnings ...` to show where the warning was created)  

If there is a way to grab more logs, please let me know.
I expect it's user error, but any help gratefully received.

**Comment by MeuricW** [comment]
For Portainer the biggest thing for me was getting the correct Key and ensuring I had the right environment selected.  In my instance it was Env 1. Make sure you include this in your widget details.

**Comment by benphelps** [comment, marked as answer]
What does your services.yaml look like.

Edit: Thanks @bigmak79 for catching a typo, https://github.com/benphelps/homepage/discussions/234#discussioncomment-3710545

**Reply by trythatagain** [reply]
- Containers:
    - Portainer:
        icon:   portainer.png
        href:   https://192.168.1.45:9443
        description: Manage Docker Containers
        container:  portainer
        server: myserver
        widet:
           type:  portainer
           url:   https://192.168.1.45:9443
           env:   2
           key:   ptr_etc=

    - Nginx:
        icon:   nginx.png
        href:   192.168.1.45:9981
        description: NGINX
        container:  nginx
        server: myserver
        widet:
           type:  npm
           url:   192.168.1.45:9981
           username:  my_username
           password:  my_password

portainer:- https://myserver:9443/#!/endpoints/2 

As I've said, I've put the yml through a checker and comes back good. 
Tried http and https as well.

**Reply by benphelps** [reply]
Try to paste it here in a code block, it can validate fine but still be incorrect.

**Reply by Nonoss117** [reply]
Hi,
may be change :
`href: 192.168.1.45:9981` to `href: http://192.168.1.45:9981`
`url: 192.168.1.45:9981` to `url: http://192.168.1.45:9981`

**Reply by trythatagain** [reply]
> Try to paste it here in a code block, it can validate fine but still be incorrect.

I thought I did.  How do I paste the block in and keep the yml format? Or do I just go through it after and alter in the message?

I've been through the file again and followed the Emby example in Service Widgets->Configuration and made sure it matched.

As I said my Sabnzb and Sonarr work correctly.

**Reply by trythatagain** [reply]
> Hi, may be change : `href: 192.168.1.45:9981` to `href: http://192.168.1.45:9981` `url: 192.168.1.45:9981` to `url: http://192.168.1.45:9981`

I have tried it both ways, but I will add the http(s) any way.

**Reply by benphelps** [reply]
Use 

\`\`\`
paste here
\`\`\`

**Reply by trythatagain** [reply]
I'm going to go through all the yml files and check the formatting after I've started a new homepage container and see the originals first. I'll post back later :)

**Reply by trythatagain** [reply]
I've been through the files and they seem formatted properly, I've included my jellyfin. which works as expected. I've also tried commenting 'server:' no change. I'm at a lost as to what try next. I've copied directly from vs-coder.

```
- Containers:
    - Portainer:
        icon:  portainer.png
        href:  192.168.1.45:9443
        description:  Manage Docker Containers
        container:  portainer
        server:  myserver
        widet:
          type:  portainer
          url:  192.168.1.45:9443
          env:  2
          key:  ptr_etc=

    - Nginx:
        icon:  nginx.png
        href:  http://192.168.1.45:9981
        description:  NGINX
        container:  nginx
        server:  myserver
        widet:
          type:  npm
          url:  http://192.168.1.45:9981
          username:  my_username
          password:  my_password

- Media Related:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.1.45:8096
        description:  Media Player
        container:  jellyfin
        widget: 
          type:  jellyfin
          url:  http://192.168.1.45:8096
          key:  apikey-etc  
```
