### DISCUSSION TITLE
monitoring a remote qbittorrent instance, getting api error

### DISCUSSION THREAD

**Discussion by gottoesplosivo** [gethomepage/homepage#2346] [Support] [answered]
Hello,

I'm trying to setup a widget to monitor a remote qbittorrent instance, however after setting up the widget I get this error
`API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.

The snippet is the following

```
- Backup:
    - qBittorrent:
        icon: qbittorrent
        href: https://domain/qbittorrent
        ping: https://domain/qbittorrent
        widget:
            type: qbittorrent
            url: https://domain/qbittorrent
            username: user
            password: pass
```

![Screenshot 2023-11-19 182235](https://github.com/gethomepage/homepage/assets/46649143/4bacd54f-455f-436f-8fba-4ff9f93939e9)

Ping is working and showing the remote host is up, since it is. But I can't get widget to work.
Could anybody help?

Thanks!

**Comment by dkowis** [comment]
I'm having the same problem, my configuration is basically the same:

```
    - Qbittorrent:
        icon: qbittorrent.png
        href: http://qbittorrent:8080/
        description: Torrents Downloader
        widget:
          type: qbittorrent
          url: http://192.168.69.254:8080
          username: admin
          password: teeheehee
```

No slash on the end of the URL, I've even tried adding `/api/v2` to it also, but I don't get any satisfaction.

I even installed curl into the homepage container to make sure it'd work, and it did, and yet still errors from the logs:

```
/app # curl -i --data 'username=admin&password=teeheehee' http://192.168.69.254:8080/api/v2/auth/login
HTTP/1.1 200 OK
connection: keep-alive
content-length: 3
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self';
content-type: text/plain; charset=UTF-8
cross-origin-opener-policy: same-origin
date: Sat, 23 Dec 2023 00:48:06 GMT
referrer-policy: same-origin
set-cookie: SID=pretendthisisvalid; HttpOnly; path=/; SameSite=Strict
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```

LOGS:
```
[2023-12-23T00:46:37.807Z] error: <qbittorrentProxyHandler> HTTP 404 getting data from qBittorrent.  Data: Not Found
[2023-12-23T00:46:48.538Z] error: <qbittorrentProxyHandler> HTTP 404 getting data from qBittorrent.  Data: Not Found
[2023-12-23T00:47:23.627Z] error: <qbittorrentProxyHandler> HTTP 404 getting data from qBittorrent.  Data: Not Found
[2023-12-23T00:47:49.636Z] error: <qbittorrentProxyHandler> HTTP 404 getting data from qBittorrent.  Data: Not Found
```

I don't know why it's giving a 404 in the logs, but I see the API error pasted above on the actual dashboard.
