### DISCUSSION TITLE
Modal window support

### DISCUSSION THREAD

**Discussion by gamosoft** [gethomepage/homepage#2366] [General]
First of all, thank you SO MUCH for this dashboard, I was using Dashy before which I also loved, but this one really got me because of its simplicity, the docker container status etc... 😊

Now one thing I am missing from this is the ability to open links in a modal window, something Dashy supports. And I believe this was asked some time ago (https://github.com/gethomepage/homepage/discussions/205), but I understand there are other things with more priority

For this I have created a **VERY** dummy implementation of it by means of using custom _css_ and _js_ files.
https://gethomepage.dev/v0.8.0/configs/custom-css-js/

Just create them and make them accessible to your instance with the following contents:

**custom.css**
```css
#modal {
    resize: both;
    display: none;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: -400px;
    margin-left: -400px;
    width: 800px;
    height: 800px;
    z-index: 3;
}

#overlay {
    position: fixed;
    display: none;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 2; /* Specify a stack order in case you're using a different order for other elements */
    cursor: pointer;
  }
```

**custom.js**
```js
const iframeName = 'modal';
const overlayName = 'overlay';

function loaded () {
    const overlay = document.createElement('div');
    overlay.id=overlayName;
    overlay.addEventListener('click', () => {
        document.getElementById(overlayName).style.display = 'none';
        const iframe = document.getElementById(iframeName);
        iframe.style.display = 'none';
        iframe.src = 'about:blank';
    });
    document.body.appendChild(overlay);

    const iframe = document.createElement('iframe');
    iframe.id=iframeName;
    iframe.name=iframeName;
    iframe.src = 'about:blank';
    document.body.appendChild(iframe);

    var tabs = document.querySelectorAll('button[role="tab"]')
    for (i = 0; i < tabs.length; i++) {
        tabs[i].addEventListener('click', () => setTimeout(addClickEvents, 1000));
    }

    addClickEvents();
};

function addClickEvents() {
    var modalTargets = document.querySelectorAll('a[target="' + iframeName + '"]')
    for (i = 0; i < modalTargets.length; i++) {
        modalTargets[i].addEventListener('click', click);
    }
}

function click(evt) {
    const iframe = document.getElementById(iframeName);
    iframe.src = evt.currentTarget.href;
    document.getElementById(overlayName).style.display = 'block';
    iframe.style.display = 'block';
}

window.onload = loaded;
```

Next all you have to do in your _services.yml_ file is use **target: modal**
![image](https://github.com/gethomepage/homepage/assets/9968384/02ac4990-f3c1-413d-abf6-394744d85eca)

And will look something like this:
![image](https://github.com/gethomepage/homepage/assets/9968384/25719607-9c9a-4177-a6b1-8b7748644cb1)

Please have in mind you may have CORS issues as well, because it renders inside an iframe, but there's nothing much I can do about it.
~~Also the iframe is not resizable, so please adjust the dimensions as you see fit, or if you feel brave enough make it resizable.~~
After posting this I just realized that adding `resize: both;` to the class it allows for resizing, so edited this page to include it. It doesn't reset or keeps in the center but again, it's a temporary hack. 😉
By default it waits 1000 ms when changing between tabs to allow for screen redraw and reattach the click events, so you may need to adjust this as well.

Thank you.
Kind regards.
