### DISCUSSION TITLE
Custom background not loading

### DISCUSSION THREAD

**Discussion by the0neWhoKnocks** [gethomepage/homepage#2396] [Support] [answered]
I've read through https://gethomepage.dev/v0.8.2/configs/settings/#background-image, and I restarted the Container after I added a new image. There's no error in the CLI, and nothing displayed on the page.

I went to http://localhost:3000/images/<IMAGE_NAME> and it loaded, so the Server has access to the image.

My `settings.yaml`
```yaml
# background: "/images/<IMAGE_NAME>"

background:
  image: "/images/<IMAGE_NAME>"
```

Image: `ghcr.io/gethomepage/homepage:v0.8.2`
