### DISCUSSION TITLE
Issue with Wazuh API using customapi widget

### DISCUSSION THREAD

**Discussion by shaunwalters** [gethomepage/homepage#2404] [Support] [answered]
Hey all! First post on Github so please be nice :) I am basically trying to replicate what [#2084](https://github.com/gethomepage/homepage/discussions/2084) accomplished but with Wazuh. I seem to be hitting a roadblock with using the token in the actual yml file.

```yaml
    - Custom API:
        widget:
          type: customapi
          url: https://WazuhIP:55000/agents/summary/status?pretty=true
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          username: wazuh # auth - optional
          password: wazuh # auth - optional
          method: GET # optional, e.g. POST
          headers: # optional, must be object, see below
            Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzAxMjk3NDA2LCJleHAiOjE3MDEyOTgzMDYsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AdCOZ4Vs5EciK-1g0kWxs4j4Mh6StV9meo-S2UBX2c_SDBx4lYGMz5hNGhjWJ03WVp7OpWvFtFeUfezlk6Kw8Zn4AIG6kT3lVZEhz2OGia6wARy-AtyiLVjTan5Jn5O-zscRXP5SLgG6M5YG3zWT9KNuXImD56Sc-yBE91Nm-DybY_Zx
          mappings:
            - field: # needs to be YAML string or object
                data:
                  connection: active
              label: Active
``` 

When I run the command from cli I do receive JSON data in return

`
curl -u wazuh:wazuh -k -X GET "https://WazuhIP:55000/agents/summary/status?pretty=true" -H "Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzAxMjk3NDA2LCJleHAiOjE3MDEyOTgzMDYsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AdCOZ4Vs5EciK-1g0kWxs4j4Mh6StV9meo-S2UBX2c_SDBx4lYGMz5hNGhjWJ03WVp7OpWvFtFeUfezlk6Kw8Zn4AIG6kT3lVZEhz2OGia6wARy-AtyiLVjTan5Jn5O-zscRXP5SLgG6M5YG3zWT9KNuXImD56Sc-yBE91Nm-DybY_Zx"
`

```json
{
   "data": {
      "connection": {
         "active": 10,
         "disconnected": 0,
         "never_connected": 0,
         "pending": 0,
         "total": 10
      },
      "configuration": {
         "synced": 10,
         "total": 10,
         "not_synced": 0
      }
   },
   "error": 0
}
```

When using this widget I am receiving an error on Homepage -

https://imgur.com/a/fNQU9XY

Is anyone able to help this noob out? I am sure it is something dead simple I am missing.
