### DISCUSSION TITLE
Custom API - Concatenate Multiple Items

### DISCUSSION THREAD

**Discussion by Budlyte** [gethomepage/homepage#2406] [Support]
Anyone know if it's possible to concatenate multiple items, from different keys, into a single output for the widget in the customapi?  (Writing this with lots of different words & spellings in order to be returned on as many search matches as possible.)

Here's what I have working.
```
    - Comics:
        icon: mylar.png
        widget:
            type: customapi
            url: http://192.168.1.202:8090/mylar/api?cmd=getHistory&apikey=APIKEY
            refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
            method: GET # optional, e.g. POST
            mappings:
                - field:
                    data:
                        0: ComicName 
                  label: Most Recent
                  format: text # optional - defaults to text
```
Result:
![image](https://github.com/gethomepage/homepage/assets/4451365/f70fa910-9353-484d-8ba6-8cb58fd54919)

And here's the data result, where I would like to combine the ComicName with the Issue_Number so that it says "X-Men Annual #1" in the widget.

```
data		[8028]
	0		{11}
IssueID	:	61120_9150
ComicName	:	X-Men Annual
Issue_Number	:	1
Size	:	null
DateAdded	:	2023-11-30 11:18:13
Status	:	Post-Processed
FolderName	:	null
ComicID	:	153608
Provider	:	null
Hash	:	null
crc	:	null
```
