### DISCUSSION TITLE
Customapi - Is it possible to have multiple queries in a single widget?

### DISCUSSION THREAD

**Discussion by Budlyte** [gethomepage/homepage#2407] [Feature Requests]
Example:

```
widget:
  type: customapi
  mappings:
    - field: 
      path:
         key 0
      url: http://custom.api.host.or.ip:port/path/to/exact/api/endpoint1
      label: Field 1
      format: text # optional - defaults to text
    - field: # needs to be YAML string or object
      url: http://custom.api.host.or.ip:port/path/to/exact/api/endpoint2
      path:
         key 0
      format: number # optional - defaults to text
      label: Field 2
```

I don't really need similar info from both Mylar & Komga, or other similar combos. So hoping for something like this to work.
![image](https://github.com/gethomepage/homepage/assets/4451365/64960bb8-887c-4aed-8b94-11a05aaa962c)

**Comment by cyberndj** [comment]
Thanks for the info!  Here is a pic of the json for the next level up in the URL. Hopefully it shows why we can't drill down in the tree from a higher level.
![image](https://github.com/gethomepage/homepage/assets/16530317/7777b0fe-38f9-4da5-803c-dc9b9754d4e3)

**Reply by Budlyte** [reply]
That's because the return of "api/dcim/" is the JSON you pasted above. You can get each of the endpoints successfully, individually.

I updated this thread to a Feature Request, since it looks like we're asking for the same thing here.

**Reply by cyberndj** [reply]
Crap...wrong post...but thank you!

**Reply by cyberndj** [reply]
Howdy, I did a workaround. I setup a Krakend container with a config that merges the different endpoint into a single endpoint that Homepage could reference. I used the https://designer.krakend.io/#!/ online tool to get the different fields. I had to only allow and rename the count field for each of the end points. There are some no responses that Krakend doesn't display, but its generally pretty good.

**Comment by pretubedongit** [comment]
Hi I really hope this can be implemented. I have encountered the same issue using linkding. They have different api endpoints for "Bookmark count" and "Tags count". Both are field "count" in "/api/bookmarks/" and "/api/tags/" respectively.

**Comment by OBoudreaux** [comment]
Adding another voice to the request of multiple endpoints in a single customapi widget. I'm attempting to get counts bookmarks, tags and highlights from hoarder but each is it's own endpoint.

**Reply by joepool** [reply]
I solved this with a php page that combines json of the two endpoints.
For example:
```
<?php
$player_url = 'http://192.168.0.3:3689/api/player';
$library_url = 'http://192.168.0.3:3689/api/library/count';
$player_response = file_get_contents($player_url);
$library_response = file_get_contents($library_url);
$response = [
    'player' => json_decode($player_response, true),
    'library' => json_decode($library_response, true),
];
header('Content-Type: application/json');
echo json_encode($response);
?>
```
Then you can query the php page in the custom api and will be able to use the data from both endpoints.

**Reply by pretubedongit** [reply]
> I solved this with a php page that combines json of the two endpoints. For example:
> 
> ```
> $player_url = 'http://192.168.0.3:3689/api/player';
> $library_url = 'http://192.168.0.3:3689/api/library/count';
> $player_response = file_get_contents($player_url);
> $library_response = file_get_contents($library_url);
> $response = [
>     'player' => json_decode($player_response, true),
>     'library' => json_decode($library_response, true),
> ];
> header('Content-Type: application/json');
> echo json_encode($response);
> ?>
> ```
> 
> Then you can query the php page in the custom api and will be able to use the data from both endpoints.

Hey it sounds like a practical solution. Could you please elaborate more for a php noob like me? E.g. where do you place the php page file and how to query the php page in the custom api? Thank you.

**Reply by joepool** [reply]
Very easy to setup, you just need a web server with php. Im using lighttpd but apache or similar would work too with a php addon if required. Assuming you're on a Debian based distro web files go in `/var/www/html/`. So for my example for an OwnTone widget -  `/var/www/html/owntone-api.php`
The php code above can be used as a template replacing player_url and library_url with the api endpoints you want to combine. You can add more than 2, make sure you also add them to the response. To add to your homepage, the your `services.yaml` would look something like this:
```
  - OwnTone:
      icon: owntone.svg
      href: http://192.168.0.3:3689
      server: docker
      container: OwnTone
      widget:
        type: customapi
        url: http://192.168.0.3/owntone-api.php
        refreshInterval: 100000
        method: GET
        mappings:
          - field:
              player: state
            label: State
          - field:
              library: tracks
            label: Tracks
```

happy to help if you need a hand setting it up

**Reply by pretubedongit** [reply]
> Very easy to setup, you just need a web server with php. Im using lighttpd but apache or similar would work too with a php addon if required. Assuming you're on a Debian based distro web files go in `/var/www/html/`. So for my example for an OwnTone widget - `/var/www/html/owntone-api.php` The php code above can be used as a template replacing player_url and library_url with the api endpoints you want to combine. You can add more than 2, make sure you also add them to the response. To add to your homepage, the your `services.yaml` would look something like this:
> 
> ```
>   - OwnTone:
>       icon: owntone.svg
>       href: http://192.168.0.3:3689
>       server: docker
>       container: OwnTone
>       widget:
>         type: customapi
>         url: http://192.168.0.3/owntone-api.php
>         refreshInterval: 100000
>         method: GET
>         mappings:
>           - field:
>               player: state
>             label: State
>           - field:
>               library: tracks
>             label: Tracks
> ```
> 
> happy to help if you need a hand setting it up

Wow that's helpful bro! I got what you meant. Planning to use an NGINX docker container as the php server and setup my Linkding custom api. I will try it on the weekend and update here.

**Comment by rebron1900** [comment]
I'm now using Cloudflare Worker to implement this function, and with AI to write the interface code, everything is very comfortable.

**Reply by buffaloexpatbill** [reply]
Middleware of some kind does look like the right answer here. It certainly is in the business world.

**Comment by OBoudreaux** [comment]
These are certainly functional workarounds but a native implementation would still be preferable!

**Comment by pretubedongit** [comment]
Guys, BTW do you know of any other alternatives like dashy or so, which supports multiple endpoint widgets?

**Reply by buffaloexpatbill** [reply]
As I mentioned previously, commercial products use middleware to accomplish this. This is a solution, not a workaround. In my humble opinion, it is not the best use of developer time to add a feature that commercial products don't include and for which an entire class of products already exists.

**Reply by Budlyte** [reply]
Good thing it isn't up to you. This is one of the highest requested items in the Feature Requests.

**Comment by kuzmoyev** [comment]
Would like to bump this request. And specifying separate endpoints (that are empty by default) with the base url would be great (and backward compatible):

```
widget:
  type: customapi
  url: http://custom.api.host.or.ip:port/api/v1/
  mappings:
    - field: 
      path:
         key 0
      endpoint: /endpoint1
      label: Field 1
    - field:
      endpoint: /endpoint2
      path:
         key 0
      format: number
      label: Field 2
```
