### DISCUSSION TITLE
[Feature Request] Support private Google Calendar links for iCal widget

### DISCUSSION THREAD

**Discussion by Encephala** [gethomepage/homepage#2410] [Feature Requests]
### Description

I saw the new iCal widget in v0.8.2 and wanted to try it out. While it works perfectly for a public Google Calendar iCal URL, it gives an "API Error Information" when using a private iCal URL.

I have my public URL set up to only show "Busy/Available" for privacy reasons, but would like to be able to use the private URL, which does show all information, for my homepage instance.

From inspecting the `.ics` files, it looks like it should be reasonably straightforward. It would be awesome if someone could figure this out!

**Comment by Nimuie** [comment]
I found this while I was troubleshooting why the private ical address isn't working for google cal. Is this feature request being considered? Google cal has a very broad exposure for public calendars so I would very much want to avoid having to turn that on

**Comment by shamoon** [comment]
I honestly don’t remember if I looked at this yet but perhaps the .ics is somehow invalid. Homepage uses a tool to parse the files, you’d be amazed (or maybe you wouldn’t) how often the generated ics files aren’t correct.

**Comment by shamoon** [comment]
Do you guys want to see if this works with the current `main` image?

(because it does for me)

**Comment by denispapec** [comment]
Make sure that when you visit that `.ics` URL in the browser: it starts downloading the calendar file and I't doesn't respond with a error like this in case of calendar permission issues:
```
404. That’s an error.

Feed Processing Error That’s all we know
``` 
Maybe we should handle that in the code :thinking:

**Comment by Encephala** [comment]
I tested it on main, and it didn't work; turns out my config was missing `name: ...` ([docs](https://gethomepage.dev/latest/widgets/services/calendar/)).

Adding that, it did work on main, tested on `v0.8.2` and it also works.

Old config:
```yaml
- Calendar:
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: monday
            view: agenda
            showTime: true
            integrations:
                - type: ical
                  url: ...
                  color: magenta
                  params:
                    showName: true
```

New config:
```yaml
- Calendar:
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: monday
            view: agenda
            showTime: true
            integrations:
                - type: ical
                  url: ...
                  name: Events
                  color: magenta
                  params:
                    showName: true
```

I guess the `name` tag is necesary for GCal's private ics files but not for public ones? I wanted to test this but if I now try to use the private URL, I get the 404 that @denispapec mentioned.
FWIW, homepage reports the error pretty clearly, I think a user should be able to figure out what's going on when they see this:
![image](https://github.com/gethomepage/homepage/assets/29434548/7e1b0d3c-eabb-4b25-9eb1-e0f2808c2124)
