### DISCUSSION TITLE
Remote Docker TLS connection not working

### DISCUSSION THREAD

**Discussion by geekifier** [gethomepage/homepage#2413] [Support] [answered]
No matter, what I do, I cannot get the remote docker connection (with TLS) to work. There are no errors anywhere, despite trying to enable debug logging.

Autodiscovery works fine for the local socket connection, but nothing shows up for the remote host.

I have the following `docker.yaml`:

```yaml
rpi2:
  host: docker.host.tld
  port: 2376
  tls:
    keyFile: /secrets/keyfile.key
    caFile: /secrets/cafile.pem
    certFile: /secrets/certfile.pem
vacuum2:
  socket: /var/run/docker.sock
```

I executed a shell into the Homepage container and verified that the certs are there under `/secrets/`. Those are also the same certs I am using with another piece of software, and they work fine. I am able to display the cert files in the container.

I am also able to ping the destination host from the container. There is no curl in the container, but I am able to connect via curl to the Docker API endpoints from the host.

I tried changing the FQDN of the docker host to IP address, but also can put anything in that field and there is no error being generated.

How can I troubleshoot this further?

There was a similar issue (I think) being reported here back in April: #1331.
