### DISCUSSION TITLE
Good source for service icons

### DISCUSSION THREAD

**Discussion by corticalstack** [gethomepage/homepage#2415] [General]
HI,

Wondering if there is a good source of icons for various services like Proxmox. I did try the following svg icons from the below, but couldn't get to work. As soon as I replaced with another .png variant, it loaded fine after restarting the container.
https://github.com/loganmarchione/homelab-svg-assets/tree/main/assets

**Comment by benphelps** [comment]
Homepage has baked in support for two sources that should cover everything, or near everything.

https://gethomepage.dev/v0.8.2/configs/services/#icons

**Reply by corticalstack** [reply]
@benphelps Thanks for that. I tried to use the baked-in icons, e.g. ref proxmox.png as below, and no icon shows. I presume we don't need an icon volume loaded in the docker, nor any download of icons, to use these prebaked ones?

```
- HCI:
    - Proxmox VE:
        icon: proxmox.png
        href: 192.168.1.3:8006
        description: Virtualization platform.
        ping: 192.168.1.3
        widget:
            type: proxmox
            url: 192.168.1.3:8006
            username: api@pam!homepage
            password: 
            fields: ["vms", "resources.cpu", "resources.mem"]
```
