### DISCUSSION TITLE
Disks other than root show API Error

### DISCUSSION THREAD

**Discussion by sottey** [gethomepage/homepage#2420] [Support] [answered]
I am sure I am doing something wrong, but regardless of how I attempt to display disks other than / they show API Error.

I have tried this:
```
- resources:
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    units: imperial # only used by cpu temp
    refresh: 3000 # optional, in ms
- resources:
    label: Root
    disk: /

- resources:
    label: 2t Internal
    disk: /media/2t_internal
```

I have also tried this:
```
- resources:
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    units: imperial # only used by cpu temp
    refresh: 3000 # optional, in ms
- resources:
    label: Storage 
    disk:
        - /
        - /media/2t_internal
```
But all I get is this:
![image](https://github.com/gethomepage/homepage/assets/8494620/441ae11f-144c-4d82-bf8d-47456b4ecf57)

These are mounts. One is an internal nvme ssd and the other is an external ssd. Both are mounted and RW.

What am I doing wrong?

Thanks
