### DISCUSSION TITLE
[Feature Request] Custom Labels in Default Widgets

### DISCUSSION THREAD

**Discussion by Budlyte** [gethomepage/homepage#2430] [Feature Requests]
### Description

- Support custom labels in defaults widgets 
EX: 
```
widget:
          type: plex
          fields: ["movies", "tv"]
          label: ["1", "2", "3", "4"]
```
or
```
widget:
          type: plex
          fields: ["movies", "tv"]
          label: ["3", "4"]
```
or
```
widget:
          type: plex
          fields: ["movies":"3", "tv":"4"]
```

### Other

Then all the "change the labels to what I want" requests can end.

**Comment by benphelps** [comment]
It would have to be something like this:

```yaml
widget:
    type: plex
    fields:
        movies: My Label
        albums: My Label
        streams: My Label
        tv: My Label
```

I think it's a pretty decent idea.
