### DISCUSSION TITLE
qBittorrentVpn

### DISCUSSION THREAD

**Discussion by aiernt** [gethomepage/homepage#2431] [Support]
how do I setup a widget for qBittorrentVpn. Using the widget information in the documentation I just get an api error in a red box. qbittorrent does show up and I can click it and it will open my instance, but the widget items won't show. I assume it's because this is bundled with the vpn?

![image](https://github.com/gethomepage/homepage/assets/99772746/3d5984f2-3a80-4738-bb57-902b2bb2215f)

**Comment by mgrimace** [comment]
I'm using qbit with vpn (Hotio image, wireguard conf0). Here's the services.yaml entry I use:

```yaml
    - qBittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
#        description: manage downloads
        server: my-docker
        container: qbittorrent        
        widget:
            type: qbittorrent
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
            username: {{HOMEPAGE_VAR_QB_USER}}
            password: {{HOMEPAGE_VAR_QB_PASS}}
```

Noting that I'm using secrets and have all my IPs, usernames, and passwords all defined in .secrets.env. You would want to make sure to customize to your own info. 

Nothing too special in the Qbit settings:

<img width="698" alt="Screen Shot 2023-12-06 at 6 42 01 PM" src="https://github.com/gethomepage/homepage/assets/55518507/a1a2adc6-5d43-44c0-984b-044310380e06">

**Reply by aiernt** [reply]
It's weird. I have the same setup in my services.yaml (with my own information) but I am getting that api error. I did change my port from 8080 to 8070 because it looked like sabnzbd was on 8080. I am using the binhex and not Hotio. My config screen looks the same as yours above, but I'm using a different ip range, but I have everything set identical other than that. 

If I open up the developer console I see a 404 error. When I copy and place that link in the browser I just see words on my screen that says "Not Found". Maybe you could go into the dev console (F12) and  compare your URL to mine to see if it's any different? In all the gets you should see one where in the file column it will show type=qbittorrent. 

![devconsole](https://github.com/gethomepage/homepage/assets/99772746/f9656e28-23d1-4e74-84ba-b5ba6ddd82df)

**Comment by Budlyte** [comment]
Not much help, maybe, but I prefer an iframe for Qb. 

![image](https://github.com/gethomepage/homepage/assets/4451365/bbfd1fca-b1dd-4960-a6f1-90d94a842ae9)

**Reply by mgrimace** [reply]
Cool, can you share how you set that up?

**Reply by aiernt** [reply]
yeah, if you could post how you set this up that would be awesome!

**Reply by Budlyte** [reply]
It's just the iFrame widget, with qb using the vuetorrent UI.

https://gethomepage.dev/v0.8.2/widgets/services/iframe/
https://github.com/WDaan/VueTorrent

```
- QBittorrent:
        icon: qbittorrent.png
        href: http://192.168.1.202:8080/#
        widget:
            type: iframe
            classes: h-60
            name: QBittorrent
            src: http://192.168.1.202:8080/#
```
