### DISCUSSION TITLE
[Feature Request] Tandoor

### DISCUSSION THREAD

**Discussion by teffalump** [gethomepage/homepage#2439] [Feature Requests] [answered]
### Description

I was wondering if anyone else is interested in a [Tandoor](https://tandoor.dev/) service widget? I have a working one to submit as a pull request if there is interest.

![widget](https://github.com/gethomepage/homepage/assets/90264/8e3c6a7c-b310-4ff8-be6f-f94351fb7768)

ADDENDUM: Currently, new service widgets require 10 up-votes per contributor guidelines.

**Comment by brhahlen** [comment]
Yes, that would be cool!

**Comment by Sn1p3r123** [comment]
Yes!

**Comment by schmitzCatz** [comment]
may be you can share your custom widget in the mean time? :-)

**Reply by teffalump** [reply]
Sorry about delay but I was waiting for 5 upvotes before the pull request given I believe that is one of the guidelines for new services. Should be able to see it in my fork in the feature/tandoor-widget branch if anyone wants it or has thoughts.

**Reply by schmitzCatz** [reply]
In the mean time, everybody who wants to have a quick solution utilizing [customapi widget](https://gethomepage.dev/latest/widgets/services/customapi/) can use this template.
## Template
``` yaml
     - Kitchen:
        icon: {$icon}
        href: {$url}
        siteMonitor:  {$url}
        widget:
            type: customapi
            url: http://{$url}/api/space/1/
            headers:
                Authorization: Bearer {$token}
            mappings:
                - field: name
                  label: Space
                  format: text
                - field: user_count
                  label: Users
                  format: number
                - field: recipe_count
                  label: Recipe
                  format: number 
```
## How to use
Edit your `service.yaml` and do the following:
- Create API-Token with `read` scope in tandoor
- Replace all three `{$url}` with your tandoor URL
- Replace {$icon} with your preferred icon 
- Replace `{$token}` with your API-Token
