### DISCUSSION TITLE
MAM API Error - HTTPS Not Supported

### DISCUSSION THREAD

**Discussion by Budlyte** [gethomepage/homepage#2445] [Support]
I have the MAM API call setup as below.

```
- My Anonymouse:
        widget:
            type: customapi
            url: http://www.myanonamouse.net/jsonLoad.php?pretty&snatch_summary
            username: [email]
            password: [Password]
            mappings:
                - field:
                    0:
                        seedbonus # needs to be YAML string or object
                  label: Points
                  format: text # optional - defaults to text
```

The webpage returns this:

```
{
    "uid": 123456,
    "username": "muh name",
    "seedbonus": 7571,
    "uploaded": "722.86 GiB",
    "downloaded": "55.91 GiB",
    "uploaded_bytes": 776163134189,
    "downloaded_bytes": 60034349134,
    "class": "VIP",
    "ratio": 12.9
}
```
But I'm getting this error. I don't think it actually has anything to do with the returned JSON, it seems to be getting stuck on even requesting the webpage.

```
[2023-12-08T18:12:13.585Z] error: <httpProxy> Error calling http://www.myanonamouse.net/jsonLoad.php...
[2023-12-08T18:12:13.586Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:462:24)
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:62:10)
      ... 3 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:335:12)
      at readableAddChunk (node:internal/streams/readable:308:9) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:358:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:284:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:459:10)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:62:10)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
```
