### DISCUSSION TITLE
Showing multiple servers on a single instance of Homepage

### DISCUSSION THREAD

**Discussion by sottey** [gethomepage/homepage#2446] [Support]
Hi all, thanks for reading...

I have two servers, and I love using the resource widget to see each server's status.

That said, installing Homepage on both of them, where bookmarks, services, settings, etc. are all the same means I have two sets of identical config files to maintain/update. I tried using symlinks to a shared folder, but that doesn't currently work.

What I would like is to be able to have the widget for server B show up in Homepage on Server A. I have tried using the iframe widget but I have not been able to get it to work.

Is there a way to display server B's resource widget on Server A? I would love to learn that Homepage has an API and I could just use the custom API widget to display the info, but it doesn't look like there is an API or a Homepage widget in Homepage.

Help?

**Comment by AlexFigas** [comment]
I'm looking forward to this.

**Comment by ThaMighty90** [comment]
you can install the glances container on both server and use glances as widgets instead of the resources widget. Works the same but with much more information.

![image](https://github.com/gethomepage/homepage/assets/30285364/446506b8-99d0-43ec-a153-6a45d3986ad5)

**Comment by AlexFigas** [comment]
@ThaMighty90 can you please provide that specific config? Thank you for your information, Now either I need to have a translucent box like yours or move the search bar to the center of the screen.

![image](https://github.com/gethomepage/homepage/assets/65889776/1b86960e-8655-4bac-9e6f-949d27312f80)

**Reply by Gecko-with-a-hat** [reply]
I actually want to display resources of server B on the resource widget of homepage running on server A. So basically I want what you did here, but only showing the resources of the external server. How did you get the resources of another server to show up there?

**Reply by ThaMighty90** [reply]
hey look at this post here https://github.com/gethomepage/homepage/discussions/2446#discussioncomment-8273690

you have to run glances on the server you want to monitor and then use the glances widget.

**Reply by Gecko-with-a-hat** [reply]
Thanks for the reply, I actually figured it out in the meantime. I was just a bit confused. 😄

**Comment by ThaMighty90** [comment]
EDIT2: @AlexFigas 

this is what i have in my widgets.yaml

```
- glances:
    url: IP1
    label: Alpha
    cpu: true
    mem: true
    cputemp: true # disabled by default
    uptime: true # disabled by default
    disk: /rootfs
    
- glances:
    url: IP2
    label: Beta
    cpu: true
    mem: true
    cputemp: true # disabled by default
    uptime: true # disabled by default
    disk: /rootfs
```

or do you mean my settings.yaml?

settings.yaml

```
theme: dark # or light
color: slate
headerStyle: boxedWidgets
language: de
hideVersion: true
useEqualHeights: true

background:
  image: https://images.wallpaperscraft.com/image/single/black_light_dark_73356_1920x1080.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
```

EDIT: You want to use  

`headerStyle: boxedWidgets`

in your settings.yaml
