### DISCUSSION TITLE
[Feature Request] Allow Bookmarks to be Configured for Multiple Tabs

### DISCUSSION THREAD

**Discussion by mzrimsek** [gethomepage/homepage#2447] [Feature Requests]
### Description

I love the tabs option and love that you can have a bookmarks group show up on just a single tab or on all the tabs. Would it be possible to allow a list of tabs?

Perhaps an additional configuration option that's mutually exclusive with the "tab" option called "tabs"
```yaml
...
- group
  - bookmark:
      tabs:
        - a
        - b
        - c
...
```

**Comment by GetOutOfMyBakery** [comment]
So this feature already exists, and it was introduced with the tabs, see the video clip on the PR:
- https://github.com/gethomepage/homepage/pull/1981

I was looking to the exact same thing that you've suggested, and I couldn't quite make sense of [the docs](https://gethomepage.dev/v0.8.0/configs/settings/#tabs).

This discussion thread really helped:
- https://github.com/gethomepage/homepage/discussions/2321

## TL;DR
`bookmarks.yaml`:
```yaml
- Documentation:
  - Homepage:
    - icon: homepage
      href: https://gethomepage.dev/latest/configs/
      description: Homepage documentation
```

`services.yaml`:
```yaml
- Dashboard:
    - Portainer:
        icon: portainer
        href: <Local Portainer URL>
```

In `settings.yaml`:
```yaml
layout

  # Display the Dashboard services on the First tab
    Dashboard:
      tab: First
      style: row
      columns: 3

  # Display the bookmark on the First tab
    Documentation:
      tab: first
```
