### DISCUSSION TITLE
[Feature Request] Config Variables

### DISCUSSION THREAD

**Discussion by modem7** [gethomepage/homepage#2452] [Feature Requests] [answered]
### Description

Allow for variables to be set in configs.

E.g.

```yaml
- Portainer:
  - HDA:
      href: http://hda:9000
      description: HDA
      icon: portainer
      siteMonitor: http://$HDA:9000
      widget:
        type: portainer
        env: 1
        url: http://portainer:9000
        key: key
```

### Other

Maybe within an env.yaml file or just in the compose file itself, allowing the config files to read system variables.
