### DISCUSSION TITLE
Widget with multiple API Endpoints

### DISCUSSION THREAD

**Discussion by cyberndj** [gethomepage/homepage#2475] [Support]
Howdy,
I'm setting up a custom-api widget on my NetBox service entry. I have it setup so where one node is pulled and displayed just fine. However, I would like to setup the widget to pull from different end points from the API.
Some of the endpoints are:
/api/dcim/cables
/api/dcim/devices
/api/dcim/locations
/api/dcim/racks
... and each of these endpoints have a "count" keypair that I would like to have displayed.

When I try below, no number shows up in the field.
```
            url: https://netbox-dev.url/api/dcim           
            mappings:
                - field: 
                     devices: count
                  label: Devices
```

My config that works with one endpoint:
```
- Documentation:
    - NetBox Dev:
        href: https://netbox-dev.url
        icon: netbox.png
        siteMonitor: https://netbox-dev.url
        widget:
            type: customapi
            url: https://netbox-dev.url/api/dcim/devices
            username: homepage
            password: homepagepassword
            mappings:
                - field:  count
                  label: Devices
```
Any suggestions you could give to allow multiple items from different endpionts would be amazing!

Thanks!
-Jake
