### DISCUSSION TITLE
[Feature Request]  User configurable max CPU temp for resources information widget

### DISCUSSION THREAD

**Discussion by cmerkle** [gethomepage/homepage#2478] [Feature Requests] [answered]
### Description

Currently, the cputemp bar in the resources information widget always appears full. I'm not sure where homepage is currently getting the maximum CPU temp from, but I propose making the max cputemp to be a user configurable option. I think the configuration in widgets.yaml should look something like this:

```yaml
- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: 
        max: 80
    units: metric 
```

This would make the cputemp widget much easier to read at a quick glance and make the bar below the cputemp actually useful, which it currently is not. 

![image](https://github.com/gethomepage/homepage/assets/33108196/e554164b-0eb6-46a9-bbb5-acc9a89c661f)
