### DISCUSSION TITLE
Openweathermap widget giving API error

### DISCUSSION THREAD

**Discussion by NanoBaker** [gethomepage/homepage#2506] [Support] [answered]
Hello, I have been trying to add the OpenWeatherMap widget but it will not display anything only giving a vague 'API error' and nothing on the logs.
![error](https://github.com/gethomepage/homepage/assets/62188715/61cf538b-371a-4ae7-afdd-fa7dbb55fe73)

From widgets.yaml:
```
- openweathermap:
    label: Home
    latitude: 38.98
    longitude: -76.15
    units: imperial
    provider: openweathermap
    apikey: [default api key]
    cache: 5
```
Trying to access it from the browser works and curling from the container gives me the correct data:
```
curl "https://api.openweathermap.org/data/2.5/weather?lat=38.98&lon=-76.15&appid=[key]&units=imperial&lang=en"
{"coord":{"lon":-76.15,"lat":38.98},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"base":"stations","main":{"temp":42.15,"feels_like":36.64,"temp_min":40.28,"temp_max":44.55,"pressure":1033,"humidity":65},"visibility":10000,"wind":{"speed":9.22,"deg":10},"clouds":{"all":40},"dt":1703173441,"sys":{"type":2,"id":2002502,"country":"US","sunrise":1703161185,"sunset":1703195122},"timezone":-18000,"id":4356634,"name":"Grasonville","cod":200
```
Any idea what is wrong here?
