### DISCUSSION TITLE
Doorbell camera video widget

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#2508] [Support]
Hello, is it possible to display a video feed in a widget? 

I have a Wyze Doorbell cam, and I use docker-wyze-bridge -> scrypted -> home assistant to get it into Homekit. That means AFAIK there's a few ways to catch the video, such as a direct RTSP feed (docker-wyze-bridge), homekit secure video (from homekit), or anything along the way. That being said, I have no idea if this is possible (e.g., via custom API, iFrame, etc.).

Any advice would be appreciated, thanks

**Comment by GetOutOfMyBakery** [comment]
This isn't something I currently have set up myself, but this looks like what you're after:
- https://github.com/gethomepage/homepage/pull/1784

https://gethomepage.dev/v0.8.3/widgets/services/mjpeg/
```yaml
widget:
  type: mjpeg
  stream: http://mjpeg.host.or.ip/webcam/stream
```

You _might_ need to restream in a supported protocol if RTSP doesn't work out of the box.

**Reply by mgrimace** [reply]
Thanks, that's promising! I tested it out with RTSP (and the other protocols available in docker-wyze-bridge), but unfortunatley none work out-of-the-box. I'll see if I can 'restream' it somehow.

**Reply by TheTaylorLee** [reply]
If you figure something out please share. Attempting to get it working with iframe or mjpeg right now.

**Reply by Byrnesdigital** [reply]
@TheTaylorLee @mgrimace I would think that it would be pretty simple with the [iFrame widget](https://gethomepage.dev/v0.8.3/widgets/services/iframe/#full-example). Just pop the RTSP url in there as the src and tweak the options according to your preferences. I don't know enough about those camera systems or their web interface.

If that doesn't work you could try restreaming it with VLC or FFMpeg. I don't personally have experience doing that but I imagine one could spin up a docker image, pull the feed and restream it via the server functionality built into both and point the Mjpeg widget to that.

**Reply by TheTaylorLee** [reply]
Thanks, unfortunately that does not work. Resolved to just using the Wyze bridge for now.

**Comment by angryviking** [comment]
I have been trying to do something like this as well.
I thought I could use the camera_proxy endpoint from Home Assistant in an iframe widget, but I am having problems getting it to work.
A couple of problems are that camera_proxy uses a different token from Home Assistants long lived token and that token only lasts 5 minutes.

The camera_proxy endpoint and token can be found in Developer tools > states in Home Assistant
![image](https://github.com/gethomepage/homepage/assets/28925820/b43dcc58-6f93-4a22-b3bb-9505271e0907)

Configuring my services.yaml like:
```
  - TestCamera:
      widget:
        type: iframe
        name: test
        src: <home_assistant.url>/api/camera_proxy/camera.garage_sub_lens_0?token=<camera_token_from_ha>
        referrerPolicy: same-origin # optional, no default
        refreshInterval: 2000 # optional, no default
```
I get `Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` in the browser console no matter what I put in `referrerPolicy` in the iframe widget.
