### DISCUSSION TITLE
homepage over https

### DISCUSSION THREAD

**Discussion by phazethru** [gethomepage/homepage#2519] [Support] [answered]
Hey all,

Is there a way to have homepage to use a certificate (valid, from letsencrypt) and serve https instead of http?  I couldn't find a configuration for it.

Thanks!

**Comment by benphelps** [comment, marked as answer]
Use a TLS termination proxy, something like [Caddy](https://caddyserver.com/) would make this very easy.

**Reply by phazethru** [reply]
I've never used that, but it seems easy enough.   Thanks!

**Reply by phazethru** [reply]
For anyone curious about how to do this, here's the simplest implementation I found.

Caddyfile should look like this:

```
   your.server.hostname:4000 {
           reverse_proxy :3000
           tls /opt/certs/certificate.cer /opt/certs/key.key
   }
```


docker compose looks like this:

```
    caddy:
        container_name: caddy
        image: caddy:latest
        network_mode: host
        restart: unless-stopped
        ports:
            - "4000:4000"
        volumes:
            - /path/to/your/Caddyfile:/etc/caddy/Caddyfile
            - /path/to/your/certificate.cer:/opt/certs/certificate.cer
            - /path/to/your/key.key:/opt/certs/key.key
```
