### DISCUSSION TITLE
[Feature Request] Service widget to view statistics for a blog powered by WordPress

### DISCUSSION THREAD

**Discussion by OGRLEAF** [gethomepage/homepage#2544] [Feature Requests]
### Description

A service widget to view statistics for a blog powered by WordPress, including the number of visitors and new comments. I believe the following API is useful for this purpose: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/highlights/"

**Comment by Michael1337** [comment]
I played around with the API a bit, but only got stuff like this working:
```
        widget:
          type: customapi
          url: https://wordpress.mydomain.com/wp-json/wp/v2/posts
          mappings:
          - field:
               0: date
            label: Latest Post
            format: date
```
If someone could write a neat WordPress plugin to make some basic statistics available through one URL, that would be great.
