### DISCUSSION TITLE
Is there any way to not store passwords in plain text in the yml?

### DISCUSSION THREAD

**Discussion by jcoulter** [gethomepage/homepage#2547] [General]
Is there any way to not store passwords in plain text in the yml?

**Comment by aeikenberry** [comment]
This worked for me: https://gethomepage.dev/latest/installation/docker/#using-environment-secrets

```
Using Environment Secrets

You can also include environment variables in your config files to protect sensitive information. Note:

Environment variables must start with HOMEPAGE_VAR_ or HOMEPAGE_FILE_
The value of env var HOMEPAGE_VAR_XXX will replace {{HOMEPAGE_VAR_XXX}} in any config
The value of env var HOMEPAGE_FILE_XXX must be a file path, the contents of which will be used to replace {{HOMEPAGE_FILE_XXX}} in any config
```

**Reply by Eschguy** [reply]
I have various variables defined in a .env file but it's not reading it for me. 

```
HOMEPAGE_VAR_NEXT_USER=TestUser
HOMEPAGE_VAR_NEXT_PASS=TestPass
```

Then in a service entry, I have
```
username={{HOMEPAGE_VAR_NEXT_USER}}
password={{HOMEPAGE_VAR_NEXT_PASS}}
```

It doesn't work, what am I missing?

**Reply by aeikenberry** [reply]
in your homepage compose service, make sure you're adding 
```
env_file:
  - .env
```
so it loads the .env vars into the running container not just when it renders the compose file?

or:
```
environment:
  - HOMEPAGE_VAR_NEXT_USER=$HOMEPAGE_VAR_NEXT_USER
  ...
```

**Reply by Eschguy** [reply]
> in your homepage compose service, make sure you're adding
> 
> ```
> env_file:
>   - .env
> ```
> 
> so it loads the .env vars into the running container not just when it renders the compose file?
> 

Well that was annoyingly easy and obvious. Thanks for the help.

**Reply by JGNi** [reply]
Homepage compose service?
Can you say a little more about that?

Where, what, how?

**Reply by aeikenberry** [reply]
Yeah, this is for a Docker installation: https://gethomepage.dev/latest/installation/docker/#using-environment-secrets

So if you have your homepage service setup in compose like the example in the docs:
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
 ```
 You should pass your environment variables in via  .env file:
 ```
 version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
 ```
 Or pass them in explicitly:
 ```
 version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_VAR_XXX=myvalue # or $MYVALUE (read from .env file)
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
 ```

**Reply by suckmyhardware** [reply]
Interesting. This does not work for me (tried with PiHole API Key). I've tried to place the .env file inside $HOME/docker/homepage and added the key entry {{HOMEPAGE_VAR_XXX}} to services.yaml. It just doesn't work. As soon as I enter the key directly into the config file, it works.

**Reply by suckmyhardware** [reply]
BTW: I am using Dockge for docker container management. The compose file looks like this:
`version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /path/to/container/config:/app/config #     Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID
      PGID: $PGID
networks: {}`

I've tried the following:

- add the HOMEPAGE_VAR_XXX to environment
- add the HOMEPAGE_VAR_XX to the .env file which dockge created
- add the HOMEPAGE_VAR_XXX to the .env file inside path/to/container/.env
- add the HOMEPAGE_VAR_XXX to the services.yaml

Nothing works. As soon as I enter the API key directly into the services.yaml file, it works. I suspect that docker doesn't find the .env fil.

**Reply by gitmotion** [reply]
the same thing is happening for me as well. i've tried docker-compose.yml file with .env file and with portainer but passwords and username variables don't seem to register? only variables for keys work for some reason

**Reply by aeikenberry** [reply]
If you can provide your full example maybe I could help figure it out. From what I can tell, maybe you're missing:
```
services:
  homepage:
    env_file:
       - .env
```
