### DISCUSSION TITLE
Unifi Container service widget fails unless widgets.yaml widget also enabled

### DISCUSSION THREAD

**Discussion by undaunt** [gethomepage/homepage#2569] [Support]
As the topic states, surprisingly, I can repeatedly reproduce and then resolve this issue for myself and I'm wondering if anyone else has seen it.

If I only have the services.yaml widget configured to point to my UDM SE, as below, I get a 403 error: `[2024-01-03T23:47:11.479Z] error: <unifiProxyHandler> HTTP 403 logging in to Unifi. Data: {"code":"AUTHENTICATION_FAILED","message":"Authentication failed","level":"debug"}`

services.yaml
```
  - Unifi Controller:
      href: https://unifi.domain.com
      description: Network Controller
      icon: unifi.png
      ping: https://unifi.domain.com
      widget:
        type: unifi
        url: https://unifi.domain.com
        user: homepage
        password: xxxxx
```

However, as soon as I also enable the widgets.yaml config as below, **both** of them begin to work. If I remove the widgets config and refresh the page, the services widget once again throws an error.

widgets.yaml
```
- unifi_console:
    url: https://unifi.domain.com
    username: homepage
    password: xxx
```
