### DISCUSSION TITLE
CustomAPI with Docker Service Discovery

### DISCUSSION THREAD

**Discussion by aeikenberry** [gethomepage/homepage#2574] [Support]
The docs suggest:
https://gethomepage.dev/latest/configs/docker/#automatic-service-discovery
```
labels:
  - homepage.group=Media
  - homepage.name=Emby
  - homepage.icon=emby.png
  - homepage.href=http://emby.home/
  - homepage.description=Media server
  - homepage.widget.type=customapi
  - homepage.widget.url=http://argus.service/api/v1/service/summary/emby
  - homepage.widget.field[0].label=Deployed Version
  - homepage.widget.field[0].field.status=deployed_version
  - homepage.widget.field[1].label=Latest Version
  - homepage.widget.field[1].field.status=latest_version
  ```

But when I try my version:
```
labels:
      - homepage.group=Downloaders
      - homepage.name=Kapowarr
      - homepage.href=http://kapowarr.loc.com
      - homepage.description=Comics management
      - homepage.widget.type=customapi
      - homepage.widget.url=http://kapowarr.loc.com/api/volumes/stats?api_key=$KAPOWARR_API_KEY
      - homepage.widget.field[0].label=Series
      - homepage.widget.field[0].field.result=volumes
```

I don't get any errors, but also no blocks. The console shows that the data is coming back correctly from the proxy.
![image](https://github.com/gethomepage/homepage/assets/599112/db05fa92-3561-47d8-82e1-38bdc7c6eb38)

Changing it to:
```
- homepage.widget.mappings.field[0]...
```

gives me an error: 
```
Something went wrong.
TypeError: d.slice is not a function
```

Wondering if someone has had success and what's the correct way to do it?

**Comment by Zelnes** [comment]
Hi,

I'm exactly in the same situation, I have no clue how to add a customApi result. There's no error and no block.
I've tried many things, searched a lot, but still no idea what to write.

For information, I'm using a swarm mode, don't know if it might be related to this issue.

And to add even more info, I'm trying to show some info for my Technitium container. This is the kind of label I have
```yaml
...
    deploy:
      labels:
        - homepage.group=Network
        - homepage.name=Technitium DNS
        - homepage.icon=https://mytechnitium/img/logo.png
        - homepage.href=https://mytechnitium
        - homepage.description=Handle DNS at Home
        - homepage.widget.type=customapi
        - homepage.widget.refreshInterval=10000
        - homepage.widget.url=http://mytechnitium/api/dashboard/stats/get?token=AVERYLONGTOKEN&type=LastDay
        - homepage.widget.field[0].label=Nb Queries
        - homepage.widget.field[0].format=number
        - homepage.widget.field[0].field.response.stats=totalQueries
```
