### DISCUSSION TITLE
Calendar showTime not using correct time zone

### DISCUSSION THREAD

**Discussion by pineconebatwolverine** [gethomepage/homepage#2575] [Support] [answered]
I am pulling in some ical urls for calandar and agenda views and using the showTime option. The times that are showing are not the correct time zone. I tried adding an option like timeZone: America/Los_Angeles but it does not seem to do anything. Here is what my config looks like:

```
- School Schedule:
  - School:
      widget:
        type: calendar
        view: agenda
        icon: mdi-diamond-stone-purple
        maxEvents: 4
        showTime: true
        previousDays: 0
        integrations:
          - type: ical
            url: https://xxxxxx
            name: School
            color: purple
```
