### DISCUSSION TITLE
Error on homepage nginx widget

### DISCUSSION THREAD

**Discussion by JGNi** [gethomepage/homepage#2581] [General]
Hi
I'm trying to see which features this could give me https://gethomepage.dev/v0.7.2/widgets/services/nginx-proxy-manager/
But keeps ending up with this error:
API Error: Unknown error
**URL: http://192.168.1.2:81/api/tokens
Raw Error:
{
    "errno": -113,
    "code": "EHOSTUNREACH",
    "syscall": "connect",
    "address": "192.168.1.2",
    "port": 81
}**
Any suggestions to what could be wrong?

**Comment by brypie** [comment]
I have this widget working fine - can you post your configuration for your one?
Looks like you may have the wrong url/IP address?

**Reply by JGNi** [reply]
- Nginx Proxy Manager:
        icon: nginx.png
        href: http://192.168.1.2:81
        description: Proxy
        widget:
            type: npm
            url: http://192.168.1.2
            username: email@domain.tld
            password: some_password
         
I use email and password as I use in http://192.168.1.2:81 to log in with.

**Comment by JGNi** [comment]
![image](https://github.com/gethomepage/homepage/assets/26222087/57a442bd-4ea6-410b-8b89-ffafaf6d4294)

**Reply by JGNi** [reply]
I've also tried with :81 in the end

**Comment by brypie** [comment]
```
- Nginx Proxy Manager:
        icon: nginx.png
        href: my_url (https)/  ## trainling slash
        ping: my_url (https)  ## no trailing slash
#        description: Reverse Proxy Manager
        server: local
        container: nginx-proxy-manager
        widget:
            type: npm
            url: my_url (https)  ## no trailing slash
            username: some_email@gmail.com
            password: some_password
```

That's my whole setup for Nginx Proxy Manager in Homepage
Don't know if you need https in the url (I do)

![image](https://github.com/gethomepage/homepage/assets/34678889/0e5c9f6e-df0e-43ea-8d96-4857c3aca16d)
