### DISCUSSION TITLE
Noob question about ical integration

### DISCUSSION THREAD

**Discussion by okietech** [gethomepage/homepage#2588] [Support]
I have the following in my services.yaml file.  The result is that it shows monthly instead of agenda, and it doesn't show any events.

Thanks!
Jason

```
- calendar:
    - agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 1000
          showTime: true
          integrations:
            - type: ical
              url: https://ics.calendarlabs.com/76/20b7c57c/US_Holidays.ics
              name: US Holidays

```

**Comment by shamoon** [comment]
That yaml is not correct. Please review https://gethomepage.dev/v0.8.4/widgets/services/calendar/

**Reply by okietech** [reply]
Thanks for the quick response, but I've looked at that link already and didn't find it very helpful.  Can you provide an example of how it should be?

**Reply by shamoon** [reply]
I think its the ical file, try https://www.thunderbird.net/media/caldata/autogen/United-States-Holidays.ics

**Reply by okietech** [reply]
Thanks again for the reply.

I tried that, and get the same result.  Attached is my result.
![2024-01-07_114829](https://github.com/gethomepage/homepage/assets/342470/727bbb46-4a1b-4506-86fe-80b939d12352)

It always show monthly view and doesn't show any events.

**Reply by shamoon** [reply]
Copy & pasting your exact snippet above and changing the URL yields:

<img width="645" alt="Screenshot 2024-01-07 at 10 23 44 AM" src="https://github.com/gethomepage/homepage/assets/4887959/67ee35fc-7250-41b6-8680-6c27ad4a5684">

The entire contents of the services.yaml file for this screenshot is:

```yaml
- calendar:
    - agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 1000
          showTime: true
          integrations:
            - type: ical
              url: https://www.thunderbird.net/media/caldata/autogen/United-States-Holidays.ics
              name: US Holidays
```
