### DISCUSSION TITLE
Help with iFrame creation, garage-door status page

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#2595] [Support] [answered]
Hello,

I'm trying to create a basic iFrame widget that displays whether my garage door is open, pulled from the new landing page for the homekit-ratGDO [github source](https://github.com/ratgdo/homekit-ratgdo). RatGDO is a hardware homekit device that was created due to Chamberlain's lockdown of the API that re-enables 'native' homekit for the garage.

<img width="813" alt="Screen Shot 2024-01-08 at 1 44 25 PM" src="https://github.com/gethomepage/homepage/assets/55518507/81921d4c-1cb4-4b8f-82a2-f3f13851c1ae">

I don't know the first thing about how to specify an iframe, nor how to specify that particular spot on the page. The source page is a local IP address for the ratGDO device, and here's some random developer views from within Safari for that spot.

<img width="1912" alt="Screen Shot 2024-01-08 at 1 46 26 PM" src="https://github.com/gethomepage/homepage/assets/55518507/83fd9e9e-eb32-4264-9588-9846ee218e7c">

Note: this could alternatively be accomplished by loading it into home assistant (HA) then using the relevant HA fields; however, I don't want my garage door tied to my home server, which I routinely break as I'm learning.

**Comment by mgrimace** [comment, marked as answer]
Ok, I created the widget using the `status.json` and customAPI widget, here it is:

```yaml
- Automation:
    - Garage Door:
        icon: https://avatars.githubusercontent.com/u/144837877?s=200&v=4
        href: http://{{HOMEPAGE_VAR_RATGDO_IP}}
        #description: my garage-door opener
        siteMonitor: http://{{HOMEPAGE_VAR_RATGDO_IP}}
        widget:
          type: customapi
          url: http://{{HOMEPAGE_VAR_RATGDO_IP}}/status.json
          mappings:
            - field: garageDoorState
              label: Garage Door
              format: text
            - field: garageLightOn
              label: Garage Light
              format: text
              remap:
                - value: false
                  to: Off
                - value: true
                  to: On
            - field: upTime
              label: Uptime
              format: number
              scale: 1/3600000
              suffix: hrs
```
