### DISCUSSION TITLE
[Feature Request] Hidden services/widgets

### DISCUSSION THREAD

**Discussion by smavridis** [gethomepage/homepage#2597] [Feature Requests] [answered]
### Description

I have a Calendar with a few integrations (*arr) as follows(services.yaml):

```
- Calendar:
   - Monthly:
       widget:
         type: calendar
         integrations:
           - type: sonarr
             service_group: Details
             service_name: Sonarr
           - type: radarr
             service_group: Details
             service_name: Radarr

 - Details:
   - Sonarr:
      widget:
        type: sonarr
        ...
        fields: []
   - Radarr:
      widget:
        type: radarr
        ...
        fields: []
```

The calendar correctly shows the events from these interrogations.

My issue though is that even though i have not included the 'Details' group in my layout, as i don't care about their output, the integrations appear at the end of the homepage.
I also set their fields option to [] in hopes of hiding them, but they still are visible as empty rectangles with just the title.

Is there a way to hide them from the front-end?

Potentially either:
 - As a per-service `hide` flag, or perhaps if the `fields` variable is empty `[]`?
 - Or as a per-group hide flag (or python style, if a group starts with underscores don't show it)?

Thanks for your work on this great project.

### Other

![screen](https://github.com/gethomepage/homepage/assets/55295153/a19d98b9-a36d-4770-bcb4-abdb16fa9638)

**Comment by sgrtye** [comment]
I have a similar issue since I have multiple services, and some don't include a widget at all, I just put the widget under other services so it effectively hides the widget. Not the most elegant way but it works for me.

**Comment by nicjay** [comment, marked as answer]
I'm currently using [custom CSS](https://gethomepage.dev/latest/configs/custom-css-js/) to achieve this. 

Give the services an id:
```yaml
- Sonarr:
    id: hide_me
    widget:
      type: sonarr
        ...
- Radarr:
    id: hide_me_too
    widget:
      type: radarr
        ...
```

Update **custom.css** referencing the ids. `display: none` is an easy approach.
```css
#hide_me, #hide_me_too {
  display: none;
}
```

**Reply by smavridis** [reply]
I went with this in the end, good enough.

**Comment by VFansss** [comment]
I was thinking about exactly this! I have a funny suggestion about the solution.

Use case: I have 2 instances of Homepage, one private and one public (exposed and secured through Cloudflare).

In my private homepage instance, I have all the services added (and is accessible only from LAN).

In the public one (accessible from internet) I have a subset of services used by my friends and myself. However, more services are actually exposed (**AND SECURED**) to the internet than the ones displayed through the public instance.

Would be good to use the same "public instance" to display both "friend compatible" services but also have something to also display, only for me, extra exposed services.

Solution? Tag the services/categories/bookmarks and display them only under certain condition e.g. key is passed through GET

```
- Sonarr:
    secret_key: 123
    widget:
      type: sonarr
        ...
- Radarr:
    widget:
      type: radarr
        ...
``` 

Under that way, calling "https://my-public-page:80" would display only "Radarr" but calling "https://my-public-page:80?secret_key=123" would display both services.

The cool things is that I could bookmark my "public homepage url but with secrets" and use a single public instance to display both public exposed and private exposed services/links.

Sure, this could be viewed as some kind of "security through obscurity" but actually isn't: exposed private services are protected from Cloudflare, or in general should be protected in other way so this is only a convenient thing
