### DISCUSSION TITLE
Simple Icons not shown

### DISCUSSION THREAD

**Discussion by zkvvoob** [gethomepage/homepage#2613] [Support] [answered]
Hello all,

I just found out about the option to use Simple Icons instead of locally stored png/svg files. So, I tried adding one for Portainer, to begin with, like this:

```yaml
- Portainer:
    href: https://192.168.1.100:9443/#!/2/docker/containers
    icon: si-13BEF9
    description: Docker management
    server: unraid
    container: portainer
```

but the icon did not show. I tried with and without the `#` sound that is automatically copied from https://simpleicons.org. I also tried restarting the Homepage docker container – without any luck.

Could someone tell me what I'm doing wrong, please?

Thanks!
