### DISCUSSION TITLE
how to find and edit services.yaml file on docker?

### DISCUSSION THREAD

**Discussion by BarisGURENC** [gethomepage/homepage#2614] [Support]
I've used portainer to create container. How can i find the services.yaml file and update it?
I'm not prof for container.  

I'd be glad if you explain the way step by step.

Thanks.

**Comment by A-Void-Me** [comment]
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 -- optional, your user id
      PGID: 1000 -- optional, your group id
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```

look at the volumes. under - /path/to/config:/app/config you saved those files.
