### DISCUSSION TITLE
Local and built-in icons not working

### DISCUSSION THREAD

**Discussion by sullydan** [gethomepage/homepage#2616] [General]
So I attempted to use the built-in icons and the google material design icons and nothing showed up on my dashboard. I saw the issue related to blocking the CDN so I decided to download the icons and bind mount them to the docker container at /app/public/icons. Here is my docker-compose
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      - LOG_LEVEL=debug
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /volume1/docker/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```
I am now referencing them at /icons/iconname.png but the dashboard still isn't showing icons or even leaving space where I would expect the icon to be.  See screenshot
![homepage](https://github.com/gethomepage/homepage/assets/20598672/1bd11e7a-0cdd-4698-a46c-8668b9ece713)

I added the debug log level to my docker-compose but everytime I access the homepage it writes 
```homepage    | [2024-01-12T15:57:14.400Z] debug: No containers were found with homepage labels.```

I double checked that the icons are mounted in the docker container and have the appropriate privileges. I even completely removed the container and rebuilt it but nothing has worked. I'm not sure what else to do. 
![homepage privs](https://github.com/gethomepage/homepage/assets/20598672/c73b9e5f-a2bc-4c26-9f4c-bfd6539f2552)

**Comment by A-Void-Me** [comment]
Can you restart your homepage docker? docker restart homepage

and can you show your services.yaml?

**Reply by sullydan** [reply]
Sure, I've even tried purging the image to no avail. I simplified my services.yaml just to see if that would fix it, but it has not. Please see below
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Applications:
  - Darts:
    icon: /icons/bullseye.png
    href: http://10.10.3.201:9090
```

**Reply by A-Void-Me** [reply]
i think your .yaml is wrong, you need 2 more spaces before the icon and href, try:


```
- Applications:
  - Darts:
      icon: /icons/bullseye.png
      href: http://10.10.3.201:9090
```
the other icons (mdi / built-in icons) probably work too ^^
