### DISCUSSION TITLE
[Feature Request] Display json fields from a local file to "Info Widgets" (widgets.yaml)

### DISCUSSION THREAD

**Discussion by beef-dead** [gethomepage/homepage#2622] [Feature Requests]
### Description

Hi,
Is it tpossible to add from Info Widgets the ability to display some fields from a local json file ?
Thx in advance

**Comment by shamoon** [comment]
I have no idea what this means

**Comment by beef-dead** [comment]
Ok, the idea is to do like Custom Api does, but instead of retrieving a json file through an API url, the url would be a file name.
For example, the widgets.yaml file (or services.yaml if it's not possible to add this functionality in Info Widget) would be :
```
widget:
  type: jsonfile
  url: /tmp/infos.json   # or filepath: /tmp/infos.json
  refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
  etc...
```
Features like "remap" and "mappings" would work like Custom Api widget (https://gethomepage.dev/latest/widgets/services/customapi/)

Hope it's more understandable now ;-)
