### DISCUSSION TITLE
[QUESTION] Getting Outlook iCal working.

### DISCUSSION THREAD

**Discussion by ziadhorat** [gethomepage/homepage#2626] [Support] [answered]
Hello, all my relevant conf is at the bottom, my iCal is showing way more events than there should be, and weeks apart. 

I went to outlook, and shared my calender with my personal email (I tried the full perms and only titles sharing perms in outlook). 

Then i put that URL (https://outlook.office365.com/owa/calendar/***/name.ics) into icscalendar.com to view it, it looked normal:
![image](https://github.com/gethomepage/homepage/assets/46789968/f179bf9a-4158-4b00-9a3a-867a310b957a)

I then followed the wiki and tried both monthly and agenda, and keep getting way more results that I see in Outlook and the Site. (TZ is wrong so everything is pushed around a couple hours) but its showing way too many meetings (some from early last week and such) [Red = iCal]:
![image](https://github.com/gethomepage/homepage/assets/46789968/eb37acd0-d632-438f-9b15-fcc16cc2f523)

`services.yml` :
```yaml
    - Calendar:
        widget:
            type: calendar
            showTime: true
            firstDayInWeek: monday
            integrations:
                - type: sonarr
                  ***
                - type: radarr
                  ***
                - type: ical
                  url: https://outlook.office365.com/owa/calendar/***@***/***/***/***.ics
                  name: Work
                  color: red
                  params:
                    showName: true
```
`settings.yml` :
```yaml
title: ***
favicon: ***
color: gray
headerStyle: clean
hideVersion: true
hideHeader: true
statusStyle: "dot"
fiveColumns: true
useEqualHeights: true
hideErrors: true

layout:
  5:
    header: false
```

Has anyone managed to make it integrate successfully? Im unsure if this is just cause im 2 hours ahead of GMT and looks like the iCal is in GMT/UCT?

Edit: I should mention, ALL the red is being pulled from outlook, but theres duplicates being generated only in homepage, and i NEVER have that many meetings in a day - I even went through and deleted my scheduled meeting and that then dissapeared from homepage.
And if i try use the .ics mentioned in this issue: https://github.com/gethomepage/homepage/discussions/2588, i get no results...
