### DISCUSSION TITLE
Synology Downloadstation widget is not working, while diskstation widget is working fine

### DISCUSSION THREAD

**Discussion by bobvmierlo** [gethomepage/homepage#2632] [Support]
### Description

I started configuring Homepage today and after getting the diskstation widget to work, I decided to add the downloadstation widget as well. I've tried every variation, but it always results in an API error.
When running the API endpoints manually in any API client (I used RapidAPI in VScode) everything works fine.

Also trying to get debug logging didn't work out. I installed using [proxmox-helper-scripts](https://tteck.github.io/Proxmox/). But when adding `HOMEPAGE_VAR_LOG_LEVEL=debug` to the .env file in the /config folder, nothing happens. Also tried `LOG_LEVEL=debug`, but that didn't work either.

### Steps to reproduce

1. Added configuration below
2. API for downloadstation is not working
3. Tried several things (see below)

### homepage version

v0.8.4

### Installation method

Other (please describe above)

### Configuration

I added the codelines (redacted here):

```yaml
- Storage:
    - Synology DS1821+:
        icon: synology-dsm.svg
        href: "https://synology.mydomain"
        description: Synology DSM
        widget:
            type: diskstation
            url: http://192.168.2.40:5000
            username: remote_stats
            password: verysecretpassword
    - Synology DS1821+:
        icon: synology-download-station.png
        href: "https://synology.mydomain"
        description: Synology DSM
        widget:
            type: downloadstation
            url: http://192.168.2.40:5000
            username: remote_stats
            password: verysecretpassword
```

### Container Logs

Nothing in homepage.log about downloadstation

### Browser Logs

GET http://192.168.2.33:3000/api/services/proxy?type=downloadstation&group=Storage&service=Synology+DS1821%2B&endpoint=list 403 (Forbidden)

### Troubleshooting

I created the user like stated in the diskstation docs and used the same user for downloadstation, without changing the rights in DSM.
Also tried the downloadstation port that i use (port 8000), that didn't work either.

When doing all the api calls from the code in the repo manually to port 5000. I get the results below (currently no active downloads).
First API call (I have DSM7, so version is 7 and path is entry.cgi):
http://192.168.2.40:5000/webapi/entry.cgi?api=SYNO.API.Auth&version=7&method=login&account=remote_stats&passwd=VERYSECRET&session=DownloadStation&format=cookie
```
{
  "data": {
    "account": "remote_stats",
    "device_id": "REMOVED",
    "ik_message": "",
    "is_portal_port": false,
    "sid": "REMOVED",
    "synotoken": "--------"
  },
  "success": true
}
```
Second API call:
http://192.168.2.40:5000/webapi/DownloadStation/task.cgi?api=SYNO.DownloadStation.Task&version=1&method=list&additional=transfer
`{"data":{"offset":0,"tasks":[],"total":0},"success":true}`

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
- LOG_LEVEL is an env var, doesn’t go anywhere in “/config”
-  services cannot have the same name although if they’re the same info you might get away with it

In general, no one else has reported this so not yet convinced it’s borked…

**Comment by bobvmierlo** [comment]
I managed to figure it out after running a new instance in a docker container instead of running from source and enabling the debug logging. If you use 2 Synology services at the same time, the 2nd one does not work. Maybe because they share the same initial handler script?

If I do this, the 2nd Synology entry (downloadstation) doesn't work and doesn't create any debug logs.:
```
- Storage:
    - Synology DS1821+:
        icon: synology-dsm.svg
        href: "https://synology.mydomain"
        description: Synology Diskstation
        widget:
            type: diskstation
            url: http://192.168.2.40:5000
            username: remote_stats
            password: REMOVED
    - Synology DS1821+:
        icon: synology-download-station.png
        href: "https://download.mydomain"
        description: Synology Downloadstation
        widget:
            type: downloadstation
            url: http://192.168.2.40:5000
            username: remote_stats
            password: REMOVED
```

However, when I do this (comment out the first entry). The downloadstation widget works perfectly fine.:
```
- Storage:
#    - Synology DS1821+:
#        icon: synology-dsm.svg
#        href: "https://synology.mydomain"
#        description: Synology Diskstation
#        widget:
#            type: diskstation
#            url: http://192.168.2.40:5000
#            username: remote_stats
#            password: REMOVED
    - Synology DS1821+:
        icon: synology-download-station.png
        href: "https://download.mydomain"
        description: Synology Downloadstation
        widget:
            type: downloadstation
            url: http://192.168.2.40:5000
            username: remote_stats
            password: REMOVED
```
