### DISCUSSION TITLE
Show docker health state

### DISCUSSION THREAD

**Discussion by OberfragGER** [gethomepage/homepage#2633] [Support]
Hi,

im a starter with docker, so please be patient.

I like homepage very much but now i stumble upon the feature with the docker integration. Im using portainer with various containern, like bookstack or Jdownloader2. I will use both as an example.
Im looking for something like this.
![image](https://github.com/gethomepage/homepage/assets/28652993/cbe65a19-3082-4673-a2ce-bc44640adb8d)

My portainer is installed on the host 'Turnkey-Portainer'. I used to install dockerproxy and also homepage this docker-compose:

```version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
    volumes:
      - /portainer/Homepage:/app/config # Make sure your local config directory exists
      - /portainer/Homepage/images:/app/public/images
      - /portainer/Homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
```

My docker.yaml

```my-docker:
  host: dockerproxy
  port: 2375
```

My services.yaml

``` 
   - Jdownloader2:
        icon: jdownloader.png
        href: http://192.168.178.113:5800/
        description: Docker Jdownloader
        server: local
        container: jdownloader2-jdownloader-2-1
        widget:
          type: jdownloader
          url: http://192.168.178.113:5800
          username: xxx
          password: xxx
          client: xxx

    - Bookstack:
        icon: bookstack.png
        href: http://192.168.178.113:6875
        description: Dokumentation
        server: Turnkey-Portainer
        container: bookstack
```

Jdownloader-container ist stopped. Bookstack is running but both are showming just this grey "unknown" bar.
![image](https://github.com/gethomepage/homepage/assets/28652993/e947cdba-6d9b-4f9e-b22b-c3dfd636b784)

How can i get this green "healthy" state?

**Comment by OberfragGER** [comment]
Finally... i got it.
docker.yaml
```
my-docker:
  host: dockerproxy
  port: 2375
```

services.yaml
```
    - Jdownloader2:
        icon: jdownloader.png
        href: http://192.168.178.113:5800/
        description: Docker Jdownloader
        server: my-docker
        container: jdownloader2
        widget:
          type: jdownloader
          url: http://192.168.178.113:5800
          username: xxx
          password: xxx
          client: xxx
```
![image](https://github.com/gethomepage/homepage/assets/28652993/5d68910a-db9b-4a62-a739-540004bc0b7d)
