### DISCUSSION TITLE
[Feature Request] Web pages Icon

### DISCUSSION THREAD

**Discussion by Xenod666** [gethomepage/homepage#2634] [Feature Requests]
### Description

Am curious if it's possible to add the website icon option when we just add a "youtube.com" link ... link work well but would like to see it's icon too. 

like

- youtube
     icon: www.html.of.the.icon
     href: https://www.youtube.com
     description: YT

**Comment by Lockszmith-GH** [comment]
What did you try?

`icon` is mentioned in the [documentation](https://gethomepage.dev/latest/configs/bookmarks/).

I just tried the following in my `bookmarks.yaml':

```yaml
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

    - YouTube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com

    - YouTube:
        - icon: youtube
          href: https://youtube.com

    - YouTube:
        - icon: https://www.youtube.com/s/desktop/7197d3dc/img/favicon_96x96.png
          href: https://youtube.com
```

and this is the result:
![image](https://github.com/gethomepage/homepage/assets/905716/6fceb70a-309d-4c8b-a2ac-f8933a178239)

For the URL of the icon, in FireFox I revied the page info and got the URL from the Media list.

Is this what you were asking for?
