### DISCUSSION TITLE
Synology and Watchtower service widgets all not working

### DISCUSSION THREAD

**Discussion by maikdiepenbroek** [gethomepage/homepage#2641] [Support]
Hi there, 

I recently discovered this amazing tool built on great tech GJ all! 

Unfortunately the two service widgets mentioned above seem to completely not work for me.

I've read through the FAQ, troubleshooting and asked the AI bot for help without avail.

I've set my log level to debug but for all of the services mentioned above i dont get any output whatsoever. Looking through the source code of each one it's suppose to work but it isn't

Can someone help me out with properly debugging or maybe helping me out with addressing what im doing wrong.

Synology
```
- Storage:
  - Synology:
    icon: synology.png
    href: ...
    widget:
      type: diskstation
      url: ...
      username: ...
      password: ...
      volume: ...
```

Watchtower
```
- Containers:
  - Watchtower:
    icon: watchtower.png
    href: ""
    server: localhost
    container: watchtower
    widget:
      type: watchtower
      url: http://watchtower:8080 (docker-compose exposed host name, reachable via curl/ping from within the homepage container)
      key: ...
```
