### DISCUSSION TITLE
Support: Adguard Widget control/stats error, but curl works

### DISCUSSION THREAD

**Discussion by desmondfuller** [gethomepage/homepage#2643] [Support]
New user to homepage (starting yesterday),  Quite nice, and was able to get 22 out of 23 services/widgets working without a hitch.  Adguard gives:

```
API Error: HTTP Error
URL: http://172.16.64.46/control/stats
```

The syntax I used:

```
- AdGuard:
        icon: adguard-home.png
        href: http://172.16.64.46:80/
        widget:
          type: adguard
          url: http://172.16.64.46
          username: {removed_username}
          password: {removed_password}
```

Followed the troubleshooting section and the syntax looks fine.  

curl command to the same server (w/ same credentials) worked fine.

**Comment by shamoon** [comment]
Did you run that curl from inside the homepage container?

**Reply by desmondfuller** [reply]
Yes, I did.  I tried it inside the Proxmox container and outside the container (iTerm / OSX).

**Reply by shamoon** [reply]
Is there more info in the logs/if you click the error?

**Reply by desmondfuller** [reply]
There is not.  There is only one error which is from me messing up the background settings in the home page.  

`[2024-01-16T15:46:10.417Z] error: undefined`

**Reply by A-Void-Me** [reply]
can you try:

`
- AdGuard:
        icon: adguard-home.png
        href: http://172.16.64.46:80/
        widget:
          type: adguard
          url: http://172.16.64.46:80
          username: {removed_username}
          password: {removed_password}
`

**Reply by desmondfuller** [reply]
Same API error

**Reply by A-Void-Me** [reply]
i tried a bit, i get the same error if i use the wrong username / password.

do you maybe have a # inside of them?

**Reply by desmondfuller** [reply]
It is the right password… 

It was “_PQ2!z2mTx4vraaoRPRALky3w_” and I changed to "_Apple1234_".  Neither worked.  I have changed the password again and that does not work.

**Reply by shamoon** [reply]
Yea not clear what the issue is, I did test it and worked fine:

```yaml
...
        - homepage.widget.type=adguard
        - homepage.widget.url=http://localhost
        - homepage.widget.username=admin
        - homepage.widget.password=password
```

```
curl -L -k -u 'admin:password' http://localhost/control/stats
{"time_units":"hours","top_queried_domains":[],"top_clients":[],"top_blocked_domains":[],"top_upstreams_responses":[],"top_upstreams_avg_time":[],"dns_queries":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"blocked_filtering":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"replaced_safebrowsing":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"replaced_parental":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"num_dns_queries":0,"num_blocked_filtering":0,"num_replaced_safebrowsing":0,"num_replaced_safesearch":0,"num_replaced_parental":0,"avg_processing_time":0}
```

<img width="711" alt="Screenshot 2024-01-16 at 2 37 27 PM" src="https://github.com/gethomepage/homepage/assets/4887959/f7e91250-db65-48a6-af29-9af1e90faaf6">

**Reply by desmondfuller** [reply]
Odd.  I set up a new Adguard instance on a Synology box and the same issue.

Curl works from the homepage container:

```
curl -L -k -u 'adguard:Apple1234' http://172.16.64.2:9080/control/stats
{"time_units":"hours","top_queried_domains":[],"top_clients":[],"top_blocked_domains":[],"top_upstreams_responses":[],"top_upstreams_avg_time":[],"dns_queries":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"blocked_filtering":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"replaced_safebrowsing":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"replaced_parental":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"num_dns_queries":0,"num_blocked_filtering":0,"num_replaced_safebrowsing":0,"num_replaced_safesearch":0,"num_replaced_parental":0,"avg_processing_time":0}

```
In homepage, services.yaml:

```
    - AdGuard:
        icon: adguard-home.png
        href: http://172.16.64.2:9080/
        widget:
          type: adguard
          url: http://172.16.64.2:9080
          username: adguard
          password: Apple1234
```

![CleanShot 2024-01-17 at 09 42 04](https://github.com/gethomepage/homepage/assets/7647860/4f0e55cf-5d90-4f0c-a966-1d396f6d61af)

**Reply by A-Void-Me** [reply]
Sorry, but shouldn't your curl give an error because you used adguard:Apple1234? and in your config its admin:Apple1234

**Reply by desmondfuller** [reply]
you are right... that was a typing mistake on my side.

**Comment by itsgiff** [comment]
I am getting the same API Error issue as @desmondfuller

**Comment by mjschrod** [comment]
Same "API Error" here, using Docker:
Adguard v0.107.45
Homepage [v0.8.8 (87d1ea4, Feb 13, 2024)]

I used several "easy" and impossible to misstype passwords. :)

Curl works and shows me a long output, when using the appropriate login/pass.

**Comment by srodriguezt** [comment]
Hi,
Same error here. But I have some homepage logs for the Adguard conneciton:

```
[2024-04-08T09:21:00.208Z] error: <httpProxy> Error calling http://10.10.10.2:8080/control/stats...
[2024-04-08T09:21:00.209Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 10.10.10.2:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '10.10.10.2',
    port: 8080
  }
]
```
Adguard Home: v0.107.46
Homepage [v0.8.10 (0af975b, Mar 24, 2024)](https://github.com/gethomepage/homepage/releases/tag/v0.8.10)

Curl output is correct:
```
curl http://10.10.10.2:8080/control/stats -u "srodriguez:xxxxxx"
{"time_units":"hours","top_queried_domains":[{"cloudsync-tw.synology.com":2897},{"0.es.pool.ntp.org":1554},{"1.es.pool.ntp.org":1478},{"2.es.pool.ntp.org":1418},{"ccp-lh.googleusercontent.com":1391},{"3.es.pool.ntp.org":1300},{"api.cloudflare.com":1136},{"4083-ipv4v6e.clump.dprodmgd105.aa-rt.sharepoint.com":630},{"b._dns-sd._udp.0.10.10.10.in-addr.arpa":609},{"clients3.google.com":602},{"www.gstatic.com":568},{"db._....
```
I try two different configs for my homepage and both with the same error. 
The homepage configs are:
```
    - Adguard Home:
        href: http://10.10.10.2:8080/login.html
        description: Adguard Home portal
        icon: adguard-home.png
        widget:
            type: adguard
            url: http://10.10.10.2:8080
            username: srodriguez
            password: xxxxxx
    -  Adguard testing:
        href: http://10.10.10.2:8080
        icon: mdi-shield
        #server: myServer
        container: adguard     
        widget:
            type: adguard
            fields: ["queries", "blocked", "filtered", "latency"]
            url: http://10.10.10.2:8080/control/stats
            username: srodriguez
            password: xxxxxx
```
Any idea what is the problem??
