### DISCUSSION TITLE
[Feature Request] href to port

### DISCUSSION THREAD

**Discussion by klubi** [gethomepage/homepage#2646] [Feature Requests]
### Description

I'm running homepage on a Raspberry Pi.
It's accessible either via pi.local, RPi's IP or via tailscale host/IP.
Accessing homepage from those addresses makes it tricky to set `href` for services.
While services that are exposed via nginx, on their dedicated path are easy to configure:
```yaml
- Management:
    - Portainer:
        icon: portainer
        href: /portainer
        description: What runs in docker
        siteMonitor: http://portainer:9000
```
things get a bit more complicated with services that can't be setup that way
```yaml
- Dev:
    - Influx:
        icon: influxdb
        href: http://pi.local:8086
        siteMonitor: http://influxdb:8086
        server: my-docker
        container: influxdb
```
I wasn't able to make `href` work for influx, and not be bound to specific address/IP.
Regardless of what I come up with I always end up at `<address_used_to_open_homepage>/:8086`.

Tried:
```
href: 8086
href: '8086'
href: ':8086'
href: $:8086
href: $host:8086
href: '$host:8086'
href: http://::8086
```
