### DISCUSSION TITLE
widget help for unifi UDM se

### DISCUSSION THREAD

**Discussion by evilfootware** [gethomepage/homepage#2654] [Support]
Hi, I've got everything my homepage running spot-on, but I can't get the unfi widget to connect to my UDM se controller.  Keeps giving me the api error. This is the code

```
- UniFi:
        icon: unifi.png
        href: http://192.168.10.1 #My UDM se internal access IP
        description: Unifi Router and firewall
        widget:
          type: unifi
          url: http://192.168.10.1 #My UDM se internal access IP
          username:  userid # created a super admin on the UDM
          password: password #created a super admin password here
```
Can anyone point me into the right direction to where I'm going wrong? Thanks

**Comment by recipriversexcluson** [comment]
I have the same issue currently. The FAQ says to rebuild the container if having API issues, and I've tried re-creating in Portainer which hasn't worked yet.

**Reply by evilfootware** [reply]
Hi, thanks for the reply. Finally got it working. I'm not running a container, getting the info directly from the UDMse machine itself. My issue was I did not add the *.01 to the IP address, but just *.1 Which is why it did not work. School boy error. This is the code I used. 

```
- Unifi Controller:
        icon: unifi.png
        href: https://192.168.10.01
        description: wifi controller
        ping: https://192.168.10.01
        container: unifi-controller
        widget:
            type: unifi
            url: https://192.168.10.01
            username: userid
            password: password for above user
```
