### DISCUSSION TITLE
Portainer environment variables not replaced with secrets

### DISCUSSION THREAD

**Discussion by nkamenar** [gethomepage/homepage#2667] [Support] [answered]
I have a widget configured as shown below and I have created an environment variable via the Portainer GUI for HOMEPAGE_VAR_PIHOLE_API_KEY but the value fails to load and I get the "TypeError: Cannot read properties of undefined (reading 'toPrecision')" error message in the widget. Is there a way to recognize the environment variables set in Portainer?

```
- DNS:
    - Pi-Hole:
        icon: pi-hole.svg
        href: ""
        widget:
            type: pihole
            url: "https://pihole.domain.com"
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
```

**Comment by A-Void-Me** [comment]
did you add the env_file in your homepage compose service? and i dont think you need the "".

```
env_file:
  - .env
  
or

   environment:
     - HOMEPAGE_VAR_PIHOLE_API_KEY=XXX
```

**Reply by nkamenar** [reply]
I did not set the env_file and I am not sure what to set it to. Setting it to just .env as you show results in the container failing to run because it can't fine the file. When adding Environment variables through the Portainer gui I  am not sure where they actually go.

**Reply by A-Void-Me** [reply]
can you share your compose file? or whatever you set up in portainer?

**Reply by nkamenar** [reply]
![image](https://github.com/gethomepage/homepage/assets/8999291/18199e63-3fe5-4e6f-9cc7-6f573bb9c221)

**Reply by A-Void-Me** [reply, marked as answer]
okay can you add this

```
env_file:
  - stack.env
```
like
```
version: "3.3"
services:
 homepage:
   image: ghcr.io/gethomepage/homepage:latest
   container_name: homepage
   env_file:
     - stack.env
   ports:
     - 3000:3000
   volumes:
     - /path/to/config:/app/config
```
