### DISCUSSION TITLE
Qbittorrent question

### DISCUSSION THREAD

**Discussion by fliberdygibits** [gethomepage/homepage#267] [Support]
I'm getting an API error from the qbittorrent widget and I am curious if it's something to do with the fact I have it set to bypass auth on local network?  I've tried it with the password space empty in services.yaml and with the line completely removed.

    - Qbittorrent:
        icon: qbittorrent.png
        href: http://192.168.1.156:8080
        description: Torrent client
        widget:
          type: qbittorrent
          url: http://192.168.1.156:8080/
          username: username

**Comment by C8opmBM** [comment]
No, it's not related to bypassing auth on local.

Remove the slash at the end of you url
`url: http://192.168.1.156:8080`

And also put both your user/pass fields.

```
        widget:
          type: qbittorrent
          url: http://192.168.1.156:8080
          username: user
          password: passs!
```
