### DISCUSSION TITLE
Plex integration won't work

### DISCUSSION THREAD

**Discussion by nkamenar** [gethomepage/homepage#2670] [Support]
I have plex media server running on my personal PC and I am trying to set it up in homepage but no matter what I have tried I am getting:
API Error Information
API Error: Unexpected token 'I', "Internal S"... is not valid JSON

Configuration:
```
- Media:
    - Plex:
        icon: plex.svg
        href: "http://192.168.1.46:32400"
        description: media server
        widget:
            type: plex
            url: "http://192.168.1.46:32400"
            key: "{{HOMEPAGE_VAR_PLEX_API_KEY}}"
```
I have verified my key is correct and even tried pasting it directly instead of using the variable but it makes no difference and I get the same error. Am I missing something here or is this plugin broken? I tried doing a search but didn't see anything similar.
