### DISCUSSION TITLE
[Feature Request] Adding Tokens to the GameDig Widget

### DISCUSSION THREAD

**Discussion by frunkAF** [gethomepage/homepage#2679] [Feature Requests]
### Description

I'm trying to add a GameDig widget on my homepage to monitor my Terraria server.

The exmaple on gethomepage.dev states to use the following structure...

widget:
    type: gamedig
    serverType: csgo # see https://github.com/gamedig/node-gamedig#games-list
    url: udp://server.host.or.ip:port

I went to the GameDig github url to pull up information for my Terraria server specifically. It looks like the latest version says the type is 'terrariatshosck' but this didn't work. I found that I needed to set the type to either 'terraria' or 'tshock' to work as Homepage is using version 4.3.1

    - Terraria:
        icon: si-steam-#FFFFFF
        description: My Terraria Server
        widget:
          type: gamedig
          serverType: terraria
          url: http://172.16.0.230:7878
          token: KYJmo3GP6T69iJJ4T3TsG5q4ar79Aup2

The GameDig GAMES_LIST.md states that I need to create a REST user token and pass it to the runner. I verified that this token is working via a web browser query but I get 401 unauthorized errors in homepage's log. 

I'm guessing that homepage is not reading my **token:** and passing it to the runner.

If there isn't a way to enable this already, can we have this feature?

**Comment by CosminPerRam** [comment]
Note that we could also need other fields to be passed on for certain games (or in general for the query), so being able to do something like this
```
- Terraria: # just as an example
    icon: si-steam-#FFFFFF
    description: My Terraria Server
    widget:
      type: gamedig
      serverType: terraria
      url: http://172.16.0.230:7878
      gamedigArgs: # free form object
        token: KYJmo3GP6T69iJJ4T3TsG5q4ar79Aup2
        socketTimeout: 4000
        maxAttempts: 8
```
would be great as it ensures that we can pass any options to gamedig as they would be needed/added.

**Reply by Kaiede** [reply]
I was actually poking around with adding username/password support for Palworld as I've recently started using homepage for my local network, but I like your approach better as it means making this change once, and then being able to focus more on making sure gamedig stays up to date.

```
- Terraria: 
    icon: si-steam-#FFFFFF
    description: My Terraria Server
    widget:
      type: gamedig
      serverType: terraria
      url: http://172.16.0.230:7878
      # Anything not 'type', 'serverType', 'url' or 'fields' is assumed to be for gamedig and passed in directly
      token: KYJmo3GP6T69iJJ4T3TsG5q4ar79Aup2
      socketTimeout: 4000
      maxAttempts: 8

- Palworld:
    description: Best Pals
    widget:
        type: gamedig
        serverType: palworld
        url: http://172.16.0.230:8212
        # Again, anything not used for the widget is assumed to be for gamedig.
        username: admin
        password: myterribleinsecurepassword
```

This has the advantage that the arguments for gamedig follow the same pattern of other widgets. I've done the work to enable this locally (and update Gamedig to 5.0.0 at the same time to support newer games which is another request), and it checks out. At this point we just need the votes.

https://github.com/gethomepage/homepage/compare/main...Kaiede:homepage:gamedig-update
