### DISCUSSION TITLE
[Feature Request] Service status indicator "RUNNING" (like for docker), but sourced from uptime-kuma, UptimeRobot etc

### DISCUSSION THREAD

**Discussion by systemofapwne** [gethomepage/homepage#2681] [Feature Requests]
### Description

When using docker, one can add a state label to a service, that shows, if a container is running or not.
![image](https://github.com/gethomepage/homepage/assets/30482165/cb09a49f-9042-41a2-886c-0a481a388b4a)
While the status indicator serves well for monolithic services based on only one container (or via ping: server), there is no solution for a group of multiple containers (or even servers), that work together as a single service (e.g.: nextcloud, mariadb and redis for a 'nextcloud service' or multiple samba active directory domain controllers).

It would be quite nice to have a "RUNNING" indicator based on solutions like uptime-kuma or UptimeRobot (in contrast to their widget inplementation), that only adds this "RUNNING" tag to the service.

A possible implementation could work like this:
```yml
# services.yaml example
- Network:
    - DNS:
        href: https://dns.domain.tld
        description: DNS & piHole
        uptime: 
          - provider: my-uptime-kuma
          - service: dns   # Translates to the 'slug' similar to the uptimekuma widget or 'container' for docker
        widget:
          type: pihole
          url: http://pihole.domain.tld
          key: <<<<<<<>>>>>>>
```
A corresponding `uptime.yaml` configures the upstream uptime services.
```yml
# uptime.yaml example
my-uptime-kuma:
  type: uptimekuma
  url: http://uptimekuma.host.or.ip:port

my-uptime-robot:
  type: uptimerobot
  url: https://api.uptimerobot.com
  key: uptimerobotapitoken

# NOTE: I just added this example down here as it would look like in docker.yaml. It would be absolutely fine to keep docker.yaml/kubernbernetes.yaml dedicated files. But the proposed 'uptime' monitor plugin then should also source from those two files.
my-remote-docker
  type: docker
  host: 192.168.0.101
  port: 275

my-local-docker
  type: docker
  socket: /var/run/docker.sock
```

Note: I am aware about the uptime-kuma & UptimeRobot widgets. While they both offer valuable status information via a widget, they are quite bloated (stretch vertical space). 
![image](https://github.com/gethomepage/homepage/assets/30482165/1313667a-7bcb-4e17-926c-4c5d403423c5)
Further more, there seems to be a limit of only having one widget per service (correct me, if I'm wrong), so if I want to have uptime data & dedicated widget data (like for pihole: a statistics of blocked/allowed), this wont work
