### DISCUSSION TITLE
Incorrect kubernetes labelSelector

### DISCUSSION THREAD

**Discussion by max06** [gethomepage/homepage#2701] [Support]
### Description

On page load the log shows a failed request for `/api/kubernetes/status/dummyns/dummy-homepage`

```jsonc
// 20240120001410
// http://127.0.0.1:3000/api/kubernetes/status/dummyns/dummy-homepage?

{
  "error": "no pods found with namespace=dummyns and labelSelector=app.kubernetes.io/name=dummy-homepage"
}
```

The app is running in kubernetes, deployed via helm with release-name `dummy` in namespace `dummyns`. The app is still called `homepage`. Or rephrased: There's no single resource with label `app.kubernetes.io/name=dummy-homepage`.

I found 2 pages in this repo where the label selector is generated. Sadly I don't speak go, I'm unable to fix it by myself.

Changing the url to `.../dummyns/homepage` works.

### Steps to reproduce

n/a

### homepage version

v0.8.4

### Installation method

Other (please describe above)

### Configuration

```yaml
widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  kubernetes.yaml: |
    mode: cluster
```

### Container Logs

none

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
