### DISCUSSION TITLE
Support Tdarr widget with api key.

### DISCUSSION THREAD

**Discussion by AbdullahDahmash** [gethomepage/homepage#2705] [Feature Requests] [answered]
### Description

Hi

tdar widget does not work with api key.

You can enable tdar auth as described here https://github.com/HaveAGitGat/Tdarr/issues/297#issuecomment-1866494484

### Steps to reproduce

1- Use tdar image `docker.io/haveagitgat/tdarr_acc:dev_2.18.01_2023_12_21T15_42_37z`
2- Enter local user credentials. Go to tools > API key > generate a new one
3- Add key attribute to tdar widget
4- It shows API error on the home page

### homepage version

 v0.8.4

### Installation method

Docker

### Configuration

```yaml
- Tdarr:
      title: tdarr
      href: http://tdarr.host.or.ip
      description: Transcoding System
      server: my-docker
      container: tdarr
      widget:
        type: tdarr
        url: http://tdarr.host.or.ip
        key: apikeyapikeyapikeyapikeyapikey
```

### Container Logs

```
[2024-01-20T06:04:13.129Z] error: <tdarrProxyHandler> Error getting data from Tdarr: 403.  Data: {"status":403,"message":"No auth token or API key provided"}
[2024-01-20T06:04:14.289Z] error: <tdarrProxyHandler> Error getting data from Tdarr: 403.  Data: {"status":403,"message":"No auth token or API key provided"}
```

### Troubleshooting

```bash
docker exec homepage ping tdarr

PING tdarr (172.19.0.12): 56 data bytes
64 bytes from 172.19.0.12: seq=0 ttl=64 time=0.173 ms
64 bytes from 172.19.0.12: seq=1 ttl=64 time=0.123 ms
64 bytes from 172.19.0.12: seq=2 ttl=64 time=0.151 ms
64 bytes from 172.19.0.12: seq=3 ttl=64 time=0.144 ms
64 bytes from 172.19.0.12: seq=4 ttl=64 time=0.160 ms
```
```bash
docker exec homepage curl -L -k https://tdarr.host.or.ip/api/v2/cruddb

{"status":403,"message":"No auth token or API key provided"}
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by glime-ai** [comment]
Based on the context provided, it seems that the Tdarr widget configuration does not currently support the `key` attribute directly in the widget configuration for authentication. The error logs indicate that the Tdarr service is expecting an auth token or API key, but it is not being provided in the correct manner, resulting in a 403 error.

The Tdarr documentation provided in the context does not mention the use of an API key, and the allowed fields are only `[\"queue\", \"processed\", \"errored\", \"saved\"]`. This suggests that the widget configuration should not include the `key` attribute as it is not recognized.

However, you mentioned a GitHub issue comment that suggests enabling Tdarr auth and generating an API key. If Tdarr has been updated to require an API key for authentication, and this is not yet reflected in the Homepage documentation, you may need to update the widget configuration to include the API key in the correct format that Tdarr expects.

Since the Homepage documentation does not provide details on how to include the API key in the widget configuration, you may need to refer to the Tdarr documentation or the GitHub issue you mentioned for guidance on the correct configuration format.

If you have followed the Tdarr documentation for generating and using the API key and are still encountering issues, it would be advisable to reach out to the Homepage support with the details of the steps you have taken, including the Tdarr version you are using, the API key generation process, and the exact configuration you have set up. They may be able to provide more specific guidance or update the Homepage documentation to reflect any changes in Tdarr's authentication process.

For now, please ensure that the Tdarr service is correctly configured to use API keys and that the Homepage widget configuration is updated accordingly. If the issue persists, please provide the exact steps and configurations you have used so that further assistance can be provided.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by sym0nd0** [comment]
Drop the `key` and just use: 
```
    - Tdarr:
        icon: tdarr.png
        href: http://ip.or.domain
        description: Transcoder
        server: my-docker
        container: tdarr
        widget:
          type: tdarr
          url: http://ip.or.domain
```

This works for my instance.
