### DISCUSSION TITLE
[Feature Request] configuration in the browser

### DISCUSSION THREAD

**Discussion by aliuq** [gethomepage/homepage#2714] [Feature Requests]
### Description

Sometimes I found a website, I want to add to my homepage, may I complete this on the broswer?

**Comment by glime-ai** [comment]
Based on the context provided, it seems you are asking if you can add a website to your Homepage dashboard directly from the browser. If you are referring to the Homepage application described in the context, then yes, you can add custom service and web bookmarks to your Homepage. This can be done by editing the configuration files, which can be accessed if you are running Homepage on your local machine or server.

To add a custom link to the Homepage, you would typically edit the configuration files such as `widgets.yaml` or similar, depending on how you have set up your Homepage instance. If you are using Docker, you might also be able to add services via Docker label discovery.

However, if you are looking for a browser extension or a direct browser interface that allows you to add websites to your Homepage without manually editing configuration files, the provided context does not mention such a feature. You would need to follow the standard procedure for adding bookmarks or services as described in the documentation.

For detailed instructions on how to add custom service bookmarks, you should refer to the documentation and guides available on the official Homepage website or the GitHub repository.

If you need further assistance or clarification on how to add a website to your Homepage, please provide more details about your setup or the specific steps you are looking for.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by macpo** [comment]
There is a possibility using code-server to configure homepage in the browser. Here is an example:
```
version: '3.9'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config
      - /path/to/icons:/app/public/icons
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - 8444:8443
    volumes:
      - /path/to/code-server-config:/config
      - /path/to/config:/config/homepage
      - /path/to/icons:/config/icons
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
```
