### DISCUSSION TITLE
Calendar shows finished event.

### DISCUSSION THREAD

**Discussion by sasagar** [gethomepage/homepage#2719] [Support]
### Description

When I add iCal data from Google Calendar, the old schadule come to be shown and does not end. Whichever monthly or agenda.

### Steps to reproduce

1. Add Calender service widget
2. In yaml, add iCal private url of Google Calendar.
3. The old data shown. (even few years ago.)

### homepage version

v0.8.6

### Installation method

Docker

### Configuration

```yaml
- Agenda:
        icon: <some_icon_url>
        href: <some_url>
        description: <some_service_name>
        widget:
          type: calendar
          view: agenda
          maxEvents: 15 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          previousDays: 0 # optional - shows events since three days ago - defaults to 0
          integrations: # same as in Monthly view example
            - type: ical # Show calendar events from another service
              url: https://calendar.google.com/calendar/ical/<some_path>/basic.ics # URL with calendar events
              name: <SOMENAME> # required - name for these calendar events
              color: blue # optional - defaults to pre-defined color for the service (zinc for ical)
              params: # optional - additional params for the service
                showName: true # optional - show name before event title in event line - defaults to false
```
```


### Container Logs

(none)

### Browser Logs

(none)

### Troubleshooting

### PING

```
PING calendar.google.com (172.217.161.206): 56 data bytes
64 bytes from 172.217.161.206: seq=0 ttl=112 time=14.439 ms
64 bytes from 172.217.161.206: seq=1 ttl=112 time=14.470 ms
64 bytes from 172.217.161.206: seq=2 ttl=112 time=14.299 ms
64 bytes from 172.217.161.206: seq=3 ttl=112 time=14.846 ms
64 bytes from 172.217.161.206: seq=4 ttl=112 time=14.568 ms
64 bytes from 172.217.161.206: seq=5 ttl=112 time=14.724 ms
64 bytes from 172.217.161.206: seq=6 ttl=112 time=14.710 ms
64 bytes from 172.217.161.206: seq=7 ttl=112 time=14.450 ms
64 bytes from 172.217.161.206: seq=8 ttl=112 time=14.359 ms
64 bytes from 172.217.161.206: seq=9 ttl=112 time=14.196 ms
64 bytes from 172.217.161.206: seq=10 ttl=112 time=15.059 ms
```

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
