### DISCUSSION TITLE
[Feature Request] Add VPN check for Synology Downloadstation (or DSM)

### DISCUSSION THREAD

**Discussion by bobvmierlo** [gethomepage/homepage#2722] [Feature Requests]
### Description

Add the VPN connection status to the Downloadstation widget.
The status could be retrieved with the URL below, after authenticating:
http://HOST:PORT/webapi/entry.cgi?api=SYNO.Core.Network.Router.Gateway.List&version=1&method=get&iptype=ipv4&type=wan

This returns a JSON response like this one below, where the class 'vpn-client' can be seen as the fact that the NAS is behind a VPN as a client. If this connection is not working, this config entry (class: vpn-client) is completely absent.
```JSON
{
  "data": {
    "configs": [
      {
        "class": "vpn-client",
        "dns": "103.86.96.100",
        "gateway": "10.8.0.1",
        "ifname": "tun0",
        "priority": 0,
        "slave": false
      },
      {
        "class": "ethernet",
        "dns": "8.8.8.8",
        "gateway": "192.168.2.254",
        "ifname": "ovs_bond0",
        "priority": 1,
        "slave": false
      }
    ]
  },
  "success": true
}
```

Currently I added this with the custom api entry below. But this stops working after the auth cookie expires.:
```YAML
    - Synology VPN:
        icon: synology-download-station.png
        href: "https://synology.example.com"
        description: Synology Connection Status
        widget:
            type: customapi
            url: http://HOST:PORT/webapi/entry.cgi?api=SYNO.Core.Network.Router.Gateway.List&version=1&method=get&iptype=ipv4&type=wan
            method: GET
            mappings:
              - field:
                  data:
                    configs:
                      0: class
                label: Connection 1
                remap:
                  - value: vpn-client
                    to: VPN connected
                  - value: ethernet
                    to: Ethernet connection up
                  - any: true
                    to: VPN not connected
              - field:
                  data:
                    configs:
                      1: class
                label: Connection 2
                remap:
                  - value: vpn-client
                    to: VPN connected
                  - value: ethernet
                    to: Ethernet connection up
                  - any: true
                    to: VPN not connected
```
