### DISCUSSION TITLE
Ping doesn't appear to show when something is down

### DISCUSSION THREAD

**Discussion by buddwm** [gethomepage/homepage#2725] [Support] [answered]
I have homepage setup to ping my Plex instance on the same localhost.  Plex is running as a service (not a docker container) on the host.  The config looks like this:

```
- Media:
    - Plex:
        icon: plex.png
        href: https://<host ip or dns name>:32400
        description: Movies, Anime, and TV Shows
        ping: https://<host ip or dns name>:32400
        statusStyle: "dot"
        widget:
            type: tautulli
            url: http://<host ip>:8181
            key: <key>
```
Ping will show a green status when Plex is up and running - this is great and expected.  However, if I decide to turn off Plex (in other words stop the service), I would expect the ping to show that the page is down, but it stays green.

![image](https://github.com/gethomepage/homepage/assets/12883173/f03d117c-fa86-4302-adda-c11681704fdd)

I must be doing something wrong, that or I've hit a bug.  I've tried changing ping to just use the ip address with the port (no https:// in front), tried the hostname instead of the ip address, etc.  It's always the same result.  Anyone know why this is happening?
