### DISCUSSION TITLE
Change specific event colors on calendar widget

### DISCUSSION THREAD

**Discussion by fizzyhd** [gethomepage/homepage#2733] [Support]
I am trying to change the color of the dots for specific events such as radarr digital release and radarr physical release etc... Could anyone help me figure out how to do this even if it's a custom css that I have to do. I am willing to learn.

**Comment by glime-ai** [comment]
To change the color of the dots for specific events like Radarr digital release and Radarr physical release, you will indeed need to use custom CSS. Since you are willing to learn, I'll guide you through the process.

First, you need to identify the classes or IDs associated with the events you want to target. If the events already have specific IDs or classes assigned to them, you can use those to apply your custom styles. If not, you may need to modify the configuration to add unique identifiers to these events.

Once you have the identifiers, you can add your custom CSS rules to the `custom.css` file in your config directory. Here's a general example of what the CSS might look like:

```css
/* Custom CSS for Radarr digital release */
#radarr-digital-release {
    background-color: #hexcolor; /* Replace #hexcolor with the color you want */
}

/* Custom CSS for Radarr physical release */
#radarr-physical-release {
    background-color: #hexcolor; /* Replace #hexcolor with the color you want */
}
```

In the above example, `#radarr-digital-release` and `#radarr-physical-release` are hypothetical IDs for the digital and physical release events. You would replace `#hexcolor` with the actual hexadecimal color codes you want to use.

If you are not sure about the classes or IDs to target, or if you need to set them up, you can refer to the documentation for adding a specific `id` for a service or bookmark in the custom CSS or JavaScript section. Here's an example from the context provided:

```yaml
Service:
    id: myserviceid
    icon: icon.png
    ...
```

You would replace `myserviceid` with a unique identifier for the Radarr digital or physical release event.

Remember to test your changes and ensure that they are working as expected. If you encounter any issues or need further assistance, you can refer to the documentation or ask for help from the community.

Since this is a custom modification, please remember to do so at your own risk and ensure you have backups of your configurations before making changes.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).
