### DISCUSSION TITLE
[Feature Request] Kubernetes - Allow to infer `gethomepage.dev/widget.url`

### DISCUSSION THREAD

**Discussion by onedr0p** [gethomepage/homepage#2734] [Feature Requests]
### Description

Hi 👋

It would be awesome if homepage could infer the `gethomepage.dev/widget.url` from the ingress or (traefik) ingressroute rules. Since these resources can have multiple ingress rules, maybe it's best to always choose the first one if this gets implemented.

**Comment by glime-ai** [comment]
Hello!

To address your request for Homepage to infer the `gethomepage.dev/widget.url` from the ingress or Traefik IngressRoute rules, I would like to clarify that Homepage's current behavior requires explicit annotations to be set for certain functionalities. As per the documentation, the `gethomepage.dev/href` annotation is required for Homepage to recognize and use a Traefik IngressRoute. This is because Traefik routing rules can be complex, and Homepage needs a clear indication of which URL to use.

However, your suggestion to automatically infer the `widget.url` from the first rule in an ingress resource is an interesting idea. This could potentially be a feature request for future versions of Homepage. As of now, there is no mention in the documentation that Homepage supports this kind of inference automatically.

If you would like to see this feature implemented, I recommend opening a feature request issue on the Homepage GitHub repository. This way, the developers can consider it for inclusion in a future release. When creating the issue, provide a clear description of the feature, the potential benefits, and any considerations or edge cases that might need to be addressed.

For now, you should continue to use the annotations as documented to ensure Homepage correctly displays your services.

If you have any further questions or need assistance with another matter, feel free to ask!

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Reply by joryirving** [reply]
Hilarious that the bot's suggestion would be to open an issue _in this repo_. Seems a bit lacking in self-awareness.

This solution would also go towards cleaning up my annotations, since this is an example one for home-assistant:

```
annotations:
  gethomepage.dev/enabled: "true"
  gethomepage.dev/group: Home
  gethomepage.dev/name: Home-Assistant
  gethomepage.dev/icon: home-assistant.png
  gethomepage.dev/widget.type: homeassistant
  gethomepage.dev/widget.url: http://home-assistant.default:8123
  gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
```

Even pulling the `name` from the `metadata.name` field automatically would be helpful, and then you could use the existing annotation to overwrite that.

Additionally, have `enabled` default to true, if any of the other annotations are populated, and have it allowed to be disabled if you no longer want to use it. It could shorten it to something like:

```
annotations:
  gethomepage.dev/group: Home
  gethomepage.dev/icon: home-assistant.png
  gethomepage.dev/widget.type: homeassistant
  gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
```
