### DISCUSSION TITLE
[Feature Request]  Spotify player widget

### DISCUSSION THREAD

**Discussion by ItzLue** [gethomepage/homepage#2739] [Feature Requests]
### Description

Create a Spotify player widget, to see, current playing music, skip, queue, repeat, available devices, etc.

see https://developer.spotify.com/documentation/web-api/reference/get-information-about-the-users-current-playback

**Comment by glime-ai** [comment]
To create a Spotify player widget that includes features like viewing the current playing music, skipping tracks, managing the queue, toggling repeat, and listing available devices, you would need to use the Spotify Web API, specifically the endpoints related to user's current playback.

However, as a customer support agent, I do not have the capability to create new widgets or features. If you are looking to have this feature implemented in the Homepage product, I would recommend reaching out to the development team or submitting a feature request on the Homepage GitHub repository.

For now, you can use the Spotify Web API documentation to understand how to interact with the Spotify service programmatically. The endpoint you mentioned in your question (`/v1/me/player`) provides information about the user's current playback state, and you can use other endpoints to control playback (like skipping tracks or toggling repeat).

If you are a developer or have access to one, you can use the Spotify Web API to build a custom widget for your Homepage setup. You will need to handle authentication with Spotify using OAuth, make calls to the appropriate endpoints, and design a user interface for the widget.

For more information on how to use the Spotify Web API, you can visit the official documentation provided by Spotify at the link you've mentioned.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by github-actions** [comment]
This discussion has been automatically closed due to lack of community support. See our [contributing guidelines](https://github.com/gethomepage/homepage/blob/main/CONTRIBUTING.md#automatic-repository-maintenance) for more details.

**Comment by kaleben0** [comment]
I just embeded my Spotify playlist in a iframe widget

**Reply by shadowaero** [reply]
Can you provide instructions on how to do that.  I tried to add the code to bookmarks.yml and it didn't work.

**Reply by kaleben0** [reply]
It has to be a service. First you need to get the embed code here:

![image](https://github.com/user-attachments/assets/5b4f50cc-a17d-4bf8-9e43-6768d99bd782)

Example :
`<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/33KN4klcwrU05Ho4rf5Axl?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>`

Then you need to extract the src. In this case - https://open.spotify.com/embed/album/33KN4klcwrU05Ho4rf5Axl?utm_source=generator

Then your service should look something like this :
```

    - Spotify:
        icon: sh-spotify
        href: https://www.spotify.com
        siteMonitor: 'https://www.spotify.com'
        widget:
          type: iframe
          name: Spotify
          src: https://open.spotify.com/embed/album/33KN4klcwrU05Ho4rf5Axl?utm_source=generator
          classes: h-40
          referrerPolicy: same-origin
          allowFullscreen: false
```
