### DISCUSSION TITLE
[Feature Request] UISP API

### DISCUSSION THREAD

**Discussion by ctv99** [gethomepage/homepage#2740] [Feature Requests] [answered]
### Description

I'm no Developer on this but does anyone know how to Access this, i have a selfhosted UISP Site with 300+ Routers for customers.

Would love to use api on Each client Section To See Router Stats like OPNSense has.

**Comment by glime-ai** [comment, marked as answer]
Based on the context provided, it seems you are looking to access router statistics similar to the OPNSense widget but for a self-hosted UISP (Ubiquiti Internet Service Provider) site. While there is no direct mention of a UISP widget in the provided context, you can potentially use a similar approach as the custom API widget mentioned in the GitHub issue #2269 for OPNSense or the Unifi Controller widget.

To create a custom widget for UISP, you would need to utilize the UISP API. You would need to obtain an API token from your UISP instance, which you can usually find in the web UI under the API section or by inspecting the network requests using a web browser's developer tools.

Once you have the API token, you can create a custom API widget in your Homepage configuration similar to the example provided in the GitHub issue #2269. You would need to adjust the `url` to point to your UISP API endpoint and use the appropriate headers to authenticate your requests.

Here's a rough example based on the context provided:

```yaml
- UISP Router Stats:
    - Router1:
        icon: router.png
        widget:
          type: customapi
          url: https://uisp.yourdomain.com/api/path/to/router/stats
          headers:
            Authorization: 'Bearer YOUR_API_TOKEN'
          mappings:
            - field:
                data:
                  stats: wan_ip
              label: WAN IP
              format: text
            - field:
                data:
                  stats: uptime
              label: Uptime
              format: number
              suffix: Hours
            # Add more mappings as needed for CPU, RAM, etc.
```

Please note that the actual API endpoint, headers, and data mappings will depend on the UISP API and the specific data you want to display. You will need to refer to the UISP API documentation for the correct endpoints and data structure.

If you are not comfortable with creating a custom widget or if the UISP API is significantly different from the examples provided, you may need to seek assistance from someone with development experience or request a feature addition from the Homepage development team.

Remember to replace `YOUR_API_TOKEN` with the actual API token you obtain from UISP and adjust the `url` and `mappings` to match the UISP API's requirements.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).
