### DISCUSSION TITLE
Change placement of data from Glances no-chart for consistency

### DISCUSSION THREAD

**Discussion by finagle69** [gethomepage/homepage#2755] [General]
Hi,

I would like to see the location of Used/Free/Total be consistent across Glances non-chart.  How it appears currently below:
![glances-no-chart](https://github.com/gethomepage/homepage/assets/20806098/9beb50a5-171b-482c-a039-b9a48bc008be)

**Comment by glime-ai** [comment]
To achieve a consistent display of Used/Free/Total metrics across Glances non-chart (graphless) views, you would need to ensure that the configuration for each widget is set up correctly in your YAML configuration file. The non-chart view is enabled by setting `chart: false` in the widget options.

Based on the context provided, here is an example of how you might configure a Glances widget for network usage without the chart:

```yaml
- Network Usage:
    widget:
      type: glances
      url: http://glances.host.or.ip:port
      metric: network:enp0s25
      chart: false
```

To apply this to other metrics like CPU, memory, and disk, you would follow a similar pattern, specifying the appropriate metric and setting `chart: false`. Here are additional examples for CPU and memory:

```yaml
- CPU Usage:
    widget:
      type: glances
      url: http://glances.host.or.ip:port
      metric: cpu
      chart: false

- Memory Usage:
    widget:
      type: glances
      url: http://glances.host.or.ip:port
      metric: memory
      chart: false
```

Make sure to replace `http://glances.host.or.ip:port` with the actual URL of your Glances server and adjust the `metric` field to match the specific resource you want to monitor.

If you are still experiencing inconsistencies in the display of Used/Free/Total metrics after configuring the widgets as shown above, it may be a bug or a limitation in the current version of the Homepage application you are using. In such a case, you should report the issue to the maintainers of the Homepage project for further assistance.

Remember to check the documentation and any recent updates or discussions in the project's issue tracker to see if there are any known issues or solutions related to your query.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).
