### DISCUSSION TITLE
[Feature Request]  Resources/Glances Information Widget view Used size instead of Free amount for Memory and Disk

### DISCUSSION THREAD

**Discussion by brikim** [gethomepage/homepage#2769] [Feature Requests]
### Description

I would love to see a setting to see Used sizes for memory and disk instead of the default free size. Suggested adding a used flag for resources and glances widgets to see the the used size for memory (RAM) and Disk space.

### Other
```yaml
- resources:
    label: Memory Resouces
    used: true
    memory: true
    disk:
      - /disk1
```

![homepageUsedWidgetBar](https://github.com/gethomepage/homepage/assets/3686683/0f3c6562-9877-463d-9ae7-fe59cbb4fa1f)

16GiB of RAM would show with 3.2 GiB used would show
3.2 GiB Used for RAM instead of the current 12.8 GiB Free

_No response_
