### DISCUSSION TITLE
homepage died after compose down / up

### DISCUSSION THREAD

**Discussion by Archigos** [gethomepage/homepage#2777] [Support] [answered]
I'm running this via a docker-compose file on macOS Ventura... it's been working great for weeks (when I first got it set up).

However, tonight I was doing some work on the computer and ran `docker compose down` finished my work and ran `docker compose up -d` and in the logs it says Cannot find module '/app/server.js' and a few lines about where it looked... it states Node.js v18.19.0 as well if that matters. I checked the repo and noticed there was an update 7 hours ago so I'm wondering if that broke it? Either way, should I change the docker-compose file from `image: ghcr.io/gethomepage/homepage:latest` to a specific version number to get back up and running (if this was a bug)... and what version number would I use?

Here's my docker-compose.yml for reference:
```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```
Sadly I won't be able to check up on this issue until tomorrow because it's already 2am and I need sleep. :(

**Comment by glime-ai** [comment]
Based on the information provided, it seems like the issue might be related to a recent update to the `homepage` Docker image. If the `latest` tag now points to a version that is causing issues, you could indeed try using a specific version of the image that was working for you before.

To find a specific version number to use, you can check the tags available on the GitHub Container Registry for the `homepage` image. You can visit the registry for `gethomepage/homepage` and look for a tag that corresponds to a version that you know was working well for you.

Once you have identified a suitable version tag, you can modify your `docker-compose.yml` file to use that version instead of `latest`. For example, if you found that version `0.8.3` was working for you, you would change the `image` line to:

```yaml
image: ghcr.io/gethomepage/homepage:0.8.3
```

Remember to replace `0.8.3` with the actual version number you wish to use.

After making this change, you can run `docker compose up -d` again to pull the specified version and start your containers.

If you are unable to check the GitHub Container Registry for tags, you could also consider using a version that was known to be stable, such as `0.8.4`, which was mentioned in one of the issues you provided in the context.

Here's how you could modify your `docker-compose.yml`:

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:0.8.4
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

Please replace `0.8.4` with the version number you decide to use. If you continue to experience issues, you may want to check the GitHub issues page for `gethomepage/homepage` to see if others are experiencing similar problems or if there has been any official communication about the issue.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).
