### DISCUSSION TITLE
API Errors on Sonarr, Radarr, nzbget.

### DISCUSSION THREAD

**Discussion by BuzzMcWoof** [gethomepage/homepage#278] [Support]
Hi

Just configuring Homepage, and while the links work perfectly (nzbget etc) and the container stats work fine the app stats such as queued downloads and wanted shows just show an api error.  YAML files are configured according the the wiki I believe. 

Homepage is running under docker on a Synology, and all services are also hosted on the Synology.

Services YAML for the above :  
![image](https://user-images.githubusercontent.com/57343989/192236355-4ddfa383-0b90-4853-bbe2-17d9fdad49a3.png)

Log file entries:

[2022-09-26T08:36:58.837Z] error: undefined
[2022-09-26T08:37:01.205Z] error: undefined
[2022-09-26T08:37:21.235Z] error: undefined
[2022-09-26T08:37:49.738Z] error: [
  500,
  Error: connect ETIMEDOUT 192.168.1.120:8989
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.120',
    port: 8989
  }
]
[2022-09-26T08:37:49.739Z] error: [
  500,
  Error: connect ETIMEDOUT 192.168.1.120:8989
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.120',
    port: 8989
  }
]
[2022-09-26T08:37:49.741Z] error: [
  500,
  Error: connect ETIMEDOUT 192.168.1.120:7878
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.120',
    port: 7878
  }
]
[2022-09-26T08:37:49.742Z] error: [
  500,
  Error: connect ETIMEDOUT 192.168.1.120:7878
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.120',
    port: 7878
  }
]

Thanks in advance

**Comment by JazzFisch** [comment]
Docker doesn't allow containers to send traffic to the same IP address they are hosted on.  I would recommend changing the IP address to instead the container name, as long as all of the containers are running on the same docker network.

**Comment by trythatagain** [comment]
I don't use Synology, but here is my snippet of services for Sonarr.
```
    - Sonarr:
        icon:   sonarr.png
        href:   http://192.168.1.12:8989
        description:    TV Series management
        container:  sonarr
        widget:
          type:   sonarr
          url:    http://192.168.1.12:8989
          key:    apikey
  ```
It shows the correct info. Could it be a Synology Docker thing?

**Reply by JazzFisch** [reply]
Which IP address is homepage on?  192.168.1.12?

**Reply by trythatagain** [reply]
Yes

**Comment by BuzzMcWoof** [comment]
Thanks to those that have provided help :)

Seems it's something to do with the Synology network used. Sonarr/Radarr/Nzbget were all on the host network within Docker, moved them to the default bridge network and voila, can see the stats in Homepage. Saying that, I first moved them to a newly created bridge network just for those 3 apps and that didn't work either, seems only the default bridge network allows the relevant connections. No idea why, not sure I can be bothered pursuing that one!

@Jazzfisch - you mentioned changing the IP address to the container name, do you have an example of it, did try http://nzbget:6789 and that didn't connect.

Many thanks

**Reply by JazzFisch** [reply]
Here is a chopped up copy of my docker-compose.yml file.  It absolutely won't work as written, but hopefully the ideas inside can help.

You'll see that I set the `container_name` and some internal docker DNS aliases as well.  I've also included how I create my bridge network and then set which bridge network to use for each container.

```yml
version: "3.8"

########################### NETWORKS
networks:
  traefik-internal:
    name: traefik-internal
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.19.1/24"
          gateway: "172.19.19.1"

########################### SERVICES
# All services / apps go below this line
services:
  # Radarr - Movie management
  radarr:
    container_name: radarr
    networks:
      traefik-internal:
        aliases:
          - radarr.docker.internal
          - radarr

  # Sonarr - TV Shows management
  sonarr:
    container_name: sonarr
    networks:
      traefik-internal:
        aliases:
          - sonarr.docker.internal
          - sonarr

  # SABNZBD - Binary newsgrabber (NZB downloader)
  sabnzbd:
    container_name: sabnzbd
    networks:
      traefik-internal:
        aliases:
          - sabnzbd.docker.internal
          - sabnzbd
```
