### DISCUSSION TITLE
[Feature Request] Ceph Widget

### DISCUSSION THREAD

**Discussion by slapcat** [gethomepage/homepage#2785] [Feature Requests]
### Description

A widget for querying the Ceph prometheus endpoint to get information such as status, available capacity, OSDs up/down/in/out, etc.

**Comment by glime-ai** [comment]
To create a widget for querying the Ceph Prometheus endpoint, you would need to define a custom widget that can interact with the Prometheus API and extract the necessary metrics related to Ceph. Based on the context provided, it seems that the Homepage project allows for the creation of widgets that can display various metrics from different services, including Prometheus.

Given that Prometheus is already supported, you can use the existing Prometheus widget configuration as a starting point. You would need to specify the metrics you want to display related to Ceph, such as cluster status, available capacity, and OSD (Object Storage Daemon) states.

Here's an example of how you might define a widget in YAML format to query Ceph metrics from a Prometheus endpoint:

```yaml
widget:
  type: prometheus
  url: http://prometheus-host:port
  metrics:
    - name: ceph_health_status
      query: ceph_health_status{job="ceph"}
    - name: ceph_available_capacity
      query: ceph_cluster_total_bytes{job="ceph"} - ceph_cluster_total_used_bytes{job="ceph"}
    - name: ceph_osds_up
      query: sum(ceph_osd_up{job="ceph"})
    - name: ceph_osds_down
      query: sum(ceph_osd_down{job="ceph"})
    - name: ceph_osds_in
      query: sum(ceph_osd_in{job="ceph"})
    - name: ceph_osds_out
      query: sum(ceph_osd_out{job="ceph"})
```

Please note that the actual metric names and queries will depend on how Ceph metrics are exposed to Prometheus in your environment. You will need to adjust the `query` fields to match the correct expressions for your Prometheus setup.

You would then add this widget configuration to your Homepage instance, following the documentation and examples provided for other widgets.

If you need further assistance with the specific Prometheus queries for Ceph or with the integration into Homepage, you may need to consult the Prometheus and Ceph documentation or seek help from their respective communities.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by slapcat** [comment]
This might work if there were a `metrics` key and the Prometheus widget could read Prometheus data, but it can't.

Ceph can expose its metrics over a prometheus-compatible HTTP endpoint, or they can be gathered via the API (which requires authentication).

**Comment by slapcat** [comment]
I found a workaround to get information from ceph using the `customapi` widget:
```
        widget:
            type: customapi
            url: http://<address>:<port>/api/health/full
            method: GET
            headers:
              Authorization: "Bearer <token>"
              Accept: "application/vnd.ceph.api.v1.0+json"
            mappings:
              - field:
                  health: status
                label: Status
              - field:
                  df:
                    stats: num_osds
                label: OSDs
              - field:
                  df:
                    stats: total_avail_bytes
                label: Free Space
                format: bytes
```

But it would still be useful to have a proper widget that can calculate things like how many OSDs are out/in/down/up, which would require some basic math operations.
