### DISCUSSION TITLE
How to use "provider" in the service-widgets?  Can this be customized?

### DISCUSSION THREAD

**Discussion by rutravis** [gethomepage/homepage#2786] [Support]
### Description

I am trying to define my own "provider apikeys" for my widgets.

An example would be the following.  Would this be correct?  It doesn't log into the service right now:

### homepage version

0.8.7

### Installation method

Docker

### Configuration

```yaml
settings.yaml file:

providers:
  sonarrapi: [sonarr api key]
  etc....

services.yaml file:

    - Sonarr:
        icon: sonarr.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: http://[server:port]
        description: Sonarr TV Show Search Engine
        widget:
          type: sonarr
          url: [url]
          provider: sonarrapi
          enableQueue: true
```

### Browser Logs

API Error: HTTP Error
URL: http://[server:port]/api/v3/wanted/missing?apikey=***

### Troubleshooting

If I define the apiKey in the widget directly in the services.yaml, access to the services work properly.  When implemented as here, the apikey doesn't appear to be passed from the settings.yaml -> providers section to the services.yaml -> service -> widget -> api

**Comment by glime-ai** [comment]
Based on the context provided, it seems that you are trying to use a `provider` key to reference an API key defined under the `providers` section in your `settings.yaml` file. However, from the documentation and examples provided, there is no indication that the `provider` key is a supported method for passing API keys to widgets in the configuration files.

The standard way to define an API key for a widget, as shown in the examples, is to use the `key` field directly within the widget configuration. Here is an example based on the documentation:

```yaml
- Sonarr:
    icon: sonarr.svg
    href: http://sonarr.host/
    description: Sonarr TV Show Search Engine
    widget:
      type: sonarr
      url: http://sonarr.host/
      key: yoursonarrapikey
      enableQueue: true
```

If you are experiencing issues with the API key not being passed correctly when using the `provider` key, it is likely because this is not a recognized configuration option. You should use the `key` field directly within each widget configuration to specify the API key.

To resolve the issue, you should define the API key directly in the `services.yaml` file under the `widget` configuration for each service, as shown in the example above.

If you have further questions or need additional assistance, please let me know.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer above is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).
