### DISCUSSION TITLE
How to display stats dot for Proxmox or external server

### DISCUSSION THREAD

**Discussion by eBarazi** [gethomepage/homepage#2789] [Support] [answered]
### Description

Hi, 
I was able to show the stats for docker containers, but I am not able to add the ststs of proxmox or plex on other machine, any help is really apprecited.
E

### homepage version

v0.8.7 (05a7c0f, Jan 26, 2024)

### Installation method

Docker

### Configuration

```yaml

#Setting:

showStats: true
statusStyle: "dot"



#Service:

 Services:
    - Proxmox:
        icon: /icons/Proxmox.svg
        href: https://192.168.1.101:8006
        server: pve1
        #description: Proxmox
        widget:
            type: proxmox
            url: https://192.168.1.101:8006
            username: koala12
            password: X1234567899X
            node: pve1 # optional
```

### Troubleshooting

n/a
