### DISCUSSION TITLE
[Feature Request] TrueNAS information widget for resources

### DISCUSSION THREAD

**Discussion by dstotz** [gethomepage/homepage#2791] [Feature Requests]
### Description

Add new information widget to display resource utilization for the TrueNAS server. Suggesting that it has the same aesthetic as the Kubernetes information widget

### Other

```yaml
- truenas:
    url: http://host.or.ip:port
    username: user # not required if using api key
    password: pass # not required if using api key
    key: yourtruenasapikey # not required if using username / password
    label: My TrueNAS # optional
    icon: si-truenas # optional, defaults to si-truenas
    refresh: 5000 # optional, in ms
```

![image](https://github.com/gethomepage/homepage/assets/9381594/ed1ac5f1-b876-4315-80ff-44738238fd4f)

Initial dev work already complete on PR https://github.com/gethomepage/homepage/pull/2788 but do not yet have the upvote requirement met
