### DISCUSSION TITLE
[Feature Request] TrueNAS display pool usage information

### DISCUSSION THREAD

**Discussion by dstotz** [gethomepage/homepage#2792] [Feature Requests] [answered]
### Description

Extend the existing TrueNAS service widget with an optional parameter that allows displaying the pool information for at a glance pool usage.

### Other

```yaml
widget:
  type: truenas
  url: http://truenas.host.or.ip
  username: user # not required if using api key
  password: pass # not required if using api key
  key: yourtruenasapikey # not required if using username / password
  enablePools: true # optional, defaults to false
```

![image](https://github.com/gethomepage/homepage/assets/9381594/0621bce4-283e-4244-b449-6b394c390183)

Initial dev work already complete on PR https://github.com/gethomepage/homepage/pull/2788 but do not yet have the upvote requirement met
