### DISCUSSION TITLE
Strugging to get docker automatic service discovery to work

### DISCUSSION THREAD

**Discussion by EweSparky** [gethomepage/homepage#2795] [Support]
### Description

Hi there,

I'm setting Homepage up for the first time and trying to get docker automatic discovery to work. I added the labels to the docker compose file (below) and restarted the container, then added the following into `./config/services.yaml`:

```yaml
- Media:
    - Audiobookshelf:
        href: https://app.example.com/
        description: Audiobook and podcast server and app
```

but when I do this, I only get the `Media` group and an iconless button to Audiobookshelf. My understanding from the [services documentation](https://gethomepage.dev/latest/configs/docker/#services) is that:

> You do not need to specify the server or container values, as they will be automatically inferred.

Which I assume refers to the `server` and `container` values in `services.yaml`. Conversely, when I change `services.yaml` to the following, I get the service details in Homepage... but these are obviously not automatically discovered:

```yaml
- Media:
    - Audiobookshelf:
        icon: audiobookshelf
        href: https://app.example.com/
        description: Audiobook and podcast server and app
        server: server-docker
        container: audiobookshelf
```

Can someone highlight where I'm going wrong here please?

Thank you!

### homepage version

0.8.7

### Installation method

Docker

### Configuration

```yaml
Homepage docker-compose.yml:

version: '3.8'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    container_name: homepage
    ports:
      - 8680:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./data/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations



Audiobookshelf docker-compose.yml:

version: '3.8'
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    container_name: audiobookshelf
    ports:
      - 8580:80
    environment:
      - TZ=Australia/Melbourne
    volumes:
      - /srv/audiobookshelf/audiobooks:/audiobooks
      - /srv/audiobookshelf/podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    labels:
      - homepage.group=Media
      - homepage.name=Audiobookshelf
      - homepage.icon=audiobookshelf.png
      - homepage.href=https://app.example.com/
      - homepage.description=Audiobook and podcast server and client



Homepage ./config/docker.yaml:

---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

server-docker:
  socket: /var/run/docker.sock



Homepage ./config/services.yml:

---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎

- Media:
    - Audiobookshelf:
        icon: audiobookshelf
        href: https://app.example.com/
        description: Audiobook and podcast server and app
        server: server-docker
        container: audiobookshelf
```

### Container Logs

```text
Listening on port 3000
Listening on port 3000
```

`./config/logs/homepage.log` is empty.

### Browser Logs

N/A

### Troubleshooting

```text
user@server:/srv/docker/homepage$ sudo docker exec -it homepage ping 10.10.70.31
PING 10.10.70.31 (10.10.70.31): 56 data bytes
64 bytes from 10.10.70.31: seq=0 ttl=64 time=0.074 ms
64 bytes from 10.10.70.31: seq=1 ttl=64 time=0.060 ms
64 bytes from 10.10.70.31: seq=2 ttl=64 time=0.036 ms
64 bytes from 10.10.70.31: seq=3 ttl=64 time=0.061 ms
^C
--- 10.10.70.31 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.036/0.057/0.074 ms
```
