### DISCUSSION TITLE
Auto discovery not working

### DISCUSSION THREAD

**Discussion by tomerh2001** [gethomepage/homepage#2796] [Support] [answered]
### Description

Hi, I'm trying to use Homepage on my NAS, but for some reason, it doesn't seem to pick up the auto-discovery; I tried reading about the issues others had in the past, and it seems it's usually the docker not running, as root, but I don't think it's the issue in my case (or maybe I'm doing something wrong?)

These are my files:

`homepage/compose.yml`:
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /pool/services/homepage:/app/config
    environment:
      LOG_LEVEL: trace
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=HostRegexp(`x.y.{domain:com|local}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```
I also tried using the docker-socket-proxy, setting PUID and PGID to 0 or 1000 (1000 is my main user), etc

`{homepage_config}/docker.yaml`:
```
my-docker:
  socket: /var/run/docker.sock
```

`{homepage_config}/services.yaml`:
```
# Empty - Do I need to put anything here if I use auto-discovery? I didn't seem to find anything about it in the docs
```

 `pihole/compose.yml`:
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "8033:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Asia/Jerusalem'
      DNSMASQ_LISTENING: 'all'
      WEBPASSWORD: ${WEBPASSWORD} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '/pool/services/pihole:/etc/pihole'
      - '/pool/services/pihole/dnsmasq:/etc/dnsmasq.d'
      - './01-pihole.conf:/etc/dnsmasq.d/01-pihole.conf'
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=HostRegexp(`x.y.{domain:com|local}`)
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.routers.pihole.tls=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - homepage.group=Network
      - homepage.name=Pihole
      - homepage.icon=pihole.png
      - homepage.description=Home DNS Server
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - traefik
```

And finally, when I run homepage this is are the logs I get:
```
homeserver@homeserver:/app$ sudo docker compose up homepage --force-recreate 
[+] Running 1/0
 ✔ Container homepage  Recreated                                                                                                                0.0s 
Attaching to homepage
homepage  | Listening on port 3000
homepage  | [2024-01-31T16:37:41.300Z] debug: No containers were found with homepage labels.
homepage  | [2024-01-31T16:37:41.405Z] debug: No containers were found with homepage labels.
homepage  | [2024-01-31T16:37:41.595Z] debug: No containers were found with homepage labels.
homepage  | [2024-01-31T16:37:42.819Z] debug: No containers were found with homepage labels.
homepage  | [2024-01-31T16:37:46.412Z] debug: No containers were found with homepage labels.
```

But when I navigate to homepage I don't see the service there:
![image](https://github.com/gethomepage/homepage/assets/45624804/ca62719a-6faa-4599-868e-545143c8bb22)

### homepage version

v0.8.7

### Installation method

Docker

### Troubleshooting

Tried previously suggested solutions from other discussions, didn't work.

**Comment by glime-ai** [comment]
Based on the information provided, it seems that you have correctly set up the Homepage container to run as root and have mounted the Docker socket into the container. However, the auto-discovery feature is not picking up the services as expected.

Here are a few things you can check and try:

1. **Ensure Labels are Correct**: Verify that the labels on your `pihole` service are correctly formatted and that they follow the Homepage auto-discovery conventions. Labels should start with `homepage.` and be properly formatted as shown in your `pihole/compose.yml`.

2. **Check Docker Socket Permissions**: Even though you are running the Homepage container as root, ensure that the Docker socket has the correct permissions and that the Homepage container can access it.

3. **Review Homepage Configuration**: Make sure that your `docker.yaml` configuration is correct. The `socket` entry should point to the Docker socket, and it seems to be correctly set in your configuration.

4. **Check for Network Issues**: Ensure that there are no network issues preventing the Homepage container from communicating with the Docker API through the socket.

5. **Review Logs for More Details**: Since you have set the `LOG_LEVEL` to `trace`, you should be able to see more detailed logs. Look for any errors or warnings that could indicate what might be going wrong.

6. **Check Version Compatibility**: Ensure that the version of Homepage you are using (`v0.8.7`) is compatible with the auto-discovery feature and that there are no known issues with this version related to auto-discovery.

7. **Consult Documentation and Issues**: Review the official documentation and search for any open or closed issues in the Homepage repository that might be related to your problem.

8. **Try Manual Configuration**: As a temporary workaround, you can try manually configuring the services in the `services.yaml` file to see if they appear on the Homepage.

If none of these steps resolve the issue, you may want to reach out to the Homepage community or create a new issue in the Homepage repository with all the details of your setup and the steps you have tried.

Since you have already tried some solutions from other discussions without success, it might be a more specific issue with your setup or a bug in the version you are using.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by shamoon** [comment]
What is the content of your `settings.yaml`?

**Reply by tomerh2001** [reply]
I didn't change anything except `docker.yaml` from the defaults, so -
```
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
```

Do I need to change anything here?

**Reply by shamoon** [reply]
No, thats fine. 

I did just notice they're in different compose stacks. I'd have to double-check but this might be an issue with the docker API and what containers are being returned.

Homepage uses [docker.listContainers](https://github.com/apocas/dockerode?tab=readme-ov-file#docker) --> https://docs.docker.com/engine/api/v1.37/#tag/Container/operation/ContainerList

**Reply by shamoon** [reply]
I just tested with separate compose files and no issue.

Hmm, Im sure theres something obvious I just dont see

**Reply by shamoon** [reply]
Oh, did you re-create the pihole container? Environment vars are only changed after re-create, not restart

**Reply by tomerh2001** [reply]
Huh, that's interesting, that's my main `compose.yml` if it's relevant:

```
name: homeserver

include:
  - path: cloudflared/compose.yml
  - path: traefik/compose.yml
  - path: watchtower/compose.yml
  - path: pihole/compose.yml
  - path: registry/compose.yml
  - path: sabnzbd/compose.yml
  - path: prowlarr/compose.yml
  - path: sonarr/compose.yml
  - path: radarr/compose.yml
  - path: jellyfin/compose.yml
  - path: bazarr/compose.yml
  - path: readarr/compose.yml
  - path: kavita/compose.yml
  - path: notifiarr/compose.yml
  - path: confluence/compose.yml
  - path: dozzle/compose.yml
  - path: homepage/compose.yml
 ```  

But how could that be the problem?

**Reply by tomerh2001** [reply, marked as answer]
You were right! I tried putting all services into a single compose file and it worked:

```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "8033:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Asia/Jerusalem'
      DNSMASQ_LISTENING: 'all'
      WEBPASSWORD: ${WEBPASSWORD} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '/pool/services/pihole:/etc/pihole'
      - '/pool/services/pihole/dnsmasq:/etc/dnsmasq.d'
      - './01-pihole.conf:/etc/dnsmasq.d/01-pihole.conf'
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=HostRegexp(`x.y.{domain:com|local}`)
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.routers.pihole.tls=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - homepage.group=Network
      - homepage.name=Pihole
      - homepage.icon=pihole.png
      - homepage.description=Home DNS Server
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - traefik

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /pool/services/homepage:/app/config
    environment:
      LOG_LEVEL: debug
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=HostRegexp(`x.y.{domain:com|local}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/traefik.yaml:/traefik.yaml:ro
      - ../traefik/configs/:/configs/:ro
      - ../traefik/certificates/:/certificates:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=HostRegexp(`x.y.{domain:com|local}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```

Unfortunately, I need to have my compose files separated... Is there any way to solve this?
