### DISCUSSION TITLE
Kavita widget requires Admin role

### DISCUSSION THREAD

**Discussion by renemarc** [gethomepage/homepage#2797] [Support] [answered]
### Description

Using any Kavita user without both **Admin** and **Login** roles result in a 403 Forbidden status code when the Kavita widget queries the Kavita server stats endpoint.

Adding both **Admin** and **Login** roles satisfies the endpoint requirements.

A documentation PR will follow.

### homepage version

v0.8.7 (05a7c0f)

### Installation method

Docker

### Configuration

```yaml
- Media:
    - Kavita:
        icon: kavita.svg
        href: http://media.local:5000/all-series
        description: Comics
        widget:
          type: kavita
          url: http://media.local:5000
          username: homelab
          password: password123
```

### Container Logs

[2024-02-01T02:40:32.181Z] error: <kavitaProxyHandler> Error getting data from Kavita: http://media.local:5000/api/Stats/server/stats status 403. Data:
[2024-02-01T02:40:32.237Z] error: undefined

### Troubleshooting

Skipped
