### DISCUSSION TITLE
pfSense widget throwing node errors

### DISCUSSION THREAD

**Discussion by doublehelix** [gethomepage/homepage#2816] [Support] [answered]
### Description

I've installed the pfSense API, configured it, tested in in the swagger test interface.
All works ok.

I then configured the pfsense Service Widget in Homepage (in the `services.yaml` file - detailed below).
When viewing Homepage, I get the following error message:
![image](https://github.com/gethomepage/homepage/assets/355130/2b30a1af-653e-4537-8cd2-57b5a92bf3bf)

My logs are empty (`config/logs/homepage.log)

(docker) `/compose.yml`:
```yml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /home/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /home/docker/homepage/images:/app/public/images
```

`/config/settings.yaml`:

```yml
title: HomeLab
theme: dark
color: slate
headerStyle: boxedWidgets
target: _blank
```

`/config/services.yaml`:

```yml
- Network management:
    - pfSense Gateway:
        widget:
            type: pfsense
            url: https://pfsense.neurotechnics.lan:10443/
            username: james-admin
            password: 6j7Ghv5kpKr!YXzz
            wan: igb0
```

### homepage version

v0.8.7 (05a7c0f, Jan 27, 2024)

### Installation method

Docker

### Troubleshooting

The pfSense API works ok:
![image](https://github.com/gethomepage/homepage/assets/355130/24b8642b-a0b1-4813-acf6-41ec44ef77a9)
