### DISCUSSION TITLE
[Feature Request] settings to auto refresh the page every x seconds (config changes + widgets)

### DISCUSSION THREAD

**Discussion by AmahaShadow** [gethomepage/homepage#2817] [Feature Requests]
### Description

Hi,

first off, superb work on this.
I was wondering if we could have an option to automatically refresh the page without user intervention.
that way, if a monitored service/vm/... crashes while the page is already open, we would get an updated status

probably at the widgets level to minimize calls to only the services we need to refresh
I know some widgets have that refresh: option, but having it on a global scale would be nice

maybe .
```

settings.yaml
default-refresh : 120
# refresh time of the widgets is seconds. auto-refresh: true should be set at the widget level
# the config will be checked for changes at the same rate

services.yaml
proxmox
    type: proxmox
    auto-refresh: true # this widget would now be refreshed at the rate defined in settings.yaml/default-refresh
    (....)
  
```  
it would also make possible the use of homepage as a dashboard, especially if you couple it with a backend script to alter the configuration live (like alter settings.yaml set background color to red instead of slate if your external script detects a crash, or adding widgets live if an issue is detected).

I'm really not great with node or I would have done it myself, 
If I have some times, I might look into it at some point though

**Comment by glime-ai** [comment]
Hello,

Thank you for your kind words and for your suggestion regarding the auto-refresh feature for widgets on the Homepage dashboard. As of my knowledge cutoff in March 2023, the standard behavior for widgets in Homepage is to fetch data when the page is rendered and then again any time the page gains focus.

However, you can set a `refreshInterval` property for individual widgets to make them refresh automatically at a specified interval. Here's an example of how you can set this up for a widget in your `services.yaml` file:

```yaml
widget:
    type: proxmox
    url: https://proxmox.host.or.ip:8006
    username: api_token_id
    password: api_token_secret
    refreshInterval: 120 # time in seconds
```

In this example, the `refreshInterval` is set to 120 seconds, which means the widget will refresh its data every 120 seconds.

Currently, there isn't a global setting for auto-refresh across all widgets, but your idea of having a `default-refresh` in the `settings.yaml` that can be overridden at the widget level is interesting. This would require changes to the Homepage application code.

If you're interested in contributing to the project, I would recommend checking out the Homepage repository on GitHub and possibly opening an issue or pull request with your feature suggestion. The maintainers and community can then discuss the feasibility and implementation details.

For altering configurations live, such as changing the background color or adding widgets dynamically based on certain conditions, this would also require custom scripting and potentially contributing to the Homepage project to support such dynamic configurations.

If you have any further questions or need assistance with the current configuration options, feel free to ask.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by AmahaShadow** [comment]
ok, sooo, I checked our helpful (?) AI friend, and that doesn't work, so either I screwed something up in my config (below), Or the AI just imagined that setting ?
```
  - Prox/234:
       href: https://10.1.81.228:8006/
       icon: proxmox.png
       description: Databases
       widget:
         type: proxmox
         url: https://10.1.81.228:8006
         username: dashboard@pve!api-homepage
         password: ***********************
         node: prox234
         refreshInterval: 120
```

----EDIT
after checking the issues mentionning this, it seems it's now only for the graphs/custom API. any particular reason ?
or is it just that, by policy, it should be handled at the widget level instead ?

I think the ability to check  a change on the config files, and refresh the page in such a case would be nice to have
