### DISCUSSION TITLE
Defining widget fields via kubernetes automatic service discovery annotations?

### DISCUSSION THREAD

**Discussion by katanacrimson** [gethomepage/homepage#2821] [Support]
### Description

I'm not seeing any documented way to define which widget fields are desired when using the kubernetes ingress annotations, documented [here](https://gethomepage.dev/latest/configs/kubernetes/#automatic-service-discovery).  Digging through the code, it almost looked like it was supposed to be parsed out from JSON, like so:

```yaml
apiVersion: 'networking.k8s.io/v1'
kind: 'Ingress'
metadata:
  name: 'app-ingress'
  namespace: 'calibreweb'
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: 'calibre-web'
    gethomepage.dev/description: 'e-book collection'
    gethomepage.dev/href: 'https://...'
    gethomepage.dev/group: 'services'
    gethomepage.dev/icon: 'mdi-book-arrow-down-outline-#bb2d2d'
    gethomepage.dev/widget.type: 'calibreweb'
    gethomepage.dev/widget.url: 'https://...'
    gethomepage.dev/widget.fields: "['books', 'authors']"
    gethomepage.dev/pod-selector: ''
```

This, however, does not appear to be working as desired - all fields show for the calibreweb widget, instead of just `books` and `authors`.  Further, specifying this as an actual list in yaml is rejected by kubernetes, as annotation values *must* be a string.

Is this not supported?  Is this intended to work differently, or should this be a feature request?

### homepage version

0.8.4

### Installation method

Other (please describe above)

### Troubleshooting

-
