### DISCUSSION TITLE
[Feature Request] Redact credentials from logs with when YAML fails to parse

### DISCUSSION THREAD

**Discussion by bphenriques** [gethomepage/homepage#2822] [Feature Requests]
### Description

I have the following setup for Glances widget and I made a mistake when setting up the URL:
```yaml
- glances:
    url: http://glances:61208
    username: glances
    password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    expanded: true
    disk:
      - /volume1
      - /volume2
```

 I was surprised to see this in the logs:
```
homepage  | Data: {"type":"Buffer","data":[]}
homepage  | [2024-02-02T21:13:20.427Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
homepage  | [2024-02-02T21:13:20.427Z] error: named tag handle cannot contain such characters (4:30)
homepage  | 
homepage  |  1 | - glances:
homepage  |  2 |     url: http://glances:61208
homepage  |  3 |     username: glances
homepage  |  4 |     password: redacted
homepage  | ----------------------------------^
homepage  |  5 |     cpu: true
homepage  |  6 |     mem: true
```

The fields related with credentials should not be logged, or should be at least redacted.
