### DISCUSSION TITLE
[Feature Request] Docker discovery traefik integration

### DISCUSSION THREAD

**Discussion by LouDou** [gethomepage/homepage#2823] [Feature Requests]
### Description

Hi,

Firstly I'm really enjoying getting homepage installed on my home server. Very slick work.

There's just one thing nagging me, is that I use traefik labels already to route requests to apps, but I have to duplicate the URLs in the homepage labels;

e.g.

```yaml
services:
  syncthing:
    image: syncthing/syncthing:1.27
    ports:
      - '22000:22000/tcp'
      - '22000:22000/udp'
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing-private.rule=Host(`syncthing.home.lan`)
      - traefik.http.routers.syncthing-private.entrypoints=web
      - homepage.group=NAS
      - homepage.name=Syncthing
      - homepage.icon=syncthing.png
      - homepage.href=http://syncthing.home.lan
```

You can see that I access syncthing's web interface via configuring a traefik Host rule for `syncthing.home.lan`. But I have to duplicate that same host string for `homepage.href`.

Could homepage be made to look at some subset of traefik router rules to avoid this duplication?

Regards,
Doug
