### DISCUSSION TITLE
Can't get Glances to work

### DISCUSSION THREAD

**Discussion by Zabriskije** [gethomepage/homepage#2830] [Support]
### Description

I'm running Homepage and Glances as Docker containers, both inside an Ubuntu Server 23.10 machine. While all the other services can communicate without any problem, Glances refuses to do so, and I can't figure out why.

![glances](https://github.com/gethomepage/homepage/assets/101254295/396896d0-e468-4f8d-9adb-d8bee36d37d2)

### Edit
Looks like it's a firewall issue. What rule should I add to ufw to make things work?

### Solution
```
sudo ufw allow from 172.16.0.0/12
```

---

### homepage version

v0.8.7 (05a7c0f)

### Installation method

Docker

### Configuration

Docker compose file for Glances:

```yaml
version: "3"
services:
  glances:
    image: nicolargo/glances
    container_name: glances
    restart: always
    network_mode: host
    pid: host
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/glances:/glances/conf
    ports:
      - 61208:61208
networks: {}
```

I know ports are ignored when Glances run as host, I just leave it here to remember which port it's using.

Docker compose for Homepage:

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/homepage/images:/app/public/images
      - /srv/homepage:/app/config
    ports:
      - 3000:3000
networks: {}
```

I've also tried restarting both containers without read-only, but nothing changed.

Usage in `services.yaml`:

```yaml
- Glances:
    - CPU:
        widget:
            type: glances
            url: http://localhost:61208
            metric: cpu
```

All the widgets have unique names.
I've tried using the internal IP and the machine hostname but with no luck.

Example from `homepage.log`:

```log
[2024-02-03T14:41:34.717Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://localhost:61208/api/3/cpu
[2024-02-03T14:41:34.717Z] error: <httpProxy> Error calling http://localhost:61208/api/3/system...
[2024-02-03T14:41:34.718Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT localhost:61208
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: 'localhost',
    port: 61208
  }
]
```

### Container Logs

```log
homepage  | [2024-02-03T16:10:46.927Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://localhost:61208/api/3/cpu
homepage  | [2024-02-03T16:10:49.025Z] error: <httpProxy> Error calling http://localhost:61208/api/3/cpu...
homepage  | [2024-02-03T16:10:49.025Z] error: <httpProxy> [
homepage  |   500,
homepage  |   AggregateError
homepage  |       at internalConnectMultiple (node:net:1114:18)
homepage  |       at afterConnectMultiple (node:net:1601:5) {
homepage  |     code: 'ECONNREFUSED',
homepage  |     [errors]: [ [Error] ]
homepage  |   }
homepage  | ]
```

### Troubleshooting

`docker exec homepage ping localhost:61208` can ping. All URLs do not end with a <kbd>/</kbd> or other API path.

**Comment by glime-ai** [comment]
Based on the information provided, it seems that the Glances service is running in host network mode (`network_mode: host`), which means it is using the host's network stack and not a separate Docker network. When you try to access Glances from the Homepage container using `http://localhost:61208`, it is actually trying to access the loopback interface (`localhost`) of the Homepage container itself, not the host machine.

Since Glances is running in host network mode, you should try accessing it using the host's external IP address or hostname instead of `localhost`. Here's what you can do:

1. Find out the host's external IP address or a hostname that resolves to it.
2. Replace `localhost` with the host's IP address or hostname in your `services.yaml` configuration for the Glances widget.

For example, if your host's IP address is `192.168.1.100`, your `services.yaml` should look like this:

```yaml
- Glances:
    - CPU:
        widget:
            type: glances
            url: http://192.168.1.100:61208
            metric: cpu
```

Make sure to replace `192.168.1.100` with your actual host's IP address or a valid hostname.

Additionally, ensure that the Glances API is accessible from other machines on the network by trying to access it from another computer or using a tool like `curl` from the Homepage container:

```bash
docker exec homepage curl http://192.168.1.100:61208/api/3/cpu
```

Replace `192.168.1.100` with your host's IP address. If you receive a valid response, then the Glances API is accessible, and the Homepage widget should be able to connect to it using the updated URL.

If you continue to experience issues, please provide the output of the `curl` command from the Homepage container, and ensure that there are no firewall rules blocking the connection to the Glances API on the host machine.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).
