### DISCUSSION TITLE
How to get dynamic information on qbittorrent widget?

### DISCUSSION THREAD

**Discussion by CaptainTrex** [gethomepage/homepage#2837] [Support] [answered]
### Description

I have tried everything at my end to get the dynamic information about the current download and upload speed but unable to get it working. 
I remember that previously it was working but not anymore.
Also, tried adding "refreshInterval: 10000 # optional - in milliseconds, defaults to 10s". But this also doesn't work.

To get the latest information I have to switchh to another tab and come back to homepage.

### homepage version

v0.8.7 (05a7c0f, Jan 27, 2024)

### Installation method

Docker

### Configuration

```yaml
- Qbittorrent:
        icon: qbittorrent.png
        href: https://1.1.1.1
        siteMonitor: https://1.1.1.1
        widget:
          type: qbittorrent
          url: https://1.1.1.1
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          username: hello
          password: thanku
```

### Troubleshooting

- Qbittorrent:
        icon: qbittorrent.png
        href: https://1.1.1.1
        siteMonitor: https://1.1.1.1
        widget:
          type: qbittorrent
          url: https://1.1.1.1
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          username: hello
          password: thanku
