### DISCUSSION TITLE
Using a  env_file to pass environment variables to the docker container

### DISCUSSION THREAD

**Discussion by cesarnr21** [gethomepage/homepage#2838] [Support] [answered]
### Description

I have been trying to pass API keys to the homepage container using `env_file`. But have not been able to get it to work. I added the path to the `compose.yaml` like:
```yaml
env_file:
  - path: /path/to/.env
    required: true
```

I even used `docker compose config` to see the environment variables set on the docker compose and then variables are correct there, here is the output
```
name: homepage
services:
  homepage:
    container_name: homepage
    environment:
      HOMEPAGE_VAR_PORTAINER_API: <api_key>
      HOMEPAGE_VAR_WEATHER_API: <api_key>
    image: ghcr.io/gethomepage/homepage:latest
```

And then I followed the instructions from here, <https://gethomepage.dev/latest/installation/docker/#using-environment-secrets>

- In the `widgets.yaml` set the api key to `apiKey: {{HOMEPAGE_VAR_WEATHER_API}}`
- And I also set the variable in the `settings.yaml` file
  ```yaml
  providers:
    openweathermap: openweathermapapikey
    weatherapi: {{HOMEPAGE_VAR_WEATHER_API}}
  ```

I keep getting an API Error. I tried hard coding the actual API key in `widgets.yaml` and the key does work, so there is nothing wrong with the keys, the issue is the passing the environment variables to the container. I entered the shell of the container and I did not see the environmnet variables inside the container.

### homepage version

v0.8.7

### Installation method

Docker

### Configuration

```yaml
- openweathermap:
    label: <city> #optional
    latitude: <lat>
    longitude: <lon>
    units: imperial # or imperial
    provider: openweathermap
    apiKey: {{HOMEPAGE_VAR_WEATHER_API}}
```

### Troubleshooting

There isn't any
