### DISCUSSION TITLE
Resources grouping

### DISCUSSION THREAD

**Discussion by uchuu-me** [gethomepage/homepage#2850] [Support]
### Description

How can i put resources in to some group?

### homepage version

fc7ce0a

### Installation method

Docker

### Troubleshooting

How can i put resources in to some group?

**Comment by glime-ai** [comment]
To group resources in your Homepage configuration, you can use the `label` option within the resources configuration block in your YAML file. This allows you to name a group and assign resources to it. Here's an example of how you can group CPU and memory resources under a "System" label and disk resources under a "Storage" label:

```yaml
- resources:
    label: System
    cpu: true
    memory: true

- resources:
    label: Storage
    disk: /mnt/storage
```

If you have multiple disks and want to group them under the same label, you can pass an array of paths like this:

```yaml
- resources:
    label: Storage
    disk:
      - /mnt/storage
      - /mnt/backup
      - /mnt/media
```

Make sure to include these configurations in the appropriate section of your Docker configuration file. If you need further assistance, please provide more details about your current configuration so I can give you a more precise answer.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Reply by uchuu-me** [reply]
No, i'm talking about something like this:
```
- My_Servers:
    - Some_server_with_remote_mount:
        icon: icon
        ping: 192.168.1.2
        widget:
          type: resources <---------------------
          disk: /mnt/remote_mount_point
```
