### DISCUSSION TITLE
rootless docker and valid docker.sock api/docker/status/my-docker/goaccess returns 500

### DISCUSSION THREAD

**Discussion by structwafel** [gethomepage/homepage#2858] [Support] [answered]
### Description

I have been trying to make Homepage work for quite a bit now, and not really sure what is at fault here.

I am giving homepage my rootless docker.sock `/run/user/1000/docker.sock` which also works as I can verify from the shell:
``` bash
apk add --no-cache curl
curl --unix-socket /var/run/docker/sock http://localhost/containers/json 

curl --unix-socket /var/run/docker/sock http://localhost/containers/goaccess/json
```
So access to the socket is valid and works.

In `services.yaml` there is:
``` yaml
- My Third Group:
    - sailing-thing:
        href: http://localhost/
        description: Homepage is 😎
        server: goaccess
        container: my-docker
```
and docker.yaml:
``` yaml
my-docker:
  socket: /var/run/docker.sock
```

but on homepage the endpoint `http://hetzner:666/api/docker/stats/my-docker/goaccess` fails and returns:
`Object { message: "Cannot read properties of null (reading 'conn')" }`

My knowledge on Node/js is smol, so this is kinda where i couldn't go any further.

Same issues when using dockerproxy
Not sure why: `In order to use the socket directly homepage must be running as root`
As you can pass the user docker.socket instead.
This is for example also done in Portainer. Most docker containers have the convention to use $DOCKER_HOST for using the docker.socket

Is there anything I did wrong? (other than using rootless docket?)

compose.yaml
``` yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 666:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    #user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
networks:
  default:
    name: proxy
    external: true
```
Every container is on the `proxy` network

### homepage version

v0.8.7

### Installation method

Docker

### Troubleshooting

```
[2024-02-07T23:30:43.760Z] error: <dockerStatsService> TypeError: Cannot read properties of null (reading 'conn')
    at handler (/app/.next/server/pages/api/docker/stats/[...service].js:89:86)
    at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:365:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:303:20)
    at async Server.<anonymous> (/app/server.js:19:5)
```

**Comment by glime-ai** [comment]
Based on the information provided, it seems that you are trying to use a rootless Docker socket with Homepage, and you are encountering an error related to the Docker stats service within Homepage.

The error message `Cannot read properties of null (reading 'conn')` suggests that there might be an issue with the connection to the Docker socket or with the configuration of the Docker service within Homepage.

Here are a few things you can check and try:

1. **Socket Path**: Ensure that the socket path provided in `docker.yaml` matches the actual path of the rootless Docker socket. In your case, it should be `/run/user/1000/docker.sock` instead of `/var/run/docker.sock`. Update your `docker.yaml` to reflect the correct path:

```yaml
my-docker:
  socket: /run/user/1000/docker.sock
```

2. **Volume Mapping**: In your `compose.yaml`, you have mapped the rootless Docker socket to `/var/run/docker.sock:ro` inside the container. Make sure that this path is consistent with the path you are using in your `docker.yaml` configuration.

3. **Permissions**: Even though you are using a rootless Docker setup, there might be permission issues with the socket file. Ensure that the user inside the container (determined by `PUID` and `PGID`) has the necessary permissions to access the Docker socket.

4. **Network Configuration**: Verify that the `proxy` network configuration does not have any restrictions that could prevent the Homepage container from accessing the Docker socket.

5. **Homepage Version**: Check if there are any known issues with the version of Homepage you are using (v0.8.7) that could be causing this problem. You may want to look at the GitHub issues or discussions for any similar reports or updates.

6. **Logs and Troubleshooting**: Review the container logs for any additional error messages that could provide more insight into the issue. You can view the logs by running `docker logs homepage`.

7. **Documentation and Support**: Refer to the official Homepage documentation and support channels for any specific guidance on using rootless Docker with Homepage. You may also want to ask for help in the GitHub discussions or issues if you cannot resolve the problem.

If after checking these items the issue persists, please provide any additional error messages or logs that could help in diagnosing the problem further.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by structwafel** [comment]
Small update.

Without the dockerproxy the node user in the container coulnd't connect to the docker.sock, makes sense, my mistake.

But when i have the dockerproxy set.
curl http://dockerproxy:2375/containers/goaccess/json
Works perfectly, on the node user.

docker.yaml is also updated to:
``` yaml
my-docker:
  host: dockerproxy
  port: 2375
```

but it still responds with the same:
http://hetzner:666/api/docker/status/my-docker/goaccess 
Object { message: "Cannot read properties of null (reading 'conn')" }
