### DISCUSSION TITLE
[Feature Request] I hate money widget

### DISCUSSION THREAD

**Discussion by Flo2410** [gethomepage/homepage#2874] [Feature Requests]
### Description

[I hate money](https://ihatemoney.org) is a finance management tool.

I currently have a custom widget configured to show the current balance for three persons.
![image](https://github.com/gethomepage/homepage/assets/31217036/7ae141cf-0738-4f45-85ee-c4647f243b33)

If there is enough interest (upvotes), I would be open to implementing a widget for it to allow for an easier configuration.

### Other

My `custom widget` config:

```yaml
            
  - I hate money:
      href: https://ihatemoney.example.com/myproject
      icon: mdi-currency-eur
      widget:
        type: customapi
        url: https://ihatemoney.example.com/api/projects/myproject
        refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
        username: {{HOMEPAGE_VAR_IHATEMONEY_USER}}
        password: {{HOMEPAGE_VAR_IHATEMONEY_PW}}
        method: GET
        mappings:
          - field:
              members:
                0: balance # the 0 is the index into the array of members returned by the api
            label: Flo
            format: float
            suffix: €
          - field:
              members:
                6: balance # the 6 is the index into the array of members returned by the api
            label: Max
            format: float
            suffix: €
          - field:
              members:
                5: balance # the 5 is the index into the array of members returned by the api
            label: Engelbert
            format: float
            suffix: €
```
