### DISCUSSION TITLE
[Feature Request] ArchiSteamFarm Widget

### DISCUSSION THREAD

**Discussion by MayhemBill** [gethomepage/homepage#2893] [Feature Requests]
### Description

I would like a widget for Archi Steam Farm, github is here: https://github.com/JustArchiNET/ArchiSteamFarm

I would preferably like information for active accounts, currently farming accounts, and how many cards left to farm.

**Comment by glime-ai** [comment]
To create a widget for Archi Steam Farm (ASF) that displays information such as active accounts, currently farming accounts, and how many cards are left to farm, you would need to utilize ASF's IPC (Inter-Process Communication) API to retrieve the necessary data. The ASF IPC API provides various endpoints that can be used to obtain information about the ASF bot instances and their farming status.

However, as of my last update, there is no pre-built widget for Archi Steam Farm in the Homepage project. To implement such a widget, you would need to develop a custom service widget that interacts with the ASF IPC API. This would involve:

1. Familiarizing yourself with the ASF IPC API and identifying the endpoints that provide the data you need.
2. Generating an API key for ASF if required for authentication.
3. Creating a new widget definition in your `services.yaml` file for Homepage, specifying the type, URL, and any other necessary parameters.
4. Writing the logic to call the ASF IPC API, handle the response, and extract the relevant information to be displayed in the widget.

Since this is a custom requirement, you might need to have development skills or seek assistance from someone who can help you with the implementation. If you're not familiar with coding or the Homepage project's structure, you might want to request this feature directly from the Homepage community or contribute to the project by creating a new widget.

You can start by opening an issue on the Homepage GitHub repository to discuss this feature request with the maintainers and community. Provide details about what you would like the widget to display and any technical details you have about the ASF IPC API.

For now, you can refer to the documentation and examples of other service widgets provided by Homepage to get an idea of how to structure your widget configuration.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Reply by Macleykun** [reply]
Not making any promises, but given i asked and documented it here: https://github.com/gethomepage/homepage/discussions/1462 i'll have a look it can be done using the custom api from homepage.
I'll focus on trying to show 4 things:

CardsFarmer > CurrentGamesFarming
CardsFarmer > TimeRemaining
GamesToRedeemInBackgroundCount
IsConnectedAndLoggedOn

fetch from: /Api/Bot/{botNames}

I know this is not exactly what you want, but once i have a working example, it should be doable to get yours to work first and then adjust it to your needs usijng the steamarchi.domain/swagger page. It's a very user friendly way to learn how to use API's.

**Comment by Macleykun** [comment]
I made the following:
![image](https://github.com/gethomepage/homepage/assets/26381427/ddd42949-7e8f-444f-a825-30a515afec2f)

Using the following customapi widget config:

```yaml
    - ArchiSteamFarm:
        icon: archisteamfarm
        href: https://archisteamfarm.urdomain.ext/bots
        description: Farming Steam cards from multiple accounts.
        container: archisteamfarm
        server: my-docker
        ping: https://archisteamfarm.urdomain.ext/bots
        widget:
          type: customapi
          url: http://172.17.0.1:1242/Api/Bot/UrBotName # I used the default gateway IP of the default docker network, should work more or less universal. The last part needs to be changed to the name of your bot that logs into your account.
          method: GET
          headers:
            accept: application/json
            Authentication: 'YourIPCpassword' # https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC
          mappings:
            - field:
                Result:
                    Velocimomometer: # So if visit your steamarchifarm but go to /swagger you can click on the slot icon, enter the IPC password and then enter in the bot name. From there you can go to the bots section, do a get and you'll get a curl output in json. If you compare how that is build up with the working values here, you'll be able to figure things out easily :)
                        CardsFarmer: TimeRemaining
              label: Farming ETA
              format: text
            - field:
                Result:
                    Velocimomometer: # Ofcours replace every instance of Velocimometer with the name of your bot choosing
                        CardsFarmer: CurrentGamesFarming
              label: Farming Game
              format: float
            - field:
                Result:
                    Velocimomometer: # Do you know what reference this is btw?
                        CardsFarmer: GamesToFarm
              label: Games to farm
              format: float
            - field:
                Result:
                    Velocimomometer: IsConnectedAndLoggedOn
              label: Connected
              format: float # play around with the format aswell, the way the value you get from curl can be changed in homepage by switching from text to float or intreger for example.
```

I hope this answer helped you getting the result your looking for :)

**Reply by mgrimace** [reply]
Thanks so much for this, I tweaked it a bit for my liking: changed `connected` to show `online` or `offline` instead of a digit, and switched from `GamesToFarm` to `GamesToRedeemInBackgroundCount`

```yaml
    - ArchiSteamFarm:
        icon: archisteamfarm.png
        href: http://{{HOMEPAGE_VAR_BOT_IP}}:1242
#        description: Steam card and free game farmer
        server: docker-bots
        container: asf
        widget:
            type: customapi
            url: http://{{HOMEPAGE_VAR_BOT_IP}}:1242/Api/Bot/{{HOMEPAGE_VAR_ASF_BOT_NAME}} #enter botname in .env
            method: GET
            headers:
                accept: application/json
                Authentication: {{HOMEPAGE_VAR_IPC_KEY}} #enter key in .env
            mappings:
              - field:
                    Result:
                        {{HOMEPAGE_VAR_ASF_BOT_NAME}}: 
                            CardsFarmer: CurrentGamesFarming
                label: Farming
                format: float   
              - field:
                    Result:
                        {{HOMEPAGE_VAR_ASF_BOT_NAME}}: 
                            CardsFarmer: TimeRemaining
                label: ETA
                format: text
              - field:
                    Result:
                        {{HOMEPAGE_VAR_ASF_BOT_NAME}}: GamesToRedeemInBackgroundCount
                label: Redeeming
                format: float
              - field:
                    Result:
                        {{HOMEPAGE_VAR_ASF_BOT_NAME}}: IsConnectedAndLoggedOn
                label: Connected
                format: text 
                remap:
                  - value: false
                    to: Offline
                  - value: true
                    to: Online    
```

## To Do (need help)
- change null value to `nothing` for `CurrentGamesFarming` if nothing is presently farming (shows `0`)
- colour `online` green for `IsConnectedAndLoggedOn`

<img width="406" alt="Screen Shot 2024-03-26 at 5 34 57 PM" src="https://github.com/gethomepage/homepage/assets/55518507/aca46a73-2ae3-44a7-b085-27caddd6b63f">

**Reply by mgrimace** [reply]
Ah 'redeeming' doesn't work for plugins that are redeeming free games e.g., https://github.com/Citrinate/FreePackages - I'll have to see if there's something there as well (showing as 0 presently, but the plugin is redeeming 13 games at the moment)

**Reply by mgrimace** [reply]
> I made the following: ![image](https://private-user-images.githubusercontent.com/26381427/316328864-ddd42949-7e8f-444f-a825-30a515afec2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzMyODYsIm5iZiI6MTcxNjc3Mjk4NiwicGF0aCI6Ii8yNjM4MTQyNy8zMTYzMjg4NjQtZGRkNDI5NDktN2U4Zi00NDRmLWE4MjUtMzBhNTE1YWZlYzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAxMjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNDU1MzRkOWMwNDNjNTczMmU2YjYyY2NjZjQyYTUyZGEwNjY1YjZmYzUwNTQxZTU0NDQ0YzE0ZDgyYzFmN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TMZST127fmx87Udwls92PnkPlPNpyyaJ2p5zHT9wTo4)
> 
> Using the following customapi widget config:
> 
> ```yaml
>     - ArchiSteamFarm:
>         icon: archisteamfarm
>         href: https://archisteamfarm.urdomain.ext/bots
>         description: Farming Steam cards from multiple accounts.
>         container: archisteamfarm
>         server: my-docker
>         ping: https://archisteamfarm.urdomain.ext/bots
>         widget:
>           type: customapi
>           url: http://172.17.0.1:1242/Api/Bot/UrBotName # I used the default gateway IP of the default docker network, should work more or less universal. The last part needs to be changed to the name of your bot that logs into your account.
>           method: GET
>           headers:
>             accept: application/json
>             Authentication: 'YourIPCpassword' # https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC
>           mappings:
>             - field:
>                 Result:
>                     Velocimomometer: # So if visit your steamarchifarm but go to /swagger you can click on the slot icon, enter the IPC password and then enter in the bot name. From there you can go to the bots section, do a get and you'll get a curl output in json. If you compare how that is build up with the working values here, you'll be able to figure things out easily :)
>                         CardsFarmer: TimeRemaining
>               label: Farming ETA
>               format: text
>             - field:
>                 Result:
>                     Velocimomometer: # Ofcours replace every instance of Velocimometer with the name of your bot choosing
>                         CardsFarmer: CurrentGamesFarming
>               label: Farming Game
>               format: float
>             - field:
>                 Result:
>                     Velocimomometer: # Do you know what reference this is btw?
>                         CardsFarmer: GamesToFarm
>               label: Games to farm
>               format: float
>             - field:
>                 Result:
>                     Velocimomometer: IsConnectedAndLoggedOn
>               label: Connected
>               format: float # play around with the format aswell, the way the value you get from curl can be changed in homepage by switching from text to float or intreger for example.
> ```
> 
> I hope this answer helped you getting the result your looking for :)

Thanks, finally had a game start farming and I have NaN as the title, and the time remaining is way too many decimal places. Any suggestions? Anything you’ve ended up changing over time?

**Reply by mgrimace** [reply]
Nm, fixed it, here's an updated widget:

```yaml
 widget: 
            type: customapi
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:1242/Api/Bot/{{HOMEPAGE_VAR_ASF_BOT_NAME}} #enter botname in .env
            method: GET
            headers:
                accept: application/json
                Authentication: {{HOMEPAGE_VAR_IPC_KEY}}
            #display: list
            mappings:
              - field:
                    Result:
                        {{HOMEPAGE_VAR_ASF_BOT_NAME}}:
                            CardsFarmer:
                              CurrentGamesFarming: 
                                0: GameName
                label: Farming
                format: text
              - field:
                    Result:
                        {{HOMEPAGE_VAR_ASF_BOT_NAME}}: 
                            CardsFarmer: TimeRemaining
                label: ETA
                format: text
              - field:
                    Result:
                        {{HOMEPAGE_VAR_ASF_BOT_NAME}}: IsConnectedAndLoggedOn
                label: Connected
                format: text
                remap:
                  - value: false
                    to: Offline
                  - value: true
                    to: Online
```
