### DISCUSSION TITLE
Container cannot start when siteMonitor can't reach website

### DISCUSSION THREAD

**Discussion by frabnet** [gethomepage/homepage#2899] [Support]
### Description

Hi and thank you all for this project.
I have some problem when I restart my server: Homepage container does not start and log this error:

`Error: write EPROTO 684BA758717F0000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 112 `

This happens just at first server reboot. If I start the container manually it works.
I thought it was Reverse Proxy not starting, but If I start Homepage without Reverse Proxy, it just starts and mark service as offline, as it should.

Do anyone has any clue if this a bug that can be addressed?

### homepage version

v0.8.7

### Installation method

Docker

### Configuration

```yaml
- Jellyfin:
        icon: jellyfin
        href: https://myapp.mydomain.eu
        siteMonitor: https://myapp.mydomain.eu/web/index.html
        server: my-docker
        container: jellyfin
```

### Container Logs

[2024-02-12T09:31:56.915Z] error: <httpProxy> Error calling https://myapp.mydomain.eu/web/index.html...
[2024-02-12T09:31:56.916Z] error: <httpProxy> [
  500,
  Error: write EPROTO 684BA758717F0000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 112
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]

### Troubleshooting

---
