### DISCUSSION TITLE
Sonarr widget not loading since v4 update

### DISCUSSION THREAD

**Discussion by jjscaria** [gethomepage/homepage#2904] [Support] [answered]
### Description

Sonarr widget stopped working after updating it to v4. I am able to directly get to the API URL on the browser, but homepage is showing error. Radarr is hosted on the same machine and homepage is able to show the widget for that

Sonarr version: 4.0.1.929

I reported this earlier as well: https://github.com/gethomepage/homepage/discussions/2607#discussioncomment-8151827

![image](https://github.com/gethomepage/homepage/assets/9114566/e68b56ef-46e7-411f-8cf0-2b4a4b9ba743)

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- Shows:
        href: http://192.168.1.101:8989
        ping: http://192.168.1.101:8989
        icon: sonarr.png
        widget:
          type: sonarr
          url: http://192.168.1.101:8989
          key: apikey
```

### Container Logs

![image](https://github.com/gethomepage/homepage/assets/9114566/5b783149-aaa5-490c-b27e-dfa3ad34d49b)

### Troubleshooting

I can reach the API URL on the browser. But, unable to curl the URL from where homepage is hosted

**Comment by glime-ai** [comment]
Based on the information provided and the context from the sources, it seems that the Sonarr widget is not working after an update to Sonarr v4, even though the API URL is accessible via the browser. Since you are able to reach the API URL in the browser but not via `curl` from the Homepage host, this suggests there might be a network or configuration issue specific to the Homepage environment or container.

Here are some steps you can take to troubleshoot the issue:

1. **Check Network Configuration**: Ensure that the Homepage container can communicate with the Sonarr service. You can do this by executing a ping from within the Homepage container to the Sonarr host.

2. **Verify API Endpoint**: Make sure that the API endpoint in the widget configuration does not have a trailing slash, as per the documentation. Since Sonarr v4 might have different API endpoints, verify that the endpoint you are using is correct for Sonarr v4.

3. **Curl from Container**: Try to `curl` the Sonarr API from within the Homepage container. You mentioned that you are unable to do this, so it's important to check if `curl` is installed in the container (`apk add curl`) and then attempt to reach the Sonarr API using `curl` with the appropriate headers and API key.

4. **Check Container Logs**: Review the logs of the Homepage container for any errors or warnings that could provide more insight into the issue (`docker logs homepage`).

5. **Review Sonarr Configuration**: Ensure that the Sonarr API key is correct and that the Sonarr service allows connections from the Homepage container.

6. **Check for Open Issues**: Since you've mentioned that this issue was reported earlier, check if there are any open issues or discussions on the Homepage GitHub repository that might provide a solution or a workaround.

7. **Update Homepage**: If you are not running the latest version of Homepage, consider updating to the latest version to see if the issue has been resolved in a newer release.

8. **Ask for Help**: If you are still unable to resolve the issue, consider using the Homepage AI Bot for assistance, opening a GitHub discussion, or asking for help in the #ai-support channel on Discord.

Please provide any error messages you see when attempting to `curl` from within the Homepage container, as this will help in diagnosing the issue further.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by s3rverro0m** [comment]
This is how mine is set up and it works fine with v4 of Sonar:
```
    - Sonarr:
        icon: sonarr
        href: http://<serverIP>:8989
        service: docker
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: apikey
```
