### DISCUSSION TITLE
Anyone know if you can configure a service or bookmark to email?

### DISCUSSION THREAD

**Discussion by dnade** [gethomepage/homepage#2905] [Support] [answered]
### Description

I'm creating an in-house homepage and I'd like users to be able log into the helpdesk portal (working fine) OR email the IT team.  I tried putting mailto:xxxxx@xxx.com into the href section of a service but all it does is pop up a blank web page (_blank target is set obviously).  I also tried putting <a> tags around it but that errored out (I figured it would)... Anything I'm missing?

### homepage version

v0.8.7

### Installation method

Docker

### Configuration

```yaml
(in services.yaml)
- IT:
  - Helpdesk Portal:
      icon: /images/it.png
      href: https://xxxxxxxxxxxxxx.com/portal/registrations #obscuring actual site
      description: Submit tickets here

  - Helpdesk Email:
      icon: nextcloud-notes
      href: mailto:help@xxxxx.com #### obscuring email
      description: Or email us here!
```

### Troubleshooting

n/a
