### DISCUSSION TITLE
watchtower API in homepage error

### DISCUSSION THREAD

**Discussion by BulldozerPete** [gethomepage/homepage#2909] [Support]
### Description

Hi,

I am receiving this error when trying to connect to the watchtower API:

API Error: Unknown error
URL: http://192.168.10.3:8081/v1/metrics
Raw Error:
{
    "code": "ECONNRESET"
}

### homepage version

0.8.8

### Installation method

Docker

### Configuration

```yaml
- Watchtower:
         icon: watchtower.png
         widget:
            type: watchtower
            url: http://192.168.10.3:8081
            key: demotoken
```

### Troubleshooting

I don't know how to do this.
