### DISCUSSION TITLE
CSS handling question

### DISCUSSION THREAD

**Discussion by Cyberbeni** [gethomepage/homepage#2910] [Support] [answered]
### Description

I noticed that when reloading the page, there is a split second where it displays the page without the custom.css loaded.

![reload-upstream gif](https://github.com/gethomepage/homepage/assets/8356175/792b764a-6886-4774-a9e4-470672d78f20)

I moved css linking to the head based on mdn web docs and it seems to solve this issue and also make the reload time shorter.

![reload-modified gif](https://github.com/gethomepage/homepage/assets/8356175/f4b2b9d6-bc4e-4675-bc74-157c89b2f507)

There is still an issue with the default header style displaying for a split second, I couldn't figure that out yet. Modifying the css seems to be instantly reflected on the page as expected. I'm not a web developer, could someone please explain to me what is happening here? Isn't the current solution a server side rendered one? Or does it render once without the css then it gets the css and then updates the page? In which case I don't understand why custom.css is marked for preload now, it doesn't show up in the sources tab inside the dev console. (After my changes applied, it shows up there)

### homepage version

latest dev (ea0310548a190af11ba18fa2fd1f705bea518902)

### Installation method

Docker

### Configuration

custom.css:

```css
.service-card {
    min-height: 96px;
}

.service-card:has(.service-title:only-child) {
    display: flex;
    justify-content: center;
}

.service-card > .service-title:only-child {
    width: 100%;
}

.service-card > .service-title:only-child > .service-icon > img {
    margin-left: 32px;
    width: 48px !important;
    height: 48px !important;
}

.service-card > .service-title:only-child .service-name {
    margin-left: 24px;
    font-size: 110%;
}
```

modifications:
```diff
diff --git a/src/components/filecontent.jsx b/src/components/filecontent.jsx
deleted file mode 100644
index 1dd6266a..00000000
--- a/src/components/filecontent.jsx
+++ /dev/null
@@ -1,10 +0,0 @@
-import useSWR from "swr";
-
-export default function FileContent({ path, loadingValue, errorValue, emptyValue = "" }) {
-  const fetcher = (url) => fetch(url).then((res) => res.text());
-  const { data, error, isLoading } = useSWR(`/api/config/${path}`, fetcher);
-
-  if (error) return errorValue;
-  if (isLoading) return loadingValue;
-  return data || emptyValue;
-}
diff --git a/src/pages/index.jsx b/src/pages/index.jsx
index 4bf1d9a2..e283c8f8 100644
--- a/src/pages/index.jsx
+++ b/src/pages/index.jsx
@@ -11,7 +11,6 @@ import { serverSideTranslations } from "next-i18next/serverSideTranslations";
 import { useRouter } from "next/router";

 import Tab, { slugify } from "components/tab";
-import FileContent from "components/filecontent";
 import ServicesGroup from "components/services/group";
 import BookmarksGroup from "components/bookmarks/group";
 import Widget from "components/widgets/widget";
@@ -391,17 +390,10 @@ function Home({ initialSettings }) {
         )}
         <meta name="msapplication-TileColor" content={themes[settings.color || "slate"][settings.theme || "dark"]} />
         <meta name="theme-color" content={themes[settings.color || "slate"][settings.theme || "dark"]} />
+        <link rel="preload" href="/api/config/custom.css" as="style" />
+        <link rel="stylesheet" href="/api/config/custom.css" />
       </Head>

-      <link rel="preload" href="/api/config/custom.css" as="fetch" crossOrigin="anonymous" />
-      <style data-name="custom.css">
-        <FileContent
-          path="custom.css"
-          loadingValue="/* Loading custom CSS... */"
-          errorValue="/* Failed to load custom CSS... */"
-          emptyValue="/* No custom CSS */"
-        />
-      </style>
       <Script src="/api/config/custom.js" />

       <div className="relative container m-auto flex flex-col justify-start z-10 h-full">
```

### Troubleshooting

-
