### DISCUSSION TITLE
Unable to run on port other than 3000?

### DISCUSSION THREAD

**Discussion by rlangtind** [gethomepage/homepage#2911] [Support] [answered]
I have earlier been running Homepage on a port different to the default port 3000, but with the recent update docker ignores my port assignment.. Any idea why?

**Comment by glime-ai** [comment]
To assist you with the issue of Docker ignoring your custom port assignment after a recent update, I would need to know more about how you are configuring the port change. Typically, you can specify the port mapping in your `docker-compose.yml` file or in the `docker run` command by mapping your desired external port to the internal port that the application listens on (which is port 3000 for Homepage).

For example, in a `docker-compose.yml` file, you would have something like this to map port 8080 on the host to port 3000 in the container:

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "8080:3000"
    volumes:
      - /path/to/config:/app/config
    restart: unless-stopped
```

And for a `docker run` command, it would look like this:

```bash
docker run -p 8080:3000 -v /path/to/config:/app/config ghcr.io/gethomepage/homepage:latest
```

If you have already configured the port mapping correctly and it's not working after an update, here are a few steps you can take to troubleshoot the issue:

1. Ensure that the external port you are trying to use is not already in use by another service on your host machine.
2. Check the Docker container logs for any error messages that might indicate why the port mapping is not working.
3. Verify that there were no changes in the latest version of Homepage that might affect how port mapping is handled.
4. If you are using a `docker-compose.yml` file, ensure that it is correctly formatted and that there are no syntax errors.

If you provide the exact method you are using to change the port (docker-compose or docker run) and any relevant configuration files or commands, I can give you a more specific answer.

Remember to check the documentation and changelogs for any updates that might affect port configuration. If the issue persists, you might want to consider reporting it on the Homepage GitHub repository as a bug.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).

**Comment by bennaa** [comment]
Hi! I face a similar problem, if i map my ports as 
`ports:
      - "80:3000"`
I can access the hompage with just my ip address, but the hompage doesnt have the right background or settings.

**Comment by Dalewn** [comment]
I can confirm this.

Duplicated a working stack with port assignment "3000:3000" and assigned "8080:3000".

After deploying the stack, the background and layout are missing.
While the entire settings.yaml doesn't seem to be used at all, a custom icon is displayed even though the background isn't.

Minimal working sample:
```
version: "3.8"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    privileged: true
    container_name: homepage
    ports:
      - 8080:3000
    volumes:
      - data:/app/config # Make sure your local config directory exists
      - images:/app/public/images # for the background images
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```

Volumes are CIFS mounted folders in my case. Proper access has been verified for the container.

**Comment by shamoon** [comment]
I, on the other hand, cannot. I dont see a real reason why changing the port would affect the other stuff mentioned here unless the issue has nothing to do with homepage e.g. reverse proxy or something else.

In general, it works fine:
<img width="1840" alt="Screenshot 2024-02-21 at 1 42 20 PM" src="https://github.com/gethomepage/homepage/assets/4887959/ff1ca039-3da3-48c0-b556-91ff0d66232d">

**Comment by adamzvolanek** [comment, marked as answer]
I'm in the same boat, where I am wanting to run the service on port 80 however even when creating a docker-compose file with `80:3000` the homepage logs still report: `Listening on port 3000`.

I've tried installing from the Unraid App store, where modifying the port for TCP has no change, be it the webgui port or direct IP access. Likewise when using docker-compose, it does not update the port the container is listening to.


My docker-compose

```yaml
---
version: '3'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      fixed_homepage_ip:
        ipv4_address: ${HOMEPAGE_IP}
    environment:
      - TZ=America/Chicago
      - PORT=80
      - PUID=99
      - PGID=100
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:80]'
      - net.unraid.docker.icon='https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-512x512.png'
    ports:
      - 80:3000
    volumes:
      - /mnt/user/appdata/internal/homepage/:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
    fixed_homepage_ip:
        external: true
        name: ${UNRAID_BRIDGE_NAME}  # Specify the name of the existing bridge network in Unraid
```
