### DISCUSSION TITLE
Multiple Pi-Hole Instances, but same data in Homepage widget

### DISCUSSION THREAD

**Discussion by wpattison74** [gethomepage/homepage#2917] [Support] [answered]
### Description

Hey all, I'm seeing some weirdness where I have two Pi-Hole instances, and both have a widget on Homepage - but both widget's are displaying only the first Pi-Hole stats.  I'll post screenshots here showing the configuration and behavior.

<img width="443" alt="homepagewidget" src="https://github.com/gethomepage/homepage/assets/95833680/f6472258-5b65-43cc-af39-f717df4d30cf">
<img width="539" alt="homepage_service_config" src="https://github.com/gethomepage/homepage/assets/95833680/4d50d612-0a9d-43e2-a530-f6dffbe01eea">
<img width="1678" alt="pihole_num_1" src="https://github.com/gethomepage/homepage/assets/95833680/f3a7e523-fad2-43d4-ad43-28ae99e44fa2">
<img width="1902" alt="pihole_num_2" src="https://github.com/gethomepage/homepage/assets/95833680/3dea21dd-7e78-44ba-b730-075eb1d01089">

### homepage version

v0.8.8

### Installation method

Docker

### Configuration

```yaml
- PiHole:
        icon: pi-hole.png
        href: http://192.168.1.244/admin/
        description: PiHole Privacy DNS
        widget:
          type: pihole
          url: http://192.168.1.244
          key: dff03f45f1ec3e45d17b7df137944623d365c46b8457c652f0da2d20c0a71f94

    - PiHole:
        icon: pi-hole.png
        href: http://192.168.1.10/admin/
        description: PiHole Privacy DNS (New RPI5)
        widget:
          type: pihole
          url: http://192.168.1.10
          key: 3b02357602c634d74165cfb0f4a3fe45dc9a5c5cd082d0e444cbde6e92c18381
```

### Troubleshooting

- two separate pi-hole instances with different passwords (to prove API key is different for both)
- defined widgets for both pi-hole's in homepage service config
