### DISCUSSION TITLE
Just updated from 0.8.7 to 0.8.8 and all the (Docker based) API's broke.

### DISCUSSION THREAD

**Discussion by Archigos** [gethomepage/homepage#2918] [Support] [answered]
### Description

All my modules that use the API for Docker give the following error:
`API Error: connect EACCES /var/run/docker.sock`
I can still click the Container name to open the web interface for it with no problem, just the Health status is broken. My native apps (like Sonarr, etc) the API still works fine.

I have not changed any settings for Docker and they have worked in the past. I upgraded the container via Dockge (which I've done in the past as well).

(System Info if it helps)
Docker Desktop (latest version) running on iMac macOS Ventura 13.6.3
9 Total Containers.

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
docker-compose.yml

version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: 501
      PGID: 20
    restart: unless-stopped

config/docker.yml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

AeroMaster-Docker:
    socket: /var/run/docker.sock
```

### Container Logs

homepage  | [2024-02-16T00:31:37.703Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
homepage  |     at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
homepage  | [2024-02-16T00:31:37.712Z] error: <dockerStatsService> Error: connect EACCES /var/run/docker.sock
homepage  |     at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
homepage  | [2024-02-16T00:31:37.735Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
homepage  |     at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

(There's 9 containers, so this replicates 9 times on every refresh of the page, I just didn't you'd want to see that much)

### Troubleshooting

Only troubleshooting I've tried so far was: (
1. After the update and saw the errors, restart the container again (via Dockge)
2. Still saw errors, went to the physical computer, restarted 'homepage' and 'Dockge' via 'docker compose down' 'docker compose up -d'
3. Still saw errors, shut down Docker Desktop, waited 5 minutes, restarted DD
4. Rebooted the iMac
