### DISCUSSION TITLE
Cannot start docker container

### DISCUSSION THREAD

**Discussion by mat-m** [gethomepage/homepage#2923] [Support]
### Description

I'm trying to install Homepage on a Raspberry Pi 2 with docker compose

dkc is an alias:

```
❯ dkc down && dkc up -d
Removing homepage ... done
Removing network hpg_default
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "hpg_default" with the default driver
Creating homepage ... done
❯ dkc logs -f
Attaching to homepage
homepage exited with code 139

```

Log is very short, although debug is enabled in config

### homepage version

v0.8.8

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
#      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
#
```

### Container Logs

Attaching to homepage
homepage exited with code 139

### Troubleshooting

Tried to set log_level to debug
