### DISCUSSION TITLE
[Feature Request] Proxmox List VM/LXC Veritcal

### DISCUSSION THREAD

**Discussion by ctv99** [gethomepage/homepage#2924] [Feature Requests]
### Description

``list each with 2 Statuses added 

1. running/stopped
2. uptime

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc

they return an array and would want all listed in id order.

the new custome api vertical should be usable for manually doing it but i cant seem to make it work as of yet.

        icon: proxmox.png
        target: _blank
        widget:
          type: customapi
          url: https://ip/api2/json/nodes/(nodeid)/qemu
          display: list
          headers:
            Authorization: PVEAPIToken=(username)=(API)
          mappings:
            - field: 
                data: 
                  0: name
              additionalField: 
                0: cpus
            - field: 
                data: 
                  1: name
              additionalField:
                field:
                  data:
                    1: cpus
                format: number
            - field: 
                data: 
                  2: name
              additionalField:
                field:
                  data:
                    2: cpus
                format: number
            - field: 
                data: 
                  3: name
              additionalField:
                field:
                  data:
                    3: cpus
                format: number

**Comment by glime-ai** [comment]
To list each VM or container with their statuses (running/stopped) and uptime, you can use the Proxmox API endpoints for QEMU VMs and LXC containers. The endpoints are:

- For QEMU VMs: `/nodes/{node}/qemu`
- For LXC containers: `/nodes/{node}/lxc`

These endpoints return an array of objects, each representing a VM or container. You can sort these arrays by the `vmid` (ID) to list them in order.

To use these endpoints with the custom API widget in Homepage, you need to configure the widget with the correct URL, headers (including the authorization token), and mappings to display the desired fields.

Here's an example configuration for the custom API widget to list QEMU VMs:

```yaml
widget:
  type: customapi
  url: https://proxmox.host.or.ip:8006/api2/json/nodes/{node}/qemu
  headers:
    Authorization: PVEAPIToken={username}={API}
  mappings:
    - field: 
        path:
          to: name
      label: Name
    - field: 
        path:
          to: status
      label: Status
    - field: 
        path:
          to: uptime
      label: Uptime
      format: relativeDate
```

Replace `{node}`, `{username}`, and `{API}` with the actual node ID, username, and API token respectively. The `format: relativeDate` will display the uptime in a human-readable relative format (e.g., "2 hours ago").

Please note that the `url` must be the full API endpoint URL, and you must have the correct permissions set up in Proxmox to access these endpoints with the API token.

If you need further assistance with the specific configuration or if you encounter any issues, please provide more details about the problem you're facing, and I'll be happy to help you troubleshoot.

---

Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

This comment was generated by [Glime](https://glimelab.ai/).
