### DISCUSSION TITLE
Homepage can't reach any APIs

### DISCUSSION THREAD

**Discussion by OddMagnet** [gethomepage/homepage#2932] [Support]
### Description

I'm running Homepage behind a reverse proxy (Traefik) on my Unraid server.
Everything is installed via docker-compose and everything is on the same Network in Docker.
Homepage is configured via docker labels.
My domain points to my internal network IP (192.168.178.xxx)
I can access the services via `service.domain.com`
Homepage can't reach any API via `service.domain.com`
When I use  networks internal IP (172.18.0.xx) it works

For the purpose of brevity I've reduced the contents of my configuration to a minimum

### homepage version

v0.8.8

### Installation method

Docker

### Configuration

```yaml
services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR}/traefik:/etc/traefik/
      - ${CONFIG_DIR}/traefik/logs:/logs
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=webSecure
      - traefik.http.routers.api.rule=Host(`${TRAEFIK_SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.api.service=api@internal
    # Homepage Service
      - homepage.group=Proxy & Identity
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=https://${TRAEFIK_SUBDOMAIN}.${DOMAIN}
      - homepage.description=Reverse Proxy
    # Homepage Widget
      - homepage.widget.type=traefik
      - homepage.widget.url=https:${TRAEFIK_SUBDOMAIN}.${DOMAIN}

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/homepage/config:/app/config
      - ${CONFIG_DIR}/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
     - traefik.enable=true
     - traefik.http.routers.homepage.entrypoints=webSecure
     - traefik.http.routers.homepage.rule=Host(`${DASHBOARD_SUBDOMAIN}.${DOMAIN}`)

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${MEDIA_DIR}:/data/media
    devices:
      - '/dev/dri:/dev/dri'
    environment:
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=https://${JELLYFIN_SUBDOMAIN}.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=webSecure
      - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_SUBDOMAIN}.${DOMAIN}`)
      # Homepage Services
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=https://${JELLYFIN_SUBDOMAIN}.${DOMAIN}
      - homepage.description=Netflix, but on your server
      # Homepage Widgets
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://${JELLYFIN_SUBDOMAIN}.${DOMAIN}
      - homepage.widget.key=${JELLYFIN_API_TOKEN}
      - homepage.widget.fields=["movies", "series", "episodes", "songs"]
      - homepage.widget.enableBlocks=true
```

### Container Logs

[2024-02-17T22:59:16.375Z] error: <httpProxy> Error calling https://jelly.domain.com/emby/Sessions...
[2024-02-17T22:59:16.375Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND jelly.domain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'jelly.domain.com'
  }
]
[2024-02-17T22:59:21.403Z] error: <httpProxy> Error calling https://jelly.domain.com/emby/Sessions...
[2024-02-17T22:59:21.403Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND jelly.domain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'jelly.domain.com'
  }
]

### Troubleshooting

1. No trailing slash in the URLs
2. The `docker exec homepage ping jellyfin` command works
3. When trying to `curl` to an API from inside the homepage container, it fails with: `curl: (6) Could not resolve host: jelly.domain.com` 
4. When trying `ping jelly.domain.com` it gives me a `bad address 'jelly.domain.com'`, pinging `domain.com` however works
