### DISCUSSION TITLE
ZeroSSL Widget

### DISCUSSION THREAD

**Discussion by Hackashaq666** [gethomepage/homepage#2937] [General]
![image](https://github.com/gethomepage/homepage/assets/11585615/365a5ba1-f6da-4438-b42c-413e180d2da6)

```
    - ZeroSSL:
        href: https://app.zerossl.com/certificates/issued
        icon: /icons/zerossl.png
        siteMonitor: https://app.zerossl.com
        widget:
          type: customapi
          url: https://api.zerossl.com/certificates?access_key=YOUR_KEY_FROM_app.zerossl.com/developer
          mappings:
            - field: 
                results: 
                  0: common_name
              label: Domain
            - field: 
                results: 
                  0: created
              format: date
              dateStyle: short 
              label: Created
            - field: 
                results: 
                  0: expires
              format: date
              dateStyle: short
              label: Expires
```

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the context provided, it appears that you are configuring a `customapi` widget for ZeroSSL to display information about SSL certificates such as the domain name, creation date, and expiration date. The configuration snippet you've provided is mostly correct, but there are a few things to consider:

1. Ensure that `YOUR_KEY_FROM_app.zerossl.com/developer` is replaced with your actual access key from ZeroSSL.
2. The `url` should be the endpoint provided by ZeroSSL for accessing certificate details, and it should include your access key as a query parameter.
3. The `mappings` section is used to map the data from the API response to the fields you want to display in the widget. Make sure that the path specified in the `field` matches the structure of the JSON response from the ZeroSSL API.

Here is the corrected configuration snippet with placeholders for your actual access key:

```yaml
widget:
  type: customapi
  url: https://api.zerossl.com/certificates?access_key=YOUR_ACTUAL_ACCESS_KEY
  mappings:
    - field: 
        results: 
          0: common_name
      label: Domain
    - field: 
        results: 
          0: created
      format: date
      dateStyle: short 
      label: Created
    - field: 
        results: 
          0: expires
      format: date
      dateStyle: short
      label: Expires
```

Please replace `YOUR_ACTUAL_ACCESS_KEY` with the access key you obtained from ZeroSSL. If you need further assistance with the API response structure or have any other questions, feel free to ask.

This comment was generated by [Glime](https://glimelab.ai/).
