### DISCUSSION TITLE
Adguard: API Error: Invalid data

### DISCUSSION THREAD

**Discussion by itsgiff** [gethomepage/homepage#2939] [Support]
### Description

Receiving API Error: Invalid data error:

```
    API Error: Invalid data
    URL: http://10.10.1.250/control/stats
    Response Data:
    <!DOCTYPE html>
    <html>
        <body>
            <input type="hidden" id="http" name="http" value="5000">
            <input type="hidden" id="https" name="https" value="5001">
            <input type="hidden" id="prefer_https" name="prefer_https" value="false">
        </body>
        <script type="text/javascript">
            var protocol=location.protocol;
            var port=location.protocol === "https:" ? 5001 : 5000;
            var URL=protocol+"//"+location.hostname+":"+port+location.pathname+location.search;
            location.replace(URL);
        </script>
    </html>
```

with the following configuration: 

```
    -  Adguard:
        href: http://10.10.1.250
        ping: http://10.10.1.250
        icon: mdi-shield
        server: storage
        container: adguard     
        widget:
            type: adguard
            fields: ["queries", "blocked", "filtered", "latency"]
            url: http://10.10.1.250
            username: admin
            password: <REDACTED>

```

### homepage version

v0.107.44

### Installation method

Docker

### Configuration

```yaml
-  Adguard:
        href: http://10.10.1.250
        ping: http://10.10.1.250
        icon: mdi-shield
        server: storage
        container: adguard     
        widget:
            type: adguard
            fields: ["queries", "blocked", "filtered", "latency"]
            url: http://10.10.1.250
            username: admin
            password: <REDACTED>
```

### Troubleshooting

Validated curl commands from inside container and external

Home Assistant Plugin functioning properly and pulling correct stats.
