### DISCUSSION TITLE
API Error Information for widgets like jellyfin, paperless, portainer etc.

### DISCUSSION THREAD

**Discussion by Anilo1990** [gethomepage/homepage#2940] [Support]
### Description

Hello everyone,

I get the following errors in the widgets on my homepage:
![grafik](https://github.com/gethomepage/homepage/assets/16625964/f67c2792-701f-49d0-b6e6-dc8de4f0684a)

This is how it is configured in NPM
![grafik](https://github.com/gethomepage/homepage/assets/16625964/2e742e7e-b160-43c5-a167-041876368ac2)
![grafik](https://github.com/gethomepage/homepage/assets/16625964/bd8f7306-9310-434d-a7f6-594a6652aa3a)

DNS Rewrite in Adguard
![grafik](https://github.com/gethomepage/homepage/assets/16625964/369db6b9-3c92-4e61-a354-7d08673593c3)

I hope someone here can help me out with this issue.
Thanks a lot!

### homepage version

0.8.8

### Installation method

Docker

### Configuration

```yaml
Docker-Compose in Portainer:

version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1026
      PGID: 100
    ports:
      - 3001:3000
    volumes:
      - /volume2/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker

networks:
 docker:
  name: docker
  external: true

----

Services.yaml
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.mydomain.de
        widget:
          type: jellyfin
          url: http://jellyfin.mydomain.de
          key: c2003525f1954e2a8e4cd3def080daee

    - Portainer:
        icon: portainer.png
        href: https://portainer.mydomain.de
        widget:
          type: portainer
          url: https://portainer.mydomain.de
          env: 2
          key: ptr_Pgm50bqmOTjy8nkwnij+olXK4gIKzCQazH7PBoUfKB0=

    - Paperless NGX:
        icon: paperless-ng.png
        href: http://paperless.mydomain.de
        widget:
          type: paperlessngx
          url: http://paperless.mydomain.de
          username: admin
          password: d7#4S32KR#7hhB7s2QG#g%
```

### Container Logs

  Error: getaddrinfo ENOTFOUND paperless.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'paperless.mydomain.de'
  }
]
[2024-02-19T11:17:04.170Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless.mydomain.de/api/statistics/?format=json
[2024-02-19T11:17:08.638Z] error: <httpProxy> Error calling http://jellyfin.mydomain.de/emby/Sessions...
[2024-02-19T11:17:08.638Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND jellyfin.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.mydomain.de'
  }
]
[2024-02-19T11:17:13.715Z] error: <httpProxy> Error calling http://jellyfin.mydomain.de/emby/Sessions...
[2024-02-19T11:17:13.716Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND jellyfin.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.mydomain.de'
  }
]
[2024-02-19T11:17:18.748Z] error: <httpProxy> Error calling http://jellyfin.mydomain.de/emby/Sessions...
[2024-02-19T11:17:18.748Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND jellyfin.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.mydomain.de'
  }
]
[2024-02-19T11:17:23.780Z] error: <httpProxy> Error calling http://jellyfin.mydomain.de/emby/Sessions...
[2024-02-19T11:17:23.781Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND jellyfin.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.mydomain.de'
  }
]
[2024-02-19T11:17:24.242Z] error: <httpProxy> Error calling https://portainer.mydomain.de/api/endpoints/2/docker/containers/json...
[2024-02-19T11:17:24.242Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND portainer.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'portainer.mydomain.de'
  }
]
[2024-02-19T11:17:24.242Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://portainer.mydomain.de/api/endpoints/2/docker/containers/json?all=1
[2024-02-19T11:17:24.244Z] error: <httpProxy> Error calling http://jellyfin.mydomain.de/emby/Items/Counts...
[2024-02-19T11:17:24.244Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND jellyfin.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'jellyfin.mydomain.de'
  }
]
[2024-02-19T11:17:24.245Z] error: <httpProxy> Error calling https://nextcloud.mydomain.de/ocs/v2.php/apps/serverinfo/api/v1/info...
[2024-02-19T11:17:24.246Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND nextcloud.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'nextcloud.mydomain.de'
  }
]
[2024-02-19T11:17:24.246Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nextcloud.mydomain.de/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2024-02-19T11:17:24.247Z] error: <httpProxy> Error calling http://paperless.mydomain.de/api/statistics/...
[2024-02-19T11:17:24.247Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND paperless.mydomain.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3007,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'paperless.mydomain.de'
  }
]
[2024-02-19T11:17:24.248Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://paperless.mydomain.de/api/statistics/?format=json

### Browser Logs

Gemischte (unsichere) Anzeige-Inhalte von "https://simpleicons.org/icons/printables.svg" werden auf einer sicheren Seite geladen
homepage.mydomain.de
Gemischte (unsichere) Anzeige-Inhalte von "http://simpleicons.org/icons/printables.svg" werden auf einer sicheren Seite geladen
homepage.mydomain.de
Gemischte (unsichere) Anzeige-Inhalte von "https://simpleicons.org/icons/snapcraft.svg" werden auf einer sicheren Seite geladen
homepage.mydomain.de
Gemischte (unsichere) Anzeige-Inhalte von "http://simpleicons.org/icons/snapcraft.svg" werden auf einer sicheren Seite geladen
homepage.mydomain.de
XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  63ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=paperlessngx&group=Filesharing&service=Paperless+NGX&endpoint=statistics
[HTTP/2 500  149ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=nextcloud&group=Filesharing&service=Nextcloud&endpoint=serverinfo
[HTTP/2 500  132ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Count&query={"refreshInterval":60000}
[HTTP/2 500  95ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=portainer&group=Administration&service=Portainer&endpoint=docker/containers/json&query={"all":1}
[HTTP/2 500  116ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=portainer&group=Administration&service=Portainer&endpoint=docker/containers/json&query={"all":1}
[HTTP/2 500  64ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  62ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=paperlessngx&group=Filesharing&service=Paperless+NGX&endpoint=statistics
[HTTP/2 500  82ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=nextcloud&group=Filesharing&service=Nextcloud&endpoint=serverinfo
[HTTP/2 500  84ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Count&query={"refreshInterval":60000}
[HTTP/2 500  82ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  13ms]

Die Ressource unter "https://homepage.mydomain.de/api/config/custom.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. homepage.mydomain.de
XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  12ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  14ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  22ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  15ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  12ms]

Error: Promised response from onMessage listener went out of scope 2 build.js:2:92650
XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  13ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  14ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  13ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  16ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  12ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/2 500  59ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=nextcloud&group=Filesharing&service=Nextcloud&endpoint=serverinfo
[HTTP/2 500  89ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Count&query={"refreshInterval":60000}
[HTTP/2 500  88ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=portainer&group=Administration&service=Portainer&endpoint=docker/containers/json&query={"all":1}
[HTTP/2 500  87ms]

XHRGET
https://homepage.mydomain.de/api/services/proxy?type=paperlessngx&group=Filesharing&service=Paperless+NGX&endpoint=statistics
[HTTP/2 500  91ms]

### Troubleshooting

1. I'm running homepage in a network called "docker" in portainer. I know that communication between networks is restricted when the docker components are not in the same network. I tried also "network_mode: host" but same error.
2. I renewed all API keys
3. I tried to play around with the href adress in services.yaml
