### DISCUSSION TITLE
TypeError: Cannot read properties of null (reading 'conn')

### DISCUSSION THREAD

**Discussion by Gerry546** [gethomepage/homepage#2942] [Support]
### Description

I recently moved to Homepage from Heimdall and I'm trying to get the docker integration working but am getting a lot of API errors.
Specifically TypeError: Cannot read properties of null (reading 'conn'). 

However I doubt it is the configuration of socket-proxy itself as I multiple other containers correctly working with it (like Portainer).

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
My configuration is as follows:

I have all containers which need acces to the Docker socket behind a socket-proxy. So also Homepage. I followed the documentation.

- Socket proxy :
<pre>services:
  ########################################################################
  # Socket-proxy - Security Enchanced Proxy for Docker Socket
  ########################################################################
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    networks:
      socket_proxy:
        ipv4_address: $SOCKETPROXY_IP
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Portainer
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer
 </pre>

- Homepage:
<pre>
services:
  ########################################################################
  # Homepage - Container dashboard
  ########################################################################
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      home_internal:
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homepage-http-router.entrypoints=https"
      - "traefik.http.routers.homepage-http-router.rule=Host(`$DOMAINNAME_CLOUD_SERVER`,`www.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.homepage-http-router.tls=true"
      - "traefik.http.routers.homepage-http-router.middlewares=chain-oauth@file"
      - "traefik.http.routers.homepage-http-router.service=homepage-http-service"
      - "traefik.http.services.homepage-http-service.loadbalancer.server.port=3000"
</pre>

- docker.yaml
<pre>
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

my-docker:
  host: socket-proxy
  port: 2375

# my-docker:
#   socket: /var/run/docker.sock
</pre>
```

### Container Logs

<pre>
19-02-2024
18:26:39
[2024-02-19T17:26:39.125Z] error: <dockerStatusService> TypeError: Cannot read properties of null (reading 'conn')
19-02-2024
18:26:39
    at handler (/app/.next/server/pages/api/docker/status/[...service].js:89:86)
19-02-2024
18:26:39
    at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:15)
19-02-2024
18:26:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19-02-2024
18:26:39
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
19-02-2024
18:26:39
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
19-02-2024
18:26:39
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
19-02-2024
18:26:39
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:365:29)
19-02-2024
18:26:39
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:303:20)
19-02-2024
18:26:39
    at async Server.<anonymous> (/app/server.js:19:5)
</pre>

### Browser Logs

![image](https://github.com/gethomepage/homepage/assets/59296539/c887e8ae-b03f-466b-976b-c7e27c850259)

### Troubleshooting

See output of the other fields.
