### DISCUSSION TITLE
Pfsense show status for all interfaces

### DISCUSSION THREAD

**Discussion by D4Bugi** [gethomepage/homepage#2945] [Support] [answered]
### Description

Hi
Is it possible to get the pfsense service to show status of all interfaces?
![Skärmbild 2024-02-20 122738](https://github.com/gethomepage/homepage/assets/158157770/53e363f1-cb58-4ff6-8d41-edb7ac79e519) so like this but not just for the Wan interface

My services.yaml looks like this

- pFsense:
        icon: si-pfsense
        href: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
        #ping: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
        widget:
         type: pfsense
         url: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
         username: "{{HOMEPAGE_VAR_PFSENSE_USER}}"
         password: "{{HOMEPAGE_VAR_PFSENSE_PWD}}"
         fields: ["wanStatus", "load", "lanStatus"]
         wan: hn0
         lan: hn1

the lan parts was just for testing and didin´t work. Am i doing something wrong or is this not possible?

- DaBug

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- pFsense:
        icon: si-pfsense
        href: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
        #ping: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
        widget:
         type: pfsense
         url: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
         username: "{{HOMEPAGE_VAR_PFSENSE_USER}}"
         password: "{{HOMEPAGE_VAR_PFSENSE_PWD}}"
         fields: ["wanStatus", "load", "lanStatus"]
         wan: hn0
         lan: hn1
```

### Troubleshooting

-
