### DISCUSSION TITLE
Speedtest-tracker widget

### DISCUSSION THREAD

**Discussion by theliamllyd** [gethomepage/homepage#2948] [Support] [answered]
### Description

Hi there, I have just deployed a new update / version of speedtest-tracker by linuxserver via docker. Strange thing is my previous version displayed everything in mbit/s and now everything is in tbits/s. Does anybody have this same experience?

### homepage version

V0.8.8 (87d1ea4)

### Installation method

Docker

### Configuration

```yaml
# -- Speedtest Tracker Start -- #
            - Speedtest Tracker:
                icon: speedtest-tracker.png
                href: http://192.168.x.xxx:8080
                description: Internet Speedtest Tracker
                server: local
                container: speedtest-tracker
                widget:
                       type: speedtest
                       url: http://192.168.x.xxx:8080
# -- Speedtest Tracker End -- #
```

### Troubleshooting

Checked all documentation.
