### DISCUSSION TITLE
Application error

### DISCUSSION THREAD

**Discussion by gustavbnm** [gethomepage/homepage#295] [Support]
Hey,
I'm going to start off by saying I'm new to using Docker so my know-how is quite low. 

I'm using Portainer Using docker-compose I got it up and running. To get the config files (which I made a volume for) tried using a file manager docker container and it let me see the files but as I refreshed the homepage page I got the message:
 `Application error: a client-side exception has occurred (see the browser console for more information).`  
looking at the console I saw 
`TypeError: Cannot read properties of undefined (reading 'tag_name')`,
`GET http://192.168.1.86:3000/locales/en-SE/common.json 404 (Not Found)`, and 
`Unchecked runtime.lastError: The message port closed before a response was received.`

If anyone knows what I messed up and/or how to fix it I would be very grateful.

**Comment by benphelps** [comment]
Would need to see your configuration files.

**Reply by gustavbnm** [reply]
I can't find where the config files are 🥲 I tried searching where to find them but no luck. I do hope this is enought. 
![image](https://user-images.githubusercontent.com/30975975/192605232-a9843be1-a12a-4d7b-aa9c-3a87c6a0a64f.png)

Heres the log as well if it helps
```
Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
docker.yaml was copied to the config folder
bookmarks.yaml was copied to the config folder
[Error: ENOENT: no such file or directory, open '/app/config/widgets.yaml'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/config/widgets.yaml'
}
widgets.yaml was copied to the config folder
settings.yaml was copied to the config folder
services.yaml was copied to the config folder
Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Reply by gustavbnm** [reply]
btw if it is the .yaml files in app/config I did find them

**Reply by benphelps** [reply]
Yes, your homepage config files.

**Reply by gustavbnm** [reply]
docker.yaml
```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   
```
services.yaml
```

# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
```

setting.yaml
```

# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

```
wigets.yaml
```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
```

bookmarks.yaml was emty
