### DISCUSSION TITLE
[Feature Request] Add generic widget that supports scraping prometheus metrics format

### DISCUSSION THREAD

**Discussion by potchin** [gethomepage/homepage#2969] [Feature Requests] [answered]
### Description

Similar to the `customapi` widget, it would be really useful to have a widget that was able to parse the prometheus (aka openmetrics) metrics text format ([docs](https://prometheus.io/docs/instrumenting/exposition_formats/)). This format is exposed by a lot of services. I'm particularly interested in it for [bitmagnet](https://bitmagnet.io/endpoints.html) but having a generic provider seems more valuable. 

Implementation would be very similar to `customapi`, just with a different parser and I would expect the `field` to refer to the metric name and labels rather than the path to a yaml object.

Example metrics snippet:

```
# HELP bitmagnet_dht_crawler_persisted_total A counter of persisted database entities.
# TYPE bitmagnet_dht_crawler_persisted_total counter
bitmagnet_dht_crawler_persisted_total{entity="Torrent"} 313104
bitmagnet_dht_crawler_persisted_total{entity="TorrentsTorrentSource"} 303028
# HELP bitmagnet_dht_ktable_hashes_added Total number of hashes added to routing table.
# TYPE bitmagnet_dht_ktable_hashes_added counter
bitmagnet_dht_ktable_hashes_added 1528
# HELP bitmagnet_dht_ktable_hashes_count Number of hashes in routing table.
# TYPE bitmagnet_dht_ktable_hashes_count gauge
bitmagnet_dht_ktable_hashes_count 1528
```

Proposed configuration (copied from `customapi`)

```
widget:
  type: custommetrics
  url: http://custom.api.host.or.ip:port/path/to/metrics
  refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
  username: username # auth - optional
  password: password # auth - optional
  method: GET # optional, e.g. POST
  headers: # optional, must be object, see below
  mappings:
    - field: bitmagnet_dht_crawler_persisted_total{entity="Torrent"}
      label: Discovered Torrents
      format: text # optional - defaults to text
```
