### DISCUSSION TITLE
[Feature Request]  Suwayomi aka tachidesk-server Widget

### DISCUSSION THREAD

**Discussion by Dalewn** [gethomepage/homepage#2972] [Feature Requests] [answered]
### Description

I would like to have a widget for suwayomi (formerly known as tachidesk-server) that displays the number of chapters of a given category that can be filtered by 

- download and 
- reading status

A contributor of suwayomi already has a working prototype (see screenshot below).

### Other

This is just a sample:
![image](https://github.com/gethomepage/homepage/assets/43420891/727514a7-366e-40c7-b1af-0b8e97a1e4bb)

**Comment by Robonau** [comment]
(im the Suwayomi dev with the prototype)
(im not gonna submit it as a pr till this gets 10 upvotes as the [guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines) say)
i currently have    
```yml 
- My First Group:
    - Suwayomi:
        icon: https://raw.githubusercontent.com/Suwayomi/Suwayomi-Server/master/server/src/main/resources/icon/faviconlogo.png
        # should probably pr the suwayomi icon to the icon repo, but it might change soon so il wait
        widget:
          type: suwayomi
          url: http://suwayomi:4567
          username: username # if u have basic auth setup
          password: password # if u have basic auth setup
          readCount: true # to enable/disable block defaults enabled
          downloadCount: true # to enable/disable block defaults enabled
          downloadedUnread: true # to enable/disable block defaults enabled
          category: all # to use a given categoryID defaults to all
```
![image](https://github.com/gethomepage/homepage/assets/30987265/04dce1cd-3193-4b2f-9bda-5ed6d0c699ea)

i have had to use a custom proxy to get the category id in the Graphql body
it also allowed me to do the processing on the server to minimise the data being sent to the client
and the enable/disable blocks
