### DISCUSSION TITLE
SABnzbd widget shows rate as MBit/s

### DISCUSSION THREAD

**Discussion by Roycinger** [gethomepage/homepage#2989] [Support] [answered]
### Description

As the title says, the SABnzbd widget shows rate as MBit/s
![image](https://github.com/gethomepage/homepage/assets/7791335/4fa9a976-29b9-461a-9e74-63fab786a442)
Is it possible to set it to show MB/s instead of MBit/s?

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- SABnzbd:
        icon: sabnzbd.svg
        href: http://192.168.178.2:8081
        description: Usenet downloader
        ping: 192.168.178.2
        widget:
            type: sabnzbd
            url: http://192.168.178.2:8081
            key: <removed>
```

### Troubleshooting

not relevant
