### DISCUSSION TITLE
Unable to configure widgets

### DISCUSSION THREAD

**Discussion by CodeWithCJ** [gethomepage/homepage#2991] [Support] [answered]
### Description

I tried to add widget for glances and adguard. but shows missing error.

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    temperature: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank


widget:
  type: adguard
  url: http://192.168.0.11:3000
  username: myuser
  password: mypassword
```

### Troubleshooting

i tried to add "- widget" and as well as just "widget". Also tried to adjust spacing but nothing worked. widgets.yaml is the file i tried to append at the last. restarting docker also didn't help.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems like there might be an issue with the structure of your `widgets.yaml` configuration file. The configuration for the AdGuard widget should be part of a service block, and it should be properly indented to reflect the hierarchy of the configuration. Additionally, the `widget` configuration for AdGuard should be a list item (indicated by a dash `-`) since you can have multiple widgets.

Here's how you might structure your `widgets.yaml` file:

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    temperature: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- adguard:
    widget:
      - type: adguard
        url: http://192.168.0.11:3000
        username: myuser
        password: mypassword
```

Make sure that the indentation is consistent, as YAML is sensitive to whitespace. Each level of indentation typically consists of two spaces.

If you continue to experience issues, please ensure that:

1. The URL provided does not end with a trailing slash, as per the documentation.
2. The AdGuard service is accessible from the Homepage instance running in Docker.
3. The username and password are correct and have the necessary permissions.

If the problem persists, you may want to use the troubleshooting steps provided in the documentation, such as checking the container logs for errors or using `curl` to manually check the API response from the AdGuard service.

Remember to replace sensitive information such as passwords before sharing your configuration publicly.

Please try updating your configuration with the suggested changes and let me know if the issue persists. If you need further assistance, please provide any error messages you are seeing in the container or browser logs.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by shamoon** [reply]
The bot is wrong, you cant put adguard in widgets.yaml, that needs to go in services.yaml

**Reply by shamoon** [reply]
Also it should be 

```
- Group Name:
     - Service name:
          ...
          widget:
```

Look at the default config files

**Reply by CodeWithCJ** [reply]
sorry. I didn't understand. should it go to widgets.yaml or services.yaml? I tried to add inside both and didn't work. I used the code you provided.

**Reply by CodeWithCJ** [reply]
Could you tell me where to add? i tried in services.yaml and it didn't work.

``
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome
        widget:
          - type: adguard
            url: http://192.168.0.11:3000
            username: user
            password: password

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
   
``

**Reply by shamoon** [reply, marked as answer]
I just copied and pasted the bot, thats also wrong bot.

```
- Group:
     - Service:
          ...
          widget:
               type:
               url:
               ...
```

in services.yaml
