### DISCUSSION TITLE
Help to add Glances services in homepage

### DISCUSSION THREAD

**Discussion by CodeWithCJ** [gethomepage/homepage#2997] [Support] [answered]
### Description

I can access glances via http://192.168.0.11:61208. But when I try to add in services.yml file its show error in the browser when viewed. 

![image](https://github.com/gethomepage/homepage/assets/151883488/eb40a371-60fb-4c3c-8bac-c7207e805c78)

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best
  

- Adguard:
     - Service:
          widget:
               type: adguard
               url: http://192.168.0.11:3000
               username: SparkyAdguard
               password: Adguard123$

  

- Usage:
     - Service:
          widget:
               type: glances
               url: http://192.168.0.11:61208
               cpu: true # optional, enabled by default, disable by setting to false
               mem: true # optional, enabled by default, disable by setting to false
               cputemp: true # disabled by default
               uptime: true # disabled by default
               disk: / # disabled by default, use mount point of disk(s) in glances. Can also be a list (see below)
               expanded: true # show the expanded view
               label: MyMachine # optional
```

### Browser Logs

TypeError: Cannot read properties of undefined (reading 'match')

    at A (https://home.mywebsite.com/_next/static/chunks/5535.5d41c9099bcd3308.js:1:19666)
    at h (https://home.mywebsite.com/_next/static/chunks/3581-88371f2e9f576e6a.js:1:34749)
    at n (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:17324)
    at B (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:31664)
    at div
    at li
    at A (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:35546)
    at ul
    at H (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:39629)
    at div
    at https://home.mywebsite.com/_next/static/chunks/3581-88371f2e9f576e6a.js:1:78610
    at div
    at l (https://home.mywebsite.com/_next/static/chunks/3581-88371f2e9f576e6a.js:1:107361)
    at https://home.mywebsite.com/_next/static/chunks/3581-88371f2e9f576e6a.js:1:96767
    at https://home.mywebsite.com/_next/static/chunks/3581-88371f2e9f576e6a.js:1:95535
    at l (https://home.mywebsite.com/_next/static/chunks/3581-88371f2e9f576e6a.js:1:107361)
    at https://home.mywebsite.com/_next/static/chunks/3581-88371f2e9f576e6a.js:1:76549
    at div
    at M (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:40129)
    at div
    at div
    at ve (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:59475)
    at n (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:17324)
    at https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:90387
    at be (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:57481)
    at div
    at div
    at div
    at ge (https://home.mywebsite.com/_next/static/chunks/pages/index-a6ca8a4a01a38683.js:1:67395)
    at a (https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:16472)
    at a (https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:16115)
    at s (https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:17031)
    at u (https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:15543)
    at https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:90387
    at https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:14794
    at l (https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:1470)
    at n (https://home.mywebsite.com/_next/static/chunks/pages/_app-5fcdee10a6dd87b5.js:1:6048)
    at r (https://home.mywebsite.com/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)
    at Y (https://home.mywebsite.com/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)
    at ie (https://home.mywebsite.com/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)

### Troubleshooting

Glances doesn't have user name password when i access via ip:port in browser. But tried to give similar to the syntax given below. But still didn't work. 

https://gethomepage.dev/latest/widgets/info/glances/

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the error logs from the browser, it seems like there might be an issue with the configuration syntax in your `services.yml` file. The error `TypeError: Cannot read properties of undefined (reading 'match')` suggests that there might be a problem with the way the configuration is structured or a certain property is not being accessed correctly.

Here are a few steps to troubleshoot the issue:

1. Ensure that the `url` provided in the widget configuration does not end with a trailing slash, as mentioned in the troubleshooting guide. The correct format should be `http://192.168.0.11:61208` without a trailing slash.

2. Verify that the structure of your `services.yml` file is correct. Based on the context provided, the configuration for the Glances widget should look something like this:

```yaml
- Usage:
    widget:
      type: glances
      url: http://192.168.0.11:61208
      metric: cpu # or any other metric you want to monitor
```

3. Since Glances does not require a username and password when accessed via IP and port in the browser, you should omit these fields from your configuration unless you have set up authentication for Glances.

4. Make sure that the indentation in your `services.yml` file is correct. YAML files are sensitive to indentation, and incorrect indentation can lead to parsing errors.

5. If you have recently made changes to the configuration, ensure that you have restarted the Docker container to apply the new configuration.

6. Check the homepage documentation for the correct configuration examples for Glances widgets. You can find the documentation for Glances service widgets here: https://gethomepage.dev/latest/widgets/services/glances and for Glances information widgets here: https://gethomepage.dev/latest/widgets/info/glances.

7. If the issue persists, you may want to check the homepage GitHub issues or discussions for similar problems or open a new issue/discussion for assistance.

Please try the above steps and adjust your configuration accordingly. If you continue to experience issues, please provide the updated configuration and any new error messages you may be receiving.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
