### DISCUSSION TITLE
Unraid disk

### DISCUSSION THREAD

**Discussion by PincoPanco1** [gethomepage/homepage#300] [Support]
I want to have the Unraid disk array set on Homepage. it's possible?

Docker path: 
![mnt](https://user-images.githubusercontent.com/83478038/192871635-0893798a-0e28-4b43-afdc-fee79d3016f9.png)

Widget.yaml 
![widgets](https://user-images.githubusercontent.com/83478038/192871644-23937970-8c22-4e16-8fde-43752d85af89.png)

**Comment by Nonoss117** [comment]
Hi,
I'm on unraid, My configuration :

![image](https://user-images.githubusercontent.com/79055577/192874292-32ef390e-634e-4c1d-ba2f-2576a20e804a.png)


`widgets.yaml`
``` yaml
- resources:
    label: Array Disks
    expanded: false
    disk:
        - /disk1
        - /disk2
        - /disk3

- resources:
    label: Cache pool
    expanded: false
    disk:
        - /cache
```

homepage:
![image](https://user-images.githubusercontent.com/79055577/192874398-e9afabd8-293c-481c-bb1d-65992fe27439.png)
