### DISCUSSION TITLE
Unable to setup ical with homepage

### DISCUSSION THREAD

**Discussion by Generator** [gethomepage/homepage#3010] [Support]
### Description

I'm trying to integrate ical (ics) calendar to homepage, but no luck.
On browser console returns HTTP error 400.

ICS URL: https://www.thunderbird.net/media/caldata/autogen/PortugalHolidays.ics

Tested with other calendar applications, with no issues.

### homepage version

v0.8.8

### Installation method

Docker

### Configuration

```yaml
- Calendar:
    - calendar:
        name: ""
        widget:
          type: calendar
          view: monthly
          firstDayInWeek: sunday
          integrations:
            - type: ical
              url: https://www.thunderbird.net/media/caldata/autogen/PortugalHolidays.ics
              name: Holidays
```

### Browser Logs

XHRGET
http://localhost:3000/api/services/proxy?type=ical&group=Calendar&service=null&endpoint=Holidays&query={"refreshInterval":300000}
[HTTP/1.1 400 Bad Request 56ms]

	
GET
	http://localhost:3000/api/services/proxy?type=ical&group=Calendar&service=null&endpoint=Holidays&query={"refreshInterval":300000}
Estado
400
Bad Request
VersãoHTTP/1.1
Transferido254 B (tamanho 31 B)
Política de referênciasstrict-origin-when-cross-origin
Resolução de DNSSistema

    	
    Connection
    	keep-alive
    Content-Length
    	31
    Content-Type
    	application/json; charset=utf-8
    Date
    	Mon, 26 Feb 2024 15:07:57 GMT
    ETag
    	"ut82ht5uzav"
    Keep-Alive
    	timeout=5
    Vary
    	Accept-Encoding
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	pt-PT,pt;q=0.8,en;q=0.5,en-US;q=0.3
    Connection
    	keep-alive
    Cookie
    	player-61646d696e=1; X-ND-Client-Unique-Id=2f633901-a800-43b7-b79c-53347c7b5f63; nd-player-67656e657261746f72=43fbae21-fcb6-49c6-9d54-4ede6414745a; x-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdlbmVyYXRvciIsImlhdCI6MTcwMTM1OTI4NH0.KfWW3o935PWnoXIqnU-BT-BTVQgckJtyurShF1p-VUY; next-auth.session-token=743224a2-c6f2-460c-a770-ba5748409b82
    DNT
    	1
    Host
    	localhost:3000
    Referer
    	http://localhost:3000/api/services/proxy?type=ical&group=Calendar&service=null&endpoint=Holidays&query=%7B%22refreshInterval%22%3A300000%7D
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0

### Troubleshooting

API Error Information
API Error: ical: Invalid integration
