### DISCUSSION TITLE
How to get Docker statuses for containers on a different server?

### DISCUSSION THREAD

**Discussion by goaliedude3919** [gethomepage/homepage#3011] [Support]
### Description

I have homepage installed on Server A, along with some other containers. I also have a Server B where I have some other containers installed. I would like to have the docker statuses for both containers on Server A and Server B. I followed [these steps](https://gist.github.com/styblope/dc55e0ad2a9848f2cc3307d4819d819f) from [Homepage's Docker documentation](https://gethomepage.dev/latest/configs/docker/), but it just results in it saying "Not Found" in orange letters. There is nothing in the logs that indicate an error or anything like that.

docker.yaml config:
```
 my-remote-docker:
   host: 192.168.7.210
   port: 2375
```

daemon.json contents:
```
{
  "log-driver": "journald",
  "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
}
```

From another machine, I can telnet to 192.168.7.210 over port 2375, so it doesn't appear to be a firewall issue as far as I can tell.

### homepage version

8.8

### Installation method

Docker

### Configuration

```yaml
docker.yaml config:
 my-remote-docker:
   host: 192.168.7.210
   port: 2375

daemon.json contents:
{
  "log-driver": "journald",
  "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
}

Service config:
    - Mealie:
        href: https://my.url
        siteMonitor: https://my.url
        description: Recipe Manager
        icon: mealie.png
        server: my-remote-docker
        container: mealie
```

### Troubleshooting

$ docker exec homepage ping 192.168.7.210
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/homepage/json": dial unix /var/run/docker.sock: connect: permission denied
$ sudo docker exec homepage ping 192.168.7.210
Password:
PING 192.168.7.210 (192.168.7.210): 56 data bytes
64 bytes from 192.168.7.210: seq=0 ttl=63 time=1.487 ms
64 bytes from 192.168.7.210: seq=1 ttl=63 time=1.462 ms
