### DISCUSSION TITLE
OpenWRT widget - API error when specifying any interfaceName

### DISCUSSION THREAD

**Discussion by husq-nz** [gethomepage/homepage#3012] [Support] [answered]
### Description

OpenWRT widget works fine without any interfaceName: specified, however as soon as one is added, the status switches to API error.

v0.8.8, deployed via LCX on Proxmox 8.1

OpenWRT is deployed as x86 on an Intel N5105 based router.

### homepage version

0.8.8

### Installation method

Other (please describe above)

### Configuration

```yaml
- OpenWRT:
        href: http://x.x.x.x
        icon: openwrt.png
        widget:
          type: openwrt
          url: http://x.x.x.x
          username: xxxxxxxx
          password: xxxxxxxx
          interfaceName: eth1
```

### Troubleshooting

Have tried with the "friendly" name of the interface (wan, Wan, WAN) and the interface name (eth1). Have also tried with other interfaces. No joy.

Removing the interfaceName: line reverts to default (not-interface-specific) config, which works fine.
