### DISCUSSION TITLE
Undefined error after new installation

### DISCUSSION THREAD

**Discussion by Pak77** [gethomepage/homepage#3015] [Support]
### Description

Hello,
I installed homepage on my synology today using portainer and docker compose. I have not yet made any changes to the page, but I get "error: undefined" in the logs and "Failed to load resource: the server responded with a status of 500 (internal server error)" in the console every time I call it up. In addition, I have two warnings: "The resource http://x.x.x.x:60020/api/config/custom.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing."
Does anyone know the error or what I am doing wrong? I will gladly provide further information.
Best regards

### homepage version

v0.8.8

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: xxxx
      PGID: xxx
    ports:
      - 60020:3000
    volumes:
      - /volume2/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```

### Container Logs

[2024-02-27T20:45:28.897Z] info: docker.yaml was copied to the config folder
[2024-02-27T20:45:28.898Z] info: services.yaml was copied to the config folder
[2024-02-27T20:45:28.899Z] info: bookmarks.yaml was copied to the config folder
[2024-02-27T20:45:28.904Z] info: widgets.yaml was copied to the config folder
[2024-02-27T20:45:28.905Z] info: custom.css was copied to the config folder
[2024-02-27T20:45:28.905Z] info: custom.js was copied to the config folder
[2024-02-27T20:45:28.999Z] info: kubernetes.yaml was copied to the config folder
[2024-02-27T20:45:34.008Z] error: undefined
[2024-02-27T20:45:40.179Z] error: undefined
[2024-02-27T20:46:28.912Z] error: undefined
[2024-02-27T20:46:29.171Z] error: undefined
[2024-02-27T20:46:35.855Z] error: undefined
[2024-02-27T20:46:36.765Z] error: undefined
[2024-02-27T20:53:52.300Z] error: undefined
[2024-02-27T20:53:53.258Z] error: undefined
[2024-02-27T20:54:00.423Z] error: undefined
[2024-02-27T20:54:01.384Z] error: undefined
[2024-02-27T20:55:25.547Z] error: undefined
[2024-02-27T20:55:26.496Z] error: undefined
[2024-02-27T20:55:32.224Z] error: undefined
[2024-02-27T20:55:33.325Z] error: undefined
[2024-02-27T21:00:43.500Z] error: undefined
[2024-02-27T21:00:53.516Z] error: undefined
[2024-02-27T21:01:23.530Z] error: undefined
[2024-02-27T21:02:13.548Z] error: undefined
[2024-02-27T21:03:48.568Z] error: undefined
[2024-02-27T21:05:18.582Z] error: undefined
[2024-02-27T21:06:06.486Z] error: undefined
[2024-02-27T21:06:07.355Z] error: undefined
[2024-02-27T21:06:17.369Z] error: undefined

### Browser Logs

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### Troubleshooting

currently no service widgets
