### DISCUSSION TITLE
CalDAV support?

### DISCUSSION THREAD

**Discussion by dehnhard** [gethomepage/homepage#3018] [Support]
### Description

I tried to connect a CalDAV server (xandikos) to the calendar widget and it reports that it can't find any events.
The CalDAV server hosts a collection of ics files, each consisting of one event. 

The widget actually loads a single event, when pointes to a single file of the collection (see comment in config).

Looking at the source code I see that the ical plugin uses `cal-parser` which reads only single ics files. The npm module `tsdav` could propably be used for caldav servers.

### homepage version

0.8.8

### Installation method

Docker

### Configuration

```yaml
- Kalender:
    - " ":
        widget:
          type: calendar
          integrations:
            - type: ical
              url: https://<server>/user/calendars/calendar
#              url: https://<server>/user/calendars/calendar/537c7d88678bac08e7d0b2c253bfb218c84fbb1b.ics
              name: Kalender
```

### Container Logs

none

### Browser Logs

"API Error: No Events found" on homepage

### Troubleshooting

none
