### DISCUSSION TITLE
Multiple Widgets Failing

### DISCUSSION THREAD

**Discussion by Erieg1969** [gethomepage/homepage#3030] [Support]
### Description

I am setting up Homepage for the first time and I am having an issue with some widgets. The *arr widgets work great but I also added widgets for sabnzbd, speedtest-tracker and openmediavault which aren't. The widgets show up on homepage but here are not stats. There is nothing in the logs concerning them. I ran my config file through a yaml checker are there are no errors.

I pasted the info from the services.yaml file in the configuration screen. For some reason it changes the formating but the formatting is correct when looking at the file on the server.

Any suggestions would be appreciated. Pounding my head on my desk is getting painful.

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- SabNZBD:
        icon: sabnzbd.png
        href: http://192.168.50.202:8080/
        description: Download client
        widget:
        type: sabnzbd
        url: http://192.168.50.202:8080
        key: XXXXXXXXXXXXX
        fields: ["rate", "queue", "timeleft"]

    - Speedtest-Tracker:
        icon: speedtest-tracker.png
        href: http://192.168.50.194:8080
        description: ISP speedtest
        widget:
        type: speedtest
        url: http:// 192.168.50.194:8080
        fields: ["download", "upload", "ping"]

    - OpenMediaVault:
        icon: openmediavault.png
        href: http://192.168.50.209/#/login
        description: NAS server
        widget:
        type: openmediavault
        url: http://192.168.50.209
        username: admin
        password: 
        method: services.getStatus # required
```

### Container Logs

[2024-02-28T20:53:39.394Z] warn: API response for /api/services/proxy?type=lidarr&group=Media&service=Lidarr&endpoint=artist exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T20:53:41.263Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T20:55:23.358Z] warn: API response for /api/services/proxy?type=lidarr&group=Media&service=Lidarr&endpoint=artist exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T20:55:26.606Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T21:25:08.443Z] warn: API response for /api/services/proxy?type=lidarr&group=Media&service=Lidarr&endpoint=artist exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T21:25:09.946Z] warn: API response for /api/services/proxy?type=lidarr&group=Media&service=Lidarr&endpoint=artist exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T21:25:12.774Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T21:25:14.432Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T22:09:28.884Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T22:16:11.084Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-28T22:16:12.324Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-29T13:58:34.382Z] warn: API response for /api/services/proxy?type=radarr&group=Media&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-02-29T13:58:35.155Z] warn: API response for /api/services/proxy?type=lidarr&group=Media&service=Lidarr&endpoint=artist exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit

### Troubleshooting

I have removed the widgets with the issue and then added them back with no luck.
