### DISCUSSION TITLE
[Calendra] iCal integration bad indentation

### DISCUSSION THREAD

**Discussion by Chucky2401** [gethomepage/homepage#3033] [Support]
### Description

Hello everyone,
I tried to add an iCal integration in the calendar widget, here the code I used:

```yaml
- Other:
    - HomeAssistant WAN:
        icon: si-homeassistant-#18BCF2
        href: https://xxxxxxx.xxxxxx.org
        description: Home Assistant from external
        siteMonitor: https://xxxxxxxxx.xxxxx.org
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: monday
            view: monthly
            maxEvents: 5
            showTime: true
            timezone: Europe/Paris
            integrations:
                - type: ical
                    url: https://calendar.google.com/xxxxxx/xxxx/xxxxxxx.xxxxxx.xx%40xxxxx.xxx/xxxxxx/basic.ics
                    name: Personnal events
                    color: zinc
```

But I got this error message:

![image](https://github.com/gethomepage/homepage/assets/53853245/a919bd45-9dff-42c7-bc13-0acbff9e2739)

My calendar is public, and I tried to open the URL and my browser ask where to save the file.

I don't know what to do to fix it.

### homepage version

v0.8.8 (87d1ea4)

### Installation method

Docker

### Configuration

```yaml
N/A
```

### Container Logs

```txt
homepage  | [2024-02-29T16:58:37.117Z] error: Failed to load services.yaml, please check for errors
homepage  | [2024-02-29T16:58:37.118Z] error: YAMLException: bad indentation of a mapping entry (278:24)
homepage  | 
homepage  |  275 |             timezone: Europe/Paris
homepage  |  276 |             integrations:
homepage  |  277 |                 - type: ical
homepage  |  278 |                     url: https://calendar.google.com/c ...
homepage  | ------------------------------^
homepage  |  279 |                     name: Personnal events
homepage  |  280 |                     color: zinc
```

### Browser Logs

N/A

### Troubleshooting

I tried:

- Ping *calendar.google.com* -> OK
- curl the complete URL -> OK
- Rewrite completely the widget settings -> No change

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the error message provided in the container logs, it appears that there is a YAML indentation issue in your configuration file. YAML is very sensitive to indentation, and the error `bad indentation of a mapping entry` suggests that the lines following the `- type: ical` entry are not indented correctly.

To fix this issue, you should ensure that the properties `url`, `name`, and `color` are indented at the same level under the `- type: ical` line. Here is the corrected snippet:

```yaml
- Other:
    - HomeAssistant WAN:
        icon: si-homeassistant-#18BCF2
        href: https://xxxxxxx.xxxxxx.org
        description: Home Assistant from external
        siteMonitor: https://xxxxxxxxx.xxxxx.org
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: monday
            view: monthly
            maxEvents: 5
            showTime: true
            timezone: Europe/Paris
            integrations:
                - type: ical
                  url: https://calendar.google.com/xxxxxx/xxxx/xxxxxxx.xxxxxx.xx%40xxxxx.xxx/xxxxxx/basic.ics
                  name: Personnal events
                  color: zinc
```

Notice that `url`, `name`, and `color` are aligned with `type` under the `integrations` list. Make sure to use spaces for indentation and not tabs, as tabs can cause parsing errors in YAML files.

After making these changes, save your configuration file and restart the Homepage service to apply the changes. If the issue persists, please ensure that the URL is correct and does not contain any spaces or special characters that might not be properly encoded.

Remember to validate your YAML configuration using an online validator if you're unsure about the syntax.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
