### DISCUSSION TITLE
How can I layout two groups in the same row?

### DISCUSSION THREAD

**Discussion by tomerh2001** [gethomepage/homepage#3035] [Support]
### Description

I have the following layout:
![image](https://github.com/gethomepage/homepage/assets/45624804/f4973db8-2db0-4092-9267-197949244f2c)

Let's say I move kavita and speed test into a different group; I want to layout the remaining services as follows:
```
Row 1: Streaming[Jellyfin] Networking[Cloudflare, PiHole, Traefik]
Row 2: Other groups/services
```

### homepage version

latest

### Installation method

Docker

### Troubleshooting

no errors, just a question.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To achieve the layout you're describing, you would need to modify your `layout` configuration in your `settings.yaml` file to specify the desired structure. Based on the context provided, you can organize your services into groups and then define the layout for each group. Here's an example of how you might configure your `settings.yaml` file:

```yaml
layout:
  Streaming:
    style: row
    columns: 1
  Networking:
    style: row
    columns: 3
  OtherGroup1:
    style: row # or column, depending on your preference
    columns: 4 # adjust the number of columns as needed
  OtherGroup2:
    style: row # or column, depending on your preference
    columns: 4 # adjust the number of columns as needed
  # Add more groups as needed
```

In this configuration:
- The `Streaming` group contains only Jellyfin and is set to have 1 column.
- The `Networking` group contains Cloudflare, PiHole, and Traefik, each in its own column, totaling 3 columns.
- Additional groups (`OtherGroup1`, `OtherGroup2`, etc.) can be added below with their own styles and column numbers.

Make sure to replace `OtherGroup1`, `OtherGroup2`, etc., with the actual names of your groups and adjust the `columns` value to match the number of services you have in each group.

After making these changes, you should restart your Homepage Docker container to apply the new configuration.

Please note that the exact names of the groups (`Streaming`, `Networking`, etc.) should match the names used in your `services.yaml` or `bookmarks.yaml` files where you define the services under each group.

If you need further assistance with the exact configuration or if you have a different structure in mind, please provide more details or the current content of your `settings.yaml` and `services.yaml` files for a more precise answer.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
