### DISCUSSION TITLE
Background color change

### DISCUSSION THREAD

**Discussion by adm2k** [gethomepage/homepage#3040] [Feature Requests]
### Description

Wondering if it is possible to change the background color or maybe the actual text color based on the value being displayed. 

For example, if the "status" in the screen shot below were to change to something other than "Healthy" then either the "status" change to red or maybe the background change to red. 

![image](https://github.com/gethomepage/homepage/assets/120423301/82f195f5-50c8-4960-aac5-d3bfa5c06be0)

Or in this case if "sites down" were other than zero.

![image](https://github.com/gethomepage/homepage/assets/120423301/56913edf-3cc0-475b-b153-402988403f68)

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To change the background color or text color based on the value being displayed, such as the "status" or "sites down" indicators, you can utilize custom CSS and JavaScript functionality provided by Homepage. As of version v0.6.30, Homepage supports adding your own custom CSS and JavaScript, which allows you to target elements with specific IDs or classes and apply styles conditionally based on their content.

You can edit the `custom.css` file under your config directory to add custom CSS rules, and similarly, you can edit the `custom.js` file to add JavaScript that can dynamically change styles based on conditions.

For example, you could use JavaScript to check the content of the "status" element, and if it is not "Healthy," you could add a class to change the text color to red or change the background color. Similarly, you could check if "sites down" is greater than zero and apply styles accordingly.

Here's a basic example of how you might use JavaScript to change the text color based on the status:

```javascript
document.addEventListener('DOMContentLoaded', function() {
  var statusElement = document.getElementById('statusElementId'); // Replace with the actual ID
  if (statusElement && statusElement.textContent !== 'Healthy') {
    statusElement.style.color = 'red';
  }
});
```

And here's how you might use CSS to style an element with a specific ID when the condition is met:

```css
#statusElementId {
  color: red; /* This will only apply if the JavaScript adds this ID */
}
```

Remember to set a specific `id` for the service or bookmark in your Homepage configuration to target it with your custom CSS or JavaScript.

Please note that you should do this at your own risk, and it's important to test your changes thoroughly to ensure they work as expected across different browsers and devices.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by adm2k** [comment]
I have reviewed the "AI" response but, having little experience with Java Script or CSS I am at a loss.  

Can anyone provide me a sample of how to do this using the UptimeKuma widget? Where/how do I reference the custom JS to display the "sites down" (text or the background) in red if greater than 0?

Here is my current yaml for UptimeKuma:

- UptimeKuma:
        icon: uptime-kuma.png
        href: http://xxx.xxx.xx.xx:xxxx
        description: UptimeKuma monitor
        widget:
          type: uptimekuma
          url: http://xxx.xxx.xx.xx:xxxx
          slug: homelab

**Reply by cadeluca** [reply]
Hi adm2k,

I cobbled together something that works for me and hopefully will work for you too. This is specific to your UptimeKuma request. By no means is this code perfect, but take a look:

First, here's how I have my UptimeKuma service definition in ```services.yaml```, note the `id` property I've set to let me reference it in JS later, per the [docs](https://gethomepage.dev/latest/configs/custom-css-js/):

```yaml filename="services.yaml"
- Uptime Kuma:
    id: uptime-kuma
    icon: uptime-kuma
    href: <redacted>
    description: Website and Container uptime tracker
    server: rpi-docker
    container: uptime-kuma
    widget:
      type: uptimekuma
      url: <redacted>
      slug: <redacted>
```

Next, I have this css defined in `custom.css`:

```css
.down-bg {
  background: #802a2a !important; /* this color works for my homepage theming, chances are you'll want to change it */
  /* I have this css transition code uncommented in mine, just personal preference */ 
  /* -webkit-transition: all 0.2s linear;
  -moz-transition: all 0.2s linear;
  -o-transition: all 0.2s linear;
  transition: all 0.2s linear; */
}
```

Last, my `custom.js`:

```js
document.addEventListener("DOMContentLoaded", function () {
  // not working for me, consider moving code execution here if it works for you
  // createObserver();
});

function createObserver() {
  // calling this on init to get style updated first time
  updateDownSitePanelStatus();

  // select the target node, referencing the id parameter from the service definition
  const downSitePanel = document
    .getElementById("uptime-kuma")
    .querySelector(".service-container").children[1];

  // create an observer instance
  const observer = new MutationObserver(function (mutations) {
    mutations.forEach(function (mutation) {
      if (mutation.type === "characterData") {
        updateDownSitePanelStatus();
      }
    });
  });

  const config = {
    subtree: true,
    characterData: true,
  };

  // pass in the target node and observer options
  observer.observe(downSitePanel, config);
}

function updateDownSitePanelStatus() {
  const downSitePanel = document
    .getElementById("uptime-kuma")
    .querySelector(".service-container").children[1];

  const siteDownCount = parseInt(downSitePanel.children[0].textContent);

  if (siteDownCount > 0) {
    if (!downSitePanel.classList.contains("down-bg")) {
      downSitePanel.classList.add("down-bg");
    }
  } else {
    if (downSitePanel.classList.contains("down-bg") || isNaN(siteDownCount)) {
      downSitePanel.classList.remove("down-bg");
    }
  }
}

setTimeout(createObserver, 1000); // band-aid, use as needed - sometimes would fire too early without the timeout
//createObserver();
```
The observer keeps an eye on the down sites panel. When it detects the number changed, it updates the css.
As I note in the snippet comments, I'm not sure why I'm having trouble with DOMContentLoaded, perhaps [this](https://stackoverflow.com/questions/39993676/code-inside-domcontentloaded-event-not-working). The ever so slight delay doesn't bother me.

Let me know if this works for you or if you have any questions!
