### DISCUSSION TITLE
[Feature Request] Simple text box to display arbitrary markdown

### DISCUSSION THREAD

**Discussion by theS1LV3R** [gethomepage/homepage#3041] [Feature Requests]
### Description

Just a text box or a widget or something to display arbitrary markdown data would be awesome

### Other

Say if there are multiple users, some less tech-savvy than others, having a simple text box to be like a reminder for what does what (or similar) can be really useful.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the context provided, it seems you are looking for a way to display arbitrary markdown data on the Homepage dashboard, possibly for instructional or informational purposes for users of varying technical skill levels.

The Homepage dashboard does have a widget that allows you to display simple text, which could potentially be used for reminders or instructions. This is the "Greeting" widget, and it can be configured to display text in various sizes. However, the documentation does not explicitly state that it supports markdown formatting.

Here is an example of how you can configure the Greeting widget in your `widgets.yaml` file:

```yaml
- greeting:
    text_size: xl
    text: Greeting Text
```

Valid text sizes for the Greeting widget are `4xl`, `3xl`, `2xl`, `xl`, `md`, `sm`, `xs`.

If you need to display markdown data specifically and the Greeting widget does not support markdown, you might need to look into whether Homepage has a markdown widget or consider requesting this feature from the developers.

For more detailed information on the Greeting widget and other widgets, you can refer to the Homepage documentation:

- Greeting Widget: https://gethomepage.dev/latest/widgets/info/greeting
- Greeting Widget GitHub Documentation: https://github.com/gethomepage/homepage/tree/main/docs/widgets/info/greeting.md

If the Greeting widget does not meet your needs, you may consider reaching out to the Homepage community or developers to suggest the addition of a markdown widget or to inquire about alternative solutions.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by theS1LV3R** [reply]
Doesn't work very well:
![image](https://github.com/gethomepage/homepage/assets/32072697/5441705a-cac8-4717-852d-edf6342f9787)

Config:
```yml
- datetime:
    text_size: 2xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h24

- search:
    provider: [duckduckgo]
    target: _blank

- greeting:
    text_size: xl
    text: |
      Test test
      with newlines
      - and a test of a line
```
