### DISCUSSION TITLE
Portainer widget shows API Error

### DISCUSSION THREAD

**Discussion by brantje** [gethomepage/homepage#3051] [Support] [answered]
### Description

After configuring the portainer widget with the proper credentials i see an "API Error"

![image](https://github.com/gethomepage/homepage/assets/2758767/e50dc5e6-c8d2-474c-b81d-0760b9958eec)

Looking into the network tab it shows the server had an internal server error:

![image](https://github.com/gethomepage/homepage/assets/2758767/c8818bd6-057e-4643-81aa-bacc989fd1ed)

When i request the running containers via curl it works fine:
`curl -H "X-API-Key: ptr_xxxxxxx"  http://localhost:9000/api/endpoints/1/docker/containers/json?all=1`

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Container Logs

`api/services/proxy?type=portainer&group=Homelab&service=Portainer&endpoint=docker/containers/json&query={"all":1}`
[2024-03-02T20:39:14.927Z] error: undefined
[2024-03-02T20:40:26.860Z] error: undefined
[2024-03-02T20:40:59.288Z] error: undefined
[2024-03-02T20:41:20.598Z] error: undefined
[2024-03-02T20:41:25.681Z] error: undefined

### Troubleshooting

See above

**Comment by brantje** [comment, marked as answer]
And it suddenly started working, nice :)

**Comment by rankokrneta** [comment]
Hi @brantje, 

I have same problem, could you share service.yaml for Portainer, here is mine but it wont work for me:
I dont know how to format URL and KEY to get authenticate

`[2024-03-19T17:32:14.368Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://192.168.1.10:9000/api/stacks/api/endpoints/env1/docker/containers/json?all=1`

```
-Portainer:
        icon: portainer.svg
        href: http://192.168.1.10:9000
        description: docker
        widget:
            type: portainer
            url: http://192.168.1.10:9000/api/stacks
            env: env1
            key: ptr_2QQD7**************************************
```
