### DISCUSSION TITLE
Authentik widget TypeError: f.reduce is not a function

### DISCUSSION THREAD

**Discussion by dkruyt** [gethomepage/homepage#3053] [Support]
### Description

I am using the Authentik widget, after configure it it shows the stats correct, but after 15 min I get in a red box: 

Something went wrong.
TypeError: f.reduce is not a function

And the stats are not showing anymore, just the error. I have 3 sites running, all give the same error.

![image](https://github.com/gethomepage/homepage/assets/713812/f3786269-2f51-4348-ae3a-050b047daf33)

![image](https://github.com/gethomepage/homepage/assets/713812/28c4ce58-58da-47ea-a1b9-62c33a2f01f8)

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- Authentik:
        href: https://auth.......nl
        description: Identity Provider
        icon: authentik.png
        container: authentik_server
        widget:
          type: authentik
          #hideErrors: true
          url: https://auth.......nl
          key: J......................g
```

### Troubleshooting

The output from the 3 endpoints all look normal from Authentik:

const widget = {
  api: "{url}/api/v3/{endpoint}",
  proxyHandler: credentialedProxyHandler,

  mappings: {
    users: {
      endpoint: "core/users/?page_size=1",
    },
    login: {
      endpoint: "events/events/per_month/?action=login",
    },
    login_failed: {
      endpoint: "events/events/per_month/?action=login_failed",
    },
  },
};
