### DISCUSSION TITLE
Can't get background or favicon to work with local resources

### DISCUSSION THREAD

**Discussion by Prolly92** [gethomepage/homepage#3056] [Support]
### Description

Can't get the background/favicon settings to use local resources, they work fine with a URL so I don't think its my settings.yaml file. I've gotten it to work on other similar containers like Homarr, heimdall, organizr, etc. but for some reason I can't manage to get it to work here.

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Unraid

### Configuration

```yaml
Mount path
-v '/mnt/user/Media/Resources/images':'/images':'rw' 

Relevant settings.yaml config
background:
  image: /images/background.png
  opacity: 60
cardBlur: xl
theme: dark

favicon: /images/favicon-32x32.png
```

### Container Logs

[2024-02-26T11:38:41.917Z] info: docker.yaml was copied to the config folder
[2024-02-26T11:38:41.924Z] info: services.yaml was copied to the config folder
[2024-02-26T11:38:41.924Z] info: bookmarks.yaml was copied to the config folder
[2024-02-26T11:38:41.925Z] info: widgets.yaml was copied to the config folder
[2024-02-26T11:38:41.926Z] info: custom.css was copied to the config folder
[2024-02-26T11:38:41.926Z] info: custom.js was copied to the config folder
[2024-02-26T11:38:42.034Z] info: kubernetes.yaml was copied to the config folder
[2024-03-02T07:43:36.995Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-03-03T15:43:25.768Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-03-03T15:43:26.584Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-03-03T18:27:59.988Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-03-03T18:28:11.784Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-03-03T18:28:30.303Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-03-03T18:31:46.039Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-03-03T18:31:46.979Z] warn: API response for /api/services/proxy?type=radarr&group=Applications&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit

### Browser Logs

404 Not Found
http://IP:3033/images/background.png

### Troubleshooting

I've tried mounting different paths, double checked the permissions/owner on the path and files. Tried removing the container, deleting any leftover appdata files and starting from scratch.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems you have taken the correct steps to configure the background and favicon using local resources. However, there are a few common issues that could be causing the problem:

1. **File Permissions:** Ensure that the permissions for the `/mnt/user/Media/Resources/images` directory and the files within it are set correctly so that the container can read them. The user running the container should have read access to the files.

2. **Container Restart:** After adding new images or making changes to the `settings.yaml` file, you need to restart the container for the changes to take effect. Make sure you have restarted the container after making changes.

3. **File Paths:** Verify that the file paths specified in the `settings.yaml` are correct and that the files exist at those paths. The path `/images/background.png` should correspond to `/mnt/user/Media/Resources/images/background.png` on your Unraid system.

4. **Image Format and Size:** Check if the image format is supported and the image size is not too large, which might prevent it from loading properly.

5. **Cache Issues:** Clear your browser cache or try accessing the page using a different browser or incognito mode to ensure that the issue is not related to cached data.

6. **Docker Volume Mapping:** Double-check the volume mapping in your Docker container settings. The left side of the volume mapping (`'/mnt/user/Media/Resources/images'`) is the path on your Unraid system, and the right side (`'/images'`) is the path inside the container. Ensure that this mapping is correctly set up in your Docker container configuration.

7. **Check for Typos:** Ensure there are no typos in the `settings.yaml` file, especially in the file paths.

If you have checked all the above and the issue persists, please provide the container logs as they may contain errors or warnings that can help identify the problem. Additionally, browser logs can sometimes offer clues if the issue is related to the client side.

Since you mentioned that you've tried mounting different paths and checked permissions, and assuming you've restarted the container after making changes, the issue might be with how the container is accessing the files. If possible, check the container's logs for any errors related to file access or paths.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by gcortes** [comment]
```
I'm having the same problem. I'm running Homepage in a Proxmox LXC. I also can get a web linked image to work. I've done a reboot as specified on the help page.
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: My Homepage

background: /opt/homepage/config/wallpapersden.com_mount-fuji-4k-ultra-hd-japan_1920x1080.jpg
# background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format

theme: dark
color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

```
