### DISCUSSION TITLE
Text and Hilights stuck on a rose-like color

### DISCUSSION THREAD

**Discussion by dn512214** [gethomepage/homepage#3059] [Support] [answered]
### Description

Hi All,

I copied my homepage folders (main and images) to another location and modified the docker-compose bind mounts to the new folders, in an attempt to set up a clone for testing.  In the new container, all the text and foreground boxes, etc are stuck on this weird rose color, and all the palette boxes are the same color.  I've checked every single file between both containers, and can't see a difference anywhere.  What am I doing wrong?

![image](https://github.com/gethomepage/homepage/assets/107143494/37bd552c-77d3-4f9c-9194-ce0fd14a99e4)

TIA!

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
settings.yaml:

title: homepaged1.l.example.com
background: /images/skyrim--night-sky-over-high-hrothgar-wallpaper.png
backgroundOpacity: 0.3
theme: dark
color: slate

headerStyle: boxedWidgets

showStats: true
fiveColumns: true

layout:

  Infrastructure:
    style: column
    rows: 6
    columns: 2
    
  Servers:
    style: column
    rows: 8
    columns: 1
    
  Docker:
    style: column
    rows: 6
    
  Applications:
    style: column
    columns: 1
    
  TailScale:
    style: column
    columns: 1
```

```yaml
docker-compose:

version: "3.3"
services:
  homepaged1:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-d1
    ports:
      - 3110:3000
    volumes:
      - /apps/homepaged1/main:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /apps/homepaged1/images:/app/public/images 
      - /apps/homepaged1/images:/app/public/icons 
    networks:
      - net1
    restart: unless-stopped
    
networks:
  net1:
    name: homepage-d1

```

### Container Logs

nothing relevant in container logs (just a few glances unable to connect to shut down servers)

### Troubleshooting

no errors in the docker logs (just a few glances unable to connect to shut down servers)
issue not related to widgets
issue not related to missing icons
