### DISCUSSION TITLE
Two Raspberry Pi Metrics?

### DISCUSSION THREAD

**Discussion by bearded-papa** [gethomepage/homepage#3061] [Support]
### Description

I am just about to set up my second Rpi but intend to just use one dashboard.

Is there a way that I can see the metric for cpu and memory for both on the same dashboard?

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Troubleshooting

I have read through the documentaion and have been unable to see this mentioned

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Yes, you can monitor the CPU and memory metrics for both of your Raspberry Pi devices on the same dashboard using the Glances widget. You will need to set up Glances on both Raspberry Pi devices and then configure two separate instances of the Glances widget on your dashboard, each pointing to the respective Raspberry Pi's Glances instance.

Here's an example configuration for your `docker-compose.yml` or `homepage.yaml` file:

```yaml
- Raspberry Pi 1:
    widget:
      type: glances
      url: http://raspberrypi1.host.or.ip:port
      metric: cpu
- Raspberry Pi 1 Memory:
    widget:
      type: glances
      url: http://raspberrypi1.host.or.ip:port
      metric: memory
- Raspberry Pi 2:
    widget:
      type: glances
      url: http://raspberrypi2.host.or.ip:port
      metric: cpu
- Raspberry Pi 2 Memory:
    widget:
      type: glances
      url: http://raspberrypi2.host.or.ip:port
      metric: memory
```

Replace `http://raspberrypi1.host.or.ip:port` and `http://raspberrypi2.host.or.ip:port` with the actual hostnames or IP addresses and ports where your Glances instances are accessible.

Make sure that Glances is properly installed and configured on both Raspberry Pi devices to allow remote access. You may also need to configure authentication if you have enabled it in Glances.

For more detailed information on configuring the Glances widget, you can refer to the Glances widget documentation provided in the context sources.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
