### DISCUSSION TITLE
Jellyfin Widget Reversed State Logic

### DISCUSSION THREAD

**Discussion by shiftoptk** [gethomepage/homepage#3063] [Support] [answered]
### Description

I've been running Plex and Jellyfin side by side evaluating a switch from one to the other, and as such I have the Tautulli widget and Jellyfin widget running side by side on my homepage. I noticed that the Jellyfin widget for showing active streams (enableNowPlaying) shows the streams as paused (icon) while its playing, and playing (icon) while its paused. Instead of how the Tautulli widget shows the play icon while its playing, and paused when its paused.

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
widget:
  type: jellyfin
  url: http://jellyfin.host.or.ip
  key: apikeyapikeyapikeyapikeyapikey
  enableBlocks: true # optional, defaults to false
  enableNowPlaying: true # optional, defaults to true
```

### Troubleshooting

I played a movie in Plex and in Jellfin at the same time and observed opposite behavior between the widgets showing the active streams. See attachment. 
![image](https://github.com/gethomepage/homepage/assets/116144680/c57bec51-50dd-47f9-9737-17ce1760f074)
