### DISCUSSION TITLE
[Feature Request] Show current PV Production

### DISCUSSION THREAD

**Discussion by geilername** [gethomepage/homepage#3071] [Feature Requests]
### Description

I'd love to implement a Service Widget that is able to show statistics from Fronius Solar Web (https://www.solarweb.com/) and/or Fronius Solarapi (https://www.fronius.com/de-at/austria/solarenergie/installateure-partner/technische-daten/alle-produkte/anlagen-monitoring/offene-schnittstellen/fronius-solar-api-json-).

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To implement a Service Widget for Fronius Solar Web or Fronius Solar API, you would typically need to create a custom widget that can interact with the Fronius API to fetch and display the desired statistics. Since Homepage supports custom widgets, you can use the API documentation provided by Fronius to understand how to make API calls and what data you can retrieve.

You would need to:

1. Review the Fronius Solar API documentation to understand the endpoints, required parameters, and the structure of the API responses.
2. Create a custom widget definition in your `services.yaml` file that makes requests to the Fronius API endpoints.
3. Define how the data retrieved from the API should be displayed within the widget, including any formatting or styling.

Here's a hypothetical example of what the widget configuration might look like in your `services.yaml` file:

```yaml
- Fronius Solar Web:
    icon: fronius.png
    widget:
      type: customapi
      url: https://fronius.example.com/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System
      headers:
        # Add any required headers here
      mappings:
        - field:
            data:
              Body:
                Data:
                  PAC:
                    Value: current_power
          label: Current Power
          format: number
          suffix: W
        # Add more mappings for additional data points you want to display
```

Please note that the above is just an illustrative example and the actual API endpoint, parameters, and JSON paths will depend on the Fronius API documentation.

Since this is a custom implementation, you would need to ensure that you handle authentication (if required by the API), error handling, and any other specifics as per the Fronius API's requirements.

If you need further assistance with the specifics of the Fronius API or with the implementation of the widget, you may need to consult the API documentation or seek help from a developer with experience in integrating third-party APIs.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
