### DISCUSSION TITLE
Moonraker widget layers

### DISCUSSION THREAD

**Discussion by akalderon** [gethomepage/homepage#3072] [Support] [answered]
### Description

Moonraker (Klipper) widget shows **null/null** for the "layers" field.  "print_status" and "print_progress" show correctly.  Any info on how to resolve and show actual layers (and total) or guidance to open an issue is appreciated.

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- Creality K1 Max Video:
          href: http://*.*.*.*:8080/?action=stream
          icon: https://c-3d.niceshops.com/upload/image/product/large/default/creality-k1-max-1-pc-558016-en.png
          weight: 1100
          widget:
            type: moonraker
            url: http://*.*.*.*:4408 (also tried with port 4409 and port 7125 with same results)
            fields: ["printer_state","print_status","print_progress","layers"]
```

### Troubleshooting

Using configuration above tried the widget with http://<printer_ip>:4408 (Fluidd) / :4409 (Mainsail) / :7125 (Klipper) - all three return the right data for "print_status" and "print_progress" but not for "layers".
Tried with defining the fields: and without defining fields: - same result - null/null for layers
