### DISCUSSION TITLE
How can I use the value got from the customapi widget as a key?

### DISCUSSION THREAD

**Discussion by A1exMinatoooo** [gethomepage/homepage#3074] [Support]
### Description

```yaml
widget:
    type: customapi
    url: http://url/to/api
    refreshInterval: 3600000
    mappings:
    - field:
        FieldA:
          FieldB: keyA
    - field:
        FieldC:
          keyA's value: keyB
```

As the above, I want to use KeyA's value get from `KeyA` as the key-value's key in FieldC, is there any workaround to do this?

### homepage version

v0.8.8 (87d1ea4)

### Installation method

Unraid

### Troubleshooting

no relevant troubleshooting
