### DISCUSSION TITLE
Portainer Widget: show multiple environments

### DISCUSSION THREAD

**Discussion by pflavio** [gethomepage/homepage#3077] [Feature Requests] [answered]
### Description

Hello

I have three different servers running docker with an environment each. Within Portainer, I've added two into another one so I always have to only check one site. When I just want to see the widget, I need to run three of them though. Any chance the current widget may be expanded to allow multiple environments?

Thanks

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Hello,

To display multiple Portainer environments within a single Homepage instance, you will need to configure multiple Portainer widgets, each with its own environment ID (`env`) and API key (`key`) if necessary. Based on the context provided, it seems that Homepage supports the configuration of widgets for different services, including Portainer.

Here's an example of how you might configure your `services.yml` file to include multiple Portainer widgets for different environments:

```yaml
- Portainer1:
    href: http://portainer1.example.com
    description: Portainer Environment 1
    icon: portainer.png
    widget:
      type: portainer
      url: http://portainer1.example.com
      env: 1
      key: ptr_key_for_env1

- Portainer2:
    href: http://portainer2.example.com
    description: Portainer Environment 2
    icon: portainer.png
    widget:
      type: portainer
      url: http://portainer2.example.com
      env: 2
      key: ptr_key_for_env2

- Portainer3:
    href: http://portainer3.example.com
    description: Portainer Environment 3
    icon: portainer.png
    widget:
      type: portainer
      url: http://portainer3.example.com
      env: 3
      key: ptr_key_for_env3
```

Make sure to replace `http://portainer1.example.com`, `http://portainer2.example.com`, `http://portainer3.example.com` with the actual URLs of your Portainer instances, and `ptr_key_for_env1`, `ptr_key_for_env2`, `ptr_key_for_env3` with the actual API keys for each environment. The `env` value should correspond to the environment ID you wish to monitor with each widget.

If you encounter any issues with displaying multiple widgets, ensure that each Portainer service entry in your configuration has a unique name (e.g., `Portainer1`, `Portainer2`, `Portainer3`) as this may affect how Homepage distinguishes between different widgets.

Please refer to the documentation and discussions provided in the context for more detailed instructions and troubleshooting steps if needed.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
