### DISCUSSION TITLE
[Feature Request] Allow nested groups

### DISCUSSION THREAD

**Discussion by Maronato** [gethomepage/homepage#3083] [Feature Requests] [answered]
### Description

Currently there's no (documented?) way to have two or more configured groups in the same row. This means layouts like the following aren't possible:
![CleanShot 2024-03-07 at 22 51 01](https://github.com/gethomepage/homepage/assets/19658460/70bceeb6-1b84-4820-9117-d2f8272a64a1)

Intuitively the layout should look like this:
```yaml
# settings.yaml

layout
    Group A:
        style: row
        columns: 3
    Group B:
        style: column
    Group C:
        style: column
    Group D:
        style: row
        columns: 3
    # This will be the parent of B and C
    Group BC:
        style: row
        columns: 2
```

And then our services would look like:
```yaml
# services.yaml

- Group A:
    - Service 1:
    - Service 2:
    - Service 3:
- Group BC:
    - Group B:
        - Service 4:
    - Group C:
        - Service 5:
        - Service 6:
- Group D:
    - Service 7:
    - Service 8:
    - Service 9:
```

When parsing the tree, Homepage would check if the elements from the Group array are arrays themselves. If so, they'd be treated as Groups. Otherwise, services.

This recursive syntax would allow nesting deeper than two levers, though I believe setting a max of 2 or 3 would suffice.

The example above might look convoluted, but simpler layouts are also currently not possible, such as:
![CleanShot 2024-03-07 at 23 30 35](https://github.com/gethomepage/homepage/assets/19658460/93d5cc08-cd7e-4bc2-a7a2-00f5bcbaf604)
