### DISCUSSION TITLE
InfluxDB as a widget instead of docker portainer  widget

### DISCUSSION THREAD

**Discussion by Whiskey103** [gethomepage/homepage#3087] [Support]
### Description

Is it possible to have InfluxDB as a standalone widget?

All i can find is a docker portainer integration of some kind.
But i have InfluxDB running as seperate LSC in Proxmox.

### homepage version

0.8.8

### Installation method

Other (please describe above)

### Configuration

```yaml
- Influx:
        icon: influxdb
        href: http://pi.local:8086
        siteMonitor: http://influxdb:8086
        server: my-docker
        container: influxdb

#        - Portainer:
#            href: http://192.168.1.91:9000/
#            description: influxDB
#            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
#            widget:
#                type: portainer
#                url: http://192.168.1.91:9000
#                env: 10
#                key: ptr_{key}=
```

### Troubleshooting

.
