### DISCUSSION TITLE
[Feature Request] iobroker Widget

### DISCUSSION THREAD

**Discussion by DickenSerm** [gethomepage/homepage#3090] [Feature Requests]
### Description

Would it be possible to build a widget that would allow you to access iobroker data points?
Or can you somehow implement this yourself using [Simple API](https://github.com/ioBroker/ioBroker.simple-api)?

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided in the context, it seems that Homepage supports the creation of custom widgets through the use of APIs. The Custom API widget configuration allows for the integration of various data points by specifying the API endpoint, method, headers, and other parameters.

To access ioBroker data points, you can indeed use the Simple API plugin for ioBroker, which provides a straightforward way to access objects and states in ioBroker via HTTP/HTTPS requests. You would need to configure the Custom API widget in Homepage to make requests to the ioBroker Simple API endpoint and map the relevant data points to the widget fields.

Here's a basic example of how you might configure the Custom API widget to use ioBroker's Simple API:

```yaml
widget:
  type: customapi
  url: http://iobroker-ip:port/simple-api-endpoint
  method: GET
  headers:
    # Add any required headers here
  mappings:
    - field: key1 # The key from the ioBroker data point
      label: Data Point 1
      format: text # Choose the appropriate format
    # Add more mappings as needed for additional data points
```

You would need to replace `http://iobroker-ip:port/simple-api-endpoint` with the actual URL to your ioBroker Simple API, and `key1` with the actual key for the data point you want to display.

Please note that you should ensure that your ioBroker setup allows for such integrations and that you handle authentication and authorization appropriately to secure access to your ioBroker data.

If you need further assistance with the specifics of the widget configuration or have any other questions, please let me know!

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by DickenSerm** [reply]
Unfortunately that does not work. I always get an API error.

When I retrieve the data point via browser it works:  `http://ip:port/get/0_userdata.0.Wochentag_aktuell`

Unfortunately not via the Custom API Widget:
 ```yaml 
widget:
  type: customapi
  url: http://ip:port
  method: GET
  headers:   
  mappings:
    - field: 0_userdata.0.Wochentag_aktuell
      label: Wochentag
      format: text 
```

Did I miss something?

**Comment by macpo** [comment]
Do you have ideas which information should be displayed in the widget? CPU, memory, adapter to update, amount errors/warnings?

**Reply by DickenSerm** [reply]
I managed it. Thats how it works:

```yaml
        widget:
          type: customapi
          url: http://ip:port/get/0_userdata.0.Wochentag_aktuell
          method: GET
          headers:
          mappings:
            - field: val
              label: Wochentag_aktuell
              format: text
```

@macpo This is a custom api widget in which I simply use a GET command from the Simple API adapter from iobroker.

In this case, as a test, I have the contents of the data point "0_userdata.0.Wochentag_aktuell" output. But in principle you can display any existing data point.
