### DISCUSSION TITLE
[BUG?] gamedig widget fails when fields specified in docker labels

### DISCUSSION THREAD

**Discussion by dud1337** [gethomepage/homepage#3099] [Support] [answered]
### Description

By #3098, this is **not** an issue with `services.yml`. I believe it is with docker compose labels.

`gamedig`, when using docker auto discover, and `homepage.widget.fields` specified as a label, as instructed in documentation [here](https://gethomepage.dev/latest/configs/docker/#widgets): , produces a JSON decode error.

```yaml
...
      - homepage.group=Test
      - homepage.name=Mumble With Fields
      - homepage.widget.type=gamedig
      - homepage.widget.serverType=mumbleping
      - homepage.widget.url=udp://mumble-with-fields:64738
      - homepage.widget.fields=["name","map","players"] # Causes the bug (as does simply ["players"])
```
Fails. Whereas, the same formatting for fields on another app,
```yaml
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.fields=["movies","series","episodes"] # This, for Jellyfin, works fine. As for Sonarr.
```
Works.

* This syntax for gamedig fails with:
    * ut99
    * mumble
    * minecraft (gamedig's type)
* This syntax is fine for Jellyfin and Sonarr - works

![image](https://github.com/gethomepage/homepage/assets/5631021/854edd4a-8351-4fa4-a3ee-44ec965f98dd)

### homepage version

v0.8.9 (c89c488, Mar 10, 2024)

### Installation method

Docker

### Configuration

This test uses two mumble instances.

```yaml
version: "3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - /tmp/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mumble_with_fields:
    image: mumblevoip/mumble-server
    hostname: mumble-with-fields
    labels:
      - homepage.group=Test
      - homepage.name=Mumble With Fields
      - homepage.widget.type=gamedig
      - homepage.widget.serverType=mumbleping
      - homepage.widget.url=udp://mumble-with-fields:64738
      - homepage.widget.fields=["name","map","players"]

  mumble_no_fields:
    image: mumblevoip/mumble-server
    hostname: mumble-no-fields
    labels:
      - homepage.group=Test
      - homepage.name=Mumble No Fields
      - homepage.widget.type=gamedig
      - homepage.widget.serverType=mumbleping
      - homepage.widget.url=udp://mumble-no-fields:64738
```

Modify `docker.yaml` to be
```yaml
---
my-docker:
  socket: /var/run/docker.sock
```

`docker compose up` and navigate to http://localhost:3000

### Container Logs

`homepage-1            | [2024-03-11T04:48:58.375Z] error: undefined`

### Browser Logs

`SyntaxError: JSON.parse: unterminated string at line 1 column 5 of the JSON data`

### Troubleshooting

Irrelevant as same issue occurs for mumble, ut99, and minecraft (when using gamedig's version).
