### DISCUSSION TITLE
Getting error 500 with scrutiny

### DISCUSSION THREAD

**Discussion by Moret84** [gethomepage/homepage#3104] [Support]
### Description

Hello, it seems there is an issue when homepage try to parse the scrutiny result. I have a 500 error on my homepage.

![image](https://github.com/gethomepage/homepage/assets/7255460/5814f204-78ac-4f67-ad56-8c5e9e88b873)

Please let me know if I can help to find out what is happening.

### homepage version

v0.8.9

### Installation method

Docker

### Configuration

```yaml
homepage/compose.yml

version: "3.3"

networks:
  docker-proxy_network:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      GUID: 1000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /media:/mnt/1
    networks:
      - docker-proxy_network
    labels:
      - "swag=enable"
      - "swag_port=3000"
      - "swag_auth=authelia"
```
homepage/config/services.yml
```
- Containers:
    - Scrutiny:
        icon: scrutiny.png
        href: https://scrutiny.domain.com
        server: my-docker
        container: scrutiny
        widget:
            type: scrutiny
            url: 192.168.0.9:8080
```

scrutiny/compose.yml
```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
    labels:
      - "swag=enable"
      - "swag_port=8080"
      - "swag_auth=authelia"

    networks:
      - docker-proxy_network

networks:
  docker-proxy_network:
    external: true
```
```


### Container Logs

homepage  | Listening on port 3000
homepage  | [2024-03-11T09:16:15.029Z] error: undefined
homepage  | [2024-03-11T09:16:15.032Z] error: undefined
homepage  | [2024-03-11T09:16:15.973Z] error: undefined
homepage  | [2024-03-11T09:16:15.984Z] error: undefined
homepage  | [2024-03-11T09:16:21.062Z] error: undefined
homepage  | [2024-03-11T09:16:21.063Z] error: undefined
homepage  | [2024-03-11T09:16:31.128Z] error: undefined
homepage  | [2024-03-11T09:16:41.135Z] error: undefined
homepage  | [2024-03-11T09:16:56.173Z] error: undefined
homepage  | [2024-03-11T09:16:57.855Z] error: undefined
homepage  | [2024-03-11T09:16:57.856Z] error: undefined
homepage  | [2024-03-11T09:17:02.989Z] error: undefined
homepage  | [2024-03-11T09:17:08.017Z] error: undefined
homepage  | [2024-03-11T09:17:21.217Z] error: undefined

### Browser Logs

_No response_

### Troubleshooting

First I was getting a parsing error, but it was because of my configuration: the process encountered the authelia login page and I couldn't get the result whith an api call from the container itself.
Now this part is solved as when I issue `docker exec homepage wget 192.168.0.9:8080/api/summary` and `docker exec homepage cat summary` I get the endpoint output.
