### DISCUSSION TITLE
Error to load a custom font

### DISCUSSION THREAD

**Discussion by R3laxAti0n** [gethomepage/homepage#3105] [Support] [answered]
### Description

Hello everyone,
I use a custom font for my homepage. I added it in my custom.css file with @font-face. I load it from a public sharing link form my nextcloud. The public link is working without issue and prior to the v0.8.9 I had no issue with loading the font.
If you have any idea of the change that induced this issue I am listening, I'm not good enough to put my hand in the code unfortunately...

### homepage version

v0.8.9

### Installation method

Docker

### Configuration

```yaml
Custom.css :
@font-face {
    font-family: 'Readex';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    unicode-range: U+000-5FF;
    src: url('https://next.meyer-guillot.fr/s/ZaCNmGJrdC577Sf/download/ReadexPro-Regular.woff2') format('woff2');
  }

body {
    font-family: 'Readex', sans-serif;
}
```

### Container Logs

No relevant log

### Troubleshooting

No relevant troubleshooting tests

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that the issue might be related to the homepage application's ability to load external resources, such as fonts, from public links after the update to version v0.8.9. Since the error log mentions an error with the httpProxy when trying to call your Nextcloud link, it's possible that there have been changes in the way external resources are handled by the proxy or the application itself in the latest update.

Here are a few steps you can take to troubleshoot this issue:

1. **Check for Breaking Changes**: Look at the release notes for version v0.8.9 to see if there were any breaking changes regarding the loading of external resources or proxy configurations.

2. **Proxy Configuration**: Verify if there have been any changes to the proxy settings within the homepage application that could be blocking the loading of external fonts.

3. **CORS Policy**: Ensure that the server hosting the font file has the appropriate CORS (Cross-Origin Resource Sharing) headers set up to allow your homepage to load the font. Changes in browser security policies or application updates could affect this.

4. **Font Hosting**: As an alternative, consider hosting the font file directly within the homepage container if possible, to avoid cross-origin requests.

5. **Community and Support**: Since this seems to be a specific issue related to a recent update, you might find more information or others with similar issues by checking the homepage community forums, GitHub discussions, or by asking for help directly in the support channels.

6. **Fallback Font**: As a temporary measure, you can specify a fallback font in your CSS to ensure that text is still readable if the custom font fails to load.

7. **Revert to Previous Version**: If the issue is severely impacting your usage and you cannot find a solution, consider reverting to a previous version of homepage that did not have this issue, until a fix is available.

Unfortunately, without access to the specific release notes or update details for version v0.8.9, I cannot provide a more precise solution. If you have access to the homepage documentation or release notes, I would recommend starting there to look for any mentioned changes that could affect font loading.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by benphelps** [comment]
You might have to add `!important` to force it, can try that.

**Reply by R3laxAti0n** [reply]
Thanks for your answer! So I tried something like that 
```
@font-face {
    font-family: 'Readex';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    unicode-range: U+000-5FF;
    src: url('https://next.meyer-guillot.fr/s/ZaCNmGJrdC577Sf/download/ReadexPro-Regular.woff2') format('woff2') !important;
  }

body {
    font-family: 'Readex', sans-serif !important;
}
```
And now I do have the sans-serif that load well as fallback font, but still no luck getting that distant font. 

Additionnaly I tried to put the font in the "images" or in the "icons" folder to load it locally :
`    src: url('/icons/ReadexPro-Regular.woff2') format('woff2') !important;`
But still no luck this way.

I can also say that the proxy error in my docker log is my bad, it's not linked to the issue at hand.

**Comment by shamoon** [comment]
The problem is your font definition somehow. I just copied it directly from Google fonts and this works fine

```css
/* arabic */
@font-face {
    font-family: 'Readex Pro';
    font-style: normal;
    font-weight: 160 700;
    font-display: swap;
    src: url(https://fonts.gstatic.com/s/readexpro/v21/SLXYc1bJ7HE5YDoGPuzj_dh8uc7wUy8ZQQyX2Iw1ZEzehiB9Q1U.woff2) format('woff2');
    unicode-range: U+0600-06FF, U+0750-077F, U+0870-088E, U+0890-0891, U+0898-08E1, U+08E3-08FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE70-FE74, U+FE76-FEFC, U+102E0-102FB, U+10E60-10E7E, U+10EFD-10EFF, U+1EE00-1EE03, U+1EE05-1EE1F, U+1EE21-1EE22, U+1EE24, U+1EE27, U+1EE29-1EE32, U+1EE34-1EE37, U+1EE39, U+1EE3B, U+1EE42, U+1EE47, U+1EE49, U+1EE4B, U+1EE4D-1EE4F, U+1EE51-1EE52, U+1EE54, U+1EE57, U+1EE59, U+1EE5B, U+1EE5D, U+1EE5F, U+1EE61-1EE62, U+1EE64, U+1EE67-1EE6A, U+1EE6C-1EE72, U+1EE74-1EE77, U+1EE79-1EE7C, U+1EE7E, U+1EE80-1EE89, U+1EE8B-1EE9B, U+1EEA1-1EEA3, U+1EEA5-1EEA9, U+1EEAB-1EEBB, U+1EEF0-1EEF1;
  }
  /* vietnamese */
  @font-face {
    font-family: 'Readex Pro';
    font-style: normal;
    font-weight: 160 700;
    font-display: swap;
    src: url(https://fonts.gstatic.com/s/readexpro/v21/SLXYc1bJ7HE5YDoGPuzj_dh8uc7wUy8ZQQyX2Iw_ZEzehiB9Q1U.woff2) format('woff2');
    unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB;
  }
  /* latin-ext */
  @font-face {
    font-family: 'Readex Pro';
    font-style: normal;
    font-weight: 160 700;
    font-display: swap;
    src: url(https://fonts.gstatic.com/s/readexpro/v21/SLXYc1bJ7HE5YDoGPuzj_dh8uc7wUy8ZQQyX2Iw-ZEzehiB9Q1U.woff2) format('woff2');
    unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
    font-family: 'Readex Pro';
    font-style: normal;
    font-weight: 160 700;
    font-display: swap;
    src: url(https://fonts.gstatic.com/s/readexpro/v21/SLXYc1bJ7HE5YDoGPuzj_dh8uc7wUy8ZQQyX2IwwZEzehiB9.woff2) format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }

body {
    font-family: 'Readex Pro', sans-serif !important;
}
```

<img width="704" alt="Screenshot 2024-03-11 at 7 20 43 AM" src="https://github.com/gethomepage/homepage/assets/4887959/14e5386e-dcc6-46a1-b445-9573028fbdef">
