### DISCUSSION TITLE
[Feature Request] Webcheck and WebMap

### DISCUSSION THREAD

**Discussion by aries223** [gethomepage/homepage#3108] [Feature Requests]
### Description

Please add service widgets and icons for these two services:

Webcheck - https://github.com/Lissy93/web-check - A self-hosted website analysis tool.
WebMap- https://github.com/SabyasachiRana/WebMap - Self-hosted browser based frontend to nmap

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To add service widgets and icons for Webcheck and WebMap to your Homepage setup, you will need to define them in your `services.yaml` file. Below are example configurations for each service:

```yaml
- Group C:
    - Webcheck:
        icon: webcheck.png
        href: http://webcheck.host/
        description: Self-hosted website analysis tool
        widget:
          type: custom
          url: http://webcheck.host/api/status
          key: your_api_key_if_needed

    - WebMap:
        icon: webmap.png
        href: http://webmap.host/
        description: Browser based frontend to nmap
        widget:
          type: custom
          url: http://webmap.host/api/status
          key: your_api_key_if_needed
```

Please replace `http://webcheck.host/` and `http://webmap.host/` with the actual URLs where your instances of Webcheck and WebMap are hosted. If these services require an API key for status checks, replace `your_api_key_if_needed` with the actual API key.

For the icons, you will need to add `webcheck.png` and `webmap.png` to your icons directory. Make sure that the icons are named exactly as specified in the `icon` field of the configuration.

If these services have specific API endpoints for status checks, you should replace `http://webcheck.host/api/status` and `http://webmap.host/api/status` with the correct endpoints.

After updating your `services.yaml` file and adding the icons, you may need to restart your Homepage instance for the changes to take effect.

Please note that the `type: custom` in the widget configuration is a placeholder, as Homepage may not have built-in support for these specific services. You might need to develop custom widgets if you require more than just a link and an icon for these services.

If you have developed or found specific widgets for these services that are compatible with Homepage, you can follow the guidelines for adding third-party widgets as described in the Homepage documentation.

Remember to check the documentation for any additional steps or considerations when adding new services and widgets to Homepage.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
