### DISCUSSION TITLE
Implement tabs in a working setup of Service Groups

### DISCUSSION THREAD

**Discussion by IosifZ** [gethomepage/homepage#3117] [Support]
### Description

Hello,

I have a working setup with Service Groups, now I would like to make a tab for each Service Group. I tried the AI but it butchered my file (literally). Can anyone point me in the right direction?

Thanks.

### homepage version

v.0.8.9

### Installation method

Docker

### Configuration

```yaml
settings.yaml file:

'---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
base: https://homepage.xxxxxxxxx.com
headerStyle: boxedWidgets
language: en-RO
color: slate
theme: dark # or light
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
layout:
  - MediaServer:
      tab: MediaServer
      style: row
      columns: 3
  - HomeServer:
      tab: HomeServer
      style: row
      columns: 3      
  - Downloads:
      tab: Downloads
      style: row
      columns: 3      
  - Shortcuts:
      tab: Shortcuts
      style: row
      columns: 3'
```

### Troubleshooting

Tried to talk with AI, he butchered my services.yaml file and I am pretty sure that in the end I broke him. He ran away.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To create a tabbed layout for your Service Groups in Homepage, you need to ensure that each group in your `settings.yaml` file has a `tab` field specified. The `tab` field should be unique for each group that you want to appear under a separate tab. It looks like you've already started doing this correctly in your configuration file.

Here's a refined example based on your provided configuration:

```yaml
layout:
  MediaServer:
    tab: Media
    style: row
    columns: 3
  HomeServer:
    tab: Home
    style: row
    columns: 3      
  Downloads:
    tab: Downloads
    style: row
    columns: 3      
  Shortcuts:
    tab: Shortcuts
    style: row
    columns: 3
```

In this example, each Service Group (`MediaServer`, `HomeServer`, `Downloads`, `Shortcuts`) is assigned to a unique tab (`Media`, `Home`, `Downloads`, `Shortcuts`). This should create four separate tabs on your Homepage, each displaying the corresponding Service Group.

Make sure that the `tab` field values do not contain spaces and are unique for each group. Also, ensure that the indentation in your YAML file is correct, as YAML is sensitive to whitespace.

If you have followed these steps and are still experiencing issues, please provide more details about what is not working, and I can offer more specific advice.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
