### DISCUSSION TITLE
Homepage not respecting label, latitude, longitude, or units in openmeteo weather widget

### DISCUSSION THREAD

**Discussion by chenichadowitz** [gethomepage/homepage#3118] [Support] [answered]
### Description

I believe this is a bug in using/passing the options for the widget. When I first load Homepage, it shows the 'click to allow' prompt for getting the current location, even though I've set a latitude and longitude in my widgets.yaml. If I allow it to get my location, the api call in the network tab in my browser shows the following (replaced latitude and longitude retrieved for privacy). Note the `object+Object` at the end.

`.../api/widgets/openmeteo?latitude=xx.xxxxx&longitude=yy.yyyyy&index=4&style=%5Bobject+Object%5D`

I believe this is also related to https://github.com/gethomepage/homepage/discussions/675

### homepage version

v0.8.9 (c89c488, Mar 10, 2024)

### Installation method

Docker

### Configuration

```yaml
widgets.yaml

- openmeteo:
  label: Home
  latitude: 50.449684
  longitude: 30.525026
  timezone: America/New_York
  units: imperial
  cache: 5 # Time in minutes to cache API responses, to stay within limits
  format:
    maximumFractionDigits: 1
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

n/a

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems like there might be an issue with how the `format` option is being handled in the Open-Meteo widget configuration. The `style=%5Bobject+Object%5D` part of the URL suggests that an object is being passed as a query parameter, which is likely incorrect and should be a string representation of the formatting options instead.

To resolve this issue, please ensure that the `format` option in your `widgets.yaml` is correctly specified. If the issue persists even after verifying the configuration, it could be a bug with the widget's handling of the `format` option.

Since you are using Docker for installation, you can also check the Docker container logs for any error messages that might give more insight into the problem. Use the following command to view the logs:

```sh
docker logs <container_name>
```

Replace `<container_name>` with the actual name or ID of your Homepage container.

If you continue to experience issues, consider reaching out for support using the 'Ask AI' button on the documentation pages, opening a GitHub discussion, or checking the `#ai-support` channel on Discord as mentioned in the troubleshooting documentation.

Additionally, you can check for any updates or known issues on the Homepage GitHub repository that might be related to this problem.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by chenichadowitz** [reply]
Not bad! Unless I'm missing something, I think there's a bug in how the Open-Meteo widget handles the configuration parameters.

**Comment by shamoon** [comment, marked as answer]
This would imply the widget essentially does not work, which I do not think is the case. Sometimes formatting gets lost in copy and paste, but for example the formatting of the config above is not correct, I’d start there.

**Reply by chenichadowitz** [reply]
What's the error in the formatting of the widgets.yaml I provided? It's based directly on the example at https://gethomepage.dev/latest/widgets/info/openmeteo/
```
- openmeteo:
  label: Home
  latitude: 50.449684
  longitude: 30.525026
  timezone: America/New_York
  units: imperial
  cache: 5 # Time in minutes to cache API responses, to stay within limits
  format:
    maximumFractionDigits: 1
```
