### DISCUSSION TITLE
NextCloud Isn't Showing Proper File Count

### DISCUSSION THREAD

**Discussion by iamronr** [gethomepage/homepage#3119] [Support]
### Description

NextCloud isn't showing the proper file count in the widget.

Here is a screenshot of one of my NextCloud containers (NextCloud TRC), and it's clear it has more than 0 files.
![TRC 5](https://github.com/gethomepage/homepage/assets/698319/7d9d74f4-4802-4825-bc92-124f60d88573)
![TRC 6](https://github.com/gethomepage/homepage/assets/698319/eed2072f-bd05-4275-ba10-eb62017a8432)

### homepage version

v0.8.9 (c89c488, Mar 10, 2024)

### Installation method

Docker

### Configuration

```yaml
I'm running the latest of Homepage and NextCloud in Docker Desktop on MacOS, running Sonoma. -> image: nextcloud:apache
```

```yaml
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=911
      - PGID=1001
      - UMASK=002
      - TZ=America/New_York
    ports:
      - 3030:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/iamronr/Server/homepage/config:/app/config
      - /Users/iamronr/Server/homepage/images:/app/public/images
      - /Users/iamronr/Server/homepage/icons:/app/public/icons
    restart: unless-stopped
```

```yaml
  nextcloud-trc:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nextcloud:apache
    container_name: nextcloud-trc
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
      - POSTGRES_HOST=nc-postgres-trc
      - POSTGRES_PASSWORD=########
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres-trc
    volumes:
      - /Users/iamronr/Server/nextcloud-trc/nextcloud:/var/www/html
      - /Users/iamronr/Server/nextcloud-trc/apps:/var/www/html/custom_apps
      - /Users/iamronr/Server/nextcloud-trc/config:/var/www/html/config
      - /Users/iamronr/Server/nextcloud-trc/data:/var/www/html/data
    ports:
      - 8085:80
      - 445:443
    depends_on:
      - nextcloud-postgres-trc
    restart: unless-stopped
```

### Troubleshooting

```yaml
    - Nextcloud-TRC:
        icon: nextcloud.png
        href: https://cloud.theramsayco.com
        siteMonitor: https://cloud.theramsayco.com
        description: The Ramsay Company's Cloud & Drive Storage
        widget:
            type: nextcloud
            url: https://cloud.theramsayco.com
            username: iamronr
            password: sept0923
       Added this --> fields: ["freespace", "activeusers", "numfiles", "numshares"]
```

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To address the issue with the NextCloud widget not showing the proper file count, we should first ensure that the widget configuration is correct and that the NextCloud instance is properly connected and configured to report the file count.

Based on the context provided, here are a few steps you can take to troubleshoot the issue:

1. **Check Widget Configuration**: Ensure that the widget configuration for NextCloud in your Homepage setup includes the `numfiles` field, as this is the field responsible for displaying the number of files. The configuration should look something like this:

```yaml
widget:
  type: nextcloud
  url: https://nextcloud.host.or.ip:port
  key: token # or username and password
  fields: ["numfiles", ...] # Ensure 'numfiles' is included
```

2. **Verify NextCloud API Access**: Make sure that the Homepage instance can access the NextCloud API. You can test this by using `curl` to access the NextCloud API directly. The command would be similar to the examples provided for other services in the troubleshooting documentation, but adapted for NextCloud.

3. **Check for Deprecated Fields**: Note that some fields like `cpuload` and `memoryusage` were deprecated in version v0.6.18 of Homepage. Ensure that you are not using any deprecated fields in your configuration.

4. **Review NextCloud Settings**: In NextCloud, under Settings > System, verify that the API token (if used) is correct and has the necessary permissions to access file count information.

5. **Check for Updates**: Ensure that both Homepage and NextCloud are running the latest versions, as updates may contain bug fixes or enhancements that could resolve your issue.

6. **Review Logs**: Although you mentioned that you do not have container logs or browser logs, it would be helpful to review them if possible. They can provide clues about any errors or issues in the communication between Homepage and NextCloud.

7. **Permissions**: Ensure that the user account or token used by Homepage to connect to NextCloud has the necessary permissions to retrieve file count information.

If you continue to experience issues after following these steps, you may need to seek further assistance from the Homepage community or support channels. You can also check the GitHub issues for Homepage to see if others have reported similar problems and if there are any suggested solutions.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
