### DISCUSSION TITLE
New additionField does not appear on display

### DISCUSSION THREAD

**Discussion by ArthurMitchell42** [gethomepage/homepage#3121] [Support] [answered]
### Description

Trying the new list feature, I don't seem to be able to get the additionalField parameter to display:
```yaml
    - UPS list:
        href: http://10.0.10.9:9995?addr=127.0.0.1&dev=ups
        description: CyberPower CP900EPFCLCD
        icon: http://10.0.10.9:9995/static/favicon.ico
        widget:
            type: customapi
            url: http://10.0.10.9:9995/json?target=127.0.0.1:3493
            refreshInterval: 60000
            method: GET
            display: list
            mappings:
                - field: 
                    ups: 
                      nutcase.battery.runtime
                  label: Runtime
                  additionalField:    # This clause dosen't appear
                    ups: 
                      input.voltage		
                - field: 
                    ups: nutcase.ups.load.watts
                  label: Power
                  suffix: W
                  additionalField:    # This clause dosen't appear
                    ups: 
                      nutcase.ups.status.composite		
                  additionalFieldColor: yellow-500 
                - field: 
                    ups: nutcase.ups.status.composite
                  label: Status
                - field: 
                    ups: input.voltage
                  label: Input
                  format: text
                  suffix: V
                - field: 
                    ups: nutcase.ups.client-check
                  label: Client status
                  additionalField:   # This clause dosen't appear
                    ups: 
                      nutcase.ups.client-count
                - field: 
                    ups: nutcase.ups.client-count
                  label: Clients
```
![image](https://github.com/gethomepage/homepage/assets/82239494/64ebcdbe-d328-415c-a4c4-717c1aa7d25e)

### homepage version

v0.8.9

### Installation method

Docker

### Troubleshooting

I've made sure the fields are in the JSON

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the context provided, it seems that you are trying to use the `additionalField` parameter within the `list` display option for the `customapi` widget, but it's not displaying as expected.

First, ensure that the `additionalField` is correctly formatted according to the documentation. The `field` within `additionalField` should be a YAML string or object that matches the structure of your data source. Also, make sure that the `additionalFieldColor` is a supported option; it should be `color` and the value should be one of the allowed options (`"theme"`, `"adaptive"`, `"black"`, `"white"`).

Here's a corrected version of your configuration for the `additionalField`:

```yaml
mappings:
    - field: 
        ups: 
          nutcase.battery.runtime
      label: Runtime
      additionalField:
        field: 
          ups: 
            input.voltage
        color: "theme" # or "adaptive", "black", "white"
    # ... other mappings
```

If the `additionalField` is still not appearing, there might be an issue with the version of the software you are using or a bug. As per the discussion in the GitHub repository, the list view feature may not have been released in the version you are using (v0.8.8 as per one of the discussions). You might need to update to a newer version or use the `main` image to access unreleased features.

If you are already using the latest version (v0.8.9 as you mentioned), and the issue persists, it could be a bug or a feature that is not yet fully implemented. In this case, you should report the issue on the GitHub repository for the developers to investigate.

Remember to replace the actual URLs and sensitive information with placeholders when sharing your configuration publicly.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
