### DISCUSSION TITLE
Trouble With Docker Integrations

### DISCUSSION THREAD

**Discussion by searay345** [gethomepage/homepage#3124] [Support] [answered]
### Description

Hello, I'm trying to see my container's status in Homepage. When I try to add the server and container, I get an API Error. I'm running homepage via Docker through OMV (latest release) on a Pi 4. I'm stuck and I am not sure what I am doing wrong here. Any help is appreciated. I'll paste my configurations below. 

If I uncomment these two lines in the docker.yml file, I get a different error. 

#  my-docker:
#    socket: /var/run/docker.sock

### homepage version

0.8.9

### Installation method

Docker

### Configuration

```yaml
My Homepage Docker Container Compose:

version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: XXX
      PGID: XXX
    ports:
      - 3020:3000
    volumes:
      - /srv/dev-disk-by-uuid-XXXXXXXXXXX/Config/Homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

My Services.yml config: 

- My Website:
    - Wordpress:
        icon: wordpress-light.png
        href: https://XXXX.YYYYYY.com
        description: My NEW Website!
        server: my-docker
        container: Wordpress

My Docker.yml file:

---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock
```

### Troubleshooting

API Error: Cannot read properties of null (reading 'my-docker')

If I uncomment the two lines mentioned above in the docker.yml file, I get this error:

API Error: connect EACCES /var/run/docker.sock

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems like you are encountering permission issues with the Docker socket. The `EACCES` error indicates that the process does not have the necessary permissions to access the Docker socket.

Here are a few steps you can take to troubleshoot the issue:

1. **Ensure Proper Permissions**: The Docker socket (`/var/run/docker.sock`) should be accessible by the user running the Homepage container. You can set the `PUID` and `PGID` environment variables to match the user and group IDs that have access to the Docker socket on the host system.

2. **Running as Non-Root**: If you prefer not to run the Homepage container as root, you can use the `docker socket proxy` as a safer alternative. This requires setting up a proxy container that exposes a restricted Docker API. You can find more information on setting up a Docker Socket Proxy in the [Homepage documentation](https://gethomepage.dev/latest/configs/docker).

3. **Check Volume Bindings**: Ensure that the volume binding for the Docker socket is correct in your `docker-compose.yml` file. If you are using a Docker Socket Proxy, you should not bind the Docker socket directly to the Homepage container.

4. **Check Docker Configuration**: If you are using the Docker Socket Proxy, ensure that your `docker.yaml` file is configured correctly to point to the proxy instead of the direct socket. For example:

```yaml
my-docker:
  host: dockerproxy
  port: 2375
```

5. **Check Service Configuration**: In your `services.yaml`, ensure that the `server` key matches the name you've given to your Docker instance in the `docker.yaml` file. If you are using a Docker Socket Proxy, the `server` should be the name of the proxy service.

6. **Review Logs**: Check the logs of the Homepage container for any additional error messages that might provide more insight into the issue. You can view the logs by running `docker logs homepage`.

7. **Check Homepage Version Compatibility**: Ensure that the version of Homepage you are using is compatible with the configuration you are attempting. You can check the [Homepage GitHub repository](https://github.com/gethomepage/homepage) for any version-specific documentation or issues.

8. **Ask for Help**: If you continue to have issues, consider using the Homepage AI Bot for assistance, opening a discussion on the [Homepage GitHub](https://github.com/gethomepage/homepage/discussions), or asking for help in the [#ai-support channel on Discord](https://discord.com/channels/1019316731635834932/1177885603552038993).

Remember to replace `XXX` and `XXXX.YYYYYY.com` with your actual user/group IDs and domain in your configuration files.

If you need further assistance, please provide more details about the exact error messages you are seeing and any additional steps you have taken.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
