### DISCUSSION TITLE
[Feature Request] Services URL Open Without BaseURL

### DISCUSSION THREAD

**Discussion by adamzvolanek** [gethomepage/homepage#3126] [Feature Requests] [answered]
### Description

I am currently using Unraid and have HomePage running on it's own IP address for my internal DNS re-direct to have all `*.domain.tld` on my LAN be pointed directly back to the the Homepage docker's dedicated_IP:80. In doing so, the URL originally typed does not get re-placed in the browser and clicking on the services **appends** the `href` tag.

e.g. navigating to subdomain.domain.tld hits my DNS and redirects to the homepage_IP albiet leaves the original URL in place. Selecting services results in the browser attempting to navigate to: `subdomain.domain.tld/server_ip:service_port`. Where `server_ip:server_port` is what I have defined in the href field.

Would it be possible for the href to act as a "full" url re-direct from the homepage, especially when opening in a new tab?

### Other

- `services.yaml`

```yaml
- Family:
    - Service_name:
        href:server_ip:server_port
        description: Items
```

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

It sounds like you're experiencing an issue with relative URLs being appended to the current domain in the browser's address bar when clicking on services in HomePage. To ensure that the `href` attribute acts as a full URL redirect, you should include the full URL, including the scheme (http or https), in the `href` attribute for each service.

For example, your `services.yaml` should look like this:

```yaml
- Family:
    - Service_name:
        href: http://server_ip:server_port
        description: Items
```

or if you're using HTTPS:

```yaml
- Family:
    - Service_name:
        href: https://server_ip:server_port
        description: Items
```

Make sure to replace `http://server_ip:server_port` with the actual full URL you want the service to redirect to. This should ensure that when you click on a service, it opens the correct full URL in a new tab or the same tab, depending on your browser settings and whether you have set `target="_blank"` for the links.

If you continue to have issues, please check the HomePage documentation and discussions for any additional configuration settings that might be relevant to your setup. If necessary, you can also consider filing a bug report or asking for help in the HomePage community discussions.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
