### DISCUSSION TITLE
Docker stats don't open

### DISCUSSION THREAD

**Discussion by henkiewie** [gethomepage/homepage#313] [Support] [answered]
My system updated to the latest this morning. v0.4.0 (de4ce73, Oct 1, 2022)
But the green button for the docker info stopped working.
Should i change something in the config?
The release notes suggest it was completely reworked.

Thanks in advance.

**Comment by ironfistperez** [comment]
Same here.

**Comment by JazzFisch** [comment]
> My system updated to the latest this morning. v0.4.0 ([de4ce73](https://github.com/benphelps/homepage/commit/de4ce73a9af25427dd72b0c9a0b10f8cfca4b272), Oct 1, 2022) But the green button for the docker info stopped working. Should i change something in the config? The release notes suggest it was completely reworked.
> 
> Thanks in advance.

Does your widget definition contain both the `server` and `container` properties?  If it does, can you please post a sample of your services.yaml file (preferably inside of a ```yaml block) with your private information obscured?

**Reply by henkiewie** [reply]
Some example. I changed nothing in the .yaml files. Also tried the main version nightly (a63f71d, Oct 2, 2022). Same effect.

`    - PiHole:
        icon: pihole
        href: http://pihole.rpi-lite.lan/admin
        description: DNS and AdBlocker
        container: pihole
        widget:
          type: pihole
          url: http://192.168.1.29:82`

`     - Portainer:
        icon: portainer
        href: https://portainer.rpi-lite.lan/#!/1/docker/containers
        description: Docker management
        container: portainer
        widget: 
          type: portainer
          url: http://192.168.1.29:9001
          env: 1
          key: 12345678`

The code looks a bit funny inside the code blocks.

**Reply by henkiewie** [reply]
For testing purposes. I changed the services.yaml to one entry. Still the same result.
 So its reading the values from docker.
Is it possible to 'temporary' disable CORS so i can see in the browser console what is happening in the backend?
Now it has no errors.
![Screenshot 2022-10-02 at 10 02 38](https://user-images.githubusercontent.com/74558874/193444281-337cc800-6ca5-42c5-ba9a-fe006a58919d.png)

**Reply by JazzFisch** [reply]
Your provided configuration is missing the `server` property.  Widget require both the `server` as well as `container` property.

**Comment by ericlokz** [comment]
I have the same problem.v0.4.0

**Comment by benphelps** [comment]
What browser does the issue happen on?

**Reply by henkiewie** [reply]
Tried on all. I have tried chrome, firefox, safari android chrome firefox.

**Reply by JazzFisch** [reply]
Can you confirm that you have provided both the `server` as well as `container` properties?

**Reply by henkiewie** [reply]
```
docker-compose.yml;
#--------------------------------------------------------------------------------------------#`
#                                 homepage                                                   #
#--------------------------------------------------------------------------------------------#
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3456:3000
    volumes:
      - /home/pi/Templates/dashy/icons:/app/public/images
      - /home/pi/Templates/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /disks/USB1:/USB1
      - /disks/USB2:/USB2
      - /disks/ARGON:/ARGON
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam

```
services.yaml

````
#- My First Group:
#    - My First Service:
#        href: http://localhost/
#        description: Homepage is awesome

#- My Second Group:
#    - My Second Service:
#        href: http://localhost/
#        description: Homepage is the best

#- My Third Group:
#    - My Third Service:
#        href: http://localhost/
#        description: Homepage is 😎

- Test:

    - Nginx Proxy Manager:
        icon: nginxproxymanager
        href: https://npm.rpi-lite.lan
        description: Nginx Proxy Manager
        container: npm_app
        widget:
          type: npm
          url: http://192.168.1.29:81
          username: test@123.45678com
          password: canyoufixit ;-)
````
