### DISCUSSION TITLE
Calendar widget, iCal intergation and Exchange Online calendar

### DISCUSSION THREAD

**Discussion by lbalogh** [gethomepage/homepage#3132] [Feature Requests]
### Description

Hi,

The calendar widget doesn't seem to be able to parse ics from Exchange Online. It show the following error : Unsupported RFC prop EXDATE in EXDATE;TZID=W.

Configuration :

```
- Calendar:
    - Calendar:
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          timezone: Europe/Zurich
          integrations:
            - type: ical
              url: https://[...]/calendar.ics
              name: Work
              color: green
```

Result when reloading Homepage :

```
Something went wrong.
Error: Unsupported RFC prop EXDATE in EXDATE;TZID=W.

    at g (https://home.mydomain.com/_next/static/chunks/6357.b8ce8f0e37fc8980.js:1:1873)
    at h (https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:34749)
    at div
    at div
    at div
    at c (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:2588)
    at M (https://home.mydomain.com/_next/static/chunks/3594.395ba74fc5f864bd.js:1:8089)
    at h (https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:34749)
    at n (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:17107)
    at q (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:32175)
    at div
    at li
    at H (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:36057)
    at ul
    at M (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:40120)
    at div
    at https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:78651
    at div
    at l (https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:107402)
    at https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:96808
    at https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:95576
    at l (https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:107402)
    at https://home.mydomain.com/_next/static/chunks/7012-e3db63444157287b.js:1:76590
    at div
    at J (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:40620)
    at div
    at div
    at xe (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:59967)
    at n (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:17107)
    at https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:90767
    at pe (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:57973)
    at div
    at div
    at div
    at ke (https://home.mydomain.com/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:67612)
    at a (https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:16143)
    at a (https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:15786)
    at s (https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:16702)
    at u (https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:15214)
    at https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:90767
    at https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:14465
    at l (https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:1249)
    at n (https://home.mydomain.com/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:5713)
    at r (https://home.mydomain.com/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)
    at Y (https://home.mydomain.com/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)
    at ie (https://home.mydomain.com/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)
```

Unfortunately, I can't share my calendar URL.

Any idea ?

### homepage version

v0.8.9 (c89c488, Mar 10, 2024)

### Installation method

Docker

### Configuration

```yaml
- Calendar:
    - Calendar:
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          timezone: Europe/Zurich
          integrations:
            - type: ical
              url: https://[...]/calendar.ics
              name: Work
              color: green
```

### Troubleshooting

N/A
