### DISCUSSION TITLE
Local Icons Without Docker

### DISCUSSION THREAD

**Discussion by gcortes** [gethomepage/homepage#3134] [Support] [answered]
### Description

I'm running HomePage in a Proxmox VE container without docker. I want to use a custom icon. I tried putting in the images/icons. The resulting home page shows not found. Where do you put local icons and how do you refer to them when not using Docker?

The image is a jpg. It for Phillips Hue since I couldn't find on the icons site.

### homepage version

not sure, just installed a couple of weeks ago

### Installation method

Other (please describe above)

### Configuration

```yaml
- Phillips Hue:
        icon: /icons/Phillips-Hue.jpg
        href: http://10.0.0.186
        ping: http://10.0.0.186
        statusStyle: "dot"
        description: Phillips Hue Hub
```

### Troubleshooting

The page just shows the missing image icon

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the context provided, when running HomePage in a Proxmox VE container without Docker, you should place your custom icons in the `public` directory of your HomePage installation. The path you refer to in your configuration should be relative to the `public` directory.

For example, if you have placed your `Phillips-Hue.jpg` icon in `/app/public/icons/`, your configuration should reference the icon like this:

```yaml
- Phillips Hue:
    icon: /icons/Phillips-Hue.jpg
    href: http://10.0.0.186
    ping: http://10.0.0.186
    statusStyle: "dot"
    description: Phillips Hue Hub
```

Make sure that the `public` directory is correctly mapped to where you are storing your icons in the Proxmox VE container. If you are still experiencing issues, you may need to check the permissions of the icon file to ensure that the HomePage application has read access to it.

If you have followed these steps and the issue persists, please provide more details about your installation method and the exact path where you placed the icon file, so I can assist you further.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
