### DISCUSSION TITLE
Hompage not showing any of my services

### DISCUSSION THREAD

**Discussion by AKK2112** [gethomepage/homepage#3135] [Support] [answered]
### Description

Hello, 

I was adding a service to my homepage and now none of the services display. I can see the bookmarks, and the search bar at the top, and the resources. But nothing else. 

![image](https://github.com/gethomepage/homepage/assets/86672952/9331e898-ca0e-42ce-9caa-2fe7dce9c37d)

### homepage version

v0.8.9

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Hypervisor:
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve1

- DNS:
    - PiHole:
        icon: pi-hole.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
        description: Ubuntu Server Pihole
        widget:
            type: pihole
            url: "{{HOMEPAGE_VAR_PIHOLE_API_URL}}"
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
- Docker:
    - Home Assistant:
        icon: home-assistant.svg
        href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
        description: home assistant yippie
        widget:
            type: homeassistant
            url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
            key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
    - Portainer:
        icon: portainer.png
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: Portainer
- Media:
    -Jellyfin:
        icon: jellyfin.png
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Jellyfin :)
        # widget:
        #     type: jellyfin
        #     url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        #     key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
- Network:
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
        description: network
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
            username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
            password:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
    - Synology:
        icon: synology.png
        href: "{{HOMEPAGE_VAR_NAS_URL}}"
        description: nas
```

### Browser Logs

[2024-03-18T21:03:48.683Z] error: Failed to load services.yaml, please check for errors
[2024-03-18T21:03:48.684Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function

### Troubleshooting

I recomposed the container, went through this link again: https://technotim.live/posts/homepage-dashboard/ and went through the discussion board and didnt find anything.

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the error message from the browser logs, it seems there is an issue with the structure of your `services.yaml` file. The error `TypeError: servicesGroup[Object.keys(...)[0]].map is not a function` suggests that the application is expecting an array where it is actually getting something else (likely an object or a non-array value).

Looking at your provided `services.yaml` configuration, there is a syntax error in the `Media` group. The `-Jellyfin:` entry is missing a space after the hyphen, which should be `- Jellyfin:`. YAML is very sensitive to indentation and formatting, so this small mistake can cause the entire file to be read incorrectly.

Here's the corrected section:

```yaml
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Jellyfin :)
        # widget:
        #     type: jellyfin
        #     url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        #     key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
```

Please correct this in your `services.yaml` file and try reloading the homepage. If you continue to experience issues, ensure that all other entries in your YAML file are correctly formatted and that you are using spaces (not tabs) for indentation.

If the problem persists after making these changes, you may want to validate your entire YAML file using a YAML linter to catch any other potential formatting issues.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
