### DISCUSSION TITLE
problem setting up custom api with comed realtime

### DISCUSSION THREAD

**Discussion by kakachen001** [gethomepage/homepage#3137] [Support] [answered]
### Description

I believe my mapping are correct.
![comed](https://github.com/gethomepage/homepage/assets/78639368/265e6947-49f5-4a8e-9617-ed65733bc5d4)
comed api  https://hourlypricing.comed.com/api?type=5minutefeed

### homepage version

v0.8.9

### Installation method

Docker

### Configuration

```yaml
- Information:
    - ComEd Pricing:
        icon: https://hourlypricing.comed.com/wp-content/uploads/2023/03/hp-favicon-new-36x36.png
        href: https://hourlypricing.comed.com/live-prices/five-minute-prices/
        description: Current 5 Minute Price
        widget:
          type: customapi
          url: https://hourlypricing.comed.com/api?type=5minutefeed
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          method: GET
          mappings:
            - field: price
              label: Price
              format: text
            - field: millisUTC
              label: Time
              format: text
```

### Troubleshooting

I am new to program tried chatgpt but no help
