### DISCUSSION TITLE
Private Google Calendar Invalid Integration

### DISCUSSION THREAD

**Discussion by Linguiniotta** [gethomepage/homepage#3138] [Support] [answered]
### Description

Similar to #2410, my private Google Calendar is not working.

My calendar widget with Sonarr and Radarr integration works, only the `ical` type does not.

The homepage shows:
```
API Error Information
API Error: ical: Invalid integration
```

- I tried with new and existing calendars, both does not work.
- The URL / `.ics` is accessible with curl, and is downloaded when entered in browser.
- The URL / `.ics` works and is tested working with Vivaldi Calendar.
- The URL / `.ics` came from `Integrate Calendar` > `Secret address in iCal format`.
- I have restarted the container a lot of times, no error shows in the compose logs.
- Was previously `v0.8.8`, updated to recent `v0.8.9` but issue still persists.
- Tried changing `name` to different values, enclosed and not enclosed in quotation marks.

What am I doing wrong?

### homepage version

v0.8.9 (c89c488, Mar 11, 2024)

### Installation method

Docker

### Configuration

```yaml
`services.yaml`

- Calendar:
    - "":
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          maxEvents: 10
          showTime: true
          integrations:
            - type: sonarr
              service_group: Media
              service_name: Sonarr
              params:
                unmonitored: true
            - type: radarr
              service_group: Media
              service_name: Radarr
              params: 
                unmonitored: true
            - type: ical
              url: https://calendar.google.com/calendar/ical/XXXX%40group.calendar.google.com/private-YYYY/basic.ics
              name: Public
              color: magenta
              params: 
                showName: true
    - "":
        widget:
          type: calendar
          view: agenda
          maxEvents: 11
          showTime: true
          previousDays: 3
          integrations:
            - type: ical
              name: "Calendar no workyy"
              url: https://calendar.google.com/calendar/ical/XXXX%40group.calendar.google.com/private-YYYY/basic.ics
              color: zinc
              params:
                showName: true
```

### Container Logs

`docker compose logs -f homepage`
```bash
homepage  | Listening on port 3000

```

### Troubleshooting

`docker exec homepage ping -c 4 calendar.google.com`
```bash
PING calendar.google.com (172.217.27.14): 56 data bytes
64 bytes from 172.217.27.14: seq=0 ttl=57 time=50.180 ms
64 bytes from 172.217.27.14: seq=1 ttl=57 time=50.120 ms
64 bytes from 172.217.27.14: seq=2 ttl=57 time=49.923 ms
64 bytes from 172.217.27.14: seq=3 ttl=57 time=50.088 ms

--- calendar.google.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 49.923/50.077/50.180 ms
```

`curl https://calendar.google.com/calendar/ical/XXXX%40group.calendar.google.com/private-YYYY/basic.ics`
```bash
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Public
X-WR-TIMEZONE:Asia/Singapore
END:VCALENDAR
```

**Comment by shamoon** [comment]
Some specific ics files aren't compatible at the moment but in general google calendars work fine, for example:

```yaml
     - EPL Calendar:
        widget:
            type: calendar
            showTime: true
            maxEvents: 10
            integrations:
                - type: ical
                  url: https://calendar.google.com/calendar/ical/871e3e037b64fbdc7d374bac61978ab9b71d569da147a0b0abd4337259314288%40group.calendar.google.com/public/basic.ics
                  name: EPL Fixtures
                  color: purple   
```

<img width="753" alt="Screenshot 2024-03-18 at 11 39 20 PM" src="https://github.com/gethomepage/homepage/assets/4887959/13a005d9-1533-4182-a3b1-1b84b3b2c83c">

I dont see anything obviously incorrect about your config above, assuming that is the formatting you have in your yaml

**Comment by m3lv1lle** [comment, marked as answer]
I had the exact same problem with this config:
```
- Productivity:
    - "":
        widget:
          type: calendar
          showTime: true
          maxEvents: 10
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/myprivateurl
              name: calendar
              color: purple

``` 
Changing the "" to something else magically solved it. My current file looks like this and works perfectly.
```
- Productivity:
    - Calendar:
        widget:
          type: calendar
          showTime: true
          maxEvents: 10
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/myprivateurl
              name: calendar
              color: purple

```

**Reply by Linguiniotta** [reply]
You are right. The issue seems to be from the `""`.

However, I did not like putting text above the calendar, so I replaced it with an [empty character](https://emptycharacter.com).

The caveat for this is that using the same empty character as name for multiple widgets results into another API Error. So to remedy that, I just used a different empty character for each widget.
```yaml
- Calendar:
    # U+200E
    - ‎:
        widget:
          type: calendar
            ...
            - type: ical
              url: https://calendar.google.com/calendar/ical/XXXX%40group.calendar.google.com/private-YYYY/basic.ics
              name: Public
              color: magenta
              params: 
                showName: true
    # U+200A
    -  :
        widget:
        ...
```
Thanks a lot!
