### DISCUSSION TITLE
Adguard shows "API Error Info"

### DISCUSSION THREAD

**Discussion by Deadlyender** [gethomepage/homepage#3139] [Support] [answered]
### Description

Adguard shows "API Error Info," password is simple, so is username,I cannot figure out what the problem is. I am using unraid
![image](https://github.com/gethomepage/homepage/assets/123915655/4c2f0bd9-4610-4126-9dba-a5fadc3ed644)

### homepage version

v0.7.1 (3cf88d2, Oct 4, 2023)

### Installation method

Unraid

### Configuration

```yaml
- Utility:
    - Smokeping:
        href: http://192.168.0.200:5124/smokeping/
        icon: smokeping.png
        description: Monitor latency
    - Adguard:
        href: http://192.168.0.5:3004/
        icon: adguard-home.png
        description: Home Ad-blocker
        widget:
            type: adguard
            url: http://192.168.0.5:3004
            username: username
            password: password
```

### Troubleshooting

Changed the password to something more simple did not work. I had to uninstall adguard, and before uninstallation it was working on homepage. After reinstalling on br0 network(might be the problem), it does not show the satistic anymore.
