### DISCUSSION TITLE
CustomAPI Widgets

### DISCUSSION THREAD

**Discussion by jgiddens** [gethomepage/homepage#3142] [Support] [answered]
### Description

Hello, I am trying to use the CustomAPI widget to pull my external IP address and display it.  My goal is to have it compare to the Gluetun IP address so I can make sure my Gluetun container is on a different IP address than the rest of my infrastructure.

I am trying to use this API:  https://www.ipify.org/ to return my IP address.  If you 
`curl 'https://api.ipify.org?format=json'
{"ip":"108.67.20.63"}`

So, I created this in my services.yaml:

>     - Public IP:
>         widget:
>             type: customapi
>             url: https://api.ipify.org/?format=json
>             refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
>             method: GET # optional, e.g. POST
>             mappings:
>                 field: ip # needs to be YAML string or object
>                 label: Public IP
>                 format: text # optional - defaults to text  

When I reload Homepage I see the new widget displayed but it has the error:

> Type Error: f.slice is not a function

When I expand that notice I get this:

> at u (https://homepage.jasong.cc/_next/static/chunks/3540.14e9ed84005238ed.js:1:2927)
>     at h (https://homepage.jasong.cc/_next/static/chunks/7012-e3db63444157287b.js:1:34749)
>     at n (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:17107)
>     at q (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:32175)
>     at div
>     at li
>     at H (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:36057)
>     at ul
>     at M (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:40120)
>     at div
>     at https://homepage.jasong.cc/_next/static/chunks/7012-e3db63444157287b.js:1:78651
>     at div
>     at l (https://homepage.jasong.cc/_next/static/chunks/7012-e3db63444157287b.js:1:107402)
>     at https://homepage.jasong.cc/_next/static/chunks/7012-e3db63444157287b.js:1:96808
>     at https://homepage.jasong.cc/_next/static/chunks/7012-e3db63444157287b.js:1:95576
>     at l (https://homepage.jasong.cc/_next/static/chunks/7012-e3db63444157287b.js:1:107402)
>     at https://homepage.jasong.cc/_next/static/chunks/7012-e3db63444157287b.js:1:76590
>     at div
>     at J (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:40620)
>     at div
>     at div
>     at xe (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:59967)
>     at n (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:17107)
>     at https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:90767
>     at pe (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:57973)
>     at div
>     at div
>     at div
>     at ke (https://homepage.jasong.cc/_next/static/chunks/pages/index-0465cc6b7f00ba7a.js:1:67612)
>     at a (https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:16143)
>     at a (https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:15786)
>     at s (https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:16702)
>     at u (https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:15214)
>     at https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:90767
>     at https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:14465
>     at l (https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:1249)
>     at n (https://homepage.jasong.cc/_next/static/chunks/pages/_app-fd53e57b1f81f779.js:1:5713)
>     at r (https://homepage.jasong.cc/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)
>     at Y (https://homepage.jasong.cc/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)
>     at ie (https://homepage.jasong.cc/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)

Ideas?

### homepage version

v0.8.9 (c89c488, Mar 10, 2024)

### Installation method

Docker

### Configuration

```yaml
- Public IP:
    widget:
        type: customapi
        url: https://api.ipify.org/?format=json
        refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
        method: GET # optional, e.g. POST
        mappings:
            field: ip # needs to be YAML string or object
            label: Public IP
            format: text # optional - defaults to text
```

### Troubleshooting

/app # curl 'https://api.ipify.org?format=json'
{"ip":"108.67.20.63"}/

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that there is an issue with the way the `mappings` field is structured in your `services.yaml` configuration for the CustomAPI widget. The error message "Type Error: f.slice is not a function" suggests that there is a problem with the data processing within the widget, possibly due to an incorrect or unexpected data format.

To resolve this issue, you should adjust the `mappings` field to correctly map the JSON response from the API to the widget. The correct structure for the `mappings` field should be an array of objects, each containing the `field` and other properties like `label` and `format`. In your case, you want to map the `ip` field from the JSON response to your widget.

Here's how you can adjust your `services.yaml` configuration:

```yaml
- Public IP:
    widget:
        type: customapi
        url: https://api.ipify.org?format=json
        refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
        method: GET # optional, e.g. POST
        mappings:
            - field: ip
              label: Public IP
              format: text # optional - defaults to text
```

Please note that I removed the trailing slash from the `url` field (`https://api.ipify.org/?format=json` to `https://api.ipify.org?format=json`) as per the troubleshooting guide which states that URLs should not end with a slash unless otherwise noted.

After making these changes, reload your Homepage instance and check if the widget displays the IP address correctly.

If the issue persists, please refer to the troubleshooting steps provided in the context, such as ensuring that the Homepage installation can connect to the API and checking the API output using `curl` from within the Docker container.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
