### DISCUSSION TITLE
Watchtower widget has white dot in top right

### DISCUSSION THREAD

**Discussion by Bag72** [gethomepage/homepage#3144] [Support] [answered]
### Description

I installed the Watchtower widget as suggest somehwere on this site and it woks fine.   One cosmetic point is there is a white dot at the top right of the widget.

![watchtower](https://github.com/gethomepage/homepage/assets/114260783/d82620f7-c093-4764-9d1b-be2e0b6d9bce)

Homepage yaml
    - Watchtower:
        description: Container Information
        container: watchtower
        widget:
          type: watchtower
          url: http://10.0.3.8:8080
          key: mykey

I didn't add any pings or other things that I recognise.  How can I remove the dot?

### homepage version

Latest

### Installation method

Docker

### Configuration

```yaml
QNAP System
Docker Compose

Homepage yaml
    - Watchtower:
        description: Container Information
        container: watchtower
        widget:
          type: watchtower
          url: http://10.0.3.8:8080
          key: mykey
```

### Container Logs

No error logs

### Browser Logs

No browser issues

### Troubleshooting

tried adjusting every line on its own but no joy.
