### DISCUSSION TITLE
Problems with proxmox widget

### DISCUSSION THREAD

**Discussion by jason-m** [gethomepage/homepage#3150] [Support] [answered]
### Description

I've been trying to get the dashboard widget to work on my proxmox cluster ( 8.1.4 ) but it always reports 0/0 for vms and lxc and NaN% for cpu and mem.

to ensure it wasnt permissions issues i even added an api to the root user temporarily 

I have been installing this on nixos Using nix packages, i've tried both stable (0.8.2) and unstable ( 0.8.9 ) 

### homepage version

0.8.9

### Installation method

Other (please describe above)

### Configuration

```yaml
- Proxmox Cluster:
        icon: proxmox.svg
        href: https://10.0.0.X:8006
        widget:
          type: proxmox
          url: https://10.0.0.X:8006
          username: api@pam!homepage
          password: <removed> 

    - Proxmox Node1:
        icon: proxmox.svg
        href: https://10.0.0.X:8006
        widget:
          type: proxmox
          url: https://10.0.0.X:8006
          username: api@pam!homepage
          password: <removed> 
          node: node1
```

### Troubleshooting

i've verified connectivity between the homepage my proxmox cluster nodes, and i am able to query the api endpoint using the api keys,
