### DISCUSSION TITLE
[Feature Request] Mailpit Widget

### DISCUSSION THREAD

**Discussion by zmweske** [gethomepage/homepage#3151] [Feature Requests]
### Description

[Mailpit](https://github.com/axllent/mailpit) is a great smtp relay/testing tool. 

I was able to set up a customapi without too much hassle, as shown below. The actual customapi used is also below. 

BasicAuth is used for authenticaiton. 

![image](https://github.com/gethomepage/homepage/assets/31971632/cf5d6d68-c2a8-4820-a5b0-1c63132c1bdd)
```yaml
        widget:
            type: customapi
            url: http://custom.api.host.or.ip:port/api/v1/info
            username: username # optional
            password: password # optional
            mappings:
              - field: Unread
                label: Unread
              - field: Messages
                label: Messages
```

If this gets the upvotes, maybe it'll become official. If not, at least it might help someone else.
