### DISCUSSION TITLE
Pi-hole Widget API Error

### DISCUSSION THREAD

**Discussion by searay345** [gethomepage/homepage#3152] [Support] [answered]
### Description

I'm trying to get the Pi-Hole widget working with no luck. Below is my setup in the services.yml file and the results inside Homepage. I copied and pasted my API directly from the API section in the Pihole GUI. 

### homepage version

0.8.9

### Installation method

Docker

### Configuration

```yaml
- Networking:
    - PiHole:
        icon: pi-hole.png
        href: http://192.168.54.5/admin
        description: Home Network Protection
        server: my-docker
        container: pihole
        widget:
         type: pihole
         url: http://192.168.54.5
         key: XXXXXXXXXXXXX
```

### Troubleshooting

API Error: HTTP Error
URL: http://192.168.54.5/admin/api.php?summaryRaw&auth=XXXXXXXXXXXXX
