### DISCUSSION TITLE
CustomAPI from simple status.json (no actual API)

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#3166] [Support] [answered]
### Description

Hello, I have a ratGDO HomeKit garage door opener, and it has a very basic status page at ` IP/status.json` with no authentication for pulling basic stats. I’d like a simple widget that shows whether the garage is open from this, and if the lights are on. The output of status.json is:

```
{
"upTime": 346810852,
"deviceName": "Garage Door",
"paired": true,
"firmwareVersion": "1.0.0",
"accessoryID": "[redacted]",
"localIP": "[redacted",
"subnetMask": "255.255.255.0",
"gatewayIP": "192.168.0.1",
"macAddress": "[redacted",
"wifiSSID": "[redacted",
"GDOSecurityType": "2",
"garageDoorState": "Closed",
"garageLockState": "Unsecured",
"garageLightOn": false,
"garageMotion": false,
"garageObstructed": false,
"passwordRequired": false,
"rebootSeconds": 0,
"freeHeap": 18376,
"minHeap": 3736
}
```
For example using the field garageDoorState.
Is it possible to use customAPI for this and if so, how? 

### homepage version

f06214a

### Installation method

Docker

### Troubleshooting

None at the moment

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Yes, you can use the `customapi` widget type in Homepage to create a widget that shows the status of your garage door and lights based on the output from your `status.json`. Here's an example of how you could set up your `services.yaml` configuration to achieve this:

```yaml
- Garage:
    - Garage Door Opener:
        icon: garage.png  # Replace with the path to your desired icon
        widget:
          type: customapi
          url: http://IP/status.json  # Replace IP with the actual IP address of your device
          mappings:
            - field: garageDoorState
              label: Garage Door
              format: text
            - field: garageLightOn
              label: Garage Light
              format: boolean
              trueValue: 'On'
              falseValue: 'Off'
```

In this configuration:

- Replace `http://IP/status.json` with the actual IP address of your garage door opener.
- The `mappings` section is used to map fields from your JSON output to the widget.
- The `field` specifies the JSON field name to display.
- The `label` is the text that will be displayed in the widget as the name of the field.
- The `format` specifies how the data should be displayed. For `garageDoorState`, it's just text, but for `garageLightOn`, it's a boolean that will display "On" when true and "Off" when false.

Make sure to replace `garage.png` with the actual path to your icon if you have one, and ensure that the IP address is correct. Once you have added this configuration to your `services.yaml`, restart your Homepage container to see the changes.

Remember to follow the general troubleshooting steps provided in the Homepage documentation if you encounter any issues, such as verifying that the Homepage installation can connect to the IP address of your device and checking the API output using `curl` from inside the container.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by mgrimace** [comment, marked as answer]
Thank you, the `boolean` value did not work, but a remap for that did, the final working version for me is:

```yaml
 - Garage:
    - Garage Door:
        icon: https://avatars.githubusercontent.com/u/144837877?s=200&v=4
        href: http://{{HOMEPAGE_VAR_RATGDO_IP}}
        #description: my garage-door opener
        siteMonitor: http://{{HOMEPAGE_VAR_RATGDO_IP}}
        widget:
          type: customapi
          url: http://{{HOMEPAGE_VAR_RATGDO_IP}}/status.json
          mappings:
            - field: garageDoorState
              label: Garage Door
              format: text
            - field: garageLightOn
              label: Garage Light
              format: text
              remap:
                - value: false
                  to: Off
                - value: true
                  to: On
            - field: upTime
              label: Uptime
              format: number
              scale: 1/3600000
              suffix: hrs
```
