### DISCUSSION TITLE
Pfsense widget not working properly

### DISCUSSION THREAD

**Discussion by vk6xebec** [gethomepage/homepage#3174] [Support]
### Description

I am unable to get pfSense and Unifi Controller Service to work properly

Pfsense:
I get an API error as follows
![image](https://github.com/gethomepage/homepage/assets/59078659/4df3b3a2-9e19-4459-9705-5a3bb0be3f10)

> > 
>     - Pfsense:
>         icon: pfsense.svg
>         href: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
>         description: Firewall
>         siteMonitor: "{{HOMEPAGE_VAR_PFSENSE_URL}}" 
>         widget:
>             type: pfsense
>             url: {{HOMEPAGE_VAR_PFSENSE_URL}}
>             username: "{{HOMEPAGE_VAR_PFSENSE_USERNAME}}"
>             password: "{{HOMEPAGE_VAR_PFSENSE_PWD}}"
>             wan: pppoe0
>             fields: ["load", "memory", "temp", "disk"]

I read from one of the other post that the WAN interface is pppoe0

These are my pfSense settings:
![image](https://github.com/gethomepage/homepage/assets/59078659/3584afee-1097-4c19-a445-d4017278a1c7)

![image](https://github.com/gethomepage/homepage/assets/59078659/2e4757f1-d356-46fb-8ff4-b90b8d4bf253)

### homepage version

0.8.9

### Installation method

Docker

### Configuration

```yaml
- Pfsense:
        icon: pfsense.svg
        href: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
        description: Firewall
        siteMonitor: "{{HOMEPAGE_VAR_PFSENSE_URL}}" 
        widget:
            type: pfsense
            url: {{HOMEPAGE_VAR_PFSENSE_URL}}
            username: "{{HOMEPAGE_VAR_PFSENSE_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PFSENSE_PWD}}"
            wan: pppoe0
            fields: ["load", "memory", "temp", "disk"]
```

### Troubleshooting

1. Changed WAN interface to pppoe0 From: [#2816](https://github.com/gethomepage/homepage/discussions/2816l) 
2. Installed curl in the container 
3. Ran the curl command ` curl -u username:password https://pfsense.lan/api/v1/status/system`

Got this error:

> curl: (60) SSL certificate problem: self-signed certificate in certificate chain
> More details here: https://curl.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.

4. Ran command again with -k parameter 
` curl -u -k username:password https://pfsense.lan/api/v1/status/system`

Got this error code
`{"status":"unauthorized","code":401,"return":3,"message":"Authentication failed","data":[]}`

Looks like it has a problem with my self signed certificate. 

5. I tried to change from https to http in the pfsense GUI settings, but the homepage widget timed out.

Any ideas?
