### DISCUSSION TITLE
Unifi Service Controller widget not working properly

### DISCUSSION THREAD

**Discussion by vk6xebec** [gethomepage/homepage#3175] [Support]
### Description

Unifi service controller widget is not working properly

As soon as I add the fields line, it goes blank
` fields: ["uptime", "wan", "wlan_devices", "lan_devices"]  `

![image](https://github.com/gethomepage/homepage/assets/59078659/5e4953fa-abeb-4e9c-9e29-f936bb444d26)

This is the code that works
```
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
        description: Wifi Network
        siteMonitor: "{{HOMEPAGE_VAR_UNIFI_BACKEND_URL}}"
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_BACKEND_URL}}"
            username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
            password: "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
            site: ATH
#            fields: ["uptime", "wan", "wlan_devices", "lan_devices"]  
```

Note that I have to uncomment out the fields line to get it to work

### homepage version

0.8.9

### Installation method

Docker

### Configuration

```yaml
- UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
        description: Wifi Network
        siteMonitor: "{{HOMEPAGE_VAR_UNIFI_BACKEND_URL}}"
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_BACKEND_URL}}"
            username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
            password: "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
            site: QTH
#            fields: ["uptime", "wan", "wlan_devices", "lan_devices"]
```

### Troubleshooting

Commented out the fields line and it works
