### DISCUSSION TITLE
How to set two lines of the service description?

### DISCUSSION THREAD

**Discussion by hengwu0** [gethomepage/homepage#3176] [Support]
### Description

How to set two lines of the service description? I want to write more infomation.

### homepage version

v0.8.9 (c89c488)

### Installation method

Docker

### Configuration

```yaml
- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome
        description2: Homepage is awesome
```

### Troubleshooting

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome
        description2: Homepage is awesome

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To set a multi-line description for a service in your `services.yaml` file, you can use the pipe character `|` to indicate a block scalar in YAML. This will allow you to write a description that spans multiple lines. Here's how you can modify your configuration:

```yaml
- My First Group:
    - My First Service:
        href: http://localhost/
        description: |
          Homepage is awesome
          Homepage provides a great user experience
```

This will set the `description` field to a string that includes a newline character between the two lines of text. When displayed, it should show the description on two separate lines.

Please note that the indentation for the lines following the pipe character is important and should be consistent to ensure the YAML is parsed correctly.

If you encounter any issues or the description does not display as expected, please check the browser console for any errors and ensure that your YAML syntax is correct. You can use online YAML validators to check your configuration file for syntax errors.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
