### DISCUSSION TITLE
TrueNAS widget - TypeError: Expected a finite number, got undefined: undefined

### DISCUSSION THREAD

**Discussion by ZoltrixGFC** [gethomepage/homepage#3180] [Support] [answered]
### Description

Hi all,

Have searched around and couldn't find a description of similar errors. Currently configuring Homepage and have already configured many widgets. Trying to configure the TrueNAS widget against TrueNAS Core 13.0-U6.1.

Currently attempting to use the API option, and am receiving the following error:

"TypeError: Expected a finite number, got undefined: undefined"

Not sure if relevant, but the same API key and settings work successfully in Heimdall (currently migrating away from)...

When configuring other widgets, I'd normally see API Error if I had settings wrong. First time I have this the error mentioned above.

### homepage version

v0.8.10 (0af975b, Mar 24, 2024)

### Installation method

Docker

### Configuration

```yaml
- Truenas 1:
        icon: truenas.svg
        href: https://truenas.xxx.xxx
        description: xxx
        widget:
          type: truenas
          url: https://truenas.xxx.xxx
          key: 3-HXcfaL2TWkcNkAl4QJpNLZ9MqsQGxB8hB6JE3jPLO3d0Ham97CgwJ1hEkr4ziWe6
          enablePools: true
```

### Troubleshooting

Tried to generate a new API key... tried using hostname vs IP
