### DISCUSSION TITLE
Unifi Widget some fields do not work and users not reported correctly

### DISCUSSION THREAD

**Discussion by jalouke** [gethomepage/homepage#3185] [Support]
### Description

the following field options do not display any information on my homepage dashboard: "lan", "lan_devices", "wlan", and "wlan_devices".

I also noticed that lan_users and wlan_users reports 1 extra device than is listed in the unifi dashboard.

### homepage version

v0.8.9 (c89c488, Mar 10, 2024)

### Installation method

Docker

### Configuration

```yaml
- UniFi:
        icon: unifi.svg
        href: https://unifi.ip/network
        description: network
        widget:
            type: unifi
            fields: ["lan", "lan_users", "wlan_users", "wlan"]
            url: https://unifi.ip
            username:  username
            password:  password
```

### Troubleshooting

some fields display information, and some don't. I have switched out different fields.
