### DISCUSSION TITLE
Own icons not showing (docker)

### DISCUSSION THREAD

**Discussion by devra1** [gethomepage/homepage#3190] [Support]
### Description

There was no icon available for StirlingPDF container so I downloaded a PNG and put it in a directory icons.
It is not showing the PNG icon.
I followed the instructions in the docs, and the AI says more or less the same as the docs.
I also rebuilt the container. There is nothing in the logs. 
If I list the contents of /app/public there is no icons subdirectory. File ownership and permissions are correct.

### homepage version

v0.8.10 (0af975b, Mar 24, 2024)

### Installation method

Docker

### Configuration

```yaml
compose.yml

    volumes:
      - ${DOCKERDIR}/homepage/config:/app/config
      - ${DOCKERDIR}/homepage/icons:/app/public/icons

config/services.yaml

    - Stirling PDF:
        icon: /icons/stirling.png
```

### Troubleshooting

The page just shows the missing image icon
