### DISCUSSION TITLE
Uptime Kuma widget says "Missing"

### DISCUSSION THREAD

**Discussion by klamann** [gethomepage/homepage#3198] [Support] [answered]
### Description

The Uptime Kuma widget does not show up, all I get is

![missing uptime](https://github.com/gethomepage/homepage/assets/1008877/d59b8f73-345e-49ff-b22e-da88f7f75b5c)

The Uptime Kuma API works fine, I have no error messages in the homepage logs or any other error message.

### homepage version

v0.8.10 (0af975b)

### Installation method

Docker

### Configuration

widgets.yml

```yaml
- uptime:
    icon: uptimekuma.svg
    href: https://uptime.example.org
    description: monitoring & alerting
    widget:
        type: uptimekuma
        url: https://uptime.example.org
        slug: mydashboard
```

### Container Logs

launched homepage with `LOG_LEVEL: debug`, only one log entry: "Listening on port 3000"

### Browser Logs

no messages on the browser console. No failing HTTP requests

### Troubleshooting

`curl https://uptime.example.org/api/status-page/mydashboard` works from the host system and from within the homepage docker container
