### DISCUSSION TITLE
[Feature Request] Add backgroud-image picker

### DISCUSSION THREAD

**Discussion by jammsen** [gethomepage/homepage#3203] [Feature Requests]
### Description

I placed in /app/public/wallpaper some images, but i can only choose 1 at a time via the settings.yaml. It would be awesome if the "Color-Picker" would get a new companion, i guess called "Image/Wallpaper-Picker" where i can switch Background images and see what layout fits with what and change the Background depending on your mood and stuff.

Maybe the "image" tag should be disabled when you enabled a "background-switcher" tag with source option, so the app doesnt get confused.

```yaml
background:
  image: false
  image-picker: true
    source: /app/public/wallpapers
```
