### DISCUSSION TITLE
Tailscale - curl works, widget doesn't

### DISCUSSION THREAD

**Discussion by ZoltrixGFC** [gethomepage/homepage#3222] [Support]
### Description

Attemtping to use the Tailscale widget. It just shows:

![Screenshot 2024-04-02 172927](https://github.com/gethomepage/homepage/assets/77313738/fcf1ece8-cf60-45b1-94e2-589715cfdccd)

I copied out the **deviceid** and **key** directly from what I had entered into the _services.yaml_ file, and ran a curl command from the docker host. It appears successful:

![Screenshot 2024-04-02 173217](https://github.com/gethomepage/homepage/assets/77313738/f4203a0b-5837-4c1f-bf5c-7b6bfa14be2e)

### homepage version

v0.8.10 (0af975b, Mar 24, 2024)

### Installation method

Docker

### Configuration

```yaml
- Tailscale (Management VM):
        icon: tailscale.svg
        href: https://login.tailscale.com/admin/machines
        description: Zero config VPN for building secure networks
        widget:
          type: tailscale
          deviceid: *******CNTRL
          key: tskey-api-**************CNTRL-*****************DkVjSkX8asRtvba
```

### Container Logs

[2024-04-02T06:35:46.651Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://api.tailscale.com/api/v2/device/*******CNTRL

[2024-04-02T06:38:01.647Z] error: <httpProxy> Error calling https://api.tailscale.com/api/v2/device/******7CNTRL...

[2024-04-02T06:38:01.649Z] error: <httpProxy> [

  500,

  AggregateError

      at internalConnectMultiple (node:net:1114:18)

      at internalConnectMultiple (node:net:1173:5)

      at Timeout.internalConnectMultipleTimeout (node:net:1632:3)

      at listOnTimeout (node:internal/timers:571:11)

      at process.processTimers (node:internal/timers:512:7) {

    code: 'ENETUNREACH',

    [errors]: [

      [Error], [Error],

      [Error], [Error],

      [Error], [Error],

      [Error], [Error],

      [Error], [Error],

      [Error], [Error]

    ]

  }

]

### Troubleshooting

curl test appears ok.
