### DISCUSSION TITLE
Wrong color status of siteMonitor/ping

### DISCUSSION THREAD

**Discussion by dukobpa3** [gethomepage/homepage#3223] [Support]
### Description

I have two services (marked on picture)
First one have response more than second.
Second one event not accessible (http status undefined NaN ms)
But both of them have green mark.
Not so important with text view but with `statusStyle: dot` green color hides real situation.

First one (with long ping) shows red even with 500ms if I'm using http, but green even with 1,500ms https

<img width="905" alt="Screenshot 2024-04-03 at 00 10 45" src="https://github.com/gethomepage/homepage/assets/1858880/4a795951-d32e-49ef-bbb4-f48b6352305e">

### homepage version

0.8.10

### Installation method

Docker

### Troubleshooting

..

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

It seems like you are experiencing an issue with the status indicators for your services not accurately reflecting their actual status when using the `statusStyle: dot` configuration. This could be a bug or a misconfiguration in the way the status is being determined and displayed.

To help you further, I would need to know the exact configuration you are using for these services in your `services.yaml` file. Specifically, how you have set up the `ping` or `siteMonitor` properties for these services, as well as the `statusStyle` setting.

In the meantime, you can try the following steps to troubleshoot the issue:

1. Ensure that your `services.yaml` configuration is correct and that the `ping` or `siteMonitor` properties are set up properly for each service.
2. Check the documentation for any updates or changes in the `statusStyle` configuration that might affect how statuses are displayed.
3. Review the release notes for version 0.8.10 to see if there are any known issues or changes related to service status indicators.
4. If you are comfortable with it, you can also check the browser's developer console for any errors or warnings that might provide more insight into the issue.

If after these steps the issue persists, please provide the relevant sections of your `services.yaml` configuration, and any additional information from your troubleshooting that could help identify the problem.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by dukobpa3** [reply]
I think configuration works well, the issue is just with wrong color codes for different statuses.

- HTTP status NaN definitely `not accessible` so it should be red.
- I'm not sure about long pings, because site works but it is slow. But in other hand in case I'll make siteMonitor with `http://....` definition instead of `https://...` same request times marks as red.

**Comment by shamoon** [comment]
Perhaps this has something to do with the status codes the server is responding with, it would be helpful to have an actual URL to test, can you provide that?

**Reply by dukobpa3** [reply]
https://notifiarr.com/

This one I know have huge pings.
Try both, http and https. In my setup it shows http with red if over 500ms, and https with green even over 1.5s

Another one is my internal, but it is easy to test, just use `siteMonitor` to random not existed host. It will show you NaN, but in green color both dot, and text.

**Reply by dukobpa3** [reply]
Maybe long ping should be yellow or orange. Because site works, just not so healthy

**Reply by shamoon** [reply]
We're not going to set the ping time to be a color based on time, the color is based on http response. https://notifiarr.com works fine but agree its a slow ping for me too.

As for the NaN thats what I'd like to figure out, most likely that URL (especially if its an internal one its almost certainly a DNS issue) is not responding to the http head request. You could try `ping` instead.

**Reply by dukobpa3** [reply]
> is not responding to the http head request

So should not it be red due to it is unavailable?

Pings not works for me because of whole network settings, maybe will change it later but don't want to do it right now. My homepage can't `ping` anything, only `siteMonitor` works.

**Reply by shamoon** [reply]
Can you look at what homepage is returning for that monitor and post it here? See screenshot example for where to find it in your browser
<img width="552" alt="Screenshot 2024-04-06 at 4 52 31 PM" src="https://github.com/gethomepage/homepage/assets/4887959/a41343fa-0055-49fb-953f-6416986dee4e">

**Reply by dukobpa3** [reply]
400

**Reply by shamoon** [reply]
Uh... can you be more specific? http 400?

**Reply by dukobpa3** [reply]
Yes

```
Request Method:
GET
Status Code:
400 Bad Request
```

**Reply by shamoon** [reply]
Please check the logs, and report them here

**Reply by spadazz** [reply]
I'm having the same problem here, both on v0.8.10 and .12
In my case I have 4 sitemonitors per service as you can see here :

![image](https://github.com/gethomepage/homepage/assets/33067859/67d31958-df11-48dd-8d71-a96057ae151e)

I tried both with ping and sitemonitor, but it always mark it green even if the host is powered off.
The homepage container (on casaos) has both ping and curl and they work as expected.
It doesn't work from the dashboard.
On homepage.log no error appears related to sitemonitors.
For some reason after a 6-7 seconds the response fail with 502 (correctly) but returns 200, as you can see on the developer console.
It could be a race condition that causes this.

P.S. : The first dot on the Nas button is correct, the Wake also (but its doing sitemonitor on another url), the Reboot and Poweroff are wrong, should be red as the first, instead its green...

Thanks for your help

**Reply by shamoon** [reply]
Commenting on someone else's thread like this isnt always very helpful, rarely are they really the same issue. The screenshot above is correct, the API endpoint returns status 200, the results report the test returned status 502

**Reply by spadazz** [reply]
So it's 'correct' and wrong at the same time.
Like Schroedinger's cat.
I'm sorry if I posted here,  for the time being if will avoid using multiple siteMonitor on the same service.

**Reply by shamoon** [reply]
Ha, not sure which part you think is wrong? The 502? It's very simple to investigate, homepage is sending an http head request from the container and the NAS is returning a 502.

**Reply by spadazz** [reply]
Yeah, what I was thinking...?
The server is powered off and the status is green instead of red.
But "it is correct"

**Reply by shamoon** [reply]
The screenshot above is for the one named "Nas" (`siteMonitor?group=Power&service=Nas`) and the picture shows a red dot.

**Reply by spadazz** [reply]
Reading my WHOLE first message would'v been clearer...
So I paste here the 2 lines that presumably you skipped :

P.S. : The first dot on the Nas button is correct, the Wake also (but its doing sitemonitor on another url), **the Reboot and Poweroff are wrong, should be red as the first, instead its green...**

**Reply by shamoon** [reply]
Yes, but you didnt post the results of the API call for those two, so not much to say about them.

**Reply by spadazz** [reply]
The first, third and fourth button are using :
- different href: to call an api
- THE SAME siteMonitor: to check if the  host is active or not.
After this, if it's still not clear, I give up.

**Reply by shamoon** [reply]
Oh, now I get what youre doing. Can you post the actual config? Wondering if thats the issue.

Theres not really a reason it should be different as long as the homepage API is returning the same result. So theres still a miscommunication in the other direction, which is that you havent posted the homepage API results for anything other than the Nas one. For example, if you've set things up correctly e.g. 'Wake' will call `siteMonitor?group=Power&service=Wake` (not Nas), thats what I'd be curious to see if its different.

For example:

```yaml
- Testing:
     - Example 1:
          href: http://localhost?dosomething
          siteMonitor: https://404doesntexist.org
     - Example 2:
          href: http://localhost?dosomethingelse
          siteMonitor: https://404doesntexist.org
     - Example 3:
          href: http://localhost?dosomethingelse2
          siteMonitor: https://404doesntexist.org
     - Example 4:
          href: http://localhost
          siteMonitor: https://google.com
```

yields:

<img width="755" alt="Screenshot 2024-04-29 at 11 18 01 AM" src="https://github.com/gethomepage/homepage/assets/4887959/99711010-3256-4891-b824-537c979402fb">

And you can see the distinct network calls:

<img width="1273" alt="Screenshot 2024-04-29 at 11 20 00 AM" src="https://github.com/gethomepage/homepage/assets/4887959/42585e66-ca6c-4ae3-8415-fb1ee7fb3821">

**Reply by spadazz** [reply]
Thank you, I'll get back to you as soon as possible..I think tomorrow.
I just add that the first href: is calling the NAS webui
The third and fourth href: are calling a go api that executes commands via ssh on the host (Nas).
Clicking the button the api works as expected.
It's just the status reported by siteMonitor that do not work.

**Reply by spadazz** [reply]
So, this is a sample config of the service Nas that we saw earlier :
```
    - Nas:
        icon: mdi-nas
        href: https://nas.<domain>
        description: Nas
        siteMonitor: https://nas.<domain>
    - Wake:
        icon: cloudflare-pages
        href: http://192.168.178.220:8089/wolweb/wake/NAS
        description: Nas
        siteMonitor: http://192.168.178.220:8089/wolweb
    - Reboot:
        icon: mdi-restart-#f4a520
        href: http://192.168.178.220:9000/api/host/..something..
        siteMonitor: http://192.168.178.10:8080
        description: Nas
    - Poweroff:
        icon: mdi-power-plug-off-#f4a520
        href: http://192.168.178.220:9000/api/host/..something..
        siteMonitor: http://192.168.178.10:8080
        description: Nas
  ```
  the siteMonitor in https//nas.<domain> and http://192.168.178.10 are equivalent, the first is just proxied to get ssl certificate.
  
  Disabling all these sitemonitors and the re-enabling the one at a time, works up to 3 sitemonitors, showing a red status for a powered off host.
  From 4+ all the statuses are always green.
   
  Since I have 3 equal sitemonitors per-service, and there are now 3 services in the group...it's too much.
  Notice that in the other 2 services there are equivalent "sub-groups" that are also called Wake, Reboot, Poweroff
  I tried to keep the titles clean for "easy readability", but maybe this is a naming problem for the the sitemonitor.
  
  I validated the entire yaml and it seems fine.
