### DISCUSSION TITLE
Ability to hide stats from an auto discovered entry?

### DISCUSSION THREAD

**Discussion by MarkDarwin** [gethomepage/homepage#3229] [General]
**The goal:** 
To add entries using auto discorvery and labels within the compose.yml file for each service

I'm trying to auto configure as much of the dashboard as possible so have been adding labels to my compose files like this:

```
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Europe/London
    labels:
      - homepage.group=Brix
      - homepage.name=jellyseerr
      - homepage.icon=jellyfin.png
      - homepage.href="https://jellyseerr.${{HOMEPAGE_VAR_TLD}}"
      - homepage.description=Media management
    networks:
      docknet:
        ipv4_address: 10.16.10.30
    volumes:
      - /localpath/jellyseerr:/app/config
    restart: unless-stopped
networks:
  docknet:
    external: true

```

**The problem:**
The problem is that it shows the CPU, MEM, TX, RX underneath the item

I've tried adding these additional labels, but this doesn't fix the problem and further adds an API error:

```
      - homepage.widget.fields=["CPU"]
      - homepage.widget.type=emby
```

Is there no way to hide these?
