### DISCUSSION TITLE
customapi widget - Iterate over a nested list of objects (+ a bug report?)

### DISCUSSION THREAD

**Discussion by DeepSpace2** [gethomepage/homepage#3233] [Support]
### Description

Hi, what an awesome little project :)

I'm trying to use the customapi widget but I can not seem to be able to iterate over a nested list of objects.

My API returns the following json:

```json
{
  "shows": [
    {
      "name": "Chicago P.D.",
      "number_of_episodes": 218,
      "number_of_seasons": 11
    },
    { }
  ]
}
```

I set the widget as

```yaml
 - "aa":
    - Shows:
        widget:
          type: customapi
          url: ***
          display: list
          mappings:
            - field:
                shows:
                  0: name
              label: Name
            - field:
                shows:
                  0: number_of_episodes
              label: Episodes
```

I want to be able to display information for all shows in the response. Of course I can hardcode all of them but it is not scalable.

Additionally, if I'm using `""` as the group name, the HTTP request fails with 404 because the request is sent to `http://homepage-host/api/services/proxy?type=customapi&group=&service=Shows&endpoint=null&query=%7B%22refreshInterval%22%3A600000%7D` which is a malformed URL due to an empty parameter (``&group=&``). I can use a literal whitespace but group names apparently need to be unique.

Perhaps there is a better way to have a group with a hidden name on the dashboard?

Thanks! :)

### homepage version

v0.8.10 (0af975b)

### Installation method

Docker

### Troubleshooting

I don't think this is relevant
