### DISCUSSION TITLE
Secret ENV file for Building from Source installation

### DISCUSSION THREAD

**Discussion by martirale** [gethomepage/homepage#3234] [Support]
### Description

Hello, I have a question for better management of environment variables in a Homepage installation in its mode `Building from source`. As you may already know, when doing it with Docker the users and passwords can be placed in a `.env` file and referred to in the `services.yaml` as `{{HOMEPAGE_VAR_LOREMIPSUM}}`.

The problem is that in an installation like the one I performed, I don't know how to configure the `.env` file for it. I tried trying to implement a `secrets.yaml` but I don't know how to manifest it in files like `services.yaml`. For this reason, at the moment I have all that data placed directly in the `services.yaml` file as follows:

```yaml
- Proxmox:
     icon: proxmox.svg
     href: 0.0.0.0:3000
     description: PVE
     widget:
         type: proxmox
         url: 0.0.0.0:3000
         username: user@pam!TokenID
         password: The token in question
         node: pve1
```

And as I already mentioned, the ideal would be to have it this way:
```yaml
- Proxmox:
     icon: proxmox.svg
     href: 0.0.0.0:3000
     description: PVE
     widget:
         type: proxmox
         url: 0.0.0.0:3000
         username: {{HOMEPAGE_VAR_PVE_USER}}
         password: {{HOMEPAGE_VAR_PVE_KEY}}
         node: pve1
```

### homepage version

dev (dev. Apr 4. 2024)

### Installation method

Source

### Troubleshooting

I tried setting up a .env file (and it didn't work). Then I tried a secrets.yaml file (and the same thing). Both files had this internal configuration:

```yaml
HOMEPAGE_VAR_PROXMOX_USER=user@pam!TokenID
HOMEPAGE_VAR_PROXMOX_API_KEY=Token
```
