### DISCUSSION TITLE
Sonarr API `http error` dispite curl working

### DISCUSSION THREAD

**Discussion by ACSoupir** [gethomepage/homepage#3235] [Support] [answered]
### Description

I have Homepage running on my synology NAS in a docker container. I have the network bridged and am able to ping another local computer with Sonarr/Radarr hosted on it. Have tested various ways of having Homepage see the other computer that I have the services on following the Troubleshooting guide and suggestions yet see an http error in the widget for the service.

Saw #3222 and from what I could gather from that discussion was that the service needed to be in a "group" which seems like it just needs to be in a parent thing for the service (exampled as Group A and Group B in the documentation). I have Sonarr service under the a group heading along with the some other things like my HDHomerun which seems to work. 
![pinging sonarr computer from inside container](https://github.com/gethomepage/homepage/assets/34483643/190c8a6a-6de1-47e5-81d4-9a789aa6a282)

After installing curl in the container and running the command it does seem to return information (though don't know if the format or whatever is right).
![docker exec curl](https://github.com/gethomepage/homepage/assets/34483643/2d363d85-43a8-41d2-b4e9-993e38d15717)

Even diving into the container and running the command it gives the output:
![inside container curl](https://github.com/gethomepage/homepage/assets/34483643/25ff1209-ac1c-443e-9b53-6ca6f213c82f)

Interestingly, even with being able to do that I get an http error in the widget for the Sonarr service.
![image](https://github.com/gethomepage/homepage/assets/34483643/00338112-f3b8-4784-adf7-32f75c8663fb)

In the documentation is says can explore `src/widgets/{widget}/widget.js` if up to it but 1) I have no idea what I should look for and 2) mine is .jsx so not sure if the documentation at least for this particular thing is up to date. Not sure what other troubleshooting steps to perform since it seems like Homepage can actually reach the API and, from what I can naively glean, the curl response seems to produce the correct format?

Also, the curl commands above are based on the error message in the Sonarr service itself and *not* the exact recommended curl command in the Troubleshooting guide. I have the Service set to use `['queued']` (see below) but it still reports an error with 'wanted' and 'missing' in the API link as if hard-coded somewhere? Perhaps my fields part isn't right for testing.
![services_yaml](https://github.com/gethomepage/homepage/assets/34483643/9ac13293-4c5e-40d3-985b-39b65acf590c)

Have checked other discussion like #2904 but the answer was 'I bet your homepage container cannot reach the sonarr instance' which I'm pretty sure mine can? I'm a noob with this stuff but maybe even with the curl responses, it can't reach my sonarr? I have tailscale also installed on the sonarr computer but don't think that has anything to do with it because am able to reach it with the local IP?.

### homepage version

v0.8.10

### Installation method

Docker

### Configuration

```yaml
#services.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media Lists: #Group
    - Sonarr: #Service
        icon: sonarr.png
        href: http://192.168.1.55:8989
        ping: 192.168.1.55
        description: Series management
        widget:
            type: sonarr
            fields: ["queued"]
            url: http://192.168.1.55:8989
            apikey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - HDHomerun: #Service
        icon: hdhomerun.png
        href: http://192.168.1.81
        ping: 192.168.1.81
        widget:
            type: hdhomerun
            url: http://192.168.1.81
```

### Troubleshooting

Above in the description
