### DISCUSSION TITLE
How to add a title to a widget in widgets.yaml

### DISCUSSION THREAD

**Discussion by accessiblepixel** [gethomepage/homepage#3236] [Support]
### Description

Hi! I'm not sure where I should ask this, but I'm trying to add multiple clocks to my widgets.yaml, but have it show the timezone below each one.

For example I have these two clocks - one with the date, and one without, one is my local timezone and one is Japan.

And I'd like to display *below* the 'time' a timezone (under, smaller). I've checked the documentation but I'm not sure if it's possible or if I'm just missing how to do it?
I know I can use time formatting with Intl.DateTimeFormat to display it on the same line, which if that's all I can do, that'll have to do, but I'd like to add (say UTC+9 below it).

I'm planning on having more clocks eventually.

Can someone point me in the right direction please :)

Thank you.

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- datetime:
    text_size: xl
    locale: sv-SE
    format:
      dateStyle: short
      timeStyle: medium
      hour12: false

- datetime:
    text_size: xl
    locale: sv-SE
    format:
      timeStyle: short
      hour12: false
      timeZone: "Asia/Tokyo"
```

### Troubleshooting

n/a

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the documentation available, it seems that the datetime widget configuration does not directly support displaying the timezone as a separate line below the time. However, you can achieve a similar effect by creating a custom layout with a greeting widget below each datetime widget to display the timezone information.

Here's an example of how you could set up your `widgets.yaml` file to display the time for two different time zones, with the timezone label displayed underneath each clock:

```yaml
- datetime:
    text_size: xl
    locale: sv-SE
    format:
      dateStyle: short
      timeStyle: medium
      hour12: false

- greeting:
    text_size: sm
    text: "Local Timezone (e.g., UTC+1)"

- datetime:
    text_size: xl
    locale: sv-SE
    format:
      timeStyle: short
      hour12: false
      timeZone: "Asia/Tokyo"

- greeting:
    text_size: sm
    text: "Japan Timezone (UTC+9)"
```

In this configuration, the `greeting` widget is used to display the timezone information as plain text below each clock. You can adjust the `text_size` and `text` properties to match your desired appearance and timezone information.

Please note that the timezone offset (e.g., UTC+9) is static text and will not automatically adjust for daylight saving changes or other timezone adjustments. You will need to manually update this text if the offset changes.

Remember to check the documentation for any updates or additional features that might have been introduced after the knowledge cutoff date that could provide a more integrated solution for displaying timezones.

If you need further assistance or if the feature you're looking for has been introduced in a newer version, please check the latest documentation or reach out to the community for support.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
