### DISCUSSION TITLE
2 space indentation causes service to not load

### DISCUSSION THREAD

**Discussion by nopoz** [gethomepage/homepage#3237] [Support]
### Description

If you use 2 space indentation then services only load with the name and everything else under it is ignored. Standard YAML indentation is typically 2 spaces, although there shouldn't by any synatx errors in YAML with other indentation levels as long as it's uniform. I'm not seeing any homepage errors logged anywhere when the service doesn't load due to 2 space indentation. Is this by design? Or a bug? Easily reproduced with steps below. 

Example where service will only load with the Title using 2 space indentation: 

<img width="1112" alt="2_space_indent" src="https://github.com/gethomepage/homepage/assets/460545/720d454f-442d-46c6-8c42-d227680ca90b">

```
- Media:
  - Deluge:
    icon: deluge.png
    href: http://192.168.1.3
    description: torrent manager
    siteMonitor: http://192.168.1.3
    server: docker
    container: deluge
    widget:
      type: deluge
      url: http://192.168.1.3
      password: {{HOMEPAGE_VAR_DELUGE_PASS}}
```

Example where it will load as expected with 4 space indentation:

```
- Media:
    - Deluge:
        icon: deluge.png
        href: http://192.168.1.3
        description: torrent manager
        siteMonitor: http://192.168.1.3
        server: docker
        container: deluge
        widget:
            type: deluge
            url: http://192.168.1.3
            password: {{HOMEPAGE_VAR_DELUGE_PASS}}
```

### homepage version

v0.8.10

### Installation method

Docker

### Troubleshooting

see description
