### DISCUSSION TITLE
deluge widget displays "NaN undefined/s" for upload and download speed

### DISCUSSION THREAD

**Discussion by nopoz** [gethomepage/homepage#3238] [Support]
### Description

deluge widget displays "NaN undefined/s" for upload and download speed - using Deluge 2.1.1

<img width="379" alt="deluge_widget" src="https://github.com/gethomepage/homepage/assets/460545/05fdc7ac-c6d9-4c84-a3f9-8d5d15f9f380">

### homepage version

v0.8.10

### Installation method

Docker

### Configuration

```yaml
- Media:
    - Deluge:
        icon: deluge.png
        href: http://192.168.1.3:8112
        description: torrent manager
        siteMonitor: http://192.168.1.3:8112
        server: docker
        container: deluge
        widget:
            type: deluge
            url: http://192.168.1.3:8112
            password: {{HOMEPAGE_VAR_DELUGE_PASS}}
```

### Container Logs

none found that are relevant

### Browser Logs

browser debug network request:

```
http://192.168.1.2:8091/api/services/proxy?type=deluge&group=Media&service=Deluge&endpoint=undefined
```

relevant json response data:

```
{
  "stats": {
    "max_download": -1,
    "max_upload": 12345,
    "max_num_connections": 9000,
    "num_connections": 33,
    "upload_rate": 24576,
    "download_rate": 0,
    "download_protocol_rate": 33140,
    "upload_protocol_rate": 37979,
    "dht_nodes": 0,
    "has_incoming_connections": 1,
    "free_space": <redacted>,
    "external_ip": "<redacted>"
  }
}
```

The transfer size for this request is 256.83 kB as I have a large amount of torrents, not sure if that has anything to do with it. The stats are at the bottom of the json response which is where I assume homepage needs to parse the upload and download speed. 

### Troubleshooting

see browser logs
