### DISCUSSION TITLE
Search bar search engine selection behind other elements

### DISCUSSION THREAD

**Discussion by gitmotion** [gethomepage/homepage#3242] [Support]
### Description

![image](https://github.com/gethomepage/homepage/assets/43588713/02c198d8-e9b0-44ff-b358-3260361be88c)
When selecting a different search engine, other elements on the page seem to be in front of the selections making accidental clicks anyone know if there's a fix for this?

### homepage version

v0.8.10 (0af975b, Mar 24, 2024)

### Installation method

Docker

### Configuration

```yaml
- search:
    provider: [brave, google, duckduckgo, bing]
    target: _blank
```

### Troubleshooting

after adding the search engine widget with multiple search engine choices the selections are behind the elements below
