### DISCUSSION TITLE
Battling passing environment values

### DISCUSSION THREAD

**Discussion by ZuluPilgrim** [gethomepage/homepage#3244] [Support] [answered]
### Description

I am not sure if my docker compose file is set up correctly with respect to the environment files as none of my widgets are pulling information through.

My docker compose file looks as follows:

Docker:

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 8921:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    # user: 1000:1000 optional, not compatibile with direct socket see https://gethomepage.dev/en/configs/docker/#using-socket-directly
    restart: unless-stopped
    env_file: .env
```

The .env file has the below in it, and is in the same directory as docker-compose.yml
`HOMEPAGE_VAR_JELLYFINAPI=fellyfinapikey`

The yaml for home pages is
```
- Services Group:
    - JellyFin Service:
        icon: jellyfin.svg
        href: https://jellyfin.mysite.com/
        Description: Home Movies
        widget:
          type: jellyfin
          url: http://jellyfin.mysite.com/
          key: "{{HOMEPAGE_VAR_JELLYFINAPI}}"
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
```

I have restarted the container.

This is what I see
![image](https://github.com/gethomepage/homepage/assets/111164245/2c22e403-192a-40ab-9e80-89927e89ab9e)

followed by
![image](https://github.com/gethomepage/homepage/assets/111164245/aa3aef81-8913-4a1d-b088-8b9562ba1a34)

It does not look like the env variable is being pulled through. How do I troubleshoot this?

### homepage version

v0.8.10 (0af975b, Mar 24, 2024)

### Installation method

Docker

### Troubleshooting

I am  not sure how to troubleshoot this. I have tried other widgets and had the same result.

How do I test to see that the env variable can/is being red?
