### DISCUSSION TITLE
Information Widget for Unifi Controller

### DISCUSSION THREAD

**Discussion by xyeoda** [gethomepage/homepage#3254] [Support] [answered]
### Description

Have read the documentation and restarted the container to clear the cache

https://gethomepage.dev/latest/widgets/info/unifi_controller/

This is a self-hosted unifi site on Contabo ; i was able to logon with the user that i created just fine.

It shows API Error however there is nothing in the logs
<img width="1054" alt="Screenshot 2024-04-07 at 9 52 18 PM" src="https://github.com/gethomepage/homepage/assets/31374940/ddae9adb-43ca-4c1c-be16-ff64a713c599">

### homepage version

v0.8.10 (0af975b, Mar 24, 2024)

### Installation method

Docker

### Configuration

```yaml
- unifi_console:
    url: {{HOMEPAGE_VAR_UNIFI_URL}}
    username: {{HOMEPAGE_VAR_UNIFI_USER}}
    password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    #site: YeoDa UniFi Network VPS
```

### Container Logs

Listening on port 3000

### Browser Logs

logs are empty

### Troubleshooting

i tried loggin onto the self hosted controller with the read only user and it was able to log on.
