### DISCUSSION TITLE
CustomAPI Widget with Bearer Token

### DISCUSSION THREAD

**Discussion by angryviking** [gethomepage/homepage#3255] [Support] [answered]
### Description

I have configured a service for GrampsWeb using the CustomAPI widget. According to the GrampsWeb API documentation [here](https://gramps-project.github.io/gramps-web-api) and [here](https://www.grampsweb.org/dev-backend/queries/), I need to get a Bearer token before I do an API query.
If I manually get a Bearer token and place that token in the CustomAPI widget, the widget works fine. Here is the excerpt from my services.yml:
```
  - Gramps:
      href: https://grampweb.url
      icon: https://grampsweb.url/images/favicon.ico
      server: my-docker
      container: gramps
      widget:
        type: customapi
        url: https://grampsweb.url/api/metadata/
        headers:
          Authorization: 'Bearer super_long_token_here'
        mappings:
          - field:
              object_counts: people
            label: People
            type: number
          - field:
              object_counts: families
            label: Families
            type: number
          - field:
              object_counts: places
            label: Places
            type: number
```
This configuration works fine until the token expires. Is there a way to automatically pull another bearer token from within the CustomAPI widget so it doesn't need to be hard coded?

I can do something like this using curl on the command line with curl and jq, like:
`curl -sk -X GET https://grampsweb.url/api/metadata/ -H "Authorization: Bearer $(curl -sk -X POST https://grampsweb.url/api/token/ -H "Content-Type: application/json" -d '{"username":"user", "password":"xxxxxxxxxx"}' | jq -r '.access_token')"`
Curl and jq are not available within the homepage docker container.

### homepage version

v0.8.10 (0af975b)

### Installation method

Docker

### Troubleshooting

N/A
