### DISCUSSION TITLE
homepage behind (!) traefik reverse proxy

### DISCUSSION THREAD

**Discussion by holzauto** [gethomepage/homepage#3256] [Support] [answered]
### Description

Hi there,

i've been (unsuccessfully) trying to get homepage behind my traefik reverse proxy.
My (docker) traefik installation is working, i'm currently using for pihole, (docker) portainer and proxmox, works like a charm.
Granted, i've relied on tutorials and youtube videos to get all that working (i'm new to all of this).

Now  i want to integrate my homepage behind traefik, because i want want ssl and a nice url without ports.
But traefik labels are not working.. 

Having spent the better part of the last two days trying to figure this out i'm ready to abandon homepage and look for other dashboards with some kind of example oder documentation on how to achieve that.

But before i do that, my last attempt to get this working is, asking for help here... does anyone have a similar setup with NO kubernetes and is willing to share the basic traefik labels to get this working..

Best, holzauto

### homepage version

v0.8.10

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.10
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    depends_on:
      - traefik
    environment:
      - PUID: 1000
      - PGID: 1000
      - TZ: Europe/Berlin
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
```

### Troubleshooting

unfortunately, i don't see anything, not in the logs or elsewhere.. it just doesn't work.

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Hello holzauto,

To integrate Homepage with Traefik and enable SSL with a nice URL without ports, you need to add Traefik labels to your Homepage service in your Docker Compose file. These labels will tell Traefik how to route traffic to your Homepage container and how to obtain an SSL certificate for it.

Here's a basic example of how you can set up your `docker-compose.yml` file with the necessary Traefik labels:

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.10
    container_name: homepage
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    environment:
      - PUID: 1000
      - PGID: 1000
      - TZ: Europe/Berlin
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=myresolver"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
```

Make sure to replace `your-domain.com` with your actual domain and `myresolver` with the name of the certificate resolver you have configured in Traefik for SSL certificates.

Please note that the `ports` section is removed because Traefik will handle the routing to your container, and you don't need to expose the port directly.

After updating your `docker-compose.yml` file, you can apply the changes by running:

```bash
docker-compose up -d
```

This should configure Traefik to route traffic to your Homepage container and enable SSL for it. If you have any issues, please check the Traefik logs for any errors related to the routing or SSL certificate generation.

If you need further assistance, please provide any error messages or logs that you see, and I'll be happy to help you troubleshoot the issue.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by holzauto** [comment]
Thanks to the bot answer i had re-think and this is what i came up with, and it works, my homepage is behind the revers proxy, including redirecting traffic to ssl:

```
---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.10
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
    environment:
      PUID: 1002
      PGID: 1002
      TZ: Europe/Berlin
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`your-domain.com`)"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=myresolver"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

Best, holzauto
