### DISCUSSION TITLE
Adding anything to services creates a text only un-clickable item

### DISCUSSION THREAD

**Discussion by pbean** [gethomepage/homepage#3257] [Support] [answered]
### Description

Hello folks

New user of homepage trying to figure out what the heck is going wrong with my implementation. Any time I try to add anything into services.yaml the result is a unclickable box that only shows the name field. It also doesn't support using the server and container fields either for docker. I can use labels just fine on docker compose files but nothing in services.yaml. can someone please let me know what I might be missing? I have set log_level to debug and the logs say nothing I have also tried multiple docker hosts and there containers and have the same results even though labels work on those as well

My Services.yaml
```
---
- Test:
  - Adguard 02:
    icon: adguard-home
    href: "http://192.192.2.2"
    description: Adguard Blackhole DNS 02(potato)
    widget:
      type: adguard
      url: http://192.192.2.2
      username: admin
      password: PASSSSSSSSS
```
![image](https://github.com/gethomepage/homepage/assets/333283/d9d7eaff-7e9c-4aa3-ac25-c0f735bc55fa)

in the "test" group is the one cited in services.yaml my docker label one is under IaaS including a working widget. The Adguard 02 result happens if I try to do the docker service inclusion in services.yaml instead of docker labels as well just fyi

new services.yaml for testing with another container without a widget
```
---
- Test:
  - Adminer:
    icon: adminer
    href: "http://192.192.2.2"
    description: Adminer test for example
    server: dockerxx
    container: adminer
```
![image](https://github.com/gethomepage/homepage/assets/333283/2f87c919-eca2-4b46-a5bf-d8c97153def3)

Same thing happens with it as well

### homepage version

v0.8.10 (0af975b)

### Installation method

Docker

### Configuration

```yaml
---
- Test:
  - Adminer:
    icon: adminer
    href: "http://192.192.2.2"
    description: Adminer test for example
    server: dockerxx
    container: adminer
```

### Container Logs

Nothing shows even with debug other than:
2024-04-08T04:49:07.218656737Z Listening on port 3000

### Browser Logs

no errors

### Troubleshooting

see description, these tests all pass it works using docker lables just fine but not services.yaml

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the `services.yaml` configuration examples you've shared, it seems there might be an issue with the structure of your YAML file. YAML is very sensitive to indentation and requires consistent use of spaces for nesting.

In your `services.yaml` file, you should ensure that the indentation is consistent and correct. Each nested level should be indented by two spaces. Here's a corrected version of your first `services.yaml` example:

```yaml
---
- Test:
    Adguard 02:
      icon: adguard-home
      href: "http://192.192.2.2"
      description: Adguard Blackhole DNS 02(potato)
      widget:
        type: adguard
        url: http://192.192.2.2
        username: admin
        password: PASSSSSSSSS
```

And for the second `services.yaml` example:

```yaml
---
- Test:
    Adminer:
      icon: adminer
      href: "http://192.192.2.2"
      description: Adminer test for example
      server: dockerxx
      container: adminer
```

Please note that each service under the `Test` group should be indented two spaces under the group name, and the properties of each service should be indented two spaces under the service name.

After making these changes, try reloading your homepage instance and check if the services are displayed correctly.

If you continue to experience issues, please refer to the documentation for the correct structure and examples of `services.yaml` configurations. You can also check the logs for any errors that might indicate what's going wrong.

If you need further assistance, please provide additional details or error messages that you encounter after making the suggested changes.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by pbean** [reply, marked as answer]
So the AI is wrong and right at the same time. These yml files are not correct either but they were better than mine. They are missing the - in front of the service name(they use 4 spaces instead and that does NOT work i triple checked)  and only 2 spaces of indent. I'm not quite sure why, and it doesn't make sense to me as far as my knowledge of yaml goes but,  the services.yaml file works if you give 4 spaces below the name of the services for its information (see below) for an actual working file for my implementation

```
---
- Test:
  - Adminer:
      icon: adminer
      href: "http://192.192.2.2"
      description: Adminer test for example
      server: docker
      container: adminer
  - Adguard 02:
      icon: adguard-home
      href: "http://192.168.1.10"
      description: Adguard Blackhole DNS 02(potato)
      widget:
        type: adguard
        url: http://192.168.1.10
        username: admin
        password: Pass
```

Why is it doing this? Is this as expected behavior and im just unaware of something as glaring as that with yaml? (thought it was two spaces why is the data for services arbitrarily from what I can tell 4 spaces

I would definitely recommend this be noted in the docs (im pretty sure it's not unless my mind is playing tricks on me) I wasted hours on trying to track, redploy, shimmy, shake, and search here as well for the answer.
