### DISCUSSION TITLE
glances installed with docker unable to view host OS root drive and display it to homepage widget

### DISCUSSION THREAD

**Discussion by dnielso5** [gethomepage/homepage#3260] [Support] [answered]
### Description

I'm not sure if anyone else is using the glances widget app, I can get the cpu and memory to display but I can't get the disk to show up 

I am running glances docker in one machine: 

version: '3'
services:
  glances:
    image: nicolargo/glances:latest-alpine
    restart: always
    pid: "host"
    volumes:
      - ./config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - 61208:61208

![Screenshot_20240407-220708.png](https://github.com/nicolargo/glances/assets/107376351/b9dd5b14-5e9b-4bbb-90e7-ab95e0059b0a)

And my config for homepage:

 - glances:
    url: http://192.168.1.34:61208
    cpu: true
    mem: true
    disk: /
    label: Laptop
    expanded: true

### homepage version

8.10

### Installation method

Docker

### Configuration

```yaml
- glances:
    url: http://192.168.1.34:61208
    cpu: true
    mem: true
    disk: /
    label: Laptop
    expanded: true
```

### Troubleshooting

tried adding a config file and added

[fs]
show= /
