### DISCUSSION TITLE
intermitent API Error, 502, 500

### DISCUSSION THREAD

**Discussion by ankycooper** [gethomepage/homepage#3265] [Support]
### Description

Intermittent API and 502 errs, auto-fixes on self-refresh at times.

### homepage version

v0.8.11 (4239e8f, Apr 9, 2024)

### Installation method

Docker

### Configuration

```yaml
version: "3.9"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/flash/hosted/docker/homepage/config:/app/config
      - /mnt/flash/hosted/docker/homepage/images:/app/images
      - /mnt/flash/hosted/docker/homepage/icons:/app/icons
    env_file:
      - stack.env
    restart: always
```

### Container Logs

[2024-04-09T01:57:03.935Z] error: <credentialedProxyHandler> HTTP Error 502 calling https://port.mydomain.com/api/endpoints/3/docker/containers/json?all=1
[2024-04-09T01:57:04.794Z] error: <httpProxy> Error calling https://auth.mydomain.com/api/v3/events/events/per_month/...
[2024-04-09T01:57:04.808Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN auth.mydomain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'auth.mydomain.com'
  }
]
[2024-04-09T01:57:04.812Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://auth.mydomain.com/api/v3/events/events/per_month/?action=login
[2024-04-09T01:57:10.115Z] error: <httpProxy> Error calling https://adg.mydomain.com/...
[2024-04-09T01:57:10.119Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN adg.mydomain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adg.mydomain.com'
  }
]
[2024-04-09T01:57:22.560Z] error: <credentialedProxyHandler> HTTP Error 502 calling https://port.mydomain.com/api/endpoints/3/docker/containers/json?all=1
[2024-04-09T01:57:23.528Z] error: <httpProxy> Error calling https://adg.mydomain.com/...
[2024-04-09T01:57:23.531Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN adg.mydomain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adg.mydomain.com'
  }
]
[2024-04-09T01:57:55.897Z] error: <credentialedProxyHandler> HTTP Error 502 calling https://port.mydomain.com/api/endpoints/3/docker/containers/json?all=1
[2024-04-09T01:57:57.145Z] error: <httpProxy> Error calling https://adg.mydomain.com/...
[2024-04-09T01:57:57.149Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN adg.mydomain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adg.mydomain.com'
  }
]
[2024-04-09T01:58:21.959Z] error: <credentialedProxyHandler> HTTP Error 502 calling https://port.mydomain.com/api/endpoints/3/docker/containers/json?all=1
[2024-04-09T01:58:22.961Z] error: <httpProxy> Error calling https://adg.mydomain.com/...
[2024-04-09T01:58:22.966Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN adg.mydomain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'adg.mydomain.com'
  }
]

### Troubleshooting

Uptime kuma container on the same host is monitoring the services without any issue
DNS resolution works
can access the services from my laptop
