### DISCUSSION TITLE
docker socket-proxy / No such file or directory

### DISCUSSION THREAD

**Discussion by ThierryIT** [gethomepage/homepage#3266] [Support]
### Description

Hello,
I have installed homepage, the basic config is working.
But I am fighting to make it working with a docker-socket-proxy. I am using the "wollomatic/socket-proxy".
``

### homepage version

v0.8.10

### Installation method

Docker

### Configuration

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.10
    container_name: homepage
    ports:
      - 3000:3000
    networks:
      - mynet
      - socket_h
    command:
      - '--host=tcp://h-docker-socket-proxy:2375'
    volumes:
      - /mnt/user/appdata/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /mnt/user/appdata/docker/homepage/icons:/app/public/icons
      - /mnt/user/appdata/docker/homepage/images:/app/public/images
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.domain.tld`)"
      - "traefik.http.routers.homepage.entrypoints=https-external"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      PUID: 1002
      PGID: 1002
      HOMEPAGE_VAR_PROXMOX_USERNAME: &HOMEPAGE_VAR_PROXMOX_USERNAME
      HOMEPAGE_VAR_PROXMOX_PASSWORD: &HOMEPAGE_VAR_PROXMOX_PASSWORD
    restart: unless-stopped
    
  dockerproxy:
    image: wollomatic/socket-proxy:1
    container_name: h-docker-socket-proxy
    command:
      - '-loglevel=debug'
      - '-allowfrom=homepage' # allow only access from the "watchtower" service
      - '-listenip=0.0.0.0'
      - '-shutdowngracetime=10'
      # this whitelists the API endpoints that watchtower needs:
      #- '-allowGET=/v1\..{2}/(containers/.*|images/.*)'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
      - '-allowPOST=/v1\..{2}/(containers/.*|images/.*|networks/.*)'
      - '-allowDELETE=/v1\..{2}/(containers/.*|images/.*)'
      # check socket connection every hour and stop the proxy if it fails (will then be restarted by docker):
      - '-watchdoginterval=3600'
      - '-stoponwatchdog'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 65534:995 # change gid from 998 to the gid of the docker group on your host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=false # if watchtower would try to update the proxy, it would just stop
    networks:
      - socket_h
networks:
  socket_h:
    internal: true
    attachable: false
  mynet:
    driver: bridge
    attachable: false
```
```


### Container Logs

su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
su-exec: --host=tcp://h-docker-socket-proxy:2375: No such file or directory
### Browser Logs

_No response_

### Troubleshooting

If I comment `#command:
      #- '--host=tcp://h-docker-socket-proxy:2375'` it work again.

How to pass this command ? Is it correct: `HOMEPAGE_HOST: tcp://h-docker-socket-proxy:2375`

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

It appears that you are trying to configure Uptime Kuma to use a Docker socket proxy, but you are encountering an error with the `setpriv` command not recognizing the `--host` option. The error message indicates that the `--host` option is being passed to `setpriv`, which is not a valid option for that command.

The `command` section in your Docker Compose configuration is likely intended for Uptime Kuma, but it seems to be incorrectly formatted or placed. The `--host` option is not a valid argument for `setpriv`, which is a Linux utility for running commands with different privileges.

To resolve this issue, you should ensure that the `command` option in your Docker Compose file is correctly specified for Uptime Kuma and that it does not include options that are not recognized by the application you are trying to configure.

If you are trying to specify the Docker host for Uptime Kuma to connect to the Docker socket proxy, you should refer to the Uptime Kuma documentation to find the correct way to pass this configuration. It might involve setting an environment variable or a command-line argument that is specific to Uptime Kuma.

Please double-check the Uptime Kuma documentation or the documentation of the Docker image you are using for the correct syntax and options to use. If you are using a custom entrypoint script or command for Uptime Kuma, ensure that it is correctly parsing and using the arguments you provide.

If you need further assistance, please provide more context or clarify the exact configuration you are trying to achieve, and I will do my best to assist you.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by Smeeth** [comment]
So I don't know where the robot gets the idea that your problem is related to Uptime-Kuma, but let's just let it bubble away.

I've already tried that and it didn't work. Do you really need to use a socket proxy?

**Comment by angryviking** [comment]
I don't use a docker-socket container, but the homepage container is trying to execute a command called `--host=tcp://h-docker-socket-proxy:2375` which it can't find. You should probably remove the command lines altogether. 
The documentation at https://gethomepage.dev/latest/configs/docker/#using-docker-socket-proxy says to put something like this
```
my-docker:
  host: dockerproxy
  port: 2375
```
in the config/docker.yaml file. Have you tried that?

**Reply by Smeeth** [reply]
Well wollomatic IS a docker socket proxy... pls read their readme AND don't use it with homepage. Currently it doesn't work. Just use Homepage Like it is

**Reply by wollomatic** [reply]
[wollomatic/socket-proxy](https://github.com/wollomatic/socket-proxy) dev here. For sure, it works with Homepage. @angryviking wrote the right answer to solve the connectivity problem.

However, the socket proxy is not configured appropriately in the original question. The sample seems to be copied and pasted from the Watchtower example. However, Watchtower needs way more rights than Homepage.

```
# [...]
  dockerproxy:
    image: wollomatic/socket-proxy:1
    container_name: h-docker-socket-proxy # my personal preference would be to delete this line and let compose name the service
    command:
      - '-loglevel=debug' # better change to info in prod
      - '-allowfrom=homepage'  # allow only the service called homepage
      - '-listenip=0.0.0.0'
      - '-shutdowngracetime=10'
      - '-allowGET=/v1\..{1,2}/(containers.*|services.*|tasks.*)'
      # check socket connection every 600s and stop the proxy if it fails (will then be restarted by docker):
      - '-watchdoginterval=600'
      - '-stoponwatchdog'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 65534:995 # change gid from 995 to whatever the gid of the docker group is on your host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_h
# [...]
```

The advantages over tecnativa/docker-socket-proxy are: No shell in container, no interpreter in container, proxy written in memory safe programming language.
