### DISCUSSION TITLE
Crowdsec Widget High Memory & CPU Usage

### DISCUSSION THREAD

**Discussion by KonVei82** [gethomepage/homepage#3269] [Support] [answered]
### Description

High memory and cpu usage with a big alert list. CPU jumps to 80% while memory increases from 100mb to 320mb on every refresh. Running "docker exec crowdsec cscli alerts -l 0 list" comes back with 2 alerts.

I am not sure how the widget is pulling alerts and if there is a way to limit how many do we pull.

### homepage version

v0.8.11

### Installation method

Docker

### Configuration

```yaml
- Crowdsec:
        icon: si-springsecurity-#5CDD8B
        widget:
          type: crowdsec
          url: http://crowdsec:8080
          username: localhost
          password: password
```

### Container Logs

[2024-04-09T09:03:36.513Z] warn: API response for /api/services/proxy?type=crowdsec&group=Status&service=Crowdsec&endpoint=alerts exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit

### Browser Logs

API returns 100 alerts on each refresh.

### Troubleshooting

-
