### DISCUSSION TITLE
Portainer

### DISCUSSION THREAD

**Discussion by paolos7709** [gethomepage/homepage#3271] [Support]
### Description

Portainer widget is not getting details from Portainer. 
My Portainer URL doesn't contain "#!/endpoints/1", only "https://192.168.1.200/#!/1/kubernetes/dashboard"

Then I'm getting an API Error: The string did not match the expected pattern.

### homepage version

v0.8.11

### Installation method

Other (please describe above)

### Configuration

```yaml
- Portainer:
        icon: portainer.png
        href: https://192.168.1.200
        description: Container management
        siteMonitor: https://192.168.1.200
        statusStyle: "dot"
        widget:
            type: portainer
            url: https://192.168.1.200
            env: 1
            key: ptr_key
            fields: ["running", "stopped", "total"]
```

### Troubleshooting

curl -L -k -H 'X-Api-Key:ptr_key' 'https://192.168.1.200/api/endpoints/2/docker/containers/json'
{"message":"Unable to find an environment with the specified identifier inside the database","details":"object not found inside the database (bucket=endpoints, key=2)"}
