### DISCUSSION TITLE
Cardblur options

### DISCUSSION THREAD

**Discussion by MarkDarwin** [gethomepage/homepage#3275] [Support]
### Description

Is it possible to supply multiple options to the cardblur setting?

I'd like to change the colour of the card to make it darker so it stands out more but adding anything other than `cardblur: sm|md|xl` doesn't seem to work.

I've tried adding various options after the comma but it breaks it.
`cardBlur: xl, backdrop-brightness-105`

Is the only option to make a custom css as shown in  #2098 ?

### homepage version

v0.8.11 (4239e8f, Apr 8, 2024)

### Installation method

Other (please describe above)

### Configuration

```yaml
title: Homelab Homepage
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

showStats: false

theme: dark
color: gray
headerStyle: underlined
#background: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wY>
background: https://img.freepik.com/free-photo/vibrant-colors-flow-abstract-wave-pattern-generated-by-ai_188544-9781.jp>
#backgroundOpacity: 0.5


cardBlur: xl #, md, etc... see https://tailwindcss.com/docs/backdrop-blur
useEqualHeights: true
```

### Troubleshooting

Adding anything after the comma breaks it.
cardBlur: xl, backdrop-brightness-105

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

The `cardBlur` setting in the Homepage configuration is designed to accept only one value that corresponds to the size of the blur filter you want to apply to the cards. The values you can use are based on Tailwind CSS classes such as `sm`, `md`, `lg`, `xl`, etc. It does not support multiple values or additional CSS properties directly within the `cardBlur` setting.

If you want to apply additional styles such as changing the brightness, you would indeed need to use custom CSS. You can create a `custom.css` file in your configuration directory and add your custom styles there. For example, to change the brightness, you could add a rule targeting the card elements and apply the `backdrop-brightness` filter.

Here's an example of what your custom CSS might look like:

```css
.card-class {
  backdrop-filter: blur(var(--card-blur)) brightness(105%);
}
```

You would replace `.card-class` with the actual class used by the cards on your Homepage. The `var(--card-blur)` is a placeholder for the blur value you set in your `settings.yaml` file, and `brightness(105%)` is the brightness filter you want to apply.

Please note that you should do this at your own risk, as custom CSS can affect the layout and functionality of your Homepage in unexpected ways.

For more information on how to add custom CSS, you can refer to the documentation on custom CSS and JS:

- Custom CSS & JS: https://github.com/gethomepage/homepage/blob/main/docs/configs/custom-css-js.md

Remember to check the actual class names used by the Homepage application and adjust your custom CSS accordingly.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by MarkDarwin** [comment]
Thanks @glime-ia

I got almost where I wanted to be with
```css
.flex-1 {
  backdrop-filter: brightness(40%) blur(10px);
}
```

This still changes the brightness of the outer elements which is a shame but it will do for now if no one else has a better approach
