### DISCUSSION TITLE
[Feature Request] href tag for custom api widget

### DISCUSSION THREAD

**Discussion by sieteunoseis** [gethomepage/homepage#3277] [Feature Requests] [answered]
### Description

Could we add an href tag for the custom api widget?

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To clarify your request, are you asking if it's possible to add an HTML `href` tag within the configuration of a Custom API widget in Homepage, so that a particular field can be clickable and link to a specified URL?

If that's the case, based on the provided documentation, there is no direct mention of using an `href` tag within the Custom API widget configuration. The documentation focuses on defining fields and their formats, such as text, number, percent, date, etc., and does not explicitly state the ability to create hyperlinks.

However, if you want to create a clickable link within a widget, you might consider using custom JavaScript to manipulate the DOM after the widget has been rendered. This would involve using the Custom CSS & JS feature mentioned in the documentation, where you can add your own JavaScript to interact with elements on the page.

Please confirm if this is what you're looking to achieve, or provide additional details if your request is different. If you need further assistance with the Custom CSS & JS feature or have a specific implementation in mind, please let me know, and I can provide more detailed guidance.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by TheRolfFR** [comment]
The href tag does work with the customapi:
```yaml
    - customapi:
        href: https://gethomepage.dev
        description: Test on customapi
        widget:
          type: customapi
          url: https://jsonplaceholder.org/users/1
          mappings:
            - field: id
              label: ID
              prefix: "#"
            - field:
                login: registered
              label: Registered
              format: date
```
It becomes clickable:
![image](https://github.com/gethomepage/homepage/assets/18086786/64c661f4-d593-4c72-825f-a099f040447b)
