### DISCUSSION TITLE
Custom API throwing API error despite Curl GET returning (Syncthing)

### DISCUSSION THREAD

**Discussion by AndyPro720** [gethomepage/homepage#3279] [Support] [answered]
### Description

Just as the title says, I've got a custom api running a widget for syncthing. I wrote custom code, tried #1869 and a few others and the bug persists. Using Curl with the API token works as intended. 

Also, the problem ideally isn't with the API key / header as the /noAuth link gave the same error. (Doesn't need any key verification)

Error I'm getting : 
``` API Error: HTTP Error     URL: http://syncthing:8384/rest/svc/report ```

### homepage version

v0.8.11 

### Installation method

Docker

### Configuration

```yaml
- Syncthing:
        icon: syncthing.png
        href: "http://127.0.0.1:8384"
        description: Syncs Data
        widget:
          type: customapi
          url: http://syncthing:8384/rest/svc/report
          headers:
            X-API-Key: <redacted>
          mappings:
            - field: totMiB
              label: Stored (MB)
              format: number
            - field: numFolders
              label: Folders
              format: number
            - field: totFiles
              label: Files
              format: number
            - field: numDevices
              label: Devices
              format: number
```

### Container Logs

![image](https://github.com/gethomepage/homepage/assets/42208057/60fdcf47-8c10-4626-9f21-533ee5ddfd89)

### Troubleshooting

``` curl -X GET -H "X-API-Key: Df------" http://127.0.0.1:8384/rest/svc/report``` works as intended. 

Also, the problem ideally isn't with the API key / header as the /noAuth link gave the same error. (Doesn't need any key verification)
