### DISCUSSION TITLE
Potential issue with sabnzbd widget

### DISCUSSION THREAD

**Discussion by ArthurMitchell42** [gethomepage/homepage#3291] [Support]
### Description

I have a services file with two entries for sabnzbd on two different hosts.
Although I have a different URL for the JSON API and different API keys the widget seems to display the same information for the first instance on both widgets as if the data isn’t being uniquely used.

### homepage version

0.8.9

### Installation method

Docker

### Configuration

```yaml
- SabNZB:
   href: http://10.0.10.180:8180/
   ping: http://10.0.10.180:8180/
   description: PI-Serve
   icon: nzbget.png
   widget:
      type: sabnzbd
      url: http://10.0.10.180:8180
      key: bab
- SabNZB:
   href: http://10.0.10.10:8180/
   ping: http://10.0.10.10:8180/
   description: Borg
   icon: nzbget.png
   widget:
      type: sabnzbd
      url: http://10.0.10.10:8180
      key: 212711b35
```

### Troubleshooting

Not investigations done yet, I’ll post tomorrow if I can find anything out about this
