### DISCUSSION TITLE
2 Pi-hole services listed, same stats for both... when they shouldn't be.

### DISCUSSION THREAD

**Discussion by cmdshft** [gethomepage/homepage#3294] [Support]
### Description

So I have two instances of Pi-Hole running for redundancy if I have to service one of the devices they run on. When I duplicated the services widget for it, I am getting the same stats for both of them even though one of them is brand new to the setup. Obviously this shouldn't be the case. I made sure the URLs are different as well, so idk how it's doing this.

![image](https://github.com/gethomepage/homepage/assets/8571823/755a595f-2a03-4e0a-bc41-1e521991f66e)

Stats from the primary pi-hole 10.0.0.15:
![image](https://github.com/gethomepage/homepage/assets/8571823/4dbd7088-46df-4ae3-b74c-2921f9eeb922)

Stats from the secondary pi-hole 10.0.0.25:
![image](https://github.com/gethomepage/homepage/assets/8571823/ea18649d-5b72-4ff4-af09-11b932d5715c)

As you can see, the stats shown by Homepage are incorrect.

### homepage version

0.8.11

### Installation method

Docker

### Configuration

```yaml
- Network Services:
    - Distributary:
        icon: unifi
        href: https://10.0.0.1/network/default/dashboard
        description: Unifi Dream Machine SE @ 10.0.0.1
        ping: http://10.0.0.1
        widget:
            type: unifi
            url: https://10.0.0.1:443
            username: 
            password: 
    - Pi-hole:
        icon: pi-hole.svg
        href: http://10.0.0.15/admin
        description: Raspberry Pi 4b @ 10.0.0.15
        ping: http://10.0.0.15
        widget:
            type: pihole
            url: http://10.0.0.15
            key: a485d05c831cfd2f3210cf670e9fe81cbfe00ba8a447a1fff235b2d3ef9f02c8
    - Pi-hole:
        icon: pi-hole.svg
        href: http://10.0.0.25/admin
        description: Raspberry Pi 3b+ @ 10.0.0.25
        ping: http://10.0.0.25
        widget:
            type: pihole
            url: http://10.0.0.25
            key: a485d05c831cfd2f3210cf670e9fe81cbfe00ba8a447a1fff235b2d3ef9f02c8
    - SpeedTest:
        icon: /icons/speedtest.png
        href: http://10.0.0.15:8080
        description: SpeedTest (PenTeleData Server)
        widget:
            type: speedtest
            url: http://10.0.0.15:8080
            fields: ["download", "upload", "ping"]


- Media Services:
    - Plex:
        icon: plex
        href: http://10.0.0.15:32400/web/index.html
        description: 10.0.0.15:32400
        ping: https://10.0.0.15
        widget:
          type: plex
          url: http://10.0.0.15:32400
          fields: ["streams", "movies", "tv"]
          key: abQZrmanT1A96qq6gXiq
    - Tautili:
        icon: tautulli
        href: http://10.0.0.15:8181
        description: Stats for Plex Media Server
        ping: http://10.0.0.15
        widget:
          type: tautulli
          url: http://10.0.0.15:8181
          key: d82be50d88d54d589ab53392aa35f364
    - Portainer:
        icon: portainer
        href: http://10.0.0.15:9000
        description: Raspberry Pi 4b @ 10.0.0.15:9000
        ping: http://10.0.0.15
        widget:
            type: portainer
            url: http://10.0.0.15:9000
            env: 2
            fields: ["running", "stopped", "total"]
            key: ptr_xVMUYglJ/C1G2PasqBVmsD23XLawkNNwqaRYEBnm738=

- System Stats (4b):
    - System Info:
        href: http://10.0.0.15:61208
        widget:
          type: glances
          url: http://10.0.0.15:61208/
          metric: info
    - CPU Usage:
        widget:
          type: glances
          url: http://10.0.0.15:61208/
          metric: cpu
    - Memory Usage:
        widget:
          type: glances
          url: http://10.0.0.15:61208/
          metric: memory
    - Network Usage:
        widget:
          type: glances
          url: http://10.0.0.15:61208/
          metric: network:eth0
```

### Troubleshooting

None.
