### DISCUSSION TITLE
Adding a Windows Drive to the resources list?

### DISCUSSION THREAD

**Discussion by ldbennett3** [gethomepage/homepage#3295] [Support] [answered]
### Description

Hello, I've been racking my brain about this and searching all over, but I cannot find any resources.
In the widgets.yaml I'm trying to add my D drive to the widgets at the top of the screen next to CPU usage and RAM.

I've tried `D:` `D:/` `D://` `D:\` and `D:\\` with no results. `D:\` is the only one that doesnt have an API error but just puts a singular - mark 

Installed via Node on a Windows 10 PC

### homepage version

v0.8.9 (c89c488)

### Installation method

Other (please describe above)

### Configuration

```yaml
widgets.yaml:

- resources:
    cpu: true
    memory: true
    disk: D:\
    uptime: true
```

### Troubleshooting

N/A

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the documentation available, it seems that you are trying to configure a disk resource to display information about your D drive on a Windows 10 PC where Homepage is installed via Node.

The correct way to specify the disk path in the `widgets.yaml` file for a Windows system should be using the standard Windows path format, but you need to escape the backslash (`\`) by using a double backslash (`\\`). However, since you've mentioned that using `D:\\` results in an API error, it's possible that there might be an issue with the way Homepage handles Windows paths or a bug in the version you are using.

Given that you've tried various formats without success, and considering that there was a similar issue discussed in the Homepage discussions where a bug with disks containing ':' was mentioned (see source: https://github.com/gethomepage/homepage/discussions/2169), it's possible that you are encountering a similar bug.

As a troubleshooting step, you can try updating to the latest version of Homepage if you haven't already, as the bug might have been fixed in a newer release. If the issue persists, it would be advisable to report this as a bug on the Homepage GitHub issues page, providing all the details you've mentioned here.

For now, please try the following format in your `widgets.yaml` file and see if it resolves the issue:

```yaml
- resources:
    cpu: true
    memory: true
    disk: "D:\\"
    uptime: true
```

If this does not work, consider reaching out to the Homepage community or checking if there are any updates or bug fixes related to this issue.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by kingofthesheep** [comment]
Just in case you still didn't figure this out or for anyone else is looking for this info, the proper syntax is "D:"
```
- resources:
    cpu: true
    memory: true
    disk: "D:"
    uptime: true
```
Or in the case of multiple drives
```
- resources:
    cpu: true
    memory: true
    disk:
      - "C:"
      - "D:"
      - etc..
    uptime: true
```

**Reply by psyonly** [reply]
It works fine on my computer

**Comment by Cryptorino** [comment]
cant get it to work either.. i really want it to show

**Comment by 10mfox** [comment]
you have to add the drive in your docker compose or docker run and adjust widgets.yaml like this

## Docker

    volumes:     
      - C:\:/pc # pc storage
      - F:\:/media # plex storage
      - Z:\:/games # games storage 

## widgets.yaml
```      
- resources:
    expanded: true
    disk: 
      - /pc
    label: Pc
    
- resources:
    expanded: true
    disk: 
      - /games      
    label: Games
    
- resources:
    expanded: true
    disk: 
      - /media
    label: Media```

**Comment by Tyri0n** [comment]
Anybody know how to add a path to a network drive under Windows?
I've tried all combinations that I can think of.
Mounting it as a drive letter and using - "X:" hasn't worked, either.

**Reply by ldbennett3** [reply, marked as answer]
I forgot to update my solution to this post but **"**X:**"** was the solution on Windows 10 (not in docker) for me. So same as above but most importantly putting it in quotes
Here's a copy of my config as an example:
```
- resources:
    label: "Drive Pool Total"
    expanded: true
    disk: "D:"
- resources:
    label: "Drive Pool Array"
    expanded: true
    disk: 
        - "F:"
        - "G:"
        - "H:"
        - "J:"
```
