### DISCUSSION TITLE
Misaligned widgets in mobile view

### DISCUSSION THREAD

**Discussion by auanasgheps** [gethomepage/homepage#3297] [Support]
### Description

Hi,
I have configured some widgets and they look great on Desktop, but looks like are misaligned when using a mobile portrait view.

Am I doing anything wrong?

Mobile portrait
<img width="540" alt="Screenshot_20240411-142726_Brave" src="https://github.com/gethomepage/homepage/assets/20586878/c647a662-f3c6-4cf6-8434-7c8af12db563">

Desktop 
<img width="515" alt="2024-04-15 14_54_29-lolnas homepage – Mozilla Firefox" src="https://github.com/gethomepage/homepage/assets/20586878/93721f50-2d41-4c72-81d2-b8cbe8928ae4">

### homepage version

v0.8.11

### Installation method

Docker

### Configuration

```yaml
# widgets.yaml 
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    label: System
    cpu: true
    memory: true
- resources:
    label: NVMe
    expanded: true
    disk: /
- resources:
    label: HDD
    expanded: true
    disk: /mnt/hdd

- search:
    provider: duckduckgo
    target: _blank

# settings.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: lolnas homepage

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  
 
layout:
  - Multimedia:
  - Download:
  - Storage:
  - Monitoring:
  - System:
        style: row
        columns: 4
```

### Container Logs

I don't think are relevant.

### Browser Logs

I don't think are relevant.

### Troubleshooting

I don't think are relevant.
