### DISCUSSION TITLE
Kubernetes widget results in TypeError: undefined is not an object (evaluating 's.show')

### DISCUSSION THREAD

**Discussion by jlaska** [gethomepage/homepage#3298] [Support] [answered]
### Description

Using homepage in kubernetes, changes to `settings.yaml` are not reflected in the application.  This issue appears similar to what is reported in #1446.  Homepage loads, but does not apply changes specified in my `settings.yaml` file.  I see the following errors in the web console.

The problem happens only when I add the following section to `widgets.yaml`.  Am I configuring the `kubernetes` widget incorrectly?  Is this a misconfiguration/authorization issue with my `ServiceAccount` or `ClusterRole`?

```yaml
- kubernetes:
  cluster:
    # Shows the cluster node
    show: true
    # Shows the aggregate CPU stats
    cpu: true
    # Shows the aggregate memory stats
    memory: true
    # Shows a custom label
    showLabel: false
    label: "cluster"

  nodes:
    # Shows the clusters
    show: true
    # Shows the CPU for each node
    cpu: true
    # Shows the memory for each node
    memory: true
    # Shows the label, which is always the node name
    showLabel: true
```

### homepage version

v0.8.11 (4239e8f, Apr 8, 2024)

### Installation method

Other (please describe above)

### Configuration

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
```

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
rules:
rules:
    - apiGroups:
        - ""
      resources:
        - namespaces
        - pods
        - nodes
      verbs:
        - get
        - list
    - apiGroups:
        - extensions
        - networking.k8s.io
      resources:
        - ingresses
      verbs:
        - get
        - list
    - apiGroups:
        - traefik.containo.us
        - traefik.io
      resources:
        - ingressroutes
      verbs:
        - get
        - list
    - apiGroups:
        - metrics.k8s.io
      resources:
        - nodes
        - pods
      verbs:
        - get
        - list
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions/status
      verbs:
        - get
```

### Container Logs

```
│ [2024-04-15T14:10:57.613Z] debug: No containers were found with homepage labels.                                                                                   │
│ [2024-04-15T14:10:57.646Z] error: undefined                                                                                                                        │
│ [2024-04-15T14:10:57.647Z] error: undefined                                                                                                                        │
│ [2024-04-15T14:10:58.148Z] debug: No containers were found with homepage labels.                                                                                   │
```

### Browser Logs

```js
[Error] TypeError: undefined is not an object (evaluating 's.show')
h — 2557.76303deb18b2f44c.js:1:3082
Eo — framework-eda4609282c049ac.js:3257:161
xi — framework-eda4609282c049ac.js:6422
bs — framework-eda4609282c049ac.js:5767
gs — framework-eda4609282c049ac.js:5760
vs — framework-eda4609282c049ac.js:5749
as — framework-eda4609282c049ac.js:5526:99
is — framework-eda4609282c049ac.js:5549
jl — framework-eda4609282c049ac.js:2417
Ss — framework-eda4609282c049ac.js:6105
(anonymous function) — framework-eda4609282c049ac.js:5834
S — framework-eda4609282c049ac.js:7388
T — framework-eda4609282c049ac.js:7426

	du (framework-eda4609282c049ac.js:1:71893)
	(anonymous function) (framework-eda4609282c049ac.js:1:72410)
	Ua (framework-eda4609282c049ac.js:1:53535)
	ki (framework-eda4609282c049ac.js:1:101309)
	bi (framework-eda4609282c049ac.js:1:100877)
	yi (framework-eda4609282c049ac.js:1:100413)
	(anonymous function) (framework-eda4609282c049ac.js:1:112250)
	ws (framework-eda4609282c049ac.js:1:112763)
	is (framework-eda4609282c049ac.js:1:106484)
	jl (framework-eda4609282c049ac.js:1:46919)
	Ss (framework-eda4609282c049ac.js:1:114106)
	(anonymous function) (framework-eda4609282c049ac.js:1:110554)
	S (framework-eda4609282c049ac.js:1:138469)
	T (framework-eda4609282c049ac.js:1:139003)
```

```js
[Error]  (2)
TypeError: undefined is not an object (evaluating 's.show') — 2557.76303deb18b2f44c.js:1:3082
{componentStack: "↵h@https://www.example.com/_next/static/chunks/2557.…xt/static/chunks/main-5004eaa7b9f962cb.js:1:11877"}
	value (index-923c207639b06e2f.js:1:17304)
	(anonymous function) (framework-eda4609282c049ac.js:1:72519)
	Ua (framework-eda4609282c049ac.js:1:53535)
	ki (framework-eda4609282c049ac.js:1:101309)
	bi (framework-eda4609282c049ac.js:1:100877)
	yi (framework-eda4609282c049ac.js:1:100413)
	(anonymous function) (framework-eda4609282c049ac.js:1:112250)
	ws (framework-eda4609282c049ac.js:1:112763)
	is (framework-eda4609282c049ac.js:1:106484)
	jl (framework-eda4609282c049ac.js:1:46919)
	Ss (framework-eda4609282c049ac.js:1:114106)
	(anonymous function) (framework-eda4609282c049ac.js:1:110554)
	S (framework-eda4609282c049ac.js:1:138469)
	T (framework-eda4609282c049ac.js:1:139003)
```

### Troubleshooting

See debug output and relevant log files in other sections.

(edited for syntax)

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that the issue might be related to the configuration of the `kubernetes` widget in your `widgets.yaml` file. The error in the browser logs suggests that there is a problem with the `show` property of the widget configuration. This could be due to a syntax error or misconfiguration in the `widgets.yaml` file.

To troubleshoot this issue, please verify the following:

1. Ensure that the indentation in your `widgets.yaml` file is correct. YAML files are sensitive to indentation, and incorrect indentation can lead to configuration not being read properly.

2. Check if the `kubernetes` widget configuration in your `widgets.yaml` file matches the structure shown in the documentation. It should look like this:

```yaml
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: false
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
```

Notice that the `kubernetes` key should be at the same indentation level as the `-` (dash) that starts the list item.

3. Verify that the `ServiceAccount` and `ClusterRole` have the necessary permissions to access the Kubernetes API and retrieve the required metrics.

4. Check the `homepage` version you are using to ensure it supports the configuration you are trying to apply.

5. Look at the container logs for any additional error messages that might indicate a problem with the Kubernetes API communication or other issues.

If you have verified the configuration and the issue persists, you may want to reach out to the Homepage support community for further assistance. You can use the 'Ask AI' button on the documentation pages, open a GitHub discussion, or check out the #ai-support channel on Discord for more help.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by jlaska** [comment]
🤦  For anyone else following, my problem was syntax of the `kubernetes` section in my `widgets.yaml` file.

## Incorrect

```yaml
- kubernetes:
  cluster:
    show: true
    cpu: true
    memory: true
    showLabel: false
    label: "cluster"

  nodes:
    show: true
    cpu: true
    memory: true
    showLabel: true
```

## Correct

```yaml
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: false
      label: "cluster"

    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
```
