### DISCUSSION TITLE
[Feature Request] Weather forecast

### DISCUSSION THREAD

**Discussion by rockett87** [gethomepage/homepage#3301] [Feature Requests]
### Description

Widget or service to show full 7 or 10 day weather forecast.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To display a full 7 or 10-day weather forecast on your Homepage dashboard, you can use the OpenWeatherMap widget, which offers a free tier "One Call API" that includes daily weather forecast data. You will need to subscribe to OpenWeatherMap, obtain an API key, and configure the widget with your API key and desired location coordinates.

Here's a basic configuration example for the OpenWeatherMap widget:

```yaml
- openweathermap:
    label: YourLocationLabel #optional
    latitude: YourLatitude
    longitude: YourLongitude
    units: metric # or imperial
    provider: openweathermap
    apiKey: youropenweathermapkey # required only if not using provider, this reveals api key in requests
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
```

Please replace `YourLocationLabel`, `YourLatitude`, `YourLongitude`, and `youropenweathermapkey` with your actual location label, latitude, longitude, and OpenWeatherMap API key.

Keep in mind that the widget will use your current location if you do not pass a `latitude` and `longitude`, but this requires a secure context (e.g., HTTPS).

For more detailed information and to subscribe for an API key, visit the OpenWeatherMap subscription page:
[https://home.openweathermap.org/subscriptions/unauth_subscribe/onecall_30/base](https://home.openweathermap.org/subscriptions/unauth_subscribe/onecall_30/base)

For the widget configuration documentation, refer to the OpenWeatherMap widget documentation on GitHub:
[https://github.com/gethomepage/homepage/tree/main/docs/widgets/info/openweathermap.md](https://github.com/gethomepage/homepage/tree/main/docs/widgets/info/openweathermap.md)

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
