### DISCUSSION TITLE
[Feature Request] Tasmota widget

### DISCUSSION THREAD

**Discussion by sprior** [gethomepage/homepage#3304] [Feature Requests]
### Description

It would be great to have a widget that shows on/off status of a Tasmota device, even better to optionally show current power consumption (available on some of their devices).  Not sure if providing a button to turn on/off the device is needed or not.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To create a widget that shows the on/off status and current power consumption of a Tasmota device, you would need to use a service that can interact with the Tasmota API or MQTT to retrieve the device's status and power consumption data. Currently, there is no direct documentation or feature within the Homepage project that specifically mentions integration with Tasmota devices.

However, you could potentially use a custom widget or an existing service widget that allows querying custom states or templates, such as the Home Assistant widget, if you have Home Assistant set up with your Tasmota devices. Home Assistant has integration with Tasmota, and you can create a long-lived access token to use with the Home Assistant widget on Homepage.

Here's a rough example of how you might configure the widget in Homepage to display Tasmota device status and power consumption using Home Assistant:

```yaml
widget:
  type: homeassistant
  url: http://homeassistant.host.or.ip:port
  key: access_token
  custom:
    - state: switch.your_tasmota_device
      label: Tasmota Device
      value: "{state}"
    - state: sensor.your_tasmota_power_consumption
      label: Power Consumption
      value: "{state} {attributes.unit_of_measurement}"
```

Please note that the `entity_id` (`switch.your_tasmota_device` and `sensor.your_tasmota_power_consumption`) will need to be replaced with the actual entity IDs of your Tasmota devices in Home Assistant.

As for providing a button to turn on/off the device, this would require additional functionality that allows sending commands back to the Tasmota device, which is not covered by the current documentation of Homepage. This feature might require custom development or a new feature request for the Homepage project.

If you're interested in pursuing this, you may want to reach out to the Homepage community or developers to see if there's interest in adding Tasmota integration or if someone has already worked on a similar feature.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
