### DISCUSSION TITLE
can customapi parse a json array?

### DISCUSSION THREAD

**Discussion by nopoz** [gethomepage/homepage#3305] [Support] [answered]
### Description

If an API endpoint outputs a json array, is it possible to parse each array entry with the customapi widget? My goal is to get the name and status for each array item below to display. I thought maybe I could use `[0]`, `[1]` on the services.yaml mappings but that doesn't work. 

Example json:
```
[
    {
        "name": "FirstName",
        "status": "online"
    },
    {
        "name": "SecondName",
        "status": "online"
    }
]
```

If I use this services.yaml below, the label names are there, but the values shows as "-"

```
    - Example Dashboard:
        href: https://example.com
        description: Example Dashboard
        widget:
            type: customapi
            url: https://api.example.com/api/v1/endpoint
            method: GET
            headers:
                Authorization: Bearer {{HOMEPAGE_VAR_EXAMPLE_API}}
            mappings:
                - field: name
                  label: Name
                - field: status
                  label: Status
```

If I try this services.yaml below, no widget items show up under the dashboard item at all:

```
    - Example Dashboard:
        href: https://example.com
        description: Example Dashboard
        widget:
            type: customapi
            url: https://api.example.com/api/v1/endpoint
            method: GET
            headers:
                Authorization: Bearer {{HOMEPAGE_VAR_EXAMPLE_API}}
            mappings[0]:
                - field: name
                  label: Name
                - field: status
                  label: Status
            mappings[1]:
                - field: name
                  label: Name
                - field: status
                  label: Status
```

### homepage version

v0.8.10

### Installation method

Docker

### Troubleshooting

see description
