### DISCUSSION TITLE
Quickstart and Search focus not working

### DISCUSSION THREAD

**Discussion by mayur2281** [gethomepage/homepage#3309] [Support]
### Description

widgets.yaml:
```yaml
- search:
    provider: google
    focus: true
    target: _blank
    showSearchSuggestions: true
```

settings.yaml:
```yaml
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
```

These 2 blocks are not working on my dashboard. Internet results are coming when i search for applications within homepage.

Screenshots:
![Screenshot 2024-04-16 at 10 18 15 PM](https://github.com/gethomepage/homepage/assets/125241115/0fc814d1-0191-4e31-a826-7e5801ec589c)

### homepage version

v0.8.11 (4239e8f, Apr 8, 2024)

### Installation method

Docker

### Troubleshooting

Screenshots added above
