### DISCUSSION TITLE
API Error: Unexpected token 'I', "Internal S"... is not valid JSON

### DISCUSSION THREAD

**Discussion by thisguyshouldworkforus** [gethomepage/homepage#3311] [Support] [answered]
### Description

I'm not sure what I'm doing wrong, hoping someone can clue me in, but my implementation of the Pi-Hole widget is not working. All I get is an `API Error`.

I am able to connect to the URL from the `homepage` server, and I have many other widgets operating normally. I am also able to successfully get valid JSON when I visit the URL directly `http://pihole.myinternal.domain.com/admin/api.php`

```json
{
    "domains_being_blocked": 164561,
    "dns_queries_today": 136634,
    "ads_blocked_today": 23172,
    "ads_percentage_today": 16.959175,
    "unique_domains": 10512,
    "queries_forwarded": 37892,
    "queries_cached": 74064,
    "clients_ever_seen": 33,
    "unique_clients": 33,
    "dns_queries_all_types": 136634,
    "reply_UNKNOWN": 2161,
    "reply_NODATA": 13386,
    "reply_NXDOMAIN": 9911,
    "reply_CNAME": 16115,
    "reply_IP": 85407,
    "reply_DOMAIN": 8025,
    "reply_RRNAME": 13,
    "reply_SERVFAIL": 1430,
    "reply_REFUSED": 0,
    "reply_NOTIMP": 0,
    "reply_OTHER": 0,
    "reply_DNSSEC": 7,
    "reply_NONE": 0,
    "reply_BLOB": 179,
    "dns_queries_all_replies": 136634,
    "privacy_level": 0,
    "status": "enabled",
    "gravity_last_updated": {
        "file_exists": true,
        "absolute": 1713094384,
        "relative": {
            "days": 2,
            "hours": 10,
            "minutes": 16
        }
    }
}
```

This is the section of my `services.yaml` file:
```yaml
    - PiHole:
        icon: pi-hole.png
        href: http://pihole.myinternal.domain.com/admin/login.php
        description: DNS Blackhole Utility
        widget:
          type: pihole
          url: pihole.myinternal.domain.com
          version: 5
          key: API_KEY
```

Thanks for the help!

### homepage version

0.8.11

### Installation method

Docker

### Troubleshooting

`curl -L -k http://pihole.myinternal.domain.com/admin/api.php`
```json
[]
```
