### DISCUSSION TITLE
Bookmark on 5 columns

### DISCUSSION THREAD

**Discussion by stanthewizzard** [gethomepage/homepage#3315] [Support]
### Description

I would like to display the bookmarks on 5 columns 

### homepage version

v0.8.11 (4239e8f, Apr 8, 2024)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: HQC Network

headerStyle: boxedWidgets
disableCollapse: false

layout:
  Bookmark Group on First Tab:
    tab: Glances

  Glances>Network10:
    tab: Glances
    style: row
    columns: 4

  Glances>Service10:
    tab: Glances
    style: row
    columns: 4

  Glances>Network20:
    tab: Glances
    style: row
    columns: 4

  Glances>Service20:
    tab: Glances
    style: row
    columns: 4

  Glances>Service30:
    tab: Glances
    style: row
    columns: 4

  Glances>Grabbing20:
    tab: Glances
    style: row
    columns: 4

  Grabbing:
    tab: Grabbing
    style: row
    columns: 3

  My Media:
    tab: My Media
    style: row
    columns: 3

  Portainer:
    tab: Portainer
    style: row
    columns: 3

  Kuma:
    tab: Kuma
    style: row
    columns: 3

  Network:
    tab: Network
    style: row
    columns: 3

  Files:
    tab: Files
    style: row
    columns: 3

  Service Group on every Tab:
    style: row
    columns: 4

showStats: true



quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
```

### Troubleshooting

only displays max 4 columns

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To display bookmarks in 5 columns, you need to add the `fiveColumns: true` setting to your configuration. However, based on the context provided, it seems that the `fiveColumns` setting is only applicable to services and not bookmarks. By default, homepage will max out at 4 columns for services with `columns` style, and bookmarks default to 6 columns.

If you want to enforce a 5-column layout for bookmarks, you might need to adjust the layout settings specifically for the bookmark groups. Unfortunately, the provided context does not include a direct way to set bookmarks to 5 columns, as the `fiveColumns` setting is mentioned in relation to services, not bookmarks.

If you are experiencing that bookmarks are not adhering to the `fiveColumns` setting, it could be due to a version-specific behavior or a limitation in the application. In such a case, you may want to reach out to the maintainers of the Homepage project for further assistance or check if there have been any updates or bug fixes related to this issue.

For now, you can try adding the `fiveColumns: true` setting under the `quicklaunch` or `layout` section of your `settings.yaml` file to see if it affects the bookmark columns. If this does not work, it's likely that the feature is not supported for bookmarks, and you may need to look for alternative solutions or wait for a feature update.

```yaml
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  fiveColumns: true
```

or

```yaml
layout:
  ...
  fiveColumns: true
```

Remember to replace the `...` with the actual content of your layout configuration.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
