### DISCUSSION TITLE
info widgets only show stats from the docker container, not the host that docker is running on…

### DISCUSSION THREAD

**Discussion by bewareofgeek** [gethomepage/homepage#3316] [Support]
### Description

I'm having trouble getting disk info, but even the CPU, memory, etc. widgets show stats for the docker container, not the host system that docker is running in. What could I be doing wrong.
![Screenshot 2024-04-17 at 11 55 07 AM](https://github.com/gethomepage/homepage/assets/121703739/ac53f032-bbca-4714-96a0-bc31d0594a0b)

### homepage version

0.8.12

### Installation method

Docker

### Configuration

```yaml
Host system: macos sonoma 14.4.1
docker-compose.yaml:
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 501
      GUID: 20
    ports:
      - 3000:3000
    volumes:
      - /Volumes/DATA/config/Homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - /Volumes/DATA/config/Homepage/config/images:/app/public/images
      - /Volumes/DATA/config/Homepage/config/icons:/app/public/icons
      - /Volumes/DATA
    restart: unless-stopped

---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    expanded: true
    cpu: true
    cputemp: true
    memory: true
    uptime: true
    disk: /Volumes/DATA

- search:
    provider: duckduckgo
    target: _top


/Volumes/Data is an external drive connected to the mac
In the screenshot, the disk info is identical to what docker desktop shows. The drive I've configured is 5TB, with 1.47TB free. 

The CPU and memory widgets are clearly for the docker container and match what docker desktop shows. The host system has 16GBs RAM and the the CPU was at about 23% when the screenshot was taken. 

CPU temp shows nothing at all, I assume because it can't see outside the container as well. 

Even uptime is wrong, but it doesn't match the container or the host. The container had been up for less than an hour and the host had an uptime of 10 days+.

I am very new to this, but I have searched high and low and can't find a good answer.

I have no doubt I'm doing something wrong, but the documentation hasn't cleared up anything for me.
```

### Troubleshooting

I've tried every variation I could find for the disk info, but have no idea how to correct the other widgets.
