### DISCUSSION TITLE
Wrong Unit in evcc.io Widget

### DISCUSSION THREAD

**Discussion by abeggled** [gethomepage/homepage#3317] [Support]
### Description

The evcc.io widget use wrong units. Currently it's Wh but it has to be W, as it's the current power which is displayed.

### homepage version

v0.8.12 (12ec1cf, Apr 17, 2024)

### Installation method

Docker

### Configuration

```yaml
- evcc.io:
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROnVvywsGSPL9oidGw_kwQz9hWrQJjQ3cvZkRI1ubcpQ&s
        href: http://fqdn:7070
        description: Ladesteuerung
        widget:
            type: evcc
            url: http://fqdn:7070
```

### Troubleshooting

-
