### DISCUSSION TITLE
Move from x86 VM to Raspberry pi - no icons?

### DISCUSSION THREAD

**Discussion by oester** [gethomepage/homepage#3324] [Support]
### Description

I had Homepage running on an x86 VM, and I decided to move it over to my raspberry pi 4. Copied the config directory, docker-compose.yml. Homepage starts up fine, but when I connect to port 3000, none of the icons display - just the word "icon". I'm not using any custom icons, just the ones from "Dashboard Icons"

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
Example entry from services.yml:

- Services:
    - Proxmox:
        icon: proxmox.png
        href: https://192.168.15.2:8006
        description: Hypervisor
        siteMonitor: https://192.168.15.2:8006
        widget:
          type: proxmox
          url: https://192.168.10.6:8006
          username: api@pam!homepage
          password: XXXXX
#          node: pve01
```

### Troubleshooting

None.
