### DISCUSSION TITLE
Calender widget not showing new Sonarr & Radarr events

### DISCUSSION THREAD

**Discussion by Mikeoes** [gethomepage/homepage#3326] [Support] [answered]
### Description

With some effort I got the calender widget visible but for some reason it does not show the releases info from Radarr or Sonarr. I assume there is something missing in my code but I can't find it on the Wiki or here on the Github so I hope any of you can point out my error. Where masking is required I added the name of the value in caps.

EDIT: The individual widgets work as expected. That is obviously important to know,
EDIT2: Other solutions like Homarr can pick up the value's so the API rights also seem to be in place and correct.

Sonarr config:
- Sonarr:
        icon: sonarr.png
        href: http://IP:PORT
        server: my-docker
        container: CONTAINERNAME
        widget:
         type: sonarr
         url: http://IP:PORT
         key: "APIKEY"
         enableQueue: true # optional, defaults to false

Radarr config:
    - radarr:
        icon: radarr.png
        href: http://IP:PORT
        server: my-docker
        container: CONTAINERNAME
        widget:
          type: radarr
          url: http://IP:PORT
          key: "APIKEY"
          enableQueue: true # optional, defaults to false

Calendar Config:
    - Calender:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          maxEvents: 31
          showTime: true
          timezone: TIMEZONE
          integrations:
            - type: Sonarr
              service_group: Media
              service_name: Sonarr
              color: lime
              params:
                unmonitored: true
            - type: Radarr
              service_group: Media
              service_name: Radarr
              color: yellow
              params:
                unmonitored: true

### homepage version

v0.8.12

### Installation method

Docker

### Troubleshooting

I read all of the wiki and went trough the github. Loggins is empty.

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the context from the sources, it seems that there might be a discrepancy in the way the `type` is defined in the calendar integrations compared to the individual service configurations. In the calendar configuration, the `type` for Sonarr and Radarr integrations is capitalized ("Sonarr" and "Radarr"), whereas in the service configurations and the documentation, the `type` is all lowercase ("sonarr" and "radarr").

To potentially resolve the issue, try updating the calendar configuration to use lowercase for the `type` as shown below:

```yaml
- Calendar:
    widget:
      type: calendar
      firstDayInWeek: monday
      view: monthly
      maxEvents: 31
      showTime: true
      timezone: TIMEZONE
      integrations:
        - type: sonarr
          service_group: Media
          service_name: Sonarr
          color: lime
          params:
            unmonitored: true
        - type: radarr
          service_group: Media
          service_name: Radarr
          color: yellow
          params:
            unmonitored: true
```

Please ensure that the `service_group` and `service_name` match the group and service names you have set up elsewhere in your configuration. Also, make sure that the `url` and `key` values are correct and that the API key has the necessary permissions.

If the issue persists after making these changes, please check the container logs for any errors that might indicate a problem with the integration or the API connection to Sonarr and Radarr.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
