### DISCUSSION TITLE
Pi-Hole Widget is not working: "API Error: The string did not match the expected pattern."

### DISCUSSION THREAD

**Discussion by d33pjs** [gethomepage/homepage#3327] [Support] [answered]
### Description

My Pi-Hole Widget on Homepage is not working and I can't figure out why.

<img width="424" alt="image" src="https://github.com/gethomepage/homepage/assets/2799774/300afffc-3599-463b-a4b2-053d98d9baf9">

It's available (only) via two reverse proxies. But it doens't look like a Problem with them.

My Configuration is attached.

Also Safari returns:
<img width="432" alt="image" src="https://github.com/gethomepage/homepage/assets/2799774/70f0fa8e-9f06-4a24-a351-978b4f5e1cd9">
in console.

Any idea what could be wrong?

PS. Your AI-Bot-Channel on https://gethomepage.dev/latest/more/troubleshooting/ doesn't seem to work anymore.

### homepage version

v0.8.12 (12ec1cf, Apr 17, 2024)

### Installation method

Docker

### Configuration

```yaml
(services)
    - PiHole Berkelium:
        widget:
          type: pihole
          url: https://name:9999/
          version: 6
          key: token_via_ansible
        href: https://anothername/admin
        icon: pi-hole.svg

---
(docker-compose.yml)
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      TZ: 'Europe/Berlin'
      VIRTUAL_HOST: name
      CORS_HOSTS: name, anothername
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"      
      - /pihole/etc-pihole:/etc/pihole
      - /pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
```

### Container Logs

The Proxy next to Pi-Hole writes:
```
<ip> - - [18/Apr/2024:11:58:20 +0000] "POST /api/auth HTTP/1.1" 404 341 "-" "-" "ip"
```
or
```
<ip> - - [18/Apr/2024:12:44:57 +0000] "POST //api/auth HTTP/1.1" 404 341 "-" "-" "-"
```
So, yeah, it's a 404.

Homepage on the other Hand throw some (not very helpfull) errors on every access:

```
[2024-04-18T12:38:51.061Z] error: undefined
[2024-04-18T12:39:13.018Z] error: undefined
[2024-04-18T12:39:23.106Z] error: undefined
```

### Troubleshooting

I tried "https://name:9999" (without / at the end), "https://anothername/" (lets encrypt cert), "https://anothername" (again, without / at the end) and both DNS Names like: "https://name:9999/admin". But none of them are working inside Homepage. API via curl is indeed working.
