### DISCUSSION TITLE
[Feature Request] Add Nomad service discovery

### DISCUSSION THREAD

**Discussion by icyleaf** [gethomepage/homepage#3329] [Feature Requests]
### Description

As you can see from the discussion https://github.com/gethomepage/homepage/discussions/1655 I submitted, I am a homelab user of nomad clusters. At first I used the docker proxy compatible solution to display services for the homepage, until some services needed to scale > 2, the control panel would show multiple duplicate services and could not be merged into one. To this end, I particularly hope to be able to support nomad service discovery. At present, I have forked the repository myself and implemented this solution to run stably in versions 0.7~ 0.8.x. Those who are interested can try it out. At the same time, I hope to gain your support to merge this feature into the main project. Please feel free to +1 it!

My forked repository: https://github.com/icyleaf/homepage/tree/feature/nomad-support
Docker image: https://ghcr.io/icyleaf/homepage:0.8.8-nomad

### Docker compose 

Add new file named `nomad.yaml` to `/app/config` directory:

remove `token` key if not enable ACL.

```yaml
---
nomad-cluster:
  endpoint: http://171.169.21.100/v1
  token: "<token>"
  namespace: "*"
```

Replace image in Docker Compose file:

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/icyleaf/homepage:0.8.8-nomad
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
```

### Nomad homepage job

```hcl
job "homepage" {
  type        = "service"

  group "homepage" {
    network {
      port "web" {
        to     = 3000
      }
    }

    service {
      name = "homepage"
      port = "web"
      provider = "nomad"

      tags = [
        "traefik.enable=true",
        "traefik.http.routers.whoami.rule=Host(`home.example.com`)",
        "traefik.http.routers.whoami.entrypoints=web, websecure",
      ]
    }

    task "homepage" {
      driver = "docker"
      config {
        image = "ghcr.io/icyleaf/homepage:0.8.8-nomad"
        volumes = [
          "local/:/app/config/"
        ]
      }

      template {
        destination = "local/nomad.yaml"
        data        = <<-EOF
        ---
        nomad:
          endpoint: http://{{ env "attr.nomad.advertise.address" }}/v1
        EOF
      }
    }
  }
}
```

### Register a job to homepage

Append tags in `service` block with same struct as [Kubernetes](https://gethomepage.dev/latest/configs/kubernetes/#automatic-service-discovery).

```hcl
job "whoami" {
  type        = "service"

  group "whoami" {
    network {
      port "web" {
        to     = 80
      }
    }

    service {
      name = "whoami"
      port = "web"
      provider = "nomad"

      tags = [
        "traefik.enable=true",
        "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)",
        "traefik.http.routers.whoami.entrypoints=web, websecure",

        "gethomepage.dev/enabled=true",
        "gethomepage.dev/group=Tool",
        "gethomepage.dev/name=whoami",
        // "gethomepage.dev/href=https://whoami.example.com",  # overwrite oraginal service ip with port address.
        "gethomepage.dev/description=Whoami is a tiny Go webserver that prints os information and HTTP request to output",
      ]
    }

    task "whoami" {
      driver = "docker"
      config {
        image = "ghcr.io/traefik/whoami:v1.10.1"
      }
    }
  }
}
```

### Other

Relates to #2494
