### DISCUSSION TITLE
Wrong disk usage resources widget

### DISCUSSION THREAD

**Discussion by matsudayoji** [gethomepage/homepage#3334] [Support]
### Description

Widget shows more free resources than fact.
For example,
widget
![image](https://github.com/gethomepage/homepage/assets/23697246/e011402c-bcc7-47f1-be90-77c6a6d93bf7)

in fact
```console
df -h
```
output
```console
Filesystem                        Size  Used Avail Use% Mounted on
/dev/sda1                         7.3T  1.6T  5.7T  22% /mnt/DATA
```

### homepage version

v0.8.12

### Installation method

Source

### Configuration

```yaml
widgets.yaml

- resources:
    label: storage
    expanded: true
    disk: 
      - /
      - /mnt/DATA
```

### Troubleshooting

no logs
