### DISCUSSION TITLE
[Feature Request] Create/show bookmarks with Docker Automatic Service Discovery

### DISCUSSION THREAD

**Discussion by okunze** [gethomepage/homepage#3359] [Feature Requests]
### Description

I use the Automatic Service Discovery in Homepage for my containers. What I'm currently missing is a way to create additional bookmarks together with the service using a label in Docker.

My ulterior motive: I start a Grafana instance, for example, and additional links are automatically created for dashboards that I have defined.

I imagine something like this (where “.id*” is just a placeholder/ID to be defined to distinguish individual bookmarks)

```
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    labels:
      - homepage.group=Dashboards
      - homepage.name=Grafana
      - homepage.icon=grafana.png
      - homepage.href=http://grafana.local/
      - homepage.description=Dashboard anything. Observe everything.
      - homepage.bookmark.id1.group=Other Dashboards
      - homepage.bookmark.id1.name=Dashboard 1
      - homepage.bookmark.id1.icon=grafana.png
      - homepage.bookmark.id1.abbr=D1
      - homepage.bookmark.id1.href=http://grafana.local/d/dashboard1/
      - homepage.bookmark.id1.description=Dashboard 1
      - homepage.bookmark.id2.group=Other Dashboards
      - homepage.bookmark.id2.name=Dashboard 2
      - homepage.bookmark.id2.icon=grafana.png
      - homepage.bookmark.id2.abbr=D2
      - homepage.bookmark.id2.href=http://grafana.local/d/dashboard2/
      - homepage.bookmark.id2.description=Dashboard 1
```

Or is there already a way to implement something like this or has it already been implemented?

Thanks

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Currently, Homepage does not support the direct creation of additional bookmarks using Docker labels alongside the Automatic Service Discovery for services. The service discovery feature is designed to automatically detect and configure services based on the labels provided, but it does not extend to creating bookmarks within those services.

However, you can manually add bookmarks by editing the `bookmarks.yaml` file as described in the documentation. This file allows you to configure bookmarks similarly to services, but they are simpler and are essentially just links.

If you want to have bookmarks automatically created based on Docker labels, this would likely require a feature request to be submitted to the Homepage project for consideration. You can check the existing issues and discussions on the Homepage GitHub repository to see if such a feature has been requested or is being discussed, and if not, you can open a new issue to suggest it.

For now, you would need to manually manage your bookmarks in the `bookmarks.yaml` file. Here is an example of how you could manually add bookmarks for your Grafana dashboards:

```yaml
- Dashboards:
    - Dashboard 1:
        icon: grafana.png
        href: http://grafana.local/d/dashboard1/
        description: Dashboard 1
    - Dashboard 2:
        icon: grafana.png
        href: http://grafana.local/d/dashboard2/
        description: Dashboard 2
```

Remember to follow the structure and syntax as outlined in the bookmarks documentation when editing the `bookmarks.yaml` file.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
