### DISCUSSION TITLE
[Feature Request] Multiple Plex servers

### DISCUSSION THREAD

**Discussion by funnelcloudservices** [gethomepage/homepage#3363] [Feature Requests]
### Description

I run multiple Plex servers.  They both use the same key however so the widget only shows information for one machine.

### Other

(sorry in advance if this is more a support request, I tried a few different things but nothing worked)

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To address the issue of your Plex widget only showing information for one machine despite running multiple Plex servers, you will need to ensure that each Plex server has a unique API key. The widget configuration relies on these keys to fetch and display data for each individual server. If both servers are using the same key, the widget may not be able to distinguish between the two servers, leading to the problem you're experiencing.

Here's what you can do:

1. Generate a unique API key for each Plex server. You can usually do this within the Plex server settings. Refer to Plex's documentation or the Plexopedia link provided in the context for guidance on generating a new token: https://www.plexopedia.com/plex-media-server/general/plex-token/

2. Update your widget configuration for each Plex server with the respective unique API key. Make sure that the `url` field points to the correct IP address and port for each server.

Here is an example of how your configuration might look with two separate Plex servers:

```yaml
- Plex1:
    icon: plex.png
    href: http://plex1.host.or.ip:32400/web/index.html
    description: Plex Server 1
    widget:
      type: plex
      url: http://plex1.host.or.ip:32400
      key: uniqueTokenForPlex1

- Plex2:
    icon: plex.png
    href: http://plex2.host.or.ip:32400/web/index.html
    description: Plex Server 2
    widget:
      type: plex
      url: http://plex2.host.or.ip:32400
      key: uniqueTokenForPlex2
```

Replace `uniqueTokenForPlex1` and `uniqueTokenForPlex2` with the actual API keys for your Plex servers, and adjust the `url` and `href` fields to match the correct addresses for your setup.

If you continue to experience issues after ensuring each Plex server has a unique API key and updating your configuration accordingly, please provide additional details about your setup, and I will be happy to assist you further.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
