### DISCUSSION TITLE
Homepage errors using glances widget

### DISCUSSION THREAD

**Discussion by Sitherious** [gethomepage/homepage#3368] [Support] [answered]
### Description

well i am having an error with pulling glances info for homepage, the AI bot said my format was correct and im at a loss on what to fix and what todo. no error in logs
website error

### homepage version

startpage@0.1.0 build

### Installation method

Docker

### Configuration

```yaml
services.yaml
`---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Infrastructure:
    - PiHole:
        href: http://192.168.1.206/admin
        icon: mdi-pi-hole
        ping: http://192.168.1.206/admin
        statusStyle: "dot"
        widget:
          type: pihole
          url: http://192.168.1.206
          key: psswd
          fields: ["queries", "blocked", "blocked_percent", "gravity"]
    - Cloudflared:
        href: https://dash.cloudflare.com
        icon: mdi-cloud-key
        ping: https://dash.cloudflare.com
        statusStyle: "dot"
        widget:
          type: cloudflared
          accountid: 47c64940abff809212790c952475cf91 # from zero trust dashboard url e.g. https://one.dash.cloudflare.com/<accountid>/home/quick-start
          tunnelid: 4f896008-6e75-4e78-bf4d-7bb2bb6344e1 # found in tunnels dashboard under the tunnel name
          key: BA7Pjs_rbKA_8xgwScBXFk6SLC2SuqmkMMJpaod8 # api token with `Account.Cloudflare Tunnel:Read` https://dash.cloudflare.com/profile/api-tokens
          fields: ["status", "origin_ip"]
    - Pfsense:
        href: https://192.168.1.1
        icon: mdi-wall-fire
        ping: http://192.168.1.1
        statusStyle: "dot"
        widget:
          type: pfsense
          url: https://192.168.1.1:443
          username: user
          password: psswd
          wan: igb0
          fields: ["load", "memory", "temp", "disk"]
    - AMP:
        href: http://192.168.1.207:8080
        icon: mdi-youtube-gaming
        ping: http://192.168.1.207:8080
        statusStyle: "dot"
- Media:
    - Immich:
        href: http://192.168.1.208:2283
        icon: mdi-image-album
        widget:
          type: immich
          url: http://192.168.1.208:2283
          key: psswd
          fields: ["users" ,"photos", "videos", "storage"]
    - Jellyfin:
        icon: mdi-jellyfish
        href: http://localhost
        widget:
          type: jellyfin
          url: http://jellyfin.host.or.ip
          key: apikeyapikeyapikeyapikeyapikey
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          fields: ["movies", "series", "episodes", "songs"]
    - Sonarr:
        icon: mdi-satellite
        widget:
          type: sonarr
          url: http://sonarr.host.or.ip
          key: apikeyapikeyapikeyapikeyapikey
          enableQueue: true # optional, defaults to false
          fields: ["wanted", "queued", "series"]
    - Radarr:
       icon: mdi-satellite-variant
       widget:
          type: radarr
          url: http://192.168.1.85
          key: psswd
          enableQueue: true # optional, defaults to false
          fields: ["wanted", "missing", "queued", "movies"]
- Remote Management:
    - Matrix:
       description: 6.8.4-2-pve
       icon: mdi-server
       href: https://192.168.1.203:8006
       ping: https://192.168.1.203:8006
       statusStyle: "dot"
       widget:
          type: proxmox
          url: https://192.168.1.203:8006
          username: info@pam!homepage
          password: psswd
          fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - Matrix:
       icon: mdi-server
       widget:
          type: glances
          url: http://192.168.1.23:61208
          metric: sensors:loc1
    - Matrix:
       icon: mdi-server
       widget:
          type: glances
          url: http://192.168.1.23:61208
          metric: info
    - Matrix iDRAC:
        icon: mdi-server-network-outline
        href: https://192.168.1.223
        ping: https://192.168.1.223
        statusStyle: "dot"
    - NeoMatrix:
       description: 6.8.4-2-pve
       icon: mdi-server
       href: https://192.168.1.204:8006
       ping: https://192.168.1.204:8006
       statusStyle: "dot"
       widget:
         type: proxmox
         url: https://192.168.1.204:8006
         username: info@pam!homepage
         password: psswd
         node: neo # optional
         fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - NeoMatrix iDRAC:
        icon: mdi-server-network-outline
        href: https://192.168.1.224
        ping: https://192.168.1.224
        statusStyle: "dot"
    - OmniMatrix:
       icon: mdi-server
       href: https://192.168.1.202:8006
       ping: https://192.168.1.202:8006
       statusStyle: "dot"
       widget:
         type: proxmox
         url: https://192.168.1.202:8006
         username: info@pam!homepage
         password: psswd
         node: omni # optional
         fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - OmniMatrix iDRAC:
        icon: mdi-server-network-outline
        href: https://192.168.1.220
        ping: https://192.168.1.220
        statusStyle: "dot"
    - SubMatrix:
       icon: mdi-server
       href: https://192.168.1.201:8006
       ping: https://192.168.1.201:8006
       statusStyle: "dot"
       widget:
         type: proxmox
         url: https://192.168.1.201:8006
         username: info@pam!homepage
         password: psswd
         node: submatrix # optional
         fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - SubMatrix iDRAC:
        icon: mdi-server-network-outline
        href: https://192.168.1.221
        ping: https://192.168.1.221
        statusStyle: "dot"
    - UniMatrix:
       icon: mdi-server
       href: https://192.168.1.200:8006
       ping: https://192.168.1.200:8006
       statusStyle: "dot"
       widget:
         type: proxmox
         url: https://192.168.1.200:8006
         username: info@pam!homepage
         password: psswd
         node: uni # optional
         fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - UniMatrix iDRAC:
        icon: mdi-server-network-outline
        href: https://192.168.1.222
        ping: https://192.168.1.222
        statusStyle: "dot"`
```

### Container Logs

none

### Browser Logs

`Something went wrong.
TypeError: Cannot read properties of undefined (reading 'forEach')

    at $ (http://192.168.1.205:3000/_next/static/chunks/4573.e12a00b4e81a1da2.js:1:16517)
    at A (http://192.168.1.205:3000/_next/static/chunks/4573.e12a00b4e81a1da2.js:1:19986)
    at h (http://192.168.1.205:3000/_next/static/chunks/3273-b41d9b4211d16133.js:1:34135)
    at n (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:16753)
    at O (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:32077)
    at div
    at li
    at H (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:35971)
    at ul
    at D (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:40036)
    at div
    at http://192.168.1.205:3000/_next/static/chunks/3273-b41d9b4211d16133.js:1:77871
    at div
    at l (http://192.168.1.205:3000/_next/static/chunks/3273-b41d9b4211d16133.js:1:106624)
    at http://192.168.1.205:3000/_next/static/chunks/3273-b41d9b4211d16133.js:1:96029
    at http://192.168.1.205:3000/_next/static/chunks/3273-b41d9b4211d16133.js:1:94797
    at l (http://192.168.1.205:3000/_next/static/chunks/3273-b41d9b4211d16133.js:1:106624)
    at http://192.168.1.205:3000/_next/static/chunks/3273-b41d9b4211d16133.js:1:75810
    at div
    at M (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:40530)
    at div
    at div
    at be (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:59262)
    at n (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:16753)
    at http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:86949
    at he (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:57268)
    at div
    at div
    at div
    at ve (http://192.168.1.205:3000/_next/static/chunks/pages/index-9a51a6daed02a468.js:1:66903)
    at a (http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:12301)
    at a (http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:11945)
    at s (http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:12860)
    at u (http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:11373)
    at http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:86949
    at http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:10618
    at l (http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:1886)
    at n (http://192.168.1.205:3000/_next/static/chunks/pages/_app-66fb2a0d4552baa6.js:1:6350)
    at n (http://192.168.1.205:3000/_next/static/chunks/main-e8fe7019ccc09aba.js:1:14345)
    at X (http://192.168.1.205:3000/_next/static/chunks/main-e8fe7019ccc09aba.js:1:16462)
    at oe (http://192.168.1.205:3000/_next/static/chunks/main-e8fe7019ccc09aba.js:1:19153)

### Troubleshooting

i am able to curl the url from homepage 
`root@homepage:/opt/homepage/config# curl http://192.168.1.23:61208/
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Glances</title>

    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <script>
      window.__GLANCES__ = {
        'refresh-time': '2'
      }
    </script>
    <script src="glances.js" defer></script>

</head>

<body>
  <div id="app"></div>
</body>
</html>
root@homepage:/opt/homepage/config# `
