### DISCUSSION TITLE
Change column width

### DISCUSSION THREAD

**Discussion by apat183** [gethomepage/homepage#3373] [General]
Hi, not sure if this can be already achieved with custom CSS (if so any guidance would be great) but what I'm trying to achieve is have three columns, but the middle column having all the main content and taking up like 70% of screen. So that more glance/information widgets can be placed on left and right.

e.g.
![image](https://github.com/gethomepage/homepage/assets/7892604/d111cf67-325b-4c07-a1c3-b2e574e930df)

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To achieve a layout where the middle column takes up approximately 70% of the screen with additional columns on the left and right for glance/information widgets, you will indeed need to use custom CSS along with the layout configuration in your `settings.yaml` file.

Here's a general approach you could take:

1. Define your layout in the `settings.yaml` file with three columns, where the middle column is designated for your main content. You can use the `style: row` and `columns: 3` configuration to create a three-column layout.

2. Use custom CSS to adjust the width of the middle column to take up 70% of the screen. You will need to edit the `custom.css` file in your config directory to add the necessary styles.

3. Assign classes or IDs to your columns in the YAML configuration if needed, so you can target them specifically in your CSS.

4. In your custom CSS, you might use Flexbox or CSS Grid properties to achieve the desired layout. For example, you could set the `flex` property for the middle column to a higher value compared to the side columns.

Here is an example of what your custom CSS might look like:

```css
/* Assuming you have classes assigned to your columns in the YAML config */
.left-column {
  flex: 1; /* takes up less space */
}

.middle-column {
  flex: 3; /* takes up more space, adjust the ratio as needed */
}

.right-column {
  flex: 1; /* takes up less space */
}

/* Ensure the container for the columns uses display: flex */
.columns-container {
  display: flex;
}
```

Please note that the actual class names and the structure of your HTML will affect how you write your CSS. The example above is a general guide and will need to be adjusted to fit your specific setup.

Remember to test your layout on different screen sizes to ensure responsiveness and to adjust the CSS as necessary.

If you are not familiar with CSS, you might consider reaching out to the Homepage community for specific guidance or examples of similar customizations. Keep in mind that any custom CSS you add will need to be maintained separately and could be affected by updates to the Homepage dashboard.

Unfortunately, the image link you provided does not work, so I cannot see the exact layout you are referencing. If you need further assistance with the CSS or have more specific requirements, please provide additional details or a working image link.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
