### DISCUSSION TITLE
[Feature Request] teslamate widget

### DISCUSSION THREAD

**Discussion by a406877521** [gethomepage/homepage#3375] [Feature Requests]
### Description

Testamate is a car data recorder that I hope can display the current status of the car.
https://github.com/teslamate-org/teslamate

But I couldn't find the API for testamate itself, so I need to use another open-source program, testamate API
https://github.com/tobiasehlert/teslamateapi

api：wake up;status;drives;logging

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To display the current status of your car using Teslamate and Teslamate API, you will need to set up both Teslamate and Teslamate API. Teslamate is the data recorder that logs data from your Tesla vehicle, and Teslamate API provides a RESTful interface to access this data.

Here are the general steps you would need to follow:

1. Install and set up Teslamate following the instructions provided in the Teslamate documentation: https://docs.teslamate.org/docs/installation/docker

2. Once Teslamate is up and running, install and configure Teslamate API by following the instructions on the Teslamate API GitHub repository: https://github.com/tobiasehlert/teslamateapi

3. After setting up Teslamate API, you can use the provided endpoints to access data such as wake up, status, drives, and logging. The API endpoints will look something like this (replace `your-teslamateapi-host` with the actual host where Teslamate API is running):

   - Wake up: `http://your-teslamateapi-host/api/car/wake_up`
   - Status: `http://your-teslamateapi-host/api/car/status`
   - Drives: `http://your-teslamateapi-host/api/car/drives`
   - Logging: `http://your-teslamateapi-host/api/car/logging`

4. You can make HTTP GET requests to these endpoints to retrieve the data you need. Depending on your requirements, you may need to authenticate your requests using an API key or other authentication methods as specified in the Teslamate API documentation.

Please note that the exact API endpoints and how to use them will be detailed in the Teslamate API documentation. Make sure to review the documentation for any specific requirements or configurations needed to access the data from your Tesla vehicle.

If you need to integrate this data into a custom widget or application, you may need to write additional code to handle the API requests and display the data accordingly.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by ederstef** [comment]
here is my custom widget. hope it helps
    - Teslamate:
        icon: teslamate.png
        href: http://your.ip.adress:4000
        server: my-docker
        container: teslamate
        widget:
          type: customapi
          url: http://your.ip.adress:8080/api/v1/cars/1/status
          refreshInterval: 60000 # 1min. - in milliseconds, defaults to 10s
          method: GET # optional, e.g. POST
          headers:
            Content-Type: application/json
            x-authorization: Bearer your-super-secret-API_TOKEN-for-authorization #must be the same as API_TOKEN
            requestBody: # optional, can be string or object, see below
          display: # optional, default to block, list
          mappings:
            - field: #success # needs to be YAML string or object
                data:
                  status: odometer
              label: KM-Stand
              format: number # optional - defaults to text
              suffix: km
            - field: #success # needs to be YAML string or object
                data:
                    status:
                      climate_details: inside_temp
              label: Temperatur
              format: number # optional - defaults to text
              suffix: °C
            - field: #success # needs to be YAML string or object
                data:
                    status:
                      battery_details: battery_level
              label: Akkustand
              format: percent # optional - defaults to text
            - field: #success # needs to be YAML string or object
                data:
                    status:
                      battery_details: est_battery_range
              label: Reichweite
              format: number # optional - defaults to text
              suffix: km
![teslamatewidget](https://github.com/gethomepage/homepage/assets/129668117/85beddc0-b8e5-4b9c-97e6-3a372d8df9e8)

**Reply by dnielso5** [reply]
Having an issue, this is what i get:

![image](https://github.com/gethomepage/homepage/assets/107376351/39f7fb1b-6867-421c-8554-7a76c2854207)

![image](https://github.com/gethomepage/homepage/assets/107376351/00b88fe7-c1c2-4e35-933d-1da3691026e1)

**Reply by dnielso5** [reply]
Indenting is hard. got it fixed:

         - field: #success # needs to be YAML string or object
             data:
               status: odometer

**Comment by rkmd** [comment]
Been trying to follow the thread and still can only see the "NaN" output for any field.

    - TeslaMate:
        icon: teslamate
        href: <URL>
        server: my-docker
        container: TeslaMate
        widget:
          type: customapi
          url: http://<my-IP-address>:8080/api/v1/cars/1/status
          refreshInterval: 10000
          method: GET
          headers:
            x-authorization: Bearer <token I put into the TeslaMateAPI docker container's environmental variable>
          mappings:
            - field: odometer
              data:
                status: odometer
              label: Mi-LR
              format: number
              
When I refresh homepage, it just shows "NaN" with "Mi-LR" below it. If I try to indent the "data" entry below the "field" entry (similar to how @dnielso5 has with their fix), I get an error saying bed indentation of a mapping entry.

Any thoughts?

**Reply by ederstef** [reply]
Hi, you have to make the right indentation
   
        mappings:
            - field:
                data:
                  status: odometer
              label: Mi-LR
              format: number
![Indentation](https://github.com/gethomepage/homepage/assets/129668117/bcb4856f-191c-46e1-955f-7b518cdedcc2)

**Reply by rkmd** [reply]
I honestly thought I tried every combination of indentation before posting, but your solution did the trick! Thank you so much!

**Comment by pochacho99** [comment]
Thank you all for the guidance! I got mine to work. Is there any way to get more than 4 fields in a widget? Also, where can i find a list of all Teslamate fields i can pull from?

**Reply by ederstef** [reply]
Hi, 
yes you can list the widget with  **display: list # optional, default to block**   / same indentation as mappings .
![list-widget](https://github.com/gethomepage/homepage/assets/129668117/c1c8a735-85e4-4310-97f6-7e98178244a5)
![display-list](https://github.com/gethomepage/homepage/assets/129668117/ed60828f-45e0-4e24-be30-0c9e315a1af5)

all endpoints ar descipde at https://github.com/tobiasehlert/teslamateapi
i use the endpoint **http://your.ip.adress:8080/api/v1/cars/1/status**  go to the site and pick your mappings
![endpoint](https://github.com/gethomepage/homepage/assets/129668117/883d9f90-de1a-4ae5-9b27-148e8a2aedeb)

**Reply by pochacho99** [reply]
Thank you so much, it's working great!

**Comment by ekalp** [comment]
Here is mine, thank you for the pointers!
![image](https://github.com/gethomepage/homepage/assets/109757692/569ccb56-66ea-4251-92e0-5dd55f25118e)


```
- Tesla:
    - Teslamate:
        icon: teslamate.png
        href: http://<IPAddress>:4000
        server: servername
        container: teslamate-teslamate-1
        widget:
          type: customapi
          url: http://<IPAddress>:4001/api/v1/cars/1/status
          refreshInterval: 60000 # 1min. - in milliseconds, defaults to 10s
          method: GET # optional, e.g. POST
          headers:
            x-authorization: <snip> #must be the same as API_TOKEN
          mappings:
            - field: #success # needs to be YAML string or object
                data:
                  status: odometer
              label: Odometer
              format: number # optional - defaults to text
              suffix: mi
            - field: #success # needs to be YAML string or object
                data:
                  status:
                    climate_details: inside_temp
              label: Inside
              format: number # optional - defaults to text
              suffix: °F
            - field: #success # needs to be YAML string or object
                data:
                  status:
                    battery_details: battery_level
              label: Charge
              format: percent # optional - defaults to text
            - field: #success # needs to be YAML string or object
               data:
                  status:
                    battery_details: est_battery_range
              label: Range
              format: number # optional - defaults to text
              suffix: mi
```
