### DISCUSSION TITLE
[Feature Request] Value translation for Binary sensors from Home Assistant

### DISCUSSION THREAD

**Discussion by mploetner** [gethomepage/homepage#3376] [Feature Requests]
### Description

I did not find if or how its possible but if not I would like to see a way to translate the value of HA binary sensor from on/off to e.g. open/closed in case its a window or something different. The setting from HA seems to be ignored

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To translate the value of a Home Assistant binary sensor from "on/off" to "open/closed" or any other custom values within the Homepage widget configuration, you can use the `remap` feature. This feature allows you to define custom mappings for the values returned by your Home Assistant binary sensors.

Here's an example of how you might configure the widget to remap the binary sensor state:

```yaml
widget:
  type: homeassistant
  url: http://homeassistant.host.or.ip:port
  key: access_token
  custom:
    - state: binary_sensor.window_sensor
      label: Window
      value: "{state}"
      remap:
        - value: "on"
          to: "Open"
        - value: "off"
          to: "Closed"
```

In this example, the `remap` section within the `custom` configuration is used to translate the "on" state to "Open" and the "off" state to "Closed". You can adjust the `entity_id` and the `to` values to match your specific Home Assistant binary sensor and desired translations.

Please note that the `remap` feature is not explicitly documented in the provided context, but it is a common feature in similar configurations, as seen in the discussion about custom API mappings (source: https://github.com/gethomepage/homepage/discussions/3166). If this feature is not currently supported by the Homepage Home Assistant widget, you may need to request it as a new feature or contribute to the project to add this functionality.

If you need further assistance or clarification, please let me know!

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
