### DISCUSSION TITLE
Quick Launch no longer works.

### DISCUSSION THREAD

**Discussion by pasqualowitsch** [gethomepage/homepage#3379] [Support] [answered]
### Description

Hello, I have finished configuring my homepage. After I was done, I noticed that Quicklaunch no longer worked as it should. The following error message occurs when I try to search for something via Quicklaunch:

![txgpIjSeAn](https://github.com/gethomepage/homepage/assets/77759729/113f812a-b20d-4e28-b37c-1405dabd0050)

![brave_JGsU2pHpv3](https://github.com/gethomepage/homepage/assets/77759729/1c69d2a4-c0f3-41c1-960e-fe9f8041449b)

Thanks for any Help.

### homepage version

latest

### Installation method

Docker

### Troubleshooting

1. Checked YAML-Files.
2. Rebuild Container. 
3. Docker Prune.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To assist you with the Quicklaunch issue you're experiencing, I would need to see the actual error message that is being displayed when you attempt to use the Quicklaunch feature. The images you've referenced in your message do not appear to be accessible, as they are not displaying correctly. Could you please provide the text of the error message or ensure that the links to the images are correct?

Additionally, it would be helpful to know if you've made any recent changes to your `settings.yaml` file or any other configuration files that might have affected the Quicklaunch functionality. If you have a backup of your configuration before the issue started, you might want to compare it with your current configuration to identify any discrepancies.

In the meantime, please ensure that you have followed the general troubleshooting steps provided in the documentation:

- Check the browser error console for any errors that might indicate what is going wrong.
- Review the `homepage.log` file for any relevant error messages or warnings.
- If you have set the `ENV` variable `LOG_LEVEL` to `debug`, check the debug logs for more detailed information.

If you have already tried these steps, please provide any output or findings that could help diagnose the issue further.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by shamoon** [comment]
You havent really provided enough information to investigate this, but nothing has changed here for a while. Did you leave a name off of one of your services or bookmarks?

**Reply by pasqualowitsch** [reply]
e.g. Bookmarks: 

```
- Entertainment:
    - Twitch: 
        - abbr: TTV
          icon: twitch.png
          href: https://twitch.tv/
          description: false
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://youtube.com/
          description: false
```
e.g. Services:
```
    - FRITZ!Box:
        href: http://xxx/
        description: Dect-Station
        icon: avmfritzbox.png
        ping: xxx
        statusStyle: 'dot'
        widget:
          type: fritzbox
          url: xxx
          fields: ["maxDown", "maxUp"]
```
Settings:
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

headerStyle: boxedWidgets

language: en
theme: dark
color: zinc

layout:
  Home Automation:
    tab: Home
  Entertainment:
    tab: Home
  Social:
    tab: Home
  Developer:
    tab: Home
  Network:
    tab: Home
    style: row
    columns: 3
  Placeholder:
    tab: Home
    style: row
    columns: 1
    header: false
  Hypervisor:
    tab: Home
    style: row
    columns: 1
  VMs:
    tab: Home
  Services:
    tab: Home
    style: row
    columns: 2
  Container:
    tab: Home
    style: row
    columns: 5
  Documentations:
    tab: Bookmarks
    style: row
    columns: 4
    initiallyCollapsed: true
  Forums:
    tab: Bookmarks
    style: row
    columns: 4
    initiallyCollapsed: true
  Shops:
   tab: Bookmarks
   style: row
   columns: 4
   initiallyCollapsed: true
  Onlinebanking:
    tab: Bookmarks
    style: row
    columns: 2
    initiallyCollapsed: true

useEqualHeights: false
disableCollapse: false

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false

hideVersion: true
hideErrors: false
```
