### DISCUSSION TITLE
Add Icon in Tabs

### DISCUSSION THREAD

**Discussion by Nickous** [gethomepage/homepage#3380] [Feature Requests]
Hello Folks :)
I like the Tabs management.
I would like to display an icon + text in the tab header, as it is possible on a Service or Group.
I tried added a icon line under the "tab" option, but without success.

Let's try with a Docker tab, SmartHome Tab, HomeServer tab:
```
layout:
  System:
    tab: Docker
    style: row
    columns: 4
  SmartHome:
    tab: SmartHome
    icon: home-assistant.png
  HomeServer:
    tab: HomeServer
    icon: mdi-home
```
![image](https://github.com/gethomepage/homepage/assets/10545977/890d5398-4fb1-4b59-90fd-96456ee394ad)
But SmartHome and HomeServer tabs don't display any icon?!

I would appreciate any help on that.
Thanks
