### DISCUSSION TITLE
piHole Widget is working without API-Key

### DISCUSSION THREAD

**Discussion by OberfragGER** [gethomepage/homepage#3388] [Support] [answered]
### Description

I set up 3 diffent pihole. Each has the admin password activated.
So i want to show the different stats.

But i always get the same stats, even if i uncomment the lines...
Thats odd!

I already restarted the stack.

![image](https://github.com/gethomepage/homepage/assets/28652993/1f7b0fd1-823a-4a11-838e-69deed2e41a4)

### homepage version

0.812

### Installation method

Docker

### Configuration

```yaml
- piHole:
        icon: pi-hole.png
        href: http://192.168.178.10/admin/index.php
        description: LXC-Container
        siteMonitor: http://192.168.178.10
        statusStyle: dot
        widget:
          type: pihole
          url: http://192.168.178.10
          key: apikey

    - piHole:
        icon: pi-hole.png
        href: http://192.168.178.114/admin/index.php
        description: Alpine-Linux
        siteMonitor: http://192.168.178.114
        statusStyle: dot
        widget:
          type: pihole
#          url: no url
#          key: no apikey
          
    - piHole:
        icon: pi-hole.png
        href: http://192.168.178.100/admin/index.php
        description: Raspi4
        siteMonitor: http://192.168.178.100
        statusStyle: dot
        widget:
          type: pihole
          url: http://192.168.178.100
          key: apikey
```

### Troubleshooting

root@pihole:~# curl -L -k http://192.168.178.10/admin/api.php
[]root@pihole:~#

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the context from the sources, it seems that you are experiencing an issue where all your Pi-hole widgets on the Homepage dashboard are showing the same statistics, despite being set up for different Pi-hole instances.

The first thing to check is that each Pi-hole widget configuration in your `services.yaml` file has a unique `url` and `key` (API key). Since you have admin passwords set on your Pi-hole instances, each one should have a unique API key. You've mentioned that some lines are commented out, which could be part of the issue. Ensure that each Pi-hole instance has both the `url` and `key` fields correctly set and uncommented.

Here's an example of what each widget configuration should look like:

```yaml
- piHole:
    icon: pi-hole.png
    href: http://192.168.178.10/admin/index.php
    description: LXC-Container
    siteMonitor: http://192.168.178.10
    statusStyle: dot
    widget:
      type: pihole
      url: http://192.168.178.10
      key: uniqueapikey1

- piHole:
    icon: pi-hole.png
    href: http://192.168.178.114/admin/index.php
    description: Alpine-Linux
    siteMonitor: http://192.168.178.114
    statusStyle: dot
    widget:
      type: pihole
      url: http://192.168.178.114
      key: uniqueapikey2

- piHole:
    icon: pi-hole.png
    href: http://192.168.178.100/admin/index.php
    description: Raspi4
    siteMonitor: http://192.168.178.100
    statusStyle: dot
    widget:
      type: pihole
      url: http://192.168.178.100
      key: uniqueapikey3
```

Make sure that each `apikey` is the correct one for the corresponding Pi-hole instance.

After making these changes, you should restart your Homepage stack to ensure the new configuration is loaded.

If you continue to experience issues, you can use `curl` to manually check the API response from each Pi-hole instance as you did in your troubleshooting step. If the `curl` command returns an empty array `[]`, it could indicate a problem with the API or the way the API key is being used.

If you need further assistance, please provide the exact error message or behavior you're observing, and ensure that the API keys are indeed different for each instance.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
