### DISCUSSION TITLE
Hide the scroll bar on mobile

### DISCUSSION THREAD

**Discussion by asukasu** [gethomepage/homepage#3390] [Support]
### Description

I want to hide the right scroll bar,I've looked through the docs and discussions, but I can't seem to find anything helpful. If somebody could let me know how to do this or if such a feature doesn't exist, that would be great.

### homepage version

v0.8.3

### Installation method

Docker

### Troubleshooting

![Screenshot_2024-04-30-19-11-06-057_com android chrome](https://github.com/gethomepage/homepage/assets/34979476/404bae40-008e-4c35-9e51-cbce9a690912)

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To hide the right scrollbar on your Homepage application, you can use custom CSS. Since Homepage supports adding your own custom CSS starting from version v0.6.30, you can add the necessary styles to hide the scrollbar.

Here's a general example of how you can hide the scrollbar using CSS:

```css
/* Hide scrollbar for Chrome, Safari and Opera */
body::-webkit-scrollbar {
    display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
body {
    -ms-overflow-style: none;  /* IE and Edge */
    scrollbar-width: none;  /* Firefox */
}
```

You would need to add this CSS to the `custom.css` file under your config directory. Please note that hiding the scrollbar can affect the user experience, especially if the content overflows the viewport height.

Remember to test your changes to ensure that it behaves as expected across different browsers and does not negatively impact the usability of your application.

If you need further assistance or if this solution does not work for your specific setup, please provide more details about your configuration or any customizations you have made to the Homepage application.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
