### DISCUSSION TITLE
Using Environment Secrets on docker

### DISCUSSION THREAD

**Discussion by Vctrsnts** [gethomepage/homepage#3403] [Support]
### Description

Hello good.
I have my homepage working like a charm (thanks for all the work you do), but when it comes to using the `.env` file (Using Environment Secrets) I find that in Jellyfin, Traefik, Caliber-web, etc.
When I want to pass the jellyfin key I use:
 - With Jellyfin use `HOMEPAGE_VAR_JELLYFIN` --> which I then use `{{HOMEPAGE_VAR_JELLYFIN}}`
 - With Calibre-Web use `HOMEPAGE_VAR_CALIBREUSER` --> which I then use `{{HOMEPAGE_VAR_CALIBREUSER}}`

Does anyone know where the problem could be? I mention this because I have been searching for information and many people say that it is because I do not have the `.env` file defined in docker-compose. This is why? I mention this, because I am in unRaid, and sometimes it is a little difficult to modify the templates that come by default (I have already added the `env_file` variable to test, but it has been of no use)

Thank you

### homepage version

v0.8.12 (12ec1cf, Apr 17, 2024)

### Installation method

Docker

### Configuration

```yaml
In the .env file I have it as follows:

HOMEPAGE_VAR_CALIBREUSER=user
HOMEPAGE_VAR_JELLYFIN=key
HOMEPAGE_VAR_TRAEFIKUSR=user

In the services.yaml:

Jellyfin:
  icon: jellyfin.png
  href: http://IP:PORT
  description: Servidor Multimedia
  ping: http://IP:PORT
    widget:
      type: jellyfin
      url: http://IP:PORT
      key: THE KEY ( work with key ) OR {{HOMEPAGE_VAR_JELLYFIN}} ( not work with variable )
      enableBlocks: true
      enableNowPlaying: false
      fields: ["movies", "series", "episodes"]
```

### Troubleshooting

With variable, I see no correct key with direct key work perfect

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that the environment variables from the `.env` file are not being correctly passed to the homepage container. This can happen if the `env_file` directive in the Docker Compose file is not correctly specified or if the `.env` file is not in the correct location.

Since you are using UNRAID, which can sometimes make it difficult to modify default templates, you should ensure that the `env_file` directive is correctly pointing to your `.env` file. The `.env` file should be in the same directory as your `docker-compose.yml` file, or you should specify the correct path to it in the `env_file` directive.

Here are some steps you can take to troubleshoot this issue:

1. Ensure that the `.env` file is in the same directory as your `docker-compose.yml` file.
2. Verify that the `env_file` directive in your `docker-compose.yml` file is correctly formatted. It should look like this:
   ```yaml
   version: "3.3"
   services:
     homepage:
       image: ghcr.io/gethomepage/homepage:latest
       container_name: homepage
       ports:
         - "8921:3000"
       volumes:
         - ./config:/app/config
         - ./images:/app/public/images
         - /var/run/docker.sock:/var/run/docker.sock:ro
       restart: unless-stopped
       env_file:
         - .env
   ```
3. Check that the environment variables are correctly named in the `.env` file and that they follow the required format (`HOMEPAGE_VAR_` prefix).
4. After making changes, remember to restart the Docker container to apply the new configuration.
5. If you have access to the command line, you can also enter the running container and check if the environment variables are set correctly using the following command:
   ```bash
   docker exec -it homepage env
   ```
   This will list all the environment variables available in the container, and you should see your `HOMEPAGE_VAR_` variables listed there.

If you have followed these steps and the issue persists, please provide the exact error message or behavior you are encountering, and ensure that there are no typos or syntax errors in your `.env` file or `docker-compose.yml` file.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
