### DISCUSSION TITLE
CustomAPI - F1 Widget

### DISCUSSION THREAD

**Discussion by nubbeldupp** [gethomepage/homepage#3412] [Support] [answered]
### Description

I'm trying to build a Formula 1 Widget using the CustomAPI.
I found a Website that provides the Data in a JSON Format.

e.g. [https://api.openf1.org/v1/meetings?meeting_key=latest](url)

Somehow nothing show up when I open Homepage

<img width="663" alt="Screenshot 2024-05-04 at 14 18 24" src="https://github.com/gethomepage/homepage/assets/2195212/a0f6be7e-9543-4e50-8a50-7730f1e8a8bb">

I'm a bit at a loss on what's going on. 

### homepage version

v0.8.12 (12ec1cf, Apr 17, 2024)

### Installation method

Docker

### Configuration

```yaml
- Formula 1:
  - F1 Race:
    widget:
      type: customapi
      url: https://api.openf1.org/v1/meetings?meeting_key=latest
      method: GET
      mappings:
        - field: meeting_name
          label: Current Race
        - field: meeting_code
          label: Country
        - field: year
          label: Year
  - F1 Pit:
    widget: 
      type: customapi
      url: https://api.openf1.org/v1/pit?session_key=latest
      refreshInterval: 1000
      method: GET
      mappings:
        - field: driver_number
          format: text
          label: DriverNo
        - field: lap_number
          format: text
          label: Lap
        - field: pit_duration
          format: text
          label: Pit-Time
```

### Troubleshooting

I tried the 0: for the array with the same result

`- Formula 1:
  - F1 Race:
    widget:
      type: customapi
      url: https://api.openf1.org/v1/meetings?meeting_key=latest
      method: GET
      mappings:
        - field: 
          0:
            meeting_name
          label: Current Race
        - field: 
          0:
            meeting_code
          label: Country
        - field: 
          0:
            year
          label: Year`
