### DISCUSSION TITLE
Proxmox backup server - API Error: Unexpected token 'a', "authentica"... is not valid JSON

### DISCUSSION THREAD

**Discussion by oswaldo-be** [gethomepage/homepage#3417] [Support]
### Description

I am trying to add the PBS widget to homepage. But the error persists.

### homepage version

0.8.12

### Installation method

Docker

### Configuration

```yaml
Proxmox backup server:
        icon: proxmox-light.png
        href: internal
        ping: internal
		widget:
          type: proxmoxbackupserver
          url: internal
          username: removed
		  
          password: removed
```

### Container Logs

API Error: Unexpected token 'a', "authentica"... is not valid JSON

### Troubleshooting

none
