### DISCUSSION TITLE
[Feature Request] Network usage statistics (Upload, Download)

### DISCUSSION THREAD

**Discussion by ramazansancar** [gethomepage/homepage#3421] [Feature Requests] [answered]
### Description

A feature that gives information about the total internet bandwidth used by the device would be nice. Maybe instant upload and download speeds can also be added here.

Feature PR: https://github.com/gethomepage/homepage/pull/3420

Example Screenshot:
![image](https://github.com/gethomepage/homepage/assets/8878055/4480f2de-2ad5-49f8-aeed-cd8c103cf1c5)
![image](https://github.com/gethomepage/homepage/assets/8878055/808a1838-77d3-40a4-85e0-9d62f94d6af1)
![image](https://github.com/gethomepage/homepage/assets/8878055/fd649fa5-8799-4068-b9bf-81169b1123d4)
![image](https://github.com/gethomepage/homepage/assets/8878055/b0f8012d-1a92-41e7-99bd-5143cc824e29)
![image](https://github.com/gethomepage/homepage/assets/8878055/d7d4e98d-1437-41be-9e50-bd9bc63b0d4c)
![image](https://github.com/gethomepage/homepage/assets/8878055/65782ac3-28c9-4295-8796-b043bafeacc6)

**Comment by ramazansancar** [comment]
Up :)

**Reply by shamoon** [reply]
Please don’t leave comments like this, it’s spammy. Just up-vote things. Comments should actually add to a conversation.

**Comment by ramazansancar** [comment]
@shamoon I just wanted to push for this feature to come. When I get new updates, this development will be overwritten. This is kind of annoying :(

**Reply by shamoon** [reply]
Bumping your own thread by spamming "+1" comments is also kind of "annoying" imho

**Comment by o2e** [comment]
I agree with this feature, and I think real-time internet speed information should also be added, like this (if I wrote it correctly)
```js
 if (type === "network") {
    const network = await si.networkStats();
    const eth = network.findLast((n) => n.iface === target);
    if (eth === undefined) {
      return res.status(404).json({
        error: "Target not found"
      });
    }
    return res.status(200).json({
      net: {
        rx: eth.rx_sec,
        tx: eth.tx_sec
      }
    });
  }
```

**Reply by ramazansancar** [reply]
@o2e The PR for the relevant development is already ready, you can test it by including it in the project if you want.

**Reply by o2e** [reply]
That's good, I know what you're doing. The PR seems to be rejected though, it looks like the dependency configuration was inadvertently updated `pnpm-lock.yaml` You could try removing the dependency changes and resubmitting.

The current commit only has traffic stats and lacks a real-time network speed display, which I was able to modify him and use on my own computer, which is fine.

**Reply by o2e** [reply]
I couldn't agree more with your work, you may need to fix the problem and then submit the code again for admin to review it again so that your work makes sense.

**Reply by ramazansancar** [reply]
@o2e The reason why PR is not approved and checked is because feature developments are decided after receiving at least 10 votes with the disc.

**Reply by o2e** [reply]
@ramazansancar I polled a few of my friends who use the homepage as often as I do, and they made it clear that they need this feature, and I suggested that they vote for it, but since most of them aren't developers, 2 of them have voted for it so far, which meets the 10-vote requirement. Finally, if you have the time, could you add a real-time speed display as well, I really like this feature, but since I'm not very proficient in the homepage project's development language, I was hoping you could help me out.

**Reply by ramazansancar** [reply]
@o2e Thanks for your support (you and your friends). I can make improvements regarding the instantaneous speed indicator and how many seconds it should check.

**Reply by ramazansancar** [reply]
Now when I check the code, it updates the data by making a request every 1500 ms. If you wish, you can update this period by editing the refresh data via widgets.yaml.

```yaml
# widgets.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /
    network: default # options: 'default' or active network interface name
    cputemp: true
    uptime: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    units: metric
    diskUnits: bytes
    expanded: true
    #refresh: 3000
```

```jsx
// resources.jsx
/* -- */
export default function Resources({ options }) {
  const { expanded, units, diskUnits, tempmin, tempmax } = options;
  let { refresh } = options;
  if (!refresh) refresh = 1500;
  refresh = Math.max(refresh, 1000);
  return (
    <Container options={options}>
```
