### DISCUSSION TITLE
Docker .env HOMEPAGE_VAR_XXX template variable substitution not working

### DISCUSSION THREAD

**Discussion by steve-king** [gethomepage/homepage#3422] [Support]
### Description

Sorry to post this, I realise this has been a recurring issue and a point of frustration. 

I have searched through all previous discussions on this topic and tried everything I can think of, but have not managed to find a solution.

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Configuration

compose.yaml:
```yaml

networks:
  homelab:
    name: homelab
    external: true
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      - homelab
    env_file:
      - .env
    environment:
      PUID: $PUID
      PGID: $PGID
    ports:
      - 8080:3000
    volumes:
      - ./config:/app/config 
      - ./images:/app/public/images
    deploy:
      restart_policy:
        condition: unless-stopped
  dockerproxy:
    container_name: dockerproxy
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    networks:
      - homelab
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
```

.env
```
PUID=1000
PGID=1000

# ---
HOMEPAGE_VAR_EMAIL=XXX
HOMEPAGE_VAR_USERNAME=XXX
HOMEPAGE_VAR_PASSWORD=XXX
HOMEPAGE_VAR_PORTAINER_TOKEN=XXX

```

services.yaml:
```
- Services:
    - Nginx:
        href: http://nginxproxy.homelab.lan
        description: Nginx Proxy Manager
        icon: nginx-proxy-manager
        server: homelab
        container: nginxproxy
        statusStyle: "dot"
        widget:
            type: npm
            url: http://nginxproxy:81
            # username: XXX
            # password: XXX
            username: {{ HOMEPAGE_VAR_EMAIL }}
            password: {{ HOMEPAGE_VAR_PASSWORD }}
    - Adguard Home:
        href: http://adguard.homelab.lan
        description: DNS server
        icon: adguard-home
        server: homelab
        container: adguard
        statusStyle: "dot"
        widget:
            type: adguard
            url: http://adguard:3000
            # username: XXX
            # password: XXX
            username: {{ HOMEPAGE_VAR_USERNAME }}
            password: {{ HOMEPAGE_VAR_PASSWORD }}
    - Portainer:
        href: http://portainer.homelab.lan
        description: Container management
        icon: portainer
        server: homelab
        container: portainer
        statusStyle: "dot"
        widget:
            type: portainer
            url: http://portainer:9000
            env: 14
            key: {{ HOMEPAGE_VAR_PORTAINER_TOKEN }}
            # key: XXX
```
### Container Logs
```
[2024-05-07T11:32:04.901Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://portainer:9000/api/endpoints/14/docker/containers/json?all=1
[2024-05-07T11:32:05.325Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://portainer:9000/api/endpoints/14/docker/containers/json?all=1
[2024-05-07T11:32:09.450Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://portainer:9000/api/endpoints/14/docker/containers/json?all=1
```
 All environment variables are present when running `docker exec homepage env`:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=905adec29027
HOMEPAGE_VAR_USERNAME=XXX
HOMEPAGE_VAR_PASSWORD=XXX
HOMEPAGE_VAR_PORTAINER_TOKEN=XXX
PUID=1000
PGID=1000
HOMEPAGE_VAR_EMAIL=XXX
NODE_VERSION=18.20.2
YARN_VERSION=1.22.19
NODE_ENV=production
PORT=3000
HOME=/root
```

### Browser Logs
```
index-13ff1c2d6f3e37ec.js:1 
GET http://homelab.lan/api/services/proxy?type=npm&group=Services&service=Nginx&endpoint=nginx%2Fproxy-hosts 400 (Bad Request)
fetcher @ index-13ff1c2d6f3e37ec.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
o @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
A @ _app-b877b7641e51de94.js:1
index-13ff1c2d6f3e37ec.js:1 
GET http://homelab.lan/api/services/proxy?type=adguard&group=Services&service=Adguard+Home&endpoint=stats 403 (Forbidden)
fetcher @ index-13ff1c2d6f3e37ec.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
o @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
(anonymous) @ _app-b877b7641e51de94.js:1
A @ _app-b877b7641e51de94.js:1
index-13ff1c2d6f3e37ec.js:1 
GET http://homelab.lan/api/services/proxy?type=portainer&group=Services&service=Portainer&endpoint=docker%2Fcontainers%2Fjson&query=%7B%22all%22%3A1%7D 401 (Unauthorized)
```
### Troubleshooting

When I swap out the `{{HOMEPAGE_VAR_XXX}}` variables and input strings directly (as per commented lines in `services.yaml`), everything works correctly.

I have tried: 
- completely removing the container
- pulling a fresh image
- Running  `docker compose up --build --force-recreate`

However the problem still occurs.
