### DISCUSSION TITLE
Omada Issue

### DISCUSSION THREAD

**Discussion by ryaneford** [gethomepage/homepage#3424] [Support]
### Description

Hi there, I added my omada controller info but it's giving the following error.

`API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- Omada:
        icon: omada.png
        href: http://192.168.0.11
        description: Omada Controller
        widget:
            type: omada
            url: http://192.168.0.11
            username: REDACTED
            password: REDACTED
            site: Turntable
            fields: ["connectedSwitches", "connectedAp",  "activeUser", "alerts"]
```

### Container Logs

[2024-05-07T22:57:54.052Z] error: <httpProxy> Error calling http://192.168.0.11/fb6be238b74fc2aa4c40a7b44f7d5ea2/api/v2/login...
[2024-05-07T22:57:54.054Z] error: undefined
[2024-05-07T22:57:54.053Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]

### Troubleshooting

tried adding http/https
