### DISCUSSION TITLE
Settings not being reflected

### DISCUSSION THREAD

**Discussion by kanjieater** [gethomepage/homepage#3425] [Support] [answered]
### Description

I can't get the settings to read from my local png in images. In addition, I can't get auto discovery my docker containers to be discovered.
Similar to the unresolved discussion here:
https://github.com/gethomepage/homepage/discussions/3049
![4Be7mhe8UQ](https://github.com/gethomepage/homepage/assets/32607317/78e40902-ca9b-48ad-af90-2b9e6c2c0d9e)

### homepage version

v0.8.13 (986a181

### Installation method

Docker

### Configuration

```yaml


./config/compose.yml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # environment:
    #   PUID: 1000 -- optional, your user id
    #   PGID: 1000 -- optional, your group id
    ports:
      - 7000:3000
    volumes:
      - /home/ke/srv/homepage/images:/images
      - /home/ke/srv/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```
./config/my-docker.yml
```
my-docker:
  socket: /var/run/docker.sock
```

./config/settings.yml
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

# title: My Awesome Homepage
# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey

background:
  image: /images/crt.png
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
  cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur
# favicon: https://www.google.com/favicon.ico



layout:
  - Auto-Discovered1:
#   - Configured1:
#   - Configured2:
#   - Auto-Discovered2:
#   - Configured3:
#       style: row
#       columns: 3
```

audiobookshelf/compose.yml
```
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/a/MusicBee/Audiobooks:/audiobooks
      - /mnt/a/MusicBee/podcasts:/podcasts
      - /home/ke/srv/audiobookshelf:/config
      - /home/ke/srv/audiobookshelf:/metadata
    environment:
      - TZ=Etc/UTC
    labels:
      - homepage.group=Media
      - homepage.name=AudiobookShelf
      - homepage.href=https://github.com/advplyr/audiobookshelf/releases
      - homepage.description=Media server
```
```


### Container Logs

2024-05-07 20:45:12 Listening on port 3000
2024-05-07 20:45:21 settings.yaml was copied to the config folder
2024-05-07 20:45:21 [2024-05-08T01:45:21.745Z] info: docker.yaml was copied to the config folder
2024-05-07 20:45:21 [2024-05-08T01:45:21.748Z] info: services.yaml was copied to the config folder
2024-05-07 20:45:21 [2024-05-08T01:45:21.748Z] info: bookmarks.yaml was copied to the config folder
2024-05-07 20:45:21 [2024-05-08T01:45:21.752Z] info: widgets.yaml was copied to the config folder
2024-05-07 20:45:21 [2024-05-08T01:45:21.752Z] info: custom.css was copied to the config folder
2024-05-07 20:45:21 [2024-05-08T01:45:21.752Z] info: custom.js was copied to the config folder
2024-05-07 20:45:21 [2024-05-08T01:45:21.807Z] info: kubernetes.yaml was copied to the config folder
2024-05-07 20:47:18 Listening on port 3000


### Browser Logs

_No response_

### Troubleshooting

➜ docker exec homepage ping 7000             
PING 7000 (0.0.27.88): 56 data bytes
