### DISCUSSION TITLE
Traefik not working as service widget

### DISCUSSION THREAD

**Discussion by chachew** [gethomepage/homepage#3428] [Support]
### Description

I am trying to add the Traefik service widget to the dashboard and ive had no luck over the last couple days.

I have a raspberry pi 5 running raspbian. It runs docker and all my containers(PiHole, Portainer, Traefik, Homepage).
PiHole is acting as the DNS server with its local DNS of raspberrypi.local.example.live pointing back to itself at 192.168.1.20

I can get dashboard to connect successfully to the PiHole widget, and the Portainer widget, but ive had zero luck connecting the Traefik widget to dashboard. Its probably the reverse https proxy thats causing the issue but i have no ide how to fix this. All containers are on the same network called 'proxy' and all internal docker IPs are in the same network.

So with PiHole and Portainer, i can connect just fine with the internal docker ip address, but that doesnt work with traefik.

If i test the url in the browser with the resolved DNS name of 'https://traefik-dashboard.local.example.live/api/overview' this works as expected. But this cannot be accessed inside the container. Accessing 'http://172.19.0.2:8080/api/overview' within dashboard throws errors in the dashboard as well as the dashboard container logs.

### homepage version

v0.8.13 (986a181, May 5, 2024)

### Installation method

Docker

### Configuration

```yaml
traefik docker-compose.yml

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 8080:80
      - 443:443/tcp
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.local.example.live`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.local.example.live`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=local.example.live"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.example.live"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
```

dashboard docker-compose.yml
```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`homepage.local.example.live`)"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.local.example.live`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true
```

homepage config/services.yml
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- DNS:
    - PiHole:
        icon: pi-hole.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: http://raspberrypi.local.example.live/admin
        # description: PiHole Server
        widget:
            type: pihole
            url: http://172.19.0.5
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"

- Containers:
    - Portainer:
        icon: portainer.svg
        href: https://portainer.local.example.live
        # description: Portainer
        widget:
            type: portainer
            url: http://172.19.0.4:9000
            env: 2
            key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"

    - Traefik:
        icon: traefik.svg
        href: https://traefik-dashboard.local.example.live
        # description: Traefik
        widget:
            type: traefik
            url: http://172.19.0.2:8080
            username: "{{HOMEPAGE_VAR_TRAEFIK_USERNAME}}"
            password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"
```
```


### Container Logs

[2024-05-08T18:24:25.507Z] error: <httpProxy> Error calling http://172.19.0.2:8080/api/overview...
[2024-05-08T18:24:25.510Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.19.0.2:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.19.0.2',
    port: 8080
  }
]

### Browser Logs

API Error: HTTP Error
URL: http://172.19.0.2:8080/api/overview

### Troubleshooting

Ive tried to supply the dashboard widget every ip/name i can think of and nothing works for me.

- http://172.19.0.2:8080
- http://172.19.0.2:80
- http://172.19.0.2
- https://traefik-dashboard.local.example.live
- http://192.168.1.20:8080
- http://192.168.1.20:80
- http://192.168.1.20
- http://traefik:8080
- http://traefik:80
- http://traefik
