### DISCUSSION TITLE
Widget > Uptime Kuma: API Error: HTTP Error

### DISCUSSION THREAD

**Discussion by cmonty14** [gethomepage/homepage#3435] [Support]
### Description

I created widget "Uptime Kuma" in _services.yaml_ according to [documentation](https://gethomepage.dev/latest/widgets/services/uptime-kuma/).

However I get this error in _homepage_:
![image](https://github.com/gethomepage/homepage/assets/12523591/fde7296b-a61f-4b21-9bcb-0bf95866e5b4)

The error is pointing to an URL `URL: https://docker.example.com:3001/api/status-page/overview` that does not exist.
The URL should be: `https://docker.example.com:3001/status/overview`

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
- Monitoring and Observability:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://docker.example.com:3001/
        description: Uptime Monitoring
        widget:
          type: uptimekuma
          url: https://docker.example.com:3001
          slug: overview
```

### Troubleshooting

curl -L -k http://docker.example.com:3001/api/status-page/overview
{"config":{"slug":"overview","title":"overview","description":null,"icon":"/icon.svg","theme":"auto","published":true,"showTags":false,"customCSS":"body {\n  \n}\n","footerText":null,"showPoweredBy":true,"googleAnalyticsId":null,"showCertificateExpiry":false},"incident":null,"publicGroupList":[{"id":1,"name":"Services","weight":1,"monitorList":[{"id":11,"name":"LVA","sendUrl":0,"type":"group"},{"id":12,"name":"C11","sendUrl":0,"type":"group"}]}],"maintenanceList":[]}
