### DISCUSSION TITLE
Disks potentially recognized, but disk sizes not showing up in resources section

### DISCUSSION THREAD

**Discussion by rmatthiessen** [gethomepage/homepage#3445] [Support]
### Description

I'm trying to connect 3 known disk sizes to the resources section of widgets.yaml. I'm using OMV, but below shows the disks I want to add to resources:
![image](https://github.com/gethomepage/homepage/assets/54874929/42816b4d-a6c6-4744-8122-1fec0d022998)

This is the result, and I haven't been able to get any of my disks to recognize:
![image](https://github.com/gethomepage/homepage/assets/54874929/cfac5c88-36f9-4afb-8c3e-de54a4138b5d)

Configuration is below, but unless I'm mounting wrong due to a misunderstanding, I don't recognize how these disk sizes aren't being recognized.

docker-compose.yaml:
```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1003
      PGID: 100
    ports:
      - 3000:3000
    volumes:
      - /srv/dev-disk-by-uuid-df7d8fb0-65d3-4332-8d28-a546004b7f60/appdata/homepage:/app/config
      - /:/boot
      - /srv/dev-disk-by-uuid-df7d8fb0-65d3-4332-8d28-a546004b7f60:/docker
      - /srv/dev-disk-by-uuid-1df8843c-a5e7-47d0-b8cb-a14f14fd3111:/data
      #- /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
``` 

widgets.yaml:
```
- resources:
    label: BOOT
    expanded: true
    disk:
      - /boot

- resources:
    label: DOCKER
    expanded: true
    disk:
      - /docker

- resources:
    label: DATA
    expanded: true
    disk:
      - /data
``` 

### homepage version

v0.8.13

### Installation method

Docker

### Troubleshooting

- Deleted and remade container
- Tried different names for mount paths
- Am on latest version
- Restructured docker-compose.yaml and widgets.yaml many times

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that you are trying to monitor disk resources within the Homepage application running in a Docker container. The issue you are facing where the disks are not being recognized is likely due to incorrect volume mounts in your `docker-compose.yaml` file.

In your `docker-compose.yaml`, you have the following volume mounts:

```yaml
volumes:
  - /srv/dev-disk-by-uuid-df7d8fb0-65d3-4332-8d28-a546004b7f60/appdata/homepage:/app/config
  - /:/boot
  - /srv/dev-disk-by-uuid-df7d8fb0-65d3-4332-8d28-a546004b7f60:/docker
  - /srv/dev-disk-by-uuid-1df8843c-a5e7-47d0-b8cb-a14f14fd3111:/data
```

The issue here is that you are trying to mount the root directory (`/`) of the host to `/boot` inside the container, which is not correct. Instead, you should mount the actual boot partition (if that's what you want to monitor) to a directory inside the container, and then reference that directory in your `widgets.yaml`.

Here's how you can correct the volume mounts:

1. Identify the correct mount points for your disks on the host system.
2. Mount these disks to directories within the container.
3. Reference these directories in your `widgets.yaml`.

For example, if `/dev/sda1` is your boot partition, you would mount it like so (assuming `/dev/sda1` is mounted on `/boot` on the host):

```yaml
volumes:
  - /boot:/mnt/boot
  - /srv/dev-disk-by-uuid-df7d8fb0-65d3-4332-8d28-a546004b7f60:/mnt/docker
  - /srv/dev-disk-by-uuid-1df8843c-a5e7-47d0-b8cb-a14f14fd3111:/mnt/data
```

Then, in your `widgets.yaml`, you would reference the mount points as follows:

```yaml
- resources:
    label: BOOT
    expanded: true
    disk:
      - /mnt/boot

- resources:
    label: DOCKER
    expanded: true
    disk:
      - /mnt/docker

- resources:
    label: DATA
    expanded: true
    disk:
      - /mnt/data
```

Make sure that the paths you use in the `docker-compose.yaml` and `widgets.yaml` match and that the disks are properly mounted to the container.

Remember that any disk you wish to access must be mounted to your container as a volume, as mentioned in the documentation. If the disks are not properly mounted, the Homepage application will not be able to access them, resulting in the issues you are experiencing.

Please adjust your volume mounts accordingly and ensure that the paths used in the `widgets.yaml` are the paths to the volumes inside the container.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
