### DISCUSSION TITLE
Whats the problem? Pi-hole, Homepage or me/user error?

### DISCUSSION THREAD

**Discussion by Arelius-D** [gethomepage/homepage#3447] [Support]
### Description

Fresh install, first setup and I can't say I'm particularly impressed since it dose not work..

![image](https://github.com/gethomepage/homepage/assets/168124713/d15208c7-5d41-4f3a-a3ef-0744997e1450)

Also lets skip:
_Have you tried reentering the API Key?_ Yes, at least 20 times.
_Have you read all other posts here regarding the same issue?_ Yes many of them.
_Just run it as root!_ No I'll not.
_Give it docker.sock access then?_ No. But why? [Here](https://unix.stackexchange.com/questions/776276/lost-sudo-beyond-salvation) is why.

### homepage version

NODE_VERSION=18.20.2, YARN_VERSION=1.22.19

### Installation method

Docker

`cat $HOME/docker/homepage/docker-compose.yml`
``` 
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - ./:/app/config # Make sure your local config directory exists
#      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```

`cat $HOME/docker/homepage/services.yaml`
```
- Self-Hosted:
    - Pi-hole:
        icon: pi-hole.png
        href: http://10.0.0.10/admin
        ping: http://10.0.0.10/admin
        description: Network-wide Ad Blocking
        widget:
          type: pihole
          url: http://10.0.0.10
          key: NOT_GOING_TO_SHARE_THAT
```

`cat $HOME/docker/pi-hole/docker-compose.yml`
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#     - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Stockholm'
      WEBPASSWORD: 'NO_NOT_HAPPENING'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
#   cap_add:
#     - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
```
No I'm not running Pi-hole as a DHCP server for my network.

`cat $HOME/docker/homepage/docker.yaml`
```
my-docker:
   host: 10.0.0.10
   port: 2375

# my-docker:
#   socket: /var/run/docker.sock
```

`cat $HOME/docker/homepage/settings.yaml`
```
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
```

`cat $HOME/docker/homepage/widgets.yaml`
```
- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
```

`docker stats homepage`

```
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT   MEM %     NET I/O          BLOCK I/O     PIDS
8a6402b17d49   homepage   0.01%     0B / 0B             0.00%     1.48MB / 803kB   0B / 9.91MB   13
```

`docker compose logs homepage`
```
homepage  | Listening on port 3000
```

```
┌──[00:24:22]─[0]─[Pi5:~/docker/homepage]
└──| docker compose down
[+] Running 2/2
 ✔ Container homepage        Removed                                                                                                                 10.4s
 ✔ Network homepage_default  Removed                                                                                                                  0.3s
┌──[00:25:06]─[0]─[Pi5:~/docker/homepage]
└──| docker compose up
[+] Running 2/2
 ✔ Network homepage_default  Created                                                                                                                  0.1s
 ✔ Container homepage        Created                                                                                                                  0.1s
Attaching to homepage
homepage  | Listening on port 3000
^C
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container homepage  Stopped                                                                                                                       10.3s
canceled
┌──[00:32:02]─[0]─[Pi5:~/docker/homepage]
└──|
```

`docker inspect 89346706275f`
```
[
    {
        "Id": "sha256:89346706275f87ec761069af74623c2ff648c71da5f5e33f52f04768e413d4f7",
        "RepoTags": [
            "ghcr.io/gethomepage/homepage:latest"
        ],
        "RepoDigests": [
            "ghcr.io/gethomepage/homepage@sha256:43a3ee88abe3b37c64bc52ea93da01c3dcb4a332a953bcd7f438c8d7328d3947"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-05-06T05:20:17.487336468Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=18.20.2",
                "YARN_VERSION=1.22.19",
                "NODE_ENV=production",
                "PORT=3000"
            ],
            "Cmd": [
                "node",
                "server.js"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:$PORT/api/healthcheck || exit 1"
                ],
                "Interval": 10000000000,
                "Timeout": 3000000000,
                "StartPeriod": 20000000000
            },
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.created": "2024-05-06T04:39:02.032Z",
                "org.opencontainers.image.description": "A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations.",
                "org.opencontainers.image.documentation": "https://github.com/gethomepage/homepage/wiki",
                "org.opencontainers.image.licenses": "GPL-3.0",
                "org.opencontainers.image.revision": "986a18170c12f63c10264a666700973c84bf13a0",
                "org.opencontainers.image.source": "https://github.com/gethomepage/homepage",
                "org.opencontainers.image.title": "homepage",
                "org.opencontainers.image.url": "https://github.com/gethomepage/homepage",
                "org.opencontainers.image.version": "v0.8.13"
            }
        },
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 172373977,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/3b34d22865a0702e7c0ba1d0c45a31307fe489f33ecac042a494cd6864baa6da/diff:/var/lib/docker/overlay2/756252b3b9b66da49136974a4616311d01602d4aa0def79dde5bc665ff9e01b7/diff:/var/lib/docker/overlay2/69d24cc75c005b1eff1190f635a8ef2bbcb9de3900a158f8d8e1f428c717fc31/diff:/var/lib/docker/overlay2/03208249153ff9b4ebc31e3e93522830085fe80a72fcce3f51bf6ff3f46829c7/diff:/var/lib/docker/overlay2/c6aaa737dc336c9c5ab1f1207c657f70f2996571717a12a2e6e131a1f54dab45/diff:/var/lib/docker/overlay2/51cb87f4972669f1048f4818ab5f36924a4e8fc1fde22ecefb9d92fc7aa00baa/diff:/var/lib/docker/overlay2/3c66f991dad5266a05c4bbc8854f2a3df74502e2c2ec78b4c5ff2d395e6e5d31/diff:/var/lib/docker/overlay2/5e69c451e907c1e1829010f070da0179bf30438c874e214ba83944f3388d15e4/diff:/var/lib/docker/overlay2/14a5984ea4968fdfa7e9f40bba394cd018a8ae3ffcc5d5edd545ebb57319828c/diff:/var/lib/docker/overlay2/aa2657ac14b7b18fead226b0c2558298b8f08598c1abb09b208dc5cdccb44d11/diff",
                "MergedDir": "/var/lib/docker/overlay2/b36c2bd1ad50747340bb6281c6199a23ca52c8ccff3a99772b34bcfe76ef80fd/merged",
                "UpperDir": "/var/lib/docker/overlay2/b36c2bd1ad50747340bb6281c6199a23ca52c8ccff3a99772b34bcfe76ef80fd/diff",
                "WorkDir": "/var/lib/docker/overlay2/b36c2bd1ad50747340bb6281c6199a23ca52c8ccff3a99772b34bcfe76ef80fd/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:b09314aec293bcd9a8ee5e643539437b3846f9e5e55f79e282e5f67e3026de5e",
                "sha256:6724b338f31e05a34a70c96cea95a8a9297e23c68f784e4407ea1c848a807e1a",
                "sha256:a2ba55aa088114dc597b8850c2f64dfd4758afd9577cda1a4620d1c21b6e37e4",
                "sha256:d4fbada397b709e07fa5fa406b5b14d53ca6b085dbb6e0facbc50369699e03fe",
                "sha256:3d401b029ff7cc11b94c5f2369c114d980ebbf2435c95d4a9ab4455011e3e1c5",
                "sha256:6309541888fc9f5570ceb1dad1fee820d3bd897c7b5c11fdeb2fca18dbd67ca2",
                "sha256:91464abaf14a1cb5f1afb2c7a6428d5e559f35de984ffdc1fec46010c02e993b",
                "sha256:a1bd89f5571acb5a95c8964300d5ec45c738f0e0349aa49356bcc4c948d2b755",
                "sha256:52f00df2f8cb90de15623d265a33a72f6bbd4c3ea084b4ff56879d8f00cf2ec8",
                "sha256:f1e7a200634aeae288b03fcda7ad262315a025971807fc2cc42cd6a446b5eda0",
                "sha256:76afa76018a0b1315ccb9478089391e67a0942f98888a576062d54f064c1f098"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

### Troubleshooting

`docker exec homepage ping 10.0.0.10:80`
```
PING 10.0.0.10:80 (10.0.0.10): 56 data bytes
64 bytes from 10.0.0.10: seq=0 ttl=64 time=0.129 ms
64 bytes from 10.0.0.10: seq=1 ttl=64 time=0.046 ms
64 bytes from 10.0.0.10: seq=2 ttl=64 time=0.080 ms
64 bytes from 10.0.0.10: seq=3 ttl=64 time=0.051 ms
^C
```

```
┌──[00:18:06]─[0]─[Pi5:~/docker/homepage]
└──| curl -L -k http://10.0.0.10/admin/api.php
┌──[00:18:07]─[0]─[Pi5:~/docker/homepage]
└──| 
```

`docker -v && docker compose version && docker ps -a --format "table {{.Names}}\t{{.State}}\t{{.Status}}\t{{.Networks}}\t\t{{.Mounts}}\t\t{{.Image}}"`
```
Docker version 26.1.2, build 211e74b
Docker Compose version v2.27.0
NAMES          STATE     STATUS                    NETWORKS                       MOUNTS                                      IMAGE
homepage       running   Up 16 minutes (healthy)   homepage_default               /home/pi/docke…                             ghcr.io/gethomepage/homepage:latest
pihole         running   Up 2 hours (healthy)      pi-hole_default                /home/pi/docke…,/home/pi/docke…             pihole/pihole:latest
dozzle         running   Up 2 hours                doozle_default                 /var/run/docke…                             amir20/dozzle:latest
qbittorrent    running   Up 2 hours (healthy)                                     /home/pi/docke…,/mnt/nas/media              lscr.io/linuxserver/qbittorrent:latest
gluetun        running   Up 2 hours (healthy)      gluetun_default                /home/pi/docke…                             qmcgaw/gluetun:latest
ddns-updater   running   Up 2 hours (healthy)      bridge                         /home/pi/docke…                             qmcgaw/ddns-updater:latest
watchtower     running   Up 2 hours (healthy)      watchtower_default             /var/run/docke…                             containrrr/watchtower:latest
```

`docker network ls`
```
NETWORK ID     NAME                 DRIVER    SCOPE
4370d36864e4   bridge               bridge    local
258f03953fb7   doozle_default       bridge    local
2ae78447a0e9   gluetun_default      bridge    local
c612fe1ec052   homepage_default     bridge    local
e8aa32809604   host                 host      local
758b9b78c2d4   none                 null      local
9be8eb0256dc   pi-hole_default      bridge    local
546a7be2755b   watchtower_default   bridge    local
```
