### DISCUSSION TITLE
DDNS-updater service and widget

### DISCUSSION THREAD

**Discussion by Arelius-D** [gethomepage/homepage#3451] [Feature Requests]
### Description

Well this is what I for one would like to see..
![image](https://github.com/gethomepage/homepage/assets/168124713/35643c5c-7d83-4945-9dd5-1dd500ca7253)

The program is great tool, massive provider support, lightweight, has a WebUI and the information there would be nice to get integrated in Homepage.

![image](https://github.com/gethomepage/homepage/assets/168124713/fc2d4ac7-901c-4983-8747-4a9877ead2ab)

[DDNS-updater](https://github.com/qdm12/ddns-updater)

### Other

My home brewed substitute until the real thing comes along!

`services.yml`
```
- Services:
    - DDNS Updater:
       icon: https://raw.githubusercontent.com/qdm12/ddns-updater/master/readme/ddnsgopher.svg
#      herf: http://10.0.0.10:8000/ # Obviously this doesn't work now but added as a suggestion.
       ping: 10.0.0.10:8000
       description: Lightweight universal DDNS Updater program
#      widget:
#        type: ddns-updater # Obviously this doesn't work now but added as a suggestion.
#        fields: ["Provider", "Domain", "ISP IP", "Status"] # Obviously this doesn't work now but added as a suggestion.
#        url: http://10.0.0.10:8000/ # Obviously this doesn't work now but added as a suggestion.
```
