### DISCUSSION TITLE
Glances widget not working only for sensor:Package id 0

### DISCUSSION THREAD

**Discussion by joshoram80** [gethomepage/homepage#3452] [Support] [answered]
### Description

I have recently switched from Glances 3 to 4 and all my widgets have been updated with "version: 4" and they all work apart from the sensor widget

If i restart Homepage container, the widget works at the start but after a few seconds the error is thrown.

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- Glances:
  - Info:
        href: http://glances.stalepopcorn.me
        widget:
            type: glances
            version: 4
            url: http://glances:61208
            metric: info
  - CPU Usage:
        widget:
            type: glances
            version: 4
            url: http://glances:61208
            metric: cpu
  - CPU Temp:
        widget:
            type: glances
            version: 4
            url: http://glances:61208
            metric: sensor: Package id 0
  - Disk Usage:
        widget:
            type: glances
            version: 4
            url: http://glances:61208
            metric: disk:nvme0n1
  - File System:
        widget:
            type: glances
            version: 4
            url: http://glances:61208
            metric: fs:/mnt/htpc
  - Network Usage:
        widget:
            type: glances
            version: 4
            url: http://glances:61208
            metric: network:eth0
  - Processes:
        widget:
            type: glances
            version: 4
            url: http://glances:61208
            metric: process
```
```


### Container Logs

There are no errors showing in container logs with LOG_LEVEL=debug

### Browser Logs

```
TypeError: Cannot read properties of undefined (reading 'value')
    at 1382.e214cc315189d017.js:1:5880
    at No (framework-95233f837b560043.js:1:64015)
    at zo (framework-95233f837b560043.js:1:64473)
    at Object.useState (framework-95233f837b560043.js:1:70894)
    at n.useState (framework-95233f837b560043.js:1:136831)
    at g (1382.e214cc315189d017.js:1:5597)
    at Eo (framework-95233f837b560043.js:1:63196)
    at Pu (framework-95233f837b560043.js:1:74884)
    at xi (framework-95233f837b560043.js:1:121319)
    at bs (framework-95233f837b560043.js:1:109372) 
```

### Troubleshooting

docker exec homepage ping glances works fine. All other widgets work
