### DISCUSSION TITLE
Navidrome

### DISCUSSION THREAD

**Discussion by IkariTyux** [gethomepage/homepage#3457] [Support]
### Description

Hello there,
I'd like to use the Navidrome widget but i don't understand how it works. I follow this [discussion](https://github.com/gethomepage/homepage/discussions/1364) , but it's not working.

The error message is the following :
![Screenshot_202405 dd](https://github.com/gethomepage/homepage/assets/160258025/a94a5cff-e5b7-4fac-8fb3-6b935a40a95c)
 
I generated the md5 token following the discussion mentioned earlier.

### homepage version

0.8.13

### Installation method

Docker

### Configuration

```yaml
- Navidrome:
      icon: "https://favicon.twenty.com/navidrome.org" 
      description: "Music server"
      href: "http://eva-docks.local:4533"
      widget:
        type: navidrome
        url: "http://eva-docks.local:4533"
        user: shinji
        token: ee1d556d5e4eb971bfb20282ef56d0f3
        salt: salt
```

### Troubleshooting

I can ping my server : 
`PING eva-docks.local:4533 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.098 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.218 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.300 ms
64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.191 ms`

When running the following curl command that does the same thing as the widget, it works: 
`curl http://eva-docks.local:4533/rest/getNowPlaying?u=shinji&t=ee1d556d5e4eb971bfb20282ef56d0f3&s=salt&v=1.16.1&c=homepage`

![Screenshot_202405 dd](https://github.com/gethomepage/homepage/assets/160258025/319a9004-92fb-4e30-9db0-dfa5b1ce0806)
