### DISCUSSION TITLE
Widget > gotify: error: <credentialedProxyHandler> HTTP Error 401 calling http://gotify.example.com:8680/client

### DISCUSSION THREAD

**Discussion by cmonty14** [gethomepage/homepage#3461] [Support]
### Description

I have added widget _gotify_ to service file.
This creates error message
`HTTP Error 401 calling http://gotify.example.com:8680/client`

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

services.yaml:
```
    - Gotify:
        icon: gotify.png
        href: http://gotify.example.com:8680/
        description: Push notification service
        siteMonitor: http://gotify.example.com:8680/
        widget:
          type: gotify
          url: http://gotify.example.com:8680
          key: ASaG-yml6So3yx-
          fields: ["apps", "clients", "messages"]
```

### Container Logs

HTTP Error 401 calling http://gotify.example.com:8680/client
HTTP Error 401 calling http://gotify.example.com:8680/message
HTTP Error 401 calling http://gotify.example.com:8680/application

### Troubleshooting

Running this command
`curl -X POST "http://gotify.example.com:8680/message?token=ASaG-yml6So3yx-" -F "title=notification" -F "message=message from terminal"`
is working as expected: `{"id":2,"appid":3,"message":"message from terminal","title":"notification","priority":1,"date":"2024-05-14T14:59:10.475177001+02:00"}`
