### DISCUSSION TITLE
Mealie widget still not working on latest release of Mealie (nightly build)

### DISCUSSION THREAD

**Discussion by lennon101** [gethomepage/homepage#3467] [Support]
### Description

I want to reopen the (now closed) issue outline in #1924 

I'm currently on the latest release of Mealie and the latest release of HomePage and I'm not having any luck with the Mealie widget. The config I have is: 

![image](https://github.com/gethomepage/homepage/assets/1709944/91021169-4687-4fc6-a991-7714af975e09)

And the result is: 

![image](https://github.com/gethomepage/homepage/assets/1709944/0e8f154d-100e-42e8-8816-9c63793b0b2d)

# Steps to reproduce
Create an api key via an admin user on the mealie page using 
Click on Settings
Create an api key under "API-Tokens"
Insert API-Key on the **homepage-config**

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- Mealie:
        href: http://<private ip>:9925
        description: A self-hosted recipe manager and meal planner
        icon: mealie.png
        widget:
          type: mealie
          url: http://<private ip>:9925
          key: <mealie api token>
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

I've tried recreating an API token and refreshing my browswer cache.
