### DISCUSSION TITLE
emby api not working

### DISCUSSION THREAD

**Discussion by UberMetroid** [gethomepage/homepage#3468] [Support]
### Description

Good evening. I followed the instructions but I cant get the emby api key to work. Did emby change their apis?

### homepage version

.8.13

### Installation method

Docker

### Configuration

```yaml
- Emby:
        icon: emby.png
        href: http://192.168.1.141:8096
        ping: http://192.168.1.141:8096
        description: Media player
        widget:
          type: emby
          url: http://192.168.1.141:8096
          key: ****
```

### Troubleshooting

I know im doing something right, because all my other widgets at working. Ideas?
