### DISCUSSION TITLE
Ping reports OK on 502

### DISCUSSION THREAD

**Discussion by Steeven9** [gethomepage/homepage#3477] [Support] [answered]
### Description

When a service is down and returns 502, the ping result is still green as if it was up.

![image](https://github.com/gethomepage/homepage/assets/25285679/7dc2ca1e-8399-49ba-aaa4-a3cdf97dad66)

Check with `curl`:

![image](https://github.com/gethomepage/homepage/assets/25285679/3f17f969-a964-4eae-b0ee-0abef6e8eef1)

I would expect status codes 50x to be considered errors and thus be marked "down" as well.

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
`services.yaml`
[...]
- Your Spotify:
  description: Self-hosted Spotify statistics
  href: https://yourspotify.xxxx
  ping: https://yourspotify.xxxx
  icon: /images/your_spotify.ico
  server: swarm
  container: home_spotify_client
```

### Container Logs

-

### Browser Logs

-

### Troubleshooting

-

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

It seems like there might be a misunderstanding regarding the `ping` feature and how it operates. The `ping` property in the service configuration is designed to monitor the availability of an external host using ICMP ping, which checks if the host is reachable at the network level, not at the application level. This means that even if a service is returning a 502 HTTP status code (which indicates a problem at the application level or with a gateway), the host itself might still be reachable at the network level, and thus the ICMP ping would show the host as "up".

If you want to monitor the application status and consider HTTP status codes like 502 to mark the service as "down", you should use the `siteMonitor` property instead. The `siteMonitor` feature works by making an HTTP `HEAD` request to the URL and can fall back to a `GET` request if the `HEAD` request fails. This feature is more suitable for monitoring the application's HTTP response and will mark the service as "down" if it encounters 50x status codes.

To resolve your issue, you should update your `services.yaml` configuration to use `siteMonitor` instead of `ping` for the service you want to monitor at the application level. Here's how you can modify your configuration:

```yaml
`services.yaml`
[...]
- Your Spotify:
  description: Self-hosted Spotify statistics
  href: https://yourspotify.xxxx
  siteMonitor: https://yourspotify.xxxx
  icon: /images/your_spotify.ico
  server: swarm
  container: home_spotify_client
```

Please note that the `siteMonitor` feature was introduced in version 0.8.0, and it replaced the old `ping` functionality for HTTP monitoring. Make sure your Homepage instance is updated to at least version 0.8.0 to use this feature.

For more information on the `ping` and `siteMonitor` properties, you can refer to the documentation provided in the context section.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
