### DISCUSSION TITLE
Docker swarm shows "Running" for 0 replicas

### DISCUSSION THREAD

**Discussion by Steeven9** [gethomepage/homepage#3478] [Support]
### Description

When a service is scaled down to 0 replicas in Swarm mode, the Docker state is shown as "Running 0/0".

![image](https://github.com/gethomepage/homepage/assets/25285679/7dc2ca1e-8399-49ba-aaa4-a3cdf97dad66)

I would expect existing services with 0 replicas to be marked as "Not running".

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
`services.yaml`
[...]
- Your Spotify:
  description: Self-hosted Spotify statistics
  href: https://yourspotify.xxxx
  ping: https://yourspotify.xxxx
  icon: /images/your_spotify.ico
  server: swarm
  container: home_spotify_client
```

### Container Logs

-

### Browser Logs

-

### Troubleshooting

-
