### DISCUSSION TITLE
Calendar widget, showing "Alarm notification" instead of event name

### DISCUSSION THREAD

**Discussion by giannis371** [gethomepage/homepage#3482] [Support]
### Description

Like on the title, when i set an email notification for remembering the event on my phone then the name disappears and instead "Alarm notification" is showing on my dashboard. When i only add a Push notification its working.
Is there any fix on this?

### homepage version

v0.8.13

### Installation method

Other (please describe above)

### Configuration

```yaml
- Calendar:
    - Calendar:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/google-calendar.png
        widget:
          type: calendar
          view: monthly
          maxEvents: 10
          showTime: true
          firstDayInWeek: monday
          integrations:
            - type: ical
              url: *************
              color: red
              name: to-do
              showName: true
            - type: ical
              url: *********************
              color: blue
              name: german holiday
              showName: true
```

### Troubleshooting

Name of event not showing
