### DISCUSSION TITLE
[Feature Request] public holidays from Enrico

### DISCUSSION THREAD

**Discussion by Enissay** [gethomepage/homepage#3483] [Feature Requests]
### Description

Reviving this discussion as it was closed: https://github.com/gethomepage/homepage/discussions/1059

Suggestion:
+ Use Enrico who exposes an API to get the public holidays by country/period:
https://kayaposoft.com/enrico/
https://kayaposoft.com/enrico/json/v3.0/openapi/

+ Sadly even with CustomAPI, I cannot think of a dynamic way to retrieve all holidays => list length is variable
  + `/getHolidaysForYear`
  + Maybe add a way to list/dump all elements in a list at once ?
+ Then, what would be even better is to list the remaining holidays in the year, so, since we are in May, it would be interesting to only show the incoming holidays only till the end of the year
  + We might need to create some dynamic variables that hold such values like: currentDate, currentYear, currentMonth, ... 
  + Then use `/getHolidaysForDateRange`

Please advise :-)

**Comment by angryviking** [comment]
Would [ical for the calendar widget](https://gethomepage.dev/latest/widgets/services/calendar/#ical) work for you?
I wasn't able to get holidays from Google Calendar, but adding the Enrico ical, I now see holidays.

```
- Calendar:
  - Calendar:
      href: https://calendar.google.com/calendar/u/0/r?tab=mc
      icon: https://calendar.google.com/googlecalendar/images/favicons_2020q4/calendar_17.ico
      widget:
        type: calendar
        firstDayInWeek: sunday
        view: monthly
        showTime: true
        integrations:
          - type: ical
            url: https://calendar.google.com/calendar/ical/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/basic.ics
            name: My Events
            color: slate
            params:
              showName: true
          - type: ical
            url: http://www.kayaposoft.com/enrico/ics/v2.0?fromDate=04-07-2022&toDate=04-07-2024&country=usa&region=dc&lang=en
            name: holidays
            color: slate
```
![image](https://github.com/gethomepage/homepage/assets/28925820/6fede09b-0ce3-425b-9526-2cc2c67c9b0f)

I just used the example url from the link you posted, but the fromDate and toDate could be modified with a cron job or scheduled task to just get the holidays for the current month (for example).
