### DISCUSSION TITLE
customised icon for services

### DISCUSSION THREAD

**Discussion by GBInformatics** [gethomepage/homepage#3486] [Support]
### Description

Hello, I want to put icons corresponding to the hardware as for example for a nas synology ds923+, put the icon corresponding to the model. 

For that I have the following configurations:
In portainer :       -/volume1/docker/homepage/config/icons:/app/public/icons:rw
-In the docker folder I've created the "icons" folder inside the "config" folder

then I put "icon: /icons/example.png" in the service.
I've restarted and updated the container but it doesn't work.

Is it possible to do this?

### homepage version

v0.8.13 (986a181, 6 mai 2024)

### Installation method

Docker

### Configuration

```yaml
- Matériels réseau:
    - Box:
        href: https://192.168.xx.1/
        description: LIVEBOX [Modem]- xx
        icon: /icons/example.png
        ping: https://192.168.xx.1/
        showStats: true
        target: _blank
        statusStyle: 'dot'
```

### Troubleshooting

Hello, I want to put icons corresponding to the hardware as for example for a nas synology ds923+, put the icon corresponding to the model. 

For that I have the following configurations:
In portainer :       -/volume1/docker/homepage/config/icons:/app/public/icons:rw
-In the docker folder I've created the "icons" folder inside the "config" folder

then I put "icon: /icons/example.png" in the service.
I've restarted and updated the container but it doesn't work.

Is it possible to do this?
