### DISCUSSION TITLE
Glances plugin not working anymore since Glances changed their API

### DISCUSSION THREAD

**Discussion by stecydube** [gethomepage/homepage#3487] [Support] [answered]
### Description

Glances plugin changed their API and calls result in an error:

> Something went wrong: TypeError: S.find is not a function

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
- Network Usage:
      widget:
        type: glances
        url: https://glances.example.com
        metric: network:eth0
```

### Container Logs

2024-05-14T13:09:05.373700342Z [2024-05-14T13:09:05.357Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://glances.example.com/api/3/cpu
2024-05-14T13:09:05.439610141Z [2024-05-14T13:09:05.439Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://glances.example.com/api/3/quicklook
2024-05-14T13:09:05.460195292Z [2024-05-14T13:09:05.459Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://glances.example.com/api/3/network

### Troubleshooting

None
