### DISCUSSION TITLE
ESPHome

### DISCUSSION THREAD

**Discussion by sergiobaiao** [gethomepage/homepage#3488] [Support] [answered]
### Description

Hi there,
My ESPHome dashboard is password protected. When i enable the widget for ESPHome is giving the "API Error Information" box.

How can i solve it?

### homepage version

v0.8.13

### Installation method

Docker

### Troubleshooting

i tried putting the username and password on the widget but it didn't work:

- ESPHome:
        href: http://192.168.0.244:6052
        description: ESPHome
        icon: esphome.png
        container: esphome
        showStats: true
        widget:
            type: esphome
            url: http://192.168.0.244:6052
            username: admin
            password: my_very_secure_password

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To resolve the "API Error Information" issue with your ESPHome widget on the Homepage dashboard, you should ensure that your configuration is correct and follows the documentation for the ESPHome widget. Based on the context provided, the ESPHome widget configuration does not include fields for `username` and `password`. This means that the widget may not support authentication directly through the widget configuration.

Here are some steps you can take to troubleshoot the issue:

1. **Check the ESPHome Documentation**: Verify if ESPHome has an API that supports authentication and if there are specific parameters or headers required for authenticated requests.

2. **Check the Homepage Documentation**: Review the documentation for the ESPHome widget to ensure that you are using the correct configuration options. If the widget does not support authentication, it may not be possible to use it with a password-protected ESPHome dashboard.

3. **Check for Updates**: Ensure that you are using the latest version of Homepage, as updates may include fixes or enhancements for widgets.

4. **Review Error Messages**: If there are any error messages in the "API Error Information" box or in the container logs, they may provide clues as to what is causing the issue.

5. **Contact Support**: If you are unable to resolve the issue, consider reaching out to the Homepage community or support channels for assistance.

Since the ESPHome widget configuration provided in the context does not include authentication fields, it is likely that the widget is not designed to work with a password-protected ESPHome dashboard. You may need to disable password protection on your ESPHome dashboard or look for alternative methods to display ESPHome data on your Homepage dashboard.

If you have any further questions or need additional assistance, please let me know.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by shamoon** [reply]
1 & 2 above are basically the answer. If auth is an 'official' option of ESPHome (I dont have one of those things to know), then we can consider this a feature request to add support for that. The default username / password options only really work with one type of auth, which might not be what ESPhome uses

**Comment by mircsicz** [comment]
In my case the username and password are set via docker environment vars in my compose.yml

```
version: '3'
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /srv/docker/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    environment:
      - USERNAME=USERNAME
      - PASSWORD=SECRETPASSWD
```

**Comment by a7hybnj2** [comment]
This is my same problem. Would be awesome for a widget update. In the meantime I guess I will try to remove the uname/pass from my docker config and see if that works...

EDIT/UPDATE: Commenting out my the whole "enviroment" block of my compose file worked fine. The widgets load and since this is a local only install I am not too worried about having it password protected...

**Comment by pduchnovsky** [comment]
I found out there is new possibility of using cookie, but even this does not work, I tried several ways on how to provide it and none worked.

Maybe somebody made it work ?

Current guide [here](https://gethomepage.dev/widgets/services/esphome/) says:
```
widget:
  type: esphome
  url: http://esphome.host.or.ip:port
  key: myesphomecookie # only if auth enabled, get the value from a request from the frontend e.g. `authenticated=myesphomecookie`
```

<img width="544" alt="image" src="https://github.com/user-attachments/assets/f31b8d57-39f9-4d95-b674-0a8b85b3ad43">

So I set it up as this, according to my cookie:

```
    - ESPhome:
        icon: esphome.svg
        href: https://esphome.{{HOMEPAGE_VAR_DOMAIN}}
        siteMonitor: http://{{HOMEPAGE_VAR_SERVER_LAN_IP}}:6052
        widget:
          type: esphome
          url: http://{{HOMEPAGE_VAR_SERVER_LAN_IP}}:6052
          key: "2|1:0|10:1727774431|13:authenticated|4:eWVz|xxxxxxxxxxxxxxxxxxxxxxxx"
```

Doesn't work.

Error in the log:
```
[2024-10-01T09:21:03.656Z] error: <validateWidgetData> Invalid data for widget 'esphome' endpoint 'undefined':
Expected:undefined
Parse error: SyntaxError: Unexpected token < in JSON at position 0
Data: {"type":"Buffer","data":[60,33,68,79,67,84,89,80,69,32,104,116,109,108,62,10,60,104,116,109,108,3........
```

**Reply by Jens-Wymeersch** [reply]
anyone in the end found a way to get this sorted ?

**Comment by ostgardh** [comment]
Any news?
I have try
          key: authenticated=2|1:0|10:1731520406|13:authenticated|4:eWVz|259f716a17e11fdedfda50b0e3879db01fdfdd1d95b2be6116358a6b7d3275"

Same problem..

**Comment by fanaticDavid** [comment]
I can't get it to work either when authentication is active. I attempted to provide the authenticated cookie in a few different ways, but none of them work for me.

**Comment by jesserockz** [comment]
Hello :wave: 

ESPHome maintainer here (and user of homepage personally)

I came across this issue and thought I would give it a test (don't normally have an ESPHome dashboard running) and it works with the below configuration:

```yaml
    - ESPHome:
        icon: esphome.svg
        widget:
          type: esphome
          url: http://10.1.1.50:6052
          key: "2|1:0|10:1731977187|13:authenticated|4:eWVz|abc123abc123"
```

I found that I had to restart the whole homepage server after changing the key and the normal homepage refresh would not send the new/correct key.

Now, this using the cookie like this is not ideal at all, if someone wants to contribute base64 encoded username and password in the `Authorization` header to the ESPHome dashboard webserver, then please do and it might just make this a bit easier on everyone. 
The homepage config could take username and password and the proxy code behind it can encode them and attach.

I get way too many notifications on GH to notice if someone replies to me, but I will try to check back again in the future.

Jesse
