### DISCUSSION TITLE
Feature Request: support RAID for TrueNAS widget pool metrics

### DISCUSSION THREAD

**Discussion by zkvvoob** [gethomepage/homepage#3493] [Feature Requests] [answered]
### Description

Hello,

I noticed that the TrueNAS widget is not reporting the size and used space of my pools correctly. Here's what I have in Homepage:

![SCR-20240519-doq](https://github.com/gethomepage/homepage/assets/7645808/001408d8-e830-4546-9401-6bbbe300c455)

And here are snapshots of the two pools from within TrueNAS's interface:
![SCR-20240519-dqk](https://github.com/gethomepage/homepage/assets/7645808/cb01b5e1-35a4-4a49-b402-f34a43e91b18)
![SCR-20240519-dqt](https://github.com/gethomepage/homepage/assets/7645808/a31fa39f-6582-44e6-9272-7a8462907d67)

My `settings.yaml` contains this:

```yaml
- SYSTEM:
    - TrueNAS:
        widget:
            type: truenas
            url: http://10.0.0.77:81
            key: ***
            enablePools: true
            nasType: scale
```

and I'm running TrueNAS-SCALE-23.10.0.1.

Do you know if this is caused by their API or is it a bug on Homepage's end?

Thanks!

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Troubleshooting

N/A
