### DISCUSSION TITLE
Two column layout: one with two sections and one with one section

### DISCUSSION THREAD

**Discussion by Kribensisis** [gethomepage/homepage#3499] [Support]
### Description

Hi. I've asked the bot, and Discord. I've tried 20+ layouts. I must be missing something quite basic, but I can't make it work. I use `settings.yml` and `services.yml`. I don't use `bookmarks.yml`, I just define my bookmarks in services. 

I want a two-column layout where the left column has two headings: Services and Tools. The right column just has Media. 

Column 1 (title hidden):
- Services
  - Service 1
  - Service 2
  - Etc.
- Tools
  - Tool 1
  - Tool 2
  - Etc.

Column 2 (title hidden)
- Media
  - Media 1
  - Media 2

I'm not even going to post my current YAML since none of it works. In any of the 20+ layouts I've tried, it's either three columns (Services, Tools, and Media) or it's valid yaml that results in an empty page with only the widgets in the heading loading. I've used the bot's YAML verbatim and I've used alternates of my own. 

I would love input. Because 100%, I am not going to figure this out myself. Thank you! 

### homepage version

0.8.13

### Installation method

Docker

### Troubleshooting

N/A

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To achieve the two-column layout with the sections and services you've described, you can use the following configuration in your `settings.yaml` file:

```yaml
layout:
  Column 1:
    style: column
    groups:
      - Services
      - Tools
  Column 2:
    style: column
    groups:
      - Media
```

In this configuration, `Column 1` and `Column 2` are just identifiers for your columns and can be named anything. The `groups` key under each column identifier lists the groups that should appear in that column. Since you want to hide the titles, you can add `header: false` to each group in your `services.yaml` file like so:

```yaml
Services:
  header: false
  - Service 1:
      # Service 1 details
  - Service 2:
      # Service 2 details
  # ... other services

Tools:
  header: false
  - Tool 1:
      # Tool 1 details
  - Tool 2:
      # Tool 2 details
  # ... other tools

Media:
  header: false
  - Media 1:
      # Media 1 details
  - Media 2:
      # Media 2 details
  # ... other media
```

Make sure that the group names used in `layout` match exactly with those in `services.yaml`. Also, ensure that your YAML indentation is correct, as incorrect indentation can lead to parsing errors.

If you encounter any issues or the page doesn't render as expected, please check the container logs and browser console for any errors that might provide more insight into the problem.

Remember to validate your YAML using an online validator if you're unsure about the syntax. Here are a couple of validators you can use:
- https://codebeautify.org/yaml-validator
- https://jsonformatter.org/yaml-validator

If you continue to have issues, please provide the YAML you're using, and I can help you troubleshoot further.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
