### DISCUSSION TITLE
TrueNAS widget help

### DISCUSSION THREAD

**Discussion by Kenji776** [gethomepage/homepage#3502] [Support]
### Description

I just updated to the newest release of homepage and it seems like it broke the TrueNAS widget. 

![image](https://github.com/gethomepage/homepage/assets/2421263/15e6197e-2b5f-47ab-af5c-8ab5d70a01b1)
            
Anything I should check? This is running as a docker container, but no errors relevant to this I can see in the docker logs. Any help is appreciated. This is for TrueNAS core btw. Thanks.

### homepage version

v0.8.13 (986a181, May 5, 2024)

### Installation method

Docker

### Configuration

```yaml
- TrueNas:
        icon: https://www.svgrepo.com/show/331613/truenas.svg
        href: http://10.0.0.202
        description: NAS storage. Hosts videos for plex server and various software
        ping: 10.0.0.202
        widget:
            type: truenas
            url: http://10.0.0.202
            key: [KEY REDACTED]
            #enablePools: true # optional, defaults to false
            nasType: core # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
```

### Container Logs

Listening on port 3000
[2024-05-20T20:16:25.654Z] error: undefined
[2024-05-20T20:16:26.123Z] error: undefined
[2024-05-20T20:16:36.283Z] error: undefined
[2024-05-20T20:16:56.367Z] error: undefined
[2024-05-20T20:17:26.472Z] error: undefined
[2024-05-20T20:17:32.237Z] error: undefined

### Browser Logs

![image](https://github.com/gethomepage/homepage/assets/2421263/5007a445-ade1-4ce8-a69a-e12b3672c29c)

### Troubleshooting

I am able to issue a basic http curl request, so I can tell the connection is fine.

curl -X GET "http://10.0.0.202/api/v2.0/system/info/" -H "Authorization: Bearer [API KEY HERE]"
{
 "version": "TrueNAS-13.0-U6.1",
 "buildtime": {
  "$date": 1701702478000
 },
 "hostname": "truenas.local",
 "physmem": 17037254656,
 "model": "Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz",
 "cores": 4,
 "loadavg": [
  0.26904296875,
  0.22802734375,
  0.20751953125
 ],
 "uptime": "4 days, 20:11:25.334661",
 "uptime_seconds": 418285.334661445,
 "system_serial": "System Serial Number",
 "system_product": "System Product Name",
 "system_product_version": "System Version",
 "license": null,
 "boottime": {
  "$date": 1715819763000
 },
 "datetime": {
  "$date": 1716238048841
 },
 "birthday": {
  "$date": 1715230961361
 },
 "timezone": "America/Los_Angeles",
 "system_manufacturer": "System manufacturer",
 "ecc_memory": false
}

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems like you are encountering an issue with the TrueNAS widget after updating to the latest version of homepage. The error message is not very descriptive ("error: undefined"), but since you mentioned that this is for TrueNAS Core, there are a couple of things we can check:

1. **Configuration**: Ensure that the `enablePools` option is set correctly. Since you are using TrueNAS Core, you need to uncomment the `enablePools` line in your configuration and set it to `true`. This is required along with setting `nasType` to `core` as per the TrueNAS widget documentation.

2. **API Key**: Verify that the API key is still valid and has the necessary permissions. You mentioned that you can make a successful curl request, which is good. Ensure that the API key in the widget configuration matches the one used in your curl test.

3. **URL Format**: Check that the URL in the widget configuration does not end with a trailing slash, as per the troubleshooting documentation. This can cause errors.

4. **Homepage Version**: There might be a known issue with the version of homepage you are using. Check the GitHub issues and discussions for any known bugs related to the TrueNAS widget in version v0.8.13.

5. **Logs**: Since the container logs are showing "error: undefined", it might be helpful to set the `LOG_LEVEL` to `debug` for more detailed logs that could provide additional insight into the issue.

6. **Browser Console**: Check the browser console for any errors that might indicate what's going wrong with the widget.

7. **Known Issues**: Look for any known issues on the homepage GitHub repository that might be related to your problem. For example, there was a known issue discussed in GitHub discussion #3180 that might be relevant.

Here's the updated configuration snippet with `enablePools` set to true:

```yaml
- TrueNas:
        icon: https://www.svgrepo.com/show/331613/truenas.svg
        href: http://10.0.0.202
        description: NAS storage. Hosts videos for plex server and various software
        ping: 10.0.0.202
        widget:
            type: truenas
            url: http://10.0.0.202
            key: 1-fEr9x5lpe6UDSxqu7DMrMHJtNiWHR6oi50h1iA57QOEk3kGh2E0gYZJH9NxB5Llv
            enablePools: true
            nasType: core
```

If after making these checks and updates the issue persists, consider reaching out to the homepage community on GitHub discussions or Discord for further assistance.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
