### DISCUSSION TITLE
Gamedig

### DISCUSSION THREAD

**Discussion by conanbeach** [gethomepage/homepage#3503] [Support]
### Description

cannot get any server to display on the Gamedig widget tried internal and external, tried different types of games, check thru discussion board, have no error message 

this is sample of code using

 - Steam Game:
        icon: /images/logos/steam.png
        widget:
          type: gamedig
          serverType: sdtd # see https://github.com/gamedig/node-gamedig#games-list
          url: udp://http://176.57.160.22:27010

any help would be really appreciated

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- Steam Game:
        icon: /images/logos/steam.png
        widget:
          type: gamedig
          serverType: sdtd # see https://github.com/gamedig/node-gamedig#games-list
          url: udp://http://176.57.160.22:27010
```

### Troubleshooting

none

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the configuration you've provided, there seems to be an issue with the `url` field in your GameDig widget configuration. The `url` should not include the `http://` protocol when using `udp://`. It should be formatted as `udp://IP:PORT` without the `http://` prefix.

Please try updating your configuration to the following:

```yaml
- Steam Game:
    icon: /images/logos/steam.png
    widget:
      type: gamedig
      serverType: sdtd # see https://github.com/gamedig/node-gamedig#games-list
      url: udp://176.57.160.22:27010
```

Additionally, ensure that your Docker container has network access to the game server IP and port you are trying to query. You can test this by executing a ping or similar network test from within the Docker container to the game server IP.

If you continue to experience issues, please refer to the troubleshooting steps provided in the documentation, such as verifying the homepage installation can connect to the IP address or host you are using for the widget `url`, and checking the API output using `curl` if necessary.

Let me know if this resolves your issue or if you need further assistance.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
