### DISCUSSION TITLE
Tailscale widget API is not working

### DISCUSSION THREAD

**Discussion by diptamahardhika** [gethomepage/homepage#3504] [Support]
### Description

Hello, i have an issue since few weeks back that the Tailscale widget is not working and receive this below API error;
![rCfJYPKluB](https://github.com/gethomepage/homepage/assets/85156185/6a378c00-03d7-4cfc-8006-ec248a50d4da)

Normally this is not the case, and widget always working before.
Is someone having similar issue, or is this some kind of bug?

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- Tailscale:
        icon: https://tailscale.gallerycdn.vsassets.io/extensions/tailscale/vscode-tailscale/1.0.0/1698786256133/Microsoft.VisualStudio.Services.Icons.Default
        href: https://login.tailscale.com/admin/machines
        description: Tailscale Admin Console
        siteMonitor: https://login.tailscale.com/admin/machines
        widget:
            type: tailscale
            deviceid: deviceid
            key: {{HOMEPAGE_VAR_TAILSCALE_API_KEY}}
```

### Troubleshooting

The troubleshooting use `sudo docker exec homepage ping` is return with `ping: bad port FROMSERVICEIP`
