### DISCUSSION TITLE
pfSense Widget only works when credentials exposed

### DISCUSSION THREAD

**Discussion by jewstan83** [gethomepage/homepage#3512] [Support]
### Description

I got Homepage setup in Portainer. I then went back and moved all sensitive information into env variables. Upon doing this, pfSense widget stopped working. I've found that it only works if I put the API Authentication token info directly into services.yaml. I've tried using variables for username/password and Authorization and neither works. I can only get it to work if putting the credentials directly into the yaml file.

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
- pfSense:
        href: {{HOMEPAGE_VAR_PFIP}}
        description: Firewall / Route / Public
        icon: pfsense.png
        siteMonitor: {{HOMEPAGE_VAR_PFIP}}
        widget:
            type: pfsense
            url: {{HOMEPAGE_VAR_PFIP}}
            #username: {{HOMEPAGE_VAR_PFU}}
            #password: {{HOMEPAGE_VAR_PFP}}
            headers:
                Authorization: {{HOMEPAGE_VAR_PFID HOMEPAGE_VAR_PFTH}}
            wan: vtnet0
            fields: ["load", "memory", "wanStatus"]
```

### Container Logs

[2024-05-23T02:02:59.534Z] error: <httpProxy> Error calling http://10.15.20.110:2802/api/v1/status/system...

[2024-05-23T02:02:59.534Z] error: <httpProxy> [

  500,

  Error: connect ETIMEDOUT 10.15.20.110:2802

      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {

    errno: -110,

    code: 'ETIMEDOUT',

    syscall: 'connect',

    address: '10.15.20.110',

    port: 2802

  }

]

### Browser Logs

{"error":{"message":"HTTP Error","url":"http://10.15.20.110:2802/api/v1/status/system","resultData":{"type":"Buffer","data":[123,34,115,116,97,116,117,115,34,58,34,117,110,97,117,116,104,111,114,105,122,101,100,34,44,34,99,111,100,101,34,58,52,48,49,44,34,114,101,116,117,114,110,34,58,51,44,34,109,101,115,115,97,103,101,34,58,34,65,117,116,104,101,110,116,105,99,97,116,105,111,110,32,102,97,105,108,101,100,34,44,34,100,97,116,97,34,58,91,93,125,10]}}}

### Troubleshooting

Enter username/password in services.yaml = works
 -- remove username/password
Enter id/token in services.yaml = works
 -- remove id/token
Enter username/password as env variable = no work
 -- remove username/password env variable
Enter id/token as env variable = no work

Create new user with same steps and results as above.

Tried {{pfid pfth}} & {{pfid}} {{pfth}} - neither works, separate vars throws error in Homepage (invalid indentation) - single var with both included throws API error.
