### DISCUSSION TITLE
cputemp has disappeared from glances widgets?

### DISCUSSION THREAD

**Discussion by crispybegs** [gethomepage/homepage#3513] [Support] [answered]
### Description

I just noticed that the temperature for various severs has disappeared from my glances widgets:

<img width="747" alt="Screenshot 2024-05-23 at 10 23 28" src="https://github.com/gethomepage/homepage/assets/129169122/9401a8b9-5dc6-4186-ab10-5561720f463e">

my widgets yaml has been untouched apart from inserting `version: 4` a couple of weeks back following an update:

```
- glances:
    label: Plex # optional
    cpu: true
    memory: true
    expanded: true
    url: http://192.168.1.63:61208
    version: 4
    cputemp: true # disabled by default
    uptime: true # disabled by default
    units: metric
    disk:
      - /etc/hostname
      - /drive1
      - /drive2

- glances:
    label: NAS # optional
    cpu: true
    memory: true
    url: http://192.168.1.14:61208
    version: 4
    cputemp: true # disabled by default
    uptime: true # disabled by default
    units: metric
    expanded: true
    disk:
      - /etc/hosts
      - /mnt/NAS_4TB_1
      - /mnt/NAS_4TB_2

- glances:
    label: Pi 1 # optional
    cpu: true
    memory: true
    expanded: true
    url: http://192.168.1.42:61208
    version: 4
    cputemp: true # disabled by default
    uptime: true # disabled by default
    units: metric
    disk:
      - /etc/hostname
     # - /drive1
     # - /drive2
```

Any suggestions on how i can get the cputemp to show again?

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Troubleshooting

read the docs, yaml seems to be correct?
