### DISCUSSION TITLE
Multiple use of CustomAPI Widget Only uses first entry url

### DISCUSSION THREAD

**Discussion by marcwoconnor** [gethomepage/homepage#3515] [Support] [answered]
### Description

I've written a small Flask application that will output metrics for each of my VMware ESXi hosts in JSON at the following urls: 

- http://flask.server/api/hosts_metrics?name=esxi-1.server
- http://flask.server/api/hosts_metrics?name=esxi-2.server
- http://flask.server/api/hosts_metrics?name=esxi-3.server

I've verified that each of those urls provides the respective server's metrics but when I define them in my services.yaml file, I only get esxi-1's information.  Here's the output of the api:
`{
    "metrics": {
        "cpu.ready.summation": [
            5591
        ],
        "cpu.usage.average": [
            2639
        ],
        "cpu.usagemhz.average": [
            6833
        ],
        "disk.maxTotalLatency.latest": [
            5
        ],
        "disk.usage.average": [
            11853
        ],
        "mem.consumed.average": [
            218283188
        ],
        "mem.overhead.average": [
            0
        ],
        "mem.swapinRate.average": [
            0
        ],
        "mem.swapoutRate.average": [
            0
        ],
        "mem.usage.average": [
            5421
        ],
        "mem.vmmemctl.average": [
            0
        ],
        "net.usage.average": [
            0
        ],
        "sys.uptime.latest": [
            6190007
        ]
    },
    "name": "esxi-1.server"
}`

`{
    "metrics": {
        "cpu.ready.summation": [
            8353
        ],
        "cpu.usage.average": [
            1401
        ],
        "cpu.usagemhz.average": [
            6814
        ],
        "disk.maxTotalLatency.latest": [
            8
        ],
        "disk.usage.average": [
            9416
        ],
        "mem.consumed.average": [
            118527368
        ],
        "mem.overhead.average": [
            0
        ],
        "mem.swapinRate.average": [
            0
        ],
        "mem.swapoutRate.average": [
            0
        ],
        "mem.usage.average": [
            2943
        ],
        "mem.vmmemctl.average": [
            0
        ],
        "net.usage.average": [
            0
        ],
        "sys.uptime.latest": [
            435948
        ]
    },
    "name": "esxi-2.server"
}`

`{
    "metrics": {
        "cpu.ready.summation": [
            593
        ],
        "cpu.usage.average": [
            558
        ],
        "cpu.usagemhz.average": [
            2666
        ],
        "disk.maxTotalLatency.latest": [
            0
        ],
        "disk.usage.average": [
            226
        ],
        "mem.consumed.average": [
            73800580
        ],
        "mem.overhead.average": [
            0
        ],
        "mem.swapinRate.average": [
            0
        ],
        "mem.swapoutRate.average": [
            0
        ],
        "mem.usage.average": [
            5499
        ],
        "mem.vmmemctl.average": [
            0
        ],
        "net.usage.average": [
            4
        ],
        "sys.uptime.latest": [
            12325673
        ]
    },
    "name": "esxi-3.server"
}`

I've been unable to figure out why on the homepage it's only displaying data from the first url for each 3 of the servers even though I've defined the respective url for each server.
![homepage-hypervisor](https://github.com/gethomepage/homepage/assets/17690536/af1406d2-9e1b-44a0-90d1-cf92eae8d390)

This is my first implementation of Homepage, so please forgive me if I missed something, but I have read over the CustomAPI docs a few times and can't find anything that would address this behavior.

Thanks!

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
services.yaml

---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Hypervisor:
    - VMware VCSA:
        icon: vmware-vcenter.png
        href: https://vcsa01.server/ui
        description: vcsa01
    - VMware ESXi:
        icon: vmware-esxi.svg
        href: https://esxi-1.server/ui
        description: esxi-1
        widget:
          type: customapi
          url: http://flask.server:5001/api/hosts_metrics?name=esxi-1.server
          mappings:
            - field:
                metrics:
                    sys.uptime.latest
              label: Uptime (Days)
              scale: 0.000011574
              format: number
            - field:
                metrics:
                    cpu.usagemhz.average
              label: CPU MHz (Avg)
            - field:
                metrics:
                  disk.maxTotalLatency.latest
              label: Disk Latency MAX(ms)
            - field:
                metrics:
                  disk.usage.average
              label: Disk Usage AVG (MB/s)
            - field:
                metrics:
                  mem.usage.average
              label: Mem Used(GB)
    - VMware ESXi:
        icon: vmware-esxi.svg
        href: https://esxi-2.server/ui
        description: esxi-2
        widget:
           type: customapi
           url: http://flask.server:5001/api/hosts_metrics?name=esxi-2.server
           mappings:
             - field:
                 metrics:
                     sys.uptime.latest
               label: Uptime (Days)
               scale: 0.000011574
               format: number
             - field:
                 metrics:
                     cpu.usagemhz.average
               label: CPU MHz (Avg)
             - field:
                 metrics:
                   disk.maxTotalLatency.latest
               label: Disk Latency MAX(ms)
             - field:
                 metrics:
                   disk.usage.average
               label: Disk Usage AVG (MB/s)
             - field:
                 metrics:
                   mem.usage.average
               label: Mem Used(GB)
    - VMware ESXi:
        icon: vmware-esxi.svg
        href: https://esxi-3.server/ui
        description: esxi-3
        widget:
          type: customapi
          url: http://flask.server:5001/api/hosts_metrics?name=esxi-3.server
          mappings:
            - field:
                metrics:
                  sys.uptime.latest
              label: Uptime (Days)
              scale: 0.000011574
              format: number
            - field:
                metrics:
                    cpu.usagemhz.average
              label: CPU MHz (Avg)
            - field:
                metrics:
                  disk.maxTotalLatency.latest
              label: Disk Latency MAX(ms)
            - field:
                metrics:
                  disk.usage.average
              label: Disk Usage AVG (MB/s)
            - field:
                metrics:
                  mem.usage.average
              label: Mem Used(GB)
```

### Troubleshooting

Which ever url I define first is which metrics are displayed on the Homepage webpage even when each server has it's own url.
