### DISCUSSION TITLE
wg-easy widget gives error after some amount of time

### DISCUSSION THREAD

**Discussion by dnielso5** [gethomepage/homepage#3516] [Support]
### Description

using the wg-easy widget in the main branch works, but then after an amount of time it gives this error:

![image](https://github.com/gethomepage/homepage/assets/107376351/97468e46-537f-4e6f-87c5-7f56acbcbe9a)

Restarting the homepage container fixes it, but then eventually gives the same error.

### homepage version

main (0a75c83, May 22, 2024)

### Installation method

Docker

### Configuration

```yaml
- Wireguard:
       icon: wireguard.png
       id: col-small
       widget:
         type: wgeasy
         url: http://internal IP:Port
         password: Password
         threshold: 1
       server: Docker-Dell
       container: wg-easy
       showStats: true
```

### Container Logs

No errors in homepage docker logs

### Troubleshooting

restarting all containers, server
