### DISCUSSION TITLE
Size of a list in Custom API

### DISCUSSION THREAD

**Discussion by Tygo-van-den-Hurk** [gethomepage/homepage#3517] [Support] [answered]
So I was working on a custom API, but this was as far as I got:
```YML
    - Ollama:       
        href:           https://some.domain.com/
        siteMonitor:    http://ollama:11434
        icon:           /icons/ollama.svg
        widget:
          type: customapi
          url: http://ollama:11434/api/tags
          refreshInterval: 10000
          method: GET
          mappings:
            - field: models
              label: Models
              remap:
              - any: true
                to: totals # I can't figure out how to get the total amount 
```

How does one get the total size of a list? The [documentation](https://gethomepage.dev/latest/widgets/services/customapi/) doesn't mention anything about it, I couldn't find any similar discussions, nor did I get any wiser from reading the source code.

Does anyone know if this is possible? If not, shall I open a feature request?
