### DISCUSSION TITLE
Synology diskstation widget does not work

### DISCUSSION THREAD

**Discussion by ithinkmax** [gethomepage/homepage#3518] [Support]
### Description

Good morning, everyone,

I am trying to use the widget for Synology nas and Download Station but I can't get them to work even if I try to point 2 different NAS inside the LAN. Clearly I have created the remote stats user, given permissions to access the DSM and Download Station and logged in with that user asking not to enable 2FA and smart MFA.

I see from the Synology logs that the connection/login is not coming in either. And in the homepage logs I see errors.
I have tried HTTP port 5000 and HTTPS port 5001 yaml setup, the strange thing is that if i put HTTPS in the yamls setting i can see a connection attemp in the log to the http cgi anyway...

Homepage runs on Docker (Container Station) from the same synology NAS. The connection with Plex works so I don't think it is a docker network problem.

Can you guys help me? Thanks guys!

Services YAML extract:

```
    - ALiNAS:
        type: diskstation
        url: https://192.168.1.10:5001
        username: remote_stats
        password: hidden
        volume: volume_1 # optional
        statusStyle: dot
```
      
```
    - ALiNAS DOWNLOADS:
        type: downloadstation
        url: https://192.168.1.10:5001
        username: remote_stats
        password: hidden
```

Docker LOG:

![CleanShot 2024-05-24 at 07 27 58](https://github.com/gethomepage/homepage/assets/44212536/8f880799-9aa8-4645-810c-a59da7d3b82a)

![CleanShot 2024-05-24 at 07 25 12](https://github.com/gethomepage/homepage/assets/44212536/91eeeee4-271b-4387-9c2e-4882020823b7)

### homepage version

v0.8.13

### Installation method

Docker

### Troubleshooting

![CleanShot 2024-05-24 at 07 35 16](https://github.com/gethomepage/homepage/assets/44212536/9f0e29f4-b4ba-4642-b9af-0f01ee5f19a7)
