### DISCUSSION TITLE
Bookmark widget

### DISCUSSION THREAD

**Discussion by bozzio83** [gethomepage/homepage#3529] [Support]
### Description

Just wondering if its possible to have a bookmark up top in the widget bar? 

I have this config in my widgets.yaml.. there is a space made but it just says "missingbookmarks" in black lettering.

Any help would be greatly appreciated.

Thank you

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Unraid

### Configuration

```yaml
- bookmarks:
    - unraid:
        - abbr: ur
          icon: unraid.png
          href: https://*************************.net/
          widget:
            type: bookmark
            url: https://************************.net/
            bookmark: unraid  # Make sure the bookmark name matches
```

### Troubleshooting

na

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the provided context and configuration, it seems like you are trying to add a bookmark as a widget in the top bar of your homepage dashboard. However, the configuration you've provided is not correct for adding a bookmark as a widget. The `bookmarks.yaml` file is used to configure bookmarks that appear in the main body of the homepage, not in the widget bar.

The widget bar is typically reserved for service widgets that provide dynamic information, such as monitoring stats or service statuses. Bookmarks are static links and do not have associated widgets that can be placed in the widget bar.

If you want to add a bookmark to the main body of the homepage, you should only include the bookmark configuration without the `widget` part. Here's how you can correct your configuration:

```yaml
- unraid:
    - abbr: UR
      icon: unraid.png
      href: https://*************************.net/
      description: "Your custom description here"  # Optional
```

This configuration should be placed in the `bookmarks.yaml` file, not the `widgets.yaml` file. Make sure that the `icon` path is correct and the icon file is placed in the appropriate directory.

If you are looking to add a custom link or button to the top bar, this functionality may not be supported by the homepage application as it is designed. You would need to check the documentation or reach out to the developers for any custom modifications that might allow this.

Please remove the `widget` part from your configuration and place your bookmark configuration in the `bookmarks.yaml` file. If you have further questions or need more assistance, feel free to ask.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
