### DISCUSSION TITLE
[Feature Request] : add API widget for Ollama and OpenWeb UI

### DISCUSSION THREAD

**Discussion by Tygo-van-den-Hurk** [gethomepage/homepage#3532] [Feature Requests]
### Description

I was wondering if it'd be possible to add an API widget for Ollama, which is an opensource application to run AI models, and for [OpenWeb UI](https://github.com/open-webui/open-webui) which is an opensource application that serves a web interface for ollama. It might be a bit harder to do something for OpenWeb UI, especially since their API isn't well documented. To what I could see

**Edit**: @shiftoptk had a great idea of adding a prompt bar that would instead of search, create a new chat in openwebUI with that prompt.

**Comment by shiftoptk** [comment]
Replacing the search bar in Homepage with a OpenWebUI prompt to Ollama would be a game changer.

**Reply by Tygo-van-den-Hurk** [reply]
This is so good. I’m adding this to the issue.

**Reply by Madad1996** [reply]
> Replacing the search bar in Homepage with a OpenWebUI prompt to Ollama would be a game changer.

would be awesome

**Comment by UberMetroid** [comment]
Something with Ollama would be really cool.

**Comment by thadude3** [comment]
following so I can see any updates on this.

**Reply by jeremyjoslin** [reply]
Amazed not more discussion about this. Looking for a "Homepage" that does exactly this. Thought for sure homepage would.

**Comment by maxexcloo** [comment]
You can have a list of current chats with the `customapi` type:
```
      "widget":
        "headers":
          "Authorization": "Bearer APIKEY"
        "mappings":
        - "format": "size"
          "label": "Chats"
        "type": "customapi"
        "url": "https://chat.domain.org/api/v1/chats/all"
```

**Reply by buffaloexpatbill** [reply]
I looked into this recently. While I can successfully generated a completion (asked a question and gotten a response) using curl with the endpoint 

> POST /api/generate

There are many parameters that can be used/sent other than the question itself that I have not standardized in my environment yet.
After looking at available endpoints for the ollama API (and so far unsuccessfully testing the openwebui API in my environment), I found adding a service widget with link URL pointing to openwebui, and an API call to ollama to get a count of the locally installed models to be useful.

> GET /api/tags

https://github.com/ollama/ollama/blob/main/docs/api.md

```
     - ollama - openwebui:
        href: https://openwebui_FQDN_or_IP
        description: ollama using openwebui
        icon: https://openwebui_FQDN_or_IP/static/favicon.png
        widget:
          type: customapi
          url: http://ollama_FQDN_or_IP:11434/api/tags
          method: GET
          mappings:
            - field: models
              label: "local models"
              format: size
```

![image](https://github.com/user-attachments/assets/b3aae279-6c9e-48f8-a0b0-20981e1bb2c6)

**Reply by Madad1996** [reply]
would be sufficient if we could configure the model in the widget  definition imho

**Reply by buffaloexpatbill** [reply]
Might be possible with the openwebui api. I'll have to dig into why I couldn't get that working.

**Reply by buffaloexpatbill** [reply]
I had a chance to look at this.  The model or models to be used can be specified as parameters of the URL based on https://docs.openwebui.com/features/chat-features/url-params
I have tested it in my environment. This can simply be added to the link URL itself, so doesn't even require API/widget.
In my previous example, we can modify the href value.
Check what models are available.  One way to check is with curl:

> curl -X GET http://openwebui_FQDN_or_IP:port (if port is needed)/api/models -H "Authorization: Bearer API KEY" -H "Content-Type: application/json" -d ''

If we were to change href: https://openwebui_FQDN_or_IP to href: https://openwebui_FQDN_or_IP/?model=gemma2:27b
the link would load an openwebui chat with gemma2:27b as the selected model.
The models parameter, in my experience (or model parameter with a comma separated list) loads an openwebui chat with both models selected.

i.e. 
href: https://openwebui_FQDN_or_IP/?model=gemma2:27b,mistral:latest
or
href: https://openwebui_FQDN_or_IP/?models=gemma2:27b,mistral:latest

**Comment by chiragkrishna** [comment]
You can use [Open-WebUI](https://docs.openwebui.com/tutorials/integrations/browser-search-engine/) in quick-launch or search bar, selecting model also works

settings.yaml
```yaml
quicklaunch:
  provider: custom
  url: http://open-webui:8080/?q=
  target: _blank
```

widgets.yaml
```yaml
- search:
    provider: custom
    url: http://open-webui:8080/?models=gemma3&q=
    target: _blank
```

**Comment by chiragkrishna** [comment]
Finally got this working

```yaml
- A.I Services:
    - Ollama:
        icon: sh-ollama-light.png
        description: A.I Backend
        widget:
          type: customapi
          url: http://ollama:11434/api/ps
          method: GET
          mappings:
            - field: models[0].name
              label: "Running Model"
              format: text
            - field: models[0].size
              label: "Model Size"
              format: bytes
            - field: models[0].size_vram
              label: "VRAM Used"
              format: bytes
    - Open WebUI:
        icon: open-webui-light.png
        href: http://open-webui:8080
        description: A.I Frontend
        widget:
          type: customapi
          url: http://open-webui:8080/api/models
          headers:
            Authorization: "Bearer {{HOMEPAGE_VAR_OPENWEBUI_KEY}}"
          mappings:
            - field: data
              label: Total Models
              format: size
```
![Screenshot_20250331_090353](https://github.com/user-attachments/assets/5f107f75-bd34-4dda-947d-0f3370ab0d26)
