### DISCUSSION TITLE
Adguard Widget 403 Error

### DISCUSSION THREAD

**Discussion by alexbstl** [gethomepage/homepage#3533] [Support]
### Description

I've been trying to debug my adguard widget as I keep getting a homepage API error.  So far, I've been trying to debug this with the suggested curl command:

no matter what I do, I get a 403 error in the widget.
Adguard Home is installed directly on the system, with the web portal set to port 9093
### homepage version

v0.8.13 (986a181)

### Installation method

Docker

### Configuration

```yaml
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/alex/docker_config/AppData/homepage/config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock 
      - /media/data:/media
      - /mnt/media:/media2
    restart: unless-stopped
    environment:
      - HOMEPAGE_VAR_ADGUARD_USER='{user here}'
      - HOMEPAGE_VAR_ADGUARD_PASSWORD='{password here}'
```

### Troubleshooting

I have run `curl -L -k -u 'username:password' http://ADGUARDIPORHOST/control/stats` both inside and outside the homepage docker container

curl inside the docker container using both the hardcoded variables and docker_compose env variables works (i.e. returns a large json).  Note: variables only work when I use `${HOMEPAGE_VAR_ADGUARD_USER}:${HOMEPAGE_VAR_ADGUARD_PASSWORD}` without the single quotes around `'username:password'`  in the above command

outside the container, calling curl with docker exec using the hardcoded variables works (with quotes), but using variables, with the exact same command that worked inside the container, fails.
