### DISCUSSION TITLE
Docker image stuck in unhealthy state for a long time

### DISCUSSION THREAD

**Discussion by foolab** [gethomepage/homepage#3544] [Support]
### Description

I have an issue with the docker container stuck for a very long time in "unhealthy" state. Eventually it will come back to life and work but it takes 10-15 minutes.

I also have this issue only when running as non-root.
 
When initially created the docker container I faced this issue.

Yesterday I had to reinstall my server but I keep all containers in a separate data pool so I'd say a reboot caused the issue to show up again.

This is my docker compose config:
```
version: "3.3"
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 3002
      PGID: 3002
    ports:
      - 3000:3000
    volumes:
      - /mnt/data/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
```

To me it looks similar to #1190. Has anyone seen this issue before?

### homepage version

v0.8.13 (986a181, May 6, 2024)

### Installation method

Docker

### Troubleshooting

Nothing relevant in the logs :/
