### DISCUSSION TITLE
2 columns below 2 columns

### DISCUSSION THREAD

**Discussion by BulldozerPete** [gethomepage/homepage#3559] [Support]
### Description

Hello,

I am not able to create a layout with 2 columns below 2 columns.
Each time I edit the setting.yaml I will have 3 columns later.

Can someone tell me how to achieve this layout:
LAN                     Docker
   service 1                service1
   service 2               service 2

Apps                    Downloads
   service 1                service1
   service 2               service 2

"Next box1"       "next box2"   
    service 1                service1
    service 2               service 2

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
My settings.yaml:

# https://gethomepage.dev/latest/configs/settings
title: "Homepage"
disableCollapse: true
useEqualHeights: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  LAN:
    tab: Services
    style: columns
    useEqualHeights: true
  Docker:
    tab: Services
    style: columns
    useEqualHeights: true
  Apps:
    style: columns
  Downloads:
    style: columns

  Bookmarks:
    tab: bookmarks
    style: columns
    row: 2
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

![image](https://github.com/gethomepage/homepage/assets/61943052/7c7f21d5-b0dc-4672-8dfd-b62f0f4937f2)

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To achieve the layout you're describing, you need to ensure that each section in your `settings.yaml` is configured to display as columns and that the number of columns is set to 2 for each section. Additionally, you should ensure that the services within each section are correctly organized to match the desired layout.

Here's an example of how you might configure your `settings.yaml` file:

```yaml
layout:
  LAN:
    style: row
    columns: 2
  Docker:
    style: row
    columns: 2
  Apps:
    style: row
    columns: 2
  Downloads:
    style: row
    columns: 2
```

In this configuration, each section (`LAN`, `Docker`, `Apps`, `Downloads`) is set to display in a row with 2 columns. This should create the 2x2 layout you're looking for.

Please note that the `row` property should be used to define the number of columns within a row, and the `columns` property specifies the number of columns. Since you want two columns for each section, you should set `columns: 2` for each.

If you continue to experience issues, please ensure that your services are correctly defined in the `services.yaml` file and that they are grouped under the correct headings as defined in your `layout` configuration.

Remember to check your indentation as YAML is sensitive to it, and validate your YAML configuration using an online validator if necessary.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
