### DISCUSSION TITLE
Nginx Proxy Manager Docker Autodiscovery

### DISCUSSION THREAD

**Discussion by urbanTyger** [gethomepage/homepage#3560] [Support]
### Description

Widget set via Docker autodiscovery (via label) gives an error of "invalid password"
 
When widget is set via services.yml file, with all the same settings, works fine. 

It is the only widget not working 

Ubuntu 24.04 / ARM 64

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
YAML (working)
- Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        description:  Reverse Proxy Management
        server: docker
        container: nginx
        ping: {url}
        widget:
          type: npm
          url: {url}
          username: {email}
          password: {password}  

DOCKER COMPOSE (not working)
    labels:
      - homepage.group=General
      - homepage.name=Nginx
      - homepage.icon=nginx-proxy-manager.png
      - homepage.href={url}
      - homepage.ping={url}
      - homepage.description=Nginx
      - homepage.widget.type=npm
      - homepage.widget.url={url}
      - homepage.widget.username={email}
      - homepage.widget.password={password}
```

### Container Logs

[2024-06-02T21:00:34.156Z] debug: <npmProxyHandler> HTTTP 401 logging into npm api: [object Object]

### Browser Logs

GET 401 errors

### Troubleshooting

ping can reach container

-------------------------------------------------------------------------------------------

Resolution:

unlike the services yaml, the docker label password needs to be urlencoded? or without symbols, which was not always the case. I created a new user with view only rights for the hosts with a password using no symbols and it works again.
