### DISCUSSION TITLE
Errore API: ical: Unmapped proxy request.

### DISCUSSION THREAD

**Discussion by IoSonoAndreaZ** [gethomepage/homepage#3561] [Support] [answered]
### Description

Today I upgraded my docker setup with the latest version (v0.9.0 (7e50da8, 3 giu 2024) and I get an error with public ICAL calendar for italian holidays

### homepage version

v0.9.0 (7e50da8)

### Installation method

Docker

### Configuration

```yaml

 - type: ical # Show calendar events from another service
   url: https://calendar.google.com/calendar/ical/it.italian%23holiday%40group.v.calendar.google.com/public/basic.ics
   name: Festività Italiane # required - name for these calendar events
   color: blue # optional - defaults to pre-defined color for the service (zinc for ical)
   params: # optional - additional params for the service
     showName: true # optional - show name before event title in event line - defaults to false
```

### Container Logs

`[2024-06-03T06:25:09.543Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://192.168.178.24:2283/api/server-info/stats`

### Troubleshooting

I removed that section at the moment.
