### DISCUSSION TITLE
[v0.9.0] Glances bug with "cpu"

### DISCUSSION THREAD

**Discussion by dennyb** [gethomepage/homepage#3562] [Support] [answered]
### Description

Glances metric "cpu" occours into an API Error.
All other metrics works.

![image](https://github.com/gethomepage/homepage/assets/7408805/30f36873-72b3-422f-b657-fcafa23b0db8)

### homepage version

v0.9.0

### Installation method

Docker

### Configuration

```yaml
- srv01:
   - CPU Usage:
         widget:
             type: glances
             url: http
             username: xxx
             password: xxx
             metric: cpu
             chart: false
   - Memory Usage:
         widget:
             type: glances
             url: http
             username: xxx
             password: xxx
             metric: memory
             chart: false
   - Disk Usage:
         widget:
             type: glances
             url: http
             username: xxx
             password: xxx
             metric: fs:/
             chart: false
```

### Troubleshooting
```{"error":"Unmapped proxy request."}```
-
