### DISCUSSION TITLE
qBittorrent API error

### DISCUSSION THREAD

**Discussion by Tiritibambix** [gethomepage/homepage#357] [Support]
Hi.

Installed Homepage using docker-compose via portainer all up to date.

I get an ```API error``` for qBittorrent. Been reading previous issues here, looks like it should be working.

```
    - qBittorrent:
        icon: qbittorrent.png
        href: http://xxx.xxx.x.xxx:8992
        description: qbittorrent
        widget:
          type: qbittorrent
          url: http://xxx.xxx.x.xxx:8992
          username: ****
          password: ****
```

I get ```error: <qbittorrentProxyHandler> HTTP 403 logging in to qBittorrent.```

Also, how should I proceed if I use ```Bypass authentication for clients on localhost``` and ```Bypass authentication for clients in whitelisted IP subnets``` ? Leave username and password empty ?

Let me know if you need further informations.

Thanks for your help.

**Comment by JazzFisch** [comment]
We only attempt to log in to qBittorrent if sending a request to it results in a 403, so I'm not sure.  Can you check your qBittorrent logs?

**Comment by Tiritibambix** [comment]
Damn, I hate this. It is working now. I spent a couple hours tinkering with the config, stopping and restarting things before posting this. I can not say what was the problem... I HATE THIS xD

So anyway, as for this question:
> Also, how should I proceed if I use `Bypass authentication for clients on localhost` and `Bypass authentication for clients in whitelisted IP subnets` ? Leave username and password empty ?

What would be the healthiest way to do it ?

**Comment by JazzFisch** [comment]
qBittorrent isn't my primary torrent client, but here is the config I have for my local testing.  It is worth noting that all of my containers are on the same docker network and traffic to them from the "outside" world is proxied through Traefik.

Here is an obfuscated version of my config from `services.yaml`.
```yaml
    - qBittorrent:
        description: qbittorrent
        icon: qbittorrent.png
        href: https://qbittorrent.home.local
        server: my-local-docker
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: username
            password: password
```

Here is my config from qBittorrent's Tools => Options, Web UI tab.

![image](https://user-images.githubusercontent.com/3441425/194678348-cba12f4d-0ebc-4142-9c33-e803cc950a81.png)
