### DISCUSSION TITLE
Caddy metrics issue on 0.9.1

### DISCUSSION THREAD

**Discussion by lnlyssg** [gethomepage/homepage#3584] [Support] [answered]
### Description

The Caddy widget does not work under 0.9.1 but does work OK under 0.8.13. This is what the widget now shows:
<img width="366" alt="Screenshot 2024-06-04 at 11 08 44" src="https://github.com/gethomepage/homepage/assets/10902647/766be0ac-435f-422c-ba93-95acf45db92c">

I can't see any errors in the logs

### homepage version

v0.9.1 (19c3ac0, Jun 3, 2024)

### Installation method

Docker

### Configuration

```yaml
- Caddy:
        icon: caddy
        widget:
          type: caddy
          url: http://192.168.6.198:2019/
```

### Browser Logs

"Failed to load resource: the server responded with a status of 403 (Forbidden)" against  `api/services/proxy?group=Home&service=Caddy&endpoint=result` 

### Troubleshooting

curl within container works fine
ping works fine
Widget works fine after downgrading to 0.8.13:
<img width="366" alt="Screenshot 2024-06-04 at 11 06 10" src="https://github.com/gethomepage/homepage/assets/10902647/05e14b54-a4be-4b08-b7bf-5ab9a8dacfc2">
