### DISCUSSION TITLE
Omada API error in v0.9.1

### DISCUSSION THREAD

**Discussion by rookie50** [gethomepage/homepage#3585] [Support] [answered]
### Description

In the new version I got an API error:
{"error":"Unmapped proxy request."}

### homepage version

v0.9.1

### Installation method

Docker

### Configuration

```yaml
- Network:
    - Omada:
        icon: omada.svg
        href: "https://oc01.domain.me:8043"
        description: omada
        widget:
            type: omada
            url: "https://oc01.domain.me:8043"
            username:  "idiot"
            password:  "xtremeSavePWD"
            site: "Asylum"
            fields: ["connectedAp",  "activeUser", "alerts"]
```

### Container Logs

no log output

### Browser Logs

Network Answer 

{"error":"Unmapped proxy request."}

### Troubleshooting

v0.8.13 works with same settings.
