### DISCUSSION TITLE
Personal Favicon - not working if we use the local volume....

### DISCUSSION THREAD

**Discussion by jpquinta** [gethomepage/homepage#3601] [Support] [answered]
### Description

I'm trying to add my personal favicon like is described on your manuals on your page. But it's not working....

I'm using the setting path to a local image relative that I have on my docker settings, that is the same for my personal Background (and this one is working) but the image of the "favicon.ico" is never load.

What can be wrong?
<img width="532" alt="2024-06-06_11h03_36" src="https://github.com/gethomepage/homepage/assets/42496083/ce403cd6-7937-426d-9dd0-1e3ede978613">

Thank you
JQ

### homepage version

v0.9.1

### Installation method

Docker

### Configuration

```yaml
These are the settings of my volumes for my docker

volumes:
      - ./config:/app/config
      - ./public/images:/app/public/images
      - ./public/icons:/app/public/icons
```

### Troubleshooting

This is the result:
<img width="127" alt="image" src="https://github.com/gethomepage/homepage/assets/42496083/5f47f63c-a1ec-4cc1-9c0f-1f86ae42ca77">

<img width="401" alt="image" src="https://github.com/gethomepage/homepage/assets/42496083/7f9ed5b6-74b4-40f6-aca1-4ba8a9a3eb69">

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

To troubleshoot the issue with your favicon not loading, please follow these steps:

1. **Check the favicon file name and format**: Ensure that the favicon file is named `favicon.ico` and is in the correct ICO format. Some browsers may not recognize favicons in other formats or with different names.

2. **Verify the favicon path**: Based on your Docker volume settings, the favicon should be placed in the `./public/icons` directory on your host machine. Make sure the favicon is in this directory.

3. **Restart the container**: After adding or changing the favicon, you need to restart the Homepage container for the changes to take effect. This is a common requirement mentioned in the documentation.

4. **Clear browser cache**: Browsers aggressively cache favicons. Clear your browser cache or try accessing the page using a different browser or incognito mode to see if the favicon loads.

5. **Check browser console**: Open the browser's developer tools and check the console for any errors related to loading the favicon. This can provide clues if the file is not being found or if there's another issue.

6. **Inspect the page**: Right-click on the page and select "Inspect" or "View Page Source" to check the HTML head section. Look for the `<link rel="icon" href="...">` tag and verify that the path to the favicon is correct.

7. **Check file permissions**: Ensure that the favicon file has the correct permissions and is readable by the container.

8. **Review the documentation**: Double-check the [Homepage documentation](https://gethomepage.dev/latest/configs/settings) to ensure you haven't missed any steps specific to setting up a custom favicon.

If you've followed all these steps and the favicon still isn't loading, please provide additional information such as any error messages in the browser console or container logs, as this can help further diagnose the issue.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by 777Arch** [comment]
Got the same problem.

**Comment by Panichdi** [comment]
Got the same problem.

**Comment by amanger-qual** [comment]
Same here!

**Comment by truhponen** [comment]
Hi,

I had similar issues but after mapping svg-file as favicon started working.
`favicon: /images/kotimme.svg`

After this change I still had problems with my Android-phone. When I added homepage to start screen it used Homepage-icon. To fix this I mapped my whole favicon set (cannot remember which online service I used) to Homepage-icons (which are in root of public folder).

My Docker compose with mappings:
 
```
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /config-local/homepage/config:/app/config # Make sure your local config directory exists
      - /config-local/homepage/icons:/app/public/icons
      - /config-local/homepage/images:/app/public/images
      - /config-local/homepage/favicon/android-chrome-192x192.png:/app/public/android-chrome-192x192.png
      - /config-local/homepage/favicon/android-chrome-512x512.png:/app/public/android-chrome-512x512.png
      - /config-local/homepage/favicon/apple-touch-icon.png:/app/public/apple-touch-icon.png
      - /config-local/homepage/favicon/favicon-16x16.png:/app/public/favicon-16x16.png
      - /config-local/homepage/favicon/favicon-32x32.png:/app/public/favicon-32x32.png
      - /config-local/homepage/favicon/favicon.ico:/app/public/homepage.ico
      - /config-local/homepage/favicon/mstile-144x144.png:/app/public/mstile-144x144.png
      - /config-local/homepage/favicon/mstile-150x150.png:/app/public/mstile-150x150.png
      - /config-local/homepage/favicon/mstile-310x150.png:/app/public/mstile-310x150.png
      - /config-local/homepage/favicon/mstile-310x310.png:/app/public/mstile-310x310.png
      - /config-local/homepage/favicon/mstile-70x70.png:/app/public/mstile-70x70.png
      - /config-local/homepage/favicon/safari-pinned-tab.svg:/app/public/safari-pinned-tab.svg
      - /config-local/homepage/favicon/site.webmanifest:/app/public/site.webmanifest
```
