### DISCUSSION TITLE
Special characters in service titles

### DISCUSSION THREAD

**Discussion by CFenner** [gethomepage/homepage#3608] [Support]
### Description

When using special characters in service titles, they are not displayed correctly.

<img width="416" alt="Bildschirmfoto 2024-06-07 um 09 41 54" src="https://github.com/gethomepage/homepage/assets/9592452/ea06fa1b-e191-4164-92d0-e725a812f350">

### homepage version

v0.9.2 (af16956, Jun 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- "Wasserzähler OG":
        icon: mdi-speedometer
    - "Wasserzähler EG":
        icon: mdi-speedometer
    - "Wasserzähler UG":
        icon: mdi-speedometer
    - "Wasserzähler Garten":
        icon: mdi-speedometer
```

### Troubleshooting

n/a
