### DISCUSSION TITLE
Please provide support for Wg-Easy servers without password

### DISCUSSION THREAD

**Discussion by KuuDS** [gethomepage/homepage#3610] [Support]
### Description

Currently, the wg-easy widget uses `POST /api/session` to perform login validation. Therefore, it is not possible to support password-less Wg-Easy. 
I reviewed the wg-easy API and found that it provides a `GET /api/session` request to retrieve the authentication status of the current session. 
For an wg-easy service without a set login password, this request defaults to returning `{ "requiresPassword": false, "authenticated": true }`.

We can prioritize calling the GET method during login, and then judge whether to proceed with password authentication based on the returned 'authenticated' value. 
In [my fork repository](https://github.com/KuuDS/homepage/commit/0c626ecdac202627eb1b91a1d5f1e0f34f884c15), I implemented this simply and verified it.

### homepage version

v.0.9.1

### Installation method

Docker

### Configuration

```yaml
---
- My Group:
    - wg_test_no_password:
        href: http://192.168.x.1:51821
        siteMonitor: http://192.168.x.1:51821
        widget:
            type: wgeasy
            url: http://192.168.x.1:51821
```

### Troubleshooting

$ docker exec homepage  ping 192.168.x.1
PING 192.168.x.1 (192.168.x.1): 56 data bytes
64 bytes from 192.168.x.1: seq=0 ttl=61 time=18.444 ms
64 bytes from 192.168.x.1: seq=1 ttl=61 time=21.302 ms
64 bytes from 192.168.x.1: seq=2 ttl=61 time=21.891 ms
64 bytes from 192.168.x.1: seq=3 ttl=61 time=91.556 ms
64 bytes from 192.168.x.1: seq=4 ttl=61 time=19.474 ms
64 bytes from 192.168.x.1: seq=5 ttl=61 time=22.783 ms
64 bytes from 192.168.x.1: seq=6 ttl=61 time=23.059 ms
