### DISCUSSION TITLE
Synology service (same host homepage is running on) is having issues (2FA)

### DISCUSSION THREAD

**Discussion by begunfx** [gethomepage/homepage#3611] [Support]
### Description

I have three synology servers.   I tried to set all three up as services on homepage.  All three of them have users that only have access to the DSM and 2FA authentication is turned off.  Two of them are working without issue.  However, the one server (datavault) that is hosting the homepage container is not.  When I first create the user and add the service it connects without issue and displays stats as expected.  After about 15 minutes I get an API error.  When I look at the logs I get the following error:

> [2024-06-08T01:01:43.153Z] warn: <synologyProxyHandler> Unable to call https://datavault/webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 407, error: Authentication failed. 2FA enabled..
[2024-06-08T04:16:31.510Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2024-06-08T04:16:31.511Z] warn: <synologyProxyHandler> Unable to call https://datavault/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info.  code: 407, error: Authentication failed. 2FA enabled..
[2024-06-08T04:16:31.588Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2024-06-08T04:16:31.589Z] warn: <synologyProxyHandler> Unable to call https://datavault/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info&type="storage".  code: 407, error: Authentication failed. 2FA enabled..
[2024-06-08T04:16:31.743Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2024-06-08T04:16:31.744Z] warn: <synologyProxyHandler> Unable to call https://datavault/webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 407, error: Authentication failed. 2FA enabled..
[2024-06-08T04:25:38.518Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2024-06-08T04:25:38.519Z] warn: <synologyProxyHandler> Unable to call https://datavault/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info&type="storage".  code: 407, error: Authentication failed. 2FA enabled..
[2024-06-08T04:25:38.571Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2024-06-08T04:25:38.572Z] warn: <synologyProxyHandler> Unable to call https://datavault/webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 407, error: Authentication failed. 2FA enabled..
[2024-06-08T04:25:38.573Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2024-06-08T04:25:38.573Z] warn: <synologyProxyHandler> Unable to call https://datavault/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info.  code: 407, error: Authentication failed. 2FA enabled..

Here's the services.yaml for my servers:
`
- Servers:
    - MediaVault:
        icon: synology.svg
        href: https://mediavault.mydomain.com
        widget:
          type: diskstation
          url: https://mediavault
          username: xxxxx
          password: xxxxx
          volume: volume_1 # optional

    - DataVault:
        icon: synology.svg
        href: https://datavault.mydomain.com
        widget:
          type: diskstation
          url: https://datavault
          username: xxxxxx
          password: xxxxxx
          volume: volume_1 # optional
        
    - TMVault:
        icon: synology.svg
        href: https://tmvault.mydomain.com
        widget:
          type: diskstation
          url: https://tmvault
          username: xxxxx
          password: xxxxxx
          volume: volume_1 # optional`

I can confirm without a doubt that 2FA is disabled for that user.  I tried disabling 2FA for all users, shortening the password, removing special characters.  I also tried changing the URL to: HTTP://localhost/ and HTTP://127.0.0.1/.  I also tried both HTTP and HTTPS.  I also tried restarting the container and re-deploying the stack.

Again, just to be clear, when I first add the DSM only user it works for about 15 minutes, then after that I get the errors and cannot get it to work again.  

Any ideas would be greatly appreciated.

### homepage version

v0.9.2

### Installation method

Docker

### Configuration

```yaml
version: "3.9"
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 3550:3000
    volumes:
      - /volume1/docker/homepage:/app/config:rw
      - /volume1/docker/homepage/public:/app/public/images:rw
      - /volume1/docker/homepage/public/icons:/app/public/icons:rw
      - /var/run/docker.sock:/var/run/docker.sock
```

### Troubleshooting

See above.
