### DISCUSSION TITLE
[Feature Request] Shelly Service Widget

### DISCUSSION THREAD

**Discussion by MatthiasOs** [gethomepage/homepage#3612] [Feature Requests]
### Description

Hello,

I have multiple shellys in my network and would like to display some information from them on my dashboard.
Since the Custom Widget API seems to not work (see discussion #2036 ) I implemented a custom shelly service widget:
https://github.com/gethomepage/homepage/compare/main...MatthiasOs:homepage:shelly?expand=1
(first time coding in js)

There are a lot of different shellys on the market, so as of right now the widget only works with some swiches (i.e. 1, 1PM), see readme file for more info.
Dashboard
![grafik](https://github.com/gethomepage/homepage/assets/36775764/8c59ea2c-f806-4123-86c2-8dc27e54d599)
The Shelly Pro3EM is not a switch and not yet supported by the widget.
The Shelly RGBW2 is not a Gen 2 device, thats why an error is displayed.

Is anyone interested this widget? Accoring to the [development readme](https://github.com/gethomepage/homepage/blob/main/docs/more/development.md) 10 up-votes are needed.

**Comment by MatthiasOs** [comment]
Just FYI I got it working with the custom API aswell. Even though the code is not very readable and has some contraints:
#### Shelly RGBW2 (Gen1)
```yaml
    - ShellyName:
        href: http://192.168.178.7
        description: Shelly RGBW2
        icon: si-shelly
        ping: http://192.168.178.7
        widget:
           type: customapi
           display: list
           url: http://192.168.178.7/status
           method: GET
           mappings:
              - field:
                  lights:
                     0: ison
                label: "Status"
                remap:
                 - value: true
                   to: On
                 - value: false
                   to: Off
```
#### Shelly Plus1 (Gen2)
```yaml
    - ShellyName:
        href: http://192.168.178.6
        description: Shelly Plus1
        icon: si-shelly
        ping: http://192.168.178.6
        widget:
           type: customapi
           display: list
           url: http://192.168.178.6/rpc/Shelly.GetStatus
           method: GET
           mappings:
              - field:
                  'switch:0': output
                label: "Status"
                remap:
                 - value: true
                   to: On
                 - value: false
                   to: Off
```
#### Shelly Plus1PM (Gen2)
```yaml
    - ShellyName:
        href: http://192.168.178.5
        description: Shelly Plus1PM
        icon: si-shelly
        ping: http://192.168.178.5
        widget:
           type: customapi
           display: list #looks better imho
           url: http://192.168.178.5/rpc/Shelly.GetStatus
           method: GET
           mappings:
              - field:
                  'switch:0': apower
                label: Production
                suffix: W
                format: number
              - additionalField:
                  field: #sadly no label possibible for this additionalField
                   'switch:0': output
                  remap:
                   - value: true
                     to: On
                   - value: false
                     to: Off
```
#### Shelly Pro3EM (Gen2)
```yaml
    - Energy Manager:
        href: http://192.168.178.4
        description: Shelly Pro3EM
        icon: si-shelly
        ping: http://192.168.178.4
        widget:
           type: customapi
           display: list
           url: http://192.168.178.4/rpc/Shelly.GetStatus
           method: GET
           mappings:
            - field:
                 'em:0': total_act_power
              label: Total Consumption
              format: number
              suffix: W
```

Sadly it doesnt seem possible to give the additionalField a seperat label:
![grafik](https://github.com/gethomepage/homepage/assets/36775764/26c6a50c-b8fe-474c-812f-f38a3ec01e20)

**Reply by Titanmarcel** [reply]
Hello everyone!

I’m using parts of your implementation with a Shelly Plug S 3Gen to monitor the wattage usage of my home server. The HTML request http://192.168.178.68/rpc/Switch.GetStatus?id=0 returns some values, which works fine for me. However, I’m having trouble accessing the energy.total value.

Here’s an example response I’m receiving:
`{"id":0, "source":"HTTP_in", "output":true, "apower":20.6, "voltage":222.9, "freq":50.0, "current":0.128, "aenergy":{"total":82.423,"by_minute":[425.380,425.380,425.380],"minute_ts":1736786220}, "ret_aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1736786220},"temperature":{"tC":15.2, "tF":59.4}}`

I’ve tried various formats, but I’m still unable to retrieve the aenergy.total value. Does anyone have any suggestions on how to properly extract this data?

Thanks in advance!

**Reply by MatthiasOs** [reply]
Should work like this:
```
           mappings:
            - field:
                 'aenergy': total
              format: number
```

**Reply by Titanmarcel** [reply]
Thanks for your reply! But this doesn't work.

` mappings:
              - field:
                  'switch:0': apower
                label: Watt
                format: number
                suffix: W
              - field:
                  'aenergy': total
                format: number`

![Bildschirmfoto 2025-01-16 um 09 38 53](https://github.com/user-attachments/assets/dabc4e84-f4e0-4749-86bc-b3d6bcc1b24d)

I don't really get I but I think it must have something to do with with "{}" brackets.

**Reply by MatthiasOs** [reply]
according to the json, "apower" and "aenergy" is on the same hierarchy.
But your mapping is different:
```
 - field: 
 'switch:0': apower 
```
```
 - field: 
 'aenergy': total 
```
The second one is missing 'switch:0'
should be something like this:
```
 - field: 
 'switch:0':
  'aenergy': total 
```
I only got a Shelly Plus1 atm, but i did something similar with the temperature:
```
           mappings:
              - field:
                  'switch:0': output
                label: "Status"
                remap:
                 - value: true
                   to: On
                 - value: false
                   to: Off
              - field:
                  'switch:0':
                      'temperature': tC
                label: "Temp"
                format: number
```
my json file looks something like this:
```
{...
    "switch:0": {
        "id": 0,
        "output": false,
        "source": "SHC",
        "temperature": {
            "tC": 41.6,
            "tF": 106.9
        }
...}
```

Hope that helps.
