### DISCUSSION TITLE
ghcr.io/gethomepage/homepage:latest is pulling v0.8.3

### DISCUSSION THREAD

**Discussion by winzlocom** [gethomepage/homepage#3623] [Support]
### Description

In creating a docker compose file to run generate, i discovered that the latest tag is not pulling the latest version. 

### homepage version

0.8.3

### Installation method

Docker

### Configuration

```yaml
services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/appdata/homepage/config:/app/config
      - $DOCKERDIR/appdata/homepage/images:/app/public/images
    env_file:
      - $DOCKERDIR/.env
    environment:
      LOG_LEVEL: debug
      TZ: $TZ
      PUID: $PUID
#      PGID: $PGID
      PGID: 999
```

### Browser Logs

Listening on port 3000

### Troubleshooting

If I explicitly pull v0.9.2, I get that version

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that you are experiencing an issue where pulling the `latest` tag of the `ghcr.io/gethomepage/homepage` Docker image does not give you the most recent version of the application. Instead, you have to explicitly pull version `v0.9.2` to get the latest release.

This could be due to a few reasons:

1. The `latest` tag has not been updated to point to the most recent release. Docker image tags are mutable, and it's up to the maintainers of the repository to ensure that the `latest` tag is updated whenever a new version is released.

2. There might be a caching issue on your Docker host. If you have previously pulled the `latest` tag, your Docker may be using the locally cached version instead of checking for updates from the registry.

To resolve this issue, you can try the following steps:

- **Force Pull the Latest Image**: Use the `docker pull` command with the `--no-cache` option to force Docker to re-pull the image from the registry and ignore any locally cached versions.
  
  ```bash
  docker pull --no-cache ghcr.io/gethomepage/homepage:latest
  ```

- **Check for Image Updates**: Ensure that you are connected to the internet and that there are no issues with the Docker registry that might prevent you from pulling the latest image.

- **Contact the Maintainers**: If the issue persists, it may be worth reaching out to the maintainers of the Homepage project to inquire about the status of the `latest` tag. You can do this by opening an issue on the project's GitHub repository.

Remember to replace the `latest` tag with the specific version tag `v0.9.2` in your Docker Compose file if you want to ensure you are using that version:

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.2
    # ... rest of your configuration
```

Lastly, ensure that your `.env` file contains the correct values for `PUID`, `PGID`, and `TZ` as these are being used in your Docker Compose file.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
