### DISCUSSION TITLE
Glances widget unable to show data

### DISCUSSION THREAD

**Discussion by cmdshft** [gethomepage/homepage#3626] [Support] [answered]
### Description

Large red error box appears when adding the widget for Glances. Glances is installed in docker, running and I can see stats by opening up the web page for it.

![Screenshot 2024-06-11 223002](https://github.com/gethomepage/homepage/assets/8571823/7e1e6edc-6b15-471a-9050-32bc5c10bbb5)

### homepage version

0.9.2

### Installation method

Docker

### Configuration

```yaml
- System Info:
        href: http://10.0.0.15:61208
        widget:
          type: glances
          url: http://10.0.0.15:61208
          metric: info
```

### Troubleshooting

pi@raspberrypi4b:~ $ curl -L -k http://10.0.0.15:61208/api/cpu
{"detail":"Not Found"}

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the context from the sources, it seems that the issue might be related to the configuration of the Glances widget or the Glances API endpoint itself. Here are a few steps you can take to troubleshoot the issue:

1. **Check the Glances Version**: Ensure that Glances is running in "web server" mode and that the API is enabled. Since you are using Homepage version 0.9.2, if you are also using Glances version 4 or higher, you need to specify the version in your widget configuration. Add `version: 4` to your widget configuration if it's missing.

2. **Correct API Endpoint**: The error message from the `curl` command suggests that the API endpoint might be incorrect. The correct API endpoint for CPU information in Glances is usually `/api/3/cpu` or `/api/3/all` if you are using Glances version 3. For Glances version 4, the endpoint might be different. Check the [Glances documentation](https://glances.readthedocs.io/en/latest/api/README.html) for the correct API endpoints.

3. **Remove Trailing Slashes**: As mentioned in the troubleshooting guide, ensure that the URL in the widget configuration does not end with a trailing slash or other API path, as each widget will handle the path on its own.

4. **Check Network Connectivity**: Verify that the Homepage installation can connect to the Glances service. You can do this by pinging the Glances service from the Homepage container.

5. **Review Container Logs**: Check the logs of the Homepage container for any error messages that might indicate what the issue is. You can view the logs by running `docker logs <container_name>`.

6. **Browser Console**: Check the browser console for any errors when loading the widget. This can sometimes provide additional clues.

Here is an updated configuration snippet that includes the version:

```yaml
- System Info:
    href: http://10.0.0.15:61208
    widget:
      type: glances
      url: http://10.0.0.15:61208
      metric: info
      version: 4  # Add this line if Glances is version 4 or higher
```

If after these steps the issue persists, you may want to seek further assistance by using the Homepage AI Bot, opening a GitHub discussion, or checking the [#ai-support channel on Discord](https://discord.com/channels/1019316731635834932/1177885603552038993).

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
