### DISCUSSION TITLE
I'm unable to obtain the desidered layout

### DISCUSSION THREAD

**Discussion by IoSonoPiero** [gethomepage/homepage#3629] [Support]
### Description

Hello people, sorry to bother you, but it's days I'm fighting with the layout.
I want on my homepage 5 blocks in total:

- 3 blocks in the upper part
- 2 blocks in the bottom

This is my settings.yaml file:
```
---
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# You can show all docker stats expanded
#showStats: true

layout:
  Web:
    icon: /icons/web.svg
    style: column
    column: 3
  Monitoraggio:
    icon: /icons/monitoring.svg
    #style: column
  Utilità:
    icon: /icons/utility.svg
    #style: column
  Server Locale:
    style: column
    column: 2
    icon: /icons/server.svg
  Server Oracle:
    icon: oracle
    style: row

language: it

headerStyle: boxed

statusStyle: "dot"

background:
  image: https://images.unsplash.com/photo-1713970700051-556d05c59fce
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
```

![Schermata_20240613_005952](https://github.com/gethomepage/homepage/assets/82404704/9f3d7373-35b9-4485-bd72-79c385f7b64a)

As you can see, I got 4 columns in the upper and 1 in the bottom.
Any help, please?

### homepage version

v0.9.2 (af16956, 6 giu 2024)

### Installation method

Docker

### Troubleshooting

I tried to change settings in the layout, playing with columns and rows, but without success.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the context from the documentation, it seems like there might be a typo in your `settings.yaml` file. You've used `column: 3` and `column: 2` under the `Web` and `Server Locale` sections, respectively, but according to the documentation, the correct key should be `columns` (plural), not `column`.

Here's how you can adjust your `settings.yaml` file to achieve the desired layout:

```yaml
layout:
  Web:
    icon: /icons/web.svg
    style: row
    columns: 3
  Monitoraggio:
    icon: /icons/monitoring.svg
    style: row
    columns: 3
  Utilità:
    icon: /icons/utility.svg
    style: row
    columns: 3
  Server Locale:
    style: row
    columns: 2
    icon: /icons/server.svg
  Server Oracle:
    icon: oracle
    style: row
    columns: 2
```

Make sure that each section that you want to display as a block has the `style` set to `row` and the correct number of `columns` specified. For the upper part, you want three blocks, so you should set `columns: 3` for each section you want in the upper part. For the bottom part, since you want two blocks, you should set `columns: 2` for each section you want in the bottom part.

Remember to regenerate the static HTML after making changes to the `settings.yaml` file. This can usually be done by refreshing the page or restarting the container, depending on how Homepage is set up to regenerate content.

Please try making these adjustments and see if it resolves your issue. If you continue to have trouble, please provide any additional details or error messages you might be encountering.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
