### DISCUSSION TITLE
[Feature Request]  Add `mobile_href` to services to allow app deep linking if mobile browser detected

### DISCUSSION THREAD

**Discussion by jonathanjsimon** [gethomepage/homepage#3636] [Feature Requests]
### Description

It would be great if there was some way to open a different link on mobile for a given service. This would allow me to deep link into the native app for a given service if using Homepage from my phone and to open the service's web interface if browsing on my computer.

For example, `services.yaml`:

```yaml
- Services:
  - Automation:
      mobile_href: homeassistant://navigate
      href: https://myhomeassistanturl.com
      widget:
        type: homeassistant
        url: https://myhomeassistanturl.com
        key: foobarbaz
```
