### DISCUSSION TITLE
Services and Widgets Not Loading Data in Docker Version v0.9.2

### DISCUSSION THREAD

**Discussion by scottgigawatt** [gethomepage/homepage#3637] [Support] [answered]
### Description

The services and widgets on my homepage are not loading data. Instead, they display variable references such as:

	•	common.number resources.cpu
	•	common.bytes resources.free
	•	common.bytes resources.free

This issue occurs with any widget that loads data from a service. I encountered this problem on both v0.9.2 and the previous version v0.9.1.
<img width="1284" alt="Screenshot 2024-06-13 at 23 21 05" src="https://github.com/gethomepage/homepage/assets/16313565/16444045-3041-4cf3-95d2-d92c4400231f">
<img width="1248" alt="Screenshot 2024-06-13 at 23 23 20" src="https://github.com/gethomepage/homepage/assets/16313565/f15e7603-6346-4064-994b-604e71c8fef6">

### homepage version

v0.9.2

### Installation method

Docker

### Configuration

I am running the Docker version v0.9.2. My configuration files include bookmarks.yaml, services.yaml, settings.yaml, widgets.yaml, docker.yaml, and kubernetes.yaml. The issue persists regardless of changes made to these files.

#### settings.yaml
```yaml
title: {{HOMEPAGE_VAR_TITLE}}
favicon: https://img.icons8.com/?size=100&id=32558&format=png&color=000000
color: slate
background: /images/canyon-waterfall.gif
backgroundOpacity: 0.6
cardBlur: md # or sm, lg
headerStyle: boxedWidgets
useEqualHeights: true
disableCollapse: true
hideVersion: false
showStats: true
statusStyle: "dot"
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Media:
    style: row
    columns: 3
  Data:
    style: row
    columns: 2
  Downloads:
    style: row
    columns: 2
```
#### services.yaml

```yaml
---
#
# For more information see: https://gethomepage.dev/latest/configs/services
#

- Media:
    - Plex:
        id: 100
        icon: plex.svg
        href: https://plex.{{HOMEPAGE_VAR_HOST_URL}}
        description: Plex Media Server
        widget:
          type: plex
          fields: ["streams", "movies", "tv"]
          url: {{HOMEPAGE_VAR_PLEX_URL}}
          key: {{HOMEPAGE_VAR_PLEX_TOKEN}}

    - Radarr:
        icon: radarr.svg
        href: https://radarr.{{HOMEPAGE_VAR_HOST_URL}}
        description: Movies management
        container: radarr-latest
        widget:
          type: radarr
          fields: ["wanted", "queued"]
          url: {{HOMEPAGE_VAR_RADARR_URL}}
          key: {{HOMEPAGE_VAR_RADARR_KEY}}

    - Sonarr:
        icon: sonarr.svg
        href: https://sonarr.{{HOMEPAGE_VAR_HOST_URL}}
        description: Series management
        container: sonarr-latest
        widget:
          type: sonarr
          fields: ["wanted", "queued"]
          url: {{HOMEPAGE_VAR_SONARR_URL}}
          key: {{HOMEPAGE_VAR_SONARR_KEY}}

    - Bazarr:
        icon: bazarr.svg
        href: https://bazarr.{{HOMEPAGE_VAR_HOST_URL}}
        description: Subtitles management
        container: bazarr-latest
        widget:
          type: bazarr
          url: {{HOMEPAGE_VAR_BAZARR_URL}}
          key: {{HOMEPAGE_VAR_BAZARR_KEY}}

    - Readarr:
        icon: readarr.svg
        href: https://readarr.{{HOMEPAGE_VAR_HOST_URL}}
        description: Ebooks management
        container: readarr-develop
        widget:
          type: readarr
          url: {{HOMEPAGE_VAR_READARR_URL}}
          key: {{HOMEPAGE_VAR_READARR_KEY}}

    - Overseerr:
        icon: overseerr.svg
        href: https://overseerr.{{HOMEPAGE_VAR_HOST_URL}}
        description: Requests management
        container: overseerr-latest
        widget:
          type: overseerr
          url: {{HOMEPAGE_VAR_OVERSEERR_URL}}
          key: {{HOMEPAGE_VAR_OVERSEERR_KEY}}

- Data:
    - Calendar:
      widget:
        type: calendar
        firstDayInWeek: sunday
        view: monthly
        maxEvents: 10
        showTime: true
        integrations:
          - type: radarr
            service_group: Media
            service_name: Radarr
            color: amber
            params:
              unmonitored: true
          - type: sonarr
            service_group: Media
            service_name: Sonarr
            color: teal
            params:
              unmonitored: true
          - type: readarr
            service_group: Media
            service_name: Readarr
            color: pink
            params:
              unmonitored: true

    - Tautulli:
        icon: tautulli.svg
        href: https://tautulli.{{HOMEPAGE_VAR_HOST_URL}}
        description: Plex monitoring
        container: tautulli-latest
        widget:
          type: tautulli
          url: {{HOMEPAGE_VAR_TAUTULLI_URL}}
          key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false

- Downloads:
    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.{{HOMEPAGE_VAR_HOST_URL}}
        description: Indexers management
        container: prowlarr-latest
        widget:
          type: prowlarr
          url: {{HOMEPAGE_VAR_PROWLARR_URL}}
          key: {{HOMEPAGE_VAR_PROWLARR_KEY}}

    - qBittorrent:
        icon: qbittorrent.svg
        href: https://qbittorrent.{{HOMEPAGE_VAR_HOST_URL}}
        description: Torrents management
        container: qbittorrent-latest
        widget:
          type: qbittorrent
          url: {{HOMEPAGE_VAR_QBITTORRENT_URL}}
          username: {{HOMEPAGE_VAR_QBITTORRENT_USER}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASS}}
```

For reference, my configuration files are available [here](https://github.com/scottgigawatt/plundarr/tree/main/config/homepage), the Docker compose file [here](https://github.com/scottgigawatt/plundarr/blob/main/docker-compose.yml#L333-L396), and the env file section [here](https://github.com/scottgigawatt/plundarr/blob/main/example.env#L150-L187).

### Container Logs

[homepage-latest.log](https://github.com/user-attachments/files/15831147/homepage-latest.log)

### Browser Logs

The API calls seem to be working in the chrome network inspector

### Troubleshooting

1. Verified connectivity to apps (Sonarr, Radarr, etc.) running through a VPN container (Gluetun) by exec'ing into the homepage container:
   ```bash
   /app # curl -L -k 'http://radarr:8989/api/v3/queue?apikey=abc123'
   {
     "page": 1,
     "pageSize": 10,
     "sortKey": "timeleft",
     "sortDirection": "descending",
     "totalRecords": 0,
     "records": []
   }
   ```
2. Renamed all configuration files to `config-file.bak.yaml` and let the server generate fresh files. The resources widgets still did not show the correct data.
3. Noticed that sometimes, during container startup, the page partially loads and shows widget data. However, after a hard refresh, the widgets fail to load correctly while the settings and wallpaper load properly.

For reference, my configuration files are available [here](https://github.com/scottgigawatt/plundarr/tree/main/config/homepage), the Docker compose file [here](https://github.com/scottgigawatt/plundarr/blob/main/docker-compose.yml#L333-L396), and the env file section [here](https://github.com/scottgigawatt/plundarr/blob/main/example.env#L150-L187).
