### DISCUSSION TITLE
Conflict between minecraft widgets

### DISCUSSION THREAD

**Discussion by henriquesw** [gethomepage/homepage#3638] [Support] [answered]
### Description

I tried to add two minecraft servers so I can check the status.

Both servers are in the same machine but with different ports.

I notice the second widget follow the status of the first widget.

Can I use two of the same widgets together?

Server status with only the 25565 online.
![image](https://github.com/gethomepage/homepage/assets/28535929/8a71c577-1f63-4489-a677-6f163bbbf646)
 

### homepage version

v0.9.2

### Installation method

Other (please describe above)

### Configuration

```yaml
- Game Servers Status:
    - Minecraft Server:
        icon: minecraft.svg
        description: Minecraft server port 25565
        widget:
          type: minecraft
          url: udp://192.168.0.100:25565

    - Minecraft Server:
        icon: minecraft.svg
        description: Minecraft server port 25566
        widget:
          type: minecraft
          url: udp://192.168.0.100:25566
```

### Troubleshooting

Run the server on port 25565 with server on port 25566 stoped.
Both show as running.
