### DISCUSSION TITLE
[Feature Request] Add url option for logo widget

### DISCUSSION THREAD

**Discussion by xJylin** [gethomepage/homepage#3643] [Feature Requests]
### Description

Would be nice to have an optional url option for the logo widget used in headers that turns it into a hyperlink.

example:
widgets.yaml
````
- logo:
    icon: unraid
    url: https://myunraid.net/
- logo:
    icon: home-assistant
    url: https://myhomeassistant:8123/
- logo:
    icon: n8n
    url: https://myn8n.net/
````
![image](https://github.com/gethomepage/homepage/assets/53369252/2a0e66fe-389d-4d71-aa2a-cc4d8ad3cac0)

This would basically allow to have permanently pinned quick-shortcuts regardless on which tab you are currently on.

Edit: Closed this because request already exists #2647
