### DISCUSSION TITLE
PiHole widget not working

### DISCUSSION THREAD

**Discussion by prkrln** [gethomepage/homepage#3649] [Support] [answered]
### Description

Hi, I'm running PiHole and Homepage on the same machine in docker and when trying to use the widget i get this error.
![image](https://github.com/gethomepage/homepage/assets/137010852/cbfc8b99-9180-436d-b484-0f704e83ee52)

Here is my services.yaml for PiHole.
```
    - Pi-hole:
        icon: pi-hole.svg
        href: http://pihole.home.arpa
        description: DNS Server And Add Blocker
        widget:
          type: pihole
          url: http://192.168.0.10:8090
          version: 6 # required if running v6 or higher, defaults to 5
          key: (apikey) # optional
```

When going to http://192.168.0.10:8090/admin/api.php on my normal browser I can see this.
```
{
  "domains_being_blocked": 902509,
  "dns_queries_today": 39052,
  "ads_blocked_today": 6266,
  "ads_percentage_today": 16.045273,
  "unique_domains": 3255,
  "queries_forwarded": 28213,
  "queries_cached": 4193,
  "clients_ever_seen": 13,
  "unique_clients": 13,
  "dns_queries_all_types": 39052,
  "reply_UNKNOWN": 399,
  "reply_NODATA": 9637,
  "reply_NXDOMAIN": 2064,
  "reply_CNAME": 12890,
  "reply_IP": 13009,
  "reply_DOMAIN": 62,
  "reply_RRNAME": 0,
  "reply_SERVFAIL": 0,
  "reply_REFUSED": 0,
  "reply_NOTIMP": 0,
  "reply_OTHER": 0,
  "reply_DNSSEC": 3,
  "reply_NONE": 0,
  "reply_BLOB": 988,
  "dns_queries_all_replies": 39052,
  "privacy_level": 0,
  "status": "enabled",
  "gravity_last_updated": {
    "file_exists": true,
    "absolute": 1718569766,
    "relative": {
      "days": 0,
      "hours": 19,
      "minutes": 18
    }
  }
}
```

But when I go to http://192.168.0.10:8090/admin/api.php on a different browser where I have never been signed into PiHole it is blank.
I can ping PiHole from the container but curl just returns empty.

I've been trying to fix this all day but I'm not really getting anywhere with it.

### homepage version

v0.9.2

### Installation method

Docker

### Configuration

```yaml
- Pi-hole:
        icon: pi-hole.svg
        href: http://pihole.home.arpa
        description: DNS Server And Add Blocker
        widget:
          type: pihole
          url: http://192.168.0.10:8090
          version: 6 # required if running v6 or higher, defaults to 5
          key: (apikey) # optional
```

### Troubleshooting

Ping works.
```
# ping 192.168.0.10:8090
PING 192.168.0.10:8090 (192.168.0.10): 56 data bytes
64 bytes from 192.168.0.10: seq=0 ttl=64 time=0.116 ms
64 bytes from 192.168.0.10: seq=1 ttl=64 time=0.128 ms
64 bytes from 192.168.0.10: seq=2 ttl=64 time=0.128 ms
64 bytes from 192.168.0.10: seq=3 ttl=64 time=0.118 ms
^C
--- 192.168.0.10:8090 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.116/0.122/0.128 ms
```

Curl returns blank.
```
# curl -L -k 192.168.0.10:8090/admin/api.php
[]
```
