### DISCUSSION TITLE
layout of widget.yaml

### DISCUSSION THREAD

**Discussion by Beaver-A** [gethomepage/homepage#3650] [Support]
### Description

Hello everyone,
I try to figure out how to modify the order for the widget.yaml. The ressource widget is always the first one. I use, datetime, ressource, weather and search widget.
How is it possible to modify the order of them?
 Furthermore, there is a way to put them in two row ? 

Thank you very much for your help.

### homepage version

0.9.2

### Installation method

Docker

### Configuration

```yaml
- datetime:
    text_size: xl
    locale: fr
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23

- search:
    provider: duckduckgo
    target: _blank

- openmeteo:
    label: Paris # optional
    latitude: 48.866667
    longitude: 2.333333
    timezone: Europe/Paris 
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- resources:
    label: System
    cpu: true
    memory: true
    cputemp: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    uptime: true
    units: metric # only used by cpu temp
    refresh: 3000 # optional, in ms


- resources:
    label: Disk
    expanded: true
    disk:
      - /
      - /dev/sda1
      - /dev/sdb1
```

### Troubleshooting

na
