### DISCUSSION TITLE
Homepage not starting when PUID and GUID set

### DISCUSSION THREAD

**Discussion by ChoosenMEME** [gethomepage/homepage#3654] [Support] [answered]
### Description

When i set PGID and PUID the container will instantly go unhealthy, and disk is spinning until i stop the container again. This does not happen when those variables are not set, then it starts like expected, and disks stop spinning.

I also checked if permissions might be wrong, but user and group docker-user has rwx

```
docker-user@docker:/mnt/data$ id docker-user
uid=3001(docker-user) gid=3001(docker-user)

docker-user@docker:/mnt/data$ getfacl homepage/
# file: homepage/
# owner: docker-user
# group: docker-user
user::rwx
user:root:rwx
user:docker-user:rwx
group::rwx
group:docker-user:rwx
mask::rwx
other::rwx
default:user::rwx
default:user:root:rwx
default:user:docker-user:rwx
default:group::rwx
default:group:docker-user:rwx
default:mask::rwx
default:other::---
```

### homepage version

0.9.2

### Installation method

Docker

### Configuration

```yaml
docker-compose.yml

services:  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /mnt/data/homepage:/app/config
    networks:
      - proxy
    environment:
      PUID: 3001
      PGID: 3001
      LOG_LEVEL: debug
    restart: unless-stopped
    ports:
      - 3000:3000

networks:
  proxy:
    external: true
```

### Container Logs

There are none when started as user 
```

```

if started as root:
```
Listening on port 3000
```

### Troubleshooting

this is not relevant, as topic is not widgets

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that setting the `PUID` and `PGID` environment variables is causing the container to become unhealthy and the disk to spin continuously. This behavior suggests that the container is attempting to perform an operation that it cannot complete, possibly related to file permissions or ownership.

The `PUID` and `PGID` are used to set the user ID and group ID for the process running inside the container. This is typically done to ensure that any files written by the container have the correct permissions when accessed from the host system. However, if the container is trying to change ownership or permissions of existing files to match these IDs and encounters a large number of files or files that it cannot modify (due to being read-only or other restrictions), it could lead to the symptoms you're experiencing.

Here are a few steps you can take to troubleshoot the issue:

1. Verify that the `PUID` and `PGID` values you are setting correspond to the `docker-user` on your host system. You've already done this with the `id docker-user` command, which is good.

2. Ensure that the volume `/mnt/data/homepage` is owned by the `docker-user` and has the correct permissions set. It seems you have already checked this with `getfacl`, but it's worth double-checking.

3. Check if there are any large numbers of files or subdirectories within `/mnt/data/homepage` that could be causing the container to take a long time to change permissions or ownership.

4. Look for any logs that might indicate what the container is doing when it becomes unhealthy. Since you mentioned there are no logs when started as a user, you might need to enable more verbose logging or attach to the container to see if there's any output to the console.

5. Review the documentation and any related issues on the official repository for the Homepage project to see if others have encountered similar problems and if there are any known solutions or workarounds.

6. As a last resort, you could try setting the `PUID` and `PGID` to `0` to run the container as root, which should have unrestricted access to all files. However, this is not recommended for security reasons and should only be done temporarily for troubleshooting purposes.

If you continue to experience issues, you may want to reach out to the maintainers of the Homepage project or file an issue on their GitHub repository with the details of your problem.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by mscheltienne** [reply]
Same issue. This configuration fails:

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 30007:3000
    volumes:
      - /mnt/tank/data-apps/homepage:/app/config
    restart: unless-stopped
networks: {}
```

Despite the correct permissions for PUID/PGID 568.

**Reply by SheepReaper** [reply]
I'm having the same problem. If I specify PUID and PGID startup time is north of 5 minutes. makes it impossible to do a stack deploy with since the health check times out well before that and causes the container to restart. removing the variables works around the issue. This is on a debian VM on a Pi5. first thing to look at is su-exec in the entrypoint.
the root cause of my problem is that the server doesn't start listening for the whole 5 minutes, so the healthcheck to localhost:3000 is going to fail since nothing is listening yet. But running as root starts instantly. what gives?

**Reply by jerobins** [reply]
I find myself here for the same reason. The docker log says "Ready in 285ms" but it is more like 5mins + 285ms.

**Comment by Fernando-Checa** [comment]
I use this and works fine for me:

```
services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        environment:
              - PUID=1000 # optional, your user id
              - PGID=1000 # optional, your group id
.....

```
