### DISCUSSION TITLE
Dividing Bookmarks among tabs

### DISCUSSION THREAD

**Discussion by davidtippit** [gethomepage/homepage#3655] [Support] [answered]
### Description

I would like to know if bookmarks can be assigned to specific tabs  instead of clustered at the bottom?

### homepage version

v0.9.2(af16956 Jun 5,2024)

### Installation method

Docker

### Configuration

```yaml
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: TippitHome Page
theme: dark # or light
color: slate

layout:
  Infrastructure Stack:
    tab: Infrastructure
    style: row
    columns: 4

  Media Stack:
    tab: Media
    style: row
    columns: 4

  Development Stack:
    tab: Development
    style: row
    columns: 4

  LifeStyle Stack:
    tab: LifeStyle
    style: row
    columns: 4
===============================================================
- Developrment and Infrastructure:
   - Docker:
       - abbr: DK
         icon: docker.png
         href: https://hub.docker.com/
   - Fedora:
       - abbr: fdp
         icon: fedora.png
         href: https://fedoraproject.org/start
   - Github:
       - abbr: GH
         icon: github.png
         href: https://github.com/

- Entertainment and Social:
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://youtube.com/
    - Spotify:
        - abbr: SP
          icon: Spotify.png
          href: https://open.spotify.com/
    - Pandora:
        - abbr: PA
          icon: pandora.png
          href: https://www.pandora.com/station

    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/
    - Facebook:
        - abbr: FB
          icon: facebook.png
          href: https://facebook.com
    - Pinterest:
        - abbr: PN
          icon: pinterest.png
          href: https://pinterest.com

- Food and Cooking:
    - ChinaSichuanFood:
        - abbr: CSF
          href: https://www.chinasichuanfood.com/
- Take out:
    - Qing Qing:
        - abbr: QQ
          href: https://qmenu.us/#/qing-qing-texas-city/menu/1
    - Gringos & Jimmy Changas:
        - abbr: GJC
          href: https://order.gringostexmex.com/
    - Jersey Mike's:
        - abbr: JM
          href: https://www.jerseymikes.com/15086/la-marque-tx
```

### Troubleshooting

Unsure what to do or how to TS

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Yes, bookmarks can be assigned to specific tabs. The feature to use tabs in the layout was introduced in version 0.6.30, as indicated in the provided context. To assign bookmarks to specific tabs, you need to set the `tab` field on at least one layout group in your `settings.yaml` or equivalent configuration file.

Based on the configuration you provided, it seems you have already defined tabs for different stacks such as "Infrastructure Stack," "Media Stack," "Development Stack," and "LifeStyle Stack." To assign bookmarks to these tabs, you would need to ensure that the bookmark categories in your `bookmarks.yaml` file have the same names as the tabs you want them to appear under.

For example, if you want the "Developer and Infrastructure" bookmarks to appear under the "Infrastructure Stack" tab, you should ensure that the group name in your `bookmarks.yaml` matches the tab name in your `settings.yaml`. Here's how you could modify the bookmarks section:

```yaml
- Infrastructure Stack:
    - Docker:
        - abbr: DK
          icon: docker.png
          href: https://hub.docker.com/
    - Fedora:
        - abbr: fdp
          icon: fedora.png
          href: https://fedoraproject.org/start
    - Github:
        - abbr: GH
          icon: github.png
          href: https://github.com/
```

Make sure that the group names used in `bookmarks.yaml` match the tab names defined in `settings.yaml`. If you follow this structure, your bookmarks should be displayed under the corresponding tabs instead of being clustered at the bottom.

For more detailed information on configuring tabs and layouts, please refer to the documentation:
- [Settings Configuration](https://gethomepage.dev/latest/configs/settings)
- [Bookmarks Configuration](https://gethomepage.dev/latest/configs/bookmarks)

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
