### DISCUSSION TITLE
Multiple replicas in Kubernetes cause Homepage to sometimes not apply settings.yaml

### DISCUSSION THREAD

**Discussion by Zeashh** [gethomepage/homepage#3656] [Support]
### Description

Hi,

I've deployed Homepage in Kubernetes with a known working config (without automatic discovery) and I've noticed odd behavior when running more than one replica (in my case 2).

On **some** browser sessions Homepage will, as far as I can tell, apply bookmarks.yaml, services.yaml, widgets.yaml, custom.js and custom.css, but not settings.yaml (causing the background and layout to revert to defaults, which is how I noticed it to begin with). Both Pods can read the file as well as the background image mounted through a RWX volume on NFS.

Pods are running in K3s v1.28.7+k3s1.

### homepage version

v0.9.2

### Installation method

Other (please describe above)

### Configuration

```yaml
Kubernetes configuration:

- Deployment and service:

 yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/public/images
              name: homepage-images
      volumes:
        - name: homepage-config
          secret:
            secretName: homepage
        - name: homepage-images
          persistentVolumeClaim:
            claimName: homepage-images
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app: homepage
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: homepage
```

- Ingress (homepage-redirect is just for redirecting http to https):
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  annotations:
    kubernetes.io/ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.middlewares: homepage-redirect@kubernetescrd
spec:
  tls:
  rules:
    - host: "homepage.domain"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  name: http
```

- PVC for images:
``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: homepage
  name: homepage-images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs
```

### Container Logs

Setting `LOG_LEVEL` to `debug` didn't tell me much, except for this:
```
debug: No containers were found with homepage labels.
```

### Browser Logs

The browser console doesn't output anything in either case.

### Troubleshooting

Again, one replica works fine, 2 don't.

I tried circumventing the Ingress by changing the service type to NodePort, but it didn't fix the issue.
