### DISCUSSION TITLE
widgets are not showing

### DISCUSSION THREAD

**Discussion by ahmedm95** [gethomepage/homepage#3660] [Support] [answered]
### Description

hey i run my homepage on a portainer and after setting it up and add some services the services show up with out the widget im not sure why 
![Screen Shot 2024-06-21 at 5 51 24 PM](https://github.com/gethomepage/homepage/assets/128874390/7725f597-edcb-4335-9977-ed76f378fe9c)

### homepage version

v0.9.2

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My Services:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox.***
        description: Proxmox cluster
        widget:
        type: proxmox 
        url: https://proxmox.***
        username: user
        password: pass
        node: pve # optional 

    - Alpha Server:
        icon: portainer.png
        href: https://alpha.****
        description: alpha docker container
        widget:
        type: portainer

- Beta Server:
        icon: portainer.png
        href: https://beta.***
        description: Beta Docker Container
        widget:
        type: portainer
        url: https://192.158.0.172:9443
        env: 
        key: my key


- Media Services:
    - Plex:
        icon: plex.png
        href: https://plex.***
        description: Watch movies and TV shows
        widget:
        type: tautulli
        url: http://192.168.0.25:8181
        key: my key

- DNS:
    - Pi-Hole:
        icon: pi-hole
        href: http://192.168.0.189/admin
        description: DNS Proxy
        widget:
        type: pihole
        url: http://192.168.0.189
        key: my key
```

### Troubleshooting

widget not showing
![Screen Shot 2024-06-21 at 5 51 24 PM](https://github.com/gethomepage/homepage/assets/128874390/6c251733-3250-4c4a-89cc-bb83f6b30156)

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the provided configuration, it seems there might be an issue with the indentation of the YAML file, which is critical for the configuration to be parsed correctly. YAML relies on indentation to define structure, and the `widget` configurations for your services appear to be incorrectly indented. They should be nested under the service they belong to.

Here's how the corrected configuration should look for one of your services:

```yaml
- My Services:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox.ahmedm.org
        description: Proxmox cluster
        widget:
          type: proxmox 
          url: https://proxmox.***
          username: user
          password: pass
          node: pve # optional 
```

Notice that the `widget` block is indented under the `Proxmox` service. You should apply this indentation fix to all services in your configuration.

Additionally, for the Portainer widget, you need to specify the `env` (environment ID) and `key` (API key). For example:

```yaml
- Beta Server:
    icon: portainer.png
    href: https://beta.***
    description: Beta Docker Container
    widget:
      type: portainer
      url: https://192.158.0.172:9443
      env: 1 # Replace with your actual environment ID
      key: my key # Replace with your actual API key
```

Make sure to replace the placeholders with your actual environment ID and API key.

After making these corrections, ensure that your `docker-compose.yml` file is also correctly configured and that the Homepage container has network access to the services you are trying to monitor with widgets.

If the issue persists after correcting the indentation and ensuring all required fields are filled, you may want to check the container logs for any errors and verify that the Homepage version you are using supports the widgets you are trying to add.

Please apply these changes and let me know if the widgets start displaying correctly.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
