### DISCUSSION TITLE
pyLoad widget not working with pyload-ng

### DISCUSSION THREAD

**Discussion by nathan-lamy** [gethomepage/homepage#3666] [Support] [answered]
### Description

Hello,
I just discovered this awesome project and started playing a bit with it :)
I discovered the pyload widget wasn't working with the latest pyload-ng update.

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
pyLoad:
        icon: pyload.png
        href: redacted
        # server: docker
        # container: pyload-ng
        widget:
            type: pyload
            url: redacted
            username: pyload
            password: pyload
```

### Container Logs

And in the logs :
```
error: <pyloadProxyHandler> Error logging into pyload API: {"type":"Buffer","data":[........]}
```

### Browser Logs

I'm getting this error :
```
API Error: HTTP error communicating with Pyload API
Error 404: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

### Troubleshooting

The /api/login route is working as intended :
```
{
    "_permanent": true,
    "authenticated": true,
    "id": 4,
    "name": "homepage",
    "role": 1,
    "perms": 20,
    "template": "default",
    "_flashes": [
        [
            "message",
            "Logged in successfully"
        ]
    ]
}
```
