### DISCUSSION TITLE
[Feature Request] Search append field

### DISCUSSION THREAD

**Discussion by mrpops2ko** [gethomepage/homepage#3668] [Feature Requests] [answered]
### Description

some search providers lock custom features or a subset of features behind specific url appended flags, i wil be using the one I wanted to implement as an example. perplexity.ai 

```
- search:
    provider: custom
    url: https://perplexity.ai/search?q=
    target: _blank
```
this functions fine, as it folows the structure but it prevents the usage of pro (paid) features. perplexity provide this by appending 
```
&copilot=true
```
to the url, meaning a search for test would result in this url 
```
https://perplexity.ai/search?q=test&copilot=true
```

it would be nice if an optional append yaml option could be added to support just this feature, which would help towards constructing more complex queries

```
- search:
    provider: custom
    url: https://perplexity.ai/search?q=
    target: _blank
    append: &copilot=true 
```
so that something like above would construct the url as desired
