### DISCUSSION TITLE
Autocomplete list on search widget doesn't work with SearXNG

### DISCUSSION THREAD

**Discussion by truppelito** [gethomepage/homepage#3671] [Support] [answered]
### Description

I have a self-hosted SearXNG instance and I want to setup homepage to use it when I search in the search widget, so I added this to my `widgets.yaml` file:

```
- search:
    provider: custom
    url: http://10.23.58.4:26322/search?q=
    focus: true
    target: _self
    suggestionUrl: http://10.23.58.4:26322/autocompleter?q=
    showSearchSuggestions: true
```

The url works, i.e. if I type in the search field and press enter, I'm shown the SearXNG page with the results. However, autocomplete doesn't work. Just to make sure this isn't SearXNG's fault, I opened `http://10.23.58.4:26322/autocompleter?q=asdf` directly in Firefox and this is what I got:
<img width="649" alt="Screenshot 2024-06-26 at 20 55 24" src="https://github.com/gethomepage/homepage/assets/1059798/96635cd7-1626-4944-916f-a4613a1af5f7">

According to the [documentation](https://gethomepage.dev/main/widgets/info/search/), this is exactly the response format that homepage supports, right? But when I start typing something in the search field, no autocompletions are shown:
<img width="481" alt="Screenshot 2024-06-26 at 20 56 43" src="https://github.com/gethomepage/homepage/assets/1059798/6da9553c-8b79-49b3-b2d1-359e7fe96ed7">

(I have also verified that if I choose Google as a provider, for example, the autocompletions do show up)

Is there anything obivous I'm missing here?

### homepage version

v0.9.2

### Installation method

Docker

### Container Logs

Empty

### Browser Logs

Empty

### Troubleshooting

see above
