### DISCUSSION TITLE
Error when using custom search with quick launch feature

### DISCUSSION THREAD

**Discussion by Juxsta** [gethomepage/homepage#3673] [Support]
### Description

I'm using custom search with the quick launch feature and when performing the search via quick launch a new tab opens with the following error
> Application error: a client-side exception has occurred (see the browser console for more information).
The relevant console and server logs report undefined errors.  I am able to perform the custom search fine when not using the quick launch feature and instead using the widget directly.

### homepage version

v0.9.2 (af16956, Jun 5, 2024)

### Installation method

Docker

### Configuration

```yaml
- search:
    provider: [google, custom]
    url: https://www.perplexity.ai/search?q=
    target: _blank
    suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
    showSearchSuggestions: true # Optional
```

### Container Logs

[2024-06-27T20:01:41.316Z] error: undefined

### Browser Logs

TypeError: Cannot read properties of null (reading 'classList')
    at l (_app-b877b7641e51de94.js:1:16848)
    at _app-b877b7641e51de94.js:1:16976
    at ri (framework-95233f837b560043.js:1:93734)
    at Ss (framework-95233f837b560043.js:1:113961)
    at framework-95233f837b560043.js:1:110551
    at S (framework-95233f837b560043.js:1:138480)
    at MessagePort.T (framework-95233f837b560043.js:1:139014)

### Troubleshooting

N/A
