### DISCUSSION TITLE
z-index issue | Status and ping display over search results

### DISCUSSION THREAD

**Discussion by plafreniere** [gethomepage/homepage#3678] [Support] [answered]
### Description

When I do a search query, the suggestions pop-up go over the services normally. But the health and ping indicators are still displayed.  

![homepage-issue](https://github.com/gethomepage/homepage/assets/65878393/70f9c0a0-23a2-4e3c-9eef-495fc3e59c02)

I tried fiddling with custom CSS but I cant seem to change the z-index to something that work so I'm not sure what is the issue here. It may be me.

Should I create an issue? I can't believe that I'm the only one so I probably misconfigured something

Thanks.

### homepage version

v0.9.2 (af16956)

### Installation method

Docker

### Configuration

```yaml
my settings.yaml :

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Local services
target: _self # Possible options include _blank, _self, and _top

hideErrors: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom

theme: dark

headerStyle: boxedWidgets
useEqualHeights: false

layout:
  Media:
    style: row
    columns: 4
    useEqualHeights: true

And the way I made the badges in the services.yaml :

    - Sonarr:
        href: <my-url>/
        description: TV shows management
        siteMonitor: <my-url>/
        server: unraid-docker
        container: sonarr
        icon: /images/sonarr.png
        widget:
            type: sonarr
            url: <my-url>
            key: <my-key>
            fields: ["wanted", "queued"]
            enableQueue: false # optional, defaults to false

current custom css :

#layout-groups {
    margin-bottom: 0px;
}
#services {
    margin-top: 0px;
}
```

### Troubleshooting

I basically tried to change the z-index of the status badges to -1000 but it didnt work.

I the tried changing the z-index of the query suggestions <div> to 9000. Chrome complained about the div being position:static. 

I then set the positon: relative;  No changes but chrome stopped complaining.

Wasnt sure if it were a transparency issue, so I tried to set the background-color: rgba(0,0,0,255); full alpha, but the text still appeared from under.

It was the limit of my css abilities.
