### DISCUSSION TITLE
Multiple slug support for Uptime Kuma?

### DISCUSSION THREAD

**Discussion by Fintanw23** [gethomepage/homepage#3699] [Support] [answered]
### Description

Just wondering if this is supported or if there are plans to support multiple slugs in the future?
Documentation makes no mention of more than 1 slug and i've tried:
- slug: slug1, slug2
- slug: [slug1, slug2]
- slug: ["slug1", "slug2"]
Love your work!
Thanks!

### homepage version

v0.9.2

### Installation method

Docker

### Configuration

```yaml
- Uptime Kuma:
        icon: uptime-kuma.svg
        href: "https://uptime.test.example.com"
        widget:
            type: uptimekuma
            url: "http://10.10.10.10:3001"
            slug: proxmox
```

### Container Logs

n/a 

### Browser Logs

n/a

### Troubleshooting

- slug: slug1, slug2
- slug: [slug1, slug2]
- slug: ["slug1", "slug2"]

**Comment by glime-ai** [comment, marked as answer]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Currently, the Uptime Kuma widget for Homepage only supports using data from a single "status page," which means you can only specify one slug in the configuration. The slug is essentially the identifier for that particular status page. Based on the documentation and context provided, there is no mention of support for multiple slugs within a single widget configuration.

If you need to monitor multiple status pages, you would need to set up separate widget entries for each status page in your configuration file, each with its own unique slug.

Here's an example of how you could configure multiple Uptime Kuma widgets for different status pages:

```yaml
- Uptime Kuma 1:
    icon: uptime-kuma.svg
    href: "https://uptime.test.example.com/statuspage1"
    widget:
        type: uptimekuma
        url: "http://10.10.10.10:3001"
        slug: statuspageslug1

- Uptime Kuma 2:
    icon: uptime-kuma.svg
    href: "https://uptime.test.example.com/statuspage2"
    widget:
        type: uptimekuma
        url: "http://10.10.10.10:3001"
        slug: statuspageslug2
```

Each widget entry should have a unique name (e.g., "Uptime Kuma 1," "Uptime Kuma 2") and the corresponding slug for the status page it represents.

As for future support for multiple slugs within a single widget, this would be a feature request for the developers of Homepage. You may want to check the project's GitHub repository for updates or consider opening a feature request issue there.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).
