### DISCUSSION TITLE
Octoprint multiple instances with widget

### DISCUSSION THREAD

**Discussion by chickey** [gethomepage/homepage#3703] [Support]
### Description

I have multiple octoprint instances on one box so use instance names so for example i have two printers 

http://192.168.0.70/MK3s-1/
http://192.168.0.70/MK3s-2/

This works great for going to the web interface but i've also got the widget setup on homepage but it seems the widget only uses the ip and ignores the instance name so both widgets show the same information and not for each printer.  I wondered if anyone had encountered similar?

The services.yaml config is:-

- 3D Printers:
    - Octoprint:
        href: http://192.168.0.70/MK3s-1/
        description: MK3s-1
        icon: octoprint.png
        widget:
          type: octoprint
          field: ["printer_state", "temp_tool", "temp_bed", "job_completion"]
          url: http://192.168.0.70/MK3s-1/
          key: APIKEY
    - Octoprint:
        href: http://192.168.0.70/MK3s-2/
        description: MK3s-2
        icon: octoprint.png
        widget:
          type: octoprint
          field: ["printer_state", "temp_tool", "temp_bed", "job_completion"]
          url: http://192.168.0.70/MK3s-2/
          key: APIKEY   

### homepage version

v0.9.2 (af16956, Jun 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- 3D Printers:
    - Octoprint:
        href: http://192.168.0.70/MK3s-1/
        description: MK3s-1
        icon: octoprint.png
        widget:
          type: octoprint
          field: ["printer_state", "temp_tool", "temp_bed", "job_completion"]
          url: http://192.168.0.70/MK3s-1/
          key: APIKEY
    - Octoprint:
        href: http://192.168.0.70/MK3s-2/
        description: MK3s-2
        icon: octoprint.png
        widget:
          type: octoprint
          field: ["printer_state", "temp_tool", "temp_bed", "job_completion"]
          url: http://192.168.0.70/MK3s-2/
          key: APIKEY
```

### Troubleshooting

I've checked the logs but do not see any errors, i'm guessing as it's just reading the IP and displaying info it's not seeing it as an error.
