### DISCUSSION TITLE
Plex widget showing 0 TV shows

### DISCUSSION THREAD

**Discussion by phil9309** [gethomepage/homepage#3705] [Support] [answered]
### Description

Hi, I need a little info how the Plex Widget gets the "TV Shows" number.

I currently have 2 tv shows in my Plex Library, but it shows as 0 on the widget.

The code of the widget must be working, because the movie field works as intended, showing 20 movies. This number is correct, it doesnt count the tv shows as movies. Active streams is working as intended too.

The Plex tv show library is marked as tv shows in Plex, they are not in the movie library.

What else can I check?

### homepage version

latest

### Installation method

Source

### Configuration

```yaml
widget:
      type: plex
      url: XXXXXXXXXXX
      key: XXXXXXXXXXXXXXX
      fields: ["streams", "movies", "tv"]
```

### Troubleshooting

.
