### DISCUSSION TITLE
API Keys in Clear/Plain Text [Docker]

### DISCUSSION THREAD

**Discussion by cyberndj** [gethomepage/homepage#3707] [Feature Requests] [answered]
### Description

API keys in clear/plain text can pose a vulnerability....so its a no no...
A way to combat clear/plain text keys is to use the secrets function with docker swarm.
An issue with swarm is you can't put a secret inside a label  (if you know how, please share!), but you can assign them to a environment variable.

When using Docker, would it be possible to have the ability to set an environment variable on the HomepageApp container/service? This would let you reference a docker secret so the keys/passwords are not in plain text.  
The environment variable could over-ride the  docker Automatic service discovery label so that line wouldn't be needed. ...But if its not possible, setting something like "_env" in the key/password label could tell Homepage to reference the environment variable.

Thanks for your consideration!
-Jake

### Other

a potential sample snip:

```
version: '3'
services:
  homepage:
    environment:
      widget.deluge.password_file: /run/secrets/deluge
      widget.sonarr.api_file: /run/secrets/sonarr
    secrets:
      - deluge
      - sonarr

  deluge:
    deploy:
      labels:
        homepage.widget.password: "_env"
  sonarr:
    deploy:
      labels:
        homepage.widget.api: "_env"

secrets:
  deluge:
    external: true
  sonarr:
    external: true 
```

**Comment by shamoon** [comment, marked as answer]
https://gethomepage.dev/latest/installation/docker/#using-environment-secrets

**Comment by cyberndj** [comment]
Well crap....looks like I need to RTFM better....

So for my clarification:
```
  sonarr:
    deploy:
      labels:
        homepage.widget.api: somekey...
```
Would be (with a secret)
```
  homepage:
    environment:
      HOMEPAGE_VAR_sonarr.widget.api_FILE=/run/secrets/sonarr
```
