### DISCUSSION TITLE
MySpeed Widget says "Missing Widget Type: myspeed"

### DISCUSSION THREAD

**Discussion by BasDL91** [gethomepage/homepage#3708] [Support]
### Description

The MySpeed Widget does not show the Allowed fields: ["ping", "download", "upload"].
It just say´s "Missing Widget Type: myspeed"
![grafik](https://github.com/gethomepage/homepage/assets/51874985/ead58158-bfca-488b-ad93-7dfbe928bae7)

### homepage version

v0.9.2 [Proxmox VE Helper-Scripts](https://proxmox-helper-scripts.vercel.app/)

### Installation method

Other (please describe above)

### Configuration

```yaml
- MySpeed:
        href: https://myspeed.xx.xx
        description: MySpeed Internet Speed Test
        icon: https://myspeed.xx.xx/assets/img/logo192.png
        siteMonitor: https://myspeed.xx.xx
        widget:
            type: myspeed
            url: https://myspeed.xx.xx
            password: xxxxx
```

### Browser Logs

no messages on the browser console. No failing HTTP requests

### Troubleshooting

`
~# curl https://myspeed.xx.xx/api/speedtests?limit=1
[{"id":8,"serverId":31470,"ping":11,"download":147.71,"upload":36.32,"type":"auto","resultId":"4b552615-7376-4f74-9f70-d8a6a6a6578a","time":30,"created":"2024-07-05T13:00:33.218Z"}]`
