### DISCUSSION TITLE
Agenda date not in line

### DISCUSSION THREAD

**Discussion by LuciDuki** [gethomepage/homepage#3710] [Support] [answered]
### Description

Hello,

i have a Problem with the agenda widget. On some entries the dates are not in line and shift into the next line.
 
![image](https://github.com/gethomepage/homepage/assets/16707625/1067dab7-6272-432a-ba8d-bfc5b539fee6)

Any idea how i can fix this?

Best Regards
Luci

### homepage version

v0.9.2

### Installation method

Docker

### Configuration

```yaml
- Info:
    - Kalender:
        icon: si-googlecalendar
        description: Event Kalender
        widget:
          type: calendar
          view: monthly
          maxEvents: 5
          showTime: true
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/XXXXXXXXX
              name: XXXX
              color: zinc

    - Agenda:
        icon: mdi-view-agenda
        description: Agenda
        widget:
          type: calendar
          view: agenda
          maxEvents: 20
          showTime: true
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/XXXXXXXX
              name: XXXX
              color: zinc
```

### Troubleshooting

Update to newest Version, still same error
