### DISCUSSION TITLE
PFSENSE API ERROR

### DISCUSSION THREAD

**Discussion by HHUBSS** [gethomepage/homepage#3712] [Support] [answered]
### Description

Hello, I have error in pfsense.

![image](https://github.com/gethomepage/homepage/assets/89816305/7cb3661f-416f-4ceb-8dc0-d155cb65a165)

Here's my config:
![image](https://github.com/gethomepage/homepage/assets/89816305/d013d75f-d6db-43f0-893e-5440de5e70eb)

Here's the API version in PFSENSE:
![image](https://github.com/gethomepage/homepage/assets/89816305/3b739b2a-b998-453f-8aa0-33664acd4c46)

I tried to check it using curl:

using v1:
![image](https://github.com/gethomepage/homepage/assets/89816305/b4e2fe59-0326-4cd9-b85e-08607d5308c5)

using v2:
![image](https://github.com/gethomepage/homepage/assets/89816305/d150bd92-5830-4c24-8b1c-b04363c398a8)

I believed that Homepage is using api v1 rather than v2.

### homepage version

v0.9.2

### Installation method

Docker

### Configuration

```yaml
- pfSense:
        icon:  pfsense
        href: https://<REMOVED>:<REMOVED>
        description: Router & Firewall
        widget:
          type: pfsense
          url: https://<REMOVED>:<REMOVED>
          username: <REMOVED>
          password: <REMOVED>
          wan: igb0
```

### Troubleshooting

1. Check pfsense IP and port
2. Check username & password
3. Restarted Homepage docker
4. Check API status = v2 is ok.
