### DISCUSSION TITLE
I changed settings.yml but it didn't take effect

### DISCUSSION THREAD

**Discussion by imJack6** [gethomepage/homepage#3721] [Support]
### Description

rt, I tried reinstalling and restarting the server to no avail. I used Docker to install it, and then used Openresty reverse proxy.

### homepage version

v0.9.3 (b8af7ad, Jul 8, 2024)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Title
language: zh-CN

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
```

### Container Logs

```
homepage  | Listening on port 3000
homepage  | settings.yaml was copied to the config folder
homepage  | [2024-07-09T05:38:42.118Z] [32minfo[39m: docker.yaml was copied to the config folder
homepage  | [2024-07-09T05:38:42.122Z] [32minfo[39m: services.yaml was copied to the config folder
homepage  | [2024-07-09T05:38:42.123Z] [32minfo[39m: bookmarks.yaml was copied to the config folder
homepage  | [2024-07-09T05:38:42.124Z] [32minfo[39m: widgets.yaml was copied to the config folder
homepage  | [2024-07-09T05:38:42.125Z] [32minfo[39m: custom.css was copied to the config folder
homepage  | [2024-07-09T05:38:42.126Z] [32minfo[39m: custom.js was copied to the config folder
homepage  | [2024-07-09T05:38:42.488Z] [32minfo[39m: kubernetes.yaml was copied to the config folder
homepage  | Listening on port 3000
```

### Browser Logs

None

### Troubleshooting

None
