### DISCUSSION TITLE
Cannot get homepage to start on a different port

### DISCUSSION THREAD

**Discussion by Leahnaya** [gethomepage/homepage#3723] [Support] [answered]
### Description

So I am trying to get homepage setup for the first time.  I have a gitea instance running on port 3000 so I was going to change to port to 3001 instead.  I have created the following docker_compose.yml file:
```
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - TZ=America/Chicago
      - PORT=3001
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
    ports:
      - 3001:3000
    volumes:
      - /home/leahnaya/docker/homepage/config:/app/config # Make sure your local config directory exists
    restart: unless-stopped
```
However when I run "docker compose up -d" it says listening on port 3001, but when trying to access the webpage at "localhost:3001" through firefox, I get an error stating "The connection was reset.  The connection to the server was reset while the page was loading" with "NS_ERROR_NET_RESET_ in the browser console. 

Running "docker compose ps" shows:
```
NAME       IMAGE                               COMMAND                  SERVICE    CREATED          STATUS                    PORTS
homepage   ghcr.io/benphelps/homepage:latest   "docker-entrypoint.s…"   homepage   17 seconds ago   Up 16 seconds (healthy)   0.0.0.0:3001->3000/tcp, :::3001->3000/tcp
```
Running docker logs homepage doesn't show anything beyond the initial listening on port statement.

Also to note I had to manually copy the files from src/skeleton into my config folder.  Not sure if that impacts it starting up, but they are there now after manually putting them there

### homepage version

v0.9.3

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - TZ=America/Chicago
      - PORT=3001
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
    ports:
      - 3001:3000
    volumes:
      - /home/leahnaya/docker/homepage/config:/app/config # Make sure your local config directory exists
    restart: unless-stopped
```

### Container Logs

Listening on port 3001

### Troubleshooting

I've tried opening the port 3001 by running "sudo ufw allow 3001/tcp".  Not sure what else to try though.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems like you have correctly mapped the container's internal port 3000 to the external port 3001 on your host machine. However, you're encountering a connection reset error when trying to access the service via `localhost:3001`.

Here are a few troubleshooting steps you can take:

1. **Check if the Homepage application inside the container is actually running on port 3001**. The environment variable `PORT=3001` might not be correctly configuring the application to listen on port 3001. You can verify this by checking the application documentation or by entering the container and checking the port it's listening on using commands like `netstat` or `ss`.

2. **Ensure there are no conflicts with other services on port 3001**. Use `sudo netstat -tuln | grep 3001` to check if the port is already in use by another process on the host.

3. **Check Docker logs for more detailed error messages**. You mentioned that `docker logs homepage` doesn't show anything beyond the initial listening statement, but sometimes additional logs may take a moment to appear. Run `docker logs homepage` again after a few moments to see if there are any new messages.

4. **Check the Homepage configuration files**. Since you had to manually copy the files from `src/skeleton` to your `config` directory, ensure that all necessary configuration files are present and correctly formatted. Any missing or misconfigured files could prevent the application from starting properly.

5. **Check firewall settings**. Although you've allowed traffic on port 3001, ensure that there are no other firewall rules that could be interfering with the connection.

6. **Try accessing the service from within the container**. Use `docker exec -it homepage curl http://localhost:3000` to see if the service is accessible from within the container itself.

7. **Check for browser-specific issues**. Try accessing the service using a different browser or in incognito mode to rule out browser-specific problems.

8. **Review the Homepage documentation for any additional environment variables or configuration settings** that might be required for changing the default port.

If none of these steps resolve the issue, consider reaching out to the Homepage community or support channels for assistance, as there might be a specific issue with the application or the Docker image you're using.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Reply by Leahnaya** [reply]
1/2. Running "sudo netstat -tuln | grep 3001" returns the following:
```
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN
tcp6       0      0 :::3001                 :::*                    LISTEN
```

3. It's been running for awhile now and it still has nothing additionally in the log
4. They should be correctly formatted as I didn't modify any of them after copying them down
5. I didn't see any other rules that could be conflicting
6. When trying to run "docker exec -it homepage curl http://localhost:3000" I get the following response:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
```
7. I've tried other browsers to no avail

**Comment by Leahnaya** [comment, marked as answer]
Had to modify the part of my docker_compose.yml to have both ports be the same.  My compose file looks like the following now:
```
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - TZ=America/Chicago
      - PORT=3001
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
    ports:
      - 3001:3001
    volumes:
      - /home/leahnaya/docker/homepage/config:/app/config # Make sure your local config directory exists
    restart: unless-stopped
```
