### DISCUSSION TITLE
traefik v3 IngressRoute not automatically discovered

### DISCUSSION THREAD

**Discussion by Rick-van-Dam** [gethomepage/homepage#3727] [Support]
### Description

I have a traefik v3 IngressRoute resource but its not picked up by homepage. A normal Ingress resource does get picked up

### homepage version

1.2.3 (helm)

### Installation method

Other (please describe above)

### Configuration

```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homepage
spec:
  repo: http://jameswynn.github.io/helm-charts
  chart: homepage
  targetNamespace: homelab
  version: 1.2.3
  valuesContent: |-
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
      services:
        - My First Group:
            - My First Service:
                href: http://localhost/
                description: Homepage is awesome
  
      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - search:
            provider: duckduckgo
            target: _blank
      kubernetes:
        mode: cluster
      settings:
    
    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage
    
    # This enables the service account to access the necessary resources
    enableRbac: true
  
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  annotations:
    gethomepage.dev/href: "https://homepage.photogrammer.net"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Hompage
    gethomepage.dev/group: Default
    gethomepage.dev/icon: emby.png
    gethomepage.dev/app: homepage # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Homepage 
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: 10 # optional      
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`homepage.photogrammer.net`)
      services:
        - name: homepage
          port: 3000
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

 No errors

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided and the context from the documentation, it seems that your Traefik v3 IngressRoute resource is not being picked up by Homepage. There are a few things to check and consider:

1. **Annotations**: Ensure that the necessary annotations are present in your IngressRoute metadata. The `gethomepage.dev/href` annotation is particularly important as it is required for Homepage to recognize the IngressRoute. From the configuration you've provided, it seems that you have included this annotation.

2. **Version Compatibility**: Verify that the version of Homepage you are using (1.2.3) supports Traefik v3 IngressRoute resources. There might be compatibility issues between different versions of Traefik and Homepage.

3. **RBAC Permissions**: Check that the service account used by Homepage has the necessary permissions to list and get IngressRoute resources. This is important for the autodiscovery feature to work properly.

4. **Kubernetes Mode**: You have set the `kubernetes.mode` to `cluster` in your configuration. Make sure that this is the correct mode for your setup and that Homepage is configured to connect to your Kubernetes cluster correctly.

5. **API Version**: The `apiVersion` for IngressRoute in your configuration is `traefik.io/v1alpha1`. Ensure that this is the correct API version for the Traefik version you are using.

6. **Service Discovery**: Homepage automatically discovers services through Ingress annotations. If there are issues with the discovery, it could be related to the Homepage version or a misconfiguration in the annotations.

If after checking these points the issue persists, you may want to look at the Homepage logs to see if there are any errors or messages related to the discovery of IngressRoute resources. Additionally, you can check the Traefik logs to ensure that the IngressRoute is correctly configured and recognized by Traefik.

Since you mentioned that there are no errors and normal Ingress resources are being picked up, it's likely a specific issue with the IngressRoute resource or a compatibility issue with the version of Homepage you are using.

If you need further assistance, please provide additional details such as any relevant logs or error messages you are encountering.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by Gabgobie** [comment]
Hi

I was facing the same issue, except I installed the resources myself instead of going with the helm chart. Both the documentation and (probably) the helm chart are using a deprecated version of the traefik apigroup. The documentation is using the `traefik.containo.us` apiGroup. The correct one would be `traefik.io`

Below my working `ClusterRole.yaml`:

```YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      # - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
```

Please be aware that I have homepage in its own namespace so in case your deployment is not in the namespace `homepage` you would need to change that in my provided yaml. Hope you're having a great day!
