### DISCUSSION TITLE
White Flash on Page Load (FOUC?)

### DISCUSSION THREAD

**Discussion by Magnus987** [gethomepage/homepage#3728] [Support]
### Description

When reloading the Homepage dashboard, there's a brief (approximately 1 second) white flash before the content appears. This white screen is visually jarring and uncomfortable for the eyes, especially in low-light environments. Evan with a smaler or just no picture nothing changes.

https://github.com/user-attachments/assets/5d7390da-87fa-459e-8d2a-d5f19041e8cd

### homepage version

v0.9.3

### Installation method

Docker

### Configuration

```yaml
settings.yaml:
theme: dark
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
title: New smart Tab
background: https://images.hdqwalls.com/wallpapers/desert-night-minimal-4k-hp.jpg
language: en
target: _self
provider: google
fadeIn: true
headerStyle: underlined
```

### Troubleshooting

Tryed it with a smaler picture but evan with no picture it still flashes white
