### DISCUSSION TITLE
Allow "unified" widgets.yaml with private options

### DISCUSSION THREAD

**Discussion by shamoon** [gethomepage/homepage#373] [Feature Requests]
Hey @benphelps et al I was thinking about a way to be able to have info widgets be able to use sensitive data (e.g. URL, username / password) without passing them as query vars and I wondered your thoughts before I try to code it:

- Basically we strip any of the above (`key`, `url`, `username`, `password`) and dont pass them as query vars
- Add a new function (presumably in `service-helpers` that returns these sensitive values

If you think this could work it might be ideal to release it before the unifi widget (and the glances one if that gets merged) so that users dont have to adjust their yaml files first, but let me know your thoughts.

Edit:

POC: https://github.com/shamoon/homepage/tree/unified-infowidget-settings

- Adds a `getPrivateWidgetOptions` which optionally takes a widget type + index argument and returns... private widget options
- private settings (currently "url", "username", "password", "key") are removed from the widget options API response so theyre not passed as query vars

Again this allows for "unified" widgets.yaml (and multiple instances of a widget without needing `id` or anything), no settings.yaml needed 🎉:
```yaml
- glances:
    url: http://1.2.3.4:61208
    username: user
    password: pass
    label: RaspPi

- glances:
    url: http://5.6.7.8:61208
    username: user
    password: pass
    label: AnotherMachine

- unifi_console:
    url: https://9.10.11.12:443
    username: user
    password: pass
```
