### DISCUSSION TITLE
Times of repeating calendar events are off

### DISCUSSION THREAD

**Discussion by ansgaross** [gethomepage/homepage#3730] [Support]
### Description

Hello,
I have a problem with repeating calendar events.

One-time events show up correctly:
![image](https://github.com/user-attachments/assets/0629a8c6-9afc-478b-ad24-0b6ea3bba5e3)

Repeating events show up as +3 hours:
![image](https://github.com/user-attachments/assets/affc7bc0-43b7-432b-9291-dd98b3e89518)

Repeating all-day events show up as +24 hours:
![image](https://github.com/user-attachments/assets/c923dab2-b4f4-4a44-b556-ac616a3724aa)

In either repeating case interval has no effect, so daily, weekly, monthly, yearly, all behave the same (+3 or +24 hours).

I couldn't find an existing issue or discussion regarding this, but from reading earlier discussions I already understand that the calendar implementation is "best effort" and Homepage is not a calendar app.

However, is there something I can do about this as a user? Or if it's a bug, maybe an easy fix?

EDIT: Other calendar apps (Google Calendar on web & mobile, Samsung Calendar on mobile) have no problem showing these entries correctly.

### homepage version

v0.9.3 (b8af7ad, Jul 7, 2024)

### Installation method

Unraid

### Configuration

```yaml
widget:
            type: calendar
            view: monthly
            showTime: true
            integrations:
                - type: ical
                  url: https://calendar.google.com/calendar/ical/THINGSHERE/basic.ics
                  name: Oma kalenteri
                  color: violet
```

### Troubleshooting

I've tried at least:
 - changing the time zone of the calendar
   - this has no effect whatsoever
 - changing the time zone of the widget
   - this changes the times of the events as expected, but they're still off by the same amount
   - since time zones are already working (one-time events show correct times), this wouldn't be a fix anyway
 - creating a totally new, blank calendar (in case an old calendar entry is causing this)
