### DISCUSSION TITLE
Homepage reports API error from PiHole widget (Bugs #3311 and 3313)

### DISCUSSION THREAD

**Discussion by bmccann16** [gethomepage/homepage#3732] [Support] [answered]
### Description

I updated to the latest Homepage today (created on 7/7) and now my Pihole widget shows an API error "API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data". This had been working fine with Homepage as of 3/10/24.

I installed 'curl' in the Homepage container and this is the result from querying my pihole:

```
curl -L -k 'http://192.168.20.4/admin/api.php?summaryRaw&auth=XXXXX'
{"domains_being_blocked":165493,"dns_queries_today":34763,"ads_blocked_today":5554,"ads_percentage_today":15.976757,"unique_domains":13028,"queries_forwarded":20381,"queries_cached":8828,"clients_ever_seen":6,"unique_clients":6,"dns_queries_all_types":34763,"reply_UNKNOWN":1436,"reply_NODATA":5707,"reply_NXDOMAIN":8776,"reply_CNAME":8547,"reply_IP":10018,"reply_DOMAIN":2,"reply_RRNAME":1,"reply_SERVFAIL":0,"reply_REFUSED":0,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":17,"reply_NONE":0,"reply_BLOB":259,"dns_queries_all_replies":34763,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1720327202,"relative":{"days":5,"hours":5,"minutes":55}}}
```
Bugs 3311 and 3313 seem to be the same issue (that was fixed in April) so I don't know why I'm getting this error today with the July 7th release.

FWIW, I enabled debug logging but all it reports (every couple minutes) is:

```
[2024-07-12T10:39:55.271Z] debug: No containers were found with homepage labels.
[2024-07-12T10:39:55.294Z] error: undefined
```
It appears a regression has been introduced that broke the prior bug fixes.

### homepage version

v0.9.3 (b8af7ad, Jul 7, 2024)

### Installation method

Docker

### Configuration

```yaml
homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: Homepage
    restart: always
    environment:
      - TZ=America/New_York
      - UID=1004
      - GID=1004
      - LOG_LEVEL=debug
    networks:
      - admin
    ports:
      - 8099:3000
    volumes:
      - /Docker/Homepage:/app/config
```

### Container Logs

[2024-07-12T10:39:55.271Z] debug: No containers were found with homepage labels.
[2024-07-12T10:39:55.294Z] error: undefined

### Troubleshooting

See description.

**Comment by glime-ai** [comment]
Thanks for posting a discussion about homepage here on GitHub. Homepage now uses a fancy new AI tool thanks to our friends at Glime, so the answer below is the AI bot's attempt to answer your question. If you feel it's sufficient you can mark the answer and close this post, otherwise feel free to leave it open of course!

Thanks for using Homepage! ❤️

---

Based on the information provided, it seems that the Pi-hole widget is experiencing an API error after updating Homepage to the latest version. The `curl` command you executed returns valid JSON data, which suggests that the Pi-hole API is functioning correctly. The error message "API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data" typically indicates that the response from the API is not valid JSON, but this does not seem to be the case here.

Given that you have already enabled debug logging and the logs do not provide additional insight into the API error, and considering that similar issues were reported as bugs 3311 and 3313 and were fixed in April, it is possible that a regression has occurred in the July 7th release of Homepage.

To troubleshoot this issue further, you can:

1. Ensure that the Pi-hole widget configuration in your `services.yml` file matches the expected format and that there are no typos or syntax errors. The configuration should look something like this:

```yaml
pihole:
  type: pihole
  url: http://192.168.20.4
  key: XXXXXXXXXX
```

2. Check if there are any updates or comments on bugs 3311 and 3313 that might provide a solution or a workaround.

3. Report this issue as a potential regression on the Homepage GitHub repository by [opening a new issue](https://github.com/gethomepage/homepage/issues/new) and providing all the relevant details, including the output from the `curl` command and the logs from Homepage.

4. As a temporary workaround, you can try rolling back to a previous version of Homepage that did not exhibit this issue, if possible.

5. You can also seek assistance from the Homepage community by using the 'Ask AI' feature in the docs, [opening a GitHub discussion](https://github.com/gethomepage/homepage/discussions), or joining the [#ai-support channel on Discord](https://discord.com/channels/1019316731635834932/1177885603552038993).

Please let me know if you need further assistance or if there are any specific details you would like me to look into.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=Bl3mlvfCnTnRm5&utm_medium=github).

**Comment by bmccann16** [comment]
I reverted back to Homepage v0.8.9 that was released on 3/10/24 and this problem was resolved. So, something broke the pihole widget between v0.8.9 and v0.9.3.

**Comment by shamoon** [comment]
I don’t think it’s broken, it’s one of the most used widgets. Please post the entire error and your pihole service configuration.

**Comment by bmccann16** [comment]
There's really no 'entire' error. The widget displays 'API Error' and, when I click on the widget, it displays the error 'API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data' I posted in my original bug report. That's all I get. I enabled LOG_DEBUG (as described above) and that didn't help either.

The Pihole config in my 'services.yaml' file is:

```
    - Pihole:
        icon: pi-hole-unbound.png
        href: http://192.168.20.4/admin
        description: DNS Proxy
        widget:
            type: pihole
            url: http://192.168.20.4
            version: 6
            key: XXXXX
```

The widget, with this config, works fine with version 0.8.9 but doesn't work with 0.9.3.

If it would help, I could try bisecting the bug by trying versions between 0.8.9 and 0.9.3. That would narrow down where this bug occurred.

And, I am running the July 7 release which is only 5 days old. Maybe not many people have upgraded yet?
