### DISCUSSION TITLE
How to show stats for each docker service deployed using caprover?

### DISCUSSION THREAD

**Discussion by AhsanSarwar45** [gethomepage/homepage#3744] [Support] [answered]
### Description

Hi, I am new to using docker. I am using Caprover to run and manage all my docker services. In my homepage, I want to show stats (cpu, memory etc.) for each service. In the [docs](https://gethomepage.dev/v0.7.3/configs/services/#docker-integration), they tell us to do it like this:
```yaml
- Group A:
    - Service A:
        href: http://localhost/
        description: This is my service
        server: my-server
        container: my-container
```
What I am confused about is what do I actually write in the `server` and `container` fields? I guess `container` field is the container name, but what about `server`?

### homepage version

v0.8.7 (05a7c0f)

### Installation method

Docker

### Troubleshooting

-
