### DISCUSSION TITLE
my glances not showing

### DISCUSSION THREAD

**Discussion by ghost** [gethomepage/homepage#3746] [Support] [answered]
### Description

My glances is not showing CPU usage but the upper widget is.
![image](https://github.com/user-attachments/assets/f21673bd-430e-473e-85a7-2ac6d9018688)
![image](https://github.com/user-attachments/assets/4f429a35-a19a-4c79-91f7-67d2ad9b7c6a)

### homepage version

v0.9.3

### Installation method

Other (please describe above)

### Configuration

```yaml
services.yaml
"
- Info Page:

   - CPU Usage:
      widget:
      type: glances
      version: 4
      url: http://192.168.1.5:61208  
      cpu: true 
      metric: cpu  
"

widgets.yaml
"
- glances:
    url: http://192.168.1.5:61208
    version: 4     
    cpu: true     
    mem: true 
    cputemp: true 
    disk: / 
    diskUnits: bytes
"
```

### Troubleshooting

Tried putting in services.yaml version number, did not work. :(
Banged my head against the wall for 3 min (he did not). 
Tried to set username to glances, did not work.
Restarted physical machine, did not work.
Went on github.com and posted this (in progress).

**Comment by shamoon** [comment]
Its hard to tell if your indentation is off, just to check it should be

```yaml
- CPU Usage:
    widget:
      type: glances
      metric: cpu
      ...
```

If thats not the issue you can look at the output from the homepage API in your browser network tab and see what it says. But from the screenshot looks to me like a config issue.
