### DISCUSSION TITLE
watchtower not updating

### DISCUSSION THREAD

**Discussion by ghost** [gethomepage/homepage#3747] [Support]
### Description

![image](https://github.com/user-attachments/assets/f31f288a-faf7-49bf-9133-6c669203068d)
it is not updating on the homepage but on docker logs it scanning and working correctly

### homepage version

v0.9.3

### Installation method

Docker

### Configuration

```yaml
- watchtower:
        href: 
        icon: watchtower.png
        container: watchtower
        widget:
          type: watchtower
          url: http://192.168.1.7:5006
          key: demotoken
```

### Troubleshooting

restart
