### DISCUSSION TITLE
Pfsense API Get Client ID

### DISCUSSION THREAD

**Discussion by BlackOpsDown** [gethomepage/homepage#3757] [Support]
### Description

I have successfully installed the pfsense-api/REST API. Homepage works fine if I put the GUI admin and password. But I want to use the API token with client_id client_token. 

I can generate the client_token from System>REST API>Keys, but how to get the client_id? I have searched here and Google but have found no answer. I have tried using the Netgate Device ID, which is shown on the Pfsense homepage, but it gives an error.

![image](https://github.com/user-attachments/assets/f80987e8-2e6b-4819-a38d-155608ac392d)

I believe this may not be a bug, but a configuration issue, so any help would be appreciated.

Here is the error:

![image](https://github.com/user-attachments/assets/2c1cc56e-4e9c-4973-af54-b37f6536a9ce)

### homepage version

v0.9.5

### Installation method

Docker

### Configuration

```yaml
My services.yaml:

- My Third Group:
    - Pfsense:
        icon: pfsense.png
        href: https://[PFSENSE IP]
        widget:
          type: pfsense
          url: https://[PFSENSE IP]
          headers:
            Authorization: [NETGATE DEVICE ID] [GENERATED KEY]
          wan: [NAME]
          version: 2
          fields: ["load", "memory", "temp", "wanStatus"] # optional
```

### Troubleshooting

Switching to username and password works fine:

![image](https://github.com/user-attachments/assets/af7cf323-4129-4812-bf54-eb9f015e147a)

I have ensured this: URLs should not end with a / or other API path.
Ping: Can ping properly.
