### DISCUSSION TITLE
Traefik API inaccessible to Homepage

### DISCUSSION THREAD

**Discussion by DaveTSG** [gethomepage/homepage#3762] [Support] [answered]
### Description

Hello. I have successfully used [Homepage's Automatic Service Discovery mechanism](https://gethomepage.dev/v0.8.3/configs/docker/#automatic-service-discovery) with several Docker containers. However, I am having a problem getting it to work with Traefik. (I am running Traefik v3.0.4 in a Docker container - compose file below)

See attached screenshot. 
![homepage-traefik-issue](https://github.com/user-attachments/assets/b9f4dcd2-53db-4f3d-9150-09dcd7c5fba6)

As you can see, I get an API error for Traefik, specifically. I can load the URL ( https://traefik-dashboard.mydomain.com/api/overview ) in my browser and see the JSON from the Traefik API just fine, so I'm guessing this might be an issue where the Homepage container can't access the Traefik container... but they're both definitely on the same network in their respective docker-compose.yml files.

### homepage version

v0.9.5 (latest)

### Installation method

Docker

### Configuration

```yaml
Homepage docker-compose.yml:

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /home/david/docker/homepage/images:/app/public/images # Path to background image stored on computer.
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`homepage.mydomain.com`)"
      - "traefik.http.routers.homepage.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.mydomain.com`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true




Traefik docker-compose.yml:

services:
  traefik:
    image: traefik:v3.0.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80 #For internal services
      - 81:81 #For external services
      - 443:443 #For internal services
      - 444:444 #For external services
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_api_token # note using _FILE for docker secrets
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    secrets:
      - cf_api_token
    env_file: .env # use .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
      - ./logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.mydomain.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.mydomain.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=mydomain.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.mydomain.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - homepage.group=Network admin
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=https://traefik-dashboard.mydomain.com
      - homepage.description=HTTP reverse proxy and load balancer.
      - homepage.statusStyle=dot
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik-dashboard.mydomain.com
      - homepage.widget.username:dave
      - homepage.widget.password:passwordhere
      - homepage.showStats=true
secrets:
  cf_api_token:
    file: ./cf_api_token.txt

networks:
  proxy:
    external: true
```

### Container Logs

```
"Listening on port 3000
[2024-07-16T01:59:00.284Z] error: <service-helpers> Error getting services from Docker server 'docker1': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2024-07-16T01:59:00.494Z] error: <service-helpers> Error getting services from Docker server 'docker1': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2024-07-16T01:59:00.871Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
[2024-07-16T01:59:01.087Z] error: <service-helpers> Error getting services from Docker server 'docker1': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2024-07-16T01:59:01.109Z] error: <httpProxy> Error calling https://traefik-dashboard.mydomain.com/api/overview...
[2024-07-16T01:59:01.110Z] error: <httpProxy> [
  500,
  Error: getaddrinfo ENOTFOUND traefik-dashboard.mydomain.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'traefik-dashboard.mydomain.com'
  }"
```

### Troubleshooting

1. I ensured the URL for the widget (Homepage labels in the Traefik docker-compose.yml) do not end with a trailing slash.
2. I have tried running ping IPaddress_for_service from within the Homepage container console, i.e. `ping 192.168.4.7`, as well as the four ports configured for Traefik. This worked fine. 
```
/app # ping 192.168.4.7
PING 192.168.4.7 (192.168.4.7): 56 data bytes
64 bytes from 192.168.4.7: seq=0 ttl=64 time=0.056 ms
64 bytes from 192.168.4.7: seq=1 ttl=64 time=0.052 ms
^C
--- 192.168.4.7 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.052/0.054/0.056 ms
/app # ping 192.168.4.7:80
PING 192.168.4.7:80 (192.168.4.7): 56 data bytes
64 bytes from 192.168.4.7: seq=0 ttl=64 time=0.032 ms
64 bytes from 192.168.4.7: seq=1 ttl=64 time=0.035 ms
64 bytes from 192.168.4.7: seq=2 ttl=64 time=0.033 ms
^C
--- 192.168.4.7:80 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.032/0.033/0.035 ms
/app # ping 192.168.4.7:81
PING 192.168.4.7:81 (192.168.4.7): 56 data bytes
64 bytes from 192.168.4.7: seq=0 ttl=64 time=0.036 ms
64 bytes from 192.168.4.7: seq=1 ttl=64 time=0.046 ms
^C
--- 192.168.4.7:81 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.036/0.041/0.046 ms
/app # ping 192.168.4.7:443
PING 192.168.4.7:443 (192.168.4.7): 56 data bytes
64 bytes from 192.168.4.7: seq=0 ttl=64 time=0.074 ms
64 bytes from 192.168.4.7: seq=1 ttl=64 time=0.035 ms
^C
--- 192.168.4.7:443 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.035/0.054/0.074 ms
/app # ping 192.168.4.7:444
PING 192.168.4.7:444 (192.168.4.7): 56 data bytes
64 bytes from 192.168.4.7: seq=0 ttl=64 time=0.036 ms
64 bytes from 192.168.4.7: seq=1 ttl=64 time=0.034 ms
64 bytes from 192.168.4.7: seq=2 ttl=64 time=0.048 ms
^C
--- 192.168.4.7:444 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.034/0.039/0.048 ms
```

3.  I installed curl within the Homepage container: `apk add curl`, and then `curl https://traefik-dashboard.mydomain.com/api/overview`
`curl: (6) Could not resolve host: traefik-dashboard.mydomain.com
`

4. I added a DNS to my Homepage docker-compose.yml. See above Homepage docker-compose.yml (above it is shown with the DNS commented out, but I tried it uncommented, of course). 

Both with and without the DNS line enabled, I tried the following commands within the Homepage Docker container/shell, and received the same error:
/app # ping https://pihole.mydomain.com/
ping: bad port '//pihole.mydomain.com/'
/app # ping https://traefik-dashboard.mydomain.com/
ping: bad port '//traefik-dashboard.mydomain.com/'
/app # ping https://homepage.mydomain.com/
ping: bad port '//homepage.mydomain.com/'

I'm thinking it may be an issue with the Homepage container not being able to access the DNS (which is Pi-Hole, running at 192.168.4.7:500. Homepage is running on the same Docker host, 192.168.4.7.

5. I noted specifically "Error: connect EACCES /var/run/docker.sock". I thought it may be because /var/run/docker.sock didn't exist on my system. I found [this](https://superuser.com/questions/1741326/how-to-connect-to-docker-daemon-if-unix-var-run-docker-sock-is-not-available) and followed the instructions in the accepted answer (indeed, I was running Docker via systemctl and it was set to containerd.sock instead within /lib/systemd/system/docker.service (as shown in that answer), and so I changed it (again, as per the answer), so now I have /var/run/docker.sock (I also then rebooted, just in case).

Despite this change, and despite restarting the Docker host entirely, I still see the same error in the Homepage log (as seen in Portainer) and also the API error in the Homepage web UI (as seen in the screenshot provided).

6. I found [this](https://discourse.pi-hole.net/t/solve-dns-resolution-in-other-containers-when-using-docker-pihole/31413) in the Pi-Hole support forum which suggested explicitly specifying my Docker host IP address in the Pi-Hole docker-compose.yml file:

```
services:
   ...
   pihole:
      container_name: pihole
      image: pihole/pihole:latest
      ports:
         - "53:53/tcp"
         - "192.168.4.7:53:53/udp"
         - "67:67/udp"
         - "500:80/tcp"
```

...that resulted in the same problem.

7. I also tried nslookup from within the Homepage container:

```
/app # nslookup traefik
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   traefik
Address: 172.22.0.2
```

...I don't really understand what any of that means, but hopefully it'll be helpful to whoever ends up reading this.

Unfortunately, I can't troubleshoot this any further without assistance.

**Comment by shamoon** [comment]
If you use `http://traefik` instead of the fqdn as your widget url the container name (traefik) will resolve to the docker container

Eaccess to the docker sock is a permissions issue most likely

**Reply by DaveTSG** [reply]
Thanks for your reply.

I changed Traefik's docker-compose.yml file as instructed, i.e.:
`- homepage.widget.url=http://traefik`

...and restarted it, but the problem persists, unfortunately.

> Eaccess to the docker sock is a permissions issue most likely

As far as I am aware, the Homepage container is running as root. Do you know of a way to fix this issue please?

**Comment by shamoon** [comment]
Usually you need to recreate a container after changing labels eg compose down then up, not just restart

>       - homepage.widget.username:dave
>       - homepage.widget.password:passwordhere

this is also not correct syntax

**Reply by DaveTSG** [reply]
> Usually you need to recreate a container after changing labels eg compose down then up, not just restart
> 
> > ```
> >   - homepage.widget.username:dave
> >   - homepage.widget.password:passwordhere
> > ```
> 
> this is also not correct syntax

Thanks for those tips. 
I changed those colons to equals-signs, to be consistent with my other labels. Thank you - I hadn't noticed I had made that error.

So now the Homepage section of the labels part of the Traefik docker-compose.yml file is as follows:

```
      - homepage.group=Network admin
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=https://traefik-dashboard.davesservers.com
      - homepage.description=HTTP reverse proxy and load balancer.
      - homepage.statusStyle=dot
      - homepage.widget.type=traefik
      - homepage.widget.url=http://traefik
      - homepage.widget.username=dave
      - homepage.widget.password=password
      - homepage.showStats=true
```

I also tried docker compose down and then up, but nonetheless, the issue persists...

**Comment by DaveTSG** [comment]
Ok, after a long and convoluted troubleshooting process, I've added an IP address to my Pi-Hole compose file, and then set that same IP address as the DNS address for the Traefik compose file.

i.e., for Pi-Hole:


```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "500:80/tcp"
    networks:
      pihole_internal:
        ipv4_address: 172.70.9.3
      proxy:
        ipv4_address: 172.22.0.14
(this is a shortened version of the entire file)
```

...and for Homepage:


```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    dns: 172.22.0.14
(this is also shortened)
```


Now, the error message shown in the Homepage logs has changed:

```
[2024-07-21T23:53:58.034Z] error: <httpProxy> Error calling http://traefik/api/overview...
[2024-07-21T23:53:58.035Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
```

I'm no longer seeing that Docker socket error, but instead now this new error about https not being supported.

Any idea how to fix that please?
