### DISCUSSION TITLE
I can't add the Pi-Alert widget

### DISCUSSION THREAD

**Discussion by DisloyalSnow911** [gethomepage/homepage#3763] [Support] [answered]
### Description

Error API: HTTP Error
URL: http://192.168.1.7/php/server/devices.php?action=getDevicesTotals
My URL: http://192.168.1.7/pialert/devices.php

### homepage version

v0.9.3 

### Installation method

Docker

### Configuration

```yaml
- Pi-Alert:
        icon: pi-alert.png
        href: "{{HOMEPAGE_VAR_PIALERT_URL}}"
        description: Network scanner
        ping: "{{HOMEPAGE_VAR_PIALERT_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_PIALERT_URL}}"
        widget:
           type: pialert
           url: http://192.168.1.7
```

### Container Logs

[2024-07-20T21:14:11.357Z] debug: <genericProxyHandler> HTTP Error 404 calling http://192.168.1.7/php/server/devices.php...

### Browser Logs

http://192.168.1.7/php/server/devices.php?action=getDevicesTotals
Not Found
The requested URL was not found on this server.

### Troubleshooting

I found that the netalertx widget is used for both netalertx and pialert
