### DISCUSSION TITLE
Custom API widget for cup (container update checker)

### DISCUSSION THREAD

**Discussion by agrmohit** [gethomepage/homepage#3765] [General]
Using the Custom API widget, I created a config for [sergi0g/cup: The easiest way to check for your container updates](https://github.com/sergi0g/cup)

![screenshot of cup widget](https://github.com/user-attachments/assets/42eccc89-bdfd-426a-a113-653abe7483d8)

Here is the docker compose used.

```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup
    container_name: cup
    command: -c /config/cup.json serve -p 8000
    volumes:
      - ./config/cup.json:/config/cup.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    restart: unless-stopped
    labels:
      homepage.group: Network
      homepage.name: Cup
      homepage.icon: /icons/cup-with-straw.png
      homepage.href: http://myserver:8000
      homepage.ping: http://myserver:8000
      homepage.description: Checks for container updates
      homepage.widget.type: customapi
      homepage.widget.url: http://myserver:8000/json
      homepage.widget.mappings[0].label: Monitoring
      homepage.widget.mappings[0].field.metrics: monitored_images
      homepage.widget.mappings[0].format: number
      homepage.widget.mappings[1].label: Up to date
      homepage.widget.mappings[1].field.metrics: up_to_date
      homepage.widget.mappings[1].format: number
      homepage.widget.mappings[2].label: Updates
      homepage.widget.mappings[2].field.metrics: update_available
      homepage.widget.mappings[2].format: number
```
