### DISCUSSION TITLE
API error on Uptime Kuma widget

### DISCUSSION THREAD

**Discussion by DaveTSG** [gethomepage/homepage#3770] [Support] [answered]
### Description

Hello, I am using Automatic Service Discovery and wanted to get the Uptime Kuma widget working.
Unfortunately, I get a red "API Error Information" button in the Uptime Kuma section of Homepage.

Could I have some help with this issue please?

### homepage version

v0.9.5

### Installation method

Docker

### Configuration

```yaml
Homepage docker-compose:


services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    #user: 1000:1000 # uncomment if you do not want to run as root
    #ports: # uncomment if you are not using a reverse proxy
    #  - 3000:3000
    dns: 172.22.0.53
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /home/david/docker/homepage/images:/app/public/images # Path to background image stored on computer.
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`homepage.davesservers.com`)"
      - "traefik.http.routers.homepage.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.davesservers.com`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      # - "traefik.http.routers.homepage-secure.middlewares=middlewares-authentik@file"
     # - "traefik.http.routers.homepage-secure.middlewares=default-whitelist@file" # uncomment if you want to use a Traefik whitelist to restrict access
     # - "traefik.http.routers.homepage-secure.middlewares=authelia@docker" # uncomment if you want to use authelia
     # - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
```

Uptime Kima docker-compose:

```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    dns: 172.22.0.53
    volumes:
      - /home/david/dockerfilesNotOnNAS/UptimeKuma/data:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=http"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.davesservers.com`)"
      - "traefik.http.middlewares.uptime-kuma-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.uptime-kuma.middlewares=uptime-kuma-https-redirect"
      - "traefik.http.routers.uptime-kuma-secure.entrypoints=https"
      - "traefik.http.routers.uptime-kuma-secure.rule=Host(`uptime-kuma.davesservers.com`)"
      - "traefik.http.routers.uptime-kuma-secure.tls=true"
      - "traefik.http.routers.uptime-kuma-secure.service=uptime-kuma"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
      - homepage.group=Monitoring
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma
      - homepage.href=https://uptime-kuma.davesservers.com/
      - homepage.description=Monitor stuff
      - homepage.statusStyle=dot
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=https://uptime-kuma.davesservers.com/
      - homepage.widget.slug=piholestatus
      #The slug is associated with the Uptime Kuma monitoring status. See https://gethomepage.dev/main/widgets/services/uptime-kuma/
networks:
  proxy:
    external: true
```
```


### Container Logs

```
[2024-07-23T23:29:49.672Z] warn: Invalid data for widget 'uptimekuma' endpoint 'status-page':
Expected:undefined
Parse error: SyntaxError: Unexpected token < in JSON at position 0
Data: {"type":"Buffer","data":[60,33,68,79,67,84,89,80,69,32,104,116,109,108,62,10,60,104,116,109,108,32,108,97,110,103,61,34,101,110,34,62,10,60,104,101,97,100,62,10,32,32,32,32,60,109,101,116,97,32,99,104,97,114,115,101,116,61,34,85,84,70,45,56,34,32,47,62,10,32,32,32,32,60,109,101,116,97,32,110,97,109,101,61,34,118,105,101,119,112,111,114,116,34,32,99,111,110,116,101,110,116,61,34,119,105,100,116,104,61,100,101,118,105,99,101,45,119,105,100,116,104,44,32,105,110,105,116,105,97,108,45,115,99,97,108,101,61,49,46,48,44,32,118,105,101,119,112,111,114,116,45,102,105,116,61,99,111,118,101,114,34,32,47,62,10,32,32,32,32,60,108,105,110,107,32,114,101,108,61,34,97,112,112,108,101,45,116,111,117,99,104,45,105,99,111,110,34,32,115,105,122,101,115,61,34,49,56,48,120,49,56,48,34,32,104,114,101,102,61,34,47,97,112,112,108,101,45,116,111,117,99,104,45,105,99,111,110,46,112,110,103,34,62,10,32,32,32,32,60,108,105,110,107,32,114,101,108,61,34,105,99,111,110,34,32,116,121,112,101,61,34,105,109,97,103,101,47,115,118,103,43,120,109,108,34,32,104,114,101,102,61,34,47,105,99,111,110,46,115,118,103,34,32,47,62,10,32,32,32,32,60,108,105,110,107,32,114,101,108,61,34,109,97,110,105,102,101,115,116,34,32,104,114,101,102,61,34,47,109,97,110,105,102,101,115,116,46,106,115,111,110,34,32,47,62,10,32,32,32,32,60,109,101,116,97,32,110,97,109,101,61,34,116,104,101,109,101,45,99,111,108,111,114,34,32,105,100,61,34,116,104,101,109,101,45,99,111,108,111,114,34,32,99,111,110,116,101,110,116,61,34,34,32,47,62,10,32,32,32,32,60,109,101,116,97,32,110,97,109,101,61,34,100,101,115,99,114,105,112,116,105,111,110,34,32,99,111,110,116,101,110,116,61,34,85,112,116,105,109,101,32,75,117,109,97,32,109,111,110,105,116,111,114,105,110,103,32,116,111,111,108,34,32,47,62,10,32,32,32,32,60,116,105,116,108,101,62,85,112,116,105,109,101,32,75,117,109,97,60,47,116,105,116,108,101,62,10,32,32,32,32,60,115,116,121,108,101,62,32,32,32,32,32,32,32,32,46,110,111,115,99,114,105,112,116,45,109,101,115,115,97,103,101,32,123,10,32,32,32,32,32,32,32,32,32,32,32,32,102,111,110,116,45,115,105,122,101,58,32,50,48,112,120,59,10,32,32,32,32,32,32,32,32,32,32,32,32,116,101,120,116,45,97,108,105,103,110,58,32,99,101,110,116,101,114,59,10,32,32,32,32,32,32,32,32,32,32,32,32,112,97,100,100,105,110,103,58,32,49,48,112,120,59,10,32,32,32,32,32,32,32,32,32,32,32,32,109,97,120,45,119,105,100,116,104,58,32,53,48,48,112,120,59,10,32,32,32,32,32,32,32,32,32,32,32,32,109,97,114,103,105,110,58,32,48,32,97,117,116,111,59,10,32,32,32,32,32,32,32,32,125,10,32,32,32,32,60,47,115,116,121,108,101,62,10,32,32,60,115,99,114,105,112,116,32,116,121,112,101,61,34,109,111,100,117,108,101,34,32,99,114,111,115,115,111,114,105,103,105,110,32,115,114,99,61,34,47,97,115,115,101,116,115,47,105,110,100,101,120,45,67,89,115,90,85,118,55,100,46,106,115,34,62,60,47,115,99,114,105,112,116,62,10,32,32,60,108,105,110,107,32,114,101,108,61,34,115,116,121,108,101,115,104,101,101,116,34,32,99,114,111,115,115,111,114,105,103,105,110,32,104,114,101,102,61,34,47,97,115,115,101,116,115,47,105,110,100,101,120,45,67,108,114,90,48,83,97,82,46,99,115,115,34,62,10,32,32,60,115,99,114,105,112,116,32,116,121,112,101,61,34,109,111,100,117,108,101,34,62,105,109,112,111,114,116,46,109,101,116,97,46,117,114,108,59,105,109,112,111,114,116,40,34,95,34,41,46,99,97,116,99,104,40,40,41,61,62,49,41,59,97,115,121,110,99,32,102,117,110,99,116,105,111,110,42,32,103,40,41,123,125,59,105,102,40,108,111,99,97,116,105,111,110,46,112,114,111,116,111,99,111,108,33,61,34,102,105,108,101,58,34,41,123,119,105,110,100,111,119,46,95,95,118,105,116,101,95,105,115,95,109,111,100,101,114,110,95,98,114,111,119,115,101,114,61,116,114,117,101,125,60,47,115,99,114,105,112,116,62,10,32,32,60,115,99,114,105,112,116,32,116,121,112,101,61,34,109,111,100,117,108,101,34,62,33,102,117,110,99,116,105,111,110,40,41,123,105,102,40,119,105,110,100,111,119,46,95,95,118,105,116,101,95,105,115,95,109,111,100,101,114,110,95,98,114,111,119,115,101,114,41,114,101,116,117,114,110,59,99,111,110,115,111,108,101,46,119,97,114,110,40,34,118,105,116,101,58,32,108,111,97,100,105,110,103,32,108,101,103,97,99,121,32,99,104,117,110,107,115,44,32,115,121,110,116,97,120,32,101,114,114,111,114,32,97,98,111,118,101,32,97,110,100,32,116,104,101,32,115,97,109,101,32,101,114,114,111,114,32,98,101,108,111,119,32,115,104,111,117,108,100,32,98,101,32,105,103,110,111,114,101,100,34,41,59,118,97,114,32,101,61,100,111,99,117,109,101,110,116,46,103,101,116,69,108,101,109,101,110,116,66,121,73,100,40,34,118,105,116,101,45,108,101,103,97,99,121,45,112,111,108,121,102,105,108,108,34,41,44,110,61,100,111,99,117,109,101,110,116,46,99,114,101,97,116,101,69,108,101,109,101,110,116,40,34,115,99,114,105,112,116,34,41,59,110,46,115,114,99,61,101,46,115,114,99,44,110,46,111,110,108,111,97,100,61,102,117,110,99,116,105,111,110,40,41,123,83,121,115,116,101,109,46,105,109,112,111,114,116,40,100,111,99,117,109,101,110,116,46,103,101,116,69,108,101,109,101,110,116,66,121,73,100,40,39,118,105,116,101,45,108,101,103,97,99,121,45,101,110,116,114,121,39,41,46,103,101,116,65,116,116,114,105,98,117,116,101,40,39,100,97,116,97,45,115,114,99,39,41,41,125,44,100,111,99,117,109,101,110,116,46,98,111,100,121,46,97,112,112,101,110,100,67,104,105,108,100,40,110,41,125,40,41,59,60,47,115,99,114,105,112,116,62,10,60,47,104,101,97,100,62,10,60,98,111,100,121,62,10,60,110,111,115,99,114,105,112,116,62,10,60,100,105,118,32,99,108,97,115,115,61,34,110,111,115,99,114,105,112,116,45,109,101,115,115,97,103,101,34,62,10,32,32,32,32,83,111,114,114,121,44,32,121,111,117,32,100,111,110,39,116,32,115,101,101,109,32,116,111,32,104,97,118,101,32,74,97,118,97,83,99,114,105,112,116,32,101,110,97,98,108,101,100,32,111,114,32,121,111,117,114,32,98,114,111,119,115,101,114,10,32,32,32,32,100,111,101,115,110,39,116,32,115,117,112,112,111,114,116,32,105,116,46,60,98,114,32,47,62,84,104,105,115,32,119,101,98,115,105,116,101,32,114,101,113,117,105,114,101,115,32,74,97,118,97,83,99,114,105,112,116,32,116,111,32,102,117,110,99,116,105,111,110,46,10,32,32,32,32,80,108,101,97,115,101,32,101,110,97,98,108,101,32,74,97,118,97,83,99,114,105,112,116,32,105,110,32,121,111,117,114,32,98,114,111,119,115,101,114,32,115,101,116,116,105,110,103,115,32,116,111,32,99,111,110,116,105,110,117,101,46,10,60,47,100,105,118,62,10,60,47,110,111,115,99,114,105,112,116,62,10,60,100,105,118,32,105,100,61,34,97,112,112,34,62,60,47,100,105,118,62,10,32,32,60,115,99,114,105,112,116,32,110,111,109,111,100,117,108,101,62,33,102,117,110,99,116,105,111,110,40,41,123,118,97,114,32,101,61,100,111,99,117,109,101,110,116,44,116,61,101,46,99,114,101,97,116,101,69,108,101,109,101,110,116,40,34,115,99,114,105,112,116,34,41,59,105,102,40,33,40,34,110,111,77,111,100,117,108,101,34,105,110,32,116,41,38,38,34,111,110,98,101,102,111,114,101,108,111,97,100,34,105,110,32,116,41,123,118,97,114,32,110,61,33,49,59,101,46,97,100,100,69,118,101,110,116,76,105,115,116,101,110,101,114,40,34,98,101,102,111,114,101,108,111,97,100,34,44,40,102,117,110,99,116,105,111,110,40,101,41,123,105,102,40,101,46,116,97,114,103,101,116,61,61,61,116,41,110,61,33,48,59,101,108,115,101,32,105,102,40,33,101,46,116,97,114,103,101,116,46,104,97,115,65,116,116,114,105,98,117,116,101,40,34,110,111,109,111,100,117,108,101,34,41,124,124,33,110,41,114,101,116,117,114,110,59,101,46,112,114,101,118,101,110,116,68,101,102,97,117,108,116,40,41,125,41,44,33,48,41,44,116,46,116,121,112,101,61,34,109,111,100,117,108,101,34,44,116,46,115,114,99,61,34,46,34,44,101,46,104,101,97,100,46,97,112,112,101,110,100,67,104,105,108,100,40,116,41,44,116,46,114,101,109,111,118,101,40,41,125,125,40,41,59,60,47,115,99,114,105,112,116,62,10,32,32,60,115,99,114,105,112,116,32,110,111,109,111,100,117,108,101,32,99,114,111,115,115,111,114,105,103,105,110,32,105,100,61,34,118,105,116,101,45,108,101,103,97,99,121,45,112,111,108,121,102,105,108,108,34,32,115,114,99,61,34,47,97,115,115,101,116,115,47,112,111,108,121,102,105,108,108,115,45,108,101,103,97,99,121,45,67,79,113,66,57,109,78,98,46,106,115,34,62,60,47,115,99,114,105,112,116,62,10,32,32,60,115,99,114,105,112,116,32,110,111,109,111,100,117,108,101,32,99,114,111,115,115,111,114,105,103,105,110,32,105,100,61,34,118,105,116,101,45,108,101,103,97,99,121,45,101,110,116,114,121,34,32,100,97,116,97,45,115,114,99,61,34,47,97,115,115,101,116,115,47,105,110,100,101,120,45,108,101,103,97,99,121,45,68,51,68,107,118,71,84,88,46,106,115,34,62,83,121,115,116,101,109,46,105,109,112,111,114,116,40,100,111,99,117,109,101,110,116,46,103,101,116,69,108,101,109,101,110,116,66,121,73,100,40,39,118,105,116,101,45,108,101,103,97,99,121,45,101,110,116,114,121,39,41,46,103,101,116,65,116,116,114,105,98,117,116,101,40,39,100,97,116,97,45,115,114,99,39,41,41,60,47,115,99,114,105,112,116,62,10,60,47,98,111,100,121,62,10,60,47,104,116,109,108,62,10]}
```

### Browser Logs

_No response_

### Troubleshooting

If I click on the "API Error Information" button, I see the following:

```
API Error: Invalid data
URL: https://uptime-kuma.davesservers.com//api/status-page/piholestatus
Response Data:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/svg+xml" href="/icon.svg" />
    <link rel="manifest" href="/manifest.json" />
    <meta name="theme-color" id="theme-color" content="" />
    <meta name="description" content="Uptime Kuma monitoring tool" />
    <title>Uptime Kuma</title>
    <style>        .noscript-message {
            font-size: 20px;
            text-align: center;
            padding: 10px;
            max-width: 500px;
            margin: 0 auto;
        }
    </style>
  <script type="module" crossorigin src="/assets/index-CYsZUv7d.js"></script>
  <link rel="stylesheet" crossorigin href="/assets/index-ClrZ0SaR.css">
  <script type="module">import.meta.url;import("_").catch(()=>1);async function* g(){};if(location.protocol!="file:"){window.__vite_is_modern_browser=true}</script>
  <script type="module">!function(){if(window.__vite_is_modern_browser)return;console.warn("vite: loading legacy chunks, syntax error above and the same error below should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>
</head>
<body>
<noscript>
<div class="noscript-message">
    Sorry, you don't seem to have JavaScript enabled or your browser
    doesn't support it.<br />This website requires JavaScript to function.
    Please enable JavaScript in your browser settings to continue.
</div>
</noscript>
<div id="app"></div>
  <script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script>
  <script nomodule crossorigin id="vite-legacy-polyfill" src="/assets/polyfills-legacy-COqB9mNb.js"></script>
  <script nomodule crossorigin id="vite-legacy-entry" data-src="/assets/index-legacy-D3DkvGTX.js">System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))</script>
</body>
</html>
```

I note "Sorry, you don't seem to have JavaScript enabled or your browser doesn't support it."
I followed [the Google Chrome documentation](https://support.google.com/adsense/answer/12654?hl=en) and added my Homepage URL to the list of sites that are allowed to use Javascript, but the problem persists.

I definitely have used the correct slug... 

`homepage.widget.slug=piholestatus`

...the status page in Uptime Kuma is at https://uptime-kuma.davesservers.com/status/piholestatus, which matches the slug I inserted into the Uptime Kuma docker-compose file.
