### DISCUSSION TITLE
Decimal places on scale option

### DISCUSSION THREAD

**Discussion by tdtgit** [gethomepage/homepage#3771] [Support] [answered]
### Description

Sometime the `scale` option of Custom API widget can show the value like this, not rounded. I looked into the code and seem there is no option for `Math.round` or how many numbers can be after decimal places. Can you advise me how to do it?

![2024-07-24 09 27 30](https://github.com/user-attachments/assets/a26e1290-fb10-418a-a09f-4d0766dfdc37)
![2024-07-24 09 27 26](https://github.com/user-attachments/assets/69dc8fa3-874c-4efe-9c5b-b3c3a12f6622)

### homepage version

Docker latest

### Installation method

Docker

### Configuration

```yaml
widget:
        type: customapi
        url: http://aruba335proxy:3000/fetch
        display: list
        mappings:
          - field:
              apsData:
                Aruba315: clients
            label: Connected clients
          - field:
              apsData:
                Aruba315: currPower
            label: Power consumption
            suffix: W
            scale: 0.001
```

### Troubleshooting

https://github.com/gethomepage/homepage/blob/main/src/widgets/customapi/component.jsx#L47
