### DISCUSSION TITLE
Color picker and day/night switch on Homepage after updating to 0.9.5

### DISCUSSION THREAD

**Discussion by JackD-01** [gethomepage/homepage#3772] [Support] [answered]
### Description

Hi,

It is probably me but after updating to 0.9.5 I got the colorpicker and a day/night switch on the bottom of my Homepage.
I set the color in my settings file to gray, so according to the homepage manual the colorpicker should be gone on my Homepage, but it is not?

And after the update I also got a day/night switch on my Homepage. How do I get rid of that one?, I don't seem to be able to find anything about it in the Homepage manual on the website.

Hope you can help me solve these little problems. If my questions are stupid..... forgive me I am not a programmer, but just a happy user of Homepage.

Regards,
 Jack
![color picker back copy](https://github.com/user-attachments/assets/d58feab2-c290-43e6-bf46-97cdb48efe74)

### homepage version

0.9.5

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: My Dashboard

headerStyle: boxed

theme: dark

color: gray
```

### Troubleshooting

Don't know what to change, or what is wrong, so little troubleshooting done.
The only thing I tried was shutting down everything and booting my whole system up, did not help.
And deleted webbrowser cash.
