### DISCUSSION TITLE
[Search Suggestion] Not working on using self-hosted docker-container on same host/network

### DISCUSSION THREAD

**Discussion by SHU-red** [gethomepage/homepage#3774] [Support]
### Description

- Im hosting on the same machine with docker whoogle search engine
- Custom search is working
- Search suggestions for custom search are not working

Testing it in the browser with e.g. `http://192.168.178.55:8004/autocomplete?q=testsearch` shows me the following

```json
["testsearch",["telsearch","telsearch wetter","telsearch regenradar","telefonbuch deutschland","telsearch basel","telsearch wetter basel","telsearch thun","telsearch routenplaner","telsearch liechtenstein","telsearch chur"]]
```
Resonse-Headers
Cache-Control: max-age=86400
Content-Length: 225
Content-Type: application/json
Date: Wed, 24 Jul 2024 18:46:26 GMT
Server: waitress
Vary: Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

Request-Headers
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: 192.168.178.55:8004
Priority: u=0, i
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0

### homepage version

v0.9.5 (eccd96a, Jul 18, 2024)

### Installation method

Docker

### Configuration

```yaml
quicklaunch:
   provider: custom
   searchDescriptions: true
   hideInternetSearch: false
   hideVisitURL: false
   showSearchSuggestions: true
   url: http://192.168.178.55:8004/search?q=
   suggestionUrl: http://192.168.178.55:8004/autocomplete?q=
```

### Browser Logs

XHRGET
http://192.168.178.55/api/search/searchSuggestion?query=test&providerName=Custom
[HTTP/1.1 500 Internal Server Error 1ms]

	
GET
	
scheme
	http
host
	192.168.178.55
filename
	/api/search/searchSuggestion
query
	test
providerName
	Custom
Address
	192.168.178.55:80
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred171 B (21 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest
DNS ResolutionSystem

    	
    Connection
    	keep-alive
    Date
    	Wed, 24 Jul 2024 18:37:30 GMT
    Keep-Alive
    	timeout=5
    Transfer-Encoding
    	chunked
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	_pk_id.1.1d3e=0da0c75e1c1a95cf.1716021207.; X-OPENHAB-SESSIONID=ded8f5d3-5426-4b9c-b79c-72d386a4e0fd; session=.eJw1zMEKgjAYAOBXif_cQLdpTugSdDEkmjrrFHPOFMuGbJGI756Xbt_pm-Fu9PiSgx4sxHZ0egvS2fZv9R6a7gHxvGyh19MK2FQQQyq4OZdCXok4Vdgmtff9cPF0sjDppWwPlV9YJRLKe5bfCp4J37RaHKcs9_awXs519dpoHISMEoUUIztECcUo0n6EPKUaTCghIQtg-QGxqTMl.ZqFJ2g.IXmK8qjwI-aIye1p-LEQ-ehYhDs; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; csrftoken=azECsMbOqaPU9IZs2A3sFiTXfJvXgavk; immich_access_token=nlVFDGQq8eHPBKEpoQsdmJl9da1WeabMDJ5EaAfxpRE; immich_auth_type=password; immich_is_authenticated=true; nc_username=nextcloud; nc_token=gPjQnENPCukJUB3qqrLsaNX8sOJsnPqR; nc_session_id=caa73377a1f90d5a8ea75c3aee2742a8; default-theme=ngax; gitea_incredible=xW5RnBWvQ5%3A23674740853d9f706a9206b0e58a6bbcaeafd53a9a0686c85591764e3dfa7212; pyload_session=CR5Xs2VhbNhA8qEX3I1AX59TfweEaDG1WfVTZQg1G0E; table-page-size=50; agh_session=542af02b8e0cbecbe94f10d2da0bb341
    Host
    	192.168.178.55
    Priority
    	u=0
    Referer
    	http://192.168.178.55/
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0

### Troubleshooting

no service widget tests

**Comment by SHU-red** [comment]
Additionally from the docker-container of homepage i tried the following and got a response

```
/app # wget http://192.168.178.55:8004/autocomplete?q=testsearch
Connecting to 192.168.178.55:8004 (192.168.178.55:8004)
saving to 'autocomplete?q=testsearch'
autocomplete?q=tests 100% |********************************************************************************************************************************************************************|   225  0:00:00 ETA
'autocomplete?q=testsearch' saved
/app # ls
autocomplete?q=testsearch  next-i18next.config.js     node_modules               public                     src
config                     next.config.js             package.json               server.js
/app # cat autocomplete\?q=testsearch 
["testsearch",["telsearch","telsearch wetter","telsearch regenradar","telefonbuch deutschland","telsearch basel","telsearch wetter basel","telsearch thun","telsearch routenplaner","telsearch liechtenstein","telsearch chur"]]
/app # 
```

**Comment by shamoon** [comment]
Are you talking about from quicklaunch or the search widget?

Error 500 is suspicious for being not a homepage issue. You tested `http://192.168.178.55:8004/autocomplete?q=testsearch` in your browser, how about from inside the homepage container? Perhaps it's just a networking thing and homepage cant reach that container. In general, using IP addresses for docker containers isnt great (I dont know if 192.168.178.55:8004 is a docker container), and assuming a standard-ish docker setup with containers on the same network you can actually use the container name

**Comment by SHU-red** [comment]
From my comment above you see, that from within the homepage docker container the whoogle-autocomplete api seems to be available
https://github.com/gethomepage/homepage/discussions/3774#discussioncomment-10141407

As i now tried `suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=` with 500 server error

Surely the problem lies on my side but i have no idea where
Is this some CORS thing?

Switching to `provider: google` brings back suggestions

EDIT:
Talking about quicklaunch

EDIT2:
Homepage and whoogle are on the same host with this ip
i also tried localhost and whoogle-search which is the docker container name

**Comment by SHU-red** [comment]
And sorry as last point:
Both containers run on separate docker-compose-files/stacks having their own subnet

Im not an expert in this, but this may be the root cause right?
As soon as i have time i think i will take a test by starting both containers from the same stack
Maybe this makes whoogle-search reachable from within homepage

**Comment by SHU-red** [comment]
I quickly tested it
Both containers now ran in the same docker network
Using container name "whoogle-search", "localhost" or the given container ip "172.28.0 .2" did not work

I also tested the default port of 5000 as my re-mapped port 8004

Nothing worked

Always Status 500

**Comment by SHU-red** [comment]
And again from within the docker container i can ping and get the response for autocomplete

then using `whoogle-search:5000/autocomplete?q=` in the homepage config gives no autocompletes

```
/app # ping whoogle-search
PING whoogle-search (172.28.0.2): 56 data bytes
64 bytes from 172.28.0.2: seq=0 ttl=64 time=0.111 ms
64 bytes from 172.28.0.2: seq=1 ttl=64 time=0.062 ms
64 bytes from 172.28.0.2: seq=2 ttl=64 time=0.077 ms
64 bytes from 172.28.0.2: seq=3 ttl=64 time=0.058 ms
64 bytes from 172.28.0.2: seq=4 ttl=64 time=0.086 ms
q64 bytes from 172.28.0.2: seq=5 ttl=64 time=0.105 ms
64 bytes from 172.28.0.2: seq=6 ttl=64 time=0.071 ms
64 bytes from 172.28.0.2: seq=7 ttl=64 time=0.052 ms
64 bytes from 172.28.0.2: seq=8 ttl=64 time=0.047 ms
c64 bytes from 172.28.0.2: seq=9 ttl=64 time=0.078 ms
64 bytes from 172.28.0.2: seq=10 ttl=64 time=0.264 ms
^C
--- whoogle-search ping statistics ---
11 packets transmitted, 11 packets received, 0% packet loss
round-trip min/avg/max = 0.047/0.091/0.264 ms
/app # wget whoogle-search/autocomplete?q=test
Connecting to whoogle-search (172.28.0.2:80)
wget: can't connect to remote host (172.28.0.2): Connection refused
/app # wget whoogle-search:8004/autocomplete?q=test
Connecting to whoogle-search:8004 (172.28.0.2:8004)
wget: can't connect to remote host (172.28.0.2): Connection refused
/app # wget whoogle-search:5000/autocomplete?q=test
Connecting to whoogle-search:5000 (172.28.0.2:5000)
saving to 'autocomplete?q=test'
autocomplete?q=test  100% |*********************************************|   172  0:00:00 ETA
'autocomplete?q=test' saved
/app # ls
autocomplete?q=test     next.config.js          public
config                  node_modules            server.js
next-i18next.config.js  package.json            src
/app # cat auto
cat: can't open 'auto': No such file or directory
/app # cat autocomplete\?q=test 
["test",["test","testosteron","teste dich","testspiele heute","testspiele fc bayern","testosteron erh\u00f6hen","testspiel bayern","testament muster","testo","testament"]]
/app # rm autocomplete\?q=test 
```

**Comment by SHU-red** [comment]
Sorry for all the comments
I did a very interesting last test with
`suggestionUrl: https://whoogle.io/autocomplete?q=`

This also does not work
So no matter if in the network or not, it doesnt work
Also the ecosia example does not work for me

Can you confirm this behavior?

**Reply by shamoon** [reply]
> Can you confirm this behavior?

No, I cannot, it works fine for me.

```yaml
quicklaunch:
  searchDescriptions: true
  showSearchSuggestions: true
  provider: custom
  url: https://www.ecosia.org/search?q=
  suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
```

<img width="1646" alt="Screenshot 2024-07-24 at 1 57 03 PM" src="https://github.com/user-attachments/assets/61f80539-14e0-485e-9991-d0d45c83b9b1">

I dont see anything obvious, config looks ok too

**Reply by SHU-red** [reply]
It seems in your case localhost is used AS hostname by Homepage

In my case its the IP

Do you think this culd lead to the Situation where 500 is returned?

Not sure where the hostname comes from, homepage uses to call its own suggestion api

**Reply by shamoon** [reply]
That is not the issue, homepage is able to reach its own API, the error 500 is being passed from the call to the other service, homepage is just acting as a proxy

**Reply by SHU-red** [reply]
Now switched from Firefox to Chrome
Trying to get same screenshot as you did
Still 500

I agree with you that the problem may be on my side but i cant see why
I did change the port of homepage
But this does not change anything?

![2024-07-25_17-57](https://github.com/user-attachments/assets/19f16478-005c-43da-8cb7-b5cb630969fa)

**Comment by Ixiruss** [comment]
Got the same issue while using custom search from quicklaunch.
My initial config was : 

**widgets.yaml**
```yaml
- search:
    provider: [brave, google, duckduckgo]
    target: _self # One of _self, _blank, _parent or _top
```

**settings.yaml**
```yaml
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
  provider: custom # google, duckduckgo, bing, baidu, brave or custom
  url: https://www.google.com/search?udm=14&q=
  target: _self
  suggestionUrl: https://suggestqueries.google.com/complete/search?client=firefox&q=
```

I just needed to change the part from **widgets.yaml** to : 
```yaml
- search:
    provider: [brave, google, duckduckgo]
    target: _self # One of _self, _blank, _parent or _top
    suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
    showSearchSuggestions: true
```

And it show !

So, suggestionUrl must be defined and showSearchSuggestions enabled in the search widget part for suggestions from quicklaunch to be able to work.
