### DISCUSSION TITLE
Grafana widget API error

### DISCUSSION THREAD

**Discussion by DaveTSG** [gethomepage/homepage#3778] [Support] [answered]
### Description

Hello again. Unfortunately I am having problems getting [the Grafana widget](https://gethomepage.dev/main/widgets/services/grafana/) to work with Homepage. Following [your troubleshooting guide](https://gethomepage.dev/v0.9.5/troubleshooting/#service-widget-errors):

1. I definitely don't have a / at the end of the URL. The Grafana docker compose labels are as follows:
```
      - homepage.group=Monitoring
      - homepage.name=Grafana
      - homepage.icon=grafana
      - homepage.href=https://grafana.domain.com/dashboards
      - homepage.description=Data visualisation
      - homepage.statusStyle=dot
      - homepage.widget.type=grafana
      - homepage.widget.url=grafana.domain.com
      - homepage.widget.username=user
      - homepage.widget.password=pass
```
      
2. docker exec homepage ping grafana.domain.com works:
```
PING grafana.domain.com (192.168.4.7): 56 data bytes
64 bytes from 192.168.4.7: seq=0 ttl=64 time=0.027 ms
64 bytes from 192.168.4.7: seq=1 ttl=64 time=0.034 ms
64 bytes from 192.168.4.7: seq=2 ttl=64 time=0.044 ms
64 bytes from 192.168.4.7: seq=3 ttl=64 time=0.043 ms
```
3. curl commands run from inside the Homepage container:

```
curl grafana.domain.com
Moved Permanently
```

```
curl https://grafana.domain.com
<a href="/login">Found</a>.
```

```
curl https://grafana.domain.com/api/search
{"extra":null,"message":"Unauthorized","messageId":"auth.unauthorized","statusCode":401,"traceID":""}
```

I understand code 401 means unauthorized. So that at least means that the Homepage container can at least access the Grafana container. 

Based on [the Grafana documentation](https://grafana.com/docs/grafana/latest/developers/http_api/curl-examples/), I gave it the same username and password as defined in the Homepage labels and got what looks like a good response:

```
curl https://user:pass@grafana.domain.com/api/search
[{"id":2,"uid":"6L2GdB47z","title":"Crowdsec Details per instance","uri":"db/crowdsec-details-per-instance","url":"/d/6L2GdB47z/crowdsec-details-per-instance","slug":"","type":"dash-db","tags":[],"isStarred":false,"sortMeta":0,"isDeleted":false},{"id":3,"uid":"e7sWOBVnk","title":"Crowdsec Insight","uri":"db/crowdsec-insight","url":"/d/e7sWOBVnk/crowdsec-insight","slug":"","type":"dash-db","tags":[],"isStarred":false,"sortMeta":0,"isDeleted":false},{"id":4,"uid":"hjmZdB4nk","title":"Crowdsec Overview","uri":"db/crowdsec-overview","url":"/d/hjmZdB4nk/crowdsec-overview","slug":"","type":"dash-db","tags":[],"isStarred":false,"sortMeta":0,"isDeleted":false},{"id":7,"uid":"89VouM14z","title":"Frigate","uri":"db/frigate","url":"/d/89VouM14z/frigate","slug":"","type":"dash-db","tags":[],"isStarred":false,"sortMeta":0,"isDeleted":false},{"id":1,"uid":"YIIzB274z","title":"InfluxDB 2.x Telegraf Docker Dashboard","uri":"db/influxdb-2-x-telegraf-docker-dashboard","url":"/d/YIIzB274z/influxdb-2-x-telegraf-docker-dashboard","slug":"","type":"dash-db","tags":["docker","influxdb2.0"],"isStarred":false,"sortMeta":0,"isDeleted":false},{"id":5,"uid":"ofdKJG37k","title":"LAPI Metrics","uri":"db/lapi-metrics","url":"/d/ofdKJG37k/lapi-metrics","slug":"","type":"dash-db","tags":[],"isStarred":false,"sortMeta":0,"isDeleted":false}]
```

Despite this, I still see an API error on Homepage: "API Error: Unexpected token 'I', "Internal S"... is not valid JSON".

The word "Internal" doesn't appear anywhere in the above API output, so I'm not sure why it's showing this error.

The Grafana logs from the time I did that last curl onwards is as follows:

```
logger=context userId=0 orgId=0 uname= t=2024-07-26T00:09:36.367152401Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=172.22.0.1 time_ms=0 duration=38.364µs size=29 referer= handler=/ status_source=server
logger=cleanup t=2024-07-26T00:12:18.529519413Z level=info msg="Completed cleanup jobs" duration=88.940028ms
logger=plugins.update.checker t=2024-07-26T00:12:18.883824558Z level=info msg="Update check succeeded" duration=218.054499ms
logger=infra.usagestats t=2024-07-26T00:13:37.446893167Z level=info msg="Usage stats are ready to report"
```

The Homepage logs just show this line, repeating:

`[2024-07-26T00:15:35.052Z] error: undefined`

Grafana compose file:

```
services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:main-ubuntu
    dns: 172.22.0.53
    user: "0"
    networks:
      - grafana-monitoring
      - proxy
    volumes:
    - /home/david/dockerfilesNotOnNAS/grafana/grafana:/var/lib/grafana
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.domain.com`)"
      - "traefik.http.routers.grafana.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.domain.com`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - homepage.group=Monitoring
      - homepage.name=Grafana
      - homepage.icon=grafana
      - homepage.href=https://grafana.domain.com/dashboards
      - homepage.description=Data visualisation
      - homepage.statusStyle=dot
      - homepage.widget.type=grafana
      - homepage.widget.url=grafana.domain.com
      - homepage.widget.username=user
      - homepage.widget.password=pass
networks:
  proxy:
    external: true
```

Homepage compose file:

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    #user: 1000:1000 # uncomment if you do not want to run as root
    #ports: # uncomment if you are not using a reverse proxy
    #  - 3000:3000
    dns: 172.22.0.53
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /home/david/docker/homepage/images:/app/public/images # Path to background image stored on computer.
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`homepage.domain.com`)"
      - "traefik.http.routers.homepage.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.domain.com`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      # - "traefik.http.routers.homepage-secure.middlewares=middlewares-authentik@file"
     # - "traefik.http.routers.homepage-secure.middlewares=default-whitelist@file" # uncomment if you want to use a Traefik whitelist to restrict access
     # - "traefik.http.routers.homepage-secure.middlewares=authelia@docker" # uncomment if you want to use authelia
     # - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
```

Any thoughts on what might be the cause of this problem please?

Thank you.
Dave

### homepage version

0.9.5

### Installation method

Docker

### Troubleshooting

I followed all steps in [the troubleshooting guide](https://gethomepage.dev/v0.9.5/troubleshooting/#general-troubleshooting-tips).
