### DISCUSSION TITLE
[BUG] Kubernetes service status check fails when ingress name differs from service name

### DISCUSSION THREAD

**Discussion by Mik4sa** [gethomepage/homepage#3781] [Support]
### Description

I'm running youtrack in my kubernetes cluster but homepage fails for the online / status check.

These are my two needed ingress configs:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtrack-event-source-bus
  namespace: youtrack-prod
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache off;
      proxy_set_header Connection '';
      chunked_transfer_encoding off;
spec:
  ingressClassName: nginx
  rules:
    - host: youtrack.svc.local
      http:
        paths:
        - backend:
            service:
              name: youtrack
              port:
                number: 8080
          pathType: Prefix
          path: /api/eventSourceBus
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtrack-root
  namespace: youtrack-prod
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffers: "64k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "128k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_busy_buffers_size 128k;
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "YouTrack"
    gethomepage.dev/icon: "/images/youtrack.svg"
spec:
  ingressClassName: nginx
  rules:
    - host: youtrack.svc.local
      http:
        paths:
        - backend:
            service:
              name: youtrack
              port:
                number: 8080
          pathType: Prefix
          path: /
```

The request url from homepage is: `https://dashboard.svc.local/api/kubernetes/status/youtrack-prod/youtrack-root?` this results into: `{"status":"not found"}`
When making a custom request to: `https://[dashboard.svc.local/api/kubernetes/status/youtrack-prod/youtrack](https://dashboard.svc.local/api/kubernetes/status/youtrack-prod/youtrack)` everything is working. The result then is: `{"status":"running"}`

Looks like the name of the ingress resources is used and not the actual referenced service name.

### homepage version

v0.9.5 (eccd96a)

### Installation method

Other (please describe above)

### Troubleshooting

See above for all details.
