### DISCUSSION TITLE
[Storage Widget Broken] No longer correctly reports values for NAS like it used to, now only incorrectly provides values for main drive

### DISCUSSION THREAD

**Discussion by crocodilestick** [gethomepage/homepage#3786] [Support]
### Description

The Storage Widget has worked perfectly for over a year but since a recent update, it no longer correctly, no longer reporting values for NAS it's pointed to like it used to, now only incorrectly providing values for main drive no matter how deep into the NAS's filesystem I point it.

Other container's like File Browser have no problem reporting the correct values so it's something that was changed in a recent update.

### homepage version

v0.9.2 (af16956, Jun 6, 2024)

### Installation method

Docker

### Configuration

```yaml
- resources:
    label: Storage
    disk: 
        - /
        - /media/toshiba
        - /media/nas
```

### Troubleshooting

![Screenshot 2024-07-28 010350](https://github.com/user-attachments/assets/3b8e849b-4d17-4d91-9057-67418c02f9ab)

- Should report the values for the 8TB NAS it's pointed to like it did before but something in a recent update broke it.
- Doesn't matter how deep into the NAS's filesystem I point it
- Other container's like File Browser have no problem reporting the correct values so it's something that was changed in a recent update.

**Comment by shamoon** [comment]
Feel free to review the commits, nothing changed. I’d re-create (not restart) the container, etc

**Comment by faximan** [comment]
I think I have the same issue, the Resources storage widget is reporting the wrong values.

compose:
```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: 501
      PGID: 20
    ports:
      - 3001:3000
    volumes:
      - ./config:/app/config
      - /Volumes/Zion:/mnt/zion:ro
```

widgets.yaml:
```
- resources:
    label: Zion
    expanded: true
    disk: /mnt/zion
```

Result:
![Screenshot 2025-01-06 at 19 59 42](https://github.com/user-attachments/assets/d9c2f06f-14e4-41ab-bbab-1d4ecac8fb2e)

But this drive is 12TB. Inside the homepage container:

```
df -h | grep zion
mac                      10.9T      5.2T      5.7T  48% /mnt/zion
```

How is Homepage getting the values for the disk usage?
