### DISCUSSION TITLE
API Error Key

### DISCUSSION THREAD

**Discussion by greenh0** [gethomepage/homepage#3787] [Support]
### Description

I have been having an issue where almost all (besides 3) widgets are not working. There is nothing that I can figure out so far that is different from the containers that are working and those that aren't.

Here is an example of my YAML file:
- Media:
    - Lidarr:
        icon: lidarr.png
        href: http://myurl:8686
        description: Music management
        widget: 
            type: lidarr
            url: http://myurl:8686
            key: myapikey
    - Radarr:
        icon: radarr.png
        href: http://myurl:8989
        description: Movie management
        widget:
            type: radarr
            url: http://myurl:8989
            key: myapikey
    - Sonarr:
        icon: sonarr.png
        href: http://myip:7878
        description: Series management
        widget:
            type: sonarr
            url: http://myip:7878
            key: myapikey
        
![image](https://github.com/user-attachments/assets/23fd9e1e-288f-45e1-834a-3a5e50f9a8fa)

### homepage version

v0.9.5

### Installation method

Docker

### Troubleshooting

I have tried disabling the firewall on my Synology NAS, checking permissions, re-generating the API key a few times on each container, and still no luck.

**Comment by Peronia** [comment]
I use only Radarr and have the same problem:
<img width="573" alt="grafik" src="https://github.com/user-attachments/assets/7e2d2c2e-72a1-4c5e-8394-cc7d08a52c19" />

**Reply by owennewo-dev** [reply]
Please post the code for Radarr from your `services.yaml` file.

**Reply by Peronia** [reply]
Sure, sorry that I missed this:
Radarr:
```
    - Host:
        icon: https://radarr.video/img/logo.png
        href: https://host:9898
        description: Radarr
        siteMonitor: https://host:9898
        widget:
            type: radarr
            url: https://host:9898
            key: <removed>
            enableQueue: true
```
Radarr version: 5.15.1.9463

I also get the same error with Sonarr:
```
    - Host:
        icon: https://sonarr.tv/img/logo.png
        href: https://host:9899
        description: Sonarr
        siteMonitor: https://host:9899
        widget:
            type: sonarr
            url: https://host:9899
            key: <removed>
            enableQueue: true
```
Sonarr version: 4.0.11.2680
homepage version: 0.10.2

I don't use Lidarr so I can't say anything about this error.
