### DISCUSSION TITLE
Yet Another Portainer Post

### DISCUSSION THREAD

**Discussion by pageagency** [gethomepage/homepage#3789] [Support] [answered]
### Description

I am having issues with portainer widgets as i see several people are/were.  I have 2 portainer instances in my local env and 2 at remote locations. The two internal instances say "API Error: Invalid JWT token" and the two remote instances say "API Error: A valid authorisation token is missing"

If i mess with it long enough sometimes I can get the json or whitespace error that others have mentioned.  Here is a screenshot:
![image](https://github.com/user-attachments/assets/707d21f4-5425-452b-955a-e6005871eab8)

### homepage version

v0.9.5 

### Installation method

Docker

### Configuration

```yaml
services:

- PH2:
        icon: portainer.png
        href: 'redacted'
        description: Portainer instance on PH2
        ping: 'redacted'
        siteMonitor: 'redacted'
        container: portainer
        showStats: true
        server: ph2-docker
        widget:
          type: portainer
          url: 'redacted'
          env: 2
          token: 'redacted'

    - PH2 NPM (nginx):
        icon: nginx.png
        href: 'redacted'
        description: Proxy
        widget:
          type: npm
          url: 'redacted'
          username: 'redacted'
          password: 'redacted'


docker:

ph2-docker:
  host: 'redacted-remote ip port shows open'
  port: 2375

ph1-docker:
  host: dockerproxy
  port: 2375
```

### Container Logs

[2024-07-27T22:44:03.144Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]/api/endpoints/2/docker/containers/json?all=1
[2024-07-27T22:44:03.202Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]/api/endpoints/2/docker/containers/json?all=1
[2024-07-27T22:44:03.222Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]:9443/api/endpoints/2/docker/containers/json?all=1
[2024-07-27T22:44:03.250Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]/api/endpoints/2/docker/containers/json?all=1
[2024-07-27T22:44:28.040Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]/api/endpoints/2/docker/containers/json?all=1
[2024-07-27T22:44:28.041Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]/api/endpoints/2/docker/containers/json?all=1
[2024-07-27T22:44:28.117Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]/api/endpoints/2/docker/containers/json?all=1
[2024-07-27T22:44:28.163Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://[redacted]:9443/api/endpoints/2/docker/containers/json?all=1

### Browser Logs

just a bunch of 401 errors. 

### Troubleshooting

I have tried IP's, FQDN, interal docker ips, host ips, public ips, values in double  quotes, values in single quotes,  dockerproxy container ,editing daemon, and everything else I can think of, but I can successfully curl the portainer APIs with their keys from within the homepage container, so i know the keys and end points work. I am at a loss and it appears to only be the portainer widgets.
