### DISCUSSION TITLE
Provide a way to mount an icon directory

### DISCUSSION THREAD

**Discussion by T00rk** [gethomepage/homepage#3792] [Feature Requests]
### Description

It would be nice to have the possibility to get icons from a local directory.

Example:

```yaml
 - React:
        icon: /custom-icons/react.svg
        href: http://localhost:3000
```

### Other

I'm pretty sure there's already a way to do that, but there is no documentations about how to do it.
