### DISCUSSION TITLE
[Feature Request] - Technitium DNS Server Widget

### DISCUSSION THREAD

**Discussion by xXAzazelXx** [gethomepage/homepage#3805] [Feature Requests]
### Description

Hi Guys,

Would it be possible to add support for Technitium DNS Server Widget?
[https://technitium.com/dns/](url)
[Technitium DNS Server API Documentation](url)

**Comment by suicidaleggroll** [comment]
I agree that this would be nice.  In the mean time you can implement this using the customapi option in Homepage (just change "apitoken" to a token for your Technitium instance):
```
widget:
  type: customapi
  url: https://dns.example.com/api/dashboard/stats/get?token=apitoken&type=lastHour
  refreshInterval: 10000
  mappings:
    - field:
        response:
          stats: totalClients
      label: Clients
      format: text
    - field:
        response:
          stats: totalQueries
      label: Queries
      format: text
    - field:
        response:
          stats: totalBlocked
      label: Blocked
      format: text
    - field:
        response:
          stats: blockListZones
      label: BlockList
      format: text
```
There are a LOT of other fields available, just curl that url from the command line to see what all the options are.
