### DISCUSSION TITLE
Docker on other machine

### DISCUSSION THREAD

**Discussion by robertobasile84** [gethomepage/homepage#3809] [Support]
### Description

I successfully configured my remote Docker to point to a NAS that is running various services. However, I am struggling to find information on what steps to take next.

Since I can now communicate remotely with that Docker, how can I display the statuses of those running services on my homepage?

The documentation I have found so far is not clear on this matter.

### homepage version

v0.9.5

### Installation method

Docker

### Troubleshooting

I can just see that the docker starts and my homepage is there, but no clue on how to get where I need

**Comment by shamoon** [comment]
I think you need to be more specific about what youre trying to do but for Docker integration you can use a remote docker host, its literally the first example in the docs: https://gethomepage.dev/latest/configs/docker/

**Reply by jonsworkalias** [reply]
the above link is a 404 page.

**Reply by shamoon** [reply]
Was it really that hard to find since it’s moved from 8 months ago? https://gethomepage.dev/configs/docker/

**Comment by MikeBishop** [comment]
In general, the best way to integrate that is to point a widget at the service and then annotate that with the Docker server and container name. Homepage will then inject the container status over the widget/link.  For example:

```
    - AudioBookShelf:
        icon: audiobookshelf
        href: https://audiobooks.home.bishop.be
        server: catacomb
        container: audiobookshelf
        widget:
            type: audiobookshelf
            url: https://audiobooks.home.bishop.be
            key: XXXXX
            fields: ["books", "booksDuration"]
```

Produces this:
![image](https://github.com/user-attachments/assets/77cce86e-5872-43af-97fe-18db0f5d43b5)

(Note the "HEALTHY" in the corner, which comes from Docker, not from ABS itself.)
