### DISCUSSION TITLE
Add Custom Widget to Docker Container

### DISCUSSION THREAD

**Discussion by DonFU1** [gethomepage/homepage#3825] [Support] [answered]
### Description

Hi guys,

I am struggling to add a custom widget to the docker container. I tried mounting /app/src/widgets to my host file, and add my widget without any effect. Homepage still says "Missing Widget Type: mywidget". 
Whats the correct way to add a custom widget into the container using docker-compose? In which directory are the widgets stored in the container? 

Best regards

### homepage version

v0.9.5 (eccd96a, Jul 18, 2024)

### Installation method

Docker

### Configuration

```yaml
My docker-compose file:
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /root/homepage/config:/app/config
      - /root/homepage/data/images:/app/public/images
      - /root/homepage/data/icons:/app/public/icons
```

### Troubleshooting

not relevant
