### DISCUSSION TITLE
api error on disk size widget

### DISCUSSION THREAD

**Discussion by Ikarias** [gethomepage/homepage#3829] [Support] [answered]
### Description

I have a large disk mounted as /data. When i ask for disk space on / i get only that disk, when i ask for /data i get an api error

Widgets.yaml has this:
`- resources:`
`    label: Server`
 `    expanded: true`
 `     disk: `
 `     - /`
 `     - /data`

I think there's something wrong with my mounting path but i dont want to mess things up by messing with it.

### homepage version

v0.9.5 (eccd96a, Jul 18, 2024)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets
- openmeteo:
    label: Hoogvliet
    latitude: 51.55
    longitude: 4.30
    cache: 5

- resources:
    label: System
    cpu: true
    memory: true
    
- resources:
    label: Server
    expanded: true
    disk: 
      - /
      - /data

- search:
    provider: duckduckgo
    target: _blank
    focus: true
    
- greeting:
    text_size: xl
    text: Genesis project
```

### Troubleshooting

ping: bad address 'SERVICEIPORDOMAIN'
