### DISCUSSION TITLE
None of the kubernetes integrations seem to be working

### DISCUSSION THREAD

**Discussion by v1nsai** [gethomepage/homepage#3834] [Support]
### Description

I first tried installing homepage with the helm chart, then I saw it hadn't been updated in a year and decided to try the manifests directly from the [latest version of the docs](https://gethomepage.dev/main/configs/kubernetes/).  I have made zero changes except to add LOG_LEVEL=debug to the env, which seems to have done nothing anyway as the only entry in my log is "Listening on port 3000"

I have several ingresses labeled with [the labels specified here in the docs](https://github.com/gethomepage/homepage/blob/main/kubernetes.md#service-discovery), but the only services that show up are the defaults.  The resource widget in the upper left corner just reports "API Error", which the [troubleshooting page](https://gethomepage.dev/v0.9.5/troubleshooting/) says I should be able to click on and get more info....but they're static and tell me nothing.

One issue I can think of is my environment.  I'm running the latest version of Talos Kubernetes Linux, which is kubernetes 1.30.1 and pretty bleeding edge.  Not sure if I'm perhaps running into known issues, I searched issues and discussions but didn't find anything about 1.30.  I did also find some 404s in the browser logs, nothing jumped out at me as significant or relevant though.  I posted them below.

### homepage version

v0.9.5

### Installation method

Other (please describe above)

### Configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
```

### Container Logs

Listening on port 3000

### Browser Logs
 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: the server responded with a status of 404 () 
 
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID 
 
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID 
 
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID 
 
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/widgets/resources?type=memory net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/validate net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/widgets net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/bookmarks net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/hash net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/releases net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/widgets net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/widgets/resources?type=disk&target=/ net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/services net::ERR_CERT_AUTHORITY_INVALID 
 
GET https://homepage.internal/api/bookmarks 404 (Not Found)

### Troubleshooting

not relevant
