### DISCUSSION TITLE
Increase size of logo

### DISCUSSION THREAD

**Discussion by 0kn0t0K** [gethomepage/homepage#3837] [Support] [answered]
I've been playing around with custom.css to try increase the size of logo at the top of the page.    This is the custom logo I added in widgets.yml.

any advice would be appreciated.

Thanks,

**Comment by shamoon** [comment, marked as answer]
You likely just need to target it with a more specific rule eg

```css
.information-widget-logo,
.information-widget-logo svg {
    width: 200px;
    height: 200px;
}
```
