### DISCUSSION TITLE
myspeed

### DISCUSSION THREAD

**Discussion by david85091** [gethomepage/homepage#3838] [Support] [answered]
### Description

giving me an api error
API Error Information
API Error: Invalid data
URL: http://192.168.1.59:5216//api/speedtests?limit=1
Response Data:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/assets/img/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#232835" />
    <meta property="og:image" content="/assets/img/logo.png" />
    <meta name="description"
          content="A speed test analysis software that shows your internet speed for up to 30 days"
    />
    <link rel="apple-touch-icon" href="/assets/img/logo192.png" />
    <link rel="manifest" href="/manifest.json" />
    <title>MySpeed</title>
    <script type="module" crossorigin src="/assets/index-BJZ8oKdX.js"></script>
    <link rel="modulepreload" crossorigin href="/assets/vendor-BDk2oUVD.js">
    <link rel="modulepreload" crossorigin href="/assets/icons-DtxvO1kL.js">
    <link rel="stylesheet" crossorigin href="/assets/index-B0M1nYWK.css">
  <script id="vite-plugin-pwa:register-sw" src="/registerSW.js"></script></head>
  <body>
    <div id="root"></div>
  </body>
</html>

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
name: myspeed
services:
    myspeed:
        ports:
            - 5216:5216
        volumes:
            - ./myspeed:/myspeed/data
        restart: unless-stopped
        container_name: MySpeed
        image: germannewsmaker/myspeed
volumes:
    myspeed:
        external: true
        name: myspeed
```

### Troubleshooting

```
    - MySpeed Test:
#        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/openspeedtest.png
        href: http://192.168.1.59:5216/
#        ping: http://192.168.1.59:5216/
        widget:
         type: myspeed
         url: http://192.168.1.59:5216/
#         password: password # only required if password is set
no password set
```
