### DISCUSSION TITLE
Remove AI and other things from Google search results udm14?

### DISCUSSION THREAD

**Discussion by LiamKarlMitchell** [gethomepage/homepage#3839] [General]
In widgets.yaml config you can put like this.
```
- search:
    provider: custom
    target: _blank
    url: https://www.google.com/search?udm=14&q=
```

This sets 'Web' as the default search mode without AI and other clutter such as ads possibly?
Seems to work.
But also removes other fun things like metrics conversion, currency conversion, calculator etc which on second thought I actually do find useful... bummer.
