### DISCUSSION TITLE
Tubearchivist widget: api error

### DISCUSSION THREAD

**Discussion by Nonoss117** [gethomepage/homepage#3840] [Support] [answered]
### Description

TubeArchivist **v0.4.10** (docker installation)

Tubearchivist widget was ok, but since several days (homepage versions, and Tubearchivist updates) now, the widget have api error :
![1](https://github.com/user-attachments/assets/66cb8ab9-0195-47c9-99b3-711b23bb6353)

![2](https://github.com/user-attachments/assets/0ce984fe-7733-4a65-bfdc-821c1446830e)

Thank's for the help

### homepage version

nightly (74f76e2)

### Installation method

Docker

### Configuration

```yaml
- Tube Archivist:
        icon: tube-archivist.png
        href: https://tubearchivist.mydomain.com/
        server: nas-docker
        container: tubearchivist
        description: YouTube vidéos
        widget:
          type: tubearchivist
          fields: ["videos", "channels", "playlists"]  #["downloads", "videos", "channels", "playlists"]
          url: https://tubearchivist.mydomain.com
          key: redacted
```

### Container Logs

[2024-08-11T06:35:03.334Z] warn: Invalid data for widget 'tubearchivist' endpoint 'stats/download':
Expected:pending
Parse error: none
Data: {"type":"Buffer","data":[123,34,105,103,110,111,114,101,34,58,50,48,51,52,125]}

### Troubleshooting

/

**Edit:**
Everything is working fine with Homepage [v0.9.5 (eccd96a, 18 juil. 2024)](https://github.com/gethomepage/homepage/releases/tag/v0.9.5)

So I think something is broken with Homepage nightly versions (not since the latest, but several before)
