### DISCUSSION TITLE
Calendar suddenly stopped working

### DISCUSSION THREAD

**Discussion by cplieger** [gethomepage/homepage#3842] [Support] [answered]
### Description

I have 2 separate homepage instances both connected to the same radarr and sonarr instances. For a few days now they have stopped displaying any events on both installations. No config changes were made, they run on completely separate machines with separate configs.

The radarr and sonarr widgets seem to load just fine, there is no api error in the calendar, just no data:
![image](https://github.com/user-attachments/assets/53fe9ebd-f0b2-4b5c-ad85-7d0618f1d623)

Looking at the logs I sometimes get this error: 
`API response for /api/services/proxy?group=Downloads&service=Movie+management&endpoint=radarr exceeds 4MB. API Routes are meant to respond quickly.`

but these errors are not consistent, and I had these errors 2 months ago and the calendar worked fine. The widgets for radarr and sonarr still load fine every time. Even if radarr had an issue I assume sonarr data should still appear.

any way I can debug this? Does anyone else have this issue?

### homepage version

0.9.5

### Installation method

Docker

### Configuration

```yaml
Part of services.yaml:

- Media:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          showTime: true
          timezone: Europe/Paris
          integrations:
            - type: sonarr 
              service_group: Automation 
              service_name: Sonarr 
              params: 
                unmonitored: true 
            - type: radarr 
              service_group:  Automation 
              service_name: Radarr 
              params: 
                unmonitored: true 
- Automation:
    - Radarr:
        href: https://radarr.url.com
        icon: radarr
        id: col-small
        siteMonitor: https://radarr.url.com
        widget:
          type: radarr
          url: http://192.168.1.77:17878
          key: xxxxxxxxxxxxxxxxxxxxxxxxxxx
          fields: ["queued", "movies"]
    - Sonarr:
        href: https://sonarr.url.com
        icon: sonarr.png
        id: col-small
        siteMonitor: https://sonarr.url.com
        widget:
          type: sonarr
          url: http://192.168.1.77:18989
          key: xxxxxxxxxxxxxxxxxxxxxxx
```

### Container Logs

[2024-06-06T12:35:14.369Z] warn: API response for /api/services/proxy?type=radarr&group=Media+automation&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2024-06-06T12:35:21.074Z] warn: API response for /api/services/proxy?type=qbittorrent&group=Download+tools&service=Qbittorrent&endpoint=torrents%2Finfo exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit

### Troubleshooting

No connection issue with the APIs as widgets load
