### DISCUSSION TITLE
Tailscale widget bug

### DISCUSSION THREAD

**Discussion by hundredfire** [gethomepage/homepage#3853] [Support]
### Description

Hello guys. My tailscale widget used to work flawlessly, but for some time now, I have the following error in my docker logs (hid my deviceId):
```error: <credentialedProxyHandler> HTTP Error 404 calling https://api.tailscale.com/api/v2/device/############CNTRL``` 

The following message appears on homepage too:
```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

    at c (http://192.168.1.10:3550/_next/static/chunks/9986.780aa2970c3bac02.js:1:1043)
    at h (http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:34752)
    at n (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:17139)
    at R (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:33195)
    at div
    at li
    at M (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:37089)
    at ul
    at J (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:41152)
    at div
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:78656
    at div
    at l (http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:107412)
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:96815
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:95583
    at l (http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:107412)
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:76595
    at div
    at $ (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:41652)
    at div
    at div
    at ge (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:62228)
    at n (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:17139)
    at http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:90763
    at ve (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:60236)
    at div
    at div
    at div
    at we (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:69274)
    at a (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:16139)
    at a (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:15783)
    at s (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:16697)
    at u (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:15211)
    at http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:90763
    at http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:14462
    at l (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:1250)
    at n (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:5714)
    at r (http://192.168.1.10:3550/_next/static/chunks/main-6c70321fa035d8ca.js:1:6991)
    at Y (http://192.168.1.10:3550/_next/static/chunks/main-6c70321fa035d8ca.js:1:9236)
    at ie (http://192.168.1.10:3550/_next/static/chunks/main-6c70321fa035d8ca.js:1:11878)
```

Here's the relevant part of the settings yaml:
```    
- Tailscale: 
        icon: /icons/tailscale.svg
        href: https://login.tailscale.com/admin/machines
        description: Tailscale VPN
        widget:
          type: tailscale
          fields: ["address"]
          deviceid: ############CNTRL
          key: tskey-api-############CNTRL-#########################```
This points to a possible authentication issue with tailscale, so I created a new API token, updated homepage, restarted many times, to no avail.
This used to work without any issue on my existing config on docker, so I'm quite sure it's not related to a network issue? But I don't know what to do anymore..
Any ideas?


### homepage version

0.9.6

### Installation method

Docker

### Configuration

```yaml
- Tailscale: 
        icon: /icons/tailscale.svg
        href: https://login.tailscale.com/admin/machines
        description: Tailscale VPN
        widget:
          type: tailscale
          fields: ["address"]
          deviceid: ############CNTRL
          key: tskey-api-############CNTRL-#########################```
```

### Container Logs

```
Listening on port 3000
[2024-08-14T12:34:56.035Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://api.tailscale.com/api/v2/device/############CNTRL ````

### Browser Logs

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

    at c (http://192.168.1.10:3550/_next/static/chunks/9986.780aa2970c3bac02.js:1:1043)
    at h (http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:34752)
    at n (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:17139)
    at R (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:33195)
    at div
    at li
    at M (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:37089)
    at ul
    at J (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:41152)
    at div
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:78656
    at div
    at l (http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:107412)
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:96815
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:95583
    at l (http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:107412)
    at http://192.168.1.10:3550/_next/static/chunks/3657-fc23499a89c4283f.js:1:76595
    at div
    at $ (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:41652)
    at div
    at div
    at ge (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:62228)
    at n (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:17139)
    at http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:90763
    at ve (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:60236)
    at div
    at div
    at div
    at we (http://192.168.1.10:3550/_next/static/chunks/pages/index-96af4528503a8c52.js:1:69274)
    at a (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:16139)
    at a (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:15783)
    at s (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:16697)
    at u (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:15211)
    at http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:90763
    at http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:14462
    at l (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:1250)
    at n (http://192.168.1.10:3550/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:5714)
    at r (http://192.168.1.10:3550/_next/static/chunks/main-6c70321fa035d8ca.js:1:6991)
    at Y (http://192.168.1.10:3550/_next/static/chunks/main-6c70321fa035d8ca.js:1:9236)
    at ie (http://192.168.1.10:3550/_next/static/chunks/main-6c70321fa035d8ca.js:1:11878)```

### Troubleshooting

pinging api.tailscale.com works.
curl test works using:
```
curl -u "xxxxxCNTRL" https://api.tailscale.com/api/v2
```
then entering key.
