### DISCUSSION TITLE
Add Kapowarr [Feature Request]

### DISCUSSION THREAD

**Discussion by Druidblack** [gethomepage/homepage#3856] [Feature Requests] [answered]
### Description

![info](https://github.com/user-attachments/assets/668197b1-4da1-4027-83c6-8c0c753c44da)
Kapowarr is a software to build and manage a comic book library, fitting in the *arr suite of software.
https://github.com/Casvt/Kapowarr

```
 - Kapowarr:
    icon: kapowarr.png
    href: http://192.168.1.161:5656/
    description: Kapowarr is a software to build and manage a comic book library, fitting in the *arr suite of software.
    widget:
      type: customapi
      url: http://192.168.1.161:5656/api/volumes/stats?api_key=API
      refreshInterval: 10000 # 10 секунд
      method: GET
      mappings:
       - field: 
           result:
              volumes
         label: Volumes
         format: number
       - field: 
           result:
              issues
         label: Issues
         format: number
       - field: 
           result:
              downloaded_issues
         label: Issues downloaded
         format: number
       - field: 
           result:
              monitored
         label: Monitored
         format: number
       - field: 
           result:
              total_file_size
         label: Total file size
         format: number
```
