### DISCUSSION TITLE
Help with Pi Hole

### DISCUSSION THREAD

**Discussion by Alex-joomla** [gethomepage/homepage#3858] [Support]
### Description

Tried to set up the Pi-Hole widget:
```
    - Pi-Hole:
        icon: pi-hole.png
        href: "http://10.0.10.2/admin"
        description: PiHole
        widget:
          type: pihole
          url: http://10.0.10.2
          version: 5 # required if running v6 or higher, defaults to 5
          key: <my apip key>
```

But I get this error:

```
API Error: Unknown error
URL: http://10.0.10.2/admin/api.php?summaryRaw=&auth=***
Raw Error:
{
    "errno": -113,
    "code": "EHOSTUNREACH",
    "syscall": "connect",
    "address": "10.0.10.2",
    "port": 80
}
```

If i enter the URL+my API Key I get this output:

```
{
  "domains_being_blocked": 164642,
  "dns_queries_today": 111392,
  "ads_blocked_today": 9311,
  "ads_percentage_today": 8.358769,
  "unique_domains": 11755,
  "queries_forwarded": 62566,
  "queries_cached": 38561,
  "clients_ever_seen": 88,
  "unique_clients": 78,
  "dns_queries_all_types": 111392,
  "reply_UNKNOWN": 1699,
  "reply_NODATA": 21733,
  "reply_NXDOMAIN": 8884,
  "reply_CNAME": 36737,
  "reply_IP": 31659,
  "reply_DOMAIN": 9356,
  "reply_RRNAME": 0,
  "reply_SERVFAIL": 171,
  "reply_REFUSED": 0,
  "reply_NOTIMP": 0,
  "reply_OTHER": 0,
  "reply_DNSSEC": 6,
  "reply_NONE": 0,
  "reply_BLOB": 1147,
  "dns_queries_all_replies": 111392,
  "privacy_level": 0,
  "status": "enabled",
  "gravity_last_updated": {
    "file_exists": true,
    "absolute": 1723363681,
    "relative": {
      "days": 3,
      "hours": 13,
      "minutes": 20
    }
  }
}
```

What's the problem here?

### homepage version

0.9.6

### Installation method

Docker

### Configuration

```yaml
I run homepage via docker compose
```

### Troubleshooting

See above
