### DISCUSSION TITLE
Settings.yaml settings selectively working

### DISCUSSION THREAD

**Discussion by v1nsai** [gethomepage/homepage#3861] [Support] [answered]
### Description

I installed homepage on kubernetes using the [manifest files directly from the documentation](https://gethomepage.dev/main/configs/kubernetes/). When I change things in the `settings.yaml` key in the ConfigMap and restart the Homepage container, I get mixed results.  Changing `background` to an image URL works, but setting `background` to a color, or setting the `color` and `theme` options have no effect.  No matter what I set them to, I get this weird red salmon pink color.  Even the color palette in the bottom left is all the same color:

<img width="1440" alt="Screenshot 2024-08-15 at 11 56 41 AM" src="https://github.com/user-attachments/assets/9f3cf5e4-f0d6-40b0-9c54-548f00b1a094">

### homepage version

0.9.5 e23fcd332ecf927fe5c0149142040236b17686916004566c149eef06eb6f8d75

### Installation method

Other (please describe above)

### Configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Drew's Cool Shit
    theme: dark
    color: cyan
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Home:
        - HomeAssistant:
            - abbr: hass
              href: http://home-assistant.internal:8123
  services.yaml: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
```

### Container Logs

Nothing relevant in the logs

### Browser Logs

Nothing relevant

### Troubleshooting

Nothing relevant
