### DISCUSSION TITLE
Gamedig widget no longer shower minecraft bedrock edition (be) status properly

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#3862] [Support] [answered]
### Description

The Gamedig widget was working previously, but is now showing that the Minecraft server is offline. It is online. It was previously working with `serverType: minecraftbe` and I also tried `mbe` and `minecraft`

### homepage version

nightly 40b0f95, Aug 15, 2024

### Installation method

Docker

### Configuration

```yaml
    - Creative (port 19132):
        icon: minecraft.png
        href: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
#        description: Ubuntu server on Oracle
        widget:
            type: gamedig
            serverType: minecraftbe
            url: udp://{{HOMEPAGE_VAR_ORACLE_IP}}:19132
            fields: ["name", "players", "status"]
    - Survival (port 19134):
        icon: minecraft.png
        href: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
#        description: Ubuntu server on Oracle
        widget:
            type: gamedig
            serverType: minecraftbe
            url: udp://{{HOMEPAGE_VAR_ORACLE_IP}}:19134
            fields: ["name", "players", "status"]
```

### Container Logs
```bash
[2024-08-15T23:51:18.035Z] error: <httpProxy> Error calling [http://redacted/...](http://redacted:7396/...%3C/span%3E%3C/span%3E)
[2024-08-15T23:51:18.035Z] error: <httpProxy> [
  500,
  Error: socket hang up
      at connResetException (node:internal/errors:720:14)
      at Socket.socketOnEnd (node:_http_client:525:23)
      at Socket.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
]
[2024-08-15T23:51:20.787Z] error: <httpProxy> Error calling [http://redacted:7396/...](http://redacted:7396/...%3C/span%3E%3C/span%3E)
[2024-08-15T23:51:20.787Z] error: <httpProxy> [
  500,
  Error: socket hang up
      at connResetException (node:internal/errors:720:14)
      at Socket.socketOnEnd (node:_http_client:525:23)
      at Socket.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
]
[2024-08-15T23:51:28.864Z] error: <gamedigProxyHandler> Error: Failed all 1 attempts
    at QueryRunner.run (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/QueryRunner.js:106:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:11:12)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:21:12)
    at async gamedigProxyHandler (/app/.next/server/pages/api/services/proxy.js:2949:24)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
Attempt #1 - Port=19132 Retry=0:
Error: Attempt - Timed out after 10000ms
    at Timeout.<anonymous> (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-08-15T23:51:29.888Z] error: <gamedigProxyHandler> Error: Failed all 1 attempts
    at QueryRunner.run (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/QueryRunner.js:106:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:11:12)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:21:12)
    at async gamedigProxyHandler (/app/.next/server/pages/api/services/proxy.js:2949:24)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
Attempt #1 - Port=19134 Retry=0:
Error: Attempt - Timed out after 10000ms
    at Timeout.<anonymous> (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-08-15T23:51:30.562Z] error: <gamedigProxyHandler> Error: Failed all 1 attempts
    at QueryRunner.run (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/QueryRunner.js:106:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:11:12)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:21:12)
    at async gamedigProxyHandler (/app/.next/server/pages/api/services/proxy.js:2949:24)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
Attempt #1 - Port=19132 Retry=0:
Error: Attempt - Timed out after 10000ms
    at Timeout.<anonymous> (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-08-15T23:51:30.576Z] error: <gamedigProxyHandler> Error: Failed all 1 attempts
    at QueryRunner.run (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/QueryRunner.js:106:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:11:12)
    at async GameDig.query (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/gamedig.js:21:12)
    at async gamedigProxyHandler (/app/.next/server/pages/api/services/proxy.js:2949:24)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
Attempt #1 - Port=19134 Retry=0:
Error: Attempt - Timed out after 10000ms
    at Timeout.<anonymous> (file:///app/node_modules/.pnpm/gamedig@5.1.1/node_modules/gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

### Troubleshooting
```bash
docker exec homepage ping [redactedIP]
PING redactedIP (readactedIP): 56 data bytes
```

**Comment by shamoon** [comment]
Sigh. We can assume this is https://github.com/gethomepage/homepage/pull/3841 which might make it more trouble than its worth.

I don't really have much to do to check this out, it does seem like `mbe` should work and otherwise nothing about gamedig changed.

Perhaps other gamedig users can chime in, TBH I'm inclined to just revert the PR if it is breaking things.

**Comment by shamoon** [comment]
@mgrimace would you mind asking over at gamedig? Maybe their discord? The homepage code is very simple: https://github.com/gethomepage/homepage/blob/0d25f5789b2b46b8adb85eb31883f31fe07f61df/src/widgets/gamedig/proxy.js#L15-L21

Also have you tried the basic stuff like re-creating (removing and recreating, not just restart) the container?

**Reply by mgrimace** [reply]
No problem, I'll ask over there. I saw that gamedig was updated in the logs, and checked out the new game codes and figured `mbe` (the new minecraft:be code) would work, but its not connecting properly on my end at least. Yep, tried the basics (remove/recreate) after setting it as `mbe`, no change. I'll report back if I can find anything.

**Comment by shamoon** [comment]
Alright, so I forgot how easy gamedig is to test with public servers. These two work fine:

```yaml
     - GameDig csgo:
          widget:
               type: gamedig
               serverType: csgo # see https://github.com/gamedig/node-gamedig#games-list
               url: udp://135.148.151.222:16261
               fields: ["status", "maxPlayers"]
     - GameDig mbe:
          widget:
               type: gamedig
               serverType: mbe # see https://github.com/gamedig/node-gamedig#games-list
               url: udp://play.spacecraftsmp.com:25565
               fields: ["status", "maxPlayers"]
```

<img width="1476" alt="Screenshot 2024-08-15 at 9 47 38 PM" src="https://github.com/user-attachments/assets/44a149a8-45ed-4858-bbab-4dea37b01322">

(also worked fine with `serverType: minecraftbe`)
