### DISCUSSION TITLE
Search quick in quicklaunch not working

### DISCUSSION THREAD

**Discussion by saschabrockel** [gethomepage/homepage#3864] [Support] [answered]
### Description

This video will say more than I can explain. The site has no focus. I try to search for any service but the site is stuck. You can already see some item is selected and this will also be opened no matter what I click. The search also finds items that have nothing to do with my wording. It happens in Chrome and Firefox. No browser issue.

https://youtu.be/FyZRwRe9EjY

I can post more of my config but I have no idea where this behavior comes from. Too many services? I have very many and also duplicated because I have one tab where I monitor the utilization of them. Can I exclude them from the search? Haven't found an option for that.

### homepage version

v0.9.6 (805f119, Aug 11, 2024)

### Installation method

Unraid

### Configuration

```yaml
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    showSearchSuggestions: true
    hideVisitURL: true
```

### Browser Logs

:3001/#home:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
:3001/api/services/proxy?group=Documents+%26+Files&service=Immich&endpoint=stats:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:3001/api/services/proxy?group=Documents+%26+Files&service=Ghostfolio&endpoint=today:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/services/proxy?group=Documents+%26+Files&service=Ghostfolio&endpoint=year:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/services/proxy?group=Documents+%26+Files&service=Ghostfolio&endpoint=max:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/#home:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
:3001/api/services/proxy?group=Documents+%26+Files&service=Ghostfolio&endpoint=today:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/services/proxy?group=Documents+%26+Files&service=Ghostfolio&endpoint=year:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/services/proxy?group=Documents+%26+Files&service=Ghostfolio&endpoint=max:1 
        

### Troubleshooting

Not relevant.

**Comment by shamoon** [comment, marked as answer]
Dunno, but not aware of any issues and I can't reproduce this. Have you tried different browsers?

I suppose you could see if cutting down the config file(s) helps and then adding things back in parts to see if theres something specifically causing it

**Reply by saschabrockel** [reply]
You are right. I found the reason. Even though I don't open the container stats initially this is causing it. When I disable most of the service with showStats activated it works flawlessly. Can I just load them when I click on the tab or something or exclude from search?

```
- Containers:
          - Plex:
                    icon: plex.png
                    href: http://192.168.178.29:32400/web/index.html
                    server: unraid
                    container: plex
                    showStats: true
          - Tautulli:
                    icon: tautulli.png
                    href: http://192.168.178.29:8181
                    server: unraid
                    container: tautulli
                    showStats: true
          - Radarr:
                    icon: radarr.png
                    href: http://192.168.178.29:7878
                    server: unraid
                    container: radarr
                    showStats: true
```
