### DISCUSSION TITLE
docker.yaml is OK, yet error: Failed to discover services, please check docker.yaml

### DISCUSSION THREAD

**Discussion by bcurran3** [gethomepage/homepage#3865] [Support]
### Description

Weird problem.

I get the below error using homepage v0.9.6 (805f119, Aug 11, 2024) on one server using the docker.yaml below. I do not get the error on a 2nd server using homepage v0.9.2 (af16956, Jun 5, 2024). The docker.yaml is identical bit for bit. Obviously non of my containers and info are showing in homepage because of this on the box running v.0.9.6.
```
[2024-08-17T02:18:57.069Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
[2024-08-17T02:18:57.071Z] error: SyntaxError: Unexpected token [ in JSON at position 1
```

```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
#   host: 192.168.xx.yy
#   port: 2375

 my-docker:
   socket: /var/run/docker.sock
   swarm: false
```

Passively waiting for a new point release. :-) This problem started with v0.9.5 or earlier.

Bug?

### homepage version

s/a

### Installation method

Docker

### Configuration

```yaml
Both systems are:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

Both systems use:
Docker version 27.1.2, build d01f264
```

### Troubleshooting

- upgraded two (?) point releases of docker
- edited docker.yaml to move all but the  my-docker: and socket: /var/run/docker.sock lines
- re-copied and pasted docker.yaml from working 0.9.2 system to non-working 0.9.6 version

**Comment by shamoon** [comment]
Spaces matter in yaml.

It should be

```yaml
my-docker:
  socket: /var/run/docker.sock
  swarm: false
```

**Reply by bcurran3** [reply]
Agreed, but not the problem here. As mentioned, docker.yaml is the same on two servers with one working and one not. The "my-docker" portion of docker.yaml is directly pasted from the swarm part of the documentation with the variable changed from true to false. Today I edited the docker.yaml on both computers to strip out unnecessary comments and change it to only what you pasted above. homepage continues to function the same as before even after restarting the container; i.e. one works, one doesn't.

For further diagnostics I went and upgraded the server with the old version of homepage to the current version and it continued working correctly. This is perplexing. 

At this point I believe there is some environmental different between the two; possibly a setting in one of the other configuration files. Working machine is a VM running the container. Non-working machine is bare metal running the container. The two servers have minor differences in the containers they run and the settings.

What throws me is the "Failed to discover services, please check docker.yaml for errors or remove example entries." error. The docker.yaml is fine. So I looked at the file permissions. They looked fine. For shits & giggles I set it to 777. I restarted the container. I rebuilt the container. I still have the same problem. 

"SyntaxError: Unexpected token [ in JSON at position 1" - What JSON file is involved here?

**Comment by bcurran3** [comment]
Further steps to diagnose (and failed):
- deleted persistent data
- deleted container
- deleted images
- setup container from scratch (with defaults of course)
- edited docker.yaml to use docker.sock and didn't work
- edited docker.yaml clearing the file and pasting in authorative answer from above and didn't work

I still get:
```
Listening on port 3000
[2024-08-17T18:22:53.524Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
[2024-08-17T18:22:53.525Z] error: SyntaxError: Unexpected token [ in JSON at position 1
```

I still have to compare the Ansible code to set these up and verify it is the same on both servers. Will report back after doing that.

**Comment by bcurran3** [comment]
Ansible code looks good.

I just did the following and still failed:

```
docker run --name homepage \ame homepage \
  -e PUID=0 \
  -e PGID=1001 \
  -p 3000:3000 \
  -v /data/docker/homepage/config:/app/config \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --restart unless-stopped \
  ghcr.io/gethomepage/homepage:latest
Listening on port 3000
[2024-08-18T19:49:02.127Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
[2024-08-18T19:49:02.128Z] error: SyntaxError: Unexpected token [ in JSON at position 1
```
```
docker run --name homepage \
  -e PUID=0 \
  -e PGID=0 \
  -p 3000:3000 \
  -v /data/docker/homepage/config:/app/config \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --restart unless-stopped \
  ghcr.io/gethomepage/homepage:latest
Listening on port 3000
[2024-08-18T19:53:24.416Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
[2024-08-18T19:53:24.417Z] error: SyntaxError: Unexpected token [ in JSON at position 1
[2024-08-18T19:53:25.264Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
```

**Comment by shamoon** [comment]
The above corrected docker.yaml works fine for me in both versions, so I really don't know what's going on here, but you can try stripping out services etc and see if theres something else causing it.

**Comment by bcurran3** [comment]
I'm just finally getting back to this. 


```
[2024-08-31T20:25:10.997Z] error: SyntaxError: Unexpected token [ in JSON at position 1
[2024-08-31T20:26:02.131Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
```

I'm convinced we're looking at the wrong spot. Still hoping for an answer to the question: What JSON file is involved here? Is the error message message misrepresenting the YAML file as JSON? YAML and JSON are different data formats, so what JSON file is involved here? (There are non in my config directory.)

Here's another kicker:

The docker.yaml *IS* being read and used. My services.yaml is configured to display system stats from a glances container and homepage shows the info correctly with the docker container info. See below:

```
    - CPU Usage:
        icon: glances.png
        href: https://glances.domain.tld
        siteMonitor: https://glances.domain.tld
        server: my-docker
        container: glances
        widget:
          type: glances
          url: https://glances.domain.tld
          version: 4
          metric: cpu
```

![image](https://github.com/user-attachments/assets/b53c2d83-e171-4a89-b8c6-8d5b21e9c3b6)

I haven't had time to get back to this until now. I know it's not a simple or usual issue and that's exactly why it's worth diagnosing until conclusion. Possibly there's a bug in the error reporting or it specific error message could be massaged to give more pertinent info. :-)

What else can the error
`[2024-08-31T20:25:10.997Z] error: SyntaxError: Unexpected token [ in JSON at position 1`
reference other than a docker.yaml problem?
