### DISCUSSION TITLE
Pihole Widget API Error

### DISCUSSION THREAD

**Discussion by lablankspace** [gethomepage/homepage#3870] [Support]
### Description

I tried to setup the pihole widget but I cant seem to get it to work.  

Visiting https://pihole.domainname.com/admin/api.php?summaryRaw&auth=abc123 gives a valid reply and all my stats like it should but on homepage I get the 
`API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### homepage version

v0.8.13

### Installation method

Docker

### Configuration

```yaml
- PiHole:
   href: https://pihole.domainname.com/admin
   description: Pihole DNS
   icon: pi-hole.png
   widget:
      type: pihole
      url: https://pihole.domainname.com
      version: 6
      key: abc123
```
```


### Container Logs

_No response_

### Browser Logs

`API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### Troubleshooting

From docker cli I can ping pihole and curl the JSON data so I don't know whats wrong exactly
