### DISCUSSION TITLE
[Feature Request] Clickable `siteMonitor` component

### DISCUSSION THREAD

**Discussion by krin-san** [gethomepage/homepage#3871] [Feature Requests]
### Description

When most of the self-hosted apps are available via a reverse proxy it could be quite handy to have both HTTPS and HTTP links available on the Homepage. As far as I know `href` cannot contain more than 1 link and I don't see a way how to make it apparent in the UI either, whereas `siteMonitor` component could be used exactly for that.

In the following config example a Gitea service is available via https link in `href` and monitored via http link in `siteMonitor`:
```yaml
  - Gitea:
      href: https://git.domain.example
      siteMonitor: http://1.2.3.4:21345
```

I suggest adding an option – both global and per-service – to allow wrapping `siteMonitor` component into `<a>` tag making it clickable and open a `siteMonitor` link.
