### DISCUSSION TITLE
Possible bug: Calibre-Web widget

### DISCUSSION THREAD

**Discussion by logicelf** [gethomepage/homepage#3874] [Support] [answered]
### Description

Firstly, thanks for your work - Homepage is superb. I have 11 widgets, and 10 of them are working flawlessly.

The Calibre-Web widget, however, is returning the following API error:

`API Error: Unexpected token 'I', "Internal S"... is not valid JSON`

### homepage version

v0.9.6 (805f119)

### Installation method

Docker

### Configuration

```yaml
- Calibre-Web:
        icon: calibre-web.png
        href: http://10.0.4.200:8083
        description: Books
        server: my-docker
        container: calibre-web
        widget:
          type: calibreweb
          username: admin
          password: (redacted)
```

### Container Logs

(no errors)

### Browser Logs

(no errors)

### Troubleshooting

I checked that widget's source for the relevant endpoint, and then connected from the host machine.

`curl -L -k -u admin http://10.0.4.200:8083/opds/stats` appears to return valid JSON when authenticated with the configured password:

`{"books": 1, "authors": 1, "categories": 0, "series": 0}`

On the face of it, nothing looks wrong with my config or the endpoint.

Grateful for any assistance!
