### DISCUSSION TITLE
CustomAPI with Proxmox

### DISCUSSION THREAD

**Discussion by tehniemer** [gethomepage/homepage#3875] [Support] [answered]
### Description

I'm met with an HTTP error trying to pull information from a Proxmox instance using the customapi widget. 
![image](https://github.com/user-attachments/assets/df1b9c93-0a56-4bb2-848f-4c4693f299d9)

I've tried just about everything I can think of to get this to work, which it apparently does as shown in https://github.com/gethomepage/homepage/discussions/473#discussioncomment-9551948

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

```yaml
- Proxmox Node 1:
    - PVE01:
        icon: proxmox
        href: https://pve01.{{HOMEPAGE_VAR_DOMAINNAME}}
        siteMonitor: https://phpve01.home:8006
        disableCollapse: true
        widget:
          id: pve01_widget
          type: customapi
          url: https://phpve01.home:8006/api2/json/nodes/phpve01/status/
          display: list
          method: GET
          headers:
            Authorization: PVEAPIToken={{HOMEPAGE_VAR_PVE_API_ID}}={{HOMEPAGE_VAR_PVE01_API_SECRET}}
          mappings:
            - field:
                data: uptime
              label: Uptime
              scale: 1/3600
              format: number
              suffix: hours
              id: pve01_uptime
            - field:
                data:
                  loadavg: 0
              label: Load
              id: proxmox_load
              additionalField:
                field:
                  data:
                    loadavg: 1
            - field:
                data: cpu
              format: percent
              scale: 100
              label: CPU
              id: pve01_CPU
            - field:
                data:
                  memory: total
              format: bytes
              label: Mem total
              id: pve01_memtotal
            - field:
                data:
                  memory: free
              format: bytes
              label: Mem free
              id: pve01_memfree
            - field:
                data:
                  memory: used
              format: bytes
              label: Mem used
              id: pve01_memused
            - field:
                data:
                  rootfs: total
              format: bytes
              label: Rootfs total
              id: pve01_rootfstotal
            - field:
                data:
                  rootfs: free
              format: bytes
              label: Rootfs free
              id: pve01_rootfsfree
            - field:
                data:
                  rootfs: used
              format: bytes
              label: Rootfs used
              id: pve01_rootfsused
```

### Browser Logs

![image](https://github.com/user-attachments/assets/505bd7af-f40c-4c61-a04e-f16874639b06)
![image](https://github.com/user-attachments/assets/9e699368-ca31-4939-b6b3-14196a958693)

### Troubleshooting

`curl -k -X GET -H 'Authorization: PVEAPIToken=<ID>=<SECRET>' https://phpve01.home:8006/api2/json/nodes/phpve01/status/` from the docker host I'm returned usable data as shown below

```
{"data":{"wait":0.106289105033748,"pveversion":"pve-manager/8.2.4/faa83925c9641325","cpuinfo":{"cpus":12,"hvm":"1","flags":"f
pu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscal
l nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmul
qdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_t
imer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpr
iority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt 
xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp vnmi md_clear flush_l1d arch_capabilities
","mhz":"4400.013","user_hz":100,"cores":6,"model":"Intel(R) Xeon(R) W-1250 CPU @ 3.30GHz","sockets":1},"cpu":0.1532750829967
4,"current-kernel":{"version":"#1 SMP PREEMPT_DYNAMIC PMX 6.8.8-4 (2024-07-26T11:15Z)","sysname":"Linux","release":"6.8.8-4-p
ve","machine":"x86_64"},"ksm":{"shared":2383872},"loadavg":["22.73","30.58","19.56"],"uptime":1442918,"kversion":"Linux 6.8.8
-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.8-4 (2024-07-26T11:15Z)","swap":{"total":8589930496,"used":2621440,"free":8587309056},"
boot-info":{"mode":"efi","secureboot":0},"idle":0,"rootfs":{"avail":19062923264,"free":20526198784,"used":12707123200,"total"
:33233321984},"memory":{"total":67227140096,"used":52594610176,"free":14632529920}}}
```
