### DISCUSSION TITLE
Override common.json values in widgets.yaml for increased search widget clarity

### DISCUSSION THREAD

**Discussion by chrisweeksnz** [gethomepage/homepage#3878] [Support]
### Description

I would like to override the value of `.search.placeholder` in `public/locales/en/common.json`, preferably using a configuration variable in each instance of a search widget in `widgets.yaml`. This would allow me to define multiple custom search widgets and be able to differentiate between them easily.

eg. 
Instead of all search widgets displaying `Search...`, each widget could have descriptive text like `Search Document Management...` or `Search Gitlab...`.

Only the original author can tell immediately what multiple search widgets do:
![Screenshot 2024-08-20 at 21 19 52](https://github.com/user-attachments/assets/61718e0e-2148-4f8f-8645-1aec17e670d0)

The purpose of this discussion is to learn to configure the service, so that each box's query box helped differentiate and identify the backend search service.

### homepage version

v0.9.6 (805f119, Aug 12, 2024)

### Installation method

Docker

### Configuration

```yaml
# This is example config from widgets.yaml
# It contains `placeholder`, a key that doesn't seem to exist, 
# but would be awesome if something similar could be used to 
# achieve the desired result.

- search:
    provider: custom
    placeholder: Search Github Enterprise...
    url: https://my.enterprise.github.server/search?q=
    target: _blank
    showSearchSuggestions: false

- search:
    provider: custom
    placeholder: Search some.repo ...
    url: https://my.enterprise.github.server/my.group/some.repo/search?q=
    target: _blank
    showSearchSuggestions: false
```

### Troubleshooting

n/a - my homepage appears to be running correctly... I'm hoping to find out if a feature already exists that I haven't been able to identify or find a new feature request to submit.  :)
