### DISCUSSION TITLE
Glances service widget wrong fs metric value

### DISCUSSION THREAD

**Discussion by sy6sy2** [gethomepage/homepage#3880] [Support] [answered]
### Description

Using the glances widget with fs metric on my ZFS mount point show wrong usage in homepage while Glances CLI  and `df`values are correct.

`df` stdout:

```
Filesystem                1K-blocks            Used               Available        Use%   Mounted on
two_tera/nas             1885809408     1515519872   370289536.   81%     /two_tera/nas
```

`glances --stdout fs` stdout:

```
{
'device_name': 'two_tera/nas',
'fs_type': 'zfs',
'mnt_point': '/two_tera/nas',
'size': 1931068833792,
'used': 1551892348928,
'free': 379176484864,
'percent': 80.4,
'key': 'mnt_point'
}
```

`homepage` result:

![Capture d’écran 2024-08-20 à 14 55 16](https://github.com/user-attachments/assets/ff3d570f-e8b9-401e-b316-b01abb6234a8)

services.yaml:

```
- NAS storage:
    - Two terra (2 disks mirror):
        widget:
            type: glances
            url: http://XXXXXXXXX.fr
            version: 4
            metric: fs:/two_tera/nas
            chart: false
```

Thanks!

### homepage version

v0.9.6 (805f119, Aug 11, 2024)

### Installation method

Docker

### Configuration

```yaml
- NAS storage:
    - Two terra (2 disks mirror):
        widget:
            type: glances
            url: http://XXXXXXXXX.fr
            version: 4
            metric: fs:/two_tera/nas
            chart: false
```

### Container Logs

Nothing

### Browser Logs

Nothing

### Troubleshooting

Nothing
