### DISCUSSION TITLE
API Error (no details) when enabling showStats on Docker Swarm containers

### DISCUSSION THREAD

**Discussion by jamesfreeman959** [gethomepage/homepage#3883] [Support] [answered]
### Description

I've set up Homepage for the first time today, and so far so good except for one thing.

I'm running on Docker Swarm, and have enabled Show Stats for my containers. However I'm getting an API Error for each and every container I enable it on. I've tried enabling it on a container basis via a label, and via `settings.yaml` globally.

When I click on the API Error, a grey box appears below which I presume is supposed to show the details of the error, but it's blank. I've tried setting the `LOG_LEVEL` environment variable in my Docker service definition for homepage to `debug`, but I'm not seeing any errors (or useful info) in the service log.

I presume at this state this is an error on my part - either expecting something to work that doesn't, or not configuring it correctly. Can anyone advise please?

### homepage version

v0.9.6 (805f119)

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_public
    environment:
      - LOG_LEVEL=debug
    deploy:
      labels:
        # traefik
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"

        # traefikv2
        - "traefik.http.routers.homepage.rule=Host(`homepage.example.com`)"
        - "traefik.http.routers.homepage.entrypoints=https"
        - "traefik.http.routers.homepage.middlewares=authelia"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      placement:
        constraints:
          - node.role == manager
```

### Container Logs

Nothing beyond:
```
homepage_homepage.1.oapsp36m51bz@docknode01.sar.hkskies.com    | Listening on port 3000
```

### Troubleshooting

Have tried enabling on a per-container and global level but the result is the same.
