### DISCUSSION TITLE
Automatic discovery of custom API

### DISCUSSION THREAD

**Discussion by shreead** [gethomepage/homepage#3902] [Support]
### Description

Can I have automatic discovery of custom API? 
For example I have a PeaNUT docker container:
```
services:
  peanut:
    image: brandawg93/peanut
    container_name: peanut
    ports:
      - 8680:8080
    environment:
      - NUT_HOST=10.10.0.4
      - NUT_PORT=3493
      - WEB_PORT=8080
    restart: unless-stopped
```
My service.yml has a custom API that pulls data from the above container:
```
---
- INFRASTRUCTURE:
    - Power:
        href: http://10.10.0.4:8680
        icon: mdi-battery-high
        server: server-prod01-docker
        container: peanut
        showStats: false
        widget:
          type: customapi
          url: http://10.10.0.4:8680/api/v1/devices/ups
          refreshInterval: 10000
          method: GET
          headers:
          mappings:
            - field: battery.charge
              label: Charge
              format: percent
            - field: ups.load
              label: Load
              format: number
              scale: 6
              suffix: W
            - field: battery.runtime
              format: number
              scale: 1/60
              suffix: min
              label: Runtime
            - field: ups.status
              label: Status
              format: text
              remap:
              - value: "OL"
                to: Online
              - value: "OL CHRG"
                to: Charging
              - any: true # will map all other values
                to: Unknown
```
Can I convert the above custom api widget to docker label so that it can be included in peanut's docker compose file?

### homepage version

v0.9.6

### Installation method

Docker

### Troubleshooting

--
