### DISCUSSION TITLE
Russian translation bug

### DISCUSSION THREAD

**Discussion by serenitatis** [gethomepage/homepage#3907] [Support] [answered]
### Description

Homepage with russian translation have issue with resources widget panel. Widgets reading stick with widgets postfix (free, temperature etc).

![2024-08-29_17-22-40](https://github.com/user-attachments/assets/cc0ddb97-9532-47fc-9d4d-f1a8e43d0520)

I find [similar bug](https://github.com/gethomepage/homepage/issues/1110) with Czech translation and seems fix is not enough. I add `padding-left: .25rem` to .pr-1 class via browser developer tool and now it's look more acceptable. This just a proof of possible fix this issue with some css.

![2024-08-29_17-37-13](https://github.com/user-attachments/assets/5db6f1be-27da-40f9-959f-b625070bbcdf)

### homepage version

v0.9.6 (805f119)

### Installation method

Docker

### Configuration

```yaml
- resources:
    label: Система
    cpu: true
    memory: true
    cputemp: true
    uptime: true

- resources:
    label: Disk-1
    disk: /mnt/Disk-1
    
- resources:
    label: Disk-2
    disk: /mnt/Disk-2
    
- resources:
    label: Disk-3
    disk: /mnt/Disk-3
    
- resources:
    label: /
    disk: /
```

### Troubleshooting

No
