### DISCUSSION TITLE
Frigate Widget: Missing Widget Type

### DISCUSSION THREAD

**Discussion by virtualJonesie** [gethomepage/homepage#3908] [Support] [answered]
### Description

Trying to use the Frigate Widget, I get the following error: Missing Wodget Type: frigate

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- Frigate:
        description: Frigate Network Video Recorder (NVR)
        icon: frigate
        href: http://[IP_ADDRESS]:5000/
        siteMonitor: http://[IP_ADDRESS]:5000/
        widget:
          type: frigate
          url: http://[IP_ADDRESS]:5000/
```

### Container Logs

I don't see any mention of frigate in the container logs.

### Troubleshooting

I have copy/pasted the example configuration from the website and updated the values to match my environment.
