### DISCUSSION TITLE
Opt-out from copying demo configs?

### DISCUSSION THREAD

**Discussion by polarathene** [gethomepage/homepage#3909] [Support]
### Description

Tried searching issues/discussions, not the easiest thing to search for 😓 I didn't find anything in the docs about this either (_I don't think it mentions default configs being created implicitly for you either_).

If you do not want to have `widgets.yaml` / `settings.yaml` / `services.yaml` configs, there is no opt-out (like via ENV) to prevent copying the example configs. I assume the answer is to create empty config files, but beyond demo purposes like when first trying homepage out I really don't understand the point of this feature to not have a proper opt-out?

If the config directory was empty while starting homepage, sure throw in the examples. If an existing config exists then it really should be an opt-in feature to force config copying like that, which makes much more sense than opt-out or creating dummy files to prevent it?

Alternatively `settings.yaml` could offer per config file opt-out. I've seen there are ENV to control config file and dir locations. I can't seem to find any docs on the site about opt-out though?

---

Support category as I would be a bit surprised if this needs to be a feature request. I would assume I'm mistaken and that this can be configured somewhere, but briefly browsing the source code suggests I will need dummy files.

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

Very simple config for Homepage and a reverse proxy (Caddy), all config in single `compose.yaml`:

```yaml
services:
  reverse-proxy:
    image: lucaslorentz/caddy-docker-proxy:2.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"

  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: homepage-docker
        target: /app/config/docker.yaml
    labels:
      caddy: localhost
      caddy.reverse_proxy: "{{upstreams 3000}}"

  whoami:
    image: traefik/whoami
    labels:
      caddy: hello-world.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
      homepage.href: https://hello-world.localhost
      homepage.name: Hello World
      homepage.description: Basic example with Caddy
      homepage.icon: caddy
      homepage.group: Example

configs:
  homepage:
    content: |
      my-docker:
        socket: /var/run/docker.sock
```

### Container Logs

```
homepage-1       | [2024-08-30T04:02:42.816Z] info: settings.yaml was copied to the config folder
homepage-1       | [2024-08-30T04:02:42.816Z] info: services.yaml was copied to the config folder
homepage-1       | [2024-08-30T04:02:42.818Z] info: bookmarks.yaml was copied to the config folder
homepage-1       | [2024-08-30T04:02:42.825Z] info: widgets.yaml was copied to the config folder
homepage-1       | [2024-08-30T04:02:42.825Z] info: custom.css was copied to the config folder
homepage-1       | [2024-08-30T04:02:42.826Z] info: custom.js was copied to the config folder
homepage-1       | [2024-08-30T04:02:43.181Z] info: kubernetes.yaml was copied to the config folder
```

### Troubleshooting

N/A

**Comment by polarathene** [comment]
In the meantime, workaround with empty dummy files works:

```yaml
services:
  homepage:
    configs:
      - source: empty
        target: /app/config/settings.yaml
      - source: empty
        target: /app/config/services.yaml
      - source: empty
        target: /app/config/widgets.yaml
      - source: empty
        target: /app/config/bookmarks.yaml

configs:
  homepage:
    content: |
      # Nothing to see here
```
