### DISCUSSION TITLE
[Feature Request]  Collapsible Options for Radarr and Sonarr Queues

### DISCUSSION THREAD

**Discussion by collinlucke** [gethomepage/homepage#3917] [Feature Requests]
### Description

Currently, when you have `enableQueue: true` on either a Radarr or Sonarr service widget it gives you the complete queue. If you have a lot in your queue it pushes everything down and is not a good experience. What I propose is to add a `collapsible` attribute that could hide and show the full list. Additionally, I would like to add a `compactQueue` attribute that would show the queue in a scrollable container.

I'm new to the Homepage world (both as a user and a developer) and kinda went ahead and built the thing with out realizing the process. So here's a little demo for the masses (sorry for the quality):

https://github.com/user-attachments/assets/c14ba9b2-44c0-4112-90ad-c451b7c501f6

`services.yaml`
![homepage services yaml](https://github.com/user-attachments/assets/4f1eee44-910b-4c38-b236-f879c21ef1f5)

The code probably needs more love before it's ready for prime time - https://github.com/crazy-overlord/homepage/tree/feature-collapsible-arr-queues

Looking forward to any and all suggestions!

Edit: Added `services.yaml` image.
Edit 2: Added URL to branch

**Comment by nado** [comment]
I’d love to see this added.
Another way of reducing the queue I imagined was to add a limit possibility as well as ordering by ETA or % progress (descending only?)

```yaml
- Series:
      icon: sonarr
      widget:
        type: sonarr
        url: http://sonarr:8989
        enableQueue: true
        queueLimit: 0-MAX # 0 would disable the limit like the current behaviour
        queueSort: ETA | progress
```
