### DISCUSSION TITLE
Using customapi with a simple server I created to periodically run httping

### DISCUSSION THREAD

**Discussion by jmbooth2000** [gethomepage/homepage#3920] [Support] [answered]
### Description

I'm hoping someone will be able to help me. I created a simple server that runs httping against a specified url on a periodic basis. The key feature is because it uses httping you can specify a proxy using -x <proxy ip>:<proxy port> which means it will work with proxies unlike site monitor.

The httping_server is working and returns the following JASN {"ping time":"0.82 ms","time":"2024-08-31 09:15:52","url":"http://cnn.com"} when I open "http://192.168.1.3:5000/httping".

If I use the iframe widget it displays {"ping time":"0.36 ms","time":"2024-08-31 09:54:32","url":"http://cnn.com"} as expected but I'd like to use the customapi as the interface is much neater. 

My current configuration is included below.

This displays the widget but the values don't populate. What am I doing wrong? I'm not sure whether the issue is in the JASN format the httping server is generating or in my customapi configuration.

Thanks in advance for any help
Jonathan

### homepage version

v0.9.6 (805f119, Aug 11, 2024)

### Installation method

Docker

### Configuration

```yaml
- httping:
        href: http://192.168.1.3:5000/httping
        container: httping-server-custom-httping-server-custom-1
        showStats: true
        widget:
          type: customapi
          url: http://192.168.1.3:5000/httping
          refreshInterval: 10000
          mappings:
            - field: ping time
              label: ping time
              format: text
            - field: time
              label: time
              format: text
            - field: url
              label: url
              format: text
```

### Container Logs

N/A no entries for the date

### Troubleshooting

The iframe widget can successfully access the endpoint which confirms it is accessible.
