### DISCUSSION TITLE
The Jellyfin widget fail to show messages during one video playing (in Jellyfin)

### DISCUSSION THREAD

**Discussion by ShqWW** [gethomepage/homepage#3921] [Support]
### Description

The Jellyfin widget fail to show messages during one video playing (in Jellyfin), as below:
![image](https://github.com/user-attachments/assets/f20497fd-897d-4cc2-9a96-b25006913994)
when no media playing or one music playing, the message  are shown normally.
![image](https://github.com/user-attachments/assets/480dce19-13ba-44c9-a540-5ee48070bcf2)
![image](https://github.com/user-attachments/assets/9bc7974c-5ef9-426c-9cc8-08a6338452ee)

The api url [{url}/emby/{endpoint}?api_key={key}] can be access  by browser normally  during media (both video and music) playing.
The jellyfin and the homepage are run in the docker and both of them are of the lastest version.
So is it a bug for homepage or jellyfin?

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

```yaml
widget:
            type: jellyfin
            url: http://host.docker.internal:4003
            key: 1db9388cc0dc4e8c99683560698419d5
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: false # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
            version: 10
```

### Troubleshooting

omething went wrong.
TypeError: Cannot read properties of undefined (reading 'toString')

    at p (http://haoru.xyz/_next/static/chunks/6774.f5576f13708319a8.js:1:3929)
    at div
    at b (http://haoru.xyz/_next/static/chunks/6774.f5576f13708319a8.js:1:6480)
    at h (http://haoru.xyz/_next/static/chunks/3657-fc23499a89c4283f.js:1:34752)
    at n (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:17139)
    at R (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:33195)
    at div
    at li
    at M (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:37089)
    at ul
    at J (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:41152)
    at div
    at http://haoru.xyz/_next/static/chunks/3657-fc23499a89c4283f.js:1:78656
    at div
    at l (http://haoru.xyz/_next/static/chunks/3657-fc23499a89c4283f.js:1:107412)
    at http://haoru.xyz/_next/static/chunks/3657-fc23499a89c4283f.js:1:96815
    at http://haoru.xyz/_next/static/chunks/3657-fc23499a89c4283f.js:1:95583
    at l (http://haoru.xyz/_next/static/chunks/3657-fc23499a89c4283f.js:1:107412)
    at http://haoru.xyz/_next/static/chunks/3657-fc23499a89c4283f.js:1:76595
    at div
    at $ (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:41652)
    at div
    at div
    at ge (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:62228)
    at n (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:17139)
    at http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:90763
    at ve (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:60236)
    at div
    at div
    at div
    at we (http://haoru.xyz/_next/static/chunks/pages/index-96af4528503a8c52.js:1:69274)
    at a (http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:16139)
    at a (http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:15783)
    at s (http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:16697)
    at u (http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:15211)
    at http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:90763
    at http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:14462
    at l (http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:1250)
    at n (http://haoru.xyz/_next/static/chunks/pages/_app-3e4048443217bd77.js:1:5714)
    at r (http://haoru.xyz/_next/static/chunks/main-6c70321fa035d8ca.js:1:6991)
    at Y (http://haoru.xyz/_next/static/chunks/main-6c70321fa035d8ca.js:1:9236)
    at ie (http://haoru.xyz/_next/static/chunks/main-6c70321fa035d8ca.js:1:11878)
