### DISCUSSION TITLE
Pi-Hole API Error

### DISCUSSION THREAD

**Discussion by Willplayz112** [gethomepage/homepage#3923] [Support] [answered]
### Description

Hello when setting up pihole docker intergration with services.yaml with the following yaml config 

`
        widget:
          type: pihole
          url: http://192.168.1.148:80/admin
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
`
I get the following error

"API Error: Unexpected token '<', "<?xml vers"... is not valid JSON" 

I feel like I am doing something wrong myself but I don't know to be honest

(if you need any other info about the config I can grab it)

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

```yaml
- Pi-Hole:
        href: http://"RaspberryPiIP":80/admin
        description: Network Wide Adblocker
        widget:
          type: pihole
          url: http://"RaspberryPiIP":80/admin
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
```

### Troubleshooting

I have done a bit but not it weren't helpful
