### DISCUSSION TITLE
Portainer API with Homepage

### DISCUSSION THREAD

**Discussion by Willplayz112** [gethomepage/homepage#3932] [Support] [answered]
### Description

When I tried setting up API access to Portainer via Homepage I got this error

`API Error: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)`

I have looked at the entire services.yaml file and didn't find anything about a non-whitespace character 

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

```yaml
- Portainer:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
        href: https://192.168.1.148:9443/
        description: Manage Docker Containers
        widget:
          type: portainer
          url: https://192.168.1.148:9443
          key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
```

### Container Logs

[2024-09-01T23:12:48.433Z] debug: No containers were found with homepage labels.
[2024-09-01T23:12:48.502Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1
[2024-09-01T23:12:53.642Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1
[2024-09-01T23:13:14.127Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1
[2024-09-01T23:13:53.341Z] debug: No containers were found with homepage labels.
[2024-09-01T23:13:53.422Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1
[2024-09-01T23:13:59.117Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1
[2024-09-01T23:14:02.468Z] debug: No containers were found with homepage labels.
[2024-09-01T23:14:02.536Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1
[2024-09-01T23:14:13.115Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1
[2024-09-01T23:14:48.915Z] debug: No containers were found with homepage labels.
[2024-09-01T23:14:48.929Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.1.148:9443/api/endpoints//docker/containers/json?all=1

### Browser Logs

just gives me a 404 not found error

### Troubleshooting

There is no trailing / at the URL: tag

I can ping portainer from the homepage container

I couldn't get the curl command to run I just gave this 

docker exec homepage curl -L -k -H 'X-Api-Key'REDACTED' 'https://PORTAINERIPORHOST:PORT/api/endpoints/2/docker/containers/json'
>
>

and it would let me do anything
