### DISCUSSION TITLE
Grafana widget password can't be passed by environment variable

### DISCUSSION THREAD

**Discussion by zoechi** [gethomepage/homepage#3941] [Support]
### Description

I have a bunch of services with widgets that get their passwords and API tokens from `HOMEPAGE_VAR_XXX` environment variables, but I'm not able to make this work with the Grafana widget.

When I add the password directly into the config it works.

I think I checked everything a dozen times. The `EnvironmentFile` referred to by the systemd service contains the variable with the password and there is no typo.
Can anybody verify?

I run Homepage-Dashboard on

```
Linux smarthome 6.6.32-hardened1 #1-NixOS SMP PREEMPT_DYNAMIC Sat May 25 14:22:56 UTC 2024 x86_64 GNU/Linux
```

`mypassword` is not the actual password I'm using. 
The password only contains upper and lowercase characters and an underscore. No special characters or numbers.

### homepage version

0.9.6 

### Installation method

Other (please describe above)

### Configuration

```yaml
working config (`/etc/homepage-dashboard/services.yaml`)


- Network:
  - Grafana:
      description: Grafana dashboard for monitoring
      href: http://grafana.example.com:8082
      icon: https://grafana.com/img/fav32.png
      siteMonitor: http://grafana.example.com:8082
      widget:
        fields:
        - dashboards
        - datasources
        - totalalerts
        - alertstriggered
        password: mypassword
        type: grafana
        url: http://grafana.example.com:8082
        username: homepagedashboard
```

not working config

```yaml
- Network:
  - Grafana:
      description: Grafana dashboard for monitoring
      href: http://grafana.example.com:8082
      icon: https://grafana.com/img/fav32.png
      siteMonitor: http://grafana.example.com:8082
      widget:
        fields:
        - dashboards
        - datasources
        - totalalerts
        - alertstriggered
        password: '{{HOMEPAGE_VAR_GRAFANA_TOKEN}}'
        type: grafana
        url: http://grafana.example.com:8082
        username: homepagedashboard
```

/run/secrets-rendered/HomepageDashboard

```
HOMEPAGE_VAR_GRAFANA_TOKEN=mypassword
```

`systemctl cat homepage-dashboard`

```
❯ systemctl cat homepage-dashboard
# /etc/systemd/system/homepage-dashboard.service
[Unit]
After=network.target
Description=Homepage Dashboard

[Service]
Environment="HOMEPAGE_CACHE_DIR=/var/cache/homepage-dashboard"
Environment="HOMEPAGE_CONFIG_DIR=/etc/homepage-dashboard"
Environment="LOCALE_ARCHIVE=/nix/store/vk030mijyspl18ls2kz819wp8fabc7fs-glibc-locales-2.39-52/lib/locale/locale-archive"
Environment="LOG_TARGETS=stdout"
Environment="PATH=/nix/store/vb8mdklw65p9wikp97ybmnyay0xzipx3-coreutils-9.5/bin:/nix/store/9q88bb4afhqj863ka4l5pf92d2qb2225-findutils-4.10.0/bin:/nix/store/c4f952p7aml4izqphndgiy3rj7lq5aak-gnugrep-3.11/bin:/nix/store/jhn7xv6kwaydflia4n0hvqf18kjbki8x-gnused-4.9/bin:/nix/store/b11is5q9wgl4jjqs43x9qi22kljvpydj-systemd-256.4/bin:/nix/store/vb8mdklw65p9wikp97ybmnyay0xzipx3-coreutils-9.5/sbin:/nix/store/9q88bb4afhqj863ka4l5pf92d2qb2225-findutils-4.10.0/sbin:/nix/store/c4f952p7aml4izqphndgiy3rj7lq5aak-gnugrep-3.11/sbin:/nix/store/jhn7xv6kwaydflia4n0hvqf18kjbki8x-gnused-4.9/sbin:/nix/store/b11is5q9wgl4jjqs43x9qi22kljvpydj-systemd-256.4/sbin"
Environment="PORT=8083"
Environment="TZDIR=/nix/store/bkvxlipx80z1zbd33w3qvyvnhv0h0k2q-tzdata-2024a/share/zoneinfo"
CacheDirectory=homepage-dashboard
DynamicUser=true
EnvironmentFile=/run/secrets-rendered/HomepageDashboard
ExecStart=/nix/store/6m4k26r3xzwxl7awfabi2apr1xwy054q-homepage-dashboard-0.9.6/bin/homepage
Restart=on-failure
Type=simple

[Install]
WantedBy=multi-user.target
```
```


### Container Logs

`journalctl -xfeu homepage-dashboard`

```
Sep 03 19:52:45 smarthome homepage[973]: [2024-09-03T17:52:45.129Z] error: undefined
```

### Browser Logs

```
API Error: HTTP Error
URL: http://grafana.example.com:8082/api/admin/stats
```

### Troubleshooting

Shouldn't apply, because everything works when I add the password directly
