### DISCUSSION TITLE
[Stupid Question] When creating a service widget do you *have* to use `useWidgetAPI` to get data?

### DISCUSSION THREAD

**Discussion by collinlucke** [gethomepage/homepage#3946] [Support] [answered]
### Description

Trying to make a service widget for Planka and `useWidgetApi()` hates me.

In my `services.yaml` I've done this thing:
```
- Planka:
    - Planka:
        href: http://192.168.1.53:9999/
        description: What does this even do?
        widget:
          url: http://192.168.1.53:9999/
          type: planka
          emailOrUsername: ********* // Planka looks for this key
          password: ********
```

My `widget.js` appears as thus:
```
  api: "{url}api/{endpoint}",
  proxyHandler: credentialedProxyHandler,

  mappings: {
    "access-tokens": {
      method: "POST",
      endpoint: "access-tokens",
      // params: {
      //   emailOrUsername: "*********",
      //   password: "*********",
      // },
    },
    board: {
      method: "GET",
      endpoint: "boards/1327735207595344907",
    },
    users: {
      method: "GET",
      endpoint: "users",
    },
  },
};

export default widget;
```

And me `useWidgetAPI` in me`component.jsx` is like dis:
```
const { data, error } = useWidgetAPI(widget, "access-tokens");
```
The output from the above is `{error: 'Unsupported method'} 'Unsupported method'`

Quite frankly this would work great if I could just use fetch requests 😂 But I have a feeling that's frowned upon.

Thanks in advance! Just let me know if you need more/better information

### homepage version

v0.9.6

### Installation method

Source

### Troubleshooting

I've tried switching up the proxy handler, passing the `emailOrUsername/password` directly in `useWidgetAPI`, tried to pass in a Bearer to that I got from Postman, any kind of mix and match you could cincieve, and banging my mouse against my desk repeatedly.

Here's the routes for Planka and the one I'm trying to hit: [https://github.com/plankanban/planka/blob/master/server/config/routes.js](https://github.com/plankanban/planka/blob/master/server/config/routes.js#L14)

In Postman using 'POST' to this URL works a champ - `http://192.168.1.53:9999/api/access-tokens?emailOrUsername=****************&password=********`

And returns `{ "item": "###########################"}` which I can then use a bearer token for anything else I want to do in Postman
