### DISCUSSION TITLE
UDM Pro SE

### DISCUSSION THREAD

**Discussion by xsasx** [gethomepage/homepage#3949] [Support]
### Description

Cant get the widget working

Show long time nothing and after a while it brings me api error / most i got errno -110 which means connection timeout

Also tested different urls for the widget all found in issues

UniFi OS 4.0.6
Network 8.4.59

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

```yaml
- UniFi:
        icon: unifi.svg
        href: 192.168.1.1
        description: network
        widget:
            type: unifi
            url: https://192.168.1.1/proxy/network/api/stat/sites
            username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
            password:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
```

### Troubleshooting

-
