### DISCUSSION TITLE
Request for Assistance with Service Auto Discovery Configuration on k3d cluster

### DISCUSSION THREAD

**Discussion by RobertOlechowski** [gethomepage/homepage#3951] [Support]
### Description

Hello,

I am reaching out for assistance with configuring service auto discovery in my network setup.

Up until now, I have been successfully using a Homepage setup in my home network. It is hosted on one of my two machines and runs inside Docker. This setup automatically discovers both local services and Docker services on the remote host.

However, I have recently started experimenting with Kubernetes clusters and have encountered difficulties in running service auto discovery.

I am specifically looking for a working configuration example, as the dashboard is not included in this cluster.

Here's the configuration I used for creating the cluster:

```
k3d cluster create mycluster \
  --servers 1 \
  --agents 1 \
  -p "80:80@loadbalancer" \
  -p "443:443@loadbalancer"
```

I installed Nginx using Helm with the following configuration:
```
ingress:
  enabled: true
  hostname: "nginx.self.local"
  pathType: "Prefix"
  
extraHosts:
  - name: "nginx.local"
    path: /
```

Could anyone share a sample configuration or advice on how to set up service discovery on a remote Kubernetes cluster?

Thank you in advance for your assistance.

Best regards,

### homepage version

0.9.6

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: 1029
      PGID: 65536
    ports: [8091:3000]
    volumes:
      - ./homepage:/app/config
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`homepage.home.robertolechowski.com`)
      traefik.http.routers.homepage.tls.certresolver: myresolver
    networks: [docker_net]
     
networks:
  docker_net:
    external: true
```

### Troubleshooting

N/A
