### DISCUSSION TITLE
Service columns with less than four columns

### DISCUSSION THREAD

**Discussion by jgonzo-gh** [gethomepage/homepage#3957] [Support]
### Description

My settings file contains three groups of services for my main tab and three groups of bookmarks.  I hoped to have a row of columns containing my service groups and a row of my bookmark groups. Unfortunately, the settings.yaml code (in the confoguration block) below results in a dashboard where the first of my bookmark groups is located on the first row with my services.  Note: Entertainment is a bookmark group defined in my bookmarks.yaml file.
![main-tab-first](https://github.com/user-attachments/assets/ed925801-b53b-47b8-ae4c-19b10c888833)

I tried one experiment where I nested my service groups in a row.  The updated settings (also in the configuration block) had the desired affect for the row but the services now show on both my tabs, also note the tabs are not list in the same order, and the bookmarks precede the services on the main tab.  Hoping someone can point out my error.  If there is no error I will be happy to submit a bug report.
![main-tab-nested](https://github.com/user-attachments/assets/8be35731-d203-4371-baec-e95f6095ca4a)

My Homepage is running in a LXC container on my Proxmox server.  I used an install script located at https://tteck.github.io/Proxmox/ to build the container.

### homepage version

0.9.6

### Installation method

Other (please describe above)

### Configuration

```yaml
# Original settings.yaml
title: On My Network
theme: dark
color: slate
useEqualHeights: true
background: 
  image: /images/pacificdawn1_single_1920x1080.jpg
  blur: sm
  saturate: 50
  brightness: 60
  opacity: 60

layout:
# Main tab
## Main Servicea
  Network:
    tab: Main
  Servers:
    tab: Main
  Services:
    tab: Main

## Multimedia Services
  Media:
    tab: Multimedia
    style: row
    columns: 4

## Bookmarks
  Entertainment:
    tab: Main
  Social:
    tab: Main
  Tech:
    tab: Main

![main-tab-first](https://github.com/user-attachments/assets/ed925801-b53b-47b8-ae4c-19b10c888833)

I tried one experiment where I nested my service groups in a row.  The following settings had the desired affect for the row but the services showed up on both my tabs, that tabs went out of order, and the bookmarks preceded the services on the main tab.  Hoping someone can point out my error.  If there is no error I will be happy to submit a bug report.
```
title: On My Network
theme: dark
color: slate
useEqualHeights: true
background: 
  image: /images/pacificdawn1_single_1920x1080.jpg
  blur: sm
  saturate: 50
  brightness: 60
  opacity: 60

layout:
# Main tab
## Main Servicea
  mainTab:
    tab: Main
    style: row
    columns: 3
    groups:
      Network:
        tab: Main
      Servers:
        tab: Main
      Services:
        tab: Main

## Multimedia Services
  Media:
    tab: Multimedia
    style: row
    columns: 4

## Bookmarks
  Entertainment:
    tab: Main
  Social:
    tab: Main
  Tech:
    tab: Main

# Attempt at nesting services settings.yaml
title: On My Network
theme: dark
color: slate
useEqualHeights: true
background: 
  image: /images/pacificdawn1_single_1920x1080.jpg
  blur: sm
  saturate: 50
  brightness: 60
  opacity: 60

layout:
# Main tab
## Main Servicea
  mainTab:
    tab: Main
    style: row
    columns: 3
    groups:
      Network:
        tab: Main
      Servers:
        tab: Main
      Services:
        tab: Main

## Multimedia Services
  Media:
    tab: Multimedia
    style: row
    columns: 4

## Bookmarks
  Entertainment:
    tab: Main
  Social:
    tab: Main
  Tech:
    tab: Main
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

1. I attempted to nest the service groups into a row as explained above.
2. I restored my original configuration and removed all services and settings related to the second tab (Multimedia).  This still had the problem with the bookmark group being placed into the fourth column of the first row with the services.

**Comment by jgonzo-gh** [comment]
I messed up the formatting in the configuration block.  The first settings.yaml code block is accurate.  Here is the second code block where I attempted to nest columns of service groups within a row.
```
title: On My Network
theme: dark
color: slate
useEqualHeights: true
background: 
  image: /images/pacificdawn1_single_1920x1080.jpg
  blur: sm
  saturate: 50
  brightness: 60
  opacity: 60

layout:
# Main tab
## Main Servicea
  mainTab:
    tab: Main
    style: row
    columns: 3
    groups:
      Network:
        tab: Main
      Servers:
        tab: Main
      Services:
        tab: Main

## Multimedia Services
  Media:
    tab: Multimedia
    style: row
    columns: 4

## Bookmarks
  Entertainment:
    tab: Main
  Social:
    tab: Main
  Tech:
    tab: Main
```
