### DISCUSSION TITLE
Custom icon not displayed

### DISCUSSION THREAD

**Discussion by cmonty14** [gethomepage/homepage#3962] [Support]
### Description

I created a new service _Nexterm_, but the relevant icon is not displayed.

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

```yaml
- Nexterm:
        icon: /icons/nexterm.png
        href: http://docker-lve.devsys.net.sap:6989/
        description: Server management software for SSH, VNC & RDP
        siteMonitor: http://docker-lve.devsys.net.sap:6989/
```

### Troubleshooting

n/a

compose.yaml:
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 8080:3000
    env_file: .env # use .env
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      - ./images:/app/public/images
      #- /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID # read them from .env
      PGID: $PGID # read them from .env
networks: {}
```
