### DISCUSSION TITLE
NZBGet Widget stopped working on v0.9.7: Unexpected token 'I', "Internal S"... is not valid JSON

### DISCUSSION THREAD

**Discussion by slaughty101** [gethomepage/homepage#3968] [Support] [answered]
### Description

As the title goes, my NZBGet widget is showing an API error right after updating to the latest version.

`API Error: Unexpected token 'I', "Internal S"... is not valid JSON`

I presume it doesn't have to do anything with my setup, as it worked on v0.9.6 and also, I didn't change anything in any homepage yamls.

Any help would be great :smile: 

### homepage version

0.9.7

### Installation method

Docker

### Configuration

```yaml
- NZBGet:
        icon: nzbget.png
        description: Usenet Downloader
        siteMonitor: http://192.168.178.24:6789
        widget:
          type: nzbget
          url: http://192.168.178.24:6789
          username: myusername
          password: mypassword
          labels:
            - homepage.widget.fields=["rate", "remaining", "downloaded"]
```

### Troubleshooting

```
docker exec homepage ping 192.168.178.24:6789                                          
PING 192.168.178.24:6789 (192.168.178.24): 56 data bytes
64 bytes from 192.168.178.24: seq=0 ttl=64 time=0.065 ms
```
