### DISCUSSION TITLE
qBittorrent fails login

### DISCUSSION THREAD

**Discussion by sosuke3** [gethomepage/homepage#3978] [Support] [answered]
### Description

I get a login failed error with the qBittorrent widget. Login command works fine via curl on the host machine as well as inside the docker container for homepage. From looking around this seems to be a common problem but no one ever posts a solution. qbittorrent is running on a different machine than homepage.

### homepage version

v0.9.9

### Installation method

Docker

### Configuration

```yaml
- qBittorrent:
        icon: qbittorrent 
        href: https://qbittorrent.domain
        widget:
            type: qbittorrent
            url: http://qbittorrentip:8081
            user: admin
            password: 'secretepassword'
```

### Container Logs

```
homepage  | [2024-09-10T17:05:59.650Z] debug: <qbittorrentProxyHandler> qBittorrent is rejecting the request, logging in.
homepage  | [2024-09-10T17:05:59.898Z] error: <qbittorrentProxyHandler> Error logging in to qBittorrent: Data: Fails.

```

### Troubleshooting

after install curl inside the container and testing from it:

```
/app #  curl -i --request POST --data "username=admin" --data "password=secretepassword" --header 'Content-Type: application/x-www-form-urlencoded' --url  http://qbittorrentip:8081/api/v2/auth/login
HTTP/1.1 200 OK
connection: keep-alive
content-length: 3
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self';
content-type: text/plain; charset=UTF-8
cross-origin-opener-policy: same-origin
date: Tue, 10 Sep 2024 16:57:02 GMT
referrer-policy: same-origin
set-cookie: SID=***; HttpOnly; path=/
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

Ok.

```
