### DISCUSSION TITLE
Issue with Tautulli Widget Not Displaying Usernames on Homepage Dashboard

### DISCUSSION THREAD

**Discussion by ithinkmax** [gethomepage/homepage#3986] [Support] [answered]
### Description

I’m encountering an issue with the Tautulli widget in the “Homepage” dashboard. The usernames of users currently streaming are not being displayed, despite setting enableUser: true. Tautulli logs indicate that the usernames are visible, but the dashboard doesn’t reflect this. Below is the widget configuration I’m using.

### homepage version

v0.9.9 (6b1080a, 10 set 2024)

### Installation method

Docker

### Configuration

```yaml
- Tautulli:
       icon: tautulli.png
       ping: http://winbox.HIDDEN.it:8181
       href: http://winbox.HIDDEN.it:8181
       description: CineMAX Stato - winbox.HIDDEN.it:8181
       showStats: true 
       siteMonitor: http://winbox.HIDDEN.it:8181
       widget:
         type: tautulli
         url: http://192.168.1.242:8181
         key: 111db061605045ada3b6859bd5484c79
       enableUser: true # optional, defaults to false
       showEpisodeNumber: true # optional, defaults to false
       expandOneStreamToTwoRows: false # optional, defaults to true
```

### Troubleshooting

![CleanShot 2024-09-12 at 19 12 31@2x](https://github.com/user-attachments/assets/c01e31d1-9761-42f7-b426-f3432e64fa0e)
