### DISCUSSION TITLE
Pi-Hole (v6) widget fails when no api password is set

### DISCUSSION THREAD

**Discussion by felixpj2001** [gethomepage/homepage#3990] [Support] [answered]
### Description

I have no api password set in Pi-Hole, which causes the api to return no sid. However, the widget expects a non-null sid which causes it to fail.

### homepage version

v0.9.9

### Installation method

Docker

### Configuration

```yaml
widget:
        type: pihole
        url: http://pihole
        version: 6
        key: ""
```

### Container Logs

[2024-09-13T16:32:47.712Z] error: undefined

### Troubleshooting

```
curl -X POST --data '{"password":""}' -H 'Content-Type: application/json' http://pihole/api/auth
```
returns:
```json
{
        "session":      {
                "valid":        true,
                "totp": false,
                "sid":  null,
                "validity":     -1,
                "message":      "no password set"
        },
        "took": 6.36577606201172e-05
}
```
