### DISCUSSION TITLE
[Feature Request] Image field type

### DISCUSSION THREAD

**Discussion by ArthurMTX** [gethomepage/homepage#3998] [Feature Requests]
### Description

Hi!

I have developed a custom API service that tracks and displays the song I’m listening to on Spotify in real-time. As part of this functionality, I wanted to include the album cover alongside the song data. However, I encountered a limitation where the "image" type is not supported or does not work as expected for the fields.

**Request:** Can you please add support for the "image" type in the fields so that users can include visual elements, such as album covers in my case, or any other image-based data, in their API responses?

**Expected Behavior:**
- The API should properly handle image URLs or binary image data, allowing the display of the album cover in my case, and ensuring compatibility with other use cases involving images.

**Current Behavior:**
- The "image" field type is either unsupported or behaves unexpectedly.

Here is what I expect: 
![image](https://github.com/user-attachments/assets/89a1667f-9336-4ef7-9d20-a54cee75e4e3)

Here is the current state:
![image](https://github.com/user-attachments/assets/9013ffb5-75de-484c-a2b0-42c11c2d8044)

Here is my configuration: 
```yaml
- Spotify:
    icon: spotify
    widget:
      type: customapi
      url: <url>
      refreshInterval: 10000
      method: GET
      mappings:
        - field: title
          label: Song Name
          format: text
        - field: artist
          label: Artist Name
          format: text
        - field: album
          label: Album Name
          format: text
        - field: cover
          label: Album Cover
          format: image
```

Here is what my custom API returns:
```json
{
  "album": "Lost You but I Found Myself",
  "artist": "DJ COLENTINA",
  "cover": "https://i.scdn.co/image/ab67616d0000b27365b13113e30fabc8bb15db08",
  "title": "All I Do"
}
```

Thank you for considering this request!
