### DISCUSSION TITLE
Site Monitor extremely slow

### DISCUSSION THREAD

**Discussion by beyerleinf** [gethomepage/homepage#4003] [Support]
### Description

For about a week I'm having problems with the site monitor and service integrations being extremely slow.

Either using the public (reverse proxy) domain or through the internal docker network, it doesn't really make a difference. Using `docker exec` to go into the container, using ping or for example this snippet yields the expected latency. Homepage for some reasons displays latencies of multiple seconds. It's even worse when using the external address.

```
echo 'import("ping").then(r1 => r1.default.promise.probe("jellyfin").then(r2 => console.log(r2)))' | docker exec -i homepage node
```

![image](https://github.com/user-attachments/assets/2791e777-5d9c-4161-bf06-d845285493a9)

Any help would be greatly appreciated! 😊

### homepage version

v0.9.9

### Installation method

Docker

### Configuration

```yaml
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://<redacted>
        siteMonitor: http://jellyfin:8096/health
        server: arya
        container: jellyfin
        widget:
          type: jellyfin
          url: https://<redacted>
          key: {{ jellyfin_api_key }}
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false
```

### Troubleshooting

Result from above mentioned command

```
{
  inputHost: 'jellyfin',
  host: 'jellyfin',
  alive: true,
  output: 'PING jellyfin (172.19.0.6): 56 data bytes\n' +
    '64 bytes from 172.19.0.6: seq=0 ttl=64 time=0.118 ms\n' +
    '\n' +
    '--- jellyfin ping statistics ---\n' +
    '1 packets transmitted, 1 packets received, 0% packet loss\n' +
    'round-trip min/avg/max = 0.118/0.118/0.118 ms\n',
  time: 0.118,
  times: [ 0.118 ],
  min: 'unknown',
  max: 'unknown',
  avg: 'unknown',
  stddev: 'NaN',
  packetLoss: '0.000',
  numeric_host: '172.19.0.6)'
}
```
