### DISCUSSION TITLE
[Feature Request] Add kubernetes Service Discovery for Istio VirtualService

### DISCUSSION THREAD

**Discussion by emouawad** [gethomepage/homepage#4005] [Feature Requests]
### Description

homepage now support ingress & traefik IngressRoute, Istio is also still a major player. 
Example VirtualService:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: homepage
spec:
  gateways:
    - default/default-gateway
  hosts:
    - homepage.example.com
  http:
    - route:
        - destination:
            host: homepage
            port:
              number: 3000
```
