### DISCUSSION TITLE
Podman support

### DISCUSSION THREAD

**Discussion by alex27riva** [gethomepage/homepage#4013] [Support] [answered]
### Description

Hi,
does Homepage "Docker integration" feature also works on Podman?

### homepage version

v0.9.9

### Installation method

Other (please describe above)

### Configuration

```yaml
homepage: 
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    volumes:
      - ./config/homepage:/app/config:Z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
    restart: unless-stopped
```

### Container Logs

Listening on port 3000

### Troubleshooting

none
