### DISCUSSION TITLE
Kubernetes statistics are wrong due to "app:" label

### DISCUSSION THREAD

**Discussion by swooshant** [gethomepage/homepage#4014] [Support]
### Description

Using this example provided by homepage, I will explain what I found to not be working 

```
- Element Chat:
    icon: matrix-light.png
    href: https://chat.example.com
    description: Matrix Synapse Powered Chat
    app: matrix-element
    namespace: comms
    podSelector: >-
      app.kubernetes.io/instance in (
          matrix-element,
          matrix-media-repo,
          matrix-media-repo-postgresql,
          matrix-synapse
      )
```

The "app:matrix-element" is needed in order for this to work at all. I would assume if you omit that and only include `podSelector: ""` or `podSelector: "<content>"` it should automatically associate that with the pods in the namespace based on the podSelector. 

The `app: "app.kubernetes.io/name"` really throws things off since it's required. The cpu/memory metrics won't even pop up if you don't include  `app:`. When you do include `app:` it doesn't show things accurately because it seems to only match things with `app.kubernetes.io/name` first. When I manually check using `kubectl top` and compare it to the reported data by homepage, I've concluded that the `app: <app.kubernetes.io/name>` throws things off. In my opinion `app:app.kubernetes.io/name` should not be needed/effect anythinng if you're providing `namespace:` and `podSelector:`

### homepage version

v0.9.9

### Installation method

Docker

### Configuration

```yaml
homepage-cm.yaml

Here is a sample of my longhorn tile that doesn't report metrics correctly. I have many like that.

- Longhorn Storage [Cloud]:
          icon: longhorn.svg 
          href: {{HOMEPAGE_VAR_LONGHORN_CLOUD_URL}}
          description: Longhorn storage dashboard
          namespace: longhorn-system
          app: "longhorn"
          pod-selector: ""
```

### Troubleshooting

There isn't much I can provide but if you test it with common things that are more complex in nature having many different components with `app.kubernetes.io/name` you will see the issue. I have this issue with longhorn, cert-manager, prometheus-grafana, and more. Namespaces with deployments/statefulsets/daemonsets/etc where not all the pods share the same `app.kubernetes.io/name`.
