### DISCUSSION TITLE
Not Replacing Repeated Enviroment Variables

### DISCUSSION THREAD

**Discussion by snowy-jaguar** [gethomepage/homepage#4017] [Support]
### Description

I have a few enviroment variables which appear multiple times for one reason for another.
I've declared one `HOMEPAGE_VAR_` for each different thing and then refrenced them in multiple places.
For some reason some of these variables are not being replaced and I can't figure out why, although I'm assuming it might just not be written in a way to allow it.
The locations where the variables are placed worked fine when declared staically in the yml but stopped wokring after being added via enviroment variables

Edit: I should point out the PBS widget had issues before today's issue, so that can be ignored entirely.
Edits: Various Formatting issues needed fixing

![image](https://github.com/user-attachments/assets/389ec80b-1ac6-497d-b2da-c145dad5b188)

I have found #2735 which seems to be of a similar topic; however, my issue is more to do with the re-use of the same enviroment variable and not that enviroment varibles won't work at all becuase some definalty  do.

### homepage version

v0.9.9 (6b1080a, Sep 10, 2024)

### Installation method

Docker

### `docker-compose.yml` - Ran uisng Portainer
```yaml
version: "3"

volumes:
  homepage_data:
    external: true
    
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.9
    container_name: homepage
    restart: unless-stopped
    env_file: stack.env
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - homepage_data:/app/config # Make sure your local config directory exists
      - ${HOMEPAGE_VAR_DOCKER_SOCK}:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
```

### `(stack).env`
```env
HOMEPAGE_VAR_DOCKER_SOCK=/var/run/docker.sock
HOMEPAGE_VAR_DOCKER_PROXY_PORT=2375
HOMEPAGE_VAR_DOCKER_BIFROST=192.168.86.86
HOMEPAGE_VAR_DOCKER_UPTIME=192.168.86.87
HOMEPAGE_VAR_PORTAINER=192.168.86.237
HOMEPAGE_VAR_PORTAINER_PORT=9443
HOMEPAGE_VAR_PORTAINER_API_KEY=PORTAINERAPIKEYEHERE
HOMEPAGE_VAR_PORTAINER_ENV=2
HOMEPAGE_VAR_PORTAINER_ICON=portainer.png
HOMEPAGE_VAR_PROXMOXVE_CLUSTER=192.168.86.9
HOMEPAGE_VAR_PROXMOXVE_PORT=8006
HOMEPAGE_VAR_PROXMOXVE_SKULD=192.168.86.9
HOMEPAGE_VAR_PROXMOXVE_UROR=192.168.86.8
HOMEPAGE_VAR_PROXMOXVE_VEROANDI=192.168.86.7
HOMEPAGE_VAR_PROXMOXVE_DAGUR=192.168.86.5
HOMEPAGE_VAR_PROXMOXVE_API_USER=PVEAPIUSERHERE
HOMEPAGE_VAR_PROXMOXVE_API_KEY=PVEAPIKEYHERE
HOMEPAGE_VAR_PROXMOXVE_ICON=proxmox.png
HOMEPAGE_VAR_PROXMOXVE_TYPE=proxmox
HOMEPAGE_VAR_TRUENAS=192.168.86.6
HOMEPAGE_VAR_TRUENAS_KEY=TNAPIKEYHERE
HOMEPAGE_VAR_TRUENAS_ICON=truenas-scale.png
HOMEPAGE_VAR_TRUENAS_TYPE=truenas
HOMEPAGE_VAR_CEPH_PORT=8080
HOMEPAGE_VAR_PROXMOXBS=192.168.86.73
HOMEPAGE_VAR_PROXMOXBS_PORT=8007
HOMEPAGE_VAR_PROXMOXBS_API_USER=PBSAPIUSERHERE
HOMEPAGE_VAR_PROXMOXBS_API_KEY=PBSAPIKEYHERE
HOMEPAGE_VAR_PROXMOXBS_ICON=proxmox-light.png
HOMEPAGE_VAR_PROXMOXBS_TYPE=proxmoxbackupserver
```

### `services.yml`
```yml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Virtualizers:
    - Portainer:
        href: https://{{HOMEPAGE_VAR_PORTAINER}}:{{HOMEPAGE_VAR_PORTAINER_PORT}}
        description: Main Portainer Server
        icon: {{HOMEPAGE_VAR_PORTAINER_ICON}}
        server: docker-local
        container: portainer
        widget:
            type: portainer
            url: https://{{HOMEPAGE_VAR_PORTAINER}}:{{HOMEPAGE_VAR_PORTAINER_PORT}}
            env: {{HOMEPAGE_VAR_PORTAINER_ENV}}
            key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
    - Yggdrasil Cluster:
        href: https://{{HOMEPAGE_VAR_PROXMOXVE_CLUSTER}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
        description: Proxmox
        icon: {{HOMEPAGE_VAR_PROXMOXVE_ICON}}
        ping: {{HOMEPAGE_VAR_PROXMOXVE_CLUSTER}}
        widget:
            type: {{HOMEPAGE_VAR_PROXMOXVE_TYPE}}
            url: https://{{HOMEPAGE_VAR_PROXMOXVE_CLUSTER}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
            username: {{HOMEPAGE_VAR_PROXMOXVE_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
            #node:
    - Skuld:
        href: https://{{HOMEPAGE_VAR_PROXMOXVE_SKULD}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
        description: Node "Skuld" in Yggdrasil Cluster
        icon: {{HOMEPAGE_VAR_PROXMOXVE_ICON}}
        ping: {{HOMEPAGE_VAR_PROXMOXVE_SKULD}}
        widget:
            type: {{HOMEPAGE_VAR_PROXMOXVE_TYPE}}
            url: https://{{HOMEPAGE_VAR_PROXMOXVE_SKULD}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
            username: {{HOMEPAGE_VAR_PROXMOXVE_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
            node: skuld
    - Uror:
        href: https://{{HOMEPAGE_VAR_PROXMOXVE_UROR}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
        description: Node "Uror" in Yggdrasil Cluster
        icon: {{HOMEPAGE_VAR_PROXMOXVE_ICON}}
        ping: {{HOMEPAGE_VAR_PROXMOXVE_UROR}}
        widget:
            type: {{HOMEPAGE_VAR_PROXMOXVE_TYPE}}
            url: https://{{HOMEPAGE_VAR_PROXMOXVE_UROR}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
            username: {{HOMEPAGE_VAR_PROXMOXVE_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
            node: uror
    - Veroandi:
        href: https://{{HOMEPAGE_VAR_PROXMOXVE_VEROANDI}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
        description: Node "Veroandi" in Yggdrasil Cluster
        icon: {{HOMEPAGE_VAR_PROXMOXVE_ICON}}
        ping: {{HOMEPAGE_VAR_PROXMOXVE_VEROANDI}}
        widget:
            type: {{HOMEPAGE_VAR_PROXMOXVE_TYPE}}
            url: https://{{HOMEPAGE_VAR_PROXMOXVE_VEROANDI}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
            username: {{HOMEPAGE_VAR_PROXMOXVE_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
            node: veroandi
    - Dagur:
        href: https://{{HOMEPAGE_VAR_PROXMOXVE_DAGUR}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
        description: Node "Dagur" in Yggdrasil Cluster. This host runs the TrueNAS VM
        icon: {{HOMEPAGE_VAR_PROXMOXVE_ICON}}
        ping: {{HOMEPAGE_VAR_PROXMOXVE_DAGUR}}
        widget:
            type: {{HOMEPAGE_VAR_PROXMOXVE_TYPE}}
            url: https://{{HOMEPAGE_VAR_PROXMOXVE_DAGUR}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
            username: {{HOMEPAGE_VAR_PROXMOXVE_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
            node: dagur

- Storage:
    - TrueNAS:
        href: https://{{HOMEPAGE_VAR_TRUENAS}}
        description: Main TrueNAS Instance
        icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
        widget:
            type: {{HOMEPAGE_VAR_TRUENAS_TYPE}}
            url: https://{{HOMEPAGE_VAR_TRUENAS}}
            #username: user # not required if using api key
            #password: pass # not required if using api key
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}} # not required if using username / password
            enablePools: true # optional, defaults to false
            nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    - Ceph:
        href: http://{{HOMEPAGE_VAR_PROXMOXVE_CLUSTER}}:{{HOMEPAGE_VAR_CEPH_PORT}}/#/login
        description: Ceph dashboard for Yggdrasil Cluster
        icon: ceph.png

    - Proxmox Backup Server:
        href: https://{{HOMEPAGE_VAR_PROXMOXBS}}:{{HOMEPAGE_VAR_PROXMOXBS_PORT}}
        description: Main Proxmox Backup Server
        icon: {{HOMEPAGE_VAR_PROXMOXBS_ICON}}
        widget:
            type: {{HOMEPAGE_VAR_PROXMOXBS_TYPE}}
            url: https://{{HOMEPAGE_VAR_PROXMOXBS}}:{{HOMEPAGE_VAR_PROXMOXBS_PORT}}
            username: {{HOMEPAGE_VAR_PROXMOXBS_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOXBS_API_KEY}}
```
```


### Container Logs

Listening on port 3000
[2024-09-20T22:16:28.772Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://192.168.86.73:8007/api2/json/nodes/localhost/status
[2024-09-20T22:16:31.489Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.7:8006/api2/json/cluster/resources
[2024-09-20T22:16:31.528Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.9:8006/api2/json/cluster/resources
[2024-09-20T22:16:31.577Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.5:8006/api2/json/cluster/resources
[2024-09-20T22:16:31.632Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.9:8006/api2/json/cluster/resources
[2024-09-20T22:16:31.634Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.8:8006/api2/json/cluster/resources
[2024-09-20T22:16:39.518Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.7:8006/api2/json/cluster/resources
[2024-09-20T22:16:39.520Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://192.168.86.73:8007/api2/json/nodes/localhost/status
[2024-09-20T22:16:39.672Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.8:8006/api2/json/cluster/resources
[2024-09-20T22:16:44.555Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.9:8006/api2/json/cluster/resources
[2024-09-20T22:16:44.609Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.5:8006/api2/json/cluster/resources
[2024-09-20T22:16:44.660Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.86.9:8006/api2/json/cluster/resources

### Browser Logs

_No response_

### Troubleshooting

This is issue only started occuring after replacing static text declarations with enviroment variables and therefore I do not think it is related to the containers inability to access the target, My assumption is the api authentcation informtion just isn't being passed through correctly.

**Comment by shamoon** [comment]
Are you recreating (not just restarting) the container after changing the ENV?

**Reply by snowy-jaguar** [reply]
> Are you recreating (not just restarting) the container after changing the ENV?

I think I've been force stopping the container (`...compose down..` and `... compose up...`) but I'll those steps again and see what outcome I get.

**Reply by shamoon** [reply]
`down` and `up` should do it. Hmm, not aware of any issues here and I think lots of people who use this re-use variables (makes sense after all). Perhaps just some other issue with how you entered them etc

**Reply by snowy-jaguar** [reply]
> `down` and `up` should do it. Hmm, not aware of any issues here and I think lots of people who use this re-use variables (makes sense after all). Perhaps just some other issue with how you entered them etc

Just give `up` another go and same issue. What's weird is it's really only the ceph one that has issues being reused, my portainer one works fine. I'll check over how I've entered it.

**Reply by snowy-jaguar** [reply]
> > `down` and `up` should do it. Hmm, not aware of any issues here and I think lots of people who use this re-use variables (makes sense after all). Perhaps just some other issue with how you entered them etc
> 
> Just give `up` another go and same issue. What's weird is it's really only the ceph one that has issues being reused, my portainer one works fine. I'll check over how I've entered it.

Okay so I've not been able to visually notice any issues with my environment variables, both in the `.env` and the yml configuration files. I also connected to the containers shl and got all the environment variables it can see using `printenv`. From my initial look it seems like some (namely the proxmox api ones) are missing but I'm going to go through them with a fine comb line when I get some time in the next couple days.

**Reply by snowy-jaguar** [reply]
> > > `down` and `up` should do it. Hmm, not aware of any issues here and I think lots of people who use this re-use variables (makes sense after all). Perhaps just some other issue with how you entered them etc
> > 
> > 
> > Just give `up` another go and same issue. What's weird is it's really only the ceph one that has issues being reused, my portainer one works fine. I'll check over how I've entered it.
> 
> Okay so I've not been able to visually notice any issues with my environment variables, both in the `.env` and the yml configuration files. I also connected to the containers shl and got all the environment variables it can see using `printenv`. From my initial look it seems like some (namely the proxmox api ones) are missing but I'm going to go through them with a fine comb line when I get some time in the next couple days.

Okay I've been through and compared my static `.env` file against the output of `printenv` and they pretty much match, my `.env` has `31` variables in it and the containers has `41`, those addional `10` are cretaed by the container and make sense so none of mine are missing.

Now I'm going to go through and check them in my yml.
One thing I did think is that the follwowing representaion might not work, as it's the pve ones that are having the issues
```yml
- Yggdrasil Cluster:
    href: https://{{HOMEPAGE_VAR_PROXMOXVE_CLUSTER}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
    description: Proxmox
    icon: {{HOMEPAGE_VAR_PROXMOXVE_ICON}}
    ping: {{HOMEPAGE_VAR_PROXMOXVE_CLUSTER}}
    widget:
        type: {{HOMEPAGE_VAR_PROXMOXVE_TYPE}}
        url: https://{{HOMEPAGE_VAR_PROXMOXVE_CLUSTER}}:{{HOMEPAGE_VAR_PROXMOXVE_PORT}}
        username: {{HOMEPAGE_VAR_PROXMOXVE_API_USER}}
        password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
```
But the portainer one uses the same formatting and it appears to be working
```yml
- Portainer:
  href: https://{{HOMEPAGE_VAR_PORTAINER}}:{{HOMEPAGE_VAR_PORTAINER_PORT}}
  description: Main Portainer Server
  icon: {{HOMEPAGE_VAR_PORTAINER_ICON}}
  server: docker-local
  container: portainer
  widget:
      type: portainer
      url: https://{{HOMEPAGE_VAR_PORTAINER}}:{{HOMEPAGE_VAR_PORTAINER_PORT}}
      env: {{HOMEPAGE_VAR_PORTAINER_ENV}}
      key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
```
