### DISCUSSION TITLE
color palate

### DISCUSSION THREAD

**Discussion by h3xkore** [gethomepage/homepage#4023] [Support]
### Description

after creating the container for homepage using a docker-compose.yaml file for some reason it keeps the colors are redish pink for the palate. 

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
docker-compose.yaml
 services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/h3xkore/homepage/config:/app/config # Make sure your local config directory exists
      - /home/h3xkore/homepage/images:/app/public/images
      - /home/h3xkore/homepage/icons:/app/public/icons
    environment:
     - PUID=1000
     - PGID=1000
    restart: unless-stopped`
```

### Troubleshooting

i dont know how i would troubleshoot this tbh since changing colors doesnt seem to be in the settings i can change.
