### DISCUSSION TITLE
Timezone property in ical has no effect.

### DISCUSSION THREAD

**Discussion by BaqFish** [gethomepage/homepage#4029] [Support]
### Description

I have a calendar that includes sonarr and my own ical coming from Radicale. 

The service.yaml has this setup:

```
        widget:
          type: calendar
          firstDayInWeek: monday 
          view: monthly
          maxEvents: 10 
          timezone: Europe/Berlin
          showTime: true
          integrations
            - type: sonarr 
              service_group: Group1 
              service_name: Sonarr
              color: teal 
            - type: ical
              url: http://x.x.x.x:y/user/calendar.ical
              name: user
              color: blue
```

The ical file that is being added contains this information:
```
BEGIN:VEVENT
UID:5a19a891-857e-4ba6-9217-7dea9c49bd58
DTSTART;TZID=Europe/Berlin:20240919T180000
DTEND;TZID=Europe/Berlin:20240919T190000
DTSTAMP:20240920T122953Z
RRULE:FREQ=WEEKLY;WKST=MO
SUMMARY:Japanisch
END:VEVENT
```

So at 6 pm local time this event should appear every thursday. However within Homepage it is always listed as 8pm:
![image](https://github.com/user-attachments/assets/847d7670-4ab7-4311-9bc2-b520aa7a18f6)

Things I have checked/tried:
- The timezone property in widgets.yaml for openmeteo works without a problem.
- Set the variable TZ for the Docker Container to Europe/Berlin as well.
- Check the time in the homepage.log, which also doesn't display my TZ, even though the Docker Container should have changed. There is a two hour difference as well.

### homepage version

v0.9.9 (6b1080a, Sep 10, 2024)

### Installation method

Docker

### Troubleshooting

Listed tests don't seem relevant.
