### DISCUSSION TITLE
Glances service widget GPU metric doesn't appear to be working.

### DISCUSSION THREAD

**Discussion by mcmikemn** [gethomepage/homepage#4033] [Support] [answered]
### Description

Howdy. I have Glances installed on an Ubuntu server (as a docker container using the 'ubuntu-4.1.2.1-full` tag, and Docker is installed with GPU connectivity). When running `glances`, it shows the GPU info. When running ` nvidia-smi` is shows the GPU as ID 0 (zero). 

But I have the Glances service widget installed in Homepage and while other metrics work (e.g., network, memory, cpu, process, info), the "gpu" metric displays nothing, even when I've confirmed that the GPU is in use.
![image](https://github.com/user-attachments/assets/275fd76a-c902-488a-8cf3-1d43c4dd46b8)

Does anyone have the GPU metric in the Glances service widget working?

### homepage version

v0.9.9 (6b1080a)

### Installation method

Docker

### Configuration

```yaml
- server01:
    - CPU Usage:
        widget:
            type: glances
            version: 4
            url: http://192.168.x.x:61208
            metric: cpu
            refreshInterval: 5000
    - GPU:
        widget:
            type: glances
            version: 4
            url: http://192.168.x.x:61208
            metric: gpu:0
            refreshInterval: 5000
```

### Container Logs

NA (no errors, warnings, or info pertaining to glances)

### Browser Logs

The only thing in the console are these 2 warnings:
```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [markup.js:250:53](resource://devtools/server/actors/highlighters/utils/markup.js)
unreachable code after return statement
[main-0ddda9b10a00d3ad.js:1:21512](https://homepage.thewooskeys.com/_next/static/chunks/main-0ddda9b10a00d3ad.js)
```

### Troubleshooting

The service widget definitely communicates with Glances, as the non-GPU metrics are working. And the GPU is definitely working. And I can see the GPU info in Glances directly (when I run `glances` on the server itself). 

It's possible that the Glances API is not sharing GPU info, which would make this a Glances issue and not a Homepage (Glances service widget) issue. I'm not sure how to test that.
