### DISCUSSION TITLE
Missing Widget Type: stocks

### DISCUSSION THREAD

**Discussion by christrt9** [gethomepage/homepage#4035] [General]
I added in `services.yaml`  file to add widget stock but I get this message `Missing Widget Type: stocks`

Any ideas?

```
- Crypto & Stocks:
  - CoinMarketCap:
      description: crypto
      widget:
        type: coinmarketcap
        currency: USD
        symbols: [BTC, ETH, BNB, SOL, AVAX, DOT, ADA]
        key: xxxxx
        defaultinterval: 1h

  - Stocks:
      widget:
        type: stocks
        provider: finnhub
        showUSMarketStatus: true # optional, defaults to true
        watchlist:
          - GME
          - AMC
          - NVDA
          - TSM
          - TSLA
          - AAPL
          - MSFT
          - AMZN
```
