### DISCUSSION TITLE
Proton iCal as Calendar widget

### DISCUSSION THREAD

**Discussion by frogweh** [gethomepage/homepage#4038] [Support] [answered]
### Description

I was trying to get my Proton Calendar to work as the Calendar widget, to no avail. I'm thinking maybe I'm just dumb and missing something so I wanted to come here first to ask if anyone else was successful and would like to share their knowledge. If no one is successful or this is something that isn't supported I would like to then start a feature request.

### homepage version

0.9.9

### Installation method

Docker

## Edited to reflect changes in reply marked as answer

```yaml
- "":
  - Calendar:
      name: Calendar
      widget:
        type: calendar
        firstDayInWeek: sunday
        view: monthly
        maxEvents: 10
        showTime: true
        timezone: America/Denver
        integrations:
          - type: ical
            url: https://calendar.proton.me/api/calendar/v1/url/<identity>/calendar.ics?CacheKey=<secretkey>
            name: Events
            color: purple
            params:
              showName: true
```

### Troubleshooting

I tried adding the URL with quotes thinking maybe there were special characters in it that weren't properly sanitized, but even with quotes it doesn't work. I don't have another ical to test with right now, but my next step would be to create a temporary gmail account and create an ical link to do a sanity check and make sure the calendar widget is working.
