### DISCUSSION TITLE
Prefix "sh-" for selfh.st/icons does not work

### DISCUSSION THREAD

**Discussion by SoulRaven80** [gethomepage/homepage#4045] [Support] [answered]
### Description

Prefix "sh-" for selfh.st/icons does not work. Example:
services.yaml:
```
    - qBitTorrent:
        href: http://qbittorrent.mylan/
        description: Torrent client
        icon: sh-qbittorrent
        server: my-docker
        container: qbittorrent
```

**Expected**:
Generates an html referencing the selfhosted icon link (https://cdn.jsdelivr.net/gh/selfhst/icons/svg/qbittorrent.svg)
**Actual**:
Generates an html referencing the default dashboard icons (https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sh-qbittorrent.png) containing the "sh-" prefix, hence the icon is broken.

### homepage version

v0.9.9 (6b1080a, Sep 10, 2024)

### Installation method

Docker

### Configuration

```yaml
- qBitTorrent:
        href: http://qbittorrent.mylan/
        description: Torrent client
        icon: sh-qbittorrent
        server: my-docker
        container: qbittorrent
```

### Container Logs

Nothing relevant

### Troubleshooting

Already described
