### DISCUSSION TITLE
Calendar Widget Displaying time in 24hr format for Sonarr events

### DISCUSSION THREAD

**Discussion by SpartacusIam** [gethomepage/homepage#4051] [Support]
### Description

The Sonarr events on the calendar are displayed in 24hr instead of 12hr like it is in Sonarr.

### homepage version

v0.9.9 (6b1080a)

### Installation method

Docker

### Configuration

```yaml
- Events:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 30 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Hidden # group name where widget exists
              service_name: Sonarr # service name for that widget
              color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
              params: # optional - additional params for the service
                unmonitored: true # optional - defaults to false, used with *arr stack
            - type: radarr
              service_group: Hidden
              service_name: Radarr
              color: amber
```

### Troubleshooting

None
