### DISCUSSION TITLE
LubeLogger widget> API Error: Vehicle not found - no authentication

### DISCUSSION THREAD

**Discussion by vmoriaux** [gethomepage/homepage#4058] [Support] [answered]
### Description

I have setup LubeLogger to run without auth because I'm alone on my LAN.
I've setup the new widget trying with and without the username and password entries and I always get the same error. When I paste the LubeLogger URL in an icognito session, I can access the json

LubeLogger 1.3.8

![image](https://github.com/user-attachments/assets/f2096191-5b09-4c7e-963b-9fb2e519eb50)

After trying several thing, I found that the [doc](https://gethomepage.dev/widgets/services/lubelogger/) is wrong ! It says "vehicleID" where it should be "vehicleId" (lowercase d). And now it works.

### homepage version

0.9.10

### Installation method

Docker

### Troubleshooting

N/A

**Comment by vmoriaux** [comment]
@shamoon ping :)

**Comment by shamoon** [comment]
That is not accurate. It is `vehicleID`. Presumably your ID was in fact incorrect

**Reply by vmoriaux** [reply]
You are not very good at presuming :-) I have only 1 vehicle, I tried 1 and 0 for the vehicleID.

**Reply by shamoon** [reply]
Since this works:

```yaml
     - Lubelogger:
          description: lubelogger
          href: https://demo.lubelogger.com/api/vehicle/info
          icon: lubelogger.png
          widget:
                type: lubelogger
                url: https://demo.lubelogger.com
                username: test
                password: 1234
                vehicleID: 1
```

Perhaps look at the LubeLogger URL `/Vehicle/Index?vehicleId=3`

If that still doesn't work, post the API output from LubeLogger (the troubleshooting step you skipped above)
