### DISCUSSION TITLE
Failed to get API Information for Jellyfin

### DISCUSSION THREAD

**Discussion by Deytron** [gethomepage/homepage#4064] [Support]
### Description

Since recently, Homepage fails to get the latest informations from the Jellyfin API.

![image](https://github.com/user-attachments/assets/8fc12561-6299-410a-ba3e-c34d29ac97f7)

![image](https://github.com/user-attachments/assets/05456515-8391-4bd9-999a-059ebb02e94a)

This is 100% due to me using the **nightly** branch of Jellyfin. But I'm not really sure what exactly causes this.
I suspect this has to do with [this commit](https://github.com/jellyfin/jellyfin/pull/12696) that touched the API handling but I'm not totally sure. Maybe it's my fault, maybe it has to do with Homepage, or Jellyfin, I can't know exactly unfortunately.
Every other apps using an API key work fine (Jellyseer, Sonarr...)

Either way, this is not urgent but if this is one breaking change from the Jellyfin team, this should be handled properly.

### homepage version

v0.7.1 (latest)

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    extra_hosts: 
     [...]
    volumes:
      - ./homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Disks list
      [...]
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.xxx`)"
      - "traefik.http.routers.homepage.entrypoints=web-secure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    ports:
      - 3000
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - localnet
      - ip6net
```

### Container Logs

Unfortunately logs are not linked in any way to Jellyfin

### Troubleshooting

```
docker exec homepage ping xxx.xxx.xxx
PING xxx.xxx.xxx (2606:xxx): 56 data bytes
64 bytes from 2606:xxx: seq=0 ttl=58 time=10.979 ms
64 bytes from 2606:xxx: seq=1 ttl=58 time=9.512 ms
64 bytes from 2606:xxx: seq=2 ttl=58 time=9.166 ms
64 bytes from 2606:xxx: seq=3 ttl=58 time=12.640 ms
```
