### DISCUSSION TITLE
Calendar iCal - Wrong timezone when using repeating events

### DISCUSSION THREAD

**Discussion by justapawsibility** [gethomepage/homepage#4067] [Support] [answered]
### Description

I found a bug where when you add a repeating event in Google Calendar, the Calendar widget displays the wrong timezone. 
```
- Agenda:
  ¦ - Calendar:
  ¦ ¦ ¦ widget:
  ¦ ¦ ¦ ¦ type: calendar
  ¦ ¦ ¦ ¦ view: monthly
  ¦ ¦ ¦ ¦ firstDayInWeek: Sunday
  ¦ ¦ ¦ ¦ maxEvents: 15
  ¦ ¦ ¦ ¦ showTime: true
  ¦ ¦ ¦ ¦ previousDays: 3
  ¦ ¦ ¦ ¦ timezone: America/Chicago
  ¦ ¦ ¦ ¦ integrations:
  ¦ ¦ ¦ ¦ ¦ - type: ical
  ¦ ¦ ¦ ¦ ¦ ¦ url: https://calendar.google.com/calendar/ical/en.usa%23holiday%40group.v.calendar.google.com/public/basic.ics
  ¦ ¦ ¦ ¦ ¦ ¦ name: Holidays
  ¦ ¦ ¦ ¦ ¦ ¦ color: blue
  ¦ ¦ ¦ ¦ ¦ ¦ params:
  ¦ ¦ ¦ ¦ ¦ ¦ ¦ showName: true
  ¦ ¦ ¦ ¦ ¦ - type: ical
  ¦ ¦ ¦ ¦ ¦ ¦ url: <private calendar link>
  ¦ ¦ ¦ ¦ ¦ ¦ name: Family
  ¦ ¦ ¦ ¦ ¦ ¦ color: orange
  ¦ ¦ ¦ ¦ ¦ ¦ params:
  ¦ ¦ ¦ ¦ ¦ ¦ ¦ showName: true
```
How to replicate: 
- Create a new google calendar
- Create a repeating event with a time
- Copy the private ics file 
- Use the code above
- Hover over the event in the homepage calendar

### homepage version

v0.9.10

### Installation method

Docker

### Configuration

```yaml
- Agenda:
  ¦ - Calendar:
  ¦ ¦ ¦ widget:
  ¦ ¦ ¦ ¦ type: calendar
  ¦ ¦ ¦ ¦ view: monthly
  ¦ ¦ ¦ ¦ firstDayInWeek: Sunday
  ¦ ¦ ¦ ¦ maxEvents: 15
  ¦ ¦ ¦ ¦ showTime: true
  ¦ ¦ ¦ ¦ previousDays: 3
  ¦ ¦ ¦ ¦ timezone: America/Chicago
  ¦ ¦ ¦ ¦ integrations:
  ¦ ¦ ¦ ¦ ¦ - type: ical
  ¦ ¦ ¦ ¦ ¦ ¦ url: https://calendar.google.com/calendar/ical/en.usa%23holiday%40group.v.calendar.google.com/public/basic.ics
  ¦ ¦ ¦ ¦ ¦ ¦ name: Holidays
  ¦ ¦ ¦ ¦ ¦ ¦ color: blue
  ¦ ¦ ¦ ¦ ¦ ¦ params:
  ¦ ¦ ¦ ¦ ¦ ¦ ¦ showName: true
  ¦ ¦ ¦ ¦ ¦ - type: ical
  ¦ ¦ ¦ ¦ ¦ ¦ url: <private calendar link>
  ¦ ¦ ¦ ¦ ¦ ¦ name: Family
  ¦ ¦ ¦ ¦ ¦ ¦ color: orange
  ¦ ¦ ¦ ¦ ¦ ¦ params:
  ¦ ¦ ¦ ¦ ¦ ¦ ¦ showName: true
```

### Troubleshooting

N/a

**Comment by mikejsutherland** [comment]
I am seeing this bug also in v0.10.9 and believe that in the case of a reoccurring event, timezones are not taken into account.

I believe the problem is here: https://github.com/gethomepage/homepage/blob/0615799c6cda81db02fd75a88a7da4d459211f91/src/widgets/calendar/integrations/ical.jsx#L75-L89

I have created a public calendar which easily replicates the issue.

Google shows the correct time.
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/0fdd752f-670d-4148-b52b-8f110a78b991" />

While the Calendar ical integration does not.
<img width="496" alt="image" src="https://github.com/user-attachments/assets/68097b6f-7636-4b4d-9a2a-e5e0b53687ff" />

Public ics: https://calendar.google.com/calendar/ical/0b92cc71985105492b668c83caccaa7e718e384fbf8e1efceefd2e5f1e521904%40group.calendar.google.com/public/basic.ics

service.yml
```
- Calendar:
    href: https://calendar.google.com/calendar/u/0/r/month
    widget:
      type: calendar
      view: monthly
      firstDayInWeek: sunday
      showTime: true
      timezone: US/Eastern
      integrations:
        - type: ical
          url: https://calendar.google.com/calendar/ical/0b92cc71985105492b668c83caccaa7e718e384fbf8e1efceefd2e5f1e521904%40group.calendar.google.com/public/basic.ics
          name: Reoccurring Event Bug
          color: red
          params:
            showName: false
```

I am happy to create a bug and test any fixes if the devs agree?
