### DISCUSSION TITLE
Struggling to get Widgets working

### DISCUSSION THREAD

**Discussion by nniillaa** [gethomepage/homepage#4071] [Support]
### Description

Hi
I'm struggling to get widgets working. 
Examples below from 'glances'

A direct call to that url (http://omv:61208/api/3/cpu) gives me the return payload with no problems. 

### homepage version

v0.9.10

### Installation method

Docker

### Configuration

```yaml
Glances docker config:
`---
services:
  glances:
    image: nicolargo/glances:3.4.0.5-full
    container_name: glances
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
      - /home/docker1/composeFiles/glances:/glances/conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "GLANCES_OPT=-w"
      - TZ=Asia/Singapore
    restart: unless-stopped
`

Homepage docker config:
`---
# https://github.com/benphelps/homepage
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/docker1/composeFiles/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped
`

Services.yaml -1 
`---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services


- OMV:
    - OpenMediaVault:
        icon: openmediavault
        href: http://omv/
        description: Server Login
    - DokuWiki:
        icon: dokuwiki
        href: http://omv:8011
        description: Server configuration information
        container: dokuwiki
    - CPU:
        widget:
          type: glances
          version: 3
          url: http://omv:61208
          metric: cpu
`

And another failed  part:
`- Server Management & Tools:
    - Glances:
        icon: glances
        href: http://omv:61208/
        description: Server stats and utilization
        container: glances
        server: my-docker
        showStats: true
        widget:
          type: glances
          version: 3
          url: http://omv:61208
          metric: cpu
          refreshInterval: 5000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
          pointsLimit: 15 # optional, defaults to 15

`
```

### Container Logs

[2024-10-01T15:16:42.975Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://omv:61208/api/3/cpu
[2024-10-01T15:16:44.054Z] error: <httpProxy> Error calling http://omv:61208/api/3/cpu...
[2024-10-01T15:16:44.055Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED ::1:61208
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 61208
  }
]
[2024-10-01T15:16:44.056Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://omv:61208/api/3/cpu
[2024-10-01T15:16:45.014Z] error: <httpProxy> Error calling http://omv:61208/api/3/cpu...
[2024-10-01T15:16:45.015Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED ::1:61208
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 61208
  }
]

### Troubleshooting

N/A
