### DISCUSSION TITLE
Flood Validation error

### DISCUSSION THREAD

**Discussion by Mercy0310** [gethomepage/homepage#4072] [Support]
### Description

Flood 4.8.2
Validation error

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
- Flood Server:
        href: http://192.168.1.1:3001/
        icon: /icons/Flood_A.png
        widget:
          type: flood
          url: http://192.168.1.1:3001
          username: root
          password: 123456
```

### Container Logs

<img width="693" alt="屏幕截图 2024-10-02 002703" src="https://github.com/user-attachments/assets/f2c36db6-a7e3-41af-a706-c37b3b289f9c">

### Troubleshooting

no
