### DISCUSSION TITLE
Can't get SoftRAID array to show in resources widget.

### DISCUSSION THREAD

**Discussion by vastoholic** [gethomepage/homepage#4081] [Support]
### Description

I have tried this in two different environments. Ubuntu 24.04 LTS and MacOS Sequoia. 

I have a SoftRAID (RAID 5) volume mounted onto a MacStudio via Thunderbolt cable in an OWC Thunderbay 4 chassis. I have named the volume "Plex TB3 RAID 5". On the Mac it shows as mounted on /Volumes/Plex TB3 RAID 5 and is called /dev/disk8 on the filesystem. I have file sharing turned on in the Mac with SMB sharing enabled. 

I mounted it on the Ubuntu machine by editing the fstab file as a cifs type. Everything works fine on that side. I can access the volume and have full permissions to it. It is mounted on /mnt/Media. All of my *Arr apps connect to it just fine through their respective docker containers. 

I have included my docker-compose yaml and the widgets yaml below in the configuration section. I have it set to Read Only on this current configuration, but I have tried it without and still get the same results. 

All I ever get is the base system storage. 

![Screenshot 2024-10-01 at 4 36 32 PM](https://github.com/user-attachments/assets/7bae9955-d68e-43b7-a0e8-f3e2d6a342ed)

Just today I decided to give the docker desktop app a try on my Mac Studio. 

On the volumes section of the docker-compose.yml I changed it to show /Volumes/Plex TB3 RAID 5:/mnt/Plex:ro. It still would only show the host machine's internal drive. I tried various other naming methods like /dev/disk8/Volumes/Plex or just /dev/disk8. I did notice that if I installed glances via docker desktop, it doesn't show that volume even though it says /Volumes is shared in the file sharing settings for docker. I even added that specific Volume to it and it won't show up. 

I would like to resolve this on the Ubuntu side rather than the Mac side. If it's a problem 

### homepage version

v0.9.10

### Installation method

Docker

### Configuration

```yaml
Docker Compose yml
---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/user/Arr/Homepage/data:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/Media:/mnt/Plex:ro
      - /home/user/Pictures/Homepage:/app/public/images
      - /home/user/Pictures/Homepage/icons:/app/public/icons
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000


Widgets yml
- resources:
    cpu: true
    memory: true
    expanded: true
    disk: /mnt/Plex

- search:
    provider: google
    target: _blank
```

### Container Logs

Nothing shows in the logs. Just says that it's listening on port 3000.

### Troubleshooting

none
