### DISCUSSION TITLE
[Feature Request] Is there a way to have multiple instances of the date/time widget each showing a different timezone?

### DISCUSSION THREAD

**Discussion by john2069** [gethomepage/homepage#4087] [Feature Requests]
### Description

I'd like to display multiple date/times via the header widget, each showing a different value from across the globe.

**Comment by timespacedecay** [comment]
Yes, just add multiple datetime widgets.  For example, I show Date and Time separately using this:
```
- datetime:
    id: datetime
    text_size: md
    format:
        dateStyle: short

- datetime:
    id: datetime
    text_size: md
    format:
        timeStyle: short
        hourCycle: h23
```

Should should be able to do the same while specifying `locale:` for each of the `- datetime:` widgets.  More info here: https://gethomepage.dev/widgets/info/datetime/
