### DISCUSSION TITLE
An error in the operation of the tailscale

### DISCUSSION THREAD

**Discussion by Druidblack** [gethomepage/homepage#4089] [Support]
### Description

The widget for tailscale has stopped working
![6667777](https://github.com/user-attachments/assets/58faccf6-00a9-405e-9de4-2bdd15ee6366)

### homepage version

v0.9.10 (132d8f4, Sep 26, 2024)

### Installation method

Docker

### Configuration

```yaml
- Tailscale:
        icon: tailscale.png
        href: https://login.tailscale.com/admin/machines
        description: Tailscale
        widget:
          type: tailscale
          deviceid: nFdnyh1so599CNTRL
          key: tskey-api-kYPqVr5xc1CNTRL-KXVULBc8VKmyrAStV6BKeceym3XsXg
```

### Troubleshooting

Everything was working well a few days ago.
