### DISCUSSION TITLE
Immich container status

### DISCUSSION THREAD

**Discussion by b-onc** [gethomepage/homepage#4092] [Support] [answered]
### Description

Hello,

I've set up homepage on my raspberry pi and immich running in Container Manager in Synology DS923+

I'm trying to get homepage to display container status. For this, I've enabled TCP port 2375 in my NAS using [this instruction](https://gist.github.com/styblope/dc55e0ad2a9848f2cc3307d4819d819f?permalink_comment_id=4697063#gistcomment-4697063):

> For everyone finding this page and looking for instructions for Synology's new Container Manager,
> 1. `sudo vi /var/packages/ContainerManager/etc/dockerd.json`
change to:
`{"data-root":"/var/packages/ContainerManager/var/docker","log-driver":"db","registry-mirrors":[],"storage-driver":"aufs","hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}`
> (basically add the stuff from the original step 1 to the end, without the curly-brackets {} )
> 2. `systemctl daemon-reload`
> 3. `sudo systemctl restart pkg-ContainerManager-dockerd`

Then I've added NAS' docker host to raspberry pi following [this](https://gethomepage.dev/configs/docker/):
```
ds923-docker:
  host: 192.168.178.121 # my NAS is on this ip
  port: 2375
```

Configuring homepage correctly:
```
- Immich:
        href: http://ds923.local:2283
        icon: immich.png
        description: Self-hosted photo library
        server: ds923-docker
        container: immich
        widget:
          type: immich
          url: http://192.168.178.121:2283
          key: <redacted>
          fields: ["photos", "videos"]
```
Container status does not work, I see in homepage's logs:
> error: <credentialedProxyHandler> HTTP Error 404 calling http://192.168.178.121:2283/api/server-info/stats

2283 being the port I'm hosting immich.

Widget works correctly, container status does not. I see the API error even when I comment out `server` and `container`, but widget keeps working. I don't see any error in logs regarding the docker error.

<img width="403" alt="image" src="https://github.com/user-attachments/assets/7e2ba5bd-2d26-42cd-8e52-a863acf87a38">

### homepage version

v0.9.10

### Installation method

Docker

### Troubleshooting

-
