### DISCUSSION TITLE
Possible bug: WG-Easy does not show disabled field

### DISCUSSION THREAD

**Discussion by SixFive7** [gethomepage/homepage#4095] [Support] [answered]
### Description

When setting up the widget like this:

```
    - Wireguard:
        description: Secure cryptographic tunneling endpoint server
        href: https://wireguard.infrastructure.xxx.xxx/
        icon: wireguard.svg
        ping: infrastructure-wireguard
        siteMonitor: http://infrastructure-wireguard:51821
        container: infrastructure-wireguard
        server: docker-proxy
        widget:
          type: wgeasy
          url: http://infrastructure-wireguard:51821
          password: xxx
          fields: ["connected", "enabled", "disabled", "total"]
```

It renders like this:
![image](https://github.com/user-attachments/assets/885298be-6cfe-4308-b4a5-25233d2d0c36)

I'd expect there to be a disabled field. Also, I'm no front-end expert so I have no clue what this means, but whenever I reload the page it is visible for a fraction for a second and then disappears.

### homepage version

v0.9.10

### Installation method

Docker

### Troubleshooting

Not relevant, there are no errors.
