### DISCUSSION TITLE
Better handling of bookmarks

### DISCUSSION THREAD

**Discussion by ForeGuards** [gethomepage/homepage#4099] [Feature Requests]
### Description

I started using Homepage, and I literally love it. The only thing I miss is the management of all my bookmarks. I have lots of them categorised and grouped. I also have sub-groups, which I wanted to move to the Homepage, but after a few hours, I gave up. 

Would be possible to implement better handling of the bookmark like:

Main group --> sub-groups --> urls
Developer --> Python, C, C++ --> all URLs related to the thema

Thank you very much!

**Comment by chrisjenx** [comment]
I think just allowing different headers would be an awesome start, I didn't realize they were fixed names until they disappeared when I changed the names.

**Reply by owennewo-dev** [reply]
> I think just allowing different headers would be an awesome start, I didn't realize they were fixed names until they disappeared when I changed the names.

Are you saying that you can't change the text that is above your bookmarks group? The ones that by default are `Developer` `Social` and `Entertainment`?

**Reply by chrisjenx** [reply]
Thats what I noticed, I could be doing something wrong tho?

**Reply by owennewo-dev** [reply]
What does your bookmarks.yaml code look like?
Here is mine
```
- Cool Stuff:
    - Immich Github:
      - icon: immich.png
        href: https://github.com/immich-app/immich
```
I think you have formatted the header title wrong (`- Cool Stuff:`) do you have a colon after the header name?

**Reply by chrisjenx** [reply]
Lemme try again, maybe I fat fingered something.

**Reply by chrisjenx** [reply]
Oh yeah, ignore me, I must of fat fingered some white space when I did it the first time, working now, Thanks!

**Comment by owennewo-dev** [comment]
This would be great, I am trying to get my bookmarks to have subgroups. I want:
```yaml
- Bookmarks2:
  - Homepage:
      - My Homepage Repo:
        - icon: github.png
          href: https://github.com/owennewo-photo/setup-Homepage-on-TrueNAS
      - Github:
        - icon: github.png
          href: https://github.com/gethomepage/homepage
      - Discussions:
        - icon: github.png
          href: https://github.com/gethomepage/homepage/discussions
      - Docs:
        - icon: mkdocs.png
          href: https://gethomepage.dev/configs
      - Icons:
        - icon: github.png
          href: https://github.com/walkxcode/dashboard-icons
      - More Icons:
        - icon: si-simpleicons
          href: https://simpleicons.org/
```
That way I can have two rows of bookmarks, each with a few columns of subgrouped bookmarks.
