### DISCUSSION TITLE
Specify mtls for a service

### DISCUSSION THREAD

**Discussion by lukasz-lobocki** [gethomepage/homepage#4104] [General]
Hi, is it possible to provide mTLS certs to ordinary service? In a way similar to the docker approach.

```
tls:
    keyFile: tls/key.pem
    caFile: tls/ca.pem
    certFile: tls/cert.pem
```
