### DISCUSSION TITLE
Trying to wrap my head around connecting multiple docker socket proxies and one instance of homepage

### DISCUSSION THREAD

**Discussion by cribbageSTARSHIP** [gethomepage/homepage#4105] [Support]
I'm trying to wrap my head around integrating multiple machines into Homepage via dockerproxy. I have a few machines: 

```
    10.11.5.10 <-- main machine running homepage on docker

    10.11.5.20

    10.11.5.30

    10.11.5.40
```
 I'm not understanding how to link all this together though. I've been at the configs all day and my head hurts. If anyone has got this to work and could weigh in on what I may be doing wrong I would really appreciate it! Thank you.

I have a docker socket proxy installed on each machine: 

```
---
services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 10.11.5.10:2375:2375 # <-- changed on each machine to reflect its ip
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
```
My docker-compose:

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./homepage-data:/app/config # Make sure your local config directory exists
    environment:
      PUID: 1000
      PGID: 100
```
an example of what I'm trying to get working in my services.yaml:

```
    - QBT:
        icon: qbittorrent.svg
        href: http://10.11.5.20:8089/
        description: Torrent VPN
        server: sff02-docker
        container: QbitTorrent-Nord
        widget:
            type: qbittorrent
            url: http://10.11.5.20:8089/
            username: admin
            password: adminadmin   
```
My docker.yaml 

```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

sff01-docker:
  host: 10.11.5.10
  port: 2375
sff02-docker:
  host: 10.11.5.20
  port: 2375
Mini01-docker:
  host: 10.11.5.30
  port: 2375
Mini02-docker:
  host: 10.11.5.40
  port: 2375      
```
