### DISCUSSION TITLE
Can it start/stop containers

### DISCUSSION THREAD

**Discussion by adocampo** [gethomepage/homepage#4107] [General]
I would like to know if we're able to stop and start docker containers somehow, and if possible, how can we configure it.

**Comment by riccardo1991** [comment]
I was thinking the same, as I have some containers I just turn on just sometimes (e.g. scanservjs when I need to scan a document, etc.).
Ideally, it would be nice to have a small button next to the status dot (or ping time): stop button if the container is running, start button if the container is not found. Portainer, for example, exposes APIs to start/stop a specific stack.

``` yaml
server: myDockerInstance
container: myContainer
  start_call: <API_call>
  stop_call: <API_call>
```
