### DISCUSSION TITLE
Font bug

### DISCUSSION THREAD

**Discussion by mixman68** [gethomepage/homepage#4120] [Support] [answered]
### Description

Hello,

Out of the box config, I created a card and I have an issue with the font in the description

![image](https://github.com/user-attachments/assets/a927de96-317d-4a92-bcfd-b6a4b97a27b7)

the I letter is over the b

### homepage version

0.9.10

### Installation method

Docker

### Troubleshooting

Create a service with this text

```
- Test:
    - Test:
        href: http://google.com
        description: "fibre"
```
