### DISCUSSION TITLE
immich_server API error: Cannot GET /api/server-info/stats

### DISCUSSION THREAD

**Discussion by Jackie264** [gethomepage/homepage#4137] [Support] [answered]
### Description

<img width="407" alt="Screenshot 2024-10-16 at 18 32 51" src="https://github.com/user-attachments/assets/eeafb472-9fe9-4738-99e7-695d9904164e">

immich version: v1.118.1

### homepage version

v0.9.11 (2245cdd, Oct 16, 2024)

### Installation method

Docker

### Configuration

```yaml
- Immich:
        icon: http://192.88.9.6/uploads/2024/7/21/366df190786b352c73d74d0cdbcc332a.png
        hrep: http://192.88.9.6:2283
        description: Photo Library
        widget:
            type: immich
            url: http://192.88.9.6:2283
            key: xzjmsExwBmP2alI3McbDKvVtk3VycIFpMl8ypQ
        server: my-docker
        container: immich_server
```

### Container Logs

[2024-10-16T10:33:42.259Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://192.88.9.6:2283/api/server-info/version
[2024-10-16T10:33:42.265Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://192.88.9.6:2283/api/server-info/stats

### Troubleshooting

restart homepage Container
restart immich_server Container
