### DISCUSSION TITLE
iFrame widget height

### DISCUSSION THREAD

**Discussion by netsec007** [gethomepage/homepage#4143] [Support] [answered]
### Description

How do you increase the height of the iFrame widget?
changing any of the numbers here does nothing:  

- ShowInformation:
          widget:
              type: iframe
              name: myIframe
              src: https://simkl.com/tv/calendar/0000000/
              classes: h-40 sm:h-40 md:h-40 lg:h-40 xl:h-40 2xl:h-40 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height

### homepage version

latest 

### Installation method

Docker

### Configuration

```yaml
- ShowInformation:
          widget:
              type: iframe
              name: myIframe
              src: https://simkl.com/tv/calendar/00000000/
              classes: h-40 sm:h-40 md:h-40 lg:h-40 xl:h-40 2xl:h-40 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
```

### Troubleshooting

changed values

**Comment by shamoon** [comment, marked as answer]
The above should work fine, its easy enough to look in your browser web inspector to see if the css classes are being applied, but e.g.:



```
     - iFrame:
          widget:
               type: iframe
               src: https://example.com
               classes: h-40 sm:h-40 md:h-40 lg:h-40 xl:h-40
```

<img width="888" alt="Screenshot 2024-10-16 at 1 09 31 PM" src="https://github.com/user-attachments/assets/d40afa30-ed28-4728-87f1-8c842b718cd6">


vs

```
     - iFrame:
          widget:
               type: iframe
               src: https://example.com
               classes: h-60 sm:h-60 md:h-60 lg:h-60 xl:h-72
```

<img width="874" alt="Screenshot 2024-10-16 at 1 09 52 PM" src="https://github.com/user-attachments/assets/3a0f2ebc-8545-4460-a49c-41b7f0053761">

<img width="1406" alt="Screenshot 2024-10-16 at 1 11 01 PM" src="https://github.com/user-attachments/assets/6e903ba4-845a-48e8-b8d1-bd686f18e973">
