### DISCUSSION TITLE
.env variables with special characters

### DISCUSSION THREAD

**Discussion by itsjusec** [gethomepage/homepage#4153] [Support]
### Description

if i want to use the HOME_VAR_XXX variables for passwords, i get problems as soon as the passwords contain special characters.

One of my passwords contains “$&” . I used this as a variable for the description to test it. The password is then written out up to the $ then the variable and then the rest of the password.

I have tried all “ and ' combinations for the variable. I just can't get it to work.

if I put a \ in front of both characters it shows the whole string but with the two \ included.

Is there a way to use special characters in the envs?

Translated with www.DeepL.com/Translator (free version)

### homepage version

v0.9.11

### Installation method

Docker

### Configuration

```yaml
- AdGuard DNS:
        icon: adguard-home.png
        href: <Url>
        description: "{{HOMEPAGE_VAR_ADGUARDPASS}}"
        widget:
          type: adguard
          url: <url>
          username: user
          password: "{{HOMEPAGE_VAR_ADGUARDPASS}}"

env example:
HOMEPAGE_VAR_ADGUARDPASS="2qIwJjqFIBeU$&5ePGNf" # (different things tested)
```

### Troubleshooting

![image](https://github.com/user-attachments/assets/5ca4aa80-cd95-4e94-a7f1-4c57fb54df19)
