### DISCUSSION TITLE
Support other videos (YT) in Jellyfin widget

### DISCUSSION THREAD

**Discussion by t0g3pii** [gethomepage/homepage#4160] [Feature Requests]
### Description

When using the [TubeArchivist Plugin for Jellyfin](https://github.com/tubearchivist/tubearchivist-jf-plugin) and watch imported Videos from it, the widget is unable to show the stream running. hideErrors is ignored here.

First Screenshot is with a YouTube Video imported from TubeArchivist, second with a normal Episode from my Series.

![grafik](https://github.com/user-attachments/assets/973c4f94-5a4d-4c4f-a4cb-1f8642c8dfe8)
![grafik](https://github.com/user-attachments/assets/5a1bdfe6-09c0-4522-b264-24f0a527c743)

### homepage version

v0.9.11 (2245ccd)

### Installation method

Docker

### Configuration

```yaml
-- services.yaml
- Medien:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.0.30:8096
        description: Meine Mediathek
        widget:
          type: jellyfin
          url: http://192.168.0.30:8096
          key: {{HOMEPAGE_VAR_JELLYFINAPIKEY}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
          hideErrors: true
```

### Browser Logs

TypeError: o is undefined
    NextJS 11
 
Object { componentStack: "\np@http://192.168.0.24:3000/_next/static/chunks/7577.17dca6af33e5c1f6.js:1:3927\ndiv\nb@http://192.168.0.24:3000/_next/static/chunks/7577.17dca6af33e5c1f6.js:1:6478\n97986/g/h<@http://192.168.0.24:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:34754\nn@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:17554\nR@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:34336\ndiv\nli\nM@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:38229\nul\nW@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:42292\ndiv\n66548/L<@http://192.168.0.24:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:79373\ndiv\nl@http://192.168.0.24:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:108165\n96222/k<@http://192.168.0.24:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:97665\n96222/P<@http://192.168.0.24:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:96348\nl@http://192.168.0.24:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:108165\n66548/C<@http://192.168.0.24:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:77323\ndiv\nJ@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:42792\ndiv\ndiv\nge@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:63377\nn@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:17554\n75182/Y<@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:90720\nve@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:61385\ndiv\ndiv\ndiv\nwe@http://192.168.0.24:3000/_next/static/chunks/pages/index-4678908cb37f1d8c.js:1:70423\na@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:16128\na@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:15771\ns@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:16687\nu@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:15199\n75182/Y<@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:90720\n28397/t.default<@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:14450\nl@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:1248\nn@http://192.168.0.24:3000/_next/static/chunks/pages/_app-3e43cf18393ab8f7.js:1:5694\nr@http://192.168.0.24:3000/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:6997\nY@http://192.168.0.24:3000/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:9242\nie@http://192.168.0.24:3000/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:11883" }
<anonymous code>:1:145535

### Troubleshooting

N/A
