### DISCUSSION TITLE
Zabbix returns Missing Widget Type: zabbix

### DISCUSSION THREAD

**Discussion by obogle1986** [gethomepage/homepage#4163] [Support] [answered]
### Description

Not sure what's wrong but this is the error I'm getting: Missing Widget Type: zabbix
<img width="399" alt="image" src="https://github.com/user-attachments/assets/443930d5-b1ae-4925-bf4d-d9c6db2fe432">

### homepage version

v0.9.6

### Installation method

Docker

### Configuration

```yaml
- Zabbix:
        icon: zabbix.png
        href: http://192.168.x.x:8532
        description: Network Monitoring
        widget:
          type: zabbix
          url: http://192.168.x.x:8532
          key: api_key
```

### Troubleshooting

I followed the documentation, generated the api key but still receiving the error.
