### DISCUSSION TITLE
Homepage unable to connect other services running in docker in same machine

### DISCUSSION THREAD

**Discussion by CodeWithCJ** [gethomepage/homepage#4164] [Support] [answered]
### Description

I have installed portainer in Oracle free tier and installed homepage, adguard dns, nginx proxy manager etc.
I used private IP address 10.0.0.10 along with port to configure the services.yaml file. But it is showing error.

### homepage version

v0.9.11 (2245cdd, Oct 15, 2024)

### Installation method

Docker

### Configuration

```yaml
- Monitor:       
    - Adguard:
        href: https://adguard.asdasd.buzz
        icon: adguard.png
        widget:
          type: adguard               
          url: http://10.0.0.10:8443
          username: SparkyAdguard
          password: qweqwe$
         
    - NPM:
        href: https://nginx.asdasd.buzz
        icon: nginx.png
        widget:
          type: npm
          url: http://10.0.0.10:81
          username: asdasd@gmail.com
          password: asdasd$
          icon: nginx.png
    - Portainer:
        href: https://port.asdasd.buzz
        icon: portainer.png
        widget:
          type: portainer
          url: https://10.0.0.10:9000
          env: 2
          key: ptr_N/4zpU63nhEmJ
```

### Container Logs

API Error: Unknown error
URL: https://10.0.0.10:9000/api/endpoints/2/docker/containers/json?all=1
Raw Error:
{
    "errno": -71,
    "code": "EPROTO",
    "syscall": "write"
}

### Browser Logs

API Error: Unknown error
URL: https://10.0.0.10:9000/api/endpoints/2/docker/containers/json?all=1
Raw Error:
{
    "errno": -71,
    "code": "EPROTO",
    "syscall": "write"
}

### Troubleshooting

test
