### DISCUSSION TITLE
Quick Launch works not as expected

### DISCUSSION THREAD

**Discussion by denk-mal** [gethomepage/homepage#4177] [Support] [answered]
### Description

Hi

When I try to access the "Quick Launch" function (by pressing spacebar) not all entries will be shown. it seems to me that only entries with 2 or more words are visible. Furtermore if I press a single letter only those entries will be shown where the second (or third) word start with the letter.

E.g. in the below configuration when I press the space bar only 'Pi Hole' and 'Status Page' will be shown; 'Services' and 'Portal' are invisible. After pressing 'P' only 'Status Page' will be visible; 'Pi Hole' is also invisible then.
How do I have to change the bookmarks.yaml or the settings.yaml so that Quick Launch will showing all entries and showing 'Status Page and 'Pi Hole' on pressing 'P'?

BTW this happens on Firefox, Edge and Vivaldi (all windows) and on google chrome (linux) the same way so it seems not to be a browser thing.

### homepage version

v0.9.11 (2245cdd, 15. Okt. 2024)

### Installation method

Docker

### Configuration

```yaml
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Network:
    - Pi Hole:
        - href: https://pihole.company.invalid
    - Status Page:
        - href: https://statuspage.company.invalid
    - Services:
        - href: https://services.company.invalid
    - Portal:
        - href: https://portal.company.invalid
```

### Troubleshooting

none
