### DISCUSSION TITLE
[Feature Request] Seafile integration

### DISCUSSION THREAD

**Discussion by ryanwinter** [gethomepage/homepage#4185] [Feature Requests]
### Description

I see someone proposed this in the past, would love to see this integrated.

**Comment by robflate** [comment]
This appears to have the arbitrarily designated 5 "up-votes" as suggested by @shamoon in the original PR. Any chance we can get this added? Thanks.

https://github.com/gethomepage/homepage/pull/1486

**Reply by oonqt** [reply]
It looks like they changed this, now 20 upvotes are required per homepage doc site: 

"_Please only submit widgets that target a feature request discussion with at least 20 'up-votes'. The purpose of this requirement is to avoid the addition (and maintenance) of service widgets that might only benefit a small number of users._"

**Reply by huyz** [reply]
The problem with the old min-5 (and even worse new min-20) discussion policy is that discussion threads are automatically closed too quickly.  So it's very hard for new feature requests to survive.

I think the whole system is busted.  I'm not sure what the whole point is anymore.

**Reply by oonqt** [reply]
> The problem with the old min-5 (and even worse new min-20) discussion policy is that discussion threads are automatically closed too quickly. So it's very hard for new feature requests to survive.
> 
> I think the whole system is busted. I'm not sure what the whole point is anymore.

They need to change the system and allow us to use custom widgets. Im not talking a custom api widget, im talking a full widget with the front end component and the backend script.  That way we can develop widgets for people to use & test while the feature gets enough jobid.

**Reply by taronling** [reply]
It seems that this has now also passed the 20 upvotes requirement?

**Comment by hinuiiik** [comment]
In case anybody wants a customapi widget for seafile, I made one:
```
widget:
  type: customapi
  url: https://seafile.tld/api/v2.1/admin/sysinfo/
  refreshInterval: 10000
  method: GET
  headers:
    Authorization: Bearer ACCOUNT_TOKEN
  mappings:
    - field: users_count
      label: Total Users
      format: number
    - field: active_users_count
      label: Active Users
      format: number
    - field: repos_count
      label: Repositories
      format: number
    - field: total_files_count
      label: Total Files
      format: number
    - field: groups_count
      label: Groups
      format: number
    - field: org_count
      label: Organizations
      format: number
    - field: total_storage
      label: Total Storage
      format: bytes
    - field: total_devices_count
      label: Total Devices
      format: number
    - field: current_connected_devices_count
      label: Connected Devices
      format: number
```
You can get your account token here: https://seafile-api.readme.io/reference/post_api2-auth-token
It has to be for an admin account. 
You can also comment out any field you don't need.
