### DISCUSSION TITLE
Proxmox Widget API Token Not Working as expected

### DISCUSSION THREAD

**Discussion by mariocosta13** [gethomepage/homepage#4187] [Support]
### Description

Hi there,  i hope you all fine.
Yesterday, i started my journey with the homepage dashboard with the help of some tutorials on youtube. I've already added some services and added for example the pi-hole widget which is working great.

However i'm facing an issue with the proxmox widget, which is not able to provide the proxmox resources info on the dashboard. 
Worth to mention that i have followed along the [proxmox widget tutorial](https://gethomepage.dev/widgets/services/proxmox/).

With that being said, could anyone help me on this issue ? 

Best regards!

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
**docker-compose.yaml**

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      #- /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      PUID: $PUID # read from .env
      PGID: $PGID # read from .env
```
**config/services.yaml**
```
- Hypervisor:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox:8006
        description: Proxmox VE
        widget:
          type: proxmox
          url: https://proxmox:8006
          username: api@pam!homepage
          password: 7ac4849f-19c1-4dcd-8fc7-6371e7e4****
          #node: pve-1 # optional
```
```


### Container Logs

**docker logs homepage**
```
[2024-10-24T21:18:56.441Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://proxmox:8006/api2/json/cluster/resources
[2024-10-24T21:19:22.475Z] error: <httpProxy> Error calling https://proxmox:8006/api2/json/cluster/resources...
[2024-10-24T21:19:22.476Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN proxmox
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'proxmox'
  }
]
```

### Browser Logs

    API Error: Unknown error
    URL: https://proxmox:8006/api2/json/cluster/resources
    Raw Error:
    {
        "errno": -3001,
        "code": "EAI_AGAIN",
        "syscall": "getaddrinfo",
        "hostname": "proxmox"
    }

### Troubleshooting

I've already confirm that the API Token is valid, by using Postman. I have made the request to the uri api2/json/cluster/resources with the the authorization key 'PVEAPIToken=api@pam!homepage=7ac4849f-19c1-4dcd-8fc7-6371e7e4****' which retrieved the expected info data:json

I've also tested copying the url retrieved on the docker logs use it on the browser, check the network on dev console, which also gave an error, but than i've tried to retry the request but this time by adding the authorization and this worked. 


Just to finnish, i've also tried to looked to the homepage code here on github. but with no further actions.

```
      } else if (widget.type === "proxmox") {
        headers.Authorization = `PVEAPIToken=${widget.username}=${widget.password}`;
```
