### DISCUSSION TITLE
[Feature Request] Add Auto Refresh Interval and Progress Bars to SABnzbd

### DISCUSSION THREAD

**Discussion by johnagil** [gethomepage/homepage#4197] [Feature Requests]
### Description

I set up the SABnzbd widget to accept refreshInterval, enableQueue, and limit in the services.yaml. There is a related feature request, [#1956](https://github.com/gethomepage/homepage/discussions/1956) that got auto closed two days ago with 11 upvotes, and [#2621](https://github.com/gethomepage/homepage/discussions/2621). Since they have been closed and one was also asking about Overseerr I'm opening a new discussion.

I understand that maintainers are hesitant to allow refreshInterval on services, but from what I can tell JDownloader already has refreshInterval enabled. I'd be willing to make pull requests for other download widgets as well if there is enough interest. Queue progress would be dependent on their respective api's.

```yaml
- Media:
    - SABnzbd:
        icon: sabnzbd.png
        href: https://sabnzbd.myurl.app
        ping: https://sabnzbd.myurl.app
        widget:
          type: sabnzbd
          url: http://192.168.100.100:30055
          key: myapikey
          enableQueue: true # optional, defaults to false, does not interfere with default queue block
          refreshInterval: 1000 # optional, defaults to 30000 ms (30 s), minimum is 1000 ms
          limit: 10 # optional, max number of queue progress bars to display, defaults to 5
```

Example below with refreshInterval set to one second. SABnzbd is getting 205 B of data when there is nothing in the queue, and 1.3 KB max when the limit is set to 10. Limit is passed to the api as the max number of jobs retrieved. Titles are just placeholders, they would be the actual title of the file being downloaded in production.

https://github.com/user-attachments/assets/59787c4c-97b8-4090-bcf7-6d530776e6e3
