### DISCUSSION TITLE
[Feature Request]  Add Beszel Widget

### DISCUSSION THREAD

**Discussion by rcbop** [gethomepage/homepage#4201] [Feature Requests] [answered]
### Description

First, let me say thanks for the awesome project.
Could you please put in your roadmap to add a simple [Beszel monitoring](https://github.com/henrygd/beszel/tree/main) widget?

**Comment by bozzio83** [comment]
I second this. Beszel is great and would be a really good addition to homepage.

**Reply by bozzio83** [reply]
There is an option for a widget but I cannot get it to work.
```
         widget:
           type: beszel
           url: http://192.168.1.101:8098/
           username: *****@********.com
           password: ****************************
           systemId: ************ # optional)
```

`API Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` is the error message

Any help on this would be great.
