### DISCUSSION TITLE
OPNsense Widget not working

### DISCUSSION THREAD

**Discussion by tommyguuuun** [gethomepage/homepage#4203] [Support]
### Description

Hi,

when i try to use the OPNsense widget for ne newest version of opnsense, i get an API Error:

```
API Error: HTTP Error
URL: https://IP//api/diagnostics/activity/getActivity
```

When i follow the link to this endpoint:

`{"errorMessage":"Endpoint not found"}`

My guess is, that this has changed with the major update of OPNsense a view months ago.

### homepage version

v0.9.11

### Installation method

Docker

### Troubleshooting

-

**Comment by AlessioCasco** [comment]
Are you sure you set the right parameter `url` correctly ?

Like:
```yaml
widget:
  type: opnsense
  url: http://opnsense.host.or.ip
  username: key
  password: secret
```
