### DISCUSSION TITLE
Proxmox Widget error

### DISCUSSION THREAD

**Discussion by Sp33dFr34k** [gethomepage/homepage#4211] [Support]
### Description

The Proxmox widget shows an error message as per below, unsure why. Running Proxmox version 8.2.7.

### homepage version

v0.9.11 (2245cdd, Oct 15, 2024)

### Installation method

Docker

### Configuration

```yaml
- Proxmox:
        icon: proxmox.png
        href: https://proxmox.domain.com/
        description: Virtualization management
        widget:
          type: proxmox
          url: https://proxmox.domain.com
          username: api@pam!homepage
          password: dbf9635f-6f96-43b4-8bb5-d34e827xxxxx
```

### Container Logs

`error: <credentialedProxyHandler> HTTP Error 403 calling https://proxmox.domain.com/api2/json/cluster/resources`

### Browser Logs

`API Error: Unexpected token '<', "<html>
<h"... is not valid JSON`

### Troubleshooting

- The docker exec ping command works
- The API key works through curl, result:
`{"data":[{"disk":11680247808,"id":"node/pve","type":"node","node":"pve","cgroup-mode":2,"mem":24788910080,"cpu":0.0457943925233645,"maxmem":33533837312,"uptime":1331957,"level":"","maxcpu":8,"status":"online","maxdisk":14753464320}]}`
