### DISCUSSION TITLE
Value translation for Binary sensors from Home Assistant

### DISCUSSION THREAD

**Discussion by sschiphorst** [gethomepage/homepage#4222] [Support]
### Description

I'm trying to get my front door senor to map the values to be open or closed rather than on or off. As you can see below I've tried the remap function but it is still producing a on/off output rather than Open/Closed

### homepage version

v0.9.11

### Installation method

Docker

### Configuration

```yaml
custom:
                - state: binary_sensor.front_door_door 
                  label: Front Door
                  remap:
                    - value: "on"
                      to: "Open"
                    - value: "off"
                      to: "Closed"
```

### Troubleshooting

Have gone through all other threads but still not producing correct result
