### DISCUSSION TITLE
Openmeteo default settings display degrees celsius while displaying "F" for Fahrenheit

### DISCUSSION THREAD

**Discussion by corydodt** [gethomepage/homepage#4224] [Support] [answered]
### Description

The suggested configuration for Openmeteo, from https://gethomepage.dev/widgets/ is the following:

```
- openmeteo:
    label: Current
    latitude: 36.66
    longitude: -117.51
    cache: 5
```

Next I pasted this into widgets.yaml, and changed latitude and longitude to my location. The result was this:

    Current, 7.9°F
    Light Drizzle

(with a drizzle icon).

This is not the correct temp, but I did the conversion and discovered it's actually showing degrees Celsius (metric) by default--not surprising, but it shouldn't display an `F` which is confusing and incorrect. The correct temp would be either `7.9°C` or `46.2°F`.

Adding `units: imperial` to the stanza changes the number shown to the correct temp, still with an `F`. In the documentation, the suggested stanza should probably include a `units` attribute, as well.

I couldn't find an open Issue for this, and it seems like a straightforward bug that I should open a ticket for, but I am creating a discussion first as per guidelines.

### homepage version

v0.9.11

### Installation method

Docker

### Configuration

```yaml
- openmeteo:
    label: Current
    latitude: 36.66
    longitude: -117.51
    cache: 5
```

### Troubleshooting

Adding `units: imperial` to the stanza changes the number shown to the correct temp, still with an `F`. With `units: metric`, it correctly displays a C next to the celsius temperature. This only happens when units are omitted entirely.
