### DISCUSSION TITLE
Hubitat

### DISCUSSION THREAD

**Discussion by goluftwaffe** [gethomepage/homepage#4225] [General]
Someone was looking to how to configure a Custom Widget for Hubitat, so here's a link from to the thread on Discord on how to configure it:

https://discord.com/channels/1019316731635834932/1160104796934656050

Let me know if you need more info!

**Comment by ekalp** [comment]
Thank you!

**Comment by tomm1079** [comment]
i cant get the discord to pull up.  can somone past in the directions?

**Reply by ekalp** [reply]
I can confirm your solution works if you only have singular device in MakerAPI. I did add one of my hubs with all devices URL and selecting the array number to see if it will change over time.

Here is the code snippet for anyone else that would like to leverage it:
```
- Hubitat-Garage:
        icon: hubitat
        href: http://[HUBITAT_CONTROLLER_IP]
        description: Garage Hubitat Controller
        widget:
            type: customapi
            url: http://[HUBITAT_CONTROLLER_IP]/apps/api/[APP_ID]/devices/all?access_token=[TOKEN}
            refreshInterval: 10000
            method: GET
            mappings:
              - field:
                  0:
                    attributes: hubModel
                format: text
                label: Hub Model
              - field:
                  0:
                    attributes: localIP
                label: Hub IP Address
              - field:
                  0:
                    attributes: formattedUptime
                label: Hub Uptime
              - field:
                  0:
                    attributes: firmwareVersionString
                label: Firmware
```
Just update all the entries in the code between the [ ], including removing the brackets.

<@220344403825393664>
