### DISCUSSION TITLE
Auto Discovery Issue

### DISCUSSION THREAD

**Discussion by vikassaini-it** [gethomepage/homepage#4231] [Support]
### Description

I am having issue in docker auto discovery, Its not connecting to service and no status tag is showing. Also homepage logs are saying no label available

<img width="1899" alt="Screenshot 2024-11-01 at 1 00 19 PM" src="https://github.com/user-attachments/assets/db3c0e2a-3a84-4fb0-a722-511c31f8dd51">

Below are details

docker-compose.yaml    <- Of service I deployed, as mentioned in docs I have added labels

```
labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`search.example.com`)"
      - "traefik.http.routers.searxng.entrypoints=web"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
      - "traefik.http.routers.searxng.service=searxng"
      - "traefik.http.routers.searxng.middlewares=auth-middleware"
      - "traefik.http.middlewares.auth-middleware.basicauth.users=aaa:$$apr1aaaa1Z4xEFz0"
      - homepage.group=Applications
      - homepage.name=SearXNG
      - homepage.icon=redis.png
      - homepage.href=https://search.example.com
      - homepage.description=SearXNG engine`
```

services.yaml

```
- Applications:
    - SearXNG:
        icon: searxng.png
        href: https://searxng.example.com/
        server: server-docker`
```
### homepage version

v0.9.11 (2245cdd, Oct 15, 2024)

### Installation method

Docker

### Configuration

setting.yaml

```
# https://gethomepage.dev/latest/configs/settings

title: My Awesome Homepage
theme: dark # <----- add this line
color: slate # <----- add this line
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  docker:
    enabled: true
    discovery: true
    showStats: true

server-docker:
  socket: /var/run/docker.sock
```

### Container Logs

Logged into homepage container and did curl on docker socket to list down labels, this verified container is running as root and able to query socket.
Also I can see homepage labels 

```
curl --unix-socket /var/run/docker.sock http://localhost/containers/json | jq '.[] | {Name: .Names[0], Labels: .Labels | with_entries(select(.key | startswith("homepage")))}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17765    0 17765    0     0  8757k      0 --:--:-- --:--:-- --:--:-- 16.9M
{
  "Name": "/homepage",
  "Labels": {
    "homepage.description": "Homepage dashboard",
    "homepage.group": "Applications",
    "homepage.href": "https://apps.example.com",
    "homepage.icon": "home.png",
    "homepage.name": "Homepage"
  }
}
{
  "Name": "/searxng",
  "Labels": {
    "homepage.description": "SearXNG engine",
    "homepage.group": "Applications",
    "homepage.href": "https://searxng.example.com",
    "homepage.icon": "redis.png",
    "homepage.name": "SearXNG"
  }
}
{
  "Name": "/traefik",
  "Labels": {
    "homepage.description": "Traefik dashboard",
    "homepage.group": "Infrastructure",
    "homepage.href": "https://traefik.example.com",
    "homepage.icon": "traefik.png",
    "homepage.name": "Traefik"
  }
}
```

### Browser Logs

No logs in browser

### Troubleshooting

Logs from homepage container

```Listening on port 3000
[2024-11-01T07:12:02.851Z] debug: <resources> fsSize: [{"fs":"overlay","type":"overlay","size":47321268224,"used":2829733888,"available":44474757120,"use":5.98,"mount":"/","rw":false},{"fs":"/dev/sda1","type":"ext4","size":47321268224,"used":2829733888,"available":44474757120,"use":5.98,"mount":"/config","rw":true}]
[2024-11-01T07:12:02.855Z] debug: No containers were found with homepage labels.
```
