### DISCUSSION TITLE
[Feature Request] Support target for `quicklaunch` built in providers

### DISCUSSION THREAD

**Discussion by chrisjenx** [gethomepage/homepage#4242] [Feature Requests]
### Description

```
quicklaunch:
  searchDescriptions: true
  showSearchSuggestions: true
  target: _self 
  provider: google
```

This doesn't open in self, if I change to custom it works, but I expected this to apply to the google provider
