### DISCUSSION TITLE
NPM widget reporting wrong data

### DISCUSSION THREAD

**Discussion by mathieutreves** [gethomepage/homepage#4255] [Support] [answered]
### Description

The NPM widget works without errors, but it reports an incorrect number for "enabled" and "disabled" proxies, while the "total" one is right. They total one is even correctly updated if I delete or add some proxy, while the other two remains at 0 all the time. There are no errors in the homepage logs.
![Screenshot 2024-11-06 184653](https://github.com/user-attachments/assets/f9fae313-fa2d-433c-8465-2ddb9d04f1e1)

### homepage version

v0.9.11 (2245cdd)

### Installation method

Docker

### Configuration

```yaml
- Nginx Proxy Manager:
        icon: /icons/nginx-proxy-manager.svg
        href: "{{HOMEPAGE_VAR_NPM_ADDRESS}}"
        server: my-docker 
        container: nginx
        widget:
            type: npm
            url: "{{HOMEPAGE_VAR_NPM_DOCKER}}"
            username: "{{HOMEPAGE_VAR_NPM_USERNAME}}"
            password: "{{HOMEPAGE_VAR_NPM_PASSWORD}}"
```

### Troubleshooting

/app # curl -L -k -u 'username:password' http://IP:81/api/nginx/proxy-hosts
{"error":{"code":403,"message":"Permission Denied"}}/app #
