### DISCUSSION TITLE
[Feature Request] TrueNAS widget alert box turn red

### DISCUSSION THREAD

**Discussion by owennewo-dev** [gethomepage/homepage#4262] [Feature Requests] [answered]
### Description

Is there a way to make the `ALERTS` box in the TrueNAS widget (or any widget) to turn red when the number in the `ALERTS` box is more than zero? It would be helpful to be able to check if TrueNAS needs attention at a glance.

![{D01BF390-7194-48D3-B42E-2B29988DF224}](https://github.com/user-attachments/assets/97ca3dd5-0731-4cab-beb4-43ecbf99e768)

**Comment by owennewo-dev** [comment]
@RoboMagus I found this old thread (https://github.com/gethomepage/homepage/discussions/3040) where you shared the solution to making a field change color when the value is greater than zero. I have tried to use your code, but it's not working.

This is what's in my `custom.js` file (with all the unimportant stuff left out of course)

```js
greaterThanZero = (value) => {
  const _v = parseInt(value);
  return _v > 0 && !isNaN(_v);
};

// Map widget 'id' to field number and warning test
var warnWidgets = {
  'TNS':    {'truenas-alerts': 3, 'check': greaterThanZero, 'observer': null },
};
```

I have tried changing `field` to `truenas-alerts` and `alerts` but none of them work. Also I have changed the number following `field` from `1` to `4`. Do you have any idea why it isn't working?

Also I have this is `custom.css`
```css
.warning-widget {
  background-color: hsla(10, 75%, 15%, 0.3) !important;
}
```

**Reply by johnagil** [reply]
I got it to work based on cadeluca's answer in that same thread. If you want it to work for multiple widgets then you would want to figure out how to use RoboMagus's solution.

services.yaml, you have to have id set:
```yaml
- TrueNas Scale:
      id: truenas-scale
      icon: truenas.png
      href: http://192.168.50.50
      ping: http://192.168.50.50
      widget:
        type: truenas
        url: http://192.168.50.50
        key: apikey
        enablePools: true # optional, defaults to false
        nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
```
custom.js, getElementById has to match the id you set in the services.yaml. The children array is [2] because alerts is the third item for me, but in your case it looks like it should be [1]:
```javascript
function createObserver() {
  // calling this on init to get style updated first time
  updateDownSitePanelStatus();

  // select the target node, referencing the id parameter from the service definition
  const downSitePanel = document.getElementById("truenas-scale").querySelector(".service-container").children[2];

  // create an observer instance
  const observer = new MutationObserver(function (mutations) {
    mutations.forEach(function (mutation) {
      if (mutation.type === "characterData") {
        updateDownSitePanelStatus();
      }
    });
  });

  const config = {
    subtree: true,
    characterData: true,
  };

  // pass in the target node and observer options
  observer.observe(downSitePanel, config);
}

function updateDownSitePanelStatus() {
  const downSitePanel = document.getElementById("truenas-scale").querySelector(".service-container").children[2];

  const siteDownCount = parseInt(downSitePanel.children[0].textContent);

  if (siteDownCount > 0) {
    if (!downSitePanel.classList.contains("down-bg")) {
      downSitePanel.classList.add("down-bg");
    }
  } else {
    if (downSitePanel.classList.contains("down-bg") || isNaN(siteDownCount)) {
      downSitePanel.classList.remove("down-bg");
    }
  }
}

setTimeout(createObserver, 1000); // band-aid, use as needed - sometimes would fire too early without the timeout
//createObserver();
```

custom.css:
```css
.down-bg {
  background: #802a2a !important; /* this color works for my homepage theming, chances are you'll want to change it */
  /* I have this css transition code uncommented in mine, just personal preference */
  /* -webkit-transition: all 0.2s linear;
  -moz-transition: all 0.2s linear;
  -o-transition: all 0.2s linear;
  transition: all 0.2s linear; */
}
```

**Reply by owennewo-dev** [reply]
Thank you John! I have used your code and it works. But only with the default fields...
![image](https://github.com/user-attachments/assets/1977bdef-f6ad-4544-bce5-199e7fad8e70)
I have tried all the numbers and even `truenas-alerts` and `alerts` in the box. Also I tried those words with quotes on the ends.

**Reply by johnagil** [reply, marked as answer]
What does your services.yaml look like? Mine works with custom fields, I assume based on your initial post you just want uptime and alerts.

```yaml
- TrueNas Scale:
        id: truenas-scale
        icon: truenas.png
        href: http://192.168.50.50
        ping: http://192.168.50.50
        widget:
          type: truenas
          fields: ["uptime", "alerts"]
          url: http://192.168.15.15
          key: apikey
          enablePools: true # optional, defaults to false
          nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
```

![image](https://github.com/user-attachments/assets/eea69730-82fb-40ab-9e7b-dc001bed4eaf)

Here's my custom.js with two fields, I changed children[2] to children[1] since alerts is the second field.

Edit: Don't change this line, keep it at 0: `const siteDownCount = parseInt(downSitePanel.children[0].textContent);`. Only change the children referencing getElementById based on where the alerts field is located.
```javascript
function createObserver() {
  // calling this on init to get style updated first time
  updateDownSitePanelStatus();

  // select the target node, referencing the id parameter from the service definition
  const downSitePanel = document.getElementById("truenas-scale").querySelector(".service-container").children[1];

  // create an observer instance
  const observer = new MutationObserver(function (mutations) {
    mutations.forEach(function (mutation) {
      if (mutation.type === "characterData") {
        updateDownSitePanelStatus();
      }
    });
  });

  const config = {
    subtree: true,
    characterData: true,
  };

  // pass in the target node and observer options
  observer.observe(downSitePanel, config);
}

function updateDownSitePanelStatus() {
  const downSitePanel = document.getElementById("truenas-scale").querySelector(".service-container").children[1];

  const siteDownCount = parseInt(downSitePanel.children[0].textContent);

  if (siteDownCount > 0) {
    if (!downSitePanel.classList.contains("down-bg")) {
      downSitePanel.classList.add("down-bg");
    }
  } else {
    if (downSitePanel.classList.contains("down-bg") || isNaN(siteDownCount)) {
      downSitePanel.classList.remove("down-bg");
    }
  }
}

setTimeout(createObserver, 1000); // band-aid, use as needed - sometimes would fire too early without the timeout
//createObserver();
```
