### DISCUSSION TITLE
Rogue/Unkown App

### DISCUSSION THREAD

**Discussion by daedric7** [gethomepage/homepage#4271] [Support]
### Description

I can't really understand where this app is coming from. Homepage seems to believe it's part of the .yamls. I've tried to search discussions and issues but if anything exists i missed it

Screenshot:

![image](https://github.com/user-attachments/assets/00bea4f9-b9dc-4b82-ab98-e42e0437987c)

Section of that .yaml:

```
- Apps:
    - NextCloud:
        href: https://nextcloud.aguiarvieira.pt
        server: my-docker
        container: nextcloud
        icon: nextcloud.png
        siteMonitor: https://nextcloud.aguiarvieira.pt
        description: A safe home for all your data.
        widget:
          type: nextcloud
          url: https://nextcloud.aguiarvieira.pt
          username: 'admin'
          password: Teste-1234
...
...
...
```

I've tried to:

```
for f in ` ls *.yaml`  ; do echo $f ; cat $f | grep -i lounge ; done

```

The Lounge does popup, but in the expected section:

```
bookmarks.yaml
docker.yaml
kubernetes.yaml
services.yaml
    - TheLounge:
        description: The Lounge is a self-hosted web IRC client for the modern world.
        container: thelounge
        icon: thelounge.png
settings.yaml
widgets.yaml
```

Which is:

```
- Social:
....
....
....
    - TheLounge:
        href: https://irc.server
        description: The Lounge is a self-hosted web IRC client for the modern world.
        server: my-docker # The docker server that was configured
        container: thelounge
        icon: thelounge.png
        siteMonitor: https://irc.server

```

![image](https://github.com/user-attachments/assets/88d681b0-cbdd-4406-96fa-332062ab8198)

### homepage version

v0.9.11 (2245cdd, Oct 15, 2024)

### Installation method

Docker

### Troubleshooting

I tried to add The Lounge were it stands in the screenshot, it got duplicated.
I tried to rename the section, no results.
The troubleshooting tests are really not related to this issue...
