### DISCUSSION TITLE
Get 5 column layout

### DISCUSSION THREAD

**Discussion by Fernando-Checa** [gethomepage/homepage#4274] [Support]
### Description

I'm new to homepage and I'd like to have 5 columns in my services.
Out of the box, it creates 4 columns like this

![CleanShot 2024-11-11 at 12 12 41](https://github.com/user-attachments/assets/a13dab48-946d-4b60-b176-6b96c2bfe873)

But as soon as I introduce the '`fivecolumns: true`' in settings.yaml everything stops working as expected

![CleanShot 2024-11-11 at 12 16 11](https://github.com/user-attachments/assets/961002fd-0c22-42ef-99f1-469bc23cfb42)

If I introduce '`style: row`' and '`columns: 5`' it makes each group 5 columns but that is not what I need

![CleanShot 2024-11-11 at 12 17 49](https://github.com/user-attachments/assets/4c67daba-725f-428d-8364-d28d3ee419b8)

How can I make it so each group is vertical and there are 5 groups in. a row?

Thanks in advance

### homepage version

c0.9.11

### Installation method

Docker

### Troubleshooting

-

**Comment by owennewo-dev** [comment]
They need to be set as `style: column` and `columns: 1` to get all five next to each other.
This is what you need to put in your `settings.yaml` file. Make sure the names match up with the names of your groups in your `services.yaml` files.
```
  Homelab:
    style: column
    columns: 1
    header: false (optional, I like how it looks without the header)
  Domotica:
    style: column
    columns: 1
    header: false
  Media:
    style: column
    columns: 1
    header: false
  Apps:
    style: column
    columns: 1
    header: false
  Database:
    style: column
    columns: 1
    header: false
```

**Comment by Fernando-Checa** [comment]
This is what I get with your yaml.
Not what I was expecting from the 1 column setting...

![CleanShot 2024-11-11 at 18 40 17](https://github.com/user-attachments/assets/bed48ca4-f347-4ce0-a49c-2da746f537df)

**Reply by owennewo-dev** [reply]
Can you share all the code in your `services.yaml` and `settings.yaml` files?

**Comment by Fernando-Checa** [comment]
sure.. here it is:

```---
headerStyle: boxedWidgets
disableCollapse: false
fivecolumns: true
#useEqualHeights: true

layout:  
    HOMELAB:
      style: column
      columns: 1
      header: false
    DOMOTICA:
      style: column
      columns: 1
      header: false
    MEDIA:
      style: column
      columns: 1
      header: false
    APPS:
      style: column
      columns: 1
      header: false
    DATABASE:
      style: column
      columns: 1
      header: false
```

```
---

- HOMELAB:
    - Proxmox:
        id: col-med
        href: https://proxmox.lab.es
        icon: proxmox.png
        description: datacenter
        siteMonitor: https://proxmox.lab.es
        widget:
            type: proxmox
            url: https://proxmox.lab.es
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
    - TrueNAS Scale:
        id: col-med
        href: https://truenas.lab.es/
        icon: truenas-scale.png
        description: nas
        siteMonitor: https://truenas.lab.es/
        widget:
            type: truenas
            url: https://truenas.lab.es/
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: false
    - Netdata:
        href: https://netdata.lab.es/spaces
        icon: netdata.png
        description: proxmox
        widget:
            type: netdata
            url: https://netdata.lab.es
    - Pi-Hole:
        href: https://pi-hole.lab.es/admin/
        icon: /icons/Pi-hole_Logo.png
        description: jupiter
        widget:
            type: pihole
            url: https://pi-hole.lab.es/admin
            version: 5 # required if running v6 or higher, defaults to 5
            key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Uptime Kuma:
        href: https://kuma.lab.es
        icon: /icons/kuma.svg
        description: jupiter
    - Portainer:
        id: col-small
        href: https://portainer.lab.es
        icon: portainer.png
        description: europa
    - Gitea:
        id: col-small
        href: https://gitea.lab.es/
        icon: gitea.png
    - SyncThing:
        id: col-small
        href: https://syncthing.lab.es/
        icon: syncthing.png
        description: truenas
    - FileBrowser:
        href: https://files.lab.es/
        icon: /icons/filebrowser.png
        description: truenas
    - Proxmox Backup Server:
        href: https://pbs.lab.es/
        icon: /icons/proxmox.png


    

- DOMOTICA:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- MEDIA:
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.lab.es/
        description: Series management
    - Radarr:
        icon: radarr.png
        href: https://radarr.lab.es/
        description: Movie management
    - Overseerr:
        href: https://overs.lab.es/
        icon: /icons/overseerr.svg
        description: Media Discovery
    - Plex:
        icon: plex.png
        href: https://plex.lab.es/
        description: Media Server
    - Transmission:
        href: https://transmission.lab.es/
        icon: transmission
    - AudioBookshelf:
        icon: /icons/book1.svg
        href: https://books.lab.es/
        description: audio books


- APPS:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- DATABASE:
    - InfluxDB:
        href: https://influx.lab.es/
        icon: influxdb.png
        description: inklux 2
          
```
