### DISCUSSION TITLE
Is it possbile to embed code for a spotify playlist on homepage?

### DISCUSSION THREAD

**Discussion by shadowaero** [gethomepage/homepage#4276] [Support]
### Description

I would like to have a few embedded playlists on my home page.  They look like this.  Is this possible?  What are the steps if its possbile?

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4YKmPktqsGEthBvqDHDXs1?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

### homepage version

it says latest

### Installation method

Docker

### Troubleshooting

tried adding to bookmarks but obviously not setup for embedding.

**Comment by owennewo-dev** [comment]
Try pasting `https://open.spotify.com/embed/playlist/4YKmPktqsGEthBvqDHDXs1?utm_source=generator` into an iFrame widget.
You can find info on the iFrame widget here: https://gethomepage.dev/widgets/services/iframe/

Try pasting this 👇 into your `services.yaml` file
```
- Group: 
   - Spotify:
        widget:
          type: iframe
          name: Spotify
          src: https://open.spotify.com/embed/playlist/4YKmPktqsGEthBvqDHDXs1?utm_source=generator
```
