### DISCUSSION TITLE
Widgets not displaying properly

### DISCUSSION THREAD

**Discussion by timkerekes** [gethomepage/homepage#4280] [Support]
### Description

After messing with the openmeteo config to see if I could get it working, I clicked on the _**Current Location - Click to allow**_ button on the webpage.

From there all sorts of things started to go wrong... It seems there were some issues with the docker socket, as I was getting errors like I posted below.

This was most likely due to an update I made to DSM, as I am running Homepage in a docker container on my Synology NAS. There was somehow no longer a docker group on the machine, and my admin user may not have had rights to /var/run/docker.sock

After some troubleshooting and updating to the newest version of Homepage (v0.9.12), I was able to get things to render again, and stop all the errors in the logs.

However, all of my Widgets are now not loading for some reason... and I am getting this debug message in my logs (not sure if it's relevant) `debug: No containers were found with homepage labels.`

I'm not sure what's going on. I've tried troubleshooting with curl on all my services like Portainer, etc. and am getting back good responses.

Any help would be appreciated! I've included my widgets.yaml and services.yaml below. (The indenting may be off from my copy paste due to a yaml formatting plugin I have installed in VSCode, but it is valid yaml)

Here's a picture for reference:
![homepage-dashboard](https://github.com/user-attachments/assets/57fb4927-c82a-4583-91ed-1099d05bdba6)

### homepage version

v0.9.12

### Installation method

Docker

### Configuration

```yaml
widgets.yaml
---
- logo:
  icon: /icons/my-image.ico

- greeting:
  text_size: xl
  text: Welcome to Homepage

- resources:
  label: Uptime
  uptime: true

- resources:
  label: CPU
  cpu: true

- resources:
  label: Memory
  memory: true

- resources:
  label: Storage
  disk: /

- openmeteo:
  latitude: -0.01
  longitude: -0.01
  timezone: TZ
  units: imperial
  cache: 5
  format:
          maximumFractionDigits: 1

- datetime:
  locale: us
  format:
          dateStyle: long
          timeStyle: long


services.yaml
---
- Homelab Services:
          - Homepage:
            icon: homepage
            href: http://ip:port
            description: This Dashboard
            server: homepage
            container: homepage
            showStats: true

          - Pihole:
            icon: pi-hole
            href: http://ip/admin/index.php
            description: Block all the Ads
            widget:
                    type: pihole
                    url: http://ip
                    version: 6
                    key: xxxxx

          #   - Heimdall:
          #     icon: heimdall-light
          #     href: https://192.168.50.20:8443/tag/home-network
          #     description: Homelab Dashboard v1
          #     server: heimdall
          #     container: Heimdall
          #     showStats: true

          - Jenkins:
            icon: jenkins
            href: http://ip:port
            description: Jenkins Server
            server: dockerhost
            container: jenkins
            showStats: true

          - Portainer:
            icon: portainer
            href: https://ip:port/#!/2/docker/dashboard
            description: dockerhost
            widget:
                    type: portainer
                    url: https://ip:port
                    env: 2
                    key: xxxx

- Media:
          - Plex:
            icon: plex
            href: http://ip:port/
            description: Plex
            widget:
                    type: plex
                    url: http://ip:port
                    key: xxxxx

- Games:
          - Minecraft:
            icon: minecraft
            widget:
                    type: minecraft
                    url: udp://ip:port

          - Creative_Minecraft:
            icon: minecraft
            widget:
                    type: minecraft
                    url: udp://ip:port
```

### Container Logs

`error: <dockerStatusService> TypeError: Cannot read properties of null (reading 'conn')`

```
error: <service-helpers> Error getting services from Docker server 'portainer': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
```

`debug: No containers were found with homepage labels.`

### Troubleshooting

Not really sure what else to add here. But here's what I've done:

- Updated Homepage version
- Tested pinging services from Homepage container with curl successfully
