### DISCUSSION TITLE
Beszel Widget TypeError: d.items is undefined

### DISCUSSION THREAD

**Discussion by Makifun** [gethomepage/homepage#4285] [Support] [answered]
### Description

I am getting "TypeError: d.items is undefined" when using the Beszel widget. I have tried using systemId and without systemId, still getting the same error. Also tried changing my password and using username/email. Same error.

Any clues what this might be?

I have 3 extra mounts(sda2, sdb, sdc) on my beszel-agent(also running in docker) if that is why it is freaking out?

![image](https://github.com/user-attachments/assets/3edfdace-531c-470d-b326-187e143b1a14)

### homepage version

v0.9.12

### Installation method

Docker

### Configuration

```yaml
- Beszel:
        icon: /images/beszel.svg
        href: https://beszel.domain.tld
        server: jonny
        container: beszel
        widget:
            type: beszel
            url: https://beszel.domain.tld
            username: username
            password: password
```

### Container Logs

[2024-11-12T18:30:38.725Z] debug: <beszelProxyHandler> HTTTP 400 logging into npm api: [object Object]

### Troubleshooting

My homepage container is able to ping and curl my beszel instance(Traefik is in front of it). Debug only mentions one line(HTTTP with three Ts btw) 400 error.
