### DISCUSSION TITLE
Config files not working with read-only file system.

### DISCUSSION THREAD

**Discussion by jmigual** [gethomepage/homepage#4291] [Support] [answered]
### Description

So, I have the following config:

```yaml
  dashboard:
    container_name: dashboard
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    networks:
      - proxy-net
      - outside
    volumes:
      - ./config/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - ./config/homepage/docker.yaml:/app/config/docker.yaml:ro
      - ./config/homepage/services.yaml:/app/config/services.yaml:ro
      - ./config/homepage/settings.yaml:/app/config/settings.yaml:ro
      - ./config/homepage/widgets.yaml:/app/config/widgets.yaml:ro
      - ./data/dashboard2:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    environment:
      - PGID=996
      - PUID=1001
    group_add:
      - "996" # docker group
 ```

The problem is that homepage tries to chown the yaml files. Why does it need to chown them? Isn't reading them enough?

I was trying to do this because I'd like to have these files in git. I could work with another option if it also lets me have the files commited in git. If possible, I'd like to avoid copying the files from and to git every time I make a change.

### homepage version

v0.9.12 (794ec12, Nov 11, 2024)

### Installation method

Docker

### Container Logs

dashboard  | chown: /app/config/bookmarks.yaml: Read-only file system
dashboard  | chown: /app/config/settings.yaml: Read-only file system
dashboard  | chown: /app/config/docker.yaml: Read-only file system
dashboard  | chown: /app/config/services.yaml: Read-only file system
dashboard  | chown: /app/config/widgets.yaml: Read-only file system
dashboard  | chown: /app/config/bookmarks.yaml: Read-only file system

### Troubleshooting

Not needed
