### DISCUSSION TITLE
[Feature Request] Nested responsive layouts with duplicate titles

### DISCUSSION THREAD

**Discussion by Karmalakas** [gethomepage/homepage#4292] [Feature Requests]
### Description

My proposal is quite simple, but gives full flexibility to layout things however you want

---

First - duplicate titles. It would be great if section keys could actually be keys in the config and you could set a title.

Example `services.yaml`:
```yaml
- section_1:
    - widget_1:
        title: My widget
        icon: si-widget
        href: https://example.com
    - widget_2:
        title: My widget
        icon: si-widget
        href: https://example.com
- section_2:
    - widget_3:
        title: My widget
        icon: si-widget
        href: https://example.com
``` 

Then in `settings.yaml`:
```yaml
layout:
  section_1:
    title: Duplicate section
    style: row
    columns: 4
  section_2:
    title: Duplicate section
    style: row
```

If section `title` is missing, use the key value. As a bonus, would be nice to be able to hide widget titles

I believe this should not even be a breaking change

---

Secondly - the layout itself...

My proposal would allow to get rid of `columns` & `row` options and leave only `sstyle` (in my examples I use `type`). It would be fully responsive with flexbox. For example, such configs

```yaml
# settings.yaml
layout:
  container_holder_01:
    type: row # [column|row] - deafult: column
    containers:
      container_01:
        title: Container 01
        sections:
          section_01:
            title: Duplicate
            # type: column
          section_02:
      container_02:
        title: Container 02
        sections:
          section_03:
            title: Duplicate
            type: row # [column|row] - deafult: column
      container_03:
        type: row # [column|row] - deafult: column
        sections:
          section_04:
          section_05:
  container_holder_02:
    type: row
    sections:
      bookmark_section_01:
      bookmark_section_02:
        type: row
      bookmark_section_03:
  container_holder_03:
    # type: column
    sections:
      section_06:
        title: Duplicate
        # type: column
      section_07:
      section_08:
```

```yaml
# services.yaml
- section_01:
    - Widget 1:
    - Widget 2:
- section_02:
    - Widget 3:
    - Widget 4:
- section_03:
    - Widget 5:
    - Widget 6:
- section_04:
    - Widget 7:
    - Widget 8:
- section_05:
    - Widget 9:
    - Widget 10:
- section_06:
    - Widget 1:
    - Widget 2:
- section_07:
    - Widget 3:
    - Widget 4:
- section_08:
    - Widget 5:
    - Widget 6:
```

```yaml
# bookmarks.yaml
- bookmark_section_01:
    - Book 1:
        - abbr: BM1
          href: https://example.com/01
    - Book 2:
        - abbr: BM2
          href: https://example.com/02

- bookmark_section_02:
    - Book 3:
        - abbr: BM3
          href: https://example.com/03
    - Book 4:
        - abbr: BM4
          href: https://example.com/04

- bookmark_section_03:
    - Book 5:
        - abbr: BM5
          href: https://example.com/05
    - Book 6:
        - abbr: BM6
          href: https://example.com/06
```

Only containers are allowed on the layout root level. Containers then may containe either other containers or sections. The above layout with services and bookmarks configs would render something like this:
![image](https://github.com/user-attachments/assets/5d658568-da4e-4b6f-a87b-4dd5bfee87b1)

Layout parsing type maybe could be defined in the `settings.yaml`:
```yaml
layout_parse_method: nested # [legacy|nested] - default: legacy
```

Relatively unlimited nesting would open doors for any layout you could imagine. Even `tabs` could be implemented there (basically same as containers, just rendered differently):
```yaml
layout:
  container_holder_01:
    type: row # [column|row] - deafult: column
    title: Main holder
    containers:
      container_01:
        title: Container with tabs
        tabs:
          tab_01:
            title: Tab 1
            type: row
            sections:
              section_01:
              section_02:
          tab_02:
            title: Tab 2
            sections:
              section_03:
      container_02:
        title: Container 02
        sections:
          section_03:
            title: Duplicate
            type: row
```

### Other

If I want to have the same section title in services and in bookmarks, currently it's impossible to change the layout for both

Also, currently layout documentation is lacking to say the least. I find bits and pieces all over about tabs and containers, but no clear examples (or in `container` case not even a documentation itself exists) how it would look like. There are also no examples beyond the very basic ones how to set more complex rows and columns... For example, I couldn't even find a way how to set two service secions in one row and then three bookmarks section in the second row 🤷‍♂️ 

I've done this before. If you need a piece of a sample code (basically recursive function), I could try to extract it from my project
