### DISCUSSION TITLE
Upgrading to Glances v4 gives API errors

### DISCUSSION THREAD

**Discussion by gleneccles** [gethomepage/homepage#4293] [Support] [answered]
### Description

So when I run Glances v3.4.0.5-full I am able to load CPU, memory, disk, etc. just fine in Homepage. I upgrade to Glances 4 (latest-full) and I get the below error. I have version: 4 in my homepage config. I have tried various ways of setting up Homepage but none of them seem to fix this.

```
[2024-11-14T02:07:58.325Z] error: <glances> HTTP 404 getting data from glances API. Data: 
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 404 Not Found</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 404 Not Found</h1>
            <p>Sorry, the requested URL <tt>&#039;http://192.168.50.216:61208/api/4/cpu&#039;</tt>
               caused an error:</p>
            <pre>File does not exist.</pre>
        </body>
    </html>
```

Here is my homepage config (two ways of trying):
```
# - glances:
#     url: http://192.168.50.226:61208
#     version: 4 # required only if running glances v4 or higher, defaults to 3
#     cpu: true # optional, enabled by default, disable by setting to false
#     mem: true # optional, enabled by default, disable by setting to false
#     cputemp: true # disabled by default
#     expanded: true # show the expanded view
#     label: Homelab Status # optional
#     units: imperial # only used by cpu temp
```

and

```
- Glances:    
    - CPU:
        icon: https://nicolargo.github.io/glances/public/images/glances.png
        href: "http://192.168.50.226:61208"
        description: Monitoring
        widget:
            type: glances
            url: http://192.168.50.226:61208
            metric: cpu
            version: 4
```

### homepage version

v0.9.12 (794ec12, Nov 10, 2024)

### Installation method

Docker

### Configuration

```yaml
Here is my homepage config (two ways of trying):

# - glances:
#     url: http://192.168.50.226:61208
#     version: 4 # required only if running glances v4 or higher, defaults to 3
#     cpu: true # optional, enabled by default, disable by setting to false
#     mem: true # optional, enabled by default, disable by setting to false
#     cputemp: true # disabled by default
#     expanded: true # show the expanded view
#     label: Homelab Status # optional
#     units: imperial # only used by cpu temp
```

and

```
- Glances:    
    - CPU:
        icon: https://nicolargo.github.io/glances/public/images/glances.png
        href: "http://192.168.50.226:61208"
        description: Monitoring
        widget:
            type: glances
            url: http://192.168.50.226:61208
            metric: cpu
            version: 4
```
```


### Container Logs

[2024-11-14T02:14:04.147Z] error: <glances> HTTP 404 getting data from glances API. Data: 

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

    <html>

        <head>

            <title>Error: 404 Not Found</title>

            <style type="text/css">

              html {background-color: #eee; font-family: sans;}

              body {background-color: #fff; border: 1px solid #ddd;

                    padding: 15px; margin: 15px;}

              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}

            </style>

        </head>

        <body>

            <h1>Error: 404 Not Found</h1>

            <p>Sorry, the requested URL <tt>&#039;http://192.168.50.216:61208/api/4/cpu&#039;</tt>

               caused an error:</p>

            <pre>File does not exist.</pre>

        </body>

    </html>

[2024-11-14T02:14:04.607Z] error: undefined

[2024-11-14T02:14:06.812Z] error: undefined

[2024-11-14T02:14:06.813Z] error: undefined

[2024-11-14T02:14:06.813Z] error: undefined

[2024-11-14T02:14:06.814Z] error: undefined

[2024-11-14T02:14:06.815Z] error: undefined

### Browser Logs

_No response_

### Troubleshooting

I have tried various versions and combinations of things. Basically, as soon as I go to version 4 of Glances (any of the version 4) it does not work with Homepage.

The API call to Glances directly is returning data and looks fine. The UI for Glances shows all of the data and looks fine. This returns data: http://192.168.50.226:61208/api/4/cpu

It seems like Homepage is calling the API incorrectly. I don't know if it is an encoding problem or if the error in the log looks normal (and should be encoded).

**Comment by shamoon** [comment]
> href: "http://192.168.50.226:61208"

should be

`href: http://192.168.50.226:61208`

**Reply by gleneccles** [reply]
I appreciate the attempt, but the href parameter only controls the URL that I am directed to when I click on the widget.

I did try what you said regardless and the widget does not load still and gives the same error in the logs.

**Reply by shamoon** [reply]
Oh yea sorry I was looking in the wrong spot.

please follow the steps from the troubleshooting guide carefully and post the output

**Reply by gleneccles** [reply]
thank you, @shamoon I figured it out, but not sure what is different because it is the same config as I have above (the commented out one)

**Comment by gleneccles** [comment, marked as answer]
Well, I got it working with this which is literally the same as above so no idea what other magic happened.

- glances:
    url: http://192.168.50.226:61208
    version: 4 # required only if running glances v4 or higher, defaults to 3
    cpu: true # optional, enabled by default, disable by setting to false
    mem: true # optional, enabled by default, disable by setting to false
    cputemp: true # disabled by default
    expanded: true # show the expanded view
    label: Homelab Status # optional
    units: imperial # only used by cpu temp

For some reason, this is not rendering the graphs that I see from others but at least it works. I will figure out the graphs a different way.

**Reply by owennewo-dev** [reply]
You can't get the graphs to work? You need something like this in your `services.yaml` to get graphs.
```yaml
- Glances:
    - CPU:
        widget:
          type: glances
          url: http://server-ip:port
          metric: cpu
          version: 4
    - CPU Temp:
        widget:
          type: glances
          url: http://server-ip:port
          metric: sensor:Package id 0
          version: 4
    - RAM:
        widget:
          type: glances
          url: http://server-ip:port
          metric: memory
          version: 4
    - Network:
        widget:
          type: glances
          url: http://server-ip:port
          metric: network:eth0
          version: 4
    - Boot Drive:
        widget:
          type: glances
          url: http://server-ip:port
          metric: disk:sdb
          version: 4
    - Mirrored Drive 1:
        widget:
          type: glances
          url: http://server-ip:port
          metric: disk:sdc
          version: 4
    - Mirrored Drive 2:
        widget:
          type: glances
          url: http://server-ip:port
          metric: disk:sda
          version: 4
```
