### DISCUSSION TITLE
Why is my Grafana service showing as "not found"?

### DISCUSSION THREAD

**Discussion by mrsimonemms** [gethomepage/homepage#4297] [General]
My Grafana showing as "not found", but the service is working fine and the auto-discovered link is working too. Can someone explain where the status comes from please?

![image](https://github.com/user-attachments/assets/ad9e7e7b-5b61-4994-8641-d93aede2082e)

The ingress has the following annotations:
```yaml
annotations:
  kubernetes.io/tls-acme: "true"
  cert-manager.io/cluster-issuer: letsencrypt
  gethomepage.dev/description: Grafana Dashboards
  gethomepage.dev/enabled: "true"
  gethomepage.dev/group: Cluster Management
  gethomepage.dev/icon: grafana
  gethomepage.dev/name: Grafana
```

The ArgoCD ingress is working fine and configured similarly:
```yaml
annotations:
  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  nginx.ingress.kubernetes.io/backend-protocol: HTTP
  kubernetes.io/tls-acme: "true"
  cert-manager.io/cluster-issuer: letsencrypt
  gethomepage.dev/description: Get stuff done with Kubernetes!
  gethomepage.dev/enabled: "true"
  gethomepage.dev/group: Cluster Management
  gethomepage.dev/icon: argocd
  gethomepage.dev/name: ArgoCD
```

If there is some documentation which explains the nuances of the status, I've not been able to find it - if there is some, please point me in the right direction.
