### DISCUSSION TITLE
Initial launch displays wrong layout and theme

### DISCUSSION THREAD

**Discussion by dataprolet** [gethomepage/homepage#4299] [Support]
### Description

When I open Homepage for the first time in a fresh browser sessions the layout is sometimes wrong (rows instead of columns) and the color theme is also wrong (dark instead of light). After refreshing the page it fixes itself.

### homepage version

v0.9.12 (794ec12, Nov 11, 2024)

### Installation method

Docker

### Configuration

```yaml
theme: light

fiveColumns: true

layout:
  Server:
    style: row
    columns: 5
```

### Container Logs

Nothing of interest in the logs except an error for an offline device that can't be reached, which is expected.

### Troubleshooting

Not sure what to do. I already restarted the container, the logs are useless.
