### DISCUSSION TITLE
Beszel widget help

### DISCUSSION THREAD

**Discussion by bozzio83** [gethomepage/homepage#4303] [Support] [answered]
There is an option for a widget but I cannot get it to work.
```
         widget:
           type: beszel
           url: http://192.168.1.101:8098/
           username: *****@********.com
           password: ****************************
           systemId: ************ # optional)
```

`API Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` is the error message

Any help on this would be great.
