### DISCUSSION TITLE
Can't get Custom CSS/JS to apply to anything

### DISCUSSION THREAD

**Discussion by sUBFUSC96** [gethomepage/homepage#4308] [Support] [answered]
### Description

I can't get custom CSS and JS to apply changes to Homepage. Even the most simple changes like the following lead to no results:

`document.body.style.backgroundColor = "red";`

Changes applied to both custom.css and custom.js trigger the page reload, so the application seems to be aware that there were changes added.

Am I missing something? I haven't found any discussion or issue entries on this.

### homepage version

v0.9.12 (794ec12, Nov 11, 2024)

### Installation method

Docker

### Configuration

```yaml
Here is my settings.yaml if that is somehow relevant:

---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homelab Dashboard
color: zinc
useEqualHeights: true
disableCollapse: true
hideErrors: true
headerStyle: boxed
favicon: /images/dashboard.ico

layout:
  Irrigation Data:
    style: row
    columns: 1
  Irrigation View:
    header: false
    style: row
    columns: 3
  Finance:
    style: row
    columns: 2
  Delivery Tracking:
    style: row
    columns: 1
  Server:
    style: row
    columns: 2
  Power:
    style: row
    columns: 2
  Networking:
    style: row
    columns: 3
  Container Management:
    style: row
    columns: 2
  Media:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 5
  Private Services:
    style: row
    columns: 2
  Internal Infrastructure:
    style: row
    columns: 3
  Third-Party Interfaces:
    style: row
    columns: 3
  Bookmarks:
    style: row
    columns: 5
```

### Container Logs

[2024-11-19T08:37:12.433Z] error: <credentialedProxyHandler> HTTP Error 500 calling
OBFUSCATEDURL

[2024-11-19T08:37:47.763Z] error: <httpProxy> Error calling OBFUSCATEDURL

[2024-11-19T08:37:47.764Z] error: <httpProxy> [

  500,

  Error: getaddrinfo EAI_AGAIN OBFUSCATEDURL

      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {

    errno: -3001,

    code: 'EAI_AGAIN',

    syscall: 'getaddrinfo',

    hostname: OBFUSCATEDURL

  }

]

[2024-11-19T08:42:26.830Z] error: <httpProxy> Error calling OBFUSCATEDURL

[2024-11-19T08:42:26.832Z] error: <httpProxy> [

  500,

  Error: getaddrinfo EAI_AGAIN OBFUSCATEDURL

      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {

    errno: -3001,

    code: 'EAI_AGAIN',

    syscall: 'getaddrinfo',

    hostname: OBFUSCATEDURL

  }

]

[2024-11-19T08:42:26.832Z] error: <credentialedProxyHandler> HTTP Error 500 calling OBFUSCATEDURL

[2024-11-19T08:51:03.300Z] error: undefined

[2024-11-19T08:51:13.376Z] error: undefined

[2024-11-19T08:51:28.406Z] error: undefined

[2024-11-19T08:52:33.873Z] error: <httpProxy> Error calling OBFUSCATEDURL

[2024-11-19T08:52:33.874Z] error: <httpProxy> [

  500,

  Error: read ECONNRESET

      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

    errno: -104,

    code: 'ECONNRESET',

    syscall: 'read'

  }

]

[2024-11-19T08:52:33.874Z] error: <credentialedProxyHandler> HTTP Error 500 calling OBFUSCATEDURL

[2024-11-19T08:52:47.665Z] error: <httpProxy> Error calling OBFUSCATEDURL

[2024-11-19T08:52:47.665Z] error: <httpProxy> [

  500,

  Error: read ECONNRESET

      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

    errno: -104,

    code: 'ECONNRESET',

    syscall: 'read'

  }

]

[2024-11-19T08:52:47.666Z] error: <credentialedProxyHandler> HTTP Error 500 calling OBFUSCATEDURL

[2024-11-19T08:57:37.489Z] error: <httpProxy> Error calling OBFUSCATEDURL

[2024-11-19T08:57:37.490Z] error: <httpProxy> [

  500,

  Error: read ECONNRESET

      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

    errno: -104,

    code: 'ECONNRESET',

    syscall: 'read'

  }

]

[2024-11-19T08:57:37.491Z] error: <credentialedProxyHandler> HTTP Error 500 calling OBFUSCATEDURL
[2024-11-19T08:57:48.209Z] error: <httpProxy> Error calling OBFUSCATEDURL

[2024-11-19T08:57:48.209Z] error: <httpProxy> [

  500,

  Error: read ECONNRESET

      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

    errno: -104,

    code: 'ECONNRESET',

    syscall: 'read'

  }

]

[2024-11-19T08:57:48.209Z] error: <plexProxyHandler> HTTP 500 communicating with OBFUSCATEDAPP. Data: [object Object]

[2024-11-19T08:57:48.210Z] error: undefined

[2024-11-19T08:58:03.601Z] error: <httpProxy> Error calling OBFUSCATEDURL

[2024-11-19T08:58:03.601Z] error: <httpProxy> [

  500,

  Error: read ECONNRESET

      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

    errno: -104,

    code: 'ECONNRESET',

    syscall: 'read'

  }

]

[2024-11-19T08:58:03.601Z] error: <credentialedProxyHandler> HTTP Error 500 calling OBFUSCATEDURL

[2024-11-19T08:58:44.561Z] error: <httpProxy> Error calling OBFUSCATEDURL
[2024-11-19T08:58:44.561Z] error: <httpProxy> [

  500,

  Error: read ECONNRESET

      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

    errno: -104,

    code: 'ECONNRESET',

    syscall: 'read'

  }

]

[2024-11-19T08:58:44.562Z] error: <credentialedProxyHandler> HTTP Error 500 calling OBFUSCATEDURL

Listening on port 3000

### Browser Logs

moment_wrapper.ts:108 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: Delivery successful., _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (OBFUSCATEDURL.js:624:3)
    at an (OBFUSCATEDURL.js:624:25647)
    at un (OBFUSCATEDURL.js:624:29355)
    at aa (OBFUSCATEDURL.js:624:29221)
    at on (OBFUSCATEDURL.js:624:28938)
    at sa (OBFUSCATEDURL.js:624:29715)
    at Function.H [as utc] (OBFUSCATEDURL.js:621:975)
    at d (OBFUSCATEDURL.js:1:4587)
    at OBFUSCATEDURL.js:1:31226
    at Object.display (OBFUSCATEDURL.js:1:42371)

### Troubleshooting

Setting the LOG_LEVEL to debug did not result in more useful logs.
