### DISCUSSION TITLE
"API Error Information" alternative message?

### DISCUSSION THREAD

**Discussion by X500658** [gethomepage/homepage#4309] [Support]
### Description

Hi! I've been trying out homepage (LXC via Proxmox VE Helper Script) and I'd like to ask if its possible to replace "API Error Information" message if I intentionally turn off the service? I've read #3103 but I'd prefer not to hide but explicitly state its off.
I'm also using ping so I'd like to replace the message as "Service Offline" or similar. Is this possible even with the custom API widget?

Thanks!

### homepage version

0.9.6

### Installation method

Other (please describe above)

### Configuration

```yaml
- Pihole-unRaid:
        icon: pi-hole.png
        description: unRaid Docker
        ping: #redacted
        statusStyle: "dot"
        widget:
            type: pihole
            url: #redacted
            key: #redacted
```

### Troubleshooting

![homepage-pihole-snip](https://github.com/user-attachments/assets/31bef322-c026-4f6c-9929-24456d5e74ab)
