### DISCUSSION TITLE
[Bug] Uptime is broken after receiving the latest updates :/

### DISCUSSION THREAD

**Discussion by ramazansancar** [gethomepage/homepage#4326] [Support] [answered]
### Description

After receiving the last update, the counter in the uptime area was corrupted. The i18n key is included. It does not write the data.

![image](https://github.com/user-attachments/assets/e30e05e1-159b-46f0-86f5-6ec758abbc65)
![image](https://github.com/user-attachments/assets/14acd90e-4bfb-441a-b251-eda8048d013f)

### homepage version

v0.9.13

### Installation method

Source

### Configuration

```yaml
--- settings.yaml
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#headerStyle: clean
language: tr
showStats: true

--- widgets.yaml
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /
    network: default # options: 'default' or active network interface name
    cputemp: true
    uptime: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    units: metric
    diskUnits: bytes
    expanded: true
    #refresh: 3000
```

### Troubleshooting

When I check other languages ​​there is similar issue.
