### DISCUSSION TITLE
[Feature Request] Inform iframe widget the current color scheme

### DISCUSSION THREAD

**Discussion by gera2ld** [gethomepage/homepage#4329] [Feature Requests] [answered]
### Description

An iframe widget is not able to get the parent color scheme or CSS selectors due to technical constraints.

Is it possible to support placeholders in the iframe URL, so we can get the current color scheme as well as other information if needed in the future from the URL?
For example, use a placeholder in the url:

```yaml
widget:
  type: iframe
  src: 'https://example.com/my-iframe?colorScheme={colorScheme}'
```

**Update:**

if the page sets `color-scheme: dark` or `color-scheme: light` properly, `iframe`s will be able to adapt to the theme with `@media (prefer-color-scheme: dark) { ... }` without any code change needed.
