### DISCUSSION TITLE
Custom API and JSON array

### DISCUSSION THREAD

**Discussion by lbalogh** [gethomepage/homepage#4335] [Support] [answered]
### Description

I have a custom API that returns a JSON like:

```
[
   {
      "action":"Get device state",
      "id":10,
      "state":true,
      "error":""
   }
]
```

I’d like to show the “state” value, but for the life of me, I can’t get it to work.

After reading https://github.com/gethomepage/homepage/discussions/3305, I ended up with that :

```
    - Office lamp:
        type: customapi
        url: https://my.domain.com/hue/state/10
        mappings:
          - field:
              0:
                state
              label: Status
```

But the widget doesn’t show anything. Any help would be appreciated!

### homepage version

v0.9.13 (a06964d, Nov 24, 2024)

### Installation method

Docker

### Troubleshooting

From the container :

```
/app # curl -L -k https://my.domain.com/hue/state/10
[{"action":"Get device state","id":10,"state":true,"error":""}]
```

**Comment by lbalogh** [comment, marked as answer]
Well... I'm responding to myself, my config wasn't formatted correctly :

_(edit : complete config)_

```
    - Office lamp
        href: https://my.domain.com/hue/toggle/10
        icon: /icons/light.png
        widget:
            type: customapi
            url: https://my.domain.com//hue/state/10
            mappings:
            - field:
                0:
                    state
              remap:
              - value: true
                to: On
              - value: false
                to: Off
```
