### DISCUSSION TITLE
[Feature Request] Filter the Radarr integration of the Calendar widget by release format

### DISCUSSION THREAD

**Discussion by martn263** [gethomepage/homepage#4341] [Feature Requests]
### Description

Optionally filter the Radarr integration of the [Calendar](https://gethomepage.dev/widgets/services/calendar/) widget by release format (in cinemas, physical release, digital release).

```
widget:
  type: calendar
  integrations:
    - type: radarr
      ...
      showCinemaRelease: false # optional - defaults to true
      showPhysicalRelease: false # optional - defaults to true
      showDigitalRelease: true # optional - defaults to true       
      ...
```
