### DISCUSSION TITLE
Card Blur not working on android

### DISCUSSION THREAD

**Discussion by TheRedCyclops** [gethomepage/homepage#4344] [Support] [answered]
### Description

The blur on the cards doesn't work on android, the browser does not display it, I have tried multiple browsers but it only seems to work on pc.

### homepage version

v0.9.13

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

background:
  image: /mountains.jpg
  saturate: 50
cardBlur: md
theme: dark
```

### Troubleshooting

Unable to preform browser tests on android, nothing on logs from the server
