### DISCUSSION TITLE
Some icons are not loading in my homepage

### DISCUSSION THREAD

**Discussion by CodeWithCJ** [gethomepage/homepage#4345] [Support] [answered]
### Description

Some icons are not loading in my homepage. Attached Adguard is an example. Even though I reloaded, its not showing in my homepage. 
![AdGuard](https://github.com/user-attachments/assets/a371cab2-44eb-47b4-b5f5-8cecf589e3f4)

### homepage version

v0.9.13

### Installation method

Docker

### Configuration

```yaml
- Adguard:
        href: https://adguard.site.buzz
        icon: AdGuard.png
        widget:
          type: adguard               
          url: http://myip:8443
          username: myuser
          password: mypassword
```

### Container Logs

No error log

### Troubleshooting

I tried to upload various icons and image format. none seemed to have worked. I even restarted my docker and ubuntu. still didn't work. Its not just with v0.9.13, but also with older versions.
