### DISCUSSION TITLE
Cant access Dashboard when using twingate

### DISCUSSION THREAD

**Discussion by ifusiontt** [gethomepage/homepage#4354] [Support]
### Description

Dashboard works great when connected on the same network.  Once I login to my twingate client, I'm not able to access the service.   All other docker services are work well when connecting through twingate.  The webpage just keeps loading. 

### homepage version

v0.9.13 (a06964d)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: iFusionLabs Homepage

headerStyle: boxed

background: https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1472&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
```

### Container Logs

None

### Browser Logs

None

### Troubleshooting

No widgets are installed.  
The docker logs says "Listening on port 3000"
