### DISCUSSION TITLE
gitlab integration api error

### DISCUSSION THREAD

**Discussion by causalityloop** [gethomepage/homepage#4355] [Support]
### Description

noticed recent support for gitlab and altered config to test it out

### homepage version

latest as of today (7a7906f2c4c2)

### Installation method

Docker

### Configuration

```yaml
- Gitlab:
        href: https://gitlab.homelab.local
        # description: Homepage is awesome
        icon: gitlab
        widget:
          type: gitlab
          url: https://gitlab.homelab.local
          key: glpat-<redacted>
          user_id: 2
```

### Container Logs

homepage-test   | [2024-11-29T03:01:49.702Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://gitlab.homelab.local/api/v4/users/2/associations_count
homepage-test   | [2024-11-29T03:01:50.881Z] error: <httpProxy> Error calling https://gitlab.homelab.local/api/v4/users/2/associations_count...
homepage-test   | [2024-11-29T03:01:50.881Z] error: <httpProxy> [
homepage-test   |   500,
homepage-test   |   AggregateError
homepage-test   |       at internalConnectMultiple (node:net:1114:18)
homepage-test   |       at afterConnectMultiple (node:net:1601:5) {
homepage-test   |     code: 'ECONNREFUSED',
homepage-test   |     [errors]: [ [Error] ]
homepage-test   |   }
homepage-test   | ]

I also verified, from my ui profile, I am user 2
![2024-11-28_22h10_46](https://github.com/user-attachments/assets/b02c27a1-0770-4d82-a69c-131c8825a444)

### Troubleshooting

I tested the url (below), from the container log, and i get a valid response (albeit i was already logged in via the browser)

https://gitlab.homelab.local/api/v4/users/2/associations_count

{"groups_count":1,"projects_count":30,"issues_count":40,"merge_requests_count":195}
