### DISCUSSION TITLE
Tailwidget API - Not Fetching IP Info

### DISCUSSION THREAD

**Discussion by BBT-nZ** [gethomepage/homepage#4356] [Support] [answered]
### Description

I'm probably not the first and maybe not the last. But this has driven me to insanity, so hoping someone much smarter here can be a helping hand. Thanks in advance.

**Environments:**

1) Proxmox> Ubuntu Server VM> Docker/Docker Compose> Homepage
2) Proxmox> Ubuntu Desktop VM> Docker/Docker Compose> Homepage
3) Proxmox> Ubuntu Server VM> CasaOS> Homepage

At one stage, by some miracle (I cannot recall the setting of the VM's) precisely, but it was Ubuntu Desktop VM with simple docker installed on it via terminal. It did manage to work and I had it working for nearly x2 weeks before I decided to clean up my VM and start things fresh as was just testing homepage to ensure all works as desired.

However, now I'm stuck against the error below like a concrete wall driving me to insanity!

![image](https://github.com/user-attachments/assets/ef0ab564-f426-461c-886a-3780d5de9f3b)

API Error: Unknown error
URL: https://api.tailscale.com/api/v2/device/devicerandomtext
Raw Error:
{
    "code": "ENETUNREACH"
}
```



### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
- Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        ping: https://login.tailscale.com/admin/machines
        description: Tailscale Admin Console
        widget:
          type: tailscale
          deviceid: xoxoxoxoxoCNTRL
          key: apikeyapkikey
```

### Container Logs

```
]
[2024-11-29T01:41:46.314Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://api.tailscale.com/api/v2/device/nfFp5sbaYk11CNTRL
[2024-11-29T01:41:46.315Z] error: <httpProxy> Error calling https://api.tailscale.com/api/v2/device/ntx9XB9Ete11CNTRL...
[2024-11-29T01:41:46.315Z] error: <httpProxy> [
  500,
  AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1173:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1632:3)
      at listOnTimeout (node:internal/timers:571:11)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'ENETUNREACH',
    [errors]: [
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error]
    ]
  }
```

### Troubleshooting

On Host

```
ubuntu-desktop@ubuntu-desktop:~/Docker/homepage$ curl -H "Authorization: Bearer **apikeyapikeyapikey**" https://api.tailscale.com/api/v2/device/**deviceIDCNTRL**
{"addresses":["100.100.100.12","fd7a:125c:a8e0::cd01:4126"],"authorized":true,"blocksIncomingConnections":false,"clientVersion":"1.76.1","created":"2024-11-03T07:33:50Z","expires":"2025-05-02T07:33:50Z","hostname":"opnsense","id":"5576439172817070","isExternal":false,"keyExpiryDisabled":true,"lastSeen":"2024-11-29T04:54:56Z","machineKey":"mkey:1ba27e58e8997729cfdfd2bda688ab03888f1679828abc2a34ffd57da0fe4047","name":"opnsense.tail51fc9b.ts.net","nodeId":"mydeviceIDCNTRL","nodeKey":"nodekey:b4e4a3810b9340e5c48829c7a69b7889a55919023409236sudfj04bccf5a5125","os":"freebsd","tailnetLockError":"","tailnetLockKey":"nlpub:f0d5e8506aa0172629347ae5e9bccc7a031433c0f1d09a8f2b61844843ad37b2","updateAvailable":false,"user":"myemail@gmail.com"}ubuntu-desktop@ubuntu-desktop:~/Docker/homepage$ 
```
