### DISCUSSION TITLE
[Feature Request] Add bool format type to the prometheus metric widget

### DISCUSSION THREAD

**Discussion by TheEaterr** [gethomepage/homepage#4363] [Feature Requests]
### Description

A big part of the data exposed by prometheus metrics are booleans representing a status. Currently, when using the prometheus metric widget, these are just shown with a 1 or a 0. It would be neat to add a bool `format.type` option that could allow for a custom true or false string to make a prettier dashboard.

An example configuration could be:

```yaml
- query: my_custom_metric{}
  label: Metric 1
  format:
    type: bool
    trueString: ✔️
    falseString: ❌
```

I implemented it locally and it would allow to make the widget go from this:
![image](https://github.com/user-attachments/assets/86d76e79-d396-4ef8-9904-cbecffe7d373)
to this:
![image](https://github.com/user-attachments/assets/88e5ba5a-5f1b-4a62-9325-434a6877d769)

Would there be any interest in me upstreaming this feature ?
