### DISCUSSION TITLE
Kubernetes ingress paths seem to not be handled very well

### DISCUSSION THREAD

**Discussion by evertdespiegeleer** [gethomepage/homepage#4370] [Support]
### Description

We're running Homepage in k8s with ingress-annotation based autodiscovery. Super cool feature!
However, we do have some relatively complex ingresses which Homepage doesn't seem to handle very well. E.g.:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: some-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-buffer-size: '512k'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'

    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Some Service"
    gethomepage.dev/group: "Management"
    gethomepage.dev/icon: "mdi-hub"
spec:
  ingressClassName: 'nginx'
  rules:
    - host: cool-service.domain.com
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: cool-service-frontend
                port:
                  number: 8080
          - pathType: Prefix
            path: /api(/|$)(.*)
            backend:
              service:
                name: cool-service-backend
                port:
                  number: 3000
  tls:
    - hosts:
        - cool-service.domain.com
```

Homepage uses `https://cool-service.domain.com/()(.*)` as the link to this service. Obviously, that's not the intention here; It should point to `https://cool-service.domain.com/`. That being said, I wouldn't really know how it'd discern this.

The problem in our specific case is that we use [nginx target rewrite](https://kubernetes.github.io/ingress-nginx/examples/rewrite/). Homepage could account for that but depending on the ingress controller used, there's lots of complex stuff that could be going on. Accounting for all of it seems unmaintainable.

Also, an ingress supports multiple hosts and multiple paths. It seems like Homepage picks the first path of the first host, but for a lot of use cases, that's a little naive imo.

I would propose adding some more annotations. I think the following annotations would allow users to work around any quirks:
- Index of the host to use (`gethomepage.dev/host-index`)
- Index of the path to use (`gethomepage.dev/path-index`)
- Override of the host (`gethomepage.dev/host-override`)
- Override of the path (`gethomepage.dev/path-override`)

I would be able fix our specific issue like this:

```yaml
    gethomepage.dev/path-override: "/"
```

### homepage version

v0.9.6

### Installation method

Other (please describe above)

### Troubleshooting

n/a
