### DISCUSSION TITLE
Stock information widget is broken (`error: undefined`)

### DISCUSSION THREAD

**Discussion by jfroy** [gethomepage/homepage#4372] [Support] [answered]
### Description

The stock information widget appears broken. I've confirmed the API key is correct and I get valid results by issuing a request to Finnhub with curl. The regular stocks widget works with the same watchlist and API key.

I am running Homepage on a Kubernetes cluster.

### homepage version

v0.9.13

### Installation method

Other (please describe above)

### Configuration

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: ''
  custom.css: ''
  custom.js: ''
  docker.yaml: ''
  kubernetes.yaml: ''
  services.yaml: |
    ---
    - Test:
        - stocks:
            href: https://apple.com
            widget:
              type: stocks
              provider: finnhub
              watchlist:
                - AAPL
  settings.yaml: |
    ---
    title: Home
    providers:
      finnhub: {{HOMEPAGE_VAR_FINNHUB_API_KEY}}
  widgets.yaml: |
    ---
    - stocks:
        provider: finnhub
        watchlist:
          - AAPL
```

### Container Logs

```
homepage-5974848898-28czr homepage Listening on port 3000
homepage-5974848898-28czr homepage [2024-12-02T20:35:49.420Z] error: undefined
```

### Browser Logs

```
index-b16bcd0109d2040b.js:1 
        
        
       GET https://homepage/api/widgets/stocks?lang=en&index=1&provider=finnhub&watchlist=AAPL&style=%5Bobject+Object%5D 500 (Internal Server Error)
fetcher @ index-b16bcd0109d2040b.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
o @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
ti @ framework-fb129ad84e3a607e.js:1
bi @ framework-fb129ad84e3a607e.js:1
yi @ framework-fb129ad84e3a607e.js:1
gi @ framework-fb129ad84e3a607e.js:1
(anonymous) @ framework-fb129ad84e3a607e.js:1
ks @ framework-fb129ad84e3a607e.js:1
rs @ framework-fb129ad84e3a607e.js:1
S @ framework-fb129ad84e3a607e.js:1
T @ framework-fb129ad84e3a607e.js:1
index-b16bcd0109d2040b.js:1 
        
        
       GET https://homepage/api/widgets/stocks?lang=en&index=1&provider=finnhub&watchlist=AAPL&style=%5Bobject+Object%5D 500 (Internal Server Error)
fetcher @ index-b16bcd0109d2040b.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
o @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
setTimeout
onErrorRetry @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
s @ _app-2da6463c8d7db6b5.js:1
Promise.then
u @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
o @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
(anonymous) @ _app-2da6463c8d7db6b5.js:1
ti @ framework-fb129ad84e3a607e.js:1
bi @ framework-fb129ad84e3a607e.js:1
yi @ framework-fb129ad84e3a607e.js:1
gi @ framework-fb129ad84e3a607e.js:1
(anonymous) @ framework-fb129ad84e3a607e.js:1
ks @ framework-fb129ad84e3a607e.js:1
rs @ framework-fb129ad84e3a607e.js:1
S @ framework-fb129ad84e3a607e.js:1
T @ framework-fb129ad84e3a607e.js:1

```

### Troubleshooting

N/A
