### DISCUSSION TITLE
remote dockers are offline

### DISCUSSION THREAD

**Discussion by henkiewie** [gethomepage/homepage#438] [Support] [answered]
Hi,
I created two extra docker instances inside my local portainer.
I changed the labels and env: in the service widget and the server: label in the docker.yaml
They use the same API key because there is one portainer, but the status is offline.
What can I do to show the right (online) status of the portainer led?

![Screenshot 2022-10-24 at 09 38 15](https://user-images.githubusercontent.com/74558874/197472756-1252774f-13fb-4866-8506-34a273ed6acc.png)

```
    - Portainer RPI-LITE:
        icon: portainer
        href: https://portainer.rpi-lite.lan/#!/1/docker/containers
        description: Docker management RPI-LITE
        server: my-local-docker # The docker server that was configured
        container: portainer
        widget: 
          type: portainer
          url: http://192.168.1.29:9001
          env: 1
          key: [obscured]

    - Portainer RPI-2B:
        icon: portainer
        href: https://portainer.rpi-lite.lan/#!/9/docker/containers
        description: Docker management RPI-2B
        server: rpi-2b.lan # The docker server that was configured
        container: portainer
        widget: 
          type: portainer
          url: http://192.168.1.29:9001
          env: 9
          key:[obscured]       

    - Portainer RPI-FULL:
        icon: portainer
        href: https://portainer.rpi-lite.lan/#!/10/docker/containers
        description: Docker management RPI-FULL
        server: rpi-full.lan # The docker server that was configured
        container: portainer
        widget: 
          type: portainer
          url: http://192.168.1.29:9001
          env: 10
          key: [obscured]

```
```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

rpi-2b.lan:
  host: 192.168.1.30
  port: 2375

rpi-full.lan:
  host: 192.168.1.28
  port: 2375

#rpi-lite
my-local-docker:
  socket: /var/run/docker.sock
```
