### DISCUSSION TITLE
[Feature Request] Ugreen NAS

### DISCUSSION THREAD

**Discussion by MosizZ** [gethomepage/homepage#4383] [Feature Requests]
### Description

A Service Wieget for Ugreen NAS like the Qnap Integration

**Comment by CaseySJ** [comment]
I would also like to request the same thing: Service Widget for UGreen NAS.

UGreen has somewhat disrupted the market for high performance consumer NAS systems by delivering excellent value for the money.

**Comment by olli991** [comment]
I would also appreciate if we can get a widget for it like Synology or QNAP :-)

I also looked a bit into it...
There is sadly no real API documentation so far to grab that info (which is there because of the rly good app they've built). 

You could use glances in docker for some info. 
You can also use a custom integration for Home Assistant that can deliver some infos but is also in development currently: https://github.com/Tom-Bom-badil/home-assistant_ugreen-nas 
This repo could probably also give some insights as well tho.

**Reply by olli991** [reply]
I plyed around with the home assistant integration und it's possible to build something like this with it :)
![image](https://github.com/user-attachments/assets/b975942e-1747-4d9e-afeb-fc449507fd67)

**Reply by ctgiant** [reply]
> I plyed around with the home assistant integration und it's possible to build something like this with it :) ![image](https://private-user-images.githubusercontent.com/55631413/462830953-b975942e-1747-4d9e-afeb-fc449507fd67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxMjM0MDgsIm5iZiI6MTc1MzEyMzEwOCwicGF0aCI6Ii81NTYzMTQxMy80NjI4MzA5NTMtYjk3NTk0MmUtMTc0Ny00ZDllLWFmZWItZmM0NDk1MDdmZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDE4MzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTBhMjUwN2MwNTE5YTZjNTc1NDdhYTFkMDdjNTc1NzYwYWUzY2VkYjE4NzliNzQ5OWFmZDczMmY1MDYxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.idTkRulBkDrOSBZq1zK7Hi62wkDSefHb7QrXRHBrins)

This looks great!  Would you mind sharing the custom API files that you created to get this working?

**Reply by olli991** [reply]
The Home Assistant API is linked above, after that it's just this:
```yaml
      - UGREEN NAS:
          icon: sh-ugreen-nas
          href: https://nas.MYDOMAIN.tld
          siteMonitor: https://nas.MYDOMAIN.tld
          description: DXP4800+ 16 GB
          widgets:
            - type: homeassistant
              url: https://ha.MYDOMAIN.tld
              key: APIKEY
              custom:
                - state: sensor.ugreen_nas_cpu_usage
                  label: CPU
                - state: sensor.ugreen_nas_ram_size_usage_percentage
                  label: RAM
                - state: sensor.ugreen_nas_cpu_temperature
                  label: Temperatur
                - state: sensor.ugreen_nas_server_status
                  label: Status
            - type: homeassistant
              url: https://ha.MYDOMAIN.tld
              key: APIKEY
              custom:
                - state: sensor.ugreen_nas_pool_1_volume_1_available_size
                  label: Frei Vol 1
                - state: sensor.ugreen_nas_pool_1_volume_1_status
                  label: Status Vol 1
                - state: sensor.ugreen_nas_pool_2_volume_1_available_size
                  label: Frei Vol 2
                - state: sensor.ugreen_nas_pool_2_volume_1_status
                  label: Status Vol 2
```
