### DISCUSSION TITLE
[Feature Request] NTFY support

### DISCUSSION THREAD

**Discussion by JohnFawkes** [gethomepage/homepage#4392] [Feature Requests] [answered]
### Description

Would love to see support for [ntfy](https://github.com/binwiederhier/ntfy). I did see its possible for custom api widgets in another discussion but having a built in way to specify the topic and grab the latest message would be really nice. I do see theres gotify but I dont really want to install another container just to send notifications to homepage when im already using ntfy. If anyone has any ideas how i caould grab the latest message from ntfy using the custom api please let me know. Thanks

**Comment by pe1uca** [comment]
I just worked a bit on this, here's the branch https://github.com/pe1uca/homepage/tree/ntfy-widget  

The [guidelines](https://gethomepage.dev/widgets/authoring/getting-started/#service-widget-guidelines) say new widgets require at least 20 upvotes, so I won't be creating a PR at the moment.  
Also, my work is mostly a PoC, there still some validations to be done to improve UX, plus adhere to the linting settings of the project.  

Some things to note:  
- ntfy's UI uses browser's storage to know what notifications are new and which have been read, the server always returns all messages cached. Since I didn't find a precedent on how to store data in the browser I'm just showing a number for all messages in the topics. If there's an agreed way to store information maybe I can update the branch to send a notification in the browser.  
- ntfy's response is a new-line-separated list of objects, which made me do this `"[" + msgs.split("\n").filter((value) => value !== "").join(",") + "]"` to have a JS array.  
- I was planning on also having as an alternative a service widget, but the [metrics](https://docs.ntfy.sh/config/#monitoring) provided by the project are not easy to work with (I don't know Prometheus to properly understand the format of the endpoint)

**Reply by shamoon** [reply]
FYI, I dont think we would accept an 'info' widget for this. As you can see we have very few of those and they are really reserved for very widely-popular kinds of things (time, resources, weather). Something like this should be a 'service' widget. And thanks for appropriately waiting for the votes 👍

**Reply by pe1uca** [reply]
Got it!  
Yeah, that was also another thing I wanted to ask before creating the PR, if an info widget would be fine.  

I can move it to a service one, maybe list separately just one or two topics and the rest aggregated? I'll check how it looks and how other widgets work.  

----  

Quick two questions about the features allowed in the project:  
- Would it be fine to use localStorage in the browser? I only see it used for settings of the project, not for widgets.  
- Would it be fine to integrate [notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission_static)?  

Both of these would be used together, to know which messages are new from the response of ntfy, and to send a notification on new ones.  
Most probably controlled by a value in the config, so people can turn them off.

**Reply by shamoon** [reply]
Sorry, no to both.

**Comment by zhy3213** [comment]
26 already 👀

**Comment by MRi-LE** [comment]
has this been build in by now?

**Comment by jimstrang** [comment]
Here's a customapi widget that I use for ntfy that grabs the latest notification for a given topic. Works fine for my use case.

```yaml
widget:
  type: customapi
  url: https://ntfy.custom.url/topic/json?poll=1&since=latest
  headers:
    Authorization: Basic {{HOMEPAGE_VAR_NTFY_AUTH}}
  refreshInterval: 60000
  mappings:
    - field: title
      label: Title
      format: text
    - field: message
      label: Message
      format: text
    - field: time
      label: Last Alert
      format: date
      scale: 1000
```
