### DISCUSSION TITLE
Need Help for proxmox widget configuration

### DISCUSSION THREAD

**Discussion by kryptonyc** [gethomepage/homepage#4393] [Support]
### Description

Hi There!

I needed some help with Proxmox widget configuration.  When i have set up the Proxmox Widget as per the homepage guide i am encountering the error below:-

API Error: Unexpected token 'I', "Internal S"... is not valid JSON

### homepage version

v0.9.12

### Installation method

Docker

### Configuration

```yaml
- proxmox:                                                 
        icon: proxmox.png             
        href: <proxmox IP>       
        description: Hypervisor                                                    
        ping: <Proxmox IP>  
        showStats: true                        
        widget:                                                                    
          type: proxmox               
          url: <proxmox IP>            
          username: api@pam!homepage          
          password: <API-Keys>
```

### Troubleshooting

API Error: Unexpected token 'I', "Internal S"... is not valid JSON
