### DISCUSSION TITLE
Glances processes display error

### DISCUSSION THREAD

**Discussion by Darneur** [gethomepage/homepage#4402] [Support] [answered]
### Description

When displaying the process list widget, unexpected values populate the MEM area. The other widgets are working as expected.

![image](https://github.com/user-attachments/assets/96c907f7-be4a-44a9-bdde-fca9c2da7ec0)

### homepage version

v0.9.13

### Installation method

Docker

### Configuration

```yaml
- Server:
    - System Information:
        widget:
            type: glances
            url: http://10.1.10.172:61208
            metric: info
            version: 4
            refreshInterval: 2000 
    - CPU Usage:
        widget:
            type: glances
            url: http://10.1.10.172:61208
            metric: cpu
            version: 4
            refreshInterval: 2000
    - Memory:
        widget:
            type: glances
            url: http://10.1.10.172:61208
            metric: memory
            version: 4
            refreshInterval: 2000
    - Disk:
        widget:
            type: glances
            url: http://10.1.10.172:61208
            metric: disk:PhysicalDrive0
            version: 4    
            refreshInterval: 2000        
    - Processes:
        widget:
            type: glances
            url: http://10.1.10.172:61208
            metric: process
            version: 4
            refreshInterval: 2000         
    - Network Usage:
        widget:
            type: glances
            url: http://10.1.10.172:61208
            metric: network:NIC1
            version: 4
            refreshInterval: 2000
```

### Container Logs

homepage  | Listening on port 3000
homepage  | Listening on port 3000
homepage  | Listening on port 3000
homepage  | [2024-12-12T11:02:22.461Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://10.1.10.172:61208/api/3/processlist
homepage  | [2024-12-12T11:02:22.850Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://10.1.10.172:61208/api/3/processlist

### Browser Logs

![image](https://github.com/user-attachments/assets/78f3ae08-a4c0-4571-a6ad-49423f0b3c44)
![image](https://github.com/user-attachments/assets/d177fe10-2d57-4802-b070-ba133c3b06c6)

despite the error in the docker container logs the GET request seems to be working in the browser. 

### Troubleshooting

Result of `curl http://10.1.10.172:61208/api/4/processlist`
```
StatusCode        : 200
StatusDescription : OK
Content           : [{"status": "R", "pid": 1440, "num_threads": 955, "cpu_times": {"user": 590055.203125, "system":
                    1113332.859375, "children_user": 0.0, "children_system": 0.0}, "name": "svchost.exe", "nice": 32,
                    "io_c...
RawContent        : HTTP/1.1 200 OK
                    Content-Length: 160105
                    Content-Type: application/json
                    Date: Thu, 12 Dec 2024 13:35:50 GMT
                    Server: uvicorn

                    [{"status": "R", "pid": 1440, "num_threads": 955, "cpu_times": {"user":...
Forms             : {}
Headers           : {[Content-Length, 160105], [Content-Type, application/json], [Date, Thu, 12 Dec 2024 13:35:50
                    GMT], [Server, uvicorn]}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 160105
```

**Comment by shamoon** [comment]
You are definitely running in docker? Try completely removing and re-creating the container. I cant reproduce anything (and this haunts changed). The text in the screenshot looks like the untranslated string which can be a caching thing.
<img width="870" alt="Screenshot 2024-12-12 at 7 51 17 AM" src="https://github.com/user-attachments/assets/3f263fbd-eab8-41e4-804f-d7677a904d43" />

Also, please post your compose file if using docker (compose).

**Reply by Darneur** [reply]
Here is my docker compose:
```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - C:/Users/Server/Documents/HostedServices/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

I tried completely deleting and remaking the container, but the error doesn't go away. I've also tried removing the image, which didn't work either. 

Is it possible that it's something from my glances instance? I'm running it with `python -m glances -w` from outside of Docker.
