### DISCUSSION TITLE
AdguardHome API Error: HTTP Error

### DISCUSSION THREAD

**Discussion by awlobo** [gethomepage/homepage#4407] [Support]
### Description

Hello, basically my issue is that I cannot see the widget for AdGuardHome

![Screenshot_20241212_213721](https://github.com/user-attachments/assets/f589b274-3863-495c-85ac-e2889c60b640)

### homepage version

v0.9.13 (a06964d, Nov 24, 2024)

### Installation method

Docker

### Configuration

```yaml
Adguard Home is hosted in machine1 with its own IP address while Homepage is a docker container with its own network (shared with other containers) in machine2.


- Adguard Home:
      icon: adguard-home
      href: http://192.168.1.124
      siteMonitor: http://192.168.1.124
      widget:
        type: adguard
        url: http://192.168.1.124
        fields: ["queries", "blocked", "filtered", "latency"]
        username: redacted
        password: redacted
```

### Container Logs

No relevant container logs in docker.

### Browser Logs

With the chrome inspect tool I get:
![Screenshot_20241212_214012](https://github.com/user-attachments/assets/f73bbd18-3df4-42a1-bdc0-53c6830fe759)

### Troubleshooting

1. Ensured URL does not finish with /
2. PING

```
> docker exec home ping 192.168.1.124                              took 288ms
PING 192.168.1.124 (192.168.1.124): 56 data bytes
64 bytes from 192.168.1.124: seq=0 ttl=63 time=0.185 ms
64 bytes from 192.168.1.124: seq=1 ttl=63 time=0.684 ms
64 bytes from 192.168.1.124: seq=2 ttl=63 time=0.612 ms
```

3. CURL

```
>curl -L -k -u "redacted:redacted" http://192.168.1.124/control/stats
{"time_units":"hours","top_queried_domains":[redacted],"top_blocked_domains":[redacted],"top_upstreams_responses":[redacted],"top_upstreams_avg_time":[redacted],"dns_queries":[redacted],"blocked_filtering":[redacted],"replaced_safebrowsing":[redacted],"replaced_parental":[redacted],"num_dns_queries":77640,"num_blocked_filtering":2173,"num_replaced_safebrowsing":0,"num_replaced_safesearch":0,"num_replaced_parental":0,"avg_processing_time":0.003711}
```
