### DISCUSSION TITLE
Service widgets throw 403 and (system) Widgets throw 404

### DISCUSSION THREAD

**Discussion by Gerben-Tx** [gethomepage/homepage#441] [Support] [answered]
**Describe the bug**
All my Service widgets throw 403 errors even though I correctly filled in the `key`s.
My (system) Widgets (disks) throws 404 errors, but only on custom disks.

**Expected behavior**
Both widgets should work with this configuration (assuming this configuration is indeed correct)

**Screenshots**
(`sonarr.development-hub.io` is a local DNS record in my PiHole instance.)

![image](https://user-images.githubusercontent.com/9005496/197558512-a1a1c36f-8082-4d72-8c5b-9adf28a6e84f.png)

![image](https://user-images.githubusercontent.com/9005496/197558634-786a31a1-94aa-4920-a471-4060a534bc00.png)

![image](https://user-images.githubusercontent.com/9005496/197558686-e8a1a1ec-3668-472a-8cf0-a58608e75c5f.png)

![image](https://user-images.githubusercontent.com/9005496/197559230-529b1670-0a6c-4f60-be56-6b6a9f39eae5.png)

**Configuration**
_widgets.yaml_
```yaml
- resources:
      cpu: true
      memory: true
      expanded: true
      disk:
          - /
          - /media/Elements
```

_services.yaml_
```yaml
    - Sonarr:
        href: https://sonarr.development-hub.io
        icon: sonarr
        container: sonarr
        server: nuc-docker
        widget:
            type: sonarr
            url: https://sonarr.development-hub.io
            key: REDACTED
```

**Additional context**
This is the docker image i'm using 
![image](https://user-images.githubusercontent.com/9005496/197560293-fd92ad10-8135-4c08-be2f-eae29a204588.png)

This is the docker version
```
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        100c70180f
 Built:             Thu Sep 22 06:21:41 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       a89b842
  Built:            Thu Sep 22 06:22:13 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I'm using Traefik as a reverse proxy with self signed certificates. I suspect Traefik has to do something with this but i'm not sure where the problem lies..

**Comment by shamoon** [comment]
Respectfully, do you think its more likely there is a bug in every widget or a configuration issue on your end?

Please make sure homepage can ping that server e.g. `docker exec homepage ping sonarr.development-hub.io`. I bet not. If not, you need to sort out networking, often putting homepage on the same (docker) network as your service, then figure out what host / IP to use. Also, just noticed youre using traefik, which is may be 'blocking' the API calls, depends on how you have things setup

As for your disk, you need to mount it to the container for homepage to be able to see it, did you do that? https://github.com/benphelps/homepage/wiki/Information-Widgets#resources

**Reply by Gerben-Tx** [reply]
> Respectfully, do you think its more likely there is a bug in every widget or a configuration issue on your end?

No, but it is possible there is a bug in the homepage structure itself that might causes problems with a reverse proxy.

> Please make sure homepage can ping that server e.g. docker exec homepage ping sonarr.development-hub.io. I bet not. 

Pinging works fine, and i suspect it can actually reach the API's because it receives a 403 which means the client is not authorized. 
![image](https://user-images.githubusercontent.com/9005496/197570321-31507626-5a9c-4fee-8440-6a2a6de44ad4.png)

> Also, just noticed youre using traefik, which is may be 'blocking' the API calls, depends on how you have things setup

That is mainly why i made the bug report. I assumed this project would work with reverse proxies, but it appears not so i'll investigate further..

> As for your disk, you need to mount it to the container for homepage to be able to see it, did you do that? https://github.com/benphelps/homepage/wiki/Information-Widgets#resources

Makes sense, did not do that. Thanks!

**Comment by Gerben-Tx** [comment]
It seems to be working if i directly connect to the port and use http..
Seems like it doesn't hit my Traefik instance which should reroute `https://sonarr.development-hub.io` to `[sonar_docker_ip]:8989`.

_services.yaml_
```yaml
    - Sonarr:
        href: https://sonarr.development-hub.io
        # description: 
        icon: sonarr
        container: sonarr
        server: nuc-docker
        widget:
            type: sonarr
            url: http://sonarr.development-hub.io:8989
            key: REDACTED
```

**Reply by JazzFisch** [reply]
I have my instance of homepage working just fine with Traefik as a reverse proxy.  It did require that I do something like the following in my docker-compose file however:
```yaml
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    networks:
      traefik-internal:
        aliases:
          - sonarr.docker.internal
          - sonarr
    volumes:
      - $LOCALDOCKERDIR/sonarr:/config
      - $DOWNLOADSDIR:/downloads
      - '$MEDIADIR/TV Shows:/tv'
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK: 007
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-internal"
      ## HTTP Routers Auth
      - "traefik.http.routers.sonarr-rtr.entrypoints=https"
      - "traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.$DOMAINNAME`)"
      ## HTTP Services
      - "traefik.http.routers.sonarr-rtr.service=sonarr-svc"
      - "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"
      ## == Auth bypass with API Key on local network ==
      - "traefik.http.routers.sonarr-api-rtr.entrypoints=https"
      - "traefik.http.routers.sonarr-api-rtr.priority=99"
      - "traefik.http.routers.sonarr-api-rtr.rule=Host(`sonarr.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$SONARR_API_KEY`) || Query(`apikey=$SONARR_API_KEY`))"
      - "traefik.http.routers.sonarr-api-rtr.service=sonarr-svc"
      ## Middlewares
      - "traefik.http.routers.sonarr-rtr.middlewares=authentik@file"
```
