### DISCUSSION TITLE
Homepage container is crashing randomly

### DISCUSSION THREAD

**Discussion by Chaosflo** [gethomepage/homepage#4415] [Support]
### Description

Hej!
Since starting to use Homepage and configuring stuff, it crashes completly randomly.
The strange thing is without any exception logs whatsoever. 
(while writing this issue I found the debug flag, I will provide logs if I it crashes again)

The container just goes offline, I restart it, and voila everything is working like usual for a few hours/days.
I tried to narrow down the issue but I couldnt.

How do I use Homepage?

I use it via a portainer stack feature. 
I have the configuration all in github in a private repository which gets pulled along with the docker compose.
I have bound the local directory (this is equal to the dirctory where the docker-compose file is located)
I have not used any special config.
_While writing I have added the restart always config entry_

```
homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    labels:
      - homepage.group=Services
      - homepage.name=Homepage
      - homepage.icon=homepage
      - homepage.href=http://erich
      - homepage.showStats=true
    ports:
      - 80:3000
    volumes:
      - ./homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    networks:
      core-services-net:
```
This is all what the thing is logging 
(I have checked the log file but there are only old entries of me trying to get yml in correct shape)
IDK if its a correct behavior but in the log file are only errors

> Listening on port 3000

Thats bascially all I can provide sorry =(

Greetings Florian

### homepage version

v0.9.13 (a06964d, Nov 24, 2024)

### Installation method

Docker

### Container Logs

Listening on port 3000

### Troubleshooting

Will be added later
