### DISCUSSION TITLE
tailscale widget not working

### DISCUSSION THREAD

**Discussion by dowonim323** [gethomepage/homepage#4417] [Support]
### Description

The tailscale wideget, which originally worked well, has been showing up as "API Error: Failed to fetch" for a few weeks and is not working. I've also reissued the tailscale api key, and I've touched the setup file, but it still doesn't work, so I'm asking for help.

### homepage version

0.9.13

### Installation method

Docker

### Configuration

```yaml
- Network:
    - Tailscale:
        href: https://login.tailscale.com/admin/machines
        icon: tailscale
        widget:
          type: tailscale
          deviceid: *************CNTRL
          key: tskey-api-**************-***************
        siteMonitor: https://tailscale.com/
```

### Container Logs

Listening on port 3000
[2024-12-14T03:57:55.494Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://api.tailscale.com/api/v2/device/********CNTRL

### Troubleshooting

curl --request GET --url https://api.tailscale.com/api/v2/device/************CNTRL -H "Authorization: Bearer tskey-api-***************-************************"

The above command returns the correct api output.
