### DISCUSSION TITLE
Hammers the search suggestions endpoint with no input

### DISCUSSION THREAD

**Discussion by disconn3ct** [gethomepage/homepage#4418] [Support] [answered]
### Description

I have a custom search provider set.
Without selecting the search box, it hammers the homepage endpoint. It does not appear to be passing those on to the search engine fortunately (and the browser is caching most of them.)

Looking at the request, it is receiving a random-looking collection of words.

![image](https://github.com/user-attachments/assets/55b62019-6b65-4fbc-aeae-91cb9e9253a4)

### homepage version

v0.9.13

### Installation method

Docker

### Configuration

```yaml
widgets:
  - search:
      provider: custom
      url: https://potatosearch/search?q=
      target: _blank
      suggestionUrl: https://potatosearch/autocomplete?q=
      showSearchSuggestions: true
      description: Whoogle
```

### Troubleshooting

na

**Comment by shamoon** [comment]
Yea that's odd, I cant reproduce that. What browser?

```yaml
- search:
    provider: custom
    url: https://www.ecosia.org/search?q=
    suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
    target: _blank
    showSearchSuggestions: true
```

<img width="741" alt="Screenshot 2024-12-14 at 8 25 17 AM" src="https://github.com/user-attachments/assets/7a4d7e2e-e290-426a-8b7f-e96adfe65ca3" />

No requests until I type something:
<img width="384" alt="Screenshot 2024-12-14 at 8 25 47 AM" src="https://github.com/user-attachments/assets/57840f0b-1752-486c-8b62-ec2663b6e835" />
