### DISCUSSION TITLE
Custom API widget for WGDashboard

### DISCUSSION THREAD

**Discussion by daidan3k** [gethomepage/homepage#4427] [General]
Hi, I made a custom widget to give support to WGDashboard.
It shows connected peers, total peers, and total data usage.

![image](https://github.com/user-attachments/assets/2ea3bace-346f-485b-bed4-2fc7c9df3016)

```yaml
- WireGuard:
    icon: https://static-00.iconduck.com/assets.00/wireguard-icon-1024x1024-78n6jncy.png
    href: http://server
    description: Manage WireGuard Peers
    widget:
      type: customapi
      url: http://server:10086/api/getWireguardConfigurations
      method: GET
      headers:
        content-type: application/json
        wg-dashboard-apikey: -----------YOURAPIKEYHERE-------------
      mappings:
        - field:
            data:
              0: ConnectedPeers
          format: number
          label: Connected
        - field:
            data:
              0: TotalPeers
          format: number
          label: Peers
        - field:
            data:
              0:
                DataUsage: Total
          suffix: GB
          label: Total Usage
          format: float
```
