### DISCUSSION TITLE
Homepage Docker container showing unhealthy - Logs are completely blanks

### DISCUSSION THREAD

**Discussion by SvartrShell** [gethomepage/homepage#4433] [Support]
### Description

Been running homepage for well over a year with the same config via docker with a compose file, havent made any changes recently but noticed homepage wasnt up - couldnt reach it behind my proxy or via IP:PORT. Checked portainer and it was flagged unhealthy.

docker logs homepage outputs nothing at all. tried deleting and pulling image fresh, same issue.

other containers on same host reporting no issues and starting fine - any help appreciated

running :latest tag, wiped image, repulled and 

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - '3300:3000'
    volumes:
      - '${BINDMOUNTDIR}/homepage:/app/config'
      - '${DOCKERSOCK}:${DOCKERSOCK}'
```

### Container Logs

BLANK

### Browser Logs

NA

### Troubleshooting

Deleting container and image and pulling fresh, server reboots
