### DISCUSSION TITLE
HomePage  BUG

### DISCUSSION THREAD

**Discussion by JcSun-ba** [gethomepage/homepage#4434] [Support] [answered]
### Description

When I install HomePage in docker,it comes to "failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown" 

### homepage version

v0.9.13

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      TZ: Asia/Shanghai
      PUID: 1026 # optional, your user id
      PGID: 100 # optional, your group id
    ports:
      - 13000:3000
    volumes:
      - /volume1/docker/homepage/icons:/app/public/icons
      - /volume1/docker/homepage/images:/app/public/images
      - /volume1/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

### Troubleshooting

Start container homepage failed: {"message":"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"docker-entrypoint.sh\": executable file not found in $PATH: unknown"}.
