### DISCUSSION TITLE
Homepage HTTP Error 404 API request to my portainer

### DISCUSSION THREAD

**Discussion by Marcjaeger** [gethomepage/homepage#4437] [Support] [answered]
### Description

Hello, im experincing a weird problem with my homelab, which im in the progress of setting up.
Wanted to create a monitor for my homepage as to the status of my containers.

The API key was created in the Access token on the web interface of portainer.

![image](https://github.com/user-attachments/assets/b4f98254-c37a-4690-8f24-8b1136eecf69)

This is the logs of my homepage container:
error: <credentialedProxyHandler> HTTP Error 500 calling http://url:9000/api/endpoints//docker/containers/json?all=1
And i find it weird its trying to call for endpoints//docker which doesnt seem right

Does any1 have an idea to whats happening?

### homepage version

v0.9.13

### Installation method

Docker

### Configuration

```yaml
- Portainer:
        href: url:9000
        description: portainer
        icon: portainer.png
        siteMonitor: url:9000
        widget:
                type: portainer
                url: url:9000
                key: api_key
```

### Container Logs

(error: <credentialedProxyHandler> HTTP Error 500 calling http://url:9000/api/endpoints//docker/containers/json?all=1)

### Browser Logs

-------------------------------------

API Error: Unknown error
URL: url:9000/api/endpoints//docker/containers/json?all=1
Raw Error:
{
    "errno": -104,
    "code": "ECONNRESET",
    "syscall": "read"
}

### Troubleshooting

Logs etc.
