### DISCUSSION TITLE
Widget for Cronicle

### DISCUSSION THREAD

**Discussion by paulchaum** [gethomepage/homepage#4440] [General]
Hey, I have created a widget for [cronicle](https://github.com/jhuckaby/Cronicle).

The Cronicle widget retrieves the total number of success, the number failed events, the last success event date and the last failed event date.

Find your API key under `Admin > API Keys tab > Add API Key... > Create Key`.

Allowed fields: `["success", "failed", "lastSuccess", "lastFailed"]`.

Optionally, the widget can filter events with a list of event ids.

Note: events retrieved in descending chronological order.

I've tested it with [cronicle-edge](https://github.com/cronicle-edge/cronicle-edge) which is a fork of cronicle, but the API is the same.

![cronicle_widget](https://github.com/user-attachments/assets/0f7c6ead-eb8a-4c79-aca7-3a6d4497322b)

```yaml
- Cronicle:
    href: http://your.cronicle.host:port
    icon: https://cronicle.net/favicon.ico
    siteMonitor: http://your.cronicle.host:port
    widget:
      type: cronicle
      url: http://your.cronicle.host:port
      api_key: your_cronicle_api_key
      limit: 100  # Optional: the number of events (default 100)
      eventsIds:  # Optional: the list of events to filter
        - emXXX
        - emYYY
```

Check my fork if you are interested : https://github.com/paulchaum/homepage
