### DISCUSSION TITLE
Limit Number of Bookmark Groups Per Line in Rendered Page

### DISCUSSION THREAD

**Discussion by seifrajhi** [gethomepage/homepage#4444] [General]
Hi 

I have a question/request regarding the layout of bookmark groups in the rendered page.

Currently, I have six bookmark groups, and they are all aligned in one line, which makes it hard to read. I would like to have a way to limit the number of bookmark groups per line to three, so that after every three groups, a new line starts. This would greatly improve readability and organization.

Here is an example of my current `bookmarks.yaml`:

```yaml
bookmarks:
  - Group 1:
      - Subgroup 1:
          href: https://example.com/group1/subgroup1
          icon: "https://example.com/icons/group1-subgroup1.png"
      - Subgroup 2:
          href: https://example.com/group1/subgroup2
          icon: "https://example.com/icons/group1-subgroup2.png"
  - Group 2:
      - Subgroup 1:
          icon: "https://example.com/icons/group2-subgroup1.png"
          href: https://example.com/group2/subgroup1
          description: Description for Group 2 Subgroup 1
      - Subgroup 2:
          icon: "https://example.com/icons/group2-subgroup2.png"
          href: https://example.com/group2/subgroup2
          description: Description for Group 2 Subgroup 2
  - Group 3:
      - Subgroup 1:
          icon: "https://example.com/icons/group3-subgroup1.png"
          href: https://example.com/group3/subgroup1
          description: Description for Group 3 Subgroup 1
      - Subgroup 2:
          icon: "https://example.com/icons/group3-subgroup2.png"
          href: https://example.com/group3/subgroup2
          description: Description for Group 3 Subgroup 2
  - Group 4:
      - Subgroup 1:
          icon: "https://example.com/icons/group4-subgroup1.png"
          href: https://example.com/group4/subgroup1
          description: Description for Group 4 Subgroup 1
      - Subgroup 2:
          icon: "https://example.com/icons/group4-subgroup2.png"
          href: https://example.com/group4/subgroup2
          description: Description for Group 4 Subgroup 2
```

I would like the fourth group to start on a new line, ensuring that each line contains only three groups. Is there a way to achieve this layout in the current setup?

**Comment by seifrajhi** [comment]
Edit:
I found it in the docs:
```
layout:
  Media:
    style: row
    columns: 4
```
