### DISCUSSION TITLE
v0.10.0 broken?

### DISCUSSION THREAD

**Discussion by cleanmachine** [gethomepage/homepage#4452] [Support] [answered]
### Description

I noticed there was an update so I used Portainer to pull the latest version (v0.10.0) for the Docker version I have running on an Ubuntu server VM on Proxmox. All the content from my services.yaml was gone. Not API errors - just not there. Widgets and bookmarks are still there. I thought maybe I broke something so I installed the Proxmox VE Helper Script version with the same result. No content in the main section. Um, help?

PS - very new to Github, both from a user and an etiquette standpoint. Please be gentle.

### homepage version

v0.10.0

### Installation method

Docker

### Configuration

```yaml
My services.yaml file

- DLab servers and network:
    - Proxmox:
        icon: proxmox.png # icons found here https://github.com/walkxcode/dashboard-icons
        href: https://192.168.1.188:8006
        description: 3900X - Lancool II
        widget:
            type: proxmox
            url: https://192.168.1.188:8006
            username:  api@pam!homepage
            password:  dc56a05c-6bd6-4197-bf98-a6c2ed7e3e3a
            node: pve
    - DLab:
        icon: truenas.svg
        href: https://192.168.1.139
        description: 5600G - Fractal Define R5
        widget:
            type: truenas
            url: https://192.168.1.139/
            key: 1-SR7YuPHg3cKxacOHN7ijjfFmWQ5mzbviMXqWYrjkNTDm4AIhU2gKVfvh1f6AemFZ
   
    - Pi-Hole:
        icon: pi-hole.svg
        href: https://192.168.1.155/admin
        description: Pi-5 - Pi-Hole
        widget:
            type: pihole
            url: http://192.168.1.155
            version: 5 # required if running v6 or higher, defaults to 5
            key: 41dbdbea85c7b37a014d8de1e37a9dea6c6f4f394694273ede89a03cb73037b6 # optional    
            
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: http://192.168.1.206:3001/dashboard
        description: Uptime Kuma via Proxmox Helper Script
        widget:
            type: uptimekuma
            url: http://192.168.1.206:3001
            slug: dlab        

- Dlab services:

    - Plex:
        icon: plex.svg
        href: http://192.168.1.139:32400
        description: DLab - TrueNAS Chart container
        widget:
            type: plex
            url: http://192.168.1.139:32400
            key: ZsLr6-_9duesRtJp1Lxe # see https://www.plexopedia.com/plex-media-server/general/plex-token/

    - Nextcloud:
        icon: nextcloud.svg
        href: https://192.158.1.199
        description: UServeProx on Proxmox - Snap package
        widget:
            type: nextcloud
            url: https://192.168.1.199
            username: devin
            password: 8uhbgtrd8uhbgtrd

    - Portainer:
        icon: portainer.svg
        href: https://192.168.1.199:9443
        description: UServeProx on Proxmox - Docker container
        widget:
            type: portainer
            url: https://192.168.1.199:9443
            env: 2
            key: ptr_kOy1yM1jcoVg8/u1DsknxUXfvR9Y/KDuk1Z8DFgBNL8=

    - Immich:
        icon: immich.svg
        href: http://192.168.1.139:30041
        description: Immich on TrueNAS - Docker container
        widget:
            type: immich
            url: http://192.168.1.139:30041
            key: x96lJDev5LcsNqPF82XLS6ZDPbpGVZOZVr6qLLHM
            version: 2 # optional, default is 1        
       
- Calendar:
    - GCal:
        icon: google.svg
        href: https://calendar.google.com/calendar/u/0/r?tab=mc
        description: Google Calendar for devinbaines@gmail.com
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 30 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            integrations: # optional
            - type: ical # Show calendar events from another service
              url: https://calendar.google.com/calendar/ical/devinbaines%40gmail.com/private-10abe64e0d840276beeeb192fe568868/basic.ics # URL with calendar events
              name: Devin's Calendar # required - name for these calendar events
              color: zinc # optional - defaults to pre-defined color for the service (zinc for ical)
              params: # optional - additional params for the service
                showName: true # optional - show name before event title in event line - defaults to false
```

### Troubleshooting

As noted above, I tried a fresh install Proxmox Helper Script LXC install and same result.
