### DISCUSSION TITLE
v0.10.0 Broke my services.yaml - None are visible in the homepage.

### DISCUSSION THREAD

**Discussion by CodeWithCJ** [gethomepage/homepage#4453] [Support] [answered]
### Description

v0.10.0 Broke my services.yaml - None are visible in the homepage. Reverting back to one version prior brings back my services. but upgrading to v0.10.0 hides them again. 

### homepage version

v0.10.0

### Installation method

Docker

### Configuration

```yaml
Setttings.yaml
--
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
layout:
  System:
    style: row
    columns: 7  # Full-width section for the top Glances widget
  Glances Grid:
    style: row
    columns: 3  # 3x2 grid for the other Glances widgets




---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services


  
- System:    
    - Glances:
        icon: glances.png
        siteMonitor: http://myIP:61208
        href: https://glances.mySite.buzz
    - Usage:    
        widget:
            type: glances
            url: http://myIP:61208
            version: 4
            metric: info
            diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
            refreshInterval: 1000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
            pointsLimit: 15 # optional, defaults to 15
    - CPU:
        widget:
            type: glances
            url: http://myIP:61208
            metric: cpu
            version: 4
            #chart: false
    - Memory:
        widget:
            type: glances
            url: http://myIP:61208
            version: 4
            metric: memory
            #chart: false
    - Temperature:
        widget:
            type: glances
            url: http://myIP:61208
            version: 4
            metric: sensor:pch_cannonlake 0
            #chart: falser
    - Network:
        widget:
            type: glances
            url: http://myIP:61208
            version: 4
            metric: network:wlx80afca2200de
            #chart: false
    - Disk:
        widget:
            type: glances
            url: http://myIP:61208
            version: 4
            metric: disk:sda
            #chart: false
    - Scrutiny:
        href: https://scrunity.mySite.buzz
        widget:
            type: scrutiny
            url: http://myIP:8005    
           
            
- Monitor:       
    - Adguard:
        href: https://adguard.mySite.buzz
        icon: /icons/AdGuard.png
        widget:
          type: adguard               
          url: http://10.0.0.10:8443
          username: qweqwe
          password: qweqwe$
         
    - NPM:
        href: https://nginx.mySite.buzz
        icon: nginx.png
        widget:
          type: npm
          url: http://myIP:81
          username: qweqwe@gmail.com
          password: qweqwe$
          icon: nginx.png
```

### Container Logs

Listening on port 3000

### Browser Logs

No log

### Troubleshooting

Downgrading to v0.9.13 fixes. Upgrading to v0.10.0, removes apps listed under services.yaml in the browser. I can see glances alone. Rest of the items such as adguard, nginx are disappeared.
