### DISCUSSION TITLE
[Feature Request] The service container has blank space at the bottom

### DISCUSSION THREAD

**Discussion by paulchaum** [gethomepage/homepage#4457] [Feature Requests]
### Description

When you have multiple services on the same row, some widgets blocks may have one-line labels and others may have more than one line. It creates a blank bellow the 1 line widgets.

I've made a custom CSS to fix this, you can put it in your `config/custom.css`:

```css
.service > div:first-child {
    display: flex;
    flex-direction: column;
}

.service > div:first-child > div:nth-child(2) {
    flex-grow: 1;
}
```

Before :
![before](https://github.com/user-attachments/assets/099e8213-8301-49f9-b6f9-69c794bb5f29)

After :
![after](https://github.com/user-attachments/assets/013242d6-983c-43dc-9942-d208534743af)

Or if you prefer them to be placed at the bottom, you can use this CSS:
```css
.service > div:first-child {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}
```
But this last rule may brakes some widgets like Glance which has `absolute` style:
![space_between](https://github.com/user-attachments/assets/b1fcb428-9ddd-401c-be9f-3b7a1df8b76c)

### Other

The Cronicle widget is custom (see discussion #4440)

Here is my `services.yaml`:
```yaml
- Utilities:
    - AdGuard:
        icon: /images/adguard_favicon.ico
        siteMonitor: https://xxx
        href: https://xxx
        widget:
          type: adguard
          url: https://xxx
          username: xxx
          password: xxx
    - WireGuard:
        href: https://xxx
        icon: /images/wireguard_favicon.ico
        siteMonitor: https://xxx
        widget:
          type: wgeasy
          url: https://xxx
          password: xxx
    - Cronicle:
        href: https://xxx
        icon: /images/cronicle_favicon.ico
        siteMonitor: https://xxx
        widget:
          type: cronicle
          url: https://xxx
          api_key: xxx
    - Glances:
        href: https://xxx
        icon: /images/glances_favicon.ico
        siteMonitor: https://xxx
        widget:
          type: glances
          url: https://xxx
          metric: cpu
          version: 4
          chart: false
```

Here is my `settings.yaml`:
```yaml
layout:
  Utilities:
    style: row
    columns: 4
```
