### DISCUSSION TITLE
custom search stopped working

### DISCUSSION THREAD

**Discussion by henkiewie** [gethomepage/homepage#446] [Support]
Hi,

I haven't used the custom search too much lately.
But it stopped working . So I can not say with what version this started to happen.
widgets.yaml;

```
- search:
    #provider: duckduckgo
    provider: custom
    url: https://search.rpi-lite.lan/?q=
    target: _blank

```
The Url goes to my docker searxng instance which works fine outside homepage.
(I have an internal DNS running) pointing to an nginx proxy manager
It used to work OK the browser console looks like this.

![Screenshot 2022-10-25 at 09 25 27](https://user-images.githubusercontent.com/74558874/197711436-76c82c74-eef0-4016-a12d-a20e95da4eff.png)

When I change  it to duckduckgo like the examples in the wiki the search works. I also have the same URL in another menu applet  and that one still works. Also tested the URL outside my proxy http://192.168.1.29:9017/?q= same result.

Any ideas?
