### DISCUSSION TITLE
Wrong disk in resources widget

### DISCUSSION THREAD

**Discussion by nerdlich** [gethomepage/homepage#4461] [Support] [answered]
### Description

Pretty much every time after the homepage container gets recreated or even just restarted, the disk usage for the disk "Data" displays the information of the disk "/". After another 5-10 manual restarts of the container, finally the data for the correct disk is displayed. It only ever affects the "Data" disk, "/" and "Backup" are always correct.

Host fstab:
```
/dev/disk/by-id/dm-uuid-LVM-5edeTc8Tfgb0yYWlKtLKCt24m8rOWEdM7jb1UZOhpQoLXCGSyyMfbzOVGfMURqvN / ext4 defaults 0 1
/dev/disk/by-uuid/0081bc19-69d2-43d5-b4f2-6705add11cf9 /srv/docker	ext4	defaults	0	0
/dev/disk/by-uuid/d1e193b9-8b26-4d7d-b8b7-f8e691b53be6 /srv/backup	ext4	defaults	0	0
```

docker-compose.yml:
```
  homepage:
    volumes:
      - ./homepage:/app/config
      - /srv/docker:/srv/docker:ro
      - /srv/backup:/srv/backup:ro
```

widgets.yaml:
```
- resources:
    label: System
    expanded: true
    cpu: true
    memory: true
    disk: /
- resources:
    label: Data
    expanded: true
    disk: /srv/docker
- resources:
    label: Backup
    expanded: true
    disk: /srv/backup
```

### homepage version

v0.10.1

### Installation method

Docker

### Troubleshooting

Tried to remove "/" disk, change order of disks, it's always "Data" that displays info of "/".
