### DISCUSSION TITLE
[BUG] - Glances chart: false text placement incorrect

### DISCUSSION THREAD

**Discussion by Ryland0** [gethomepage/homepage#4464] [Support] [answered]
### Description

The CPU, Memory and Network text alignment is showing incorrectly with chart: false enabled. Disk and Thermal are fine.

![image](https://github.com/user-attachments/assets/6bddfef2-52b4-4f13-8288-1a03ad2daedc)

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
- Glances:
  - CPU:
      widget:
        type: glances
        url: http://10.47.20.107:61208
        metric: cpu
        chart: false
  - Memory:
      widget:
        type: glances
        url: http://10.47.20.107:61208
        metric: memory
        chart: false
  - Network:
      widget:
        type: glances
        url: http://10.47.20.107:61208
        metric: network:eth0
        chart: false
  - Disk:
      widget:
        type: glances
        url: http://10.47.20.107:61208
        metric: disk:nvme0n1
        chart: false
  - Thermal:
      widget:
        type: glances
        url: http://10.47.20.107:61208
        metric: sensor:Package id 0
        chart: false
```
### Troubleshooting

Homepage and Glances containers restarted.
chart: false removed - all good
chart: false added - not good
