### DISCUSSION TITLE
Homepage calendar with *arr applications layout

### DISCUSSION THREAD

**Discussion by ssadun** [gethomepage/homepage#4472] [Support] [answered]
### Description

Hello All,

Currently my "settings.yaml" contains below lines. I've question regarding the layout I'll paste what I want to achieve as below. Is it possible to have a layout like this?

```
layout:
  Media:
    style: row
    columns: 3
  Synology:
    style: row
    columns: 3
  Management:
    style: row
    columns: 3
```

![image](https://github.com/user-attachments/assets/65c99b66-8dd8-4e1d-a2a3-53f4214eddff)

### homepage version

v0.10.2

### Installation method

Docker

### Troubleshooting

Looked at below link and saw similar config however this config has missing *arr applications widgets

https://gethomepage.dev/widgets/services/calendar/

![image](https://github.com/user-attachments/assets/1a21dde1-f988-4719-9c95-9ebc3c20c05d)

**Comment by owennewo-dev** [comment]
I'm not sure I understand what you want to achieve, does this drawing look good to you?
![image](https://github.com/user-attachments/assets/2b9827af-c344-442c-b00d-1bf098479bc2)
If this is what you are trying to get, you might be able to with the new nested widgets feature in release `v0.10.0`

https://gethomepage.dev/configs/settings/#nested-groups

**Comment by ssadun** [comment, marked as answer]
Hello All,

I achieved desired screen by following configuration:

**Screen:**
![screencapture-nas-3080-2024-12-29-21_14_33](https://github.com/user-attachments/assets/d0921712-d3d2-49f5-a8f3-018f86de24f5)

**settings.yaml**
```
..
layout:
# ----------------
  TV Shows & Movies:
     header: true
     style: row
     columns: 3
     Calendar:
       header: false
       style: row
       columns: 1
     Media:
       header: false
       style: row
       columns: 1
     .:
       header: false
       style: row
       columns: 1

```
**services.yaml**
```
...
- TV Shows & Movies:
    - Calendar: 
        - Calendar Widget:
            header: false
            #icon: /icons/ms-calendar.png
            widget:
                type: calendar
                firstDayInWeek: monday
                view: monthly
                maxEvents: 10
                showTime: true
                timezone: Europe/Istanbul
                integrations:
                    - type: sonarr
                      service_group: Media
                      service_name: Sonarr
                      color: teal
                      params:
                        unmonitored: false
                    - type: radarr
                      service_group: Media
                      service_name: Radarr
                      color: amber
                      params:
                        unmonitored: false
    - Media:
        - Plex:
            icon: /icons/plex-media-server.png
            href: ***
            container: plex
            widget:
                type: plex
                url: ***
                key: *** # see https://www.plexopedia.com/plex-media-server/general/plex-token/
        - Radarr:
            icon: /icons/radarr.png
            href: ***
            container: radarr
            widget:
                type: radarr
                url: ***
                key: ***
        - Sonarr:
            icon: /icons/sonarr.png
            href:***
            container: sonarr
            widget:
                type: sonarr
                url: ***
                key: ***
    - .:
        - Overseerr:
            icon: overseerr
            href: ***
            container: overseerr
            widget:
                type: overseerr
                url: ***
                key: ***
        - Prowlarr:
            icon: prowlarr
            href: ***
            container: prowlarr
            widget:
                type: prowlarr
                url: ***
                key: ***
        - Bazarr:
            icon: bazarr
            href: ***
            container: bazarr
            widget:
                type: bazarr
                url: ***
                key: ***

```
