### DISCUSSION TITLE
[Feature Request] Docker autodiscovery labels - string replacements

### DISCUSSION THREAD

**Discussion by mlofjard** [gethomepage/homepage#4476] [Feature Requests] [answered]
### Description

I would like the autodiscovery docker labels to have some basic string replacements available for e.g. container name and image/tag. These are already fetched from the API through the docker.listContainers() call.

Example docker-compose:
```yaml
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    ports:
      - 8096:8096
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=$${name} # Will be replaced with 'emby'
      - homepage.icon=emby.png
      - homepage.href=http://emby.home/
      - homepage.description=$${image} # Will be replaced with 'lscr.io/linuxserver/emby:latest'
```
