### DISCUSSION TITLE
Glances widgets size changed after update

### DISCUSSION THREAD

**Discussion by owennewo-dev** [gethomepage/homepage#4477] [Support] [answered]
### Description

I just updated to v0.10.2 and my glances widgets are all weird sizes, there is extra blank space at the bottom under the graph that wasn't there before, and they converge with my bookmarks. Also the bookmarks have less space between them than they used to.

I thought this was fixed in the v0.10.2 update.

I am using the TrueNAS Scale community app for Homepage.

Widgets after update:
![Screenshot 2024-12-23 105657](https://github.com/user-attachments/assets/2513b00f-824b-4e94-bac7-5507fedc10fc)
How they looked before:
![Screenshot 2024-12-12 203032](https://github.com/user-attachments/assets/b96b2740-8984-430c-9572-fd5d7295f751)

### homepage version

v0.10.2

### Installation method

Other (please describe above)

### Configuration

```yaml
settings.yaml


layout:
  Services:
    style: row
    columns: 4
    header: false
  iframes:
    style: row
    columns: 3
    header: false
  Graphs1:
    style: row
    columns: 4
    header: false
  Graphs2:
    style: row
    columns: 3
    header: false
  Personal:
    style: row
    columns: 7
    disableCollapse: true
    header: false
  Photography:
    style: row
    columns: 3
    disableCollapse: true
    header: false
  Homepage:
    style: row
    columns: 6
    disableCollapse: true
    header: false
  View Assist:
    style: row
    columns: 4
    header: false
  Shopping:
    style: column
    columns: 1
    initiallyCollapsed: true
  Software:
    style: column
    columns: 1
    initiallyCollapsed: true
  Github:
    style: column
    columns: 1
    initiallyCollapsed: true
  Web Tools:
    style: column
    columns: 1
    initiallyCollapsed: true
```

### Troubleshooting

n/a
