### DISCUSSION TITLE
Service statuses visible on search suggestions.

### DISCUSSION THREAD

**Discussion by Zuko** [gethomepage/homepage#4483] [Support] [answered]
### Description

![image](https://github.com/user-attachments/assets/85cb8c34-544c-496f-a2e5-c0c59c0f932b)

https://github.com/gethomepage/homepage/discussions/3678 is locked. I still have that issue.

### homepage version

v0.10.3 (31c0400, Dec 24, 2024)

### Installation method

Docker

### Configuration

```yaml
- search:
    provider: [google, bing, duckduckgo] # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
    target: _blank # One of _self, _blank, _parent or _top
```

### Troubleshooting

.

**Comment by shamoon** [comment]
It may have come back with recent changes, I can check later. What browser is that?

**Reply by Zuko** [reply]
Screenshot is from Chrome: 131.0.6778.205

But I checked also on:
Firefox: 133.0.3
Edge: 131.0.2903.112

**Comment by shamoon** [comment]
Hmm, I cant reproduce this, Im trying to think if theres something else about your setup Im not replicating, can you post your settings.yaml and widgets.yaml?

<img width="1102" alt="Screenshot 2024-12-23 at 6 04 19 PM" src="https://github.com/user-attachments/assets/64e77c24-342c-4375-93b7-583936495531" />
<img width="1129" alt="Screenshot 2024-12-23 at 6 04 24 PM" src="https://github.com/user-attachments/assets/ea372d83-484a-46b1-96ae-16ed1e09285b" />

**Comment by shamoon** [comment, marked as answer]
Think I got it. You can try out the `dev` image when its done building ~20 minutes from now if youre curious

#4484

**Reply by Zuko** [reply]
Sorry I didn't notice your reply yesterday.

![image](https://github.com/user-attachments/assets/6aece72d-f966-409b-a754-ea60097fe9d6)

;-)

```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: My Stuff

headerStyle: clean
useEqualHeights: true
theme: dark
color: slate

layout:
  Statuses:
    header: false
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
```
