### DISCUSSION TITLE
Abnormal changes in transparency of service tags

### DISCUSSION THREAD

**Discussion by lutinglt** [gethomepage/homepage#4485] [Support] [answered]
### Description

When my mouse hovers over a service tag, it causes a change in the transparency of other tags

Please ignore the flicker in the GIF and pay attention to the right half of the middle column. In fact, throughout the entire process, other columns are also changing

![GIF 2024-12-24 11-52-23](https://github.com/user-attachments/assets/948252f7-7d28-4a02-8e42-3f8c64955a9a)

My customized CSS only changed the font

```css
* {
    font-family: 'Maple Hand';
}
```

### homepage version

v0.10.3

### Installation method

Docker

### Browser Logs

Chrome 131.0.6778.205
Firefox 134.0b10

### Troubleshooting

There are only two nested layers, one is 4 rows and the other is 5 rows,
This phenomenon was observed during testing from v0.10.1 to v0.10.3

**Comment by shamoon** [comment]
I dont really know what's happening here but I cant reproduce it and it hasn't been reported.

Perhaps try paring back the settings (background blur etc) and see if anything helps)


https://github.com/user-attachments/assets/dc5c7be3-0061-4008-9ac5-a46c6be8ee1e

**Reply by lutinglt** [reply]
You're right, I only set the background image, and when I removed the background image, this phenomenon disappeared

**Reply by lutinglt** [reply]
Keeping the background image and removing the blurry effect of the card will also eliminate this phenomenon

**Reply by shamoon** [reply]
Still no issues for me with backgrounds, including with filters

https://github.com/user-attachments/assets/8b1560ca-718e-4d7a-a878-abd40986bab5

https://github.com/user-attachments/assets/c2480112-d162-4747-852a-de78561ba393

**Reply by lutinglt** [reply]
After experimentation, it was found that triggering occurs only when the columns of two layers are different. This effect becomes more pronounced when cardBlur is set to xl.

```yaml
cardBlur: xl
layout:
  Group1:
    header: false
    style: row
    columns: 4
    App:
      header: false
    Tool:
      header: false
    DataService:
      header: false
    Manage:
      header: false
  Group2:
    header: false
    style: row
    columns: 5
    Monitor:
      header: false
    Data:
      header: false
    Service1:
      header: false
    Service2:
      header: false
    DevService:
      header: false
```

**Reply by shamoon** [reply]
Still nothing. If you're up for it, post your entire services + settings yaml?


https://github.com/user-attachments/assets/1127a40b-7162-42e3-9cef-ddf65c758808


https://github.com/user-attachments/assets/916367fb-09cb-415c-a3d3-4fa61203168c

**Reply by lutinglt** [reply]
I removed the section about links and widgets

services.yaml

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/

- Group1:
    - App:
        - Jellyfin:
            icon: /icons/high/Jellyfin_B.png
            server: my-docker
            container: jellyfin
        - PhotoPrism:
            icon: /icons/high/Photoprism_A.png
            server: my-docker
            container: photoprism
        - Komga:
            icon: /icons/high/Komga_A.png
            server: my-docker
            container: komga
    - Tool:
        - Files:
            icon: /icons/files.png
            server: my-docker
            container: files
        - Blinko:
            icon: /icons/blinko.png
            server: my-docker
            container: blinko
        - Git:
            icon: /icons/high/Git_A.png
            server: my-docker
            container: git
        - Mail:
            icon: /icons/png/poste.png
            server: my-docker
            container: mail
    - DataService:
        - Superset:
            icon: /icons/high/Superset_A.png
            server: my-docker
            container: superset
        - Airflow:
            icon: /icons/high/Airflow_B.png
            server: my-docker
            container: airflow
        - OpenMetadata:
            icon: /icons/high/Open-metadata_A.png
            server: my-docker
            container: openmetadata
        - SelectDB WebUI:
            icon: /icons/high/Selectdb_A.png
            server: my-docker
            container: selectdb
    - Manage:
        - Grafana:
            icon: /icons/high/Grafana_A.png
            server: my-docker
            container: grafana
        - Portainer:
            icon: /icons/high/Portainer_B.png
            server: my-docker
            container: portainer
        - qBittorrent:
            icon: /icons/high/Qbittorrent_A.png
            server: my-docker
            container: qbittorrent

- Group2:
    - Monitor:
        - Scrutiny:
            icon: /icons/high/Scrutiny_A.png
            server: my-docker
            container: scrutiny
        - UptimeKuma:
            icon: /icons/high/Uptimekuma_B.png
            server: my-docker
            container: uptimekuma
        - AdGuard:
            icon: /icons/high/Adguard_A.png
            server: my-docker
            container: adguard
        - Prometheus:
            icon: /icons/high/Prometheus_A.png
            server: my-docker
            container: prometheus
    - Data:
        - Doris FE:
            icon: /icons/high/Doris_A.png
            server: my-docker
            container: fe
        - Doris BE:
            icon: /icons/high/Doris_A.png
            server: my-docker
            container: be
        - MinIO:
            icon: /icons/high/Minio_C.png
            server: my-docker
            container: minio
        - Lakekeeper:
            icon: /icons/high/Lakekeeper_A.png
            server: my-docker
            container: lakekeeper
        - IcebergCatalog:
            icon: /icons/high/Iceberg_A.png
            server: my-docker
            container: iceberg
        - Postgres:
            icon: /icons/high/Postgresql_A.png
            server: my-docker
            container: postgres
        - ElasticSearch:
            icon: /icons/high/Elastic_B.png
            server: my-docker
            container: elastic

    - Service1:
        - Glances:
            icon: /icons/glances.png
            server: my-docker
            container: glances
        - Nexus:
            icon: /icons/nexus3.png
            server: my-docker
            container: nexus
        - NGINX:
            icon: /icons/high/Nginx_A.png
            server: my-docker
            container: nginx
        - Clash:
            icon: /icons/high/Clash_B.png
            server: my-docker
            container: clash
        - MTProto:
            icon: /icons/high/Telegram_B.png
            server: my-docker
            container: mtproto
        - OAuth2Proxy:
            icon: /icons/high/Oauth2proxy_A.png
            server: my-docker
            container: oauth2-proxy

    - Service2:
        - Syncthing:
            icon: /icons/high/Syncthing_A.png
            server: my-docker
            container: syncthing
        - Vaultwarden:
            icon: /icons/high/Bitwarden_A.png
            server: my-docker
            container: vaultwarden
        - AppDB:
            icon: /icons/high/Postgresql_B.png
            server: my-docker
            container: appdb
        - Samba:
            icon: /icons/png/windows-11.png
            server: my-docker
            container: samba
        - Homepage:
            icon: /icons/high/Homepage_B.png
            server: my-docker
            container: homepage
        - NodeExporter:
            icon: /icons/high/Prometheus_B.png
            server: my-docker
            container: nodeexporter

    - DevService:
        - Ingestion:
            icon: /icons/high/Open-metadata_A.png
            server: my-docker
            container: ingestion
        - Container:
            icon: /icons/high/Debian_A.png
            server: my-docker
            container: container
        - Runner:
            icon: /icons/high/Docker_D.png
            server: my-docker
            container: runner
        - Code:
            icon: /icons/high/Vscode_C.png
            server: my-docker
            container: code
        - Jupyter:
            icon: /icons/png/jupyter.png
            server: my-docker
            container: jupyter
        - GitHub:
            icon: /icons/high/Github_A.png
            server: my-docker
            container: github
```

settings.yaml

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

language: zh-CN
headerStyle: boxed
hideVersion: true
hideErrors: true
theme: dark
color: slate
showStats: true
statusStyle: dot
cardBlur: xl
disableCollapse: true
fiveColumns: true
background:
  image: /icons/paper/bg.png
layout:
  Group1:
    header: false
    style: row
    columns: 4
    App:
      header: false
    Tool:
      header: false
    DataService:
      header: false
    Manage:
      header: false
  Group2:
    header: false
    style: row
    columns: 5
    Monitor:
      header: false
    Data:
      header: false
    Service1:
      header: false
    Service2:
      header: false
    DevService:
      header: false
```
