### DISCUSSION TITLE
Beszel widget integration error

### DISCUSSION THREAD

**Discussion by rcbop** [gethomepage/homepage#4492] [Support] [answered]
### Description

As commented here:
- https://github.com/gethomepage/homepage/pull/4488
- https://github.com/henrygd/beszel/issues/336

I'm experiencing errors in the Beszel widget after their update to 0.9.0 that changed their API endpoint. Initially, while troubleshooting, I had the `homepage.widget.username` replaced in my labels configuration with my username (rcbop), but it should be the email. So then the error changed from `TypeError: Cannot read properties of undefined (reading 'find')` to the one below.

### homepage version

v0.10.4 (cc9b478)

### Installation method

Docker

### Configuration

```yaml
beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - /opt/docker-services/data/config/beszel:/beszel_data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.mydomain.com`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.services.beszel.loadbalancer.server.port=8090
      - homepage.group=Infrastructure
      - homepage.name=Beszel
      - homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/beszel-light.webp
      - homepage.href=https://beszel.mydomain.com
      - homepage.description=Monitoring solution
      - homepage.widget.type=beszel
      - homepage.widget.url=https://beszel.mydomain.com
      - homepage.widget.username=xxxxx@email.com
      - homepage.widget.password=xxxxxxx
      - homepage.widget.systemId=rrsa25j8p920ukn
      - homepage.widget.version=2
```

### Container Logs

```
/opt/docker-services/config/monitoring# docker logs homepage -f
Listening on port 3000
```

### Browser Logs

```
framework-fb129ad84e3a607e.js:1 TypeError: Cannot read properties of undefined (reading 'name')
    at u (9926.176fd2cdabe47be3.js:1:1649)
    at vo (framework-fb129ad84e3a607e.js:1:60606)
    at Cu (framework-fb129ad84e3a607e.js:1:74832)
    at Si (framework-fb129ad84e3a607e.js:1:121267)
    at ys (framework-fb129ad84e3a607e.js:1:109320)
    at vs (framework-fb129ad84e3a607e.js:1:109248)
    at hs (framework-fb129ad84e3a607e.js:1:109111)
    at ls (framework-fb129ad84e3a607e.js:1:105891)
    at rs (framework-fb129ad84e3a607e.js:1:104442)
    at S (framework-fb129ad84e3a607e.js:1:138430)
```

```javascript
i.jsxs)(s.Z, {
    service: u,
    children: [(0,
    i.jsx)(a.Z, {
        label: "beszel.name",
        value: p.name
    }), (0,
```

### Troubleshooting

```
/opt/docker-services/config/monitoring# docker exec homepage ping beszel.mydomain.com
PING beszel.mydomain.com (192.168.1.73): 56 data bytes
64 bytes from 192.168.1.73: seq=0 ttl=64 time=0.040 ms
64 bytes from 192.168.1.73: seq=1 ttl=64 time=0.048 ms
64 bytes from 192.168.1.73: seq=2 ttl=64 time=0.129 ms
^Ccontext canceled
```
