### DISCUSSION TITLE
nextclould status not nowrking

### DISCUSSION THREAD

**Discussion by arpanrec** [gethomepage/homepage#4497] [Support]
### Description

Next cloud version `30.0.4`

### homepage version

v0.10.4

### Installation method

Docker

### Configuration

```yaml
- Nextcloud:
            icon: nextcloud
            href: https://xxx.xxx.xxx.xxx:xxxxx
            description: https://xxx.xxx.xxx.xxx:xxxxx
            ping: xxx.xxx.xxx.xxx:xxxxx
            widget:
                type: nextcloud
                url: https://xxx.xxx.xxx.xxx:xxxxx
                key: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

```text
Something went wrong.
TypeError: Cannot read properties of undefined (reading 'system')

    at i (http://127.0.0.1:3000/_next/static/chunks/72.0dc8d1a37a336a07.js:1:1056)
    at h (http://127.0.0.1:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:34754)
    at n (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:17845)
    at R (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:35491)
    at div
    at li
    at M (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:39445)
    at ul
    at W (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:43571)
    at div
    at http://127.0.0.1:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:79373
    at div
    at l (http://127.0.0.1:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:108173)
    at http://127.0.0.1:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:97547
    at http://127.0.0.1:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:96315
    at l (http://127.0.0.1:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:108173)
    at http://127.0.0.1:3000/_next/static/chunks/9201-12240fd0587e22ee.js:1:77312
    at div
    at J (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:44097)
    at div
    at div
    at ge (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:65997)
    at n (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:17845)
    at http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:90724
    at ve (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:64005)
    at div
    at div
    at div
    at we (http://127.0.0.1:3000/_next/static/chunks/pages/index-898edf86f22783e3.js:1:72914)
    at a (http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:16132)
    at a (http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:15775)
    at s (http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:16691)
    at u (http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:15203)
    at http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:90724
    at http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:14454
    at l (http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:1250)
    at n (http://127.0.0.1:3000/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:5696)
    at r (http://127.0.0.1:3000/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:6996)
    at Y (http://127.0.0.1:3000/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:9244)
    at ie (http://127.0.0.1:3000/_next/static/chunks/main-0ddda9b10
```
