### DISCUSSION TITLE
Grouping Medusa Widget Breaks

### DISCUSSION THREAD

**Discussion by kevjustice** [gethomepage/homepage#4499] [Support]
### Description

I tried the new services grouping feature and it seems great, however the Medusa widget does not work when it's in a sub group.  I decided to replicate it in the group, not the subgroup and the exact same configuration works in a group.

![image](https://github.com/user-attachments/assets/5b843c92-808b-4e92-b5b7-d85759ce3385)

I have a hunch that your widget code does not search for sub-groups and fails to find the group of the name.  Just a theory...

Note: I have suppressed the full IP and keys in logs/configs.

### homepage version

v0.10.5

### Installation method

Docker

### Configuration

```yaml
- Media (Local):
    - Medusa:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/medusa.png
        href: http://10.10.1.XX:8681
        siteMonitor: http://10.10.1.XX:8681
        container: medusa
        widget:
          type: medusa
          url: http://10.10.1.XX:8681
          key: XXXXXXXX
    - Services:
        - Medusa2:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/medusa.png
            href: http://10.10.1.XX:8681
            siteMonitor: http://10.10.1.XX:8681
            container: medusa
            widget:
              type: medusa
              url: http://10.10.1.XX:8681
              key: XXXXXXXX
```

### Container Logs

Nothing in logs related to that ip/port.

### Browser Logs

XHRGET
http://10.10.1.YY:3000/api/siteMonitor?groupName=Services&serviceName=Medusa2
[HTTP/1.1 400 Bad Request 122ms]

	
GET
	http://10.10.1.YY:3000/api/siteMonitor?groupName=Services&serviceName=Medusa2
Status
400
Bad Request
VersionHTTP/1.1
Transferred280 B (56 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem

    	
    Connection
    	keep-alive
    Content-Length
    	56
    Content-Type
    	application/json; charset=utf-8
    Date
    	Fri, 27 Dec 2024 14:31:04 GMT
    ETag
    	"wtsb17kgvt1k"
    Keep-Alive
    	timeout=5
    Vary
    	Accept-Encoding
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	history-detailed-sort=%5B%7B%22field%22%3A%22date%22%2C%22type%22%3A%22desc%22%7D%5D; showResults-sort-field=%5B%22quality%22%5D; showResults-sort-type=%5B%22desc%22%5D; mass-update-sort-field=%5B%22title%22%5D; mass-update-sort-type=%5B%22asc%22%5D; mass-update-Show%20name=null; mass-update-Quality=null; mass-update-Sports=null; mass-update-Scene=null; mass-update-Anime=null; mass-update-Season%20folders=null; mass-update-DVD%20order=null; mass-update-Paused=null; mass-update-Subtitle=null; mass-update-Def…O3TzsHr_a1ID7Y_KlNo-2Qt3Vq31Yzo; portainer_api_key=HIDDDEN!!!; _gorilla_csrf=MTczNTMwODM3M3xJbGxYWlVock1HTkxNa2w0YVhBek5ISXhXa0pvY2l0TWJHTkZWM1pRV0RaRmFrcHJWRVpxUjI5Qk1qQTlJZ289fISnRXvGKPRJNGIlZnbH5dqd9BDqBd_pgI8wTypy6bIM
    Host
    	10.10.1.YY:3000
    Priority
    	u=4
    Referer
    	http://10.10.1.YY:3000/
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0

### Troubleshooting

To assist troubleshooting, I renamed the 2nd Medusa to Medusa2.  It wass the one that caused the browser log.
