### DISCUSSION TITLE
Icon only style bookmarks padding issue

### DISCUSSION THREAD

**Discussion by owennewo-dev** [gethomepage/homepage#4500] [Support] [answered]
### Description

Thanks shamoon for fixing the padding on nested widgets! But we still have a problem...

My icon style bookmarks don't have enough padding on the bottom to prevent from merging into the bookmarks I have right under it.

![Screenshot 2024-12-27 091649](https://github.com/user-attachments/assets/fdfce71b-4ed0-473f-8fa3-5734a3785765)

It's mostly fine if I turn on the header for the bottom bookmarks group.

![{146E4EAC-0A84-4980-AF32-58A3F9276643}](https://github.com/user-attachments/assets/704c22bc-ae62-4dea-add9-ac2af68d566a)

I know I am not using the latest version, I am on `v0.10.4` (because of how long it takes for TrueNAS Scale apps to get updated), but when I looked at the changelog from `v0.10.4` to `v0.10.5` it looks like only changes related to Beszel and Glances were made.

![image](https://github.com/user-attachments/assets/8e07d335-c932-4b20-b660-75313851f552)

Thanks shamoon, I bet you are really tired of padding issues 😡

### homepage version

v0.10.4

### Installation method

Other (please describe above)

### Configuration

```yaml
  Personal:
    iconsOnly: true
    style: row
    columns: 1
    disableCollapse: true
    header: false
  Homepage:
    style: row
    columns: 6
    disableCollapse: true
    header: false
```

### Troubleshooting

n/a
