### DISCUSSION TITLE
Uptime Kuma widget "looking" for wrong URL?

### DISCUSSION THREAD

**Discussion by igorfrag** [gethomepage/homepage#4501] [Support] [answered]
### Description

I've used Homepage for a good year now, recently I tried to add Uptime Kuma to my dashboard and it seems that the hardcoded URL mismatch URL used by Kuma. Wondering if someone else has this problem or maybe its just on my end ?

Below you can see it requests http://ip:port/api/status-page/uptime   (uptime = name of my slug).

![widget](https://github.com/user-attachments/assets/7a0d1729-4623-4f4e-be41-29dd44957140)

But the status page I made uses a different URL : http://ip:port/status/uptime

Any help? Issue seems to be here maybe? https://github.com/gethomepage/homepage/blob/e4d42b5393a1cd6d191d8ba7bca926ccdc8947e0/src/widgets/uptimekuma/widget.js#L4C2-L4C38

I'm new to Github discussions so let me know if i need to change anything.

### homepage version

v0.10.5 (e4d42b5)

### Installation method

Docker

### Configuration

```yaml
Services file:
- Management:
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: http://ip:3001/
        description: Uptime tracking
        widget:
            type: uptimekuma
            url: http://ip:3001
            slug: uptime

```

### Troubleshooting

Already went through troubleshooting.
