### DISCUSSION TITLE
Suwayomi service is all zeros?

### DISCUSSION THREAD

**Discussion by Sonny-Crockett** [gethomepage/homepage#4503] [Support]
### Description

The service is working and reporting all the right things in Homepage, no API errors or anything.

But all the values are 0. Any ideas?

I don't have authentication so I have nothing in the username and password sections.

Is there a setting in Suwayomi (Tachidesk) I need to turn on?

### homepage version

v0.10.5

### Installation method

Unraid

### Configuration

```yaml
- Suwayomi:
        icon: tanoshi
        server: unraid
        container: Tachidesk-Docker
        href: http://192.168.ip:port
        widget:
            type: suwayomi
            url: http://192.168.1.ip:port
            username: #optional
            password: #optional
            category: 0 #optional, defaults to all categories
```

### Troubleshooting

Tried removing ports and got API error, removed Username and Password and also changed nothing.
