### DISCUSSION TITLE
Api Error when widget in side 2 layouts

### DISCUSSION THREAD

**Discussion by masterwishx** [gethomepage/homepage#4515] [Support]
### Description

 have `API Error: Unknown proxy service type` when have 2 parents layouts : 

```
- Management:
    - Cloud Server: 
        - Portainer:
            href: http://instance-mysite-cloud:9000
            icon: portainer.png
            description: Portainer on instance-mysite-cloud
            server: Local-mysite-cloud
            container: portainer
            widget:
                type: portainer
                url: http://100.64.0.4:9000
                env: 2
                key: {{HOMEPAGE_VAR_PORTAINER_1_KEY}}
```

### homepage version

0.10.6

### Installation method

Docker

### Container Logs

Only first nested layout is working : 

### Browser Logs

URL запроса:
http://instance-mysite-cloud:3005/api/siteMonitor?groupName=Home+Server&serviceName=Unraid
Метод запроса:
GET
Код статуса:
400 Bad Request

### Troubleshooting

![image](https://github.com/user-attachments/assets/94a2ccbe-3143-494d-ac27-5cba6460f2eb)
