### DISCUSSION TITLE
Calendar issue

### DISCUSSION THREAD

**Discussion by wioo** [gethomepage/homepage#4522] [Support] [answered]
### Description

If I click on December 30 or 31 (2024) all dots (movies and shows) disappears. On second click calendar jumps to December 2025.

### homepage version

v0.10.6

### Installation method

Docker

### Configuration

```yaml
- Calendar:
        icon: mdi-calendar-blank
        description: Calendar
        widget:
          type: calendar
          view: monthly
          maxEvents: 10 
          showTime: false 
          previousDays: 3 
          integrations:
            - type: sonarr 
              service_group: Services
              service_name: Sonarr
              color: teal 
              params: 
                unmonitored: true
            - type: radarr 
              service_group: Services
              service_name: Radarr
              color: yellow
              params: 
                unmonitored: true
```

### Troubleshooting

Dont know how to get output for calendar widget.
