### DISCUSSION TITLE
Bug with December 2024, calendar jumps to December 2025.

### DISCUSSION THREAD

**Discussion by DevDema** [gethomepage/homepage#4523] [Support] [answered]
### Description

https://github.com/user-attachments/assets/c0bf2944-c013-49b0-943a-46b7983aef56

As you can see from the recording, December 2024 shows no data coming from sonarr and radarr, but the integration is indeed working and news on the calendar are presenter for December 2024.
Once I tap on any of the days on the calendar, the calendar jumps off to December 2025. Going back to December 2024 data, the episodes and movie data are back again.

I suspect, that whilst showing December 2024, the Calendar is actually showing December 2025 data, which is correctly jumped to on mouse clicking the days.

### homepage version

v0.10.6

### Installation method

Docker

### Configuration

```yaml
- Events:
  - Calendar:
      widget:
        type: calendar
        firstDayInWeek: sunday # optional - defaults to monday
        view: monthly # optional - possible values monthly, agenda
        maxEvents: 10 # optional - defaults to 10
        showTime: true # optional - show time for event happening today - defaults to false
        timezone: Europe/Rome # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
        integrations: # optional
          - type: ical # Show calendar events from another service
            url: http://radarr:7878/feed/v3/calendar/Radarr.ics?apikey=xxx # hidden, URL with calendar events
            name: Radarr # required - name for these calendar events
            color: orange
          - type: ical # Show calendar events from another service
            url: http://sonarr:8989/feed/v3/calendar/Sonarr.ics?apikey=xxx # hidden, URL with calendar events
            name: Sonarr # required - name for these calendar events
            color: teal # optional - defaults to pre-defined color for the service (zinc for ical)
```

### Container Logs

No related interesting container logs available

### Browser Logs

No related interesting browserlogs available

### Troubleshooting

No troubleshooting necessary to experience this issue, since it's a view issue.
