### DISCUSSION TITLE
Can someone help me get the qnap widget working.

### DISCUSSION THREAD

**Discussion by Manny8787** [gethomepage/homepage#4524] [Support]
### Description

I have 2 qnaps and I am running homepage on my pc using docker desktop. 
I would like ot add the qnap widget to monitor both of the qnaps.  I have been though discord, reddit and github but cannot find anything directly to my issue. 

### homepage version

v0.10.6

### Installation method

Docker

### Configuration

```yaml
In the services.yml    

 - TS644:
        href: https://*******:645
        icon: qnap
        widget:
          type: qnap
          url: https://********:645/cgi-bin
          username: ******
          password: ******

    - TS251:
        href: https://*********:443
        icon: qnap
        widget:
          type: qnap
          url: https://*********:443/cgi-bin
          username: ******
          password: *******
```

### Container Logs

[2024-12-31T15:52:05.143Z] error: <qnapProxyHandler> QNAP API rejected the request, attempting to obtain new session token
[2024-12-31T15:52:09.941Z] error: <qnapProxyHandler> Unable to login to QNAP API: <ref *1> Error: Unexpected close tag
Line: 246
Column: 84
Char: >
    at error (/app/node_modules/.pnpm/sax@1.4.1/node_modules/sax/lib/sax.js:658:10)
    at strictFail (/app/node_modules/.pnpm/sax@1.4.1/node_modules/sax/lib/sax.js:684:7)
    at closeTag (/app/node_modules/.pnpm/sax@1.4.1/node_modules/sax/lib/sax.js:878:9)
    at SAXParser.write (/app/node_modules/.pnpm/sax@1.4.1/node_modules/sax/lib/sax.js:1460:13)
    at module.exports (/app/node_modules/.pnpm/xml-js@1.6.11/node_modules/xml-js/lib/xml2js.js:346:12)
    at module.exports (/app/node_modules/.pnpm/xml-js@1.6.11/node_modules/xml-js/lib/xml2json.js:13:8)
    at login (/app/.next/server/pages/api/services/proxy.js:7726:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async apiCall (/app/.next/server/pages/api/services/proxy.js:7751:11)
    at async qnapProxyHandler (/app/.next/server/pages/api/services/proxy.js:7831:7) {
  note: [Circular *1]
}
[2024-12-31T15:52:15.658Z] error: <qnapProxyHandler> Error getting data from QNAP: https://192.168.0.110/cgi-bin/cgi-bin/management/chartReq.cgi?chart_func=disk_usage&disk_select=all&include=all&sid=[object%20Object] status 404. Data: 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />
<link rel="shortcut icon" href="/images/favicon.gif" type="image/gif" />
<link rel="icon" href="/images/favicon.gif" type="image/gif" />
<style type="text/css">
body{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 11px;
background: #FFFFFF url('/cgi-bin/images/error/err_bg.jpg');
overflow: hidden;
color: #A4A3A3;
text-align: center;
}
.qnap_hyperlink a,.qnap_hyperlink a:link,.qnap_hyperlink a:visited{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 11px;
color: #A4A3A3;
}

### Troubleshooting

I have tried adding my user and group id to the compose and widget section in services.yml
using the ip address, server name, changing ports, https and http.
