### DISCUSSION TITLE
calendar widget doesn't like 12/31/2024

### DISCUSSION THREAD

**Discussion by jbeckman1974** [gethomepage/homepage#4526] [Support] [answered]
### Description

I had noticed prior to today that when clicking on 12/31/2024 that it would jump to 1/1/2025 and not show any of the "dots" for upcoming releases.  There are releases on that date that would have a dot, but they would go away as soon as I clicked on the `24` (for the Dec-2024 month).  I figured it was a glitch, but it was a repeatable glitch.  It has been working since I set it up (6-ish months ago) without any problems so I don't suspect it's a configuration issue, but I've included my configuration just in case.

Today, being 12/31/2024 starts off on todays date, but none of the dots for any of the December releases are shown - they were there yesterday.  When clicking on the `1` for 1/1/2025 it jumps the calendar to Jan 2026.  When clicking on any of the Dec-2024 dates it changes the header to "2025".  Something about today's date isn't liked by the app.

Sorry I didn't post this earlier as I did notice it a couple weeks ago, but hopefully you all can see what's going on readily. 

### homepage version

v0.10.6 (43decb0, Dec 28, 2024)

### Installation method

Docker

### Configuration

```yaml
- Calendar:
    - Media Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          maxEvents: 50
          showTime: true
          timezone: America/New_York
          integrations:
            - type: sonarr
              service_group: Arrs Stack
              service_name: Sonarr
              color: red
              params:
                unmonitored: true
            - type: radarr
              service_group: Arrs Stack
              service_name: Radarr
              color: yellow
              params:
                unmonitored: true
            - type: readarr
              service_group: Arrs Stack
              service_name: Readarr
              color: green
              params:
                unmonitored: true
```

### Troubleshooting

None
