### DISCUSSION TITLE
API Error: sonarr: Unknown proxy service type

### DISCUSSION THREAD

**Discussion by theliamllyd** [gethomepage/homepage#4529] [Support] [answered]
### Description

After inputting the calendar widget into homepage I'm met with the error: API Error: sonarr: Unknown proxy service type" Where am I going wrong?

### homepage version

v0.10.6

### Installation method

Docker

### Configuration

```yaml
# -- Calendar Start -- #
            - Upcoming Calendar:
                widget:
                    type: calendar
                    firstDayInWeek: monday # optional - defaults to monday
                    view: monthly # optional - possible values monthly, agenda
                    maxEvents: 10 # optional - defaults to 10
                    showTime: true # optional - show time for event happening today - defaults to false
                    timezone: Europe/London # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
                    integrations: # optional
                        - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
                          service_group: Media # group name where widget exists
                          service_name: Sonarr # service name for that widget
                          color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
                          params: # optional - additional params for the service
                            unmonitored: true # optional - defaults to false, used with *arr stack
# -- Calendar End -- #
```

### Browser Logs

GET http://macserver:3000/api/services/proxy?group=Media&service=Sonarr&index=0&endpoint=calendar&query=%7B%22start%22%3A%22%22%2C%22end%22%3A%22%22%2C%22unmonitored%22%3Atrue%2C%22includeSeries%22%3A%22true%22%2C%22includeEpisodeFile%22%3A%22false%22%2C%22includeEpisodeImages%22%3A%22false%22%7D 403 (Forbidden)

### Troubleshooting

Restarted homepage.
