### DISCUSSION TITLE
Glances - F.find is not a function

### DISCUSSION THREAD

**Discussion by theliamllyd** [gethomepage/homepage#4548] [Support]
### Description

Hello again, I'm having an issue with my glances installation where it appears like below, does anyone have an idea? I'm sat here scratching my head.
![Screenshot 2025-01-02 at 19 06 02](https://github.com/user-attachments/assets/a747da36-1407-4287-b3c1-6127c4c52894)
![Screenshot 2025-01-02 at 19 12 47](https://github.com/user-attachments/assets/34b49f2c-19c9-427b-a440-f502af81c003)

### homepage version

v0.10.7

### Installation method

Docker

### Configuration

```yaml
# -- Glances Start -- #
- Server Stats:
            - CPU Usage:
                widget:
                    type: glances
                    url: http://192.168.1.227:61208
                    metric: cpu
            - Memory Usage:
                widget:
                    type: glances
                    url: http://192.168.1.227:61208
                    metric: memory
            - Network Usage:
                widget:
                    type: glances
                    url: http://192.168.1.227:61208
                    metric: network:eth0
            - Disk Usage:
                widget:
                    type: glances
                    url: http://192.168.1.227:61208
                    metric: disk:/
# -- Glances End -- #
```

### Troubleshooting

Restarted container, checked for spelling mistakes.
