### DISCUSSION TITLE
Glances Widget - Is this the expected behavior?

### DISCUSSION THREAD

**Discussion by NiloDrumond** [gethomepage/homepage#4551] [Support] [answered]
### Description

I'm using the glances widgets and I find this file system one a little weird. Three different drives, all with the same y value on the graph.

![image](https://github.com/user-attachments/assets/1ab2eb50-1921-499e-b408-a38240f700b1)

Shouldn't the y value of the graph be proportional to the disk usage?

### homepage version

v0.10.7

### Installation method

Docker

### Configuration

```yaml
docker-compose

services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    ports:
      - 6404:3000
    volumes:
      - /home/nilo/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - /home/nilo/homepage/images:/app/public/images
    restart: unless-stopped
```

settings
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings
title: Akai Amaterasu

hideVersion: true

providers:
  openweathermap: key
  weatherapi: weatherapiapikey

headerStyle: clean

favicon: /images/amaterasu-sun.png
background:
  image: /images/amaterasu.jpg
  opacity: 30
cardBlur: md

theme: dark
color: zinc

useEqualHeights: true
layout:
  Services:
    style: row
    columns: 3
  Raspberry:
    style: row
    columns: 4
```

Relevant services
```yaml
  - SD Card:
      widget:
        type: glances
        url: valid_url
        username: username
        password: password
        version: 4
        metric: fs:/
  - Seagate:
      widget:
        type: glances
        url: valid_url
        username: username
        password: password
        version: 4
        metric: fs:/mnt/seagate
  - Argon One:
      widget:
        type: glances
        url: valid_url
        username: username
        password: password
        version: 4
        metric: fs:/mnt/argon-ssd
```

### Troubleshooting

No errors
