### DISCUSSION TITLE
local icons in service labels

### DISCUSSION THREAD

**Discussion by OBoudreaux** [gethomepage/homepage#4555] [Support] [answered]
### Description

Having trouble with locally hosted icons with discovery labels.  I've removed the container and rebuilt with the target icon in the mount point but that didn't do it.
![Capture](https://github.com/user-attachments/assets/849759ee-09d0-4ea5-8551-f99df96bea06)

### homepage version

v.0.10.7

### Installation method

Docker

### Configuration

```yaml
in the service compose.yaml:


    labels:  
      - homepage.group=ARRS
      - homepage.name=Streaming TV
      - homepage.weight=7
      - homepage.icon=/icons/cabernet.png
      - homepage.href=https://cabernet.$DOMAINNAME
```

in the homepage compose.yaml
```
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
      - $DOCKERDIR/appdata/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
```
```


### Container Logs

none

### Browser Logs

Failed to load resource: the server responded with a status of 404 ()  /icons/cabernet.png:1 

### Troubleshooting

Rebuilt the container. Tried quotes, tried spaces. Icon is readable.
Dashboard and selfh.st icons work fine
