### DISCUSSION TITLE
Bing search breaks app

### DISCUSSION THREAD

**Discussion by CodeWithCJ** [gethomepage/homepage#4565] [Support] [answered]
### Description

Updated to latest version via docker compose running in portainer. It shows below error . Previously glances use to shown in that place horizontally. now it shows as vertical and the error appears. 
![image](https://github.com/user-attachments/assets/2f08aa62-60ba-45ff-9955-9e5168ab62af)

### homepage version

v0.10.8

### Installation method

Docker

### Configuration

```yaml
Services.yaml

- System:    
    - Glances:
        icon: glances.png
        siteMonitor: http://MYIP:PORT
        href: https://glances.domain.com
    - Usage:    
        widget:
            type: glances
            url: http://MYIP:PORT
            version: 4
            metric: info
            diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
            refreshInterval: 1000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
            pointsLimit: 15 # optional, defaults to 15
    - CPU:
        widget:
            type: glances
            url: http://MYIP:PORT
            metric: cpu
            version: 4
            #chart: false
    - Memory:
        widget:
            type: glances
            url: http://MYIP:PORT
            version: 4
            metric: memory
            #chart: false
    - Temperature:
        widget:
            type: glances
            url: http://MYIP:PORT
            version: 4
            metric: sensor:pch_cannonlake 0
            #chart: falser
    - Network:
        widget:
            type: glances
            url: http://MYIP:PORT
            version: 4
            metric: network:wlx80afca2200de
            #chart: false
    - Disk:
        widget:
            type: glances
            url: http://MYIP:PORT
            version: 4
            metric: disk:sda
            #chart: false




settings.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
layout:
  System:
    style: row
    columns: 7  # Full-width section for the top Glances widget
  Glances Grid:
    style: row
    columns: 3  # 3x2 grid for the other Glances widgets
  Monitor:
    sytle: column
    columns: 1
  Media:
    sytle: column
    columns: 1
  Network:
    sytle: column
    columns: 1
```

### Container Logs

Listening on port 3005
[2025-01-05T21:20:28.355Z] error: undefined
[2025-01-05T21:20:28.455Z] error: undefined
[2025-01-05T21:20:45.382Z] error: undefined
[2025-01-05T21:20:45.385Z] error: undefined
[2025-01-05T21:20:49.799Z] error: undefined
[2025-01-05T21:20:49.805Z] error: undefined
[2025-01-05T21:21:12.518Z] error: undefined
[2025-01-05T21:21:12.522Z] error: undefined
[2025-01-05T21:23:40.115Z] error: undefined
[2025-01-05T21:23:40.120Z] error: undefined
[2025-01-05T21:53:00.881Z] error: undefined
[2025-01-05T21:53:00.885Z] error: undefined

### Browser Logs

search.search
Something went wrong.
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at button
    at https://home.my.domain.com/_next/static/chunks/9163-5f2dc6630e05e3f7.js:1:82618
    at div
    at div
    at l (https://home.my.domain.com/_next/static/chunks/9163-5f2dc6630e05e3f7.js:1:104261)
    at https://home.my.domain.com/_next/static/chunks/9163-5f2dc6630e05e3f7.js:1:79834
    at l (https://home.my.domain.com/_next/static/chunks/9163-5f2dc6630e05e3f7.js:1:104261)
    at https://home.my.domain.com/_next/static/chunks/9163-5f2dc6630e05e3f7.js:1:58284
    at div
    at r (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:13685)
    at form
    at v (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:5709)
    at y (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:6857)
    at h (https://home.my.domain.com/_next/static/chunks/9163-5f2dc6630e05e3f7.js:1:34754)
    at n (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:17857)
    at te (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:53467)
    at div
    at div
    at div
    at div
    at ge (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:66036)
    at n (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:17857)
    at https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:90724
    at ve (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:64044)
    at div
    at div
    at div
    at we (https://home.my.domain.com/_next/static/chunks/pages/index-afa6e8dd03c08451.js:1:73256)
    at a (https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:16132)
    at a (https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:15775)
    at s (https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:16691)
    at u (https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:15203)
    at https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:90724
    at https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:14454
    at l (https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:1250)
    at n (https://home.my.domain.com/_next/static/chunks/pages/_app-2da6463c8d7db6b5.js:1:5696)
    at r (https://home.my.domain.com/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:6996)
    at Y (https://home.my.domain.com/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:9244)
    at ie (https://home.my.domain.com/_next/static/chunks/main-0ddda9b10a00d3ad.js:1:11885)

### Troubleshooting

Reverting back to previous version works. But with latest version it shows below error 

![image](https://github.com/user-attachments/assets/315a9814-9dd5-4cdf-8fcc-525771e1df0d)
