### DISCUSSION TITLE
Background image not loading in V0.10.8

### DISCUSSION THREAD

**Discussion by 54ybl** [gethomepage/homepage#4567] [Support] [answered]
### Description

The background image should load and display properly, but it is not displayed, resulting in a solid background.
compose.yaml:
```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./app/config:/app/config # Make sure your local config directory exists
      - ./app/public/images:/app/public/images
      - ./app/public/icons:/app/public/icons
```
settings.yaml
```
background:
  image: /images/background.png
  blur: md # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 75 # 0-100

```

### homepage version

v0.10.8

### Installation method

Docker

### Configuration

```yaml
compose.yaml:

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./app/config:/app/config # Make sure your local config directory exists
      - ./app/public/images:/app/public/images
      - ./app/public/icons:/app/public/icons
```
settings.yaml
```
background:
  image: /images/background.png
  blur: md # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 75 # 0-100

```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

[2025-01-06T02:01:56.341Z] error: undefined
[2025-01-06T02:01:56.344Z] error: undefined
[2025-01-06T02:01:59.066Z] error: undefined
[2025-01-06T02:01:59.080Z] error: undefined
[2025-01-06T02:02:01.050Z] error: undefined
[2025-01-06T02:02:01.066Z] error: undefined
[2025-01-06T02:04:35.351Z] error: undefined
[2025-01-06T02:04:35.433Z] error: undefined
[2025-01-06T02:04:37.916Z] error: undefined
[2025-01-06T02:04:37.937Z] error: undefined
[2025-01-06T02:04:40.927Z] error: undefined
[2025-01-06T02:04:40.939Z] error: undefined
[2025-01-06T02:04:43.396Z] error: undefined
[2025-01-06T02:04:43.410Z] error: undefined
[2025-01-06T02:06:17.693Z] error: undefined
[2025-01-06T02:06:17.764Z] error: undefined
[2025-01-06T02:09:03.223Z] error: undefined
[2025-01-06T02:09:03.243Z] error: undefined
[2025-01-06T02:09:04.995Z] error: undefined
[2025-01-06T02:09:05.009Z] error: undefined
[2025-01-06T02:09:09.009Z] error: undefined
[2025-01-06T02:09:09.021Z] error: undefined
[2025-01-06T02:09:09.431Z] error: undefined
[2025-01-06T02:09:09.444Z] error: undefined
[2025-01-06T02:09:37.328Z] error: undefined
[2025-01-06T02:09:37.341Z] error: undefined
[2025-01-06T02:10:28.929Z] error: undefined
[2025-01-06T02:10:28.932Z] error: undefined
[2025-01-06T02:21:51.893Z] error: undefined
[2025-01-06T02:21:51.896Z] error: undefined
[2025-01-06T02:21:53.676Z] error: undefined
[2025-01-06T02:21:53.694Z] error: undefined
[2025-01-06T02:22:26.051Z] error: undefined
[2025-01-06T02:22:26.104Z] error: undefined
