### DISCUSSION TITLE
TypeError: undefined is not an object (evaluating 'f.givenName') in Headscale widget

### DISCUSSION THREAD

**Discussion by dvision1979** [gethomepage/homepage#4572] [Support] [answered]
### Description

All I get in the Headscale widget is:
`TypeError: undefined is not an object (evaluating 'f.givenName')`

### homepage version

v0.10.8

### Installation method

Docker

### Configuration

```yaml
- Headscale:
      icon: headscale.png
      server: docker-nuc1
      container: headscale
      widget:
       type: headscale
       url: https://headscale.redacted.com:443
       nodeId: [LsphS]
       key: redacted
```

### Headscale version
https://github.com/juanfont/headscale/releases/tag/v0.23.0

### Container Logs

`homepage  | [2025-01-06T15:49:00.344Z] error: <credentialedProxyHandler> HTTP Error 400 calling https://headscale.redacted.com/api/v1/node/`

### Troubleshooting

```
$ docker exec homepage ping -c3 headscale.redacted.com
PING headscale.redacted.com (1.2.3.4): 56 data bytes
64 bytes from 1.2.3.4: seq=0 ttl=63 time=0.461 ms
64 bytes from 1.2.3.4: seq=1 ttl=63 time=1.260 ms
64 bytes from 1.2.3.4: seq=2 ttl=63 time=1.001 ms

--- headscale.redacted.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.461/0.907/1.260 ms
```
