### DISCUSSION TITLE
Quicklaunch search won't work with complex layout?

### DISCUSSION THREAD

**Discussion by yan3ku** [gethomepage/homepage#4575] [General]
```
- col2:
    - The Lounge:
        icon: thelounge.png
        description: 会議通信
        href: https://xxxxxxxxxxxx
        server: docker
        container: thelounge
    - Books:
        - Calibre:
            icon: calibre.png
            description: 知識アーカイブ
            href: https://xxxxxxxxxxxx
            server: docker
            container: calibre

        - Server:
            icon: calibre-web.png
            description: アーカイブ配信
            server: docker
            container: calibre
            href: https://xxxxxxxx/content-server
```
![image](https://github.com/user-attachments/assets/0103c3a8-45fd-434a-a782-c1a39ee8cff4)
![image](https://github.com/user-attachments/assets/b8352128-fb7a-4bb1-ada5-e94edb1b3c05)
Is it possible to make searchable by quicklaunch anything deeper than one level in yaml?
