### DISCUSSION TITLE
Remote Server configuration

### DISCUSSION THREAD

**Discussion by patillacode** [gethomepage/homepage#4582] [Support] [answered]
### Description

First things first: Thanks for an awesome tool!
I have been happily using homepage for a long while now!

Today I am trying to connect my homepage dashboard to an external server.

I have docker running in a Hetzner VPS that I would like to have access to from my homepage.

After going through the steps I find myself with an 
```
API Error: connect ECONNREFUSED my.vps.server.ip:2375
```

I am well aware that this is a network issue but if someone has a service in their homepage pointing to an external server I would love to see their config to maybe spot the issue.

This is my setup:

- `homepage` is running as a docker container in my original server `totoro`
- I am connecting to all the other docker services in that same `totoro` server via `dockerproxy` (also running as a docker container) and it has been working great!
- I now moved two services from `totoro` to `ushuaia` (the VPS I mentioned above)
- The port `2375` is open in `ushuaia` and from `totoro` I can `ping` as shown later in the troubleshooting logs

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

This is my `docker.yaml` file in `homepage` configuration:
```yaml

my-docker:
  host: dockerproxy
  port: 2375

ushuaia:
  host: ushuaia.server.ip
  port: 2375
```

The affected services are the ones in `ushuaia` which are the first two in the list, 
the other two are in `totoro` and working as expected:

Extract from my `services.yaml` file  

```yaml
- websites:
    - "liga conquistador":
        icon: https://production.mydomain.com/logo.png
        href: https://production.mydomain.com
        description: "production"
        server: ushuaia
        container: service_website_production
        showStats: true

    - "liga conquistador":
        icon: https://staging.mydomain.com/logo.png
        description: "staging"
        href: https://staging.mydomain.com
        server: ushuaia
        container: service_website_staging
        showStats: true

    - "humedécete":
        icon: https://otherdomain.com/logo.png
        href: https://otherdomain.com
        server: my-docker
        container: service_2
        showStats: true

    - binnacle:
        icon: https://another.domain.com/logo.png
        href: https://another.domain.com
        server: my-docker
        container: service_3
        showStats: true
```

### Container Logs

homepage container logs:

```
[2025-01-07T21:43:25.369Z] error: <dockerStatusService> Error: connect ECONNREFUSED ushuaia.ip:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
[2025-01-07T21:43:25.372Z] error: <dockerStatsService> Error: connect ECONNREFUSED ushuaia.ip:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
[2025-01-07T21:43:25.942Z] error: <dockerStatusService> Error: connect ECONNREFUSED ushuaia.ip:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
[2025-01-07T21:43:25.943Z] error: <dockerStatsService> Error: connect ECONNREFUSED ushuaia.ip:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
```

Below are the logs from the `dockerproxy` container running in the VPS, which are a bit confusing, not sure how I should configure this further, I am using the same `dockerproxy` compose file in both servers, but just in case it is helpful:

```
[WARNING] 006/212240 (1) : config : missing timeouts for backend 'docker-events'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 006/212240 (1) : Can't open global server state file '/var/lib/haproxy/server-state': No such file or directory
Proxy dockerbackend started.
Proxy docker-events started.
Proxy dockerfrontend started.
[NOTICE] 006/212240 (1) : New worker #1 (12) forked
```

### Troubleshooting

```bash
22:25 dvitto@totoro: ~ docker exec homepage ping ushuaia.server.ip
PING ushuaia.server.ip (ushuaia.server.ip): 56 data bytes
64 bytes from ushuaia.server.ip: seq=0 ttl=47 time=36.571 ms
64 bytes from ushuaia.server.ip: seq=1 ttl=47 time=35.747 ms
64 bytes from ushuaia.server.ip: seq=2 ttl=47 time=35.149 ms

22:37 dvitto@totoro: ~ docker exec homepage ping ushuaia.server.ip:2375
PING ushuaia.server.ip:2375 (ushuaia.server.ip): 56 data bytes
64 bytes from ushuaia.server.ip: seq=0 ttl=47 time=36.002 ms
64 bytes from ushuaia.server.ip: seq=1 ttl=47 time=35.313 ms
64 bytes from ushuaia.server.ip: seq=2 ttl=47 time=35.873 ms
```

**Comment by patillacode** [comment, marked as answer]
Of course the idea came to me after an hour of preparing my original message 🤦🏻 

I noticed something in my `docker-compose.yaml` for the `dockerproxy` service in `ushuaia`

```yaml
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
```

The `ports` configuration, to more specific, the IP

Changing the `ports` to the following, made everything work as expected, no more `API Error` 😄 
```
ports:
      - 0.0.0.0:2375:2375
```

Leaving all this here in case it is helpful for someone else.
