### DISCUSSION TITLE
[Bug] Automatic Service Discovery

### DISCUSSION THREAD

**Discussion by duanra08** [gethomepage/homepage#4588] [Support] [answered]
### Description

When I use Automatic Service Discovery, in addition to the service data and widgets, information about the VM also appears (similar issue as in point #343).
See image in troubleshooting.

### homepage version

v0.10.9 (b5f4daa, 6 janv. 2025)

### Installation method

Docker

### Configuration

```yaml
For Navidrome:
---
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      # ND_SCANSCHEDULE: 1h
      # ND_LOGLEVEL: info  
      # ND_SESSIONTIMEOUT: 24h
      # ND_BASEURL: ""
      # ND_ARTISTARTPRIORITY: artist.*
      # ND_COVERARTPRIORITY: folder.*
      ND_LASTFM_ENABLED: true
      ND_LASTFM_APIKEY: ${APIKEY:?APIKEY is required}
      ND_LASTFM_SECRET: ${LASTFM_SECRET:?LASTFM_SECRET is required}
      ND_LASTFM_LANGUAGE: ${LASTFM_LANGUAGE:?LASTFM_LANGUAGE is required}
    volumes:
      - ${PATH_DOCKER:?¨PATH_DOCKER is required}/navidrome/data:/data
      - ${PATH_DOCKER:?¨PATH_DOCKER is required}/navidrome/icons:/app/public/icons
      - ${PATH_MEDIA:?¨PATH_MEDIA is required}:/music:ro
    labels:
      - homepage.group=Media
      - homepage.name=Navidrome
      - homepage.icon=navidrome.svg
      - homepage.href=http://omv.home:4533
      - homepage.description=Music Media Server
    networks:
      - navidrome

networks:
  navidrome:
    name: navidrome
```

### Container Logs

![image](https://github.com/user-attachments/assets/41f005e4-8379-4aa8-891a-dda93e5c8a7f)

### Troubleshooting

<img width="747" alt="homepage" src="https://github.com/user-attachments/assets/10ad75bd-b9c9-4259-b7a7-ad4bd2440a94" />
