### DISCUSSION TITLE
UniFi (Controller) Widget - API Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### DISCUSSION THREAD

**Discussion by tumtumsback** [gethomepage/homepage#4589] [Support] [answered]
### Description

Receiving the following in the dashboard:

![image](https://github.com/user-attachments/assets/a55a8717-e54e-400b-9999-5808c595268d)

I am running a UniFi Controller VM, as opposed to a UniFi Controller on UniFi hardware, but I don't think that should matter.

Installation method is LXC container on Proxmox via Community Scripts.

### homepage version

v0.10.9 (source, Jan 10, 2025)

### Installation method

Other (please describe above)

### Configuration

```yaml
`    - unifi:
        icon: ubiquiti.png
        href: https://<my unifi fqdn>/
        description: <my unifi ip>
        widget:
          type: unifi
          url: https://<my unifi ip>:8443/
          username: <my username>
          password: <my password>
`
```

### Troubleshooting

Not even sure where to start. I have done a search for similar discussions but can't find anyone getting this specific response of 'API Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON'
