### DISCUSSION TITLE
Beszel - Authorization Issue

### DISCUSSION THREAD

**Discussion by jjjonesjr33** [gethomepage/homepage#4592] [Support] [answered]
### Description

I am having an issue where Homepage won't connect to Beszel. It shows it's going to load at first and then doesn't.

![image](https://github.com/user-attachments/assets/b9e43c34-ea97-4ac1-ac4b-dea68f543ca3)

### homepage version

 Beszel 0.9.1

### Installation method

Docker

### Configuration

```yaml
- Beszel:
        icon: https://beszel.example.com/static/favicon.svg
        href: https://beszel.example.com/
        server: Server
        container: beszel
        widget:
          type: beszel
          fields:
            - systems
            - up
          url: http://192.168.1.200:8090
          username: homepage@example.com # email
          password: password
          # systemId: systemId # optional
          version: 1 # optional, default is 1
        description: Server Monitoring
        siteMonitor: http://192.168.1.200:8090
```

### Container Logs

```yaml
[2025-01-11T01:25:53.692Z] error: <beszelProxyHandler> Error 200 logging into beszel {"type":"Buffer","data":[60,33,68,79,67,84,89,80,69,32,104,116,109,108,62,10,60,104,116,109,108,32,108,97,110,103,61,34,101,110,34,32,100,105,114,61,34,108,116,114,34,62,10,9,60,104,101,97,100,62,10,9,9,60,109,101,116,97,32,99,104,97,114,115,101,116,61,34,85,84,70,45,56,34,32,47,62,10,9,9,60,108,105,110,107,32,114,101,108,61,34,105,99,111,110,34,32,116,121,112,101,61,34,105,109,97,103,101,47,115,118,103,43,120,109,108,34,32,104,114,101,102,61,34,47,115,116,97,116,105,99,47,102,97,118,105,99,111,110,46,115,118,103,34,32,47,62,10,9,9,60,109,101,116,97,32,110,97,109,101,61,34,118,105,101,119,112,111,114,116,34,32,99,111,110,116,101,110,116,61,34,119,105,100,116,104,61,100,101,118,105,99,101,45,119,105,100,116,104,44,32,105,110,105,116,105,97,108,45,115,99,97,108,101,61,49,46,48,34,32,47,62,10,9,9,60,116,105,116,108,101,62,66,101,115,122,101,108,60,47,116,105,116,108,101,62,10,9,9,60,115,99,114,105,112,116,32,116,121,112,101,61,34,109,111,100,117,108,101,34,32,99,114,111,115,115,111,114,105,103,105,110,32,115,114,99,61,34,47,97,115,115,101,116,115,47,105,110,100,101,120,45,68,115,80,49,84,73,85,98,46,106,115,34,62,60,47,115,99,114,105,112,116,62,10,9,9,60,108,105,110,107,32,114,101,108,61,34,115,116,121,108,101,115,104,101,101,116,34,32,99,114,111,115,115,111,114,105,103,105,110,32,104,114,101,102,61,34,47,97,115,115,101,116,115,47,105,110,100,101,120,45,67,53,68,120,69,65,70,78,46,99,115,115,34,62,10,9,60,47,104,101,97,100,62,10,9,60,98,111,100,121,62,10,9,9,60,100,105,118,32,105,100,61,34,97,112,112,34,62,60,47,100,105,118,62,10,9,60,47,98,111,100,121,62,10,60,47,104,116,109,108,62,10]}
[2025-01-11T01:25:53.694Z] error: <httpProxy> Error calling http://192.168.1.200:8090/api/collections/systems/records...
[2025-01-11T01:25:53.694Z] error: <httpProxy> TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
    at ClientRequest.setHeader (node:_http_outgoing:658:3)
    at new ClientRequest (node:_http_client:291:14)
    at Object.request (node:http:100:10)
    at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.9/node_modules/follow-redirects/index.js:337:24)
    at new RedirectableRequest (/app/node_modules/.pnpm/follow-redirects@1.15.9/node_modules/follow-redirects/index.js:111:8)
    at Object.request (/app/node_modules/.pnpm/follow-redirects@1.15.9/node_modules/follow-redirects/index.js:543:14)
    at /app/.next/server/chunks/149.js:183:31
    at new Promise (<anonymous>)
    at handleRequest (/app/.next/server/chunks/149.js:175:10)
    at httpRequest (/app/.next/server/chunks/149.js:228:10)
```

### Browser Logs

```yaml
{
    "error": {
        "message": "Invalid character in header content [\"Authorization\"]",
        "url": "http://192.168.1.200:8090/api/collections/systems/records?page=1&perPage=500&sort=%2Bcreated",
        "rawError": {
            "code": "ERR_INVALID_CHAR",
            "level": "error"
        }
    }
}
```

### Troubleshooting

I have allowed the user access to the systems, confirmed it can see the systems, logged in through the browser with no issues. However the issue is present when using the same information to log into Beszel through Homepage. I have also changed the version in the config, removed the widget settings, with no luck.

**Comment by shamoon** [comment]
Please search and / or read the documentation

https://gethomepage.dev/widgets/services/beszel/

**Reply by jjjonesjr33** [reply]
I have read the documentation. It does not answer why I am having this issue. I have set the settings exactly how it is stated and the issue is still present. 

Please advise.

**Reply by shamoon** [reply]
> Beszel 0.9.1

> ```
> Beszel Version 	  Homepage Widget Version
> < 0.9.0	 	  1 (default)
> >= 0.9.0 	  2
> ```

**Reply by jjjonesjr33** [reply]
I've tried both version 1 and 2 the error remains.

**Reply by shamoon** [reply]
In that case you should go through the steps from the troubleshooting guide linked above and post the output. I would guess your authorization details are incorrect, but I cannot reproduce any issue.

```yaml
    labels:
      - homepage.group=Testing
      - homepage.name=beszel
      # - homepage.icon=beszel.png
      - homepage.href=http://localhost:8090
      - homepage.description=beszel
      - homepage.widget.type=beszel
      - homepage.widget.url=http://localhost:8090
      - homepage.widget.username=me@example.com
      - homepage.widget.password=password
      # - homepage.widget.systemId=fz72shw9454121c
      - homepage.widget.version=2
```

<img width="745" alt="Screenshot 2025-01-10 at 8 16 34 PM" src="https://github.com/user-attachments/assets/84d15fd9-5ae8-49f1-8c31-e566797dfd28" />
<img width="766" alt="Screenshot 2025-01-10 at 8 16 51 PM" src="https://github.com/user-attachments/assets/ba02bbee-a787-4eee-9cd0-37da71568fc1" />

**Reply by jjjonesjr33** [reply]
I wonder if it's because your using labels, where I am using a static config in the `services.yaml` ?

**Reply by shamoon** [reply, marked as answer]
Its not.

```yaml
     - Beszel:
          description: beszel
          icon: beszel.png
          widget:
               type: beszel
               url: http://localhost:8090
               username: me@example.com
               password: password
               systemId: fz72shw9454121c
               version: 2
```

<img width="744" alt="Screenshot 2025-01-10 at 8 35 23 PM" src="https://github.com/user-attachments/assets/3ef147f4-8029-4fc0-9a0f-f53cdaf9756b" />
