### DISCUSSION TITLE
Keep getting API Error Information when trying to set up MySpeed.

### DISCUSSION THREAD

**Discussion by tomhusband** [gethomepage/homepage#4594] [Support]
### Description

I'm trying to get MySpeed to show up on my dashboard but keep getting API Error Information. I have MySpeed as an LXC in Proxmox.
My yaml looks like this:
```
- MySpeed:
        href: http://192.xxx.xx.x:5216/
        description: Internet Speed
        widget:
            type: myspeed
            url: http://192.xxx.xx.x:5216/
            password: # only required if password is set
```

I don't have a password assigned to the app. Do I have that part incorrect? I've tried leaving that line out but still get the error.  I've tried countless other combinations but can't get it right.
I installed Homepage in a Proxmox LXC using  the Proxmox VE Helper script.
Any ideas where I'm going wrong?

### homepage version

0.10.9

### Installation method

Other (please describe above)

### Troubleshooting

API Error: Invalid data
URL: http://192.xxx.xx.x:5216//api/speedtests?limit=1
Response Data:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/assets/img/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#232835" />
    <meta property="og:image" content="/assets/img/logo.png" />
    <meta name="description"
          content="A speed test analysis software that shows your internet speed for up to 30 days"
    />
    <link rel="apple-touch-icon" href="/assets/img/logo192.png" />
    <link rel="manifest" href="/manifest.json" />
    <title>MySpeed</title>
    <script type="module" crossorigin src="/assets/index-DSkzc1lW.js"></script>
    <link rel="modulepreload" crossorigin href="/assets/vendor-B6G8AnG7.js">
    <link rel="modulepreload" crossorigin href="/assets/icons-BW3oS_Es.js">
    <link rel="stylesheet" crossorigin href="/assets/index-B0M1nYWK.css">
  <script id="vite-plugin-pwa:register-sw" src="/registerSW.js"></script></head>
  <body>
    <div id="root"></div>
  </body>
</html>
