### DISCUSSION TITLE
[Feature Request] do not write variables in the log file

### DISCUSSION THREAD

**Discussion by geeForceOne** [gethomepage/homepage#4601] [Feature Requests]
### Description

I'm using HOMEPAGE_VAR_MYKEY to keep the secrets in environment variables.
However if there's a yaml syntax error the value of the variable is showed in the log:

services.yaml
```
    - Paperless:
        icon: paperless-ngx.png
        href: http://hidden:7777
         username: {{HOMEPAGE_VAR_PLU}}
        password: {{HOMEPAGE_VAR_PLP}}

```

becomes in the log:
(showing the current values of the variables)

```
 51 |     - Paperless:
 52 |         icon: paperless-ngx.png
 53 |         href: http://hidden:7777
 54 |          username: a
-----------------------^
 55 |         password: b
 56 | 
```

can this be prevented as it exposes as security risk?
