### DISCUSSION TITLE
[Feature Request] disable collapse for specific service/bookmark group

### DISCUSSION THREAD

**Discussion by tyaga** [gethomepage/homepage#4603] [Feature Requests]
### Description

It would be great to be able to disable collapse for specific service/bookmark group. Like that: 

only Applications would be collapsable
```yaml
disableCollapse: true
layout:
  Applications:
    disableCollapse: false
  Monitoring:
    disableCollapse: true
  Setup:
```
 only Setup would be collapsable
```yaml
disableCollapse: false
layout:
  Applications:
    disableCollapse: true
  Monitoring:
    disableCollapse: true
  Setup:
```
