### DISCUSSION TITLE
[Feature Request] Quick Launch Search Target

### DISCUSSION THREAD

**Discussion by nichcuta** [gethomepage/homepage#4607] [Feature Requests] [answered]
### Description

Would be nice if we can configure the Quick Launch section with different "Link Targets", Example:

```
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: false
  hideVisitURL: true
  provider: google
  target: _self
```

Awesome project, kudos!!

**Comment by nichcuta** [comment]
For anyone who needs this for the time being, you can achieve this by editing the below file:
/app/.next/static/chunks/pages/index-15e4eacb6659f3f0.js

line 4241 & line 4254

![image](https://github.com/user-attachments/assets/8dfe7a8a-14f8-42d3-8d6a-d0ec7811b5e2)

**Reply by ericscicluna** [reply]
nice one, cheers

**Comment by Entrivax** [comment]
It looks like the setting of the target is not searched at the right place, if you put the `target` outside of the `quicklaunch` object, it works fine:
```yaml
quicklaunch:
  provider: google
target: _self
# ^ target at the same level as the quicklaunch item
```
