### DISCUSSION TITLE
How to use fields of custom api using docker labels?

### DISCUSSION THREAD

**Discussion by Elekam** [gethomepage/homepage#4609] [Support] [answered]
### Description

I want to add Nautical Backups to my Homepage using custom api with docker labels.
I am not sure how to do the fields part inside docker compose with labels though.

This is what I have so far:
```
    labels:
      homepage.group: Server
      homepage.name: Nautical-Backup
      homepage.icon: https://raw.githubusercontent.com/Minituff/nautical-backup/main/docs/media/Logo-large.png
      homepage.widget.type: customapi
      homepage.widget.url: http://REDACTED:8069/api/v1/nautical/dashboard
      homepage.widget.username: username
      homepage.widget.password: password
      homepage.widget.method: GET
      homepage.widget.mappings:
        - field: errors
          label: errors
        - field: last_cron
          label: Last Run
          format: relativeDate
```

I figured the homepage.widget.mappings wouldnt work but there are a lot of ways how this might be supposed to be done, and I would like to avoid trying every single one.
Thought about something like this too:
```
Homepage.widget.mappings.field1:errors
Homepage.widget.mappings.field1.label: errors
```

Anyone done this before/knows how it is possible?

Thanks in advance! :)

### homepage version

v0.10.9

### Installation method

Docker

### Troubleshooting

None done.
