### DISCUSSION TITLE
[Feature Request] allow search bar to filter/scroll-to homepage apps

### DISCUSSION THREAD

**Discussion by emouawad** [gethomepage/homepage#4610] [Feature Requests]
### Description

The current search bar (https://gethomepage.dev/widgets/info/search/) only searches externally on google, bing etc; while the suggestions (https://gethomepage.dev/configs/settings/#quick-launch) can filter homepage apps/bookmarks.

On mobile quick-launch can't be activated.

It's confusing for most users on web to use the search bar - expecting the search bar to search inside the list of apps not externally on google/bing/etc.

The quick-launch is great for people that know about this feature, but hidden for most users (in contrast to search)

**Comment by javierspn** [comment]
I logged in to create a new feature request for this and I can't agree more.
Also props to the creator!

**Comment by kankaristo** [comment]
> On mobile quick-launch can't be activated.

To work around this, you can add a button to open quick launch on mobile.

custom.js:  
```javascript
// Create a button to open quick launch
const quickLaunchButton = document.createElement("button");
quickLaunchButton.classList.add("custom-quick-launch-button");
quickLaunchButton.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z" /></svg>`;
document.body.appendChild(quickLaunchButton);

// Add event listener to the button
quickLaunchButton.addEventListener("click", () => {
    // Simulate a keydown event on the main document
    // The key doesn't matter, it will be ignored
    const inputEvent = new KeyboardEvent("keydown", {key: "a", bubbles: true});
    document.body.dispatchEvent(inputEvent);
    // Focus the quick launch search box
    const quickLaunch = document.querySelector('dialog input[placeholder="Search"]');
    quickLaunch.focus();
});
```

custom.css:  
```css
/* Button to open quick launch (for mobile, mostly) */
.custom-quick-launch-button {
    position: fixed;
        bottom: 20px;
        right: 20px;
    width: 50px;
    height: 50px;
    align-items: center;
    background-color: rgba(0, 0, 0, 0.4);
    border: none;
    border-radius: 50%;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
    cursor: pointer;
    display: flex;
    justify-content: center;
    z-index: 1000;
}
.custom-quick-launch-button:hover {
    background-color: rgba(0, 0, 0, 0.8);
}
.custom-quick-launch-button svg {
    width: 24px;
    height: 24px;
    fill: white;
}
```
