### DISCUSSION TITLE
[Feature Request] Improved visibility on service issues by highlighting fields.

### DISCUSSION THREAD

**Discussion by ryanwinter** [gethomepage/homepage#4619] [Feature Requests] [answered]
### Description

For a number of widgets, they are reporting some form of status that I would like to be able to easily see if its in a failure state. A good example would be the [health checks widget](https://gethomepage.dev/widgets/services/healthchecks/), that shows the `down` field where I care if its not 0.

Would like to see widgets or users being able to define rules or thresholds that could classify as issue with the field value.

This could be highlighted in 2 ways:
1. Colorize the field to indicate a problem
2. Have an informational widget that displays a list of problems reported by widgets that could be placed anywhere.

Instead of:
![image](https://github.com/user-attachments/assets/c2c73a47-6bb7-4fba-973d-658692410c09)

Something like this:
![image](https://github.com/user-attachments/assets/b30842fd-dd7b-4b16-b241-929e47cb8b09)

**Comment by owennewo-dev** [comment]
I think this is a great feature request, and should be implemented. This has been asked before, but ignored due to lack of interest I think.

Currently you can achieve this with some custom css and js, but it would be great if all you needed to do was add `highlightField: "alerts"` in the `widget` section of a service's yaml, like so:

```yaml
    - TrueNAS:
        icon: truenas-scale.png
        href: http://your.server.ip
        siteMonitor: http://your.server.ip
        statusStyle: dot
        widget:
          type: truenas
          fields: ["uptime", "alerts"]
          highlightFields: "alerts"        <----
          url: http://your.server.ip
          key: apikey
          enablePools: true
          nasType: scale
```

Then there could be a line in `settings.yaml` with the color you want for the highlighted fields, like this: `highlightColor: #ff0000`

**Reply by ryanwinter** [reply]
While this is good, I was really thinking of a dynamic highlighting based on a rule. So it would only get highlighted if it breaches some rule. The rules could be represent by the widget, or potentially overridden by the user.

So in the case of truenas above, it would only highlight if the alerts > 0.

**Reply by owennewo-dev** [reply]
Yes I understand, I totally forgot to factor that into my idea for the yaml config!

That currently is what I have setup with custom js and css, when `alerts` goes over 0 it goes red.

**Reply by ryanwinter** [reply]
> Yes I understand, I totally forgot to factor that into my idea for the yaml config!
> 
> That currently is what I have setup with custom js and css, when `alerts` goes over 0 it goes red.

Nice, I might give that a try for now :) Is there an easy way to tell which div block is what? Looking at the elements it looks like I would need to search for the parent so I can understand which widget it is, and then possible just know the ordering of the cards in the widget so I can target the right one? 

My javascript is not the best!

**Reply by owennewo-dev** [reply]
@ryanwinter You can find my code at https://github.com/owennewo-dev/Homepage-config

But I will share the relevant bits here for you.

Currently I have this for my TrueNAS widget. (I hope this becomes a feature directly in Homepage, because I couldn't get this to work with more than one widget at a time) You have to add a new line called `id: truenas-scale (or uptime-kuma)`

This is `services.yaml`
```yaml
- Services1:
    - TrueNAS:
        id: truenas-scale
        icon: truenas-scale.png
        href: http://your.server.ip
        siteMonitor: http://your.server.ip
        statusStyle: dot
        widget:
          type: truenas
          fields: ["uptime", "alerts"]
          url: http://your.server.ip
          key: apikey
          enablePools: true
          nasType: scale
```
You will use the id you set in `services.yaml` in your `custom.js` file. The only line you need to change anything in is line 5 in the `js` below.
This is `custom.js`
```js
function createObserver() {
  // calling this on init to get style updated first time
  updateDownSitePanelStatus();

  // select the target node, referencing the id parameter from the service definition
  const downSitePanel = document.getElementById("truenas-scale").querySelector(".service-container").children[1];

  // create an observer instance
  const observer = new MutationObserver(function (mutations) {
    mutations.forEach(function (mutation) {
      if (mutation.type === "characterData") {
        updateDownSitePanelStatus();
      }
    });
  });

  const config = {
    subtree: true,
    characterData: true,
  };

  // pass in the target node and observer options
  observer.observe(downSitePanel, config);
}

function updateDownSitePanelStatus() {
  const downSitePanel = document.getElementById("truenas-scale").querySelector(".service-container").children[1];

  const siteDownCount = parseInt(downSitePanel.children[0].textContent);

  if (siteDownCount > 0) {
    if (!downSitePanel.classList.contains("down-bg")) {
      downSitePanel.classList.add("down-bg");
    }
  } else {
    if (downSitePanel.classList.contains("down-bg") || isNaN(siteDownCount)) {
      downSitePanel.classList.remove("down-bg");
    }
  }
}

setTimeout(createObserver, 1000); // band-aid, use as needed - sometimes would fire too early without the timeout
//createObserver();
```
As I said, you only have to change two things in line #5. So for me this line is:
```js
  const downSitePanel = document.getElementById("truenas-scale").querySelector(".service-container").children[1];
```
If you set the `id:` field in your `services.yaml` for your Uptime Kuma widget to `id: uptime-kuma` this is what you would change that line in `custom.js` to.
```js
  const downSitePanel = document.getElementById("uptime-kuma").querySelector(".service-container").children[1];
```
The last part, `.children[1]` is where you set what widget field you want the alert to be on. The first field in your widget is field `[0]`, second is `[1]` and third is `[2]`, so if you have the same config as what you showed in your screenshot, and want the `Sites Down` field to be highlighted when the number in it goes over one, you would put `[1]` just as I have.


Now if you only wanted the `Sites Down` field in your Uptime Kuma widget to be highlighted red when the number of `Sites Down` is over 5, you would change the line that is `if (siteDownCount > 0) {` (this line is near the bottom of the code) to `if (siteDownCount > 5) {`.

Also, you need to put some code in your `custom.css` file.
```css
.down-bg {
  background-color: #ff0000 !important; /* this color works for my homepage theming, chances are you'll want to change it */
  /* I have this css transition code uncommented in mine, just personal preference */
  /* -webkit-transition: all 0.2s linear;
  -moz-transition: all 0.2s linear;
  -o-transition: all 0.2s linear;
  transition: all 0.2s linear; */
}
```
You might want to change the hexadecimal color code in `background-color: #ff0000` to suit your homepage theme and/or background.


Hopefully this helps! If I was not clear enough on something, please let me know. I am happy to help.

Again, I beg shamoon or someone else to implement this directly into Homepage. I would be immensely grateful to not have to do all this hacky js. Also I have multiple widgets I want to have field highlight alerts on, but I can't get this js to work with more than one widget.

**Reply by ryanwinter** [reply]
Awesome I'll give this a try!

I assume you would just repeat the code for each widget you want to dynamically change?

**Reply by owennewo-dev** [reply]
You can give it a shot, but I wasn't able to get it to work with multiple widgets.

**Reply by huyz** [reply]
Lack of interest, really?  It seems like one of the first things you'd want in a dashboard.  Otherwise, it's just a pretty page for the feels.  i agree that this should be core functionality.

**Reply by ryanwinter** [reply]
Lol right! A dashboard is not so useful without some way of alerting. But the solution I used recommended from @owennewo-dev is still working for me.

**Comment by ryanwinter** [comment]
Here is some js hackery I did to get something working where I could define thresholds. Not well tested :)

```js
function WatchItem(service, container, threshold) {
    this.service = service;
    this.container = container;
    this.threshold = threshold;

}
var watchItems = [
    new WatchItem('Portainer', 1, ">0"),
    new WatchItem('Uptime Kuma', 1, ">0"),
    new WatchItem('Healthchecks.io', 1, ">0"),
    new WatchItem('Uptime Robot', 1, ">0"),
    new WatchItem('Crowdsec', 1, ">0"),
    new WatchItem('Omada', 2, ">0"),
    new WatchItem('NetAlertX', 3, ">0"),
    new WatchItem('Truenas', 2, ">0"),
    new WatchItem('Scrutiny', 1, ">0"),
    new WatchItem('Scrutiny', 2, ">0"),
];

async function observeItem(item) {
    await waitForItem(item);

    item.element = document.querySelector(`[data-name='${item.service}']`).querySelector(".service-container").children[item.container];

    const observer = new MutationObserver(function (item, mutations) {
        mutations.forEach(function (mutation) {
            if (eval(`${mutation.target.data}${item.threshold}`)) {
                item.element.classList.add("fail-bg");
            } else {
                item.element.classList.remove("fail-bg");
            }
        });
    }.bind(null, item));

    observer.observe(item.element, { subtree: true, characterData: true });
}

function waitForItem(item) {
    return new Promise(resolve => {

        const observer = new MutationObserver(mutations => {
            if (document.querySelector(`[data-name='${item.service}']`).querySelector(".service-container")) {
                observer.disconnect();
                resolve();
            }
        });

        observer.observe(document.body, { childList: true, subtree: true });
    });
}

watchItems.forEach(item => {
    observeItem(item);
});
```

**Comment by huyz** [comment]
Btw, previous discussion that was locked: https://github.com/gethomepage/homepage/discussions/3040

**Reply by huyz** [reply]
Also https://github.com/gethomepage/homepage/discussions/2793

**Reply by huyz** [reply]
Also https://github.com/gethomepage/homepage/discussions/1478

**Comment by CV8R** [comment]
Thanks folks - sharing where I ended up with the help of ChatGPT to allow string comparison  i.e. !=On-Line and to remove eval.


/custom.js
```js
function WatchItem(service, container, threshold) {
    this.service = service;
    this.container = container;

    // Parse operator and value from the threshold string, e.g., ">0"
    const match = threshold.match(/(==|!=|>=|<=|>|<)(.+)/);
    if (!match) throw new Error(`Invalid threshold format: ${threshold}`);

    this.operator = match[1];
    this.threshold = match[2].trim();
}

const watchItems = [
    new WatchItem('UPS', 0, "!=On-Line"),
    new WatchItem('UPS', 1, ">80"),
    new WatchItem('UPS', 2, "<100"),
    new WatchItem('UPS', 3, ">40"),
    new WatchItem('Proxmox PBS1', 0, ">80"),
    new WatchItem('Proxmox PBS1', 1, ">0"),
    new WatchItem('Proxmox PBS1', 2, ">80"),
    new WatchItem('Proxmox PBS1', 3, ">80"),
    new WatchItem('Proxmox Cluster', 2, ">80"),
    new WatchItem('Proxmox Cluster', 3, ">80"),
    new WatchItem('TrueNAS', 2, ">0"),
    new WatchItem('BackupTrueNAS', 2, ">0"),
    new WatchItem('Portainer Docker PVE VM1', 1, ">0"),
    new WatchItem('Portainer Docker PVE VM2', 1, ">0"),
    new WatchItem('Portainer Docker TN VM1', 1, ">0"),
    new WatchItem('Portainer Docker TN VM2', 1, ">0"),
    new WatchItem('Zabbix', 2, ">0"),
    new WatchItem('Zabbix', 3, ">0"),
];

function compareValues(current, threshold, operator) {
    // Try to coerce to numbers; fallback to strings
    const numCurrent = parseFloat(current);
    const numThreshold = parseFloat(threshold);

    const useNumbers = !isNaN(numCurrent) && !isNaN(numThreshold);

    const a = useNumbers ? numCurrent : current;
    const b = useNumbers ? numThreshold : threshold;

    switch (operator) {
        case "==": return a == b;
        case "!=": return a != b;
        case ">":  return a > b;
        case "<":  return a < b;
        case ">=": return a >= b;
        case "<=": return a <= b;
        default:
            console.error(`Unsupported operator: ${operator}`);
            return false;
    }
}

async function observeItem(item) {
    await waitForItem(item);

    item.element = document
        .querySelector(`[data-name='${item.service}']`)
        .querySelector(".service-container")
        .children[item.container];

    const observer = new MutationObserver(function (mutations) {
        mutations.forEach(function (mutation) {
            const currentValue = mutation.target.data;

            if (compareValues(currentValue, item.threshold, item.operator)) {
                item.element.classList.add("fail-bg");
            } else {
                item.element.classList.remove("fail-bg");
            }
        });
    });

    observer.observe(item.element, { subtree: true, characterData: true });
}

function waitForItem(item) {
    return new Promise(resolve => {
        const observer = new MutationObserver(() => {
            const container = document.querySelector(`[data-name='${item.service}']`)?.querySelector(".service-container");
            if (container) {
                observer.disconnect();
                resolve();
            }
        });

        observer.observe(document.body, { childList: true, subtree: true });
    });
}

// Start observers
watchItems.forEach(observeItem);
```


/custom.css
```css
.fail-bg {
  background-color: #cc0000 !important; /* this color works for my homepage theming, chances are you'll want to change it */
  /* I have this css transition code uncommented in mine, just personal preference */
  /* -webkit-transition: all 0.2s linear;
  -moz-transition: all 0.2s linear;
  -o-transition: all 0.2s linear;
  transition: all 0.2s linear; */
}
```
