### DISCUSSION TITLE
[Healthchecks widget] Continuous error

### DISCUSSION THREAD

**Discussion by Chucky2401** [gethomepage/homepage#4622] [Support]
### Description

Hi,
Since I set up a widget to my Healthchecks local instance I receive parse error in the container logs every minutes.

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
- Healthchecks:
        icon: mdi-heart-flash
        href: http://debian.localdomain.fr:8060
        description: Monitoring cron jobs
        server: local-docker
        container: health-web
        siteMonitor: http://debian.localdomain.fr:8060
        widget:
            type: healthchecks
            url: http://debian.localdomain.fr:8060
            key: [redacted]
```

### Container Logs

```shell
homepage  | 2025-01-18T13:42:00.770912396Z [2025-01-18T13:42:00.770Z] error: <httpProxy> Error calling http://debian.localdomain.fr:8060/...
homepage  | 2025-01-18T13:42:00.774151335Z [2025-01-18T13:42:00.773Z] error: <httpProxy> [
homepage  | 2025-01-18T13:42:00.774209742Z   500,
homepage  | 2025-01-18T13:42:00.774217817Z   Error: Parse Error: Expected HTTP/
homepage  | 2025-01-18T13:42:00.774221076Z       at Socket.socketOnData (node:_http_client:541:22)
homepage  | 2025-01-18T13:42:00.774223965Z       at Socket.emit (node:events:517:28)
homepage  | 2025-01-18T13:42:00.774226872Z       at addChunk (node:internal/streams/readable:368:12)
homepage  | 2025-01-18T13:42:00.774230020Z       at readableAddChunk (node:internal/streams/readable:341:9)
homepage  | 2025-01-18T13:42:00.774232891Z       at Readable.push (node:internal/streams/readable:278:10)
homepage  | 2025-01-18T13:42:00.774235761Z       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
homepage  | 2025-01-18T13:42:00.774238594Z     bytesParsed: 375,
homepage  | 2025-01-18T13:42:00.774241483Z     code: 'HPE_INVALID_CONSTANT',
homepage  | 2025-01-18T13:42:00.774244168Z     reason: 'Expected HTTP/',
homepage  | 2025-01-18T13:42:00.774247168Z     rawPacket: <Buffer 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65 78 74 2f 68 74 6d 6c 3b 20 63 68 61 72 73 65 74 3d ... 7018 more bytes>
homepage  | 2025-01-18T13:42:00.774252020Z   }
homepage  | 2025-01-18T13:42:00.774254594Z ]
```

### Troubleshooting

I do all the verification in the troubleshooting tests page, everything is good, no issue with the widget, only in the log, for no reason.
