### DISCUSSION TITLE
QNAP Widget Intermittent API Error

### DISCUSSION THREAD

**Discussion by dbowles1975** [gethomepage/homepage#4623] [Support]
### Description

I have been able to configure the QNAP widget and it displays correctly on the homepage, but it occassionally throws an error and then goes back to working on its own. 

### homepage version

V0.10.9

### Installation method

Docker

### Configuration

```
 - TS-431XeU:
        icon: qnap.png
        href: http://192.168.50.20:8080/cgi-bin/
        description: QNAP NAS Web Interface
        widget:
          type: qnap
          url: http://192.168.50.20:8080
          username: *******
          password: *********   
```

### Container Logs

```
2025-01-17 12:30:41 [2025-01-17T17:30:41.498Z] error: <qnapProxyHandler> QNAP API rejected the request, attempting to obtain new session token
2025-01-17 12:30:45 [2025-01-17T17:30:45.753Z] error: undefined
```

### Troubleshooting

![Screenshot 2025-01-18 125620](https://github.com/user-attachments/assets/a30063e5-59cc-43df-a0e9-0df50a9486a8)
![Screenshot 2025-01-18 125710](https://github.com/user-attachments/assets/edb7995a-477c-4f2d-a6ae-088575049a37)
