### DISCUSSION TITLE
query parameters as in customapi

### DISCUSSION THREAD

**Discussion by RhykerWells** [gethomepage/homepage#4625] [Support]
### Description

Is there a way of passing custom JS to the customapi widget?
I have gone through docs and search through github and the discussions just in case I have missed something but have not found anything relevant
I'm attempting to integrate your_spotify's api into my homepage
And the api utilises query strings to access data for specific periods

I have a way of generating the data for query string via the customJS but am unsure on how to integrate it into my yaml file

### homepage version

v0.10.9

### Installation method

Docker

### Configuration
This is how I am generating my queries
```yaml

const isoToday = new Date().toISOString();
const isoHistoryBegin = "2019-10-21T17:01:12.000Z"
const isoDayBefore = new Date(new Date().setUTCDate(new Date().getUTCDate() - 1)).toISOString().split('T')[0] + 'T00:00:00.000Z';
const isoMonthBefore = new Date(new Date().setUTCMonth(new Date().getUTCMonth() - 1)).toISOString().split('T')[0] + 'T00:00:00.000Z';
const isoYearBefore = new Date(new Date().setUTCFullYear(new Date().getUTCFullYear() - 1)).toISOString().split('T')[0] + 'T00:00:00.000Z';
```

And this is my widget config
```yaml
- Spotify:
    - Past day:
        widget:
          type: customapi
          url: https://api.rhykerw.com/spotify/songs_per?start={{START DATE HERE}}&end={{END DATE HERE}}&timeSplit=all
          mappings:
            - field:
                "0": count
              label: Total songs listened
            - field:
                "0": differents
              label: Unique songs
```

### Troubleshooting

Not applicable
