### DISCUSSION TITLE
evcc widget: grid power is shown as 0

### DISCUSSION THREAD

**Discussion by thierolm** [gethomepage/homepage#4627] [Support]
### Description

evcc widgets grid power is shown as 0 in widget, while evcc state API provides value.

![image](https://github.com/user-attachments/assets/f88ba997-b6d4-4ee7-b523-91475679c040)

evcc version: 0.133.0

There was a change on evcc side: https://github.com/evcc-io/evcc/commit/9dcb1fa0a7c08dd926b79309aa1f676a5fc6c8aa

![image](https://github.com/user-attachments/assets/16d4ac23-3f62-4adf-998d-8c60f17a7772)

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- evcc:
            href: http://192.xx.xx.xx:7070
            description: Sonne tanken
            icon: /icons/evcc-lightning.svg
            server: localdocker
            container: evcc
            widget:
              type: evcc
              url: http://192.xx.xx.xx:7070
```

### Browser Logs

First part of evcc state api json:
```json
{
  "result": {
    "auth": {

    },
    "aux": [],
    "battery": [
      {
        "power": -2.76,
        "energy": 5102.71863,
        "capacity": 10.2,
        "soc": 7.6,
        "controllable": true
      }
    ],
    "batteryCapacity": 10.2,
    "batteryDischargeControl": true,
    "batteryEnergy": 5102.719,
    "batteryGridChargeActive": false,
    "batteryMode": "hold",
    "batteryPower": -2.76,
    "batterySoc": 7.6,
    "bufferSoc": 80,
    "bufferStartSoc": 96,
    "currency": "EUR",
    "eebus": false,
    "ext": [],
    "fatal": null,
    "greenShareHome": 0.942,
    "greenShareLoadpoints": 0,
    "grid": {
      "power": 3579.080078125,
      "energy": 7885.003,
      "powers": [3587.05004882813, 115.339996337891, -123.309997558594],
      "currents": [15.4910001754761, 1.38300001621246, -0.7049999833107]
    },
    "gridConfigured": true,
    "hems": {

    },
    "homePower": 628.7,

....
}

### Troubleshooting

na
