### DISCUSSION TITLE
gamedig widget doesn't show players for Minecraft [bedrock] server

### DISCUSSION THREAD

**Discussion by Swiftnesses** [gethomepage/homepage#4628] [Support] [answered]
### Description

I have this yaml, all other metrics should OK (online checkers also show players for my server OK).

```
    - Minecraft:
        icon: minecraft.svg
        widget:
          type: gamedig
          serverType: mbe
          url: https://www.***.co.uk
          fields: ["status", "map", "players", "ping"] # removed "name"
```

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Troubleshooting

Tried various configs, with no luck.
