### DISCUSSION TITLE
Setting 'weight: 0' for a configured service doesn't result in it being sorted correctly

### DISCUSSION THREAD

**Discussion by okunze** [gethomepage/homepage#4649] [Support] [answered]
### Description

https://gethomepage.dev/configs/docker/#ordering
This link explains that discovered services have a weight of 0 and that if two items have the same weight then they will be sorted alphabetically.

I have several “discovered services” and would like to add some configured services:
![grafik](https://github.com/user-attachments/assets/51bf4aec-0fc0-483f-8f43-a497fe96be17)

So I have added multiple services via the `settings.yaml`, given them all weight of 0 expecting them to be sorted amongst the discovered services:
```
- Monitoring:
    - Grafana - Dashboard 1:
        weight: 0
        icon: /icons/grafana.png
        href: {REDACTED}
    - Grafana - Dashboard 2:
        weight: 0
        icon: /icons/grafana.png
        href: {REDACTED}
    - OpenDTU:
        icon: /icons/opendtu.png
        href: {REDACTED}
        weight: 0
```
![grafik](https://github.com/user-attachments/assets/302dce14-7f3c-425d-b3ad-a5d894bed4c7)

Apparently only the first configured service with the weight 0 is sorted correctly, all others end up at the end of the list.

**Steps to reproduce**

1. Have a group with discovered services added via docker labels
2. Add some configured services via `services.yml`
3. Add a `weight: 0` to the configured services

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
settings.yaml:
- Monitoring:
    - Grafana - Dashboard 1:
        weight: 0
        icon: /icons/grafana.png
        href: {REDACTED}
    - Grafana - Dashboard 2:
        weight: 0
        icon: /icons/grafana.png
        href: {REDACTED}
    - OpenDTU:
        icon: /icons/opendtu.png
        href: {REDACTED}
        weight: 0
```

### Troubleshooting

I've tried adjusting the weight, setting it to -1 puts the configured services at the top of the list, as does any negative integer.
0 put only the first configured services in the correct position. All positive integers put them at the bottom of the list.

This issue has already been dealt with [here](https://github.com/gethomepage/homepage/issues/2627), but is still present.
