### DISCUSSION TITLE
Instance / Calendar Widget Integration Question

### DISCUSSION THREAD

**Discussion by undaunt** [gethomepage/homepage#4650] [Support]
### Description

Hello,

I have a scenario where my family and friends access a subset of my containers. I am running three instances of homepage, 'me', 'family', and 'users'. I have some calendar views that I think my users could benefit from, but it doesn't seem to be possible to expose the upcoming TV and/or movies to them without also granting them access to the Sonarr/Radarr widgets directly. Is that correct?

Right now I see this:

![image](https://github.com/user-attachments/assets/65a37053-1135-4dba-85cd-c34e1be85320)

My users see this:

![image](https://github.com/user-attachments/assets/3e1f4c49-0560-4a58-9662-9cfc1f7292b1)

I'm putting the Radarr compose labels below. Thanks for your insight.

### homepage version

v0.10.9 (b5f4daa)

### Installation method

Docker

### Configuration

```yaml
services.yaml:

- Media Schedule:
    - Upcoming Movies & Books:
        widget:
            type: calendar
            view: agenda # optional - possible values monthly, agenda
            maxEvents: 11 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            integrations: # optional
                - type: radarr
                  service_group: PVR
                  service_name: Radarr
                - type: radarr
                  service_group: PVR
                  service_name: Radarr (Anime)
                - type: readarr
                  service_group: PVR
                  service_name: Readarr
                - type: readarr
                  service_group: PVR
                  service_name: Readarr (Audio)

radarr compose labels:

      homepage.instance.me.group: PVR
      homepage.instance.me.name: Radarr
      homepage.instance.me.icon: radarr.png
      homepage.instance.me.href: https://${SUB_RADARR}.${DOMAINNAME}
      homepage.instance.me.weight: 100
      homepage.instance.me.description: Movie management
      homepage.instance.me.widget.type: radarr
      homepage.instance.me.widget.url: http://radarr:7878
      homepage.instance.me.widget.key: ${RADARR_KEY}
```

### Browser Logs

index-15e4eacb6659f3f0.js:1 
        
        
       GET https://myfqdn/api/services/proxy?group=PVR&service=Radarr+%28Anime%29&index=0&endpoint=calendar&query=%7B%22start%22%3A%222024-10-24%22%2C%22end%22%3A%222025-04-24%22%2C%22unmonitored%22%3Afalse%7D 403 (Forbidden)

### Troubleshooting

Homepage itself shows `API Error: radarr: Unknown proxy service type` on the widget when I unhide errors.
