### DISCUSSION TITLE
Multi widget glance containers overlapping

### DISCUSSION THREAD

**Discussion by Raz89x** [gethomepage/homepage#4652] [Support] [answered]
### Description

Only opening this here as opening a bug said it would be closed without a discussion.

When a service contains multiple widgets including glance, the first non-glance widget is overlapped by a following glance widget.

possible fix in css is changing `.chart+.chart` to `.chart+.chart, .service-container+.chart`
this was changed in the browser and was unable to locate in source

non-glance/glance issue
![image](https://github.com/user-attachments/assets/4b0792b3-cd55-47f9-ba1a-6127c130719d)

glance/glance widgets are fine
![image](https://github.com/user-attachments/assets/970a74e3-2376-427b-ab68-97b67bf4c9d0)

non-glance/glance widget modded css result
![image](https://github.com/user-attachments/assets/a1b4ba44-96e5-48fe-8eb4-54e90f164077)

### homepage version

latest 0.10.9

### Installation method

Docker

### Configuration

```yaml
- test:
  widgets:
    - type: glances
      version: 4
      url: -----
      metric: cpu
      username: -----
      password: -----
      refreshInterval: 1000
      pointsLimit: 25
    - type: glances
      version: 4
      url: -----
      metric: network:enp6s18
      username: -----
      password: -----
      refreshInterval: 1000
      pointsLimit: 25        
- Proxmox:
  icon: proxmox.webp
  href: -----
  description:
  ping: -----
  siteMonitor: -----
  widgets:
    - type: proxmox
      url: -----
      username: -----
      password: -----
      fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - type: glances
      version: 4
      url: -----
      metric: sensor:CPUTIN
      username: -----
      password: -----
      refreshIntercal: 1000
      pointsLimit: 25
    - type: glances
      version: 4
      url: -----
      metric: cpu
      username: -----
      password: -----
      refreshIntercal: 1000
      pointsLimit: 25
```

### Troubleshooting

none

**Comment by Raz89x** [comment]
additional custom.css kludge so glances stop overlapping each other

```css
.service-container+.chart {
  margin-top: 2.1em !important;
}
.chart+.chart {
  margin-top: 2.5em !important;
}
```
