### DISCUSSION TITLE
macOS Safari not honouring background settings

### DISCUSSION THREAD

**Discussion by drblmitchell** [gethomepage/homepage#4654] [Support]
### Description

I've been running homepage on an RPi5 for some time with great success. Earlier this month, Safari on macOS stopped honouring the background settings, specifically the `blur`, `brightness` and `opacity` settings. The `image` setting works fine.

Interestingly, if I open homepage on Google Chrome everything works perfectly and oddly if I open it on iOS safari it also works perfectly...

I've cleared my cache, rebuilt the docker container, updated to the latest homepage docker image and still cannot get macOS safari to work correctly.

`docker logs homepage` shows nothing of interest when run as `LOG_LEVEL=debug`, similarly there are no errors in the JS console of safari, in fact no output in the console at all...

Any ideas what is happening and how I can fix it?

Safari macOS:
![Screenshot 2025-01-25 at 1 21 33 pm](https://github.com/user-attachments/assets/c615c402-c4f6-4e65-95bb-a5362e4daa5f)

Chrome macOS:
![Screenshot 2025-01-25 at 1 21 47 pm](https://github.com/user-attachments/assets/8fe492b4-5b3c-40cb-a203-8e78e1ea0157)

Safari iOS:
![IMG_7428](https://github.com/user-attachments/assets/aa1385e9-0a69-4884-9cd7-54f5b1cd6833)

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
settings.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Homelab
theme: dark
color: slate
cardBlur: md
background:
  image: /images/firewatch-river.jpg
  blur: sm
  brightness: 50
  opacity: 90
headerStyle: clean
hideVersion: true
useEqualHeights: true

layout:
  Media:
    style: row
    columns: 2
```

### Container Logs

`docker logs homepage`
```
Listening on port 3000
[2025-01-25T02:43:50.816Z] debug: <resources> memory: {"total":8443396096,"free":138412032,"used":8304984064,"active":4277010432,"available":4166385664,"buffers":112050176,"cached":3873390592,"slab":336756736,"buffcache":4322197504,"swaptotal":209698816,"swapused":200130560,"swapfree":9568256,"writeback":0,"dirty":655360}
[2025-01-25T02:43:51.072Z] debug: <resources> cputemp: {"main":58.4,"cores":[],"max":58.4,"socket":[],"chipset":null}
```

### Browser Logs

Safari console empty

### Troubleshooting

Not applicable
