### DISCUSSION TITLE
Tailscale Widget Stopped Working (Renewed API Kay)

### DISCUSSION THREAD

**Discussion by pretubedongit** [gethomepage/homepage#4656] [Support] [answered]
### Description

    API Error: Unknown error
    URL: https://api.tailscale.com/api/v2/device/n*********CNTRL
    Raw Error:
    {
        "code": "ENETUNREACH"
    }

### homepage version

v0.10.8

### Installation method

Docker

### Configuration

```yaml
- Tailscale:
        icon: tailscale
        widget:
          type: tailscale
          deviceid: n*********CNTRL
          key: tskey-api-********************************************
```

### Container Logs

[2025-01-25T03:14:02.853Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://api.tailscale.com/api/v2/device/n*********CNTRL
[2025-01-25T03:14:07.211Z] error: <httpProxy> Error calling https://login.tailscale.com/...
[2025-01-25T03:14:07.213Z] error: <httpProxy> [
  500,
  AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1173:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1632:3)
      at listOnTimeout (node:internal/timers:571:11)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'ENETUNREACH',
    [errors]: [
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error]
    ]
  }
]

### Browser Logs

    API Error: Unknown error
    URL: https://api.tailscale.com/api/v2/device/n*********CNTRL
    Raw Error:
    {
        "code": "ENETUNREACH"
    }

### Troubleshooting

Tried to renew API. still ng.
Tried curl -u apikey: url. I can get response from both container and host.
