### DISCUSSION TITLE
Docker Service Discovery - Hostname Translates into IP, Breaking Reverse Proxy Rules

### DISCUSSION THREAD

**Discussion by estebanthi** [gethomepage/homepage#4658] [Support] [answered]
### Description

I am using Traefik + docker-socket-proxy to route traffic to Docker API through rules such as `docker.mydomain.com`. However, homepage can't manage to get Docker API info. It looks like `docker.mydomain.com` gets translated into my IP but I made Docker API available only through my reverse proxy so it doesn't work.

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
# docker.yaml

docker-host:
  host: docker.mydomain.com
  port: 443
```

My docker-socket-proxy config for reference:

```yaml
services:
  dockerproxy:
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy
    restart: always
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.docker-server.rule=HostSNI(`docker.${COMPANY_DOMAIN}`)"
      - "traefik.tcp.routers.docker-server.entrypoints=websecure"
      - "traefik.tcp.routers.docker-server.tls.certresolver=myresolver"

networks:
  traefik:
    external: true
```

### Container Logs

homepage  | [2025-01-25T20:29:08.165Z] error: <service-helpers> Error getting services from Docker server 'my_ip': Error: (HTTP code 404) unexpected - 404 page not found
homepage  |
homepage  |     at /app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:382:17
homepage  |     at getCause (/app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:417:7)
homepage  |     at Modem.buildPayload (/app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:378:5)
homepage  |     at IncomingMessage.<anonymous> (/app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:346:16)
homepage  |     at IncomingMessage.emit (node:events:529:35)
homepage  |     at endReadableNT (node:internal/streams/readable:1400:12)
homepage  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
homepage  |   reason: undefined,
homepage  |   statusCode: 404,
homepage  |   json: <Buffer 34 30 34 20 70 61 67 65 20 6e 6f 74 20 66 6f 75 6e 64 0a>
homepage  | }

### Troubleshooting

I tried with different Traefik configurations, it looks like the issue is really just the hostname being translated into an IP.
