### DISCUSSION TITLE
Portainer widget not working

### DISCUSSION THREAD

**Discussion by mclane** [gethomepage/homepage#4665] [Support]
### Description

Portainer widget generates an API error; link is working correctly.
Troubleshooting as per the troubleshooting guide for the portainer widget generates correct output.

### homepage version

0.10.9

### Installation method

Docker

### Configuration

```yaml
services.yaml:

- Portainer:
  href: https://192.168.0.102:9001
  icon: portainer
  widget:
    type: portainer
    url: https://192.168.0.102:9001
    env: 2
    key: ptr_******=
```
```


### Container Logs

Log file output:
```[2025-01-27T12:47:27.269Z] error: <httpProxy> Error calling https://192.168.0.102:9001/api/endpoints/2/docker/containers/json...
[2025-01-27T12:47:27.269Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.102:9001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.102',
    port: 9001
  }
]
```

### Troubleshooting

```
curl -L -k -H 'X-Api-Key:ptr_*********=' 'https://192.168.0.102:9001/api/endpoints/2/docker/containers/json'
```
generates a long json response.
