### DISCUSSION TITLE
Beszel widget not working

### DISCUSSION THREAD

**Discussion by DamianRyse** [gethomepage/homepage#4666] [Support]
### Description

Hi, I'm trying to add Beszel as widgets to my dashboard, but for some reason, I'm getting API errors all the time. I've tried changing the mail address to the user ID, exchange the version number from 2 to 1, etc. but the result is always the same.

What am I doing wrong?

### homepage version

dev (dev, 27. Jan. 2025)

### Installation method

Source

### Configuration

```yaml
widget:
  type: beszel
  url: http://srv-mon-01
  username: user@provider.net
  password: myrandompassword
  systemId: randomsystemstring
  version: 2
```

### Troubleshooting

API-Fehler: Invalid character in header content ["Authorization"]
URL: http://srv-mon-01/api/collections/systems/records?page=1&perPage=500&sort=%2Bcreated
Rohfehler:
{
    "code": "ERR_INVALID_CHAR",
    "level": "error"
}
