### DISCUSSION TITLE
QuickLaunch only suggests services not inside nested groups

### DISCUSSION THREAD

**Discussion by eivarin** [gethomepage/homepage#4669] [Support] [answered]
### Description

The installation is in kubernetes with bjw-s app-template. ([helmrelease manifest](https://github.com/eivarin/Athena-Ops/blob/main/kubernetes/apps/default/homepage/app/helmrelease.yml))

If a service is within a nested group it will not show up in the quicklaunch suggestions.

For example if i search for `kuma` which is not inside a nested group it shows in quick launch:
![image](https://github.com/user-attachments/assets/65c6707f-3835-4eb9-935b-f8522da6ee86)

But if i search for `kubernetes` which is inside a nested group it will not show in quicklaunch(the link being shown is a different bookmark from another tab):
![image](https://github.com/user-attachments/assets/d31516b2-bfcd-444b-905f-878cc0ff8f9d)

I can't figure out if this is a bug or misconfiguration on my part.

### homepage version

 v0.10.7

### Installation method

Docker

### Configuration

```yaml
--- services.yaml relevant snippet ---
- Stats:
  - Uptime Kuma:
      href: https://kuma.<redacted-domain>/
      siteMonitor: &url http://uptime-kuma.observability:3001
      icon: uptime-kuma
      widget:
        type: uptimekuma
        url: *url
        slug: main
  - K8s:
    - Kubernetes Dashboard:
        href: https://k8s.<redacted-domain>/
        siteMonitor: https://kubernetes-dashboard-kong-proxy.observability:443
        icon: kubernetes-dashboard

--- settings.yaml relevant snippet ---
target: _blank
hideErrors: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom
base: https://<redacted-domain>/
background:
  image: https://bing.biturl.top/?resolution=1920x1080&format=image&index=0&mkt=ja-JP
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 40  # 0-100
cardBlur: xl
headerStyle: boxed
useEqualHeights: true
layout:
  ...
  Stats:
    header: false
    tab: Stats
    Kubernetes:
      style: row
  ...
```

### Troubleshooting

Not an API error
Checked container logs - No container logs related to quicklaunch
Checked browser console - No errors/info in the browser console related to quicklaunch
Not a Service/Widget error
Not a missing custom icon error
