### DISCUSSION TITLE
[Feature Request] Lazy Librarian Widget

### DISCUSSION THREAD

**Discussion by Budlyte** [gethomepage/homepage#4676] [Feature Requests]
### Description

Since the Servarr team is giving up on the metadata server issues for Readarr, Lazy Librarian is about to get a bunch of refugees.
https://wiki.servarr.com/readarr/metadata-issues

We need a Lazy Librarian widget, please.  :)

LL API Docs
https://lazylibrarian.gitlab.io/api/

**Comment by AdamWHY2K** [comment]
hah, i've been looking for readarr alternatives thanks. +1

**Reply by Budlyte** [reply]
You are welcome.
Be warned, LL is built on Headphones and really difficult to setup compared to Readarr.  If you want some help, start by searching on their reddit page and use the docs.

The single biggest issue I found in LL is the authors adding related authors loop.
Example: ([1](https://www.reddit.com/r/LazyLibrarian/comments/erbzlo/unwanted_authors_keep_popping_up_in_my_library/)), ([2](https://www.reddit.com/r/LazyLibrarian/comments/cbs5il/ll_adding_comics_and_books_by_authors_i_dont_want/)), [Another Post About the Settings](https://www.reddit.com/r/LazyLibrarian/comments/pzjfnt/having_trouble_with_processing_status_settings/).

If you mess up this setting, adding an author will add their books and then LL will automatically add any secondary authors of those books, and loop.

**Reply by AdamWHY2K** [reply]
thanks for those links, i did run into that problem and they helped :) 

i've got my LL library set up how I want it metadata wise, but now i'm facing an issue  with downloading the missing books, i'm just not getting results from the providers for most books (it successfully downloaded 3 out of 207 books).

any chance i could get a peep at your config?

**Reply by Budlyte** [reply]
Hit me up on Discord. We're pretty far outside of the scope of Homepage and getting to topics better not discussed here.
Jump on the Audiobookshelf discord and DM me @ The_Crimson_Chin
https://discord.gg/yNYqdNNZ

**Comment by joncrangle** [comment]
FYI, you can use the `customapi` widget to display stats from LazyLibrarian:

Example with an API key created called `homepage`, just insert your own after "apikey=":
```yaml
        widget:
          type: customapi
          url: http://lazylibrarian:5299/api?apikey=homepage&cmd=showstats&json
          mappings:
            - field: book_stats.Open
              label: eBooks
              format: number
            - field: book_stats.Wanted
              label: wanted
              format: number
            - field: audio_stats.Open
              label: audiobooks
              format: number
            - field: audio_stats.Wanted
              label: wanted
              format: number
```

Edit: If you visit the showstats endpoint you can see the other key/values available to include.
