### DISCUSSION TITLE
Swag Dashboard behind Authelia on VPS, widget API blocked

### DISCUSSION THREAD

**Discussion by mgrimace** [gethomepage/homepage#4689] [Support]
### Description

I use Swag on a VPS, while Homepage is self-hosted on a local computer. I'd like, if possible to use the Swag Dashboard widget. However, the API calls redirect to Authelia (as expected). Is there a way in homepage to authenticate with Authelia so that I can use that widget? 

### homepage version

main (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
    - Swag:
        icon: nginx
        href: https://swag.{{HOMEPAGE_VAR_DOMAIN}}
        server: docker-oracle
        container: swag
        widget:
            type: swagdashboard
            url: https://swag.{{HOMEPAGE_VAR_DOMAIN}}
    - Authelia:
        icon: authelia
        href: https://authelia.{{HOMEPAGE_VAR_DOMAIN}}
        server: docker-oracle
        container: authelia
```

### Troubleshooting

I attempted to use an unauthenticated path in Authelia for ?stats=true, but apparently that's not a 'path' per se and the over-ride in Authelia doesn't work. This appears to be a unique challenge specific to swag, versus other traditional /api paths. I could be wrong about this though, I'm a novice when it comes to all this.
