### DISCUSSION TITLE
API Error Openweathermap

### DISCUSSION THREAD

**Discussion by Dvalin21** [gethomepage/homepage#4690] [Support]
### Description

Followed instructions to subscribe for the free api key, placed it in the widget.yml, but it still shows api error

```
- openweathermap:
    label: some city #optional
    latitude: 111111
    longitude: 111111
    units: imperial
    provider: openweathermap
    apiKey:  apikey  # required only if not using provider, this reveals api key in requests
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

``` 

### homepage version

10.9

### Installation method

Docker

### Configuration

```yaml
- openweathermap:
    label: some city #optional
    latitude: 111111
    longitude: 111111
    units: imperial
    provider: openweathermap
    apiKey:  apikey  # required only if not using provider, this reveals api key in requests
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

Tried without the api key and just the provider, tried with the key and without the provide, tried with both.
