### DISCUSSION TITLE
[Feature Request] Public IP Info Widget

### DISCUSSION THREAD

**Discussion by hojerst** [gethomepage/homepage#4694] [Feature Requests]
### Description

I'd like to display my public IP in the dashboard. It would be nice to have a widget that displays your public ip (and maybe a way to configure a simple discovery service for that. I personally use ifconfig.me all the time though, which could be a good start)

**Comment by shamoon** [comment]
use custom api for that

**Reply by hojerst** [reply]
thats a service widget though - a customapi for info widget would be fine as well

**Reply by astappiev** [reply]
An example via custom api
```yml
  widget:
    type: customapi
    url: https://api.ipify.org/?format=json # or https://api6.ipify.org/?format=json
    refreshInterval: 300000 # milliseconds, defaults to 10s
    method: GET
    mappings:
      - field: 'ip'
        format: text
```

However, this option misses an opportunity to display 2 addresses: ipv6 and ipv4 (NAT tunnel in my case), which would require sending two requests.

<img width="1314" alt="image" src="https://github.com/user-attachments/assets/dff7aeb9-4010-4a34-895a-0bd90c6227b5" />
Of course, I can use two widgets, but that will require more space.
And in my homepage, it would be perfect to fit two addresses in a single widget.
