### DISCUSSION TITLE
Layout needs manual refresh?

### DISCUSSION THREAD

**Discussion by iohenkies** [gethomepage/homepage#4703] [General]
I've deployed homepage on Kubernetes and all is running fine. I've got one annoyance though, and that is that every time I redeploy (`kubectl rollout restart`), the config from the `settings.yaml` seems to be needed to be re-applied with the refresh icon at the bottom right (see screenshot).

![image](https://github.com/user-attachments/assets/d60c58ac-c725-4df9-a26a-80477e8102c5)

Only then my 'custom' layout like seen in the below codeblock, shows up. Is this expected? I rather not do this every time. I also need to do this when I redeploy, without actually changing the `settings.yaml`, but for instance the `bookmarks.yaml`.

```
    headerStyle: boxed
    layout:
      ArgoCD:
        style: row
        columns: 3
      General:
        style: column
      Network:
        style: column
```

Thanks in advance for any insights!

**Comment by shamoon** [comment]
I dont use k8s, not that I can imagine why that would matter, but no, thats not expected. Homepage uses a simple hash which is checked (on focus) and should reload if needed

**Comment by iohenkies** [comment]
Thanks!

I just noticed some problems in the logs, which most probably has something to do with it then.

```
[2025-02-04T10:53:34.997Z] error: undefined
[2025-02-04T10:53:59.945Z] error: Error: EACCES: permission denied, copyfile '/app/src/skeleton/custom.css' -> '/app/config/custom.css'
    at copyFileSync (node:fs:2982:3)
    at checkAndCopyConfig (/app/.next/server/chunks/1090.js:53:55)
    at /app/.next/server/pages/api/hash.js:74:78
    at Array.map (<anonymous>)
    at handler (/app/.next/server/pages/api/hash.js:73:26)
    at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
[2025-02-04T10:53:59.945Z] error: undefined
```

I can't run the pod as root because of security constraints on the cluster. The `node` user with uid 1000 doesn't have permissions to write in the `/app/config` folder. I need to figure something out to work around this :|

**Comment by iohenkies** [comment]
The problem was, as expected, that my non-root user did not have the proper privileges to write files to /app/config resulting in the above error and the refresh annoyance.

This can be solved by patching the home page deployment by using an emptyDir.

Like so:

```
spec:
  template:
    spec:
      containers:
        - name: homepage
          volumeMounts:
            - name: config
              mountPath: /app/config
```

And so:

```
      volumes:
        - name: config
          emptyDir: {}
```

For when other people may stumble upon this use case.
