### DISCUSSION TITLE
Bug: No way to use nested groups via annotations

### DISCUSSION THREAD

**Discussion by disconn3ct** [gethomepage/homepage#4704] [Support] [answered]
### Description

It does not seem to be possible to use ingress annotations to target a nested group.

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
services:
  - Hardware:
    - Group1:
      - Foo:
        description: Examples
    - UPS:
```

ingress:
```yaml
annotations:
  gethomepage.dev/enabled: "true"
  gethomepage.dev/description: Random Battery
  gethomepage.dev/group: Hardware/UPS
  gethomepage.dev/name: Battery
```
In general it behaves as you'd expect without nested groups:
"Hardware/UPS" results in a new "Hardware/UPS" group. Same for "Hardware.UPS".
"UPS" results in a UPS top-level group. (I had hoped maybe it would find the nested group.)
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

n/a

**Comment by shamoon** [comment]
I don’t actually use k8s so testing this would be a bit of a challenge. You’re saying you’ve defined the group in the “layout” block of settings? (Your code above says otherwise)

**Comment by disconn3ct** [comment]
Looking at https://gethomepage.dev/configs/services/#nested-groups I didn't think I needed a layout for nested groups. (I have tried with and without.)

What is the annotation syntax for addressing a nested group? (And is it possible to differentiate groups under different headers? EG "Downstairs/Lights" and "Upstairs/Lights".)

Using the examples, https://gethomepage.dev/configs/kubernetes/#automatic-service-discovery shows that these annotations:
```yaml
gethomepage.dev/group: Media
gethomepage.dev/name: Emby
gethomepage.dev/icon: emby.png
```
are grouped as:
```yaml
services:
 - Media:
   - Emby:
     icon: emby.png
```

How would I turn it to:
```yaml
services:
  - Media:
    - Sources:
      - Emby:
        icon: emby.png
...
```

**Reply by shamoon** [reply]
It does work with docker, which again, I can easily confirm. There is no support for e.g. `X/Y` but in general, using the name of the group should target an existing group of the same name (so just "UPS" in your example)

**Reply by disconn3ct** [reply]
I am still not having any luck targetting a nested group using k8s ingress annotations.

If I understand what you said, I should just be able to reference a unique nested group name the same as a top-level group.

Starting with:
```
services:
  - Media:
    - Nested:
      - Emby: # a manual service definition
```

If I set the annotation to:

`gethomepage.dev/group: "Media"`: This lands in the top-level Media group as expected.

`gethomepage.dev/group: "Media/Nested"`: This creates a new top-level "Media/Nested" group, also as expected.

`gethomepage.dev/group: "Nested"`: This results in `error: undefined` in the logs. `LOG_LEVEL=DEBUG` doesn't seem to help.

```syslog
homepage [2025-02-04T19:19:03.307Z] info: custom.css was copied to the config folder
homepage [2025-02-04T19:19:03.309Z] info: custom.js was copied to the config folder
homepage [2025-02-04T19:19:03.347Z] debug: <resources> fsSize: ...
homepage [2025-02-04T19:19:03.348Z] debug: No containers were found with homepage labels.
homepage [2025-02-04T19:19:03.357Z] debug: <resources> memory: ...
homepage [2025-02-04T19:19:03.610Z] debug: No containers were found with homepage labels.
homepage [2025-02-04T19:19:05.588Z] error: undefined
homepage [2025-02-04T19:19:05.605Z] debug: <servicesProxy> Unknown proxy service type: undefined
homepage [2025-02-04T19:19:06.897Z] error: undefined
```

Here are all of the gethomepage annotations in case the issue is there:
```yaml
annotations:
  gethomepage.dev/description: Jelly
  gethomepage.dev/enabled: "true"
  gethomepage.dev/group: Nested
  gethomepage.dev/href: https://jelly.url
  gethomepage.dev/icon: jellyfin
  gethomepage.dev/name: Jelly
  gethomepage.dev/widget.enableBlocks: "true"
  gethomepage.dev/widget.enableNowPlaying: "true"
  gethomepage.dev/widget.enableUser: "true"
  gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_JELLYFINAPI}}'
  gethomepage.dev/widget.showEpisodeNumber: "true"
  gethomepage.dev/widget.type: jellyfin
  gethomepage.dev/widget.url: http://jellyfin.media.svc:8096
```
