### DISCUSSION TITLE
Services not ordered by name when manual config with weight 0 and docker combined

### DISCUSSION THREAD

**Discussion by duts-ke** [gethomepage/homepage#4705] [Support]
### Description

I've configured two static services in the services.yaml file and three dynamic via docker labels.
The two static ones are configured with weight 0 to sort all of them by name. However only the first static service is sorted by name:
![image](https://github.com/user-attachments/assets/680e4a67-c5c6-48e8-8e9e-5fcc9cf72ccb)

### homepage version

v0.10.9 (b5f4daa)

### Installation method

Docker

### Configuration

```yaml
- Network Services:
    - Pi-Hole RP:
        icon: sh-pi-hole
        href: {REDACTED}
        description: Ad-Blocking DNS Server
        weight: 0
    - Traefik RP:
        icon: sh-traefik
        href: {REDACTED}
        description: Open Source Edge Router
        weight: 0
```

### Troubleshooting

When the weight of Traefik RP is set to -1 it is on top of the list. So the weight setting does work.

When changing the order in the services.yaml file (while keeping the weight for both at 0), Traefik RP is sorted by name between the dynamic containers and Pi-Hole RP is put at the bottom.

```yaml
- Network Services:
    - Traefik RP:
        icon: sh-traefik
        href: {REDACTED}
        description: Open Source Edge Router
        weight: 0
    - Pi-Hole RP:
        icon: sh-pi-hole
        href: {REDACTED}
        description: Ad-Blocking DNS Server
        weight: 0
```

![image](https://github.com/user-attachments/assets/38380586-ca3b-4c0f-83b2-374d1cb96649)

Did some digging in the script part of the webpage. And the second static entry seems to be getting a weight of 100 instead of the 0 configured in yaml.
If the weight is set to 1 in the config, it is also 1 in the script part of the webpage.

```json
"fallback": {
    "/api/services": [
        {
            "name": "Network Services",
            "services": [
                {
                    "name": "Pi-Hole",
                    "container": "Pihole",
                    "server": "my-docker",
                    "type": "service",
                    "description": "Ad-Blocking DNS Server",
                    "href": "REDACTED",
                    "icon": "sh-pi-hole",
                    "weight": 0,
                    "widgets": []
                },
                {
                    "name": "Pi-Hole RP",
                    "icon": "sh-pi-hole",
                    "href": "REDACTED",
                    "description": "Ad-Blocking DNS Server",
                    "weight": 0,
                    "type": "service",
                    "widgets": []
                },
                {
                    "name": "Traefik",
                    "container": "Traefik",
                    "server": "my-docker",
                    "type": "service",
                    "description": "Open Source Egde Router",
                    "href": "REDACTED",
                    "icon": "sh-traefik",
                    "weight": 0,
                    "widgets": []
                },
                {
                    "name": "Unifi",
                    "container": "Unifi",
                    "server": "my-docker",
                    "type": "service",
                    "description": "Unifi Controller",
                    "href": "REDACTED",
                    "icon": "sh-ubiquiti-unifi",
                    "weight": 0,
                    "widgets": []
                },
                {
                    "name": "Traefik RP",
                    "icon": "sh-traefik",
                    "href": "REDACTED",
                    "description": "Open Source Edge Router",
                    "weight": 100,
                    "type": "service",
                    "widgets": []
                }
            ],
            "groups": []
        }
    ]
}
```
