### DISCUSSION TITLE
iFrame refreshing broken

### DISCUSSION THREAD

**Discussion by kexo1** [gethomepage/homepage#4709] [Support]
### Description

I use iframe widget to see my camera snapshot (taken from go2rtc), which refreshes every 20 seconds. However if you're casually browsing on other tabs for some time, and you go back on homepage, it seems like it tries to catch up that lost time - like if i was gone from homepage for 60 seconds, and I go back it refreshes 3 times (60/20) as fast as it can.  Here's example:

https://streamable.com/w5hhyn

But if you stay on site, it refreshes every 20 seconds just like I set in widget.

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
widget:
           type: iframe
           name: camera-iFrame
           src: https://my.domain/go2rtc/api/frame.jpeg?src=camera&width=640&height=360
           classes: rounded w-full aspect-video h-auto  # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
           referrerPolicy: same-origin
           allowFullscreen: true
           allowScrolling: no
           refreshInterval: 20000
```

### Troubleshooting

Everything is reachabe
