### DISCUSSION TITLE
Glances Service Widget Incorrect Memory usage for Docker Containers

### DISCUSSION THREAD

**Discussion by gflip220** [gethomepage/homepage#4710] [Support] [answered]
### Description

While using the Glances service widget (Containers metric), I have noticed the reported memory usage for Docker containers does not match what Glances and Docker Stats show.  While Glances and Docker stats match, the Homepage widget shows sometimes wildly different memory statistics.  This does not appear to be a timing issue as the numbers are consistently incorrect.  

This screenshot, while cropped for size, was taken with all three windows on the screen at the same time.  Note how several memory statistics on the widget are very far apart from Glances itself.  

This is a freshly built Ubuntu 24.04 with latest versions of everything.  Any thoughts as to what I may be able to check?  Thank you!

![image](https://github.com/user-attachments/assets/5b871d82-024f-478d-b48b-6b7cb59c59ab)

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
Basic glances/containers services.yaml entry:

   - Containers:          
        widget:
          type: glances
          url: http://IP:61208
          version: 4 # required only if running glances v4 or higher, defaults to 3
          metric: containers
          refreshInterval: 5000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
          pointsLimit: 15 # optional, defaults to 15
```

### Troubleshooting

Troubleshooting steps do not appear relevant.  Logs are not showing any errors relative to this issue.  Homepage and Glances widget appear to otherwise work correctly.
