### DISCUSSION TITLE
API errors (HTTP 500, errno -3001) on Service Widgets after moving to the current Homepage Repo

### DISCUSSION THREAD

**Discussion by Pete060490** [gethomepage/homepage#4712] [Support]
### Description

As the title says, I recently updated and moved from the old repo to the new one (I know, it's been a while). Before, everything was working without a problem. 
Since then, in what to me seems somewhat random, one or two of my widgets throws and unknown API error. After a few seconds, functionality is restored. It seems that all (or most of) my widgets exhibit this behavior.

I'm using Traefik 3 (latest update) for my services, so that also could be the source of the error (HTTP 500 error), but since the old version of Homepage worked just fine, I'm not so sure.

I've looked through quite a few issues with similar problems but couldn't find a fix. Any help is greatly appreciated. :)

### homepage version

0.10.9

### Installation method

Docker

### Configuration

```yaml
---Compose File---

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - PUID=5001
      - PGID=5000
      - TZ=Europe/Berlin
    env_file: .env
    volumes:
      - /data/appdata/homepage/config:/app/config
      - /data/appdata/homepage/icons:/app/public/icons
    networks:
      - homepage
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage-secure.entrypoints=websecure
      - traefik.http.routers.homepage-secure.rule=Host(`homepage.local.xxx.de`)
      - traefik.http.routers.homepage-secure.middlewares=local-whitelist@file,default-headers@file
      - traefik.http.routers.homepage-secure.tls=true
      - traefik.http.routers.homepage-secure.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.docker.network=homepage
networks:
  homepage:
    name: homepage
    ipam:
      config:
        - subnet: 172.104.0.0/16
          gateway: 172.104.0.1

--- Services File ---
    - Proxmox-Local:
        href: https://proxmox.local.xxx.de
        icon: proxmox.png
        ping: https://proxmox.local.xxx.de
        description:
        widget:
          type: proxmox
          url: https://proxmox.local.xxx.de
          username: "{{HOMEPAGE_VAR_PVE_USER}}"
          password: "{{HOMEPAGE_VAR_PVE_PASSWORD}}"
          node: pve
```

### Container Logs

```
[2025-02-03T17:29:40.840Z] error: <httpProxy> Error calling https://proxmox.local.xxx.de/api2/json/cluster/resources...
[2025-02-03T17:29:40.841Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN proxmox.local.xxx.de
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'proxmox.local.xxx.de'

```

### Browser Logs

```
    API Error: Unknown error
    URL: https://proxmox.local.xxx.de/api2/json/cluster/resources
    Raw Error:
    {
        "errno": -3001,
        "code": "EAI_AGAIN",
        "syscall": "getaddrinfo",
        "hostname": "proxmox.local.xxx.de"
```

### Troubleshooting

I went back to the old version and functionality was restored. I have no idea whats going on.
