### DISCUSSION TITLE
Bug in iCal integration: username and password stripped when used in url like http://user:password@url

### DISCUSSION THREAD

**Discussion by conchyliculture** [gethomepage/homepage#4718] [Support]
### Description

I want to use a service widget calendar, with ical integration. My remote caldav service requires basic auth authentication.

It works well when I curl https://username:password@myurl.com/cal/, but when using that same URL for the service, it seems the user and password get stripped, and I get a 401 error. This is confirmed on the server side, as the logs show no attempt at using HTTP Basic authentication

### homepage version

v0.10.9(b5f4daa)

### Installation method

Docker

### Configuration

```yaml
widget:
  type: calendar
  timezone: Europe/Paris
  integrations:
     - type: ical
       url: https://username:password@url/cal
```

### Troubleshooting

`curl -k https://username:password@url/cal` returns calendar data
