### DISCUSSION TITLE
iFrame or Stream for AgentDVR camera streams

### DISCUSSION THREAD

**Discussion by Fizzy77** [gethomepage/homepage#4719] [Support]
### Description

I'm trying to see is I can get the camera stream (mjpeg or jpeg) into Homepage in either an iFrame or a Mjpeg widget.

Neither want to display the video or jpeg image/
![image](https://github.com/user-attachments/assets/f5ae764c-94f2-477d-91df-ceca20948e6a)

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- GarageCam:
        widget:
          type: iframe
          name: GarageCam
          src: http://192.168.77.13:8090/grab.jpg?oid=1&size=1920x1080
          refreshInterval: 2000
    - DriveCam: 
        widget:
          type: mjpeg
          name: GarageCam
          stream: http://192.168.77.13:8090/video.mjpg?oid=2
```

### Troubleshooting

Only screenshot above
