### DISCUSSION TITLE
[Feature Request] Palworld widget

### DISCUSSION THREAD

**Discussion by ichlaffterlalu** [gethomepage/homepage#4720] [Feature Requests]
# Description

I would like to request a new widget that shows basic Palworld server stats.
If you don't know about Palworld, it's an open-world pet-catching game made by Pocketpair (https://www.pocketpair.jp/palworld).
A Palworld server has its own REST API, showing stats of currently running server, such as Server Frame-per-Second (FPS), Days-in-Game, and Currently Logged-in Players.

## About the API
Here is the documentation about Palworld's API:
- Server Info: https://docs.palworldgame.com/api/rest-api/info
- Server Metrics: https://docs.palworldgame.com/api/rest-api/metrics

## Current Situation
Currently, I can extract informations from Palworld's API using "Custom API" widget, with this configuration:
```yaml
  - Palworld:
      icon: /images/palworld.png
      description: Some custom world
      widget:
        type: customapi
        url: http://palworld:8212/v1/api/metrics
        username: **********
        password: **********
        mappings:
          - field: serverfps
            label: FPS
            format: number
          - field: currentplayernum
            label: Players
            format: number
          - field: serverframetime
            label: Frame Time
            format: float
          - field: days
            label: In-Game Days
            format: number
```
Unfortunately, unlike the `minecraft` widget where it can indicate the online/offline status of a server, this one doesn't.
This one shows API error instead when the server is turned off, which is expected, but is not the behaviour I wanted.

## What I Wished for This Widget to Be
Here is the list of fields that can be showed up in the `palworld` widget:
| **Field Description** | **Field Codename** | **Possible Values/Types** | **API Source**                                                           | **JSON Segment**                                                                     | **Default?** |
|-----------------------|--------------------|---------------------------|--------------------------------------------------------------------------|--------------------------------------------------------------------------------------|--------------|
| Status                | `status`           | "Offline" or "Online"     | Any API, when the API returns ENOTFOUND error, or HTTP 500 status code.  |                                                                                      | **Yes**       |
| Players               | `players`          | integer/integer           | /v1/api/metrics                                                          | Before slash: `currentplayernum`<br />After slash: `maxplayernum`                    | **Yes**       |
| Server FPS            | `fps`              | integer                   | /v1/api/metrics                                                          | `serverfps`                                                                          | **Yes**       |
| Version               | `version`          | string                    | /v1/api/info                                                             | `version`                                                                            | No            |
| Frame Time (ms)       | `frametime`        | float                     | /v1/api/metrics                                                          | `serverframetime`                                                                    | No            |
| Uptime                | `uptime`           | time                      | /v1/api/metrics                                                          | `uptime` (in seconds [integer], we need to convert it to time format: `dd hh:mm:ss`) | No            |
| Days In-Game          | `days`             | integer                   | /v1/api/metrics                                                          | `days`                                                                               | No            |

The `status` and `players` are fields that I can't recreate using "Custom API" widget, so I want to have this implemented using separate widget.
Also indicating "server off" by showing red API errors feels just too annoying rather than having dedicated `status` field.

## Configurations of the Widget
Here is the example on how I want the widget configuration to be:
```yaml
widget:
  type: palworld
  url: http://palworld.host.or.ip
  username: admin
  password: password
  fields: ["status", "players", "serverfps"]
```

# Other

To try run a Palworld server yourself, I recommend this Docker image: `thijsvanloef/palworld-server-docker:dev`
Here is the GitHub repo for that: https://github.com/thijsvanloef/palworld-server-docker
