### DISCUSSION TITLE
Proxmox Backup Server Bug

### DISCUSSION THREAD

**Discussion by MatzHilven** [gethomepage/homepage#4724] [Support]
### Description

The PBS widget is not working, it has a type error.
https://github.com/gethomepage/homepage/blob/0615799c6cda81db02fd75a88a7da4d459211f91/src/widgets/proxmoxbackupserver/component.jsx#L32

It looks like the response does not contain an array, just plain json fields.

https://github.com/proxmox/proxmox-backup/blob/master/src/api2/node/status.rs

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
- PBS:
      description: Proxmox Backup Server.
      href: https://192.168.1.70:8007/
      icon: proxmox.png
      widget:
        type: proxmoxbackupserver
        url: https://192.168.1.70:8007
        username: ...
        password: ...
```

### Browser Logs

TypeError: i.data[0] is undefined
component error: TypeError: i.data[0] is undefined, info: [object Object]

### Troubleshooting

Output of `https://192.168.1.70:8007/api2/json/nodes/localhost/status`:

`{"data":{"boot-info":{"mode":"legacy-bios","secureboot":false},"cpu":0.0012897678417884695,"cpuinfo":{"cpus":4,"model":"QEMU Virtual CPU version 2.5+","sockets":1},"current-kernel":{"machine":"x86_64","release":"6.8.12-4-pve","sysname":"Linux","version":"#1 SMP PREEMPT_DYNAMIC PMX 6.8.12-4 (2024-11-06T15:04Z)"},"info":{"fingerprint":""},"kversion":"Linux 6.8.12-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-4 (2024-11-06T15:04Z)","loadavg":[0.0,0.0,0.0],"memory":{"free":3931111424,"total":4108349440,"used":177238016},"root":{"avail":25311084544,"total":29061197824,"used":2247925760},"swap":{"free":4106219520,"total":4106219520,"used":0},"uptime":4860,"wait":0.001}}`
