### DISCUSSION TITLE
mount external drive in "resources"

### DISCUSSION THREAD

**Discussion by eras3r86** [gethomepage/homepage#4725] [Support]
### Description

i'm not able to mount an external drive.
i get api error...
if i mount in "resources" '/' it works and it shows the internal disk but if i try to mount the external drive (put the path show by the command df) i get api error...

### homepage version

0.10.9

### Installation method

Docker

### Configuration

```yaml
- resources:
    expanded: true
    cpu: true
    cputemp: true
    memory: true
    uptime: true
    disk: /media/usbdisk/
```

### Troubleshooting

API error
