### DISCUSSION TITLE
Audiobookshelf widget is not working

### DISCUSSION THREAD

**Discussion by joalmeid** [gethomepage/homepage#4728] [Support]
### Description

The Audiobookshelf is not working, following documented widget configuration. An error is redered in the Homepage UI: 
API Error Information
API Error: Error getting data from Audiobookshelf: 500. Data: [object Object]

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- Audiobookshelf:
        icon: audiobookshelf.svg
        href: "HTTP://xxx:8083"
        description: Ebooks, AudioBooks & Podcasts
        ping: "HTTP://xxx:8083"
        target: _blank
        widget:
            type: audiobookshelf
            url: "HTTP://xxx:8083"
            key: "YYYYYYYYYYYYYY"


NOTE: X and Y values have been verified.
```

### Container Logs

[2025-02-09T16:26:31.229Z] error: <httpProxy> Error calling http://audiobookshelf:XXXX/api/libraries...
[2025-02-09T16:26:31.234Z] error: <httpProxy> [
  500,
  AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at afterConnectMultiple (node:net:1601:5) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error] ]
  }
]
[2025-02-09T16:26:31.235Z] error: <audiobookshelfProxyHandler> Error: Error getting data from Audiobookshelf: 500. Data: [object Object]
    at retrieveFromAPI (/app/.next/server/pages/api/services/proxy.js:1442:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async audiobookshelfProxyHandler (/app/.next/server/pages/api/services/proxy.js:1485:25)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:365:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:303:20)
    at async Server.<anonymous> (/app/server.js:19:5)

### Browser Logs

index-15e4eacb6659f3f0.js:1 
                
       GET http://xxxx:3000/api/services/proxy?group=Media&service=Audiobookshelf&index=0&endpoint=libraries 500 (Internal Server Error)

### Troubleshooting

trying to access the Audiobookshelf API directly from a browser. All returns ok.
