### DISCUSSION TITLE
Multiple iCal's in a single calendar.

### DISCUSSION THREAD

**Discussion by MartinBelko** [gethomepage/homepage#4734] [Feature Requests]
I work with multiple iCal sources and would like the option to have all of them merged into a single calendar and agenda view. 

At least from the documentation I couldn't see any option for multiple iCal's, unless I've missed something.

I've been able to add multiple iCal Integrations, but if I remember correctly, both the color and iCal gets overwritten by the last iCal written.

**Comment by Staubgeborener** [comment]
Indeed, this problem still exists today. The problem only occurs with iCal integrations. For example, if I want to integrate a sonarr and a radarr into one calendar, this works:
```
          widget:
              type: calendar
              view: agenda
              maxEvents: 10
              previousDays: 3
              integrations:
                - type: sonarr
                  service_name: Sonarr
                  params:
                    unmonitored: false
                - type: radarr
                  service_name: Radarr
                  params:
                    unmonitored: false
```
But the same thing does not work with iCal:

```
          widget:
              type: calendar
              view: agenda
              maxEvents: 10
              previousDays: 3
              integrations:
                - type: ical
                  url: https://calendar.google.com/calendar/ical_1.ics
                - type: ical
                  url: https://calendar.google.com/calendar/ical_2.ics
```
In this case, the last entry `ical_2.ics` is simply ignored and only the first URL `ical_1.ics` is displayed inside the calendar widget.

This is a bug which belongs into the issue section @shamoon
