### DISCUSSION TITLE
Plex Display Recently Added Posters (8)

### DISCUSSION THREAD

**Discussion by Keatingfish** [gethomepage/homepage#4738] [Support]
### Description

Losing my mind as I cannot get my api to show in Homepage. 
All tokens and IPs were removed for this post.

Format of the JSON is as follows :::

[
  {
    "added_at": "2025-02-09T02:25:41",
    "library": "IDTV",
    "poster": "http://<plexip>/library/metadata/175557/thumb/1739109891?X-Plex-Token=<token>",
    "title": "The Curious Case Of...",
    "type": "show"
  },
  ]

I can see this file at http://<plexip>:<port>/recently_added

I can see this file inside of my homepage docker console by using GET, 0 issues.

No matter how I try to add this to my services.yaml I always end up with the same ending :::

Recently Added (Title for the Service)
and then either - Title and - Poster

It will not parse the info into Homepage no matter what. I have confirmed everything works outside and inside the docker except I cannot get it to show any info from that recently added link.

### homepage version

v0.10.9

### Installation method

Unraid

### Configuration

```yaml
- AddedPlex:
    - Recently Added:
        icon: plex
        href: http://<plexip>:port/
        widget: 
          type: customapi
          url: http://<plexip>:port/recently_added
          method: GET
          fields: ["title, added_at, library, poster, type"]
          mappings: 
            - field: title
              format: text
```

### Container Logs

Nothing appears as an error in the log

### Troubleshooting

I have tried every variation of DisplayTemplate/etc that AI could give me. I always end up where the location of the JSON (that only shows recent 8) does not show in Homepage no matter what. I can do a GET inside the homepage docker console to that link and it does populate with all info. So it does see it.
