### DISCUSSION TITLE
Tailscale wiget give unknown error

### DISCUSSION THREAD

**Discussion by soheiladeli** [gethomepage/homepage#4739] [Support] [answered]
### Description

I have configured the Tailscale widget as per the documentation. But in home page it give unknown error as below:

API Error: Unknown error
URL: https://api.tailscale.com/api/v2/device/nVwpDJAnCR11CNTRL
Raw Error:
{
    "code": "ETIMEDOUT"
}
<img width="432" alt="image" src="https://github.com/user-attachments/assets/771bbccc-d0c7-4b8d-8063-a1a38cbdb765" />

I can call the api from the homepage container and it successfully retrieve information

curl --request GET --url https://api.tailscale.com/api/v2/device/xxxxxxxxxxxxxx -H "Authorization: Bearer tskey-api-xxxxxxxxxxxxxxxxx"

homepage is installed in Proxmox container. All other services and widgets work fine.

### homepage version

v0.10.9

### Installation method

Other (please describe above)

### Configuration

```yaml
My widget setup in my Services yaml:

    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        ping: https://login.tailscale.com/admin/machines    
        widget:
          url: https://login.tailscale.com/admin/machines
          type: tailscale
          deviceid: xxxxxxxxxxxCNTRL
          key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### Container Logs

[2025-02-11T02:44:26.047Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://api.tailscale.com/api/v2/device/nVwpDJAnCR11CNTRL
[2025-02-11T02:44:33.151Z] error: <httpProxy> Error calling https://api.tailscale.com/api/v2/device/nVwpDJAnCR11CNTRL...
[2025-02-11T02:44:33.152Z] error: <httpProxy> [
  500,
  AggregateError [ETIMEDOUT]: 
      at internalConnectMultiple (node:net:1122:18)
      at internalConnectMultiple (node:net:1190:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1716:5)
      at listOnTimeout (node:internal/timers:583:11)
      at process.processTimers (node:internal/timers:519:7) {
    code: 'ETIMEDOUT',
    [errors]: [
      [Error], [Error], [Error], [Error],
      [Error], [Error], [Error], [Error],
      [Error], [Error], [Error], [Error],
      [Error], [Error], [Error], [Error],
      [Error], [Error], [Error], [Error],
      [Error], [Error], [Error], [Error],
      [Error], [Error], [Error], [Error],
      [Error], [Error], [Error], [Error]
    ]
  }
]
[2025-02-11T02:44:33.152Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://api.tailscale.com/api/v2/device/nVwpDJAnCR11CNTRL

### Browser Logs

API Error: Unknown error
URL: https://api.tailscale.com/api/v2/device/nVwpDJAnCR11CNTRL
Raw Error:
{
    "code": "ETIMEDOUT"
}

### Troubleshooting

I can call the api from the homepage container and it successfully retrieve information:

root@homepage:~# curl --request GET --url https://api.tailscale.com/api/v2/device/xxxxxxx -H "Authorization: Bearer tskey-api-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxF"
