### DISCUSSION TITLE
Multiple widgets won't work

### DISCUSSION THREAD

**Discussion by Gapoly** [gethomepage/homepage#4741] [Support]
### Description

I'm trying to use 2 widgets on 1 service, for example on Plex, I'd like to use Plex and Uptime Kuma widget.

I do have a status page on my Uptime Kuma on "https://kuma.nemeanas.lan:31050/status/plex" and I get this error : 

![image](https://github.com/user-attachments/assets/df54a14b-74d2-4dd3-8cc0-ebdf03d915a5)
*(Widget type is missing)*

### homepage version

0.10.9

### Installation method

Docker

### Configuration

```yaml
- Plex:
        icon: https://www.plex.tv/wp-content/themes/plex/assets/img/favicons/favicon.ico
        href: https://192.168.1.88:32400/web/index.html#!/
        description: Médiathèque
        siteMonitor: https://192.168.1.88:32400/web/index.html#!/
        widget:
            - type: plex
              url: https://192.168.1.88:32400
              key: topsecretapikey
            - type: uptimekuma
              url: https://kuma.nemeanas.lan:31050
              slug: plex
```

### Troubleshooting

Removed 1 widget and it worked
