### DISCUSSION TITLE
Beszel Wdiget Fields

### DISCUSSION THREAD

**Discussion by beboprocky** [gethomepage/homepage#4750] [Support] [answered]
### Description
https://gethomepage.dev/widgets/services/beszel/

Greetings! How can I add additional fields to the Beszel widget? My widget will show "NAME", "STATUS", "CPU", and "MEM" but I don't know how to add additional fields or replace existing ones. Ideally I would like to add "disk" and "network" which are supported. I do not see any fields in the YAML to be able to add or edit these fields.

> Allowed fields for 'overview' mode: ["systems", "up"] Allowed fields for a single system: ["name", "status", "updated", "cpu", "memory", "disk", "network"]

```
widget:
  type: beszel
  url: http://beszel.host.or.ip
  username: username # email
  password: password
  systemId: systemId # optional
  version: 2 # optional, default is 1
```

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Troubleshooting

Not relevant

**Comment by shamoon** [comment]
“Adding” fields is not a thing

**Comment by beboprocky** [comment, marked as answer]
Issue solved. Was able to find in a thread about a different widget. You can add "fields:" to the YAML and specify which four fields you'd like Beszel to show. Example:

```
- Beszel:
    icon: beszel
    href: ip-address:8090
    widget:
      type: beszel
      url: ip-address:8090
      username: email@email.com
      password: password
      systemId: Name
      version: 2
      fields: ["disk", "network", "cpu", "memory"]
```
