### DISCUSSION TITLE
Is there a way to suppress labels in nested groups?

### DISCUSSION THREAD

**Discussion by iandouglas** [gethomepage/homepage#4765] [Support] [answered]
### Description

I have a few nested sections in my services.yaml file and every nested group prints out its label on the screen. Is there a way to suppress this from happening? I want things nested on the screen, but not print the labels.

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- Home Stuff
  - Family Calendar: # i'd like to NOT print this label
    - calendar:
        name: calendar
        widget:
          type: iframe
          etc
  - Bookmarks # I'd like to NOT print this label on the screen
    - Top Links
      - Meal Planning
        description: Mealie
        href: etc
    - School bookmarks
      - Parent portal
        description: Mealie
        href: etc
etc
etc
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

<img width="910" alt="image" src="https://github.com/user-attachments/assets/acbbcbc5-859c-4580-ace6-3cdd3025180d" />
