### DISCUSSION TITLE
[Feature Request] Epic Games Free Games Widget

### DISCUSSION THREAD

**Discussion by tpbnick** [gethomepage/homepage#4768] [Feature Requests]
### Description

I already have the code working on my own fork of Homepage.  While I was creating the PR and checking the guidelines, I noticed the following:
```
Please only submit widgets that target a feature request discussion with at least 20 'up-votes'. The purpose of this requirement is to avoid the addition (and maintenance) of service widgets that might only benefit a small number of users.
```

This is that feature request!  The widget displays current and upcoming free games. Here is an image of the working widget:
![image](https://github.com/user-attachments/assets/5d29f522-7d44-424e-87e1-d741cf3a4b9c)

Clicking on the widget takes you to the "Free Games" section of Epic Game's homepage, where you can claim them.  I am in no way affiliated with Epic Games, I just often forget to claim all the free games and this widget would definitely help!

Comments/suggestions/gripes welcomed!

**Comment by mfhulskemper** [comment]
Friendly bump.

**Comment by spider1163** [comment]
I use 

https://github.com/claabs/epicgames-freegames-node

Automatically login and find available free games the Epic Games Store. Sends you a prepopulated checkout link so you can complete the checkout after logging in. Supports multiple accounts, login sessions, and scheduled runs.

**Comment by SimplyKok** [comment]
I was looking for something similar, and came up with a solution myself using existing "Custom API" widget.

<img width="599" height="125" alt="image" src="https://github.com/user-attachments/assets/9f9c7990-a753-496b-93c2-b02b0022b02b" />

For anyone interested, I am sharing what I did here.

To define in services.yaml:
```
- Epic Games Store:
    icon: sh-epic-games.png
    widgets:
      - type: customapi
        url: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=SG&allowCountries=SG
        method: GET
        headers:
          Content-Type: application/json
        display: dynamic-list
        mappings:
          items: data.Catalog.searchStore.elements
          name: title
          label: price.totalPrice.discountPrice
          target: https://store.epicgames.com/en-US/p/{offerMappings.0.pageSlug}
```
With this, I have generated dynamic list of all games returned by API. Since the custom API widget does not allow for item filtering (maybe should be a feature request in itself), I wrote custom javascript to do filtering post rendering. I took advantage of the label field to represent the price, which the javascript will use for filtering (show only items with price == 0).

To define in custom.js:
```
function filterEpicGames() {
    document.querySelectorAll('li[data-name="Epic Games Store"] [class*="flex-row"]').forEach(entry => {
        entry.style.display = entry.querySelector('.text-right')?.innerText === "0" ? 'flex' : 'none';
    });
}

new MutationObserver((mutations) => { filterEpicGames(); }).observe(document.body, { childList: true, subtree: true });
```

With both changes, you will get widget as seen in my attached screenshot. It is abit hacky, but it works well for my needs, and most importantly for me, without a custom homepage build.
