### DISCUSSION TITLE
0.10.9 help on using local background image

### DISCUSSION THREAD

**Discussion by rharmonson** [gethomepage/homepage#4769] [Support] [answered]
### Description

My assumption is I am the problem, but looking for help with using a local image. I pulled down the current release v0.10.9 and successfully built and added services, widgets, and bookmarks. All good but I could not get a local image to display.

I deleted my original install and pulled the v0.10.9 release down and built without issue a second time. Kept the defaults for everything but the settings file as shown below. I successfully used `background: https://images.unsplash.com/photo-1681802731183-c07ee779dabd` (green snake) from post https://github.com/gethomepage/homepage/discussions/4567#discussioncomment-11745780. I used `curl` to download the file and copied it to /opt/homepage/images/green-snake.jpg. Updated settings.yaml and nothing. No image is display. Hit the the refresh widget in the right bottom corner, reset the service, and rebooted the server. Still no image.

I am new to homepage so apprecaite guidance.

```
ls -al /opt/homepage/images/green-snake.jpg 
-rw-rw-r--    1 root     root       1301420 Feb 15 08:58 /opt/homepage/images/green-snake.jpg
```

/opt/homepage/config/settings.yaml in its entirety.
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background: /images/green-snake.jpg 
```

Using Firefox > More tools> Page Source it shows reference `url(&#x27;/images/green-snake.jpg&#x27;);` 

![homepage](https://github.com/user-attachments/assets/bcce8b4f-2a77-4899-b7f3-a8fbbf6cb5b2)

### homepage version

v0.10.9

### Installation method

Source

### Configuration

```yaml
homepage:/opt/homepage/config# cat settings.yaml 
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

#background: https://images.unsplash.com/photo-1681802731183-c07ee779dabd
background: /images/green-snake.jpg
```

```
homepage:/opt/homepage/config# cat services.yaml 
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
```

```
homepage:/opt/homepage/config# cat bookmarks.yaml 
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
```

```
homepage:/opt/homepage/config# cat widgets.yaml 
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

N/A?
