### DISCUSSION TITLE
Outdated Image Reference on Official Website -> Widget Problems (solved)

### DISCUSSION THREAD

**Discussion by ExecFail0** [gethomepage/homepage#4770] [Support]
### Description

I'm having trouble getting my widget to work despite spending the last hour troubleshooting my code. Here’s a quick summary of what I've tried so far:

Network connectivity: I can successfully ping the target IP from within the container.
Container update: I've updated the container to the latest version.
Configuration review: I've double-checked my YAML configuration based on various suggestions, including those from AI tools, but the widget still fails to load.
At this point, I'm at a loss and would really appreciate any insights or suggestions on what might be going wrong. Has anyone encountered a similar issue or could point me in the right direction?

Thanks in advance for your help!

![image](https://github.com/user-attachments/assets/05c1f203-ea04-490f-a793-33c308e3fcfd)

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
- Netzwerk:
    - FRITZ!Box:
        href: http://192.168.178.1
        icon: fritzbox.png
        description: 7590 Router
        widget:
            type: fritzbox
            url: http://192.168.178.1
            fields: ["maxDown", "maxUp", "connectionStatus", "externalIPAddress"]
```

### Troubleshooting

docker exec -it homepage ping -c 5 192.168.178.1
PING 192.168.178.1 (192.168.178.1): 56 data bytes
64 bytes from 192.168.178.1: seq=0 ttl=63 time=1.627 ms
64 bytes from 192.168.178.1: seq=1 ttl=63 time=1.851 ms
64 bytes from 192.168.178.1: seq=2 ttl=63 time=1.927 ms
64 bytes from 192.168.178.1: seq=3 ttl=63 time=1.694 ms
64 bytes from 192.168.178.1: seq=4 ttl=63 time=2.429 ms

--- 192.168.178.1 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 1.627/1.905/2.429 ms
