### DISCUSSION TITLE
Internal error on duplicate service name

### DISCUSSION THREAD

**Discussion by solumath** [gethomepage/homepage#4772] [Support]
### Description

When adding a service with a duplicate name the widget will output `API Error: Internal Error`. 

This doesn't provide any useful information and more likely makes the user more confused. There are no logs in the docker logs nor in the console only the HTTP request with error code 500. I would expect that it would write me the reason why it fails rather than `API Error: Internal Error`.

### homepage version

v.0.10.9

### Installation method

Docker

### Configuration

```yaml
- NPM:
    - Nginx:
        icon: nginx-proxy-manager.png
        href: <url1>
        description: Nginx proxy manager
        widget:
            type: npm
            url: <url1>
            username: dashboard@example.com
            password: <passwd>
    - Nginx:
        icon: nginx-proxy-manager.png
        href: <url2>
        description: Nginx proxy manager
        widget:
            type: npm
            url: <url2>
            username: dashboard@example.com
            password: <passwd>
```

### Container Logs

Empty

### Troubleshooting

No relevant logs.
