### DISCUSSION TITLE
Custom API Widget Not Displaying Data from SentinelOne API

### DISCUSSION THREAD

**Discussion by Da3dalusCode** [gethomepage/homepage#4774] [Support]
### Description

I'm trying to set up a SentinelOne widget in Homepage using the customapi widget. The API request works when tested externally, but in Homepage:

- The widget appears under Security, but only placeholder values (-) are shown.
- osStartTime is displaying "56 years ago" instead of a valid date.
- The API response contains valid data, but it's not being displayed.

I verified that the SentinelOne API is returning the expected JSON, and I can successfully retrieve the data outside of Homepage.

The widget should display actual SentinelOne endpoint data instead of placeholders.  osStartTime should properly format as a relative date.  Instead, placeholder values (-) appear instead of actual data.  osStartTime is not formatting correctly.

How should I properly structure the mappings when data is an array?  Is there something missing with the customapi widget that prevents the API response from displaying correctly?

Would really appreciate any guidance.
    

### homepage version

0.9.6

### Installation method

Docker

### Configuration

```yaml
Widget Configuration in services.yaml

- Security:
    - SentinelOne:
        icon: mdi:security
        href: "{{HOMEPAGE_VAR_S1_URL}}"
        description: Endpoint Security
        widget:
            type: customapi
            url: "{{HOMEPAGE_VAR_S1_URL}}/web/api/v2.1/agents"
            refreshInterval: 10000
            display: list
            headers:
                Authorization: "APIToken {{HOMEPAGE_VAR_S1_API_KEY}}"
                Accept: "application/json"
            mappings:
                - field: data
                  label: "Endpoints"
                  format: size
                - field:
                    path:
                      to: data
                      0: computerName
                  label: "Computer"
                - field:
                    path:
                      to: data
                      0: osName
                  label: "OS"
                - field:
                    path:
                      to: data
                      0: osStartTime
                  label: "Uptime"
                  format: relativeDate
                  style: short
                - field:
                    path:
                      to: data
                      0: activeThreats
                  label: "Threats"
                  format: number
                - field:
                    path:
                      to: data
                      0: infected
                  label: "Infected"
                  format: text
                  remap:
                    - value: true
                      to: "Yes"
                    - value: false
                      to: "No"
                - field:
                    path:
                      to: data
                      0: isUpToDate
                  label: "Up to Date"
                  format: text
                  remap:
                    - value: true
                      to: "Yes"
                    - value: false
                      to: "No"
                - field:
                    path:
                      to: data
                      0: networkStatus
                  label: "Network"
                - field:
                    path:
                      to: data
                      0: operationalState
                  label: "State"

This is a modified example of what the API returns (sanitized):

{
  "data": [
    {
      "computerName": "examplepcname",
      "osName": "Windows 11 Pro",
      "osStartTime": "2025-02-15T02:57:43Z",
      "activeThreats": 0,
      "infected": false,
      "isUpToDate": true,
      "networkStatus": "connected",
      "operationalState": "na"
    },
    {
      "computerName": "examplepcname2",
      "osName": "Windows 11 Pro",
      "osStartTime": "2025-02-13T01:07:18Z",
      "activeThreats": 0,
      "infected": false,
      "isUpToDate": true,
      "networkStatus": "connected",
      "operationalState": "na"
    }
  ]
}
```

### Container Logs

Listening on port 3000

### Troubleshooting

To make sure the issue isn’t on my end, I started by verifying that the SentinelOne API is working correctly. I tested the API using PowerShell, and the response returned valid JSON with the expected structure, including endpoint details like computerName, osName, and osStartTime. Since the API itself seemed fine, I moved on to checking my Homepage configuration.

I carefully reviewed my services.yaml file to confirm that the API key, URL, and data mappings were correctly set up. I also experimented with different display modes, including display: list, to see if the issue was related to how the widget renders the data, but that didn’t make a difference.

To rule out caching issues or old configurations, I performed a full container rebuild. I stopped the container, ran docker system prune -af to remove any cached images and orphaned data, and then restarted everything with docker compose up -d --build. Despite that, the widget still didn’t display the expected data.

I also checked inside the container to confirm that my changes were actually applied. I verified that the component.jsx file exists in /app/src/widgets/customapi/ and that it includes my debug statements. To ensure the service fully restarted with the updated files, I manually restarted Homepage inside the container using kill 1.

Lastly, I checked the logs using docker logs homepage --tail 100, but I didn’t see any errors related to the customapi widget or the SentinelOne API. At this point, I’ve gone through multiple layers of troubleshooting, but the widget is still displaying placeholders instead of actual data.
