### DISCUSSION TITLE
custom api return a 404 with collect data

### DISCUSSION THREAD

**Discussion by Devinaille** [gethomepage/homepage#4780] [Support] [answered]
### Description

I use custom api to show data from PeerBanHelper. My config looks like :
```yaml
- PeerBanHelper:
      href: http://192.168.100.101:9898
      icon: http://192.168.100.101:9898/favicon.ico
      widget:
        type: customapi
        url: "http://192.168.100.101:9898/api/statistic/counter"
        method: GET
        refreshInterval: 10000
        headers:
          Authorization: "Bearer abcd"
        mappings:
          - field:
              data: checkCounter
            label: 共检查
          - field:
              data: peerBanCounter
            label: 封禁Peer
          - field:
              data: peerBanCounter
            label: 正处于封禁的IP数量
```

but Homepage return a 404 with data 
```json
{
    "error": {
        "message": "HTTP Error",
        "url": "http://192.168.100.101:9898/api/statistic/counter",
        "resultData": "{\"success\":true,\"message\":null,\"data\":{\"peerUnbanCounter\":691,\"peerBanCounter\":193,\"bannedIpCounter\":331,\"checkCounter\":11222,\"banlistCounter\":331}}"
    }
}
```

And I try to curl in docker, it works well:
```bash
/app # curl http://192.168.100.101:9898/api/statistic/counter -H "Authorization: Bearer abcd"
{"success":true,"message":null,"data":{"peerUnbanCounter":691,"peerBanCounter":193,"bannedIpCounter":331,"checkCounter":11235,"banlistCounter":331}}/app # 
```

Could anyone help me ?

### homepage version

0.10.4

### Installation method

Docker

### Container Logs

[2025-02-17T04:53:55.636Z] debug: <genericProxyHandler> HTTP Error 404 calling http://192.168.100.101:9898/api/statistic/counter...

### Troubleshooting

1. curl in host -- ok
2. curl in homepage docker -- ok
3. homepage not work with 404
