### DISCUSSION TITLE
Homepage crashing consistently every couple of page reloads

### DISCUSSION THREAD

**Discussion by ThorpeJosh** [gethomepage/homepage#4790] [Support]
### Description

About 6 months homepage has been crashing regularly. I've searched issues but only one similar discussion was found #4415.

I have homepage running on multiple machines (identical config) but it only crashes on 1 of them that is a VPS in the cloud.

I understand the finger could easily be pointed at the VPS server or docker daemon. In its defense it has over 40 containers running in which homepage is the only one that has crashed in 6 months. In this time the linux kernel has been updated several times, the docker engine has been updated several times, and homepage has been updated several times.

But behavior is consistent, crashing consistently after a few page refreshes/loads.

Please let me know if I can provide any more useful information.

### homepage version

v0.10.9 (b5f4daa, Jan 7, 2025)

### Installation method

Docker

### Configuration

```yaml
homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9@sha256:b6d732817572f9af99ec168b10641b8f7820f30cfa5a5cc5c68f1e291804bec8
    environment:
      - LOG_LEVEL=debug
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homepage.rule=Host(`home.my.domain`)'
      - 'traefik.http.routers.homepage.entrypoints=https'
      - 'traefik.http.routers.homepage.tls=true'
      - 'traefik.http.routers.homepage.middlewares=authelia@docker'
    command: sh -c 'echo "10.0.1.10 custom.my.domain" >> /etc/hosts && node server.js'
    networks:
      - proxy
    expose:
      - 3000
    volumes:
      - ./homepage:/app/config
      - ./homepage/images:/app/public/images
    <<: *common
```

### Container Logs

```
Listening on port 3000
Container stopped
Container started
Listening on port 3000
[2025-02-18T18:31:48.929Z] debug: No containers were found with homepage labels.
[2025-02-18T18:31:50.962Z] debug: No containers were found with homepage labels.
[2025-02-18T18:31:55.379Z] debug: No containers were found with homepage labels.
[2025-02-18T18:32:13.677Z] debug: No containers were found with homepage labels.
Container stopped
Container started
Listening on port 3000
Container stopped
Container started
Listening on port 3000
#
# Fatal error in , line 0
# Check failed: CodeKindCanDeoptimize(compiled_code_.kind()).
#
#
#
#FailureMessage Object: 0x7ffffe9bcb30
Container stopped
Container started
Listening on port 3000
Container stopped
Container started
Listening on port 3000
```

### Troubleshooting

Debug logs have been enabled but I have never noticed any log messages upon a crash until today, so now I have something to share.

Before today it has been purely silent crashes.

VPS has sufficient memory and swap, and is running latest version of Almalinux9 with nightly kernel patching.
