### DISCUSSION TITLE
PiHole Widget stopped working after update of the PiHole Docker Container today

### DISCUSSION THREAD

**Discussion by sqrt-1764** [gethomepage/homepage#4793] [Support] [answered]
### Description

Widget stopped working (was working before the PiHole Update).

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- PiHole:
      icon: pi-hole.svg
      href: "http://{{HOMEPAGE_VAR_PIHOLE_IPV4}}:500/admin"
      siteMonitor: "http://{{HOMEPAGE_VAR_PIHOLE_IPV4}}:500"
      widget:
        type: pihole
        url: "http://{{HOMEPAGE_VAR_PIHOLE_IPV4}}:500"
        key: "{{HOMEPAGE_VAR_PIHOLE_APITOKEN}}"
```

PiHole reports: Docker Tag 2025.02.0
New GUI ... so the update has breaking changes.
```


### Container Logs

The Pihole-Container throws warnings as follows:
pihole  | 2025-02-18 22:09:49.037 CET [54/T1639] WARNING: API: Bad request (The API is hosted at pi.hole/api, not pi.hole/admin/api)


### Browser Logs

_No response_

### Troubleshooting

None applicable as I can not see any details of the api path in the widget configuration
