### DISCUSSION TITLE
Tailscale Widget gets "API Error: 404 page not found"

### DISCUSSION THREAD

**Discussion by bvzasfb** [gethomepage/homepage#4799] [Support] [answered]
### Description

Good morning, 

I tried configuring the tailscale widget but it fails with the error in the title.

The logs are not very helpful (see below)

The HTTP call works from the command line 
`curl https://api.tailscale.com/api/v2/device/############CNTRL -H "Authorization: Bearer tskey-api-############CNTRL-############################"`
and I get the correct JSON in response

The following issue resolution doesn't work for me:
[https://github.com/gethomepage/homepage/discussions/3853](https://github.com/gethomepage/homepage/discussions/3853)

Homepage is running in a LXC on proxmox installed through a community-script
[https://community-scripts.github.io/ProxmoxVE/scripts?id=homepage](https://community-scripts.github.io/ProxmoxVE/scripts?id=homepage)

### homepage version

0.9.6

### Installation method

Other (please describe above)

### Configuration

```yaml
- Tailscale:
      icon: tailscale.png
      href: https://login.tailscale.com/admin/machines
      widget:
        type: tailscale
        devideid: ############CNTRL
        key: tskey-api-############CNTRL-############################
```

### Container Logs

[2025-02-19T10:06:35.248Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://api.tailscale.com/api/v2/device/

### Troubleshooting

- Rebooted
- Renewed the api key
- changed to another device
- tested API call by curl from the same LXC homepage is running
- used the numerical deviceId
