### DISCUSSION TITLE
Homepage Error - Connecting to localhost:3000 ([::1]:3000) wget: can't connect to remote host: Connection refused

### DISCUSSION THREAD

**Discussion by SvartrShell** [gethomepage/homepage#4805] [Support] [answered]
### Description

I have been running homepage for over a year, and today after a server reboot am getting an error where homepage is not available -  docker logs homepage is empty - portainer shows the error Connecting to localhost:3000 ([::1]:3000) wget: can't connect to remote host: Connection refused 

I am running this via docker compose - i will put my config below. its worth noting, if i use docker run, with same ports, same config and same UID and GID, the container runs - it very much appears to be an issue with something inside the container attaching to port 3000 when ran via compose

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - '3300:3000'
    volumes:
      - '${BINDMOUNTDIR}/homepage:/app/config'
      - '${DOCKERSOCK}:${DOCKERSOCK}'
```

Docker run command (that works)
`docker run -p 3300:3000 -v /mnt/docker/bindmounts/homepage:/app/config -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/gethomepage/homepage:latest`
```


### Container Logs

Docker logs shows nothing - portainer has this error
```
Connecting to localhost:3000 ([::1]:3000) wget: can't connect to remote host: Connection refused 
```


### Browser Logs

_No response_

### Troubleshooting

Attempted to deploy fresh instance via compose with no config and no UID/GID specified - same issue
