### DISCUSSION TITLE
Manual build giving screen redness

### DISCUSSION THREAD

**Discussion by bubsy21-dev** [gethomepage/homepage#4819] [Support] [answered]
### Description

I am met with a reddish hue over text and background. I see in the images provided that the color palette tool is also only showing the red hue.  It seems to be a problem with the build process? Logs do not provide any output. I can provide more details if prompted - not sure what else I can include at the moment.

Happens when building either via tteck script, my ansible playbook that mimics the tteck script, or manually inputting the commands to setup nodejs repo + install nodejs + clone repo + pnpm install and build.

OS: Debian 12
Homepage: v0.10.9 (also tried v.010.8)
npm version: 10.9.2
pnpm version: 10.4.1

Default config
![image](https://github.com/user-attachments/assets/0499cbeb-12e4-43e4-8b28-ae39fc768dde)

With my config
![image](https://github.com/user-attachments/assets/12d9b187-c50d-4cde-b15d-ff72a2190ec0)

### homepage version

v0.10.9

### Installation method

Source

### Troubleshooting

tteck script
```
#!/usr/bin/env bash

# Copyright (c) 2021-2025 tteck
# Author: tteck (tteckster)
# License: MIT
# https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE

source /dev/stdin <<< "$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt-get install -y curl
$STD apt-get install -y sudo
$STD apt-get install -y mc
$STD apt-get install -y gpg
msg_ok "Installed Dependencies"

msg_info "Setting up Node.js Repository"
mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" >/etc/apt/sources.list.d/nodesource.list
msg_ok "Set up Node.js Repository"

msg_info "Installing Node.js"
$STD apt-get update
$STD apt-get install -y nodejs
$STD npm install -g pnpm
msg_ok "Installed Node.js"

RELEASE=$(curl -s https://api.github.com/repos/gethomepage/homepage/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')
msg_info "Installing Homepage v${RELEASE} (Patience)"
wget -q https://github.com/gethomepage/homepage/archive/refs/tags/v${RELEASE}.tar.gz
$STD tar -xzf v${RELEASE}.tar.gz
rm -rf v${RELEASE}.tar.gz
mkdir -p /opt/homepage/config
mv homepage-${RELEASE}/* /opt/homepage
rm -rf homepage-${RELEASE}
cd /opt/homepage
cp /opt/homepage/src/skeleton/* /opt/homepage/config
$STD pnpm install
export NEXT_PUBLIC_VERSION="v$RELEASE"
export NEXT_PUBLIC_REVISION="source"
$STD pnpm build
echo "${RELEASE}" >/opt/${APPLICATION}_version.txt
msg_ok "Installed Homepage v${RELEASE}"

msg_info "Creating Service"
cat <<EOF >/etc/systemd/system/homepage.service
[Unit]
Description=Homepage
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=root
WorkingDirectory=/opt/homepage/
ExecStart=pnpm start
[Install]
WantedBy=multi-user.target
EOF
systemctl enable -q --now homepage
msg_ok "Created Service"

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get -y autoremove
$STD apt-get -y autoclean
msg_ok "Cleaned"
```

my playbook
```
---
- name: Check if homepage is configured
  ansible.builtin.stat:
    path: /etc/systemd/system/homepage.service
  register: homepage
  failed_when: false


- name: Install prerequisites
  ansible.builtin.apt:
    pkg: "{{ item }}"
  loop: "{{ homepage_pkgs }}"
  when: homepage.stat.exists == false


- name: Curl GPG key
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  when: homepage.stat.exists == false


- name: Setup Node.js repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/nodesource.list
    content: deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main
  when: homepage.stat.exists == false


- name: Install Node.js
  ansible.builtin.apt:
    pkg: nodejs
    state: present
    update_cache: true
  when: homepage.stat.exists == false


- name: Install Node.js - p2
  ansible.builtin.command: |
    npm install -g pnpm
  when: homepage.stat.exists == false


- name: Get latest homepage release version
  ansible.builtin.shell:
    curl -s https://api.github.com/repos/gethomepage/homepage/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }'
  register: homepage_version
  when: homepage.stat.exists == false


- name: Git clone homepage
  ansible.builtin.git:
    repo: 'https://github.com/gethomepage/homepage.git'
    dest: /opt/homepage/
    version: "v{{ homepage_version.stdout }}"
  when: homepage.stat.exists == false


- name: Copy config (overwrite with -e overwrite_config=true)
  ansible.builtin.copy:
    src: ../files/
    dest: /opt/homepage/config/
  when: (homepage.stat.exists == false) or ((overwrite_config is defined) and (overwrite_config == "true"))


- name: Generate config (overwrite with -e overwrite_config=true)
  template:
    src: ../templates/{{ item.key }}
    dest: /opt/homepage/config/{{ item.value}}
  loop: "{{ homepage_templates | dict2items }}"
  when: (homepage.stat.exists == false) or ((overwrite_config is defined) and (overwrite_config == "true"))


- name: Install dependencies
  ansible.builtin.shell: pnpm install
  args:
    chdir: /opt/homepage
  when: homepage.stat.exists == false


- name: Build homepage
  shell: pnpm build
  args:
    chdir: /opt/homepage
  environment:
    NEXT_PUBLIC_VERSION: "v{{ homepage_version.stdout }}"
    NEXT_PUBLIC_REVISION: "source"
  when: homepage.stat.exists == false


- name: Move systemd file
  ansible.builtin.command:
    cmd: mv /opt/homepage/config/homepage.service /etc/systemd/system/homepage.service
  when: homepage.stat.exists == false


- name: Enable systemd service for homepage
  ansible.builtin.service:
    name: homepage
    enabled: true
    state: started
  when: homepage.stat.exists == false
```
npm_install.log
```
up to date, audited 645 packages in 943ms

197 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

npm_build.log
```
> homepage@0.10.9 build
> next build

   ▲ Next.js 15.1.7

   Linting and checking validity of types ...
   Creating an optimized production build ...
   Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
   Using external babel configuration from /opt/homepage/.babelrc
   Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
   Using external babel configuration from /opt/homepage/.babelrc
   Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
   Using external babel configuration from /opt/homepage/.babelrc
 ✓ Compiled successfully
   Collecting page data ...
   Generating static pages (0/5) ...
   Generating static pages (1/5) 
   Generating static pages (2/5) 
   Generating static pages (3/5) 
 ✓ Generating static pages (5/5)
   Finalizing page optimization ...
   Collecting build traces ...

Route (pages)                              Size     First Load JS
┌ ● /                                      68.9 kB         187 kB
├   /_app                                  0 B             118 kB
├ ○ /404                                   1.47 kB         119 kB
├ ƒ /api/bookmarks                         0 B             118 kB
├ ƒ /api/config/[path]                     0 B             118 kB
├ ƒ /api/docker/stats/[...service]         0 B             118 kB
├ ƒ /api/docker/status/[...service]        0 B             118 kB
├ ƒ /api/hash                              0 B             118 kB
├ ƒ /api/healthcheck                       0 B             118 kB
├ ƒ /api/kubernetes/stats/[...service]     0 B             118 kB
├ ƒ /api/kubernetes/status/[...service]    0 B             118 kB
├ ƒ /api/ping                              0 B             118 kB
├ ƒ /api/releases                          0 B             118 kB
├ ƒ /api/revalidate                        0 B             118 kB
├ ƒ /api/search/searchSuggestion           0 B             118 kB
├ ƒ /api/services                          0 B             118 kB
├ ƒ /api/services/proxy                    0 B             118 kB
├ ƒ /api/siteMonitor                       0 B             118 kB
├ ƒ /api/theme                             0 B             118 kB
├ ƒ /api/validate                          0 B             118 kB
├ ƒ /api/widgets                           0 B             118 kB
├ ƒ /api/widgets/glances                   0 B             118 kB
├ ƒ /api/widgets/kubernetes                0 B             118 kB
├ ƒ /api/widgets/longhorn                  0 B             118 kB
├ ƒ /api/widgets/openmeteo                 0 B             118 kB
├ ƒ /api/widgets/openweathermap            0 B             118 kB
├ ƒ /api/widgets/resources                 0 B             118 kB
├ ƒ /api/widgets/stocks                    0 B             118 kB
├ ƒ /api/widgets/weather                   0 B             118 kB
├ ƒ /browserconfig.xml                     260 B           118 kB
└ ƒ /site.webmanifest                      261 B           118 kB
+ First Load JS shared by all              131 kB
  ├ chunks/framework-19baaf6675f9027b.js   44.8 kB
  ├ chunks/main-b95f5a6e8f68de23.js        41.4 kB
  ├ chunks/pages/_app-3c1d959182a55a0e.js  27.5 kB
  ├ css/69efc90ef6a64298.css               13.6 kB
  └ other shared chunks (total)            4.24 kB

ƒ Middleware                               32.8 kB

○  (Static)   prerendered as static content
●  (SSG)      prerendered as static HTML (uses getStaticProps)
ƒ  (Dynamic)  server-rendered on demand
```
