### DISCUSSION TITLE
Pi-Hole v6 doesn't work

### DISCUSSION THREAD

**Discussion by edwardtich1** [gethomepage/homepage#4825] [Support] [answered]
### Description

Pi-Hole v6 doesn't work

```
{
	"error":	{
		"key":	"bad_request",
		"message":	"Bad request",
		"hint":	"The API is hosted at pi.hole/api, not pi.hole/admin/api"
	},
	"took":	2.47955322265625e-05
}
```

### homepage version

v0.10.9

### Installation method

Docker

### Troubleshooting

Pi-Hole v6 doesn't work

```
{
	"error":	{
		"key":	"bad_request",
		"message":	"Bad request",
		"hint":	"The API is hosted at pi.hole/api, not pi.hole/admin/api"
	},
	"took":	2.47955322265625e-05
}
```

**Comment by thierolm** [comment]
Pls share your yaml widget configuration and homepage.log. 
You can find my findings in #4814. The current master version is working with pihole v6. We need a new release with alle the updates since jan 2025 ...

**Comment by shamoon** [comment, marked as answer]
Please search and read the documentation

**Reply by thierolm** [reply]
Hi @shamoon , this is what I did.
I'm running the last docker release
![image](https://github.com/user-attachments/assets/9bd66c82-24e4-4a35-bf97-41130d8e1ce6)
with the following pihole v6 widget config and getting an error:
```yaml
        - Pi-hole:
            href: http://192.168.1XX.XX:8080/admin
            description: Pi-hole
            icon: si-pihole-#96060C
            widget:
                type: pihole
                url: http://192.168.1XX.XX:8080/
                version: 6
                key: xyz
 ```
I cloned the current homepage git head branch and used the same config in a vs-code test environment and it's working.
What am I missing in the documentation?
