### DISCUSSION TITLE
Feature Request] Support for Multiple Portainer Environments in Homepage Widget

### DISCUSSION THREAD

**Discussion by eBarazi** [gethomepage/homepage#4827] [Feature Requests]
### Description

Hi Homepage Team,

I’d like to suggest an enhancement to the Portainer widget that would allow displaying multiple environments within a single widget. This would be particularly useful for setups where Portainer is running on a server as an agent and paired with a main Portainer instance on another server.

Currently, the widget configuration only allows specifying a single environment ID:

```
widget:
  type: portainer
  url: https://portainer.host.or.ip:9443
  env: 1
  key: ptr_accesskeyaccesskeyaccesskeyaccesskey
```

An ideal solution could involve supporting an array of environment IDs or an option to display all available environments under a specified Portainer instance. This feature would provide better visibility and management for multi-node or multi-environment Docker setups.

Thank you for creating homepage and I would really appreciate considering this suggestion! Please let me know if you need any additional details about this use case.

Best regards,
ebarazi

**Comment by SamNabz** [comment]
Any chance this is going to be implemented? Currently, you can only see stats for a **single** environment, which isn't ideal...

**Comment by buffaloexpatbill** [comment]
Any widget can be included in your homepage config more than once if you give the different instances different names. 
<img width="1744" height="170" alt="image" src="https://github.com/user-attachments/assets/bd7147e8-04d7-4f67-9b70-ad8950a3bb36" />
There may still be something to accomplish within a single widget (aggregating numbers across all portainer instances maybe?), but for now, it is possible to see stats across multiple portainer instances.

**Reply by SamNabz** [reply]
@buffaloexpatbill, I've _already_ been doing this. But seeing as how Portainer can show multiple instances via agents, it would be good to also show the stats for any/all connected instances.

**Reply by mikesalz** [reply]
I am new to Homepage.  I have a Portainer setup with one main instance and then agents running on two other servers.  Are we saying there is currently no way to display stats from the agents?  Ick.

**Reply by buffaloexpatbill** [reply]
> I am new to Homepage.  I have a Portainer setup with one main instance and then agents running on two other servers.  Are we saying there is currently no way to display stats from the agents?  Ick.

This makes it sound like there is "no way to display stats from the agents". Their stats can be displayed through separate entries/widgets. So it is not that there is no way. Just not the requested way. 
There may also be an API in portainer that can be used with the customapi option.

**Reply by mikesalz** [reply]
Thank you for the clarification, @buffaloexpatbill!  Would you mind explaining how I would do that?

This works for me, and shows my primary Portainer instance.  
```
    - Portainer:
        icon: portainer
        href: http://192.168.1.200:9000
        description: Portainer
        widget:
            type: portainer
            url: http://192.168.1.200:9000
            env: 3
            key: xxxxxxxxxxxxxx
```

I'm just not sure how to pull the other 2 agent instances in.  As far as I know, I only have one key because the other instances are only agents, correct?  

I tried the below (same key, different env), but it just shows the same instance twice.  I also tried different variations of the IP address for the agents.

```
    - Portainer:
        icon: portainer
        href: http://192.168.1.200:9000
        description: Portainer
        widget:
            type: portainer
            url: http://192.168.1.200:9000
            env: 3
            key: xxxxxxxxxxxxxx

    - Portainer:
        icon: portainer
        href: http://192.168.1.200:9000
        description: Portainer
        widget:
            type: portainer
            url: http://192.168.1.200:9000
            env: 4
            key: xxxxxxxxxxxxxx
```

**Reply by buffaloexpatbill** [reply]
Each service element needs to have a unique key.  You could use something like "Portainer 1". "Portainer 2", etc or anything else that makes the name unique.  Something that tells you which instance it is could at the same time be helpful to you to know what you're looking at.

I've changed the domain to domain.com because it is beside the point (I have internal DNS that routes these all to an apache server that is handling reverse proxying), but my services config for the Portainer portion looks like:
```
- Docker Management:
    - Portainer (pi4-1):
        href: https://portainer1.domain.com
        description: Docker management on pi4-1 (swarm host)
        icon: portainer.svg
        widget:
          type: portainer
          url: https://portainer1.domain.com/
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER1_API_KEY}}"

    - Portainer (pi4-2):
        href: https://portainer2.domain.com
        description: Docker management on pi4-2
        icon: portainer.svg
        widget:
          type: portainer
          url: https://portainer2.domain.com/
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER2_API_KEY}}"

    - Portainer (pi4-3):
        href: https://portainer3.domain.com
        description: Docker management on pi4-3
        icon: portainer.svg
        widget:
          type: portainer
          url: https://portainer3.domain.com/
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER3_API_KEY}}"

    - Portainer (pi5-1):
        href: https://portainer4.domain.com
        description: Docker management on pi5-1
        icon: portainer.svg
        widget:
          type: portainer
          url: https://portainer4.domain.com/
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER4_API_KEY}}"

    - Portainer (billserver-01):
        href: https://portainer5.domain.com
        description: Docker management on billserver-01
        icon: portainer.svg
        widget:
          type: portainer
          url: https://portainer5.domain.com/
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER5_API_KEY}}"
```
