### DISCUSSION TITLE
Cannot authenticate with PiHole V6

### DISCUSSION THREAD

**Discussion by thierolm** [gethomepage/homepage#4829] [Support] [answered]
### Description

Cannot connect to a pihole v6 instance with current docker head version v0.10.9:
![image](https://github.com/user-attachments/assets/f75fa6fd-81b5-4509-919e-66249ea9b1b0)

I cloned the current homepage git head branch and used the same config in a vs-code test environment and it's working. 

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- Pi-hole:
            href: http://192.168.1XX.XX:8080/admin
            description: Pi-hole
            icon: si-pihole-#96060C
            widget:
                type: pihole
                url: http://192.168.1XX.XX:8080/
                version: 6
                key: 4HSXXX/Xkk=
```

### Container Logs

Debug log level is active but not providing more details
`[2025-02-23T16:58:06.238Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 404`

### Browser Logs

None

### Troubleshooting

Curl connection test in docker container:
```sh
/app/config # ping 192.168.1XX.XX
PING 192.168.188.10 (192.168.1XX.XX): 56 data bytes
64 bytes from 192.168.1XX.XX: seq=0 ttl=61 time=42.240 ms
64 bytes from 192.168.1XX.XX: seq=1 ttl=61 time=40.015 ms
^C
--- 192.168.188.10 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 40.015/41.127/42.240 ms
/app/config # cat ./piholev6-test.sh 
curl -k -X POST "http://192.168.1XX.XX:8080/api/auth" --data '{"password":"4HSXXX/Xkk="}' 
/app/config # ./piholev6-test.sh 
{"session":{"valid":true,"totp":false,"sid":"D0egeCV9p4jbp02zKfauRA=","csrf":"VsQ8uhyPhUy2C55EsIwn5g=","validity":1800,"message":"password correct"},"took":0.708918809890747}/app/config # ```
