### DISCUSSION TITLE
Can't get correct JSON value

### DISCUSSION THREAD

**Discussion by My-Random-Thoughts** [gethomepage/homepage#4833] [Support] [answered]
### Description

I am using a UPS Web GUI tool (https://github.com/SuperioOne/nut_webgui) that returns the following partial JSON data when its API is called:

    {
        "name":"ups",
        "vars":{
            "battery.charge":100.0,
            "battery.charge.low":10.0,
            "battery.charge.warning":"50",
            "battery.runtime":2640.0,
            "battery.runtime.low":"120",
            "...":"..."
        }
    }

I am trying to get the data into a CustomAPI Widget but the mappings are not working.
I have tried lots of different options, but I would have thought `vars["battery.charge"]` would have worked.

It's seeing the tool OK:
![image](https://github.com/user-attachments/assets/655e4af9-515c-4df8-b280-2c41347522ba)

Does anyone have any ideas?

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- UPS Status:
      href: http://home.lan:81
      description: Network UPS Tools
      icon: /icons/nutweb.png
      ping: http://home.lan:81
      widget:
        type: customapi
        url: http://home.lan:81/api/ups/ups
        mappings:
          - field: vars["battery.charge"]
            label: Charge
            format: number
          - field: vars["battery.runtime"]
            label: Runtime
            format: number
          - field: vars["ups.status"]
            label: Status
            format: text
```

### Container Logs

None relevant for this

### Browser Logs

None

### Troubleshooting

See above

**Comment by joepool** [comment, marked as answer]
Try this...

```
        mappings:
          - field:
              vars: battery.charge
            label: Battery Charge
            format: percent
          - field:
              vars: battery.runtime
            label: Runtime
            suffix: "Hours"
         
```
![Screenshot 2025-02-25 at 22 23 11](https://github.com/user-attachments/assets/68491846-149b-4d92-bda4-36f444ccf764)
