### DISCUSSION TITLE
SABnzbd Widget not working in 0.10.9

### DISCUSSION THREAD

**Discussion by durmonator** [gethomepage/homepage#4834] [Support] [answered]
### Description

I believe this error was happening with NZBget, looking at Issues here, basically I am getting the error `API Error: Unexpected token 'I', "Internal S"... is not valid JSON` when I try and connect to the SABnzbd widget

![Screenshot 2025-02-26 at 09 25 36](https://github.com/user-attachments/assets/c16a67c0-114c-470c-a1aa-9f1ae7ea44e7)

### homepage version

0.10.9

### Installation method

Docker

### Configuration

```yaml
- SABnzbd:
        icon: sabnzbd.png
        href: [redacted]
        widget:
            type: sabnzbd
            href: [redacted]
            key: [redacted]
```

### Troubleshooting

Docker's ping is telling me it cannot reach my URLs, but I tried with the sonarr url and the key etc is working for sonarr, so I am not sure it will be that

`ping: bad address '[redacted]'`

This happens for sonarr as well, but homepage can see my sonarr instance and API when I go into my homepage url, so, either my docker is beyond borked, or something funky with my setup is happening
