### DISCUSSION TITLE
Same ip address for all Tailscale devices

### DISCUSSION THREAD

**Discussion by natanaelfornel** [gethomepage/homepage#4851] [Support] [answered]
### Description

Hi everyone,  (_sorry for any mistake, english insn't my official language_)

I'm configuring a gethomepage and everything is going smoothly until now.
For some reason the Tailscale Widget is not collecting the correct ipv4 address from tailscale (via api).

![image](https://github.com/user-attachments/assets/724c537f-fbf0-4c1e-89ef-10196454cd27)

I already try to create one auth key for each device but for some reason they still showing the same ipv4 address for all.

OS: Ubuntu Server 22.04LTS 

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
services.yaml

- MACHINES:
    
    - TAILSCALE:
        description: GL-MT3000
        icon: tailscale.svg
        siteMonitor: https://login.tailscale.com/admin/machines
        widget:
            type: tailscale
            fields: ["address", "last_seen"]
            deviceid: xxxxxxxxxxxxxxxxxCNTRL
            key: "{{HOMEPAGE_VAR_TAIL_TOKEN}}"
    
    - TAILSCALE:
        description: Storage
        icon: tailscale.svg
        siteMonitor: https://login.tailscale.com/admin/machines
        widget:
            type: tailscale
            fields: ["address", "last_seen"]
            deviceid: xxxxxxxxxxxxxxxxxCNTRL
            key: "{{HOMEPAGE_VAR_TAIL2_TOKEN}}"
    
    - TAILSCALE:
        description: Windows Server 2022
        icon: tailscale.svg
        siteMonitor: https://login.tailscale.com/admin/machines
        widget:
            type: tailscale
            fields: ["address", "last_seen"]
            deviceid: xxxxxxxxxxxxxxxxxCNTRL
            key: "{{HOMEPAGE_VAR_TAIL_TOKEN}}"
    
    - TAILSCALE:
        description: Windows Server 2022 MNGT
        icon: tailscale.svg
        siteMonitor: https://login.tailscale.com/admin/machines
        widget:
            type: tailscale
            fields: ["address", "last_seen"]
            deviceid: xxxxxxxxxxxxxxxxxCNTRL
            key: "{{HOMEPAGE_VAR_TAIL_TOKEN}}"

########################################################################

docker-compose.yaml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped 
    networks:
        dhcp_hostlab:
          ipv4_address: 192.168.2.40
    container_name: homepage
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./config:/app/config
      - ./config:/app/public/images
      - ./config:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    environment:

      - HOMEPAGE_VAR_ADGUARD_USERNAME=$HOMEPAGE_VAR_ADGUARD_USERNAME
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=$HOMEPAGE_VAR_ADGUARD_PASSWORD
      - HOMEPAGE_VAR_RTBOX_USERNAME=$HOMEPAGE_VAR_RTBOX_USERNAME
      - HOMEPAGE_VAR_RTBOX_PASSWORD=$HOMEPAGE_VAR_RTBOX_PASSWORD
      - HOMEPAGE_VAR_NPM_USERNAME=$HOMEPAGE_VAR_NPM_USERNAME
      - HOMEPAGE_VAR_NPM_PASSWORD=$HOMEPAGE_VAR_NPM_PASSWORD
      - HOMEPAGE_VAR_SYN_USERNAME=$HOMEPAGE_VAR_SYN_USERNAME
      - HOMEPAGE_VAR_SYN_PASSWORD=$HOMEPAGE_VAR_SYN_PASSWORD
      - HOMEPAGE_VAR_PVE_API=$HOMEPAGE_VAR_PVE_API
      - HOMEPAGE_VAR_PVE_TOKEN=$HOMEPAGE_VAR_PVE_TOKEN
      - HOMEPAGE_VAR_TAIL_TOKEN=$HOMEPAGE_VAR_TAIL_TOKEN
      - HOMEPAGE_VAR_TAIL2_TOKEN=$HOMEPAGE_VAR_TAIL2_TOKEN

networks:
  dhcp_hostlab:
    name: dhcp_hostlab
    driver: macvlan
    driver_opts:
        parent: ens34
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
          ip_range: 192.168.2.0/24
```

### Troubleshooting

1.-  `docker exec -it homepage curl --request GET --url https://api.tailscale.com/api/v2/device/xxxxxxxxxxxxxxxCNTRL -H "Authorization: Bearer tskey-api-xxxxxxxxxxxxxCNTRL-5Zz1tFDU9k2kKgvjArP9k2Xtzt4eumbH"`

Return with all information about the device.

2.- I already try what was explained here: https://github.com/gethomepage/homepage/discussions/4356

3.- `docker exec homepage ping api.tailscale.com` with response (Code 200)
