### DISCUSSION TITLE
Tautulli showing on homepage despite no mention in any config

### DISCUSSION THREAD

**Discussion by chronomac** [gethomepage/homepage#4852] [Support] [answered]
### Description

When I was first setting up homepage I included tautulli in my services.yaml file but then decided to remove it later. Right now it's not included in any .yaml file whatsoever. I grep'ed to ensure it. It gets mentioned in the log file from 2 days ago but that's it. Despite all that, here it is:

![image](https://github.com/user-attachments/assets/48e5d0ce-a105-4ce7-88a6-9a5c711c0e0b)

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

headerStyle: boxed

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
```

### Troubleshooting

I've tried to recreate the settings and services files to no avail.
