### DISCUSSION TITLE
How to show more than one volume in the DSM widget?

### DISCUSSION THREAD

**Discussion by crispybegs** [gethomepage/homepage#4864] [Support]
### Description

I can see 'volume 1' in my widget, but I also have 'volume 2' on my synology.
is there a way of showing both in the widget?

<img width="673" alt="Screenshot 2025-03-02 at 19 12 36" src="https://github.com/user-attachments/assets/ed1d406a-29c0-4fa3-8dee-4b727a341ce4" />

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Troubleshooting

tried:

```
        widget:
          type: diskstation
          url: https://192-168-1-58.xxxxx.direct.quickconnect.to:5002/
          username: homepage
          password: xxxxxx
          volume: volume_1 
          volume: volume_2
```

and

```
        widget:
          type: diskstation
          url: https://192-168-1-58.xxxxx.direct.quickconnect.to:5002/
          username: homepage
          password: xxxxxx
          volume: volume_1,volume_2 
```
          
without success
