### DISCUSSION TITLE
Am I missing something about nested groups?

### DISCUSSION THREAD

**Discussion by kylepyke** [gethomepage/homepage#4866] [General]
I'm not sure I understand the point of nested groups. It seems like the following bits of code produce the exact same visual result with the exception being the ability to collapse everything under the parent group in the first example– is that the sole purpose of groups?

**Ex. 1**
`services.yaml`:
```
- Proxmox:
    - Proxmox:
        icon: proxmox.svg
        href: "#########"
    - Docker:
        - Portainer:
            icon: portainer.svg
            href: "#########"

        - Immich:
            icon: immich.svg
            href: "########"
```
`settings.yaml`:
```
layout:
  Proxmox:
    style: row
    columns: 1
    Docker:
      style: row
      columns: 1
```
<img width="1064" alt="Ex 1" src="https://github.com/user-attachments/assets/6d1b026b-aab2-4b06-9f73-b6c58608dc5d" />

**Ex. 2**
`services.yaml`:
```
- Proxmox:
    - Proxmox:
        icon: proxmox.svg
        href: "#########"
- Docker:
    - Portainer:
        icon: portainer.svg
        href: "#########"

    - Immich:
        icon: immich.svg
        href: "########"
```
`settings.yaml`:
```
layout:
  Proxmox:
    style: row
    columns: 1
  Docker:
    style: row
    columns: 1
```
<img width="1043" alt="Ex 2" src="https://github.com/user-attachments/assets/675dabe2-7b2f-4ebd-9da6-91c7c0e10549" />
