### DISCUSSION TITLE
Help with my layout please

### DISCUSSION THREAD

**Discussion by janreinhardt** [gethomepage/homepage#4867] [Support] [answered]
### Description

Please, I am having a problem with my layout. I want the section „Monitoring / Docker / Misc“ to be three columns. And *not* use a responsive fourth column like in the screenshot from my iPad.
The link sections „Repos + Linux“ should be separate and two columns only. How do I achieve that? Would nested groups be the answer? „I have tried everything, but I cant get it to work.“
Below is also my settings.yaml.

Thanks!

![IMG_0016](https://github.com/user-attachments/assets/d593d3ef-2aa0-4a7b-be32-264e8b34c6ba)

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
layout:
  My First Group:
    header: false
    style: row
    columns: 2 
  Monitoring:
  Docker:
  Misc:
  Repos:
  Linux:
  Router:
    header: false
    style: row
    columns: 1
```

### Troubleshooting

(not relevant)

**Comment by owennewo-dev** [comment]
Yes nest `Monitoring ` `Docker` and `Misc` in another group. And make another group with `Repos` and `Linux` nested in it. So your `settings.yaml` would look like this...

```yaml
layout:
  My First Group:
    header: false
    style: row
    columns: 2 
  Nested1:
    style: column
    columns: 3
    header: false
    Monitoring:
      style: column
      header: false
    Docker:
      style: column
      header: false
    Misc:
      style: column
      header: false
  Nested2:
    style: column
    columns: 2
    header: false
    Repos:
      style: column
      header: false
    Linux:
      style: column
      header: false
  Router:
    header: false
    style: row
    columns: 1
```

**Reply by janreinhardt** [reply]
Thanks for answering! 
This does solve half the problem, but there are still funny things going on. I have changed my `settings.yaml` to this:
```
layout:
  My First Group:
    header: false
    style: row
    columns: 2
  Nested1:
    style: column
    columns: 3
    Monitoring:
      style: column
    Docker:
      style: column
    Misc:
      style: column
  Nested2:
    style: column
    columns: 2
    Repos:
      style: column
    Linux:
      style: column
  Router:
    header: false
    style: row
    columns: 1
```
Which gives me this layout:

![IMG_0017](https://github.com/user-attachments/assets/8d440e51-2c18-4a8f-b76c-5fd0a1050967)


Why is the 'Router' section in the middle of the homepage, it should be the last section at the bottom?
And why are 'Docker' and 'Misc' in the wrong order??

@owennewo-dev Thanks for your help!

**Reply by owennewo-dev** [reply]
@janreinhardt the wrong order might be because of how you have things ordered in `services.yaml`

**Reply by janreinhardt** [reply]
I have only got **one** thing in `services.yaml`:
```
- Router:
    - FRITZ!Box 5590 Fiber:
        href: https://XXXXXX.myfritz.net:40193
        icon: fritzbox-light
        weight: 9
        widget:
          type: fritzbox
          url: http://192.168.178.1
          fields: ["uptime", "received", "sent"]
```

@owennewo-dev Do I need to add anything here?
All the other services are auto-added via Docker labels.

**Reply by owennewo-dev** [reply]
@janreinhardt I haven't ever used service widgets added via docker labels, sorry.

**Comment by janreinhardt** [comment]
This is all so bogus: maybe its not me and my settings, but a homepage bug instead??

**Comment by janreinhardt** [comment]
@shamoon Could you please have a quick look at this: is this a bug or is it my `settings.yaml `and `services.yaml` mistake?
I have got **one** service configured in the `services.yaml`
All my other services are auto-detected from their Docker labels.
My homepage layout is defined in the `settings.yaml `and working fine except for one little detail (I'd like a fixed 3 column layout for three groups instead of a 4th column). But as soon as I start nesting groups, weird stuff is happening and all groups become **disordered** instead of ordered.
Do I have to keep on trying or is this a homepage error?

**Reply by shamoon** [reply]
Can you try the dev image and tell me if it makes a difference?

**Reply by shamoon** [reply]
And if not please post the labels for a couple of the relevant services

**Reply by janreinhardt** [reply]
@shamoon I am trying the :dev image and its the same thing.
Putting 'Monitoring' and 'Docker' and 'Misc' in a nested group puts this nested group at the very bottom of the homepage and also displays the three groups in a different order.
This is the `settings.yaml`
```
layout:
  My First Group:
    header: false
    style: row
    columns: 2 
  Nested1:
    style: column
    columns: 3
    Monitoring:
      style: column
      columns: 3
    Docker:
      style: column
      columns: 3
    Misc:
      style: column
      columns: 3
  Repos:
    style: column
    columns: 1
  Linux:
    style: column
    columns: 1
  Router:
    header: false
    style: row
```

and this is the labels on one of the containers:
```
-l homepage.group="Misc" \
-l homepage.name="Baïkal" \
-l homepage.icon="baikal" \
-l homepage.href="https://raspi5:7443/" \
-l homepage.description="CalDAV+CardDAV server" \
-l homepage.weight="2" \
```

![IMG_0018](https://github.com/user-attachments/assets/5feeffd1-fea6-4d0a-9fc3-d47973f573dc)
