### DISCUSSION TITLE
[Feature Request] Presearch widget

### DISCUSSION THREAD

**Discussion by mebitek** [gethomepage/homepage#4869] [Feature Requests]
### Description

Hello,
should be nice to have a presearch widget to check the incoming request of your selfhosted node.

Presearch is federated search engine, here the documentation: https://docs.presearch.io/

**Comment by mebitek** [comment]
just to let you know I was able to use the customapi widget to make it working:

```
        widget:
          refreshInterval: 900000
          type: customapi
          url: https://nodes.presearch.com/api/nodes/status/${TOKEN_API}?stats=true
          mappings:
            - field: nodes_returned 
              label: Nodes
            - field:
                nodes:
                  "${PUBLIC_KEY}":
                    status:
                      connected

              label: Status
```
