### DISCUSSION TITLE
Widget EVCC didnt show Loadpoint/Car Loading

### DISCUSSION THREAD

**Discussion by horst789github** [gethomepage/homepage#4877] [Support] [answered]
### Description

in evcc widget i always have loadpoint on zero

homepage evcc widget:
![grafik](https://github.com/user-attachments/assets/d889210b-abfa-4a07-943e-d8045246eaae)

evcc:
![grafik](https://github.com/user-attachments/assets/df13352b-859e-4432-b529-663e9b873ee5)

how i can change this?

### homepage version

v0.10.9 (b5f4daa)

### Installation method

Docker

### Configuration

```yaml
services.yaml

- Wichtige Tools/Programme:
    - EVCC:
        icon: evcc.png
        href: http://192.168.0.2:7070/#/
        description: E-Auto Ladesteuerung
        server: my-docker
        container: evcc
        widget:
            type: evcc
            url: http://192.168.0.2:7070
```

### Troubleshooting

not relevant
