### DISCUSSION TITLE
Connection to GlueTUN - cross device

### DISCUSSION THREAD

**Discussion by jimmisavage** [gethomepage/homepage#4878] [Support]
### Description

I have GlueTUN installed in docker in a stack (portainer)
I have Homepage installed on a Proxmox LXC

I can ping GlueTUN from Homepage lxc but i cannot get the widget to work/connect - API Error information

Any idea where I'm going wrong here?

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
GlueTUN:
`services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
     #- 8888:8888/tcp # HTTP proxy
      - 9075:9075/tcp # HTTP Control Server
      - 9091:9091/tcp # transmission  
      - 65225:65225/tcp # transmission peer
      - 65225:65225/udp # transmission peer
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPNSP=private internet access
      - OPENVPN_USER=secret
      - OPENVPN_PASSWORD=secret
      - SERVER_REGIONS=UK Streaming Optimized
      - TZ=Europe/London
      - FIREWALL_OUTBOUND_SUBNETS=192.168.86.0/24
      - HTTP_CONTROL_SERVER_ADDRESS=9075
      - HTTP_CONTROL_SERVER_LOG=ON
      - HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH=/gluetun/config.toml
    restart: always`
    
    GlueTUN up and running on IPAddress:"192.168.96.2"
    
    Services.yaml
    `- Group D:
    - GlueTUN:
        icon: gluetun.png
        ping: http://192.168.96.2:9075
        statusStyle: "dot"
        description: VPN Connection
        widget:
          type: gluetun
          fields: ["public_ip", "region", "country"]
          url: http://192.168.96.2:9075`
          
 config.toml
 `[[roles]]
name = "homepage"
routes = ["GET /v1/publicip/ip"]
auth = "none"`

Homepage log error:
`[2025-03-05T13:59:18.340Z] error: <httpProxy> Error calling http://192.168.96.2:9075/v1/publicip/ip...
[2025-03-05T13:59:18.344Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.96.2:9075
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.96.2',
    port: 9075
  }
]
[2025-03-05T13:59:18.344Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.96.2:9075/v1/publicip/ip`
```

### Troubleshooting

I've tried various config variations
