### DISCUSSION TITLE
Synology Disk Station Widget Showing Incorrect Resource Usage

### DISCUSSION THREAD

**Discussion by HossLab** [gethomepage/homepage#4879] [Support] [answered]
### Description

I am interested if anyone else is seeing odd resource usage being reported on the Synology Disk Station widget recently. It worked completely fine until about a month ago and I am now getting to the point after troubleshooting that I thought I would ask here.

So far this is what I am seeing on the widget vs what my Synology reports:
![image (1)](https://github.com/user-attachments/assets/3fb073f8-2a93-4ce6-ae85-2d4dc59c6daf)
![image](https://github.com/user-attachments/assets/6b79416f-0059-4bf5-8d36-d720de0cc3f8)

Rebooting the NAS seems to bring the resource usage CLOSE to what is it, but then over time the Memory on the widget will start climbing and showing double to triple what is actually being used...

I know this is kind of a shot in the dark since I do not have much for logs. If someone could help direct me as to where/how I could generate logs specific for this widget that would be awesome.

My gethomepage container is deployed in portioner on my Synology

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
- Synology:
        ping: mynasip
        statusStyle: 'dot'
        icon: synology-dsm.svg
        href: https://mynas
        description: HossNAS
        widget:
            type: diskstation
            url: https://mynasip
            username: myuser
            password: mypassword
```

### Troubleshooting

Here is what I have done so far:
- Rebooted the NAS many times
- Completely wiped the widget and user within Synology and carefully went through the steps TWICE to get the widget working again
- Wiped my getHomepage container and pulled a new docker image to start "fresh"...
