### DISCUSSION TITLE
Hide certain service widget parameteres

### DISCUSSION THREAD

**Discussion by AyaanMAG** [gethomepage/homepage#4883] [Support] [answered]
### Description

Hello folks, 
I'm setting up Prowlarr and Radarr service widgets and don't like the missing and numberOfFailGrabs count, and I'd like to hide it, I tried adding numberOfFailGrabs: false to the yaml but that didn't seem to work.

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
- Radarr:
        href: http://10.0.0.11:7878
        description: For Movies
        searchDescriptions: true
        icon: radarr.png
        widget:
            type: radarr
            url: http://10.0.0.11:7878
            key: key
            enableQueue: false # optional, defaults to false
            missing: false

    - Prowlarr:
        href: http://10.0.0.11:9696
        description: For Torrent Trackers
        searchDescriptions: true
        icon: prowlarr.png
        widget:
            type: prowlarr
            url: http://10.0.0.11:9696
            key: key
            numberOfFailGrabs: false
```

### Troubleshooting

N/A
