### DISCUSSION TITLE
Startpage unsupported?

### DISCUSSION THREAD

**Discussion by wanderling** [gethomepage/homepage#4895] [Support]
### Description

Seem like adding Startpage search to this is unsupported? I currently get an error:
![image](https://github.com/user-attachments/assets/393d90f3-7e47-4958-b241-a56ed55d183f)

These instructions were lightly adapted but came from here:
https://support.startpage.com/hc/en-us/articles/4520913488148-Search-strings-adding-Startpage-to-unsupported-web-browsers

Not terribly certain whats going on at the moment.

### homepage version

v0.10.9 (b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
`- search:
    provider: startpage
    url: https://www.startpage.com/sp/search?query=
    target: _blank
    suggestionUrl: https://www.startpage.com/osuggestions?q= # Optional
    showSearchSuggestions: true # Optional
    focus: true # Optional, will set focus to the search bar on page load`
```

### Container Logs

error: undefined

### Troubleshooting

Not relevant. This is a difficult thing to troubleshoot due to the unfortunate names of both the container and the thing I want to add...

**Comment by shamoon** [comment]
You need to use a `custom` provider.
https://gethomepage.dev/widgets/info/search/

**Comment by wanderling** [comment]
Adding 'custom' to the spot currently held by the 'startpage' resulted in duck-duck-go being returned as the search provider. Complete with the logo.

Should I have restarted the container? Should I need to do anything else? If so, I was unable to find further documentation.

Thanks!

**Comment by shamoon** [comment]
When entered correctly that config works fine, maybe you have something else going on, like a duplicate entry or something.

```yaml
- search:
    provider: custom
    url: https://www.startpage.com/sp/search?query=
    target: _blank
    suggestionUrl: https://www.startpage.com/osuggestions?q= # Optional
    showSearchSuggestions: true # Optional
    focus: true # Optional, will set focus to the search bar on page load`
```

https://github.com/user-attachments/assets/8cae7f30-476c-497e-9490-4a8a0556bd1a
