### DISCUSSION TITLE
Group not showing widgets

### DISCUSSION THREAD

**Discussion by macfeegle** [gethomepage/homepage#4896] [Support] [answered]
### Description

Got my homepage mostly up and running, except for a couple of nagging problems.
I'm running homepage in a LXC Container on Proxmox

I've defined a few groups in settings.yaml, and while the first three behave as expected, the fourth named Services (basically a copy of the other three as far as settings are concerned) does show up but remains stubbornly empty of widgets... I've duplicated 2 widgets from Services into the Network group where they function as expected, but they don't show up under Services, nor does the download station widget.

What am I doing wrong?

![homepage2](https://github.com/user-attachments/assets/652d16eb-40d8-41a3-b167-ba100038da62)

### homepage version

v.0.10.9 (source 03/09/2025)

### Installation method

Other (please describe above)

### Configuration

```yaml
settings.yaml:
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab

theme: dark

color: sky

headerStyle: boxed

hideVersion: true

background:
  image: https://img.freepik.com/free-vector/gradient-hexagonal-background_23-2148944165.jpg
  blur: sm
  opacity: 50

providers:
  openweathermap: xxxxxxxxxxxxxxxxxxxxx
  weatherapi: weatherapiapikey

layout:
  Server:
    icon: mdi-server-network-outline
    style: row
    columns: 3
  DNS:
    icon: mdi-dns-outline
    style: row
    columns: 3
  Network:
    useEqualHeights: true
    icon: mdi-lan
    style: row
    columns: 3
  Services:
    icon: mdi-play-network-outline
    style: row
    columns: 3

services.yaml:
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Server:
    - Proxmox:
        icon: proxmox.png
        statusStyle: 'basic'
        href: http://x.x.x.x:8006
        description: Proxmox | Angua status
        widget:
          type: proxmox
          url: https://x.x.x.x:8006
          username: xxxxxxxxxxxxxxxxxxxx
          password: xxxxxxxxxxxxxxxxxxxx

- DNS:
    - PiHole & Unbound instance 1:
        icon: pi-hole-unbound.png
        href: https://x.x.x.x/admin
        description: Raspberry Pi 4B
        widget:
          type: pihole
          url: https://x.x.x.x
          version: 6 # required if running v6 or higher, defaults to 5
          key: 'xxxxxxxxxxxxxxxxxxxxx' # optional, in v6 can be your password or app password
    - PiHole & Unbound instance 2:
        icon: pi-hole-unbound.png
        href: https://x.x.x.x/admin
        description: Proxmox LXC
        widget:
          type: pihole
          url: https://x.x.x.x
          version: 6 # required if running v6 or higher, defaults to 5
          key: "xxxxxxxxxxxxxxxxxxxxx" # optional, in v6 can be your password or app password

- Network:
    - Unifi:
        icon: unifi.png
        statusStyle: 'basic'
        href: http://x.x.x.x
        description: UDM Pro
        widget:
          type: unifi
          url: https://x.x.x.x
          username: xxxxxxxxxxxxxxx
          password: xxxxxxxxxxxxxxx
    - Synology RS1821+:
        icon: synology-dsm.png
        href: https://x.x.x.x:5001
        description: Volume 1 | Data
        widget:
          type: diskstation
          url: https://x.x.x.x:5001
          username: xxxxxxxxxxx
          password: xxxxxxxxxxx
          volume: volume_1
    - Synology RS1821+:
        icon: synology-dsm.png
        href: https://x.x.x.x:5001
        description: Volume 2 | Backups
        widget:
          type: diskstation
          url: https://x.x.x.x:5001
          username: xxxxxxxxxx
          password: xxxxxxxxxx
          volume: volume_2
    - Uptime:
        icon: uptime-kuma.png
        href: http://x.x.x.x:3001
        widget:
          type: uptimekuma
          url: http://x.x.x.x:3001
          slug: homepage
    - MySpeed:
        icon: mdi-speedometer
        href: http://x.x.x.x:5216
        description: Ookla Speedtests
        widget:
          type: myspeed
          url: http://x.x.x.x:5216
    - Plex server:
        icon: plex.png
        href: http://x.x.x.x:32400
        widget:
          type: plex
          url: http://x.x.x.x:32400
          key: xxxxxxxxxx # see https://www.plexopedia.com/plex-media-server/general/plex-token/
    - NGINX:
        icon: nginx-proxy-manager
        description: Reverse Proxy Manager
        href: http://x.x.x.x:81
        widget:
          type: npm
          url: http://x.x.x.x:81
          username: xxxxxxxx
          password: xxxxxxxx

- Services:
    - Plex server status:
      icon: plex.png
      widget:
        type: plex
        url: http://x.x.x.x:32400
        key: xxxxxxxx # see https://www.plexopedia.com/plex-media-server/general/plex-token/
    - Synology Download Station:
      icon: synology.png
      widget:
        type: downloadstation
        url: http://x.x.x.x:5001
        username: xxxxxxxx
        password: xxxxxxxx
    - MySpeed:
      icon: mdi-speedometer
      widget:
        type: myspeed
        url: http://x.x.x.x:5216
```

### Troubleshooting

Does not seems relevant - homepage is running in an LXC, not Docker. All paths are OK, widgets are working when placed in another group
