### DISCUSSION TITLE
[Feature Request]  Services.yaml overriding automatic discovery labels

### DISCUSSION THREAD

**Discussion by owpac** [gethomepage/homepage#4897] [Feature Requests]
### Description

Hello!

First of all, thanks for this amazing application.

I would like to suggest to add a feature that make sense specifically about the Ordering feature of services.

Automatic discovery service is trully an amazing feature. However, when you need to move around services on your dashboard, docker container labels is not a pleasant way for user experience: moving services around should be a parameters in `settings.yml `rather than a docker container label. So, here we are choosing over two possibility:
- Using the amazing automatic discovery service, but without the possibility to move your services without some docker down & up
- Using the settings.yaml for the whole configuration of a service, with an easy ordering but without the flexibility and comfort of automatic discovery service

To fix this user experience, what I suggest is to be able to have a docker compose container like this:

```yaml
services:
  homeassistant:
    container_name: homeassistant
    env_file: 
      - .env
    image: "ghcr.io/home-assistant/home-assistant:stable"
    labels:
      homepage.group: Home
      homepage.name: Home Assistant
      homepage.icon: home-assistant.png
      homepage.href: https://home-assistant.local.net
      homepage.description: Connected home
      # homepage.weight: 10
      homepage.widget.type: homeassistant
      homepage.widget.url: https://home-assistant.local.net
      homepage.widget.key: ${HA_KEY}
      homepage.widget.custom[0].state: sensor.home_temperature
      homepage.widget.custom[0].label: temperature
      homepage.widget.custom[1].state: sensor.home_humidity
      homepage.widget.custom[1].label: humidity
    privileged: true
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
```

With a `services.yaml` like this:

```yaml
---
- Home:
    - Home Assistant:
        weight: 10
        server: docker
        container: homeassistant
```

And the `services.yaml` takes precedence over the docker labels (here it would took the weight in `services.yaml` to be correctly order the service in the dashboard. With this method, we would have the both advantages of automatic discovery scalability and the flexibility of `services.yaml` configuration.

WDYT?
