### DISCUSSION TITLE
Difficulty configuring Custom API for Dokuwiki API

### DISCUSSION THREAD

**Discussion by buffaloexpatbill** [gethomepage/homepage#4898] [Support] [answered]
### Description

I am trying to configure a custom API in homepage services.yaml to get information from Dokuwiki's API.
I have successfully constructed the API call and get a JSON payload from Dokuwiki, but have been unable to configure homepage to successfully map the data.

### homepage version

v0.10.9 (b5f4daa)

### Installation method

Docker

### Configuration

```
    - Dokuwiki:
        href: http://192.168.1.141:1080/
        description: Mullen Studios Wiki
        icon: dokuwiki.svg
        widget:
          type: customapi
          url: http://192.168.1.141:1080/lib/exe/jsonrpc.php/core.listPages
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          method: POST # optional, e.g. POST          
          headers: # optional, must be object, see below
            Content-Type: application/json
            Authorization: Bearer <token>
          requestBody: 
            namespace: 
            depth: 42
            hash: true
          display: # optional, default to block, see below
          mappings:
            - field: 'result'
              label: Pages
              format: size
```

### Container Logs

No errors seen in container logs with debug enabled. Only seeing swapused and available debug logging, which appears to be normal.

### Browser Logs

nothing relevant found in chrome debug logs.
Can attach a HAR capture if useful.

### Troubleshooting

Attaching screen shot of what  is seen in the web page.
[Dokuwiki_widget_customapi](https://github.com/user-attachments/assets/70e0c689-386d-406a-be40-0449fd04b472)

I have confirmed through curl. postman, and even F12 developer tools of chrome, that the JSON is retrieved from the Dokuwiki API.
[Dokuwiki_json_result.txt](https://github.com/user-attachments/files/19155274/Dokuwiki_json_result.txt)

I have utilized the Custom API info at https://gethomepage.dev/widgets/services/customapi/
as well as searched for solutions.

I tested a more simple json output from Dokuwiki using url: http://192.168.1.141:1080/lib/exe/jsonrpc.php/core.getWikiTitle
(Which does not require authentication) I got the JSON result:
{"result":"Mullen Studios Wiki","error":{"code":0,"message":"success"}}
but was unable to get a working mapping to pull the title as text. Presumably this would be something like:

```
    - Dokuwiki:
        href: http://192.168.1.141:1080/
        description: 
        icon: dokuwiki.svg
        widget:
          type: customapi
          url: http://192.168.1.141:1080/lib/exe/jsonrpc.php/core.getWikiTitle
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          method: POST # optional, e.g. POST
          headers: # optional, must be object, see below
            Content-Type: application/json
          display: # optional, default to block, see below
          mappings:
            - field: 'result'
              label: "Wiki Title"
              format: text
```

I have successfully recreated a calibre-web Widget using a Custom API definition as a proof of concept with a different API source. For that custom api testing, I both recreated the output of the built-in API integration as well as using a mapping of:
            - label: Fields
              format: size
to give a count of fields (4).

Reviewed troubleshooting guide as well as logged issues.  I did find https://github.com/gethomepage/homepage/issues/3975 - [Bug] Other jsonRPC handlers broken in 0.9.8 #3975
But it was unclear which jsonRPC handlers would be impacted and if they would still be in v0.10.9 (b5f4daa)

Edit:  forgot to format the yaml text included in the comments.

**Comment by buffaloexpatbill** [comment]
[formatted_services_yaml_entries.txt](https://github.com/user-attachments/files/19155690/formatted_services_yaml_entries.txt)
Had issues getting the inline formatting for yaml.  Attached working (calibre-web) tests and non-working (Dokuwiki) attempts.

**Reply by buffaloexpatbill** [reply]
Thank you @shamoon for fixing the formatting on the original post. It was my first ever on GitHub (had cloned projects to compile before that).
I know that you are very busy. If it would help for anyone that could assist, I could supply a troubleshooting account and expose my Dokuwiki install to the internet to avoid having to install/configure Dokuwiki. 
Also, I have been working in software support for nearly 3 decades. If there is a suggestion to point me in the right direction, I don't need a lot.
I have successfully isolated the count using a curl API request and piping it through jq twice, but still haven't found any mappings that return any values (text or size) from the json objects provided by Dokuwiki.

**Comment by buffaloexpatbill** [comment, marked as answer]
I decided to serve the API response statically on a different webserver so I could easily test GET vs POST as well as alter the JSON.
I found the issue. In both Dokuwiki endpoints I tested, the JSON array returned ended with:

> "error": {
>         "code": 0,
>         "message": "success"
>     }

Which the code in homepage/src/widgets/customapi/component.jsx rather rightfully interprets as a customError.
When I changed the key in the static text on the webserver (changing the name of the key from "error" to "testing"), the customapi info displayed as expected. 
I will workaround this by using middleware to make the API request to Dokuwiki and either strip the error element or change the key name.

Is this something that homepage should handle better, or should Dokuwiki avoid sending an error element/key when there is no error?

**Reply by buffaloexpatbill** [reply]
Workaround completed. Created a dokuwiki_pages.php on a LAN webhost with PHP containing:
```
<?php
$pages_url = 'http://192.168.1.141:1080/lib/exe/jsonrpc.php/core.listPages';
$authToken = 'Bearer <token>';
$options = array(
    'http' => array(
        'method' => 'POST',
        'header' => "Authorization: {$authToken}\r\n".
            "Content-Type: application/json\r\n",
    ));
$context=stream_context_create($options);
$pages_response = file_get_contents($pages_url,FALSE, $context);
$altered_response = str_replace("\"error\"","\"junk\"", "$pages_response");
header('Content-Type: application/json');
echo $altered_response;
?>
```

The widget is configured with:
```
    - Dokuwiki:
        href: http://192.168.1.141:1080/
        description: Mullen Studios Wiki
        icon: dokuwiki.svg
        widget:
          type: customapi
          url: http://192.168.1.101/dokuwiki_pages.php
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          method: GET # optional, e.g. POST          
          headers: # optional, must be object, see below
            Content-Type: application/json
          mappings:
            - field: "result"
              label: "Pages"
              format: size
```
and it now displays the label Pages with the count of pages. This will prevent any other custom error sent in the Dokuwiki API response from being displayed, but is getting the job done for now.
