### DISCUSSION TITLE
mounts fallback to /

### DISCUSSION THREAD

**Discussion by henkiewie** [gethomepage/homepage#49] [Support] [answered]
Hi,
Docker container user here

My df output shows;
/dev/sda1          258095      50713    207383  20% /boot
/dev/sdb2      3906885628 3178624504 728261124  82% /disks/USB2
/dev/sdc1       960280276  320797968 590629524  36% /disks/USB1
/dev/sda3       909653780  300315440 563057176  35% /disks/ARGON
But they are not accepted by homepage and fallback to /
So it seems it can only see the / from the physical machine?

Also my custom search URL from my internal pihole DNS gives me a 404.
- search:
    provider: custom
    target: _blank
    customdata:
      url: https://search.rpi-lite.lan/search?q=
this URL works in all other apps and clients

Any help would be appreciated.

**Comment by benphelps** [comment, marked as answer]
You'll want to make sure your extra disks are mounted to the docker container as volumes for it to be able to access them.

```yaml
volumes:
    - /disks/USB1:/USB1
    - /disks/USB2:/USB2
    - /disks/ARGON:/ARGON
```

and then in your widget configuration:
```yaml
- resources:
    label: USB1
    disk: /USB1

- resources:
    label: USB2
    disk: /USB2

- resources:
    label: ARGON
    disk: /ARGON
```

For search widget configuration, check here: https://github.com/benphelps/homepage/wiki/Information-Widgets#search

**Reply by henkiewie** [reply]
Record breaking support 🚀 .
The search engine had two spaces in front it's all working now.
Now adding my 30+ containers 😄 
Thanks for the quick answers.

**Comment by hunkyn** [comment]
@benphelps this helped. Is there a way we can group all of these under one Storage? I have around 5 disks and wanted to see if there is a way we can group them

<img width="571" alt="image" src="https://user-images.githubusercontent.com/2773074/189513817-ecef24e4-4b0c-452e-b3e5-1a9173d9bce4.png">

**Reply by benphelps** [reply]
Sure, I just pushed a change that will allow you to group them, you can pass an array of disks instead of a single disk, like this:

```yaml
- resources:
    disk:
      - /mnt/Data
      - /mnt/Backup
      - /mnt/Media
```

<img width="369" alt="Screenshot 2022-09-11 at 2 15 42 PM" src="https://user-images.githubusercontent.com/82196/189524488-9dfa2845-6b85-4169-9277-b8dd3d047dd2.png">
