### DISCUSSION TITLE
Pi-Hole Widget is not working after upgrading Pi-Hole to version 6

### DISCUSSION THREAD

**Discussion by specanything** [gethomepage/homepage#4901] [Support] [answered]
### Description

I recently upgraded my Pi Hole to version 6 and noticed that my homepage widget is no longer working. Here is my version information from PiHole:

![pi-hole version](https://github.com/user-attachments/assets/3165d226-42af-4a8c-a23d-9809485cba78)

I keep getting the following on the homepage:

![Homepage with v6 version](https://github.com/user-attachments/assets/fb5e54be-ed2e-4a02-8dda-5f7cdac4c0f5)

I have adjusted and used the old version 5 configuration, which is not working.

![Homepage without v6](https://github.com/user-attachments/assets/c5769d12-05e0-4f30-a6a5-088b0c1ef8b0)

But I noticed in the 6.0.5 documentation of Pi-hole, the API URL call has changed to now http://[pi-hole address]/api. It no longer points to http://[pi-hole address]/admin/api. Also, the default port of 80 has been changed to 8080. Was this taken into account with the recent homepage release? 

### homepage version

v0.10.9(b5f4daa, Jan 6, 2025)

### Installation method

Docker

### Configuration

```yaml
- Pi-Hole:
        icon: pi-hole.png
        href: https://<private>
        siteMonitor: https://<private>
        description: Ad Blocking Service
        widget:
          type: pihole
          url: http://<private>
          version: 6
          key: <extracted>
```

### Container Logs

![curl - pihole](https://github.com/user-attachments/assets/068e0775-58e0-4e31-8246-85b0a9e18bb6)

### Troubleshooting

1. Reconfigured the widget config to point to both version 6 and not version 6
2. Change widget URL to point to http://<pihole address>/api 
3. Curl the pihole page in docker container with /admin/api, /api, port 80, port 8080. Got a successful call with 8080 port was used.
