### DISCUSSION TITLE
[Bug/Feature] Plex Widget causes "Missing X-Plex-Container-Size header" errors in Plex

### DISCUSSION THREAD

**Discussion by cglatot** [gethomepage/homepage#4902] [Support] [answered]
### Description

The Plex widget is causing the following error in Plex:
`Missing X-Plex-Container-Size header. This will fail with status code 400 in the future.`

Looking at the Plex logs the originating calls are:
`GET /library/sections/1/all (10 live)`
`GET /library/sections/2/all (10 live)`

This is for both of my libraries, but I assume it will cause this error for as many libraries you have. I have also confirmed 100% that this is coming from Homepage, as it lists the LAN IP that Homepage is using.

It's easy to replicate this - just open your Homepage. If you have the Plex Console up, you can see it cause these errors in realtime. It doesn't do it _every_ time, as I assume there is some caching involved. But if you restart the Homepage service, or the cache expires, it will cause this error in Plex every time.

Technically speaking, this doesn't break anything _right now_, but as per the warning, in the future it could break something. It's also clogging up the Plex logs, so makes reading it more difficult.

### homepage version

v0.10.9

### Installation method

Unraid

### Configuration

```yaml
This is probably irrelevant, as looking at the github there is indeed no X-Plex-Container-Size header, but here it is anyway:

- Plex:
        icon: plex.svg
        href: <redacted WAN URL>
        container: plex
        widget:
          type: plex
          url: <redacted local ip:port>
          key: <redacted>
          fields: ["streams", "movies", "tv"]
```

### Container Logs

No relevant logs from Homepage side, as technically it works and still returns the data. The Requests and errors on Plex look like this:

Requests:
`Request: [<HomepageIP>:<localport>] GET /library/sections/2/all (10 live) #1553d Signed-in Token (<username>)`
`Request: [<HomepageIP>:<localport>] GET /library/sections/1/all (10 live) #1554b Signed-in Token (<username>)`

Responses:
`[Req#1553d] Missing X-Plex-Container-Size header. This will fail with status code 400 in the future.`
`[Req#1554b] Missing X-Plex-Container-Size header. This will fail with status code 400 in the future.`

### Troubleshooting

There isn't troubleshooting. It's not a personal problem, it's missing code.

To replicate:
1. Open Plex and go to Settings > Console. Filter to Warning.
2. Load your Homepage that has the Plex widget in it.
3. Look at the errors in the Plex Console.
a. If there are no errors, try restarting your Homepage service or wait for some time - there seems to be some caching.
