### DISCUSSION TITLE
Widget - Custom API security issue

### DISCUSSION THREAD

**Discussion by albinmedoc** [gethomepage/homepage#4908] [Support]
### Description

Hi there!

I successfully set up a widget for PhotoPrism using the Custom API, as the native PhotoPrism widget didn't work for me. However, I noticed that the entire response from PhotoPrism is being returned through the proxy to the client, not just the mapped values.

Why is this necessary? It seems like it should be possible to return only the mapped values. If the response contains any sensitive information, it becomes accessible from the browser.

### homepage version

v0.10.9 (b5f4daa)

### Installation method

Docker

### Configuration

```yaml
widget:
  type: customapi
  url: 'http://photoprism.photoprism-resor.svc.cluster.local/api/v1/config'
  method: GET
  display: block
  mappings:
    - field:
        count: photos
      label: Foton
    - field:
        count: videos
      label: Videor
    - field:
        count: people
      label: Personer
```

### Troubleshooting

I viewed the response using developer tools in chrome, in network tab.
