### DISCUSSION TITLE
Created a Custom API widget for Nagios Core 4.x

### DISCUSSION THREAD

**Discussion by buffaloexpatbill** [gethomepage/homepage#4911] [General]
Not sure how many people use Nagios Core 4.x, but if anyone is interested,  I implemented a Custom API widget in my services.yaml utilizing their hostcount endpoint, to display number of hosts that are up and number of hosts that are down.
EDIT: To update the custom widget config I settled on. Though I've never had a count other than 0 for "unreachable" or "pending", the JSON payload from nagios includes them and 4 data points still work well for the widget.

```
    - nagios:
        href: https://nagios host(:port, if needed)/nagios
        description: system monitoring/alerting
        icon: nagios.svg
        widget:
          type: customapi
          url: https://nagios host(:port, if needed)/nagios/cgi-bin/statusjson.cgi?query=hostcount
          refreshInterval: 10000
          username: username
          password: password
          method: GET
          mappings:
            - field:
                data:
                  count: 'up'
              label: "up"
              format: text
            - field:
                data:
                  count: 'down'
              label: "down"
              format: text
            - field:
                data:
                  count: 'unreachable'
              label: "unreachable"
              format: text
            - field:
                data:
                  count: 'pending'
              label: "pending"
              format: text
```

![nagios_custom_widget](https://github.com/user-attachments/assets/7a6d3287-addb-41ee-86db-f68e0a3f9eda)
