### DISCUSSION TITLE
Pi-Hole v6 widget/service causing zombie sessions on Pi-Hole

### DISCUSSION THREAD

**Discussion by Taomyn** [gethomepage/homepage#4912] [Support] [answered]
### Description

The new v6 widget/service is creating multiple sessions which eventually fills up the default of 16 set on the Pi-Hole server, then blocking all further API accesses. I have Home Assistant, Homarr and others like my browsers starting sessions but none of them cause this to happen.

![image](https://github.com/user-attachments/assets/eac624ba-1bc8-4649-ab37-b469f2681ade)

I can't be 100% certain that Homepage is the cause as the IP is from the container server, but I've seen them logged when I refresh the Homepage page. Perhaps including a User Agent would be helpful.

![image](https://github.com/user-attachments/assets/60862084-33fa-4f27-993f-3ee29548a164)

### homepage version

v0.10.9

### Installation method

Docker

### Configuration

```yaml
- PiHole:
        href: https://pi-hole.mydomain.com/admin
        icon: pi-hole.svg
        description: PI-HOLE
        ping: ralph.star-one.co.uk
        siteMonitor: https://pi-hole.mydomain.com/admin
        statusStyle: "basic"
        widget:
            type: pihole
            url: https://pi-hole.mydomain.com
            version: 6
            key: <redacted>
```

### Container Logs

Nothing is logged

### Browser Logs

n/a

### Troubleshooting

I have also tried http which behaves the same, so I believe the issue is not SSL or the certificate
