### DISCUSSION TITLE
HOMEPAGE_ALLOWED_HOSTS multiple hosts

### DISCUSSION THREAD

**Discussion by modem7** [gethomepage/homepage#4918] [Support] [answered]
### Description

How would I go about putting multiple hosts in HOMEPAGE_ALLOWED_HOSTS?

I've tried both space separated and comma separated. 

### homepage version

1.0.0

### Installation method

Docker

### Configuration

```yaml
homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: Homepage
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HDA: $SERVER_IP
      HOMEPAGE_ALLOWED_HOSTS: homepage.$DOMAINNAME,hda.home
    networks:
      pihole:
        ipv4_address: '172.22.0.118'
    ports:
      - 23626:3000
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $USERDIR/Homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    labels:
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=https"
      - "traefik.http.routers.homepage-rtr.rule=Host(`homepage.$DOMAINNAME`)"
      # - "traefik.http.routers.homepage-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-oauth-admins@file" # Google OAuth 2.0
      - "traefik.http.routers.homepage-rtr.middlewares=chain-authentik@file"
      ## HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:3000/api/healthcheck || exit 1
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
```

### Troubleshooting

I've tried both space separated and comma separated.
