### DISCUSSION TITLE
1.0.0 isn't working

### DISCUSSION THREAD

**Discussion by NightHawkATL** [gethomepage/homepage#4919] [Support] [answered]
### Description

   ▲ Next.js 15.1.7

   - Local:        http://[::1]:3000

   - Network:      http://[::]:3000

 ✓ Starting...

 ✓ Ready in 287ms

[2025-03-14T18:44:54.431Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:54.444Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.403Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.641Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.647Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.652Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.665Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.671Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.680Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.690Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.694Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.701Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.705Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.707Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:55.814Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T18:44:57.295Z] error: Host validation failed for: 10.0.2.25:3015. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

### homepage version

1.0.0

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    network_mode: bridge
    environment:
    #   PUID: 1000
    #   PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: 10.0.0.0/8
    ports:
      - 3015:3000
    volumes:
      - /portainer/Files/AppData/Config/Homepage/images:/app/public/images
      - /portainer/Files/AppData/Config/Homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```

### Troubleshooting

tried copy and pasting the variable multiple times and it still isn't working.
