### DISCUSSION TITLE
`fiveColumns` doesn't work since v1.0.0

### DISCUSSION THREAD

**Discussion by Cheekie25** [gethomepage/homepage#4921] [Support] [answered]
### Description

Even though I have `fiveColumns: true` in my `settings.yaml`, there is only 4 columns since I updated to v1.0.0.
I noticed that this issue only applies to services that are at the "root" of the layout.

### homepage version

v1.0.0

### Installation method

Docker

### Configuration

```
fiveColumns: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  columns: 5

  System:
    tab: Main
    icon: mdi-cog
  Monitor:
    tab: Main
    icon: mdi-monitor-eye
  Media:
    tab: Main
    icon: mdi-multimedia
  Apps:
    tab: Main
    icon: mdi-apps
    Productivity:
      icon: mdi-clipboard-list-outline
    Network_Web_Services:
      icon: mdi-lan
      style: row
      columns: 2
  Network:
    tab: Main
    icon: mdi-lan

  Download:
    tab: Main
    style: row
    columns: 5
    icon: mdi-cloud-download

  Download Others:
    tab: Download Others
    style: row
    columns: 5
    icon: mdi-cloud-download
```

### Troubleshooting

I expect System, Monitor, Media, Apps and Network to be on five columns. But there is only 4.
However, the content of Download is well displayed with 5 columns.
Everything is working fine otherwise.
