### DISCUSSION TITLE
error: Host validation failed for: coco.local:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

### DISCUSSION THREAD

**Discussion by RPadial** [gethomepage/homepage#4925] [Support] [answered]
### Description

After docker update the following error is reported when accessing to Homepage from another computer. Docker image was downloaded from latest brach. 
"error: Host validation failed for: coco.local:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host."

### homepage version

v1.0.0

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    env_file: 
      - stack.env
    volumes:
      - /docker/homepage/config:/app/config # Make sure your local config directory exists
      - /docker/homepage/images:/app/images # Make sure your local config directory exists
      - /docker/homepage/icons:/app/icons   # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      - HOMEPAGE_VAR_NEXTCLOUD=$HOMEPAGE_VAR_NEXTCLOUD
      - HOMEPAGE_VAR_PORTAINER=$HOMEPAGE_VAR_PORTAINER
      - HOMEPAGE_VAR_PORTAINER_KEY=$HOMEPAGE_VAR_PORTAINER_KEY
      - HOMEPAGE_VAR_WIREGUARD=$HOMEPAGE_VAR_WIREGUARD
      - HOMEPAGE_VAR_QBITTORRENT=$HOMEPAGE_VAR_QBITTORRENT
      - HOMEPAGE_VAR_JACKETT=$HOMEPAGE_VAR_JACKETT
      - HOMEPAGE_VAR_SONARR=$HOMEPAGE_VAR_SONARR
      - HOMEPAGE_VAR_RADARR=$HOMEPAGE_VAR_RADARR
      - HOMEPAGE_VAR_JELLYFIN=$HOMEPAGE_VAR_JELLYFIN
      - HOMEPAGE_VAR_JDOWNLOADER=$HOMEPAGE_VAR_JDOWNLOADER
      - HOMEPAGE_VAR_NPM=$HOMEPAGE_VAR_NPM
      - HOMEPAGE_VAR_FILEBROWSER=$HOMEPAGE_VAR_FILEBROWSER

    restart: unless-stopped
```

### Container Logs

   ▲ Next.js 15.1.7

   - Local:        http://[::1]:3000

   - Network:      http://[::]:3000

 ✓ Starting...

 ✓ Ready in 221ms

[2025-03-14T19:47:54.400Z] error: Host validation failed for: coco.local:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:47:54.411Z] error: Host validation failed for: coco.local:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:47:55.466Z] error: Host validation failed for: coco.local:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

### Browser Logs

Error

Host validation failed. See logs for more details.

### Troubleshooting

After docker update the following error is reported when accessing to Homepage from another computer.
