### DISCUSSION TITLE
Error - Host validation failed. See logs for more details.

### DISCUSSION THREAD

**Discussion by sagatxxx** [gethomepage/homepage#4927] [Support] [answered]
### Description

Good afternoon.

After the last update, my homepage stopped working. I get the error "Host validation failed"

I added the variable requested like this:
(      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.6 # required, may need port)
 but it still doesn't work.

I would appreciate it if someone could help me.

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.6 # required, may need port
      PUID: 1026 # optional, your user id
      PGID: 100 # optional, your group id
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - /volume1/docker/homepage/icons:/app/public/icons
    restart: unless-stopped
```

### Container Logs

     
   ▲ Next.js 15.1.7

   - Local:        http://[::1]:3000

   - Network:      http://[::]:3000

 ✓ Starting...

 ✓ Ready in 394ms

[2025-03-14T19:57:33.277Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.473Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.479Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.485Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.493Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.500Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.504Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.514Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

[2025-03-14T19:57:33.519Z] error: Host validation failed for: 192.168.1.13:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

### Browser Logs

Error
Host validation failed. See logs for more details.

### Troubleshooting

-
