### DISCUSSION TITLE
Host validation failed. See logs for more details.

### DISCUSSION THREAD

**Discussion by nvroot** [gethomepage/homepage#4928] [Support] [answered]
### Description

It seems like the Homepage team recently introduced HOMEPAGE_ALLOWED_HOSTS as a required environment variable for host validation. This change is frustrating because it breaks existing setups without clear documentation on how to properly configure it for reverse proxies.

After the latest update, I'm getting the error message:
"Host validation failed. See logs for more details."
when using a forward proxy like Authentik or Authelia with Nginx Proxy Manager.
Can someone explain what values should be set in HOMEPAGE_ALLOWED_HOSTS?
HOMEPAGE_ALLOWED_HOSTS=homepage.site,authentik.site,authentik-internal:port,authentik-internal doesnt works same for Authenlia too. 

### homepage version

v1.0.0

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - './config:/app/config:rw'
      - './icons:/app/public/icons'
      - './images:/app/images:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - 'HOMEPAGE_ALLOWED_HOSTS=home.site,auth.site,authentik-outpost,authentik-outpost:port'
networks:
  proxy:
    external: true
```

### Container Logs

[2025-03-14T20:18:26.704Z] error: Host validation failed for: homepage:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.
[2025-03-14T20:18:26.731Z] error: Host validation failed for: homepage:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.
[2025-03-14T20:18:27.885Z] error: Host validation failed for: homepage:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.
[2025-03-14T20:18:27.897Z] error: Host validation failed for: homepage:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.
[2025-03-14T20:18:27.915Z] error: Host validation failed for: homepage:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.

### Browser Logs

Host validation failed. See logs for more details.

### Troubleshooting

Install latest homepage using docker-compose and add some proxy-auth
