### DISCUSSION TITLE
Error: listen EADDRNOTAVAIL: address not available

### DISCUSSION THREAD

**Discussion by lemppari** [gethomepage/homepage#4929] [Support] [answered]
### Description

Version v0.10.9 starts fine, when trying to use latest, I get error:
 ⨯ Failed to start server
Error: listen EADDRNOTAVAIL: address not available 192.168.2.12:3000
    at <unknown> (Error: listen EADDRNOTAVAIL: address not available 192.168.2.12:3000) {
  code: 'EADDRNOTAVAIL',
  errno: -99,
  syscall: 'listen',
  address: '192.168.2.12',
  port: 3000
}

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
My docker compose file:

services:
  # Homepage - Application Dashboard
  homepage:
#    image: ghcr.io/gethomepage/homepage:v0.10.9
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - "no-new-privileges=true"
#    restart: unless-stopped
    networks:
      - socket_proxy
      - t3_proxy
    ports:
      - "3000:3000"
    env_file: $DOCKERDIR/.env # use .env
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
      - $DOCKERDIR/appdata/homepage/images:/app/public/images
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_ALLOWED_HOSTS: mydomain.dom
      LOG_LEVEL: debug
    labels:
      - "traefik.enable=true"
      # Local
      - "traefik.http.routers.homepage-rtr-local.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr-local.rule=Host(`intra.$DOMAINNAME_1`) && ClientIP(`$LOCALNETWORK`)"
      - "traefik.http.routers.homepage-rtr-local.priority=100"
      # Remote
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`intra.$DOMAINNAME_1`)"
      - "traefik.http.routers.homepage-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.homepage-rtr-local.middlewares=chain-no-auth@file"
      - "traefik.http.routers.homepage-rtr-local.middlewares=homepage-rtr-local-mw"
      - "traefik.http.routers.homepage-rtr.middlewares=chain-authelia-auth@file"
      - "traefik.http.middlewares.homepage-rtr-local-mw.ipallowlist.sourcerange=127.0.0.1/32, 192.168.0.0/16"
      # HTTP Services
      - "traefik.http.routers.homepage-rtr-local.service=homepage-svc"
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
```

### Container Logs

 ⨯ Failed to start server
Error: listen EADDRNOTAVAIL: address not available 192.168.2.12:3000
    at <unknown> (Error: listen EADDRNOTAVAIL: address not available 192.168.2.12:3000) {
  code: 'EADDRNOTAVAIL',
  errno: -99,
  syscall: 'listen',
  address: '192.168.2.12',
  port: 3000
}

### Troubleshooting

Everything works fine using 0.10.9. If I use latest and uncomment restart, the containers restarts constantly with the error message as shown above.
