### DISCUSSION TITLE
Plex Widget Reporting Incorrect Movie Count

### DISCUSSION THREAD

**Discussion by teedoff087** [gethomepage/homepage#4931] [Support] [answered]
### Description

I searched and could not find a discussion about this, but it's definitely a new issue for me. I just upgraded to 1.0.0 and added the HOMEPAGE_ALLOWED_HOSTS environment variable to my compose.yml. Everything is working fine after the upgrade except now my Plex tile is misreporting the number of movies in my library. See screenshot:

<img width="312" alt="image" src="https://github.com/user-attachments/assets/43aae8df-d852-436c-85f7-3ee995653999" />

I was immediately alarmed because I thought something had happened, but both Plex and Jellyfin are unchanged when I check them and they report the same amount of movies. TV Show count is also correct.

Any idea as to why this might be? Any tips for troubleshooting?

### homepage version

1.0.0

### Installation method

Docker

### Configuration

```yaml
- Apps 1:
    - Plex:
        icon: /icons/plex.png
        href: https://plex.example.com
        description: home streaming service
        server: myserver
        container: plex
        showStats: false
        widget:
          type: plex
          fields: ["movies", "tv", "streams"]
          url: https://plex.example.com
          key: <plex token>
```

### Troubleshooting

I updated the Plex token in my services.yaml to see if I was using the incorrect one. I still get the same reported movie count after Homepage refreshes.

Output of `curl -X GET https://plex.example.com/library/sections/1/all?X-Plex-Token=mytoken`:

```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="2307" allowSync="1" art="/:/resources/movie-fanart.jpg" content="secondary" identifier="com.plexapp.plugins.library" librarySectionID="1" librarySectionTitle="My Movies" librarySectionUUID="[redacted]" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1740148659" thumb="/:/resources/movie.png" title1="My Movies" title2="All My Movies" viewGroup="movie">
<Video ratingKey=...
```
