### DISCUSSION TITLE
FiveColumns doesnt work after switch to v1.0

### DISCUSSION THREAD

**Discussion by Elekam** [gethomepage/homepage#4937] [Support] [answered]
### Description

I just updated to v1.0 , adding the new Env var for the allowed host. Everything runs smoothly, no errors with Log_Level on INFO, but my homepage isnt five columns anymore and I dont know why.

I think Im misunderstood in the past what the columns: and style: tags in the layout work but it still looked like I wanted it.
After the upgrade it just wasnt five columns anymore.

### homepage version

v1.0

### Installation method

Docker

### Configuration

```yaml
docker compose:
name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - /docker/homepage:/app/config:rw
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dashboard.my-domain.com
      LOG_LEVEL: DEBUG
    labels:
      # Traefik
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`dashboard.my-domain.com`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000

networks:
  traefik:
    external: true

settings.yaml:
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: My Server
theme: dark # or light
color: slate #Disable/fix color palette
hideVersion: false

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: true
  provider: duckduckgo # google, duckduckgo, bing, baidu, brave or custom

# TODO: Add transparent background

cardBlur: md

statusStyle: "dot"

fiveColumns: true
disableCollapse: true

layout:
  Server:
    tab: Dashboard
    style: column
    columns: 1
    icon: mdi-server
  Personal:
    tab: Dashboard
    style: column
    columns: 3
    icon: mdi-account
  Documentation:
    tab: Dashboard
    style: column
    columns: 3
    icon: mdi-book-multiple
  Media:
    tab: Dashboard
    header: true
    style: column
    columns: 1
    icon: mdi-multimedia
  Network:
    tab: Dashboard
    style: column
    columns: 4
    icon: mdi-server-network
  Security:
    tab: Dashboard
    style: column
    columns: 3
    icon: mdi-security
  Smart Home:
    tab: Dashboard
    style: column
    columns: 5
    icon: mdi-home-automation
  Developing:
    tab: Dashboard
    icon: mdi-code-greater-than
  Media-Management:
    tab: Dashboard
    style: column
    columns: 3
    icon: mdi-download
  Monitoring:
    tab: Dashboard
    style: column
    columns: 4
    icon: mdi-monitor-eye
  Finances:
    tab: Dashboard
```

### Container Logs

homepage  |    ▲ Next.js 15.1.7
homepage  |    - Local:        http://[::1]:3000
homepage  |    - Network:      http://[::]:3000
homepage  | 
homepage  |  ✓ Starting...
homepage  |  ✓ Ready in 145ms

### Browser Logs

TypeError: this is undefined[bootstrap-autofill.js:1857:9](moz-extension://6302d2b6-ee65-48f5-910d-e7466ffff596/content/bootstrap-autofill.js)
    checkPageContainsShadowDom moz-extension://6302d2b6-ee65-48f5-910d-e7466ffff596/content/bootstrap-autofill.js:1857
    requestIdleCallbackPolyfill moz-extension://6302d2b6-ee65-48f5-910d-e7466ffff596/content/bootstrap-autofill.js:334

### Troubleshooting

Activated LOG_LEVEL: DEBUG
Browser console gives out this type error every 2 seconds, not sure whether it  is related
