### DISCUSSION TITLE
Kavita API Issue

### DISCUSSION THREAD

**Discussion by chiragkrishna** [gethomepage/homepage#4947] [Support] [answered]
### Description

When using **username** & **Password**, it works perfectly but using API gives error

### homepage version

v1.0.2

### Installation method

Docker

### Configuration

services.yaml
```
    - Kavita:
        icon: kavita.png
        href: {{REDACTED}}
        description: Book Services
        widget:
          type: kavita
          url: {{REDACTED}}
          key: "{{HOMEPAGE_VAR_KAVITA_KEY}}"
```

### Container Logs

Widget shows NaN NaN
Logs
```
error: <kavitaProxyHandler> Error getting data from Kavita: https://{{REDACTED}}/api/Stats/server/stats status 401. Data: 
```
