### DISCUSSION TITLE
OpenMeteo always requires "click to allow current location"

### DISCUSSION THREAD

**Discussion by aarononeal** [gethomepage/homepage#4951] [Support]
### Description

The [documentation](https://gethomepage.dev/widgets/info/openmeteo/) states:

> You can optionally not pass a latitude and longitude and the widget will use your current location ...

This implies that passing a latitude and longitude should _not_ require the user click to allow location. However, I am always forced to click and grant current location access, even if using the config from the docs:

```yaml
- openmeteo:
    label: Kyiv # optional
    latitude: 50.449684
    longitude: 30.525026
    timezone: Europe/Kiev # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
```

<img width="214" alt="image" src="https://github.com/user-attachments/assets/4e819ad4-7977-40ea-8593-7c230ee5397e" />

### homepage version

v0.10.9

### Installation method

Docker

### Troubleshooting

N/A
