### DISCUSSION TITLE
Kubernetes liveness probe failed

### DISCUSSION THREAD

**Discussion by pmezhuev** [gethomepage/homepage#4959] [Support] [answered]
### Description

When launching Homepage in a Kubernetes cluster, the liveness probe fails. The error clearly indicates the need to configure `HOMEPAGE_ALLOWED_HOSTS`, but this is impossible to do because the pod's IP address changes dynamically with each restart.

### homepage version

v1.0.2

### Installation method

Other (please describe above)

### Configuration

```yaml
spec:
  containers:
    - env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: example.com
      image: ghcr.io/gethomepage/homepage:v1.0.2
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /api/healthcheck
          port: http
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: homepage
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
```

### Container Logs

> error: Host validation failed for: 10.244.2.23:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.

### Troubleshooting

—
