### DISCUSSION TITLE
Cannot connect to Homepage after HOMEPAGE_ALLOWED_HOSTS environment variable was mandatory

### DISCUSSION THREAD

**Discussion by Agrigor** [gethomepage/homepage#4960] [Support]
### Description

Hi there,

my setup is about having gethomepage running as docker container orchestrated by docker-compose and a caddy webserver as reverse proxy.

In the code/configuration/logs below I used PRIVATEDOMAIN.TLD due to privacy reasons for a proper FQDN.

Could you please provide me a solution for this? Thanks in advance!!

Kind regards,
Agirgor

### homepage version

latest (Image ID d333d18f5552), should be 1.0.2

### Installation method

Docker

### Configuration

```yaml
The docker-compose file looks like:
`

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/caddy/config:/config
      - /docker/caddy/data:/data
      - /docker/caddy/web:/srv
      - /docker/caddy/certs:/certs
      - /docker/caddy/CaddyFile:/etc/caddy/Caddyfile

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    hostname: services
    volumes:
      - /docker/homepage/public/images:/app/public/images
      - /docker/homepage/public/icons:/app/public/icons
      - /docker/homepage/settings:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: services.PRIVATEDOMAIN.TLD,services.PRIVATEDOMAIN.TLD:80,services.PRIVATEDOMAIN.TLD:443,services.PRIVATEDOMAIN.TLD:3000,homepage:3000
      PUID: 1000
      PGID: 994

`

The CaddyFile as reverse proxy is:
`

services.PRIVATEDOMAIN.TLD {
  reverse_proxy homepage:3000
  encode zstd gzip
  tls /certs/PRIVATEDOMAIN.TLD/fullchain.pem /certs/PRIVATEDOMAIN.TLD/key.pem
  header Strict-Transport-Security max-age=63072000
}

`
```

### Container Logs

If I recreate the container and the container is started, the logs still say:
`

homepage  | 2025-03-15T10:50:56.624395762Z    ▲ Next.js 15.1.7
homepage  | 2025-03-15T10:50:56.624525718Z    - Local:        http://[::1]:3000
homepage  | 2025-03-15T10:50:56.624536249Z    - Network:      http://[::]:3000
homepage  | 2025-03-15T10:50:56.624577077Z
homepage  | 2025-03-15T10:50:56.624654996Z  ✓ Starting...
homepage  | 2025-03-15T10:50:56.762664476Z  ✓ Ready in 146ms
homepage  | 2025-03-15T10:51:08.707697095Z [2025-03-15T10:51:08.706Z] error: Host validation failed for: services.PRIVATEDOMAIN.TLD. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | 2025-03-15T10:51:08.716673528Z [2025-03-15T10:51:08.716Z] error: Host validation failed for: services.PRIVATEDOMAIN.TLD. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.

`

### Troubleshooting

I tried all the possible combinations from domains and ports (as single entry as well as all as comma seperated list) and always recreated the container before starting it up again. I am using Ansible, so it is always the same playbook with recreate policy set to always.
