### DISCUSSION TITLE
HOMEPAGE_ALLOWED_HOSTS issue after update on docker

### DISCUSSION THREAD

**Discussion by Spojler** [gethomepage/homepage#4961] [Support] [answered]
### Description

Hello,
I running Homepage on docker. After Homepage was updated by watchtower that manage with updating my containers without interaction I seen that homepage show me up error "Host validation failed. See logs for more details." After looking at logs I seen that homepage.local (custom DNS record at ADGuard) is not allowed host. I using docker-compose file for deploying and I tried add host that show at my log into .ENV file that I hold API keys and even at yml file but it not help.
And also I use NGING Proxy Manager allowing me to access my stuff using SSL encryption with self signed certificates.

### homepage version

1.0.2

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 8081:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./icons:/app/public/icons
      - ./images:/app/public/images
      #- /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: homepage.local
```

### Container Logs

[2025-03-15T11:55:09.854Z] error: Host validation failed for: homepage.local. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.

### Browser Logs

Host validation failed. See logs for more details.

### Troubleshooting

I tried to add environment variable like log entry suggest HOMEPAGE_ALLOWED_HOSTS into docket-compose.yml file and even .ENV file that I hold API keys for statistics at my dashboard in Homepage.
