### DISCUSSION TITLE
ENOTFOUND Failed to start server with version 1.0.3

### DISCUSSION THREAD

**Discussion by platteel** [gethomepage/homepage#4986] [Support] [answered]
### Description

Homepage has been updated to version 1.0.3 and HOMEPAGE_ALLOWED_HOSTS = *
All other options in the docker compose file have remained the same. But now I see the following errors in the docker logs:

 ⨯ Failed to start server

[Error: getaddrinfo ENOTFOUND myserver] {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'myserver'
}

This causes the container to restart over and over again.
Where is this error comming from?

### homepage version

1.0.3

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    restart: always
    profiles: ["app", "all"]
    networks:
      - t3_proxy
    ports:
      - "$HOMEPAGE_PORT:3000"     # HOMEPAGE_PORT = 4080
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - HOMEPAGE_ALLOWED_HOSTS=*
      - LOG_LEVEL=debug 
    volumes:
      - $DOCKERDIR/appdata/homepage/config:/app/config # Make sure your local config directory exists
      - $DOCKERDIR/appdata/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"      
      - "traefik.enable=true"
      - "alloy.logs.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`home.$DOMAINNAME`)"
      ## HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
```

### Container Logs

 ⨯ Failed to start server

[Error: getaddrinfo ENOTFOUND myserver] {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'myserver'
}
 ⨯ Failed to start server

[Error: getaddrinfo ENOTFOUND myserver] {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'myserver'
}

### Troubleshooting

Added - LOG_LEVEL=debug
