### DISCUSSION TITLE
Homepage allowed hosts problem

### DISCUSSION THREAD

**Discussion by luebbe** [gethomepage/homepage#4991] [Support]
### Description

Sorry, this is really frustrating and the answers provided here didn't help me yet.

I'm running homepage on a raspberry using docker compose.

My docker compose:

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
#      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: unless-stopped
    environment:
#      HOMEPAGE_ALLOWED_HOSTS: http://192.168.0.10:80
#      HOMEPAGE_ALLOWED_HOSTS: http://192.168.0.10
      HOMEPAGE_ALLOWED_HOSTS: 192.168.0.10
```

and the log is full of:

`Host validation failed for: 192.168.0.10. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host.`

no matter which variant with/without http(s) and or port number I have tried.

### homepage version

v1.0.3

### Installation method

Docker

### Troubleshooting

I didn't find any relevant information for the allowed hosts problem in the troubleshooting guide.

**Comment by shamoon** [comment]
1. What is the output of `docker exec -it homepage env`?
2. Did you re-create (not just restart) the container after changing it?

**Comment by luebbe** [comment]
Thanks for your reply. Here's the current docker-compose.yml, which works.

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
#      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.0.10
#      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev
```
output of docker exec -it homepage env:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=0.0.0.0
TERM=xterm
HOMEPAGE_ALLOWED_HOSTS=192.168.0.10
NODE_VERSION=22.14.0
YARN_VERSION=1.22.22
NODE_ENV=production
PORT=3000
HOME=/root
```

and yes, I recreated the container. Also tried with --force-recreate, which didn't help at first.
I don't understand, what finally made the difference. I tried several times with or without port number and the variant without port number works.

**Comment by roarinpenguin** [comment]
Good morning.
My docker compose.yaml reads:
```
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.189 
    ports:
      - 3000:3000
```

Despite this, I cannot connect from the mentioned IP.
I have also tried` HOMEPAGE_ALLOWED_HOSTS: * `
but it returns an error like:
yaml: line 8: did not find expected alphabetic or numeric character
I have tried to use 
`HOMEPAGE_ALLOWED_HOSTS: '*'`
and only that made the trick.
Could you please elaborate more on why my IP based syntax is wrong?
Thanks.
