### DISCUSSION TITLE
Hoarder API error

### DISCUSSION THREAD

**Discussion by aptonline** [gethomepage/homepage#4992] [Support] [answered]
### Description

Added the new Hoarder api using domain name (minus port as reverse proxy adds this) and seeing the following error:

`API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### homepage version

1.0.3 (proxmox script)

### Installation method

Other (please describe above)

### Configuration

```yaml
- Apps:
    - Hoarder:
        href: https://hoarder.domain.com
        icon: hoarder.png
        description: Bookmark manager.  
        server: my-docker # The docker server that was configured
        container: hoarder # The name of the container you'd like to connect
        widget:
          type: hoarder
          url: https://hoarder.domain.com
          key: api key
```

### Container Logs

-

### Browser Logs

-

### Troubleshooting

-
