### DISCUSSION TITLE
iFrame heights

### DISCUSSION THREAD

**Discussion by trackermb** [gethomepage/homepage#4993] [Support] [answered]
### Description

On the latest version iframe heights fail to do anything, 

### homepage version

V1.0.3

### Installation method

Docker

### Configuration

```yaml
- ‎:
    - Playing / Coming Soon  :
        widget:
          type: iframe
          src: https://poster-active.xxxxxxxxxxx
          classes: h-96
#- ‎‎:          
    - On Demand :
        widget:
          type: iframe
          src: https://poster-xxxxxxxx.xx
          classes: h-96
```

### Troubleshooting

I have changed the h-96 to, h-60, h-60, h-72 and even h-full from tailwind height classes but no change happened, the only time I saw any change was when removed classes and it did increase the size a bit. 
Below is screenshot of 0.10.9 with h-96
<img width="1569" alt="Screenshot 2025-03-16 at 13 01 00" src="https://github.com/user-attachments/assets/81ed7011-d3ec-427f-af56-c14899603b79" />

Below is screenshot of 1.0.3 with h-96
<img width="1751" alt="image" src="https://github.com/user-attachments/assets/f74948b8-52a6-481e-bbc8-a36a121b25de" />
