### DISCUSSION TITLE
Bookmarks Widget Incorrect Height

### DISCUSSION THREAD

**Discussion by epd5** [gethomepage/homepage#4995] [Support] [answered]
### Description

The anchor elements when using bookmarks have the incorrect height, resulting in the box being longer than the icon + text. Looking at the HTML the anchor elements seem to contain the class h-full, which results in this. Removing them fixes the problem. 
![Screenshot](https://github.com/user-attachments/assets/baf42c8d-426f-4b8e-8b66-37a28ae60ead)

### homepage version

v1.0.3 (6292a07, Mar 15, 2025)

### Installation method

Docker

### Configuration

```yaml
Relevant:
Settings.yaml
layout:
  Bookmarks:
    tab: Home
    header: false
    style: row
    columns: 8

bookmarks.yaml
  - Free Code Camp:
    - icon: coder-light.svg
      href: https://www.freecodecamp.org/learn
      description: ""
```

### Troubleshooting

Removing class h-full from the anchor element removes this error.
