### DISCUSSION TITLE
Docker 5 minute start-up delay - please fix

### DISCUSSION THREAD

**Discussion by jerobins** [gethomepage/homepage#5016] [Support] [answered]
### Description

When configuring docker to not run as root, there is a 5 minute delay when bringing up the service.

This appears to be because of a chown -R for the entire app dir,

Other references of folks reporting this:

_Originally posted by @ChoosenMEME in https://github.com/gethomepage/homepage/discussions/3654_

_Originally posted by @ihatemyisp in https://github.com/gethomepage/homepage/discussions/4116_

### homepage version

v1.0.4

### Installation method

Docker

### Configuration

```yaml
homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 4000:3000
    volumes:
      - ./config:/app/config
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: "*"
```
```


### Container Logs

```
homepage  |    ▲ Next.js 15.1.7
homepage  |    - Local:        http://localhost:3000
homepage  |    - Network:      http://0.0.0.0:3000
homepage  |
homepage  |  ✓ Starting...
homepage  |  ✓ Ready in 140ms
```

### Browser Logs

```homepage
UID        PID       PPID      C    STIME   TTY   TIME       CMD
root       1747502   1747481   0    13:40   ?     00:00:00   /bin/sh /usr/local/bin/docker-entrypoint.sh node server.js
jerobins   1755129   1747502   1    13:45   ?     00:00:04   next-server
```
Note the times.

### Troubleshooting

Notes that just chown'ing the config dir has no ill affects: _@ihatemyisp in https://github.com/gethomepage/homepage/discussions/4116_
