### DISCUSSION TITLE
Versions beyond 1.0.2 not working with Traefik

### DISCUSSION THREAD

**Discussion by modem7** [gethomepage/homepage#5019] [Support] [answered]
### Description

Versions beyond 1.0.2 not working with Traefik.
 
For some odd reason, homepage stops working with Traefik beyond version 1.0.2. Nothing changes beyond recreating the container with a different version.

### homepage version

1.0.4

### Installation method

Docker

### Configuration

```yaml
homepage:
    image: ghcr.io/gethomepage/homepage:v1.0.2
    container_name: Homepage
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HOMEPAGE_VAR_HDA: $SERVER_IP
      HOMEPAGE_ALLOWED_HOSTS: homepage.$DOMAINNAME,hda.home:23626
    networks:
      pihole:
        ipv4_address: '172.22.0.118'
    ports:
      - 23626:3000
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $USERDIR/Homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    labels:
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=https"
      - "traefik.http.routers.homepage-rtr.rule=Host(`homepage.$DOMAINNAME`)"
      # - "traefik.http.routers.homepage-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-oauth-admins@file" # Google OAuth 2.0
      - "traefik.http.routers.homepage-rtr.middlewares=chain-authentik@file"
      ## HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:3000/api/healthcheck || exit 1
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
```

### Container Logs

No additional logs, including if I set log level to debug

### Troubleshooting

Tried creating container as 1.0.2 which works. 
1.0.3 and 1.0.4 doesn't work. Doesn't even come up in Traefik for some reason as an error or service. 

With 1.0.2, it works immediately without any configuration changes bar setting the tag. 

It works internally (e.g. accessing it outside Traefik, which is expected), but something between 1.0.2 and 1.0.3 has changed which has broken something, not sure what though as there are no logs pointing to any form of error.
