### DISCUSSION TITLE
[Feature Request] Netbird

### DISCUSSION THREAD

**Discussion by fede843** [gethomepage/homepage#5023] [Feature Requests]
### Description

Netbird has become a popular choice for self hosted VPN solution.
It would be nice to get it integrated.

https://netbird.io/

**Comment by pops199** [comment]
I am also busy re-installing my home server and while adding all services to homepage couldn't find a netbird integration, this should be something the devs look at.

**Comment by kray74** [comment]
Perhaps someone will be interested in a netbird widget implemented with [custom api](https://gethomepage.dev/widgets/services/customapi/). It shows a list of peers and their IP addresses:

```yaml
Netbird:
  href: https://app.netbird.io
  icon: netbird.png
  widget:
    type: customapi
    url: https://api.netbird.io/peers
    method: GET
    headers:
      Authorization: Token {{HOMEPAGE_VAR_NETBIRD_TOKEN}}
    display: dynamic-list
    mappings:
      name: name
      label: ip
      target: https://app.netbird.io/peer?id={id}
```

Useful links:
[How to get netbird token](https://docs.netbird.io/how-to/access-netbird-public-api)
[Netbird API documentation](https://docs.netbird.io/api)
