### DISCUSSION TITLE
Layout implementation seems hacky

### DISCUSSION THREAD

**Discussion by Blubberland** [gethomepage/homepage#5028] [Support]
### Description

I looked at the closed issues and discussions and search through the discord channel, that gets abused for showcasing instead of sharing.

---

> Layout implementation seems hacky

is an assumption, based on the expected behaviour in contrary to the actual behaviour. I don't javascript.

---

Besides the fact, that I don't get, why
```
style: row
columns: 4
```
even if there seems to be no other style type, because the implicated (there's no documentation, which values can have which keys) vice versa
```
style: column  # or style: columns
rows: 4 # or row: 4
```
does just nothing; the following layout is buggy:

settings.yml
```yml
layout:
  firsttab:
    tab: tabA
    style: row
    columns: 4
...
```
services.yml
```yml
- firsttab:
    - Some-widget
    - Another-widget
    - Widget-group:
      - grouped-widget-one
      - grouped-widget-two
    - Any-widget
```

Is displayed like this:

|  Some-widget  | Another-widget | Any-widget |
| Widget-group |

instead of like this:

|  Some-widget  | Another-widget | Widget-group | Any-widget |

### homepage version

v1.0.3 (6292a07)

### Installation method

Docker

### Configuration

```yaml
see above
```

### Container Logs

don't seem relevant

### Browser Logs

don't seem relevant

### Troubleshooting

definitely not relevant
