### DISCUSSION TITLE
Podman non-root - permission denied settings.yaml

### DISCUSSION THREAD

**Discussion by arnaud-sk** [gethomepage/homepage#5031] [Support] [answered]
### Description

I use podman on Fedora with my username.
I can compose and run my container, but I can't access homepage.

### homepage version

15.1.7

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: $PUID
      PGID: $PGID
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /run/user/1000/podman/podman.sock:/var/run/podman.sock
    restart: unless-stopped
```

### Container Logs

   ▲ Next.js 15.1.7
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 133ms
H ⨯ Error: EACCES: permission denied, open '/app/config/settings.yaml'
    at u (.next/server/pages/browserconfig.xml.js:9:1330)
    at p (.next/server/pages/index.js:9:22130)
    at <unknown> (.next/server/pages/index.js:9:22542)
    at f (.next/server/pages/index.js:9:22790)
    at <unknown> (.next/server/pages/index.js:9:16959) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.yaml'
}
H ⨯ Error: EACCES: permission denied, open '/app/config/settings.yaml'
    at d (.next/server/chunks/8567.js:1:1457)
    at d (.next/server/chunks/8567.js:1:17357)
    at <unknown> (.next/server/chunks/8567.js:1:17769)
    at m (.next/server/chunks/8567.js:1:18017)
    at <unknown> (.next/server/pages/api/config/[path].js:1:1207)
    at o.a (.next/server/webpack-api-runtime.js:1:866)
    at 25079 (.next/server/pages/api/config/[path].js:1:1040)
    at o (.next/server/webpack-api-runtime.js:1:127)
    at <unknown> (.next/server/pages/api/config/[path].js:1:749) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.yaml'
}

### Browser Logs

Application error: a client-side exception has occurred (see the browser console for more information).

### Troubleshooting

After create and run container without error, I have an error when I want access to page. I use podman-compose command for create container.
Logs say : Error: EACCES: permission denied, open '/app/config/settings.yaml'.

I have checked rights : 
```
~% ls -l config 
total 24
-rw-r--r--. 1 arnaud arnaud  533 18 mars  14:52 bookmarks.yaml
-rw-r--r--. 1 arnaud arnaud 2859 18 mars  14:20 config-backup.zip
-rw-r--r--. 1 arnaud arnaud  192 18 mars  14:49 docker.yaml
-rw-r--r--. 1 arnaud arnaud    0 18 mars  14:51 kubernetes.yaml
drwxr-xr-x. 1 arnaud arnaud   24 14 mars  16:06 logs
-rw-r--r--. 1 arnaud arnaud  420 18 mars  14:51 services.yaml
-rw-r--r--. 1 arnaud arnaud  522 18 mars  14:50 settings.yaml
-rw-r--r--. 1 arnaud arnaud  330 18 mars  14:49 widgets.yaml
```
