### DISCUSSION TITLE
HOMEPAGE_ALLOWED_HOSTS isn't working for me

### DISCUSSION THREAD

**Discussion by schtocker** [gethomepage/homepage#5033] [Support] [answered]
### Description

I know there have been a number of discussions on this already but I cannot figure this out. The documentation says to "ensure that the host exactly as output in the logs is in the HOMEPAGE_ALLOWED_HOSTS list" but as you can see in my Dockge screenshot below, it is! 

<img width="1888" alt="Screenshot 2025-03-18 at 17 36 06" src="https://github.com/user-attachments/assets/35bf20b6-2cfb-478a-b1c8-2bab10c07962" />

Cannot work out why this isn't working. I have even tried it with the wildcard asterisk on the allowed hosts but even that doesn't work. I imagine I'm missing something obvious!

### homepage version

v1.0.4

### Installation method

Docker

### Configuration

```yaml
version: "3"
services:
  homepage:
    container_name: homepage
    dns:
      - 192.168.31.1
    environment:
      - HOMEPAGE_ALLOWED_HOSTS:*
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3550:3000/tcp
    restart: always
    networks:
      - service-network
    volumes:
      - /volume1/docker/homepage:/app/config
      - /volume1/docker/homepage/public/icons:/app/public/icons
      - /volume1/docker/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  service-network:
    external: true
```

### Container Logs

```
homepage  |    ▲ Next.js 15.1.7
homepage  |    - Local:        http://localhost:3000
homepage  |    - Network:      http://0.0.0.0:3000
homepage  | 
homepage  |  ✓ Starting...
homepage  |  ✓ Ready in 727ms
homepage  | [2025-03-18T17:48:16.251Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.337Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.355Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.383Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.401Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.412Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.436Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.453Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.473Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.497Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.518Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:16.524Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
homepage  | [2025-03-18T17:48:17.274Z] error: Host validation failed for: 172.16.44.2:3550. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
```

### Troubleshooting

- Tried wildcard asterisk for allowed hosts, same error
- Tried different port for container, same error
