### DISCUSSION TITLE
Portainer Missing 3 in the API Call

### DISCUSSION THREAD

**Discussion by naby-dev** [gethomepage/homepage#5035] [Support] [answered]
### Description

Hello! 
I recently installed Homepage and the portainer widget failing to load data as the endpoint is returning a 404. 

![IMG-20250319-WA0001](https://github.com/user-attachments/assets/a67596d7-c391-40b6-9ac0-cc764288f793)
![IMG-20250319-WA0000](https://github.com/user-attachments/assets/68f9edec-7f4d-43b7-bd13-64b000a4d607)

Notice I'm the double slash in the endpoint. 
Investigating the calls I noticed that Portainer places a 3 there.

NB: I am using Portainer BE (Free) running via a compose

### homepage version

v1.0.4 (6fbe080, Mar 16, 2025)

### Installation method

Docker

### Configuration

```yaml
PORTAINER_URL=https://192.168.3.232:9443

  portainer:
    labels:
    - homepage.group=Utilities
    - homepage.name=Portainer
    - homepage.icon=portainer.png
    - homepage.href=${PORTAINER_URL}
    - homepage.description=Manage Docker Containers and Volumes
    - homepage.widget.type=portainer
    - homepage.widget.url=${PORTAINER_URL}
    - homepage.widget.key=${PORTAINER_KEY}
```

### Container Logs

[2025-03-18T23:06:47.589Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:09:35.848Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:09:41.380Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:11:15.166Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:11:25.205Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:14:05.745Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:14:10.790Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:14:25.817Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:14:55.844Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1
[2025-03-18T23:16:30.871Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.3.232:9443/api/endpoints//docker/containers/json?all=1

### Troubleshooting

Checked Portainer Network Tab for the correct call.
