### DISCUSSION TITLE
PiHole widget: JSON parsing failing during auth

### DISCUSSION THREAD

**Discussion by hrafnthor** [gethomepage/homepage#5039] [Support] [answered]
### Description

Hi, 

First time user of Homepage, and just wanted to start with saying thanks for all the hard work that goes into it.

I'm currently running into an issue with having the PiHole widget communicate with my PiHole instance. Both PiHole and Homepage are being run as part of a Docker compose setup, behind Traefik (I don't believe this has any bearing on the issue, but mention it nonetheless).

According to the logs there seems to be a  JSON parsing error happening during the authentication step against `http://pihole:8080/api/auth` (please see logs).

Any assistance in figuring out what is going wrong here would be highly appreciated, as I am a bit stumped at the moment.

### homepage version

1.0.4

### Installation method

Docker

### Configuration

```yaml
#### Service.yaml

The relevant definition in the `service.yaml` file is as follows:


  - PiHole:
      icon: pihole.png
      href: "{{HOMEPAGE_VAR_PIHOLE_URL}}/admin"
      widgets:
        - type: pihole
          version: 6
          url: "http://pihole:8080"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
          field: ["queries", "blocked", "blocked_percent"]



#### PiHole:

The PiHole versions in question:

```
PiHole Core: 6.0.5
PiHole FTL: 6.0.4
PiHole Web interface: 6.0.2
```
```

### Container Logs

error: <httpProxy> Error calling http://pihole:8080/api/auth...
[
	500,
	Error: connect ECONNREFUSED 192.168.240.3:8080
	at <unknown> (Error: connect ECONNREFUSED 192.168.240.3:8080) {
		errno: -111,
		code: 'ECONNREFUSED',
		syscall: 'connect',
		address: '192.168.240.3',
		port: 8080
	}
]

[2025-03-19T12:39:47.615Z] error: undefined 
[2025-03-19T12:39:47.618Z] error: SyntaxError: "[object Object]" is not valid JSON
	at JSON.parse (<anonymous>)
	at c (/app/.next/server/pages/api/services/proxy.js:4:67541)
	at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
	at async y (/app/.next/server/pages/api/services/proxy.js:4:68289)
	at async z (/app/node_modules/.pnpm/next@15.1.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17092)
	at async U.render (/app/node_modules/.pnpm/next@15.1.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js: 20:17800)
	at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.1.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:628:9)
	at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.1.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-s
erver.js:278:37)
	at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.1.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:8
53:17)
	at async invokeRender (/app/node_modules/.pnpm/next@15.1.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:230:21)

### Troubleshooting

Homepage is able to communicate with the Pihole container:

 ```shell
 docker exec homepage ping pihole
 PING pihole (192.168.240.3): 56 data bytes
64 bytes from 192.168.240.3: seq=0 ttl=64 time=0.082 ms
64 bytes from 192.168.240.3: seq=1 ttl=64 time=0.181 ms
```

And just to double check that the credentials given to the Homepage container were valid, I shelled into the container and used them to authenticate with PiHole:

```shell
wget --header="Content-Type: application/json" 
     --post-data="{\"password\": \"$HOMEPAGE_VAR_PIHOLE_API_KEY\" }" 
     -qO- http://pihole/api/auth

or using curl:

curl -s 
     -H "Content-Type: application/json"
     -d "{\"password\":\"$HOMEPAGE_VAR_PIHOLE_API_KEY\"}" http://pihole/api/auth

```
which seems to work, returning:

```json
{
    "session":
    {
        "valid": true,
        "totp": false,
        "sid": "z6gDGl7eBO+js/aCMKb8SA=",
        "csrf": "lYzGiYGKe+FR4sT23dh7BA=",
        "validity": 1800,
        "message": "app-password correct"
    },
    "took": 0.24115633964538574
}
```
