### DISCUSSION TITLE
Brave browser with hardware acceleration disabled extremely laggy

### DISCUSSION THREAD

**Discussion by Unspec7** [gethomepage/homepage#5042] [Support] [answered]
### Description

When using homepage on Brave, the UI is extremely laggy. Works fine on Chrome. Tried guest profile (e.g. default brave settings with zero extensions) and see the same behavior.

Hardware acceleration is off.

### homepage version

v1.0.4

### Installation method

Source

### Configuration

```
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings
title: Jeff's Homepage
useEqualHeights: true
headerStyle: clean
target: _blank

background:
  image: https://raw.githubusercontent.com/gethomepage/homepage/main/docs/assets/blossom_valley.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

quicklaunch:
  searchDescriptions: true
  provider: google
providers:
  openweathermap: [redacted]

layout:
  Proxmox Monitoring:
    style: row
    columns: 4

  Networking:
    style: row
    columns: 4

  Home:
    style: row
    columns: 4

  Media Management:
    style: row
    columns: 4

  Download Clients:
    style: row
    columns: 4
```

### Troubleshooting

N/A
