### DISCUSSION TITLE
[Feature Request] Implement animated/slideshow component that cycles through widgets

### DISCUSSION THREAD

**Discussion by cwlowder** [gethomepage/homepage#5043] [Feature Requests]
### Description

> Disclaimer: I implemented an MVP of this, but I did that before I [read this](https://gethomepage.dev/widgets/authoring/getting-started/#new-feature-guidelines)

# How it's set up right now

Right now, if you want to know the weather in 2 or more cities, you need to create dedicated widget for each city:

```yaml
#widgets.yaml
- openweathermap:
    label: London
    latitude: 51.5072
    longitude: 0.1276
    cache: 15
    units: imperial
    provider: openweathermap
- openweathermap:
    label: New York City
    latitude: 40.7128
    longitude: -74.0060
    cache: 15
    units: imperial
    provider: openweathermap
```

This takes up valuable space on the dashboard.

![image](https://github.com/user-attachments/assets/c07f8c57-5734-46e8-81f9-5bdb6b8de576)

 What if you want 4, 5 or even 6 different cities?

# What I would like

It would be very useful if we could rotate between multiple widgets like so:

[Screencast from 2025-03-19 19-25-35.webm](https://github.com/user-attachments/assets/10402bde-f92c-4e8c-8b7a-3c8fbd13b82c)

These components could be defined as follows:

```yaml
# Example for resource widget since it's shorter
- animated:
    interval: 3
    transition: fade
    widgets:
        - resources:
            cpu: true
        - resources:
            memory: true
        - resources:
            disk: /
```

# Advantages to adding this widget

We can add tons of cool transitions!

[Screencast from 2025-03-19 19-28-12.webm](https://github.com/user-attachments/assets/56ea8b0a-a0ef-4ec4-87fa-9fa43b55fee5)

# Disadvantages

-  **Widget.yaml parsing** The way that widgets are parsed will need to be changed. The hacky solution I used might not be 100% production ready.
- **Widget Size** The size of widgets are not consistent. If you group together a resource widget with a weather widget, the information widgets will move around. I got around this by rendering each subwidget invisibly and then measuring the max width/height across all of them.
- **Right Aligned** In order to have a consistent experience, I had to refactor the way that right aligned components functioned. I had to add a new property `isRightAligned` to better control where the animated component ends up on the page.

There are a few alternatives that I imagine the community may prefer. We could simply update the relevant components (resource/weather) to allow for cycling between each option. A less generic approach might be simpler/less confusing. Any feedback/suggestions would be appreciated!

You can check out my changes [here](https://github.com/cwlowder/homepage/commit/e3b2ac517de923eba3e504be20aa7c23fbed4874) (be warned I haven't bothered cleaning it up yet - will do so when I create the PR)

If people think it's good enough to move forward, I'll create a PR. I'm sure there are some bugs that will need to be squashed as well.
