### DISCUSSION TITLE
[Feature Request] Video widget (Similar to MJPEG widget)

### DISCUSSION THREAD

**Discussion by bryan065** [gethomepage/homepage#5050] [Feature Requests]
### Description

I'm running frigate and would love to have better/nicer integration to show individual streams as a widget. I'm currently using an iframe widget but it's not ideal.

I had tested using the MJPEG widget but replacing the `<img></img>` section with `<video></video>`.

I also tested it with the iframe widget both stock and with changed HTML. `<iframe></iframe>` section to `<video style="object-fit:cover"></video>` as well.

Example below:
Left is MJPEG widget (with HTML changed). Right is the iFrame widget (no changes to HTML).

![Screenshot 2025-03-21 160736](https://github.com/user-attachments/assets/97ad7ca5-2350-4ff2-bc44-c695fdec8149)

![Screenshot 2025-03-21 155955](https://github.com/user-attachments/assets/ff65c7fc-f6a9-4ba1-99fa-2312557d9be4)

Below is with iframe with HTML changed.

![Screenshot 2025-03-21 161803](https://github.com/user-attachments/assets/a12e533b-ca6b-4af9-be80-e3a3d694622f)

### Homepage settings
https://go2rtc.frigate.domain:1985 is the direct link to the video stream in go2rtc.

```
- NVR:
    - Doorbell:
        widget:
            type: mjpeg
            stream: https://go2rtc.frigate.domain:1985/api/stream.mp4?src=Doorbell&mp4=all
            
    - Driveway:
        widget:
            type: iframe
            name: Driveway
            src: https://go2rtc.frigate.domain:1985/api/stream.mp4?src=Driveway&mp4=all
            classes: h-96
            referrerPolicy: same-origin
            allowFullscreen: false
```
