### DISCUSSION TITLE
EISDIR Error After Updating to v1.0.4

### DISCUSSION THREAD

**Discussion by mischavandenburg** [gethomepage/homepage#5052] [Support]
### Description

# EISDIR Error When Accessing Configuration Files After Updating to Latest

## Issue Description

After updating to the latest version of Homepage, the application fails to start with the following error:

```
Error: EISDIR: illegal operation on a directory, read
    at readFileSync (node:fs:442:20)
    at d (/app/.next/server/pages/index.js:9:6311)
    at f (/app/.next/server/pages/index.js:9:6426)
    at /app/.next/server/pages/index.js:9:16986
```

The application is trying to read something as a file that is actually a directory.

## Environment

- **Homepage version**: v1.0.4
- **Deployment environment**: Kubernetes with ExternalSecret
- **Previously working**: Yes, before updating to v1.0.4

### Kubernetes Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
    try: "1"
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v1.0.4"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: homepage-env-configmap
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          secret:
            secretName: homepage-config
        - name: logs
          emptyDir: {}
```

### ExternalSecret Configuration

My configuration is created from an ExternalSecret that populates a secret with the following structure:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: homepage-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        kubernetes.yaml: |
          mode: cluster
        settings.yaml: ""
        custom.css: ""
        custom.js: ""
        bookmarks.yaml: |
          - Business:
              - KubeCraft Calendar:
                  - abbr: KC
                    href: https://calendar.google.com/calendar/u/1/r
              # ... (additional bookmarks)

        services.yaml: |
          - Homelab:
            - Pi-hole:
                  href: "http://192.168.120.10:3009/admin"
                  icon: pi-hole.png
                  widget:
                      type: pihole
                      url: "http://192.168.120.10:3009"
                      key: {{ .piholekey }}
            # ... (additional services)

        widgets.yaml: |
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "cluster"
              # ... (additional widget config)

        docker.yaml: ""
  data:
    - secretKey: piholekey
      remoteRef:
        key: pihole-key
    # ... (additional secret references)
```

## Debugging Steps Taken

1. Accessed the pod shell to examine the filesystem:

```bash
# Checked Next.js server files
ls -la /app/.next/server/pages
```

Output:
```
total 788
drwxr-xr-x    4 node     node          4096 Mar 16 21:46 .
drwxr-xr-x    5 node     node          4096 Mar 16 21:46 ..
-rw-r--r--    1 node     node          5316 Mar 16 21:46 _app.js
-rw-r--r--    1 node     node         34107 Mar 16 21:46 _app.js.nft.json
-rw-r--r--    1 node     node           926 Mar 16 21:46 _document.js
-rw-r--r--    1 node     node          3982 Mar 16 21:46 _document.js.nft.json
-rw-r--r--    1 node     node          7808 Mar 16 21:46 _error.js
-rw-r--r--    1 node     node         37046 Mar 16 21:46 _error.js.nft.json
drwxr-xr-x    8 node     node          4096 Mar 16 21:46 api
-rw-r--r--    1 node     node          5459 Mar 16 21:46 browserconfig.xml.js
-rw-r--r--    1 node     node         39811 Mar 16 21:46 browserconfig.xml.js.nft.json
drwxr-xr-x    2 node     node            38 Mar 16 21:46 en
-rw-r--r--    1 node     node         43878 Mar 16 21:46 en.html
-rw-r--r--    1 node     node         19896 Mar 16 21:46 en.json
-rw-r--r--    1 node     node        290931 Mar 16 21:46 index.js
-rw-r--r--    1 node     node        229731 Mar 16 21:46 index.js.nft.json
-rw-r--r--    1 node     node          5580 Mar 16 21:46 site.webmanifest.js
-rw-r--r--    1 node     node         39811 Mar 16 21:46 site.webmanifest.js.nft.json
```

2. All files in the application's server directory appear to be correctly set up as files (not directories).

3. The error stack trace shows the issue is in the application's Next.js code, not in the Kubernetes mounting mechanism.

4. I confirmed all configuration files are properly mounted and readable from within the pod.

5. I am running as user node and can cat the index.js file

```bash
/app/.next/server/pages $ cat /etc/passwd
root:x:0:0:root:/root:/bin/sh
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
node:x:1000:1000::/home/node:/bin/sh
/app/.next/server/pages $ whoami
node


```

## Temporary fix

Downgrading to v0.10.9 resolves the issue.

### homepage version

v1.0.4

### Installation method

Other (please describe above)

### Troubleshooting

See above
