### DISCUSSION TITLE
Pihole widget exhausts api sessions

### DISCUSSION THREAD

**Discussion by ForSquirel** [gethomepage/homepage#5058] [Support]
### Description

Every time homepage is loaded it uses another session, reducing the amount of available sessions

### homepage version

1.0.4

### Installation method

Docker

### Configuration

```yaml
- Katie:
        icon: /icons/pihole.png #si-pihole
        href: https://x.x.x/admin
        #description: Katie Pi-Hole Server
        widget: 
          type: pihole
          url: https://x.x.x
          version: 6
          key: my secret key
```

### Container Logs

[2025-03-22T23:30:51.147Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:30:51.625Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:31:13.286Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:31:13.289Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:32:59.034Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:32:59.122Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:35:48.172Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:35:48.260Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:38:38.160Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429
[2025-03-22T23:38:38.169Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 429

### Troubleshooting

Update pihole and startpage to latest. Have also submitted issue with pihole.
