### DISCUSSION TITLE
Pihole V6 widget API authentication error

### DISCUSSION THREAD

**Discussion by Stuart-Bush** [gethomepage/homepage#5061] [Support]
### Description

I am using PiHole 6 and have researched all of the solutions posted here.  No matter what I do, Homepage seems to default to looking for https//xxxxx/admin/api instead of the new requirement that the api is found at https://xxxx/api

I specified version: 6 in my config file, but still no change. I can confirm my homepage and pihole are on the same network. I would like to know how anyone solved this.  Thanks!

### homepage version

v 0.71 (3cfr88d2)

### Installation method

Docker

### Configuration

```yaml
- PiHole:
        icon: pi-hole.png
        href: "http://pihole-k2.XXXX.com"
        description: Primary K2 DNS Ad Blocker
        server: k2-docker # The docker server that was configured
        container: pihole # The name of the container you'd like to conne>
        widget:
          type: pihole
          url: https://192.168.50.150
          version: 6
          key: "WEQ/TBjPvxYdQlo9A/4rRH1bXdD52wTz89nBgiJwAVw"
```

### Container Logs

![container log](https://github.com/user-attachments/assets/b8f91c4e-42eb-4b0c-808a-c3e96913550c)

### Browser Logs

![api error](https://github.com/user-attachments/assets/3e3e1f7b-8575-4c51-a89d-8df15ca0fe6f)

### Troubleshooting

I attempted to:
1. switch between a FQDN, the primary IP of the server that I always use to access Pihole, and the internal subnet IP.
2. Homepage and Pihole are both on the same docker network (proxy) as they are both using Traefik
3. Confirmed and changed the Pihole API token
4. Even added webserver.api.app_sudo: true to my Pihole container
