### DISCUSSION TITLE
Seeking Assistance - Nested Groups

### DISCUSSION THREAD

**Discussion by BBT-nZ** [gethomepage/homepage#5064] [Support] [answered]
### Description

Hey Folks,

Really could do with some help here :( after seeing all the amazing work you guys have shared.

For the life of me I'm unable to achieve the below config, this is how far I've managed to get.

![image](https://github.com/user-attachments/assets/a20fb0e4-c464-47bd-87ef-d89296e103fb)

### homepage version

v1.0.3

### Installation method

Other (please describe above)

### Configuration

```yaml
LXC (Proxmox)

settings.yml

providers:
openweathermap: KEYKEYKEY
weatherapi: weatherapiapikey

title: My Homepage

background: 
 image: /images/pexels-photo-1169754.jpeg
 opacity: 27 # 0-100
    #  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    #  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    #  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness

statusStyle: "dot"
useEqualHeights: true
theme: dark
language: en

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: false

layout:
  Media:
   style: row
   columns: 3
   useEqualHeights: false

  Calendar:
     header: false

Let me know, if services.yml is required as well and I'm happy to post that too. TIA :)
```

### Troubleshooting

Followed the layout settings on this URL:

https://gethomepage.dev/configs/settings/#layout
https://gethomepage.dev/configs/settings/#nested-groups

**Comment by chiragkrishna** [comment]
Remove
```yaml
useEqualHeights: true
```

**Reply by BBT-nZ** [reply]
nope, does not work unfortunately.

**Comment by chiragkrishna** [comment, marked as answer]
sorry my bad, i have replicated your setup
![Screenshot 2025-03-24 150812](https://github.com/user-attachments/assets/4b43093f-cf8d-4d7d-be31-8ca1fa35968e)

the way to do it is to create 3 groups in media group
Group A - Left
Group B - Middle
Group C - Right
in your case
settings.yml
```yaml
layout:
  Media:
   style: row
   columns: 3
    Group A:
      header: false
    Group B:
      header: false
    Group C:
      header: false
```
services.yml
```yaml
- Media:
  - Group A:
    - Radarr:
    - Lidarr:
    - Jellyfin:
    - SABnzbd:
  - Group B:
    - Calender:
    - Prowlarr:
    - Navidrome:
  - Group C:
    - Sonarr:
    - Jellyseerr:
    - Deluge:
```
