### DISCUSSION TITLE
Missing gitlab widget

### DISCUSSION THREAD

**Discussion by ionesculiviucristian** [gethomepage/homepage#5070] [Support]
### Description

Hi. I have added the gitlab widget like so:
```
- resources:
    cpu: true
    disk: "/"
    memory: true
- search:
    provider: "google"
    target: "_blank"
- openmeteo:
    cache: 5
    label: "Brașov"
    latitude: 45.657974
    longitude: 25.601198
    timezone: "Europe/Bucharest"
    units: "metric"
- gitlab:
    url: xxx
    key: xxx
    user_id: xxx
    fields: ["events", "issues", "merges", "projects"]
```
but on the homepage I see:

![image](https://github.com/user-attachments/assets/b1e26c63-6318-45b5-a709-c9c7089f31dc)

Other widgets show correctly. Had the same result with whatsupdocker widget as well.

### homepage version

v1.0.4 (6fbe080, Mar 16, 2025)

### Installation method

Docker

### Troubleshooting

Nothing to add at the moment.
