### DISCUSSION TITLE
[Feature Request] Ability to use env variables in yaml files

### DISCUSSION THREAD

**Discussion by ionesculiviucristian** [gethomepage/homepage#5071] [Feature Requests]
### Description

Hi. I have the situation in which my config is:
```
- Projects:
    - GitLab:
        href: "xxx"
        icon: "/icons/gitlab.png"
        widget:
          fields: ["events", "issues", "merges", "projects"]
          key: "${HOMPAGE_WIDGET_GITLAB_KEY}"
          type: "gitlab"
          url: "xxx"
          user_id: "${HOMPAGE_WIDGET_GITLAB_USER_ID}"
```
It would be nice to have this working as each user could set their own config without committing the token / ID 🤪.

**Comment by buffaloexpatbill** [comment]
This is supported. Just may need some different formatting. Take a look at https://github.com/gethomepage/homepage/discussions/5024

**Comment by ionesculiviucristian** [comment]
In this case is not working though:

```
    - Mailpit:
        container: "dev-mailpit-1"
        description: "Mailpit - email & SMTP testing tool with API for developers"
        href: "https://mailpit.localdev/"
        icon: "/icons/mailpit.ico"
        server: "my-docker"
        showStats: true
        widget:
          mappings:
            - field: "total"
              label: "Total"
            - field: "unread"
              label: "Unread"
          password: {{DEV_PASSWORD}}
          type: "customapi"
          url: "http://mailpit:8025/api/v1/messages"
          username: {{DEV_USER}}
```

It just keeps asking for basic auth but if I put the literal values, it works. And also checked for the env vars to be present and correct in the container (both quoted in the env file).
