### DISCUSSION TITLE
HomeAssistant widget 401 unauthorized error

### DISCUSSION THREAD

**Discussion by matteo-martinelli** [gethomepage/homepage#5074] [Support]
### Description

I am trying to use the Homeassistant widget of Homepage, but the error I receive back is always "401 - unauthorized". 
I followed throuble shooting steps as reported below, but unsuccessfully.
I really cannot figure it out what is the problem.

### homepage version

v1.0.4

### Installation method

Docker

### Configuration

```yaml
- HomeAssistant:
        href: https://homeassistant.my_root.it
        description: My home automation
        siteMonitor: https://homeassistant.my_root.it
        icon: si-homeassistant
        widget:
            type: homeassistant
            url: https://homeassistant.my_root.it
            key: {{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}
            custom:
                - state: sensor.entities_counter
```

### Troubleshooting

I tried several alternatives, such as testing the endpoint with postman or doing a request using curl from within the container, and they all work as expected. I also tried deleting cookies or opening the page from another browser from my usual Chrome, and there are no differences.

**Comment by shamoon** [comment]
Instead of just summarizing like that can you provide the actual results of each of the steps in the troubleshooting guide that’s linked above

**Reply by matteo-martinelli** [reply]
Sure: 
- Postman: 
![image](https://github.com/user-attachments/assets/f8a88d80-7fd8-4634-9f31-033bcc562d2b)

![image](https://github.com/user-attachments/assets/d7856a22-25f0-4747-a447-d9ff2f016b08)

**Reply by shamoon** [reply]
Have you ruled out any funny business with the key (like it’s not being correctly read into the container or special characters getting messed up)? And just making sure the url you redacted in the screenshots is exactly the same as the one in your config

**Reply by matteo-martinelli** [reply]
No, I did not. About special characters, I have very limited control about it since is Home Assistant the entity generating it. 

Moreover, I also made another "cross-test", where I used the key dedicated to another service (that I know is actually working) in the Homepage configuration for the widget. In doing it, I pasted the key directly in the yaml without even using the .env file, but the result is the same: the access in unauthorized for Homepage.

**Reply by shamoon** [reply]
Yea I dunno, 401 means it is rejecting the auth for some reason, maybe the home assistant logs will provide more insight

**Reply by matteo-martinelli** [reply]
Strange, since the same requests made from postman and curl, as reported above, work properly. 

In the following the log from HA: 
```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:136
integration: HTTP (documentation, issues)
First occurred: March 24, 2025 at 21:14:00 (277 occurrences)
Last logged: 22:44:25

Login attempt or request with invalid authentication from dynamic-adsl-***-***-***-***.***.****.**(***-***-***-***). Requested URL: '/api/template'. (None)
Login attempt or request with invalid authentication from dynamic-adsl-***-***-***-***.***.****.**(***-***-***-***). Requested URL: '/api/states/sensor.entities_counter'. (None)
Login attempt or request with invalid authentication from 10.0.0.1 (10.0.0.1). Requested URL: '/api/states/sensor.entities_counter'. (None)
Login attempt or request with invalid authentication from 10.0.0.1 (10.0.0.1). Requested URL: '/api/template'. (None)
```

I want to point out that the sensor "entities_counter" actually exists in my instance: 

![image](https://github.com/user-attachments/assets/5f4de824-6a3b-4d76-b932-71243819f4ed)

**Comment by anotheraccount1** [comment]
try editing your services.yaml home assistant stanza to replace the "api_key" with just "key"
no quotes on it.
I had the same problem, but by experimenting, i found that single fixed the 401 errors in the stats areas.

**Comment by ljhardy** [comment]
I have the same issue, this integration was working for quite a long time.  My services.yaml key, has always been "key".  Maybe this is due to a recent Homeassistant upgrade?  Mine only uses the default stuff, no custom sensors, and also works via CURL.

**Comment by ljhardy** [comment]
Any other ideas here?

**Reply by ljhardy** [reply]
Has anyone gotten anywhere on this one?  Should I open up an issue?

**Comment by projectfreak** [comment]
I also get the "401 unauthorized error" even though it works with CURL.
I'd also be interested in a solution.

**Comment by slavendam** [comment]
https://github.com/home-assistant/supervisor/issues/5045

This 401 error is connected with ingress session token I think, and there are other add-ons which uses e.g. web page with the same problem.

**Comment by ljhardy** [comment]
Not sure, that original Homeassistant issue was opened in April of 2024, the Homepage integration worked fine long after that.  It just stopped working a few releases ago.

**Reply by slavendam** [reply]
Try to open File editor in left panel, or directly this Homepage addon from Addon list. And after that check do you still have 401 error on home

**Reply by ljhardy** [reply]
This isn't an addon to Homeassistant.  It is configured on Homepage as a "service", with the Homeassistant URL and a long-lived access token generated on Homeassistant to call the API.

**Comment by DongleDangleDingle** [comment]
Is the widget working for anyone at the moment or down for everyone?

**Reply by buffaloexpatbill** [reply]
I haven't used the HomeAssistant widget yet as I haven't used HomeAssistant much yet, but I do have a HomeAssistant instance I can test with later.

**Reply by buffaloexpatbill** [reply]
I had to test with an entity that existed in my HomeAssistant environment (sensor.entities_counter did not), but it works for me. 
Tested first with key directly in services.yaml, then as an env variable without quotes, then with quotes.  All worked for me, though I did get a 401 error when I switched to using the env variable but had not yet recreated the container.

I would advise using the quotes around the env variable in the services.yaml regardless to be safe as well as recreating the container. Here is the working configuration I tested (I put it into a LAN category in my config).
```
- LAN:
    - HomeAssistant:
        href: http://192.168.1.56/:8123
        description: My home automation
        siteMonitor: http://192.168.1.56:8123
        icon: si-homeassistant
        widget:
          type: homeassistant
          url: http://192.168.1.56:8123
          key: "{{HOMEPAGE_VAR_HOMEASSISTANT_API_KEY}}"
          custom:
            - state: sensor.dryer_current_status
```
