### DISCUSSION TITLE
v1.1.0 broke PeaNUT custom API for some reason?

### DISCUSSION THREAD

**Discussion by ForsakenRei** [gethomepage/homepage#5079] [Support] [answered]
### Description

After upgrade to v1.1.0, my custom API of PeaNUT stop working without any config change.
![image](https://github.com/user-attachments/assets/cf09f6c9-2b04-4663-996d-6109075425dc)

PeaNUT v5.6.0 API output
```
{
  "battery.charge": 100,
  "battery.charge.low": "10",
  "battery.charge.warning": 20,
  "battery.mfr.date": "CPS",
  "battery.runtime": 1550,
  "battery.runtime.low": "300",
  "battery.type": "PbAcid",
  "battery.voltage": 26.2,
  "battery.voltage.nominal": 24,
  "device.mfr": "CPS",
  "device.model": "CP1500PFCRM1U",
  "device.serial": "BH5PS7000012",
  "device.type": "ups",
  "driver.name": "usbhid-ups",
  "driver.parameter.pollfreq": 30,
  "driver.parameter.pollinterval": 15,
  "driver.parameter.port": "auto",
  "driver.parameter.synchronous": "auto",
  "driver.version": "2.8.0",
  "driver.version.data": "CyberPower HID 0.6",
  "driver.version.internal": 0.47,
  "driver.version.usb": "libusb-1.0.26 (API: 0x1000109)",
  "input.voltage": 122,
  "input.voltage.nominal": 120,
  "output.voltage": 122,
  "ups.beeper.status": "enabled",
  "ups.delay.shutdown": "20",
  "ups.delay.start": "30",
  "ups.load": 23,
  "ups.mfr": "CPS",
  "ups.model": "CP1500PFCRM1U",
  "ups.productid": 601,
  "ups.realpower.nominal": 900,
  "ups.serial": "BH5PS7000012",
  "ups.status": "OL",
  "ups.test.result": "No test initiated",
  "ups.timer.shutdown": -60,
  "ups.timer.start": -60,
  "ups.vendorid": 764
}
```

It seems there is no API change from PeaNUT side and homepage didn't have any obvious change related to NUT? Container itself didn't throw any error. If I revert back to v1.0.4 everything works as expected.

### homepage version

v1.1.0

### Installation method

Docker

### Configuration

```yaml
- PeaNUT:
        icon: peanut
        href: https://peanut.shigure.gg
        widget:
          type: customapi
          url: http://mypeanut.domain.com/api/v1/devices/ups
          mappings:
            - field: ups.status
              label: Status
              format: text
              remap:
                - value: OL
                  to: Online
                - value: OB
                  to: On Battery
                - value: LB
                  to: Low Battery
                - any: true
                  to: Unknown
            - field: ups.load
              label: UPS Load
              format: percent
            - field: battery.runtime
              label: Runtime
              format: duration
            - field: battery.charge
              label: Charge
              format: percent
```

### Container Logs

homepage has been recreated
homepage  |    ▲ Next.js 15.2.3
homepage  |    - Local:        http://localhost:3000
homepage  |    - Network:      http://0.0.0.0:3000
homepage  | 
homepage  |  ✓ Starting...
homepage  |  ✓ Ready in 145ms

### Troubleshooting

Checked PeaNUT API and homepage docs, reverted to last release and the issue was resolved automatically.
