### DISCUSSION TITLE
Custom API Widget custom headers / API authorization error

### DISCUSSION THREAD

**Discussion by CAPS3** [gethomepage/homepage#5082] [Support]
### Description

I am running latest version of HomePage, [v1.1.1 (313835c, Mar 28, 2025)].
My services config contains the following widget for Xen Orchestra:

 ```   
  - XOA:
        description: XOA Appliance - VM Management
        href: http://<ip address>:<port>
        icon: xen-orchestra.png
        widget:
          type: customapi
          url: http://<IP address>:<port>/rest/v0/vms?fields=name_label%2Cpower_state&filter=power_state%3ARunning&limit=42
          refreshinterval: 10000
          method: GET
          headers:
            Cookie: authenticationToken=<API Token>
          requestBody:
          display: list
          mappings:
            - field: 
                0:
                  name_label
              format: text
            - field: 
                0:
                  power_state
              format: text
            - field: 
                1:
                  name_label
              format: text
            - field: 
                1:
                  power_state
              format: text
            - field: 
                2:
                  name_label
              format: text
            - field: 
                2:
                  power_state
              format: text
            - field: 
                3:
                  name_label
              format: text
            - field: 
                3:
                  power_state
              format: text
```
After the recent update to 1.1.1, this appears to have broken the custom header authentication token.
I am still able to query the API from the docker container via curl. Below is an example of the command I use and the reponse that is received. (Yes I know this is an array - I was using the dev image in the last 2 days and observed the same issue...)
```
/app # curl -b \
> authenticationToken=<redacted> \
> http://<ip address>:<port>/rest/v0/vms?fields=name_label%2Cpower_state&filter=power_state%3ARunning&limit=42
```
returns the output 
```
[
  {
    "name_label": "Windows 16 Domain Controller",
    "power_state": "Running",
    "href": "/rest/v0/vms/a949d91e-be78-8cf1-78c9-6e59b5ed642c"
  },
  {
    "name_label": "cerberus",
    "power_state": "Running",
    "href": "/rest/v0/vms/fc2f1a21-c02d-1073-1af5-c4fcf534071b"
  },
  {
    "name_label": "mailserver",
    "power_state": "Running",
    "href": "/rest/v0/vms/d3a41452-1fa3-52d6-a9e7-d307e35556bc"
  }
]
```
But in the webUI, it appears to have an API error saying 
"API Error: HTTP Error
URL: http://<ip address>:<port>/rest/v0/vms?fields=name_label%2Cpower_state&filter=power_state%3ARunning&limit=42
Response Data:
"Unauthorized"

Which suggests that the Custom Header is not been passed through?

I did not appear to have this issue with the previous version.
(I am also looking forward to the dynamic list working with this !)

I have confirmed that the API key is valid, and that this issue is occurring in the dev branch as well. 
I am unsure how to check using Chrome Browser dev tools if the payload being sent by Homepage contains the header - any assistance here would be appreciated. 

The XOA REST API docs can be found [here ](https://docs.xcp-ng.org/management/manage-at-scale/xo-api/) - An offical widget with feature parity with the proxmox widget would be _amazing_ :+1: 

Thank you for making this cool and free project!

### homepage version

v1.1.1 (

### Installation method

Docker

### Configuration

```yaml
- XOA:
        description: XOA Appliance - VM Management
        href: http://<ip address>:<port>
        icon: xen-orchestra.png
        widget:
          type: customapi
          url: http://<IP address>:<port>/rest/v0/vms?fields=name_label%2Cpower_state&filter=power_state%3ARunning&limit=42
          refreshinterval: 10000
          method: GET
          headers:
            Cookie: authenticationToken=<API Token>
          requestBody:
          display: list
          mappings:
            - field: 
                0:
                  name_label
              format: text
            - field: 
                0:
                  power_state
              format: text
```

### Container Logs

docker-compose logs -f                                                                                                                                      ✔ 
homepage  |    ▲ Next.js 15.2.3
homepage  |    - Local:        http://localhost:3000
homepage  |    - Network:      http://0.0.0.0:3000
homepage  | 
homepage  |  ✓ Starting...
homepage  |  ✓ Ready in 135ms

### Browser Logs

Failed to load resource: the server responded with a status of 401 (Unauthorized)Understand this errorAI
:3000/api/services/proxy?group=Bubbler&service=XOA&index=0&query=%7B%22refreshInterval%22%3A10000%7D:1 
            
            
           Failed to load resource: the server responded with a status of 401 (Unauthorized)Understand this errorAI
:3000/api/services/proxy?group=Bubbler&service=XOA&index=0&query=%7B%22refreshInterval%22%3A10000%7D:1 
            
            
           Failed to load resource: the server responded with a status of 401 (Unauthorized)Understand this errorAI
:3000/api/services/proxy?group=Bubbler&service=XOA&index=0&query=%7B%22refreshInterval%22%3A10000%7D:1 
            
            
           Failed to load resource: the server responded with a status of 401 (Unauthorized)

### Troubleshooting

Confirmed docker container is able to curl API endpoint with authentication Token successfully.

**Comment by shamoon** [comment]
I can’t test this right this second but I don’t exactly see a reason why as nothing has really changed here: https://github.com/gethomepage/homepage/compare/v1.0.4...v1.1.1

As far as looking at the payload, you can’t in the browser (intentionally) because it’s proxied. Perhaps the receiving api has logs that would be helpful?

**Reply by CAPS3** [reply]
Sooo, I had a look at XenOrchestra side - I wasn't able to see anything in the logs, or user audit logs that contains API REST response data.

I double-checked the API keys, and it looks like I had restored a backup copy of the services.yaml which contained an old API key...Sorry  for the headache!
I updated the API key and it worked. 


Strangely enough, I copied the same API key to the services.yaml for the homepage dev container, and it still gets the API error. 

Due to the recent changes being pushed to the main/latest branch (all I wanted was the Dynamic List feature so it could parse the json array response), I added a second widget for testing like so 
```
    - XOA2:
        description: XOA Appliance - VM Management
        href: http://<ip address>:<port>/
        icon: xen-orchestra.png
        server: cerberus
        widget:
          type: customapi
          url: http://<ip address>:<port>/rest/v0/vms?fields=name_label%2Cpower_state&filter=power_state%3ARunning&limit=42
          headers:
            Cookie: authenticationToken=AETcVgC8S21D5oV0q9Unh1NH7lK3ac-ELym5nFljbv4
          display: dynamic-list
          mappings:
            items:
            name: name_label
            label: power_state
```
and voilia
![image](https://github.com/user-attachments/assets/ce936c0f-c9a6-46ed-a62d-7c761be1375f)

So it appears my issue is resolved (at least on the main branch - I'm not worried about it not working on the dev branch :D) 

Put this one down to user error or incompetence.

Thanks again for all the effort you put into this project, and the quick response - Wishing you all the best!

(oh - for the wishlist, can we get an 'official' Xen Orchestra widget that looks pretty like the proxmox one :P ?!)

**Reply by CAPS3** [reply]
OK, I must be taking Crazy Pills.

Because I thought I'd solved it, I copied over the config from my dev branch container for Jellyfin and Qbitorrent Widgets to the "main" container.  

Low and behold, the issue popped back up again, so I undid the changes. Undoing the changes in the file (and saving) simply isn't enough to get it working again. In this case, I had to restart the container after removing the recently added config, and it was working again. 

So I added the Items back one at a time. 
Jellyfin widget seems fine, and plays the XOA is happy, but as soon as I add the Qbitorrent widget, the customAPI widget for XOA seems to get a 401 Access denied/ Unauthorised. 

The Qbitorrent Service item & widget that seems to be causing the issue:
```
    - Qbitorrent:
        description: Torrent Downloads
        href: http://<IP>:<port>/
        icon: qbittorrent.png
        server: cerberus
        widget:
          type: qbittorrent
          url: http://<ip>:<port>
          username: <qbit username>
          password: "<8 char numeric password>"
          enableLeechProgress: true # optional, defaults to false
```

The Qbitorrent IP and the XOA IP address are actually the same; only the port is different. (Same for the Jellyfin widget) - They all live on Truenas. 
Is it possible Qbitorrent widget is doing something it shouldn't in terms of setting an auth cookie? 

Sorry for the headache (again!).
