### DISCUSSION TITLE
v1 no longer works behind traefik

### DISCUSSION THREAD

**Discussion by pefoo** [gethomepage/homepage#5093] [Support] [answered]
### Description

I am running homepage behind traefik. For an unknown reason, this stopped working with version 1. 

The following docker-compose file contains an example of a working and a no longer working version. Please note that it assumes, that your network is able to resolve the service URLs. You can fake DNS responses using your hosts file. The exposed ports are used for reference. The real world deployment does not use exposed ports (thats the whole point of running a reverse proxy in the docker network)

As seen in the screenshot below, v1.1.1 behind traefik does not work. Accessing the page using the exposed port works. 

```
networks:
  backend-net:
    driver: bridge

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    healthcheck:
      test: traefik healthcheck --ping
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    command:
      - --ping=true
      - --log.level=INFO
      - --api.insecure=false
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.rule=Host('traefik.t.home.lan')
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.entrypoints=web
    networks:
      - backend-net

  homepage-working:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage-working
    hostname: homepage
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 3001:3000
    volumes:
      - ./homepage-0:/app/config/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage-0.t.home.lan`)
      - traefik.http.routers.homepage.entrypoints=web
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - backend-net

  homepage-broken:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-broken
    hostname: homepage
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 3002:3000
    volumes:
      - ./homepage-0:/app/config/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage1.rule=Host(`homepage-1.t.home.lan`)
      - traefik.http.routers.homepage1.entrypoints=web
      - traefik.http.services.homepage1.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - backend-net
```

![image](https://github.com/user-attachments/assets/250ba034-827d-41cf-846f-5c0e21599c3d)

Similarly, the health check for the newer image version does not longer work. 
```
$ docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS                             PORTS                                         NAMES
79144451ccda   ghcr.io/gethomepage/homepage:latest    "docker-entrypoint.s…"   23 seconds ago   Up 19 seconds (health: starting)   0.0.0.0:3002->3000/tcp, [::]:3002->3000/tcp   homepage-broken
15ee5a9097c3   ghcr.io/gethomepage/homepage:v0.10.9   "docker-entrypoint.s…"   23 seconds ago   Up 19 seconds (healthy)            0.0.0.0:3001->3000/tcp, [::]:3001->3000/tcp   homepage-working
96bd1f045cff   traefik:latest                         "/entrypoint.sh --lo…"   23 seconds ago   Up 19 seconds (healthy)            0.0.0.0:80->80/tcp, [::]:80->80/tcp           traefik
```

### homepage version

v1.1.1

### Installation method

Docker

### Configuration

```yaml
Default configuration. Nothing specified. Mapping just empty folders.
```

### Container Logs
```
$ docker logs homepage-broken
   ▲ Next.js 15.2.3
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 354ms
```

```
$ docker logs homepage-working 
Listening on port 3000
```

### Troubleshooting

seems not relevant
