### DISCUSSION TITLE
[Feature Request] Paperless-AI widget

### DISCUSSION THREAD

**Discussion by remussamoila** [gethomepage/homepage#5095] [General]
### Description

Is anybody interested in a widget for [Paperless-AI](https://clusterzx.github.io/paperless-ai/)?
Paperless-Ai is a companion of Paperless-ngx, an automated document analyzer using OpenAI API, Ollama and all OpenAI API compatible Services to automatically analyze and tag your documents.
It features: Automode, Manual Mode, Ollama and OpenAI, a Chat function to query your documents with AI, a modern and intuitive Webinterface.
It has an API available at its own address /api-docs/openapi.json
At the moment I am testing with a Google Cloud model: gemini-2.0-flash
I made a custom widget for the address http://xx.xx.xx.xx:port/api/processing-status
that returns the status, daily processed documents and last processed etc
 
```
        widget:
            type: customapi #http://<IP_address>:<ip_port>/api-docs/openapi.json
            url: http://<IP_address>:<ip_port>/api/processing-status
            refreshInterval: 10000 # optional - in milliseconds, defaults to 10s   
            headers:
                Authorization: Bearer <JWT_token> #JWT authentication token obtained from the /login endpoint. The token should be included in the Authorization header as "Bearer {token}".'
                x-api-key: <API_key> #This key can be generated or regenerated using the /api/key-regenerate endpoint
            method: GET
            mappings:
                - field: currentlyProcessing
                  label: Processing
                  format: text
                - field: lastProcessed.title
                  label: Last Processed
                  format: text
                - field: lastProcessed.processed_at
                  label: Last Processed Date
                  format: date                  
                - field: processedToday
                  label: Processed Today
                  format: number   
```
and the result
![image](https://github.com/user-attachments/assets/1e37045c-9ecb-4df7-990c-24e5c1f1001d)

Following Services and OpenAI API compatible services have been successfully tested:
Ollama
OpenAI
DeepSeek.ai
OpenRouter.ai
Perplexity.ai
Together.ai
VLLM
LiteLLM
Fastchat
Gemini (Google)
