### DISCUSSION TITLE
Pihole  6 (Docker tag 2025-2-26)

### DISCUSSION THREAD

**Discussion by banshee1971** [gethomepage/homepage#5099] [Support] [answered]
### Description

Cant's make the Widget work on Homepage
```
    - Pi-Hole:
        icon: pi-hole.png
        href: http://192.168.1.20:8080/admin/login
        widget:
          type: pihole
          fields: ["queries", "blocking", "blocked_percent", "gravity"]
          url: http://192.168.1.20:8080/admin/settings/api
          version: 6
          Key: **my_API_key_here**
```
Nothing's show on the fields. I also comment the "fields" .. and same result, no information pop-up
after some time, got API error on Homepage : API Error: Pi-Hole API Error

I test with Powershell the communication, and seem to work : 
```
$headers = @{ "X-API-Key" = "**my_API_key_here**" }
Invoke-WebRequest -Uri "http://192.168.1.20:8080/admin/settings/api" -Headers $headers -Method Get
```

got Status Code : 200 .. and SatusDescription : OK ...

### homepage version

1.1.1

### Installation method

Other (please describe above)

### Configuration

```yaml
Using Portainer to deploy this Docker image
```

### Troubleshooting

I test with Powershell the communication, and seem to work : 
```
```
$headers = @{ "X-API-Key" = "**my_API_key_here**" }
Invoke-WebRequest -Uri "http://192.168.1.20:8080/admin/settings/api" -Headers $headers -Method Get
```
The powershell test help me find that for that version of Pi-Hole, i need to use /admin/settings/api  ... /api only not working

I  try multiple variant, like : 
url: http://192.168.1.20:8080
url: http://192.168.1.20:8080/api
url: http://192.168.1.20:8080/admin/api
url: http://192.168.1.20:8080/admin/settings/api

all end-up with same result, no API communication
