### DISCUSSION TITLE
[Custom API] OPNSense Unbound Ad-Blocker Stats

### DISCUSSION THREAD

**Discussion by chiragkrishna** [gethomepage/homepage#5102] [General]
User Permisions Required:-  **Services: Unbound (MVC)**

```yaml
- Monitoring Services:
    - Unbound:
        icon: sh-unbound.png
        href: https://10.10.11.1:8443/ui/unbound/overview
        description: OPNSense Ad-Blocker
        widget:
          type: customapi
          url: https://10.10.11.1:8443/api/unbound/overview/totals/0
          username: "{{HOMEPAGE_VAR_OPNSENSE_KEY}}"
          password: "{{HOMEPAGE_VAR_OPNSENSE_SECRET}}"
          mappings:
            - field: total
              label: Total Queries
            - field: resolved.total
              label: Resolved
            - field: blocked.total
              label: Blocked
```

![Screenshot_20250331_094818](https://github.com/user-attachments/assets/d3e405fe-71ef-4ad9-a22b-c15e26dbefee)
