### DISCUSSION TITLE
Just wanted category icons, need help with layout

### DISCUSSION THREAD

**Discussion by Metal-Frog** [gethomepage/homepage#5108] [Support]
### Description

Hi,
I've just wanted to add category icons. But when I define the icons in the settings.yaml it leads to a changed layout. I wouldn't mind to configure the desired layout als0, but I couldn't get it as desired. 
The out-of-the box layout configured my service groups in three columns (see screenshot 1).
After adding the icons I got four columns.
So how can I have group icons and maintain the original layout??

This is what I did in the settings:
```
layout:
  Admin:
    icon: mdi-tools
  Anwendungen:
    icon: mdi-apps
  Zuhause:
    icon: mdi-home-automation
  Links:
    icon: mdi-link-variant
  Shopping:
    icon: mdi-cart
```

### homepage version

1.1.1

### Installation method

Docker

### Configuration

```yaml
layout:
  Admin:
    icon: mdi-tools
  Anwendungen:
    icon: mdi-apps
  Zuhause:
    icon: mdi-home-automation
  Links:
    icon: mdi-link-variant
  Shopping:
    icon: mdi-cart
```

### Troubleshooting

 
![1-before](https://github.com/user-attachments/assets/c9d72f1d-5246-4f69-bcfa-92f76df6d09a)
![2-after](https://github.com/user-attachments/assets/a06e87d6-5b27-423d-bbb5-5d8f662c8b1f)

**Comment by kevinruffus** [comment]
You've defined your bookmarks the same as your services.
Use the bookmarks.yaml to define those columns.

Remove
```
  Links:
    icon: mdi-link-variant
  Shopping:
    icon: mdi-cart
```
from your settings file and segment your bookmarks in the bookmarks file like this:
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Developer:
  - Github:
    - abbr: GH
      href: https://github.com/
      icon: github.png

- Server Docs:
  - HomePage Docs:
    - abbr: HP
      href: https://gethomepage.dev/
      icon: homepage.png

- DNS:
  - Namecheap:
    - abbr: NC
      href: https://www.namecheap.com/
      icon: namecheap.png

  - Cloudflare:
    - abbr: CF
      href: https://dash.cloudflare.com/login/
      icon: cloudflare.png

- SecOps:
  - Crowdsec:
    - abbr: CS
      href: https://app.crowdsec.net/security-engines/
      icon: crowdsec.png
```
