### DISCUSSION TITLE
[Feature Request] Dynamic List: Handle arrays in response

### DISCUSSION THREAD

**Discussion by xathon** [gethomepage/homepage#5115] [Feature Requests]
### Description

Currently, mappings of a `dynamic-list` only work as strings. It would be great to either be able to further transform them, or in some other way support the display of an array here without just concatenating the elements.

As an example, I'm getting this response from my Maloja API:
```
list": [
    {
      "time": 1743546725,
      "track": {
        "artists": [
          "Spiritbox",
          "Sam Carter"
        ],
        "title": "Yellowjacket",
        "album": {
          "artists": [
            "Spiritbox",
            "Sam Carter"
          ],
          "albumtitle": "Eternal Blue"
        },
        "length": 199
      },
      "duration": null,
      "origin": "client:multiscrobbler"
    },
    ...
]
```
My widget is defined as:
```
   - type: customapi
     url: https://maloja.example.com/apis/mlj_1/scrobbles?page=0&perpage=5
     display: dynamic-list
     mappings:
       items: list
       name: track.title
       label: track.artists
```
If the `artists` array only has one entry, everything is fine, but if it contains multiple entries, they are simply concatenated:

![image](https://github.com/user-attachments/assets/36f47d12-3543-41bd-93ed-8007d280102d)

### Other

It would of course be possible to write a small proxy api that handles these transformations, but I'd like to avoid that if possible.
