### DISCUSSION TITLE
Help setting up Beszel widget

### DISCUSSION THREAD

**Discussion by bluecasita** [gethomepage/homepage#5125] [Support] [answered]
### Description

First off, I am using Beszel and love it.  It does what it took me a week to build in Grafana, Prometheus, Node Exporter, etc.  What a great piece of software.  Highly recommended if you haven't tried it.

I use Homepage (gethomepage.dev) as my main dashboard.  It has a pre-built widget for Beszel, but for some reason, I just cannot get it to work.  (https://gethomepage.dev/widgets/services/beszel/). Not sure what I am doing wrong.  Here is the code snippet from my Homepage config.
 
>     - Beszel:
>         icon: beszel.svg
>         description: Beszel
>         widget:
>             type: beszel
>             url: http://192.168.100.100:8090
>             username: admin@domain.net
>             password: mypassword
>             systemId: <id copied from Systems table in PocketBase>
>             version: 2 

The error I get is: 
API Error: No items returned from beszel API

### homepage version

Latest

### Installation method

Docker

### Configuration

```yaml
- Containers:
    - AdGuard:
        icon: adguard-home.svg
        href: https://adguard.mydomain.net
        description: https://adguard.mydomain.net
        siteMonitor: http://192.168.100.100:4080
        widget:
            type: adguard
            url: http://192.168.100.100:4080
            username: admin
            password: WTE$Waersdf44

    - Beszel:
        icon: beszel.svg
        href: https://beszel.mydomain.net
        description: https://beszel.mydomain.net
        siteMonitor: http://192.168.100.100:8090
        widget:
            type: beszel
            url: http://192.168.100.100:8090
            username: beszel@mydomain.net
            password: XW342346kaT99
            systemId: a0345565jin5l5
            version: 2
```

### Container Logs

Nothing noted in the logs for Beszel at all

### Troubleshooting

Tried to setup the widget.  
Get the error.
Nothing noted in the logs.
