### DISCUSSION TITLE
Jdownloader - error decoding jdownloader API data

### DISCUSSION THREAD

**Discussion by barukh27** [gethomepage/homepage#5130] [Support] [answered]
### Description

Hi there!

I've a Jdownloader docker container behind Gluetun. It's working fine. I've connected this container with homepage but I got the error:  <jdownloaderProxyHandler> Error decoding jdownloader API data. The container can be seen by myjdownloader though.

What can be wrong?

Thanks in advance for your help.

### homepage version

v1.1.1 (313835c)

### Installation method

Docker

### Configuration

```yaml
- Jdownloader:
        icon: jdownloader
        href: http://XXX.XXX.X.XXX:5800
        server: portainer # The docker server that was configured
        container: jdownloader2 # The name of the container you'd like to connect
        widget:
         type: jdownloader
         username: user
         password: password
         client: portainer
         fields: ["downloadCount", "downloadTotalBytes","downloadBytesRemaining", "downloadSpeed"]
```

### Container Logs

[2025-04-04T15:06:58.862Z] error: <jdownloaderProxyHandler> Error decoding jdownloader API data. Data: (a text string)

[2025-04-04T15:06:58.875Z] error: <jdownloaderProxyHandler> Error decoding jdownloader API data. Data: (a different text string)/iewh

[2025-04-04T15:06:59.128Z] error: <jdownloaderProxyHandler> HTTP 500 communicating with jdownloader. Data: {

  "src" : "MYJD",

  "type" : "UNKNOWN"

}

[2025-04-04T15:06:59.151Z] error: <jdownloaderProxyHandler> HTTP 500 communicating with jdownloader. Data: {

  "src" : "MYJD",

  "type" : "UNKNOWN"

}

### Troubleshooting

docker exec homepage ping XXX.XXX.X.XXX:5800 gives an answer.
