### DISCUSSION TITLE
Two gluetun instances

### DISCUSSION THREAD

**Discussion by barukh27** [gethomepage/homepage#5132] [Support] [answered]
### Description

Hi there!,

I've have two gluetun instances running in two different hosts. One is monitored via portainer and the other via portainer_agent.
Each gluetun instance is giving its own endpoint IP. Both are different.

I've set up two gluetun widgets, one for each container, but I got the same info (IP...) from both of them.

I've located two different config.toml files.

[[roles]]
name = "homepage"
# Define a list of routes with the syntax "Http-Method /path"
routes = ["GET /v1/publicip/ip"]
# Define an authentication method with its parameters
auth = "none"

### homepage version

v1.1.1 (313835c)

### Installation method

Docker

### Configuration

```yaml
- Gluetun:
        icon: gluetun.png
        server: portainer # The docker server that was configured
        container: gluetun # The name of the container you'd like to connect
        widget:
         type: gluetun
         url: http://XXX.XXX.X.215:8000
         fields: ["public_ip", "region", "country"]

    - Gluetun:
        icon: gluetun.png
        server: portainer_agent # The docker server that was configured
        container: gluetun-nord # The name of the container you'd like to connect
        widget:
         type: gluetun
         url: http://XXX.XXX.X.206:8000
         fields: ["public_ip", "region", "country"]
```

### Troubleshooting

-
