### DISCUSSION TITLE
NPM on macvlan Unreachable from Homepage - NPM & Homepage on Unraid

### DISCUSSION THREAD

**Discussion by Postman67** [gethomepage/homepage#5136] [Support]
### Description

I've been having an issue with the NPM (NGINX Proxy Manager) erroring out. Both NPM & Homepage are running on the same Unraid machine in Docker containers. However, Homepage is utilizing a bridge while NPM is using a br0 on the same interface, therefore giving just NPM a different IP from Unraid.

Unraid + Homepage IP: 192.168.1.57
NPM IP: 192.168.1.81

It's possible that this _could just_ be a flaw with my Unraid container network config, as my other Bridge containers **also** fail to curl NPM. 

### homepage version

v1.1.1

### Installation method

Unraid

### Configuration

```yaml
- Services:
    - Unique Services:
        - NGINX Proxy Manager:
            icon: nginx-proxy-manager
            href: http://192.168.1.81:81/login
            description: NGINX Proxy Manager - WIDGET BROKEN
            widget:
                type: npm
                url: http://192.168.1.81:81
                username: {my-user}
                password: {my-pass}
```

### Container Logs

[2025-04-05T07:50:19.001Z] error: <httpProxy> Error calling http://192.168.1.81:81/api/tokens...
[2025-04-05T07:50:19.002Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.1.81:81
      at <unknown> (Error: connect EHOSTUNREACH 192.168.1.81:81) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.1.81',
    port: 81
  }
]
[2025-04-05T07:50:19.003Z] error: <npmProxyHandler> Error 500 logging into npm {"error":{"message":"Unknown error","url":"http://192.168.1.81:81/api/tokens","rawError":[500,{"errno":-113,"code":"EHOSTUNREACH","syscall":"connect","address":"192.168.1.81","port":81}]}}

### Browser Logs

http://192.168.1.57:3000/api/services/proxy?group=Unique+Services&service=NGINX+Proxy+Manager&index=0&endpoint=hosts 500 (Internal Server Error)

### Troubleshooting

![image](https://github.com/user-attachments/assets/46de25ef-dfc2-4f7b-9684-095cc7dd6f2a)
Top CLI is from the Homepage Container
Bottom CLI (Command Prompt) is from a Windows machine

All of them are on the same network 192.168.1.0/24
