### DISCUSSION TITLE
Two Unifi controllers not working

### DISCUSSION THREAD

**Discussion by TyShawn76** [gethomepage/homepage#5139] [Support] [answered]
### Description

I have two unifi Controllers I would like to monitor. I enter the first controller and everything works fine. I entered the config for the second controller and I do not see any data, I also don't have any errors either. I sent my info to a friend and he is seeing data but only has the single controller. I did try to comment out the first controller and that didn't help. 

### homepage version

v1.1.1

### Installation method

Docker

### Configuration

```yaml
- Network Group:
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
        description: AWS 
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
            username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
            password:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
            site: removed # optional
            ping: removed.net
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL_2}}"
        description: edited Controller
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL_2}}"
            username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
            password:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
            siteMonitor: removed.net
```

### Troubleshooting

changed settings 
recreated container
