### DISCUSSION TITLE
host validation fails when set to *

### DISCUSSION THREAD

**Discussion by kommandantredundant** [gethomepage/homepage#5141] [Support] [answered]
### Description

I am using homepage with a tailscale sidecar. I have set `HOMEPAGE_ALLOWD_HOSTS=*` but I still get a host validation error, when trying to access homepage via ts MagicDNS name.

### homepage version

:latest, cannot confirm version as I cannot access

### Installation method

Docker

### Configuration

```yaml
**compose.yml**

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    network_mode: service:ts-homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  ts-homepage:
    image: tailscale/tailscale:latest
    container_name: ts-homepage
    cap_add:
      - net_admin
    hostname: homepage
    environment:
      - TS_AUTHKEY=tskey-auth-xxx
      - TS_AUTH_ONCE=true
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_STATE_DIR=/var/lib/tailscale
    restart: always
    volumes:
      - /var/liv/tailscale:/var/lib/tailscale
      - ./serve:/config

**serve.json**
{
    "TCP": {
      "443": {
        "HTTPS": true
      }
    },
    "Web": {
      "${TS_CERT_DOMAIN}:443": {
        "Handlers": {
          "/": {
            "Proxy": "http://homepage:3000"
          }
        }
      }
    }
  }
```

### Container Logs

[2025-04-05T20:16:22.009Z] error: Host validation failed for: homepage._funny-name_.ts.net. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.

### Troubleshooting

I have previously set up homepage without a ts sidecar and it worked fine.
Adding the ts sidecar and access via the tailscale funny name I can see my dashboard for splitsecond before I get the _Host validation failed. See logs for more details._ error message. The log as stated aboce shows, I should add my domain to the variable. Adding that does not work. Bypassing host validation does not work either.
As far as I see, none of the troubleshooting steps help either.

I cannot tell, what the problem could be with my ts sidecar or my ts serve proxy...

Thanks in advance for any help!
