### DISCUSSION TITLE
Beszel widget needs restart of homepage to show correct information

### DISCUSSION THREAD

**Discussion by bentschrader** [gethomepage/homepage#5146] [Support] [answered]
### Description

The beszel widget shows the correct information only after a restart of homepage container.

![image](https://github.com/user-attachments/assets/a040f482-c28e-432d-a303-baf7d892243f)

Next day the widget shows only zeros as values.

### homepage version

v1.1.1 (313835c, 28. März 2025)

### Installation method

Docker

### Configuration

```yaml
- Beszel Monitoring:
            icon: /icons/beszel.png
            description: Administrationsportal
            href: https://beszel.public.domain
            server: docker-vm2
            container: beszel
            widget:
                type: beszel
                url: http://beszel.local.domain:8090
                username: myusername
                password: mypassword
                version: 2
```

### Troubleshooting

Because of the widget is working fine for a specific time, I assume that this is a reload or refreshing issue?

**Comment by shamoon** [comment]
Homepage does not cache the data from beszel, so perhaps you have some other layer between the two that is doing this, but you can easily test the api calls that homepage is making and see what beszel is reporting back

**Reply by bentschrader** [reply]
As far as I know there's no other layer, homepage should access the beszel container directly. As I described, the wigdet looks one day after the last restart of the homepage container as follows:

![image](https://github.com/user-attachments/assets/c78e9080-ec47-4c05-999e-376763afce47)

The api call 

`curl -L -k -u 'username:password' http://beszel.domain.local:8090/api/collections/systems/records`

gave me the following corresponding output:

`{"items":[],"page":1,"perPage":30,"totalItems":0,"totalPages":0}`

I guess this is not the right api call? Any suggestions? After restarting the homepage container once, my dashboard shows the correct values again ...

**Reply by shamoon** [reply]
After restarting does that api call you posted return correct values? If so that would suggest a beszel issue

**Reply by bentschrader** [reply]
Not it shows the same values.

**Reply by shamoon** [reply]
Sorry, no thats not the correct curl. You need to first

```
curl -L -k -d '{"identity":"YOUREMAIL","password":"YOURPASS"}' -H "content-type:application/json" http://localhost:8090/api/collections/_superusers/auth-with-password
```

```json
{"record":{"collectionId":"pbc_3142635823","collectionName":"_superusers","created":"2024-12-25 19:21:36.794Z","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyIsImV4cCI6MTc0NTQ0MDU0NiwiaWQiOiI0azY5MnMxaDd4cTQ2MDIiLCJyZWZyZXNoYWJsZSI6dHJ1ZSwidHlwZSI6ImF1dGgifQ.NoDtSKd4u6qiRbgkmfTF2-plAvT0bxK-Wl8cTDYjW5c"}
```

And then take the token and run

```
curl -L -k -H "Authorization:Bearer YOURTOKEN" -H "content-type:application/json" 'http://localhost:8090/api/collections/systems/records?page=1&perPage=500&sort=%2Bcreated'
```

```json
{"items":[{"collectionId":"2hz5ncl8tizk5nx","collectionName":"systems","created":"2024-12-25 19:22:09.668Z","host":"localhost","id":"fz72shw9454121c","info":{"h":"","c":0,"m":"","u":0,"cpu":0,"mp":0,"dp":0,"b":0,"v":""},"name":"local","port":"45876","status":"down","updated":"2024-12-25 19:22:09.670Z","users":["ak2d4q76817c7x0"]}],"page":1,"perPage":500,"totalItems":1,"totalPages":1}
```

**Comment by bentschrader** [comment]
Hi shamoon,

I tried it exactly as you wrote. For one day it runs with the correct results. I guess, that after one day the token gets invalid, so the result is 0.

`{"items":[],"page":1,"perPage":30,"totalItems":0,"totalPages":0}`

Could it be, that the first call where the token is created do not run each time when homepage is opened up? As I mentioned, each time I restart the homepage container, the widget shows the exact values ...

**Reply by shamoon** [reply]
As you can see, the token above does not include any expiration information therefore homepage does not set a duration on caching the token (if an API is providing an expiring token, it probably should). 

https://github.com/gethomepage/homepage/blob/767c1a54dd4458cfc4cff4edaa3f259652c7ea57/src/widgets/beszel/proxy.js#L28

Also the beszel docs dont mention an expiration time that I saw (or a way to set it). Regardless, if / when the token expires the beszel api should return a 403, triggering homepage to login again:

https://github.com/gethomepage/homepage/blob/767c1a54dd4458cfc4cff4edaa3f259652c7ea57/src/widgets/beszel/proxy.js#L75-L83

With debug enabled the above should be visible in the logs, which btw would probably have been helpful as the initial support template notes.

**Comment by bentschrader** [comment]
My homepage container runs on a Synology Diskstation DS220+. The problem is, that the terminal is limited in the length of a new command line. Even though I was I able to create a token (after installing curl using apk) it's not possible to fill the command line with the second api call - so I'm unfortunately not able to test it. I did turn on the debug log level but did not see any log entry regarding the beszel api calls ...

**Reply by daurpam** [reply]
I have the exact problem as @bentschrader, but a little weird. I have multiple beszel widgets for different systems but using the same beszel container (a unique url). One of those works but other doesn't:
![image](https://github.com/user-attachments/assets/25654ad1-c1fd-437f-bf3d-50945e82166c)

![image](https://github.com/user-attachments/assets/0587c48a-6ccf-4e03-851a-00d08429d614)

Some of the widgets declaration in services.yml:
```
- server1-beszel:
        icon: beszel.png
        href: https://my.com/system/server1
        widget:
          type: beszel
          fields: ["cpu", "memory", "disk", "network"]
          url: http://beszel.lan.local
          username: XXXXX
          password: XXXXX
          systemId: server1
          version: 2
- server2-beszel:
        icon: beszel.png
        href: https://my.com/system/server2
        widget:
          type: beszel
          fields: ["cpu", "memory", "disk", "network"]
          url: http://beszel.lan.local
          username: XXXX
          password: XXXX
          systemId: server2
          version: 2
```

Don't understand why works for a day more or less, and after that only one of those still working, the differences is there are in different tabs on homepage: 4 not working widgets on a tab, an one working widget on a differente tab. 

If I change passwor for superuser, is working for hours, later the issue come back again.
