### DISCUSSION TITLE
[Feature Request] Dockwatch widget

### DISCUSSION THREAD

**Discussion by hvmzx** [gethomepage/homepage#5156] [Feature Requests]
### Description

Interest check on Dockwatch, saw an already existing request made about a year ago, the project has moved forward a lot and is still being enhanced by the Notifiarr team very frequently which is great.

The PR is ready, tried it and it looks like this, but there is possibility to add more fields like the disk, ram, cpu ... basically all info from Dockwatch's overview stats.

![CleanShot 2025-04-08 at 01 16 44@2x](https://github.com/user-attachments/assets/9366cf75-b345-4831-b267-9d975d4f8c15)

**Comment by MrLyallCSIT** [comment]
Definitely interested in this. Moved away from watchtower fairly recently as was able to customise Dockwatch more

**Reply by hvmzx** [reply]
Same for me, Dockwatch is way better with devs constantly integrating new features, it's also very soon replacing Portainer for me that doesn't have any more use anymore.

If you want to use Dockwatch for now you can use this:
- remove the fields you don't need as you need to have 4 maximum per widget
- in url, of course use your own container_name and port
- replace {{HOMEPAGE_VAR_DOCKWATCH}} by your own API key

I personally divided it in 3 widgets so it can look like this, but the config I wrote down there is the generic one with everything :

![image](https://github.com/user-attachments/assets/14fb458c-71a8-47ba-bd08-3aed5f2af3ff)


```
    - Dockwatch:
        icon: dockwatch
        description: Container Manager/Updater
        server: docker
        container: dockwatch
        widget:
          type: customapi
          url: http://dockwatch:80/api/stats/overview
          refreshInterval: 10000 # in ms
          method: GET
          headers:
            X-Api-Key: {{HOMEPAGE_VAR_DOCKWATCH}}
          mappings:
            - field: response.status.running
              label: running
              format: number 
            - field: response.status.stopped
              label: stopped
              format: number 
            - field: response.status.total
              label: total
              format: number 
            - field: response.health.healthy
              label: healthy
              format: number 
            - field: response.health.unhealthy
              label: unhealthy
              format: number 
            - field: response.health.unknown
              label: unknown
              format: number 
            - field: response.updates.uptodate
              label: up to date
              format: number 
            - field: response.updates.outdated
              label: outdated
              format: number 
            - field: response.updates.unchecked
              label: unchecked
              format: number 
            - field: response.usage.disk
              label: disk
              format: bytes 
            - field: response.usage.cpu
              label: cpu
              format: percent 
            - field: response.usage.memory
              label: memory
              format: percent 
            - field: response.usage.netIO
              label: netIO
              format: bytes
```
