### DISCUSSION TITLE
Nested layouts break widgets "Unknown proxy service type"

### DISCUSSION THREAD

**Discussion by t3chguy** [gethomepage/homepage#5157] [Support] [answered]
### Description

Before

![image](https://github.com/user-attachments/assets/594c8b3b-39cd-4a16-89df-14bbdd6a8324)

After

![image](https://github.com/user-attachments/assets/16cdc438-369e-4710-b456-d82606327026)

### homepage version

v1.1.1 (313835c, Mar 28, 2025)

### Installation method

Docker

### Configuration

Broken configuration:

```yaml
- Auth:
  - Main:
    - Authentik:
        description: Authentication provider
        href: https://URL
        icon: authentik
        server: phoenix
        container: authentik
        widget:
          type: authentik
          url: https://URL
          key: KEY

  - Workers:
    - Authentik Worker:
        icon: authentik
        server: phoenix
        container: authentik_worker

    - Authentik LDAP:
        icon: authentik
        server: nexus
        container: authentik-ldap

    - Authentik Outpost:
        icon: authentik
        server: nexus
        container: authentik-outpost
```

Working configuration:

```yaml
- Auth:
  - Authentik:
      description: Authentication provider
      href: https://URL
      icon: authentik
      server: phoenix
      container: authentik
      widget:
        type: authentik
        url: https://URL
        key: KEY

  - Workers:
    - Authentik Worker:
        icon: authentik
        server: phoenix
        container: authentik_worker

    - Authentik LDAP:
        icon: authentik
        server: nexus
        container: authentik-ldap

    - Authentik Outpost:
        icon: authentik
        server: nexus
        container: authentik-outpost
```

### Container Logs

```
[2025-04-08T17:22:11.948Z] debug: <servicesProxy> Unknown proxy service type: undefined
```

### Browser Logs

```
GET https://dash.bit.ovh/api/services/proxy?group=Main&service=Authentik&index=0&endpoint=login 403 (Forbidden)
```

### Troubleshooting

N/A
