### DISCUSSION TITLE
I want to hide the right scroll bar,I've looked through the docs and discussions, but I can't seem to find anything helpful. If somebody could let me know how to do this or if such a feature doesn't exist, that would be great.

### DISCUSSION THREAD

**Discussion by asukasu** [gethomepage/homepage#5168] [Support]
### Description

![Screenshot_2025-04-12-11-25-37-406_com android chrome-edit_1744428408096](https://github.com/user-attachments/assets/fa66dafb-c3e9-4c1c-8b34-20484205e6f3)

### homepage version

v1.1.1

### Installation method

Docker

### Troubleshooting

I want to hide the right scroll bar,I've looked through the docs and discussions, but I can't seem to find anything helpful. If somebody could let me know how to do this or if such a feature doesn't exist, that would be great.

**Comment by owennewo-dev** [comment]
Put this in your `custom.css` file.
```css
div::-webkit-scrollbar {
  width: 0; /* Hides the scrollbar for specific elements */
  background: transparent;
}
```
