### DISCUSSION TITLE
Calendar widget off by 1 day for repeating events

### DISCUSSION THREAD

**Discussion by Azmodeszer** [gethomepage/homepage#5170] [Support]
### Description

https://github.com/gethomepage/homepage/discussions/3730 This is still an issue. Repeating events are offset by one day into the future by the widget.

### homepage version

v1.1.1 (313835c, Mar 28, 2025)

### Installation method

Docker

### Configuration

```yaml
- Calendar:
        widget:
          type: calendar
          view: monthly
          firstDayInWeek: monday
          timezone: Europe/Vienna
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/<email>/private-<blahblah>/basic.ics
              color: pink
```

### Troubleshooting

-
