### DISCUSSION TITLE
Emby widget counts multiple versions of movies and episodes as separate entries

### DISCUSSION THREAD

**Discussion by dinosmm** [gethomepage/homepage#5171] [Support]
### Description

As it's my first post here, first I want to thank you for this wonderful software.
---

The Emby widget reports counts incorrectly. If I have a movie in both 4K and 1080p, it counts both files as separate movies, so the total movie count is significantly higher than it should be. Same for episodes with multiple versions.

Is this just how the Emby API reports things, and is there anything that can be done on the homepage side? Or should this be a question for Emby support?

### homepage version

1.1.1 (313835c)

### Installation method

Docker

### Configuration

```yaml
Movies, TV Series, Documentaries:
          icon: /icons/emby.png
          href: https://domain.com
          description: Emby
          siteMonitor: https://domain.com/web/index.html#!/home
          widget:
            type: emby
            url: https://domain.com
            key: APIkey
            enableBlocks: true
            enableUser: true
            showEpisodeNumber: true
```

### Container Logs

Unsure if any are relevant, if they are please would you let me know what to grep in there and I will provide them.

### Browser Logs

Unsure if any are relevant, if they are please would you let me know what to grep in there and I will provide them.

### Troubleshooting

I have followed the standard instructions for the Emby widget, there don't seem to be any further descriptions of potential issue mitigations such as this one.
