### DISCUSSION TITLE
API call port hardcoded?

### DISCUSSION THREAD

**Discussion by MPHxxxLegend** [gethomepage/homepage#5176] [Support]
### Description

Hi guys,

I think I am stuck with troubleshooting, I am running PiHole as a container.
Have mapped port 8082 to 80, I can access the Pihole website but I can't get the widget to work.
The gethomepage container is running at 10.20.20.3 at site A and the Pihole container at site B is running at 10.42.0.11
There is no FW or other blocking in between, I have tested everything.
As the gethomepage log shows, it is still trying to call the API via port 80 as I have configured it to use port 8082 via the configuration.

Thx for the hints

### homepage version

v1.1.1

### Installation method

Docker

### Configuration

```yaml
- Pi-Hole RPi-3B:
    href: http://10.42.0.11:8082/admin
    icon: pi-hole.svg
    widget:
      type: pihole
      url: http://10.42.0.11:8082
      version: 6
      key: "FTLCONF_webserver_api_password"


Docker-compose.yml
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "bridge"
    hostname: pihole-container-sec
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'Europe/Vienna'
      FTLCONF_webserver_api_password: "***************+"
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - pi-hole:/etc/pihole
      - pi-hole-dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
volumes:
  pi-hole:
    name: pi-hole
    external: true
  pi-hole-dnsmasq:
    name: pi-hole-dnsmasq
    external: true
```

### Container Logs

[2025-04-14T19:40:10.751Z] error: <piholeProxyHandler> Error calling Pi-Hole API: 500. Data: { error: [Object] }
[2025-04-14T19:47:00.904Z] error: <httpProxy> Error calling http://10.42.0.11/api/stats/summary...
[2025-04-14T19:47:00.905Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.42.0.11:80
      at <unknown> (Error: connect ECONNREFUSED 10.42.0.11:80) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.42.0.11',
    port: 80
  }
]
[2025-04-14T19:47:00.906Z] error: <piholeProxyHandler> Error calling Pi-Hole API: 500. Data: { error: [Object] }
[2025-04-14T20:00:53.584Z] error: <piholeProxyHandler> Error calling Pi-Hole API: 400. Data: {"error":{"key":"bad_request","message":"Bad request","hint":"The API is hosted at pi.hole/api, not pi.hole/admin/api"},"took":0.00035381317138671875}

### Troubleshooting

nothing relevant
