### DISCUSSION TITLE
[Feature Request] Support for Woodpecker CI

### DISCUSSION THREAD

**Discussion by APT37** [gethomepage/homepage#5179] [Feature Requests]
### Description

Support for the Woodpecker CI API.

- Running Tasks
- Queued Tasks
- More?

### Other

Since I do not know much about JavaScript, all I can provide is my custom API configuration:

![image](https://github.com/user-attachments/assets/b3c6ae55-5869-4d00-9a81-3d223b93a6eb)

```yaml
    - Woodpecker CI:
        icon: woodpecker
        description: Pipeline Queue
        href: https://ci.host/admin/queue
        siteMonitor: https://ci.host/
        widget:
          type: customapi
          url: https://ci.host/api/queue/info
          refreshInterval: 5000
          headers:
            Accept: application/json
            Authorization: Bearer ey...
          mappings:
            - label: Running
              field:
                stats: running_count
            - label: Pending
              field:
                stats: pending_count
```
