### DISCUSSION TITLE
Can't get Navidrome widget to work

### DISCUSSION THREAD

**Discussion by dacampsss** [gethomepage/homepage#5181] [Support]
### Description

I'm using Navidrome with the system package (Ubuntu 22.04 LTS) provided by Navidrome itself, running it through a Caddy reverse proxy and my own keys/cert generated by LEGO. However, any URL I try I get an "API Error Information", and ECONNREFUSED error in the request. I tried both a MD5 token that is username+salt and a MD5 token that is password+salt, but neither do work. When I try a curl in my ssh, all I get is the following message:

```
<subsonic-response xmlns="http://subsonic.org/restapi" status="failed" version="1.16.1" type="navidrome" serverVersion="0.55.2 (a057a680)" openSubsonic="true"><error code="10" message="missing parameter: &#39;v&#39;"></error></subsonic-response>
```

But I wasn't able to figure out what is this "v" parameter, and as I know, it should be in the request itself, i.e. in this application code. Below, there is my services.toml's service:

```
- Navidrome:
        href: [external_url:external_port]
        description: Biblioteca musical
        icon: navidrome.webp
        widget:
          type: navidrome
          url: [internal_url:internal_port] # with these I can at least have a response with the curl command
          user: [myuser]
          token: [MD5(username+salt)]
          salt: [my-salt]
```

### homepage version

v1.1.1 (313835c, Mar 28, 2025)

### Installation method

Docker

### Troubleshooting

PING domain.tld (94.130.220.166): 56 data bytes
64 bytes from [ipaddress]: seq=0 ttl=63 time=0.429 ms
64 bytes from [ipaddress]: seq=1 ttl=63 time=0.492 ms
64 bytes from [ipaddress]: seq=2 ttl=63 time=0.284 ms
