### DISCUSSION TITLE
Missing config files in docker swarm mode deployment

### DISCUSSION THREAD

**Discussion by snowy-jaguar** [gethomepage/homepage#5186] [Support]
### Description

I'm trying to deploy homepage via docker swarm but when I go to deploy I only get 4 files:
```
snowy@janus:~$ ls -a /mnt/omnipool/docker/homepage/
.  ..  kubernetes.yaml  logs  settings.yaml
snowy@janus:~$
```
My compose service stack is
```yml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homepage:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.snowyjaguar.xyz
      - HOMEPAGE_VAR_PORTAINER_IP=${PORTAINER_IP}
      - HOMEPAGE_VAR_PORTAINER_PORT=${PORTAINER_PORT}
      - HOMEPAGE_FILE_PORTAINER_API_KEY=/run/secrets/portainer_api_key
      - HOMEPAGE_VAR_PVE_PORT=${PROXMOX_VE_PORT}
      - HOMEPAGE_VAR_PVE_VEROANDI_IP=${PVE_VEROANDI_IP}
      - HOMEPAGE_VAR_PVE_URD_IP=${PVE_URD_IP}
      - HOMEPAGE_VAR_PVE_SKULD_IP=${PVE_SKULD_IP}
      - HOMEPAGE_FILE_PVE_USER=/run/secrets/proxmox_api_user
      - HOMEPAGE_FILE_PVE_PASSWORD=/run/secrets/proxmox_api_password
    secrets:
      - portainer_api_key
      - proxmox_api_password
      - proxmox_api_user
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.homepage.rule=Host(`homepage.snowyjaguar.xyz`)
        - traefik.http.routers.homepage.entrypoints=websecure
        - traefik.http.routers.homepage.tls.certresolver=letsencrypt
        - traefik.http.services.homepage.loadbalancer.server.port=3000
        - traefik.http.routers.homepage.ruleSyntax=v3
      placement:
        constraints:
          - node.role == manager
      replicas: 1

volumes:
  homepage:
    external: true  # Assumes you created this volume in Portainer or via CLI

networks:
  traefik:
    external: true  # Assumes your traefik network is already created

secrets:
  portainer_api_key:
    external: true
  proxmox_api_password:
    external: true
  proxmox_api_user:
    external: true
```

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
I don't have any configuration set yet as most of the configuration files have not been created.
```

### Container Logs

```
   ▲ Next.js 15.2.3
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000
 ✓ Starting...
 ✓ Ready in 461ms
settings.yaml was copied to the config folder
[2025-04-17T19:14:24.849Z] info: kubernetes.yaml was copied to the config folder
```

### Troubleshooting

- Deleted the homepage stack, service and container
- Deleted all of the files in the homepage volume
- Re-Created the homepage stack
