### DISCUSSION TITLE
HELP - I've never seen my homepage

### DISCUSSION THREAD

**Discussion by bryanembley** [gethomepage/homepage#5187] [Support]
### Description

No matter what I put in my settings.yaml file, I get "Application error: a client-side exception has occurred while loading <serverIP> (see the browser console for more information)."

I cannot even tell for sure that my container is working, let alone start customizing stuff. Is there a really basic settings file where I can specify the HOMEPAGE_ALLOWED_HOSTS and at least get a page to load so that I can begin to visualize whether I even want to keep trying to use homepage?

### homepage version

1.1.1

### Installation method

Docker

### Configuration

```yaml
My current settings.yaml

Although I have tried it with just the homepage allowed IP and still get the same error.

---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

color: gray
title: Homepage
headerStyle: underlined
hideVersion: false
target: _self
showStats: true
statusStyle: "dot"

layout:
  Management:
    style: row
    columns: 3
    icon: mdi-server
  File Sharing:
    style: row
    columns: 3
    icon: mdi-folder-multiple-impage
  Apps:
    style: row
    columns: 3
    icon: mdi-apps

HOMEPAGE_ALLOWED_HOSTS=172.16.14.101:3000
```

### Container Logs

[_homepage_logs.txt](https://github.com/user-attachments/files/19801509/_homepage_logs.txt)

### Browser Logs

I don't know how to find these.

### Troubleshooting

I cannot get far enough for any of the troubleshooting steps to even apply to me.
