### DISCUSSION TITLE
settings.yaml not being applied

### DISCUSSION THREAD

**Discussion by roughnecks** [gethomepage/homepage#5191] [Support]
### Description

Hello.
I just installed homepage via docker. Whatever I change in `settings.yaml` isn't picked up by the site.

### homepage version

v1.1.1 (313835c, Mar 28, 2025)

### Installation method

Docker

### Configuration

```yaml
This is current setting.yaml file content


cat config/settings.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

theme: dark
color: gray  # Set colour to gray to enable `dracula` theme from `custom.css` to be enabled by default
cardBlur: xl
headerStyle: clean
```
```


### Container Logs

```
cat config/logs/homepage.log
[2025-04-18T11:03:08.953Z] info: kubernetes.yaml was copied to the config folder
[2025-04-18T11:24:41.224Z] info: docker.yaml was copied to the config folder
[2025-04-18T11:24:41.230Z] info: services.yaml was copied to the config folder
[2025-04-18T11:24:41.231Z] info: bookmarks.yaml was copied to the config folder
[2025-04-18T11:24:41.253Z] info: widgets.yaml was copied to the config folder
[2025-04-18T11:24:41.254Z] info: custom.css was copied to the config folder
[2025-04-18T11:24:41.258Z] info: custom.js was copied to the config folder
```

### Browser Logs

no error whatsoever in browser's console

### Troubleshooting

What I already did:
1) Used browser's incognito-mode and refreshed via the arrow in homepage and with CTRL+F5
2) restarted docker after every change to settings.yaml
3) ensured that:
`docker exec homepage cat /app/config/settings.yaml`
is the same as the local one inside config/ dir
4) tried changing other config files, like the bookmark one and that change gets applied successfully.
