### DISCUSSION TITLE
White flash (FOUC?) when homepage loads

### DISCUSSION THREAD

**Discussion by AlexDiego123** [gethomepage/homepage#5192] [Support] [answered]
### Description

I noticed that when homepage loads there's a brief white flash (white background), is there a way to remove this? I'm using homepage as my browser's (Microsoft Edge) new page but it's very annoying to see that white flash.

### homepage version

v1.1.1 (313835c, Mar 28, 2025)

### Installation method

Docker

### Configuration

```yaml
settings.yaml:                                                                   
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Home Lab
description: Welcome
language: en
disableCollapse: true
target: _self
cardBlur: sm
background:
  image: /images/wallpaper.png
headerStyle: boxedWidgets
statusStyle: "dot"
layout:
  Services:
    style: row
    columns: 4
quicklaunch:
  provider: google
  searchDescriptions: true
  showSearchSuggestions: true
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
```

### Container Logs
```
   ▲ Next.js 15.2.3
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 329ms
```

### Browser Logs
```
framework-bbeeca9707659ffa.js:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
```

### Troubleshooting

Not relevant

**Comment by wispborne** [comment]
A workaround for this is to use `config/custom.css` and add something like:
```css
body {
  background-color: #1e293b;
}
```
Rather than a blinding white flash, it'll flash whatever dark color you enter.

**Reply by jayh1** [reply]
I'm having the same issue and unfortunately changing the config/custom.css just doesn't work for me.  I'm sure I'm doing something incorrectly.  Do I have to add anything additional to my settings.yaml to use the custom.css?  I've searched and can't seem to find anything that references adding configuration that enables custom.css.  

I understand from reading a few posts that just putting the code you suggested into custom.css should work.  The .css is valid, I've restarted the container (even the host), and used different browsers.  Nothing so far seems to work.  I do have the theme and color set in settings.yaml.  This started, I believe, around version 1.4.1.

Thanks in advance.

**Reply by wispborne** [reply, marked as answer]
@jayh1 It works in v1.4.1, I just tested. I believe that PR #5611 by @shamoon broke custom.css's background-color, meaning that it is no longer respected on load and the white flash is back.

I just retested v1.4.2 and can confirm that that's where the white flash happens even with 
```css
body {
  background-color: #1e293b;
}
```

in `custom.css`, but it does NOT happen in v1.4.1. The white flash happens in 1.4.3 as well.

---
tldr;
To avoid getting a white flash before your dark theme loads, add the above css to your `custom.css` AND revert to Homepage v1.4.1.
