### DISCUSSION TITLE
"Host validation failed" even when host is in the environment variables (HOMEPAGE_ALLOWED_HOSTS)

### DISCUSSION THREAD

**Discussion by Frenchfrench** [gethomepage/homepage#5196] [Support] [answered]
### Description

Hi !
I'm encountering some issues with homepage, as my domain name is refused as an allowed host even if it is enabled in the docker compose file. At first it wasn't, I added it.
(note : I censored my domain name below)

Here's what I've tried so far :
- adding my domain name to the docker compose
- recreating the container (`docker compose down && docker compose up --force-recreate`)

Thanks for your help !

### homepage version

1.1.1

### Installation method

Docker

### Configuration

```yaml
Docker compose :
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS:g*************s.org
```

### Container Logs

`[2025-04-19T08:09:53.677Z] error: Host validation failed for: g*************s.org. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.`

### Troubleshooting

I tried to do what was advised here :
[https://github.com/gethomepage/homepage/discussions/4927](https://github.com/gethomepage/homepage/discussions/4927)

**Comment by buffaloexpatbill** [comment]
I re-checked my configuration (in my case it is specified in .env file, which would override the environment section of a compose file). At least with my local network apache reverse proxy, I only need the host ip plus port that the domain points to even when I use subdomain.domain to reverse proxy to that host:ip.
So HOMEPAGE_ALLOWED_HOSTS=192.168.1.141:3000  is working for connections using 192.168.1.141:3000 directly as well as my subdomain.domain using 192.168.1.141:3000 through reverseproxy.
You can add ip:port as a secondary entry, would just use a comma with no space between the entries, and be sure to recreate the container after the change.

**Reply by Frenchfrench** [reply]
Thank you for your answer, I did what you said the issue persists.

I was expecting this as [the docs](https://gethomepage.dev/installation/#homepage_allowed_hosts) say that :

> `localhost:3000` and `127.0.0.1:3000` are always included

**Comment by shamoon** [comment]
As was said above, be sure you are re-creating, not just restarting when changing this. The setting in general works fine, so this is definitely a configuration issue. And I assume you are but make sure youre copying the exact URL(s) listed in the logs

**Comment by Frenchfrench** [comment, marked as answer]
Solved, thanks for your help ! The issue was a syntax error : I put a hyphen before HOMEPAGE_ALLOWED_HOSTS variable,  and no space after the colon ; here's the correct docker compose :

```
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: g*************s.org
#    ^                       ^
```
