### DISCUSSION TITLE
[Feature Request] : Support for multiple service widgets on docker labels

### DISCUSSION THREAD

**Discussion by sylv3rblade** [gethomepage/homepage#5201] [Feature Requests]
### Description

```
  # compose.yml entry for peanut
  peanut:
    image: brandawg93/peanut:latest
    container_name: PeaNUT
    restart: unless-stopped
    profiles: [monitoring]
    env_file: .env.peanut
    volumes:
      - ./container_data/peanut:/config
    ports:
      - 8082:8082
    networks:
      - reverse_proxy
    labels:
      com.centurylinklabs.watchtower.enable: true
      homepage.group: Services
      homepage.name: UPS Monitor
      homepage.icon: peanut.svg
      homepage.href: http://peanut.homelab
      homepage.weight: 2
      homepage.widgets[0].type: peanut
      homepage.widgets[0].key: ups-main
      homepage.widgets[1].type: peanut
      homepage.widgets[1].key: ups-network
```

I have setup a PeaNUT service to monitor my 2 UPS but I have to remember which is which, is there a way to add a label?  or is there a way to setup multiple services via docker labels so i dont have to go with manually adding them to services.yaml ie

```
# services.yaml entry for 2 separate services, is there a way to convert this to a docker label so we end up with the same result?
- Services:
 - UPS-Main:
      icon: peanut.svg
      widget: 
         type: peanut
         key: ups-main 
 - UPS-Network
      icon: peanut.svg
      widget: 
         type: peanut
         key: ups-main 
```

![Screenshot 2025-04-21 at 2 24 29 PM](https://github.com/user-attachments/assets/d12abbc1-9cb3-4554-957b-da7b9f6c9835)

i tried making the homepage label an array but it doesnt work ie 
```
homepage[0].group: Services
```
