### DISCUSSION TITLE
Resource Information Widget shows host information not container

### DISCUSSION THREAD

**Discussion by sinusvonan** [gethomepage/homepage#5205] [Support]
### Description

Widgets -> Information Widgets -> Resources
> The cpu and memory resource information are the container's usage while [glances](https://gethomepage.dev/widgets/info/glances/) displays statistics for the host machine on which it is installed.

If I create an Information Widget like this:
```yaml
- resources:
    label: System
    cpu: true
    memory: true
```
it shows the exact same values as the glances widget:
```yaml
- glances:
    url: http://ip:port
    cpu: true 
    mem: true 
```
and if I open glances in terminal, it also shows the same cpu and memory usage.

The docs should be updated, since it doesn't seem to show the container's usage?

(Also the glances information widget and glances service widget update way slower than the Resource Information Widget)

### homepage version

v1.1.1

### Installation method

Docker

### Troubleshooting

- Create Resource Information Widget
- Create Glances Information Widget
- Create Glances Service Widget
- Open Glances in terminal
- compare all values (cpu usage ~7%)
- start a heavy task
- compare all values (cpu usage ~98%)
