### DISCUSSION TITLE
[Feature Request] Pangolin Widget

### DISCUSSION THREAD

**Discussion by begunfx** [gethomepage/homepage#5213] [Feature Requests] [answered]
### Description

Please consider adding Pangolin as a widget to gethomepage.
`https://github.com/fosrl/pangolin?tab=readme-ov-file`

**Comment by DmitryArkh** [comment]
Up!
Would be great to have a status indicator for a specific site and for Pangolin health status as well.

**Comment by Node815** [comment]
I have made some progress with this, but it's not rendering the stats  right now.    After creating the API Key, I recorded it in a safe place then through the Swagger API provided by Pangolin, I used the following section:
<img width="1550" height="621" alt="image" src="https://github.com/user-attachments/assets/5b4d0def-c405-4648-9052-d58356156143" />

After executing it, it returned the results in the Response body.  

```
{
  "data": {
    "sites": [
      {
        "siteId": 11,
        "niceId": "nippy-bandy-bandy",
        "name": "Proxmox",
        "pubKey": "######REDACTED####=",
        "subnet": "100.89.128.8/30",
        "megabytesIn": 186.72592163085938,
        "megabytesOut": 1186.707592010498,
        "orgName": "Master",
        "type": "newt",
        "online": true
      },
      {
        "siteId": 12,
        "niceId": "beneficial-spea-hammondii",
        "name": "Racknerd",
        "pubKey": null,
        "subnet": "0.0.0.0/0",
        "megabytesIn": null,
        "megabytesOut": null,
        "orgName": "Master",
        "type": "local",
        "online": false
      }
    ],
    "pagination": {
      "total": 2,
      "limit": 1000,
      "offset": 0
    }
  },
  "success": true,
  "error": false,
  "message": "Sites retrieved successfully",
  "status": 200
}
```
Since the response is showing the mappings, I tried the following below:
```
  widget:
          type: customapi
          url: https://api.yoursite.com/v1/org/primary/sites?limit=1000&offset=0
          refreshInterval: 30000 # optional, refresh every 30s
          method: GET
          headers:
             Authorization: Bearer APIKEYAPIKEYetc..        
        display: list
        dataPath: data.sites
          mappings:
            - field: name
              label: Name
            - field: niceId
              label: ID
            - field: orgName
              label: Org
            - field: subnet
              label: Subnet
            - field: online
              label: Online
              format: boolean # shows green/red
            - field: megabytesIn
              label: MB In
              format: number
            - field: megabytesOut
              label: MB Out
              format: number
                 
```
This is what it returns:
<img width="631" height="300" alt="image" src="https://github.com/user-attachments/assets/96ee702c-7f20-4f03-b4c8-390f931a28dd" />

This is as far as I've gotten and have hit the brick wall on it not populating the data properly, I hope this helps inspire some further discussion toward this and another set of eyes can be placed on this so we can get this integrated into Homepage!

**Comment by Node815** [comment]
I was able to get some of it to work, but it seems like we can only  use the Dynamic-List which in itself seems limiting based on the total number of entries we can have access to in the JSON:
<img width="633" height="196" alt="image" src="https://github.com/user-attachments/assets/278cff84-4e6d-4dbf-ac04-f771aa8ad2a5" />
The relevant code for the Dynamic List"

```
          display: dynamic-list
          mappings:
            items: data.sites
            name: name            
            label: siteId     
            description: subnet

```
As this stage, I think it would be really ideal if it could be similar to other ones where it aggregates the total site ID's to show the total number of sites, total number of resources etc.  But this is the best I could get with it and no other widget options work.    I couldn't get a status indicator for each site to show, but this at least is more of a proof of concept.

**Comment by ushandelucca** [comment]
Thank you very much for the preliminary work. With a few minor adjustments, I was able to display the data in the widget:
<img width="593" height="131" alt="grafik" src="https://github.com/user-attachments/assets/9562e4a8-938c-441f-8417-1f71fdc39705" />


```yml
          headers:
             Authorization: Bearer ....        
          display: block
          mappings:
             - field: data.sites.0.online
               label: Online
               format: boolean
             - field: data.sites.0.megabytesIn
               label: MB In
               format: number
             - field: data.sites.0.megabytesOut
               label: MB Out
               format: number            
             - field: status
               label: Status
               format: number       `

```

**Reply by mgrimace** [reply]
Thanks for this! For others here's the full widget, noting you'll need your `orgid` which is just the name of your organization in Pangolin, which I've included in the api URL as an env var.

```yaml
            widget:
                type: customapi
                url: https://api.{{HOMEPAGE_VAR_DOMAIN}}/v1/org/{{HOMEPAGE_VAR_PANGOLIN_ORG}}/sites?limit=1000&offset=0
                refreshInterval: 30000 # optional, refresh every 30s
                method: GET
                headers:
                   Authorization: Bearer {{HOMEPAGE_VAR_PANGOLIN_API}}
                display: block
                mappings:
                   - field: data.sites.0.online
                     label: Online
                     format: boolean
                   - field: data.sites.0.megabytesIn
                     label: MB In
                     format: number
                   - field: data.sites.0.megabytesOut
                     label: MB Out
                     format: number            
                   - field: status
                     label: Status
                     format: number
```
