### DISCUSSION TITLE
Custom Icon too small

### DISCUSSION THREAD

**Discussion by InnocentRain** [gethomepage/homepage#5215] [Support] [answered]
### Description

I'm trying to set a custom logo in the info-widgets header. It works in the sense that it is visible but the size is way too small. The original file is 512x512 but on the screen its a few pixels at best. If i upscale it to 1024x1024 it's the exact same size on screen. Is there any way to change this?

### homepage version

v1.1.1

### Installation method

Docker

### Configuration

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.example.com
    volumes:
      - /srv/data/homepage:/app/config
      - /srv/data/icons:/app/public/icons
    ports:
      - 3000:3000
```

### Troubleshooting

Tried upscaling the image itself but it stays the same size.
