### DISCUSSION TITLE
Issue consuming api

### DISCUSSION THREAD

**Discussion by hvmzx** [gethomepage/homepage#5218] [Support]
### Description

"The size format will return the length of the array or string, or the number of keys in an object. This is then formatted as number."

I am trying to use size for an object here to get the number of objects in that parent object, the curl of http://cwa-dl:8084/api/status (done within homepage container): 
   
 ```
{
  "available": {

  },
  "done": {

  },
  "downloading": {

  },
  "error": {

  },
  "queued": {

  }
}
```

What i would expect is that it gives me 0 but all I see is this from Homepage (nothing shows in logs) 

![image](https://github.com/user-attachments/assets/77fec8ac-0201-466b-82bd-90e52680788c)

### homepage version

v1.1.1 (313835c)

### Installation method

Docker

### Configuration

yaml
```
- CWA:
        server: docker
        container: cwa-dl
        widget:
          type: customapi
          url: http://cwa-dl:8084/api/status
          refreshInterval: 60000 # in ms
          method: GET
          mappings:
            - field: available
              label: available
              format: size
```

### Container Logs

```
2025-04-25T16:02:24.379336079Z    ▲ Next.js 15.2.3
2025-04-25T16:02:24.379555817Z    - Local:        http://localhost:3000
2025-04-25T16:02:24.379569519Z    - Network:      http://0.0.0.0:3000
2025-04-25T16:02:24.379755615Z 
2025-04-25T16:02:24.379967386Z  ✓ Starting...
2025-04-25T16:02:24.675582348Z  ✓ Ready in 307ms
```

### Browser Logs

Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

### Troubleshooting

```
docker exec homepage ping cwa-dl
PING cwa-dl (172.18.0.6): 56 data bytes
64 bytes from 172.18.0.6: seq=0 ttl=64 time=0.222 ms
64 bytes from 172.18.0.6: seq=1 ttl=64 time=0.055 ms
64 bytes from 172.18.0.6: seq=2 ttl=64 time=0.059 ms
```

```
curl -L -k http://cwa-dl:8084/api/status
{"available":{},"done":{},"downloading":{},"error":{},"queued":{}}
```
