### DISCUSSION TITLE
[Bug] FRITZ!Box widget has stopped working

### DISCUSSION THREAD

**Discussion by dpan** [gethomepage/homepage#5226] [Support]
### Description

API Error: Unexpected token '<', "<html>
<h"... is not valid JSON

### homepage version

v1.1.1 (313835c)

### Installation method

Docker

### Configuration

```yaml
- Fritz!Box:
        icon: mdi-router-network
        href: http://192.168.75.1
        description: FRITZ!Box 7590 Router
        ping: http://192.168.75.1
        widget:
          type: fritzbox
          url: http://192.168.75.1
          fields: ["connectionStatus", "uptime", "externalIPAddress"]
```

### Troubleshooting

It was working before and then it started failing without any configuration changes. 
I believe it started with a FRITZ!OS update. Currently running FRITZ!OS 8.03
