### DISCUSSION TITLE
Homepage not working with nextcloud widget with vars in stack.env file

### DISCUSSION THREAD

**Discussion by EvilSkeleton** [gethomepage/homepage#5227] [Support]
### Description

This is my code for homepage nextcloud widget

```
- Storage:
    - Nextcloud:
        href: "{{NEXTCLOUD_VAR_PORTAINER_URL}}"
        icon: nextcloud.svg
        description: NextCloud - File Storage
        widget:
            type: nextcloud
            url: "{{NEXTCLOUD_VAR_PORTAINER_URL}}"
            username: "{{NEXTCLOUD_VAR_USERNAME}}"
            password: "{{NEXTCLOUD_VAR_PASSWORD}}"
```

the issue is I have set the variables in the stack.env file but I am getting the below error.
I have restarted the container, but still getting error

> 
API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data 

I am getting this link when i click the widget

192.168.29.232:3000/{{NEXTCLOUD_VAR_PORTAINER_URL}}

![Screenshot 2025-04-29 000710](https://github.com/user-attachments/assets/812d1753-9feb-41dc-943c-f5151e1f900c)

### homepage version

portainer:latest

### Installation method

Other (please describe above)

### Configuration

```yaml
- Storage:
    - Nextcloud:
        href: "{{NEXTCLOUD_VAR_PORTAINER_URL}}"
        icon: nextcloud.svg
        description: NextCloud - File Storage
        widget:
            type: nextcloud
            url: "{{NEXTCLOUD_VAR_PORTAINER_URL}}"
            username: "{{NEXTCLOUD_VAR_USERNAME}}"
            password: "{{NEXTCLOUD_VAR_PASSWORD}}"
```

### Container Logs

API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data 

### Troubleshooting

It works when I hardcode the url, username and password into the code.
But I want to use the env file to store the details
