### DISCUSSION TITLE
fiveColumns not work on version 1.2.0

### DISCUSSION THREAD

**Discussion by Vctrsnts** [gethomepage/homepage#5236] [Support] [answered]
### Description

I have the version v0.10.9 on docker. When update to version v1.2.0 the **fiveColumns** not work

### homepage version

v1.2.0

### Installation method

Docker

### Configuration

```settings.yml```

```yaml
### Customization
headerStyle: clean
cardBlur: md
theme: dark
color: zinc
fiveColumns: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false

### Group layouts
layout:
  columns: 5
## Homepage
  Virtualization:
    tab: Home
    icon: mdi-desktop-classic
  Monitoring:
    tab: Home
    icon: mdi-message-alert
  Media:
    tab: Home
    icon: mdi-video-vintage
  Audio:
    tab: Home
    icon: mdi-cast-audio
  Books:
    tab: Home
    icon: mdi-book-multiple

## Glances
  myLocalServer:
    tab: Glances
    useEqualHeights: true
    style: row
    columns: 3
    initiallyCollapsed: false
  externalServer:
    tab: Glances
    useEqualHeights: true
    style: row
    columns: 3
    initiallyCollapsed: false
```
And the ```services.yml``` is this:
```yaml
- Virtualization:
    - unRaid:
        icon: unraid
        href: http://xxx
        description:
        siteMonitor: http://xxx
        widget:
          type: customapi
          url: http://xxx
          method: GET # this doesn't matter
    - Traefik:
        icon: traefik.png
        href: https://xxx
        description: Open-source Reverse Proxy and Load Balancer
        siteMonitor: https://xxx
    - JDownloader:
        icon: jdownloader.png
        href: http://xxx
        description: Aplicacio per a descarregues
        siteMonitor: http://xxx
        container: JDownloader2
- Monitoring:
    - piHole:
        icon: pi-hole.png
        href: http://xxx
        description: Servidor PiHole
        siteMonitor: http://xxx
        container: pihole
    - CUP:
        icon: /icons/cup-with-straw.png
        href: https://xxx
        description: Notifications for New Container Version Releases
        siteMonitor: https://xxx
    - Scrutiny:
        icon: https://xxx
        href: http://xxx
        description: S.M.A.R.T. Monitoring Dashboard
        siteMonitor: http://xxx
        container: scrutiny
- Media:
    - Jackett:
        icon: jackett.png
        href: http://xxx
        description: Servidor Indexers
        siteMonitor: http://xxx
        container: jackett
    - Transmission:
        icon: transmission.png
        href: http://xxx
        description: Servidor Transmission
        siteMonitor: http://xxx
        container: transmission
    - Immich:
        icon: immich.png
        href: http://xxx
        description: Servidor Fotos
        siteMonitor: http://xxx
        container: immich_server
- Audio:
    - Jellyfin:
        icon: jellyfin.png
        href: http://xxx
        description: Servidor Multimedia
        siteMonitor: http://xxx
        container: jellyfin
    - Music:
        icon: http://xxx
        href: http://xxx
        description: Servidor Musica
        siteMonitor: http://xxx
        container: navidrome
- Books:
    - Calibre-Web:
        icon: calibre-web.png
        href: http://xxx
        description: Web per a la gestió de llibres (Calibre) i la seva BDDD
        siteMonitor: http://xxx
        container: calibre-web
    - Calibre:
        icon: calibre.png
        href: http://xxx
        description: Software de Gestió de Llibres
        siteMonitor: http://xxx
    - Kavita:
        icon: kavita.png
        href: http://xxx
        description: Servidor de Comics
        siteMonitor: http://xxx
        container: kavita
- localServer:
    - CPU Usage:
        widget:
          type: glances
          url: http://xxx
          metric: cpu
    - Memory:
        widget:
          type: glances
          url: http://xxx
          metric: memory
    - Network:
        widget:
          type: glances
          url: http://xxx
          metric: network:eth0
    - Processes:
        widget:
          type: glances
          url: http://xxx
          metric: process
    - Disk I/O:
        widget:
          type: glances
          url: http://xxx
          metric: disk:nvme0n1
    - Disk I/O:
        widget:
          type: glances
          url: http://xxx
          metric: disk:sdb
- VPS:
    - CPU Usage:
        widget:
          type: glances
          url: http://xxx
    - Memory:
        widget:
          type: glances
          url: http://xxx
          metric: memory
          version: 4
    - Network:
        widget:
          type: glances
          url: http://xxx
          metric: network:eth0
          version: 4
    - Processes:
        widget:
          type: glances
          url: http://xxx
          metric: processa
          version: 4
    - Disk Usage:
        widget:
          type: glances
          url: http://xxx
          metric: fs:/etc/hostname
          version: 4
    - Disk I/O:
        widget:
          type: glances
          url: http://xxx
          metric: disk:sda
          version: 4
```

And the result is that only have 4 columns and all is small. Not the same that v0.10.9

Any person have the same problem? Because I dont update to new version because this problem.

Thanks a lot
```


### Container Logs

Not see any error for this problem

### Browser Logs

Not see any error for this problem

### Troubleshooting

Hi,
I have the homepage version v.0.10.9 and **fiveColumns** work perfect with my configuration.

But the update to latest version ( v1.2.0 ) the **fiveColumns** not work and all homepage make small. The size reduce and change to version v0.10.9 with the same configuration ( no change anything ) all work perfect.

Where is the problem?? Because I read the documentation and dont see that change anything on configuration files with the new version.

Thanks a lot is help me.
