### DISCUSSION TITLE
[Feature Request] Support Multiple Search Engines with Query Prefix Routing (Like Browser Keyword Search)

### DISCUSSION THREAD

**Discussion by ghalibsaleem** [gethomepage/homepage#5244] [Feature Requests]
### Description

It would be great if Homepage dashboard supported multiple search engines with dynamic routing based on query prefixes—similar to how modern web browsers allow keyword-based search engine shortcuts (e.g., typing `g cats` for Google, `docs caddy` for homepage docs, `ddg cats` for DuckDuckGo, etc.).

Currently, Homepage only allows defining a single search provider, or a custom search engine URL. However, there's no native way to dynamically route search queries to different engines based on a prefix or keyword. This limits the flexibility of the search feature and forces users to either use only one engine or rely on external redirect services.

**Proposed Feature**:
Add support for query prefix-based routing to multiple search engines directly within the Homepage configuration.

### Behavior:

* Users can define a list of engines with a keyword prefix.
* When a query begins with a recognized prefix (e.g., `ddg cats`), Homepage strips the prefix and routes the query to the corresponding search engine.
* If no prefix is detected, the query goes to the default search engine.

**Benefits**:

* Adds powerful, browser-like search routing to the dashboard.
* Greatly improves flexibility for users who prefer different engines for different types of queries (e.g., general search, video, programming).
* Keeps everything local and centralized—no need for external redirector scripts or services.

### Suggested YAML Schema (example):

```yaml
search:
  provider: multi
  engines:
    g:
      name: Google
      url: https://www.google.com/search?q={query}
    ddg:
      name: DuckDuckGo
      url: https://duckduckgo.com/?q={query}
    yt:
      name: YouTube
      url: https://www.youtube.com/results?search_query={query}
  default:
    name: Google
    url: https://www.google.com/search?q={query}
```
