### DISCUSSION TITLE
Unifi Cloud Gateway Fiber - widget API error 404 on sites

### DISCUSSION THREAD

**Discussion by MilosHavranek** [gethomepage/homepage#5253] [Support]
### Description

I switched from Unifi Controller to Unifi Cloud Gateway Fiber and currently having issues with unifi widget.

### homepage version

v1.2.0

### Installation method

Docker

### Configuration

```yaml
widget:
- unifi_console:
    url: https://unifi
    username: homepage
    password: ....
```

### Container Logs

[2025-05-08T21:21:55.095Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://unifi/api/stat/sites. Data: Not Found

### Troubleshooting

Changed configs for both services and widgets.
Service works, widget doesn't.
Container recreated just in case.
