### DISCUSSION TITLE
Unable add more than one group

### DISCUSSION THREAD

**Discussion by rhpeZ** [gethomepage/homepage#5262] [Support] [answered]
### Description

Hello, I am new to homepage so apologies if I have read any guides wrong. I have followed multiple guides but cannot get this work. I have added a group and defined the layout in the settings.yaml and then customised it in services.yaml and then it shows on the homepage working, but when I add a second group and customise that it just shows a blank homepage with both groups not there. Below is the configuration in my services.yaml and settings.yaml and the error I get in the logs file on docker and the homepage.log

### homepage version

v1.2.0 (2376184)

### Installation method

Docker

### Configuration yaml
services.yaml

```yaml
- Hypervisors:
    - Ganymede:
        href: https://10.17.10.10:8006
        icon: proxmox.png
        description: Proxmox Main Node
        siteMonitor: https://10.17.10.10:8006
        widget:
            type: proxmox
            url: https://10.17.10.10:8006
            username: my username
            password: my password
            node: ganymede 
    - Europa:
        href: https://10.17.10.20:8006
        icon: proxmox.png
        description: Proxmox Media Node
        siteMonitor: https://10.17.10.20:8006
        widget:
            type: proxmox
            url: https://10.17.10.20:8006
            username: my username
            password: my password
            node: europa
-  Administration:
    Technitium:
        href: https://10.17.10.100:5380
        icon: technitium.png
        description: DNS Server
        siteMonitor: https://10.17.10.100:5380
        widget:
            type: technitium
            url: https://10.17.10.100:5380
            key: my api key
            range: LastYear
```

settings.yaml

```yaml
headerStyle: boxedWidgets
statusStyle: "dot"
cardBlur: sm
language: en
layout:
  Hypervisors:
    style: row
    columns: 2
  Administration:
    style: row
    columns: 4
quicklaunch:
  hideInternetSearch: true
  hideVisitURL: true
  searchDescription: true
fullWidth: true
```

### Container Logs

[2025-05-12T09:51:22.326Z] error: Failed to load services.yaml, please check for errors
[2025-05-12T09:51:22.326Z] error: TypeError: t[a].forEach is not a function

### Browser Logs

[2025-05-12T09:51:22.326Z] error: Failed to load services.yaml, please check for errors
[2025-05-12T09:51:22.326Z] error: TypeError: t[a].forEach is not a function

### Troubleshooting

I have followed all applicable troubleshooting steps and got nowhere, I have updated the log level to debug but got no extra information or errors.
