### DISCUSSION TITLE
Calendar service does not respect "maxEvents:0"

### DISCUSSION THREAD

**Discussion by andbad** [gethomepage/homepage#5263] [Support] [answered]
### Description

If I set "maxEvents: 0", the integration ignore the setting and switch to default (10).
If I set "maxEvents: 1", I see correctly one event.

services.yaml  
```
- "Calendar": 
    - Personal:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          maxEvents: 0
          showTime: true
          integrations:
           - type: ical
             url: http://xxxxxxxxxx/cal.ics
             name: "Cal"
             color: zinc
             params:
               showName: false 
```

Screenshot:
![Schermata 2025-05-13 08:52:18](https://github.com/user-attachments/assets/a92b94ee-a1cb-4b14-a9d9-bc48c002ab6a)

Can you confirm?

By(t)e

### homepage version

V1.2.0

### Installation method

Docker

### Configuration

```yaml
- "Calendar": 
    - Personal:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          maxEvents: 0
          showTime: true
          integrations:
           - type: ical
             url: http://xxxxxxxxxx/cal.ics
             name: "Cal"
             color: zinc
             params:
               showName: false
```

### Troubleshooting

Not relevant
