### DISCUSSION TITLE
Can't get to homepage in browser

### DISCUSSION THREAD

**Discussion by Kindlewing** [gethomepage/homepage#5265] [Support]
### Description

I'm using a docker macvlan network for my homelab setup. I've assigned static ips to the containers, and I can access the other containers, but not homepage. It just says problem loading page.

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
# .env
HOMEPAGE_ALLOWED_HOSTS=192.168.1.246 #The static IP I set in docker-compose

# docker-compose.yml
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env
    networks:
      pihole_network:
        ipv4_address: 192.168.1.246
    ports:
      - "3000:3000"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: $HOMEPAGE_ALLOWED_HOSTS
    volumes:
      - ./homepage/config:/app/config # Make sure your local config directory exists
      - ./homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```

### Container Logs

There's not much here.

### Troubleshooting

The site just doesn't even register in the browser. There's no logs to speak of.
