### DISCUSSION TITLE
Homepage fails to load after 10mins

### DISCUSSION THREAD

**Discussion by pmharris77** [gethomepage/homepage#5266] [Support]
# Description

I'm having an issue where my homepage initially loads ok on container startup, but then after about 10mins, only the footer loads and I get log messages saying that all the yaml config files don't exist every time I refresh the page.

Any ideas?

# Homepage Version
V1.2.0

# Installation Method
docker compose stack (see below)

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.local # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    ports:
      - 3190:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      # - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

```

# Container Logs

Log extract below for settings.yaml. Same log error also happens for the other three config files.

```
 ✓ Starting...
 ✓ Ready in 1122ms
[2025-05-13T20:49:55.327Z] info: kubernetes.yaml was copied to the config folder
[2025-05-13T20:49:57.282Z] info: docker.yaml was copied to the config folder
[2025-05-13T20:49:57.321Z] info: custom.css was copied to the config folder
[2025-05-13T20:49:57.323Z] info: custom.js was copied to the config folder
[2025-05-13T21:20:44.765Z] error: Error: ENOENT: no such file or directory, copyfile '/app/src/skeleton/settings.yaml' -> '/app/config/settings.yaml'
    at copyFileSync (node:fs:3086:11)
    at l (/app/.next/server/pages/browserconfig.xml.js:9:700)
    at c (/app/.next/server/pages/site.webmanifest.js:1:2998)
    at /app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:31:909
    at /app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/trace/tracer.js:169:36
    at NoopContextManager.with (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/trace/tracer.js:151:103
[2025-05-13T21:20:44.775Z] error: Error: ENOENT: no such file or directory, copyfile '/app/src/skeleton/settings.yaml' -> '/app/config/settings.yaml'
    at copyFileSync (node:fs:3086:11)
    at l (/app/.next/server/pages/browserconfig.xml.js:9:700)
    at c (/app/.next/server/pages/site.webmanifest.js:1:2998)
    at /app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:31:909
    at /app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/trace/tracer.js:169:36
    at NoopContextManager.with (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/trace/tracer.js:151:103

```
