### DISCUSSION TITLE
[Feature Request] Allow templating in label of Widget for Custom API

### DISCUSSION THREAD

**Discussion by smileBeda** [gethomepage/homepage#5271] [Feature Requests]
### Description

I am using Custom API widget:
```
widget:
          type: customapi
          url: my-url
          refreshInterval: 999
          display: dynamic-list
          data: updates
          mappings:
            items: updates
            name: image
            label: container
            limit: 1000
            target: https://example.com/server/{image}
```

I would like to be able to combine values in `label` (or also `name`)
Example:
```
widget:
          type: customapi
          url: my-url
          refreshInterval: 999
          display: dynamic-list
          data: updates
          mappings:
            items: updates
            name: image
            label: container (v{version})
            limit: 1000
            target: https://example.com/server/{image}
```

Just an example. Basically, allow us to use string, and combinations of strings + values from API response in the label and name.

Exactly like it is allowed in the `target`.

### Other

This is helpful because otherwise every API has to be rewritten to deliver responses with already combined values.
