### DISCUSSION TITLE
openmeteo offline

### DISCUSSION THREAD

**Discussion by ozdeadmeat** [gethomepage/homepage#5273] [Support] [answered]
### Description

getting an error 500 and API Error on my homepage. It was set to update once an hour so i dont think it was due to over use. I have upped the time between cache updates to 6 hours. Does anyone else have this problem?

[2025-05-15T09:15:51.782Z] error: <httpProxy> Error calling https://api.open-meteo.com/v1/forecast...
[2025-05-15T09:15:51.786Z] error: <httpProxy> [ 500, [AggregateError: ] { code: 'ETIMEDOUT' } ]

### homepage version

v1.2.0 (2376184, 29 Apr 2025)

### Installation method

Docker

### Configuration

```yaml
- openmeteo:
    label: Canberra # optional
    latitude: -35.282001
    longitude: 149.128998
    timezone: Australia/Sydney # optional
    units: metric # or imperial
    cache: 360 # Time in minutes to cache API responses, to stay within limits
```

### Troubleshooting

Checked that i can get to the website https://api.open-meteo.com/v1/ Nothing else has changed, this just stopped working.
