### DISCUSSION TITLE
Calendar Widget

### DISCUSSION THREAD

**Discussion by Keatingfish** [gethomepage/homepage#5276] [Support]
### Description

Hi all,

For the calendar widget, does anyone know how to have it refresh or auto update? When I am sitting on a day (5/15/2025) and it changes to a new day (5/16/2025) the calendar stays on 5/15/2025 and doesn't update when my homepage is static and hasn't been refreshed. All other widgets do update with additional info (arrs, etc)

### homepage version

v1.2.0 2376184

### Installation method

Docker

### Configuration

```yaml
Calendar Widget --

- Calendar:
          widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            showTime: false # optional - show time for event happening today - defaults to false
            timezone: America/Chicago # optional and only when timezone is not detected properly (slightly slower performance)
```

### Troubleshooting

Just not sure what to do to make it refresh automatically. I tried using refreshIntervals: 10 under it but that didn't seem to update it.
