### DISCUSSION TITLE
Uninformative error message with widgets

### DISCUSSION THREAD

**Discussion by Dinth** [gethomepage/homepage#5279] [Support]
### Description

Hi. I just started learning Homepage, so im certain im doing something wrong when setting up widgets, resulting in "API Error Information" errors under each widget. This being said, according to docs and previous discussions, i should see a informative error message when i click on "API Error Information", but only thing which shows up is "API Error: Unexpected error". 
![image](https://github.com/user-attachments/assets/14613edf-54ce-478f-bad4-1e82e240458c)

### homepage version

v1.2.0 (2376184, Apr 28, 2025)

### Installation method

Docker

### Configuration

```yaml
homepage:

services:
  homepage-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: homepage-socket-proxy
    restart: unless-stopped
    networks:
      - homepage
    environment:
      CONTAINERS: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ipc: private
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "fp.${DOMAIN_NAME},10.10.1.13:3008"
      PUID: "${DOCKER_PUID}"
      PGID: "${DOCKER_PGID}"
    ports:
      - 3008:3000
    volumes:
      - /opt/docker/homepage/homepage_config:/app/config
    restart: unless-stopped
    networks:
      - homepage
      - traefik
networks:
  homepage:
    name: homepage
    driver: bridge
    external: false
  traefik:
    external: true


other services:

calibre-web:

      homepage.group: "Media"
      homepage.name: "Calibre-web"
      homepage.icon: "calibre-web.png"
      homepage.href: "https://calibre.${DOMAIN_NAME}"
      homepage.description: "E-book catalogue"
#      homepage.widget.fields: "['books', 'authors', 'categories', 'series']"
      homepage.widget.type: "calibreweb"
      homepage.widget.url: "http://10.10.1.13:8083"
      homepage.widget.username: "${HOMEPAGE_CALIBREWEB_USER}"
      homepage.widget.password: "${HOMEPAGE_CALIBREWEB_PASS}"


sonarr:

    labels:
      - "homepage.group=Media"
      - "homepage.name=Sonarr"
      - "homepage.icon=sonarr.png"
      - "homepage.instance.internal.href=http://10.10.1.13:8989"
      - "homepage.description=TV Shows catalogue"
      - "homepage.widget.type=sonarr"
      - "homepage.widget.url=http://10.10.1.13:8989"
      - "homepage.widget.key=${SONARR__INSTANCES__0__APIKEY}"
      - "homepage.widget.enableQueue=true"
```

### Container Logs
```
homepage               | 2025-05-15T20:35:03.835814136Z [2025-05-15T20:35:03.835Z] error:  TypeError: t.map is not a function
homepage               | 2025-05-15T20:35:03.835833050Z     at e (/app/.next/server/chunks/5965.js:1:11475)
homepage               | 2025-05-15T20:35:03.835838088Z     at y (/app/.next/server/chunks/5965.js:1:11840)
homepage               | 2025-05-15T20:35:03.835841788Z     at async b (/app/.next/server/chunks/5965.js:1:13928)
homepage-socket-proxy  | 2025-05-15T20:35:03.926132907Z ::ffff:169.254.4.3:39476 [15/May/2025:20:35:03.888] dockerfrontend dockerbackend/dockersocket 0/0/0/23/37 200 226171 - - ---- 4/4/1/1/0 0/0 "GET /containers/json?all=true HTTP/1.1"
homepage-socket-proxy  | 2025-05-15T20:35:03.926836728Z ::ffff:169.254.4.3:39488 [15/May/2025:20:35:03.925] dockerfrontend dockerbackend/dockersocket 0/0/0/1/1 200 11279 - - ---- 4/4/0/0/0 0/0 "GET /containers/calibre-web/json HTTP/1.1"
homepage-socket-proxy  | 2025-05-15T20:35:03.935354827Z ::ffff:169.254.4.3:39476 [15/May/2025:20:35:03.933] dockerfrontend dockerbackend/dockersocket 0/0/0/1/1 200 25978 - - ---- 4/4/1/1/0 0/0 "GET /containers/sonarr/json HTTP/1.1"
homepage               | 2025-05-15T20:35:03.835845586Z     at async A (/app/.next/server/chunks/5965.js:1:14207)
homepage               | 2025-05-15T20:35:03.835849251Z     at async u (/app/.next/server/pages/api/services/proxy.js:28:45285)
homepage               | 2025-05-15T20:35:03.835852938Z     at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
homepage               | 2025-05-15T20:35:03.835857005Z     at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
homepage               | 2025-05-15T20:35:03.835861048Z     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
homepage               | 2025-05-15T20:35:03.835864993Z     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
homepage               | 2025-05-15T20:35:03.835869015Z     at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
homepage               | 2025-05-15T20:35:03.836698171Z [2025-05-15T20:35:03.836Z] error:  TypeError: t.map is not a function
homepage               | 2025-05-15T20:35:03.836709187Z     at e (/app/.next/server/chunks/5965.js:1:11475)
homepage               | 2025-05-15T20:35:03.836715355Z     at y (/app/.next/server/chunks/5965.js:1:11840)
homepage               | 2025-05-15T20:35:03.836721335Z     at async b (/app/.next/server/chunks/5965.js:1:13928)
homepage               | 2025-05-15T20:35:03.836727058Z     at async A (/app/.next/server/chunks/5965.js:1:14207)
homepage               | 2025-05-15T20:35:03.836732967Z     at async u (/app/.next/server/pages/api/services/proxy.js:28:45285)
homepage               | 2025-05-15T20:35:03.836738829Z     at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
homepage-socket-proxy  | 2025-05-15T20:35:03.956416083Z ::ffff:169.254.4.3:39476 [15/May/2025:20:35:03.937] dockerfrontend dockerbackend/dockersocket 0/0/0/17/17 200 226171 - - ---- 4/4/2/2/0 0/0 "GET /containers/json?all=true HTTP/1.1"
homepage-socket-proxy  | 2025-05-15T20:35:03.957496804Z ::ffff:169.254.4.3:39498 [15/May/2025:20:35:03.933] dockerfrontend dockerbackend/dockersocket 0/0/0/18/23 200 226171 - - ---- 4/4/1/1/0 0/0 "GET /containers/json?all=true HTTP/1.1"
homepage-socket-proxy  | 2025-05-15T20:35:03.962107269Z ::ffff:169.254.4.3:39514 [15/May/2025:20:35:03.935] dockerfrontend dockerbackend/dockersocket 0/0/0/19/26 200 226171 - - ---- 4/4/1/1/0 0/0 "GET /containers/json?all=true HTTP/1.1"
homepage-socket-proxy  | 2025-05-15T20:35:03.962844697Z ::ffff:169.254.4.3:39498 [15/May/2025:20:35:03.961] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 200 11549 - - ---- 4/4/0/0/0 0/0 "GET /containers/frigate/json HTTP/1.1"
homepage-socket-proxy  | 2025-05-15T20:35:03.967647588Z ::ffff:169.254.4.3:39514 [15/May/2025:20:35:03.966] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 200 10268 - - ---- 4/4/0/0/0 0/0 "GET /containers/traefik/json HTTP/1.1"
homepage               | 2025-05-15T20:35:03.836745255Z     at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
homepage               | 2025-05-15T20:35:03.836751369Z     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
homepage               | 2025-05-15T20:35:03.836757444Z     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
homepage               | 2025-05-15T20:35:03.836771754Z     at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
homepage               | 2025-05-15T20:35:03.846661512Z [2025-05-15T20:35:03.846Z] error:  TypeError: t.map is not a function
homepage               | 2025-05-15T20:35:03.846730534Z     at e (/app/.next/server/chunks/5965.js:1:11475)
homepage               | 2025-05-15T20:35:03.846740224Z     at y (/app/.next/server/chunks/5965.js:1:11840)
homepage               | 2025-05-15T20:35:03.846747221Z     at async b (/app/.next/server/chunks/5965.js:1:13928)
homepage               | 2025-05-15T20:35:03.846755211Z     at async A (/app/.next/server/chunks/5965.js:1:14207)
homepage               | 2025-05-15T20:35:03.846762684Z     at async u (/app/.next/server/pages/api/services/proxy.js:28:45285)
homepage               | 2025-05-15T20:35:03.846770293Z     at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
homepage               | 2025-05-15T20:35:03.846778949Z     at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
homepage               | 2025-05-15T20:35:03.846786458Z     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
homepage               | 2025-05-15T20:35:03.846794555Z     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
homepage               | 2025-05-15T20:35:03.846802075Z     at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
homepage               | 2025-05-15T20:35:03.888172323Z [2025-05-15T20:35:03.887Z] error:  TypeError: t.map is not a function
homepage               | 2025-05-15T20:35:03.888215756Z     at e (/app/.next/server/chunks/5965.js:1:11475)
homepage               | 2025-05-15T20:35:03.888225336Z     at y (/app/.next/server/chunks/5965.js:1:11840)
homepage               | 2025-05-15T20:35:03.888231849Z     at async b (/app/.next/server/chunks/5965.js:1:13928)
homepage               | 2025-05-15T20:35:03.888238564Z     at async A (/app/.next/server/chunks/5965.js:1:14207)
homepage               | 2025-05-15T20:35:03.888245243Z     at async u (/app/.next/server/pages/api/services/proxy.js:28:45285)
homepage               | 2025-05-15T20:35:03.888251786Z     at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
homepage               | 2025-05-15T20:35:03.888259813Z     at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
homepage               | 2025-05-15T20:35:03.888268043Z     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
homepage               | 2025-05-15T20:35:03.888290459Z     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
homepage               | 2025-05-15T20:35:03.888302009Z     at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
homepage               | 2025-05-15T20:35:03.976821497Z [2025-05-15T20:35:03.976Z] error: Failed to load services.yaml, please check for errors
homepage               | 2025-05-15T20:35:03.977007847Z [2025-05-15T20:35:03.976Z] error: TypeError: t.map is not a function
```

### Troubleshooting

1. No
2. Yes
3. Ping is all right
4.```
root@r720-omv:~# docker exec homepage /usr/sbin/curl -L -k 'http://10.10.1.13:8989/api/v3/queue?apikey=xxxx'
OCI runtime exec failed: exec failed: unable to start container process: exec: "/usr/sbin/curl": stat /usr/sbin/curl: no such file or directory: unknown

```
