### DISCUSSION TITLE
Can someone help me fix this error with qBittorrent?

### DISCUSSION THREAD

**Discussion by MsTekkie** [gethomepage/homepage#5280] [Support] [answered]
### Description

![qbtorrent error](https://github.com/user-attachments/assets/2024578b-b154-49c3-b078-9d79af9dc4d8)

Hi.  Can someone please help me fix this error?

Thank you.

### homepage version

v1.2.0 (2376184, Apr 28, 2025)

### Installation method

Docker

### Configuration

```yaml
- TOOLS:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://192.168.192.54:8080
        description: Torrent manager
        widget:
          type: qbittorrent
          url: http://192.168.192.54:8080
          username: admin
          password: "%nunyabizness%"
          enableLeechProgress: true # optional, defaults to false
```

### Troubleshooting

Not sure how to troubleshoot.  I tried to google but it bombed out when I made the request.
