### DISCUSSION TITLE
[Feature Request] Komodo Widget

### DISCUSSION THREAD

**Discussion by mregni** [gethomepage/homepage#5288] [Feature Requests] [answered]
### Description

Since I moved from Portainer to Komodo I was missing a widget to see my container stats. 
I created a widget that can display max 4 items of the following list of items:

Servers: `Healthy`, `Unhealthy`, `Disabled` and `Total`
Stacks: `Running`, `Stopped`, `Down`,  `Unhealthy` and `Total`
Containers: `Running`, `Stopped`, `Unhealthy`, `Updates` and `Total`

Screenshot:
![image](https://github.com/user-attachments/assets/4a8c9780-809c-4364-9921-21c1fd8c515e)

Config:
```
widget:
  type: komodo
  url: http://komodo:9120
  key: K-1234567800
  secret: S-1234567800
  fields: ["serversHealthy", "stacksRunning", "containersRunning"]
```
When omitted, `["serversHealthy", "stacksRunning", "containersRunning", "containersStopped"]` will be used. Authentication is done with a Komodo Api-Key and Api-Secret. 

Feel free to upvote the feature or request more blocks.
