### DISCUSSION TITLE
[Feature Request] Login / password protection

### DISCUSSION THREAD

**Discussion by abonforti** [gethomepage/homepage#529] [Feature Requests]
Altough each exposed service should be (at least) password protected, it would be nice to have the possibility to set a login method to view the whole dashboard (e.g. username/password login).
Of course, this can be expanded by defining per-user ACL (like what the user is allowed to see).
Many personal dashboards offer this possibility, so, I believe it would be nice to have as well on this.

**Comment by gordon848** [comment]
First of all thanks for this amazing dashboard. I installed it yesterday and Im verry happy with it. Only one thing: I miss an option to enable password protection. Something like basic auth?

**Reply by abonforti** [reply]
I managed to fix that deploying it behind an authelia container. But yes, the functionality would be a nice to have

**Reply by EricGuic** [reply]
Yes, and to be able to specify for each user different dashboard (so one simple for my kids with their bookmarks and services, and another dashboard for me as an administrator of the house).

**Reply by psociety** [reply]
So the only solution right now is to setup yet another docker container just to protect this container? damn it. Glad i just set 1 service before noticing this security hole.

**Reply by shamoon** [reply]
Honestly, deploying self-hosted services on the public web while relying on their built-in auth doesn't seem like the best approach any more and reverse-proxies have become incredibly user-friendly, so not sure how much of a priority this really is. Also with the exception of playing / pausing media, homepage is 99% "read-only"

**Reply by psociety** [reply]
I'm also switching to frp for the reverse proxying and i found out i can set the auth there:
https://github.com/fatedier/frp#require-http-basic-auth-password-for-web-services

So seems like the missing auth is not longer a blocker to me :p

**Reply by JazzFisch** [reply]
Hearing of people wanting to put Homepage on the public internet, and knowing how brutally hard AuthN / AuthZ is to securely implement, I truly believe that leveraging a dedicated AuthN / AuthZ solution is the best approach.  @psociety the last thing I want to find out is that someone relied on a "simple" basic auth implementation in Homepage that had a bug and exposed someone's homepage details to the internet.

For people looking to add Basic Authentication and are using reverse proxies, there are dedicated pages related to adding this to your setups.  See the following links:
* https://doc.traefik.io/traefik/middlewares/http/basicauth/
* https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Reply by psociety** [reply]
@JazzFisch i do agree that proper proxying is a subject i'm quite behind in. Until yesterday i was relying on autossh to make a basic reverse proxy and my main problem was that the connection still dropped from time to time (third world country) requiring manual restart of the tunnel. I moved to frp because setting it up took less than 5mins, but i don't have SSL.
Seems like i should take my time to study traefik as it may be able to cover all 3 things i need: SSL, Auth, reverse proxy.
Next step would be multiplexing as most apps i run locally don't have SSL/auth on their own, run on diff ports and right now i can't access them from the outside. Only homepage.

**Reply by pradiptabasu** [reply]
Ability to define per-user ACL and dashboard is definitely needed. 
While it will be best, if homepage can integrate with external AuthN/AuthZ service, thru standard OIDC implementation, and itself implement the user specific dashboard rendering, but in the interest of simplicity, I am okay if a local AuthN/AuthZ is implemented. 

@benphelps - need your help with this feature request.

**Comment by JazzFisch** [comment]
For anyone looking to implement security in their environments, both Authelia and Authentik provide features that you can get up and running.  Personally, I use Authentik for both authentication inside my network as well as outside my network.  I then use Traefik's forward auth provision to ensure that all services behind it are authenticated.

**Reply by pugnobellum** [reply]
I use SWAG + Authelia but same idea works great.

**Comment by crispybegs** [comment]
fwiw i made this remotely available for myself with a cloudflare tunnel that's heavily locked down (need an OTP code to get in, and mine is the only email it can be sent to... and also it can only be accessed from three specifed countries in the world). 
Would still be nice to have a simple user login page as well, just because it's a tiny bit extra.

**Comment by stayingarmed** [comment]
I was going to switch to this from Heimdall but seeing as it doesn’t have a simple auth option, I guess I’ll stick with what I already have.

**Comment by mgrimace** [comment]
## General steps to add authorization control using [Authentik](https://github.com/goauthentik/authentik)
Note: there are a variety of ways to accomplish this, I'm sharing the steps I used for what it's worth.

- First, make sure you reverse proxy the application using your app of choice. I'm using [NPM](https://github.com/NginxProxyManager/nginx-proxy-manager) for example, and have homepage.mydomain.com pointed to my local IP:Port for Homepage.
- You may wish to also create auth.mydomain.com pointing to Authentik while you're here as well to make later steps easier. 

## In Authentik 

- go to the webadmin panel, and go to applications/providers
- select proxy provider, we need to create a new provider for each app that we want to add authentication to
    - Name: Homepage ForwardAuth
    - Authorization flow: ... <u>implicit</u>
    - Forward Auth (single)
    - External host: https://homepage.mydomain.com/ set in your reverse proxy

### Go to applications

- Create app name: Homepage
- Slug homepage (should autofill)
- Provider: select the Homepage ForwardAuth provider you created above
- Optionally, add an icon and brief description of the application

###  Go to outposts

- Select edit for the existing option, and highlight the new app you want to redirect to Authentik. You'll have to do this for each new app you add. Hold control to select multipe entries.
- In the configuration script section, make sure the auth address is not your internal IP but auth.yourdomain.com (so you can authenticate while not at home) hit update.
- **Note:** If you don't see the configuration script (e.g., this didn't show up in Safari for me for some reason) switch to another browser.

### Go back to providers to get advanced config information for your reverse proxy

- in providers, select Homepage ForwardAuth (not edit, just click the name). 
- Under overview, select your reverse proxy. I chose NPM.
- Add the information provided to your reverse proxy.

## in NPM / your reverse proxy

- select your app in proxy hosts, go to edit, and paste the config provided into advanced, noting that you need to change the line that says

`    proxy_pass          http://auth.example.com/outpost.goauthentik.io;` to your actual IP `http://[AUTHENTIK IP]:9000/outpost.goauthentik.io;`

## Adding authentication to other apps and services

- Note, you can repeat these steps for any others services that Homepage, in turn, links out to. Use Authentik's [integrations](https://goauthentik.io/integrations/) page as a starting point for specific application setups.

**Comment by xorgxx** [comment]
Hi i was thinking that this app is very good. but in the end well not really, my using was with docker on sever to provide for my user's to get "very good hone page" but every body have to get the same homepage !!! and this is not very good option. it since that it will no way have possibility to get natif login page pity. anyway very good initiative .

**Reply by crispybegs** [reply]
can't you just run a different instance for each user? (assuming you don't have, like, 87 users or something)

**Reply by xorgxx** [reply]
true but it take port and resource if we compere with just login page. plus for my homepage a have lot of "private" link that i dont want any user can have access easy if they find with scan ip ...

**Reply by xorgxx** [reply]
i think that this project dos not use any Dbase, but it can be i sujecte to use yml to implement same user login and password ok it's not really on good practice secure but still small implementation for at list small security.

**Comment by josfaber** [comment]
Could a very simple login password be an option, perhaps based on environment variable USE_LOGIN=true?
Might be as simple as looking in the header for a jwt, if not available, then have a password page which sets jwt. This way users could also set this jwt token in header directly with proxy then?

I have set basic auth in Traefik, it's very simple, but when I use this with a Chrome extension such as [custom new tab url](https://chromewebstore.google.com/detail/custom-new-tab-url/mmjbdbjnoablegbkcklggeknkfcjkjia), when I close the last tab, I have to re-enter credentials on opening new tab :-/

**Reply by iFedix** [reply]
How did you configure traefik with homepage? Do you have any compose I can have a look to? I'm struggling to put a basic auth :(

**Reply by josfaber** [reply]
Sure!

- I've mounted my external drive as read only to be able to show disk space (the `T7` mount)
- I've setup basic auth, but that keeps asking me for the usr/pwd every time after restart / new tab
- `dash_jf` and `dash_jf2` are just made up names for the routers and services in traefik

Here's the `docker-compose.yml`

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./config:/app/config
      - ./robots.txt:/app/public/robots.txt 
      - /mnt/T7:/T7:ro
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - web
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.dash_jf.rule=Host(`homepage.myurl.com`)
      - traefik.http.routers.dash_jf.middlewares=dash_jf-auth
      - traefik.http.routers.dash_jf.entrypoints=websecure
      - traefik.http.routers.dash_jf.tls=true
      - traefik.http.routers.dash_jf.tls.certresolver=letsencrypt
      - traefik.http.routers.dash_jf2.rule=Host(`homepage.myurl.com`)
      - traefik.http.routers.dash_jf2.middlewares=redirect-https@file
      - traefik.http.routers.dash_jf2.entrypoints=web
      - traefik.http.services.dash_jf.loadbalancer.server.port=3000
      - traefik.http.middlewares.dash_jf-auth.basicauth.users=username:*******/
networks:
  web:
    external: true
```

Here's the `.env`

```
PUID=1000
PGID=1000

# for use in e.g. config/services.yaml
HOMEPAGE_VAR_TRAEFIK_USER=***
HOMEPAGE_VAR_TRAEFIK_PASSWORD=***

```

The `robots.txt` mount is just there to prevent Google from indexing the url

```
User-agent: *
Disallow: /
```

And here is a part of the `config/services.yaml` that monitors traefik

```
- Monitors:
    - 'Traefik':
        href: https://traefik.myurl.com
        icon: traefik.png
        widget:
            type: traefik
            url: https://traefik.myurl.com
            username: {{HOMEPAGE_VAR_TRAEFIK_USER}} 
            password: {{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}
```

Here's a part of `config/widgets.yaml` that shows the resource usage including the mounted drive

```
- resources:
    cpu: true
    memory: true
    disk: /

- resources:
    disk: /T7
```
