### DISCUSSION TITLE
Host Validation Failed Even With Correct URL In `HOMEPAGE_ALLOWED_HOSTS`

### DISCUSSION THREAD

**Discussion by rajivvishwa** [gethomepage/homepage#5290] [Support]
### Description

I'm getting this error when I'm trying to access homepage via the URL configured in ngnix proxy manager. 

`[2025-05-19T04:40:46.175Z] error: Host validation failed for: start.astra.home. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.`

I already have this url in the compose and I have restarted the container many times. 

`HOMEPAGE_ALLOWED_HOSTS: astra.infv:4100, start.astra.home, start.astra.home:443 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts`

### homepage version

v1.2.0 (2376184, Apr 28, 2025)

### Installation method

Docker

### Troubleshooting

Already checked many posts related to this topic in github but this one seems different.

**Comment by shamoon** [comment]
> Already checked many posts related to this topic in github but this one seems different.

Probably not :)

Please review the docs again, your setting as pasted here is invalid https://gethomepage.dev/installation/#homepage_allowed_hosts

Also, restarting a container is not sufficient when changing environment variables, you must re-create it

**Reply by rajivvishwa** [reply]
What exactly makes it invalid? When I mentioned "restart," I meant that I recreated the container and started it again. I missed to indicate that, my bad.

In any case, I switched the hosts, and it's working now.

```yaml
HOMEPAGE_ALLOWED_HOSTS: start.astra.home, astra.infv:4100
```

If you were referring to the use of `=` instead of `:`, you're right—Docker Compose doesn't support `HOMEPAGE_ALLOWED_HOSTS=` syntax. Also, I couldn't find a clear way to define a wildcard for this setting, as `HOMEPAGE_ALLOWED_HOSTS: *` doesn’t work either. Someone else pointed this out in [[discussion #4991](https://github.com/gethomepage/homepage/discussions/4991#discussioncomment-12598624)](https://github.com/gethomepage/homepage/discussions/4991#discussioncomment-12598624).

That said, my issue is resolved for now.
**TL;DR for others:** If you run into a similar problem, try switching the host values—this workaround might help.

Here is my full docker-compose.yml for reference

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    container_name: homepage
    ports:
      - 4100:3000
    volumes:
      - /home/rajivvishwa/docker/docker_files/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: start.astra.home, astra.infv:4100 # first one is reverse proxied via nginxproxymanager
    networks:
      - default_astra
networks:
  default_astra:
    external: true
```
