### DISCUSSION TITLE
How to manage subgrouping via Swarm deploy labels

### DISCUSSION THREAD

**Discussion by incomingstick** [gethomepage/homepage#5293] [Support] [answered]
### Description

Hello!

I am looking for the correct way to use subgroups with Swarm deploy labels. I have this working for many containers already, but there seems to be an edge case that I am bumping into, and wondering if its because I am just doing something wrong?

In my supplied "configuration" I pasted my layout section.

When I have a subgroup with a **mix** of manually defined services (`services.yaml`), and auto-discovered services (swarm deploy labels), the auto-discovered services are correctly placed in their subgroup when I provide the "lowest" group to the label, i.e `- "homepage.group=Admin"` will correctly place the service under `Row 0 > Row 0A > Admin`.

**However**, if a subgroup contains **no** manually defined services and **only** auto-discovered services, the `layout` is not respected, and a new top level group is created at the bottom of _homepage_. This is the case for both Source Control and Hosting in the following image.

![Screenshot_20250520_191857](https://github.com/user-attachments/assets/64992082-1b1f-475e-8b8c-31d4511b1064)

Now here is where it gets interesting. I can actually correct this, by creating "dummy" `Tmp` services in the `services.yaml` file:

```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Row 0:
  - Row 0A:
    - Admin:
      - Proxmox:
          [...]
      - Unifi OS:
          [...]

    - Security:
      - Unifi Protect:
         [...]

  - Networking:
    - Modem:
        [...]
    - Fast:
        [...]
    - Unifi Network:
        [...]
    - Cloudflare:
        [...]

  - Row 0B:
    - Data & Logging:
      - Proxmox Backup:
          [...]

    - Network Resources:
      - HP Envy 4520 Printer:
          [...]
      - TrueNAS Scale:
          [...]
- Row 1:
  - Engergy:
    - Enphase Enlighten:
        [...]
    - Enphase Envoy:
        [...]
    - WE Energies:
        [...]

  - Source Control:
    - Tmp:

  - Hosting:
    - Tmp:
```

See, it works:

![Screenshot_20250520_192312](https://github.com/user-attachments/assets/5b78644c-8d3e-4fe0-87f6-cfc6e95d21dd)

This, however, is a less than perfect solution, because now whenever I visit homepage the logs are absolutely SPAMMED with parsing errors (but yet it all works!).

Anyone have any suggestions?? Is there a correct way to define subgroups with Docker Swarm deploy labels? Am I missing something for the dummy services? Any time I try and "match" them to a container, we are back to the incorrect layout, with duplicated services which is even worse!

Any help would be greatly appreciated! 

### homepage version

v1.2.0 (2376184, Apr 28, 2025)

### Installation method

Docker

### Configuration

```yaml
layout:
  Row 0:
    header: false
    style: row
    columns: 3
    Row 0A:
      header: false
      style: row
      columns: 2
      Admin:
        icon: mdi-shield-crown
      Security:
        icon: mdi-security
    Networking:
      icon: mdi-lan
      style: row
      columns: 2
    Row 0B:
      header: false
      style: row
      columns: 2
      Data & Logging:
        icon: mdi-database
      Network Resources:
        icon: mdi-folder-network
  Row 1:
    header: false
    style: row
    columns: 3
    Engergy:
      icon: mdi-lightning-bolt
    Source Control:
      icon: mdi-git
    Hosting:
      icon: mdi-server
```

### Container Logs
```
[2025-05-21T00:10:08.553Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.554Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.555Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.555Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.556Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.556Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.577Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.577Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.596Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.596Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.637Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
[2025-05-21T00:10:08.638Z] warn: <service-helpers> Error parsing service "Tmp" from config. Ensure required fields are present.
```

### Troubleshooting

I can actually correct this, by creating "dummy" `Tmp` services in the `services.yaml` file:

```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Row 0:
  - Row 0A:
    - Admin:
      - Proxmox:
          [...]
      - Unifi OS:
          [...]

    - Security:
      - Unifi Protect:
         [...]

  - Networking:
    - Modem:
        [...]
    - Fast:
        [...]
    - Unifi Network:
        [...]
    - Cloudflare:
        [...]

  - Row 0B:
    - Data & Logging:
      - Proxmox Backup:
          [...]

    - Network Resources:
      - HP Envy 4520 Printer:
          [...]
      - TrueNAS Scale:
          [...]
- Row 1:
  - Engergy:
    - Enphase Enlighten:
        [...]
    - Enphase Envoy:
        [...]
    - WE Energies:
        [...]

  - Source Control:
    - Tmp:

  - Hosting:
    - Tmp:
```

This, however, is a less than perfect solution, because now whenever I visit homepage the logs are absolutely SPAMMED with parsing errors (but yet it all works!).

**Comment by shamoon** [comment]
Yea this is a limitation of labels (annotations, etc).

I had a think about it and I believe this will solve it, if you'd like to try out the docker image tagged `feature-layout-only-nested` and let me know (it did in my testing)

**Reply by incomingstick** [reply]
Thanks for getting on it so quick!

Hmmm, maybe I'm still misunderstanding something, but I am not experiencing anything different with the `feature-layout-only-nested` image.

I tried to take a look at the code changes but I'm not quite sure what flattening the groups does in context so I am unsure how to translate that to yaml and label changes on my end.

I did try making various changes and all the behavior appears to be the same.

From my perspective, it would be most ideal to have syntax such that:

1. `settings.yaml`:
```
layout:
  Row 0:
    header: false
    style: row
    columns: 3
    Row 0A:
      header: false
      style: row
      columns: 2
      Admin:
        icon: mdi-shield-crown
      Security:
        icon: mdi-security
    Networking:
      icon: mdi-lan
      style: row
      columns: 2
    Row 0B:
      header: false
      style: row
      columns: 2
      Data & Logging:
        icon: mdi-database
      Network Resources:
        icon: mdi-folder-network
  Row 1:
    header: false
    style: row
    columns: 3
    Engergy:
      icon: mdi-lightning-bolt
    Source Control:
      icon: mdi-git
    Hosting:
      icon: mdi-server

```

2. `services.yaml`:
```
- Row 0:
  - Row 0A:
    - Admin:
      - Proxmox:
          [...]
      - Unifi OS:
          [...]

    - Security:
      - Unifi Protect:
         [...]

  - Networking:
    - Modem:
        [...]
    - Fast:
        [...]
    - Unifi Network:
        [...]
    - Cloudflare:
        [...]

  - Row 0B:
    - Data & Logging:
      - Proxmox Backup:
          [...]

    - Network Resources:
      - HP Envy 4520 Printer:
          [...]
      - TrueNAS Scale:
          [...]
- Row 1:
  - Engergy:
    - Enphase Enlighten:
        [...]
    - Enphase Envoy:
        [...]
    - WE Energies:
        [...]
```

3. and the service would have the label: `- "homepage.group=Hosting"`

together would correctly place the service in the `Hosting` group under `Row 1` as defined in the `layout` even though it is not defined in the `services.yaml`. I see you have a note about this: https://github.com/gethomepage/homepage/blob/5e475dab9db37e8100f0a813d7a2370ff8f2849e/src/utils/config/api-response.js#L204

**Reply by shamoon** [reply, marked as answer]
Actually that note is old because it does work in some situations, but I see the difference in what we're testing.

Testing a layout like:

```yaml
layout:
...
  Testing Nested:
    style: row
    columns: 2
    icon: mdi-test-tube
    Nested A:
    Nested B:
      style: row
      columns: 2
      icon: mdi-alpha-b
      Nested B1:
        icon: mdi-numeric-1
```

and a container like:

```yaml
services:
  whoami:
    image: traefik/whoami
    container_name: faux_gamedig
    labels:
      - homepage.group=Nested B1
```

with nothing in services.yaml works fine for me:

<img width="422" alt="Screenshot 2025-05-20 at 8 39 09 PM" src="https://github.com/user-attachments/assets/10d410a4-b8c3-485e-90d8-bdeac078599b" />


But, if you do have something in services.yaml for `Testing Nested` e.g.:

```yaml
- Testing Nested:
    - Radarr:
        icon: radarr.png
        description: Movies
    - Plex:
        icon: plex.png
        description: plex
```

That breaks the Nested B1:

<img width="1084" alt="Screenshot 2025-05-20 at 8 39 54 PM" src="https://github.com/user-attachments/assets/ce14f62b-befc-474b-a5b9-507b8852145a" />

So I've updated that same docker image and I think this does it. Please let me know.

<img width="1033" alt="Screenshot 2025-05-20 at 8 49 29 PM" src="https://github.com/user-attachments/assets/2ff89201-b9a0-40d1-9035-d03fe0f1f6db" />

Now you know why I havent dug into this sorta thing in a while...
