### DISCUSSION TITLE
[Widget Development] Yaml configs are not passing through

### DISCUSSION THREAD

**Discussion by zeknoss** [gethomepage/homepage#5308] [General]
Hello,
I'm currently developing a Umami Analytics widget for Homepage and having trouble with passing the config parameters to the `component.jsx` file.

Here is the `config/services.yaml` file:
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Analytics:
    - Umami:
        href: https://domain.ltd/
        widget:
            type: umami
            url: "https://domain.ltd/api/"
            timeSpan: 2
            endpoint: pageviews
            refreshInterval: 10000
            timezone: "Europe/Istanbul"
            unit: day
            key: "some-auth-key
            websiteId: some-website-id
```

And here's the part I 'm trying to access the widget config params

```jsx
const { endpoint, timezone, unit, timeSpan = 1, refreshInterval = 10000 } = widget;
```

However, the `timezone`, `unit` and `timeSpan` parameters return `undefined`.

I also created a proxy for the project to use `Authorization` header during the requests.

Any help would be appreciated.
Kind regards.
