### DISCUSSION TITLE
RSS widget

### DISCUSSION THREAD

**Discussion by andbad** [gethomepage/homepage#5312] [General]
Sorry if the question is badly phrased or off topic but I've been researching and trying services on the web for a week without finding a decent solution.
In short, I have some RSS feeds that I would like to include in my homepage to have a solution similar to this:
![Screenshot 2025-05-23 184346](https://github.com/user-attachments/assets/43490e9d-9332-413c-a69b-a88d17d0d6cb)

I tried with various widgets found on the web and including them as iframes but the solution is terrible both aesthetically and in terms of functionality.
Do you have any advice?

By(t)e

**Comment by andbad** [comment]
I got a good result using selfhosted FreshRSS, iFrame and some CSS.
![Schermata 2025-06-04 09:24:30](https://github.com/user-attachments/assets/2ca6e39c-a953-42f7-b3c5-95ea22f47ca5)

services.yaml
```
- "Row2":
    - Updates:
        widget:
          type: iframe
          name: Ansa
          src: https://domani.ext/freshrss/i/?a=normal&get=f_4&state=3
          classes: h-96
          referrerPolicy: same-origin
          allowPolicy: autoplay; fullscreen; gamepad 
          allowFullscreen: false
          loadingStrategy: eager
          allowScrolling: yes 
```

FreshRSS custom CSS

```
/* compact mode :) */
 .flux .item {
         line-height: 15px;
 }
 .tree-folder-title {
         font-size: 1rem;
         line-height: 2.1rem;
 }
 .flux_header .title {
     font-size: 0.8rem;
 }
/* Warning: this disables the header, so it also hides the button to access the configuration */
 .header {
	display: none;
 }

 #nav_entries {
	display: none;
 }
 .nav_menu {
	display: none;
 }
 .day {
	display: none;
 }
 .flux {
	background-color: rgb(60,60,60);
 }

.flux.not_read {
	background-color: rgb(38,38,38);
 }
```

By(t)e
