### DISCUSSION TITLE
YAML Formatting help

### DISCUSSION THREAD

**Discussion by jbeck22** [gethomepage/homepage#532] [Support]
I'm trying to apply a "layout" to my "media management" section and I"m getting YAML formatting errors.  Here is what I have:

```
layout:
  Media Management:
    style: row
    columns: 4
      - Plex:
          href: https://<redacted>
          description: My Plex media server
          icon: plex.png
          widget:
            type: plex
            url: http://<redacted>
            key: <redacted>


    - Sonarr:
        icon: sonarr.png
        href: <redacted>
        description: Series Management 
#        widget:
#          type: sonarr
#          url: <redacted>
#          key: <redacted>
```
