### DISCUSSION TITLE
Resources on mobile homepage always offset

### DISCUSSION THREAD

**Discussion by abosaad11** [gethomepage/homepage#5321] [Support] [answered]
![Screenshot_20250526_195344_Chrome](https://github.com/user-attachments/assets/6bba545c-5f7e-4c8a-95a3-f8bfc6c02c3a)
### Description

Hello

The resources widget at the top has always been offset. If you see the attached screenshot, the area in the red box shouldn't be empty. The resource next to it (CPU) should be moved to the LEFT where the red box is drawn.

This issue is an old one and is still present until the latest version (v1.2.0)

### homepage version

v1.2.0 (2376184, Apr 28, 2025)

### Installation method

Docker

### Troubleshooting

There are no relevant troubleshooting steps for the UI issue.

**Comment by shamoon** [comment]
Not here: 
<img width="340" alt="Screenshot 2025-05-26 at 10 53 29 AM" src="https://github.com/user-attachments/assets/2a0daf50-1c35-444c-8c3f-ba13e19fa2a2" />
<img width="425" alt="Screenshot 2025-05-26 at 10 55 24 AM" src="https://github.com/user-attachments/assets/b756d54a-ac93-4159-909b-b443e25665c6" />

So as a starting point it would be helpful if you posted your config as requested in the template

**Reply by abosaad11** [reply]
Sorry I apologize my bad. Here's the widgets.yaml; (EDIT after solution):

Widget.yaml:

```yaml
---

- resources:
    units: metric

- resources:
    label: CPU
    cpu: true
    expanded: true

- resources:
    label: Memory
    memory: true
    expanded: true

- resources:
    label: CPU Temp
    cputemp: true
    expanded: true

- resources:
    label: Uptime
    uptime: true
    expanded: true

- resources:
    label: SSD
    disk: /
    expanded: true

- resources:
    label: HDD
    disk: /mnt/d
    expanded: true

- resources:
    label: 8 TB
    disk: /mnt/8tb
    expanded: true

- datetime:
    text_size: md
    locale: en-tt
    format:
      timeStyle: short
      dateStyle: short
      hour12: true

- openweathermap:
    label: xxx
    latitude: xxx
    longitude: xxx
    units: metric 
    provider: openweathermap
    cache: 5 
    format:
      maximumFractionDigits: 0
```
