### DISCUSSION TITLE
What is the proper way to use the "network" resource widget?

### DISCUSSION THREAD

**Discussion by abosaad11** [gethomepage/homepage#5322] [Support]
### Description

Hello 

I have a question about the `network` widget. If I leave it at the default `network: true` which interface is it using? 

I'm guessing it's an interface internal to the container. Should I mount anything in the compose file?

If I use this: `network: eno1` I get an API error. The host machine is an Ubuntu which uses the physical `eno1`  interface.

I have seen the documentation but there was no mention of host vs container network interfaces, or how I can properly use this widget.

https://gethomepage.dev/widgets/info/resources/

```yaml
- resources:
    network: true # optional, uses 'default' if true or specify a network interface name
```

### homepage version

v1.2.0 (2376184, Apr 28, 2025)

### Installation method

Docker

### Configuration

```yaml
- resources:
    label: CPU
    cpu: true
    expanded: true

- resources:
    label: Memory
    memory: true
    expanded: true

- resources:
    label: CPU Temp
    cputemp: true
    expanded: true

- resources:
    label: Uptime
    uptime: true
    expanded: true

- resources:
    label: SSD
    disk: /
    expanded: true

- resources:
    label: HDD
    disk: /mnt/d
    expanded: true

- resources:
    label: 8 TB
    disk: /mnt/8tb
    expanded: true

- resources:
    label: Network
    network: eno1
```

### Container Logs

Could not find any errors in the log

```
    at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:235:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:426:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:450:13)
    at async Server.requestListener (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js:158:13)
```

### Troubleshooting

There is no troubleshooting steps for this
