### DISCUSSION TITLE
Widget for Proxmox VE version 8.4.1 showing incorrect stats

### DISCUSSION THREAD

**Discussion by vicnunes** [gethomepage/homepage#5327] [Support]
### Description

FYI: I just upgraded a lab proxmox host to VE v8.4.1 which released on April 9, 2025 and the widget for node: Bigz appears to connect, but its not reporting stats properly.  See attached
![homepage-pmox8 4 1-widget](https://github.com/user-attachments/assets/080f3991-cdbb-4742-b06e-692d30b43077)

It should be reporting 1/1 VMS;  0/0 LXC; ~1.5% CPU; ~28% MEM

As you can also see in the attached screenshot, the Widget is working fine on NucCluster nodes running Proxmox VE v8.3.1 

Thanks for the continued great work in Homepage!!

### homepage version

v1.2.0 running on LXC (https://community-scripts.github.io/ProxmoxVE/scripts?id=homepage)

### Installation method

Other (please describe above)

### Configuration

```yaml
- BIGZ:
        href: https://bigz.local.testing.com:8006
        ping: 192.168.17.218
        icon: proxmox.png
        description: 
        widget:
          type: proxmox
          url: https://bigz.local.testing.com:8006
          username: apistats@pam!api
          password: b043f6e3-3287-...-314d57924217
          node: bigz
```

### Container Logs

No errors reported

### Troubleshooting

Widget was was working fine prior to upgrading from Proxmox VE 8.3.1 to 8.4.1
