### DISCUSSION TITLE
Unable to get some info widgets to work

### DISCUSSION THREAD

**Discussion by MisterPig200471** [gethomepage/homepage#5328] [Support] [answered]
### Description

Hello,
    I have the latest version of HomePage running in a docker container. I am able to access the webpage and i have set up some web links without issue. My issue is with info widgets, some of the ones i have tried don't appear.
    E.g. with the following widgets.yaml file, the greeting and the dattime do show BUT the weather widget just appears as "Missingweather". I put greeting and datetime in my widgets.yaml file to confirm it is being read
    
```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/
- greeting:
    text_size: xl
    text: Greeting Text
    # 1/23/22, 1:37 PM
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
    timeStyle: short

- weather:
    label: Weather
    latitude: 40.7128
    longitude: -74.0060
```

  Can anyone suggest why this may be happening?

### homepage version

v1.2.0 (2376184, Apr 29, 2025)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/
- greeting:
    text_size: xl
    text: Greeting Text
    # 1/23/22, 1:37 PM
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
    timeStyle: short

- weather:
    label: Weather
    latitude: 40.7128
    longitude: -74.0060
```

### Troubleshooting

i have reduced the size onf my widgets.yaml file down to two widgets that work and one of th emany that don't. This tells me the yaml file is being read but something else is stopping the weather widget for displaying correctly
