### DISCUSSION TITLE
Homepage Docker TLS Auto discovery help

### DISCUSSION THREAD

**Discussion by Thor192** [gethomepage/homepage#5329] [Support]
### Description

only works for container that are in the same server no remote docker host work 

### homepage version

v1.2.0 (2376184, Apr 28, 2025)

### Installation method

Docker

### Configuration

```yaml
docker:
  - name: raspi06
    socket: /var/run/docker.sock

  - name: raspi07
    host: 192.168.0.7
    port: 2376
    tls:
      caFile: certs/192.168.0.7/ca.pem
      certFile: certs/192.168.0.7/cert.pem
      keyFile: certs/192.168.0.7/key.pem

  - name: docker-mon
    host: 192.168.0.40
    port: 2376
    tls:
      caFile: certs/192.168.0.40/ca.pem
      certFile: certs/192.168.0.40/cert.pem
      keyFile: certs/192.168.0.40/key.pem

  - name: docker-media
    host: 192.168.0.250
    port: 2376
    tls:
      caFile: certs/192.168.0.250/ca.pem
      certFile: certs/192.168.0.250/cert.pem
      keyFile: certs/192.168.0.250/key.pem
```

### Container Logs

sudo docker logs homepage
   ▲ Next.js 15.2.4
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 250ms
pi@raspberrypi06:~ $ sudo docker logs homepage

I can turn on debug if needed

### Troubleshooting

curl works and it show tags

curl --cacert /app/config/certs/192.168.0.40/ca.pem \
>      --cert /app/config/certs/192.168.0.40/cert.pem \
>      --key /app/config/certs/192.168.0.40/key.pem \
>      https://192.168.0.40:2376/version
{"Platform":{"Name":"Docker Engine - Community"}

curl get tags
heimdall:
  homepage.group: Applications
heimdall:
  homepage.href: https://192.168.0.40:8754
heimdall:
  homepage.icon: heimdall
heimdall:
  homepage.name: Heimdall
smokeping:
  homepage.enabled: true
smokeping:
  homepage.group: Monitoring
smokeping:
  homepage.href: http://192.168.0.40:8065
smokeping:
  homepage.icon: smokeping
smokeping:
  homepage.name: Smokeping
influxdb1:
  homepage.enabled: true
influxdb1:
  homepage.group: Monitoring
influxdb1:
  homepage.href: http://192.168.0.40:8083
influxdb1:
  homepage.icon: influxdb
influxdb1:
  homepage.name: InfluxDB
