### DISCUSSION TITLE
Calendar Widget - iCal's showing different times

### DISCUSSION THREAD

**Discussion by CyberZig** [gethomepage/homepage#5332] [Support]
### Description

I am having a strange issue where 1 of my calendar integrations through iCal is showing the correct date and time, the other one, again through iCal, is showing the same date but 1 hour ahead on all events.

The calendar's I am using are:
- Todoist - this is showing the correct date and time
- Proton - this is showing 1 hr ahead of the correct time

### homepage version

v1.2.0 (2376184)

### Installation method

Docker

### Configuration

```yaml
- Calendars:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          showTime: true
          timezone: Europe/London
          integrations:
            - type: ical
              url: https://ext.todoist.com/export/ical/todoist user_id=xxx
              name: Todo List
              color: teal
            - type: ical
              url: https://calendar.proton.me/api/calendar/v1/url/xxx
              name: Proton
              color: purple
```

### Troubleshooting

I have tried setting a different timezone, but this changes the correct one. I have tried having no timezone set but this does not resolve the issue

Example in Proton
![image](https://github.com/user-attachments/assets/3ef4b4a4-ee8a-4613-b896-f18f2df9ea3b)

Shows as 1hr later in calendar widget
![image](https://github.com/user-attachments/assets/edef8629-2e9e-4221-a4a7-1d486ed6bdec)
