### DISCUSSION TITLE
New endpoint for PiHole API

### DISCUSSION THREAD

**Discussion by Jinra** [gethomepage/homepage#5334] [Support] [answered]
### Description

The PiHole seems to no longer work. It seems some changes were made recently with pihole which changed both the API key (now called app password) as well as the endpoint to access the api. This is the message I get in PiHole logs now when loading homepage

> WARNING: API: Bad request (key: bad_request, hint: The API is hosted at pi.hole/api, not pi.hole/admin/api)

### homepage version

v1.2.0

### Installation method

Docker

### Configuration

```yaml
- Pihole:
        icon: pi-hole.png
        href: http://pi.hole
        description: Local DNS ad blocker
        container: pihole-unbound
        widget:
          type: pihole
          url: http://pi.hole
          key: <redacted>
```

### Troubleshooting

Rotated my API key to the new app password, but widget is still broken. Homepage should make calls to pi.hole/api instead of pi.hole/admin/api
