### DISCUSSION TITLE
Support WG-Easy v15

### DISCUSSION THREAD

**Discussion by hockeymanjs** [gethomepage/homepage#5336] [Support] [answered]
### Description

System (Truenas)

After updating to Version 15.0 of WG-Easy which requires a backup and reinstall of the app the API is no longer working.
![image](https://github.com/user-attachments/assets/0c34d739-d2b4-46d5-a7f2-5fc0fd61ac52)

### homepage version

v1.2.0

### Installation method

Other (please describe above)

### Configuration

```yaml
-  WireGuard:
        href: http://10.0.0.132:30058
        icon: sh-wireguard.png
        widget:
          type: wgeasy
          url: http://10.0.0.132:30058
          password: 
          threshold: 2 # optional
```

### Troubleshooting

Moved ports 
attempted HTTPS vs HTTP 
changed password.
