### DISCUSSION TITLE
How to indicate that a k8s service is running in another namespace when using `HTTPRoute`?

### DISCUSSION THREAD

**Discussion by FirelightFlagboy** [gethomepage/homepage#5338] [Support]
### Description

I've installed `gethomepage` in my k8s cluster.
I'm trying to use `gethomepage` with `HTTPRoute` from the Gateway API.

Currently the routes are defined in the namespace `default` and referencing services (through `backendRefs`) in their respective namespaces (i.e.: different than `default`)

<details>

<summary>Example <code>HTTPRoute</code></summary>

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mealie
  namespace: default
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Application
    gethomepage.dev/description: A recipe manager
    gethomepage.dev/icon: /icons/mealie.svg
    gethomepage.dev/href: https://mealie.example.com
    gethomepage.dev/name: Mealie
    gethomepage.dev/pod-selector: ''
spec:
  parentRefs:
    - name: traefik
      sectionName: websecure

  hostnames:
    - mealie.example.com

  rules:
    - backendRefs:
        - name: mealie
          namespace: mealie
          port: 80
```

</details>

### homepage version

1.2.0

### Installation method

Other (please describe above)

### Configuration

```yaml
---
# https://gethomepage.dev/latest/configs/kubernetes/
mode: cluster

# Configure gethomepage to discover traefik, gateway and ingres
traefik: true
gateway: true
ingress: true
```

### Container Logs

```
<kubernetesStatusService> no pods found with namespace=default and labelSelector= 
```

### Troubleshooting

N/A
