### DISCUSSION TITLE
port_forwarded field in Gluetun widget

### DISCUSSION THREAD

**Discussion by v1rusnl** [gethomepage/homepage#5344] [Support] [answered]
### Description

Since a long time I use Gluetun in Wireguard mode connected to PrivadoVPN via custom provider. 
Since homepage 1.3.0 update, I got an API error with the Gluetun widget. So I rechecked my settings and got rid of the API error by adding `GET /v1/openvpn/portforwarded` to my Gluetun config.toml.

Gluetun config.toml
```
[[roles]]
name = "homepage"
# Define a list of routes with the syntax "Http-Method /path"
routes = [
  "GET /v1/publicip/ip",
  "GET /v1/openvpn/portforwarded"
]
# Define an authentication method with its parameters
auth = "apikey"
apikey = "GENERATED_API_KEY"
```

Homepage services.yaml (Gluetun API Port 8000 is mapped to 8001 on the host):
```
...
    - Gluetun VPN IP:
        icon: gluetun.png
        description: VPN IP und Standort
        ping: host.docker.internal
        widget:
            type: gluetun
            url: http://host.docker.internal:8001
            key: GENERATED_API_KEY
...
```

The other widget fields from the endpoint `/v1/publicip/ip` are correctly shown as expected, but it shows "0" in the port forwarded section. 
![image](https://github.com/user-attachments/assets/6010351e-f262-46d8-951f-e210772be361)

Question: How can I either let the widget show a correct port or get rid of the portforwarded field?

### homepage version

v1.3.0

### Installation method

Docker

### Troubleshooting

```
curl -H "X-API-Key: GENERATED_API_KEY" http://host.docker.internal:8001/v1/openvpn/portforwarded
{"port":0}
```

**Comment by shamoon** [comment, marked as answer]
#2262 Is the culprit here.

You can hide the field by specifying the `fields` property on the widget see https://gethomepage.dev/widgets/services/gluetun/

**Reply by v1rusnl** [reply]
Thanks, that did it. Did not know about the "fields" property. Thanks! But to my understanding, `/v1/openvpn/portforwarded` needs to be accessible from 1.3.0 on to use the gluetun widget without API error, correct?

**Reply by shamoon** [reply]
Yea it’s a breaking change and I’m thinking about how to handle. I don’t use gluetun. Presumably we will make it opt-in, not opt-out.

Perhaps you don’t know, but I assume that all gluetun users will need to edit the config like that, correct? The instructions say similar to get the IP but this wasn’t added for port forwarded.

**Reply by v1rusnl** [reply]
Yeah, at least all gluetun users that just have `routes = [ "GET /v1/publicip/ip"]` solely without `"GET /v1/openvpn/portforwarded"` in their gluetun config.toml. I guess for the most of them like me, this setting was sufficient since this entrypoint reflects public_ip, region and country. If I should guess after reading the purpose of this port forwarding in e.g. ProtonVPN wiki, #2262 use case should be a minority use case.

**Reply by shamoon** [reply]
Thanks for clarifying. Yea I’ll make it “opt-in”

**Reply by av1155** [reply]
Hey, I am trying to fix mine after the update by using `fields` (I also use WireGuard):

```yaml
    - Gluetun:
        icon: gluetun
        href: https://airvpn.org/client/
        description: VPN Tunnel Status
        server: ct-media
        container: gluetun
        showStats: true
        widget:
          type: gluetun
          url: "{{HOMEPAGE_VAR_GLUETUN_URL}}"
          fields: ["public_ip", "region", "country"]
          key: "{{HOMEPAGE_VAR_GLUETUN_KEY}}"
```

But it still errors out, what is the correct way to use "fields"?

```
API Error Information
API Error: The string did not match the expected pattern.
```

My config.toml looks like:

```toml
[[roles]]
name = "homepage"
routes = ["GET /v1/publicip/ip"]
auth = "apikey"
apikey = "API_KEY"
```

**Reply by v1rusnl** [reply]
You need to specify
```
routes = [
  "GET /v1/publicip/ip",
  "GET /v1/openvpn/portforwarded"
]
```
in your Gluetun config.toml routes section. `/v1/openvpn/portforwarded` needs to be included atm also if you're hiding it in the widget.

And this is my working widget conf:
```
    - Gluetun VPN IP:
        icon: gluetun.png
        description: VPN IP und Standort
        widget:
            type: gluetun
            url: http://host.docker.internal:8001
            key: API_KEY
            fields: ["public_ip", "region", "country"]
```

**Reply by shamoon** [reply]
Changing `fields` wont prevent the widget from trying the port_forward endpoint (currently), but if you'd like to test out `dev` I've merged #5345

That will make port_forwarded opt-in, meaning no change needed for you at all, and leaving off "port_forwarded" from `fields` (or not specifying fields at all) will prevent even trying that endpoint

**Reply by shamoon** [reply]
Sorry the dev image is building, just a few minutes: https://github.com/gethomepage/homepage/actions/runs/15376986358/job/43262942118

**Reply by shamoon** [reply]
Ok all set, if either of you are able to verify the change I'd actually like to release it in a patch to avoid other users hitting this.

Thanks

**Reply by av1155** [reply]
@shamoon I tried it out with the following, and it worked, that fixed it:

```yaml
    - Gluetun:
        icon: gluetun
        href: https://airvpn.org/client/
        description: VPN Tunnel Status
        server: ct-media
        container: gluetun
        showStats: true
        widget:
          type: gluetun
          url: "{{HOMEPAGE_VAR_GLUETUN_URL}}"
          key: "{{HOMEPAGE_VAR_GLUETUN_KEY}}"
```

and

```toml
[[roles]]
name = "homepage"
routes = ["GET /v1/publicip/ip"]
auth = "apikey"
apikey = "API_KEY"
```

**Reply by v1rusnl** [reply]
Same, well done @shamoon !

**Comment by kuya1284** [comment]
I seem to be having trouble with the new `port_forwarded` field after updating from **v1.2.0** directly to **v1.3.1**.

![image](https://github.com/user-attachments/assets/272405f0-fde5-44dc-8bbd-7d7cb73f06cd)


However, when I downgrade to **v1.3.0**, the port appears as expected:

![image](https://github.com/user-attachments/assets/ef75f943-c26a-43cc-a0fd-7058f586db59)


In the **v1.3.1** container, I even tested to make sure I was able to fetch the port, and that did appear to work without issues as well:

```
/app # apk add curl
...

/app # curl -H "X-API-Key: [REDACTED]" http://[LOCAL IP]:8000/v1/openvpn/portforwarded
{"port":33632}
```

If I need to create a new issue, I can do that if needed. I figured I'd mention the issue here first just in case someone could provide some insight.

**Gluetun config.toml**
```
[[roles]]
name = "homepage"
auth = "apikey"
apikey  = "[REDACTED]"
routes = [
  "GET /v1/publicip/ip",
  "GET /v1/openvpn/portforwarded"
]
```

**Homepage services.yaml**
```
  - Gluetun:
      icon: gluetun
      href: http://[LOCAL IP]:8000/v1/publicip/ip
      siteMonitor: http://[LOCAL IP]:8000
      server: node-804-docker
      container: qbittorrent-vpn
      widget:
        type: gluetun
        url: http://[LOCAL IP]:8000
        key: [REDACTED]
        fields: [ 'public_ip', 'region', 'country', 'port_forwarded' ]
```
