### DISCUSSION TITLE
Paperless-ngx custom API call returns HTML user login page - but service widget works?!

### DISCUSSION THREAD

**Discussion by bstarke-pi** [gethomepage/homepage#5379] [Support] [answered]
### Description

Hi community,

I would like to switch from the standard Paperless-ngx widget to a custom one to be able to display further information. So I set up the 'customapi' entry in services.yaml and tried to consider the provided guides. I even tried to set it up just like the standard service widget (double-checking the used token, url scheme etc.). Unfortunately, the custom API call doesn't return the expected data. Instead, it returns the HTML user login page of Paperless-ngx in the call's response?!

Of course, I looked for existing/past discussions - and yes, there are some - , but I already took care of things like the trailing slash or the content type. Therefore, I'm stuck.

The interesting thing is: The standard service widget is working flawlessly:
<img width="862" alt="widgets" src="https://github.com/user-attachments/assets/176ddba3-9046-4832-a143-78c6cc7c4447" />

Can anyone help me out?

Headers of Homepage proxy call:
<img width="690" alt="01_Headers" src="https://github.com/user-attachments/assets/b9d427eb-9e5c-4ca3-a2d6-12dfa4fc1a51" />

Response:
<img width="690" alt="02_Response" src="https://github.com/user-attachments/assets/4441d29c-eb60-4c1b-8a0b-758da3812a5c" />

Best and thanks,
Ben

### homepage version

v1.2.0 (2376184, 28. Apr. 2025)

### Installation method

Docker

### Configuration

```yaml
- Paperless-ngx:
        icon: paperless-ngx.svg
        href: https://paperless.-----.org/
        description: Document Manager
        server: pi-docker
        container: paperless-ngx-webserver-1
        widget:
          type: paperlessngx
          url: https://paperless.-----.org
          key: d3b2d-----fa
- Paperless-ngx Custom:
        icon: paperless-ngx.svg
        href: https://paperless.-----.org/
        description: Document Manager
        server: pi-docker
        container: paperless-ngx-webserver-1
        widget:
          type: customapi
          method: GET
          url: https://paperless.-----.org/api/statistics/
          headers:
            Content-Type: application/json
            Accept: application/json
            Authorization: Token d3b2d-----fa
          mappings:
            - field: documents_total
              label: Dokumente
            - field: documents_inbox
              label: Posteingang
```

### Container Logs

Couldn't find any relevant error logs.

### Browser Logs

Brwoser also just says 200, but response is not the expected data, but the HTML user login page of Paperless-ngx (just like described at the top).

### Troubleshooting

I went through the troubleshooting steps, but couldn't find anything helpful... E.g. IPv6 is disabled, container logs don't print anything that can help me out, and since the standard service widget is working, the Homepage container is able to reach Paperless-ngx.
