### DISCUSSION TITLE
Tailscale widget returning code: "ETIMEDOUT" in API Error

### DISCUSSION THREAD

**Discussion by afit21** [gethomepage/homepage#5384] [Support]
### Description

 The following API Error Information output:
 API Error: Unknown error
    URL: https://api.tailscale.com/api/v2/device/[device id redacted]
    Raw Error:
    {
        "errno": -3001,
        "code": "EAI_AGAIN",
        "syscall": "getaddrinfo",
        "hostname": "api.tailscale.com"
    }

### homepage version

v1.3.2

### Installation method

Source

### Configuration

```yaml
- Tailscale:
        icon: https://play-lh.googleusercontent.com/wczDL05-AOb39FcL58L32h6j_TrzzGTXDLlOrOmJ-aNsnoGsT1Gkk2vU4qyTb7tGxRw=w240-h480-rw
        description: VPN
        ping: 192.168.50.73
        href: https://login.tailscale.com/admin/machines
        widget:
          type: tailscale
          deviceid: asdasd2Pl42CNTRL
          key: tskey-api-reDpCyXyu334CNTRL-asfodpjkKSaosjkdapj1231asdOPdsd
```

### Troubleshooting

Essentially just double checked that my config looked correct
Made sure there wasn't any firewall rules, etc blocking this.
Can connect to https://api.tailscale.com/api/v2/device/[device id redacted] with my web browser, though it complains about an invalid API key (as expected, point is, its not being blocked)
