### DISCUSSION TITLE
docker socket-proxy: missing docker

### DISCUSSION THREAD

**Discussion by p1r473** [gethomepage/homepage#5386] [Support]
### Description

Hi, I keep getting the error "missing docker"
I am trying to have docker socket proxy be a separate container from homepage
Do I just need to delete the docker widget?

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/76e570d1-0b76-4426-b61e-6695fe7ef484" />
### homepage version

1.3.2

### Installation method

Docker

### Configuration

```
--- ./homepage/config/widgets.yaml ---


- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- docker:
    name: my-docker
    showAll: true
    showStopped: true


--- ./homepage/config/services.yaml ---
- Services:
    - Homepage:
        icon: homepage.png
        href: http://192.168.1.186:3000
        description: Self-hosted dashboard
        server: my-docker
        container: homepage


--- ./homepage/config/settings.yaml ---
title: My Dashboard
theme: dark
color: slate
layout:
  - Services
  - Links
--- ./homepage/config/docker.yaml ---
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

my-docker:
  host: dockerproxy
  port: 2375

--- ./homepage/docker-compose.yaml ---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./config:/app/config
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.1.186:3000,192.168.1.168:3000"
    networks:
      - docker-net

networks:
  docker-net:
    external: true
--- ./dockersocketproxy/docker-compose.yaml ---
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - docker-net

networks:
  docker-net:
    external: true

```
