### DISCUSSION TITLE
Can I see my netbird network?

### DISCUSSION THREAD

**Discussion by pippo73** [gethomepage/homepage#5387] [Support]
### Description

Hi all, 
I'm running HP as a docker image.
On my host server I have also a netbird network interface. Is there a way to see the traffic of this interface on my HP?

### homepage version

dev (be7e111, 1 giu 2025)

### Installation method

Docker

### Configuration

$ cat widgets.yaml
```

- resources:
    label: System
    cpu: true
    cputemp: true
    memory: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    uptime: true
    units: metric # only used by cpu temp, options: 'imperial' or 'metric'
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
#    network: true # optional, uses 'default' if true or specify a network interface
    network: eth0 # optional, uses 'default' if true or specify a network interface
#    network: wt0 # optional, uses 'default' if true or specify a network interface
    disk: /
    expanded: true

```

### Troubleshooting

hope someone has some good idea for my request :-)
