### DISCUSSION TITLE
customapi widget – additionalField and remap not displaying additional data (e.g. MAC address)

### DISCUSSION THREAD

**Discussion by BBT-nZ** [gethomepage/homepage#5388] [Support]
### Description

Hey Team,

I'm using the customapi widget in dynamic-list mode with an API (through OPNSense) returning DHCP lease data (hostname, IP, MAC). My goal is to show the hostname (left) and IP (right), and ideally also show the MAC address as an additional field or inline.

```
    - Connected Clients:
        icon: /icons/opnsense.svg
        href: https://opnsense.mydomain.org/
        ping: http://10.10.100.1
        widgets:
        - type: customapi
          url: https://opnsense.mydomain.org/dhcp_leases.php
          refreshInterval: 30000 # optional - in milliseconds, defaults to 10s
          display: dynamic-list
          method: GET
          mappings:
            name: hostname
            label: ip
            additionalField:
              field: mac
              format: text
              remap:
                  - any: true
                    to: "MAC: {mac}"
```
Resulting in:

![image](https://github.com/user-attachments/assets/e0e42ee4-a5cf-4ee3-90f7-e0ccd3e94e12)

### homepage version

v1.2.0 (source, Apr 29, 2025) Installed in an LXC under Proxmox

### Installation method

Other (please describe above)

### Container Logs

Executing a curl within the LXC container:

![image](https://github.com/user-attachments/assets/b249d91e-d5da-4f36-ad28-6f63e91475ae)

### Troubleshooting

Google, Official Docs on customapi – After exhausting all options, just for the heck of it, I swapped the IP address field with the MAC address—and it worked! The MAC address displayed correctly. However, as expected, the IP address was no longer shown.

This indicates that the data is being passed through correctly, but the MAC address simply isn’t being displayed when used as an `additionalField` or combined with others.

**Comment by shamoon** [comment]
It’s confusing but I think you’re mixing dynamic list vs list, dynamic-list doesn’t support an additional field

**Reply by BBT-nZ** [reply]
Thanks for looking into this bud, unfortunately based on everything i could learn and pick up. When I attempted using just "list", and accordingly change the mapping. The widget would remain blank.

Are you able to point me in the right direction or assist in any manner? Fairly new to the whole custom api widget thing.

**Reply by shamoon** [reply]
I can (now) see how this is pretty confusing, `list` refers to the display format of the widget but still only works with an api that returns a json object, whereas `dynamic-list` refers to the display but also dynamic-list works with an api response that is a _list_ (also known as an array) of objects, exactly like yours.

In other words, your api snippet above is only compatible with dynamic-list.

(technically you can use the other types but not in the way you’re after)

**Reply by BBT-nZ** [reply]
Thanks for the clarification, Shamoon — that makes a lot of sense now!

Would it be possible to consider a feature enhancement to allow a bit more flexibility in dynamic-list widgets?

Suggestion:

1) Add support for additionalField in dynamic-list, similar to how it's used in other formats

Or, alternatively, allow basic template interpolation in the label value — e.g. something like:

`label: "{ip} | {mac}"`

This would let us show essential data combinations (like IP + MAC) without altering the API structure or resorting to workarounds at the API end.

I totally understand if this adds complexity — but even partial support (e.g., just displaying another value below the label) would make the widget more powerful and user-friendly, especially for monitoring network-related data like DHCP leases.

Thanks again for all the support :D

**Comment by BBT-nZ** [comment]
1.  Decided to beat the system   :P ever so slightly, tweaked the in OPNSense Shell

vi /usr/local/www/dhcp_leases.php

```
<?php
header('Content-Type: application/json');

$leases_file = '/var/dhcpd/var/db/dhcpd.leases';

if (!file_exists($leases_file)) {
    echo json_encode(["error" => "Leases file not found"]);
    exit;
}

$leases_content = file_get_contents($leases_file);
$leases_raw = [];

// Extract all lease blocks
preg_match_all('/lease\s+([\d\.]+)\s+\{([^}]+)\}/m', $leases_content, $matches, PREG
_SET_ORDER);

foreach ($matches as $lease_block) {
    $ip = $lease_block[1];
    $details = $lease_block[2];

    // Only keep active leases
    if (strpos($details, 'binding state active;') !== false) {
        preg_match('/hardware ethernet ([0-9a-f:]+);/i', $details, $mac_match);
        preg_match('/client-hostname "([^"]+)";/i', $details, $host_match);
        preg_match('/ends \d (\d+\/\d+\/\d+ \d+:\d+:\d+);/', $details, $ends_match);

        // Use 'ends' time for deduplication
        $ends = isset($ends_match[1]) ? strtotime($ends_match[1]) : 0;

        // If same IP exists, keep the one with the latest end time
        if (!isset($leases_raw[$ip]) || $leases_raw[$ip]['ends'] < $ends) {
            $leases_raw[$ip] = [
                "ip" => $ip,
                "mac" => $mac_match[1] ?? null,
                "hostname" => $host_match[1] ?? null,
                "ipmac" => "$ip | " . ($mac_match[1] ?? null), // Added this line to combine
                "ends" => $ends
            ];
        }
    }
}

```
  ```

**Confirmation:** 
curl -s https://haifa.nerdbit.org/dhcp_leases.php | jq .

{
    "ip": "10.10.100.140",
    "mac": "XX:XX:XX:XX:aa:dc",
    "hostname": "OPPO-Find-X8",
    "ipmac": "10.10.100.140 | XX:XX:XX:XX:aa:dc"
  },
  {
    "ip": "10.10.100.129",
    "mac": "2c:be:XX:XX:XX:XX",
    "hostname": "Nothing-Phone-1",
    "ipmac": "10.10.100.129 | 2c:be:XX:XX:XX:XX"
  },
  {
    "ip": "10.10.100.131",
    "mac": "7e:XX:XX:XX:XX:f4",
    "hostname": "MacBookPro",
    "ipmac": "10.10.100.131 | 7e:XX:XX:XX:XX:f4"
```

**YAML Changes**

```
    - Connected Clients:
        icon: /icons/opnsense.svg
        ping: http://10.10.100.1
        widgets:
        - type: customapi
          url: https://opnsense.mydomain.org/dhcp_leases.php
          refreshInterval: 10000 # optional - in milliseconds, defaults to 10s
          display: dynamic-list
          method: GET
          mappings:
            name: hostname
            label: ipmac
```

**End Result**

![image](https://github.com/user-attachments/assets/1b2e6202-da10-471f-b162-b274be60d192)

I can finally get some sleep now! Geez.
