### DISCUSSION TITLE
Glances service widget process metric memory usage api error on macos

### DISCUSSION THREAD

**Discussion by Nats-ji** [gethomepage/homepage#5390] [Support] [answered]
### My setup:
- Glances v4.3.1 installed on an M4 Mac mini through homebrew/pip (same issue).
- Homepage v1.3.2 installed on the same machine through docker.

### The issue:
The glances service widget with process metric is having an issue displaying the process memory, it shows {{value, bytes}} instead
![image](https://github.com/user-attachments/assets/5f5b20e4-f72c-40b6-93af-990f8c179466)

### homepage version

v1.3.2 (1a46baa, Jun 2, 2025)

### Installation method

Docker

### Configuration

```yaml
- Server Stats:
    - Process:
        widget:
            type: glances
            url: http://macmini.lan:61208
            version: 4 # required only if running glances v4 or higher, defaults to 3
            metric: process
```

### The cause:
The glances service widget uses `memory_info.data` from the glances API to report the process memory. But the API response from my glances installation doesn't report this value. Is this a macos thing or something wrong with my glances installation?

Sample API response from my glances installation:
```json
[
  {
    "num_threads": 92,
    "status": "R",
    "cpu_percent": 35.1,
    "name": "OrbStack Helper",
    "cpu_times": {
      "user": 96590.089945088,
      "system": 10757.455478784,
      "children_user": 0,
      "children_system": 0
    },
    "pid": 66616,
    "gids": {
      "real": 20,
      "effective": 20,
      "saved": 20
    },
    "memory_info": {
      "rss": 5218746368,
      "vms": 9231707258880,
      "pfaults": 219400565,
      "pageins": 450962
    },
    "nice": 0,
    "memory_percent": 30.37710189819336,
    "key": "pid",
    "time_since_update": 2.8200550079345703,
    "io_counters": [
      0,
      0,
      0,
      0,
      0
    ],
    "cmdline": [
      "[/Applications/OrbStack.app/Contents/Frameworks/OrbStack Helper.app/Contents/MacOS/OrbStack Helper](http://macmini.lan:61208/Applications/OrbStack.app/Contents/Frameworks/OrbStack%20Helper.app/Contents/MacOS/OrbStack%20Helper)",
      "vmgr",
      "-build-id",
      "1748964485",
      "-handoff"
    ],
    "username": "ming"
  }
]
```
