### DISCUSSION TITLE
How do I make resource widget show host machine network stats while running homepage in a docker container?

### DISCUSSION THREAD

**Discussion by askamist** [gethomepage/homepage#5395] [Support]
### Description

I am running homepage in a container for my homelab. enabled resource info widget with `network: true`. It is showing the network stats for the docker container, but I want that of the host machine.

### homepage version

v1.3.2 (1a46baa, Jun 2, 2025)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /app/config
    uptime: true
    network: true

# - search:
#     provider: duckduckgo # google, duckduckgo, bing, baidu, brave or custom
#     focus: true # Optional, will set focus to the search bar on page load
#     showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
#     target: _blank # One of _self, _blank, _parent or _top

- datetime:
    text_size: 2xl
    format:
        timeStyle: short
        hour12: true
```

### Troubleshooting

Not relevant.
