### DISCUSSION TITLE
Typo in kubernetes related logs doesn't propagate the k8s-side error.

### DISCUSSION THREAD

**Discussion by matphilippe** [gethomepage/homepage#5396] [Support]
### Description

Hello :) 

I'd like to report and fix a small bug.
As far as I could see, no existing issues or discussion mention this.

**What's the issue ?**

There is a simple typo I'd like to fix here: 
https://github.com/gethomepage/homepage/blob/34bffe980a5e93d56529401d25dadde5f7b298c8/src/pages/api/widgets/kubernetes.js#L70 (basically, add the missing `%` before the `s` to allow propagating the k8s error).

** How to reproduce **

Just find a way to trigger an error on the metrics api.

For context, I am playing around deploying homepage on my bare-metal kubernetes cluster at home. The setup is janky, so I'm expecting issues.

I do have an issue w.r.t. service discovery and the kubernetes widget:

```
│ [2025-06-08T12:38:37.983Z] error: <widget> Error getting metrics, ensure you have metrics-server installed: s {"code":500,"body":{},"headers":{}}  
```

Can someone go ahead and have a look across the codebase to fix such typos?
I don't mind opening a PR, I should have a bit of time in the coming days.

### homepage version

1.3.2

### Installation method

Docker

### Configuration

```yaml
{
  "apiVersion": "v1",
  "data": {
    "bookmarks.yaml": "- Developer:\n    - Github:\n        - abbr: Sources\n          href: https://github.com/matphilippe/r4pi3r3pi1r0pi2\n",
    "custom.css": "",
    "custom.js": "",
    "docker.yaml": "",
    "kubernetes.yaml": "mode: cluster\ningress: true\n",
    "services.yaml": "",
    "settings.yaml": "title: Coucou <3\n",
    "widgets.yaml": "- kubernetes:\n    cluster:\n      # Shows cluster-wide statistics\n      show: true\n      # Shows the aggregate CPU stats\n      cpu: true\n      # Shows the aggregate memory stats\n      memory: true\n      # Shows a custom label\n      showLabel: true\n      label: \"cluster\"\n    nodes:\n      # Shows node-specific statistics\n      show: true\n      # Shows the CPU for each node\n      cpu: true\n      # Shows the memory for each node\n      memory: true\n      # Shows the label, which is always the node name\n      showLabel: true\n"
  },
  "kind": "ConfigMap",
  "metadata": {
    "creationTimestamp": "2025-06-08T11:51:27Z",
    "labels": {
      "app.kubernetes.io/name": "homepage",
      "kustomize.toolkit.fluxcd.io/name": "homepage",
      "kustomize.toolkit.fluxcd.io/namespace": "flux-system"
    },
    "name": "homepage",
    "namespace": "homepage",
    "resourceVersion": "1543789",
    "uid": "134ae741-cd7c-4cf2-818e-798b2a8d0a98"
  }
}
```

### Container Logs

│ [2025-06-08T12:38:37.983Z] error: <widget> Error getting metrics, ensure you have metrics-server installed: s {"code":500,"body":{},"headers":{}}  

### Browser Logs

{"error":"An error occurred while fetching nodes, check logs for more details."}

### Troubleshooting

This issue occurred while I was troubleshooting, I think the fix may lead to another, deeper discussion around kubernetes related setups.
