### DISCUSSION TITLE
PeaNUT service/widget does not support multiple UPSs

### DISCUSSION THREAD

**Discussion by papperone** [gethomepage/homepage#5397] [Support] [answered]
### Description

I have PeaNUT setup with 2 UPSs, all works perfectly from the PeaNUT GUI.
I added PeaNUT service in Home Page with first UPS and all is good but when I add second service specifying in the "key:" the name of the second NUT server it always shows they data from the first one.
it's definitely a bug as I invert the 2 services configurations I see both with the data of the second UPS (see below my configuration of both services)

### homepage version

v 1.1.1 on LXC Container (ProxMox cluster)

### Installation method

Other (please describe above)

### Configuration

```yaml
- PeaNUT:
        icon: peanut.svg
        href: http://192.168.2.250:3000
        description: UPS Tecnoware on QNAP (LXC)
        widget:
          type: peanut
          url: http://192.168.2.250:3000
          key: qnapups
    - PeaNUT:
        icon: peanut.svg
        href: http://192.168.2.250:3000
        description: UPS EATON on PVE2 (LXC)
        widget:
          type: peanut
          url: http://192.168.2.250:3000
          key: eaton
```

### Troubleshooting

tried to play with the widget/service configuration but no difference, as many istance of PeaNUT service I add all shows always the same data of the first one configured
