### DISCUSSION TITLE
Pi-hole: More than one version 6 widget cannot run

### DISCUSSION THREAD

**Discussion by thierolm** [gethomepage/homepage#5401] [Support] [answered]
### Description

I have two Pi-hole services, including widgets defined in my services.yaml. 
For the last months, one of the services was using Pi-hole version 5 and the other was using version 6.
Yesterday I updated the version 5 service to version 6. Now BOTH are of version 6.

The issue is now that only one widget is working. 

Both configurations are working, if I configure one of them out or vice versa.
 

### homepage version

v1.3.2 (1a46baa, Jun 1, 2025)

### Installation method

Docker

### Configuration

```yaml
services.yaml:

- Network:

    - City1:

        - Pi-hole:
            href: http://192.168.0.XXX
            description: ad-blocker and DNS
            icon: si-pihole-#96060C
            siteMonitor: http://192.168.0.XXX
            widget:
                type: pihole
                url: http://192.168.0.XXX
                version: 6
                key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"

    - City2:

        - Pi-hole:
            href: http://192.168.2.XXX:8080/admin
            description: ad-blocker and DNS
            icon: si-pihole-#96060C
            server: neustadtdocker
            container: pihole-neustadt-pihole-1
            widget:
                type: pihole
                url: http://192.168.2.XXX:8080
                version: 6
                key: "{{HOMEPAGE_VAR_PIHOLE_NEUSTADT_KEY}}"
```

### Container Logs

homepage                | [2025-06-09T15:08:39.418Z] error: <piholeProxyHandler> Error calling Pi-Hole API: 401. Data: {"error":{"key":"unauthorized","message":"Unauthorized","hint":null},"took":5.7220458984375e-05}

### Troubleshooting

I simply commented one or the other Pi-hole widget configuration out and did a stop and start of my homepage docker instance. 

One alone is running,
having both active will lead to an api error for the one which was activated after the other.

![image](https://github.com/user-attachments/assets/7b2c2aed-6f8f-4063-9274-5f4319fd878b)

![image](https://github.com/user-attachments/assets/e8fc5838-5fdc-40ab-878f-ed9eac21623d)

I can turn the sequence of the test and its the same behaviour.
