### DISCUSSION TITLE
Directory `/app/config/logs` created even with stdout log only or with different `logpath` setting

### DISCUSSION THREAD

**Discussion by Songworks** [gethomepage/homepage#5404] [General]
Hello there,

not an issue really, but I wanted to write it down in case somebody else stumbles upon this edge case (I didn't find anything about it yet):

In the docker installation & by default, the logs are written to a file `/app/config/logs/homepage.log` and subsequently to the host if `/app/config/` is a volume as suggested.

On my end I use the environment variable `LOG_TARGETS: stdout` to disable file logging. This works as intended.
I use the PUID & GUID variables also.

Now I've noticed that, even with stdout logging only, an empty directory `/app/config/logs/` is created on container start.

I've also tested it with the `logpath` setting, ie. log to `/tmp` instead. This works as intended also, logs are written to `/tmp/logs/homepage.log`.
But an extra logs-directory is created in the config-directory still.

Having curiosity, I've checked where that might come from and it's probably from here?
https://github.com/gethomepage/homepage/blob/dev/docker-entrypoint.sh#L34

When PUID & GUID are supplied a logs-directory is created and setup with the permissions.
And this seem to happen loooong before any `logpath` or `LOG_TARGETS` is used/checked against.

So that's that.
Cheers!

Boiled down `docker-compose.yml` example:
```yaml
services:
  homepage:
    container_name: network_homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.arpa
      LOG_TARGETS: stdout
      PGID: $PGID
      PUID: $PUID
    image: gethomepage/homepage:v1.3.2
    port:
      3000:3000
    volumes:
      - ./homepage/config:/app/config
```

Container-Log:
```
network_homepage  | /app/config already owned by correct UID/GID, skipping chown
network_homepage  | Fixing ownership of /app/config/logs
network_homepage  | Fixing ownership of /app/.next
network_homepage  |    ▲ Next.js 15.3.1
network_homepage  |    - Local:        http://localhost:3000
network_homepage  |    - Network:      http://0.0.0.0:3000
network_homepage  |
network_homepage  |  ✓ Starting...
network_homepage  |  ✓ Ready in 99ms
```

Troubleshooting:
```
utilities@utilities:~/network$ ls -la ./homepage/config/logs/
ls: cannot access './homepage/config/logs/': No such file or directory

utilities@utilities:~/network$ docker compose up -d --force-recreate homepage
[+] Running 2/2
 ✔ Container network_dockerproxy  Running 0.0s 
 ✔ Container network_homepage     Started 10.4s 

utilities@utilities:~/network$ ls -la ./homepage/config/logs/
total 8
drwxr-xr-x 2 utilities utilities 4096 Jun  9 21:08 .
drwxrwxr-x 3 utilities utilities 4096 Jun  9 21:08 ..
```

PS: Great application by the way!
