### DISCUSSION TITLE
Glances : high CPU usage when checking in Homepage but low CPU usage from glances web app

### DISCUSSION THREAD

**Discussion by lokiiiii** [gethomepage/homepage#5405] [Support]
### Description

Hello everyone,

Just wanted to know if I missed something or if it's the same for everyone : 
I added 4 Glances widget on my homepage : CPU Usage / RAM Usage / Top 5 processes / Top 5 docker containers.

While checking through the Glances web app, Glances is using around 10% max of my CPU, but when checking through Homepage, it's using at least 150% and sometimes can go up to 600%...

I think I checked all the Glances discussions here and couldn't find anything talking about this, so just wanted to check if it's a common issue or if my configuration is off ?

I'm using the official Glances docker image which is up-to-date also.

Thanks everyone 

### homepage version

v1.3.2 (1a46baa)

### Installation method

Docker

### Configuration

```yaml
- Serveur:
  - Utilisation CPU:
      widget:
        type: glances
        url: http://<docker_container>:<port>
        metric: cpu
        version: 4

  - Process:
      widget:
        type: glances
        url: http://<docker_container>:<port>
        metric: process
        version: 4

  - Docker:
      widget:
        type: glances
        url: http://<docker_container>:<port>
        metric: containers
        version: 4

  - Memoire:
      widget:
        type: glances
        url: http://<docker_container>:<port>
        metric: memory
        version: 4
```

### Troubleshooting

tried to enable one widget at a time to check if one is in fault but couldn't find anything
