### DISCUSSION TITLE
Authentik api requires trailing slash, but homepage removes it

### DISCUSSION THREAD

**Discussion by dhop90** [gethomepage/homepage#5409] [Support] [answered]
### Description

Trying to use customapi to query Authentik api that requires trailing slash, but honepage removes it.

### homepage version

v1.3.2

### Installation method

Docker

### Configuration

```yaml
widget:
          type: customapi
          url: 'https://auth.dhop.duckdns.org/api/v3/core/users/'
          method: GET
          headers:
            Accept: application/json
            Authorization: Bearer <token>
          mappings:
            - field: pagination.count
              label: Users
              type: number
```

### Troubleshooting

Authentik requires trailing slash as seen in curl calls:
```
url with trailing slash

$ curl -s -H "Accept: application/json" -H "Authorization: bearer <token>" -H "Content-Type: application/json" https://auth.dhop.duckdns.org/api/v3/core/users/ | jq .pagination
{
  "next": 0,
  "previous": 0,
  "count": 5,
  "current": 1,
  "total_pages": 1,
  "start_index": 1,
  "end_index": 5
}
```
```
url without trailing slash

$ curl -s -H "Accept: application/json" -H "Authorization: bearer <token>" -H "Content-Type: application/json" https://auth.dhop.duckdns.org/api/v3/core/users | jq .pagination
parse error: Invalid numeric literal at line 5, column 10
```

Widget config:
```
       widget:
          type: customapi
          url: 'https://auth.dhop.duckdns.org/api/v3/core/users/'
          method: GET
          headers:
            Accept: application/json
            Authorization: Bearer <token>
          mappings:
            - field: pagination.count
              label: Users
              type: number
```
Error from homepage:
```
API Error: HTTP Error
URL: https://auth.dhop.duckdns.org/api/v3/core/users
Response Data:
"\n\n\n\n<!DOCTYPE html>\n\n<html>\n    <head>\n        <meta charset=\"UTF-8\">\n 
...omitted
```
Notice trailing slash was removed
