### DISCUSSION TITLE
Glances widget with german transaltion doesn't fit the space

### DISCUSSION THREAD

**Discussion by olli991** [gethomepage/homepage#5424] [Support] [answered]
### Description

Hello, I just noticed that the CPU glances Tab is cutting off the text when using german translation because of long text.
Can there be something done to code it like it's not cutting of and shifting the actual info out of scope?
![image](https://github.com/user-attachments/assets/9adf1fd9-625e-4324-9fbb-a5824f53d858)

### homepage version

1.3.2

### Installation method

Source

### Configuration

```yaml
Services.yaml

- Stats:
    - Proxmox Host:
      - Info:
          widget:
            type: glances
            version: 4
            url: http://192.168.178.56:61208/
            metric: info
            chart: false
      - CPU:
           widget:
            type: glances
            version: 4
            url: http://192.168.178.56:61208/
            metric: cpu
            chart: false
      - RAM: 
          widget:
            type: glances
            version: 4
            url: http://192.168.178.56:61208/
            metric: memory
            chart: false
      - Prozesse:
          widget:
            type: glances
            version: 4
            url: http://192.168.178.56:61208/
            metric: process
            chart: false
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting
