### DISCUSSION TITLE
SpeedTest Error - API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### DISCUSSION THREAD

**Discussion by ozdeadmeat** [gethomepage/homepage#5427] [Support]
### Description

I am helping a mate try and sort out his Speedtest. We have almost identical setups but for some reason he is getting this bullshit error and I have checked everything I can think of to validate the config and am completely lost at this stage.

### homepage version

v1.2.0 (2376184, 29 Apr 2025)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see: 
# https://gethomepage.dev/en/configs/services   

- Infrastructure:
#    - Unifi:
#        icon: /icons/unifi.png
#        href: https://unifi.panthro.net/network/default/dashboard
#        description: Unifi Network Statistics
#        widget:
#          type: unifi
#          url: http://192.168.0.2
#          username: <redacted>
#          password: <redacted>
    - SpeedTest:
        icon: /icons/speedtest-tracker.png
        href: https://speedtest.panthro.net
        description: Internet Speed Test
        widget:
          type: speedtest
          url: http://192.168.0.3:8764
    - Pi.Hole:
        icon: /icons/pihole.png
        href: http://pihole.panthro.net/admin
        description: DNS Network Advert Blocker
        widget:
          type: pihole
          fields: ["queries", "blocked_percent", "gravity"]
          url: http://pihole.panthro.net
          key: <redacted> # optional
    - UpTime:
        icon: /icons/uptime.png
        href: https://uptime.panthro.net/status/infrastructure
        description: Service UpTime Monitoring 
        widget:
          type: uptimekuma
          #url: https://uptime.panthro.net
          url: http://192.168.0.3:3001
          slug: infrastructure
    - NginX:
        icon: /icons/nginx.png
        href: https://nginx.panthro.net
        description: nginX Proxy Manager
        widget:
          type: npm
          url: http://192.168.0.3:81
          username: <redacted>
          password: <redacted>
```

### Container Logs

[2025-06-14T05:36:12.454Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://speedtest.panthro.net/api/speedtest/latest

[2025-06-14T05:36:27.589Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://speedtest.panthro.net/api/speedtest/latest

[2025-06-14T05:36:50.071Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://speedtest.panthro.net/api/speedtest/latest

[2025-06-14T05:37:00.791Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://speedtest.panthro.net/api/speedtest/latest

[2025-06-14T05:58:00.426Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://speedtest.panthro.net/api/speedtest/latest

[2025-06-14T05:58:10.945Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://speedtest.panthro.net/api/speedtest/latest

[2025-06-14T06:13:15.200Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://speedtest.panthro.net/api/speedtest/latest

### Troubleshooting

Tried 100000000 different configs, error is ALWAYS the same. Nothing in troubleshooting docs to tell me where the problem is or what json file is busted. all the files i modify are yaml files.
