### DISCUSSION TITLE
Proxmox Widget fails getting information

### DISCUSSION THREAD

**Discussion by LeKanubbel** [gethomepage/homepage#5429] [Support]
### Description

Hello!

I am running homepage in an lxc container. I installed it with the helper script https://community-scripts.github.io/ProxmoxVE/scripts?id=homepage and it seems to working for the most part.

The first node i added doesn't give me an api error but is showing CMS: 0/0 LXC: 0/0  CPU: NaN% MEM: NaN%
The second node is working as expected and is showing everything correctly.
I also used nearly the same config in another proxmox env in another network (so they dont interfere).
I used the same step on all devices.

I added node 1 before adding node 2 and had the same issue. So it shouldn't be because of two nodes there.

Versions:
Homepage version: 1.3.2
Next.js version: 15.3.1
pnpm version: 10.12.1

### homepage version

v1.3.2

### Installation method

Other (please describe above)

### Configuration

```yaml
Here is the config in services.yaml

    - Proxmox Node 1:
        href: https://192.XXX.XXX.XX1:8006/
        description: Guess what it does
        icon: sh-proxmox.png
        ping: 192.XXX.XXX.XX1
        widget:
          type: proxmox
          url: https://192.XXX.XXX.XX1:8006/
          username: homepage@pam!dashboard
          password: my_api_key

    - Proxmox Node 2:
        href: https://192.XXX.XXX.XX2:8006/
        description: Guess what it does
        icon: sh-proxmox.png
        ping: 192.XXX.XXX.XX2
        widget:
          type: proxmox
          url: https://192.XXX.XXX.XX2:8006/
          username: homepage@pam!dashboard
          password: my_api_key
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting


What i tried:
- Redoing all users, groups, api tokens and permissions.
- Checked if users with permissions are pressent on host, which it does.
- Used curl to test the api which loaded for a couple seconds and didn't return anything.
- Checked the logs but there are no errors.
