### DISCUSSION TITLE
PiHole Widget on TrueNAS (docker container "app") API auth issues

### DISCUSSION THREAD

**Discussion by smaniktahla** [gethomepage/homepage#5431] [Support]
### Description

I'm struggling with what is probably something pretty basic. But my PiHole "app" hosted on a TrueNAS server (docker container, basically) gives me an auth error when trying to set it up in Homepage.
![image](https://github.com/user-attachments/assets/689ac158-6988-4845-a98e-f47e8cb5a432)

Any advice or assistance would be greatly appreciated.

### homepage version

v1.3.2

### Installation method

Docker

### Configuration

```yaml
- PiHole:
        icon: pi-hole.png
        href: http://10.10.10.201:20720
        description: DNS and Ad Blocking
        widget:
          type: pihole
          url: http://10.10.10.201:20720/api/auth (but I've also tried http://10.10.10.201:20720 and various permutations, including the V5 way)                                      
          version: 6 
          key: z3afdT9+53VoAOPnHygwMoJAKgwC4ph6CGt/7XT9GXE=#
```

### Container Logs

2025-06-17 17:52:56.707661+00:00[2025-06-17T17:52:56.707Z] [31merror[39m: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 404

### Troubleshooting

curl -k -X POST "http://10.10.10.201:20720/api/auth" --data '{"password":"z3afdT9+53VoAOPnHygwMoJAKgwC4ph6CGt/7XT9GXE="}'

Success!
{"session":{"valid":true,"totp":false,"sid":"pbnfRdjUJVyp0keLPrXIqA=","csrf":"Q/CRKnwzdIw9QhnV2ytVwQ=","validity":1800,"message":"app-password correct"},"took":0.076501607894897461}

I have tried several different permutation in the YAML, regenerating app keys, etc, and curl from different points on my network, with different arguments and flags to try and get things to work. 

![image](https://github.com/user-attachments/assets/8badc26d-e990-4368-b68c-32d901cbf3f1)
