### DISCUSSION TITLE
The Calendar widget report error, log display Maximum number of redirects exceeded

### DISCUSSION THREAD

**Discussion by Westwall98** [gethomepage/homepage#5432] [Support] [answered]
### Description

The Calendar widget report error, which look like rediect issue. But i was keep using this widget. It working well until today. suddenly it display error

![image](https://github.com/user-attachments/assets/df1e99c9-a298-4dc9-9bee-0e0898d0fb72)

### homepage version

1.3.2

### Installation method

Docker

### Configuration

```yaml
- Calendar:
        icon: /icons/calendar.svg
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          maxEvents: 20
          showTime: true
          timezone: UTC
          integrations:
            - type: ical
              url: https://outlook.office365.com/owa/calendar/bxxxxx0/calendar.ics
              name: Together
              color: green
```

### Container Logs

[2025-06-19T10:10:14.142Z] error: <httpProxy> Error calling https://outlook.office365.com/owa/calendar/669xxxxxxx0/calendar.ics...
[2025-06-19T10:10:14.148Z] error: <httpProxy> [
  500,
  Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded
      at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.9/node_modules/follow-redirects/index.js:424:11)
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.9/node_modules/follow-redirects/index.js:102:12)
      at Object.onceWrapper (node:events:632:26)
      at ClientRequest.emit (node:events:517:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at TLSSocket.socketOnData (node:_http_client:541:22)
      at TLSSocket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9) {
    code: 'ERR_FR_TOO_MANY_REDIRECTS'
  }
]

### Troubleshooting

docker exec homepage ping outlook.office365.com

PING outlook.office365.com (40.99.10.66): 56 data bytes                                     
64 bytes from 40.99.10.66: seq=0 ttl=240 time=74.971 ms                                     
64 bytes from 40.99.10.66: seq=1 ttl=240 time=70.377 ms                                     
64 bytes from 40.99.10.66: seq=2 ttl=240 time=67.822 ms                                     
64 bytes from 40.99.10.66: seq=3 ttl=240 time=69.696 ms                                     
64 bytes from 40.99.10.66: seq=4 ttl=240 time=68.004 ms                                     
64 bytes from 40.99.10.66: seq=5 ttl=240 time=72.644 ms                                     
64 bytes from 40.99.10.66: seq=6 ttl=240 time=67.980 ms                                     
64 bytes from 40.99.10.66: seq=7 ttl=240 time=70.199 ms                                     
64 bytes from 40.99.10.66: seq=8 ttl=240 time=69.428 ms                                     
64 bytes from 40.99.10.66: seq=9 ttl=240 time=69.717 ms                                     
64 bytes from 40.99.10.66: seq=10 ttl=240 time=71.299 ms                                    
64 bytes from 40.99.10.66: seq=11 ttl=240 time=69.771 ms                                    
64 bytes from 40.99.10.66: seq=12 ttl=240 time=67.49
