### DISCUSSION TITLE
[Feature Request] Add a Huntarr Service Widget

### DISCUSSION THREAD

**Discussion by gabriellxxix** [gethomepage/homepage#5436] [Feature Requests]
### Description

A dedicated widget for Huntarr—similar to the existing Radarr and Sonarr widgets—so users can quickly glance at their Huntarr activity...

https://github.com/plexguide/Huntarr.io

**Comment by oonqt** [comment]
One problem I see here is Huntarr doesn't provide any API key system to authenticate requests, so Huntarr authentication will have to be disabled or set to local bypass.

Looking at their API, it would be possible to make a custom widget. I'm going to make my own custom widget soon and if you want I can make one to suit your needs, until this gets enough upvotes to become an integrated widget.

Here is a simple one to show the amount of "hunted" content for sonarr, radarr, and readarr. You can easily remove or add others like lidarr, whisparr, etc.


```yaml
  - Huntarr:
      icon: huntarr.png
      href: 
      description: 
      widget:
        type: customapi
        refreshInterval: 10000
        url: http://huntarr:9705/api/stats
        mappings:
          - field: stats.sonarr.hunted
            label: Hunted (Sonarr)
          - field: stats.radarr.hunted
            label: Hunted (Radarr)
          - field: stats.readarr.hunted
            label: Hunted (Readarr)
```
