### DISCUSSION TITLE
BUG: service bg-color breaks with description and glances widget

### DISCUSSION THREAD

**Discussion by KevsterAmp** [gethomepage/homepage#5441] [Support] [answered]
### Description

service background color breaks when description exists with the glances widget:
![image](https://github.com/user-attachments/assets/9b4a3992-4829-497b-b5aa-a06cb16f8e39)
Here's what it looks like without the description:
![image](https://github.com/user-attachments/assets/4149493f-5303-48f7-a1da-eaa92b6aa8da)

## Proposed Fix
https://github.com/gethomepage/homepage/blob/00bb1a3f37940a0c3c681c3eef0a10d3e1fa0053/src/widgets/glances/metrics/info.jsx#L112-L112
I'm not familair with NextJS. But moving this div `bg-linear-to-br` outside of the `div.service-container`. Applies the color to the whole `div.service_card`
```
div.service_card
├── div.service-container
├── div.bg-linear-to-br
```
where originally, it is: 
```
div.service_card
├── div.service-container
    ├── div.bg-linear-to-br
```
![image](https://github.com/user-attachments/assets/1f417044-957b-4aa3-9fab-11a2166e1c2c)

### homepage version

v1.3.2

### Installation method

Docker

### Configuration

```yaml
- Server Stats:
    - Saturn:
        decription: ASUS X455LF
        widget:
          type: glances
          # prettier-ignore
          url: {{HOMEPAGE_VAR_SATURN_GLANCES_URL}}
          version: 4
          metric: info
```

### Container Logs

Container logs are irrelevant

### Browser Logs

Browser logs are irrelevant

### Troubleshooting

Troubleshooting steps is irrelevant, as this seems to be a simple UI fix
