### DISCUSSION TITLE
[Feature Request] Prometheus widget: support Basic Auth

### DISCUSSION THREAD

**Discussion by huyz** [gethomepage/homepage#5449] [Feature Requests] [answered]
### Description

I have my Prometheus installation reverse-proxied and protected with Basic Auth.  Could Basic Auth be added for the Prometheus widget?

I could submit a PR if need be.

### Other

Previous auto-closed ticket: https://github.com/gethomepage/homepage/discussions/1985

**Comment by github-actions** [comment]
This discussion has been automatically closed due to lack of community support. See our [contributing guidelines](https://github.com/gethomepage/homepage/blob/main/CONTRIBUTING.md#automatic-repository-maintenance) for more details.

**Reply by huyz** [reply]
sad

**Comment by shamoon** [comment]
Does it use basic auth as in http basic auth?

**Reply by huyz** [reply]
Yes

**Reply by shamoon** [reply, marked as answer]
The generic proxy handler that the prometheus widget uses supports http basic auth "out of the box", as long as you specify username / password on the widget. Indeed, I confirmed this locally:


```yaml
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/web.yml:/etc/prometheus/web.yml
      - ./config/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./config/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
    labels:
      - homepage.group=Testing
      - homepage.name=prometheus
      - homepage.icon=prometheus.png
      - homepage.href=http://localhost:9090
      - homepage.description=prometheus
      - homepage.widget.type=prometheus
      - homepage.widget.url=http://localhost:9090
      - homepage.widget.username=admin
      - homepage.widget.password=password123456
```

`web.yml`:

```yaml
basic_auth_users:
    admin: $2a$12$3f0aPeMwAcvicvlxhdiuW.2hIiUQUK28EUbajPh5Fy/hKQ8uJI6bu # password123456
```

<img width="388" height="128" alt="Screenshot 2025-12-23 at 10 53 51 AM" src="https://github.com/user-attachments/assets/03644df9-d8ea-45ef-b78f-7398d49b198e" />
