### DISCUSSION TITLE
[Feature Request] New Widget for QNAP QSS (10Gb PoE Switch)

### DISCUSSION THREAD

**Discussion by DJSdev** [gethomepage/homepage#5450] [Feature Requests]
### Description

# Summary 

I want to gauge interest in a QNAP QSS 10Gb PoE Switch widget to be merged into the homepage repo. I've created a widget to display the following information.

- Wattage
- PoE Port Usage
- Total Port Usage
- System temperature. 

 This is what the widget would look like for QNAP QSS Switches on Homepage.

![image](https://github.com/user-attachments/assets/7fe4e70f-dd85-42f1-be61-382b9b6c0c78)

Here's the link to the diff: https://github.com/gethomepage/homepage/compare/dev...DJSdev:homepage:dev

I've tested this widget on both the PoE and non-PoE models of this switch.

- [QSW-M2106PR-2S2T](https://www.qnap.com/en-us/product/qsw-m2106pr-2s2t)
- [QSW-M2106R-2S2T](https://www.qnap.com/en-us/product/qsw-m2106r-2s2t)

Sample `services.yaml` config

```yaml
- Switch:
    - QNAP Switch:
        href: https://url.or.ip.local/
        description: QNAP 10Gb Switch
        icon: qnap.svg
        widget:
            type: qnapqss
            url: https://url.or.ip.local
            username: <username>
            password: <password>
            fields: ["sensor", "poeports", "ports", "wattage"]
```

# Details

## Login

There is no API key unfortunately, so we need to auth with username/password. There is a custom response to the auth call, so I'm not 100% sure if there was already an existing proxy to handle this, so I wrote my own proxy for now.

### POST `/api/v1/users/login`

Request 

```json
{
    "username": "admin",
    "password": "<base64 encoded password>"
}
```

Response

```json
{
    "error_code": 200,
    "error_message": "OK",
    "result": "eyJhbGciOiJS..."
}
```

## API Requests

To gather this information, QNAP QSS has a three API calls to hit, but they've been minimized to reduce the total number.

### GET `/api/v1/poe/port/status`

For the Active Ports and current power consumption

Response

```json 
{
  "error_code": 200,
  "error_message": "OK",
  "result": [
    {
      "key": "1",
      "val": {
        "PowerConsumption": 66,
        "SupportMode": "poePlusDot3bt",
        "CurrentState": "poweredDeviceOn",
        "CurrentStateValue": 133,
        "PDClass": 4
      }
    },
    {
      "key": "2",
      "val": {
        "PowerConsumption": 0,
        "SupportMode": "poePlusDot3bt",
        "CurrentState": "noPoweredDeviceDetected",
        "CurrentStateValue": 168,
        "PDClass": 12
      }
    },
    // etc ...
  ]
}
```

###  GET `/api/v1/poe`

For the maximum PoE power

Response

```json
{
    "error_code": 200,
    "error_message": "OK",
    "result": {
        "PowerManagementMode": "Consumption",
        "MaxPower": 300
    }
}
```

### GET `/api/v1/system/sensor`

For the switch temperature

Response

```json
{
    "error_code": 200,
    "error_message": "OK",
    "result": {
        "Fan1Speed": 4927,
        "Fan2Speed": 4873,
        "MaxFanRpm": 12000,
        "MaxSwitchTemp": 75,
        "SwitchTemp": 45
    }
}
```
