### DISCUSSION TITLE
Recently moved homepage to proxmox on an LXC and not background image

### DISCUSSION THREAD

**Discussion by MsTekkie** [gethomepage/homepage#5463] [Support]
### Description

I recently decided to put a homepage on my Proxmox server. Everything is working fine except the background image and fav icon won't load.   The page isn't breaking, which is good- it loads, but no background image and no favicon.

### homepage version

v1.3.2 (source, Jun 1, 2025)

### Installation method

Other (please describe above)

### Configuration

```yaml
GNU nano 7.2                         settings.yaml                                  
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/


title: YOURMAMASTINKS1000
background:
   image: /images/homepage.png
   opacity: 20
favicon: /images/favicon.ico



providers:
  openweathermap: nunyabiznesssss
  weatherapi: weatherapiapikey
```

### Browser Logs

Failed to load resource: the server responded with a status of 404 (Not Found)Understand this error
3192.168.192.4/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this error
homepage.png:1 
            
            
           GET http://192.168.192.4:3000/images/homepage.png 404 (Not Found)

### Troubleshooting

I have tried Google and ChatGPT to troubleshoot.  The file is there.  The directory is there. on the Proxmox server (everything is local for this container)     ChatGPT is making up stuff at this point.  Has anyone gotten this to work?  If so, how?
