### DISCUSSION TITLE
[Feature Request] Aircraft Tracking (tar1090)

### DISCUSSION THREAD

**Discussion by saviobatista** [gethomepage/homepage#5466] [Feature Requests]
### Description

**Feature Request: Aircraft Status Widget**

**Description**:  
Implement a widget on the homepage that displays live aircraft data (similar to `tar0190-fa` format) for monitoring active flights. The widget should update in real-time, provide key flight metrics, and allow filtering or searching.

---

#### **Context & Use Case**
- Users need quick access to current air traffic without navigating away.
- Examples: Aviation enthusiasts tracking flights, logistics professionals monitoring cargo planes, pilots checking routes, airport staff verifying aircraft movements.
- Reduces reliance on external tools like FlightAware by consolidating data within the platform.

---

#### **Technical Details**
1. **Data Source**:  
   - Fetch real-time data from a reliable aviation API (e.g., ADS-B feeds via `flightradar24`, OpenSky Network, or custom internal systems).
   - Example API response structure:
     ```json
     {
       "aircraft": [
         { "id": "G-ABC1", "callsign": "XYZ123", "altitude": 9000, "speed": 450, "heading": 270, "longitude": -0.123, "latitude": 51.456 }
       ]
     }
     ```

2. **Widget Interface**:  
   - Display a list/grid of aircraft with columns for:
     - Callsign
     - Altitude (ft/m)
     - Speed (knots/km/h)
     - Heading (°)
     - Location (coordinates or simplified map)
   - Use color coding for status (e.g., green = active, gray = standby).
   - Include a "Refresh" button and real-time update interval (5-10 seconds).

---

#### **User Interaction**
- Clicking an aircraft row shows detailed info (flight route, origin/destination, airline logo).
- Search/filter functionality by callsign, ICAO ID, or airline.

---

#### **Implementation Considerations**
- Ensure data accuracy and handle connectivity issues gracefully.
- Design responsive layout to avoid homepage clutter.
- Optional: Add a mini-map for visual reference using tools like Leaflet.js.

---

#### **User Benefits**
- **Efficiency**: Instant access to live flight data without external tabs.
- **Safety**: Monitor aircraft movements during emergencies (e.g., air traffic controller use cases).
- **Engagement**: Enhance user experience for aviation-focused communities.

---

### **Adding a Session Custom Widget: Aircraft Status Widget via API**

If you want to implement an aircraft tracking widget by adding it as a service in `services.yaml`, here's how you can define it:

```yaml
# services.yaml  
- session: Aircraft Status Widget  
    description: "A session for displaying live aircraft status (similar to tar0190-fa)"  
    widget:  
        type: customapi  
        url: http://tar1090-fa:8080/data/aircraft.json  
        display: dynamic-list
        mappings:
            items: aircraft   # Assuming the data structure contains an 'aircraft' array or key.
            name: flight       # The field to display in the widget (e.g., callsign).
            label: hex          # The primary identifier for each aircraft item (e.g., ICAO code).  
        target: http://tar1090-fa:8080/?icao={hex}  # URL template for linking to more details.
```

---

### **Explanation of the YAML Structure**:
- `widget` Configuration:
   - **Type**: `customapi` indicates using external data via an API.
   - **URL**: The endpoint for fetching live aircraft data (e.g., in JSON format).
   - **Display Mode**: `dynamic-list` shows a real-time updating list of tracked items.
   - **Mappings**:
     - `items: aircraft`: Points to the root array or key containing flight objects.
     - `name: flight`: Identifies which property contains the callsign (or name) for each item.
     - `label: hex`: Uses ICAO codes as labels, ensuring unique identification even if multiple aircraft share similar names.
   - **Target**: A URL template that opens detailed views when clicking an item—replace `{hex}` with the actual value.
