### DISCUSSION TITLE
watchtower widget

### DISCUSSION THREAD

**Discussion by henkiewie** [gethomepage/homepage#622] [Support] [answered]
Hi,

I'm trying to get wireguard widget to work following the watchtower docs.
Although the curl command ` curl -H "Authorization: Bearer mytoken" 192.168.1.29:8080/v1/update` triggers an update, the widget shows;
![Screenshot 2022-12-04 at 22 39 26](https://user-images.githubusercontent.com/74558874/205517227-35d1949a-b05c-4250-82f3-0856e48a89db.png)
What am i doing wrong?
Watchtower is running inside a docker container with the ports 8080:8080, the commands and the env variables set according to the example here https://containrrr.dev/watchtower/http-api-mode/

Greetings Henk

**Comment by henkiewie** [comment, marked as answer]
Always nice to solve your own errors.

![Screenshot 2022-12-06 at 08 31 15](https://user-images.githubusercontent.com/74558874/205848964-2de5f305-84a5-4eb9-b875-418290d6996b.png)

The metrics are not published by default and have to be enabled with;
'WATCHTOWER_HTTP_API_METRICS=true'
https://containrrr.dev/watchtower/arguments/#http_api_metrics

Now lets see if the number will show up after a scan.
[edit]
![Screenshot 2022-12-06 at 13 31 12](https://user-images.githubusercontent.com/74558874/205913401-1c9ba314-27e8-4aee-a6d8-b75861abb32a.png)
It does 😄

**Reply by crispybegs** [reply]
i know this is a bit old, but i'm trying to set up a watchtower widget and i'm really struggling to understand how to set up the API so homepage can see it. this is my compose:

```
version: "2"

services:
  app:
    image: containrrr/watchtower
    hostname: 192.168.1.64
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/London
      - NO_COLOR=true
      - WATCHTOWER_SCHEDULE=0 0 19 * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_NOTIFICATIONS=slack 
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/XXXXXX
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower-2 
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#crispy
```

As you can see i have the metrics enabled, but i have no idea how to generate / find the API / token.
There are some notes here - https://containrrr.dev/watchtower/arguments/#http_api_token - about it, but i'm totally unclear on how to implement. 

the error i get from the homepage widget is
```
API Error: Unknown error
URL: http://192.168.1.64:8080/v1/metrics
Raw Error:
{
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "192.168.1.64",
    "port": 8080
}
```

Any chance you could point me in the right direction?

**Reply by henkiewie** [reply]
@crispybegs 

I trhink you have to add some more environment variables to enable metrics and add the token. 
these are mine. I turned on debugging and trace to see more info in the log.
   environment:
          - WATCHTOWER_LOG_LEVEL=trace
          - WATCHTOWER_TRACE=true
          - WATCHTOWER_DEBUG=true
          - WATCHTOWER_HTTP_API_UPDATE=true
          - WATCHTOWER_HTTP_API_METRICS=true
          - WATCHTOWER_HTTP_API_TOKEN=mytoken
          - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
          - TZ=Europe/Amsterdam
          - DOCKER_TLS_VERIFY=true
          - WATCHTOWER_MONITOR_ONLY=false
          - WATCHTOWER_NO_STARTUP_MESSAGE=false
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_SCHEDULE=0 0 7 * * *

**Reply by crispybegs** [reply]
thanks for replying. one of the main places i'm stuck is

- WATCHTOWER_HTTP_API_TOKEN=mytoken

where is that token? how do I create it or find it? i can't find any documentation that actually makes that clear.

**Reply by henkiewie** [reply]
Its the name. And in homepage services.yml it look like this;
   - Watchtower RPI-LITE:
        icon: watchtower
        server: rpi-lite.lan # The docker server that was configured
        description: Updated containers
        container: watchtower
        widget:
          type: watchtower
          url: http://192.168.1.29:8080
          key: mytoken

**Reply by henkiewie** [reply]
@crispybegs 
So the environment variable creates the token. Can be any value If fyou want it more secure.

**Reply by crispybegs** [reply]
hmm ok, so i just amended my compose to this:

```
version: "2"

services:
  app:
    image: containrrr/watchtower
    hostname: 192.168.1.64
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/London
      - NO_COLOR=true
      - WATCHTOWER_SCHEDULE=0 0 19 * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - WATCHTOWER_NOTIFICATIONS=slack 
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/XXXX
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower-2 
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#Crispy
```

and updated my homepage yaml to this

```
    - Watchtower:
        icon: https://github.com/walkxcode/dashboard-icons/raw/main/png/watchtower.png
        href: http://192.168.1.64:8080
        widget:
          type: watchtower
          url: http://192.168.1.64:8080
          key: mytoken
```

but homepage still spits out this error

```
API Error: Unknown error
URL: http://192.168.1.64:8080/v1/metrics
Raw Error:
{
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "192.168.1.64",
    "port": 8080
}
```

..which looks like it may be a connection error to the container? i was previously able to ping 192.68..64:8080 but when I tried again just now the connection reported 'name or service not found'

Actually, edit here: i can ping it successfully with
```
sudo docker exec homepage ping 192.168.1.64:8080
PING 192.168.1.64:8080 (192.168.1.64): 56 data bytes
64 bytes from 192.168.1.64: seq=0 ttl=64 time=0.170 ms
64 bytes from 192.168.1.64: seq=1 ttl=64 time=0.211 ms
64 bytes from 192.168.1.64: seq=2 ttl=64 time=0.250 ms
64 bytes from 192.168.1.64: seq=3 ttl=64 time=0.262 ms
64 bytes from 192.168.1.64: seq=4 ttl=64 time=0.133 ms
64 bytes from 192.168.1.64: seq=5 ttl=64 time=0.255 ms
64 bytes from 192.168.1.64: seq=6 ttl=64 time=0.262 ms
64 bytes from 192.168.1.64: seq=7 ttl=64 time=0.262 ms
```

is there a network variable that should be defined in the compose or am i barking up the wrong tree here?
