### DISCUSSION TITLE
gluetun - widget not working

### DISCUSSION THREAD

**Discussion by Vishnubathala** [gethomepage/homepage#639] [Support]
Hello people can someone help me with this error please

- homepage docker container runs on different docker host
- Gluetun is running is on different docker host (does it matter?)

My services yaml config looks like below 

    - gluetun:
        icon: pipe.png    
        description: vpn
        widget:
            type: gluetun
            fields: ["public_ip", "region", "country"]            
            url: https://192.168.x.x

Error I am getting

API Error: Unknown error
URL: https://192.168.x.x/v1/publicip/ip
Raw Error:
{
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "192.168.x.x",
    "port": 443
}

**Comment by makavelli20** [comment]
same here...

**Comment by mikeofree** [comment]
Okay! So I've officially figured this out! You need to publish port 8000:8000 tcp on your docker container for gluetun (access port for gluetuns control server), and then your widget on services.yaml needs to read url: http://localhost:8000/. I was using port 8155 (gluetun's port) but that is the incorrect port for the http get requests. the control server is what you want to be referring to.

**Reply by undaunt** [reply]
Alternatively, you could create a separate bridge network as described [here](https://github.com/qdm12/gluetun-wiki/blob/main/setup/inter-containers-networking.md#between-a-gluetun-connected-container-and-another-container) and then attach gluetun and homepage to it, then set the widget to http://gluetun-container:8000.

**Comment by Arelius-D** [comment]
@Vishnubathala and @makavelli20 you guys have had any luck getting this sorted out yet?

@mikeofree Please can you explain what you mean with "...on your docker container.." which one? Gluetun? If so I don´t see how you got it working.. _I just tried and not seeing any change anywhere so problem remains_ Please explain how!


`cat $HOME/docker/gluetun/docker-compose.yml`
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000/tcp # Suggested as a possible for solving the error in Homepage, widget for Gluetun
      - 8888:8888/tcp
      - 6881:6881/tcp # qBittorrent torrenting port
      - 6881:6881/udp # qBittorrent torrenting port
    volumes:
      - ./:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=LOST_IT
      - WIREGUARD_ADDRESSES=NEAR_THE_MOON/32
      - SERVER_CITIES=STAR_CITY
      - TZ=Europe/Stockholm
      - UPDATER_PERIOD=24h
    restart: unless-stopped
```

@undaunt that post is so hard to understand and to replicate/follow.. Do you think you can explain it? Your time and effort would be greatly appreciated!

**Reply by mikeofree** [reply]
You need to publish port 8000:8000 tcp on your docker container for gluetun (so do this on gluetuns container). 

Also, did you read the homepage wiki and gluetun wiki for enabling http control server? you need this to be able to sent http requests for the widget to work properly. this is the first step you should be performing before you add any ports on your container. without enabling the http control server, your open port won’t have any services running through it. (hence why your problem still remains).

add the following environments to your gluetun container: 

HTTP_CONTROL_SERVER_ADDRESS=:8000
HTTP_CONTROL_SERVER_LOG=ON

now make sure your widget is referencing the 8000 port.

**Reply by Arelius-D** [reply]
Thank you for your replay.

So you are referring to [this ](https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/control-server.md) right? _I'm new to Linux so just cause I read or tried dosn't mean I actually understand it all, but yeah I did some time ago when I installed Gluetun for the first time. Ask me if I remember anything.. No I do not Sir!_

So I add those lines im my .yml for Gluetun in the proper place ofc and then edit my services.yml for Homage and that should do it you mean?

Btw, another container I'm running called [ddns-updater](https://github.com/qdm12/ddns-updater) is using that port already though. Is it ok to continue anyway?

**Comment by mikeofree** [comment]
since your other container (ddns-updater) is already using port 8000, you can choose a different port (ex. 9075) for under the environment variable for the http control server to use.  and then use that port on the container as well. 

ex. 9075:9075/tcp

**Reply by Arelius-D** [reply]
Thank you for your time and guidance. You are an absolute genius!

**Comment by Arelius-D** [comment]
So guys, since it works for me now, I though I might share and hopefully be helpful for others who will run into the same issue.

Here is how my .yml's look like.

**Gluetun** _docker-compose.yml_
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9075:9075/tcp #HTTP Control Server
      - 6881:6881/tcp # qBittorrent torrenting port
      - 6881:6881/udp # qBittorrent torrenting port
      - 8888:8888/tcp # Don't know why I have this here
#     - 8085:8085 # Don't know why I have this here
    volumes:
      - ./:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=LOST_IT
      - WIREGUARD_ADDRESSES=NEAR_THE_MOON/32
      - SERVER_CITIES=STAR_CITY
      - TZ=Europe/Stockholm
      - UPDATER_PERIOD=24h
      - HTTP_CONTROL_SERVER_ADDRESS=:9075
      - HTTP_CONTROL_SERVER_LOG=ON
    restart: unless-stopped
```

**Homepage** _services.yml_

```
- Services:
    - Gluetun:
       icon: gluetun.png
       ping: http://10.0.0.10:9075
       description: Configured with Mullvad VPN, WireGuard
       widget:
         type: gluetun
         fields: ["public_ip", "region", "country"]
         url: http://10.0.0.10:9075
```

Remember to run `docker compose down` for Gluetun and `...up -d` and so you should get following resultat.

![image](https://github.com/gethomepage/homepage/assets/168124713/a199bdfa-495c-4ac5-a23a-5ed412b66a1a)


**All credit for this rather elegant "solutions" goes to everyone else in this post, specially @mikeofree!**
