### DISCUSSION TITLE
Add storage to glances widget

### DISCUSSION THREAD

**Discussion by phampyk** [gethomepage/homepage#672] [Feature Requests] [answered]
Hello! Thank you so much for the amazing work, I'm loving it so far, and I was wondering if there's a possibility to add storage to the glances widget, so I can control the storage on my nas from the website (I've got homepage installed on my raspberry pi). And if so to choose which HDD to see, same as the resources widget, and the possibility of having it "expanded" as the resources.
Maybe I'm asking for too much, but thank you so much for your time!

**Comment by IIIdefconIII** [comment]
This would be awesome!

**Comment by dreulavelle** [comment]
So much info in Glances that I'm surprised to see only CPU and RAM being used from it. Could be limitations set by glances though.

I'm also interested in using this since NFS mounts don't work natively.

**Reply by northernpowerhouse** [reply]
i'm just setting up glances now, for the homepage integration, what did you enable in glances, I assume one of [these](https://glances.readthedocs.io/en/latest/gw/index.html)?

**Comment by JazzFisch** [comment]
@phampyk I would encourage you to make an issue if you would like to see the glances info widget enhanced.  Thanks.

**Comment by Shadester** [comment]
Is it also possible to open the glances webpage from clicking on the widget?

**Comment by crispybegs** [comment]
+1 for storage

**Comment by SeeYouDown** [comment]
+3

**Comment by gantoine** [comment, marked as answer]
Came across this thread today after getting homepage/glances widgets setup, and was able to whip something up https://github.com/benphelps/homepage/pull/1534

Feedback on the style/implementation is welcome and appreciated!

<img width="683" alt="Screenshot 2023-04-29 at 9 15 18 PM" src="https://user-images.githubusercontent.com/3247106/235331823-a5f8c8a9-06d9-4544-bcfd-e470312f74a9.png">

**Reply by crispybegs** [reply]
hey man, can you possibly paste an example of how you get the disk space to show?

For example I have:

```
- glances:
    label: Plex Server # optional
    cpu: true
    memory: true
    disk: /home/crispy/drives/drive1
    url: http://192.168.1.63:61208
    cputemp: true # disabled by default
    uptime: true # disabled by default
    units: metric

- glances:
    label: Elitedesk 1 # optional
    cpu: true
    memory: true
    disk: /
    url: http://192.168.1.49:61208
    cputemp: true # disabled by default
    uptime: true # disabled by default
    units: metric
```

When homepage refreshes I can see the disk icons appear for a split-second in the widget, then they disappear, so I'm clearly getting something wrong here. I just end up with this every time:

<img width="412" alt="Screenshot 2023-08-27 at 04 10 51" src="https://github.com/benphelps/homepage/assets/129169122/abe3feac-39f1-46e3-98ab-2db7834021a3">
