### DISCUSSION TITLE
Changing the config files does not have any effect

### DISCUSSION THREAD

**Discussion by turkishgetup** [gethomepage/homepage#686] [Support]
I launched the container via docker-compose as suggested in the readme. It installs perfectly fine and seems very responsive, but no matter in what way I change the yaml-files in the config folder, there are no changes whatsoever to the actual homepage-dashboard. Restarting the container also doesn't do anything to that end...

Where could this go wrong? Btw. I'm running it on a Synology NAS, if that's of any relevance...
Thanks!

**Comment by shamoon** [comment]
Did you map the config dir? If you did perhaps permissions are the issue
Eg
```
volumes:
      - /path/to/config:/app/config
```

see https://gethompage.dev

**Reply by turkishgetup** [reply]
Thanks for the reply. I did map the volume, this is my docker-compose.yml
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
````

The folder "config" exists and both it and it's contained files are all owned and set with rw permissions for the admin (that is also launching the container).
