### DISCUSSION TITLE
[Bug] Portainer widget not working, error 404

### DISCUSSION THREAD

**Discussion by hvmzx** [gethomepage/homepage#701] [Support] [answered]
### Description

I have multiple widgets working but when it comes to portainer it doesn't. I deploy everything through docker compose and all the widgets work perfectly fine, I get this error on portainer though 
![image](https://user-images.githubusercontent.com/14812057/208743151-0af8d031-7d60-4af0-b5a0-65539b3b0eaf.png)

The url showing in the api call is a bit weird imo, it has 2 '/' at some point in it.

Also, I ssh'd into the docker container of homepage, and ran the curl command to the api of Portainer and it works: ```
curl -L -H 'X-Api-Key:ptr_MYKEY=' 'http://172.29.0.6:9000/api/endpoints/2/d
ocker/containers/json'
``

I really don't understand what could be wrong, containers communicate perfectly and this is my config as well for the service yaml

```
  - Portainer:
      icon: portainer.png
      href: http://localhost:9000
      description: Docker Manager
      server: my-docker
      widget:
        type: portainer
        url: http://172.29.0.6:9000
        key: KEY
```

I also tried with the url : `http://portainer:9000` and it doesn't work.

Hope you guys have a solution for this because I can't find anything <3

### Steps to reproduce

1. Setup homepage through docker compose
2. Add Portainer service and widget
3. Check connection between protainer and homepage containers
4. Check portainer widget

### homepage version

v0.5.5

### Installation method

Docker
