### DISCUSSION TITLE
[Bug] Locale isn't correct (NL)

### DISCUSSION THREAD

**Discussion by Macleykun** [gethomepage/homepage#751] [Feature Requests] [answered]
### Description

![image](https://user-images.githubusercontent.com/26381427/210134690-a7b70a64-be23-4fae-98e0-7d89f3ceca29.png)
Below is the current timezone i am in with the correct formatting. But when i look at homepage with the following config:
```yaml
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
```
It doesn't look correct, the same seems to be for the long dateStyle.
![image](https://user-images.githubusercontent.com/26381427/210134726-1d74e7eb-d533-4377-81bc-2618e82f0356.png)
This may be intentional, but i would expect it to say 31 December (dd-mm-yy) but it seems to use (mm-dd-yy).

I've also tried with the mdm docs to force the format myself, but i'm sadly unable to find out how to do that.

### Steps to reproduce

Configure widgets.yaml with the datetime and be in NL/EU.

### homepage version

v0.5.8 (0e1aeaf, Dec 30, 2022)

### Installation method

Docker

### Configuration

```yaml
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
```

### Container Logs

[2022-12-31T11:20:40.393Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
[2022-12-31T11:20:40.393Z] error: Error: All docker servers failed to connect or returned no containers

It spams this, but my container stats do work, i only configured this in the docker.yaml:
```yaml
my-docker:
  socket: /var/run/docker.sock
```
And it has the socket and looks to also be in working order.

### Browser Logs

![image](https://user-images.githubusercontent.com/26381427/210134930-b8365e4c-8adc-42e4-815f-77e324c0e7c5.png)
(not sure if relevant but it does have two entries)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment, marked as answer]
The formatting of these comes from the browser (system usually), but see https://gethomepage.dev/en/configs/settings/#language

those other errors should be sorted in the last release

**Reply by Macleykun** [reply]
Yup, i think it detected EN for some reason, i also noticed memory now say's vrij (which is the dutch equivalent).

One final question, is it possible to disable Discovery? Then i can suppress: No containers were found with homepage labels. message :)

Thank you for time and work in Homepage, i really love it!

**Reply by Macleykun** [reply]
Heya, i looked a bit at it again and wanted to give it another go. How would you specify the locales for the datetime for the netherlands?
I would believe like so:
```yaml
- datetime:
    text_size: xl
    format:
      dateStyle: medium
      timeStyle: short
      hour12: false
      locales: nl
```
I try to get it as:
![image](https://user-images.githubusercontent.com/26381427/210639972-45a68cb6-bd82-41c3-aad4-7ef7068f264c.png)

but i keep getting:
![image](https://user-images.githubusercontent.com/26381427/210640002-9d9d6b14-cf34-4620-84d1-297ee15c919f.png)

You have an idea where i might be misunderstanding the syntax perhaps?
