### DISCUSSION TITLE
API Error instead of my hdd monitoring

### DISCUSSION THREAD

**Discussion by colmaris** [gethomepage/homepage#792] [Support]
### Description

 I  configure ressources widget to show cpu memorie and disks used. It works fine for the cpu and the memorie but not for the disks. I have "API error" intead the space used from the disks.

### Steps to reproduce

Open in browser.

### homepage version

v0.5.9 (f6b1304, Dec 31, 2022)

### Installation method

Docker

### Configuration

```yaml
this my widget.yml

 - resources:
      cpu: true
      memory: true
  
 - resources:
      labels: Nas - Films - Series
      expanded: true
      disk:
        - /dev/sdb1
        - /dev/sdc1
        - /dev/sdd1
```

### Container Logs

[2023-01-07T18:15:12.870Z] error: (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

### Browser Logs

scheme
	https
host
	voljin.draconis.me
filename
	/api/widgets/resources
type
	disk
target
	/mnt/nas
Adresse
	10.34.85.1:3128
État
404
Not Found

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
