### DISCUSSION TITLE
Can't get icons, favicon or background to work at all

### DISCUSSION THREAD

**Discussion by ozdeadmeat** [gethomepage/homepage#803] [Support] [answered]
### Description

following the instructions on the site I have generated a widget config with 

- logo:
     icon: /images/OzDM.png

### Steps to reproduce

use the config below

version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3030:3000
    volumes:
      - homepage-config:/app/config # Make sure your local config directory exists
      - homepage-images:/app/public/images #For images
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    networks:
      - homepage
volumes:
  homepage-config:
    name: homepage-config
  homepage-images:
    name: homepage-images
networks:
  homepage:
    name: homepage

### homepage version

v0.5.10

### Installation method

Docker

### Configuration

```yaml
##widgets.yaml

---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

#- resources:
#    cpu: true
#    memory: true
#    disk: /
- logo:
     icon: /images/OzDM.png

- datetime:
    text_size: 2x1
    format:
      dateStyle: short
      timeStyle: short
      hour12: false

- search:
    provider: google
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank

- openmeteo:
    label: Canberra # optional
    latitude: -35.282001
    longitude: 149.128998
    timezone: Australia/Sydney # optional
    units: metric # or imperial
    cache: 10 # Time in minutes to cache API responses, to stay within limits

##settings.yaml

title: home.pwn.net
headerStyle: clean
favicon: /images/favicon.ico
background: /images/20221003_113445.png
backgroundOpacity: 0.5
theme: dark # or light
color: gray
language: en-AU
layout:
  Downloaders:
    style: row
    columns: 2
  Media Managers:
    style: row
    columns: 3
  Streaming Server:
    style: row
    columns: 2
  Infrastructure:
    style: row
    columns: 2
  Docker Managers:
    style: row
    columns: 2
```

### Container Logs

Listening on port 3000
No containers were found with homepage labels.
Listening on port 3000

### Browser Logs

how?

### Other

-

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
