### DISCUSSION TITLE
How to setup Traefik widget (basic auth)

### DISCUSSION THREAD

**Discussion by williamwoldum** [gethomepage/homepage#818] [Support] [answered]
Hi, new to homepage but enjoying it very much so far.

I've successfully set up a lot of widgets including pi-hole, npm, and portainer.
But I cannot get the traefik widget to successfully fetch the api data.

It is my understanding that most traefik containers are setup with basic auth to access the traefik dashboard, including my instance.
Meaning that I can do something like this to request the data `https://username:password@example.com`.

And it works, if I enter my homepage docker container I can curl the endpoint and get a JSON response.

```
/app # curl https://williamwoldum:x...a@traefik.local.williamwoldum.dev/api/overview
{"http":{"routers":{"total":10,"warnings":0,"errors":0},"services":{"total":8,"warnings":0,"errors":0},"middlewares":{"total":13,"warnings":0,"errors":0}},"tcp":{"routers":{"total":0,"warnings":0,"errors":0},"services":{"total":0,"warnings":0,"errors":0},"middlewares":{"total":0,"warnings":0,"errors":0}},"udp":{"routers":{"total":0,"warnings":0,"errors":0},"services":{"total":0,"warnings":0,"errors":0}},"features":{"tracing":"","metrics":"","accessLog":true,"hub":false},"providers":["Docker","File"]}
```

Yet the homepage dashboard looks like this:
![image](https://user-images.githubusercontent.com/41169797/212477965-859bb0a1-5272-402d-ad4b-679bc02b3749.png)

If I take a look at the faulty request from the dashboard it looks like this:
![image](https://user-images.githubusercontent.com/41169797/212478088-3644b446-6c4f-4732-963c-d83becefdadb.png)
And the response like this:
![image (1)](https://user-images.githubusercontent.com/41169797/212478176-2a8c1e95-57e3-4e50-a29b-f0e8b59cdd77.png)
Not sure what this means or if it's even an authorization error 

This is my current config (based of https://gethomepage.dev/en/services/traefik/ )
```
      - Traefik:
            icon: traefik.png
            href: https://traefik.local.williamwoldum.dev
            description: Proxy manager
            widget:
                type: traefik
                url: https://williamwoldum:x5...a@traefik.local.williamwoldum.dev

```

Is this a bug or should I put something else in the `url` attribute
Thanks in advance
