### DISCUSSION TITLE
Portainer widget CPU MEM RX TX fields - how can I configure these please?

### DISCUSSION THREAD

**Discussion by cubagithub** [gethomepage/homepage#860] [Support]
### Description

My Portainer widget is configured according to https://gethomepage.dev/en/services/portainer/ and I only see Allowed fields: `["running", "stopped", "total"]`. 
In this post https://www.reddit.com/r/selfhosted/comments/wx8knv/ive_created_a_new_selfhosted_dashboard/ by phelpsben his screenshot shows CPU MEM RX TX fields - how can I configure these please?

### Steps to reproduce

1. configure portainer service according to https://gethomepage.dev/en/services/portainer/
2. observe no CPU/memory resource fields available

### homepage version

v0.5.10 (e1799f1, Jan 8, 2023)

### Installation method

Docker

### Configuration

```yaml
- Portainer:
        icon:   portainer.png  
        href: http://192.168.0.99:9000
        description: Container management
        widget:
            type: portainer
            fields: ["running", "stopped", "cpu", "mem"]
            url: http://192.168.0.99:9000
            env: 2
            key:
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
This is not a bug friend

https://gethomepage.dev/en/configs/docker/#services

**Comment by cubagithub** [comment]
Sorry I don't understand what you're directing me to do here.

Since you've sent me that link, I've made these changes below, but still don't understand how this would give me resources metrics from Portainer... could you please elaborate? It's not clear from the docs.

**docker.yaml**
```yaml
my-docker:
  host: 127.0.0.1
  port: 2375
```

**services.yaml**
```yaml
...
    - Portainer:
        icon:   portainer.png  
        href: http://192.168.0.99:9000
        description: Container management
        server: my-docker # The docker server that was configured
        container: portainer # The name of the container you'd like to connect
        widget:
            type: portainer
            fields: ["running", "stopped", "cpu", "mem"]
            url: http://192.168.0.99:9000
            env: 2
            key: 'ptrXXXXX'
```

**docker-compose.yaml**
```yaml
...
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
        - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
        - 2375:2375
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: 10m
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
```
