### DISCUSSION TITLE
OctoPrint

### DISCUSSION THREAD

**Discussion by mwarner416** [gethomepage/homepage#928] [General]
Hello,

I've attempted to add octoprint to my services.yaml.  On the dashboard I have this error.  

`Missing Widget Type: octoprint`

```
    - OctoPrint:
        widget:
           type: octoprint
           field: ["printer_state", "temp_tool", "temp_bed", "job_completion"]
           url: http://192.168.1.213
           key: SUPERDUPERSECRETAPIKEY
```

Does anyone have any suggestions?
