### DISCUSSION TITLE
Page constantly refreshes

### DISCUSSION THREAD

**Discussion by KeenBockwurst** [gethomepage/homepage#943] [Support]
### Description

hey there,

the page does constantly refresh without stopping.

### Steps to reproduce

Just go on the page

### homepage version

v0.6.6

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations    
    restart: unless-stopped
      
volumes:
  config:
```

### Container Logs

Empty except a constant repeat of:

[2023-02-05T18:59:37.834Z] error: <httpProxy> Error calling https://photoprism.error/...
[2023-02-05T18:59:37.834Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN photoprism.error
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'photoprism.error'
  }
]

I disabled the ping for the host without any success

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
