### DISCUSSION TITLE
Deluge widget give API error when instance's address is https://host.domain.tld/USER/deluge.

### DISCUSSION THREAD

**Discussion by animakarkia** [gethomepage/homepage#951] [Support] [answered]
### Description

Deluge widget gives api error when deluge instance's address is in the form of https://host.domain.tld/USER/deluge. I have tried to include base url in the services.yml to no avail.

![Screenshot 2023-02-06 at 16 59 02](https://user-images.githubusercontent.com/104270828/217005913-6badb104-3223-43dc-ba19-9d5deb93204b.png)

### Steps to reproduce

The widget links to the deluge instance just fine, but that's just about it.

### homepage version

v0.6.6 (29e0b30, Feb 2, 2023)

### Installation method

Docker

### Configuration

```yaml
- P2P:
    - Deluge:
        icon: deluge.png
        href: https://host.domain.tld/USER/deluge
        widget:
            type: deluge
            url: https://host.domain.tld/USER/deluge/
            password: mypass
```

### Other

Only base url reference I found whilst consulting the documentation dealt with the actual homepage instance being deployed to a subfolder opposed to subdomain. This would lend me to believe that there's an assumption that the homepage user has total access to the services. Seedboxes usually do fall short from this.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Try removing the trailing slash / from widget URL

If that doesn't work, please provide output from the troubleshooting guide that you indicated above you did, e.g. `curl` calls

**Comment by animakarkia** [comment]
My apologies for overlooking the documentation for troubleshooting. I didn't see anything pertaining to deluge as I was skimming through it.

I adjusted the widget configuration as you suggested:
```
- P2P:
    - Deluge:
        icon: deluge.png
        href: https://host.domain.tld/USER/deluge
        widget:
            type: deluge
            url: https://host.domain.tld/USER/deluge
            password: mypass
```
Still does not work.

After this, I consulted the deluge documentation here: https://deluge.readthedocs.io/en/latest/devguide/how-to/curl-jsonrpc.html

I installed curl to the homepage container, created curl.cfg and connected to the deluge instance as per the documentation.
```
~/dev # cat curl.cfg 
request = "POST"
compressed
cookie = "cookie_deluge.txt"
cookie-jar = "cookie_deluge.txt"
header = "Content-Type: application/json"
header = "Accept: application/json"
url = "https://host.domain.tld/USER/deluge/json"
write-out = "\n"

~/dev # curl -d '{"method": "auth.login", "params": ["mypass"], "id": 1}' -K curl.cfg
{"id": 1, "result": true, "error": null}

~/dev # cat cookie_deluge.txt
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

host.domain.tld       FALSE   /USER/deluge/json     FALSE   1675764191      _session_id     d7c097676bfafbbfb1f4f12075ccb0f72433
```
From what I can tell, connecting to deluge instance from container works perfectly fine.
