### DISCUSSION TITLE
Auto discovery not working

### DISCUSSION THREAD

**Discussion by Nindouja** [gethomepage/homepage#956] [Support]
### Description

Since a while my homepage does not display any services that used to be auto discovered from labels. In the mean time I have made changes to my stack but I don't remember the exact timeline so they may or may not be the cause. Anyway I have tried commenting all homepage labels except for one container and it does not fix the problem.

Some services defined explicitly in the yaml files does show up. But the whole application takes an awful long to start; like 5 to 10 minutes. 

### Steps to reproduce

I don't really have an exact procedure. But you can check my confs below. 

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
I don't know how to condense my conf without removing a potential cause. But i suspect the problem is either 
- in the definition on my homepage container: https://gitlab.com/vba-mirrors/media-server-install/-/blob/authelia/docker-compose.yml
- in the homepage conf files: https://gitlab.com/vba-mirrors/media-server-install/-/tree/authelia/resources/homepage
```

### Container Logs

``` logs
Listening on port 3000

[2023-02-07T01:03:38.694Z] debug: No containers were found with homepage labels.

[2023-02-07T01:03:39.768Z] debug: No containers were found with homepage labels.

[2023-02-07T01:03:44.328Z] debug: No containers were found with homepage labels.
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
