### DISCUSSION TITLE
Icon Names Pre Coded?

### DISCUSSION THREAD

**Discussion by bam7** [gethomepage/homepage#969] [Support]
### Description

Are icon names pre coded somewhere?  Meaning, do I have to use  an exact name for an icon to show up?   I see this behavior occasionally when adding a service and I just noticed it with the new Uptime-Kuma widget.   I tried to use an icon named uptime.png and define it in the config, but it won't load.   When I rename the icon file to uptime-huma.png it loads fine.   Is there something I am missing in how image files need to be named?

### Steps to reproduce

    - Uptime Kuma:
         icon: uptime.png   <--- doesn't load

    - Uptime Kuma:
         icon: uptime-kuma.png   <---- loads fine

### homepage version

v0.6.7 (f8a0c69, Feb 7, 2023)

### Installation method

Docker

### Configuration

```yaml
- Uptime Kuma:
         icon: uptime-kuma.png
         href: <URL>
         widget:
            type: uptimekuma
            url: <URL>
            slug: default
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
