### DISCUSSION TITLE
How do I update my docker container?

### DISCUSSION THREAD

**Discussion by rcook55** [gethomepage/homepage#979] [Support]
I'm sure the answer is stupid simple but I can't for the life of me figure out the update command for docker. I'm on  version .6.2

```
cat docker-compose.yml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3100:3000
    volumes:
      - /opt/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```
