### DISCUSSION TITLE
trouble deploying

### DISCUSSION THREAD

**Discussion by VinneyUK** [gethomepage/homepage#985] [Support]
### Description

Hi,

When deploying the container either via CLI or Portainer, I get no errors. However when attempt to pull the GUI, it doesn't connect?

docker-compose.yml looks like:

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    user: 0:0
    ports:
      - 8180:8180
    volumes:
      - /home/dietpi/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
```

```
root@DietPi:/home/dietpi/homepage# ls
config	docker-compose.yml
root@DietPi:/home/dietpi/homepage# 

```

```
root@DietPi:/home/dietpi/homepage# docker compose up -d --force-recreate
[+] Running 12/12
 ⠿ homepage Pulled                                                                        7.7s
   ⠿ 8921db27df28 Pull complete                                                           0.6s
   ⠿ a227f84207da Pull complete                                                           4.5s
   ⠿ 3f754d9a0294 Pull complete                                                           4.7s
   ⠿ 982901c2dfd7 Pull complete                                                           4.8s
   ⠿ ee5f5ad29798 Pull complete                                                           4.9s
   ⠿ 21b5f9bf1eaa Pull complete                                                           4.9s
   ⠿ 7add08d5f98d Pull complete                                                           5.0s
   ⠿ 424d942b070f Pull complete                                                           6.0s
   ⠿ 4c3baf0595b6 Pull complete                                                           6.2s
   ⠿ 24be793e27be Pull complete                                                           6.3s
   ⠿ 4eceb5bcfb00 Pull complete                                                           6.3s
[+] Running 2/2
 ⠿ Network homepage_default  Created                                                      0.1s
 ⠿ Container homepage        Started                                                      0.5s
root@DietPi:/home/dietpi/homepage# 
```

```
root@DietPi:/home/dietpi/homepage# docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                    PORTS                                                           NAMES
d7d9f685b730   ghcr.io/benphelps/homepage:latest   "docker-entrypoint.s…"   45 seconds ago   Up 44 seconds (healthy)   3000/tcp, 0.0.0.0:8180->8180/tcp, :::8180->8180/tcp             homepage

```
Any ideas?

### Steps to reproduce

docker-compose.yml looks like:

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    user: 0:0
    ports:
      - 8180:8180
    volumes:
      - /home/dietpi/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
```

```
root@DietPi:/home/dietpi/homepage# ls
config	docker-compose.yml
root@DietPi:/home/dietpi/homepage# 

```

```
root@DietPi:/home/dietpi/homepage# docker compose up -d --force-recreate
[+] Running 12/12
 ⠿ homepage Pulled                                                                        7.7s
   ⠿ 8921db27df28 Pull complete                                                           0.6s
   ⠿ a227f84207da Pull complete                                                           4.5s
   ⠿ 3f754d9a0294 Pull complete                                                           4.7s
   ⠿ 982901c2dfd7 Pull complete                                                           4.8s
   ⠿ ee5f5ad29798 Pull complete                                                           4.9s
   ⠿ 21b5f9bf1eaa Pull complete                                                           4.9s
   ⠿ 7add08d5f98d Pull complete                                                           5.0s
   ⠿ 424d942b070f Pull complete                                                           6.0s
   ⠿ 4c3baf0595b6 Pull complete                                                           6.2s
   ⠿ 24be793e27be Pull complete                                                           6.3s
   ⠿ 4eceb5bcfb00 Pull complete                                                           6.3s
[+] Running 2/2
 ⠿ Network homepage_default  Created                                                      0.1s
 ⠿ Container homepage        Started                                                      0.5s
root@DietPi:/home/dietpi/homepage# 
```

```
root@DietPi:/home/dietpi/homepage# docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                    PORTS                                                           NAMES
d7d9f685b730   ghcr.io/benphelps/homepage:latest   "docker-entrypoint.s…"   45 seconds ago   Up 44 seconds (healthy)   3000/tcp, 0.0.0.0:8180->8180/tcp, :::8180->8180/tcp             homepage

```
Any ideas?

### homepage version

latest version 

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
