### ISSUE TITLE
[Bug] Uptime-Kuma Widget reports API Error

### ISSUE THREAD

**Issue by wohfab** [gethomepage/homepage#1133]
### Description

I have set up an uptime kuma widget on my homepage with the following code:

```yaml
- STATUS:
    href: https://statuspage
    # ping: https://statuspage
    icon: uptime-kuma.png
    description: Website status for personal projects
    widget:
      type: uptimekuma
      fields: ["up", "down"]
      url: https://statuspage
      slug: personal
```

I can reach both my main `statuspage` and the `/status/personal` endpoint but in the widget, I am getting an `API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.

![image](https://user-images.githubusercontent.com/4539234/226659126-b011a219-4e13-493c-aeaf-08dc9267a262.png)

Is there any step in the setup, that I am missing?

### Steps to reproduce

1. Set up uptime-kuma widget as stated above
2. Open Homepage dashboard and wait for the widget to load
3. Get error

### homepage version

v0.6.10 (af2566c)

### Installation method

Docker

### Configuration

```yaml
`settings.yaml`


- STATUS:
    href: https://statuspage
    # ping: https://statuspage
    icon: uptime-kuma.png
    description: Website status for personal projects
    widget:
      type: uptimekuma
      fields: ["up", "down"]
      url: https://statuspage
      slug: personal
```
```


### Container Logs

homepage  | [2023-03-21T15:42:19.356Z] error: <httpProxy> Error calling https://statuspage/api/status-page/heartbeat/personal...
homepage  | [2023-03-21T15:42:19.356Z] error: <httpProxy> [
homepage  |   500,
homepage  |   Error: connect ETIMEDOUT ip:443
homepage  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
homepage  |     errno: -110,
homepage  |     code: 'ETIMEDOUT',
homepage  |     syscall: 'connect',
homepage  |     address: 'ip',
homepage  |     port: 443
homepage  |   }
homepage  | ]

### Browser Logs

_No response_

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
