### ISSUE TITLE
[Bug] Media widget showing incorrect transcoding icon when multiple streams are active

### ISSUE THREAD

**Issue by NekoPavel** [gethomepage/homepage#2154]
### Description

It seems like the Emby/Jellyfin media widget shows the incorrect transcoding icon when multiple streams are active.

When directplaying one stream:
![correct transcoding](https://pics.pavel.gg/neko/ne7hIRHZCP)

When starting another directplay stream:
![wrong transcoding](https://pics.pavel.gg/neko/neeWzBaQst)

Wild guess is that it's related to the fact that all of the states are set to true in SingleSessionEntry:
https://github.com/gethomepage/homepage/blob/4c2ecb9b0e366f65d7f334a1102e95117cc067f1/src/widgets/emby/component.jsx#L38-L42
But not in SessionEntry:
https://github.com/gethomepage/homepage/blob/4c2ecb9b0e366f65d7f334a1102e95117cc067f1/src/widgets/emby/component.jsx#L109

### Steps to reproduce

1. Visit setup emby/jellyfin widget
2. Start a directstream in emby/jellyfin 
3. Observe correct icon in widget
4. Start another directstream in emby/jellyfin 
5. Observe incorrect icon in widget

### homepage version

v0.7.3

### Installation method

Docker

### Configuration

```yaml
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://xxxxx
        description: Media streaming
        server: xxxxx
        container: jellyfin
        widget:
          type: jellyfin
          url: xxxxx
          key: xxxxx
          enableBlocks: true
          enableNowPlaying: true
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
