### ISSUE TITLE
[Bug] Unifi Controller API Error: Unknown error

### ISSUE THREAD

**Issue by cpuks** [gethomepage/homepage#2164]
### Description

`API Error: Unknown error
URL: https://192.168.88.2:8443/api/stat/sites
Raw Error:
{
    "errno": -113,
    "code": "EHOSTUNREACH",
    "syscall": "connect",
    "address": "192.168.88.2",
    "port": 8443
}`

### Steps to reproduce

Set Unifi Controller widget configuration inside services.yaml

### homepage version

0.7.3

### Installation method

Docker

### Configuration

```yaml
- UniFi® Controller:
        icon: unifi-controller.png
        href: https://192.168.88.2:8443
        server: docker-system
        container: unifi-controller
        widget:
            type: unifi
            url: https://192.168.88.2:8443
            username: homepage
            password: password
```

### Troubleshooting

I've created view only user, when I login as that user I can easily see contents of API endpoint as per screenshot:
![image](https://github.com/gethomepage/homepage/assets/21194723/66dface4-4703-4ef4-be4e-137060632e26)

### Other

homepage is running inside same LXC container as unifi-controller - hompeage is using external network while unifi is bridged to get an external IP

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
