### ISSUE TITLE
[Bug] Kubernetes Deployment Fails Due to RO ConfigMap

### ISSUE THREAD

**Issue by 0xEmma** [gethomepage/homepage#2172]
### Description

With the kubernetes deployment in https://gethomepage.dev/v0.7.3/installation/k8s/#deployment, you are told to do the following:
```yaml
volumeMounts:
                      - name: homepage-config
                        mountPath: /app/config
                      - name: logs
                        mountPath: /app/config/logs
            volumes:
                - name: homepage-config
                  configMap:
                      name: homepage
```

This makes the /app/config folder _readonly_ which results in `error: Error: EROFS: read-only file system, copyfile '/app/src/skeleton/custom.css' -> '/app/config/custom.css'` Making some settings breaks.

### Steps to reproduce

Create homepage following the Kubernetes docs
See erorr

### homepage version

v0.7.3

### Installation method

Other (please describe above)

### Container Logs

error: Error: EROFS: read-only file system, copyfile '/app/src/skeleton/custom.css' -> '/app/config/custom.css'

### Troubleshooting

I was able to fix this, by mounting the configmap to /tmp/config, and adding the following hook:
```yaml
lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r -L /tmp/config/* /app/config/; chmod -R 777 /app/config"]
````

The CSS files should be copied into another dir, or mount the config map separately and copy it.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I don't use k8s and I find it to be dreadfully complicated.

Your solution doesnt seem ideal, chmodding a directory to 777, is that actually a recommended practice for something like this?

The real question is why does https://gethomepage.dev/v0.7.3/installation/k8s/#__codelineno-4-16 not work but https://gethomepage.dev/v0.7.3/installation/k8s/#__codelineno-4-18 does.

Either way, Im sorta losing patience with k8s, this is basically a documentation issue but just like the helm chart which is 100% external, perhaps we should just remove it.

**Comment by benphelps** [comment]
> I don't use k8s and I find it to be dreadfully complicated.
> 
> Your solution doesnt seem ideal, chmodding a directory to 777, is that actually a recommended practice for something like this?
> 
> The real question is why does https://gethomepage.dev/v0.7.3/installation/k8s/#__codelineno-4-16 not work but https://gethomepage.dev/v0.7.3/installation/k8s/#__codelineno-4-18 does.
> 
> Either way, Im sorta losing patience with k8s, this is basically a documentation issue but just like the helm chart which is 100% external, perhaps we should just remove it.

I agree fully here.  It seems like every individual ends up needing changes made for the k8s support to also work for them.

**Comment by jameswynn** [comment]
If Homepage is trying to overwrite a file that is mounted from a configmap then it definitely won't work. I would expect a read-only filesystem error like they mentioned. I haven't inspected the code, but I assume Homepage is only attempting to overwrite that file if it doesn't exist. Is that the case?

As I posted in the helm chart ticket, the manifests should probably be updated to mention specific files, just like the helm chart does.

```yaml
        volumeMounts:
        - mountPath: /app/config/custom.js
          name: homepage-config
          subPath: custom.js
        - mountPath: /app/config/custom.css
          name: homepage-config
          subPath: custom.css
        - mountPath: /app/config/bookmarks.yaml
          name: homepage-config
          subPath: bookmarks.yaml
        - mountPath: /app/config/docker.yaml
          name: homepage-config
          subPath: docker.yaml
        - mountPath: /app/config/kubernetes.yaml
          name: homepage-config
          subPath: kubernetes.yaml
        - mountPath: /app/config/services.yaml
          name: homepage-config
          subPath: services.yaml
        - mountPath: /app/config/settings.yaml
          name: homepage-config
          subPath: settings.yaml
        - mountPath: /app/config/widgets.yaml
          name: homepage-config
          subPath: widgets.yaml
        - mountPath: /app/config/logs
          name: logs
```

There really shouldn't be so much variability in the deployments. I never used the custom.css, otherwise I probably would have caught this issue in earlier testing.
