### ISSUE TITLE
[Bug] Status running / metrics not working with traefik autodiscovery on k8s

### ISSUE THREAD

**Issue by hugosxm** [gethomepage/homepage#2182]
### Description

Hi, 

I use homepage with the kubernetes autodiscovery for ingressroutes ( the traefik one, not the vanilla ingress ) 

It works as my service appear on homepage BUT i do not have the green "running" little square to the top right of the card and if I click on it it show OFFLINE.

See the screenshot 
![homepagebug](https://github.com/gethomepage/homepage/assets/23743455/dc2e0545-61a4-48d2-8720-8d507eb93338)

I hope this is not me missing something obvious...

### Steps to reproduce

Create ingress route with annotations like this : 

  ```
annotations:
    gethomepage.dev/href: "https://tools.xxx.com"
    gethomepage.dev/ping: "https://tools.xxx.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Various tools for it
    gethomepage.dev/group: Prod services
    gethomepage.dev/icon: https://tools.xxx.com/favicon-32x32.png
    gethomepage.dev/name: It tools

    # I tried with and without this, multiple values but no success
    gethomepage.dev/podSelector: "app.kubernetes.io/name: ittools-app=ittools-app"
```

### homepage version

v0.7.3

### Installation method

Docker

### Configuration

```yaml
Nothing special in my kubernetes.yaml

  kubernetes.yaml: |
    mode: cluster
```

### Container Logs

Nothing in the container log 

```
[2023-10-12T17:58:50.884Z] warn: API response for /api/services/proxy?type=prometheus&group=K8S+services&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2023-10-12T18:02:12.887Z] warn: API response for /api/services/proxy?type=prometheus&group=K8S+services&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2023-10-12T18:02:16.073Z] warn: API response for /api/services/proxy?type=prometheus&group=K8S+services&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2023-10-12T18:02:16.979Z] warn: API response for /api/services/proxy?type=prometheus&group=K8S+services&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2023-10-12T18:03:16.263Z] warn: API response for /api/services/proxy?type=prometheus&group=K8S+services&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2023-10-12T18:03:17.122Z] warn: API response for /api/services/proxy?type=prometheus&group=K8S+services&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2023-10-12T18:03:20.193Z] warn: API response for /api/services/proxy?type=prometheus&group=K8S+services&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
```

### Browser Logs

```
Request URL:
https://home.xxx.com/api/kubernetes/status/ittools-app/ittools-ingress?
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
xxxx:443
Referrer Policy:
strict-origin-when-cross-origin

```
### Troubleshooting

'n/a'

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Sigh, k8s. It seems it is very fragile and I dont use it, but I can tell you that testing with the basic k3d example we have, this works fine (and our k8s users seem to be fairly vocal and are not complaining of this suddenly being broken):

<img width="373" alt="Screenshot 2023-10-13 at 8 54 59 AM" src="https://github.com/gethomepage/homepage/assets/4887959/6821eba5-387f-40c7-bcdf-4c07f644feef">

Suffice to say, this is a configuration issue, Im sorry I cant help you troubleshoot more. The 404 means homepage cant access the k8s API, you should start there.

**Comment by hugosxm** [comment]
Sorry I forgot to mention that it works without the autodiscovery... so my config is good, this is why I included two cards in my snapshot, the working one is "writed by hands" in services.yaml...

**Comment by hugosxm** [comment]
@shamoon I solved it but i still think it is a bug to "your side" unless I do not understand the doc correclty....


It works only if my ingress have the same name that my service ( tested ok with vanilla ingress and traefik ingressroute )

Because it tries : 

`https://xxx.bbq-cloud.com/api/kubernetes/status/ittools-app/ittools-ingress? `

Where i guess ittools-app is namespace and ittools-ingress is the name of my ingressroute

So I renamed my ingress ittools-app and now it works with : 

`https://home.bbq-cloud.com/api/kubernetes/status/ittools-app/ittools-app?`

So I think that in the case of autodiscovery, the mecanism behind the construction of that url is somehow "broken" ? Or it is by design and in that case it should be specified in the doc :) It should reach for the app label instead of the ingress name, like it does when manually added to services.yaml

**Comment by shamoon** [comment]
Again I dont use k8s (and it seems so complicated that every single person who does does things a little differently than the last...) but the homepage code uses [`listNamespacedPod`](https://github.com/kubernetes-client/javascript/blob/6b713dc83f494e03845fca194b84e6bfbd86f31c/src/gen/api/coreV1Api.ts#L10656) with:

- namespace = service.namespace
- labelSelector = service.podSelector if specified or `"app.kubernetes.io/name"=service.appName

Moreover, homepage infers some of these values like:
https://github.com/gethomepage/homepage/blob/dcc2f3e8f38cba2933e4a536a862886cc571b324/src/utils/config/service-helpers.js#L241-L244
&
```constructedService.podSelector = ingress.metadata.annotations[`${ANNOTATION_BASE}/pod-selector`];```

Finally, you can see how the homepage API URL gets generated:
https://github.com/gethomepage/homepage/blob/dcc2f3e8f38cba2933e4a536a862886cc571b324/src/components/services/kubernetes-status.jsx#L6

**Comment by hugosxm** [comment]
Ok i see, the line

` app: ingress.metadata.name,`

It takes the ingress-name and fill the "app" value for homepage, there is the problem because the ingress name is not always the same as the app label value. 

A good fix, I think, should be to use the homepage "app" annotation everytime, and make that annotation mandatory  :

` gethomepage.dev/app: ittools-app`

Then the line becomes : 

` app: ingress.metadata.annotations['${ANNOTATION_BASE}/app']`

**Comment by shamoon** [comment]
That sounds like a breaking change so I’m not inclined to do that. Can you do what you need with `pod-selector` (ps docs were fixed to reflect the correct name for that)

**Comment by hugosxm** [comment]
I'm pretty sure I can not because I tried multiple pod selector settings and the problem is that in the construction of the url : 

`/api/kubernetes/status/${service.namespace}/${service.app}?${podSelectorString}`

If service.app is not right you are screwed, because whatever you will put in the podSelectorString the url before will give a 404 not found ...

**Comment by shamoon** [comment]
Yea maybe support for ${ANNOTATION_BASE}/app and fallback to the name

Again, since I dont use k8s, in your initial example, where is your app name (the one you'd want homepage to use) specified, and what is it?

**Comment by hugosxm** [comment]
On the kubernetes ingress object, you do not have the app name, and this is why someone of the homepage project decided to use the ingress name as app name, it was a great and smart move / workaround, but it does not work every case. The thing that was "missed" is that the ingress name can be everything you want, so the ingress name is not necessarily the app name. 

So on my initial exemple there is no app name specified as homepage take the ingress name as app name.

Sorry If I'm not clear, english is not my first language :/

**Comment by shamoon** [comment]
To clarify, in the [docs](https://gethomepage.dev/v0.7.3/configs/kubernetes/#__codelineno-4-4), it suggests you'd use eg:
```yaml
kind: IngressRoute
metadata:
    name: emby
    annotations:
    ...
```

In which case it'd be 'emby'. Youre saying in your setup (and presumably for others) `metadata.name` is not set at all (that part is not copy & pasted into your original comment above)?

**Comment by shamoon** [comment]
Looking through the docs, shouldn't it always be there? https://doc.traefik.io/traefik/v2.2/routing/providers/kubernetes-crd/#kind-ingressroute / https://doc.traefik.io/traefik/providers/kubernetes-crd/#configuration-requirements

**Comment by hugosxm** [comment]
Ok sorry I misunderstood you, so yes i set the metadata.name of the ingress, there is the full yaml : 

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ittools-ingress
  namespace: ittools-app
  annotations:
    gethomepage.dev/href: "https://tools.xxx"
    gethomepage.dev/ping: "https://tools.xxx"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Various tools for it
    gethomepage.dev/group: Prod services
    gethomepage.dev/icon: https://tools.xxx/favicon-32x32.png
    gethomepage.dev/name: It tools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tools.xxx`)
      kind: Rule
      services:
        - name: ittools-app
          namespace: ittools-app
          port: http
  tls:
    secretName: tools.xxx
```

If i replace the metadata.name with ittools-app instead of ittools-ingress it works, as a workarround.

**Comment by shamoon** [comment]
Appreciate your patience, I know this is dragging on.

`https://home.xxx.com/api/kubernetes/status/ittools-app/ittools-ingress` throws a 404? What exactly is the return status / data / is there data in the logs? Is it `"not found"`?

Just wanted to make sure you saw above, the docs previously suggested to use `podSelector` in your k8s config but it should be `pod-selector`.

Again, looking at our code in https://github.com/gethomepage/homepage/blob/main/src/pages/api/kubernetes/status/%5B...service%5D.js , the homepage api URL `https://home.xxx.com/api/kubernetes/status/ittools-app/ittools-ingress?` would result in:

- namespace = ittools-app
- appName = ittools-ingress

which, since no pod-selector is specified would up setting `labelSelector = app.kubernetes.io/name=ittools-ingress` which is what fails (should return 404 "not found" which btw is confusing and I can change to be more explicit that no pod was found).

I would think you could set `pod-selector=***.metadata.name`, now I'm not sure what exactly you'd use here but I would think there's some way to select the ingress name here, like `pod-selector=ingressroutes.traefik.io.metadata.name` (thats completely made up)?

Alternatively, as the docs state (now with the correct parameter), if you specify `pod-selector=""` it would return all pods within that namespace (ittools-app), which presumably would work in your case.

Holy cow, k8s.

**Comment by hugosxm** [comment]
No problem, as I love this product this is not a problem helping a bit !

Yes I just have a 404 not found, I saw this is my browser dev tools console

I used "pod-selector" we are ok on the syntax, empty pod-selector also gives the 404

I do not understand how you get the information on kubernetes but what I know for sure is that in my case it try to use ittools-ingress, which is the name of the ingress. And you have ( in k8s ) no way to know wich pods are tied to that ingress. In k8s you create pods, you create a service which refer to your pods, THEN you create a ingress which refer to a service. 

Let me show you the full picture...

First you create a deployment, which manage the pods : 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ittools-app
  name: ittools-app
  labels:
    app: ittools-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ittools-app
  template:
    metadata:
      labels:
        app: ittools-app
        app.kubernetes.io/name: ittools-app  # Here we choose the famous app label
    spec:  
# I remove the end, not revelant for the exemple
```


Then after we create a service : 

```
---
apiVersion: v1
kind: Service
metadata:
  namespace: ittools-app
  name: ittools-service
spec:
  selector:
    app: ittools-app    # Here we tell the service to hook yourself to all the pods matching this
```

Then last we create the ingress : 


```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ittools-ingress
  namespace: ittools-app
  annotations:
    gethomepage.dev/href: "https://tools.bbq-cloud.com"
    gethomepage.dev/ping: "https://tools.bbq-cloud.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Various tools for it
    gethomepage.dev/group: Prod services
    gethomepage.dev/icon: https://tools.bbq-cloud.com/favicon-32x32.png
    gethomepage.dev/name: It tools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tools.bbq-cloud.com`)
      kind: Rule
      services:
        - name: ittools-service                                       # Here we tell traefik or whatever ingress controler you use to hook itself to a service.
          namespace: ittools-app
          port: http
```


I have the feeling that homepage try to find the pods from the ingress which is impossible... The service gives the pod list but not the ingress. And it is complicated for you to parse ingress and ingressRoutes to find the service, this is why I proposed to modify the annotations with : 

`app: ingress.metadata.annotations['${ANNOTATION_BASE}/app'] ||  ingress.metadata.name,`

K8S is complicated but it solves so much for you too ^^ it is a love / hate toxic relationship with it...
