### ISSUE TITLE
[Bug] GoAuthentik update (v2023.10.1) changed api query requirement

### ISSUE THREAD

**Issue by just5ky** [gethomepage/homepage#2243]
### Description

The latest GoAuthenitk update changed the requirements for `api/v3/core/users`

> https://goauthentik.io/docs/releases/2023.10#get-coreusers

### Steps to reproduce

- Update GoAuthentik to version 2023.10.1
> ![image](https://github.com/gethomepage/homepage/assets/71321862/732c71fb-190e-4854-ae1c-cc43f9b5fea4)

### homepage version

v0.7.4 (8ec488e, Oct 19, 2023)

### Installation method

Docker

### Configuration

```yaml

- Security:
    - Authentik:
        href: XXXX
        icon: authentik.png
        description: IdP
        statusStyle: dot
        widget:
          type: authentik
          url: XXXX
          key: XXX
        server: galax 
        container: authentik-server

```

### Container Logs

```log

[2023-10-27T05:23:27.505Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://auth.justsky.in/api/v3/core/users?page_size=1
[2023-10-27T05:23:29.197Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://auth.justsky.in/api/v3/core/users?page_size=1
[2023-10-27T05:23:53.202Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://auth.justsky.in/api/v3/core/users?page_size=1
```

### Browser Logs

![image](https://github.com/gethomepage/homepage/assets/71321862/0456ce68-a322-40c3-af0d-c116a91f8f11)

### Troubleshooting

Based on documentatiom, UUID is requried.
 > https://goauthentik.io/docs/releases/2023.10#get-coreusers

![image](https://github.com/gethomepage/homepage/assets/71321862/d5b716a1-47f1-48f9-bea7-de3f6a09645b)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
