### ISSUE TITLE
[Bug] API Error in Calendar when using hideErrors: true in setting.yaml

### ISSUE THREAD

**Issue by seniyakk** [gethomepage/homepage#2257]
### Description

Hello.
In the **settings.yaml**, I used **hideErrors: true** to hide errors from the widget when services are switched off. 
However, on the calendar, I still see an error.  Please see the photo.

When services are switched off.
<img width="1836" alt="Screenshot 2023-10-29 at 16 18 28" src="https://github.com/gethomepage/homepage/assets/143352707/0a756c45-d1a7-4f00-bb75-0471146aee29">

When services are working:
<img width="1851" alt="Screenshot 2023-10-29 at 16 28 40" src="https://github.com/gethomepage/homepage/assets/143352707/477cb2c1-0827-46ca-a361-0f02d2e3f91c">

Without **hide Errors: true**:
<img width="1852" alt="Screenshot 2023-10-29 at 16 52 25" src="https://github.com/gethomepage/homepage/assets/143352707/17184d60-84e9-4f80-b06e-edea7b5951f9">

### Steps to reproduce

1. In **settings.yaml** you should have **hideErrors: true**.
2. Switch off services: Lidarr, Sonarr, Radarr, Readarr.
3. You will see the error "API Error: radarr: HTTP Error"

### homepage version

v0.7.4

### Installation method

Docker

### Configuration

```yaml
Setting.yaml

title: Selfhosted Dashboard
logfile: /app/config
backgroundOpacity: 1
headerStyle: clean #Values: boxed, underlined
target: _blank
language: en
fiveColumns: true
hideErrors: true
base: https://home.myserver.com

layout:
  Multimedia:
    icon: /icons/media.svg
    style: col
  Books & Documents:
    icon: /icons/library.svg
    style: col
  External Interaction Apps:
    icon: /icons/communication.svg
    style: col
  Infrastructure:
    icon: /icons/infrastructure.svg
    style: col
  Utility:
    icon: /icons/smart_home.svg
    style: col
---------------------------------------------------------------------
services.yaml

- Calendar:
        widget:
            type: calendar
            integrations:
              - type: sonarr
                service_group: Multimedia
                service_name: Sonarr
                color: teal 
              - type: radarr
                service_group: Multimedia 
                service_name: Radarr 
                color: blue 
              - type: lidarr
                service_group: Multimedia 
                service_name: Lidarr 
                color: violet 
              - type: Readarr
                service_group: Books & Documents
                service_name: Readarr 
                color: zinc
```

### Troubleshooting

When I run services, I do not see the error. Everything works well except that **hideErrors: true,**  does not work with the calendar.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
