### ISSUE TITLE
[Bug] Unifi Controller widget is not working

### ISSUE THREAD

**Issue by dontcrash** [gethomepage/homepage#2269]
### Description

![image](https://github.com/gethomepage/homepage/assets/32660358/a0f61782-7f51-467a-b675-13f4a7eedc22)

The default URL Homepage uses results in a "Not Found" page.
I believe at some point Ubiquiti have changed it, this URL for example results in the following JSON
https://172.16.2.1/proxy/network/api/s/default/stat/health

```JSON
{
  "meta": {
    "rc": "ok"
  },
  "data": [
    {
      "subsystem": "wlan",
      "num_user": 4,
      "num_guest": 0,
      "num_iot": 0,
      "tx_bytes-r": 144,
      "rx_bytes-r": 179,
      "status": "warning",
      "num_ap": 1,
      "num_adopted": 2,
      "num_disabled": 0,
      "num_disconnected": 1,
      "num_pending": 0
    },
    {
      "subsystem": "wan",
      "num_gw": 1,
      "num_adopted": 1,
      "num_disconnected": 0,
      "num_pending": 0,
      "status": "ok",
      "wan_ip": "REDACTED",
      "gateways": [],
      "netmask": "255.255.255.0",
      "nameservers": [
        "REDACTED",
        "REDACTED"
      ],
      "num_sta": 20,
      "tx_bytes-r": 2215,
      "rx_bytes-r": 3253,
      "gw_mac": "REDACTED",
      "gw_name": "REDACTED",
      "gw_system-stats": {
        "cpu": "18.0",
        "mem": "68.0",
        "uptime": "792683"
      },
      "gw_version": "3.2.5.13810",
      "isp_name": "REDACTED",
      "isp_organization": "REDACTED",
      "uptime_stats": {
        "WAN": {
          "alerting_monitors": [
            {
              "availability": 100.0,
              "latency_average": 1,
              "target": "1.1.1.1",
              "type": "icmp"
            },
            {
              "availability": 100.0,
              "latency_average": 100,
              "target": "1.1.1.1",
              "type": "dns"
            },
            {
              "availability": 100.0,
              "latency_average": 100,
              "target": "8.8.8.8",
              "type": "dns"
            }
          ],
          "availability": 99.65279999375343,
          "latency_average": 2,
          "monitors": [
            {
              "availability": 100.0,
              "latency_average": 1,
              "target": "www.microsoft.com",
              "type": "icmp"
            },
            {
              "availability": 100.0,
              "latency_average": 21,
              "target": "google.com",
              "type": "icmp"
            },
            {
              "availability": 100.0,
              "latency_average": 1,
              "target": "1.1.1.1",
              "type": "icmp"
            }
          ],
          "time_period": 86400,
          "uptime": 792630
        }
      }
    },
    {
      "subsystem": "www",
      "status": "ok",
      "tx_bytes-r": 2215,
      "rx_bytes-r": 3253,
      "latency": 1,
      "uptime": 160238,
      "drops": 2,
      "xput_up": 33.398,
      "xput_down": 909.11,
      "speedtest_status": "Success",
      "speedtest_lastrun": 1698862833,
      "speedtest_ping": 3,
      "gw_mac": "REDACTED"
    },
    {
      "subsystem": "lan",
      "lan_ip": null,
      "status": "ok",
      "num_user": 16,
      "num_guest": 0,
      "num_iot": 0,
      "tx_bytes-r": 2017,
      "rx_bytes-r": 2062,
      "num_sw": 2,
      "num_adopted": 2,
      "num_disconnected": 0,
      "num_pending": 0
    },
    {
      "subsystem": "vpn",
      "status": "ok",
      "remote_user_enabled": true,
      "remote_user_num_active": 0,
      "remote_user_num_inactive": 0,
      "remote_user_rx_bytes": 1494212,
      "remote_user_tx_bytes": 23008128,
      "remote_user_rx_packets": 9672,
      "remote_user_tx_packets": 23511,
      "site_to_site_enabled": false
    }
  ]
}
```

### Steps to reproduce

Create a local only user on the latest Ubiquiti console
Add the Ubiquiti widget to Homepage

### homepage version

Latest

### Installation method

Docker

### Configuration

```yaml
N/A
```

### Container Logs

N/A

### Browser Logs

N/A

### Troubleshooting

Checked the API URLs from my Ubiquiti console.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please search. Nearly every Ubiquiti “bug report” raised has been user error. Nothing has changed and many many people use it, I doubt it’s broken.

**Comment by dontcrash** [comment]
I have read the previous issues, read the documentation, completely recreated the homepage container. The issue persists.
I have a UDM-SE running the latest Unifi OS and network application.
This config in services.yaml results in 401.

[2023-11-03T08:13:29.049Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}

```YAML
    - UDM SE:
        icon: ubiquiti.png
        widget:
          type: unifi
          url: https://172.16.2.1
          username: Homepage
          password: redacted
```

**Comment by shamoon** [comment]
UDMP/UDM SE should return an `x-csrf-token` header, thats how the widget detects which URL to use.
`curl -i -v -k  https://172.16.2.1`

**Comment by shamoon** [comment]
So thats a UDMSE and what version of the OS / network is that running?

**Comment by dontcrash** [comment]
This is happening on the latest release: 7.5.187

https://community.ui.com/releases/UniFi-Network-Application-7-5-187/408b64c5-a485-4a37-843c-31e87140be64

**Comment by dontcrash** [comment]
I believe I have found the root cause, any "pro" controller needs to have "/proxy/network/" before "api" in the URI

https://ubntwiki.com/products/software/unifi-controller/api#udm_pro_api

![image](https://github.com/gethomepage/homepage/assets/32660358/e18733b2-f24b-46fe-9099-3433dc5ca10a)

**Comment by dontcrash** [comment]
If anyone else stumbles upon this, I ended up creating a customapi widget using a token I got from web inspector.

![image](https://github.com/gethomepage/homepage/assets/32660358/c2b99008-d555-4f98-ab9d-9edb402e1fc8)

services.yaml
```YAML
- Statistics:
    - UDM SE:
        icon: ubiquiti.png
        widget:
          type: customapi
          url: https://172.16.2.1/proxy/network/api/s/default/stat/health
          headers:
            Cookie: 'TOKEN=abc123'  
          mappings:
            - field:
                data:
                  1: wan_ip
              label: WAN
              format: text
            - field:
                data:
                  1:
                    gw_system-stats: uptime
              label: Uptime
              format: number
              suffix: Hours
              scale: 0.000277778
            - field:
                data:
                  1:
                    gw_system-stats: cpu
              label: CPU
              format: number
              suffix: '%'
            - field:
                data:
                  1:
                    gw_system-stats: mem
              label: RAM
              format: number
              suffix: '%'
```
