### ISSUE TITLE
[Bug] Glances widget showing same data despite different url settings

### ISSUE THREAD

**Issue by joestump** [gethomepage/homepage#2273]
### Description

I have configured some Services with the Glances widget and despite each having unique `url` settings in the `widget`, they are all showing the exact same data:

<img width="1232" alt="homepage-duplicate-error" src="https://github.com/gethomepage/homepage/assets/37667/404bb102-6934-414e-99db-32ea2d541dba">

### Steps to reproduce

* Add multiple calls to the same `metric` on a Glances widget with *different* `url` parameters.
* Homepage will show the same `metric`/`url` combination for all of the Glances widgets.

### homepage version

v0.7.4

### Installation method

Docker

### Configuration

```yaml
- Hardware:
  - nuc01:
      href: https://portainer.local/#!/16/docker/dashboard
      icon: portainer
      description: Docker on nuc01.local
      widget:
        type: portainer
        url: https://portainer.local
        env: 16
  - Network:
      widget:
        type: glances
        url: http://192.168.1.12:61208
        metric: network:eth0
  - CPU:
      widget:
        type: glances
        url: http://192.168.1.12:61208
        metric: cpu

  - nuc02:
      href: https://portainer.local/#!/17/docker/dashboard
      icon: portainer
      description: Docker on nuc02.local
      widget:
        type: portainer
        url: https://portainer.local
        env: 17
  - Network:
      widget:
        type: glances
        url: http://192.168.1.10:61208
        metric: network:eth0
  - CPU:
      widget:
        type: glances
        url: http://192.168.1.10:61208
        metric: cpu

  - hass:
      href: https://hass.local/
      icon: home-assistant
      description: Home Assistant on hass.local
      widget:
        type: homeassistant
        url: https://hass.local
        key: secret
        custom:
          - state: person.joe_stump
            label: Joe
          - state: person.chelsea_lofton
            label: Chelsea
          - state: lock.front_door
            label: Entry
          - state: cover.garage_door
  - Network:
      widget:
        type: glances
        url: http://192.168.1.40:65318
        username: me
        password: secret
        metric: network:eth0
  - CPU:
      widget:
        type: glances
        url: http://192.168.1.40:65318
        username: me
        password: secret
        metric: cpu
```

### Container Logs

Just this over and over:

```
[2023-11-04T13:12:21.318Z] error: <service-helpers> Error getting ingresses: NaN undefined undefined
[2023-11-04T13:12:27.121Z] error: <service-helpers> Error getting ingresses: NaN undefined undefined
[2023-11-04T13:12:53.818Z] error: <service-helpers> Error getting ingresses: NaN undefined undefined
[2023-11-04T13:12:58.569Z] error: <service-helpers> Error getting ingresses: NaN undefined undefined
[2023-11-04T13:13:06.509Z] error: <service-helpers> Error getting ingresses: NaN undefined undefined
[2023-11-04T13:13:12.055Z] error: <service-helpers> Error getting ingresses: NaN undefined undefined
```

### Browser Logs

It does appear to be querying for different data?

```
GET | https://dash.local/api/widgets/glances?lang=en&index=0&url=http://192.168.1.12:61208&label=nuc01&style=[object Object]
GET | https://dash.local/api/widgets/glances?lang=en&index=0&url=http://192.168.1.12:61208&label=nuc01&style=[object Object]
```

Not sure why it's sending `[object Object]` for `style`. 

### Compared to the Glances in the header

They show different data in the header. I would have expected the graph widgets I configured above to match numerically to these in the headers, which are correctly reporting different data:

<img width="913" alt="homepage-working-glances" src="https://github.com/gethomepage/homepage/assets/37667/f2131b6b-d6ec-4721-9cc4-d7667a76a08d">

### Tested unique `metric` Glance widgets

I also tested to see if I could get two of these widgets reporting correct data from two hosts. So I commented out everything except Networking from `nuc01` and CPU from `nuc02`, which correctly reported unique metrics from the two hosts. *It seems duplication only happens when you use the same `metric` with different `url` settings.*

### Restarted the container

No effect. It continued to report duplicate data after restarting the container.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
