### ISSUE TITLE
[Bug] Moonraker layers status not shown

### ISSUE THREAD

**Issue by itsmemac** [gethomepage/homepage#2279]
### Description

Dashboard is unable to fetch layer status from moonraker

![image](https://github.com/gethomepage/homepage/assets/37410297/da0043e7-6588-4de2-8b0d-4c466e503bed)

### Steps to reproduce

1. Add moonraker to dashboard
2. Refresh dashboard

### homepage version

v0.7.4

### Installation method

Docker

### Configuration

```yaml
- 3D Printer:
        icon: mainsail.svg
        href: http://192.168.0.126:4070/
        description: Ender 3
        widget:
            type: moonraker
            hideErrors: true
            fields: ["printer_state", "print_status", "print_progress", "layers"]
            url: http://192.168.0.126:7125/
```

### Container Logs

Listening on port 3000

### Troubleshooting

n/a

homepage can get other 2 stats from the service without any issues

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
