### ISSUE TITLE
Immich API widget error

### ISSUE THREAD

**Issue by C8opmBM** [gethomepage/homepage#2285]
### Description

Seems there's an API error with immich all of the sudden.
I've been using the widget since january (just checked the api key creation).

Service works normally, only dashboard error.

### Steps to reproduce

Just launch homepage

### homepage version

v0.7.4 (8ec488e, Oct 18, 2023)

### Installation method

Docker

### Configuration

```yaml
- Vulcan:
    - Immich:
        icon: /icons/immich.png
        href: https://img.vvv.net/
        description: 
        server: docker
        container: immich_web    
        widget:
            type: immich
            url: http://immich_proxy:8080
            #fields: ["users" ,"photos", "videos", "storage"] # Optional
            key: myadminkey
```

### Container Logs

No errors shown in logs

### Browser Logs

Console throws this error:
https://myimmich.net/api/services/proxy?type=immich&group=Vulcan&service=Immich&endpoint=undefined 404 (Not Found)

### Troubleshooting

Removed and recreated containers. 
Same issue

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
