### ISSUE TITLE
[Bug] k3s Status Partial Down/Offline when Cronjob pods run

### ISSUE THREAD

**Issue by shadofall** [gethomepage/homepage#2322]
### Description

When Cron job prods run for for a k3s application, and they go 0/1 Completed they cause the Status Indicate to go Partial Down/Offline for the duration that the pod exists.

I've tried using the Pod Selector to select only the normal application pods and not include the cron pod when it runs. but either i'm doing something wrong or it's still detecting it

![image](https://github.com/gethomepage/homepage/assets/9327622/04ddbe99-d5f9-400e-93a1-127f4946ff06)

` k3s kubectl get pods -n ix-nextcloud
NAME                                      READY   STATUS      RESTARTS   AGE
nextcloud-cnpg-main-rw-58994fc749-mzpg4   1/1     Running     0          25h
nextcloud-cnpg-main-rw-58994fc749-8mjlm   1/1     Running     0          25h
nextcloud-cnpg-main-1                     1/1     Running     0          25h
nextcloud-redis-0                         1/1     Running     0          25h
nextcloud-cnpg-main-2                     1/1     Running     0          25h
nextcloud-collabora-c48758657-vpjlw       1/1     Running     0          25h
nextcloud-imaginary-546944c847-xn6p4      1/1     Running     0          25h
nextcloud-clamav-9bc7cf6c4-lcnqg          1/1     Running     0          25h
nextcloud-677d86d9b6-m4bqz                1/1     Running     0          25h
nextcloud-nginx-6749bbb4df-v9mkp          1/1     Running     0          25h
nextcloud-notify-c7d69f7bd-zrp2x          1/1     Running     0          25h
nextcloud-nextcloud-cron-28332825-j5qm6   0/1     Completed   0          30s
`

### Steps to reproduce

on a Kubernetes cluster enable a widget for any application with a transient pod such as a cron job. watch status as pod comes and coes

### homepage version

V0.8.0

### Installation method

Other (please describe above)

### Configuration

```yaml
- Nextcloud:
        icon: nextcloud.png
        href: https://nc.shadogate.com
        description: Could Storage and Services
        namespace: ix-nextcloud
        pod-selector: >-
          app.kubernetes.io/instance in (
              nextcloud-cnpg-main-rw,
              nextcloud-cnpg-main-1,
              nextcloud-redis-0,
              nextcloud-cnpg-main-2,
              nextcloud-collabora,
              nextcloud-imaginary,
              nextcloud-clamav,
              nextcloud,
              nextcloud-nginx,
              nextcloud-notify
      )
        app: nextcloud
        widget:
          type: nextcloud
          url: http://nextcloud.ix-nextcloud.svc.cluster.local:12000
          key: this@is@my@life1928AndyouCantHaveIt
          fields: ["freespace", "activeusers", "numfiles", "numshares"]
```

### Troubleshooting

No error outputs. just the offline state/partial down when pod is present. regardless of pod-selector set

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
