### ISSUE TITLE
[Bug] Cards without background since 0.8.0

### ISSUE THREAD

**Issue by Sni3rs** [gethomepage/homepage#2335]
### Description

Since the 0.8.0 update, the card background blur effect disspeared for white color (see screenshot below)

![image](https://github.com/gethomepage/homepage/assets/89201449/c78a5888-4e39-41f6-8dd7-2010021e3030)

For other colors, it seems to works (I tried zinc, slate, neutral).

### Steps to reproduce

1. Go to settings.yaml
2. Apply "cardblur" (Xl for this example)
3. Apply "color: white"
4. Enjoy the bug.

### homepage version

0.8.0

### Installation method

Unraid

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  
weather:
xxxxxx
    provider: weatherapi

layout:
  Medias:
    style: row
    columns: 3

headerStyle: boxed
language: fr

color: white
target: _top
title: New Tab

cardBlur: xl

background:
  image: /images/wallpaper.jpeg
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
```

### Troubleshooting

I tried in Firefox and in Edge, same result. I also restarted the container without success.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
