### ISSUE TITLE
[Bug] The Portainer widget possibly might not use the env value correctly

### ISSUE THREAD

**Issue by ArthurMitchell42** [gethomepage/homepage#2364]
### Description

I've identified that my 5 end points are numbered 1, 50, 51, 52, 53 and 54.
When I add 5 portainer services with widgets and use the values above in the env: line they all report data for environment 1 rater than the named one.
![image](https://github.com/gethomepage/homepage/assets/82239494/85c3c0fa-e346-4648-85a7-08dc05c4629a)

### Steps to reproduce

Setting the services.yml to the data in the description field. Although data is collected it seems to be from the first instance only.

### homepage version

v0.7.4 (8ec488e, Oct 18, 2023)

### Installation method

Docker

### Configuration

```yaml
- Portainer:
        href: https://portainer.example.com/#!/1/docker/dashboard
        ping: https://portainer.example.com/
        description: Borg
        icon: portainer.png
        widget:
           type: portainer
           url: https://10.0.10.10:9443
           env: 1
           key: ptr_apiapiapiapi
    - Portainer:
        href: https://portainer.example.com/#!/52/docker/dashboard
        ping: https://portainer.example.com/
        description: DS9
        icon: portainer.png
        widget:
           type: portainer
           url: https://10.0.10.10:9443
           env: 52
           key: ptr_apiapiapiapi
```

### Container Logs

Nothing relavent

### Browser Logs

Nothing relavent

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
