### ISSUE TITLE
[Bug] Background and all link backgrounds are red

### ISSUE THREAD

**Issue by UntouchedWagons** [gethomepage/homepage#2377]
### Description

![Screenshot_20231124-215444](https://github.com/gethomepage/homepage/assets/160996/b5f6ad5c-751e-498c-b0b9-746378d73080)

This only occurs on my Pixel 6A in Firefox, Chrome is fine. If I scroll down to change the colour the only colour available is red, all 22 options are the exact same shade of red. 

I'm running Homepage in my kubernetes cluster

### Steps to reproduce

1) Go to Homepage
2) See red

### homepage version

v0.8.0

### Installation method

Other (please describe above)

### Configuration

```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: homepage
  namespace: default
  labels:
    app: homepage
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v0.8.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
              add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /app/config
              name: homepage-config
            - mountPath: /app/config/logs
              name: logs

      volumes:
        - name: homepage-config
          configMap:
              name: homepage
        - name: logs
          emptyDir: {}
```
```


### Container Logs

```
Listening on port 3000
[2023-11-25T01:59:52.850Z] warn: Failed to update prerender cache for /en [Error: EACCES: permission denied, open '/app/.next/server/pages/en.html'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/.next/server/pages/en.html'
}
```

### Browser Logs

_No response_

### Troubleshooting

N/A

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
