### ISSUE TITLE
Widget Error: Missing Widget Type: longhorn

### ISSUE THREAD

**Issue by gavinmcfall** [gethomepage/homepage#2438]
### Description

I recently installed Homepage in K3S and it is working
However, the loghorn widge is not working.
I have attached my full ConfigMap (with redacted secrets) showing what I have configured (including longhorn)
![2023-12-07 13_42_11-NERDZ Cloud](https://github.com/gethomepage/homepage/assets/131718663/380e9bf4-0bea-478b-805a-1543a39dbfb9)

### Steps to reproduce

Configure Longhorn Provider in settings.yaml
Configure Service + Widget for Longhorn in the services.yaaml file

### homepage version

0.8.2

### Installation method

Other (please describe above)

### Configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage
    namespace: default
    labels:
        app.kubernetes.io/name: homepage
data:
    kubernetes.yaml: |
        mode: cluster
    settings.yaml: |
        title: NERDZ Cloud
        providers:
          longhorn:
            username: <redacted>
            password: <redacted>
            url: https://longhorn.mydomain.com
        layout:
          Management:
            style: row
            columns: 4
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: |
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/gavinmcfall
    services.yaml: |
        - Management:
            - Proxmox - Nexus:
                description: Virtualization
                href: https://10.90.1.1:8006
                icon: proxmox.png
                widget:
                    type: proxmox
                    fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
                    url: https://10.90.1.1:8006
                    username: <redacted>
                    password: <redacted>
                    node: nexus
            - Proxmox - Hive:
                description: Virtualization
                href: https://10.90.1.1:8006
                icon: proxmox.png
                widget:
                    type: proxmox
                    fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
                    url: https://10.90.1.1:8006
                    username: <redacted>
                    password: <redacted>
                    node: hive
            - UniFi:
                description: Network
                href: https://10.90.254.1/network
                icon: unifi.png
                widget:
                    type: unifi
                    fields: ["uptime", "wan"]
                    username: <redacted>
                    password: <redacted>
                    url: https://10.90.254.1
            - Clourflare Tunnel:
                description: Zero Trust Tunnel
                href: https://dash.cloudflare.com/
                icon: cloudflare.png
                widget:
                    type: cloudflared
                    accountid: <redacted>
                    tunnelid: <redacted>
                    key: <redacted>
            - Longhorn:
                icon: longhorn.png
                href: https://longhorn.mydomain.com/
                description: HA Storage Service
                widget:
                    type: longhorn
                    url: https://longhorn.mydomain.com
                    expanded: true
                    total: true
                    labels: true
                    nodes: true

        - Smart Home:
            - My Smart Home:
                href: http://localhost/
                description: Smart Home

        - Media:
            - My Media Services:
                href: http://localhost/
                description: Media Service

        - Tools:
            - My Tools:
                href: http://localhost/
                description: Tools
    widgets.yaml: |
        - resources:
            cpu: true
            memory: true
            disk: /

        - datetime:
            text_size: x1
            locale: en-NZ
            format:
                dateStyle: long
                timeStyle: long
                hour12: true

        - search:
            provider: google
            target: _blank

        - openweathermap:
            label: Auckland #optional
            latitude: <redacted>
            longitude: <redacted>
            units: metric
            provider: openweathermap
            apiKey: <redacted>
            cache: 10 # Time in minutes to cache API responses, to stay within limits
    docker.yaml: ""
```

### Container Logs

Logs only show:

Listening on port 3000

### Browser Logs

Browser logs only show 200s and 304s, nothing relating to a failure in Longhorn

### Troubleshooting

I have tried adding and removing trailing / from the URLs to see if that helps but I suspect that would be an issue further down the chain, this seems like it doesn't even recognise that longhorn is a widget

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
