### ISSUE TITLE
[Bug] Calendar widget only includes the first date for recurring events

### ISSUE THREAD

**Issue by oratory** [gethomepage/homepage#2489]
### Description

Only the first date of recurring events and shown on the calendar, both in monthly and agenda views. Subsequent events are missing.

### Steps to reproduce

Example config:

```
        widget:
            type: calendar
            view: monthly 
            integrations: 
              - type: ical
                url: https://calendar.google.com/calendar/ical/d40b46fe188e8cb7c6cf5360461de5cb1afd54e7228d6845622eb569edd578c5%40group.calendar.google.com/public/basic.ics
                name: Repeating 
                color: green
```
The calendar URL is a public test calendar with a single event that repeats weekly, starting Dec. 18 2023. The calendar widget only shows the occurrence on December 18.

### homepage version

v0.8.3 (44b7de7, Dec 9, 2023)

### Installation method

Unraid

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
