### ISSUE TITLE
[Bug] Unifi Widget name can't contain spaces

### ISSUE THREAD

**Issue by grimsi** [gethomepage/homepage#2493]
### Description

When using a name with spaces (e.g. "Dream Machine SE") the service widget wont work and instead displays a 404 error.
It works when replacing the spaces with dashes (e.g. "Dream-Machine-SE").

![grafik](https://github.com/gethomepage/homepage/assets/9295182/11624f50-4c03-4cbd-9d7f-5183965b733f)

### Steps to reproduce

1. Create a new service widget for a Unifi Controller
2. Give it a name containing a space
3. See error

### homepage version

v0.8.3

### Installation method

Docker

### Configuration

```yaml
# Works
    - Dream-Machine-SE:
        icon: unifi-controller
        href: https://unifi.local
        description: UniFi Gateway
        widget:
          type: unifi
          url: https://192.168.1.1
          username: homepage_bot
          password: <redacted>

# Does not work
    - Dream Machine SE:
        icon: unifi-controller
        href: https://unifi.local
        description: UniFi Gateway
        widget:
          type: unifi
          url: https://192.168.1.1
          username: homepage_bot
          password: <redacted>
```

### Browser Logs

Log from Firefox:
```
XHRGET
https://lab.local/api/services/proxy?type=unifi&group=Infrastructure&service=Dream+Machine+SE&endpoint=stat/sites
[HTTP/2 404  26ms]
```

### Troubleshooting

Replacing all spaces in the name makes it work again.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
