### ISSUE TITLE
[Bug] Concise description of the issue

### ISSUE THREAD

**Issue by lubomben** [gethomepage/homepage#2504]
### Description

Still getting following error in homepage container:

`homepage  | [2023-12-21T11:16:38.368Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://immich_server:3001/api/server-info/stats`

even with homepage (docker) version 0.8.3 and immich (docker) version 1.91.4 but however I can see stats in the widget (see screenshot).

<img width="309" alt="image" src="https://github.com/gethomepage/homepage/assets/16686248/ad6d87f4-f671-4ed9-85b3-eae3863ca621">

Whi logs refers to old immich endpoint "/api/server-info/stats?

### Steps to reproduce

1. Start immich latest version (1.91.4) container
2. Start home page latest version (image: ghcr.io/gethomepage/homepage:latest) container

### homepage version

v0.8.3 (aab7de7)

### Installation method

Docker

### Configuration

```yaml
...
    - Immich:
        icon: immich.png
        href: https://<OMITTED>
        description: Immich
        server: docker
        container: immich_server
        widget:
          type: immich
          url: http://immich_server:3001
          key: <OMITTED>
...
```

### Container Logs

homepage  | [2023-12-21T11:16:38.368Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://immich_server:3001/api/server-info/stats

### Troubleshooting

```
~/docker/homepage » docker exec homepage ping immich_server
PING immich_server (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.456 ms
64 bytes from 172.18.0.3: seq=1 ttl=64 time=0.185 ms
```

```
~/docker/homepage » curl -L -k https://<OMITTED>/api/server-info/stats                                                                                                     130 
{"message":"Cannot GET /api/server-info/stats","error":"Not Found","statusCode":404}%

~/docker/homepage » curl -L -k https://<OMITTED>/api/server-info/statistics                                                                                                130 
{"message":"Authentication required","error":"Unauthorized","statusCode":401}%
```
Last message is ok because I didn't authenticate with API key but it resolve to an existing URL as it should be.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
