### ISSUE TITLE
[Bug] UrBackup Widget doesn't work over HTTPS

### ISSUE THREAD

**Issue by alphamike-1612** [gethomepage/homepage#2557]
### Description

Thank you for the widget.

The widget URL when set to HTTPS, for example https://urbackup.mydomain.com, doesn't work. Adding the SSL port number at the end (https://urbackup.mydomain.com:443) also has no effect.

The error shown is API error with no description.

Changing the URL to HTTP makes the widget work as expected. ie.) http://mydomain.com:55414.

UrBackup does not expose HTTPS directly and the recommended way for HTTPS is to set it up behind a reverse proxy that only proxies the path "/x" to fcgi on port 55413. The remaining pages are served by the server itself and not behind the proxy . In my case, the reverse proxy and web-server is Apache.

Trying to reverse proxy "https://urbackup.internal" to "http://localhost:55414" also has no effect. The API error remains.

Temporary workaround is to not disable the HTTP interface in /etc/default/urbackupsrv, but this defeats the purpose of the HTTPS website.

### Steps to reproduce

1. Install Urbackup as described in the documentation.
2. Setup HTTPS in UrBackup as per the documentation ( I used Apache)
3. Remove the HTTP interface by setting HTTP_SERVER="false" in /etc/default/urbackupsrv.
4.  Setup Homepage as described in the manual.
5. Setup UrBackup widget as described in the example with the URL "https://urbackup.mydomain.com"
6. Confirm that API Error is shown in UrBackup Widget.

### homepage version

v0.8.3

### Installation method

Source

### Configuration

```yaml
- UrBackup:
   - UrBackup:
       icon: urbackup
       href: https://urbackup.internal
       widget:
           type: urbackup
           username: <--redacted-->
           password: <--redacted-->
           url: http://urbackup.internal
           fields: ["ok", "errored", "noRecent", "totalUsed"]
           maxDays: 2
```

### Troubleshooting

Was not able to find the API endpoint for UrBackup. Server Admin Manual and the Internet had no description of the same.

Running curl -k https://urbackup.internal returns the html source of index.html.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
