### ISSUE TITLE
[BUG] Weird white lines when viewing dashboard on firefox

### ISSUE THREAD

**Issue by deffcolony** [gethomepage/homepage#2571]
# Description:
While navigating the homepage dashboard, populated with service boxes, I observed an issue. Upon scrolling down and hovering the mouse over random spots, a white buggy line becomes visible. Notably, this anomaly is exclusive to Firefox and does not occur on Chromium browsers.

# Potential Cause:
The issue seems to be related to the combination of the `cardBlur: sm` property and a background, specifically causing the appearance of the unusual lines when viewed in Firefox. Please refer to the attached video for a visual representation of the problem.

https://github.com/gethomepage/homepage/assets/61471128/323ba583-c867-4838-9835-af30c98e364c

![image](https://github.com/gethomepage/homepage/assets/61471128/b501bdb5-a278-417a-a9ff-666908bd1bb1)

### Steps to reproduce

1. add the following config in `settings.yaml`:

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

cardBlur: sm

background: https://i.imgur.com/j4nKdkD.jpeg
backgroundOpacity: 0.2
```

2. add the following placeholder services in `services.yaml` to expand the page that you need to scroll down:

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services


- ETC:
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername


- Remote Management:
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
        
- Home Control:
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername

        
- Media & Entertainment:
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername


- Networking:
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername

    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername

        
- Network Monitoring:
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername

    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername

    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername


- Productivity:
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername

    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
    
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername

    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
        
    - placeholder:
        href: https://192.168.1.1
        description: dummytext
        icon: icon.png
        server: yourserver
        container: containername
```

3. Open Firefox
4. Go to your dashboard
5. scroll down hover your mouse over the screen and see the white line bug

### homepage version

v0.8.4 (32f28d3, Dec 27, 2023)

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
