### ISSUE TITLE
[Bug] Quick Launch shows always Portainer

### ISSUE THREAD

**Issue by fruchttiger87** [gethomepage/homepage#2585]
### Description

Hi! 

I have the same problem like described here: https://github.com/gethomepage/homepage/issues/1395

When I write omada for example for opening the QuickLaunch Menu there are always three portainer entries in the Quicklaunch menu. They all have different names: 

![homepage](https://github.com/gethomepage/homepage/assets/63422494/3728ebb9-c452-424b-82fe-bcc610597f84)
![homepage2](https://github.com/gethomepage/homepage/assets/63422494/52961fba-d2e8-4dbf-b91c-07bc9760ae5e)

### Steps to reproduce

1. Open Homepage Dashboard
2. Write Omada (or anything else)

### homepage version

dev

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Proxmox:
    - Proxmox:
        href: https://192.168.0.170:8006
        description: 192.168.0.170
        siteMonitor: https://192.168.0.170:8006
        icon: proxmox
        widget:
            type: proxmox
            url: https://192.168.0.170:8006
            username: xxx
            password: xxx
            node: proxmox
    - Omada:
        href: https://192.168.0.171:8043/
        description: 192.168.0.171
        siteMonitor: https://192.168.0.171:8043/
        icon: omada
        widget:
            type: omada
            url: https://192.168.0.171:8043
            username: xxx
            password: xxx
            site: xxx
    - Nginx Proxy Manager:
        href: http://192.168.0.172:81
        description: 192.168.0.172
        icon: nginx-proxy-manager
        siteMonitor: http://192.168.0.172:81
        widget:
            type: npm
            url: http://192.168.0.172:81
            username: xxx
            password: xxx
    - Home Assistant:
        href: http://192.168.0.174:8123
        description: 192.168.0.174
        siteMonitor: http://192.168.0.174:8123
        icon: home-assistant
        widget:
            type: homeassistant
            url: http://192.168.0.174:8123
            key: xxx
    - Guacamole:
        description: 192.168.0.176
        href: http://192.168.0.176:8080
        siteMonitor: http://192.168.0.176:8080
        icon: guacamole-light
    - VS Code Server:
        description: 192.168.0.177
        href: http://192.168.0.177:8680/login
        siteMonitor: http://192.168.0.177:8680/login
        icon: code
    - Adguard Home:
        description: 192.168.0.179
        href: http://192.168.0.179
        siteMonitor: http://192.168.0.179/
        icon: adguard-home
        widget:
            type: adguard
            url: http://192.168.0.179
            username: xxx
            password: xxx
- Proxmox Docker:
    - Docker Registry:
        description: 192.168.0.181
        icon: docker
        ping: 192.168.0.181
        widget:
            type: portainer
            url: http://192.168.0.181:9000
            env: 2
            key: xxx
    - Portainer Registry:
        icon: portainer
        href: http://192.168.0.181:9000
        description: 192.168.0.181
        server: docker1
        container: portainer
    - Watchtower:
        description: 192.168.0.182
        ping: 192.168.0.183
        icon: docker
        widget:
            type: portainer
            url: https://192.168.0.182:9443
            env: 2
            key: xxx
    - Portainer Watchtower:
        icon: portainer
        href: https://192.168.0.182:9443
        description: 192.168.0.182
        server: docker2
        container: portainer
    - Watchtower 181:
        icon: watchtower
        server: docker2
        container: watchtower1
    - Watchtower 183:
        icon: watchtower
        server: docker2
        container: watchtower2
    - Toniebox:
        description: 192.168.0.183
        ping: 192.168.0.183
        icon: docker
        widget:
            type: portainer
            url: https://192.168.0.183:9443
            env: 2
            key: xxx
    - Portainer Toniebox:
        icon: portainer
        href: https://192.168.0.183:9443
        description: 192.168.0.183
        server: docker3
        container: portainer
    - MeTube:
        icon: metube
        href: http://192.168.0.183:8081
        server: docker3
        container: nervous_shtern
    - Audacity:
        icon: audacity
        href: http://192.168.0.183:3000
        server: docker3
        container: audacity
- Raspberry:
    - Docker:
        description: 192.168.0.110
        ping: 192.168.0.110
        icon: docker
        widget:
            type: portainer
            url: http://192.168.0.110:9000
            env: 2
            key: xxx
    - Portainer:
        href: http://192.168.0.110:9000
        icon: portainer
        server: docker
        container: portainer
        description: 192.168.0.110
    - Pilight:
        icon: https://www.pilight.org/theme/supremacy/images/pilight.png
        href: http://192.168.0.110:5001
        server: docker
        container: pilight
    - Adafruit Tim:
        icon: python.png
        server: docker # The docker server that was configured
        container: adafruit_tim # The name of the container you'd like to connect
    - Adafruit Julia:
        icon: python.png
        server: docker # The docker server that was configured
        container: adafruit_julia # The name of the container you'd like to connect
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
