### ISSUE TITLE
[Bug] service.yaml doesn’t read environment variables

### ISSUE THREAD

**Issue by astronaute77** [gethomepage/homepage#2587]
### Description

I configured the environment variable, and edited the services.yaml as follows:
```
          widget:
          type: npm
          url: http://192.168.1.250:81
          username: $NGINX_USER
          password: $NGINX_PASS
```

The env variables are totally ignored by the services.yaml file

env variables are visible when inspecting the container

The problem with this is that the password cannot be defined outside of the file, and because of that, the services file cannot be versioned in Git.

### Steps to reproduce

1. inject an environment variable in the container
2. try to use it inside service.yaml

### homepage version

v0.8.4

### Installation method

Docker

### Troubleshooting

API Error: No relevant user found

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Where in the documentation does it say that works?

I suppose youre looking for https://gethomepage.dev/latest/installation/docker/#using-environment-secrets

**Comment by astronaute77** [comment]
The expected behavior is to be able to inject sensitive data from the host.
Am I being unreasonable here?

If it is not implemented, can you consider it as an enhancement?
Right now I have no idea how to maintain my configuration because of this, it is very bothersome to not be able to version the config files as you can imagine.

**Comment by astronaute77** [comment]
OK just tested, it works using the above, thank you @shamoon 

```
        widget:
          type: npm
          url: http://192.168.1.250:81
          username: "{{HOMEPAGE_VAR_NGINX_USER}}"
          password: "{{HOMEPAGE_VAR_NGINX_PASS}}"
```
