### ISSUE TITLE
Prowlarr query count doesn't match application dashboard

### ISSUE THREAD

**Issue by ctmay4** [gethomepage/homepage#2598]
### Description

In Prowlarr, the number of queries listed is 12.7K:

![image](https://github.com/gethomepage/homepage/assets/444345/868033d1-7b11-4cac-9740-9ec2dfd97712)

However when displayed using the Prowlarr widget is is much smaller.

![image](https://github.com/gethomepage/homepage/assets/444345/dff2e38f-94e2-4d9b-996c-4849d3b82347)

I think the reason is that there are different query values returned from the API. Here is an example of one of the indexers returned:

```json
    {
      "indexerId": 1,
      "indexerName": "DrunkenSlug",
      "averageResponseTime": 942,
      "numberOfQueries": 24,
      "numberOfGrabs": 18,
      "numberOfRssQueries": 3328,
      "numberOfAuthQueries": 0,
      "numberOfFailedQueries": 0,
      "numberOfFailedGrabs": 0,
      "numberOfFailedRssQueries": 0,
      "numberOfFailedAuthQueries": 0
    }
```

So the widget is totaling the `numberOfQueries` but the Prowlarr seems to use `numberOfRssQueries` in its dashboard. I think the number of RSS queries are more interesting. Maybe a new field could be added so either field could be chosen?

### Steps to reproduce

1. Create a Prowlarr service width and connect it
2. Compare the number of queries in Homepage and the total queries in the Prowlarr dashboard

### homepage version

v0.8.4 (32f28d3, Dec 27, 2023)

### Installation method

Docker

### Configuration

```yaml
- Prowlarr:
        icon: prowlarr.png
        href: http://192.168.5.31:9696/
        description: Indexer Aggregator
        server: my-docker
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: SNIPPED
```

### Troubleshooting

This is not an error, so there is nothing to troubleshoot. I explained why the stats don't match above.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
