### ISSUE TITLE
Calendar items are not in proper order

### ISSUE THREAD

**Issue by LionCityGaming** [gethomepage/homepage#2601]
### Description

![image](https://github.com/gethomepage/homepage/assets/72677307/f7fa7e07-91ef-4c8a-9e88-3e5102a9aa6b)

As seen above, the three events are not arranged by their start times in Calendar widget

### Steps to reproduce

1. Add Calendar widget to Homepage
2. Add ical integration
3. Wrong times shown

### homepage version

v0.8.4 (32f28d3, Dec 27, 2023)

### Installation method

Docker

### Configuration

```
- Calendar:
    - " ":
        widget:
          type: calendar
          showTime: true
          maxEvents: 10
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/871e3e037b64fbdc7d374bac61978ab9b71d569da147a0b0abd4337259314288%40group.calendar.google.com/public/basic.ics
              name: EPL Fixtures
              color: purple              
```

Calendars tested: 
Official Premier League: https://calendar.google.com/calendar/ical/871e3e037b64fbdc7d374bac61978ab9b71d569da147a0b0abd4337259314288%40group.calendar.google.com/public/basic.ics

Fixtur.es:
https://calendar.google.com/calendar/ical/o85cmmcguboh8jat5gljc502f4%40group.calendar.google.com/public/basic.ics

### Container Logs

Nothing of note.

### Browser Logs

Nothing of note.

### Troubleshooting

The widget itself works with the ical, just that the times are in the wrong order.

### Other

Events show in the correct order in Google Calendar

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
