### ISSUE TITLE
service.yaml fail to retrive the .env value

### ISSUE THREAD

**Issue by ranrinc** [gethomepage/homepage#2636]
### Description

First time user for the homepage and would like to implement secret for all my API tokens. However portainer failed get it.

![CleanShot 2024-01-16 at 16 19 26](https://github.com/gethomepage/homepage/assets/15801696/67da1f53-110b-4cb3-9614-baa8dd0569ec)

I did all correctly, so it should work.

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.4
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3010:3000
    env_file: .env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - ./images:/app/public/images
      - ./icons:/app/public/icons
```

dot env located on root folder of homepage next to docker-compose.yml file

Without using .env structure the API working perfectly.

### Steps to reproduce

1. edit services.yaml and add the .env structure
2. add the structure to .env files
3.  reboot docker container
4. see the homepage

### homepage version

v0.8.4

### Installation method

Docker

### Configuration

```yaml
services.yaml config

    - Portainer 1:
        icon: portainer
        href: https://192.168.80.16
        description: Main Portainer Dashboard
        widget:
          type: portainer
          url: https://192.168.80.16
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
    - Portainer 2:
        icon: portainer
        href: https://192.168.80.17
        description: Backup Portainer Dashboard
        widget:
          type: portainer
          url: https://192.168.80.17
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY1}}"
```

.env config
```
HOMEPAGE_VAR_PORTAINER_API_KEY=ptr_K
HOMEPAGE_VAR_PORTAINER_API_KEY1=ptr_2
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

without using .env and paste the token directly into services.yaml work without any problem


### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
