### ISSUE TITLE
[Bug] K8s widget with absurd memory value

### ISSUE THREAD

**Issue by max06** [gethomepage/homepage#2649]
### Description

Simple issue: 

![image](https://github.com/gethomepage/homepage/assets/7556827/014d6793-c2dc-4bde-b66e-4b6c7014f2d4)

I have no idea where that value is coming from, but it's probably right.

K9s for example shows a memory usage of 130%. There's so much overcommitment on that machine I'm really wondering how it's still working 🙈 

I'd probably change the bar color for that case and prevent the overflow.

Installed via your documented manifests, since the helmchart is broken.

### Steps to reproduce

... have a single node k3s setup on an illegally undersized virtual machine. 

### homepage version

v0.8.4 (32f28d3, Dec 27, 2023)

### Installation method

Other (please describe above)

### Configuration

```yaml
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Dashboard
    headerStyle: boxedWidgets
    target: _self
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "k3s"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""


Almost default documented config, except for the hidden k8s nodes.
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
