### ISSUE TITLE
[Bug] Performance Problem in Brave Browser caused by blur and brightness

### ISSUE THREAD

**Issue by MilippFeier** [gethomepage/homepage#2666]
### Description

Hello, 

I encounter performance problems in the UI with the brave browser (and perhaps other Chromium-based ones, as well)
With the settings provided in "Steps to reproduce", the hover effect over links/widgets is noticably slow and the whole browser appears to be slowed down.
The performance problems are not present with the current Firefox browser.

### Steps to reproduce

- use current Brave Browser (v1.61.116)
- in settings.xml, define the following background:
```
background:
  image: https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=4022&auto=format&fit=crop&ix>
  blur: md # >> BUGGY in Brave
  saturate: 25
  brightness: 50 #>> BUGGY in Brave
  opacity: 50
```
- other yamls may be default
- Startup via docker
- Fly around with the mouse in the UI and see how slow everything is
- Comment out blur and brightness in settings.xml -> UI is not slowed down anymore in Brave

### homepage version

v0.8.4 (32f28d3, Dec 27, 2023)

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
