### ISSUE TITLE
[Bug] Homepage attempts to chown -R a read-only bind mount then exits

### ISSUE THREAD

**Issue by EloraDarling** [gethomepage/homepage#2676]
### Description

 I have a SSHFS fuse mounted folder with the same UID that I have set in the docker compose file, with other_user enabled, so that root can view the directory.

I have my config directory writeable by the UID that $PUID is set to. I have set the LOG_LEVEL environment variable to DEBUG, and recreated the container, but nothing is in the logs.

Upon attempting to start the docker compose without mentioning the SSH bind mount, the container is healthy, and the service works.

When attempting to start the docker compose with the bind mount for the sshfs directory and the :ro directive, the container became unhealthy for 1.5 HOURS as homepage attempts to chown every single file in the ssh mount. This is a very slow process as it fails on every file since it's a read-only file system.

After it was done, the container **exited** with no errors or debug info in the logs.

Why is homepage trying to do this on startup?

### Steps to reproduce

1. Mount the sshfs mount: `sshfs -o idmap=user -o allow_other user@server.com: /mnt/what`
2. Add the volume to the docker compose: 
```
volumes:
      - /mnt/what:/app/data/what:ro
```
3. Start docker with the compose file. (I used it in a Portainer stack)
4. Watch for the container to become unhealthy as it starts attempting to chown the entirety of the mounted folder file by file.
5. After it's done with the entire directory, the container exits.

### homepage version

0.8.4

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    env_file:
      - stack.env
    volumes:
      - /opt/homepage/config:/app/config # Make sure your local config directory exists
      - /opt/homepage/images:/app/public/images # Make sure your local images directory exists
      - /mnt/what:/app/data/what:ro # Mount the what mount read-only (commenting this makes the container work)
      #- /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID
      PGID: $PGID
```

### .env

```
PUID=1000
PGID=1000
```

### Container Logs

[...]
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/hacks/writing-mode.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/hacks: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/hacks: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/at-rule.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/autoprefixer.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/brackets.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/browsers.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/declaration.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/info.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/old-selector.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/old-value.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/prefixer.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/prefixes.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/processor.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/resolution.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/selector.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/supports.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/transition.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/utils.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/value.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/vendor.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib/autoprefixer.d.ts: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/lib: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/data/prefixes.js: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/data: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/data: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/package.json: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer/README.md: Read-only file system
chown: /app/data/what/Downloads/h5ai/node_modules/autoprefixer: Read-only file system
[...]
chown: /app/data/what/owncloud/public.php: Read-only file system
chown: /app/data/what/owncloud/remote.php: Read-only file system
chown: /app/data/what/owncloud/robots.txt: Read-only file system
chown: /app/data/what/owncloud/status.php: Read-only file system
chown: /app/data/what/owncloud/version.php: Read-only file system
chown: /app/data/what/owncloud: Read-only file system
chown: /app/data/what/owncloud: Read-only file system
chown: /app/data/what: Read-only file system
chown: /app/data/what: Read-only file system
[EOF]

### Troubleshooting

n/a

### Other

Portainer version 2.18.4.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
