### ISSUE TITLE
[Bug] Uptime Kuma has access to dashboard when following link but gives API error

### ISSUE THREAD

**Issue by AhzurdanGit** [gethomepage/homepage#2686]
### Description

Config
![image](https://github.com/gethomepage/homepage/assets/68050893/01569720-45c5-4491-a25f-567c480a5384)

Homepage shows:
![image](https://github.com/gethomepage/homepage/assets/68050893/425146d4-9abb-4a6a-8c39-4611bd4efce6)

when following the link in browser - so I assume it can connect and config is correct.
![image](https://github.com/gethomepage/homepage/assets/68050893/7f553a90-9a3c-4d44-926f-30543a405409)

### Steps to reproduce

Adjust Widget, type in ip:port and slug - immediately shows error

### homepage version

v0.8.4 (32f28d3, 27. Dez. 2023)

### Installation method

Docker

### Configuration

```yaml
- Uptime Kuma:
        icon: uptime-kuma
        href: "http://uptimekuma.domain.local:3001/dashboard"
        description: internal
        widget:
          type: uptimekuma
          url: "uptimekuma.domain.local:3001"
          slug: "homestatus"

.. same when using just IP instead of DNS name
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
