### ISSUE TITLE
[Bug] iCal unsupported RRULE param X-EVOLUTION-ENDDATE for recurring events

### ISSUE THREAD

**Issue by mgrove36** [gethomepage/homepage#2689]
### Description

Calendar widget with iCal integration causes error when loading: `Error: unsupported RRULE parm: X-EVOLUTION-ENDDATE=20230624T070000Z`
Seems to be similar to [this issue](https://github.com/home-assistant/core/issues/81409) with Home Assistant, which was related to the library used to parse the dates (dateutil), and [this PR in another project](https://github.com/MagicMirrorOrg/MagicMirror/pull/1458) that solved the issue by adding a try-except around the parsing of the recurring rule.

### Steps to reproduce

1. Add a calendar widget with the iCal integration
2. Ensure the calendar has a recurring event set with `X-EVOLUTION-ENDDATE`
3. Load homepage

### homepage version

v0.8.4 (32f28d3)

### Installation method

Docker

### Configuration

```yaml
- Calendar:
        widget:
          type: calendar
          integrations:
            - type: ical
              url: REDACTED
              name: Personal
```

### Troubleshooting

N/A

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
