### ISSUE TITLE
[Bug] Calendar does not update

### ISSUE THREAD

**Issue by jaytrickett1** [gethomepage/homepage#2691]
### Description

The event calendar, in agenda mode, does not update without browser refresh. The view is stuck on the date and events that existed at the time the dashboard loaded.

### Steps to reproduce

1. Got to Homepage instance.
2. Look at your calendar.
3. Look at your calendar again the next day.

### homepage version

v.0.8.4

### Installation method

Docker

### Configuration

```yaml
- Calendar:
        weight: -10
        widget:
          type: calendar
          #view: monthly
          view: agenda
          maxEvents: 10 # default is 10
          previousDays: 2
          firstDayInWeek: sunday # optional - defaults to monday
          showTime: true
          integrations: # optional
          - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
            service_group: Media Management Tools # group name where widget exists
            service_name: Radarr # service name for that widget
            color: red # optional - defaults to pre-defined color for the service (teal for sonarr)
            params: # optional - additional params for the service
              unmonitored: true # optional - defaults to false, used with *arr stack
          - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
            service_group: Media Management Tools # group name where widget exists
            service_name: Sonarr # service name for that widget
            color: yellow # optional - defaults to pre-defined color for the service (teal for sonarr)
            params: # optional - additional params for the service
              unmonitored: true # optional - defaults to false, used with *arr stack
```

### Troubleshooting

n/a. Not an error. It's a disfunction. 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
