### ISSUE TITLE
[Bug] PeaNUT widget returns NaN for Battery Charge and Load

### ISSUE THREAD

**Issue by cmattogno** [gethomepage/homepage#2697]
### Description

The PeaNUT webpage indicates proper values, but the PeaNUT widget displays NaN for fields "battery_charge" and "ups_load" and nothing for "status"

![image](https://github.com/gethomepage/homepage/assets/42548539/36f4d3ef-5883-4b6d-8784-d1503ded8aa7)

![image](https://github.com/gethomepage/homepage/assets/42548539/bba4b910-efa3-412a-a583-c125b1c502b6)

### Steps to reproduce

Add widget for PeaNUT with local config
![image](https://github.com/gethomepage/homepage/assets/42548539/dca80f75-cd2e-4536-87e8-95aa97c5ba28)

load Homepage

### homepage version

0.8.4

### Installation method

Docker

### Configuration

```yaml
service.yaml
...
   - NUT - UPS Monitor:
         icon: ups.svg
         widget:
            type: peanut
            fields: ["battery_charge", "ups_load", "ups_status"]
            url: http://PeaNUT:8080
            key: tripplite
```

### Troubleshooting

PeaNUT returns values with a dot delimiter not an underscore. I attempted to edit the "fields" to reflect to no change. 

I have tried to write a Custom yaml, but have not been very successful. 

### Other

https://github.com/gethomepage/homepage/discussions/2525 

indicates others have this issue as well.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
