### ISSUE TITLE
[Bug] Concise description of the issue

### ISSUE THREAD

**Issue by AbdullahDahmash** [gethomepage/homepage#2704]
### Description

Hi

tdar widget does not work with api key.

You can enable tdar auth as described here https://github.com/HaveAGitGat/Tdarr/issues/297#issuecomment-1866494484

### Steps to reproduce

1- Use tdar image `docker.io/haveagitgat/tdarr_acc:dev_2.18.01_2023_12_21T15_42_37z`
2- Enter local user credentials. Go to tools > API key > generate a new one
3- Add key attribute to tdar widget
4- It shows API error on the home page

### homepage version

 v0.8.4

### Installation method

Docker

### Configuration

```yaml
- Tdarr:
      title: tdarr
      href: http://tdarr.host.or.ip
      description: Transcoding System
      server: my-docker
      container: tdarr
      widget:
        type: tdarr
        url: http://tdarr.host.or.ip
        key: apikeyapikeyapikeyapikeyapikey
```

### Container Logs

```
[2024-01-20T06:04:13.129Z] error: <tdarrProxyHandler> Error getting data from Tdarr: 403.  Data: {"status":403,"message":"No auth token or API key provided"}
[2024-01-20T06:04:14.289Z] error: <tdarrProxyHandler> Error getting data from Tdarr: 403.  Data: {"status":403,"message":"No auth token or API key provided"}
```

### Troubleshooting

```bash
docker exec homepage ping tdarr

PING tdarr (172.19.0.12): 56 data bytes
64 bytes from 172.19.0.12: seq=0 ttl=64 time=0.173 ms
64 bytes from 172.19.0.12: seq=1 ttl=64 time=0.123 ms
64 bytes from 172.19.0.12: seq=2 ttl=64 time=0.151 ms
64 bytes from 172.19.0.12: seq=3 ttl=64 time=0.144 ms
64 bytes from 172.19.0.12: seq=4 ttl=64 time=0.160 ms
```
```bash
docker exec homepage curl -L -k https://tdarr.host.or.ip/api/v2/cruddb

{"status":403,"message":"No auth token or API key provided"}
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
