### ISSUE TITLE
values set in .env file are not replaced in homepage

### ISSUE THREAD

**Issue by PhoenixNoble** [gethomepage/homepage#2731]
### Description

I have set a bunch of HOMEPAGE_VAR_XXXXX and they do not seem to be replaced in 0.8.6 causing links to fail and status information to be missing

### Steps to reproduce

update to 0.8.6

### homepage version

0.8.6

### Installation method

Docker

### Configuration

```yaml
HOMEPAGE_VAR_PIHOLE_URL=http://192.168.1.2
HOMEPAGE_VAR_PIHOLE_ADMIN_URL=http://192.168.1.2/admin
HOMEPAGE_VAR_PIHOLE_API_KEY=00000000000000000000000000000000000000000000000000000000000000

- DNS:
    - PiHole:
        icon: pi-hole.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: "{{HOMEPAGE_VAR_PIHOLE_ADMIN_URL}}"
        description: PiHole
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}" # <--- updated with API key from PiHole
```

### Troubleshooting

n/a

### Other

never reported an issue before, if i have missed something im sorry

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
