### ISSUE TITLE
[Bug] Customapi makes to much calls

### ISSUE THREAD

**Issue by TimoTielens** [gethomepage/homepage#2748]
### Description

I have create a custom api widget that tries to fetch 3 fields. This all works nice, however I think it's make to much calls. I expect the widget to fetch the data once and then fetch the correct data from it, however it seems that it fetches the data for every field.

### Steps to reproduce

1. Create a custom widget with more then one field
2. Log the amount of request. 
3. Notice every time the refreshInterval is hit, it will do the same amount of request as fields that are configured

### homepage version

v0.8.6 (cd29cbb, Jan 21, 2024)

### Installation method

Docker

### Configuration

```yaml
- Network:
    - item1:
        icon: unifi.svg
        widget:
            type: customapi
            url: http://10.0.0.1:1880/GetNetworkStats
            refreshInterval: 100000 # optional - in milliseconds, defaults to 10s
            method: GET # optional, e.g. POST
            mappings:
                - field: wan
                  label: ISP
                - field: www
                  label: Internet
                - field: clients
                  label: Clients
                - field: alarms
                  label: Alarms
```

### Troubleshooting

Looked quickly in the code but couldn't find a solution directly. 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
