### ISSUE TITLE
[Bug] siteMonitor option for Proxmox Backup Server widget causes error to be logged on PBS

### ISSUE THREAD

**Issue by Taomyn** [gethomepage/homepage#2751]
### Description

When I add the "siteMonitor" to the Proxmox Backup Server widget (proxmoxbackupserver), the PBS server logs the error:

`Jan 25 08:21:11 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:54638] invalid http method for path`

I have similar widgets for Proxmox hosts with the siteMonitor set, and none of them report the same message

The widget does function so it's not blocking the widget itself, just causing an error to be logged when it shouldn't

![image](https://github.com/gethomepage/homepage/assets/4365929/62b072cc-65ef-4cd9-b078-4f75872482b5)

### Steps to reproduce

1. Create service widget for Proxmox Backup Server
2. Include valid setting for siteMonitor parameter
3. Refresh Homepage
4. Check the syslog of PBS

### homepage version

v0.8.6

### Installation method

Docker

### Configuration

```yaml
- Backups:
    - Proxmox Backup Server:
        href: https://lenny.<redacted>:8007
        icon: proxmox.svg
        description: LENNY
        ping: lenny.<redacted>
        siteMonitor: https://lenny.<redacted>:8007/
        statusStyle: "basic"
        widget:
            type: proxmoxbackupserver
            url: https://lenny.<redacted>:8007
            username: <redacted>
            password: <redacted>
```

### Troubleshooting

`Jan 25 08:18:34 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:43992] invalid http method for path
Jan 25 08:19:19 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:42362] invalid http method for path
Jan 25 08:19:19 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:42396] invalid http method for path
Jan 25 08:19:49 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:59096] invalid http method for path
Jan 25 08:19:49 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:59128] invalid http method for path
Jan 25 08:21:11 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:54638] invalid http method for path
Jan 25 08:27:17 lenny proxmox-backup-[1059]: lenny proxmox-backup-proxy[1059]: HEAD /: 400 Bad Request: [client [::ffff:192.168.1.70]:40712] invalid http method for path`

### Other

`proxmox-backup: 3.0.1 (running kernel: 6.5.11-7-pve)
proxmox-backup-server: 3.1.2-1 (running version: 3.1.2)
proxmox-kernel-helper: 8.1.0
pve-kernel-6.2: 8.0.5
proxmox-kernel-6.5: 6.5.11-7
proxmox-kernel-6.5.11-7-pve-signed: 6.5.11-7
proxmox-kernel-6.5.11-6-pve-signed: 6.5.11-6
proxmox-kernel-6.2.16-20-pve: 6.2.16-20
proxmox-kernel-6.2: 6.2.16-20
pve-kernel-6.2.16-3-pve: 6.2.16-3
ifupdown2: 3.2.0-1+pmx8
libjs-extjs: 7.0.0-4
proxmox-backup-docs: 3.1.2-1
proxmox-backup-client: 3.1.2-1
proxmox-mail-forward: 0.2.2
proxmox-mini-journalreader: 1.4.0
proxmox-offline-mirror-helper: not correctly installed
proxmox-widget-toolkit: 4.1.3
pve-xtermjs: 5.3.0-3
smartmontools: 7.3-pve1
zfsutils-linux: 2.2.2-pve1`

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
