### ISSUE TITLE
[Bug] ical Calendar widgets multiplies events

### ISSUE THREAD

**Issue by CestQuoiUnPseudo** [gethomepage/homepage#2753]
### Description

I'm a complete noob trying to set up my homepage. I'm mostly wondering is it's a bug or just some bad config somewhere that I'm not expecting. I may have misread the docs but I've made an effort to go through it, as far as I understood. Thanks for looking at this.
When tabbing out and in again into the Homepage, events get duplicated to the calendar widget
![image](https://github.com/gethomepage/homepage/assets/96011112/ebc9f545-5cfd-47f0-8811-c36af78df659)
In this image there's only supposed to be two "Jarðfræði Íslands" event, but after a few minutes it's already too much.

```
config/services.yaml

- Calendar:
  - Calendar:
    widget:
      type: calendar
      integrations:
        - type: ical
          url: [the url]
          name: School
          color: lime

```
### Steps to reproduce

1. Have that config
2. Go to Homepage
3. Switch to another tab and wait a few seconds
4. Switch back to the Homepage tab

### homepage version

v0.8.6 (cd29cbb, Jan 21, 2024)

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
