### ISSUE TITLE
[Bug] Unifi widget does not set widget.fields if none are configured

### ISSUE THREAD

**Issue by JeffRandall** [gethomepage/homepage#2771]
### Description

The unifi widget returns different data blocks that it calculates without respecting or setting the widget.fields described in the documentation.  The data blocks should always be returned as is consistent with other widgets.  Blocks displayed should be filtered according to the fields configured or a default set of fields that the widget sets.  Preventing configured fields from being displayed because the widget does not provide data is inconsistent with the behavior of other widgets and unexpected from an end user point of view.

Additionally, the fields described in the documentation are incomplete.  Additional fields `lan`, `lan_devices`, `wlan`, and `wlan_devices` can be configured and should be added to the documentation.  

With my setup, a self-hosted controller and 2 access points, using the configuration attached, I see one field instead of four:
![image](https://github.com/gethomepage/homepage/assets/1891490/b3c04fbd-ec8b-4660-b5f5-0d543c2b1d6f)

With no fields configured, I see:
![image](https://github.com/gethomepage/homepage/assets/1891490/633ddc03-59ce-4989-acaa-db8fe257ea5d)
(the additional fields are configurable with "wlan_devices" and "wlan" respectively)

I have a preliminary PR prepared that I will submit to address this bug.

### Steps to reproduce

1. configure the documented widget.fields eg `fields: ["uptime", "wan", "lan_users", "wlan_users"]`
2. depending on the devices present in your unifi configuration, note that you do not see fields configured if the devices are not available (eg, the fields for wan will not appear without a gateway, lan are not available without a switch, wlan without an access point).

### homepage version

v0.8.6

### Installation method

Source

### Configuration

```yaml
- UniFi Controller:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_CONTROLLER_URL}}"
        description: Unifi Wi-fi Controller
        siteMonitor: "{{HOMEPAGE_VAR_UNIFI_CONTROLLER_URL}}"
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_CONTROLLER_URL}}"
            username: "{{HOMEPAGE_VAR_UNIFI_CONTROLLER_USERNAME}}"
            password: "{{HOMEPAGE_VAR_UNIFI_CONTROLLER_PASSWORD}}"
            site: "{{HOMEPAGE_VAR_UNIFI_CONTROLLER_SITE}}"
            fields: ["uptime", "wan", "lan_users", "wlan_users"]
```

### Troubleshooting

n/a

### Other

This issue was discovered while testing the PR prepared for https://github.com/gethomepage/homepage/discussions/2764 and fixes that interaction.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).
