### ISSUE TITLE
mjpeg widget places background over icon

### ISSUE THREAD

**Issue by Goz3rr** [gethomepage/homepage#2841]
When a service has both an icon and a mjpeg widget defined, the blurred background of the mjpeg covers up the icon.

```yaml
  - Test:
      icon: dahua
      widget:
        type: mjpeg
        stream: https://www.alambassociates.com/wp-content/uploads/2016/10/maxresdefault.jpg
```

Results in
![image](https://github.com/gethomepage/homepage/assets/761433/f733dbe9-2401-4a7e-b8da-d86885b50a73)

Expected result
![image](https://github.com/gethomepage/homepage/assets/761433/579e123f-f51b-42e1-b20b-91c2e1563788)
