### ISSUE TITLE
service ping doesn't seem to ping ip6 addresses?

### ISSUE THREAD

**Issue by spacekitteh** [gethomepage/homepage#2895]
### Discussed in https://github.com/gethomepage/homepage/discussions/2894

<div type='discussions-op-text'>

<sup>Originally posted by **spacekitteh** February 13, 2024</sup>
### Description

All of my internal services are IP6 only. The ping component always returns a 400, and there's nothing in the logs about it. The hosts are definitely up (one of them is the host running dashboard, for example).

(Installation method: NixOS)

### homepage version

v0.8.7

### Installation method

Other (please describe above)

### Configuration

```yaml
- Telemetry:
   - Grafana:
       icon: grafana.png
       href: https://internal.spacekitteh.moe/grafana/
       siteMonitor: https://internal.spacekitteh.moe/grafana/
       description: Grafana telemetry
       ping: telemetry.internal.spacekitteh.moe
```

### Container Logs

No relevant logs

### Browser Logs

I noticed in the logs that the `serverIPAddress` was listed as such:
```
"serverIPAddress": "fd0d:acaa:3a8d:bff0::1",
```
I suspect that you need to wrap the IP address with square brackets before you pass it to whatever ping tool you are using.

### Troubleshooting

n/a</div>
