### ISSUE TITLE
[BUG] Google search suggestions fail with accented characters

### ISSUE THREAD

**Issue by shamoon** [gethomepage/homepage#2992]
### Description

If I search for é á ã ... the results will contain a ? in the place of the character and will keep sending search requests 

![image](https://github.com/gethomepage/homepage/assets/13727650/b64f482a-e932-427a-a6b2-a42cdd10bd32)
![image](https://github.com/gethomepage/homepage/assets/13727650/e2c324c4-04e1-4685-87c2-a5ded74d4f34)

https://github.com/gethomepage/homepage/assets/13727650/70376977-5d13-40ef-bd1a-35e60756d9c6

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- search:
    provider: google
    showSearchSuggestions: true
    target: _blank
```

### Troubleshooting

N/A

_Originally posted by @supertx2 in https://github.com/gethomepage/homepage/discussions/2985_
