### ISSUE TITLE
[Bug] Omada widget not showing connected switches

### ISSUE THREAD

**Issue by shamoon** [gethomepage/homepage#3046]
### Description

Omada widget not showing connected switches, even though I have 2 that are showing up in my Omada controller (5.13.30.8)
<img width="901" alt="homepage" src="https://github.com/gethomepage/homepage/assets/36367001/6106b435-1eec-4e2f-acd8-b2873120d4aa">
<img width="932" alt="controller" src="https://github.com/gethomepage/homepage/assets/36367001/53f1754a-45d6-4815-8bff-4a06361c102e">

### homepage version

v0.8.8 (87d1ea4, Feb 13, 2024)

### Installation method

Docker

### Configuration

```yaml
- Omada:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/omada.png
        href: https://omada.url
        widget:
            type: omada
            url: https://omada.url
            username: username
            password: supersecretpassword
            site: Home
            fields: ["connectedSwitches", "connectedAp",  "activeUser", "alerts"]
```

### Troubleshooting

Have been playing around with the different fields, but no solution.
I did notice that in src/widgets/omada/component.jsx, there seems to be no reference to connectedSwitches

_Originally posted by @Christophe999s in https://github.com/gethomepage/homepage/discussions/3045_
