### ISSUE TITLE
Resources - unseen disks

### ISSUE THREAD

**Issue by fatez** [gethomepage/homepage#3674]
### Before submitting, please confirm the following

- [X] I confirm this was discussed, and the maintainers suggest I open an issue (note that AI bots are not maintainers).
- [X] I am aware that if I create this issue without a discussion, it will be removed without a response.

### Discussion Link

https://github.com/gethomepage/homepage/issues/836

### Additional context

```Text
I add disks to monitor free space but they are not seen. I properly mounted them in fstab and in docker-compose and in the widget section but it doesn't work.
```

**Comment by fatez** [comment]
Docker compose : 

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - seccomp:unconfined
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 80:3000
#    env_file: .env # use .env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      - ./icons:/app/public/icons

      - /mnt/lvm/backup:/mnt/lvm-backup:ro
      - /mnt/lvm/docker:/mnt/lvm-docker:ro
      - /mnt/lvm/iso:/mnt/lvm-iso:ro
      - /mnt/lvm/data:/mnt/lvm-data:ro
      - /mnt/usb/2TBSSD:/mnt/2TBSSD:ro
      - /mnt/ssd/data:/mnt/ssd-data:ro
      - /mnt/usb/4TB:/mnt/4TB:ro
      - /mnt/usb/icloud:/mnt/icloud:ro
      - /mnt/usb/5TB:/mnt/5TB:ro

    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped

```

fstab 

```
/dev/mapper/nvme-root /               ext4    errors=remount-ro 0       1
/dev/mapper/nvme-swap none            swap    sw              0       0
/dev/mapper/nvme-iso    /mnt/lvm/iso       ext4    defaults,discard,noatime,nofail 0 1
/dev/mapper/nvme-data   /mnt/lvm/data       ext4    defaults,discard,noatime,nofail 0 1
/dev/mapper/nvme-backup /mnt/lvm/backup       ext4    defaults,discard,noatime,nofail 0 1
/dev/mapper/nvme-docker /mnt/lvm/docker ext4    defaults,discard,noatime,nofail 0 1
# 4TB SSD - Interno - SDA
PARTUUID=f7011db5-3c16-4c78-9c1f-0ec16636a5b5 /mnt/ssd/data ext4 defaults,discard,noatime,nofail 0 1
# 1TB Nvme - UsbC - Icloud
PARTUUID=734f33f2-01 /mnt/usb/icloud ntfs ro,noatime,discard,nofail 0 1
# 2TB ssd - usb
PARTUUID=c1de2f02-25ea-4028-838d-721d25dd82ae   /mnt/usb/2TBSSD ext4 defaults,discard,noatime,nofail 0 1
# 6TB sata - usb
PARTUUID=87027491-ae75-4764-b71e-1acdd6effd97   /mnt/usb/6TBSata ext4 defaults,discard,noatime,nofail 0 1
# 4TB usb
PARTUUID=f2e68a68-b892-42bd-bc69-88dbec8d9b39   /mnt/usb/4TB ext4 defaults,discard,noatime,nofail 0 1
# 5TB usb
PARTUUID=e4725825-b253-4a59-ae87-d6722b7e3e38   /mnt/usb/5TB ext4 defaults,discard,noatime,nofail 0 1
```

widgets.yaml

```
- resources:
    label: lvm-backup
    expanded: true
    disk:
      - /mnt/lvm-backup

- resources:
    label: lvm-docker
    expanded: true
    disk:
      - /mnt/lvm-docker

- resources:
    label: lvm-iso
    expanded: true
    disk:
      - /mnt/lvm-iso

- resources:
    label: lvm-data
    expanded: true
    disk:
      - /mnt/lvm-data

- resources:
    label: 2TBSSD
    expanded: true
    disk:
      - /mnt/2TBSSD

- resources:
    label: ssd-data
    expanded: true
    disk:
      - /mnt/ssd-data

- resources:
    label: 4TB
    expanded: true
    disk:
      - /mnt/4TB

- resources:
    label: icloud
    expanded: true
    disk:
      - /mnt/icloud

- resources:
    label: 5TB
    expanded: true
    disk:
      - /mnt/5TB
```

Result : 

<img width="1339" alt="homepage" src="https://github.com/gethomepage/homepage/assets/6235981/1c78d66e-7344-4ca7-bb0b-3170dffeba4c">
