### ISSUE TITLE
[Bug] Weather API Error

### ISSUE THREAD

**Issue by varunpan** [gethomepage/homepage#447]
### Description

Currently homepage does not show the weather information and instead shows API Error message

<img width="289" alt="image" src="https://user-images.githubusercontent.com/47158147/197797939-f5acb278-d1e3-4547-bc5f-cd3378a49b7b.png">

### Steps to reproduce

open/reload the page

### homepage version

v0.4.18 (4ea2798)

### Installation method

Docker

### Configuration

widgets.yaml config:

```
- weatherapi:
    label: <redacted>
    latitude: <redacted>
    longitude: <redacted>
    units: imperial
    provider: openweathermap
    cache: 5
```

settings.yaml Provider config:
```
provider:
  openweathermap: <redacted>
```

### Other

Docker version 20.10.20, build 9fdeb9c
Docker Compose version v2.12.0
