### ISSUE TITLE
Homepage Docker compose unhealthy, no logs, can't run as user

### ISSUE THREAD

**Issue by k0smonaut** [gethomepage/homepage#4637]
### Description

Been running homepage for well over a year with the same config via docker with a compose file, havent made any changes recently but noticed homepage wasnt up - couldnt reach it behind my proxy or via IP:PORT. Checked portainer and it was flagged unhealthy.

docker logs homepage outputs nothing at all. tried deleting and pulling image fresh, same issue.

other containers on same host reporting no issues and starting fine - any help appreciated

running :latest tag, wiped image, repulled and 

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - '3300:3000'
    volumes:
      - '${BINDMOUNTDIR}/homepage:/app/config'
      - '${DOCKERSOCK}:${DOCKERSOCK}'
```

### Container Logs

BLANK

### Browser Logs

NA

### Troubleshooting

Deleting container and image and pulling fresh, server reboots

_Originally posted by @Renderer6060 in https://github.com/gethomepage/homepage/discussions/4433_

**Comment by k0smonaut** [comment]
I am experiencing the same issue. The issue goes away when I remove PUID and PGID variables from my docker-compose.yml.
The user:group in question owns the entire volume path and has 770 permissions on all subdirectories and files.

I'm passing in a Proxmox mountpoint on /opt/chapps/. To test, I also gave 1000:1000 ownership and rwx for /opt itself. 
Issue persisted. 

My docker-compose.yml:

```
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    cpus: 0.5
    mem_limit: 128m
    ports:
      - 3003:3000
    #env_file: .env
    volumes:
      - /opt/chapps/docker-homepage/config:/app/config
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped
    pull_policy: always
```

Docker compose logs are blank. Docker logs are blank.
For now I'm running Homepage as root.
