### ISSUE TITLE
### Solved Weather widget requires click to load weather

### ISSUE THREAD

**Issue by ProAlexUSC** [gethomepage/homepage#4817]
### Description

With the weather widget being set to automatically get location, I need to always click it to fetch weather data, even if I allowed the permission permanently. After loading my Homepage, I _always_ get this:
![image](https://github.com/gethomepage/homepage/assets/43749899/29228661-409f-441e-8a47-515725bc9ee5)
(the icon is fading in and out) When I click it, it triggers the location permission (I can see in the address bar), fetches the location and displays weather data properly.

### homepage version

v0.8.10 (0af975b, Mar 24, 2024)

### Installation method

Docker

### Configuration

```yaml
- openmeteo:
    units: metric
    cache: 15
    format:
      maximumFractionDigits: 0


Browser: Firefox 121
```

### Troubleshooting

N/A

_Originally posted by @YeapGuy in https://github.com/gethomepage/homepage/discussions/3177_
