### ISSUE TITLE
Homepage delayed start when PUID and GUID set 

### ISSUE THREAD

**Issue by jerobins** [gethomepage/homepage#4964]
When i set PGID and PUID the container will instantly go unhealthy.

I also checked if permissions might be wrong, but user and group docker-user has rwx.

Eventually starts and runs fine, but with a ~5 minute delay at start.

```
docker-user@docker:/mnt/data$ id docker-user
uid=3001(docker-user) gid=3001(docker-user)

docker-user@docker:/mnt/data$ getfacl homepage/
# file: homepage/
# owner: docker-user
# group: docker-user
user::rwx
user:root:rwx
user:docker-user:rwx
group::rwx
group:docker-user:rwx
mask::rwx
other::rwx
default:user::rwx
default:user:root:rwx
default:user:docker-user:rwx
default:group::rwx
default:group:docker-user:rwx
default:mask::rwx
default:other::---
```

### homepage version

0.9.2

### Installation method

Docker

### Configuration

```yaml
docker-compose.yml

services:  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /mnt/data/homepage:/app/config
    networks:
      - proxy
    environment:
      PUID: 3001
      PGID: 3001
      LOG_LEVEL: debug
    restart: unless-stopped
    ports:
      - 3000:3000

networks:
  proxy:
    external: true
```

### Container Logs

There are none when started as user 
```

```

if started as root:
```
Listening on port 3000
```

### Troubleshooting

this is not relevant, as topic is not widgets

_Originally posted by @ChoosenMEME in https://github.com/gethomepage/homepage/discussions/3654_

I've co-opted the discussion above to document the issue. -- @jerobins
