### ISSUE TITLE
Long delay when starting with PUID and GUID set

### ISSUE THREAD

**Issue by jerobins** [gethomepage/homepage#4996]
When i set PGID and PUID the container has ~5 minute delay until it finally starts accepting connections.

The permissions seem fine as the container can read the config and write the log file just fine.

### homepage version

1.0.3

### Installation method

Docker

### Configuration

```yaml
docker-compose.yml

services:  
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 4000:3000
    depends_on:
      - dockerproxy
    volumes:
      - ./config:/app/config
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: "*"
```

### Container Logs

```
homepage  |    ▲ Next.js 15.1.7
homepage  |    - Local:        http://localhost:3000
homepage  |    - Network:      http://0.0.0.0:3000
homepage  |
homepage  |  ✓ Starting...
homepage  |  ✓ Ready in 255ms
```

### Troubleshooting

Shows the chown running for 5 minutes before node starts...

```
homepage
UID    PID       PPID      C    STIME   TTY   TIME       CMD
root   3778586   3778567   0    14:17   ?     00:00:00   /bin/sh /usr/local/bin/docker-entrypoint.sh node server.js
root   3778622   3778586   0    14:17   ?     00:00:00   chown -R 1000:1000 /app

homepage
UID        PID       PPID      C    STIME   TTY   TIME       CMD
root       3778586   3778567   0    14:17   ?     00:00:00   /bin/sh /usr/local/bin/docker-entrypoint.sh node server.js
jerobins   3787133   3778586   1    14:22   ?     00:00:00   node server.js
```

Referencing discussion: 
_Originally posted by @ChoosenMEME in https://github.com/gethomepage/homepage/discussions/3654_
