### ISSUE TITLE
Seeking Assistance - Nested Groups

### ISSUE THREAD

**Issue by BBT-nZ** [gethomepage/homepage#5063]
Hey Folks,

Really could do with some help here :( after seeing all the amazing work you guys have shared.

For the life of me I'm unable to achieve the below config, this is how far I've managed to get.

![image](https://github.com/user-attachments/assets/f9523a8f-deb7-4690-a7f3-d3953efdc847)

**settings.yml**

providers:
  openweathermap: KEYKEYKEY
  weatherapi: weatherapiapikey

```
title: My Homepage

background: 
 image: /images/pexels-photo-1169754.jpeg
 opacity: 27 # 0-100
    #  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    #  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    #  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness

statusStyle: "dot"
useEqualHeights: true
theme: dark
language: en

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: false

layout:
  Media:
   style: row
   columns: 3
   useEqualHeights: false

  Calendar:
     header: false
```

Let me know, if services.yml is required as well and I'm happy to post that too. TIA :)

_Originally posted by @BBT-nZ in https://github.com/gethomepage/homepage/discussions/473#discussioncomment-12591283_
