### ISSUE TITLE
SearXNG Autocomplete

### ISSUE THREAD

**Issue by jjsmackay** [gethomepage/homepage#5172]
Once I saw that Firefox was the only one not having an issue, I figured out this was a configuration mistake on my part. I have been able to fix this and it was not a problem with Homepage. Thank you regardless!

_Originally posted by @truppelito in https://github.com/gethomepage/homepage/discussions/3671#discussioncomment-9888130_

@truppelito, would you mind sharing what that config mistake was? I'm facing the same issue with empty lists from inside a Homepage container.

**Comment by truppelito** [comment]
I do not remember... But currently this is what I have in the `widgets.yaml` file:

```
- search:
    provider: custom
    url: https://searxng.my-server.xyz/search?q=
    focus: false
    target: _self
    suggestionUrl: https://searxng.my-server.xyz/autocompleter?q=
    showSearchSuggestions: true
```
