### ISSUE TITLE
[Bug] Deluge widget not working 

### ISSUE THREAD

**Issue by varunpan** [gethomepage/homepage#563]
### Description

Deluge widget is showing "API Error: Not Authenticated"

I am using the username/pass stored in auth file `/docker/appdata/deluge/auth`

### Steps to reproduce

Updated services.yaml with the following:
```
- Deluge:
        href: http://192.168.1.4:8112
        description: Download Manager
        server: MyDellBox
        container: deluge
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/deluge.png
        widget:
          type: deluge
          url: http://192.168.1.4:8112
          username: localclient
          password: passwordhere
```

I am using the username and password from the `/docker/appdata/deluge/auth` file

### homepage version

v0.5.1 (f16bd91)

### Installation method

Docker
