### ISSUE TITLE
[Bug] Deluge widget give API error when instance's address is https://host.domain.tld/USER/deluge.

### ISSUE THREAD

**Issue by animakarkia** [gethomepage/homepage#950]
### Description

Deluge widget gives api error when deluge instance's address is in the form of https://host.domain.tld/USER/deluge. I have tried to include base url in the services.yml to no avail.

![Screenshot 2023-02-06 at 16 59 02](https://user-images.githubusercontent.com/104270828/217005913-6badb104-3223-43dc-ba19-9d5deb93204b.png)

### Steps to reproduce

The widget links to the deluge instance just fine, but that's just about it.

### homepage version

v0.6.6 (29e0b30, Feb 2, 2023)

### Installation method

Docker

### Configuration

```yaml
- P2P:
    - Deluge:
        icon: deluge.png
        href: https://host.domain.tld/USER/deluge
        widget:
            type: deluge
            url: https://host.domain.tld/USER/deluge/
            password: mypass
```

### Other

Only base url reference I found whilst consulting the documentation dealt with the actual homepage instance being deployed to a subfolder opposed to subdomain. This would lend me to believe that there's an assumption that the homepage user has total access to the services. Seedboxes usually do fall short from this.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
